### ISSUE TITLE
Wrong error message when copying from File storage to Blob storage

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-azcopy#100]
PS C:\Program Files\azcopy_windows_amd64_10.0.2> .\azcopy.exe cp 'https://testac1.file.core.windows.net/master' 'https://testac1.blob.core.windows.net/master' --recursive=true

failed to parse user input due to error: Unable to infer the source 'https://testac1.file.core.windows.net/master' / destination 'https://testac1.blob.core.windows.
net/master' combination. Please use the --FromTo switch

**Comment by zezha-msft** [comment]
@seguler what's the desired error message in this case? "Feature not supported"?

**Comment by zezha-msft** [comment]
Fixed in 10.0.5-preview.
