### ISSUE TITLE
AuthorizationFailure Error When Copying Page Blobs Between Firewall Enabled Storage Accounts

### ISSUE THREAD

**Issue by JohnHps** [Azure/azure-storage-azcopy#1003]
### Which version of the AzCopy was used? 
10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

### What command did you run?
azcopy copy 'https://<stg-acct-1>.blob.core.windows.net/test/<file>.bak?<sas-token>' 'https://<stg-acct-2>.blob.core.windows.net/test?<sas-token>'

### What problem was encountered?
I'm getting the following errors when trying to copy page blobs between storage accounts that have a firewall enabled.  The client that I'm running the azcopy commands from is permitted on both storage account firewall rules.  Also, this problem is specific to page blobs.  When I use the same command to copy block blobs it completes successfully.  Also, if I reconfigure the storage account to allow access from all networks (disabling the firewall), the command works with page blobs again.  It's the combination of trying to copy page blobs, and having the firewall enabled, which is causing the problem.  

INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission
===== RESPONSE ERROR (ServiceCode=CannotVerifyCopySource) =====
Description=Could not verify the copy source within the specified time.

### How can we reproduce the problem in the simplest way?
Run the command above while making sure it references a page blob and have the firewall enabled on both storage accounts.  

### Have you found a mitigation/solution?
In our troubleshooting we've found the the command will work if we disable the firewall on the storage accounts, but this isn't an acceptable long term solution.

### Full Redacted Logs Below
```
2020/05/07 21:58:48 AzcopyVersion  10.4.3
2020/05/07 21:58:48 OS-Environment  windows
2020/05/07 21:58:48 OS-Architecture  amd64
2020/05/07 21:58:48 Log times are in UTC. Local time is 7 May 2020 17:58:48
2020/05/07 21:58:48 Job-Command copy https://<stg-acct1>.blob.core.windows.net/test/<file>.bak?<sas-key1> https://<stg-acct2>.blob.core.windows.net/test?<sas-key> 
2020/05/07 21:58:48 Number of CPUs: 3
2020/05/07 21:58:48 Max file buffer RAM 1.500 GB
2020/05/07 21:58:48 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2020/05/07 21:58:48 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2020/05/07 21:58:48 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2020/05/07 21:58:48 Max enumeration routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2020/05/07 21:58:48 Max open files when downloading: 2147483171 (auto-computed)
2020/05/07 21:58:48 failed to initialize destination container test; the transfer will continue (but be wary it may fail): -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:###
Time:2020-05-07T21:58:48.4100581Z, Details: 
   Code: AuthorizationFailure
   PUT https://<stg-acct2>.blob.core.windows.net/test?restype=container&<sas-key>&timeout=901
   User-Agent: [AzCopy/10.4.3 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [###]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Thu, 07 May 2020 21:58:48 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [###]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [###]
   X-Ms-Version: [2019-02-02]



2020/05/07 21:58:48 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2020/05/07 21:58:48 JobID=###, credential type: Anonymous
2020/05/07 21:58:48 Final job part has been created
2020/05/07 21:58:48 PERF: primary performance constraint is Unknown. States: W:  0, F:  0, S:  0, E:  0, T:  0, GRs:  2
2020/05/07 21:58:48 scheduling JobID=###, Part#=0, Transfer#=0, priority=0
2020/05/07 21:58:48 Final job part has been scheduled
2020/05/07 21:58:48 INFO: [P#0-T#0] has worker 36 which is processing TRANSFER
2020/05/07 21:58:48 INFO: [P#0-T#0] Transfer: Source "https://<stg-acct1>.blob.core.windows.net/test/<file>.bak?<sas-key1>" Destination "https://<stg-acct2>.blob.core.windows.net/test/<file>.bak?<sas-key>". Autodetected https://<stg-acct1>.blob.core.windows.net/test/<file>.bak?<sas-key1> blob type as PageBlob.
2020/05/07 21:58:48 INFO: [P#0-T#0] Starting transfer: Source "https://<stg-acct1>.blob.core.windows.net/test/<file>.bak?<sas-key1>" Destination "https://<stg-acct2>.blob.core.windows.net/test/<file>.bak?<sas-key>". Specified chunk size 4194304
2020/05/07 21:58:48 ==> REQUEST/RESPONSE (Try=1/76.882ms, OpTime=292.8841ms) -- RESPONSE SUCCESSFULLY RECEIVED
   PUT https://<stg-acct2>.blob.core.windows.net/test/<file>.bak?<sas-key>&timeout=901
   X-Ms-Request-Id: []

2020/05/07 21:58:48 ==> REQUEST/RESPONSE (Try=1/20.5125ms, OpTime=64.1055ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://<stg-acct1>.blob.core.windows.net/test/<file>.bak?comp=pagelist&<sas-key1>&timeout=901
   X-Ms-Request-Id: []

2020/05/07 21:58:49 ==> REQUEST/RESPONSE (Try=1/426.1085ms, OpTime=426.1085ms) -- RESPONSE STATUS CODE ERROR
   PUT https://<stg-acct2>.blob.core.windows.net/test/<file>.bak?comp=page&<sas-key>&timeout=901
   Content-Length: [0]
   User-Agent: [AzCopy/10.4.3 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [###]
   X-Ms-Copy-Source: [https://<stg-acct1>.blob.core.windows.net/test/<file>.bak?<sas-key1>]
   X-Ms-Page-Write: [update]
   X-Ms-Range: [bytes=0-4194303]
   X-Ms-Source-Range: [bytes=0-4194303]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [251]
   Content-Type: [application/xml]
   Date: [Thu, 07 May 2020 21:58:48 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [CannotVerifyCopySource]
   X-Ms-Request-Id: [###]
   X-Ms-Version: [2018-11-09]
Response Details: <?xml version="1.0" encoding="utf-8"?> <Error><Code>CannotVerifyCopySource</Code><Message>Could not verify the copy source within the specified time. </Message>

2020/05/07 21:58:49 ERR: [P#0-T#0] COPYFAILED: https://<stg-acct1>.blob.core.windows.net/test/<file>.bak?<sas-key1> : 403 : 403 This request is not authorized to perform this operation.. When Uploading page from URL. X-Ms-Request-Id: 

   Dst: https://<stg-acct2>.blob.core.windows.net/test/<file>.bak?<sas-key>
2020/05/07 21:58:49 JobID= canceled
2020/05/07 21:58:49 ==> REQUEST/RESPONSE (Try=1/74.168ms, OpTime=74.168ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://<stg-acct2>.blob.core.windows.net/test/<file>.bak?<sas-key>&timeout=30
   X-Ms-Request-Id: []

2020/05/07 21:58:49 JobID=, Part#=0, TransfersDone=1 of 1
2020/05/07 21:58:49 all parts of entire Job  successfully completed, cancelled or paused
2020/05/07 21:58:49 all parts of entire Job  successfully cancelled
2020/05/07 21:58:50 PERF: primary performance constraint is Unknown. States: W:  0, F:  0, S:  0, E:  0, T:  0, GRs: 32
2020/05/07 21:58:50 

Diagnostic stats:
IOPS: 14
End-to-end ms per request: 405
Network Errors: 0.00%
Server Busy: 0.00%


Job  summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Cancelled
```

**Comment by JohnRusk** [comment]
I've passed this issue on to the Storage team for their input.

**Comment by JohnRusk** [comment]
Hi @JohnHps 

The Storage team have asked me for the log info.  Are you comfortable with emailing me a version that is a little less redacted? Specifically, one where the x-ms-request id's are present.  (You can still react everything else that you redacted above).  If so, can you please email it to me.  My email address is in my profile.

BTW, it would be really great if you could re-run the test (to get a fresh log) rather than using the old one from a week ago.

**Comment by JohnHps** [comment]
I've sent you a fresh, non-redacted log separately.  Please let me know if you don't get it.  Thanks.

**Comment by JohnRusk** [comment]
@JohnHps Thanks for the log. I've passed it on to the Storage team for them to investigate.

If you need a workaround, while we wait for there reply, you could _possibly_ leverage the fact that this is only happening for Page blobs.  E.g. you could try:

1. Use AzCopy to copy the page blob to a block blob, entirely within the source account.  Use this on the command line: --blob-type BlockBlob
2. Copy that block blob to your destination account.
3. Convert it back to a page blob, by copying it with azcopy entirely within the destination account. Use this on the command line:  --blob-type PageBlob

You might be able to simplify the process too. E.g. try setting --blob-type PageBlob at step 2, and omitting step three OR try having step 1 copy directly to the destination, and omit step 2.  I don't know which, if any, of those simplifications will work.

**Comment by JohnRusk** [comment]
Based on feedback from the Storage team, can you pls double check that the client IP is allowed at both source and dest?

**Comment by JohnHps** [comment]
Confirmed with screenshots below.  Please let me know if you need any add’l info.  Thanks.

[cid:image001.png@01D62CF4.9A6C00A0]


[cid:image002.png@01D62CF4.9A6C00A0]


[cid:image003.png@01D62CF4.9A6C00A0]

**Comment by JohnRusk** [comment]
Thanks John. We'll circle back to the Storage team.

(BTW, the screenshots didn't come through, but I believe you.  And we don't necessarily want screenshots of your firewall setup here on GitHub anyway, since you'd probably want to redact all the useful stuff anyway, given that this is a public site).

**Comment by JohnRusk** [comment]
@JohnHps  It turns out this is a known issue.  It's documented [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints#copy-blob-support) for the CopyBlob API. While AzCopy v10 doesn't use that particular API, the same limitation applies to the APIs used by AzCopy.  

Given that it's listed there as a known issue, the implication is that the known issue will be solved at some stage.  I'd suggest you check for changes to that page from time to time, to see if that section of the documentation gets updated (i.e. if the known issue is removed).  You can see the edit history of the page here: https://github.com/MicrosoftDocs/azure-docs/commits/master/articles/storage/common/storage-private-endpoints.md

I'm going to mark this AzCopy issue as closed now, since the limitation is in the blob Service, not AzCopy itself.
