### ISSUE TITLE
Azcopy sync not transferring large files when run in windows task scheduler

### ISSUE THREAD

**Issue by neilfisher80** [Azure/azure-storage-azcopy#1009]
### Which version of the AzCopy was used? 
10.4.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2016
### What command did you run?
azcopy sync "H:\BACKUP" "https://<BLOB_ID>.blob.core.windows.net/foldername?sv=SASKEY" --recursive --delete-destination=TRUE --log-level=DEBUG

### What problem was encountered?
Command run from a powershell script, nothing else in script except this azcopy command.
Running in task scheduler as my account, administrator permissions
Small files will copy successfully, large files seem to get stuck. Files vary in size from a few KB up to 100GB.
Successful file copies are all under 1GB, but I had no files between 1GB and 50GB to get the exact threshold it fails at.

Log file has the following entry, just repeating over and over:

2020/05/14 09:35:45 ==> REQUEST/RESPONSE (Try=1/62.4827ms, OpTime=260.4802ms) -- RESPONSE SUCCESSFULLY RECEIVED
   PUT https://BLOBID.blob.core.windows.net/FOLDERNAME/Database/FILENAME?blockid=nzkzzda2mdutodrhny1jnzrjltyzotcty2m3ytewzmy5otk1&comp=block&se=2020-07-31t02%3A22%3A34z&sig=-REDACTED-&sp=rwdlacupx&spr=https&srt=sco&ss=bfqt&st=2020-05-12t18%3A22%3A34z&sv=2019-10-10&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.4.0 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [4487febc-ee3e-45b0-639d-8a6e6480f356]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 201 Created
   Content-Length: [0]
   Date: [Thu, 14 May 2020 09:35:44 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [4487febc-ee3e-45b0-639d-8a6e6480f356]
   X-Ms-Content-Crc64: [C9Q2Bdni5zQ=]
   X-Ms-Request-Id: [ff2d1782-201e-004d-5ed3-294fcc000000]
   X-Ms-Request-Server-Encrypted: [true]
   X-Ms-Version: [2019-02-02]

2020/05/14 09:35:45 ==> OUTGOING REQUEST (Try=1)
   PUT https://BLOBID.blob.core.windows.net/FOLDERNAME/Database/FILENAME?blockid=mwezyjg3m2ytywnjzs01otrjltqzzwutm2yxy2jimjvhyzfl&comp=block&se=2020-07-31t02%3A22%3A34z&sig=-REDACTED-&sp=rwdlacupx&spr=https&srt=sco&ss=bfqt&st=2020-05-12t18%3A22%3A34z&sv=2019-10-10&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.4.0 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [1b1b3f8e-387d-4bdf-6c5e-ca68272171d7]
   X-Ms-Version: [2019-02-02]

2020/05/14 09:35:45 ==> REQUEST/RESPONSE (Try=1/68.0168ms, OpTime=206.0159ms) -- RESPONSE SUCCESSFULLY RECEIVED
   PUT https://BLOBID.blob.core.windows.net/FOLDERNAME/Database/FILENAME?blockid=mwezyjg3m2ytywnjzs01otrjltqzzwutm2yxy2jimjvhyzfl&comp=block&se=2020-07-31t02%3A22%3A34z&sig=-REDACTED-&sp=rwdlacupx&spr=https&srt=sco&ss=bfqt&st=2020-05-12t18%3A22%3A34z&sv=2019-10-10&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.4.0 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [1b1b3f8e-387d-4bdf-6c5e-ca68272171d7]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 201 Created
   Content-Length: [0]
   Date: [Thu, 14 May 2020 09:35:45 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [1b1b3f8e-387d-4bdf-6c5e-ca68272171d7]
   X-Ms-Content-Crc64: [7VrpSw2QSXg=]
   X-Ms-Request-Id: [ff2d1a26-201e-004d-42d3-294fcc000000]
   X-Ms-Request-Server-Encrypted: [true]
   X-Ms-Version: [2019-02-02]

2020/05/14 09:35:46 ==> OUTGOING REQUEST (Try=1)
   PUT https://BLOBID.blob.core.windows.net/FOLDERNAME/Database/FILENAME?blockid=zdg4mtkym2mtyme4mi01njq4ltc4ntmtndg1mjgwmgrlmjy0&comp=block&se=2020-07-31t02%3A22%3A34z&sig=-REDACTED-&sp=rwdlacupx&spr=https&srt=sco&ss=bfqt&st=2020-05-12t18%3A22%3A34z&sv=2019-10-10&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.4.0 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [1ea4c089-3f6a-4e16-4e30-e38e287be2bf]
   X-Ms-Version: [2019-02-02]

2020/05/14 09:35:46 ==> REQUEST/RESPONSE (Try=1/76.0027ms, OpTime=176.0043ms) -- RESPONSE SUCCESSFULLY RECEIVED
   PUT https://BLOBID.blob.core.windows.net/FOLDERNAME/Database/FILENAME?blockid=zdg4mtkym2mtyme4mi01njq4ltc4ntmtndg1mjgwmgrlmjy0&comp=block&se=2020-07-31t02%3A22%3A34z&sig=-REDACTED-&sp=rwdlacupx&spr=https&srt=sco&ss=bfqt&st=2020-05-12t18%3A22%3A34z&sv=2019-10-10&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.4.0 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [1ea4c089-3f6a-4e16-4e30-e38e287be2bf]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 201 Created
   Content-Length: [0]
   Date: [Thu, 14 May 2020 09:35:46 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [1ea4c089-3f6a-4e16-4e30-e38e287be2bf]
   X-Ms-Content-Crc64: [AzKPL2rT134=]
   X-Ms-Request-Id: [ff2d1c58-201e-004d-2fd3-294fcc000000]
   X-Ms-Request-Server-Encrypted: [true]
   X-Ms-Version: [2019-02-02]

2020/05/14 09:35:46 PERF: primary performance constraint is Disk. States: R:  0, D:  1, W:  0, F:  0, B:  0, E:  0, T:  1, GRs: 128

### How can we reproduce the problem in the simplest way?
Run azcopy sync from task scheduler with large files?
### Have you found a mitigation/solution?
Running the powershell script manually in a powershell window works fine, so it's not a transfer issue, it's something about running it in task scheduler where it doesn't like the larger sized files.
This is able to process over 500GB in 45 minutes, but the task scheduler is getting stuck on 60GB for over 8 hours.

**Comment by JohnRusk** [comment]
That is really weird.  Could you zip up the log file and email it to me?  My email address is on my profile page.  Log files contain filenames but no credentials.

**Comment by adreed-msft** [comment]
Just a thought: Tasks ran by Windows Task Scheduler have a lower CPU priority by default. Degraded performance might be seen without a tweak, which could potentially cause this: https://aavtech.site/2018/01/windows-task-scheduler-changing-task-priority/

**Comment by adreed-msft** [comment]
@mohsha-msft this may be a good issue to watch to dip your toes into the perf world of AzCopy.

**Comment by neilfisher80** [comment]
> 
> 
> Just a thought: Tasks ran by Windows Task Scheduler have a lower CPU priority by default. Degraded performance might be seen without a tweak, which could potentially cause this: https://aavtech.site/2018/01/windows-task-scheduler-changing-task-priority/

This was exactly the issue in the end, though the difference in performance is staggering.
It was essentially waiting for the end of time, and the block transfer was running at a rate of maybe one per second or so.

Increasing priority from 7 to 4, and the job completed in a normal timeframe.

However, this does have some rather interesting affects on normal operation, where even on a multi-core computer, the system waits for this job to process before completing another process... For example deleting an empty folder took up to 5 minutes, similarly did opening different tabs in task manager, or clicking the start menu etc.

I recommend playing with the exact priority number to find the sweet spot for your system.

**Comment by gapra-msft** [comment]
Hi @neilfisher80 thank you again for reporting this issue. It sounds like you were able to resolve the issue by increasing priority of the AzCopy job, so I will go ahead and close this issue. Feel free to reopen in case I am incorrect.
