### ISSUE TITLE
How can i stop the azcopy and continue what i left

### ISSUE THREAD

**Issue by jethrogalolo** [Azure/azure-storage-azcopy#1010]
### Which version of the AzCopy was used? 
azcopy 10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy cp "L:\" "https://azw23.file.core.windows.net/2store/non/L1? --recursive --overwrite=false --preserve-smb-info --log-level ERROR 

### What problem was encountered?
There will be a patch update for the machine that i am using and a shutdown is needed. What is  the proper way to stop the running azcopy then the command i can use to continue where i left off. 

Thank you.

### Have you found a mitigation/solution?
Not yet

**Comment by adreed-msft** [comment]
`azcopy jobs resume <jobID>` will resume transfers at the file level. Currently, the block level is not supported.

Does this answer your question?

**Comment by adreed-msft** [comment]
(also, Ctrl+C GENERALLY signals a kill operation in most terminal emulators. Which should be enough to tell AzCopy to knock it off.)
