### ISSUE TITLE
Copy with service principal returns 403

### ISSUE THREAD

**Issue by cosmospuglisi** [Azure/azure-storage-azcopy#1011]
### Which version of the AzCopy was used? 
10.4.3 (W
##### Note: The version is visible when running AzCopy without any argument
no
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Linux
### What problem was encountered?
copy action using service principal fails returning a 403 error but other command like "list" are working fine
### How can we reproduce the problem in the simplest way?

**.\azcopy.exe login --service-principal --application-id XXX-YYYY-ZZZZ --tenant-id ZZZZ-WWWW**

INFO: If you set an environment variable by using the command line, that variable will be readable in your command line history. Consider clearing variables that contain credentials from your command line history.  To keep variables from appearing in your history, you can use a script to prompt the user for their credentials, and to set the environment variable.
**INFO: SPN Auth via secret succeeded.**

.\azcopy.exe copy "soruce.json" "https://datalakename.dfs.core.windows.net/containaer/folder/dest.json" --overwrite=prompt --follow-symlinks --recursive
INFO: Scanning...
**INFO: Authenticating to destination using Azure AD**
INFO: Any empty folders will be processed, because source and destination both support folders
[...]
   **RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.**
   Content-Length: [227]
   Content-Type: [application/json;charset=utf-8]
   Date: [Tue, 19 May 2020 02:40:27 GMT]
   Server: [Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [9eb2688e-601f-002d-1d86-2d240d000000]
   X-Ms-Version: [2018-11-09]

0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,

Job 2bddd7e3-365e-1c46-62de-33df0c17d039 summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
**Number of Transfers Failed: 1**
Number of Transfers Skipped: 0
TotalBytesTransferred: 0

### Have you found a mitigation/solution?
use older version azcopy10.3.4

**Comment by adreed-msft** [comment]
Interesting that 10.4 fails, but 10.3.4 succeeds in this regard. Do you happen to have logs for both revision's transfers? Perhaps there's a new operation we're performing that you don't have the permissions to on this service principal.

@mohsha-msft this could be a good starter issue for you to investigate, and get used to the world of REST API authorization on!

**Comment by cosmospuglisi** [comment]
in attachment last log file from new version.
(I have deleted the reference to datalake)
 
[899d2788-de36-e74c-7328-34ee77cfa89f.log](https://github.com/Azure/azure-storage-azcopy/files/4676058/899d2788-de36-e74c-7328-34ee77cfa89f.log)

**Comment by cosmospuglisi** [comment]
Here the last log from 10.4.3

[899d2788-de36-e74c-7328-34ee77cfa89f.log](https://github.com/Azure/azure-storage-azcopy/files/4676073/899d2788-de36-e74c-7328-34ee77cfa89f.log)

**Comment by mohsha-msft** [comment]
Hey @cosmospuglisi 
I tried to reproduce this bug and it was working fine as expected. I am certain service-principal doesn't have enough permissions to create/delete content. So I suggest you please look into [role assignment](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal). Additionally you can see this [link](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest).

If still the problem persists, please reach out and also specify what permissions are given to the service-principal.
