### ISSUE TITLE
[Feature request] Release to Microsoft Store and Windows Package Manager

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-storage-azcopy#1012]
Would be great if AzCopy could be relased through platforms/ solutions that handles installation and updates automagically. Please release AzCopy to Microsoft Store (adding azcopy.exe to environmental variables at the same time), and also for Windows Package Manager.

I see that It's in Chocolatey already.

* https://chocolatey.org/packages/azcopy10

**Comment by adreed-msft** [comment]
I was actually just having this thought as I was reading up on the new `winget` tool.

Currently, we're planning on ironing out the package manager release story for various Linux distros and Windows package managers in the future, but the work hasn't been prioritized. Thanks for the suggestion!

**Comment by mohsha-msft** [comment]
Hey @o-l-a-v 

We have a plan to release AzCopy with different package managers soon. Thanks for your inputs.

**Comment by hansmbakker** [comment]
@mohsha-msft @adreed-msft it is now almost a year later, but I cannot find how AzCopy can be installed using the store or using a package manager. Could you please reopen this issue?

#please-reopen

**Comment by arminreiter** [comment]
hey @mohsha-msft  @adreed-msft : would be great if you make it available via winget
