### ISSUE TITLE
This request is not authorized to perform this operation.

### ISSUE THREAD

**Issue by pkg01** [Azure/azure-storage-azcopy#1014]
### What command did you run?
azcopy login --tenant-id &lt;tenant-id>
INFO: Login succeeded.

azcopy make 'https://&lt;account-name>.blob.core.windows.net/&lt;container-name>'
### What problem was encountered?
-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:9331bd53-701e-0084-52d0-2f9a74000000
Time:2020-05-22T00:31:57.9996938Z, Details:
   Code: AuthorizationFailure
   PUT https://XXXXX.blob.core.windows.net/XXXXXXX?restype=container&timeout=901
   Authorization: REDACTED
   User-Agent: [AzCopy/10.4.3 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [b353a689-199b-4161-67f8-dfeff1b352ac]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Fri, 22 May 2020 00:31:57 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [b353a689-199b-4161-67f8-dfeff1b352ac]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [9331bd53-701e-0084-52d0-2f9a74000000]
   X-Ms-Version: [2019-02-02]
### How can we reproduce the problem in the simplest way?
azcopy login --tenant-id &lt;tenant-id>
azcopy make 'https://&lt;account-name>.blob.core.windows.net/&lt;container-name>'
### Have you found a mitigation/solution?
No

**Comment by adreed-msft** [comment]
What RBAC permissions are on the storage account for the AD principal you're trying to use? The Create Container documentation lists that [only the account owner can call create container](https://docs.microsoft.com/en-us/rest/api/storageservices/create-container#authorization)

**Comment by pkg01** [comment]
I am the owner of the subscription.

**Comment by binoyjt** [comment]
I had the exact same issue. Turned out that the Firewalls on the storage account was set to accept connections from only a set a Public IP's. It allows you to login but will not allow any operation (eg:- list). If you can fire up a browser into the azure portal from the same box that you are using azcopy and try to see if you can get inside the containers(You will still be able to see the storage account).

**Comment by mohsha-msft** [comment]
@pkg01 , I hope steps mentioned by @binoyjt solves your issue. I'm closing this issue. If the issue still persists, please don't hesitate to reopen it.

**Comment by nandorrb** [comment]
Hello I have exactly same issue, I am whitelisted on my IP.

I got this issue when trying to run Azure into Spring framework 2.4.1
I even Created the issue on Spring, but I am not sure if its issue of the Azure library or the Spring Framework

https://github.com/spring-projects/spring-framework/issues/26279
