### ISSUE TITLE
Unexpected failure for otherwise successful copy due to lack of container perms

### ISSUE THREAD

**Issue by malthe** [Azure/azure-storage-azcopy#1018]
### What command did you run?

```bash
$ azcopy copy <source> <destination>
```

The source is a single file and the destination ditto. The destination container already exists.

### What problem was encountered?

I get the following notices as part of the output:

```
Failed to create one or more destination container(s).
Your transfers may still succeed if the container already exists.

0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 

Elapsed Time (Minutes): 0.0333
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed
```

That is, there actually is no problem here, but the job is reported as a failure.

### How can we reproduce the problem in the simplest way?

Create a SAS token that does not have permission to create a container on the destination storage account.

### Have you found a mitigation/solution?

No.

**Comment by adreed-msft** [comment]
Hi there! Could I see a _redacted_ SAS token as an example so I can reproduce this?

**Comment by JohnRusk** [comment]
@adreed-msft Just to clarify, you mean a token where the "sig" value is removed, but everything esle is still present. Right?

**Comment by adreed-msft** [comment]
Correct.

**Comment by malthe** [comment]
@adreed-msft, here is a SAS token: `?sv=2019-10-10&ss=b&srt=o&sp=wlc&se=2021-05-26T16:06:56Z&st=2020-05-26T08:06:56Z&spr=https&sig=[REDACTED]`.

**Comment by malthe** [comment]
Bump?

That is an issue for us because shell scripts fail with a non-zero exit code for no good reason. We can't just swallow the exit code because there might be a real error some day which is then swallowed, too.

**Comment by adreed-msft** [comment]
Sorry for the slow reply, I notice your SAS token allows for only Object operations (judging by `&srt=o`). When creating your SAS token, if you wish for container creation permissions, you should add the Container level of operations.

**Comment by malthe** [comment]
@adreed-msft as I mentioned above, the "destination container already exists". That is, I'm not looking to create any containers here – they will always exist.

And this scenario is probably common to many users relying on container-scope RBAC assignments – the containers will be managed separately.

**Comment by adreed-msft** [comment]
OK, so,

```
Failed to create one or more destination container(s).
Your transfers may still succeed if the container already exists.
```

and

```
Any empty folders will not be processed, because source and/or destination doesn't have full folder support
```

are more or less just warnings. They don't indicate a direct failure condition.

However,

```
0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 

Elapsed Time (Minutes): 0.0333
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed
```

This was a failed transfer. Do you have the log files on hand for this transfer, in that case? They'd live under `~/.azcopy`.

**Comment by malthe** [comment]
I have tried to dig a little deeper into this and haven't been able to consistently reproduce the issue, especially after I have looked through the code to realize that there's no connection to those logging messages and the failure. I'll close out this issue for now and will re-open if needed.
