### ISSUE TITLE
READ permission is required in SASToken for azcopy cp uploading

### ISSUE THREAD

**Issue by gwh-cpnet** [Azure/azure-storage-azcopy#1019]
##### Note: The version is visible when running AzCopy without any argument
10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy cp "/path/to/file.txt" "https://[account].blob.core.windows.net/[container]/[path/to/blob]?[SAS]"

### What problem was encountered?
In the use case of uploading, if SAS section of the destination only got `write` permission, the result would be 
```
100.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 


Job ceecb28e-13d9-da4a-5f5a-xxxxxxxxxxxx summary
Elapsed Time (Minutes): 0.0333
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed
```
The result is a failure. 

I think it would not be a failure, but a success.

1. The file is uploaded to the container. It is there. 
2. To meet the Principle of least privilege, write permission only should be just sufficient to run this uploading job.
3. If `Read` permission is added to the SAS, the result would be a success. But I do not see why it is necessary.

**Comment by adreed-msft** [comment]
Hi there! Set the `--check-length` flag to false. It's by default true.

**Comment by gwh-cpnet** [comment]
@adreed-msft Thanks for pointing out. I figured it got something to do with some checking procedure.
