### ISSUE TITLE
azcopy sync incorrectly handles blobs with prefix of "/"

### ISSUE THREAD

**Issue by sding3** [Azure/azure-storage-azcopy#1023]
### Which version of the AzCopy was used? 

v10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

```
azcopy sync "https://source.blob.core.windows.net/..."  "https://target.blob.core.windows.net/..." 
```

### What problem was encountered?

azcopy trims one leading forward slash from source blobs with names that start with one or more forward slashes, which has two potential consequences:

1. encounter a 404 when the source does not have a blob that matches the trimmed path (more likely)
2. the incorrect blob is sync'ed onto the destination (less likely)

### How can we reproduce the problem in the simplest way?

Using an empty source blob container, create one blob with the name of "//b", then run `azcopy sync` against an empty target blob container, and observe failure. You should see 404 errors in the detailed log file.

**Comment by gapra-msft** [comment]
Hi, this issue should be resolved in the upcoming AzCopy release, which should be out in the next week or so. Closing this issue for now, feel free to open a new issue if you are still having issues with azcopy sync with empty directory names
