### ISSUE TITLE
Can't copy all containers from azurite

### ISSUE THREAD

**Issue by ldepaiva** [Azure/azure-storage-azcopy#1024]
Which version of the AzCopy was used?
10.4.3

Which platform are you using? (ex: Windows, Mac, Linux)
Linux

What command did you run?
`./azcopy cp 'http://127.0.0.1:10000/devstoreaccount1/*?sig=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==' ./data --recursive --from-to=BlobLocal`

`azcopy cp 'http://127.0.0.1:10000//devstoreaccount1//?sig=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==' ./data --recursive --from-to=BlobLocal`

What problem was encountered?
Some clients use azure as their local storage. I would like to migrate them to the latest version of azurite which is not compatible with the version they are currently in. My plan is to move everything to a local folder and then push it again to a new version of azurite.

I have also opened an issue on azurite: https://github.com/Azure/Azurite/issues/424

How can we reproduce the problem in the simplest way?
1. Run azurite by docker.
2. Create a couple of containers and blobs.
3. Execute one of the commands above.

If you look at the logs of azurite you will see that it is in an infinite loop of processing requests from `azcopy` but nothing is really copied.

Have you found a mitigation/solution?
No

**Comment by ldepaiva** [comment]
Hi, @mohsha-msft.

I hope you are doing well.

Any news on that? I just tested with the new release `10.5.0` and it is still not working.

**Comment by gapra-msft** [comment]
@ldepaiva are you still encountering this issue with AzCopy?

**Comment by gapra-msft** [comment]
Closing this issue for now due to inactivity on the thread. Please reopen an issue if you are still experiencing this issue with the latest version of AzCopy
