### ISSUE TITLE
Intermittent failures in Linux client with return code 0

### ISSUE THREAD

**Issue by shubham90** [Azure/azure-storage-azcopy#1026]
### What problem was encountered? There was an intermittent failure with this error "Login AzCopy
2020-05-28 21:15:49.956356:
2020-05-28 21:15:49.956409: Failed to perform login command:
2020-05-28 21:15:49.956420: failed to get token from msi, status code: 500
2020-05-28 21:15:49.956431:
2020-05-28 21:15:49.956439: NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again."

The intermittent error is understandable. The problem is that it didn't throw any error and continued processing the next line. My code is encapsulated in a try catch block and I expected it to have gone in the catch block.
 try {
    ./azcopy login --identity
    Write-Host "Login to AzCopy succeeded"
} catch{
     Write-Host "Login to AzCopy failed"
}
In the above intermittent failure, azcopy client printed "Login to AzCopy succeeded". Note that I am using a user assigned managed identity to do the authentication.

**Comment by nakulkar-msft** [comment]
Hi @shubham90, please use [Autologin](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)) for automoation. Let me know if you still see this issue.
