### ISSUE TITLE
The attribute filter does not work if it contains an asterisk in the path

### ISSUE THREAD

**Issue by basty0722** [Azure/azure-storage-azcopy#1028]
##### Note: The version is visible when running AzCopy without any argument
 10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?

example

.\azcopy.exe copy "D:\dummy\2020*" "SAS" --include-attributes A --recursive --overwrite ifSourceNewer --log-level ERROR

.\azcopy.exe copy "D:\dummy\2019*" "SAS" --include-attributes A --recursive --overwrite ifSourceNewer --log-level ERROR

.\azcopy.exe copy "D:\dummy\2018*" "SAS" --include-attributes A --recursive --overwrite ifSourceNewer --log-level ERROR

-There are many files under the D:\dummy\YYYYMMDD format folder.
-Details are given below
-- Transfer the last 5 years of data to Azure
-- I want to transfer only files with the archive attribute
-- Clear archive attributes after transfer

### What problem was encountered?
When the above command was executed, the following alert occurred.

INFO: Skipping file attribute filter for file 20200105/50004512-00340967/dummy-001.jpg due to error: The filename, directory name, or volume label syntax is incorrect.
INFO: Skipping file attribute filter for file 20200105/50004512-00340967/dummy-002.jpg due to error: The filename, directory name, or volume label syntax is incorrect.

### Have you found a mitigation/solution?
No error occurs if you do not use an asterisk in the source path
example:
 "D:\dummy\*"

**Comment by basty0722** [comment]
Sorry.
Some statements were incorrect.

> Have you found a mitigation/solution?
No error occurs if you do not use an asterisk in the source path
example:
"D:\dummy*"

Correct
example:
"D:\dummy\\*"

**Comment by basty0722** [comment]
Thank you for your support!
I will test it.

**Comment by mohsha-msft** [comment]
Issue has been in v10.5.0
Please reach out to me if the issue persists.
