### ISSUE TITLE
Single file download fails with OAuth, works with SAS

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-azcopy#105]
AzCopy 10.0.3-Preview

`./azcopy cp https://premiumblobfuse.blob.core.windows.net/bigdata/1GBs/myfile1 /mnt
Scanning...
Using OAuth token for authentication.

failed to perform copy command due to error: cannot start job due to error: cannot download the enitre container / virtual directory. Please use --recursive flag.
`

**Comment by jiacfan** [comment]
Hi, @seguler 

Thanks for reporting the issue.

I tried to repro the issue with latest release using following commands, and all of them work fine:
a. .\azure-storage-azcopy.exe copy "https://jiacstgwestcentralus01.blob.core.windows.net/aaaaaa/Test.pdf" "c:\test"
b. .\azure-storage-azcopy.exe copy "https://jiacstgwestcentralus01.blob.core.windows.net/aaaaaa/Test.pdf" "./test.pdf"
c. .\azure-storage-azcopy.exe copy "https://jiacstgwestcentralus01.blob.core.windows.net/a/b/c/Test.pdf" "c:\test"

Would you please help to provide a repro configuration or check if myfile1 actually became a virtual directory after some pre operations?

Thanks,
Jiachen

**Comment by seguler** [comment]
The destination directory must be pre-created. This is inline with other copy tools you'd use on Windows and Linux.

Create it via 
`mkdir -p /shared/home/admin/`
