### ISSUE TITLE
Is AzCopy the best option to Sync +55.000.000 files (+25TB)

### ISSUE THREAD

**Issue by lwlwalker** [Azure/azure-storage-azcopy#1050]
Which version of the AzCopy was used? : 10.4.3
Which platform are you using? Windows
What command did you run?: Sync blob account to blob account
What problem was encountered? Not a problem. Just a doubt.
Please, if this is not the right place to put my question, let me know who/where I can ask it.

In our company we have an User Acceptance (ACC) environment that is a copy of the production environment (synced every month regularly). This implies copy of servers, applications and data.
Currently we store our files in DB (SQL Serve filestream) but we have ready the solution to use AzureBlobs for the files. 
So, to keep the ACC environment updated, we are going to use AzCopy (again, we have this solution ready and working in our test environments)

Currently our prod environment has more than 55.000.000 files, using more than 25TB of data. and these numbers are growing (+5TB per year in the last years)
Then, my question is: Is AzCopy the best option to handle this big sync process? 
Have someone tested a similar workload successfully?
If not, do you know if is there any other option provided by Microsoft to handle this scenario?

Thank you very much for your help!

**Comment by JohnRusk** [comment]
Hi Luis. 

We'd like to advise you on whether to use `azcopy sync`, or to instead use `azcopy copy` in a configuration that produces similar results to a sync. 

There are two questions that will help the team advise on this. 

1. Would you expect to sync the whole prod environment in one AzCopy job? Or would you instead have some kind of natural subdivision of your production environment, and run multiple sync jobs? E.g. if your production environment consists of, say, 100 blob containers, you could run 100 AzCopy jobs.

2. If you are using sync, would you use the --delete-destination flag, and if so, what value would you set it to?  I'm asking because if you _don't_ need delete-destination, then there is a wider range of options we can suggest.

If you can answer those questions, we'll be able to advise you.

**Comment by lwlwalker** [comment]
Hi John,
Answering your questions:
1. We only have 1 container. The information is there split by folders (+-5000 root folders (random names), ). If possible I'd like to make a single sync. Do you think we can sync, for example: all "a*" root folders (recursive), all "b*" root folders, etc....
2. I'm using --delete-destination true, as I want to have ACC with the current files, removing the old ones. And I thought this would be the fastest way to do it. Do you think it would be faster deleting first the full ACC blob container and do a simple copy after this? 

Thank you very much for your help!

**Comment by JohnRusk** [comment]
I like your a*, b* idea.  I'm not sure we easily support it right now, but it's a good idea.

One followup question, are the subfolders inside the root folders?  (Some of our upcoming code may have different perf characteristics depending on whether there's a meaningful hierarchical structure).

**Comment by lwlwalker** [comment]
Great! I'll investigate the a*,b* method (I don't know how to have this done, but I'll review the documentation for this. Hopefully I'll found the right parameter for this 8·D)

About the root folder and subfolders, our file structure is something like this (everything in one single container):

afolder 
 - afolder_subfolder1: 
    - <many files>
 - afolder_subfolder2:
    - <many files>
 - afolder_subfolder3:
    - <many files>
bfolder
 - bfolder_subfolder1: 
    - <many files>
 - bfolder_subfolder2:
    - <many files>
 - bfolder_subfolder3:
    - <many files>
...

**Comment by JohnRusk** [comment]
OK. That structure might get performance benefits from the work @zezha-msft is looking at.

I'm not sure you'll find a good solution in the existing parameter set for a*, b*.  Sorry.

I think the next step is for us to ask @zezha-msft, our sync expert, how necessary it is to break the work up into separate jobs when there are 55 million files in a sync job.  If you had, for instance, 1 million, I'd say "don't break it up", and if you had, say 150 million, I'd say "definitely break it up (with the current version of AzCopy, at least)".    But for 55 million, I'm not _exactly_ sure. So will defer to our expert.

**Comment by lwlwalker** [comment]
Hi @JohnRusk , @zezha-msft , 
Any news on this? Can you confirm that azcopy will be able to handle 55 or 60 million files?
About the filter by folder using "a*", "b*", etc... I've seen that this is not possible. So I will look for a way to get all the root folders and iterate over them. 
Anyway, this approach (go folder by folder) could be useful for other people moving big amounts of data as we are doing now. So it could be a good idea to add it as a switch in azcopy. What do you think? 8-)

**Comment by OranguTech** [comment]
(Just an interested bystander here)
@lwlwalker , have you just tried it?

As for iterating over the root folders, powershell seems the obvious choice, grab folders, pipe to azcopy. You're going to (presumably) need to set up some error handling regardless if it's one run or a hundred.

Unless you know there's going to be a lot of unchanged files on the target, wipe-all, then sync over so you can resume interrupted would be my first pick.

**Comment by nakulkar-msft** [comment]
Hi, we've made improvements to increase number of files in each job of AzCopy. In the new versions we support upto 128Million blobs in  transfer. Let us know if you face difficulties.
