### ISSUE TITLE
azcopy cannot upload file whose file name contains '%'(pencent sign) and numbers to azure container

### ISSUE THREAD

**Issue by Wang-Caixing** [Azure/azure-storage-azcopy#1051]
### Which version of the AzCopy was used? 
AzcopyVersion  10.4.2
According to customer, the latest version also has the same issue. 

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy copy "C:\abcdef\GW155_4.5_OS_Post_DNV" "https://storageaccount.blob.core.chinacloudapi.cn/testazcopy<SAS>" --overwrite=prompt --follow-symlinks --recursive
####Note:  The local directory contains a file named 'abcdef.**%008**'.  This command failed.  

### What problem was encountered?
azcopy cannot upload file whose file name contains '%'(pencent sign), such as file 'abcdef.%008'. 

### How can we reproduce the problem in the simplest way?
1.  azcopy copy "C:\abcdef\GW155_4.5_OS_Post_DNV" "https://storageaccount.blob.core.chinacloudapi.cn/testazcopy<SAS>" --overwrite=prompt --follow-symlinks --recursive
####Note:  The local directory contains a file named 'abcdef.**%008**'.  This command failed.  

2. azcopy copy "C:\abcdef\abcdef.**%008**" "https://philfilesharesacct.blob.core.chinacloudapi.cn/testazcopy<SAS>
This azcopy command failed either. 

### Have you found a mitigation/solution?
Single file 'abcdef.**%008**' can be upload to container on portal or via Microsoft Azure Storage Explorer.

**Comparison Test:  
1. azcopy copy "C:\abcdef\abcdef.**008**" "https://philfilesharesacct.blob.core.chinacloudapi.cn/testazcopy<SAS>
####Change file name as 'abcdef.008', and upload the single file with azcopy successfully. 
2.  azcopy copy "C:\abcdef\GW155_4.5_OS_Post_DNV" "https://storageaccount.blob.core.chinacloudapi.cn/testazcopy<SAS>" --overwrite=prompt --follow-symlinks --recursive
####Note:  The local directory contains a file named 'abcdef.**008**'.  This command completed successfully.  
3. Using Microsoft Azure Storage Explorer version 1.13.1' to upload the direcory which contains 'abcdef.**%008**', it failed either. 

In my verification test, if the file name or file extension contains '%+numbers', the uploading via azcopy will fail. 
I think it might be related to 'Percent-encoding' :  https://en.wikipedia.org/wiki/Percent-encoding

[Goal] Need experts to help check why can't azcopy upload file whose file name or extension contains '%'(pencent sign)+numbers. 
Is this by design or can be improved?  Thanks.

**Comment by Wang-Caixing** [comment]
Hi Team,  may I know do you have any findings or comments about this issue?   Thanks.

**Comment by Wang-Caixing** [comment]
Had a discussion with develop engineer Mohit:
1.  Mohit could reproduce all the scenarios told in this issue. 
2.  Mohit had helped reported this issue to his senior resource for investigation. 
3.  Reached agreement with Mohit that this should be a valid bug and related to 'Percent-encoding':     https://en.wikipedia.org/wiki/Percent-encoding 
4.  Told Mohit that we verified there is no such issue on azcopy v10.1.2. 

Awaiting for further feedback from azcopy development team.

**Comment by Wang-Caixing** [comment]
Hi Experts, 

Is there any update about this issue?   Thanks.

**Comment by Wang-Caixing** [comment]
According to @mohsha-msft , this issue will be fixed with next release which has some time. 
Confirmed with @zezha-msft there is no ETA of the next release.

**Comment by Wang-Caixing** [comment]
Hi @mohsha-msft  and @zezha-msft ,  Is there an ETA of this fix?   Thanks.

**Comment by Wang-Caixing** [comment]
Thanks Mohit for confirmation: 
 PR has been raised for the issue. It will be merged and milestone for this is 10.5 hopefully which we are  going to release in a couple of weeks.

**Comment by Wang-Caixing** [comment]
According to Azcopy developer, 10.5 is going out today or tomorrow.

**Comment by mohsha-msft** [comment]
Issue has been fixed in v10.5.0 
Please reach out to me if the issue still persists.
