### ISSUE TITLE
Using HDFS location as a source to copy using azcopy copy command

### ISSUE THREAD

**Issue by ankurgadgilwar** [Azure/azure-storage-azcopy#1052]
### Which version of the AzCopy was used? 
10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
azcopy copy
### What problem was encountered?
I need to be able to copy data from HDFS to a container. Does the copy command use these as parameters for source (The HDFS file location) or I would have to get them on local and will have to then eventually move to a container? 
### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment]
Hey @ankurgadgilwar ,

Thanks for reaching out!
You can copy your data from HDFS cluster to Azure storage container if URL is public as we don't handle authentication. Alternatively, as you mentioned, you can copy it to local and it definitely will work.
