### ISSUE TITLE
Unable to get azcopy oauth token in cloud-init script

### ISSUE THREAD

**Issue by jmcshane** [Azure/azure-storage-azcopy#1053]
### Which version of the AzCopy was used?

10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

```
azcopy login --identity
azcopy logout
azcopy login --identity
 azcopy cp https://mysa.blob.core.windows.net/files/myarchive.tar /opt/myarchive.tar
```

### What problem was encountered?

The reason im doing login then logout is to see if there is a cached token in the session. When I run logout, I get this message:

```
failed to perform logout command, no cached token found for current user
```

Then, when I run the cp command, I get this error:

```
failed to perform copy command due to error: no SAS token or OAuth token is present and the resource is not public
```

I loop this block over multiple minutes. At the same time my cloud-init script is running, I can run the same azcopy login and cp commands and successfully retrieve the file from the VM.

### How can we reproduce the problem in the simplest way?

Centos 7.7 VM with cloud-init on Azure. Add init-script with the following content:

```
while true
do
    azcopy logout || true
    azcopy login --identity
    EXIT_CODE=0
    azcopy cp <BLOB_ENDPOINT>/artifact.tar /opt/artifact.tar || EXIT_CODE=$?
    if [ "$EXIT_CODE" -eq "0" ];
    then
        break
    fi
    ((c++)) && ((c==10)) && echo "Failed to copy from artifact endpoint" && exit 1 || true
    sleep 60
done
```
### Have you found a mitigation/solution?

No

**Comment by jmcshane** [comment]
This is what I did to get this working:

```
sleep 60
keyctl new_session
sleep 5 #because keyctl new_session only applies to the parent processes after a wait() syscall
azcopy login --identity --identity-resource-id ${identity_id}
keyctl show
azcopy cp '${blob_endpoint}/artifact.tar' '/opt/artifact.tar'
```

This did the trick.

**Comment by sbaier1** [comment]
still the case, really unhandy when provisioning VMs from blob storage...

**Comment by nakulkar-msft** [comment]
Keyctl has limitations. Use [auto-login](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)) for a automation and improved experience.
