### ISSUE TITLE
Azure is charging bandwidth consumption when sync'ing between storage accounts within the same region

### ISSUE THREAD

**Issue by Timothyoverton** [Azure/azure-storage-azcopy#1055]
### Which version of the AzCopy was used? 
10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows VM or Azure function

### What command did you run?
azcopy.exe sync "fileshare[SAS]" "filesahre[SAS]" --log-level=NONE --delete-destination=true

### What problem was encountered?
Both the source and destination storage accounts exist in the same Azure region but in different subscriptions. On initial sync from an Az Func or Windows VM in the same region as the storage accounts, source had 100Gb, destination was empty. There was an unexpected bandwidth charge on the source storage account, the equivalent of 3 times the monthly fee to store the 100Gb in Azure (LRS).
. 
As per MS documentation, bandwidth is charged when it leaves the region... https://azure.microsoft.com/en-au/pricing/details/bandwidth/ "i.e. data going out of Azure data centres;"

Does the AzCopy job run from a specific region? 

### How can we reproduce the problem in the simplest way?
Sync 100Gb using AzCopy, using azure file shares, source and destination should be in the same Azure region (subscriptions shouldn't make a difference)

### Have you found a mitigation/solution?
None found

Hope you can shed some light on this - thanks

**Comment by JohnRusk** [comment]
@amishra-dev This seems pretty weird.  Any ideas?

**Comment by amishra-dev** [comment]
Hi @Timothyoverton 
Do you have the account details for me to check. I am not an expert at this, but i can hit up a few friends to see whats going on.

Thanks

**Comment by Timothyoverton** [comment]
HI @amishra-dev, thanks, this was the source storage share: https://tim.file.core.windows.net/timtest

**Comment by amishra-dev** [comment]
and destination?

**Comment by Timothyoverton** [comment]
destination file share: https://extbackuptesting.file.core.windows.net/timtest
June 9th was the date, during the day (+10 GMT)

**Comment by amishra-dev** [comment]
Hi @Timothyoverton,
Can you try this again from a smaller share? Also which region is this VM in?

**Comment by JohnRusk** [comment]
BTW, how sure are we that the displayed charge was a bandwidth charge, and not a transaction charge?  (I don't know enough about billing to know if this is a relevant question, but figured I'd share it anyway).

**Comment by Timothyoverton** [comment]
Hi,

@amishra-dev I can try it with a smaller share, 5Gb? Region is Australia East.

@JohnRusk I'm looking at Azure > Subscriptions > cost analysis > just filtering by the storageaccount > says bandwidth, see images below

![image](https://user-images.githubusercontent.com/11729026/84894430-2a7ba600-b0e4-11ea-9f7b-c1a8b6719c35.png)

![image](https://user-images.githubusercontent.com/11729026/84894690-8b0ae300-b0e4-11ea-85f1-48c8a4764aac.png)

**Comment by amishra-dev** [comment]
Hi @Timothyoverton,
Thanks for the details, just being pedantic here, but the VM's region (where azcopy is running) is also australiaeast correct?

**Comment by amishra-dev** [comment]
Also, please let me know when you have tried with the 5Gb share. Thanks

**Comment by Timothyoverton** [comment]
Hi, I've been using an Azure Function in Australia East to run the Azcopy, i'll try 5Gb share this morning and let you know.

**Comment by Timothyoverton** [comment]
To create the 100Gb share, I copied a 600mb file several times within the share, maybe that counted as bandwidth? I'm just uploading the full 5Gb now into the smaller share, this will be counted as ingress as per normal. Will see how we go.

**Comment by Timothyoverton** [comment]
I've found a new way to look at storage account stats in the Az Portal... the egress is where the cost lies
![image](https://user-images.githubusercontent.com/11729026/84967578-a3681580-b157-11ea-969d-53761bfb9176.png)

I'll compare this with the 5Gb share that is coming

**Comment by Timothyoverton** [comment]
Hi Guys, midday I ran the 5Gb azcopy using an azure function in the same region as the storage account, this was the result.

Source https://tim.file.core.windows.net/fivegbtest
Destination https://extbackuptesting.file.core.windows.net/fivegbdestination

![image](https://user-images.githubusercontent.com/11729026/84984572-79761980-b17e-11ea-99ea-162d961cb326.png)


Then, I repeated the test with another 5Gb share, to a new share, same storage accounts, but running Azcopy from a VM in the same region. This was the result

Source: https://tim.file.core.windows.net/fivegbtestfromvm
Destination: https://extbackuptesting.file.core.windows.net/fivegbtestfromvmdestination

![image](https://user-images.githubusercontent.com/11729026/84984791-e5588200-b17e-11ea-8a2d-eb0b6e20cea1.png)


The costing for the day cannot be queried at this stage, but based on the above, I'm going to be charged for 10Gb of egress, when the data has never left the region. Can you confirm?

**Comment by Timothyoverton** [comment]
Another View

Source storage account (6 hours)
![image](https://user-images.githubusercontent.com/11729026/84985285-d6be9a80-b17f-11ea-85ba-564a386600cb.png)


Destination storage account
![image](https://user-images.githubusercontent.com/11729026/84985213-b8f13580-b17f-11ea-8b4f-c19c66b3ec50.png)

**Comment by Timothyoverton** [comment]
Hi @amishra-dev 

Looks to be a false alarm, despite the Egress showing 10Gb from the storage account, I haven't been charged any further bandwidth charges for yesterday, the Egress is free as hoped. I'm running a final 50Gb test this afternoon and will double check the billing on Monday, will let you know.

**Comment by amishra-dev** [comment]
Thanks for confirming @Timothyoverton.
