### ISSUE TITLE
failed to perform copy command due to error: no transfers were scheduled because no files matched the specified criteria

### ISSUE THREAD

**Issue by ramiroste** [Azure/azure-storage-azcopy#1059]
### Which version of the AzCopy was used? 
AzCopy 10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2016

### What command did you run?
azcopy copy "/*C:\MY_FOLDER\*.*" "https://myblob.blob.core.windows.net/mynewcontainer"

### What problem was encountered?
failed to perform copy command due to error: no transfers were scheduled because no files matched the specified criteria

Complete feedback:
INFO: Scanning...
INFO: Authenticating to destination using Azure AD
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 5e9900f1-5b8c-c345-5dba-c4cef709b75d has started
Log file is located at: C:\Users\admin\.azcopy\5e9900f1-5b8c-c345-5dba-c4cef709b75d.log

failed to perform copy command due to error: no transfers were scheduled because no files matched the specified criteria

other commands i tried with the same result:
azcopy copy "/*c:\\MY_FOLDER\\MyNewList.csv" "https://myblob.blob.core.windows.net/mynewcontainer"

azcopy copy "/*C:\MY_FOLDER" "https://myblob.blob.core.windows.net/mynewcontainer"

### How can we reproduce the problem in the simplest way?
try to copy a file from a local folder on an azure VM into an azure blob container

### Have you found a mitigation/solution?
NO

**Comment by adreed-msft** [comment]
Pardon me, but the syntax on your local path is incorrect.

Notice the /* at the start: "/*c:\MY_FOLDER\MyNewList.csv"

You should remove it, so your local path is syntactically correct.
