### ISSUE TITLE
Metadata with a value that has a semicolon

### ISSUE THREAD

**Issue by PhbsSmn** [Azure/azure-storage-azcopy#1062]
### Which version of the AzCopy was used?
v10.4.3 (x64)

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
    azcopy copy "<local file path>" "<blob file path>?<sas token>" --metadata "demo=2;5"

### What problem was encountered?
It didn't work, log file doesn't show anything at all either. But found out that it has to do with the semicolon in the metadata value.

### How can we reproduce the problem in the simplest way?
Just upload or simulate an upload with this metadata tag.

### Have you found a mitigation/solution?
I've posted this issue on Stackoverflow: ["azcopy metadata with a value that has a semicolon"](https://stackoverflow.com/questions/62466777/azcopy-metadata-with-a-value-that-has-a-semicolon)
There a person pointed out the following in the [AzCopy code](https://github.com/Azure/azure-storage-azcopy/blob/master/ste/mgr-JobPartMgr.go#L316):

	metadataString := string(dstData.Metadata[:dstData.MetadataLength])
	jpm.metadata = common.Metadata{}
	if len(metadataString) > 0 {
		for _, keyAndValue := range strings.Split(metadataString, ";") { // key/value pairs are separated by ';'
			kv := strings.Split(keyAndValue, "=") // key/value are separated by '='
			jpm.metadata[kv[0]] = kv[1]
		}
	}

There's no check that a semicolon could be an actual part of the property value.

**Comment by adreed-msft** [comment]
It does seem beneficial to be able to escape the semicolon.

**Comment by mohsha-msft** [comment]
@PhbsSmn ,

You can have valid ASCII characters in the key and value provided they are URL encoded. 
For example `--metadata="key1=blah%3Ablah;key2=foo%3Bbar"` will set  `key1 = "blah:blah"` and `key2 = "foo;bar"`

I hope this solves your problem. Please try this and let us know if you face any problems.
