### ISSUE TITLE
Always Hang on certain Azure VM: Standard B1s (1 vcpus, 1 GiB memory)

### ISSUE THREAD

**Issue by vickiss** [Azure/azure-storage-azcopy#1066]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1028-azure x86_64)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy Save "https://xxxxxxxxxx.blob.core.windows.net/xxxxxxxxx/xxxxxxxxxxx?st=2020-04-20T15%3A01%3A00Z&se=2021-03-01T15%3A01%3A00Z&sp=racwdl&sv=2019-06-28&sr=c&sig=xxxxxxxxxxxxxxxxxxxx" --recursive --check-md5 "FailIfDifferent"

### What problem was encountered?

It hangs, and made the VM unresponsive.

![IMG_6059](https://user-images.githubusercontent.com/67308750/85396014-99914880-b583-11ea-9ec5-43d3c44c9f86.JPG)

### How can we reproduce the problem in the simplest way?

It's unstable to repro this issue on my other VMs, it works well. But it always hangs the very VM.

By the way, I runned another Go compiled (go1.14.2) app on the VM, the app sometimes hangs as well. Maybe it's a bug in Go?

### Have you found a mitigation/solution?

No.

**Comment by adreed-msft** [comment]
It's partly known that AzCopy will hang with a particularly low amount of available resources. I suggest scaling your VM up, mainly memory wise.

**Comment by vibhansa-msft** [comment]
If bandwidth limit is put through AzCopy CLI parameter and block size is higher than the bandwidth limit and then it's expected to fail. Latest versions of azcopy will error out such invalid combinations instead of hanging up the process.
