### ISSUE TITLE
Include paths and/or patterns from file (or stdin)

### ISSUE THREAD

**Issue by malthe** [Azure/azure-storage-azcopy#1073]
This is a feature proposal to extend the current `--include-path` and `--include-pattern` options (and `--exclude` counterparts) to allow reading a list from a file, alleviating the command-line limits.

A possible syntax could be that if a path or pattern starts with the "@" character, then the list is loaded from the filename "@<filename>". Entries would be delimited with either ";" or newline.

**Comment by adreed-msft** [comment]
You can handle include-path with `--list-of-files`. Each newline is a new file or folder to transfer. Check the AzCopy wiki for documentation on this hidden parameter.

As to include-pattern, that is a new suggestion that I can see use in. Thank you!

**Comment by malthe** [comment]
@adreed-msft sounds good – I do think that this feature deserves a more prominent place than a "hidden parameter" because it's actually pretty useful.

**Comment by adreed-msft** [comment]
Yeah, we plan to GA it at some point, but due to performance issues we've yet to.

**Comment by malthe** [comment]
There's an issue I have run into which is that you can't use `/dev/stdin` as an input because of the special handling in a TTY situation (i.e. asking the user for interactive input).

I think for non-TTY it would be quite useful to be able to do `--list-of-files /dev/stdin`.

**Comment by weiwei-liu** [comment]
`AzCopy copy d:\sourceDir "http://urlToDestination" --list-of-files fullPathToYourTextFile`
This will transfer the files d:\sourceDir\File_1.pdf and d:\sourceDir\subdirA\File_2.pdf.

I have a situation, what if I have files in drive **c, d, e, f**, instead of just **d:\sourceDir**, how can I achieve this?

**Comment by malthe** [comment]
@weiwei-liu you may be able to achieve this using symbolic links – but of course, using `--list-of-files` does sacrifice some flexibility in terms of the resulting blob name.

**Comment by malthe** [comment]
@adreed-msft wdyt about `--list-of-files /dev/stdin` – ?

**Comment by malthe** [comment]
Bump!

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality. We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
