### ISSUE TITLE
Since 10.4.0 download via piping doesn't work

### ISSUE THREAD

**Issue by vitalyu** [Azure/azure-storage-azcopy#1076]
### Which version of the AzCopy was used? 
10.4.0, 10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux, Centos 7.4,7.7

### What command did you run?
`azcopy cp 'https://....blob.core.windows.net/....sql?se=..&sp=r&sv=...&sr=c&sig=...' | cat`
`azcopy cp 'https://....blob.core.windows.net/....sql?se=..&sp=r&sv=...&sr=c&sig=...' > /tmp/123.sql`

### What problem was encountered?
Piping doesn't work since 10.4.0 release. 
10.3.4 - works fine

### How can we reproduce the problem in the simplest way?
Get the url with SAS token for test blob, download blob via command above

**Comment by adreed-msft** [comment]
Oh yikes! That's a pretty bad regression. I'll go ahead and look at that, and see if it's an easy fix.

**Comment by adreed-msft** [comment]
I was not able to reproduce this on Ubuntu 18.04 with bash or zsh on azcopy 10.4.3

**Comment by vitalyu** [comment]
@adreed-msft , it's very strange, but I can't reproduce it for now.

Steps below wasn't work when issue was created. azcopy was return nothing (no errors, empty string). I tested with curl/wget and azcopy 10.3.4 and all was fine, but not 10.4.0+

Maybe, the problem was not in azcopy, but in azure storage (client header, etc)

```
docker run -it --rm centos:7
cd /usr/bin/ && curl -L https://aka.ms/downloadazcopy-v10-linux | tar --strip-components 1 -xz
export test_url='https://wedevstorage.blob.core.windows.net/azcopy10issue/test.txt?sp=r&st=2020-07-03T10:01:48Z&se=2025-07-03T18:01:48Z&spr=https&sv=2019-10-10&sr=b&sig=sjV8VUsB2DMcOxDWZUy3R7w4txMgtnVWoUuVWl52Wj0%3D'
azcopy copy $test_url
```

**Comment by adreed-msft** [comment]
Interesting. Glad to hear that it's now working.

I noticed this with your script above, in that it appears you're just untaring our archive right into /usr/bin. Are you certain you aren't dumping garbage into /usr/bin? iirc we do include our third party notice in there.

**Comment by vitalyu** [comment]
@adreed-msft untaring to /usr/bin is just for short test in container.
I suppose, I can close the issue. Thank you for your reply and help.
