### ISSUE TITLE
Issue while Copying Files from file Share

### ISSUE THREAD

**Issue by Amarjeet4a** [Azure/azure-storage-azcopy#1077]
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
Azcopy copy sourcesSAS desintaionlocation
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
 Code: AuthorizationFailure
   GET https://cmvuatsa.file.core.windows.net/cmvuatfileshare/Downloaded/?comp=list&restype=directory&se=2030-06-30t08%3A48%3A00z&sig=-REDACTED-&sp=rdl&sr=s&st=2020-06-29t08%3A48%3A5
7z&sv=2018-03-28&timeout=901
   User-Agent: [AzCopy/10.4.3 Azure-Storage/0.7.0 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [ef9880ee-e75d-4f04-5e1b-45d40af954a7]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Tue, 30 Jun 2020 16:58:51 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [ef9880ee-e75d-4f04-5e1b-45d40af954a7]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [5b0853fc-201a-0090-51ff-4e4d0d000000]

**Comment by zezha-msft** [comment]
Hi @Amarjeet4a, please double check your SAS. `sr` which means signed resource only has 's' which means service.
