### ISSUE TITLE
The PercentComplete stat returns greater than 100

### ISSUE THREAD

**Issue by hakantunc** [Azure/azure-storage-azcopy#1078]
### Which version of the AzCopy was used? 

10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

### What command did you run?

azcopy sync

### What problem was encountered?

The PercentComplete stat returns greater than 100.

### How can we reproduce the problem in the simplest way?

See the example `TotalBytesExpected` and `TotalBytesTransferred` values below.

### Have you found a mitigation/solution?

Kind of. I'm not sure if this is the only place the PercentComplete is calculated.

Multiply by 100 after the division operation.

https://github.com/Azure/azure-storage-azcopy/blob/1184c1669bda772b68627a89c224de62ee02837a/ste/init.go#L484

```go
fmt.Println(100 * float32(3099429) / float32(3099429))   // 100.00001
fmt.Println(100 * (float32(3099429) / float32(3099429))) // 100

fmt.Println(100 * float32(3099428) / float32(3099428))   // 99.99999
fmt.Println(100 * (float32(3099428) / float32(3099428))) // 100
```

**Comment by zezha-msft** [comment]
Well spotted!

**Comment by gapra-msft** [comment]
PR https://github.com/Azure/azure-storage-azcopy/pull/2439 should help resolve this issue. Thanks for finding this! We will go ahead and close this issue once the fix is in dev and it should be released in an upcoming release.

**Comment by gapra-msft** [comment]
Closing this since a PR has been merged. This will be resolved in our next release.
