### ISSUE TITLE
Undocumented "list-of-files" prepends nearest directory to output blob name

### ISSUE THREAD

**Issue by malthe** [Azure/azure-storage-azcopy#1082]
With AzCopy 10.4.3, I have stumbled upon the following issue when using the undocumented [--list-of-files](https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer) option.

Running the following command:

```bash
$ azcopy copy path/to/my/source path/to/my/destination --list-of-files manifest.txt
```

I get blob files created as `path/to/my/destination/source/<filename>`.

It seems that a workaround is to specify the source as `path/to/my/source/.` (with a period after the path separator). Still, seems like a bug?

**Comment by zezha-msft** [comment]
Hi @malthe, IIRC that is expected behavior, list-of-files is the same as include-path.

To avoid the source dir being created, you could do:

```
$ azcopy copy "path/to/my/source/*" path/to/my/destination --list-of-files manifest.txt
