### ISSUE TITLE
azcopy sync not uploading changed files

### ISSUE THREAD

**Issue by talhajilal** [Azure/azure-storage-azcopy#1086]
### What command did you run?

Upload on cloud.
azcopy  sync "Source_directory"   "Desit_URL_blob_storage/Container/Token_etc"   --recursive=true   --delete-destination=true

Download from Cloud.

azcopy  sync  "Source_URL_blob_storage/Container/Token_etc"   "Dest_local_directory"     --recursive=true   --delete-destination=true

### When upload content .git directory changes are not being synced on remote blob storage, I also check with sample test file. 
I noticed when I change some content in text file it does not upload on storage.

**Comment by zezha-msft** [comment]
Hi @talhajilal, could you please clarify the scenario?

Is the .git directory under the Source_directory? Was it uploaded? Was it not downloaded?

**Comment by talhajilal** [comment]
Hi Zezha, Thank you for responding. 

This happens when I upload, "azcopy sync" not upload when the file content change some time or from some hosts. 

I am facing sync issue in different way sometime I have and Sometime I don't. Personally  conclude this issue is related to time sync, but I need your advise.

**Comment by mohsha-msft** [comment]
Hey @talhajilal ,

We've done a bunch of modifications in the sync behaviour. Additionally we've added mirror mode support in sync operation via mirror-mode flag. The new mode disables last-modified-time based comparisons and overwrites the conflicting files and blobs at the destination if this flag is set to true.

Can you try to repro this issue in the newest versions of AzCopy and reopen if it persists. Thanks
