### ISSUE TITLE
Unable to download a VHD of managed disk from Azure Portal and Storage Explorer.

### ISSUE THREAD

**Issue by whodanishkhan** [Azure/azure-storage-azcopy#1087]
### Which platform are you using? (ex: Windows, Mac, Linux)
Answer: Windows

### What command did you run?
Answer: Used Storage Explorer with AzCopy.

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Answer: copy  --output-type=json --cancel-from-stdin --overwrite=prompt --check-md5 NoCheck --from-to=BlobLocal --blob-type Detect 

### What problem was encountered?
Answer: 2020/07/03 06:34:23 ==> REQUEST/RESPONSE (Try=1/549.9989ms, OpTime=549.9989ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET (VHD Path)
   X-Ms-Request-Id: []

2020/07/03 06:34:23 PERF: primary performance constraint is Unknown. States: C:  0, R:  1, W: 352, F:  0, H:  6, B: 186, S:  0, P: 32, Q:  0, D:  0, E:  0, T: 577, GRs: 192
2020/07/03 06:34:24 INFO: [P#0-T#0] Error reading body of reply. Next try (if any) will be Try=2. Will NOT retry. Error: unexpected EOF. Offset: 16765386752  Count: 3440640 URL: 
2020/07/03 06:34:24 INFO: [P#0-T#0] Error reading body of reply. Next try (if any) will be Try=2. Will NOT retry. Error: context canceled. Offset: 17408408536  Count: 6341672 URL: 
2020/07/03 06:34:24 ERR: [P#0-T#0] DOWNLOADFAILED: https://md-( disk path )sig=-REDACTED-&sr=b&sv=2017-04-17 : 000 : unexpected EOF. When Enqueuing chunk. X-Ms-Request-Id: 

### How can we reproduce the problem in the simplest way?
Answer: tried downloading the VHD from portal and Storage Explorer.

### Have you found a mitigation/solution?
Answer: No

**Comment by zezha-msft** [comment]
This will be fixed in 10.5.

In the mean time, if you are using a proxy, it'll probably help to bypass that proxy which is most likely the source of the problem.

**Comment by gapra-msft** [comment]
Hi @whodanishkhan I believe the [fix](https://github.com/Azure/azure-storage-azcopy/pull/859) for this issue was merged and released as part of 10.5.0. I will close this issue for now but if you are still encountering the issue, please feel free to reopen the issue.
