### ISSUE TITLE
AWS S3 Copy with MFA

### ISSUE THREAD

**Issue by michaelteo** [Azure/azure-storage-azcopy#1088]
### Which version of the AzCopy was used? 
10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

set AWS_ACCESS_KEY_ID=xxx
set AWS_SECRET_ACCESS_KEY=xxx

azcopy login
azcopy copy "https://bucketname.s3.amazonaws.com/" "https://blobname.blob.core.windows.net/container/" --recursive=true

### What problem was encountered?
Cannot do the AzCopy because ListObjects access was denied. The S3 Bucket policy enabled MFA in our case it was using "GetSessionToken"

Reference: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_configure-api-require.html

### Have you found a mitigation/solution?
I have looked for docs/examples, but I have not seen azcopy support S3 Bucket copy with MFA enabled. So this could be a new feature request vs an issue.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality. We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
