### ISSUE TITLE
Azcopy downloading to memory first before to disk? 

### ISSUE THREAD

**Issue by esinonal** [Azure/azure-storage-azcopy#1093]
### Which version of the AzCopy was used? 
AzCopy 10.5.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
azcopy copy X X

### What problem was encountered?
Azcopy is copying the entire file into memory before moving it to disk? I could see my memory usage spike as I downloaded a file of 1.8G. What if the file is too large for memory, I assume this could be a problem? It slowed down my computer to the point where I could barely click on anything (this is a new computer)

### How can we reproduce the problem in the simplest way?
Download a large (2G file) and watch as your computer struggles... :/ 

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @esinonal, thanks for reaching out!

No, AzCopy does not buffer the entire file, but we do buffer some amount of data. The buffer cap is can be configured by an environment variable (./azcopy env will display all configurations).

INFO: Name: AZCOPY_BUFFER_GB
Current Value:
Description: Max number of GB that AzCopy should use for buffering data between network and disk. May include decimal point, e.g. 0.5. The default is based on machine size.

**Comment by esinonal** [comment]
Ah that's awesome! Thank you!
