### ISSUE TITLE
Acquisition via scoop, chocolatey, etc.

### ISSUE THREAD

**Issue by heaths** [Azure/azure-storage-azcopy#1094]
Acquisition via scoop, chocolatey, etc. is much easier to script and already common for many tools used in CI/CD and development loops. Please consider publishing to something like scoop. You can set up auto-updates fairly easy, like I did [here](https://github.com/ScoopInstaller/Main/pull/1147) for https://github.com/microsoft/vswhere.

**Comment by mohsha-msft** [comment]
Hey @heaths ,

It seems someone from community is already maintaining AzCopy package via chocolatey. Refer [this](https://community.chocolatey.org/packages/azcopy10#install) to know more.
