### ISSUE TITLE
Azure Files Sync - Empty folders

### ISSUE THREAD

**Issue by PaulSaddington** [Azure/azure-storage-azcopy#1099]
AzCopy 10.5.0 - Windows 64 Bit

azcopy sync https://<<REDACTED>>.file.core.windows.net/file-share?se=2020-07-16t15%3A06%3A25z&sig=-REDACTED-&sp=racupwdl&srt=sco&ss=bfqt&sv=2019-02-02 https://<<REDACTED>>.file.core.windows.net/file-share?se=2020-07-16t15%3A06%3A26z&sig=-REDACTED-&sp=racupwdl&srt=sco&ss=bfqt&sv=2019-02-02 --recursive=true --delete-destination true

Empty folders get left behind in the destination when removed from the source.

**Comment by basnijholt** [comment]
Hi @PaulSaddington, 3 days before you opened this issue, I opened https://github.com/Azure/azure-storage-azcopy/issues/1097 about the same issue.
