### ISSUE TITLE
Copy a list of URLs directly to Blobs

### ISSUE THREAD

**Issue by brunosan** [Azure/azure-storage-azcopy#1100]
I understand you can specify a list of [**multiple** local files](https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer) OR a [**single** URL](https://github.com/Azure/azure-storage-azcopy/wiki/Reading-from-custom-URL-or-CDN).

It would be great to find a way to copy a list of URLs.

If I try to use a list of URLS, it considers them local files.

**Comment by mohsha-msft** [comment]
Hey @brunosan ,
I appreciate you reaching out!
As correctly mention by you, we support multiple_local_files/single_URL copy to/from storage account. Also we do not support copying data from multiple URLs in one go. We do not plan to implement it as of now as it does not fit with AzCopy use-case of single source and destination. 

Your use case can be realized by simple shell script of looping over this command to transfer data.
