### ISSUE TITLE
PST copy using azcopy failing

### ISSUE THREAD

**Issue by thejford** [Azure/azure-storage-azcopy#1101]
##### Note: The version is visible when running AzCopy without any argument
10.5.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy cp "local path" "sas path"
### What problem was encountered?
Failed multiple times with numerous instances of this error:
 ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:154
HTTP request failed
### How can we reproduce the problem in the simplest way?
Copy large PSTs(?)
### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment]
@thejford Can you please attach your log file for us to understand the issue in depth. Also tell us the size of file you are trying to copy.
Just for verification, I tried to reproduce the scenario with 150MB file and it uploaded just fine.
