### ISSUE TITLE
Exposed SAS key to all users - security issue with it

### ISSUE THREAD

**Issue by ToledoEM** [Azure/azure-storage-azcopy#1103]
### Which version of the AzCopy was used? 
10.4.3
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux 
### What command did you run?
`azcopy sync $folder/ --recursive https://$account.blob.core.windows.net/$blob/$folder?st=$SASKEY --delete-destination=true`

### What problem was encountered?
When azcopy it is running in a multiuser environment, the SAS key it is expose to all the other users if they check the processes running, with htop it is right there or  with `ps -ef | grep azcopy`.      

`USER_1  233210 233209 99 08:31 pts/2    01:41:36 azcopy sync $folder/ --recursive https://$account.blob.core.windows.net/$blob/$folder?st=$SASKEY --delete-destination=true`.    

This being look by user_3.    
<img width="2376" alt="Untitled 2" src="https://user-images.githubusercontent.com/8144940/87646173-5a02ea00-c746-11ea-9470-770c51928d3b.png">
 
While it is User_1 the one running azcopy in a batch their sas key it is visible by user_3.  
<img width="800" alt="Untitled 3" src="https://user-images.githubusercontent.com/8144940/87646217-6ab36000-c746-11ea-9f3a-b5e2800a6022.png">

### How can we reproduce the problem in the simplest way?  
Execute azcopy in a user  server and run `ps -ef | grep azcopy`.   
  
### Have you found a mitigation/solution?
No, but maybe azcopy by default should hide the process to all the users (_hidepid_)

### Issue

The SAS key should not be exposed to all the users. Since showing the command line for each process for all users is the default behaviour of a Linux server this should be either address as a risk in the documentation, or the SAS key to be hidden from the command line

https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview     
https://docs.microsoft.com/en-us/azure/storage/blobs/security-recommendations    

     
Edit: always someone else had the same question. https://groups.google.com/forum/#!topic/golang-nuts/gELF38g6Pco

**Comment by zezha-msft** [comment]
Hi @ToledoEM, thanks for reaching out!

@adreed-msft could you please take a look?

**Comment by ToledoEM** [comment]
The label is "need more info", what info it is needed?

**Comment by adreed-msft** [comment]
Doesn't look like it's particularly easy to hide this info in Golang. I think it'd be best to document these security implications, in that case, @zezha-msft.

**Comment by ToledoEM** [comment]
Solutions suggestions:

https://unix.stackexchange.com/questions/298178/hide-arguments-of-commands-in-ps    
https://stackoverflow.com/questions/3830823/hiding-secret-from-command-line-parameter-on-unix    
https://serverfault.com/questions/592744/how-to-hide-a-password-passed-as-command-line-argument

**Comment by jlbl** [comment]
Is there likely to be any movement on this?  This is a *huge* security issue.  If there's no intention to fix it, I'll probably need to ban this tool on our cluster.

**Comment by zezha-msft** [comment]
@jlbl an investigation is schedule, we'll update this thread as soon as a mitigation is found.

**Comment by adreed-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/wiki/Security-of-SAS-tokens-on-Linux
