### ISSUE TITLE
Azcopy breaks down the network service

### ISSUE THREAD

**Issue by yuan-commits** [Azure/azure-storage-azcopy#1108]
Wondering if there is a ICM management of azcopy for a MS internal user? If so, which team should I choose? Thank you!

##### Note: The version is visible when running AzCopy without any argument
``` bash
$ azcopy --version
azcopy version 10.3.4
```
### Which platform are you using? (ex: Windows, Mac, Linux)
ubuntu 16.04

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

see the log file

### What problem was encountered?
When a start a azcopy upload job for a large folder eg. 60G on remote ubuntu, the network breaks down.
I can ssh to the ubuntu server, but I cannot use winscp over SFTP to login the ubuntu server. In addition, the connection of vscode remote (to access the remote server) is also lost.

### How can we reproduce the problem in the simplest way?
Yes. Everytime I use azcopy for a foler, the problem accurs.

The following steps to reproduce the error:
1. prepare a ubuntu remote server with azcopy 10.3.4 installed. prepare the data folder like this:

``` bash
$ tree fr_it_es_fs_lazy -h
fr_it_es_fs_lazy
├── [335K]  dict.txt
├── [ 48G]  train.bin
├── [ 13G]  train.idx
├── [329M]  valid.bin
└── [ 92M]  valid.idx
```

2. prepare a windows machine with vs code remote and winscp installed. establish the connection to the remote ubuntu for the two software.

3. open terminal such as mobaxterm, connect to remote server, and input the azcopy command to upload the folder (see azcopy for the details of command).

4. you can find the connection of vs code remote and winscp is lost after run azcopy. But ssh via mobaxterm doesn't. The remote can be reconnect until azcopy process is finished or killed.

### Have you found a mitigation/solution?
No.

### azcopy log:

```
2020/07/22 05:29:20 AzcopyVersion  10.3.4
2020/07/22 05:29:20 OS-Environment  linux
2020/07/22 05:29:20 OS-Architecture  amd64
2020/07/22 05:29:20 Log times are in UTC. Local time is 22 Jul 2020 13:29:20
2020/07/22 05:29:20 Job-Command copy fr_it_es_fs_lazy https://exawattaiprmblob01scus.blob.core.windows.net/philly-ipgsp-beijingteam/yuanz/fairseq_exp/?se=2021-03-03t00%3A46%3A21z&sig=-REDACTED-&sp=rwdlac&spr=https&srt=sco&ss=b&st=2020-03-02t16%3A46%3A21z&sv=2019-02-02 --recursive
2020/07/22 05:29:20 Number of CPUs: 32
2020/07/22 05:29:20 Max file buffer RAM 16.000 GB
2020/07/22 05:29:20 Max concurrent network operations: 300 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2020/07/22 05:29:20 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2020/07/22 05:29:20 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2020/07/22 05:29:20 Max open files when downloading: 1047944 (auto-computed)
2020/07/22 05:29:20 JobID=86256332-72a8-a641-7b33-d3061230906f, credential type: Anonymous
2020/07/22 05:29:20 scheduling JobID=86256332-72a8-a641-7b33-d3061230906f, Part#=0, Transfer#=0, priority=0
2020/07/22 05:29:20 scheduling JobID=86256332-72a8-a641-7b33-d3061230906f, Part#=0, Transfer#=1, priority=0
2020/07/22 05:29:20 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs:  0
2020/07/22 05:29:20 scheduling JobID=86256332-72a8-a641-7b33-d3061230906f, Part#=0, Transfer#=2, priority=0
2020/07/22 05:29:20 scheduling JobID=86256332-72a8-a641-7b33-d3061230906f, Part#=0, Transfer#=3, priority=0
2020/07/22 05:29:20 scheduling JobID=86256332-72a8-a641-7b33-d3061230906f, Part#=0, Transfer#=4, priority=0
2020/07/22 05:29:20 INFO: [P#0-T#0] has worker 1 which is processing TRANSFER
2020/07/22 05:29:20 INFO: [P#0-T#4] has worker 0 which is processing TRANSFER
2020/07/22 05:29:20 INFO: [P#0-T#2] has worker 2 which is processing TRANSFER
2020/07/22 05:29:20 INFO: [P#0-T#3] has worker 4 which is processing TRANSFER
2020/07/22 05:29:20 INFO: [P#0-T#1] has worker 7 which is processing TRANSFER
2020/07/22 05:29:20 INFO: [P#0-T#2] Starting transfer: Source "/home/yuanz/hdd/vendor/fr_it_es_fs_lazy/dict.txt" Destination "https://exawattaiprmblob01scus.blob.core.windows.net/philly-ipgsp-beijingteam/yuanz/fairseq_exp/fr_it_es_fs_lazy/dict.txt?se=2021-03-03t00%3A46%3A21z&sig=-REDACTED-&sp=rwdlac&spr=https&srt=sco&ss=b&st=2020-03-02t16%3A46%3A21z&sv=2019-02-02". Specified chunk size 8388608
```

**Comment by zezha-msft** [comment]
We've responded over email. 

For anyone else who are encountering the same problem: you can limit the concurrent connections that AzCopy uses. Please refer to `azcopy env` for more info.

**Comment by yuan-commits** [comment]
To record my solution in the conmmunity as below:

Following the instruction from azcopy team, for my case, setting AZCOPY_CONCURRENCY_VALUE doesn’t work for me. “--cap-mbps” works, a value of 50 works well, and will not block SFTP services. 

Feature request for your inference: Could it be more clever on uploading a job and not block SFTP services automatically. Thank you.
