### ISSUE TITLE
AzCopy not using all available bandwidth

### ISSUE THREAD

**Issue by ddelapasse2** [Azure/azure-storage-azcopy#1109]

**Comment by mohsha-msft** [comment]
Hey @ddelapasse2 ,

Thanks for reaching out! There can be multiple things which can lead to this. For instance 
	1. Disk I/O can be slow to transfer bytes over the network. 
	2. Single file which you are trying to transfer is small in size and transfer completes before AzCopy tunes the transfer settings(eg. Bandwidth optimization, Concurrency). 

You mentioned that transfer is working well for larger files/folders, it implies that AzCopy is tuning the settings. We want to understand more on what exactly is happening so please attach AzCopy logs and your system configs for more information.

**Comment by ddelapasse2** [comment]
Hi @mohsha-msft ,

My sample file is 50MB.  I have tried doubling the size of the single file, but it seems that the sheer number of files is controlling the size of the "push".  I'm looking for a way to force it to push a single file at the same "total velocity" as multiple files (ie bandwidth amount used).  We are using scheduled uploads so it's important that the 10am file move quickly before the 10:15 files is added to the queue.   I will do another run today and get you those logs.

**Comment by ddelapasse2** [comment]
Hi @mohsha-msft!  

I ran more samples.  It's possible that the throughput value is just incorrect., because the transfer rates were pretty close between uploading a single file vs 5 of those files.  I was wondering though, if you could possibly review my logs?  My computer is on an ocean vessel and my company controls the internet.  There is 4Mbps available (we are the only sender) and we cannot average much over 2.  We have checked this a variety of ways.  The network guy did suggest that I mention the latency (400ms one way, 800ms roundtrip) to see if you think that is causing AzCopy to "hold back".  I have similar issues with my own code using TransferManager UploadAsync.  I would really appreciate an expert opinion and any tips on convincing azcopy to maximize the usage.

[ba44bf1a-73df-6040-4c4d-e95a8e28b63b.log](https://github.com/Azure/azure-storage-azcopy/files/4969786/ba44bf1a-73df-6040-4c4d-e95a8e28b63b.log)
[4422df8e-6c47-9b40-4eb2-013c2a34f207.log](https://github.com/Azure/azure-storage-azcopy/files/4969787/4422df8e-6c47-9b40-4eb2-013c2a34f207.log)

**Comment by ddelapasse2** [comment]
Many many conversations later...it sounds like our large latency is the issue (400ms each way).  According to a smart network guy I finally found if we're using a single TCP connection the most bandwidth we can EVER use is 2.3Mbps.   Inside AzCopy is there a single TCP connection?  If so, is there any Azure ingest mechanism (happy to write our own) that would allow me to insert the packets from separate connections?
