### ISSUE TITLE
Azcopy cannot scan UNC Path

### ISSUE THREAD

**Issue by Shugged** [Azure/azure-storage-azcopy#1112]
### Which version of the AzCopy was used? 
10.5

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2012

### What command did you run?
azcopy cp \\servername\driveletter$\folder\subfolder https://customer.file.core.net/containerSAS --recursive

### What problem was encountered?
failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\?\UNC\servername\driveletter$\folder\subfolder please verify that it is valid

I have confirmed that I can connect to this unc path on file explorer
### Have you found a mitigation/solution?
no

**Comment by RickEllenburg** [comment]
I'm able to use the same version to copy files from a UNC path with 10.5. It does look like you are missing a \ at the beginning of your UNC path. It should start with \\ not \.

azcopy cp **\**\servername\driveletter$\folder\subfolder https://customer.file.core.net/containerSAS --recursive

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/849

**Comment by nakulkar-msft** [comment]
Adding more logs to clarify error.
