### ISSUE TITLE
azcopy fails with service principle

### ISSUE THREAD

**Issue by tvse-central-da** [Azure/azure-storage-azcopy#1118]
### Which version of the AzCopy was used? 
10.5.1
##### Note: The version is visible when running AzCopy without any argument
10.5.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux ( Ubuntu 18.04 )

### What command did you run?
export AZCOPY_SPA_CLIENT_SECRET
./azcopy login --service-principal --application-id --tenant-id
./azcopy copy <source> <destination>

### What problem was encountered?
This is what I am doing 
- In storage account, created a container and created a folder named 'xyz'
- Created a app using app registration and got the service principle id 
- In the Azure storage explorer, gave this service principle a execute permission on the container
- Gave full permission for this folder 'xyz'
- When I try to copy I get this error "OAuth token, SAS token, or shared key should be provided for Blob FS"
- When I use this command azcopy list <url>, this succeeds

Use case
I have a vendor partner who will be copying some files on my storage account in a particular folder. I would like to give access to only that folder inside the storage container.

### How can we reproduce the problem in the simplest way?
Please have a look at the above to reproduce

### Have you found a mitigation/solution?
No

**Comment by tvse-central-da** [comment]
So when creating a directory using Storage Explorer and doing this does not work. But when I create folder using Azure portal->Storage accounts, then it works. Also the above issue does not work with files but work with folders.
 My storage explorer version is  1.9.0

**Comment by nakulkar-msft** [comment]
Fixed
