### ISSUE TITLE
azcopy sync fails when azcopy copy works (using service principal)

### ISSUE THREAD

**Issue by oren-nonamesecurity** [Azure/azure-storage-azcopy#1124]
### Which version of the AzCopy was used? 
azcopy version 10.5.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux - Ubuntu 18.04

### What command did you run?
```
export AZCOPY_SPA_CLIENT_SECRET=
azcopy login --service-principal --application-id ... --tenant-id ...
azcopy sync https://***.blob.core.windows.net/***/*** /tmp/***
```

### What problem was encountered?
`Final Job Status: Failed`
Looking at the log shows 404 error for each file in the directory.

Trying the same command with `copy --recursive` instead of `sync` works well.

Looking at the log (with loglevel DEBUG) shows that the `copy` sends `Authorization: REDACTED` where the `sync` doesn't.
So this looks like missing authorization problem.

### How can we reproduce the problem in the simplest way?
Try `copy` and `sync` from Blob to local.

### Have you found a mitigation/solution?
Nope. Sync keeps failing no matter what.

**Comment by lurifaxel** [comment]
Can confirm this issue on CentOS 7.7 when signing in with `azcopy login --identity` as well.

We sidestepped this by reverting to azcopy 10.4.3. If anyone wants to do that the URL for that version of the Linux binary is https://azcopyvnext.azureedge.net/release20200501/azcopy_linux_amd64_10.4.3.tar.gz (it was a bit tricky to find).

**Comment by riccardopinosio** [comment]
I have the same issue on a windows azure VM. Anyone has a link to the binaries of version 10.4.3 for windows?

**Comment by lurifaxel** [comment]
These should be working URLs for the other OSs as well:

Windows 64-bit: https://azcopyvnext.azureedge.net/release20200501/azcopy_windows_amd64_10.4.3.zip
Windows 32-bit: https://azcopyvnext.azureedge.net/release20200501/azcopy_windows_386_10.4.3.zip
Mac: https://azcopyvnext.azureedge.net/release20200501/azcopy_darwin_amd64_10.4.3.zip

**Comment by krknopp** [comment]
Thank you!  10.5 and 10.6 both have this same problem.  Been fighting it for weeks now.  I get 401 errors from the storage account with those versions when trying to sync from Blob to local.  Copy and syncing from local to Blob work great.

**Comment by zezha-msft** [comment]
Hi, sorry for the inconvenience!

I believe the sync command had a bug that was fixed [here](https://github.com/Azure/azure-storage-azcopy/commit/949fb327b424ad1ae696677be8f1870ca68099c2), could you please try the latest version? Please do let me know if you are still encountering any issue.
