### ISSUE TITLE
Request is not authorized to perform blob overwrite - Error 403

### ISSUE THREAD

**Issue by chandra9787** [Azure/azure-storage-azcopy#1125]
Im trying to deploy files in destination storage account via CI/CD and using azcopy task for the same. Im trying to copy from my repo to a folder in my storage account container (StorageAccount/Container/Folder/* )

I have storage **Contributor** access to my devops service connection and also assigned Read,Write , Execute permission for the Folder to which Im trying to copy.

I was able to copy to my folder but I couldn't do overwrite

Tried with --Overwrite-true --check-length false too

AzCopy task ver. 4 in Release

Can someone please help me with this?

Thanks,
Chandra

**Comment by mohsha-msft** [comment]
Hey @chandra9787 

Thanks for reaching out. !!
Please check read a little more on roles and permission from here.
[Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#contributor) vs [Storage Data Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor)

Contributor role lets you manage everything except granting access to resources. But what you probably are looking for is a **"Storage Data Blob Contributor" , "Storage Data Queue Contributor" **and** "FHIR Data Contributor" roles**. Please read up on them and if your query still persists, please reach out to me for more clarification.
