### ISSUE TITLE
Timestamp metadata not preserved when moving Table in classic Storage to a different subscription using AzCopy 7.3

### ISSUE THREAD

**Issue by tawlin** [Azure/azure-storage-azcopy#1127]
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

First command:
AzCopy /Source:https://$sourceStorageName.table.core.windows.net/osibigredswitch/ /Dest:https://$targetStorageName.blob.core.windows.net/ /SourceType:table /DestType:blob /SourceSAS:"$sourceSAS" /DestSAS:"$targetSAS"

Second command:
AzCopy /Source:https://$targetStorageName.blob.core.windows.net/ /Dest:https://$targetStorageName.table.core.windows.net/osibigredswitch /SourceSAS:"$targetSAS" /DestSAS:"$targetSAS" /Manifest:$manifestName  /EntityOperation:InsertOrReplace

### What problem was encountered?
We have a Table in a classic Storage Account that we want to move to a different subscription (sub B).  The current subscription (sub A) has multiple classic Storage Accounts in it, but we only want to move one of them to a different subscription (sub B).

After reading some Azure documents, there seems to be some limitation on classic Storage resource that I can only move ALL classic resources to a different subscription, not only moving one of them.

The only feasible solution I can find to move a Table in Classic Storage is a 2 steps procedure:
1. Use AzCopy 7.3 to export the Table in Sub A to Blob in Sub B (First command above)
2. Use AzCopy 7.3 to import the Blob in Sub B to Table in Sub B (Second command above)

However, we are seeing the "Timestamp" column not preserved after finished step 1 & 2.  Timestamp is overwritten by the time when we ran AzCopy.

Is there a way to preserve the Timestamp metadata with AzCopy 7.3?
Since we already made the transition to the new subscription, is there a way to update the Timestamp column in Sub B with content in the original Table in Sub A?

### How can we reproduce the problem in the simplest way?
Ran the 2 commands

### Have you found a mitigation/solution?
No

**Comment by amishra-dev** [comment]
Table Server is no longer supported by azcopy. please consider using azure data factory https://docs.microsoft.com/en-us/azure/data-factory/connector-azure-table-storage
