### ISSUE TITLE
Not backwards compatable with plan files

### ISSUE THREAD

**Issue by LRomandine** [Azure/azure-storage-azcopy#1130]
##### Note: The version is visible when running AzCopy without any argument
10.5.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
az jobs list

### What problem was encountered?
Old jobs are not displayed

### How can we reproduce the problem in the simplest way?
Have a plan file from an older version of azcopy and run `azcopy jobs list` and the old job will not display.

### Have you found a mitigation/solution?
Must use older binary to read older .steV## plan files.

Looking through the code it looks like the DataSchemaVersion must match between the binary and the plan files.  If it does not match, the files are not read (in my case .steV10 files cannot be read by azcopy 10.5.1 which expects .steV14 files).  Renaming the files does not work and causes azcopy to crash (as expected) due to the files being the wrong format/schema.

azcopy should be backwards compatible with plan files to enable users to upgrade their binary and be able to read old plan files via `azcopy jobs list`.

**Comment by nakulkar-msft** [comment]
@LRomandine Thanks for reaching us! This is by design and the user is expected to complete the older jobs  using a older version. We do not have plans to remove this restriction.
