### ISSUE TITLE
azcopy commands after 10.5.0 fail when trying to work through non-reachable proxy server

### ISSUE THREAD

**Issue by dtonagel** [Azure/azure-storage-azcopy#1132]
##### Note: The version is visible when running AzCopy without any argument
v10.5.1 on command line or v10.5.0 with Azure Storage Explorer

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "R:\test.txt" "https://MyCloud.blob.core.windows.net/MyContainer/test.txt?se=2020-09-09T07%3A05%3A38Z&sp=rwl&sv=2018-03-28&sr=c&sig=..." --from-to=LocalBlob

Other commands like list are also affected.

### What problem was encountered?
Program hangs with no progress. Canceled after 5 minutes. Cancel takes another minute.

> INFO: Scanning...
> INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
> 
> Job a32bbc33-63ce-2d45-5c43-6289eeea9abd has started
> Log file is located at: C:\Users\MyUser\.azcopy\a32bbc33-63ce-2d45-5c43-6289eeea9abd.log
> 
> 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,

### How can we reproduce the problem in the simplest way?
I can repro when I try to upload anything with SAS-Key or through latest Azure Storage Explorer (1.14.2, which according to Release-Notes is using azcopy 10.5.0

According to the log files, the version 10.5 is trying to use a proxy server for the connection which is not reachable at that time. I occasionally use that proxy when connected to work via VPN, but it is neither set in the Windows Proxy settings nor in any environment variable. So I have no idea where it gets that proxy url from. 
Version 10.4 run from the same command line does not use the proxy. Excerpt from the log files:

#### V10.5.1

> 2020/08/10 08:41:39 INFO: [P#0-T#0] Starting transfer: Source "%5C%5C?\\R:\\subtest.txt" Destination "https://MyCloud.blob.core.windows.net/MyContainer/test2.txt?se=2020-09-09t07%3A05%3A38z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28". Specified chunk size 8388608
> 2020/08/10 08:41:40 ==> REQUEST/RESPONSE (Try=1/9.7619ms, OpTime=9.7619ms) -- REQUEST ERROR
>    PUT https://MyCloud.blob.core.windows.net/MyContainer/test2.txt?se=2020-09-09t07%3A05%3A38z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
>    Content-Length: [7]
>    User-Agent: [AzCopy/10.5.1 Azure-Storage/0.10 (go1.14.7; Windows_NT)]
>    X-Ms-Blob-Cache-Control: []
>    X-Ms-Blob-Content-Disposition: []
>    X-Ms-Blob-Content-Encoding: []
>    X-Ms-Blob-Content-Language: []
>    X-Ms-Blob-Content-Md5: []
>    X-Ms-Blob-Content-Type: [text/plain; charset=utf-8]
>    X-Ms-Blob-Type: [BlockBlob]
>    X-Ms-Client-Request-Id: [f9718368-fbfb-4fdc-4231-6fb7dc18923f]
>    X-Ms-Version: [2019-02-02]
>    --------------------------------------------------------------------------------
>    ERROR:
> -> github.com/Azure/azure-pipeline-go/pipeline.NewError, C:/Users/MyUser/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:154
> HTTPrequest failed
> 
> Put "https://MyCloud.blob.core.windows.net/MyContainer/test2.txt?se=2020-09-09T07%3A05%3A38Z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901": proxyconnect tcp: dial tcp: lookup MyProxy.de: no such host

#### V10.4.3

> 2020/08/10 09:16:37 INFO: [P#0-T#0] Starting transfer: Source "%5C%5C?\\R:\\subtest.txt" Destination "https://MyCloud.blob.core.windows.net/MyContainer/test2.txt?se=2020-09-09t07%3A05%3A38z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28". Specified chunk size 8388608
> 2020/08/10 09:16:38 ==> REQUEST/RESPONSE (Try=1/34.9957ms, OpTime=197.9987ms) -- RESPONSE SUCCESSFULLY RECEIVED
>    PUT https://MyCloud.blob.core.windows.net/MyContainer/test2.txt?se=2020-09-09t07%3A05%3A38z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
>    X-Ms-Request-Id: [342d8894-d01e-0005-72f6-6ec54d000000]
> 
> 2020/08/10 09:16:38 ==> REQUEST/RESPONSE (Try=1/26.997ms, OpTime=26.997ms) -- RESPONSE SUCCESSFULLY RECEIVED
>    HEAD https://MyCloud.blob.core.windows.net/MyContainer/test2.txt?se=2020-09-09t07%3A05%3A38z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
>    X-Ms-Request-Id: [342d88ac-d01e-0005-08f6-6ec54d000000]
> 
> 2020/08/10 09:16:38 INFO: [P#0-T#0] UPLOADSUCCESSFUL: https://MyCloud.blob.core.windows.net/MyContainer/test2.txt

### Have you found a mitigation/solution?
Same command works with azcopy v10.4.3 or older versions of Azure Storage Explorer.

Since apparently something has changed in the way proxy servers are located, it could probably mitigated by disabling the proxy setting, but as mentioned above, the proxy is set neither in Windows (10, 2004) nor in any environment variable, so I don't know where it gets the setting from. It *is* set directly in Azure Storage Explorer but in a disabled state (Proxy Settings -> "Do not use proxy"). All other network related programs work with no problem.

**Comment by zezha-msft** [comment]
Hi @dtonagel, have you tried setting the environment variables to disable the proxy explicitly? 

Please follow the instructions [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure?toc=/azure/storage/blobs/toc.json#configure-proxy-settings).

**Comment by mohsha-msft** [comment]
Closing the stale issue. If it still persists with new versions of AzCopy, please reopen it.
