### ISSUE TITLE
Table support (background)

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [Azure/azure-storage-azcopy#1133]
Table support (primarily interested in copy) is not available instead users are asked to use an earlier version.  Why was table dropped from the tool?  Table is also poorly supported by Azure CLI (i.e. no copy feature).  Briefly looked at the Go code which uses **azure-storage-blob-go** to act on Storage via [Azure Rest](https://docs.microsoft.com/en-us/rest/api/azure/).  Assuming that there is no **azure-storage-table-go** since the current Rest API has no corresponding endpoint?  Dug around for the 7.3.1 code of AzCopy without luck.  Was interested how coping worked in that version against table storage.  Also dug around for any Azure info on upcoming support for copy with table but hit a wall.  Any background info would be great.

**Comment by zezha-msft** [comment]
Hi @MatthewDavidCampbell, thanks for reaching out!

Table support was dropped from AzCopy for many reasons, most notably there are better offerings such as the [Cosmos DB Table](https://docs.microsoft.com/en-us/azure/cosmos-db/table-introduction). 

AzCopy 7.3 (which supports table) can be downloaded [here](https://aka.ms/downloadazcopynet). Right now, we have no plans of adding table support into V10.

Please let us know if you have other questions.
