### ISSUE TITLE
Trying to Move/Copy/Sync Storage Accounts in Germany to Global Cloud with AzCopy

### ISSUE THREAD

**Issue by happyiphone** [Azure/azure-storage-azcopy#1135]
Trying to move Storage Accounts in between the non-public Germany cloud (https://portal.microsoftazure.de) and some other Global Cloud.

By reading this recommendations https://docs.microsoft.com/en-us/azure/germany/germany-migration-storage it mentions AzCopy as an option and so by reading this other [document](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs#copy-all-containers-directories-and-blobs-to-another-storage-account) about AzCopy it mentions that I can move all containers, directories and blobs to another Storage Account so I just want to do that

`azcopy copy 'https://<source-storage-account-name>.blob.core.windows.net/<SAS-token>' 'https://<destination-storage-account-name>.blob.core.windows.net/' --recursive`

azcopy copy "https://<source-account-name>.blob.core.cloudapi.de?se=2020-08-12&sp=rl&sv=2018-11-09&sr=c&sig=<correct-signature-goes-here>" "https://<destination-account-name>.blob.core.windows.net?sv=2019-02-02&st=2020-08-11T18%3A46%3A14Z&se=2020-08-12T18%3A46%3A14Z&sr=c&sp=rcwl&sig=<some-other-correct-signature-goes here>" --recursive  

But I get this instead:

```
INFO: Scanning...

failed to perform copy command due to error: failed to list containers: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:372d3c0d-101e-001f-1711-70d889000000
Time:2020-08-11T19:02:08.7235497Z, Details:
   AuthenticationErrorDetail: The specified signed resource is not allowed for the this resource level
   Code: AuthenticationFailed
   GET https://thyco0towmto2i851j7w42ph.blob.core.cloudapi.de?comp=list&se=2020-08-12&sig=-REDACTED-&sp=rl&sr=c&sv=2018-11-09&timeout=901
   User-Agent: [AzCopy/10.5.1 Azure-Storage/0.10 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [5e5bce0a-04ae-4050-553b-5574c54339b2]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [447]
   Content-Type: [application/xml]
   Date: [Tue, 11 Aug 2020 19:02:08 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [372d3c0d-101e-001f-1711-70d889000000]

````

What am I doing incorrectly?

I tried to do the same with a single BLOB and I can copy it just fine so is not the method am using that seems to be incorrect.

Any help or any test that is needed will be more than appreciated!

Thanks

##### Note: The version is visible when running AzCopy without any argument
10.5.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "https://<source-account-name>.blob.core.cloudapi.de?se=2020-08-12&sp=rl&sv=2018-11-09&sr=c&sig=<correct-signature-goes-here>" "https://<destination-account-name>.blob.core.windows.net?sv=2019-02-02&st=2020-08-11T18%3A46%3A14Z&se=2020-08-12T18%3A46%3A14Z&sr=c&sp=rcwl&sig=<some-other-correct-signature-goes here>" --recursive  

### What problem was encountered?
Not doing what the documentation says it should do.

### How can we reproduce the problem in the simplest way?
Running the same command and try to copy the entire Storage Account in between regions?

### Have you found a mitigation/solution?
Not yet other than writing it with the SDK.

**Comment by happyiphone** [comment]
I think the issue is that the special character % is being used inside a PowerShell script and I think it needs to be escaped. Not sure if others special chars need to be escaped but so far with % works.

**Comment by mohsha-msft** [comment]
Hey @happyiphone ,

I appreciate you reaching out and I apologize for late response.
Can you please tell me how you are generating SAS token? I think it can be because of insufficient permissions. To move a container you need a container level SAS. Also, please attach logs of failed job of AzCopy to help me understand this problem better.

**Comment by happyiphone** [comment]
I ended up finding what my problem was and it was that the token was generated for a BLOB not at the container level. Thank anyway. I'll close this.
