### ISSUE TITLE
Azcopy Copy Crashes Mac OS 10.15.5 

### ISSUE THREAD

**Issue by leokster** [Azure/azure-storage-azcopy#1136]
### Which version of the AzCopy was used? 
azcopy version 10.5.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac OS 10.15.5, 2.3 GHz 8-Core Intel Core i9, 32 GB RAM

### What command did you run?
azcopy copy "/my/local/path" "https://my_storage_account.blob.core.windows.net/container/path/" --recursive --overwrite false
### What problem was encountered?
After few minutes the entire system crashes and the mac restarts. System Log sais: 
```
panic(cpu 2 caller 0xffffff7f9f3a1ad5): userspace watchdog timeout: remoted connection watchdog expired, no updates from remoted monitoring thread in 69 seconds, 84 checkins from thread since monitoring enabled 1730 seconds ago after wakeservice: com.apple.logd, total successful checkins since wake (1730 seconds ago): 173, last successful checkin: 10 seconds ago
service: com.apple.WindowServer, total successful checkins since wake (1730 seconds ago): 173, last successful checkin: 10 seconds ago
```

The local file structure is:

/year/month/day/hour/my_file

Where there are 2-48 files for every hour, each 300-900 KB. I've tried to upload a whole year as well as only a single month. The problem occurs in both scenarios. One month is around 25 GB.

### How can we reproduce the problem in the simplest way?

Probably by creating a similar file structure and running the command on the same system. 

### Have you found a mitigation/solution?
No, not yet. The problem occurs by running the command manually in a terminal as well as copying files with "Microsoft Azure  Storage Explorer".

**Comment by nakulkar-msft** [comment]
@leokster Can you upload the core? Or post a backtrace?

**Comment by leokster** [comment]
> @leokster Can you upload the core? Or post a backtrace?

Do you refer the logfile, azcopy creates in ~/.azcopy/********.log ? That one does have multiple entries of the type:
```
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:154
HTTP request failed

Put https://*****.blob.core.windows.net/container/2018/10/5/file?se=2020-09-11T09%3A05%3A54Z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901: read tcp 192.168.178.135:54070->xxx.xxx.xxx.xxx:443: read: operation timed out

```

But there is nothing at the end, which explains the crash?

Otherwise, could you tell me what exactly you need? 
Thanks!

**Comment by zezha-msft** [comment]
Hi @leokster, do you mind trying the latest version 10.7?

It is quite surprising to see a crash of this magnitude, would it help if you limit the concurrency? (please follow the doc [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure?toc=/azure/storage/blobs/toc.json#optimize-throughput))

Ex: 
```
export AZCOPY_CONCURRENCY_VALUE=4
```

**Comment by jayqi** [comment]
I've had this exact problem happen to me many times over the last year when using `azycopy`, including just now. Other symptoms noted (e.g., network traffic going down a few minutes before crash) are the same. 

- macOS 10.15.7
- azcopy 10.9.0

I also see a similar error text:

<details><pre>
2021/03/23 21:59:26 ==> REQUEST/RESPONSE (Try=1/35.409µs, OpTime=3m33.453399094s) -- REQUEST ERROR
   PUT <redacted>
   Content-Length: [3948337]
   User-Agent: [AzCopy/10.5.0 Azure-Storage/0.10 (go1.13; darwin)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Md5: []
   X-Ms-Blob-Content-Type: [text/plain; charset=utf-8]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [e4d7a8a0-a3ca-4e05-4a30-ccb57a6576d8]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:154
HTTP request failed

Put <redacted>: write tcp <redacted>-><redacted>: write: broken pipe

goroutine 394 [running]:
github.com/Azure/azure-storage-azcopy/ste.stack(0xc041295830, 0xc0427c0700, 0x0)
        /Users/runner/work/1/s/ste/xferLogPolicy.go:232 +0x9d
github.com/Azure/azure-storage-azcopy/ste.NewRequestLogPolicyFactory.func1.1(0x4932e80, 0xc000afd8c0, 0xc000278c00, 0x10, 0x0, 0x0, 0xc000db5490)
        /Users/runner/work/1/s/ste/xferLogPolicy.go:146 +0x7a5
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0001a6ff0, 0x4932e80, 0xc000afd8c0, 0xc000278c00, 0xc000db5518, 0xc02a9d4b20, 0x400e6b6, 0xc0001aa3f0)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0x4932e80, 0xc000afd8c0, 0xc000278c00, 0xc02a9d4bf8, 0xc02a9d4ba8, 0x400e6b6, 0xc0001a7090)
        /Users/runner/work/1/s/ste/mgr-JobPartMgr.go:77 +0x1b1
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000ad9480, 0x4932e80, 0xc000afd8c0, 0xc000278c00, 0x10, 0x10, 0x4728980, 0x405fd80)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0x4923ee0, 0xc000ad9480, 0xc000267900, 0x4932e80, 0xc000afd8c0, 0xc000278c00, 0x0, 0x4e20aa0, 0xc02a9d4c08, 0x4030001)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.0/azblob/zz_generated_responder_policy.go:33 +0x53
github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(...)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.0/azblob/zc_credential_anonymous.go:54
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do(0xc000918ae0, 0x4932e80, 0xc000afd8c0, 0xc000278c00, 0x0, 0x0, 0x0, 0xc02a9d4d28)
        /Users/runner/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x5b
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000918af0, 0x4932e80, 0xc000afd8c0, 0xc000278c00, 0xc000afd8c0, 0xc000918c90, 0xc000000001, 0x0)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0x4932e00, 0xc000ae43c0, 0xc000278b00, 0x10, 0x46d6ae0, 0x64492d747301, 0xc000db51d0)
        /Users/runner/work/1/s/ste/xferRetrypolicy.go:384 +0x708
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0001a7040, 0x4932e00, 0xc000ae43c0, 0xc000278b00, 0xc000db5300, 0x30, 0x28, 0x8)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0x4932e00, 0xc000ae43c0, 0xc000278b00, 0x10, 0x46d6ae0, 0x400ef01, 0xc000db5080)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_unique_request_id.go:19 +0xae
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000ad94c0, 0x4932e00, 0xc000ae43c0, 0xc000278b00, 0xc000db5138, 0x31, 0xc000a30500, 0xc02a9d50f0)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0x4932e00, 0xc000ae43c0, 0xc000278b00, 0x1, 0x0, 0x1, 0xc00011a498)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_telemetry.go:34 +0x15d
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000d8e9c0, 0x4932e00, 0xc000ae43c0, 0xc000278b00, 0xc000d8e9c0, 0x0, 0xc02a9d51c0, 0x400ef28)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc000e7e5c0, 0x4932e00, 0xc000ae43c0, 0x4923fc0, 0xc000267900, 0xc000278b00, 0x29, 0xc000c48031, 0x93, 0x0)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/core.go:129 +0x81
github.com/Azure/azure-storage-blob-go/azblob.blockBlobClient.Upload(0xc000c48000, 0x5, 0x0, 0x0, 0x0, 0xc000c48008, 0x29, 0xc000c48031, 0x93, 0x0, ...)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.0/azblob/zz_generated_block_blob.go:503 +0x5c9
github.com/Azure/azure-storage-blob-go/azblob.BlockBlobURL.Upload(0xc000c48000, 0x5, 0x0, 0x0, 0x0, 0xc000c48008, 0x29, 0xc000c48031, 0x93, 0x0, ...)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.0/azblob/url_block_blob.go:65 +0x26a
github.com/Azure/azure-storage-azcopy/ste.(*blockBlobUploader).generatePutWholeBlob.func1()
        /Users/runner/work/1/s/ste/sender-blockBlobFromLocal.go:109 +0x62d
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0x61)
        /Users/runner/work/1/s/ste/sender.go:179 +0x1a7
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc0002801a0, 0x61)
        /Users/runner/work/1/s/ste/JobsAdmin.go:433 +0xdf
created by github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).poolSizer
        /Users/runner/work/1/s/ste/JobsAdmin.go:362 +0x67b

</pre></details>

There are 226 instances of this error in my most recent log file in `~/.azcopy`.

Some kind of rogue concurrency issue sounds pretty plausible. I will try setting `AZCOPY_CONCURRENCY_VALUE` going forward but it sounds like the default may need to be adjusted down.

**Comment by zezha-msft** [comment]
Hi @jayqi, thanks for reaching out!

A colleague of mine also saw some strange behavior when he was running AzCopy on an older MacOS version. If possible, I'd suggest to upgrade to Big Sur, which may help.

Personally I've been using Big Sur and it is very stable.

**Comment by gukoff** [comment]
I think I might be experiencing the same problem.
Using the latest OSX Sonoma 14.1 and azcopy 10.21.2.

When I try to download contents of a storage container (60k small files, ~2GB total size), the system first starts to stutter, then the network stops working on the computer and many apps become unresponsive. All that after only a couple of MBs are downloaded.

I did not see the system crash because I always killed azcopy and rebooted myself.

The same azcopy command works fine on linux VM in the cloud.  

```
azcopy copy "https://my-storage-account.blob.core.windows.net/folder-name/?sv=2023-01-03&se=2023-12-08T17%3A00%3A29Z&sr=c&sp=rl&sig=redacted" . --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive --log-level=INFO;
```
