### ISSUE TITLE
Sync fail with 404 The specified resource does not exist (service principle logon)

### ISSUE THREAD

**Issue by tfselby** [Azure/azure-storage-azcopy#1137]
### Which version of the AzCopy was used? 
10.5.1

### Which platform are you using? (ex: Windows, Mac, Linux)
WIndows 10 1809 17763.1339

### What command did you run?
2020/08/12 12:20:25 Job-Command sync https://Redacted/cwsynccontrol/CaseWare_Sync_Control C:\ProgramData\Caseware Sync Utility\CaseWare_Sync_Control --delete-destination=TRUE 
...
2020/08/12 12:20:25 ==> REQUEST/RESPONSE (Try=1/23.986ms, OpTime=131.6992ms) -- RESPONSE SUCCESSFULLY RECEIVED
 GET https://Redacted/cwsynccontrol/CaseWare_Sync_Control/03pilot_template.job.txt?timeout=901

### What problem was encountered?
2020/08/12 12:20:25 ERR: [P#0-T#1] DOWNLOADFAILED: https://Redacted/cwsynccontrol/CaseWare_Sync_Control/03pilot_template.job.txt : 404 : 404 The specified resource does not exist.. When Downloading response body. X-Ms-Request-Id: Redacted

 Dst: %5C%5C?\C:\ProgramData\Caseware Sync Utility\CaseWare_Sync_Control\03pilot_template.job.txt

2020/08/12 12:20:26 INFO: [P#0-T#0] https://Redacted/cwsynccontrol/CaseWare_Sync_Control/01pilot_library.job.txt Deleting incomplete destination file Dst: %5C%5C?\C:\ProgramData\Caseware Sync Utility\CaseWare_Sync_Control\01pilot_library.job.txt

### How can we reproduce the problem in the simplest way?
Not sure why this version fails to work nothing has changed in the blob store and it works in previous versions of the utility.

May be related to using service-principal to authenticate prior to Sync job.

Others also have reported sync failures using service-principal logons.  (Also fails in 10.6.0)  See issue #1124

### Have you found a mitigation/solution?
Reverted to earlier Azcopy 10.4.x

**Comment by zezha-msft** [comment]
Hi @tfselby, sorry for the inconvenience.

I believe the sync command had a bug that was fixed [here](https://github.com/Azure/azure-storage-azcopy/commit/949fb327b424ad1ae696677be8f1870ca68099c2), could you please try the latest version? Please do let me know if you are still encountering any issue.
