### ISSUE TITLE
Incorrect Content-Type in BlobStorage after Upload with Azure Storage Explorer / AzCopy / Azure Portal

### ISSUE THREAD

**Issue by fgillmann** [Azure/azure-storage-azcopy#1139]
### Which version of the AzCopy was used? 
10.5.0 in Storage Explorer 1.14.2 (AzCopy command prompt and Azure Portal used version unknown, was done by our IT)

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
Uploaded folders with files, containing *.html and *.css, to BlobStorage with Azure Storage Explorer.
Then our IT retried the same with AzCopy itself and after that via Azure Portal.

### What problem was encountered?
Content-Type for css, htm, html, xml files with 'text/*' has trailing ; appended.
e.g. 
for index.html the Content-Type is text/html;
for bundle.css the Content-Type is text/css;
etc.
which leads to Error in Kestrel Webserver because the Content-Type is invalid.

### How can we reproduce the problem in the simplest way?
Upload folder with files, containing *.html and *.css, to BlobStorage

### Have you found a mitigation/solution?
Change every Content-Type per hand inside the BlobStorage, if you're really bored  🤣 

Problem seems to be introduced with #1043

**Comment by atikhono** [comment]
I'm also experiencing this issue. Content-Type used to be set to "text/html; charset=utf-8" previously and with the latest version it's "text/html;". Breaks Cypress tests for us.

**Comment by apsarpasha** [comment]
Do we have any ETA for the fix or Workaround this issue ?  Any help on this much appreciated.

**Comment by Quirkafleeg** [comment]
I can confirm the Content-Type is broken - possibly by a partial fix to this bug - when copying containers.
**Usage:** Azure DevOps Release Pipeline, Azure PowerShell Task (Task version 4.*, Azure Powershell version 3.1.0), PowerShell script using "azcopy cp".

When copying from one container to another, all files within the destination have a MIME type of "text/plain". This worked correctly in AzCopy version 10.6.0

**Comment by nakulkar-msft** [comment]
Fixed with change #1153 in 10.6.1

**Comment by vgrebenschikov** [comment]
Still works wrong if upload files with 'az storage copy'
