### ISSUE TITLE
Add MD5 check

### ISSUE THREAD

**Issue by AlexBlain** [Azure/azure-storage-azcopy#114]
/CheckMD5 is part of the v8.1 of Azcopy and help us to avoid data corruption when downloading very large file from Azure blob.
It would be great to have this feature added as part of this next Azcopy command line.

**Comment by zezha-msft** [comment]
@AlexBlain thanks for your patience!

MD5 support was just released in 10.0.8. Please don't hesitate if you have any question/concern.
