### ISSUE TITLE
azcopy fail to download files when another process are still copying files into the blobstore container

### ISSUE THREAD

**Issue by cometta** [Azure/azure-storage-azcopy#1145]
When a user A upload files to the blob storage container, another user B also run azcopy to download files from the containers to a local computer, azcopy just return fail. May I know is there any way to use az command to check whether there is another copying activity still in progress so that can skip azcopy at that particular time

**Comment by nakulkar-msft** [comment]
It is by design that azcopy downloads the file we enumerated. If the file happened to change between the time azcopy listed it file and actually attempts to download, the transfer shall fail. There is no workaround to this.
