### ISSUE TITLE
Cannot start job due to error: cannot scan the path \\?\C:\...

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/azure-storage-azcopy#1146]
### Which version of the AzCopy was used? 
10.6.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2019 V 1809 (Build 17763.1397)

### What command did you run?
$src = "C:\vstsagent\vsts-agent-win-x64-2.155.1\_work\172\s\azcopy_windows_amd64_10.6.0\dist"
$dest = "https://<account>.blob.core.windows.net/<container>"
.\azcopy copy $src $dest --recursive

### What problem was encountered?
failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\?\C:\vstsagent\vsts-agent-win-x64-2.155.1\_work\172\s\azcopy_windows_amd64_10.6.0\dist, please verify that it is a valid.

### How can we reproduce the problem in the simplest way?
Unclear - I experience on both of my Azure-located Windows build VMs when running build in Azure DevOps, I can't reproduce locally nor if I run it manually in Powershell on either VM.

### Have you found a mitigation/solution?
No.

### Other notes
There's an identical issue at https://github.com/Azure/azure-storage-azcopy/issues/870 but I didn't want to pollute the back and forth there with a "me too!". But to respond to some of the questions posed in that thread:

#### Different language settings on the box?
No, haven't changed from the defaults (using English - United States)

**Comment by nakulkar-msft** [comment]
@WhitWaldo Does this happen consistently? Can you post the logs here?

**Comment by WhitWaldo** [comment]
@nakulkar-msft Are you able to access histories from support tickets? I've got a long running ticket, 120081924004585, that was just closed which identified the issue present here. If not, I'd be happy to forward the summary your way.

**Comment by nakulkar-msft** [comment]
@WhitWaldo  Please forward the summary. I've my email on my profile. Thanks!

**Comment by mohsha-msft** [comment]
Closing the stale issue. If it persists, please reopen this thread again.
