### ISSUE TITLE
Batch add metadata

### ISSUE THREAD

**Issue by ReedOnly** [Azure/azure-storage-azcopy#1151]
### Which version of the AzCopy was used? 
10.4.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
`azcopy copy 'filestore' 'blobstore' --recursive --metadata project='123'`
I want to add metadata to all blobs which are similar for hundreds of thousands of files. Want a method to batch add metadata, either while copying to blob store, or afterwards.

### What problem was encountered?
`failed to parse user input due to error: metadata is not supported while copying from service to service`

### How can we reproduce the problem in the simplest way?
add metadata while copying from service to service

### Have you found a mitigation/solution?
No

**Comment by zachbugay** [comment]
I am also running into this issue. Is there any workaround, or resolution to this?

**Comment by nakulkar-msft** [comment]
Fixed in 10.16.0.
