### ISSUE TITLE
hide progress

### ISSUE THREAD

**Issue by cometta** [Azure/azure-storage-azcopy#1154]
Hello, may i know is there any flag i can use to hide 
0.0 %, 0 Done, 0 Failed, 2 Pending, 0 Skipped, 2 Total
0.0 %, 0 Done, 0 Failed, 2 Pending, 0 Skipped, 2 Total
0.0 %, 0 Done, 0 Failed, 2 Pending, 0 Skipped, 2 Total
and only show error on the console if there are 'failed' with error messages ?

**Comment by hho** [comment]
Possible duplicate of #534 ?

**Comment by nakulkar-msft** [comment]
Same as #534
