### ISSUE TITLE
AzCopy Sync Blob to Blob support

### ISSUE THREAD

**Issue by thomasmaurer** [Azure/azure-storage-azcopy#116]
##### Note: The version is visible when running AzCopy without any argument
10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What problem was encountered?
Azcopy sync now supports file system to blob, it should also support blob to blob sync.

**Comment by Kapanther** [comment]
@zezha-msft any news on blob to blob sync working? is this still an enhancement

**Comment by zezha-msft** [comment]
Hi @Kapanther, I'm currently working on a change that would enable us to add this functionality more easily. I'll update this thread once I have a better idea of the timeline.

**Comment by Kapanther** [comment]
@zezha-msft I see blob-blob support has been added in 10.0.9? If so i'll go test for you.

**Comment by zezha-msft** [comment]
Hi @Kapanther, not yet for sync, it's been added for `copy`, to transfer between accounts all types of blobs.

**Comment by JohnRusk** [comment]
BTW, if the changes to the source location are purely additive (i.e. new files added, but no updates to existing files) then as a workaround it should work to use copy with `--overwrite=false`.  I haven't done any tests focused on using this as an interim replacement for blob-to-blob sync, but I can't see any reason why it wouldn't work as long as you know for sure that files are only added (never updated).

**Comment by JohnRusk** [comment]
Blob to Blob sync was release in version 10.3.  See https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync
