### ISSUE TITLE
issue copying files with special characters

### ISSUE THREAD

**Issue by greendx** [Azure/azure-storage-azcopy#1161]
##### Note: The version is visible when running AzCopy without any argument
10.6.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 2016
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "F:\Data\path" "https://<storageaccountname>.blob.core.windows.net/<containername><SAS>" --recursive --block-blob-tier=archive
### What problem was encountered?
I am migrating multiple datasets that are ~2TB ~200K files each. Data was generated by a wide mix of end users using a mix of Mac and Windows clients and a wide mix of localized operating systems. I am seeing a small amounts of failures in some of my azcopy jobs and so far in all cases this is due to files or folders with special characters, or in one case a blank space between file name and "." before file extension. 
### How can we reproduce the problem in the simplest way?
I am able to reproduce the error when uploading any of those files to a container manually via the portal. If I rename the file removing special characters I am able to upload.
### Have you found a mitigation/solution?
This is why I am here. Looking for suggestions. Is this a known issue? Looking over an older issue seems like special character issue was supposed to have been resolved.

Here is an example of a special character that is failing: Ì

**Comment by franshaarman** [comment]
I'm having a similar issues.

C-202H01 RFG.txt

**Comment by HimavarshaReddyJ** [comment]
Facing similar issue . Azcopy cant handle '_' in file names. 
Example: DUMMY_REPORT
I tried to copy above file from Azure container to local by using command 
azcopy copy "https://.blob.core.windows.net/validation/*" "path/validation/"

validation folder just has one file DUMMY_REPORT.txt

**Comment by Hamza-Benm** [comment]
Same here , got the same issue when tried to copy a root network drive (Y:\) it became Y%3A

**Comment by Deon-Gits** [comment]
Hi, has this issue been mitigated? I tried using azcopy to transfer some files and files with special characters seemed to fail, i pulled a log and it shows 400 Bad Request

**Comment by mohsha-msft** [comment]
Hey @Deon-Gits ,

Thanks for reaching out!.

Can you share the name of the file you are trying to copy (along with the special characters)?
Can you also verify that the special character is allowed by the [blob storage naming convension](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata)

**Comment by Deon-Gits** [comment]
Hi @mohsha-msft 

Thanks for your reponse. The filenames have special characters like **_"Ãngel CaldÃ"_**. I'm aware it does not fit under the blob storage naming convension. I'm just trying to confirm if there's a workaround, i have lots of files that need to be transferred using AZcopy.

**Comment by mohsha-msft** [comment]
Hey @Deon-Gits ,

AzCopy doesn't alter the name of the files we get from source. You'll have to manually alter the names before submitting the job. Please reach out for more clarifications.
