### ISSUE TITLE
Default detection of type vhd/vhdx is based on extension

### ISSUE THREAD

**Issue by chaitanyalala** [Azure/azure-storage-azcopy#1163]
### Which version of the AzCopy was used? 
Latest top of tree
##### Note: The version is visible when running AzCopy without any argument
Yes

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?

Azcopy copy file sas-uri

### What problem was encountered?

The "file" did not end in vhd/vhdx but was a vhd infact. The code seems to look for extension vhd/vhdx to determine to upload as a page blob vs block blob by default. This is not the right approach. Ideally, the check should be based on reading the file header/footer to determine file type and then use page be block blob during upload.

### How can we reproduce the problem in the simplest way?

Create a vhd file on local fs without vhd extension and upload it to a uri without defining --blobtype flag. It will be uploaded as a block blob vs page blob

### Have you found a mitigation/solution?
Yes. Pass blob type flag instead of letting the azcopy code determine

**Comment by mohsha-msft** [comment]
Hey @chaitanyalala 

Thanks for reaching out!
We try to determine the content type of file first based on the extension of that file and then on the basis of content of the file. 
- To determine content-type header based on file extension of the file, we use standard function of Golang's `filepath` package : [Ext](https://golang.org/pkg/path/filepath/#Ext)
- To determine content-type header based on content of the file, we use standard function of Golang's `http` package : [DetectContentType](https://golang.org/pkg/net/http/#DetectContentType) 

To understand more on how the flow works, please check [here](https://github.com/Azure/azure-storage-azcopy/blob/2c30af330b681d3a1f31db32e11245eafce9c5c3/ste/mgr-JobPartMgr.go#L596) to get more insight. As you mentioned, you can pass blob-type flag to determine the content too.

Please reach out if you want more clarity on the topic or if you have some suggests. 😄

**Comment by PC-Bjorn** [comment]
I know this is an old thread, but I just had an issue with this auto detection when trying to archive a 9 TB vhdx file in an Azure blob. Well, this breaks the 8 TB ceiling for page blobs. I couldn't find any arguments to force AzCopy to treat it as a block blob, but renaming the extension to BAK luckily allowed me to upload the file. So I'm glad AzCopy did not force a page blob by reading the contents of the file. A command line argument to force a block blob would be welcome!
