### ISSUE TITLE
Access is denied error - running AzCopy in Azure function App Service Plan

### ISSUE THREAD

**Issue by rjosephp** [Azure/azure-storage-azcopy#1169]
**Which version of the AzCopy was used?** 
AzCopy 10.6.0

**Which platform are you using? (ex: Windows, Mac, Linux)**
Windows (Azure function App Service Plan), .NET Core 3.1, HttpTrigger, Language: C#

**What command did you run?**
`azcopy sync "https://sourceStorageAccount.blob.core.windows.net/container1?sv=2019-12-12&st=2020-09-04T13%3A41%3A01Z&se=2020-09-04T14%3A41%3A01Z&sr=c&sp=rl&sig=T6kFVs%3D" "https://destinationStorageAccount.blob.core.windows.net/container1?sv=2019-12-12&st=2020-09-04T13%3A41%3A02Z&se=2020-09-04T14%3A41%3A02Z&sr=c&sp=racwdxlt&%3D" --recursive --delete-destination true`

**What problem was encountered?**

_Initial error:_
```
panic: mkdir : The system cannot find the path specified.
goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/common.PanicIfErr(...)
	/home/vsts/work/1/s/common/lifecyleMgr.go:553
main.main()
	/home/vsts/work/1/s/main.go:55 +0x562

```
This error went away after adding the environment variable "AZCOPY_LOG_LOCATION" to "D:\home\site\wwwroot\AzCopy\". **_ However, the current issue is:_**

```
panic: mkdir plans: Access is denied.

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/common.PanicIfErr(...)
	/home/vsts/work/1/s/common/lifecyleMgr.go:553
main.main()
	/home/vsts/work/1/s/main.go:64 +0x554
```

**How can we reproduce the problem in the simplest way?**
Create an Azure Function app with the below configuration:

1. Publish: Code
2. Runtime stack: .NET Core
3. Version: 3.1
4. Region: West Europe
5. Operating System: Windows
6. Plan Type: App service Plan
7. Function Type: HttpTrigger
8. Language: C#
9. Include the AzCopy.exe in the Visual Studio project, in the folder "AzCopy" in the project.
10. AzCopy.exe properties: Copy To Output Directory -> Copy Always
11. Add the code to invoke azcopy sync, as mentioned in the command mentioned above
12. Publish the Function
13. Add Application Setting: AZCOPY_LOG_LOCATION, value: D:\home\site\wwwroot\AzCopy\
14. Call the Function URL get endpoint

**Have you found a mitigation/solution?**
No

**Comment by DanijelaKraljevic** [comment]
Hi @rjosephp . I had similar issue on Ubuntu after changing the AZCOPY_JOB_PLAN_LOCATION variable. Solved it by assigning the same value to AZCOPY_LOG_LOCATION variable. Seems like you have problem with job plan writing, so if you still haven't solved it maybe you could change the value of AZCOPY_JOB_PLAN_LOCATION var and give it a try.
Default for both is %USERPROFILE%\.azcopy, I haven't looked into the copy command much but it looks like both variables need to have same value in order for command to work properly.

**Comment by mohsha-msft** [comment]
Hey @rjosephp ,

Thanks for reaching out!
As @DanijelaKraljevic mentioned, the default location for `AZCOPY_JOB_PLAN_LOCATION` and `AZCOPY_LOG_LOCATION` is `%USERPROFILE%` which fails sometime in Azure function apps because of permission to write to this location. Please try with some other location. Also please double check the source path once.

Please reach out for more clarification.

**Comment by rkapoor028** [comment]
This helped! Thanks would be useful to have it documented.

**Comment by atul-ram** [comment]
++ following.

how can we make the job files, readable by all
