### ISSUE TITLE
Support ls for ADLS Gen2

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-azcopy#117]
azcopyV10-win.exe ls https://myadlsgen2.dfs.core.windows.net/test

invalid path passed for listing. given source is of type 5 while expect is container / container path

**Comment by zezha-msft** [comment]
The error needs to be fixed too, it seems to be printing the enum directly without converting it to string.

**Comment by zezha-msft** [comment]
Hi @r-kolbovich, thanks for reaching out!

I'll discuss with the Team to see if we can increase the priority on this item.

FYI Storage Explorer uses AzCopy to transfer data to ADLSGen2, but uses the newest Node.js SDK to do the other tasks.

**Comment by r-kolbovich** [comment]
@zezha-msft thanks for quick answer! Hope this will be fixed soon :)

**Comment by jamesnewsome** [comment]
Just posting so that I keep track of the activity around this issue.

**Comment by huaxiawang** [comment]
Azcopy 10.1.2 on Mac also has the same issue.

**Comment by ediazrod** [comment]
Same issue here, It will be great have a command line alternative to use Datalake gen2

**Comment by JohnRusk** [comment]
Related to #692

**Comment by JohnRusk** [comment]
This feature was released today in version 10.3.3.
