### ISSUE TITLE
Ensure azcopy sync can accurately resume and validate operations

### ISSUE THREAD

**Issue by anjackson** [Azure/azure-storage-azcopy#1171]
##### Note: The version is visible when running AzCopy without any argument
10.6.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

```
azcopy sync http://blobs/ .
```

### What problem was encountered?

Interrupted/damaged downloads are not repaired when `sync` is re-run.  Even if the files are not the same length, the sync does nothing.

Ideally, I would like a `--verify` flag for `azcopy sync` that would not only check the length but also re-check the MD5 for all items in the set.  This would make `azcopy sync` consistent across re-runs and makes it possible to validate downloads/uploads.

### How can we reproduce the problem in the simplest way?

Download some files, then truncate a file to zero bytes in length.

### Have you found a mitigation/solution?

Run long (too long to monitor manually) downloads twice, check results are identical.

**Comment by amishra-dev** [comment]
having MD5 in the blob is optional, so if there is no MD5 stored in the blob we will be downloading the entire blob to check MD5. 
Based on this, at this point we cannot accept this request.

**Comment by kieranjol** [comment]
Hi, what about checking for file length as mentioned in the original post?
