### ISSUE TITLE
How to append data to append blobs

### ISSUE THREAD

**Issue by hongooi73** [Azure/azure-storage-azcopy#1172]
### Which version of the AzCopy was used? 

10.3.3

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

```
azcopy copy <localsrc> <remotedest> --blob-type AppendBlob
```

### What problem was encountered?

This is probably a really dumb question, but how do you actually append data to an append blob? The above command will create a new blob each time. I also couldn't find any references to appending in the docs; I thought it would be a simple `--append` flag but that didn't work.

### How can we reproduce the problem in the simplest way?

Running the above command does not append the uploaded data when \<remotedest\> exists.

### Have you found a mitigation/solution?

Call the REST API directly or via my R package.

**Comment by mohsha-msft** [comment]
Hey @hongooi73 

Thanks for reaching out!
As for your query, AzCopy is a copying tool and we do not support appending data to an existing append blob. 

You can however use Azure SDKs to achieve the desired results. Please find the sample [here](https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zt_url_append_blob_test.go#L16) of Go Blob SDK.

Please feel free to reach out for more clarity. 😄
