### ISSUE TITLE
Azcopy failed with error "github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:154 HTTP request failed" after some jobs are completed.

### ISSUE THREAD

**Issue by Icybiubiubiu** [Azure/azure-storage-azcopy#1173]
##### Note: The version is visible when running AzCopy without any argument
AzcopyVersion  10.5.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 2016
### What command did you run?

Job-Command copy D:\SQL_Backups\CNNANP1SQLSMS https://zcne2prdsqlbackup.blob.core.chinacloudapi.cn/cnnanp1sqlsms/?se=2SAS-Token --recursive=true --overwrite false --cap-mbps 30 

### What problem was encountered?
1. run the azcopy cmd in powershell script with windows scheduler 
2. I can see some of the 2007 files are uploaded successfully but failed at 59th.
![image](https://user-images.githubusercontent.com/61815812/92448707-96edd900-f1eb-11ea-84d4-ccbadb2c1de7.png)

### How can we reproduce the problem in the simplest way?
using ps1 script on a windows server

### Have you found a mitigation/solution?
NA

**Comment by Icybiubiubiu** [comment]
add some logs :
2020/09/08 05:08:45 ==> REQUEST/RESPONSE (Try=1/2m8.2222506s[SLOW >3s], OpTime=2m8.2222506s) -- REQUEST ERROR
   PUT https://zcne2prdsqlbackup.blob.core.chinacloudapi.cn/cnnanp1sqlsms/CNNANP1SQLSMS/CNNANP1SQLSMS_SMS_CNSMS_SQLNative_TLog_20200908022816300.BAK?blockid=mgiynwq4zdytmtuwmy1hmzq1ltqwm2utotflnmnjzjzhymy1&comp=block&se=2021-12-31t09%3A47%3A30z&sig=-REDACTED-&sp=rwdlac&spr=https%2Chttp&srt=sco&ss=b&st=2020-08-17t01%3A47%3A30z&sv=2019-10-10&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.5.1 Azure-Storage/0.10 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [5c29c29f-0894-46b3-4858-b91444e46a91]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:154
HTTP request failed

Put https://zcne2prdsqlbackup.blob.core.chinacloudapi.cn/cnnanp1sqlsms/CNNANP1SQLSMS/CNNANP1SQLSMS_SMS_CNSMS_SQLNative_TLog_20200908022816300.BAK?blockid=MGIyNWQ4ZDYtMTUwMy1hMzQ1LTQwM2UtOTFlNmNjZjZhYmY1&comp=block&se=2021-12-31T09%3A47%3A30Z&sig=-REDACTED-&sp=rwdlac&spr=https%2Chttp&srt=sco&ss=b&st=2020-08-17T01%3A47%3A30Z&sv=2019-10-10&timeout=901: read tcp 10.68.138.235:58440->40.73.81.132:443: wsarecv: An existing connection was forcibly closed by the remote host.

goroutine 535 [running]:

**Comment by amishra-dev** [comment]
Looks like you hit a network error, are you seeing this repeatedly?

**Comment by Satyajeet331** [comment]
2021/01/29 04:04:06 INFO: [P#0-T#0] Page blob throughput tuner: Target Mbps 98705
2021/01/29 04:04:06 ==> REQUEST/RESPONSE (Try=1/317.6409ms, OpTime=371.6403ms) -- REQUEST ERROR
   PUT https://zneusu5p42ssbak.blob.core.windows.net/bakunetworkdatacopy/strbaku01_vhdx2.vhdx?*********************************=2019-12-12&timeout=901
   Content-Length: [4194304]
   User-Agent: [AzCopy/10.8.0 Azure-Storage/0.10 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [d3627668-98c9-4435-42e6-ea36ae005365]
   X-Ms-Page-Write: [update]
   X-Ms-Range: [bytes=248898387968-248902582271]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed
-----

My jobs are getting failed with above errror, above 

azcopy copy "Z:\VHDXs\strbaku01_vhdx011.vhdx" "https://zneusu5p42ssbak.blob.core.windows.net/bakunetworkdatacopy?sp*************************************" --recursive=true --cap-mbps 150

**Comment by prawalgangwar** [comment]
Any update on this ?

**Comment by mohsha-msft** [comment]
@Icybiubiubiu @Satyajeet331 @prawalgangwar 

Can you share the logs with us to investigate further? It would be super nice if you use `--log-level=DEBUG` for this. Also try if `--blob-type=PageBlob` helps

**Comment by amsword** [comment]
Seeing the same issue here. Any walk-around?

**Comment by ericthomas1** [comment]
@amsword, in my case, the machine making the call was found to be offline. Would be great if the logs made this more evident.

**Comment by amsword** [comment]
> @amsword, in my case, the machine making the call was found to be offline. Would be great if the logs made this more evident.

do you mean the machine lost the internet access? on my side, it is accessible.

**Comment by prawalgangwar** [comment]
as far as I remember, it worked for me by limiting the number of threads Azcopy would create to upload. There was some environment variable that needs to be set to accomplish that `export AZCOPY_CONCURRENCY_VALUE=<number of threads>` or even try the NC option.

**Comment by mohsha-msft** [comment]
Hey @Icybiubiubiu ,

This is a standard error which can because of network constraint. Try to limit the number of goroutines we spawn by following @prawalgangwar's advice.

> as far as I remember, it worked for me by limiting the number of threads Azcopy would create to upload. There was some environment variable that needs to be set to accomplish that `export AZCOPY_CONCURRENCY_VALUE=<number of threads>` or even try the NC option.


If  the issue still persists, please reach out and open the issue again.
