### ISSUE TITLE
Copying a symlinked folder doesn't work as expected

### ISSUE THREAD

**Issue by wwlorey** [Azure/azure-storage-azcopy#1174]
### Which version of the AzCopy was used? 
AzCopy 10.5.1 

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac

### What command did you run?
```
azcopy cp "path/to/symlink" "https://wwl1.blob.core.windows.net/blobs098a/?<sas token>" --recursive --follow-symlinks
```

### What problem was encountered?
Instead of uploading the folder pointed to by the symlink, the symlink file itself was uploaded. I'm not sure if this is by design but I expected the folder to be uploaded.

### How can we reproduce the problem in the simplest way?
Copy a symlinked folder to a blob container.

### Have you found a mitigation/solution?
N/A

**Comment by amishra-dev** [comment]
@adreed-msft to investigate.
