### ISSUE TITLE
Switch to suppress version check

### ISSUE THREAD

**Issue by RowdyChildren** [Azure/azure-storage-azcopy#1175]
We run AzCopy in locked down environments and running it with the version check introduces errors into the system event logs on windows. It would be nice if there was a switch to suppress the version check.

**Comment by mohsha-msft** [comment]
Hey @RowdyChildren ,

Thanks for reaching out!

There is currently no way to disable version check in AzCopy. We, however, now support disabling logging in Syslog or Windows Event Logger by using environment variable `AZCOPY_DISABLE_SYSLOG`.  By default we log to these channels. However, to reduce the noise in Syslog/Windows Event Log, consider setting this environment variable to true. I suggest you try that. 
We're also working on improving the check time a bit. Please reach out for any concerns or clarity on the matter.
