### ISSUE TITLE
Dificult to use Azcopy version 10.6.0 

### ISSUE THREAD

**Issue by borgesrsbr** [Azure/azure-storage-azcopy#1180]
### Which version of the AzCopy was used? 
azcopy version 10.6.0
 

### Which platform are you using? (ex: Windows, Mac, Linux)
windows server

### What command did you run?
 azcopy cp E:\BACKUP_LOCAL_TEMP\bkp01.bak	   https://blablabla.blob.core.windows.net/bkp01.bak	 set AZCOPY_BUFFER_GB=1	

### What problem was encountered?
I need in this version use a command that limit the memory usage.

### How can we reproduce the problem in the simplest way?
I don't know because the argument AZCOPY_BUFFER_GB don't works in our version.
### Have you found a mitigation/solution?
yes, send for the moment using blob storage web azure portal.

**Comment by amishra-dev** [comment]
@borgesrsbr the way you have typed the command out is incorrect. You need to set the AZCOPY_BUFFER_GB as an environment variable in your shell (command prompt), it is not a parameter into azcopy (that is what i can see from the command line you provided)

**Comment by borgesrsbr** [comment]
ok Amishra then the correct way its ...

first
AZCOPY_BUFFER_GB=1
and after this
azcopy cp E:\BACKUP_LOCAL_TEMP\bkp01.bak https://blablabla.blob.core.windows.net/bkp01.bak 

?

**Comment by amishra-dev** [comment]
since you are on windows
```
set AZCOPY_BUFFER_GB=1 
```
and then the azcopy command

**Comment by borgesrsbr** [comment]
thanks dude.

**Comment by amishra-dev** [comment]
@borgesrsbr it worked I presume :)

**Comment by borgesrsbr** [comment]
yes broder, 

but I am impressed by the difficulty in the documentation to quote these simple things from version to version.
