### ISSUE TITLE
Customer is reporting azcopy login --identity + azcopy sync is not working in Redhat 7.6 and azcopy v10.6

### ISSUE THREAD

**Issue by amishra-dev** [Azure/azure-storage-azcopy#1189]
### Which version of the AzCopy was used? 
10.6
### Which platform are you using? (ex: Windows, Mac, Linux)
Redhat Linux 7.6

### What command did you run?
usr/local/bin/azcopy login --identity  &&

/usr/local/bin/azcopy sync https://$storageaccount.blob.core.windows.net/$containername/images/ /efs/customer_data/images/ --recursive=true --delete-destination=true

### What problem was encountered?
Azcopy sent a request to azure storage without a token in the header

### Have you found a mitigation/solution?
Downgrading to azcopy 10.3.1

**Comment by nakulkar-msft** [comment]
Fixed with change #1194, in release 10.6.1
