### ISSUE TITLE
AzCopy failing in on premise virtual machine but working on local system

### ISSUE THREAD

**Issue by stellajoe** [Azure/azure-storage-azcopy#1201]
### Which version of the AzCopy was used? 
10.6.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2012 R2 

### What command did you run?
azcopy sync "F:\test" "https://xxxxxx.blob.core.windows.net/xxxxx?xxxxxxxxxxxxxxxxxxxxxxx" --recursive=true  --cap-mbps 30

### What problem was encountered?
The same command is working from local system but not from a on premise server.

 ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Put https://xxxxxx.blob.core.windows.net/xxxx/test/test.csv?si=policy&sig=-REDACTED-&sr=c&sv=2019-10-10&timeout=901: dial tcp 20.150.20.132:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

goroutine 127 [running]:
github.com/Azure/azure-storage-azcopy/ste.stack(0xc0000af3b0, 0xc001042000, 0x0)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:232 +0xa4
github.com/Azure/azure-storage-azcopy/ste.NewRequestLogPolicyFactory.func1.1(0xd88de0, 0xc00004d4a0, 0xc001042400, 0x10, 0x6, 0x0, 0xc0000c6990)

### Have you found a mitigation/solution?
No

### How can we reproduce the problem in the simplest way?
  run the below command:
azcopy sync "F:\test" "https://xxxxxx.blob.core.windows.net/xxxxx?xxxxxxxxxxxxxxxxxxxxxxx" --recursive=true  --cap-mbps 30

**Comment by stellajoe** [comment]
Also as mentioned on https://github.com/Azure/azure-storage-azcopy/issues/784, ran the PowerShell command to test basic internet connectivity from the VM and got the following response :

`[System.Net.WebRequest]::Create("http://azcopyvnextrelease.blob.core.windows.net/releasemetadata/latest_version.txt").GetResponse().StatusCode`

Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
At line:1 char:130

.GetResponse <<<< ().StatusCode
CategoryInfo : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : DotNetMethodException


Can you please advise?

**Comment by nakulkar-msft** [comment]
@stellajoe The VM cannot connect to the network. Can you check your vm once again?
