### ISSUE TITLE
azcopy login failing

### ISSUE THREAD

**Issue by HunterGarza** [Azure/azure-storage-azcopy#1202]
##### Note: The version is visible when running AzCopy without any argument
 azcopy version 10.6.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy login
### What problem was encountered?
Failed to perform login command:
failed to login with tenantID "common", Azure directory endpoint "https://login.microsoftonline.com", autorest/adal/devicetoken: -REDACTED- occurred while sending request for Device Authorization Code: Post https://login.microsoftonline.com/common/oauth2/devicecode?api-version=1.0: dial tcp: lookup login.microsoftonline.com: getaddrinfow: A non-recoverable error occurred during a database lookup.
### How can we reproduce the problem in the simplest way?
Run: azcopy login in a normal PowerShell window
### Have you found a mitigation/solution?
I have not found a solution for running this command on my machine. When I run the same command on one of our Windows Servers, it works as expected. I have tried adding the tenant id, but that did not work either, and threw the same error.

**Comment by mohsha-msft** [comment]
@HunterGarza , 

Thanks for reaching out!
For the first look, it seems that the value of environment variable TENANT_ID is set incorrectly. Can you please check that once? Incorrect tenant id can lead to error "A non-recoverable error occurred during a database lookup."
One convenient way to get tenant id by logging on to your Azure Portal and navigating to Azure Active Directory. In the overview tab, you'll see your tenant information.
To learn more, check [this](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-whatis) and [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-create-new-tenant)
For more clarity, please don't hesitate to reach out to us.
