### ISSUE TITLE
Only the first instance of AZCopy running on a single Windows is consuming all resources

### ISSUE THREAD

**Issue by SamuelNeves** [Azure/azure-storage-azcopy#1206]
### Which version of the AzCopy was used? 
10.6

### Which platform are you using?
 Windows Server Datacenter 2016

### What command did you run?
Default copy commands

### What problem was encountered?
Due to the need to download files from different storage accounts at the same time. We need to start 2 instances of azcopy at the same time via cmd in windows. However, it seems that only the first instance executed consumes most of the resources. In our test the first instance consumed 2 GB of Ram and the second one consumed only 10Mb. Is it possible to balance the execution of different instances of AZCopy running at the same time through the same executable file?

### How can we reproduce the problem in the simplest way?
Execute two copy tasks  at the same time.

### Have you found a mitigation/solution? 
No

**Comment by zezha-msft** [comment]
Hi @SamuelNeves, please give the `AZCOPY_BUFFER_GB` a try, and see if that helps. More information is available with `azcopy env`.

Please let us know if it doesn't solve the problem.
