### ISSUE TITLE
invalid memory address

### ISSUE THREAD

**Issue by fdlsnyder2** [Azure/azure-storage-azcopy#1208]
### Which version of the AzCopy was used? 
10.6.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows10

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
D:\LargeData\azcopy_10.6.0\azcopy_windows_amd64 list https://sameranalyticsg2prodncus.dfs.core.windows.net/Folder/2020-10-01_09-04-45 --machine-readable
### What problem was encountered?
Other folders are able to list the file contents fine but one throws the following error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa8bf9a]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/cmd.(*blobFSTraverser).traverse(0xc000230080, 0x0, 0xc000004fe0, 0x0, 0x0, 0x0, 0x5, 0xc000067550)
	/home/vsts/work/1/s/cmd/zc_traverser_blobfs.go:172 +0x98a
github.com/Azure/azure-storage-azcopy/cmd.HandleListContainerCommand(0xc0000b0100, 0x74, 0xd67605, 0xb18a00, 0xc000067540)
	/home/vsts/work/1/s/cmd/list.go:159 +0x455
github.com/Azure/azure-storage-azcopy/cmd.init.11.func2(0xc0001fd180, 0xc000004160, 0x1, 0x2)
	/home/vsts/work/1/s/cmd/list.go:65 +0x79
github.com/spf13/cobra.(*Command).execute(0xc0001fd180, 0xc0000040c0, 0x2, 0x2, 0xc0001fd180, 0xc0000040c0)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x128f800, 0xc0000948c0, 0xc000149dc8, 0x40d06f)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2f1
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc00007cf60, 0x19, 0xc00007cf60, 0x19, 0xc00007cfa0, 0x1f, 0x7fffffff)
	/home/vsts/work/1/s/cmd/root.go:140 +0xd6
main.main()
	/home/vsts/work/1/s/main.go:82 +0x3cb

I have been able to download the entire contents of the folder without problem but am unable to list the contents.

### How can we reproduce the problem in the simplest way?  
Unknown.  It is being run against a folder with proprietary data that can not be shared.

**Comment by dciborow** [comment]
Also seeing this...
Using Ubuntu 20 on Windows 11 with WSL.

![image](https://user-images.githubusercontent.com/9027725/141848732-d8229384-3f45-4997-9b9a-3acc476adfec.png)


Seems like the encoding in my URLs is upsetting something...

**Comment by tasherif-msft** [comment]
Hi @fdlsnyder2 sorry for the late response. Are you still experiencing this issue?
If so, are the other dirs named similar to the one that's not listing correctly?

**Comment by tasherif-msft** [comment]
Hi @fdlsnyder2 I was not able to repro this in the latest releases. I will proceed to close this issue. Feel free to reopen if you're still experiencing the problem.
