### ISSUE TITLE
azcopy sync - continue on error

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-storage-azcopy#1213]
### Which version of the AzCopy was used? 
10.6.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (Azure Cloud Shell)

### What command did you run?
I`m trying to sync 2 Azure File Shares using the following syntax:
azcopy sync "https://[account].file.core.windows.net/[share]/[path/to/dir]?[SAS]" "https://[account].file.core.windows.net/[share]/[path/to/dir]" --recursive=true

### What problem was encountered?
It worked fine for a smaller file share, but on a larger one it starts processing a few thousand files before it hits this error:

2690 Files Scanned at Source, 10561 Files Scanned at Destination, 2-sec Throughput (Mb/s): 196.6596
Cannot perform sync due to error: -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=ResourceNotFound) =====
Description=404 The specified resource does not exist., Details: (none)
   HEAD https://devqtacdy.file.core.windows.net/data/temporaryfiles/srv/922308040/-99993/082494e4-c500-43d1-9aac-1cf837fd8d30.PDF?se=2021-10-01t04%3A03%3A27z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2020-10-15t20%3A03%3A27z&sv=2019-12-12&timeout=901

Each time the command is re-run it seems to fail on a different file name, so I suppose this is because it is being used by an application which frequently updates the content of the file share.

Is it possible to have azcopy continue on error, and instead just log the problematic files?

### How can we reproduce the problem in the simplest way?

Probably by deleting a file on the source quickly after the below command has been triggered:
azcopy sync "https://[account].file.core.windows.net/[share]/[path/to/dir]?[SAS]" "https://[account].file.core.windows.net/[share]/[path/to/dir]" --recursive=true

### Have you found a mitigation/solution?

No

**Comment by amishra-dev** [comment]
Unfortunately not. We expect the source and destination to not change while sync is in progress.
