### ISSUE TITLE
AzCopy thinks a blob snapshot and its base are the same location

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#1216]
### Which version of the AzCopy was used? 
10.6.0

### Which platform are you using?
macOS

### What command did you run?
copy

### What problem was encountered?
Set the src to be a blob snapshot, dst to be its base. Run copy.

### How can we reproduce the problem in the simplest way?
./azcopy copy "https://**acct**.blob.core.windows.net/container/**filename**?sv=2019-12-12&se=2020-11-18T21%3A10%3A28Z&sr=c&sp=rl&sig=redacted&**snapshot=2020-10-19T21%3A05%3A50.1136138Z**" "https://easybugs110.blob.core.windows.net/container/**filename**?sv=2019-12-12&se=2020-11-18T21%3A10%3A28Z&sr=c&sp=rwl&sig=redacted" --overwrite=true --s2s-preserve-access-tier=false --recursive;

### Have you found a mitigation/solution?
Nope.

**Comment by nakulkar-msft** [comment]
[10.7.0](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.7.0) released
