### ISSUE TITLE
AzCopy v10.3.4 issue since last night while coping files to Azure from On premise servers

### ISSUE THREAD

**Issue by jiteshkumargouthamchand** [Azure/azure-storage-azcopy#1224]
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
$azPath = "D:\AzCopyv10\azcopy_windows_amd64_10.3.4"
Set-Location $azPath
$source="https://samdevcvx.blob.core.windows.net/sam"
$sourcekey="<SASToken>"
$source +"/"+ $sourcekey 

$result =.\azcopy  copy  "https://samdevcvx.blob.core.windows.net/sam/?<SASToken>"  "D:\SAMTest\Data"  --log-level="ERROR" --recursive=true --output-type json 

$psdata =  $result | ConvertFrom-Json
$psdata.MessageContent

### What problem was encountered? This has been working since Jan but all of sudden since last night it has been failing. 
The description for Event ID 0 from source D:\AzCopyv10\azcopy_windows_amd64_10.3.4\azcopy.exe cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

==> REQUEST/RESPONSE (Try=4/21.0021967s[SLOW >3s], OpTime=1m33.5573591s) -- REQUEST ERROR
   GET https://samdevcvx.blob.core.windows.net/sam?restype=container&tRedacted
   User-Agent: [Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [a6afdd0f-21d6-4da7-58c2-f756b4394e2b]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Get https://samdevcvx.blob.core.windows.net/sam?restype=container&+=%3D&timeout=901: proxyconnect tcp: dial tcp 146.46.130.168:8080: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

goroutine 1 [running]:
github.com/Azure/azure-storage-blob-go/azblob.stack(0xc0002022d0, 0xc0007a0100, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_policy_request_log.go:146 +0xa4
github.com/Azure/azure-storage-blob-go/azblob.NewRequestLogPolicyFactory.func1.1(0xcf0fa0, 0xc0003bc120, 0xc0007a0100, 0x11aebc0, 0xcf0fa0, 0xc0003bc120, 0xc000058df0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_policy_request_log.go:96 +0x657
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0001460f0, 0xcf0fa0, 0xc0003bc120, 0xc0007a0100, 0xc0003bc120, 0xc000058df0, 0x4, 0x16f6dbc00)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewRetryPolicyFactory.func1.1(0xcf0fe0, 0xc0000dd1a0, 0xc0001e2400, 0x10, 0xab49c0, 0x64492d747301, 0xc0000c46e0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_policy_retry.go:204 +0x673
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000146140, 0xcf0fe0, 0xc0000dd1a0, 0xc0001e2400, 0xc0000c4798, 0x30, 0x28, 0x8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0xcf0fe0, 0xc0000dd1a0, 0xc0001e2400, 0x10, 0xab49c0, 0x40d001, 0xc0000c46e0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_policy_unique_request_id.go:19 +0xb5
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0000052e0, 0xcf0fe0, 0xc0000dd1a0, 0xc0001e2400, 0xc0000c4780, 0x26, 0xc00001a6c0, 0xc0004af178)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0xcf0fe0, 0xc0000dd1a0, 0xc0001e2400, 0x1, 0x0, 0x1, 0xc0001f43f8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_policy_telemetry.go:34 +0x164
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0000dd620, 0xcf0fe0, 0xc0000dd1a0, 0xc0001e2400, 0xc0000dd620, 0xbaee43, 0xc0004af248, 0x40d06f)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc0007c0040, 0xcf0fe0, 0xc0000dd1a0, 0xce2b00, 0xc0001dc000, 0xc0001e2400, 0x1f, 0xc000498338, 0x4, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:129 +0x88
github.com/Azure/azure-storage-blob-go/azblob.containerClient.GetProperties(0xc0000a4120, 0x5, 0x0, 0x0, 0x0, 0xc0000a4128, 0x1f, 0xc000498338, 0x4, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zz_generated_container.go:516 +0x35c
github.com/Azure/azure-storage-blob-go/azblob.ContainerURL.GetProperties(0xc0000a4120, 0x5, 0x0, 0x0, 0x0, 0xc0000a4128, 0x1f, 0xc000498338, 0x4, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/url_container.go:103 +0xca
github.com/Azure/azure-storage-azcopy/cmd.getBlobCredentialType.func1(0xc0000a4100)
	/home/vsts/work/1/s/cmd/credentialUtil.go:123 +0x406
github.com/Azure/azure-storage-azcopy/cmd.getBlobCredentialType(0xcf0fe0, 0xc0000dd1a0, 0xc0000a4120, 0x84, 0xc0004b0001, 0x504b1f, 0xb4e180, 0xc0000dd1a0)
	/home/vsts/work/1/s/cmd/credentialUtil.go:138 +0x270
github.com/Azure/azure-storage-azcopy/cmd.getCredentialType(0xcf0fe0, 0xc0000dd1a0, 0x301, 0xc0000a4120, 0x84, 0xc0000700d0, 0xf, 0x0, 0x0, 0x0, ...)
	/home/vsts/work/1/s/cmd/credentialUtil.go:332 +0x16d
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc000494380, 0x0, 0x0)
	/home/vsts/work/1/s/cmd/copy.go:862 +0x1d6
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc000494380, 0xd1, 0xb)
	/home/vsts/work/1/s/cmd/copy.go:766 +0x8b
github.com/Azure/azure-storage-azcopy/cmd.init.2.func2(0xc0001e1900, 0xc0000d9e60, 0x2, 0x6)
	/home/vsts/work/1/s/cmd/copy.go:1348 +0x19d
github.com/spf13/cobra.(*Command).execute(0xc0001e1900, 0xc0000d9da0, 0x6, 0x6, 0xc0001e1900, 0xc0000d9da0)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x11a8040, 0xc000098450, 0xc000149dc8, 0x40d06f)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2f1
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc0000983c0, 0x22, 0xc00006eec0, 0x18, 0xc00006eee0, 0x16, 0x7fffffff)
	/home/vsts/work/1/s/cmd/root.go:110 +0xd6
main.main()
	/home/vsts/work/1/s/main.go:82 +0x3cb

### How can we reproduce the problem in the simplest way?
Simple copy since last night is not working from a Windows sevrer. Works from local machine but not from WIndows server 2012 R2.
### Have you found a mitigation/solution?
NO

**Comment by jiteshkumargouthamchand** [comment]
@JohnRusk @zezha-msft  Request your help pn this urgently. Since last night all AzCopy services havebeen fialing for us.

**Comment by zezha-msft** [comment]
Synced offline. Network issue.
