### ISSUE TITLE
copy ORC files from ADLS Gen2 to Azure Blob Store

### ISSUE THREAD

**Issue by blueRegen** [Azure/azure-storage-azcopy#1229]
Hi

I want to copy a bunch of ORC partitioned files (about 700 of them) from ADLS Gen 2 to Azure Blob.
Is it not possible? Is it too complex?

I see information how to copy from blob to adls2 but not the other way.

ADSL Gen2 to Azure Blob.

Any help??

thanks.

**Comment by nakulkar-msft** [comment]
@blueRegen You can copy between ADLS Gen2 to Blob as if it were between two blobservices. 
azcopy copy hptts://<Gen2 source account>.**blob.**core.windows.net/<container/<SAS> https://<Blob destination acc>.blob.core.windows.net/<container>/<SAS>
