### ISSUE TITLE
Did azcopy support on Openwrt(Linux)?

### ISSUE THREAD

**Issue by johnpaladin** [Azure/azure-storage-azcopy#123]
### Which version of the AzCopy was used? 
I followed the Azcopy on linux instruction, I think the version is v7.2.
### Which platform are you using? (ex: Windows, Mac, Linux)
Openwrt(Linux) chaos_calmer/15.05.1
### What command did you run?
./Azcopy --help
### What problem was encountered? 
(It seems not working)
root@DPD3N:/tmp/azcopy# ./azcopy --help
./azcopy: line 2: syntax error: bad function name

### How can we reproduce the problem in the simplest way?
1.Install a openwrt on VM. ([https://oldwiki.archive.openwrt.org/doc/howto/virtualbox](https://oldwiki.archive.openwrt.org/doc/howto/virtualbox))
2.And try to install the azcopy or extract the tar file. 
3.Execute ./azcopy --help.
### Have you found a mitigation/solution?
no... 
If the openwrt not support upload file to azure blob, I'm consider set up a FTP server on Azure vm(Openwrt can support FTP).

**Comment by seguler** [comment]
Are you running OpenWRT on a 32 bit machine ? AzCopy is currently only supported on 64 bit.

**Comment by zezha-msft** [comment]
Closing for now due to lack of response.
