### ISSUE TITLE
Panic runtime error: invalid memory address or nil pointer deference

### ISSUE THREAD

**Issue by erkingeorge** [Azure/azure-storage-azcopy#1231]
### Which version of the AzCopy was used? 
10.6.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10
### What command did you run?
 azcopy list https://blobstoragelink/projectname

### What problem was encountered?
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa8bf9a]
goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/cmd.(*blobFSTraverser).traverse(0xc00088a040, 0x0, 0xc00095a140, 0x12b3ac0, 0x0, 0x0, 0x0, 0x0)
/home/vsts/work/1/s/cmd/zc_traverser_blobfs.go:172 +0x98a
github.com/Azure/azure-storage-azcopy/cmd.(*copyEnumerator).enumerate(0xc00097e180, 0x76f9958200000000, 0xa009ce70614acf80)
/home/vsts/work/1/s/cmd/zc_enumerator.go:629 +0x6e
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc000100380, 0x0, 0x0)
/home/vsts/work/1/s/cmd/copy.go:1142 +0x5ff
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc000100380, 0x74, 0xb)
/home/vsts/work/1/s/cmd/copy.go:947 +0xbc
github.com/Azure/azure-storage-azcopy/cmd.init.2.func2(0xc0001ee280, 0xc0001eccc0, 0x2, 0x3)
/home/vsts/work/1/s/cmd/copy.go:1517 +0x1ba
github.com/spf13/cobra.(*Command).execute(0xc0001ee280, 0xc0001ecc00, 0x3, 0x3, 0xc0001ee280, 0xc0001ecc00)
/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x128f800, 0xc00001aa00, 0xc00013bdc8, 0x40d06f)
/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2f1
github.com/spf13/cobra.(*Command).Execute(...)
/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc00001d0a0, 0x16, 0xc00001d0a0, 0x16, 0xc00001d0e0, 0x1c, 0x7fffffff)
/home/vsts/work/1/s/cmd/root.go:140 +0xd6
main.main()
/home/vsts/work/1/s/main.go:82 +0x3cb

### How can we reproduce the problem in the simplest way?
By running azcopy list on a blob storage with over 800 files. When I watch the command execute, I see that it manages to output about 900 of them, and then the failure occurs. I have tested the same command on a different blob storage that has 800 files, and I have not encountered any issues there. 
### Have you found a mitigation/solution?
No.

**Comment by mohsha-msft** [comment]
Duplicate Issue: https://github.com/Azure/azure-storage-azcopy/issues/1208

**Comment by nakulkar-msft** [comment]
Closing the duplicate. Tracked at #1208
