### ISSUE TITLE
When running azcopy on Azure Pipeline and it is failing with an azcopy error 

### ISSUE THREAD

**Issue by jlteodoro** [Azure/azure-storage-azcopy#1235]
### Which version of the AzCopy was used? 
10.6.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Using Microsoft Windows Hosted agent (windows-latest). However, my pipeline runs choco to install 10.6.1

### What command did you run?
My powershell executes the followingL
  $sourceURL = "https://$SourceAccountName.blob.core.windows.net/$($SourceContainer)?$sourceSAS"
  $targetURL = "https://$TargetAccountName.blob.core.windows.net/$($TargetContainer)?$destSAS"
 
  $copy = azcopy copy `
    $sourceURL `
    $targetURL `
    --recursive=true `
    --overwrite=ifSourceNewer `
    --output-type json

### What problem was encountered?
I receive the following error after over 1hr of execution:
azcopy : runtime: VirtualAlloc of 96477184 bytes failed with errno=1455

### How can we reproduce the problem in the simplest way?
The problem only happens when I run on the agent. I have not yet tried on a VM of the same size, I am still work on that to try.

### Have you found a mitigation/solution?
I am trying to run on a custom agent with more memory to see if it resolves.

**Comment by zezha-msft** [comment]
Hi @jlteodoro, thanks for reaching out!

Are you still encountering this issue? Do you know the spec of the hosted agent? It is a bit surprising, but I'm not sure whether those agents have really limited memory.

Please refer to our [documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure?toc=/azure/storage/blobs/toc.json#optimize-memory-use) and cap the memory usage correspondingly.
