### ISSUE TITLE
azcopy login fails on Azure ML Compute Instance

### ISSUE THREAD

**Issue by sjuratov** [Azure/azure-storage-azcopy#1237]
##### Note: The version is visible when running AzCopy without any argument
10.6.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy login

### What problem was encountered?
Got this error msg:

> Failed to perform login command: 
> failed to get keyring during saving token, key has been revoked
> 
> NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again.

### How can we reproduce the problem in the simplest way?
Repro + mitigation:
1.	Connect to Azure ML Compute Instance using SSH (Jupyter Terminal results in the same issue)
2.	Run **azcopy login** command
a.	Observe that after successful device login using browser, error msg is shown in shell

> Failed to perform login command: 
> failed to get keyring during saving token, key has been revoked
> 
> NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again.

3.	Run **keyctl new_session** command. This is based on different posts such as this one - https://github.com/Azure/azure-storage-azcopy/issues/1021
4.	Run **azcopy login** command again
a.	Observe that after successful device login using browser, login is now successful

> INFO: Login succeeded.

### Have you found a mitigation/solution?
Yes, see above.

**Comment by mohsha-msft** [comment]
Hi @sjuratov ,

Thanks for reaching out to us!
This is a known issue in CentOS, RHEL and some flavors of Linux. What flavor of Linux are you using?
FYI: We will have a work around very soon with v10.7.0 release of AzCopy where we will start supporting device login.

Please read [this](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#run-scripts-by-using-jenkins) to know more about keyctl in AzCopy. Reach out to us if you need more clarity on this.

**Comment by sjuratov** [comment]
Hi @mohsha-msft ,

Here is a version of Linux VM

> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.7 LTS
> Release:        16.04
> Codename:       xenial

Can you confirm that v10.7.0 would fix issue for Ubuntu as well? What is ETA for v10.7.0 release?

**Comment by nakulkar-msft** [comment]
@sjuratov 10.7.0 is [released](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10).
To be precise, 10.7.0 does not fix the error with linux keyring expiring. It provides a comfortable wokround.
Set the enviroment variable` AZCOPY_AUTO_LOGIN_TYPE=DEVICE`, and the copy command will ask you to login to Azure Servce.

[nakulkar@nakulkar-dev:~]$ azcopy copy file512k "https://<account>.blob.core.windows.net/container1/"
INFO: Scanning...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <KEY> to authenticate.

**Comment by hholst80** [comment]
> `AZCOPY_AUTO_LOGIN_TYPE=DEVICE`
This asks me to login for every single CLI command. Obviously that does not work.
