### ISSUE TITLE
AzCopy completes without actually completing the download

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#1239]
### Which version of the AzCopy was used? 
10.6.0

### Which platform are you using? 
Mac

### What command did you run?
copy. Download a blob using account level SAS.

### What problem was encountered?
AzCopy reports job completed without downloading that blob.

### How can we reproduce the problem in the simplest way?
1. Create a storage account SAS with resource type container (sr=c)
2. Construct a copy command "azcopy cp "https://acct.blob.core.windows.net/container/blob?sas" "localfilepath" ......
3. The job output says "Completed with 0 items transferred"

### Have you found a mitigation/solution?
Creating a SAS with both container and object resource type (sr=co) will enable AzCopy to download the blob. Ideally, AzCopy should report an error instead.

**Comment by zezha-msft** [comment]
Hi @JasonYeMSFT, I believe this is the same issue that we already discussed before, where if the source is non-existent (or cannot be read), we don't report a failure as you have asked. To clarify though, what is the expected behavior here?

**Comment by JasonYeMSFT** [comment]
If the source is non-existent, I think it is fine to say success. But since the source actually exists, reporting success while not downloading it is misleading.

**Comment by tasherif-msft** [comment]
Hi @JasonYeMSFT are you still experiencing this issue? I was not able to repro this given the steps you provided

**Comment by tasherif-msft** [comment]
Hi @JasonYeMSFT I will go ahead and close this issue as I was not able to repro it in latest releases. Feel free to reopen if still encountering this problem
