### ISSUE TITLE
AzCopy not working for fileshares

### ISSUE THREAD

**Issue by baboos78** [Azure/azure-storage-azcopy#1241]
### Which version of the AzCopy was used? 
AzCopy 10.6.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy list  https://tenant.file.core.windows.net/fileshare

### What problem was encountered?
azure files requires a SAS token for authentication

### How can we reproduce the problem in the simplest way?
azcopy login
azcopy list  https://tenant.file.core.windows.net/fileshare

### Have you found a mitigation/solution?
Found one that says keyctl session workaroundSession should work. But not ketctl not working in windows

**Comment by nakulkar-msft** [comment]
@baboos78 File Service REST APIs, which are used by AzCopy to interact with Azure Filestore, do not allow auth with AAD. Only SAS can be used. You can see more details [here](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage)
