### ISSUE TITLE
Azcopy failing Nexus IQ scan with security vulnerability over x/text package

### ISSUE THREAD

**Issue by jayaraj-selvaraj** [Azure/azure-storage-azcopy#1246]
##### Note: The version is visible when running AzCopy without any argument
Azcopy 10.7.0 latest

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
Nexus IQ Scan on the go.sum file

### What problem was encountered?
Security vulnerability reported as Azcopy 10.7.0 uses x/text package (below 0.3.3).
As per the go.sum file it used 0.3.0 an 0.3.2

Report mentioned -->  x/text package below 0.3.3 has vulnerability in encoding/unicode that could lead to UTF-16 decoder entering an infinite loop, causing program to crash or run out of memory. 
 
### How can we reproduce the problem in the simplest way?
Running a Nexus IQ scan

### Have you found a mitigation/solution?
As per the recommendation, Go modules to be updated to use x/text package v0.3.3 which addresses this vulnerability.
Ref:  https://github.com/golang/go/issues/39491

**Comment by zezha-msft** [comment]
Thank you @jayaraj-selvaraj for reporting this issue! I see it's an indirect dependency of ours. We'll get it fixed.
