### ISSUE TITLE
PipeBlob no response

### ISSUE THREAD

**Issue by AdieOlami** [Azure/azure-storage-azcopy#1247]
I tried to upload with PipeBlob but I cannot find my file in the directory which I specified.

cat test2.json | sudo azcopy cp https://xxxx.blob.core.windows.net/test --from-to PipeBlob

Nothing happens at the end of the command.

**Comment by mohsha-msft** [comment]
Hey @AdieOlami ,

Thanks for reaching out to us!
Transferring data when source is a pipe basically means providing stream of data as input and not file. As a result, all the information about file does not get copied (which obviously includes the name of the file as well). In your case, your input is the content of `test2.json` so AzCopy doesn't know what to name the file at destination. This command will work if you specify name once.

For example 

`cat test2.json | sudo azcopy cp https://xxxx.blob.core.windows.net/test/test2.json --from-to PipeBlob`
