### ISSUE TITLE
Proxy docs do not cover HTTPS_PROXY vs https_proxy

### ISSUE THREAD

**Issue by MRayermannMSFT** [Azure/azure-storage-azcopy#1249]
The documentation for proxy settings in AzCopy both make reference to all caps env vars and all lowercase env vars.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/21112697/98976388-25245b00-24cc-11eb-863f-20edd5722508.png">

On some OS's, the casing of environment variables makes a difference.

So which casing does AzCopy look for? Is it both? And if so, which one is looked at first?

**Comment by zezha-msft** [comment]
That's a great question! Thanks for asking it!

To clarify, both uppercase and lowercase variables can be used. And if both are present, the uppercase one is looked at first. We should perhaps make the doc consistent and only show uppercase ones.
