### ISSUE TITLE
High CPU when using azcopy v10.7.0

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-storage-azcopy#1251]
### Which version of the AzCopy was used? 
10.7.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 in Azure VM
Size Standard D32s v3
vCPUs = 32
RAM = 128GM

### What command did you run?
azcopy copy "c:\test\*" "https://yangshendfs002.blob.core.windows.net/test/?sv=XXXX" --cap-mbps=100 --overwrite=true

I have 100 files in the folder c:\test and each file is 1GB size.

### What problem was encountered?
High CPU (100%) 
It lasted for 5 seconds

### How can we reproduce the problem in the simplest way?
This is report by our cx, and I can reproduce it in house.

### Have you found a mitigation/solution?
If I only have one file in the local folder, the CPU is good
I think the multiple local files caused the high CPU.

**Comment by zezha-msft** [comment]
Hi @yangchengs, thanks for reaching out!

Could you please clarify the problem/expected behavior? In general, it's normal for CPU usage to spike for any application, as long as it calms down after a short time.

**Comment by yangchengs** [comment]
> Hi @yangchengs, thanks for reaching out!
> 
> Could you please clarify the problem/expected behavior? In general, it's normal for CPU usage to spike for any application, as long as it calms down after a short time.

I understand that the threads init during the start causes high CPU.
I have talked with John Rusk, he suggests me to lower the value of AZCOPY_CONCURRENT_FILES. I changed it to 5 (default is 64) and it did resolve the issue.

**Comment by zezha-msft** [comment]
Sounds good @yangchengs. Thanks for letting me know!
