### ISSUE TITLE
failed to perform copy due to error: cannot start job due to error: cannot scan the path

### ISSUE THREAD

**Issue by jradin2001** [Azure/azure-storage-azcopy#1252]
##### Note: The version is visible when running AzCopy without any argument
10.7
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "Z:\xxxxx" "https://xxxxx.blob.core.windows.net/xxxxx" --recursive=true
### What problem was encountered?
See above error in title. I can easily get to the share from CMD prompt.
### Have you found a mitigation/solution?
Nope

**Comment by zezha-msft** [comment]
Hi @jradin2001 thanks for reaching out!

Could you please double-check that the quoted path is escaped correctly?

**Comment by nakulkar-msft** [comment]
Closed due to inactivity
