### ISSUE TITLE
AzCopy fail to copy version of an append blob

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#1253]
### Which version of the AzCopy was used? 
10.7.0

### What command did you run?
./azcopy copy "https://acct.blob.core.windows.net/container/blob.txt?sv=2019-12-12&se=2020-12-19T18%3A40%3A23Z&sr=c&sp=rl&sig=&versionid=2020-06-12T17%3A50%3A39.1120973Z" "https://acct.blob.core.windows.net/container/blob.txt?sv=2019-12-12&se=2020-12-19T18%3A40%3A23Z&sr=c&sp=wl&sig=" --overwrite=true --recursive;

### What problem was encountered?
AzCopy fail with error: 400 One of the query parameters specified in the request URI is not supported.. When Appending block from URL
### How can we reproduce the problem in the simplest way?
Upload an append blob. Enable versioning. Delete the append blob. Copy it from the version to the root.

### Have you found a mitigation/solution?
No.

**Comment by zezha-msft** [comment]
I repro'd this issue and we'll follow up with the service team. Thanks for reporting it!

**Comment by zezha-msft** [comment]
It's a service issue unfortunately, I'll leave this issue to track the resolution.

**Comment by gapra-msft** [comment]
It looks like this issue has been fixed so I will go ahead and close this issue.
