### ISSUE TITLE
Add -v alias for version

### ISSUE THREAD

**Issue by brettrowberry** [Azure/azure-storage-azcopy#126]
### Which version of the AzCopy was used?
10.0.4-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
--help

### What problem was encountered?
For help, we have the `--help` and `-h` options. For version #, we only have `--version`, not `-v`.

### How can we reproduce the problem in the simplest way?
--help

### Have you found a mitigation/solution?
Can we add a `-v` option?

**Comment by zezha-msft** [comment]
Hi @brettrowberry, I apologize for the late reply. 

Yes, this is totally reasonable. Thanks for the suggestion!

**Comment by brettrowberry** [comment]
Is there still interest in this?

**Comment by zezha-msft** [comment]
@brettrowberry sorry we haven't had time to figure out how to do that with the framework we are using (Cobra), as it's `--version` is provided to us as is.

**Comment by zezha-msft** [comment]
I'm not sure that there's a compelling argument to have the shorthand, so we'll not prioritize this one for now. Sorry!
