### ISSUE TITLE
Azcopy will not copy all files instead it will give this error message

### ISSUE THREAD

**Issue by jannerajala** [Azure/azure-storage-azcopy#1260]
### Which version of the AzCopy was used? 
10.7.0
##### Note: The version is visible when running AzCopy without any argument
Windows Server 2012 R2
### What command did you run?

azcopy copy "D:\Users\MRNOREMA\Backup\1 - Claims Backup 02.07.2020\1 - CLAIMS\0  -  EMA Current - Backups\EMA Current 04.17.2018\*" --recursive "https://strusfileprod01.file.core.windows.net/users/MRNOREMA/Backup/"<-SAS-> --preserve-smb-permissions=true --preserve-smb-info=true --force-if-read-only
### What problem was encountered?
After Azcopy started it give this error
 /opt/hostedtoolcache/go/1.13.0/x64/src/net/fd_windows.go:152 +0x3f
onn).Read(0x13d251c8, 0x3f994000, 0x1faf, 0x1faf, 0x0, 0x0, 0x0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/net/net.go:184 +0x56
tls.(*atLeastReader).Read(0x60eae370, 0x3f994000, 0x1faf, 0x1faf, 0x0, 0x134085e4, 0x347923f0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:780 +0x61
*Buffer).ReadFrom(0x19cda760, 0xbff4e0, 0x60eae370, 0x4e2b3, 0x408569, 0xa0a9e0, 0xa913a0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/bytes/buffer.go:204 +0x95
tls.(*Conn).readFromUntil(0x19cda600, 0x347923f0, 0x13d251c8, 0x5, 0x13d251c8, 0x9a4f4df4)
 /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:802 +0xcb
tls.(*Conn).readRecordOrCCS(0x19cda600, 0x0, 0x0, 0x0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:609 +0x114
tls.(*Conn).readRecord(...)
 /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:577
tls.(*Conn).Read(0x19cda600, 0x32927000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1255 +0x136
p.(*persistConn).Read(0x13dae6e0, 0x32927000, 0x1000, 0x1000, 0x451aa0, 0x14bd9ef4, 0x2)
 /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1744 +0x143
*Reader).fill(0x66e31020)
 /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:100 +0xe9
*Reader).Peek(0x66e31020, 0x1, 0x2, 0x0, 0x0, 0x617cd800, 0x14bd41c0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:138 +0x41
p.(*persistConn).readLoop(0x13dae6e0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1897 +0x1c0
 by net/http.(*Transport).dialConn
 /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1566 +0x8fe

ne 2211 [IO wait]:
l/poll.runtime_pollWait(0x347abf28, 0x77, 0xc019e0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/runtime/netpoll.go:184 +0x4b
l/poll.(*pollDesc).wait(0x5bffea9c, 0x77, 0x1021200, 0x0, 0x0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_poll_runtime.go:87 +0x37
l/poll.(*ioSrv).ExecIO(0x107fdbc, 0x5bffea28, 0xaf1f98, 0x19f5a800, 0xd, 0x401d)
 /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:228 +0xef
l/poll.(*FD).Write(0x5bffe9a0, 0x19f5a800, 0x401d, 0x401d, 0x0, 0x0, 0x0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:723 +0x25c
etFD).Write(0x5bffe9a0, 0x19f5a800, 0x401d, 0x401d, 0x401d, 0x0, 0x0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/net/fd_windows.go:164 +0x3f
onn).Write(0x2c414e40, 0x19f5a800, 0x401d, 0x401d, 0x0, 0x0, 0x0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/net/net.go:196 +0x56
tls.(*Conn).write(0x1386b200, 0x19f5a800, 0x401d, 0x401d, 0x1c6f8000, 0x4000, 0x8000)
 /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:915 +0x122
tls.(*Conn).writeRecordLocked(0x1386b200, 0x17, 0x1c6f8000, 0x8000, 0x8000, 0x2e0ee1c0, 0x1c6f8000, 0x8000)
 /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:964 +0x214
tls.(*Conn).Write(0x1386b200, 0x1c6f8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
 /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1133 +0x185
Buffer(0x347a5538, 0x1386b200, 0xc008a0, 0x155a1820, 0x1c6f8000, 0x8000, 0x8000, 0xa0aaa0, 0xa3d060, 0x1, ...)
 /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:404 +0x190
(...)
 /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:364
p.persistConnWriter.ReadFrom(0x13dafd60, 0xc008a0, 0x155a1820, 0x347a5520, 0x13dafd60, 0x1, 0x34d)
 /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1591 +0x75
*Writer).ReadFrom(0x2bdf86a0, 0xc008a0, 0x155a1820, 0x347a5508, 0x2bdf86a0, 0x40a401, 0x155a1820)
 /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:713 +0x2d0
Buffer(0xbff3a0, 0x2bdf86a0, 0xc008a0, 0x155a1820, 0x0, 0x0, 0x0, 0xffffff00, 0x0, 0x28a, ...)

### How can we reproduce the problem in the simplest way?
I do not know
### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment]
Hey @jannerajala 

Thank you for reaching out!

The stack trace which you mentioned belong to these scenarios
1.  `"wsasend: An existing connection was forcibly closed by the remote host."` or 
2. `"wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"`

It is likely to happen when the network link between the client and server is going down for some reason. Read [Windows Sockets Error Codes](https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2) to know more.

Mostly the error appears due to an outdated version of .Net Framework. So, please consider upgrading it.  Also, Windows firewall can sometimes prevents the communication by blocking them.
