### ISSUE TITLE
AzCopy fail to enumerate blobs under directories in a premium storage account

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#1261]
### Which version of the AzCopy was used? 
10.7.0 (someone found that this regressed from 10.5.0)

### What command did you run?
copy

### What problem was encountered?
During enumeration for the source, AzCopy list a directory and stops without enumerating blobs in it.

### How can we reproduce the problem in the simplest way?
Go to a premium storage account's blob container, find a directory and copy it to somewhere else as source.

### Have you found a mitigation/solution?
Copy exact blobs instead of their directory.

### Extra context
This doesn't reproduce for non-premium storage accounts.

**Comment by tasherif-msft** [comment]
Hi @JasonYeMSFT I could not repro this, 
I copied a dir recursively from a premium storage account to local FS and it worked successfully. Please let me know if im missing something.
I will close this issue in the meantime, feel free to reopen if your issue still persists.
