### ISSUE TITLE
Support overriding TryTimeout (or just reduce) for copy operations

### ISSUE THREAD

**Issue by dmichon-msft** [Azure/azure-storage-azcopy#1264]
### Which version of the AzCopy was used?
10.7.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows, Linux

### What command did you run?
azcopy copy https://{sourceaccount}.blob.core.windows.net/{container}/{virtualdir} https://{destinationaccount}.blob.core.windows.net/{container}/{virtualdir} --recursive=true --from-to=BlobBlob

### What problem was encountered?
Frequently 1-3 of the 40k+ files will stall for the full 15 minute timeout duration, then succeed within seconds on retry. This results in copy operations routinely either completing within a couple of minutes or taking 15-16 minutes with no in-between. It would be advantageous in this scenario to be able to set the try timeout to something more like 1 minute.

Essentially I get hundreds of lines of this at the end of the copy operation:
```, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
99.7 %, 70704 Done, 0 Failed, 11 Pending, 0 Skipped, 70715 Total, 
```
Then those pending transfers finally timeout and it very quickly finishes.

### How can we reproduce the problem in the simplest way?
Copy block blobs in bulk between two storage accounts (in different regions) several times and observe that sooner or later a small number of the transfers will stall for the full duration, then very quickly succeed once the timeout hits.

### Have you found a mitigation/solution?
If I had a way to forcibly interrupt the job after a few minutes and tell it to resume, I'd do so, but I don't know of a safe way to interrupt the copy programatically.

Edit: added specific example

**Comment by mohsha-msft** [comment]
Hey @dmichon-msft  ,

Thanks for reaching out!

AzCopy internally uses an [exponential backoff policy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#troubleshoot-issues) with randomized delays (retry interval), that increases the backoff period for each retry attempt in a given set using the exponential function, to prevent successive collisions which mean there is no need to set retry interval. Also, the settings are not exposed to the end-user as it’s rare that a CX would know what to put. Not in the public release binaries for customers at least.

But then again, if you would like to do some experimentation, you can check out https://github.com/Azure/azure-storage-azcopy/blob/14f86d07950e0d4fe61f1815f9e8e4387acfd8d6/ste/xfer.go#L35 to tune the values and then try to build your own version of AzCopy.

I'll try to discuss with my peers about the possibility of this being a possible feature in future releases. 

Please reach out for more clarification.

**Comment by dmichon-msft** [comment]
It's actually not the retry interval that I'm concerned with. It's the timeout for a single API call. The transfers tend to have a pattern of taking a few seconds or the entire 901 second timeout interval, and nowhere in between. I suppose I might give creating a custom build a shot, since it's a highly localized change.
