### ISSUE TITLE
azcopy login --tenand-id <id> does not work on Ubuntu

### ISSUE THREAD

**Issue by akihiro-inui** [Azure/azure-storage-azcopy#1267]
### Which version of the AzCopy was used? 
azcopy_linux_amd64_10.7.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy login --tenant-id <id>

### What problem was encountered?
After successfully logging in with the temporary password shown, it said;
"Failed to perform login command: failed to get keyring during saving token, operation not permitted"

### How can we reproduce the problem in the simplest way?
Run azcopy login --tenant-id <id> in google colab

### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/1021

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/1021
