### ISSUE TITLE
AzCopy - Can i depend on the AAD login command to access the AKV resource?

### ISSUE THREAD

**Issue by thiyagarajann** [Azure/azure-storage-azcopy#1270]
### What problem was encountered? If I can depend on AzCopy utility for AAD authentication to access non-ADLS resource, would this feature remain working for all the latest versions of AzCopy Utility?

I need to connect to AKV resource from on-premise application. SP w/cert as credential for AD authentication. If authentication is successful, I will invoke the REST API url of AKV to retrieve the secret/cert.

**Comment by mohsha-msft** [comment]
@thiyagarajann 

Thanks for reaching out!

I didn't quite understand your requirement. How do you plan on using AzCopy? Please refer to [public documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory?toc=/azure/storage/blobs/toc.json) for more information on login via Azure AD in AzCopy.

Please reach out to us with the use case which you wish to solve with AzCopy.
