### ISSUE TITLE
AzCopy don't support connection to storage private endpoint while connection to Azure AD is required over proxy.

### ISSUE THREAD

**Issue by dlindblom** [Azure/azure-storage-azcopy#1275]
### Which version of the AzCopy was used? 
10.7.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows & Linux

### What command did you run?
N/A

### What problem was encountered?
Proxy used: 403 This request is not authorized to perform this operation. (Storage is on private endpoint)
Proxy not used: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/f2****03/oauth2/token?api-version=1.0: dial tcp 40.126.9.73:443: i/o timeout'

### How can we reproduce the problem in the simplest way?
You have Storage account on private endpoint on local network (perhaps extended via ExpressRoute), while you need to use Internet Proxy to connect to Azure AD on Internet for OAuth authentication (user/principle).

### Have you found a mitigation/solution?
Proxy auto-config file typically handles logic if traffic should be routed via specific Proxy or DIRECT but is not supported by AzCopy(and Storage Explorer) today. There is need to have some logic for AzCopy(and Storage Explorer) to allow connection to Azure AD over Proxy but option to have direct connection to Storage Account that have Private Endpoint enabled.

**Comment by vinuait63** [comment]
We are using Storage Explorer 1.17.0 but we are observing the same issue.
Is this issue resolved?

**Comment by cconstandis** [comment]
Hi, any potential news regarding azcopy and private endpoint issues? Still does not work even with azcopy 10.8 (latest as of today)

**Comment by vkas-chaurasia** [comment]
I am using below setting for azcopy  env 
http_proxy = < proxy >
No_proxy = '*.blob.core.windows.net,dfs.core.windows,net'
Its connecting to private endpoint via Azure AD 

However  , there is no option in storage explorer to specify no_proxy for some domain . I guess to make it work , private endpoint should be resolve by Azure Public DNS

**Comment by amuthan1983** [comment]
Any solution on this yet ?

**Comment by gapra-msft** [comment]
Hi all, are you still experiencing this in latest version of AzCopy?

**Comment by gapra-msft** [comment]
Closing this issue as there has not been any activity in 3 years. Please open a new issue if you are still experiencing issues.
