### ISSUE TITLE
When directory and blob have identical name, copy the directory actually copies the blob

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#1277]
### Which version of the AzCopy was used? 
10.7.0

### What command did you run?
Copy. Copy a directory in blob container using wildcard.

### What problem was encountered?
If there is a blob who has identical name with the directory, the blob will be copied instead.

### How can we reproduce the problem in the simplest way?
Make sure at root directory level of "container", there are two blobs
"directory/somefile" (a directory)
"directory" (a blob) 

Execute a copy command like:
./azcopy copy "https://account.blob.core.windows.net/container/directory/*?sasToken" "https://account.blob.core.windows.net/container/directoryName2?sasToken" --recursive;

Expects to see three blobs
"directory/somefile" (a directory)
"directory2/somefile" (copied directory)
"directory" (a blob) 

Actually sees:
"directory/somefile" (a directory)
"directory" (a blob) 
"directory2" (copied blob)

### Have you found a mitigation/solution?
Not use the wildcard, but this make it hard to specify the new directory name since 
./azcopy copy "https://account.blob.core.windows.net/container/directory?sasToken" "https://account.blob.core.windows.net/container/directoryName2?sasToken" --recursive;

would result in
"directory/somefile" (a directory)
"directory2/directory/somefile" (copied directory)
"directory" (a blob) 

### Additional context
I think the wildcard is a good indication that the source is a directory. If the wildcard exists in the source, AzCopy should consider enumerate with a trailing / so that blob with the same name won't be included.

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/1424

**Comment by JasonYeMSFT** [comment]
As far as I know, this is not fixed yet.
