### ISSUE TITLE
AZCopy fails after .03%

### ISSUE THREAD

**Issue by stevelogik** [Azure/azure-storage-azcopy#1278]
### What command did you run? Azcopy copy and azcopy sync
azcopy copy "C:\Test" "https://mystorageaccount.blob.core.windows.net/azcopydata/Test" --recursive

### What problem was encountered?

It will successfully start uploading files and around 0.3 % it fails and generates a huge error log

### How can we reproduce the problem in the simplest way? 

I'm trying to copy 500GB of data to a blob container that has multiple sub directories from an on-premise server

**Comment by stevelogik** [comment]
I also get this scrolling when it fails:

5918, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0x2074cc00, 0x0, 0x0, 0xffffffff)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0x2074cc00, 0x50fe4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1255 +0x136
net/http.(*persistConn).Read(0x1348efa0, 0x50fe4000, 0x1000, 0x1000, 0x40, 0x0,
0x1)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1744 +0x143

bufio.(*Reader).fill(0x503f83f0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:100 +0xe9
bufio.(*Reader).Peek(0x503f83f0, 0x1, 0x4b1b9380, 0x13882062, 0x15215fa0, 0x5c4c
a5, 0x22572a30)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:138 +0x41
net/http.(*persistConn).readLoop(0x1348efa0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1897 +0x1c0

created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1566 +0x8fe


goroutine 1679 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x3691cff0, 0x72, 0xc019e0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0x21fa343c, 0x72, 0x1021200, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_poll_runtime.go:
87 +0x37
internal/poll.(*ioSrv).ExecIO(0x107fdb8, 0x21fa3354, 0xaf1f88, 0x0, 0x5c6084, 0x
220de210)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:228 +
0xef
internal/poll.(*FD).Read(0x21fa3340, 0x4b134000, 0x1fb1, 0x1fb1, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:527 +
0x10a
net.(*netFD).Read(0x21fa3340, 0x4b134000, 0x1fb1, 0x1fb1, 0x3690c300, 0x41e12f,
0x36a92fd7)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x2297d500, 0x4b134000, 0x1fb1, 0x1fb1, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/net.go:184 +0x56
crypto/tls.(*atLeastReader).Read(0x22eec7f0, 0x4b134000, 0x1fb1, 0x1fb1, 0x21c50
000, 0x134085e4, 0x35040008)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:780 +0x61
bytes.(*Buffer).ReadFrom(0x220de360, 0xbff4e0, 0x22eec7f0, 0x1, 0x408569, 0xa0a9
e0, 0xa913a0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bytes/buffer.go:204 +0x95
crypto/tls.(*Conn).readFromUntil(0x220de200, 0x35040008, 0x2297d500, 0x5, 0x2297
d500, 0x24617bfc)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0x220de200, 0x0, 0x0, 0x7)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0x220de200, 0x20825000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1255 +0x136
net/http.(*persistConn).Read(0x20096d20, 0x20825000, 0x1000, 0x1000, 0x40, 0x0,
0x1)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1744 +0x143

bufio.(*Reader).fill(0x22daac90)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:100 +0xe9
bufio.(*Reader).Peek(0x22daac90, 0x1, 0x1d21df40, 0x15b0d78, 0x137c516c, 0x2305a
e4c, 0x20096d2c)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:138 +0x41
net/http.(*persistConn).readLoop(0x20096d20)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1897 +0x1c0

created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1566 +0x8fe


goroutine 1746 [IO wait]:
internal/poll.runtime_pollWait(0x36ab10a8, 0x72, 0xc019e0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0x20955f3c, 0x72, 0x1021200, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_poll_runtime.go:
87 +0x37
internal/poll.(*ioSrv).ExecIO(0x107fdb8, 0x20955e54, 0xaf1f88, 0x1fa4, 0x10, 0x0
)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:228 +
0xef
internal/poll.(*FD).Read(0x20955e40, 0x21fe4000, 0x1fb1, 0x1fb1, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:527 +
0x10a
net.(*netFD).Read(0x20955e40, 0x21fe4000, 0x1fb1, 0x1fb1, 0x0, 0x3ebac95, 0x196)

        /opt/hostedtoolcache/go/1.13.0/x64/src/net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x227e0dd0, 0x21fe4000, 0x1fb1, 0x1fb1, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/net.go:184 +0x56
crypto/tls.(*atLeastReader).Read(0x21fbf950, 0x21fe4000, 0x1fb1, 0x1fb1, 0x0, 0x
134085e4, 0x35040008)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:780 +0x61
bytes.(*Buffer).ReadFrom(0x20663160, 0xbff4e0, 0x21fbf950, 0x834, 0x408569, 0xa0
a9e0, 0xa913a0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bytes/buffer.go:204 +0x95
crypto/tls.(*Conn).readFromUntil(0x20663000, 0x35040008, 0x227e0dd0, 0x5, 0x227e
0dd0, 0x45be9bb0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0x20663000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0x20663000, 0x227cd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1255 +0x136
net/http.(*persistConn).Read(0x1353c8c0, 0x227cd000, 0x1000, 0x1000, 0x451aa0, 0
x30a19ef4, 0x2)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1744 +0x143

bufio.(*Reader).fill(0x22c101b0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:100 +0xe9
bufio.(*Reader).Peek(0x22c101b0, 0x1, 0x2, 0x0, 0x0, 0x1d500d00, 0x24888700)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:138 +0x41
net/http.(*persistConn).readLoop(0x1353c8c0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1897 +0x1c0

created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1566 +0x8fe


goroutine 1677 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0x20096dc0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:2196 +0xef
created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1567 +0x91f


goroutine 1724 [IO wait]:
internal/poll.runtime_pollWait(0x3691cee8, 0x77, 0xc019e0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0x1644c25c, 0x77, 0x1021200, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_poll_runtime.go:
87 +0x37
internal/poll.(*ioSrv).ExecIO(0x107fdbc, 0x1644c1e8, 0xaf1f98, 0x49cec800, 0xd,
0x401d)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:228 +
0xef
internal/poll.(*FD).Write(0x1644c160, 0x49cec800, 0x401d, 0x401d, 0x0, 0x0, 0x0)

        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:723 +
0x25c
net.(*netFD).Write(0x1644c160, 0x49cec800, 0x401d, 0x401d, 0x401d, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/fd_windows.go:164 +0x3f
net.(*conn).Write(0x223887e0, 0x49cec800, 0x401d, 0x401d, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/net.go:196 +0x56
crypto/tls.(*Conn).write(0x20662000, 0x49cec800, 0x401d, 0x401d, 0x1406c000, 0x4
000, 0x4000)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:915 +0x122
crypto/tls.(*Conn).writeRecordLocked(0x20662000, 0x17, 0x1406c000, 0x8000, 0x400
0, 0x231732e0, 0x14068000, 0x8000)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:964 +0x214
crypto/tls.(*Conn).Write(0x20662000, 0x14068000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1133 +0x185
io.copyBuffer(0x3691c9c8, 0x20662000, 0xc008a0, 0x1fe3e3c0, 0x14068000, 0x8000,
0x8000, 0xa0aaa0, 0xa3d060, 0x1, ...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:404 +0x190
io.Copy(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:364
net/http.persistConnWriter.ReadFrom(0x17a2c780, 0xc008a0, 0x1fe3e3c0, 0x3691c9b0
, 0x17a2c780, 0x1, 0x34d)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1591 +0x75
bufio.(*Writer).ReadFrom(0x21263500, 0xc008a0, 0x1fe3e3c0, 0x3691c998, 0x2126350
0, 0x40a401, 0x1fe3e3c0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:713 +0x2d0
io.copyBuffer(0xbff3a0, 0x21263500, 0xc008a0, 0x1fe3e3c0, 0x0, 0x0, 0x0, 0xfffff
f00, 0x0, 0x338, ...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:388 +0x29e
io.Copy(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:364
net/http.(*transferWriter).doBodyCopy(0x20076690, 0xbff3a0, 0x21263500, 0xc008a0
, 0x1fe3e3c0, 0x23a2d0e0, 0x20662108, 0x20662114, 0x20662108)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transfer.go:400 +0x55
net/http.(*transferWriter).writeBody(0x20076690, 0xbff3a0, 0x21263500, 0x2, 0x2)

        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transfer.go:359 +0x631
net/http.(*Request).write(0x23b1cc80, 0xbff3a0, 0x21263500, 0x0, 0x0, 0x0, 0x0,
0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/request.go:682 +0x5a7
net/http.(*persistConn).writeLoop(0x17a2c780)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:2199 +0x178

created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1567 +0x91f


goroutine 1748 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x36ab1234, 0x72, 0xc019e0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0x238c025c, 0x72, 0x1021200, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_poll_runtime.go:
87 +0x37
internal/poll.(*ioSrv).ExecIO(0x107fdb8, 0x238c0174, 0xaf1f88, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:228 +
0xef
internal/poll.(*FD).Read(0x238c0160, 0x23766000, 0x1fb1, 0x1fb1, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:527 +
0x10a
net.(*netFD).Read(0x238c0160, 0x23766000, 0x1fb1, 0x1fb1, 0x259ad8d9, 0x3fbb7c5,
 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x2297d520, 0x23766000, 0x1fb1, 0x1fb1, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/net.go:184 +0x56
crypto/tls.(*atLeastReader).Read(0x22fa8c50, 0x23766000, 0x1fb1, 0x1fb1, 0x0, 0x
134085e4, 0x35040008)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:780 +0x61
bytes.(*Buffer).ReadFrom(0x220de560, 0xbff4e0, 0x22fa8c50, 0xc07d60, 0x408569, 0
xa0a9e0, 0xa913a0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bytes/buffer.go:204 +0x95
crypto/tls.(*Conn).readFromUntil(0x220de400, 0x35040008, 0x2297d520, 0x5, 0x2297
d520, 0x4076e7)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0x220de400, 0x0, 0x0, 0xffffff)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0x220de400, 0x23bf3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1255 +0x136
net/http.(*persistConn).Read(0x20096e60, 0x23bf3000, 0x1000, 0x1000, 0x40, 0x0,
0x1)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1744 +0x143

bufio.(*Reader).fill(0x233f3e90)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:100 +0xe9
bufio.(*Reader).Peek(0x233f3e90, 0x1, 0x21ca0a00, 0x1, 0x206631a0, 0x5c4ca5, 0x2
0663000)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:138 +0x41
net/http.(*persistConn).readLoop(0x20096e60)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1897 +0x1c0

created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1566 +0x8fe


goroutine 1385 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0x1348f0e0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:2196 +0xef
created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1567 +0x91f


goroutine 1633 [IO wait]:
internal/poll.runtime_pollWait(0x36ab112c, 0x77, 0xc019e0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0x21c7743c, 0x77, 0x1021200, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_poll_runtime.go:
87 +0x37
internal/poll.(*ioSrv).ExecIO(0x107fdbc, 0x21c773c8, 0xaf1f98, 0x25050800, 0xd,
0x401d)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:228 +
0xef
internal/poll.(*FD).Write(0x21c77340, 0x25050800, 0x401d, 0x401d, 0x0, 0x0, 0x0)

        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:723 +
0x25c
net.(*netFD).Write(0x21c77340, 0x25050800, 0x401d, 0x401d, 0x401d, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/fd_windows.go:164 +0x3f
net.(*conn).Write(0x227e0dc0, 0x25050800, 0x401d, 0x401d, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/net.go:196 +0x56
crypto/tls.(*Conn).write(0x20662e00, 0x25050800, 0x401d, 0x401d, 0x1436a000, 0x4
000, 0x4000)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:915 +0x122
crypto/tls.(*Conn).writeRecordLocked(0x20662e00, 0x17, 0x1436a000, 0x8000, 0x400
0, 0x217ea540, 0x14366000, 0x8000)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:964 +0x214
crypto/tls.(*Conn).Write(0x20662e00, 0x14366000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1133 +0x185
io.copyBuffer(0x3691c9c8, 0x20662e00, 0xc008a0, 0x205a2380, 0x14366000, 0x8000,
0x8000, 0xa0aaa0, 0xa3d060, 0x1, ...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:404 +0x190
io.Copy(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:364
net/http.persistConnWriter.ReadFrom(0x1fe13360, 0xc008a0, 0x205a2380, 0x3691c9b0
, 0x1fe13360, 0x1, 0x34d)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1591 +0x75
bufio.(*Writer).ReadFrom(0x22329060, 0xc008a0, 0x205a2380, 0x3691c998, 0x2232906
0, 0x40a401, 0x205a2380)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:713 +0x2d0
io.copyBuffer(0xbff3a0, 0x22329060, 0xc008a0, 0x205a2380, 0x0, 0x0, 0x0, 0xfffff
f00, 0x0, 0x2ec, ...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:388 +0x29e
io.Copy(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:364
net/http.(*transferWriter).doBodyCopy(0x20c91270, 0xbff3a0, 0x22329060, 0xc008a0
, 0x205a2380, 0x20bcb140, 0x20662f08, 0x20662f14, 0x20662f08)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transfer.go:400 +0x55
net/http.(*transferWriter).writeBody(0x20c91270, 0xbff3a0, 0x22329060, 0x2, 0x2)

        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transfer.go:359 +0x631
net/http.(*Request).write(0x20d90400, 0xbff3a0, 0x22329060, 0x0, 0x0, 0x0, 0x0,
0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/request.go:682 +0x5a7
net/http.(*persistConn).writeLoop(0x1fe13360)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:2199 +0x178

created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1567 +0x91f

**Comment by stevelogik** [comment]
Also the logs have a lot of these. But missing data never shows up: 

17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6064, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6065, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6066, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6067, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6068, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6069, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6070, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6071, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6072, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6073, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6074, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6075, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6076, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6077, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6078, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6079, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547, Part#=2, Transfer#=6080, priority=0
2020/12/12 17:32:20 scheduling JobID=6c89650f-bd0d-454b-62bf-f93cce81b547,

**Comment by stevelogik** [comment]
The huge log doesn't state an error just a million of the "Scheduling JobID=" with no additional files ever showing up

**Comment by mohsha-msft** [comment]
Hey @stevelogik ,

It'll be difficult to find the issue with just the stack trace. Would you please email me the logs.  `mohsha@microsoft.com`
It most likely is issue from the network but to be certain I want to investigate more. Please forward the logs.

**Comment by mohsha-msft** [comment]
Hey @stevelogik ,

It'll be difficult to find the issue with just the stack trace. Would you please email me the logs at `mohsha@microsoft.com`
It most likely is issue from the network but to be certain I want to investigate more. Please forward the logs.

**Comment by stevelogik** [comment]
Hrllo @mohsha-msft I've emailed you the log file. Let me know if you need anything else. I would like to mention the environment is an On-premise server connected via IPSEC to Azure with custom DNS servers (two DCs) one on-premise and the other in Azure. Both are behind Fortigates

**Comment by mohsha-msft** [comment]
Hey @stevelogik 

The log file which you shared doesn't seem complete. For instance the logs which you just shared above are not there in the log file. Also, It doesn't have job status in the end as well.

Going through the log file, I see the enumeration of files are happening successfully and I see not a single error happening in the log file. All the requests are getting UPLOADSUCCESSFUL . 

Was the job force interrupted in between?

**Comment by stevelogik** [comment]
Hi @mohsha-msft 

In command prompt I see:

2020/12/12 17:34:17 0.2 %, 1208 Done, 0 Failed, 340420 Pending, 341628 Total, 2-sec Throughput (Mb/s): 160.7761

and it will continue to show these indicators until it seems to stop and the below strings are displayed in command prompt (not log files). I copied as much as it would allow and pasted in the reply above. The network doesn't seem to have any problems and there is good internet.

5918, 0x0)
/opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0x2074cc00, 0x0, 0x0, 0xffffffff)
/opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
/opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0x2074cc00, 0x50fe4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1255 +0x136
net/http.(*persistConn).Read(0x1348efa0, 0x50fe4000, 0x1000, 0x1000, 0x40, 0x0,
0x1)
/opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1744 +0x143

**Comment by mohsha-msft** [comment]
@zezha-msft @nakulkar-msft 
What do you think?

**Comment by stevelogik** [comment]
I was actually able to do a print screen to capture the information after the last successful upload in command prompt and I was able to see the error.

It says a byte-block is use and also fatal error: out of memory. I monitored the memory on the server and it's not maxed out and has about 40% of memory free while running azcopy. I attached the screenshot

![Memory_Error](https://user-images.githubusercontent.com/75906806/102042720-8f1c7280-3da0-11eb-8e37-ea829ad5e959.png)

**Comment by stevelogik** [comment]
@mohsha-msft Have you seen the above error "Fatal Error: Out of memory" before?

**Comment by zezha-msft** [comment]
Hi @stevelogik, which version of Windows are you running?

**Comment by stevelogik** [comment]
@zezha-msft it's actually an sbs 2011 server that is being retired

**Comment by zezha-msft** [comment]
@stevelogik ah I see, thanks for the info. 

It looks like an old non-standard distro and I'm not really sure how well Golang/AzCopy supports it. There may also be OS level limitations on how much memory/connections a process can use (this is just my guess from looking at the errors).

My suggestion would be to try to limit the concurrency and memory usage of AzCopy following the doc [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#optimize-throughput), and try to make the migration work with some trial and error.

Please let us know if you need anything else.

**Comment by stevelogik** [comment]
@zezha-msft @mohsha-msft 

After copying the data to a portable drive and using a Windows 10 machine to use azcopy with I was able to copy the data to the blob successfully. I was then able to copy the data from the Blob to the new server I setup. Thanks for your help. Ended up just being an old OS issue.

**Comment by stevelogik** [comment]
@zezha-msft @m-hn @m-mertz 

Do you all know when azcopy will support timestamps? I ended up transferring my data using another method because azcopy does not preserve time stamps

**Comment by zezha-msft** [comment]
@stevelogik could you please clarify? The blob service does not support the setting of last-modified times natively.
