### ISSUE TITLE
Add key support

### ISSUE THREAD

**Issue by brettrowberry** [Azure/azure-storage-azcopy#128]
### Which version of the AzCopy was used?
10.0.4-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
copy

### What problem was encountered?
This newer (and awesome) AzCopy allows SAS tokens and OAuth for authentication. The old AzCopy also allowed keys. Can we add key support? This makes it easier for people outside of your tenant to upload files.

### Have you found a mitigation/solution?
No

**Comment by MateuszBogdan** [comment]
Also for storage emulator this is important

**Comment by brettrowberry** [comment]
After doing a lot of testing with SAS tokens, I don't think keys are actually necessary. I agree that they are a security concern. I would actually prefer this not be implemented.
