### ISSUE TITLE
AZCopy logs missing summary when executed via Storage Explorer 

### ISSUE THREAD

**Issue by phrak** [Azure/azure-storage-azcopy#1284]
### Which version of the AzCopy was used? 
Both Azcopy 10.6.0 and 10.7.0
Storage Explorer 1.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

### What command did you run?
`azcopy copy [https://BLOB URL] [C:\Temp] --output-type=json --cancel-from-stdin --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive`
(Command copied from the Storage Explorer log file)

### What problem was encountered?
When using Storage Explorer to copy files/folders, the azcopy log does not show the Diagnostic Stats or Job Summary at the end of the log.
When running the identical azcopy command from a command prompt, the log file shows both the Diagnostic Stats and Job Summary.

### How can we reproduce the problem in the simplest way?
Using [Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/)
1. Select any file or folder located in a BLOB container.
2. Copy the file/folder to a local path
3. Open the log file
4. Observe that Diagnostic Stats and Job Summary information **_are missing_** from the bottom of the log.

Using command line:
1. Copy the "Job-command" line (line 5) from the above log file.
2. Execute `azcopy` using the same "Job-command" parameters from the log file.
3. Open the new log file
4. Observe that Diagnostic Stats and Job Summary information **_exists_** in the bottom of the log.

### Have you found a mitigation/solution?
No.
Have attempted to replace the `azcopy_[operatingsystem].exe` binary that Storage Explorer installs, with the native AZcopy.exe downloaded fresh, just in-case Storage Explorer is shipped with a different azcopy binary.
Unfortunately there was no change to the result.

**Comment by zezha-msft** [comment]
Thanks @phrak for reporting this issue! I was able to repro it.
