### ISSUE TITLE
AzCopy should not scan exclude path

### ISSUE THREAD

**Issue by SuSaiGit** [Azure/azure-storage-azcopy#1287]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy sync "https://[SourceStorageAccount].file.c
ore.windows.net/jenkins?[SASToken]" "https://[TargetStorageAccount].file.core.windows.net/jenkins-backup-6111/2020-12-15?[SASToken]" --recursive=true --preserve-smb-permissions=true --exclude-path=".cache"

### What problem was encountered?
AzCopy stopped during scanning the source storage account.
Here is the log
------------------
```
INFO: Any empty folders will be processed, because source and destination both support folders. For the same reason, permissions defi
ned on folders will be processed

Job 62b4c14a-ef11-8745-5864-611c7dbf41d9 has started
Log file is located at: /root/.azcopy/62b4c14a-ef11-8745-5864-611c7dbf41d9.log

0 Files Scanned at Source, 37619 Files Scanned at Destination
Cannot perform sync due to error: -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/
!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=DeletePending) =====
Description=409 The specified resource is marked for deletion by an SMB client., Details: (none)
   HEAD https://saa5a05e4aad859ba59d50.file.core.windows.net/jenkins/.cache/JNA/temp/jna1415416010471507020.tmp?se=2020-12-17t00%3A20
%3A39z&sig=-REDACTED-&sp=rwlc&spr=https&srt=sco&ss=f&st=2020-12-16t16%3A20%3A39z&sv=2019-12-12&timeout=901
   User-Agent: [AzCopy/10.8.0 Azure-Storage/0.8.0 (go1.13; linux)]
   X-Ms-Client-Request-Id: [3f8ba798-38e1-48c0-6440-ed5de28a75b9]
   X-Ms-Version: [2020-02-10]
   --------------------------------------------------------------------------------
   RESPONSE Status: 409 The specified resource is marked for deletion by an SMB client.
   Date: [Wed, 16 Dec 2020 16:27:28 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [3f8ba798-38e1-48c0-6440-ed5de28a75b9]
   X-Ms-Error-Code: [DeletePending]
   X-Ms-Request-Id: [7b39902d-301a-0036-58c8-d3a30e000000]
   X-Ms-Version: [2020-02-10]
```

### How can we reproduce the problem in the simplest way?
We have a Jenkins setup in which the jenkins_home is set to the file share in Azure storage account.
AzCopy sync command is used to backup the jenkins_home folder while Jenkins is running.
When Jenkins stops, the issue is also gone.
Not sure if there is another way to mark a file as DeletePending. If so, the issue could be reproduced easier.

### Have you found a mitigation/solution?
No

**Comment by siminsavani-msft** [comment]
I tried to repro this and sync with exclude-path works fine now. Please try the latest version of AzCopy and let us know if there are any issues!
