### ISSUE TITLE
Command line limitation

### ISSUE THREAD

**Issue by TrymBeast** [Azure/azure-storage-azcopy#1288]
### Which version of the AzCopy was used? 
10.6.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
This is what I'm running in powershell, and the --include-path has like 200000 folders:
azcopy copy "https://$sourceStorageAccount.blob.core.windows.net/$container$sourceSas" "https://$destinationStorageAccount.blob.core.windows.net/$container$destinationSas" --recursive --check-length=false --include-path=$includePaths

### What problem was encountered?
In powershell i see this error
> Program 'azcopy.exe' failed to run: The filename or extension is too long

### How can we reproduce the problem in the simplest way?
Just call azcopy with a very big include path for example.

### Have you found a mitigation/solution?
The only workaround I know is to call azcopy multiple times.

If it is ok to have many paths in this command I think it would be good to have an alternative like --include-path-file that I would specify it with a file path where the contents of the file would be the paths to include. This may make sense to other parameters as well.

**Comment by nakulkar-msft** [comment]
@TrymBeast AzCopy has 'list-of-files' parameter which does the same. Each file/path to be included is to be specified on a separate line. Check [here](https://github.com/Azure/azure-storage-azcopy/blob/master/cmd/copy.go#L1646)

**Comment by TrymBeast** [comment]
@nakulkar-msft I wasn't aware of this parameter as it seems to be undocumented except in the [wiki](https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer) and source code. Thanks!
