### ISSUE TITLE
add an update cli commmand

### ISSUE THREAD

**Issue by Manubi** [Azure/azure-storage-azcopy#1289]
As the title says, why not add an update command to the cli?
thanks!

**Comment by zezha-msft** [comment]
Hi @Manubi, could you please elaborate? Did you mean the [Azure CLI](https://github.com/Azure/azure-cli) or AzCopy?

**Comment by Manubi** [comment]
sorry, azcopy

**Comment by zezha-msft** [comment]
@Manubi are you looking for the sync command perhaps? https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide

If not, could you please describe how the update command works? Thank you!

**Comment by mohsha-msft** [comment]
I think @Manubi is talking about an option in AzCopy to update the AzCopy version to latest when there's a release.

**Comment by zezha-msft** [comment]
Ah I see, @Manubi  could you please confirm?

**Comment by mohsha-msft** [comment]
Hey @Manubi,

We are not planning to include this in AzCopy. However we'll include AzCopy in package managers soon.

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/1012
