### ISSUE TITLE
409 API is not yet supported for NFSv3 enabled accounts

### ISSUE THREAD

**Issue by SherryGuo1021** [Azure/azure-storage-azcopy#1290]
##### Note: The version is visible when running AzCopy without any argument
v10.1.0 and above

### What problem was encountered?
Error occured when attempting to copy data from AWS S3 bucket to blob storage account with NFSv3 enabled:
https://docs.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support

### How can we reproduce the problem in the simplest way?
1. create a storage account
2.  enable NFS 3.0 (https://docs.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support) 
3. use azcopy to copy from AWS S3 bucket to blob storage account container.

### Have you found a mitigation/solution?
Issue mitigated by copy to another blob storage without NFSv3 enabled.

**Comment by zezha-msft** [comment]
Hi @SherryGuo1021, thanks for reaching out! That is unfortunately a service limitation. I do believe that it will be solved in the future.
