### ISSUE TITLE
sync delete-destination leaves a tree of empty directories

### ISSUE THREAD

**Issue by jpvlerbe** [Azure/azure-storage-azcopy#1293]
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy sync <local_folder> <azure_folder>?<SAS> --delete-destination=true
`
### What problem was encountered?
Files on the remote folder that are not in the local folder are successfully removed from the remote folder. However the folder structure that contained those files is left in place (empty folders). This effectively causes you to be unable to really sync two directories in that sense that the end result should be two identical trees on local and remote side.

This is probably related to: #1097 and #369

**Comment by nakulkar-msft** [comment]
Being tracked by #1097
