### ISSUE TITLE
Azcopy logs show incorrect detailed error (insufficient space on the disk instead of insufficient RAM)

### ISSUE THREAD

**Issue by bazoabi** [Azure/azure-storage-azcopy#1295]
### Which version of the AzCopy was used? 

10.3.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

&$AzCopyPath copy $src $destFile --log-level="ERROR" --output-type="json" --recursive 

### What problem was encountered?

The issue is that Azcopy process doesn't have enough RAM to run on the machine, we had only 8GB free RAM available.

I checked Azcopy logs and found this error

ERR: [P#0-T#0] DOWNLOADFAILED: https://******.blob.core.windows.net/*****/***** : 000 : File Creation Error truncate
\\?\D:\**\******\******\DownloadedVHDX.vhdx: There is not enough space on the disk.

The error clearly states the there is no enough space on disk, and this is totally wrong, I am downloading 300GB blob and I have more than 1.5TB free space on disk.

After freeing up some RAM on the machine and running the command again, it worked fine.

### How can we reproduce the problem in the simplest way?

downloading 300GB+ blob on Windows 10 machine, while having only 5GB free RAM (or less than that)

### Have you found a mitigation/solution?

Freeing up RAM on the machine and then restarting the download process worked fine for me.

**Comment by gapra-msft** [comment]
This is an error message returned from the truncate call in syscall (so the filesystem is reporting this, not AzCopy), so unfortunately there isn't much we can do here. Closing for the time being.
