### ISSUE TITLE
Last modified date is not preserved when copying from blob to blob

### ISSUE THREAD

**Issue by waynebrantley** [Azure/azure-storage-azcopy#1296]
### Which version of the AzCopy was used? 
version 10.6.1 run from azure cloud shell

### Which platform are you using? (ex: Windows, Mac, Linux)
Azure cloud shell

### What command did you run?
azcopy sync "https://somesource.blob.core.windows.net/somecontainer?sv=2019-12-12&ss=b&srt=co&sp=rl&se=2020-12-31T05:59:35Z&st=2020-12-23T21:59:35Z&spr=https&sig=somesig" "https://somedest.blob.core.windows.net/imaging?sv=2019-12-12&ss=b&srt=co&sp=rwdlac&se=2020-12-31T06:00:28Z&st=2020-12-23T22:00:28Z&spr=https&sig=anothersig" --recursive=true

### What problem was encountered?
It copied everything and worked great in general.  However, the "Last Modified Date" from the source blob was lost.  The newly copied blob set last modified date to the time when it was copied.

### How can we reproduce the problem in the simplest way?
Simply copy some blobs from a container with old dates to a new container and watch the dates disapper.

### Have you found a mitigation/solution?
No.

Suggest an option for preserving original modified date/time.  There is already ``--preserve-smb-info`` but that only works if the source is SMB.  Either make that also work for blobs or add a new option.

**Comment by mohsha-msft** [comment]
Last Modified Time on blobs is the time at which blob is committed and as of now the service does not allow to set the value. We'll revisit this once the service supports Change Time API.

**Comment by invisibleninja06** [comment]
Its been over 2 years, does the service now support the Change Time API?
