### ISSUE TITLE
Copying files from a public S3 bucket -- feature request?

### ISSUE THREAD

**Issue by EgorEmeliyanov** [Azure/azure-storage-azcopy#1299]
### Which version of the AzCopy was used? 
azcopy version 10.6.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Azure Cloud Shell (bash)

### What command did you run?
`azcopy copy 'https://s3.us-east-1.amazonaws.com/irs-form-990/' 'https://myblob.blob.core.windows.net/forms-990' --recursive=true`

### What problem was encountered?
The error message:
`failed to perform copy command due to error: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables must be set before creating the S3 AccessKey credential`

I attempted to set "dummy" key and secret (they do not exist on the source bucket https://s3.us-east-1.amazonaws.com/irs-form-990/ as it is open to public for read access) by running

```
export AWS_ACCESS_KEY_ID=123
export AWS_SECRET_ACCESS_KEY=123
```

The error message has changed to:
`failed to perform copy command due to error: cannot start job due to error: cannot list objects, The AWS Access Key Id you provided does not exist in our records..`

Is the key necessary when reading from public bucket? Essentially, is there an equivalent of --no-sign-request parameter in the official AWS CLI?

### How can we reproduce the problem in the simplest way?
Run `azcopy copy 'https://s3.us-east-1.amazonaws.com/irs-form-990/' 'https://myblob.blob.core.windows.net/forms-990' --recursive=true`

### Have you found a mitigation/solution?
No

**Comment by purvi-pj** [comment]
Hi Egor,

I am also facing the same issue exactly like you have mentioned above. I tried searching it but couldn't find the solution.
Were you able to fix this issue?

My use-case is same, copying files from AWS S3 to Azure Storage.

Thanks a lot in advance!
Purvi

**Comment by EgorEmeliyanov** [comment]
Hi, @purvi-pj 

No, I moved on to other things and didn't look into this further. Let's hope Microsoft will implement this enhancement in the upcoming releases.

~Egor

**Comment by roncansan** [comment]
Do not set the variable with `set AWS_ACCESS_KEY_ID`

Set the varialbes as amazon explains
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

```
PS C:\> $Env:AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE"
PS C:\> $Env:AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
```

**Comment by paulweisjr** [comment]
> Do not set the variable with `set AWS_ACCESS_KEY_ID`
> 
> Set the varialbes as amazon explains
> https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
> 
> ```
> PS C:\> $Env:AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE"
> PS C:\> $Env:AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
> ```

This documentation needs to be updated to match the format that roncansan shared: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-s3
