### ISSUE TITLE
cannot use container level SAS token for destination when copying blobs from URLs

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-storage-azcopy#1300]
##### Note: The version is visible when running AzCopy without any argument
```
$ azcopy --version
azcopy version 10.8.0
```

### Which platform are you using? (ex: Windows, Mac, Linux)
```
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
```
azcopy copy 'https://<src>.blob.core.windows.net/<container>/<path>/?<container-level-sas-token> 'https://<dst>.blob.core.windows.net/<container>/<path>/?<container-level-sas-token> --recursive=true
```

### What problem was encountered?
```
403 This request is not authorized to perform this operation.. When Checking destination tier availability (Set blob tier) .
```
Looks like it is trying to read account level information, but I supplied a container level SAS token.  It is failing to read the available tiers before attempting to set the tier, but the tier does not need to be set (already will match).  I understand it will work if I provide an account level SAS token but that is an unnecessary restriction when the blob tier does not need to be set (it is correct by default).  It would be nice if there was a way to skip these account level checks (or only make it a warning).

### How can we reproduce the problem in the simplest way?
1. generate source and target container level SAS tokens
2. run `azcopy copy` to move files between source and target

### Have you found a mitigation/solution?
use older version of azcopy (10.4.3 or older)

**Comment by gregjhogan** [comment]
full log of the failure:
```
$ azcopy copy 'https://<src>.blob.core.windows.net/<container>/<path>/?<container-level-sas-token> 'https://<dst>.blob.core.windows.net/<container>/<path>/?<container-level-sas-token> --recursive=true

INFO: Scanning...
INFO: Failed to create one or more destination container(s). Your transfers may still succeed if the container already exists.
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job c15283b5-5215-ba4d-5b62-3e32477f5e34 has started
Log file is located at: /home/<user>/.azcopy/c15283b5-5215-ba4d-5b62-3e32477f5e34.log

INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:f23e443a-401e-00e5-15cd-df94d7000000
Time:2020-12-31T23:34:15.9161224Z, Details: 
   Code: AuthorizationFailure
   GET https://<dst>.blob.core.windows.net/<container>/<path>?comp=properties&restype=account&<container-level-sas-token>
   User-Agent: [AzCopy/10.8.0 Azure-Storage/0.10 (go1.13; linux)]
   X-Ms-Client-Request-Id: [2c842cae-fdc8-44eb-7f48-5d37ef1ff023]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Thu, 31 Dec 2020 23:34:15 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [2c842cae-fdc8-44eb-7f48-5d37ef1ff023]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [f23e443a-401e-00e5-15cd-df94d7000000]
   X-Ms-Version: [2019-12-12]



0.0 %, 0 Done, 0 Failed, 52 Pending, 0 Skipped, 52 Total, 


Job c15283b5-5215-ba4d-5b62-3e32477f5e34 summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 52
Number of Folder Property Transfers: 0
Total Number of Transfers: 52
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Cancelled
```

**Comment by adreed-msft** [comment]
Hey there!

From the first message, `403 This request is not authorized to perform this operation.. When Checking destination tier availability (Set blob tier)`. Try using `--s2s-preserve-access-tier=false` to help mitigate this. I'd like to see if this helps, because [GetAccountInfo](https://docs.microsoft.com/en-us/rest/api/storageservices/get-account-information) _should_ be callable [so long as there is a valid SAS token.](https://docs.microsoft.com/en-us/rest/api/storageservices/get-account-information#authorization)

**Comment by gregjhogan** [comment]
> [GetAccountInfo](https://docs.microsoft.com/en-us/rest/api/storageservices/get-account-information) _should_ be callable [so long as there is a valid SAS token.](https://docs.microsoft.com/en-us/rest/api/storageservices/get-account-information#authorization)

I also saw that in the docs, but as far as I can tell it is wrong.  It seems that you must use an account level SAS token (container level tokens don't work) and the account level SAS token must specify the blob service (if you specify queue service when generating the SAS, for example, it returns the same error)

I used these to draw these conclusions:
https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az_storage_account_generate_sas
https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az_storage_container_generate_sas

**Comment by adreed-msft** [comment]
The status code is AuthorizationFailure, not necessarily AuthorizationPermissionMismatch. If you try this operation again with SAS tokens generated by storage explorer, do you see similar results?

A while back, we had issues using SAS tokens with the validity times being of a higher accuracy than we parsed in the SDKs. [That was fixed in all 3 of our SDKs](https://github.com/Azure/azure-storage-blob-go/pull/169), and should be the case in 10.8.0...

The reason I make this distinction is, AuthorizationFailure means your authorization token (in this case, a SAS token) isn't valid. AuthorizationPermissionMismatch means that it is valid, but doesn't have the correct permissions.

**Comment by gregjhogan** [comment]
I am testing `https://<dst>.blob.core.windows.net/<container>/<path>?comp=properties&restype=account&<container-level-sas-token>` using `curl` so a parsing bug in the SDK should not apply, and I know the tokens are good because they work when I pass them to version 10.4.2 of `azcopy` (older version not making this account level request).

**Comment by gregjhogan** [comment]
@mohsha-msft did this issue actually get fixed, none of the above comments address the issue I reported.
