### ISSUE TITLE
Support az storage blob [upload-batch | sync] --follow-symlinks option

### ISSUE THREAD

**Issue by djc** [Azure/azure-storage-azcopy#1303]
**Is your feature request related to a problem? Please describe.**
I'm trying to update my static website from a continuous deployment process to the static website storage on Azure. The static files (CSS, images etc) live in the top of the repository, above the rest of the website contents, because they're shared with my actual project. I'd like to have a `static` symlink in the `site` directory linking to `../static` dir, and for the Azure CLI to upload the files from the static dir (symlink) if I do so.

Funnily enough, the underlying `azcopy` command outputs a warning if I try to upload/sync my symlink, saying `INFO: Skipping over symlink at /var/lib/gitlab-runner/builds/DsF6D-si/0/foo/bar/site/static because --follow-symlinks is false`. However, the Azure CLI itself does not actually recognize `--follow-symlinks`, and will thus error out with `ERROR: az: error: unrecognized arguments: --follow-symlinks`.

**Describe the solution you'd like**
It would be great if Azure CLI recognized `--follow-symlinks` and propagated it to the underlying `azcopy` invocation.

**Comment by tgalery** [comment]
Any updates on this one ? This is affecting us and it should be something relatively easy to fix. Happy to contribute as well.

**Comment by dav009** [comment]
it seems this was fixed here: https://github.com/Azure/azure-cli/pull/13589

**Comment by tgalery** [comment]
@zezha-msft maybe we can close this ?

**Comment by zezha-msft** [comment]
Thanks @tgalery @dav009 for following up on this!

**Comment by marc-hb** [comment]
> @zezha-msft do you have any plan to add --follow-symlinks in sync?

> I will log this feature request in the backlog.

Looks like
- #718
