### ISSUE TITLE
Feature request - generate SAS tokens using azcopy

### ISSUE THREAD

**Issue by aelij** [Azure/azure-storage-azcopy#1305]
Currently either PowerShell or the Azure CLI can generate storage SAS tokens. It would be beneficial for azcopy to have this ability as well, as it's a small single executable, and there are a lot of scenarios where you need a SAS token after an upload.

For example (taken from `az storage container generate-sas`):
```
azcopy generate-sas 
                                  --name
                                  [--account-key]
                                  [--account-name]
                                  [--as-user]
                                  [--auth-mode {key, login}]
                                  [--cache-control]
                                  [--connection-string]
                                  [--content-disposition]
                                  [--content-encoding]
                                  [--content-language]
                                  [--content-type]
                                  [--expiry]
                                  [--https-only]
                                  [--ip]
                                  [--permissions]
                                  [--policy-name]
                                  [--start]

```

**Comment by Rocketboy235** [comment]
+1 I would also be interested in seeing this ability added!

**Comment by landscapepainter** [comment]
+1 This would be really useful for integrating [azure blob storage feature with Skypilot](https://github.com/skypilot-org/skypilot/pull/3032) as well

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
