### ISSUE TITLE
AzureBlob File Copy Failed to execute refresh request

### ISSUE THREAD

**Issue by jvhuertas** [Azure/azure-storage-azcopy#1306]
### Which version of the AzCopy was used? 
4.179.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Loading module Az.Accounts.psm1
### What problem was encountered?
When trying to load a file from an environment behind a proxy  to a blob using AzureBlob File Copy im getting this error:

Failed to perform login command: 
2021-01-12T19:42:03.9067039Z adal: Failed to execute the refresh request. Error = 'Post https://login.windows.net/***/oauth2/token?api-version=1.0: proxyconnect tcp: dial tcp 99.99.99.999:443: connectex: No connection could be made because the target machine actively refused it.'
failed to perform copy command due to error: no SAS token or OAuth token is present and the resource is not public
2021-01-12T19:57:28.7616565Z ##[debug]ExceptionMessage: AzCopy.exe exited with non-zero exit code while uploading files to blob storage.

AzCopy.exe exited with non-zero exit code while uploading files to blob storage.'
### Have you found a mitigation/solution?
Nop. I have tried by changing the proxy to 8080 from the variable in the pipeline and removing the proxy variable at all

**Comment by zezha-msft** [comment]
Hi! Please take a look at the troubleshooting doc: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure?toc=/azure/storage/blobs/toc.json#configure-proxy-settings
