### ISSUE TITLE
Copying from Azure Files (SAS) -> Azure Blob (SAS)

### ISSUE THREAD

**Issue by amychod** [Azure/azure-storage-azcopy#1308]
### Which version of the AzCopy was used? 
AzCopy 10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`azcopy copy {file} {gen 2 blob} --recursive --from-to FileBlobFS`

### What problem was encountered?
```
failed to parse user input due to error: invalid --from-to value specified: "Fil
eBlobFS". Valid values are two-word phases of the form BlobLocal, LocalBlob etc.
  Use the word 'Blob' for Blob Storage, 'Local' for the local file system, 'File
' for Azure Files, and 'BlobFS' for ADLS Gen2. If you need a combination that is
 not supported yet, please log an issue on the AzCopy GitHub issues list.
```

### How can we reproduce the problem in the simplest way?
Try copy command with `--from-to FileBlobFS`

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi, please try FileBlob, since {gen 2 blob} is the same as {blob}=just a regular blob endpoint.
