### ISSUE TITLE
Unable to login with managed identity on remote server without UI

### ISSUE THREAD

**Issue by pgelinas** [Azure/azure-storage-azcopy#1309]
### Which version of the AzCopy was used? 
10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy login --identity

### What problem was encountered?

```
Failed to perform login command:
failed to encrypt token, Access is denied.
```

### How can we reproduce the problem in the simplest way?
1. Create an Azure VM
2. Enable system managed identity
3. Login remotely via Powershell and PSRemoting. **Do not login with RDP Prior!**
4. Download and extract Azcopy with Powershell (see bellow)
5. Got to AzCopy install location and run `azcopy login --identity`

Download and install with powershell:

``` powershell
# Step 4, download and install
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
invoke-webrequest -uri https://aka.ms/downloadazcopy-v10-windows -outfile $env:TEMP/azcopy.zip
Expand-Archive $env:TEMP/azcopy.zip C:\Users\azureuser\azcopy

# Step 5, try to login
cd C:\Users\azureuser\azcopy\azcopy_windows_amd64_10.8.0
.\azcopy.exe login --identity
```

### Have you found a mitigation/solution?
Logging in and out via RDP solves the issue and we're able to run AzCopy login. However this isn't viable since we're using AzCopy as part of an automation script and we can't just RDP on every server beforehand to make it work.
Looking through the code, the error being printed is from https://github.com/Azure/azure-storage-azcopy/blob/a3d0fe3d607255cf9fdc1ef37b15e780ec04c4ca/common/credCache_windows.go#L177-L179
And the failing method seems to be https://github.com/Azure/azure-storage-azcopy/blob/a3d0fe3d607255cf9fdc1ef37b15e780ec04c4ca/common/credCache_windows.go#L257-L264
Which, the name of the flag "cryptProtectUIForbidden" seems to have a relation to UI and that seems to indicates that we need a UI session for AzCopy to work? Not entirely sure.

**Comment by zezha-msft** [comment]
Hi @pgelinas, we have a workaround for this scenario, please refer to this wiki: https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)

**Comment by pgelinas** [comment]
@zezha-msft This didn't solve the problem, I'm actually getting a different error message now after trying the AZCOPY_AUTO_LOGIN_TYPE env variable to "MSI"

```
INFO: Scanning...
INFO: Authenticating to destination using Azure AD

failed to perform copy command due to error: get cached token failed, failed to decrypt bytes during loading token: -REDACTED- not valid for use in specified state.
```

If I RDP to the server and then retry, it works because the user running the script now has a GUI session. If I reboot the server then retry without first RDP, it fails with the above error.

**Comment by pgelinas** [comment]
Update: If I run the same thing under the SYSTEM user instead of the default azureuser it works fine.

**Comment by nakulkar-msft** [comment]
@pgelinas The automatic login mentioned by Ze did not happen. If you dont have enough permissions on the azureuser or you're automating the login/transfer use auto-login suggested by Ze. On successful login, you'll see this statement in the log. 


```
INFO: Scanning...
INFO: SPN Auth via secret succeeded.      -----------------> This line.
INFO: Authenticating to destination using Azure AD

```

This is a problem with the permissions on the user, and setting appropriate permissions for the user - like the SYSTEM user - to access keyvault should work fine.

**Comment by pgelinas** [comment]
@nakulkar-msft I believe you missed the point where I mention that azureuser works, if and only if I connect with RDP on the server at least once. It's not a user permission issue.
And I am using the auto-login mentioned via an environment variable, I don't do any other login. The line you mention, "SPN Auth", only applies when using a service-principal, which is NOT my use case; I'm using the VM identity.
![image](https://user-images.githubusercontent.com/261076/114884342-b2e5d880-9dd3-11eb-8830-f623bad9b3c2.png)
The only thing that changed between the two tries is that I have logged in via RDP.

**Comment by nakulkar-msft** [comment]
@pgelinas For a MSI auth, it would be a similar line that - MSI auth succeeded. 

I'm reopening this, to investigate for myself. But this is still a permission problem, and not azcopy.

**Comment by pgelinas** [comment]
I was curious so I did another test but with az cli:
![image](https://user-images.githubusercontent.com/261076/114888683-787e3a80-9dd7-11eb-953d-c3daf1973bed.png)
azcopy fails to login, but the az cli works fine.

**Comment by nakulkar-msft** [comment]
azcopy and az cli use different methods to save the token. For AzCopy we use windows crypt32 apis to encrypt the token before flushing to disk. And the error you've seen is because we could not encrypt.

The auto-login does not save the token instead, the token in in core when azcopy is running, and vanishes away when it exits.

**Comment by pgelinas** [comment]
O, I see, so it might be related to the login operation that is failing, but if I do an azcopy cp with auto-login it might work. Alright I can try that, I have always been testing with a login first to make sure I had the right permission to copy first.

**Comment by pgelinas** [comment]
I confirm that just doing the cp operation, without prior checking with login (ie AUTO_LOGIN) works just fine:
![image](https://user-images.githubusercontent.com/261076/114891790-30144c00-9dda-11eb-8ab2-876e69af33a0.png)
I thought I had already tried that the first time when @zezha-msft mentioned it, but I guess I must have done something wrong.
Also that the login fails with such an error was confusing to me, perhaps I could suggest adding something to the documentation linked "If you see this error, etc. etc., consider using in-memory store". That might help for anyone that stumble across this in the future.

Cheers, and thanks for the help!

**Comment by nakulkar-msft** [comment]
Umm.. @pgelinas Does not look alright :) Can you perform 'azcopy logout' and then retry? You should see that login through MSI succeeded.

```
[nakulkar@nakulkar-use-linux:~]$ env AZCOPY_AUTO_LOGIN_TYPE=MSI azcopy copy file.pdf https://storenakulkar.blob.core.windows.net/container1/
INFO: Scanning...
INFO: azcopy: A newer version 10.10.0 is available to download

INFO: Login with identity succeeded. -----------------------> This statement.
INFO: Authenticating to destination using Azure AD
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
```

**Comment by pgelinas** [comment]
Indeed, I got excited and failed to notice the Failed: 1 in the log output.

```
failed to perform logout command, no cached token found for current user
[40.77.21.16]: PS C:\images> echo $env:AZCOPY_AUTO_LOGIN_TYPE
MSI
[40.77.21.16]: PS C:\images> azcopy.exe cp .\sable.jpg https://q2e5miqo5i4xdhgkfwam.blob.core.windows.net/pgelinas-other/pgelinas-dev/config/images/static/sable.jpg
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
```

It doesn't seem to pickup the auto_login env variable....

**Comment by nakulkar-msft** [comment]
"azcopy login --identity" should report why the login failed.

**Comment by pgelinas** [comment]
```
[40.77.21.16]: PS C:\Users\azureuser\Documents> azcopy login --identity

Failed to perform login command:
failed to encrypt token, Access is denied.
```
That's the whole problem I'm having 😃 

My environment variable is probably not setup right in the session I'm doing my tests.... in another script (via Ansible) it works perfectly fine 😞 
```
changed: [pgelinas-dev-cpbld-vm] => changed=true
  cmd: azcopy.exe copy C:\images-sync\ansible.sqvptboe.kr0\config\* https://q2e5miqo5i4xdhgkfwam.blob.core.windows.net/pgelinas-other/pgelinas-dev/config/images/static/ --recursive --log-level WARNING
  delta: '0:00:02.542050'
  end: '2021-04-15 04:22:36.232555'
  rc: 0
  start: '2021-04-15 04:22:33.690505'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    INFO: Scanning...
    INFO: Login with identity succeeded.
    INFO: Authenticating to destination using Azure AD
    INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

    Job f8717e19-f5dd-6840-616d-22556418a50d has started
    Log file is located at: C:\Users\azureuser\.azcopy\f8717e19-f5dd-6840-616d-22556418a50d.log
```

Let me dig a bit more on my side, it feels like my manual tests are to blame here.

**Comment by pgelinas** [comment]
Alright, I give up 😢 
I was able to make it work once in manual testing:
```
[40.77.21.16]: PS C:\images> $env:AZCOPY_AUTO_LOGIN_TYPE="MSI"; azcopy.exe cp .\sable.jpg https://q2e5miqo5i4xdhgkfwam.blob.core.windows.net/pgelinas-other/pgelinas-dev/config/images/static/sable.jpgc
INFO: Scanning...
INFO: azcopy.exe: A newer version 10.10.0 is available to download

INFO: Login with identity succeeded.
INFO: Authenticating to destination using Azure AD
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
```
I retried **_right away_** and it failed again
```
[40.77.21.16]: PS C:\images> $env:AZCOPY_AUTO_LOGIN_TYPE="MSI"; azcopy.exe cp .\sable.jpg https://q2e5miqo5i4xdhgkfwam.blob.core.windows.net/pgelinas-other/pgelinas-dev/config/images/static/sable.jpg
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
```
I must be doing something wrong with my environment variable in Windows or whatever. It works in my automation script, good enough for me now.
