### ISSUE TITLE
[Question] Support for downloading all files and metadata

### ISSUE THREAD

**Issue by christiansgithub** [Azure/azure-storage-azcopy#131]
Is there any support using azopy, or the azure cli to download all files from a container to a local machine including metadata for each of the files?

So far I've been able to copy an entire blob storage container to another blob storage container within Azure, which works great and includes metadata. However, when I download the entire container locally to create a local backup of my data using something equivalent to:

azcopy cp "https://storageaccount.blob.core.windows.net/somecontainer" "./backupdir" --recursive=true

I seem to be able to download all files quickly in one go, but it appears that the only way to get the metadata is to query for the metadata of each file individually. With 100,000+ files in blob storage, this becomes an issue. I did try scripting this, but the individual calls were slow and so I'd need to create some custom app to do this for me. I'm expecting something like a filename.ext.metadata json file or similar that I could then use to view meta data or use along with the file to copy to another Azure storage account.

I can't find much information on how to go about getting all files and metadata locally. Is this possible or am I missing a better way of doing this? While I already have backups on Azure, I'd like to keep local copies in case of internet outage etc. and need the metadata too.

**Comment by seguler** [comment]
There is no tool that can do what you are asking, simply because it is not a common use case. You will have to write a script with Azure CLI.
