### ISSUE TITLE
Question about azcopy sync when syncing back and forth between 2 azure shares (A>B then B>A)

### ISSUE THREAD

**Issue by samcclintock** [Azure/azure-storage-azcopy#1310]
### Which version of the AzCopy was used? 
10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows and Linux

### What command did you run?

azcopy sync $VA $TX --recursive --delete-destination=true
azcopy sync $TX $VA --recursive --delete-destination=true

(where $TX and $VA are placeholders for the url+SAS)

### What problem was encountered?
I'm trying to schedule 2 one-way synchronizations between separate Azure file shares in differing geo locations.  I would like to sync from $VA to $TX and then sync $TX to $VA to ensure that both sides in sync as there will be active changes happening in both locations.. 

What I'm seeing is that when I sync in one direction, and then sync in the reverse direction, the transaction summary shows that the same number of changes are being made and the same amount of data transferred. I would expect that if $VA just pushed to $TX, then a reversed sync should only transfer unique files or files that with a more recent modification timestamp..

I've also tried adding various --preserve-* switches with no change in this behavior. 

**Questions:**

1. Is this expected behavior?
2. Is there anything that can be done to mitigate this behavior with the tools given, and if not, is a 2-way sync a feature that could be implemented in the future?

**console output:**
PS /home/scott/clouddrive/bin> ./azcopy sync $VA $TX --recursive --delete-destination=true
INFO: Any empty folders will be processed, because source and destination both support folders

Job 0329f209-4c7c-5c4d-466d-61fb231dc84f has started
Log file is located at: /home/scott/.azcopy/0329f209-4c7c-5c4d-466d-61fb231dc84f.log

97.5 %, 415 Done, 0 Failed, 8 Pending, 423 Total, 2-sec Throughput (Mb/s): 1310.898

Job 0329f209-4c7c-5c4d-466d-61fb231dc84f Summary
Files Scanned at Source: 417
Files Scanned at Destination: 417
Elapsed Time (Minutes): 0.2334
**Number of Copy Transfers for Files: 417**
Number of Copy Transfers for Folder Properties: 6
Total Number Of Copy Transfers: 423
Number of Copy Transfers Completed: 423
Number of Copy Transfers Failed: 0
Number of Deletions at Destination: 0
**Total Number of Bytes Transferred: 1048612125**
Total Number of Bytes Enumerated: 1048612125
Final Job Status: Completed

PS /home/scott/clouddrive/bin> ./azcopy sync $TX $VA --recursive --delete-destination=true
INFO: Any empty folders will be processed, because source and destination both support folders

Job 68476eae-c9fe-074f-7173-d370172d1ef0 has started
Log file is located at: /home/scott/.azcopy/68476eae-c9fe-074f-7173-d370172d1ef0.log

99.8 %, 422 Done, 0 Failed, 1 Pending, 423 Total, 2-sec Throughput (Mb/s): 0

Job 68476eae-c9fe-074f-7173-d370172d1ef0 Summary
Files Scanned at Source: 417
Files Scanned at Destination: 417
Elapsed Time (Minutes): 0.467
**Number of Copy Transfers for Files: 417**
Number of Copy Transfers for Folder Properties: 6
Total Number Of Copy Transfers: 423
Number of Copy Transfers Completed: 423
Number of Copy Transfers Failed: 0
Number of Deletions at Destination: 0
**Total Number of Bytes Transferred: 1048612125**
Total Number of Bytes Enumerated: 1048612125
Final Job Status: Completed

### How can we reproduce the problem in the simplest way?
Sync from one azure file share to another, then do it again in the reverse direction.

**Comment by samcclintock** [comment]
in all my cutting and pasting, i forgot to actually pose questions:

1. Is this expected behavior.
2. Is there anything that can be done to mitigate this behavior with the tools given, and if not, is a 2-way sync a feature that could be implemented in the future?

**Comment by samcclintock** [comment]
On reflection, it looks like perhaps this related to the timestamps not being preserved.  A>B updates all the timestamps, thus making B look newer.. Simple issue, so is there a solution available now or on the horizion?

**Comment by samcclintock** [comment]
On reflection, it looks like perhaps this related to the timestamps not being preserved. A>B updates all the timestamps, thus making B look newer..  Is there a solution for preserving the timestamps available now or on the horizon?

**Comment by zezha-msft** [comment]
Hi @samcclintock, thanks for reaching out!

Unfortunately 2-way syncs are not supported right now. The reason for that is we are unable to set timestamps as you pointed out.

Yes, I think the service is going to allow us to set the time stamps in the future, we will work on a solution as soon as they add the feature.
