### ISSUE TITLE
Copy from arbitrary URL direct into Container

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-storage-azcopy#1314]
`azcopy version 10.6.1`

Hey Guys,

I have an ISO on a public server. I now want to copy this to a StorageAccount. You could call it a "remote wget". Is there a practical solution?

That's all what I've found about this; [Copy blobs between Azure storage accounts by using AzCopy v10](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs-copy)

```powershell
$URL = "https://foo.bar/myawesomeimage.iso"
$Container = "iso"
$SAS = "https://xxx.blob.core.windows.net/$Container/?...."
azcopy copy $URL $SAS
```
Result: `failed to perform copy command due to error: cannot start job due to error: cannot scan the path /home/user/https://foo.bar/myawesomeimage.iso, please verify that it is a valid.`

**My current Workaround:**

```powershell
$URL = "https://foo.bar/myawesomeimage.iso"
$File = ($($URL.Split("/")[3]))
$Container = "iso"
wget $URL
$SAS = "https://xxx.blob.core.windows.net/$Container/?...."
if ($?) { azcopy copy $File $SAS }
```

**Comment by zezha-msft** [comment]
Thanks for reaching out!

We do not yet support arbitrary sources (outside of Azure and S3), but we'll consider adding this in the future.

**Comment by nakulkar-msft** [comment]
@Gill-Bates If the URL does not require auth, you can try
azcopy copy $URL $DST --from-to=BlobBlob

**Comment by nakulkar-msft** [comment]
Closing the request, we do not plan to add support for arbitrary URLs any time soon. However, if the source does not require authentication, please use --from-to parameter in azcopy.
