### ISSUE TITLE
az copy --put-md5. MD5 hash is calculated and stored automatically.

### ISSUE THREAD

**Issue by abilous-ti** [Azure/azure-storage-azcopy#1315]
### Which version of the AzCopy was used?
10.8.0
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.8.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy copy 'local-file-path' 'https://storageaccountname.file.core.windows.net/file-share-name/file-name?SAS-token'

### What problem was encountered?
Microsoft documentation says that MD5 hash is **not calculated and not stored automatically** if option --put-md5 is not specified. 
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-files

** However when file is uploaded into Azure Storage Container, Content-MD5 property of the uploaded has value**
![image](https://user-images.githubusercontent.com/22077679/104908916-cbd71d00-598f-11eb-9da3-f3b0eec44ac4.png)

### How can we reproduce the problem in the simplest way?
**Run command**
_azcopy copy 'local-file-path' 'https://storageaccountname.file.core.windows.net/file-share-name/file-name?SAS-token'_
**Check Content-MD5 property of the uploaded file in Azure Portal**

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @abilous-ti, thanks for reaching out!

For smaller blobs (<256MB IIRC), the service computes it automatically for you.
