### ISSUE TITLE
azcopy logfile for log-level WARNING/ERROR missing summary and "azcopy jobs show" missing  "Elapsed Time (minutes)" and "TotalBytesTransfered"

### ISSUE THREAD

**Issue by victorvogelpoel** [Azure/azure-storage-azcopy#1319]
### Which version of the AzCopy was used? 
Azcopy 10.6.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 

### What command did you run?
azcopy copy \\fileshare\path https://something.blob.core.windows.net/path?sastoken

### What problem was encountered?
azcopy logfile with default log-level contains a Job summary at the end with "Elapsed Time (minutes)" and "TotalBytesTransfered", which is good!
However, azcopy logfile with ERROR or WARNING log-level does NOT contain a summary, which is a miss.

"azcopy jobs show <jobid>" does shows a job summary, but fields  "Elapsed Time (minutes)" and "TotalBytesTransfered" are missing!

Expected:
Logfile contains a job summary for a azcopy job with ERROR or WARNING log-level, including fields "Elapsed Time (minutes)" and "TotalBytesTransfered".
azcopy jobs show contains the "Elapsed Time (minutes)" and "TotalBytesTransfered" fields

### How can we reproduce the problem in the simplest way?
Execute a azcopy with default log-level and another with ERROR log-level. 

### Have you found a mitigation/solution?
No

**Comment by gapra-msft** [comment]
Hi @victorvogelpoel I believe most of your requests above are doable. The one thing that may be difficult to add support for is displaying Elapsed Time in jobs show. My understanding is that information is not persisted in our job plan files, so it isn't something we can support.
