### ISSUE TITLE
Secret credentials exposed when passed via command line

### ISSUE THREAD

**Issue by KubaO** [Azure/azure-storage-azcopy#132]
### Which version of the AzCopy was used? 
10.0.4
### Which platform are you using? (ex: Windows, Mac, Linux)
CentOS 6
### What command did you run?
azcopy cp https://REMOVED.blob.core.windows.net/backup/Y5TvrqGibF1mmGQl1UKV6sJgcp9U8Bn7-_boot.tar.gz?SAS_REMOVED --overwrite=false --block-size=25165824
ps auxw|grep azcopy
### What problem was encountered?
Secret credentials visible in ps output.
### How can we reproduce the problem in the simplest way?
Run azcopy with any secret parameter on the command line, the inspect ps output.
### Have you found a mitigation/solution?
Azcopy should support response files and/or secret (e.g. SAS) input via environment variables.

**Comment by seguler** [comment]
Could you use OAuth/AAD login instead ? The tokens are getting encrypted in that case. 

We do not have a plan to encrypt the SAS tokens. They are limited scope, and validity anyway.
