### ISSUE TITLE
Get older versions binaries

### ISSUE THREAD

**Issue by kobibarhanin** [Azure/azure-storage-azcopy#1321]
Can you please provide information regarding how to get older versions of azcopy? 

Specifically I'm looking for version 10.0.5 for linux and i couldn't find it anywhere.

Thanks.

**Comment by zezha-msft** [comment]
Hi @kobibarhanin, is there a particular reason why you need that older version? It's not a GA version and I'd highly recommend you to use the latest version instead.

**Comment by mohsha-msft** [comment]
Idle. Closing it

**Comment by fragolinux** [comment]
> Hi @kobibarhanin, is there a particular reason why you need that older version? It's not a GA version and I'd highly recommend you to use the latest version instead.

it would be good for versioning, if we want to stay to a specific version for repeatability and reproducibility... i'd like to create an "asdf" plugin for this, but can't get a pattern for urls, as they contain both a date and the version, and the date is sometimes the release one, other times the sources one, others completely unrelated (example, v10.3.4 was released on july 1st 2020, but date in url is of 24th january! https://azcopyvnext.azureedge.net/release20200124/azcopy_linux_amd64_10.3.4.tar.gz )

**Comment by zezha-msft** [comment]
Hi @fragolinux, we hide the older versions on purpose so that users are more inclined to upgrade and pick up the improvements and bug fixes. 

You could pin your workflow to a static link if you wish to: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#obtain-a-static-download-link
