### ISSUE TITLE
Issue uploading large file

### ISSUE THREAD

**Issue by Quip16** [Azure/azure-storage-azcopy#1326]
##### Note: The version is visible when running AzCopy without any argument
10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy cp "dc1.vbk" "https://bdrbackup.blob.core.windows.net/dc1/dc1.vbk{SAS Token}" --cap-mbps 10 --block-size-mb 100                                                                                                                                                                                

### What problem was encountered?
The job will run for several minutes but then fails. I can upload the file via the Azure GUI interface, but I would like to be able to accomplish this task via azcopy. 

I've attached a log file from the job.
[logfile.log](https://github.com/Azure/azure-storage-azcopy/files/5934454/logfile.log)

### How can we reproduce the problem in the simplest way?
Try uploading a file approximately 1.5TB in size. 

### Have you found a mitigation/solution?
No. Any help would be greatly appreciated!

**Comment by zezha-msft** [comment]
Hi @Quip16, thanks for reaching out.

The error was:
Put https://bdrbackup.blob.core.windows.net/dc1/test.vbk?blockid=ZDBlOGJkYTYtZDRlZi0wYzQ1LTc0ZmYtNmM1ZDYzMTc4YjM5&comp=block&se=2023-01-02T01%3A19%3A18Z&sig=-REDACTED-&sp=rwdlacx&spr=https&srt=sco&ss=b&st=2021-02-02T17%3A19%3A18Z&sv=2019-12-12&timeout=901: **read tcp 192.168.111.194:49918->20.150.87.36:443: wsarecv: An existing connection was forcibly closed by the remote host.**

Are you running the copy via a proxy of some sort?

**Comment by Quip16** [comment]
No, my connection is not using a proxy to my knowledge.

**Comment by zezha-msft** [comment]
Thanks for the confirmation @Quip16.

We've seen similar issues in the past. In general, limiting the concurrency should solve the issue. Please refer to the doc [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure?toc=/azure/storage/blobs/toc.json#optimize-throughput).
