### ISSUE TITLE
are there two versions of azcopy.exe or can I use either to upload PSTs for import into MS365?

### ISSUE THREAD

**Issue by osirisx3** [Azure/azure-storage-azcopy#1329]
A question on azcopy.exe .  I can't find explicit information on the differences - if any - between azcopy.exe used to upload PST files into ingestiondata repository and azcopy.exe used to upload/downloads data to/from blob storage.

They appear to have separate command sets, so are they really different or can I use version 10.6.0 to upload PST files to ingestion data?

Is there a --cap-mbps throttle option in both versions or just one?

Appreciate any help. Thanks!

**Comment by nakulkar-msft** [comment]
@osirisx3 There is only one supported version of AzCopy - V10, on this repo. The other seems to be older V8 version. You should use V10 for both. The latest version is [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10)

**Comment by osirisx3** [comment]
Hello Nakulfar,

Thanks you very much for your quick reply. I am still puzzled though. When I am attempting to upload PST files in the proetection.office.com portal, the download version is ver 8.0.  See attachment 1:

![azcopy ver 8](https://user-images.githubusercontent.com/49599723/107410114-beb5e400-6b71-11eb-9942-0a19a39f0b3d.jpeg)

Moreover, I can't seem to get the script we use successfully in version 8, to run inside ver 10.06.0 to upload PSTs. see attachment:

![azcopy ver10](https://user-images.githubusercontent.com/49599723/107410090-b8276c80-6b71-11eb-97ac-999ffe59af85.jpeg)

The reason why we are asking is because we would like to use the bandwidth throttle switch in Version 10 as there does not appear to be such a switch in version 8 BUT it would seem version 8 is only used to upload PST files not for general storage requirements.

I'm wondering if ver 8 is specifically for uploading PST files and ver 10 for general storage management. Does anyone know for user?

Thanks again for your help!
