### ISSUE TITLE
Copy fails when storage account firewall is enabled

### ISSUE THREAD

**Issue by bahadir-be** [Azure/azure-storage-azcopy#1331]
##### Note: The version is visible when running AzCopy without any argument
_azcopy version 10.8.0_
### Which platform are you using? (ex: Windows, Mac, Linux)
_Windows 2016 server VM from Azure._
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

.\azcopy.exe copy "E:\DumpTools\" "https://dmp101226p01.blob.core.windows.net/crashdump/?sv=SASTOKEN" --recursive=true

### What problem was encountered?
Copy fails when storage account firewall is enabled.
### Have you found a mitigation/solution?
It was working when disabled the storage account firewall.

![image](https://user-images.githubusercontent.com/62173919/107360204-e5bed800-6ad5-11eb-9845-2bd51655b861.png)

![image](https://user-images.githubusercontent.com/62173919/107360213-ea838c00-6ad5-11eb-9737-72102fb84464.png)

**Comment by nakulkar-msft** [comment]
Hi @bahadir-be the IP of the machine where AzCopy runs should be added to allow-list on the storage account. Retry after you've completed this step.

**Comment by bahadir-be** [comment]
Machine running without Public IP and on different Tenant!
