### ISSUE TITLE
AzCopy Copy - Preserve SMB Info - Modified date changes after reading the file

### ISSUE THREAD

**Issue by wrozansk** [Azure/azure-storage-azcopy#1332]
##### Note: The version is visible when running AzCopy without any argument
10.7.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

$app = 'C:\Program Files\AzCopy\azcopy.exe'
            $arg1 = 'copy'
            $arg2 = '\\\myfiles\myfolder\\*'
            $arg3 = 'https://storageaccountname.file.core.windos.net/myfolder?sv=SharedAccessSignature'
            $arg4 = '--recursive'
            $arg5 = '--preserve-smb-info'

            & $app $arg1 $arg2 $arg3 $arg4 $arg5

### What problem was encountered?

The option to preserve SMB info, specifically preserving the Modified Date parameter, only works until someone tries to access the copied file, or even read it's properties from Azure Storage.
The Modified Date parameter then immediately changes to the time AzCopy was run.

### How can we reproduce the problem in the simplest way?

By running a similar command and coping something from the local computer to Azure File Share.

### Have you found a mitigation/solution?

No

**Comment by cg6** [comment]
Problem also exists with azcopy 10.9.0

Files were moved to Azure File Storage with 
`azcopy.exe copy $sourceParam $destParam --preserve-smb-info=true --preserve-smb-permissions=true`

The share was then made accessible via AD integration and the "Storage File Data SMB Share Reader" role. Activity via the read only role is causing modified dates to revert to the time azcopy was run.

### Test with Powershell works
The problem doesn't occur when using Powershell, so it appears to be an issue with azcopy, not the file service.
Works: `Set-AzStorageFileContent -PreserveSMBAttribute -Share $fileShare -Source $fileName -Path $destPath`

**Comment by lylebowe** [comment]
Worth noting, I was seeing this issue also, so then copied the files using ROBOCOPY.  I noticed the exact same behavior as when using AzCopy, thus reverted to XCOPY, which worked as expected.  My notes may be found here: https://docs.microsoft.com/en-us/answers/questions/304363/undesired-updates-to-azure-file-share-last-modifie.html

**Comment by lylebowe** [comment]
I just received an update MSFT has acknowledged the issue and is working on a fix.  https://docs.microsoft.com/en-us/answers/questions/304363/undesired-updates-to-azure-file-share-last-modifie.html

**Comment by zezha-msft** [comment]
Sorry for the inconvenience.

There was a breaking change (new feature) on the service to update SMB timestamps (e.g. last-write-time) when files are updated over the REST endpoint. The reason for the undesired behavior is that AzCopy first creates the file with the desired timestamps and then proceeds to write to the file, thus update the timestamps unintentionally.

They have since rolled back this change. We will update AzCopy to accommodate the service change when it's enabled again.

**Comment by stas-lucky** [comment]
Was that problem finally fixed? I have issues with preserving timestamps.
Using Ubuntu (WSL, 20.04) for copying.
azcopy version is 10.11.0

**Comment by jingeno** [comment]
The problem still seems to be occurring with AzCopy version 10.12.2.
