### ISSUE TITLE
Errors in Event Log after every execution of azcopy

### ISSUE THREAD

**Issue by misaz** [Azure/azure-storage-azcopy#1333]
##### Note: The version is visible when running AzCopy without any argument

10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

```
azcopy copy "test.txt" "https://xxxxxxx.blob.core.windows.net/yyyyyyyy/zzzzz?sas"
```

### What problem was encountered?

Every execution of azcopy writes error with message "The operation was completed successfully." (I freely translated it to english because original messages was localized and I am using Czech Windows) to system log (It is the log accessible via Event Viewer using `Win + R` > type `eventvwr` > `Enter` > select `Application` log in right panel).

While message says "success" it is loged as error. Messsage with text "success" is loged also in case of azcopy failure (for example in case of invalid parameters).

![azcopy eventvwr logs](https://user-images.githubusercontent.com/2937706/107481936-435b2f00-6b7f-11eb-80ab-b58886e837a9.png)

(`Chyba` is `Error` in english; `Operace byla dokončena úspěšně.` is `The operation was completed successfully. ` in english).

azcopy itself works good but systme log is "spamed" by error messages from every (even successfull) execution of azcopy.

### How can we reproduce the problem in the simplest way?

Execute any azcopy copy command (maybe it can be aslo triggered by some other azcopy commands, but i have tried only copy).

### Have you found a mitigation/solution?

no

**Comment by mohsha-msft** [comment]
Hey @misaz 

Thanks for reaching out. We have addressed this issue in the latest release of AzCopy `10.10.0` . We now offer knob to disable application logging (Syslog/Windows Event Log). Please refer the changelogs [here](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.10.0)
