### ISSUE TITLE
How to upload/modify a blob that has a lease?

### ISSUE THREAD

**Issue by hongooi73** [Azure/azure-storage-azcopy#1336]
I'm probably missing something very basic, but how do you specify a lease when uploading or updating a blob? I ran `azcopy copy --help` and there was nothing on this topic.

### Which version of the AzCopy was used? 

10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows 10

### What command did you run?

`azcopy copy --help | grep lease`

**Comment by mohsha-msft** [comment]
Hey @hongooi73 ,

Thanks for reaching out!
We do not support modifying/overwriting the blob which has active lease on it.
