### ISSUE TITLE
Problem with $ in the container name

### ISSUE THREAD

**Issue by heitara** [Azure/azure-storage-azcopy#1338]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac

### What command did you run?
./azcopy copy test.azure.txt "https://something.blob.core.windows.net/$web"

### What problem was encountered?
The `$` sign  is not properly handled when it's part of the container name. I got the command from the Microsoft Azure Storage Explorer. 
**Other special symbols might not be escaped properly as well.**

### How can we reproduce the problem in the simplest way?
Create a container with name that contains `$`. E.g. `$web`. 

### Have you found a mitigation/solution?
Yes. I've escaped the `$` sign and the following command works fine.

./azcopy copy test.azure.txt "https://something.blob.core.windows.net/%24web"

**Comment by mohsha-msft** [comment]
Hey @heitara,

Thanks for reaching out!

Please refer this [link](https://docs.microsoft.com/en-us/rest/api/storageservices/Naming-and-Referencing-Containers--Blobs--and-Metadata#container-names) to find the valid character set for naming containers. `$` is not a valid charset for naming container.

**Comment by heitara** [comment]
Thanks!

**Comment by heitara** [comment]
I think, the following article https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website describes how a container with $ sign can be created. Could you please re-open the issue, because this site and the one you've sent are not in sync. Obviously, there is a problem :). I'm not sure why there are some restrictions of the symbols in the name(someone has decide so), when such container can exist. Maybe the rules should be revisited.

**Comment by heitara** [comment]
@mohsha-msft could you please check the following article https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website and either update it or re-open the issue.
