### ISSUE TITLE
Azure blob AuthorizationPermissionMismatch

### ISSUE THREAD

**Issue by kavya-5** [Azure/azure-storage-azcopy#1343]
##### Note: The version is visible when running AzCopy without any argument
10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
az login
azcopy copy "C:\Users\a.cs" "https://<storage account name>.blob.core.windows.net/<storage container name>" --recursive=true

### What problem was encountered?
INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.

Time:2021-02-24T07:06:01.4666673Z, Details:
   Code: AuthorizationPermissionMismatch
   PUT https://<name>.blob.core.windows.net/<name>/a.cs?timeout=901
   Authorization: REDACTED
   Content-Length: [188]
   User-Agent: [AzCopy/10.8.0 Azure-Storage/0.10 (go1.13; Windows_NT)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Md5: []
   X-Ms-Blob-Content-Type: [text/plain]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [26bce23f-eb78-4646-6493-ce2efe91ec94]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Content-Length: [279]
   Content-Type: [application/xml]
   Date: [Wed, 24 Feb 2021 07:06:00 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [26bce23f-eb78-4646-6493-ce2efe91ec94]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [975f1acd-d01e-0082-647b-0aa9ec000000]
   X-Ms-Version: [2019-12-12]

0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,

Job  summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Cancelled

### Have you found a mitigation/solution?
no

**Comment by ricardo-overhaul** [comment]
@kavya-5 what was the solution?
