### ISSUE TITLE
AzCopy v10.8.0 shows errors in EventID=0  although files are being copied on Azure

### ISSUE THREAD

**Issue by jiteshkumargouthamchand** [Azure/azure-storage-azcopy#1345]
### Which platform are you using? (ex: Windows, Mac, Linux)  -Windows 2012 [R2]([url](url))
     $result = .\azcopy copy $sourceFolder $jdaVmDest  --recursive=true --log-level="ERROR"  --include-pattern='PJR*' --output-type='json' --overwrite="ifSourceNewer"
### What command did you run?
     $result = .\azcopy copy $sourceFolder $jdaVmDest  --recursive=true --log-level="ERROR"  --include-pattern='PJR*' --output-type='json' --overwrite="ifSourceNewer"
### How can we reproduce the problem in the simplest way?Try simple Azcopy and see if it errors
![AzCopyv10 8Errors](https://user-images.githubusercontent.com/45585264/109093642-8cf26080-76cd-11eb-9016-dce9c829e93c.PNG)

**Comment by jiteshkumargouthamchand** [comment]
Any updates on this ?

**Comment by jiteshkumargouthamchand** [comment]
@zezha-msft ; @John.Rusk@microsoft.com

**Comment by zezha-msft** [comment]
Hi @jiteshkumargouthamchand, the tool makes certain checks such as verifying whether the container exists or we should create it. These errors are expected and tolerated.

We'll offer a knob in 10.10 to disable the syslogs (already being tracked).

**Comment by jiteshkumargouthamchand** [comment]
Thanks Zezha. These errors were not noticed in 10.3.x version.

**Comment by jiteshkumargouthamchand** [comment]
Please notify us once 10.10 is released so that we could update the utility on our end. Thanks @zezha-msft 


> Hi @jiteshkumargouthamchand, the tool makes certain checks such as verifying whether the container exists or we should create it. These errors are expected and tolerated.
> 
> We'll offer a knob in 10.10 to disable the syslogs (already being tracked).

**Comment by zezha-msft** [comment]
@jiteshkumargouthamchand Please use the watch feature on this Github repo to get updates on releases. You can customize what kind of notification you get.

**Comment by jiteshkumargouthamchand** [comment]
Can you please confirm if this has been fixed in v10.10?

**Comment by zezha-msft** [comment]
@jiteshkumargouthamchand  yes the environment variable is AZCOPY_DISABLE_SYSLOG, please set it to true.
