### ISSUE TITLE
Incorrect work with AZCOPY_LOG_LOCATION and AZCOPY_JOB_PLAN_LOCATION

### ISSUE THREAD

**Issue by maxinfosoft** [Azure/azure-storage-azcopy#1346]
### Which version of the AzCopy was used? 
azcopy 10.8, CentOS 7.x

### What problem was encountered?
Logs:
+ azcopy list 'https://storage01.blob.core.windows.net/upload/****'
panic: mkdir /mnt/extdisk/.azcopy/plans/: permission denied

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/common.PanicIfErr(...)
	/home/vsts/work/1/s/common/lifecyleMgr.go:553
main.main()
	/home/vsts/work/1/s/main.go:64 +0x5d1

### How can we reproduce the problem in the simplest way?
Set variables /etc/environment:
AZCOPY_LOG_LOCATION="/mnt/extdisk/.azcopy/"
AZCOPY_JOB_PLAN_LOCATION="/mnt/extdisk/.azcopy/plans/"

###
p.s. The rights don't matter - I've tried with 777 too. I also tried creating directories in advance with the permissions 777 - the error still occurs randomly. Sometimes files are created, but an error can occur at any time during the pipeline and azcopy execution.

**Comment by siminsavani-msft** [comment]
Hi @maxinfosoft ! Sorry for the delay in getting back to you. Could you please try the latest azcopy version (https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.16.2) if you haven't already and let us know if it works!
