### ISSUE TITLE
Azcopy won't work on the mac as it is blocked by the "allow apps downloaded from appstore and identified developers" policy

### ISSUE THREAD

**Issue by PaulG77** [Azure/azure-storage-azcopy#1349]

**Comment by PaulG77** [comment]
The fact that this doesn't seem to be notarized seems a significant oversight. If AZcopy is used to perform admin tasks on mac (e.g. used by a script in Intune) then users will see on the following error message: - 
![image](https://user-images.githubusercontent.com/73136722/109480318-4ad17200-7a73-11eb-8f77-524422b50bd7.png)

This also seem inconsistent with other software for example Powershell. The Powershell build process seems to have the notarization step built in: - 
https://github.com/PowerShell/PowerShell/blob/master/tools/releaseBuild/azureDevOps/templates/mac-file-signing.yml

**Comment by mohsha-msft** [comment]
Hey @PaulG77 ,

AzCopy version `10.10.0` has been released and we've taken care of notarizing the binaries. Please go ahead and use it. Reach out to us if the issue persists.

**Comment by jimmyville** [comment]
I'm having the same issue with the latest version. How can I download 10.10 if that version was notarised?

**Comment by mohsha-msft** [comment]
Hey @jimmyville ,

Which version are you using? AFAIK our latest MAC builds are signed by Windows ESRP. Try downloading 10.14.1 and give it a go maybe?

**Comment by jimmyville** [comment]
I've downloading the latest version from the Getting Started page: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

I'm still receiving the unidentified developer error.

<img width="372" alt="Screen Shot 2022-03-31 at 7 22 15 pm" src="https://user-images.githubusercontent.com/9334724/161011560-f90e0099-e204-4b15-ae6a-80995c340053.png">

**Comment by kilteer** [comment]
I am encountering the same issue with version 10.16.1 (azcopy_darwin_amd64_10.16.1.zip was the download from Microsoft)

**Comment by kush-hbk** [comment]
the issue still exists as I tried downloading the latest - azcopy_darwin_amd64_10.17.0 
from https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10 for macOS

**Comment by mehdiharoon** [comment]
Yeah I tried it today and it still gives this error

**Comment by v-bafa** [comment]
Same here.

**Comment by stevenzim** [comment]
Same here
