### ISSUE TITLE
Is there support for copying folder from Blob storage to ADLS Gen2?

### ISSUE THREAD

**Issue by Niharikadutta** [Azure/azure-storage-azcopy#1350]
### Which version of the AzCopy was used? 
AzCopy 10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy copy "https://source.blob.core.windows.net/container/path/to/folder/SAS-token" "https://destination.dfs.core.windows.net/container/path/to/folder/SAS-token" --from-to BlobBlobFS --recursive

### What problem was encountered?
failed to parse user input due to error: invalid --from-to value specified: "BlobBlobFS". Valid values are two-word phases of the form BlobLocal, LocalBlob etc.  Use the word 'Blob' for Blob Storage, 'Local' for the local file system, 'File' for Azure Files, and 'BlobFS' for ADLS Gen2. If you need a combination that is not supported yet, please log an issue on the AzCopy GitHub issues list.

### How can we reproduce the problem in the simplest way?
Copy a folder from Azure Blob storage account to ADLS Gen2 account

### Have you found a mitigation/solution?
No, transferring to local doesn't work due to a different error as seen in log file:
`: File Creation Error mkdir \\?\C:\C:\workspace\Projects\Synapse-GPUs\Benchmarking\tpcds_datasets\tpcds_sf3000-parquet\useDecimal=false,useDate=true,filterNull=false\store_sales\ss_sold_date_sk=2451817: The filename, directory name, or volume label syntax is incorrect.
`

**Comment by mohsha-msft** [comment]
Hey @Niharikadutta,

Can you share with me the command which you were trying to transfer to local? It seems the local file path is incorrect or it contain special characters which need to be handled separately

**Comment by nakulkar-msft** [comment]
There is nothing adls2 specific metadata to be carried from a non-HNS account to a HNS account. Which is why to transfer from blob to Gen2, we use .blob endpoints on both sides. A folder on blobstorage is a virtual path on the source. It does need any further support. Your command should be

azcopy copy https://acc1.blob.core.windows.net/mycontainer/myfolder https://accgen2.blob.core.windows.net/mycontainer/ --recursive
