### ISSUE TITLE
This library breaks "Semantic Import Versioning" 

### ISSUE THREAD

**Issue by marwan-at-work** [Azure/azure-storage-azcopy#1351]
### Which version of the AzCopy was used? 
Source/master or latest 

##### Note: The version is visible when running AzCopy without any argument
v10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac (though it doesn't matter)

### What command did you run?
go install github.com/Azure/azure-storage-azcopy@v10.9.0

### What problem was encountered?

```
$ go install github.com/Azure/azure-storage-azcopy@v10.9.0
go install github.com/Azure/azure-storage-azcopy@v10.9.0: github.com/Azure/azure-storage-azcopy@v10.9.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v10
```

### How can we reproduce the problem in the simplest way?
Run the above command :) 

### Have you found a mitigation/solution?
Yes, you must follow the Semantic Import Versioning rule for Go Modules. See more here: https://github.com/golang/go/wiki/Modules#semantic-import-versioning

It'll be up to you whether you want to call the module path change a breaking one (which it is) and bump a major version or "retract" the incorrect versions and issue a new minor one.

**Comment by zezha-msft** [comment]
Thanks for your patience, 10.10 has been released and the issue should now be fixed.
