### ISSUE TITLE
Publish Mac/ARM (M1) + Universal binaries

### ISSUE THREAD

**Issue by ItalyPaleAle** [Azure/azure-storage-azcopy#1352]
Currently, builds are generated by Azure Pipelines using Go 1.15 and for macOS, they are limited to amd64. These builds run on ARM (M1) MacBooks only via emulation (Rosetta).

Go 1.16 is now stable and includes support for the ARM target for macOS. It would be great if you could publish official binaries for that too!

**Comment by zezha-msft** [comment]
Thanks for reaching out!

Adding official support for a new platform requires certain conditions, we will evaluate the situation and get back to you shortly.

**Comment by odidev** [comment]
I am working on adding ARM64 support for docker image for **andreasleicher/mongo-azure-backup** package, which requires **azure-storage-azcopy** binary.

I have successfully built the **azure-storage-azcopy** binary for arm64 using the command **GOARCH=arm64 GOOS=linux go build -o azcopy_linux_arm64** on my local machine.

It will be very helpful if the azcopy arm64 binary is released. If required, I am happy to contribute.

**Comment by zezha-msft** [comment]
That's great to hear! @odidev

We are really interested in hearing about your test experience, have you exercised the tool on the arm platform? Any issues so far?

**Comment by AdamCoulterOz** [comment]
This needs to be fully supported ... you can't just ignore macOS because of temporary rosetta 2 support which is only there as a stop gap.

**Comment by zezha-msft** [comment]
Thanks for the feedback @AdamCoulterOz. Have you encountered any other difficulty with using the AMD64 build on Mac M1?

I see that we mistakenly closed the issue, as we did release a preview build of ARM Linux, but not for Apple M1.

**Comment by Jtango18** [comment]
Adding my voice, that I'm keen to see a native ARM-64 build for Apple developers released. I understand this is also a dependency for Azure Storage Explorer to be able to release a Native build too. If there is assistance I can offer in getting this in peoples hands, please reach out.

**Comment by zezha-msft** [comment]
@Jtango18 @craigpearson could you please help us understand the current pain point? What are the steps to get AzCopy running on your M1 machine?

Sorry, our team currently does not have an M1 machine.

**Comment by ItalyPaleAle** [comment]
@zezha-msft looks like this repo is now using Go 1.17.x which is already capable of outputting darwin/arm64 code.

You should be able to create a new build from macOS and add `GOOS=darwin GOARCH=arm64`, and you have M1 support :)

**Comment by AdamCoulterOz** [comment]
@zezha-msft Amazon will be happy to help you with that ;-)

https://aws.amazon.com/ec2/instance-types/mac/

**Comment by Jtango18** [comment]
> @Jtango18 @craigpearson could you please help us understand the current pain point? What are the steps to get AzCopy running on your M1 machine?
> 
> Sorry, our team currently does not have an M1 machine.

I'm not sure I agree there are "main points" per se. But ultimately it would be good to see the performance improvement in both AZ Copy and its downstream consumers that would be enabled by moving to a native ARM64 build rather than relying on Rosetta2 to do the heavy lifting for us. 

Do we have an internal MS reason enforcing that we have to build/publish using ADO? Could we look at migrating Build/Publish to Github Actions given they have M1 runners available? 

Spitballing ideas here, but as I said, happy to help where I can

**Comment by Jtango18** [comment]
> @Jtango18 @craigpearson could you please help us understand the current pain point? What are the steps to get AzCopy running on your M1 machine?
> 
> Sorry, our team currently does not have an M1 machine.

I wouldn't say there's a pain point per-se, just that folks are keen to get a native Apple Silicon build and performance enhancements that brings for M1/2 machines for AZ Storage Copy and it's upstream consumers (Azure Storage Explorer etc)

Hopefully GitHub will have AppleSilicon hosted runners rolled out [soon](https://github.com/github/roadmap/issues/528) and we can potentially move the Mac build onto one of those runners rather than ADO perhaps?

I forked this repo, built and ran all the tests and can confirm that it does indeed work as expected, we just need an automation approach.

**Comment by zezha-msft** [comment]
Thank you @Jtango18  and the others for your feedbacks. We will take them into account for prioritization of this work.

**Comment by Wicked-Weasel** [comment]
Just adding my 2c. Use Azure Storage Explorer quite a bit and would be great to get a native version.... Appreciate this is a core component and anything that expedites this would be really well received. It is really apparent now with so many native apps that when you run an Intel app through Rosetta2 (ASE, Skype and dare I say WhatApp) the speed differential is clear. Most apps have been ported over now and looking forward to this being another soon :-)

**Comment by ramzzzay** [comment]
I'm here to say, that we all need m1 arm64 release for azcopy because Azure Storage Explorer so laggy on Rosetta 2.

**Comment by MaciejBoguta** [comment]
> I'm here to say, that we all need m1 arm64 release for azcopy because Azure Storage Explorer so laggy on Rosetta 2.

100% agreed, its a huge pain in the back working with Azure Storage Explorer - ruins all the productivity and there is no real alternative when you're using Apple Silicon.

**Comment by zezha-msft** [comment]
Thanks a lot for your feedbacks! We will provide a preview build for Apple Silicon soon (in 1-2 months). It will become available to download on our public doc page like the other builds.

**Comment by dominik-lekse** [comment]
Those people who cannot wait for the official arm64 release, can build and install `azcopy` from source. As a prerequisite, you need the Go SDK >= 1.17.

```shell
go install github.com/Azure/azure-storage-azcopy/v10@v10.16.1
mv "$(which azure-storage-azcopy)" "$(dirname $(which azure-storage-azcopy))/azcopy"
which azcopy
azcopy --version
```

**Comment by Vinski** [comment]
I'd love to see this prioritised, because lack of official ARM64 build is holding other projects back, like Azure Storage Explorer.

**Comment by ramzzzay** [comment]
Any updates?

**Comment by Jtango18** [comment]
Everything MS will be on a code freeze until at least the 3rd. Suspect we'll here back later this week at the absolute earliest.

**Comment by Jtango18** [comment]
Probably a good time for an update now.

//tag: @zezha-msft

**Comment by MaciejBoguta** [comment]
@zezha-msft its been over 3 months and not even the preview binary has come out - will you at least post any update?

**Comment by Jtango18** [comment]
A quick LinkedIn search, looks like Ze has left Microsoft and is at Apple now. Oh the irony!

**Comment by ramzzzay** [comment]
> A quick LinkedIn search, looks like Ze has left Microsoft and is at Apple now. Oh the irony!
> 
> @adreed-msft Are you potentially the right person to get this moving again?

Lol, this news makes my day, really Ironic! But yeah, six months without news makes me wary. 👀

**Comment by tasherif-msft** [comment]
Hi @ramzzzay we have picked up this item and it's a priority atm. I will keep you posted, but we are aiming to have it released on Mac M1s very soon.

**Comment by Jtango18** [comment]
Any updates on this @tasherif-msft? 2 months down.

**Comment by tasherif-msft** [comment]
> Any updates on this @tasherif-msft? 2 months down.

Hi @Jtango18, I was actually away for some time. We're currently in the testing phase against the M1s and figuring out a release process to support it. I will update this thread as we go on.

**Comment by sgerace** [comment]
Any updates on when this might become available? I am also anxiously awaiting this. One of the few things that still needs Rosetta to run.

**Comment by adreed-msft** [comment]
There is currently a beta build available native to ARM64. Please check https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10 for a download link.
