### ISSUE TITLE
Cannot run azcoply login | error:  The computer must be trusted for delegation and the current user account must be configured to allow delegation

### ISSUE THREAD

**Issue by TonySh127-ms** [Azure/azure-storage-azcopy#1355]
### Which version of the AzCopy was used? 
Windows 64-bit https://aka.ms/downloadazcopy-v10-windows
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcoply login
### What problem was encountered?
Error: Failed to perform login command: failed to encrypt token, the requested operation cannot be completed. The computer must be trusted for delegation and the current user account must be configured to allow delegation

Research: Error code 0x80090345

### How can we reproduce the problem in the simplest way?
Download https://aka.ms/downloadazcopy-v10-windows
run the command by PowerShell client
azcoply login

### Have you found a mitigation/solution?
Change to use other machine

More infomration:
- checked the code:
b, err := encrypt(json, c.entropy)
	if err != nil {
		return fmt.Errorf("failed to encrypt token, %v", err)
	}

func encrypt(data []byte, entropy *dataBlob) ([]byte, error) {
	if entropy == nil {
		return nil, errors.New("entropy is enforced in AzCopy")
	}

	var outblob dataBlob
	defer func() {
		if outblob.pbData != nil {
			mLocalFree.Call(uintptr(unsafe.Pointer(outblob.pbData)))
		}
	}()

	r, _, err := mCryptProtectData.Call(
		uintptr(unsafe.Pointer(newDataBlob(data))),
		0,
		uintptr(unsafe.Pointer(entropy)),
		0,
		0,
		cryptProtectUIForbidden,
		uintptr(unsafe.Pointer(&outblob)))
	if r == 0 {
		return nil, err
	}

	return outblob.toByteArray(), nil
}

CryptProtectData function (dpapi.h)
https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata

Seem to relate the doc https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/dpapi-masterkey-backup-failures

0x80090345 | -2146892987 | SEC_E_DELEGATION_REQUIRED | The requested operation cannot be completed. The computer must be trusted for delegation and the current user account must be configured to allow delegation.
-- | -- | -- | --

HKEY_LOCAL_MACHINE\Software\Microsoft\Cryptography\Protect\Providers\df9d8cd0-1501-11d1-8c7a-00c04fc297eb

**Comment by zezha-msft** [comment]
Hi @TonySh127-ms, sorry for the inconvenience.

Have you tried this? https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)

**Comment by TonySh127-ms** [comment]
Hi Ze,

Thank you for your response.

Sorry I have not tried it before. Currently we are trying to use below action plan to mitigate the problem


  1.  Please have a snapshot at system level in case unexpected result
  2.  Hold down Windows key + R to bring up the run dialogue box
  3.  Type regedit and press Enter. If you get a UAC prompt, click OK and proceed
  4.  In the left navigation pane, locate and click HKEY_LOCAL_MACHINE
  5.  Open folder HKEY_LOCAL_MACHINE\Software\Microsoft\Cryptography\Protect\Providers\df9d8cd0-1501-11d1-8c7a-00c04fc297eb
  6.  Backup the current registry key
  7.  After selecting df9d8cd0-1501-11d1-8c7a-00c04fc297eb look for ProtectionPolicy on the right side, if it doesn't exists then create the DWORD 32bit value and name it as ProtectionPolicy.
  8.  Double click on ProtectionPolicy and change the registry entry value to 1. Base: Hexadecimal
  9.  Restart the machine
  10. Try to use azcopy login again

By the way, the customer is using Azure VM and run it by PowerShell command. I am not sure how to follow the doc https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store) and run it
***@***.***D72083.ECDF49E0]

Best regards,
Tony Shen

**Comment by zezha-msft** [comment]
Does that mitigation work? @TonySh127-ms

**Comment by siminsavani-msft** [comment]
Hi @TonySh127-ms ! I will be closing this issue as it seems like the issue has been mitigated. Feel free to open this issue again if the issue still persists or if you have any questions! Thanks!
