### ISSUE TITLE
Last modified date is not preserved when copying from AFS to AFS (after copying from Local to AFS)

### ISSUE THREAD

**Issue by shkoubi** [Azure/azure-storage-azcopy#1356]
### Which version of the AzCopy was used? 
10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
1- `azcopy copy "Drive:\path\to\dir" "https://<storage_account_1>.file.core.windows.net/<file_share_1>/path/to/dir?SAS1"  --from-to=LocalFile --recursive=true --preserve-smb-info=true`

2- `azcopy copy "https://<storage_account_1>.file.core.windows.net/<file_share_1>/path/to/dir?SAS1" "https://<storage_account_2>.file.core.windows.net/<file_share_2>/path/to/dir?SAS2" --from-to=FileFile --recursive=true --preserve-smb-info=true`

### What problem was encountered?
After the first command is done executing, the files are copied to `file_share_1` and the last-modified-date of all the files is preserved. When the second command is done running, **the last-modified-date of the files copied to 'file_share_2' is the time of the first command execution** (i.e. the time that a file was copied from Local to AFS).

PS- got the same behavior when running the second command with `azcopy sync`

### How can we reproduce the problem in the simplest way?
Follow my specified commands and you'll get the same results.

### Have you found a mitigation/solution?
Not yet.

**Comment by shkoubi** [comment]
This issue might be related to #1332

**Comment by zezha-msft** [comment]
Sorry for the inconvenience.

There was a breaking change (new feature) on the service to update SMB timestamps (e.g. last-write-time) when files are updated over the REST endpoint. They have since rolled back this change.

We will update AzCopy to accommodate the service change when it's enabled again.
