### ISSUE TITLE
Azcopy copy | The append position condition specified was not met

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-storage-azcopy#1358]
##### Note: The version is visible when running AzCopy without any argument
10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "{{registryAccountLink.stdout}}registry/{{registryAccountSAS.stdout}}" "{{backupAccountLink.stdout}}docker-registry-backup/docker-registry-backup-{{ date }}{{backupAccountSAS.stdout}}" --recursive

### What problem was encountered?
Diagnostic stats:
IOPS: 155
End-to-end ms per request: 226
Network Errors: 0.00%
Server Busy: 0.00%

Job 3abd867c-d29c-fc48-47ce-0abda176248c summary
Elapsed Time (Minutes): 7.2744
Number of File Transfers: 14087
Number of Folder Property Transfers: 0
Total Number of Transfers: 14087
Number of Transfers Completed: 14065
Number of Transfers Failed: 22
Number of Transfers Skipped: 0
TotalBytesTransferred: 108134999246
Final Job Status: CompletedWithErrors
================

2021/03/03 09:19:24 ERR: [P#0-T#4931] COPYFAILED: https://registryx45iv5k2s7u3y.blob.core.windows.net/registry//docker/registry/v2/blobs/sha256/fe/fe81e07b4a3a5f42d9b780a548127ffeeac10c552139b385c61dc333d993fb4e/data?se=2120-06-19t16%3A21%3A53z&sig=-REDACTED-&sp=racupwdl&spr=https&srt=sco&ss=bfqt&sv=2019-02-02 : 412 : 412 The append position condition specified was not met.. When Appending block from URL. X-Ms-Request-Id: 58b19b5b-301e-00ef-210e-10f483000000

2021/03/03 09:19:24 ERR: [P#0-T#6659] COPYFAILED: https://registryx45iv5k2s7u3y.blob.core.windows.net/registry//docker/registry/v2/blobs/sha256/18/1865ca92e6a42766a890af66c33c71ac454199e012a9709d1036756f2f9ea341/data?se=2120-06-19t16%3A21%3A53z&sig=-REDACTED-&sp=racupwdl&spr=https&srt=sco&ss=bfqt&sv=2019-02-02 : 412 : 412 The append position condition specified was not met.. When Appending block from URL. X-Ms-Request-Id: f11846eb-a01e-00a0-590e-1085d7000000

Cx tried to copy one folder to another folder, what could causes this error?

**Comment by mohsha-msft** [comment]
Hey @yangchengs ,

We have not seen this issue lately. Can you please forward the AzCopy logs if this still persists?
Please use latest AzCopy version and reopen the issue if it persists.
