### ISSUE TITLE
Azcopy error. source modified during transfer

### ISSUE THREAD

**Issue by arjgupta** [Azure/azure-storage-azcopy#1359]
### Which version of the AzCopy was used? 
10.8.0
### Which platform are you using? (ex: Windows, Mac, Linux)

windows

### What command did you run?

AzCopy.exe copy "source directory" "destination blob"  --cache-control=max-age=2592000 --recursive

### What problem was encountered?
When transferrring files. some files are uploaded correctly, but some files are not uploaded. we get the error:
UPLOADFAILED: %5C%5C?\D:\a\r1\a\_P2UStaticContent\P2UStaticContent\OTC\NewDesign\fonts\source-sans-pro-v11-latin-700.svg : 000 : source modified during transfer. When epilogueWithCleanupSendToRemote

**Comment by jedjohan** [comment]
I am having the same issue, "source modified during transfer". Did you find a solution @arjgupta ?

**Comment by chshrikh** [comment]
we dont found any solution, waiting on Azcopy team to provide solution

**Comment by Gitrathirad** [comment]
Azcopy team do you have  any update for us?

**Comment by Gitrathirad** [comment]
Could anyone please review the issue and share your findings

**Comment by nakulkar-msft** [comment]
This error is received if the source file has been modified after AzCopy job has started. Please verify that no other process has modified file while transfer is in progress.
