### ISSUE TITLE
@azure-tools/azcopy-node on linux does not set chmod +x for azcopy_linux_amd64

### ISSUE THREAD

**Issue by khanaffan** [Azure/azure-storage-azcopy#1362]
I am using @azure-tools/azcopy-node v2.1

The issue is that our ci job fail on linux but generally speaking it would fail on any any linux distro
```
Error: spawn /home/vsts/work/1/s/common/temp/node_modules/.pnpm/registry.npmjs.org/@azure-tools/azcopy-linux/10.9.0/node_modules/@azure-tools/azcopy-linux/dist/bin/azcopy_linux_amd64 EACCES
```
The binary does not have execute permission on it. I am not sure what is a good solution but at minimum the package should attempt to set it either on npm install (using install script) or before invoking the executable (with hope that node process has permission to set it)

Making client code responsible to set chmod +x for file is a bit difficult as the only way they can do is at runtime or some some how find path to this executable and set it before launch but seem a bit complex.

Thanks
Affan

**Comment by MRayermannMSFT** [comment]
Hey @khanaffan, thanks for opening the issue. For now this is a known thing you might have to do:
![image](https://user-images.githubusercontent.com/21112697/111713804-8b6c1200-880d-11eb-9083-7bbb4a0d6034.png)
From: https://www.npmjs.com/package/@azure-tools/azcopy-node

We'll look into seeing if this is something we can solve/make less of a hassle, but for now, it is something you need to take care of yourself.
