### ISSUE TITLE
Can't copy from aws s3 bucket to file storage uri but can copy to azure blob storage

### ISSUE THREAD

**Issue by rbavery** [Azure/azure-storage-azcopy#1363]
### Which version of the AzCopy was used? 
10.8

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac

### What command did you run?
azcopy cp

### What problem was encountered?
this works

```bash
azcopy cp 'https://s3.amazonaws.com/hyp3-contentbucket-fo259f6r6dn6/e2f9b5d4-1b84-4908-9f0b-b3b8f8487684/S1A_IW_20161023T090556_DVP_RTC30_G_gpufed_883C.log' https://storagedmgzl7yjhdn3c.blob.core.windows.net/test?..... --recursive
```

but this does not (copying to file storage instead)
```bash
azcopy cp https://s3.amazonaws.com/hyp3-contentbucket-fo259f6r6dn6/e2f9b5d4-1b84-4908-9f0b-b3b8f8487684/S1A_IW_20161023T090556_DVP_RTC30_G_gpufed_883C.log 'https://storagedmgzl7yjhdn3c.file.core.windows.net/test?....
```

### How can we reproduce the problem in the simplest way?
NMake a blob storage and file storage in the same account, try to copy a file on an s3 bucket to a blob container and a file store. 

### Have you found a mitigation/solution?
Copy to blob storage instead, then copy all that to file store form the blob store. file stores are easier to mount to vms which is why I want to use the.

**Comment by mohsha-msft** [comment]
Hey @rbavery ,

Thanks for reaching out!

We currently support transfer from AWS S3 (Access Key) to Azure Block Blob (SAS or OAuth authentication) and not to Azure File Storage. We have this on our roadmap. In the meantime, I suggest you run another AzCopy Job to perform the transfer from Blob Store to File Store.
