### ISSUE TITLE
azcopy failed with timeout=901: write tcp 10.x.x.x:36632->10.y.y.y.y:3128: write: connection reset by peer

### ISSUE THREAD

**Issue by varun22** [Azure/azure-storage-azcopy#1369]
### Which version of the AzCopy was used? 
10.9.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
innobackupex  $backup_path >>$log_file | /usr/bin/azcopy cp "https://$storage_acc_name/$remote_path/FS_$backup_file?$SASToken" --from-to="PipeBlob" 

### What problem was encountered?
ERROR:#012-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157#01
2HTTP request failed#012#012Put https://st-acc-name//backfilename?blockid=AAAAAAAAAAAAAAAAAAAAAA%3D%3D&comp=block&
$sastoken&timeout=901: write tcp 10.x.x.x:36632->10.y.y.y.y:3128: write: connection reset by peer

The backup file 824GB single file.

### How can we reproduce the problem in the simplest way?
running script
### Have you found a mitigation/solution?
No

**Comment by varun22** [comment]
250GB files are working fine

**Comment by varun22** [comment]
This is still a issue with 824GB single file, Trying to understand size limitations / alternatives...?

**Comment by nakulkar-msft** [comment]
@varun22 This is an issue with n/w. Use flags --block-size-mb 32. You can also use --cap-mbps to limit the bandwidth to a more appropriate value.
