### ISSUE TITLE
Copying from a blob storage container to local failed during download with an apparently tcp-related error

### ISSUE THREAD

**Issue by technowannabe** [Azure/azure-storage-azcopy#137]
### Which version of the AzCopy was used? 
**10.0.4-Preview**
### Which platform are you using? (ex: Windows, Mac, Linux)
**Windows 10**
### What command did you run?
AzCopy cp "https://shsdimicut.blob.core.windows.net/chuv-lausanne?sv=2018-03-28&si=chuv-lausanne-rwl&sr=c&sig=<SAS>" R:\CUT\chuv --recursive=true --preserve-last-modified-time=true --overwrite=false

### What problem was encountered?
Copying from a blob storage container to local failed during download with an apparently tcp-related error. I've been using AzCopy 8.x on the same computer and the equivalent operation successfully, so I don't think it's a problem with the system.
Note1: There are maybe 100-300k files in that container. 
Note2: I am using the new proxy support
### How can we reproduce the problem in the simplest way?
I'm not sure.
### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @technowannabe, thanks for reaching out!

Could you please share with us the exact error message? This would really help us in investigating further. Thank you!

**Comment by technowannabe** [comment]
Hi, I've been using 10.0.4 regularly since this post have not seen this issue again. Thanks for checking back.

Todd
