### ISSUE TITLE
"AzCoopy rm command with Service Principal" does not work, because of 401 in 10.9.0

### ISSUE THREAD

**Issue by nao-830713** [Azure/azure-storage-azcopy#1370]
### Which version of the AzCopy was used? 
10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2016

### What command did you run?
Set AZCOPY_SPA_CLIENT_SECRET=XXXX 2>&1 >> "E:\XXX 
"azcopy.exe" login --service-principal --application-id XXXXXXXXXX --tenant-id=XXXXXXXX 2>&1 >> "E:\XXX" 
"azcopy.exe" rm "https://XXXX.blob.core.windows.net/interfacedata/test_pattern01" --recursive=true --include-pattern "*" 2>&1 >> "E:\XXX" 

* XXX is masked strings

### What problem was encountered?
"azcopy .exe rm"  does not work, because of "401: DELETE ERROR -401 Server failed to authenticate the request. " 

But "azcopy.exe copy" works.
And in 10.6.0 version , "azcopy.exe rm" works with same command and client_id.

### Have you found a mitigation/solution?
no
[azcopy_command.txt](https://github.com/Azure/azure-storage-azcopy/files/6154015/azcopy_command.txt)
[fd9ada4e-6bee-f247-4bdb-a73662a9ec2f.log](https://github.com/Azure/azure-storage-azcopy/files/6154016/fd9ada4e-6bee-f247-4bdb-a73662a9ec2f.log)

**Comment by nakulkar-msft** [comment]
Fixed by #1384
