### ISSUE TITLE
.azcopy logs are eating my harddrive, ok to delete?

### ISSUE THREAD

**Issue by SleepyJay** [Azure/azure-storage-azcopy#1372]
### Which version of the AzCopy was used? 
various, including azcopy version 10.5.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

### What command did you run?
various

### What problem was encountered?
I currently have a local .azcopy folder that is 227GB in size. I understand the logs are for historical reasons, but this is simply TOO MUCH DATA to keep around doing nothing (since July 2020).

Is there a `clean` command? Can I just delete old data? What are the recommendations here. 

### How can we reproduce the problem in the simplest way?
Copy lots of stuff over time? Surely you know that keeping logs around forever is going to eat up space.

### Have you found a mitigation/solution?
Well... I do have a `delete` key on my keyboard... but I'd like to know the risks involved.

**Comment by nakulkar-msft** [comment]
@SleepyJay You can always clean up the old jobs. AzCopy allows you to selectively delete the logs as well - like only complted/failed jobs.

```
$ azcopy jobs clean --help

Note that you can customize the location where log and plan files are saved. See the env command to learn more.

Usage:
  azcopy jobs clean [flags]

Aliases:
  clean, cl

Examples:
  azcopy jobs clean --with-status=completed

Flags:
  -h, --help                 help for clean
      --with-status string   only remove the jobs with this status, available values: All, Cancelled, Failed, Completed CompletedWithErrors, CompletedWithSkipped, CompletedWithErrorsAndSkipped (default "All")
```

**Comment by SleepyJay** [comment]
Interesting. `--with-status-completed` removed only about half. AFAIK, I'm not actively copying anything. I would much prefer a command like `--older-than 30`  (days) or something. Also, it sounds like I need my own mechanism for running this regularly. Sigh. Ok.

**Comment by nakulkar-msft** [comment]
AzCopy does not support the older-than flag. Logs are history of the transfers made. Cleaning the logs will remove that particular job instance from 'azcopy jobs list' and 'azcopy jobs show <jobID>'. Not much of a gain, if you don't want to revisit the transfers performed in that job.
