### ISSUE TITLE
azure stackhub failures

### ISSUE THREAD

**Issue by angryjohnnie** [Azure/azure-storage-azcopy#1377]
##### Note: The version is visible when running AzCopy without any argument
10.9
### Which platform are you using? (ex: Windows, Mac, Linux)
Mac, Linux
### What command did you run?
azcopy copy --from-to BlobLocal https://<storageaccount>.blob.azuremsk.ec.mts.ru/<container>/test123.jpg?<account key> ./test.jpg 
### What problem was encountered?
a response saying that the url requires authentication. The key is supplied as a parameter of the url string. I guess its being ignored. fwiw, the az storage command also does not work, even with the connection string that the azure portal explicitly defines for us

### How can we reproduce the problem in the simplest way?
create a storage account in an azure stackhub environment (this situation occurs explicitly in russia which is the only stackhub env I have to test with) and try to push or pull a file from the blob
### Have you found a mitigation/solution?
no

**Comment by mohsha-msft** [comment]
@angryjohnnie ,

Thanks for reaching out!

Can you please tell us more about the source URL? Is it a public cloud? It seems AzCopy is unable to parse the source URL. We do not officially support it unless URL doesn't require any AUTH i.e. public resource URL
