### ISSUE TITLE
--include-after issues when copying from Azure to Local 

### ISSUE THREAD

**Issue by danjpadgett** [Azure/azure-storage-azcopy#1379]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2016

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy.exe copy $source $destination --recursive=TRUE --preserve-smb-info --include-after '2014-03-19T17:23:09Z'
$source is \\localfolder 
$destination is Azure file share+sas key 

### What problem was encountered?

When using the above command from local to azure, the --include-after switch is working and only files modified after the specified date are uploaded 

When switching $source and $destination around - (azure to local) all files are downloaded, even those modified well before the date specified.  

### How can we reproduce the problem in the simplest way?

Follow above test (azure file not blob)

### Have you found a mitigation/solution?

No

**Comment by danjpadgett** [comment]
Further testing revealed that it this does function as expected - however if the date modified for the folder is within range of the time within 'include after' all files in the folder are copied.

**Comment by siminsavani-msft** [comment]
@danjpadgett Thank you for confirming that the tool works as expected! Please let us know if you have any other questions!
