### ISSUE TITLE
Copy Command - Local to File Share - Exclude parent directory from destination path

### ISSUE THREAD

**Issue by woodwardmatt** [Azure/azure-storage-azcopy#138]
##### Note: The version is visible when running AzCopy without any argument
azcopy_linux_amd64_10.0.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy cp system/file/path/app/drop "https://myaccount.file.core.windows.net/myfileshare?SASToken" --recursive=true

### What problem was encountered?
I would like to copy the **contents** of the directory (e.g. drop) to the file share but not the containing **directory** itself (i.e. copy the contents of the directory to the root of the storage location) .

Desired: https://myaccount.file.core.windows.net/myfileshare/ (files within drop)
Occurring: https://myaccount.file.core.windows.net/myfileshare/drop/ (files within drop)

### How can we reproduce the problem in the simplest way?
Try and copy the contents of a local directory with files and subdirectories to the root location of your storage account without the parent (or containing directory) also being copied over to the file share.

### Have you found a mitigation/solution?
Not yet - was seeking input on this use case and if there was an option not to copy the parent directory into the destination file system structure.

**Comment by zezha-msft** [comment]
Hi @woodwardmatt, thanks for reaching out.

Please change the source to: `system/file/path/app/drop/*`.

**Comment by zezha-msft** [comment]
For more information, please view the examples by invoking the help command: `azcopy copy --help`.

**Comment by zezha-msft** [comment]
Hi @woodwardmatt, thanks for the clarification. I forgot to mention that the arguments should be quoted, like so: `"system/file/path/app/drop/*"`. Otherwise, the shell (depending on your environment) would expand the pattern into a list of files, which is undesired.

**Comment by woodwardmatt** [comment]
Awesome thank you! I'll give that a test soon and confirm :)

**Comment by woodwardmatt** [comment]
@zezha-msft that did the trick!! :)

Couple of things to feedback: 

1. Would be worth adding a note [here](https://github.com/Azure/azure-storage-azcopy#copy-data-to-azure-storage) under the last dot point to mention that some environment with expand the parameters if not double-quoted, and provide a quick example - that should cull any other occurrences of this query.
2. A DevOps specific note would be that to quote the path correctly, this needs to be done in the Script block, as opposed to the environmental variable - otherwise you'll get an error.

Thanks for your help!

**Comment by shaunakv1** [comment]
This doesn't seem to work with the sync command.  even when using `./source/*` it makes a new directory under destination.

**Comment by shaunakv1** [comment]
Hi @zezha-msft my use case is pretty much the same as that in the original question. 

I have a container called $web I need to use for static hosting. Now it will host multiple sites and not just one sites. 

So the storage account structure is something like : 

```
Storage 
          ---- $web
                      |
                      ---- site_1
                      |
                      ---- site_2
                      |
                      ---- site_3
```

We use a CI server to deploy the sites right now that we are trying to migrate to azure blob storage static hosting. As the sites can be fairly big, we want to use `azcopy sync` instead of `azcopy cp`.

Currently if I use the command like so:

`azcopy sync "./site1/*" "https://dummysample.blob.core.windows.net/\$web/site_1/?TOKEN" --recursive=true --force`

This creates a new `site_1/site_1/<contents>` instead of updating `site_1/<contents>` in the storage

**Comment by jiteshkumargouthamchand** [comment]
How do I escape if the src is a blob storage and destination is a on premise and I don't need to copy the container name instead just copy files undernerath it  where src is blob and dest is on premise url ---- $result = .\azcopy copy $srcSASURL  $destFolder  --recursive=true --log-level="ERROR"  --include-pattern=$uploadItem --output-type='json' --overwrite="ifSourceNewer"

**Comment by JohnRusk** [comment]
Something like this should work (if I understand your question properly)

`azcopy copy https:\\account.blob.core.windows.net\container\*?SAS destfolder`

Note the \* just before the ? in the URL.

**Comment by jiteshkumargouthamchand** [comment]
John, yes this worked.  Thanks.
