### ISSUE TITLE
AZcopy sync deleted all my data at targer fodler while downlaoding from blob. 

### ISSUE THREAD

**Issue by HandyManny66** [Azure/azure-storage-azcopy#1380]
### What command did you run? \azcopy.exe sync  source blob  target local file storage --recursive --delete-destination=true --exclude-path '$RECYCLE.BIN' --exclude-pattern *.steV16 --log-level ERROR
 in a LOOP
### What problem was encountered?
after running this command successful for a week  
on the second week . what i suspect that it lost connection to blob or some network blip.
after following up on the process found that i had deleted more 20 TB of data.
is there a way to tell azcopy to stop if connection to source or target is lost to stop.
or validate connection every 10 min?

### How can we reproduce the problem in the simplest way?
run AZcopy in sync and after a wile disconnect source than it should delete target. 
### Have you found a mitigation/solution?
the solution is pionful i have to run AZcopy copy find a way to delete files on target that are not on source.
it is very slow and tedious as i have millions of files.

Help please.

**Comment by siminsavani-msft** [comment]
Hi @HandyManny66 ! Apologies for the delay in getting back to you. The flag `delete-destination=true` will delete files that are not present at the source. Please remove this flag or change from `true' to `prompt` to get prompt for each file being deleted. Hope this helps! Feel free to reopen this issue if you are still having problems! Thanks.
