### ISSUE TITLE
--include--pattern

### ISSUE THREAD

**Issue by totalnet32** [Azure/azure-storage-azcopy#1383]
### Which version of the AzCopy was used? 
AzcopyVersion  10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)

2021/03/31 13:20:01 OS-Environment  windows
windows 2012r2
### What command did you run?
azcopy copy "C:\Users\test\test" "https://8675309etc" --include-pattern '*.pst*' --recursive=true

### What problem was encountered?
when i add the --include--pattern switch the entire azcopy stops working.
Elapsed Time (Minutes): 0
Number of File Transfers: 0
Number of Folder Property Transfers: 0
Total Number of Transfers: 0
Number of Transfers Completed: 0
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Completed

**Comment by mohsha-msft** [comment]
Hey @totalnet32 ,

Thanks for reaching out!

This is how the syntax of copy with `--include-pattern` looks like -
`azcopy  copy "source/path/location" "https://[account].blob.core.windows.net/[container]/[path/to/directory]?[SAS]" --recursive=true --include-pattern="*.jpg;*.pdf;exactName"`

You're supposed to use wildcard `*` before `.pst` to specify the pattern. Please try with below mentioned command and reach out for more help without which it is treated as an exact file name.
`azcopy copy "C:\Users\test\test" "https://8675309etc" --include-pattern '*.pst' --recursive=true`
