### ISSUE TITLE
AzCopy sync function scanning unnecessary files on Destination

### ISSUE THREAD

**Issue by jiteshkumargouthamchand** [Azure/azure-storage-azcopy#139]
### What problem was encountered?
I could not see the option as it was still scanning unnecessary files on destination.Also we have this automated through job so not sure how would you have the option as No instead of yes as we are forcing all prompts to be suppressed.
 For ex: I use below wherein this is a new folder on source so I would want this to be created in Destination and copy all files under that folder but the sync is comparing all the files in the container and not just that specific container. This used to work well with /xo
 .\azcopy sync "C:\Users\kdlq\Desktop\TestAzCopy" "https://.blob.core.windows.net/?" --recursive

**Comment by zezha-msft** [comment]
Hi @jiteshkumargouthamchand, thanks for reaching out!

Do you mean sync is comparing all files in the container and not just the specific virtual directory? Could you please clarify what is problem and how you are observing it?

**Comment by jiteshkumargouthamchand** [comment]
In below scenario the testAzCopy is a simple folder with 3 files in source. When I run AzCopy with Copy the 3 files gets copied on Azure. Whereas when I use syc it is scanning all files rather than just scanning files within testAzCopy folder. So if you see below it has scanned 20000+ files and it is in other words scanning entire folder : 
Power Shel Script  Console Output:
Loading personal and system profiles took 2649ms.
PS C:\> cd..
PS C:\> cd C:\Users\kdlq\Desktop\azcopy_windows_amd64_10.0.4\azcopy_windows_amd64_10.0.4
PS C:\Users\kdlq\Desktop\azcopy_windows_amd64_10.0.4\azcopy_windows_amd64_10.0.4>
PS C:\Users\kdlq\Desktop\azcopy_windows_amd64_10.0.4\azcopy_windows_amd64_10.0.4> .\azcopy copy "C:\Users\kdlq\Desktop\t
estAzCopy" "https://<sa>.blob.core.windows.net/poslink?<key>" --recursive=true --log-level="DEBUG"
Scanning...

Job 565f14fb-bbbb-f741-72cf-32ad5cfd487a has started

Log file is located at: C:\Users\kdlq/.azcopy/565f14fb-bbbb-f741-72cf-32ad5cfd487a.log
0 Done, 0 Failed, 3 Pending, 0 Skipped, 3 Total


Job 565f14fb-bbbb-f741-72cf-32ad5cfd487a summary
Elapsed Time (Minutes): 0.0333
Total Number Of Transfers: 3
Number of Transfers Completed: 3
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Completed

PS C:\Users\kdlq\Desktop\azcopy_windows_amd64_10.0.4\azcopy_windows_amd64_10.0.4> .\azcopy sync "C:\Users\kdlq\Desktop\t
estAzCopy" "https://<sa>.blob.core.windows.net/poslink?<key>" --recursive=true --log-level="DEBUG"

Job 0ece26df-89ee-3940-469c-c7da5d6941c6 has started

Log file is located at: C:\Users\kdlq/.azcopy/0ece26df-89ee-3940-469c-c7da5d6941c6.log
3 File Scanned at Source, 205000 Files Scanned at Destination

**Comment by zezha-msft** [comment]
Hi @jiteshkumargouthamchand, thanks for the explanation. I see what you mean now.

To clarify, you are asking AzCopy to synchronize the contents of a local folder "testAzCopy" with an entire container "poslink". This means whatever is present at the source (the local folder) should be copied to the destination (the container), and it also means that whatever is present at the destination but **NOT** present at the source should be deleted (eventually you get prompted to confirm whether you want these blobs deleted). This is why AzCopy is scanning your container. 

Synchronizing means making the contents of both the source and destination the same. Is this not the behavior that you expect? Would the regular copy not satisfy your use case?

**Comment by zezha-msft** [comment]
Closing due to lack of response.

**Comment by jiteshkumargouthamchand** [comment]
All the details were shared with Xiang Wu.

**Comment by jiteshkumargouthamchand** [comment]
All the details were shared with Xiang Wu.

**Comment by jiteshkumargouthamchand** [comment]
In our case we have 300 servers VMs  and each server has folder structure as \\vm1\poslink\06132019 ,
\\vm1\poslink\06132018,\\vm1\poslink\06132017 upto 20 days backwards.So each day at a certain tiem the oldest folder gets deleted on source (On premise) whereas in destination(Azure) it should not be deleted. So earlier with v6 of AzCopy /xo takes care of this. With sync this is an issue as it is asking to delete on destination whereas it is not the purpose. Hope this makes sense ?

**Comment by zezha-msft** [comment]
@jiteshkumargouthamchand please give the latest version a try. By default, it doesn't delete anything from the destination. The user can change the behavior with --delete-destination flag.
