### ISSUE TITLE
MD5 hash mismatch with azcopy sync while the destination is empty. 1st azcopy sync

### ISSUE THREAD

**Issue by valvador92** [Azure/azure-storage-azcopy#1391]
### Which version of the AzCopy was used? 
AzcopyVersion  10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
`./azcopy sync '{AZURE_BLOB_DATASETS_URL}/{dataset_name}/{token}'  '{local_dataset_directory}/{dataset_name}' --recursive=true --log-level=ERROR  --delete-destination=prompt --check-md5=FailIfDifferent`
### What problem was encountered?
`DOWNLOADFAILED [...] the MD5 hash of the data, as we received it, did not match the expected value, as found in the Blob/File Service. This means that either there is a data integrity error OR another tool has failed to keep the stored hash up to date. (NOTE In the specific case of downloading a Page Blob that has been used as a VM disk, the VM has probably changed the content since the hash was set. That's normal, and in that specific case you can simply disable the MD5 check. See the documentation for the check-md5 parameter.). When Checking MD5 hash. X-Ms-Request-Id: `

I get this error even if it is the 1st time I am syncing from Azure blob storage with my local storage. I don't get how they can be a mismatch with MD5 hash if I don't have any data in my local destination. I thought mismatch could be possible if one already has a copy of a blob in the destination that we change before a sync.

### How can we reproduce the problem in the simplest way?
You can't. You need to have a token.
### Have you found a mitigation/solution?
I put `--check-md5=LogOnly` instead of `--check-md5=FailIfDifferent`
However, this error doesn't make any sense for me in this situation.

Thank you in advance for your help!

**Comment by mohsha-msft** [comment]
Hey @valvador92 ,

Thanks for reaching out!

If no MD5 was stored in the Blob/File service against this file during upload, it will not be returned. It will simply be missing.  
So the downloaded data cannot be MD5-validated because even if we compute MD5 hash of downloaded file, we don't have the reference to compare it with.

Please try it with `--check-md5=FailIfDifferentOrMissing` and I suspect it will still fail because it's not set by user during upload.

For your reference, take a look [here](https://github.com/Azure/azure-storage-azcopy/blob/4caa64368e283773b61ab572f45d3c248ae2259f/ste/xfer-remoteToLocal-file.go#L96) in AzCopy code.

**Comment by valvador92** [comment]
Hey @mohsha-msft,

The MD5 should have been stored as I am using this command to upload the data.
`./azcopy sync '{local_dataset_directory}/{dataset_name}'  '{AZURE_BLOB_DATASETS_URL}/{dataset_name}/{token}' --recursive=true --log-level=ERROR --delete-destination={delete_destination_str} --put-md5=True`

So I have this flag: `--put-md5=True`.

**Comment by mohsha-msft** [comment]
Hey @valvador92 ,

Can you quickly check on the Azure portal that destination files indeed contain non-empty contentMD5 field?

**Comment by valvador92** [comment]
This is one of the problematic file as you can see in the log. and it has the MD5

![Screenshot from 2021-04-08 17-06-49-github](https://user-images.githubusercontent.com/33961158/114051782-b2a68400-988d-11eb-809a-64e9184c173a.png)

**Comment by mohsha-msft** [comment]
Please share the logs with me on mohsha@microsoft.com
I'll investigate further.

**Comment by valvador92** [comment]
Sure I can. But you will see the token there. And I should not share this token. Is it ok for you if I remove the token from the logs?

Thanks

**Comment by mohsha-msft** [comment]
We always redact the token and sanitize the logs before writing in AzCopy log file. 
So you won't have to worry about that. But sure go ahead and do the needful if you find any secret.

**Comment by valvador92** [comment]
I have just sent it. Thanks for your help!

**Comment by mohsha-msft** [comment]
@valvador92 ,

Is the issue still persisting? I haven't heard back on the mail. Please reopen this issue if it still persists and share the logs with us
