### ISSUE TITLE
azcopy cp hangs completely when called from C++'s std::system().

### ISSUE THREAD

**Issue by xkszltl** [Azure/azure-storage-azcopy#1395]
### Which version of the AzCopy was used? 

10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Ubuntu 18.04 and macOS

### What command did you run?

In C++ code:
```
std::system("timeout -k 10s 86400s ./script_to_run_azcopy.sh");
```

In `script_to_run_azcopy.sh`:
```
set -e
...
az storage ....
azcopy --version
azcopy cp https://xxxxxx local_dir
```

When run the script from bash, it works just fine.
When run from C++, everything else in the script works, including `az storage` and `azcopy --version`, but `azcopy cp` completely hang.
It doesn't even response to SIGTERM. I can only end it with SIGKILL, with a defunct process left:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/5203025/114081352-03929880-98df-11eb-91a6-9f938aeae00a.png">

There's no screen output for `azcopy cp`, and no log is available (`~/.azcopy/plans` is newly created by `azcopy --versoin`):
```
# tree ~/.azcopy
/root/.azcopy
└── plans

1 directory, 0 files
``` 

### Have you found a mitigation/solution?

No.
Currently blocked by this.

**Comment by xkszltl** [comment]
Did a few more experiments.
Seems it has something to do with `system()` + `timeout`.
- `timeout -k 10s 86400s ./script.sh` in bash, works.
- `system("./scripts.sh")`, works.
- `system("timeout -k 10s 86400s ./scripts.sh")`, hang.

**Comment by xkszltl** [comment]
I put together a repro, with some public blob borrowed from onnxruntime.
See C++ code inline.
Execution hangs at the 4th command.

```
# cat orz.cpp && g++-8 orz.cpp -o orz && ./orz
#include <cstdlib>
#include <iostream>

using namespace std;

int main()
{
    cout << "********************" << endl;
    system("azcopy --version");
    cout << "********************" << endl;
    system("timeout 1m azcopy --version");
    cout << "********************" << endl;
    system("azcopy cp https://onnxruntimetestdata.blob.core.windows.net/models/azcopy.exe ./");
    cout << "********************" << endl;
    system("timeout 1m azcopy cp https://onnxruntimetestdata.blob.core.windows.net/models/azcopy.exe ./");
    cout << "********************" << endl;
    return 0;
}
********************
azcopy version 10.9.0
********************
azcopy version 10.9.0
********************
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 41fdc2f7-39e7-cd45-4b34-084d3ca5cff9 has started
Log file is located at: /root/.azcopy/41fdc2f7-39e7-cd45-4b34-084d3ca5cff9.log

0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 


Job 41fdc2f7-39e7-cd45-4b34-084d3ca5cff9 summary
Elapsed Time (Minutes): 0.0333
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 1
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 19159648
Final Job Status: Completed

********************

```

**Comment by xkszltl** [comment]
If I add `--foreground` to `timeout`, it'll work.
I wonder if azcopy tries to read (but for nothing, as there's no user interaction required) from tty, or has some complex signal handling

**Comment by mohsha-msft** [comment]
Hey @xkszltl ,

Thanks for reporting this. We've addressed this issue in the recent release of AzCopy `10.10.0`. We now offer environment variables to disable application logging (Syslog/Windows Event Log). Please refer to the changelogs [here](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.10.0) 

Reach out to us for more information.

**Comment by nakulkar-msft** [comment]
Closing this because of age. Please reach us back if you're hitting this.

**Comment by xkszltl** [comment]
We never saw any patch or prove of fix on our repro provided, so I don't know why we would not hit this.
We've moved to a different approach as it is a blocking issue, that doesn't mean the issue itself has gone.
