### ISSUE TITLE
AzCopy.exe is not a valid Win32 application

### ISSUE THREAD

**Issue by Fabian-at-VertiQ** [Azure/azure-storage-azcopy#1396]
### Which version of the AzCopy was used? 
AzCopy 10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2003 R2 32-bit
Windows Server 2008 SP2 32-bit

### What command did you run?
AzCopy

### What problem was encountered?
Running AzCopy returns "azcopy.exe is not a valid Win32 application"

### How can we reproduce the problem in the simplest way?
Yes, just running AzCopy.exe

### Have you found a mitigation/solution?
No

![Screenshot 2021-04-08 174105](https://user-images.githubusercontent.com/51501505/114112656-a6bcc100-9891-11eb-9d19-effc014b8e31.png)

**Comment by nakulkar-msft** [comment]
Both these OS are EOL and are not supported. Upgrade to one of the newer versions.
