### ISSUE TITLE
Azcopy limit

### ISSUE THREAD

**Issue by sathish331977** [Azure/azure-storage-azcopy#1399]
### Which version of the AzCopy was used? 
Azcopy version 10
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What problem was encountered?
i can upload upto 105 GB, any size greater than this it fails (screen freeezes). Is there a limit for uploading files using AzCopy

**Comment by nakulkar-msft** [comment]
@sathish331977 There is not limit on the size of the file. The limits are same as those defined by Azure Service - which is 4TiB per blob. 

What is the cpu configuration and memory of the Windows vm/machine you're using?
 What is the CPU and memory usage when the transfer fails.
 
  It'd be helpful if you post first few lines of the azcopy log file here. Also, you can use environment variable AZCOPY_BUFFER_GB to an appropriate value if you're observing high memory usage.
