### ISSUE TITLE
azcopy has excessive delay when run without arguments

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-storage-azcopy#1404]
### Which platform are you using? (ex: Windows, Mac, Linux)

Linux (via WSL2)

### What command did you run?

`azcopy` without arguments

### What problem was encountered?

The command prints it's help message, then pauses before exiting.  `azcopy` takes 8 seconds to run each time.

Note, this is on an lightly used 32 core host.

### How can we reproduce the problem in the simplest way?

`time azcopy`

### Have you found a mitigation/solution?

None

**Comment by bmc-msft** [comment]
Linked is an strace log of the command: [strace.log](https://github.com/Azure/azure-storage-azcopy/files/6304653/strace.log)

**Comment by mohsha-msft** [comment]
Hey @bmc-msft ,

Whenever AzCopy command is executed, it makes a call to CDN to check for the latest version which may be the reason for delay.

**Comment by bmc-msft** [comment]
I recognize the desire to check for the latest version.

The version checking performed on every launch does an HTTPS connection to `aka.ms`, then an HTTPS connection `azcopyvnext.azureedge.net` on every execution.   In network constrained areas (such as behind a firewall that drops these sessions rather than rejecting them), these delays can be extremely excessive with no value.

Can the latest version be cached on some regular window, such as once per day, perhaps saving the results in the already existing `~/.azcopy` directory?

**Comment by mohsha-msft** [comment]
Hey @bmc-msft ,

This call timeouts in 8s and doesn't influence the AzCopy job. We'll try to optimize it.
