### ISSUE TITLE
Error on azcopy login --tenant-id "8240f5c5-afc2-431a-b4d0-78cb165a4f35"

### ISSUE THREAD

**Issue by theguru0** [Azure/azure-storage-azcopy#1406]
### What problem was encountered?
Failed to perform login command:
failed to login with tenantID "8240f5c5-afc2-431a-b4d0-78cb165a4f35", Azure directory endpoint "https://login.microsoftonline.com", autorest/adal/devicetoken: -REDACTED- occurred while handling response from the Device Endpoint: Error HTTP status != 200

NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again.

**Comment by nakulkar-msft** [comment]
@theguru0 Azure directory endpoint displayed above is for public cloud, not for the USGov cloud. Use --aad-endpoint parameter to set the correct value. Check 'azcopy login --help'
`Flags:
      --aad-endpoint string           The Azure Active Directory endpoint to use. The default (https://login.microsoftonline.com) is correct for the public Azure cloud. Set this parameter when authenticating in a national cloud. Not needed for Managed Service Identity`

**Comment by theguru0** [comment]
Is there a list?

**Comment by nakulkar-msft** [comment]
Using "https://login.microsoftonline.us" will do it.
