### ISSUE TITLE
AZCOPY Bench command is not able to Cleanup

### ISSUE THREAD

**Issue by RedOhne** [Azure/azure-storage-azcopy#1408]
##### Note: The version is visible when running AzCopy without any argument
10.09 / 10.10

### Which platform are you using? (ex: Windows, Mac, Linux) 
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy bench "https://sahec44neetransfer0001.blob.core.windows.net/mig..."

### What problem was encountered?
After the bench run was successfully finished, AZCOPY tries to cleanup (remove the used files from the Blob), but is "hanging". I can still see the azcopy process running.
The log is piling up with the following entries:

2021/04/16 07:25:46 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 64
2021/04/16 07:25:46 Cleanup 200/200

The log for cleanup is looking the following:
2021/04/16 06:51:26 AzcopyVersion  10.10.0
2021/04/16 06:51:26 OS-Environment  linux
2021/04/16 06:51:26 OS-Architecture  amd64
2021/04/16 06:51:26 Log times are in UTC. Local time is 16 Apr 2021 06:51:26
2021/04/16 06:51:26 AzcopyVersion  10.10.0
2021/04/16 06:51:26 OS-Environment  linux
2021/04/16 06:51:26 OS-Architecture  amd64
2021/04/16 06:51:26 Log times are in UTC. Local time is 16 Apr 2021 06:51:26
2021/04/16 06:52:53 ==> REQUEST/RESPONSE (Try=1/24.700659ms, OpTime=174.508359ms) -- RESPONSE SUCCESSFULLY RECEIVED
   HEAD https://sahec44neetransfer0001.blob.core.windows.net/mig/benchmark-aefdf877-0ddf-3d4b-6f04-545398f2f135?.....&timeout=901
   X-Ms-Request-Id: [08ecd991-701e-007a-1d8d-323a83000000]

2021/04/16 06:52:53 ==> REQUEST/RESPONSE (Try=1/41.489766ms, OpTime=41.750408ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://sahec44neetransfer0001.blob.core.windows.net/mig?comp=list&delimiter=%2F&include=metadata&prefix=benchmark-aefdf877-0ddf-3d4b-6f04-545398f2f135%2F&.......&timeout=901
   X-Ms-Request-Id: [08ecd9a1-701e-007a-2a8d-323a83000000]

### How can we reproduce the problem in the simplest way?
Run an azcopy bench command until the end.

### Have you found a mitigation/solution?
In rare cases it's poosible to cancel the azcopy bench run with Ctrl+C, but most times it's not working. Only solution is to switch back to a version 10.5.1 (I think it's still running with 10.8, but I don't have the version available any longer on my servers)

**Comment by nakulkar-msft** [comment]
@RedOhne Do you mind sharing the log file. The secrets in log file are redacted.

**Comment by RedOhne** [comment]
@nakulkar-msft : Do you need the log from cleanup or the one from bench run itself? I will download them and store them within the next 2 hours.

**Comment by nakulkar-msft** [comment]
@RedOhne The one from bench

**Comment by RedOhne** [comment]
Here's the Log:

[848ffa3f-a620-7d44-4438-9b02ee6a6687.log](https://github.com/Azure/azure-storage-azcopy/files/6323722/848ffa3f-a620-7d44-4438-9b02ee6a6687.log)
