### ISSUE TITLE
Sync from Azure to Local panics when destination does not exist

### ISSUE THREAD

**Issue by StormRider01** [Azure/azure-storage-azcopy#141]
### Which version of the AzCopy was used? 
v10.0.4-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
.\azcopy sync "https://***.blob.core.windows.net/pdf/?<SAS>" "E:\AzureBlob\***\pdf\" --recursive=true --log-level="DEBUG"

### What problem was encountered?
.\azcopy : panic: runtime error: index out of range
At E:\AzureBlob\backup.ps1:3 char:1
+ .\azcopy sync "https://***.blob.core.windows.net/pdf/?<SAS>...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: runtime error: index out of range:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

### How can we reproduce the problem in the simplest way?
Attempt to sync from azure to non-existent local folder
### Have you found a mitigation/solution?
no

**Comment by zezha-msft** [comment]
Hi @StormRider01, thanks for reaching out!

I've logged this issue for further investigation. It indeed looks like bug.

**Comment by zezha-msft** [comment]
@StormRider01 sorry for the inconvenience, and I really appreciate your patience!

I've rewritten the sync command and released it in 10.0.8. This issue should be fixed. Please let us know if you still encounter any problem.

Here is a [wiki](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide) explaining how the new sync command works. Please feel free to reach out if you have any question or concern.
