### ISSUE TITLE
Failed to copy data between Azure containers

### ISSUE THREAD

**Issue by tamishai** [Azure/azure-storage-azcopy#1419]
### Which version of the AzCopy was used? 
AzCopy 10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
MacBook Pro 13" 2017 - Mac OS Catalina (version 10.15.7)

### What command did you run?
`azcopy cp 'https://<my_storage_account>.blob.core.windows.net/<source_container>?<SAS_token>' 'https://<the_same_storage_account_as_the_source>.blob.core.windows.net/<destination_host>' --recursive`

### What problem was encountered?
I'm trying to copy data between containers within the same Azure storage account.
Before running it on production, I'm testing it on our test subscription on a container with fewer files than what we have in production (but the file sizes are the same).

The source container (test env) I'm trying to copy has around 35,000 blobs with a small average size (KB up to 1-2 MB).
While I used the AzCopy default command, the copy operation took a long time -> in such speed, it will take us few days to copy the containers in production.

So I'm trying to [optimize the tool for large numbers of small files](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize#optimize-for-large-numbers-of-small-files).
According to the doc - 
"If you're copying blobs between storage accounts, consider setting the value of the `AZCOPY_CONCURRENCY_VALUE` environment variable to a value greater than 1000. You can set this variable high because AzCopy uses server-to-server APIs, so data is copied directly between storage servers and does not use your machine's processing power"

I tried to set its value to 3000 and the logs were full of exceptions and the job has failed, then I tried 1500 with the same results and 1000.
Eventually, I used `AZCOPY_CONCURRENCY_VALUE=100` and it seems to work fine but very slowly.

While I used 3000, 1500 I noticed the following exceptions in the logs (a lot of them):
`ERROR: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157 HTTP request failed Put "https://<my_storage_account>.blob.core.windows.net/<destination_container><file_path>?blockid=BLABLABLABLABLA&comp=block&timeout=901": dial tcp: lookup <my_storage_account>.blob.core.windows.net: no such host`

While I set the value to 1000 It failed on
`ERROR: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157 HTTP request failed Put "https://<my_storage_account>.blob.core.windows.net/<destination_container><file_path>?blockid=BLABLABLABLABLA&comp=block&timeout=901": dial tcp <IP_Address>:443: socket: too many open files`

1.  Has anyone encountered this?
2. Is there an option to run a benchmark test on copying files between containers in Azure? I didn't find this option in the documents.

### How can we reproduce the problem in the simplest way?
Run the same AzCopy command to copy data between containers within the same storage account (with around 35K small files).

### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment]
@tamishai ,

Did you try using `AZCOPY_CONCURRENCY_VALUE=AUTO`?

**Comment by tamishai** [comment]
@mohsha-msft - Nope, What are the benefits of this while copying data between Azure containers? As far as I understand, it's defining the value according to my local resources (which are not playing here a role since we are copying server-to-server).

**Comment by mohsha-msft** [comment]
@tamishai ,

`AZCOPY_CONCURRENCY_VALUE` : Overrides how many HTTP connections work on transfers. By default, this number is determined based on the number of logical cores on the machine. Since the number of files are not too large, this should work smoothly.

When set to AUTO, AzCopy tries to automatically optimize the number of HTTP connections.

**Comment by tamishai** [comment]
@mohsha-msft ,
I did a test and assigned `AZCOPY_CONCURRENCY_VALUE=AUTO`, it seems the copy succeeded but again, it took a very long time - 85 minutes to transfer 35193 blobs.
The throughput was around 0.1121 Mb/s for most of the process (at some points it was a bit above 1Mb/s but went down even more to 0.03 MB/s).
Copy the container at that speed is not acceptable, in production, we have around 300K files that should be moved, copy them will long forever.

While I used `AUTO`, the tool finds the optimal value for the concurrent connections according to my local environment.
I have less than 5 CPUs (Dual-Core with 4 threads), so it found that 4 concurrent connections are at optimum.
```
INFO: Trying 4 concurrent connections (initial starting point)
INFO: Trying 16 concurrent connections (seeking optimum)
INFO: Trying 4 concurrent connections (backing off)
INFO: Trying 8 concurrent connections (seeking optimum)
INFO: Trying 4 concurrent connections (backing off)
INFO: Trying 5 concurrent connections (seeking optimum)
INFO: Trying 4 concurrent connections (at optimum)
INFO:
INFO: Automatic concurrency tuning completed.
INFO:
100.0 %, 35183 Done, 0 Failed, 10 Pending, 0 Skipped, 35193 Total, 2-sec Throughput (Mb/s): 0.0303


Job DUMMY_ID summary
Elapsed Time (Minutes): 85.2814
Number of File Transfers: 35193
Number of Folder Property Transfers: 0
Total Number of Transfers: 35193
Number of Transfers Completed: 35193
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 186360644
Final Job Status: Completed
```
I also inspected the logs and found some `connection reset by peer` exceptions (which I'm sure contributing to the slowness for having retries):
```
2021/04/22 08:03:51 ==> REQUEST/RESPONSE (Try=1/151.482874ms, OpTime=151.58773ms) -- REQUEST ERROR PUT https://<my_storage_account>.blob.core.windows.net/<destination_container><file_path>?comp=blocklist&timeout=901
   Authorization: REDACTED
   Content-Length: [88]
   Content-Type: [application/xml]
   User-Agent: [AzCopy/10.10.0 Azure-Storage/0.13 (go1.15; darwin)]
   X-Ms-Access-Tier: [Hot]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Type: [application/octet-stream]
   X-Ms-Client-Request-Id: [a908bf5e-5afb-4098-5f76-c7723eab8a0b]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Put "https://<my_storage_account>.blob.core.windows.net/<destination_container><file_path>?comp=blocklist&timeout=901": read tcp 192.168.1.56:50537->20.60.128.132:443: read: connection reset by peer
```

I'm asking again, according to [Increase concurrency](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize#increase-concurrency):
"If you're copying blobs between storage accounts, consider setting the value of the AZCOPY_CONCURRENCY_VALUE environment variable to a value greater than 1000. You can set this variable high because AzCopy uses server-to-server APIs, so data is copied directly between storage servers and does not use your machine's processing power."

Why is it limiting me by my logical cores if the copy operation doesn't use my Mac processing power?
What are my options? How do I optimize the tool for copying data between Azure containers? There is a way to run a benchmark test that not calculating the values according to my local processing power?

As far as I understand, this tool is built to transfer the data to/from/between Azure, and with such poor performance, I found it is not useful and not effective.

**Comment by mohsha-msft** [comment]
Hey @tamishai ,

As I mentioned in my previous comment, in Unix based system, all HTTP connections are file descriptors. Unix OS has limits on resources assigned which you can check that out by executing `ulimit -a` command. Under this list, you'll find the limit of number of files (HTTP Connections) OS can open at a time.  Alter it to a higher value by executing `ulimit -n $(HigherValue)` . Notice `n` represents the number of open files at a given time. 

When you set `AZCOPY_CONCURRENCY_VALUE=AUTO`, AzCopy tries to get as much resource as available to the system. So I am inclined to assume that system resources or resource limit is the problem.

As for the `connection reset by peer` issue you mentioned means that a virtual connection was set up, but was then lost because remote machine send a RST packet. It is generally due to slow or unstable host network or sometimes, in an unlikely scenario, of server closing too many connection requests. 

Try out `ulimit` and if issue still persists, please write back to us and share AzCopy logs for further investigation.

FYI: We're planning to improve the performance of small file (<256MB) transfer in the upcoming release of AzCopy `10.10.1` or `10.11.0` significantly. So stay tuned.

**Comment by tamishai** [comment]
Thank you @mohsha-msft ,
I increased the open file descriptor limit to be 1000 (previously was defined 256) and successfully copied the container while defining `AZCOPY_CONCURRENCY_VALUE=1000`, `AZCOPY_CONCURRENCY_VALUE=2000`,  `AZCOPY_CONCURRENCY_VALUE=3000`.
However, the process was slow in all the tries and took ~14 minutes (but much better from using `AUTO`).
The logs are full of the below exceptions and I noticed a high rate of `Network Errors: 49.08%`

```
2021/04/22 10:58:01 ==> REQUEST/RESPONSE (Try=2/2.147382ms, OpTime=1.166630943s) -- REQUEST ERROR
   PUT https://<my_storage_account>.blob.core.windows.net/<destination_container><file_path>?DUMMY
   Authorization: REDACTED
   Content-Length: [0]
   User-Agent: [AzCopy/10.10.0 Azure-Storage/0.13 (go1.15; darwin)]
   X-Ms-Client-Request-Id: [93ad68b7-f6e5-4dbc-714f-43e46b7e62a2]
   X-Ms-Copy-Source: [https://<my_storage_account>.blob.core.windows.net/<destination_container><file_path>?DUMMY
   X-Ms-Source-Range: [bytes=0-734]
   X-Ms-Version: [2020-04-08]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Put "https://<my_storage_account>.blob.core.windows.net/<destination_container><file_path>?DUMMY&comp=block&timeout=901": dial tcp: lookup <my_storage_account>.blob.core.windows.net: no such host

goroutine 1770 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.stack(0xc0068155c0, 0xc007565700, 0x0)
	/Users/runner/work/1/s/ste/xferLogPolicy.go:237 +0x9f
github.com/Azure/azure-storage-azcopy/v10/ste.NewRequestLogPolicyFactory.func1.1(0x4c394e0, 0xc0068dfe60, 0xc006c4ba00, 0x10, 0x3, 0x0, 0xc001796c60)
	/Users/runner/work/1/s/ste/xferLogPolicy.go:151 +0x785
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc007600910, 0x4c394e0, 0xc0068dfe60, 0xc006c4ba00, 0xc001796d30, 0xc008b33210, 0xc005ac2c30, 0x405460f)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-azcopy/v10/ste.NewVersionPolicyFactory.func1.1(0x4c394e0, 0xc0068dfe60, 0xc006c4ba00, 0x4053afe, 0xc00553f807, 0xc00230d000, 0x706)
	/Users/runner/work/1/s/ste/mgr-JobPartMgr.go:83 +0x1b8
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0077f4d00, 0x4c394e0, 0xc0068dfe60, 0xc006c4ba00, 0x706, 0x1, 0x706, 0xc00553f800)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0x4c264c0, 0xc0077f4d00, 0xc00586c0b0, 0x4c394e0, 0xc0068dfe60, 0xc006c4ba00, 0x2, 0x2, 0xc00553f800, 0xc001796c60)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20210407023846-16cf969ec1c3/azblob/zz_generated_responder_policy.go:33 +0x53
github.com/Azure/azure-storage-blob-go/azblob.(*tokenCredential).New.func1(0x4c394e0, 0xc0068dfe60, 0xc006c4ba00, 0x4010b38, 0x10, 0x49e4320, 0xca892350801)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20210407023846-16cf969ec1c3/azblob/zc_credential_token.go:135 +0x212
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0077f4e00, 0x4c394e0, 0xc0068dfe60, 0xc006c4ba00, 0xd18c2e0a44, 0x4070300, 0xc005ac2e68, 0xc00606ddc0)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-azcopy/v10/ste.(*retryNotificationPolicy).Do(0xc004d1bf30, 0x4c394e0, 0xc0068dfe60, 0xc006c4ba00, 0x0, 0xc0068dfe70, 0x4b347a0, 0xc005ac2f20)
	/Users/runner/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x5b
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc004d1bf40, 0x4c394e0, 0xc0068dfe60, 0xc006c4ba00, 0xc0068dfe60, 0xc00a1e59b0, 0x2, 0x450d3880)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-azcopy/v10/ste.NewBlobXferRetryPolicyFactory.func1.1(0x4c39520, 0xc0076bf2f0, 0xc00200ee00, 0x10, 0x4970960, 0x64492d747301, 0xc003036dc0)
	/Users/runner/work/1/s/ste/xferRetrypolicy.go:384 +0x74e
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc007600960, 0x4c39520, 0xc0076bf2f0, 0xc00200ee00, 0xc003036ec0, 0xc005ac32a0, 0x40101d0, 0xc004d1bf50)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0x4c39520, 0xc0076bf2f0, 0xc00200ee00, 0x10, 0x4970960, 0x4010b01, 0xc003036dc0)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20210407023846-16cf969ec1c3/azblob/zc_policy_unique_request_id.go:22 +0xd4
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0077f58c0, 0x4c39520, 0xc0076bf2f0, 0xc00200ee00, 0xc003036ea8, 0x32, 0xc00fb63340, 0xc005ac3348)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0x4c39520, 0xc0076bf2f0, 0xc00200ee00, 0x1, 0x0, 0x1, 0xc008b33168)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20210407023846-16cf969ec1c3/azblob/zc_policy_telemetry.go:34 +0x162
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0076bf620, 0x4c39520, 0xc0076bf2f0, 0xc00200ee00, 0xc0076bf620, 0xc00200ee00, 0xc005ac3418, 0x4010b38)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc0053ffc00, 0x4c39520, 0xc0076bf2f0, 0x4c265c0, 0xc00586c0b0, 0xc00200ee00, 0x2e, 0xc00f385cf6, 0xf1, 0x0)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:129 +0x82
github.com/Azure/azure-storage-blob-go/azblob.blockBlobClient.StageBlockFromURL(0xc00f385cc0, 0x5, 0x0, 0x0, 0x0, 0xc00f385cc8, 0x2e, 0xc00f385cf6, 0xf1, 0x0, ...)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20210407023846-16cf969ec1c3/azblob/zz_generated_block_blob.go:591 +0x485
github.com/Azure/azure-storage-blob-go/azblob.BlockBlobURL.StageBlockFromURL(0xc00f385cc0, 0x5, 0x0, 0x0, 0x0, 0xc00f385cc8, 0x2e, 0xc00f385cf6, 0xf1, 0x0, ...)
	/Users/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20210407023846-16cf969ec1c3/azblob/url_block_blob.go:105 +0x287
github.com/Azure/azure-storage-azcopy/v10/ste.(*urlToBlockBlobCopier).generatePutBlockFromURL.func1()
	/Users/runner/work/1/s/ste/sender-blockBlobFromURL.go:146 +0x3cd
github.com/Azure/azure-storage-azcopy/v10/ste.createChunkFunc.func1(0x218)
	/Users/runner/work/1/s/ste/sender.go:180 +0x173
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0xc0003b8680, 0x218)
	/Users/runner/work/1/s/ste/JobsAdmin.go:433 +0xd5
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
	/Users/runner/work/1/s/ste/JobsAdmin.go:362 +0x685
```

Any suggestions?
Can you please let me know how can I securely share the full logs with you?

**Comment by mohsha-msft** [comment]
@tamishai ,

Good to hear that performance improvement considerable. Don't worry about exceptions because we have automatic retry policy which would retry a failed request. 

Once AzCopy 10.10.1 or 10.11.0 is released, the performance will be greatly improved for cases such as yours where customers try to copy small blobs (<256MB). 

😄

**Comment by mohsha-msft** [comment]
@tamishai 

Also, you can increase file descriptor value to an even higher value. Try using 2048 or 4096. And adjust `AZCOPY_CONCURRENCY_VALUE` according.

`AUTO` works well will large amount of data set because it takes time to optimize to the appropriate value.

As for the logs, we always sanitize the logs and redact the secrets from it.

**Comment by tamishai** [comment]
@mohsha-msft ,
Indeed, it looks like we have progress.
It may take some time for AzCppy 10.10.1 or 10.11.0 to be released, so as of now we have to work with the current version.
I did a quick calc, so far the best results were while I used `AZCOPY_CONCURRENCY_VALUE=1000` and `open files (-n) 1000`.
It took 14 minutes to copy 35,193 blobs with a total size of 186,360,644 bytes.

The source container in production has about 260,000 blobs with a total size of 18,500,000,000 bytes, this means it will take about 24hrs to copy only 17GB (not effective). 

After your second comment, I increased the open files -n even more to be 2048 as suggested and set `AZCOPY_CONCURRENCY_VALUE=3000`.
This time it took 20 minutes for the same operation.

Since I'm doing all these tests on our test environment, and I don't want to test it on our production data, I'm trying to figure out what is the best correlation for the AZCOPY_CONCURRENCY_VALUE and the open files (-n).

Do you have any suggestions? I can try increasing the open file -n limit to 4096 but what will be the right adjustment for `AZCOPY_CONCURRENCY_VALUE`?

Does the full logs will assist in finding the correct values here? If so, I can share them.

**Comment by mohsha-msft** [comment]
@tamishai ,

There isn't a lucky number as I've seen it's basically varies from network to network. For transferring the larger dataset, I suggest you to use AUTO option as AzCopy will have ample time to optimize the concurrency value. Please check [this](
https://github.com/Azure/azure-storage-azcopy/wiki/Performance:-small-blobs) to know more.

@zezha-msft  FYI

**Comment by zezha-msft** [comment]
@tamishai to clarify, the poor performance is not representative of the tool but rather the network that the client machine is on. It looks like you are running the copy operation from your laptop, could you please try running AzCopy in an Azure VM instead?

Under good network conditions (such in an Azure datacenter), AzCopy should easily saturate the account limits, up to 50 Gbps. 

The upcoming optimization that @mohsha-msft mentioned will help in reducing I/Os per copy, so it'll definitely benefit most scenarios. But in your case, I think there are many other lower hanging fruits to pick before waiting on the optimization. 

Please let us know if you have any other question or findings. Thanks.

**Comment by tamishai** [comment]
Thank you @mohsha-msft, @zezha-msft ,
I tried running AzCopy in an Azure VM and the transfer speed was much better (but still not 50 Gbps - even not 1 Gbps).
Can you recommend a VM that should do the work faster?

**Comment by zezha-msft** [comment]
Hi @tamishai, have you tried increasing AZCOPY_CONCURRENCY_VALUE to a higher number? Perhaps 1000?

If your data set consists of only small files, then it'll be inherently harder to achieve a nominal high throughput, since there's very little data copied per I/O.

**Comment by tamishai** [comment]
Hi @zezha-msft - Indeed, I increased the CONCURRENCY to a higher number and achieved a good transferring speed (5Gbps).
Thank you!

For future cases, we would like to have a ready VM with AzCopy install on it (which be stopped while we are not using it).
To get the best performance, can you please recommend us a VM that will do the work best? (CPU, Memory, Disk, etc..)
Note - we will use it only for copying data within Azure containers/storage accounted.

**Comment by zezha-msft** [comment]
Hi @tamishai, good to hear!

For such copy operations, the VM only needs to be powerful enough to support the desired level of concurrency, i.e. only the CPU core count is important since the data never comes through the client side. 

I cannot recommend a specific VM type since that depends on your expected concurrency/speed, data size, budget, etc.
