### ISSUE TITLE
ADLS-to-ADLS (dfs) source and destination requires unknown FromTo switch

### ISSUE THREAD

**Issue by kfallstrom** [Azure/azure-storage-azcopy#142]
##### Note: The version is visible when running AzCopy without any argument
10.0.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
C:\Users\Administrator\Downloads\azcopy_windows_amd64_10.0.4\azcopy_windows_amd64_10.0.4>azcopy.exe cp "https://%sourcedfs%.dfs.core.windows.net?%SAS%" "https://%destination%.dfs.core.windows.net?%SAS%" --recursive=true --follow-symlinks
--returned message--
failed to parse user input due to error: Unable to infer the source 'https://%sourcedfs%.dfs.core.windows.net?%SAS%' / destination 'https://%destinationdfs%.dfs.core.windows.net?%SAS%' combination. Please use the --FromTo switch

### What problem was encountered?

Fails to execute ADLS-to-ADLS transfer.
Cannot identity valid FromTo switch for ADLS-to-ADLS transfer.  Per documentation (below) this command should result in a transfer between ADLS Gen2 containers:

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10?toc=%2fazure%2fstorage%2ftables%2ftoc.json 

--
.\azcopy cp "https://myaccount.blob.core.windows.net/<sastoken>" "https://myotheraccount.blob.core.windows.net/<sastoken>" --recursive=true
--
To work with blob storage accounts that have hierarchical namespaces enabled, replace the string blob.core.windows.net with dfs.core.windows.net in these examples.
--

### How can we reproduce the problem in the simplest way?
Attempt to transfer between two ADLS accounts using provided syntax with noted version.

### Have you found a mitigation/solution?
not yet.

**Comment by zezha-msft** [comment]
Hi @kfallstrom, thanks for reaching out!

We do not support this scenario yet due to service limitations. I'll update this thread once we have progress to share.

In the mean time, you could download/re-upload to unblock your workflow.

**Comment by zezha-msft** [comment]
The error message was improved. 

Tracking the ADLS Gen 2->ADLS Gen 2 copy feature with #169.
