### ISSUE TITLE
Azure Table azcopy

### ISSUE THREAD

**Issue by ElAouane** [Azure/azure-storage-azcopy#1420]
### Which version of the AzCopy was used? 
v10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
--- MacOs M1 Silicon

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

--- azcopy cp "https://hamzabackupdataout.table.core.windows.net/?[SAS]" "https://hamzabackupdatain.table.core.windows.net/?[SAS]"

### What problem was encountered?

Once I run the azCopy command I got this error:
 `INFO: The parameters you supplied were Source: 'https://hamzabackupdataout.table.core.windows.net/?se=2021-04-22t04%3A49%3A23z&sig=-REDACTED-&sp=rwdlacupx&spr=https&srt=sco&ss=bfqt&st=2021-04-21t20%3A49%3A23z&sv=2020-02-10' of type Local, and Destination: 'https://hamzabackupdatain.table.core.windows.net/?s=bfqt&se=2021-04-22t04%3A51%3A15z&sig=-REDACTED-&sp=rwdlacupx&spr=https&srt=sco&st=2021-04-21t20%3A51%3A15z&sv=2020-02-10' of type Local
INFO: Based on the parameters supplied, a valid source-destination combination could not automatically be found. Please check the parameters you supplied.  If they are correct, please specify an exact source and destination type using the --from-to switch. Valid values are two-word phases of the form BlobLocal, LocalBlob etc.  Use the word 'Blob' for Blob Storage, 'Local' for the local file system, 'File' for Azure Files, and 'BlobFS' for ADLS Gen2. If you need a combination that is not supported yet, please log an issue on the AzCopy GitHub issues list.

failed to parse user input due to error: the inferred source/destination combination could not be identified, or is currently not supported'

### How can we reproduce the problem in the simplest way?
Create 2 storage accounts, give `Data Blob Contributor` to both storage accounts, azcopy login and than run the command

### Have you found a mitigation/solution?
As far as I can found online, they say that the azcopy table is only available in azcopy v7.3, but that version is not available for MacOs, is only available on windows, and I can't test it as I don't have a windows pc.

**Comment by mohsha-msft** [comment]
Hey @ElAouane ,

Thanks for reaching out!!

I see that you're using AzCopy `V10` which is different from earlier versions such as `V7` and `V8`.  AzCopy `V10` does not support copying tables. 

We don't intend to support this in future as there is another better product offered by Microsoft called [CosmosDB](https://azure.microsoft.com/en-us/blog/a-technical-overview-of-azure-cosmos-db/). If you wish to use the functionality, you can always spawn [an Azure Virtual Machine Instance](https://azure.microsoft.com/en-in/free/virtual-machines/) and try the feature through it.
