### ISSUE TITLE
Table and queue storage backup

### ISSUE THREAD

**Issue by vick-git** [Azure/azure-storage-azcopy#1423]
A lot of users would benefit from Table and queue storage backup using AzCopy or Storage explorer or any possible means. Currently blob backups are going well but table and queue backups are dependent on other services like ADF. Hence disaster recovery is challenging. Hence requesting the same in at Storage end.

**Comment by zezha-msft** [comment]
Thanks for reaching out @vick-git. 

For queue storage, isn't the data in it inherently volatile? How does the backup scenario work exactly?

**Comment by mohsha-msft** [comment]
Hey @vick-git ,

Thanks for reaching out!
AzCopy is not planning to support the transfer for tables and queues in the nearby roadmap.
