### ISSUE TITLE
(Continuouts Issue)AzCoopy rm command with Service Principal" does not work, because of 401 in 10.10.0

### ISSUE THREAD

**Issue by nao-830713** [Azure/azure-storage-azcopy#1426]
### Which version of the AzCopy was used? 
10.10.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2016

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

chcp 65001
Set rc=0
Set AZCOPY_LOG_LOCATION=D:\05_SMD_Tools\AzureStorage\AZCOPY_LOG
Set AZCOPY_SPA_CLIENT_SECRET=XXXXXX 2>&1 >> "E:\SASWORK\_TD17840_SAS-DEV02_\#LN00112" 
cd /d "C:\Program Files (x86)\AzCopy" 2>&1 >> "E:\SASWORK\_TD17840_SAS-DEV02_\#LN00112" 
"azcopy.exe" login --service-principal --application-id XXXXXX --tenant-id=XXXXXX 2>&1 >> "E:\SASWORK\_TD17840_SAS-DEV02_\#LN00112" 
if %ERRORLEVEL% neq 0 (Set rc=%ERRORLEVEL% & goto logout)
"azcopy.exe" rm "https://XXX.blob.core.windows.net/test-blob01/Remove_pattern01" --recursive=true --include-pattern "販売単価.txt*" 2>&1 >> "E:\SASWORK\_TD17840_SAS-DEV02_\#LN00112" 
 
if %ERRORLEVEL% neq 0 (Set rc=%ERRORLEVEL% & goto logout) 
:logout
"azcopy.exe" logout 2>&1 >> "E:\SASWORK\_TD17840_SAS-DEV02_\#LN00112"  
exit /b %rc%
 * XXX is masked strings

### What problem was encountered?
"azcopy .exe rm" does not work, because of "401: DELETE ERROR -401 Server failed to authenticate the request. "
But "azcopy.exe copy" works.
And in 10.6.0 version , "azcopy.exe rm" works with same command and client_id.

### Have you found a mitigation/solution?
no
[24100808-77fd-9348-5d4c-837f9947c7f4.log](https://github.com/Azure/azure-storage-azcopy/files/6363855/24100808-77fd-9348-5d4c-837f9947c7f4.log)
 #[azcopy_command.txt](https://github.com/Azure/azure-storage-azcopy/files/6363856/azcopy_command.txt)

**Comment by nao-830713** [comment]
#1370

**Comment by nakulkar-msft** [comment]
The fix was undone because of a merge problem. Will be fixed by #1427

**Comment by nakulkar-msft** [comment]
Fixed in dev
