### ISSUE TITLE
Is there a way to stop AzCopy check for new versions?

### ISSUE THREAD

**Issue by Ikbal01** [Azure/azure-storage-azcopy#1430]

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/1175

**Comment by mohsha-msft** [comment]
Hey @Ikbal01  ,

Thanks for reaching out!

There is currently no way to disable version check in AzCopy. We, however, now support disabling logging in Syslog or Windows Event Logger by using environment variable `AZCOPY_DISABLE_SYSLOG`.  By default we log to these channels. However, to reduce the noise in Syslog/Windows Event Log, consider setting this environment variable to true. I suggest you try that. 
We're also working on improving the check time a bit. Please reach out for any concerns or clarity on the matter.

**Comment by Ikbal01** [comment]
Thank you!
