### ISSUE TITLE
Unexpected EOF error

### ISSUE THREAD

**Issue by AminaLAA** [Azure/azure-storage-azcopy#1432]
Hello,

I am using azcoy to get some files from Azure, but I got this error in return:
	2021/04/28 09:35:14 ==> REQUEST/RESPONSE (Try=1/2.2411262s, OpTime=2.2411262s) -- REQUEST ERROR
   HEAD https://dat831000sta002.blob.core.windows.net/90023333?se=2021-04-29t09%3A02%3A22z&sig=-REDACTED-&sp=rl&sr=c&sv=2019-07-07&timeout=901
   User-Agent: [AzCopy/10.9.0 Azure-Storage/0.13 (go1.15; Windows_NT)]
   X-Ms-Client-Request-Id: [988744d1-02bb-4355-5ea1-bf16a2bdb278]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   ERROR:
	-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
	HTTP request failed

	Head "https://dat831000sta002.blob.core.windows.net/90023333?se=2021-04-29T09%3A02%3A22Z&sig=-REDACTED-&sp=rl&sr=c&sv=2019-07-07&timeout=901": unexpected EOF
This is the request I am using: azcopy.exe copy https://dat831000sta002.blob.core.windows.net/90023333?sv=2019-07-07&sr=c&sig=2F25kWsUpe4U%2FS6pTxOGrbwi1EkfFkdvHGgxHCkEIN0%3D&se=2021-04-28T14%3A20%3A17Z&sp=rl D:\EAI\workspace\tibco\temp\france\rh\azure --recursive --include-pattern *tibco*.csv --include-after 2021-04-26T16:20:17.396+02:00

The command is working fine on the server with my personnal account but not with the service one and we are both defined as administrator users on the server.
Do you have any idea what could be the reason of this problem?

Thank you

### Which version of the AzCopy was used? 
AzCopy/10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 

### What command did you run?
Azcopy.exe copy

### What problem was encountered?
Please read my description

### How can we reproduce the problem in the simplest way?
The problem is reproducable with the service account

### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
@AminaLAA Do yoo still see this issue? What is the bandwidth available on your machine?

**Comment by AminaLAA** [comment]
Hello,
I switched to use Azure API instead of the azCopy command and it works fine :)
Thank you!
