### ISSUE TITLE
CannotVerifyCopySource Error while performing AzCopy Sync between two Large File Shares 

### ISSUE THREAD

**Issue by nanda0285** [Azure/azure-storage-azcopy#1433]
### Which version of the AzCopy was used? 
10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?  
azcopy sync 'https://[Source Storage Account].file.core.windows.net/[file-path]?[SAS Token]' 'https://[Destination Storage Account].file.core.windows.net/[file-path]?[SAS Token]' --recursive  

### What problem was encountered?
INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission 
===== RESPONSE ERROR (ServiceCode=CannotVerifyCopySource) =====
Description=This request is not authorized to perform this operation.
Code: CannotVerifyCopySource  

RESPONSE Status: 403 This request is not authorized to perform this operation.
X-Ms-Error-Code: [CannotVerifyCopySource]

### How can we reproduce the problem in the simplest way?
The Source Storage Account (i.e., East US) and the Destination Storage Account (i.e., West US) are in different Regions. 
Both the Storage Accounts are Domain Joined, are behind Firewall and have Private Endpoints enabled.  
The Machine on which AzCopy is being run on has access to both Source and Destination Storage Accounts.  
The file path contains ~3000 files and the sync operation identified around 11 files to be synced but failed with the above error while syncing the first file itself.  

### Have you found a mitigation/solution?
Not yet.

**Comment by nakulkar-msft** [comment]
Typically this would mean that the sas on source does not have enough permissions.
We do not have logs at this point, closing this issue because of age. Please reopen if you see this again.
