### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jn-githubber** [Azure/azure-storage-azcopy#1435]
### Which version of the AzCopy was used? 
10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy sync 'source 'dest' --recursive --recursive --cap-mbps 200
and
azcopy copy 'source 'dest' --recursive --recursive --cap-mbps 200

`100.0 %, 144497 Done, 21 Failed, 3904314 Pending, 4048832 Total, 2-sec Throughput (Mb/s): 89.9784**panic: runtime error: invalid memory address or nil pointer dereference**
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1870a05]

goroutine 8668 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.ErrorEx.ErrorCodeAndString(0x0, 0x0, 0x10b9085, 0x222b480, 0xc01c905180, 0x3, 0xc0149c5790)
        /home/vsts/work/1/s/ste/ErrorExt.go:25 +0x45
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).LogError(0xc0576a8d20, 0xc081c41920, 0x56, 0xc008599a20, 0xa1, 0x0, 0x0)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:842 +0x54
github.com/Azure/azure-storage-azcopy/v10/ste.epilogueWithCleanupDownload(0x1ca9580, 0xc0576a8d20, 0x1c94860, 0xc021dad780, 0x1c8efe0, 0xc0194ed560, 0x1c9a520, 0xc00d4ba000)
        /home/vsts/work/1/s/ste/xfer-remoteToLocal-file.go:360 +0xa13
github.com/Azure/azure-storage-azcopy/v10/ste.remoteToLocal_file.func2()
        /home/vsts/work/1/s/ste/xfer-remoteToLocal-file.go:227 +0x70
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).runActionAfterLastChunk(...)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:551
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).ReportChunkDone(0xc0576a8d20, 0xc081c41920, 0x56, 0x0, 0xacf2, 0xc0358c383c, 0xc0358c3880, 0x100000001)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:538 +0x118
github.com/Azure/azure-storage-azcopy/v10/ste.createChunkFunc.func1(0x71)
        /home/vsts/work/1/s/ste/sender.go:181 +0x1eb
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0xc0003c84e0, 0x71)
        /home/vsts/work/1/s/ste/JobsAdmin.go:433 +0xdf
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
        /home/vsts/work/1/s/ste/JobsAdmin.go:362 +0x6a5`
### How can we reproduce the problem in the simplest way?
Happens everytime. I am trying to download all contents of my blob storage account to my local computer. 

### Have you found a mitigation/solution?
no, I tried azcopy copy aswell but this results in the same problem.

**Comment by CheeseBreadIsGood** [comment]
Does going back to a previous version of AZcopy fix the error? I ran into this issue on version 10.10.0. I then used version 10.8 and the error went away. Everything worked fine.

**Comment by nakulkar-msft** [comment]
#1421
