### ISSUE TITLE
azcopy list 10.10 linux bug

### ISSUE THREAD

**Issue by kwhitehall** [Azure/azure-storage-azcopy#1444]
### Which version of the AzCopy was used? 
10.10.0 
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
~/azcopy_linux_amd64_10.10.0/azcopy list https://noaahrrr.blob.core.windows.net/hrrr/hrrr.20210512/conus/hrrr.t12z.wrfsfcf00.grib2
### What problem was encountered?
"failed to obtain credential info: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public"

### How can we reproduce the problem in the simplest way?
Run above command

### Have you found a mitigation/solution?
Yes, using v10.9.0 
Note that problem does not occur with Windows version. 
![Screenshot (910)_LI](https://user-images.githubusercontent.com/7198635/118154768-7367d780-b3e5-11eb-9440-a2204b82fbe6.jpg)
![Screenshot (910)_LI](https://user-images.githubusercontent.com/7198635/118154818-84b0e400-b3e5-11eb-9085-067d95b384c9.jpg)

**Comment by nakulkar-msft** [comment]
Fixed in dev #1427
