### ISSUE TITLE
How to avoid copying duplicates using azcopy tool at Blob container level

### ISSUE THREAD

**Issue by thiszparveen** [Azure/azure-storage-azcopy#1449]
### Which version of the AzCopy was used? 
AzCopy 10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy cp "S:/Shared Documents/Stuff I Am Learning" "https://[account].blob.core.windows.net/[container]/[path/to/directory]?[SAS]" --recursive --put-md5 --overwrite=true

### What problem was encountered?
I don't want to copy duplicate files in the blob container. if it has any duplicates, it should log or prompt 
I am copying files from local to Azure blob. Currently it is copying duplicate files if there are exists in different folder structure. How should I avoid duplicates? If they are any duplicate files it should log / prompt/ overwrite. is this supported in in Azcopy.
Is there any other way to avoid duplicates.

### How can we reproduce the problem in the simplest way?
You can have same file in mutiple foder paths and try to copy using azcopy tool using above command. it is copying all the files though these are duplicates

### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
@thiszparveen When you mean duplicate files, do you mean symlinks to the same file?

**Comment by MarkReynoldsUK** [comment]
@thiszparveen Have you tried azcopy sync? https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync

**Comment by mohsha-msft** [comment]
Hey @thiszparveen ,

Is your problem resolved? 
I'm closing this issue. If you're experiencing the same problem, please reopen the issue later.
