### ISSUE TITLE
AzCopy 10.0.4 for Mac shows successful completion of copy while untrue

### ISSUE THREAD

**Issue by jessMaia** [Azure/azure-storage-azcopy#145]
### Which version of the AzCopy was used? 

azcopy_darwin_amd64_10.0.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac

### What command did you run?
```
/azcopy_darwin_amd64_10.0.4/azcopy copy \
 "/data/reads"  \
 "https://myaccount.blob.core.windows.net/mycontainer?sastokenhere" \
 --recursive=true
```
### What problem was encountered?

The final copy log reported no skips or failures while a large amount of data was simply ignored, i.e., not copied from my laptop to Blob Storage.  See this excerpt

```
Elapsed Time (Minutes): 297.2183
Total Number Of Transfers: 13436255
Number of Transfers Completed: 13436255
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 965228610000
Final Job Status: Completed
```

### How can we reproduce the problem in the simplest way?
Copy a large number of files ( > 13 million) close to 1TB in size from a local drive to Blob storage and observe if all data was transferred.

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Closing due to lack of response.

@jessMaia Please try the latest v10.0.8 as we've made significant improvements to the tool.
