### ISSUE TITLE
Azcopy  file.core.windows.net message Service may be limiting speed.

### ISSUE THREAD

**Issue by HandyManny66** [Azure/azure-storage-azcopy#1451]
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

.\azcopy.exe copy `
"https://******************.file.core.windows.net/blobfolder/*?******************" `
"https://******************".file.core.windows.net/blobfolder?st=******************" `
--recursive 

### Have you found a mitigation/solution? just wait. 
i get this message Service may be limiting speed. 
how can i copy with in Azure File not downloads to my pc or in between my pc and azure.
can it be local to the file storage?  is from one folder to the next with in the same file storage and with in the same azure files root folder.

**Comment by nakulkar-msft** [comment]
@HandyManny66  The statement you see is regarding perf and does not indicate transfer failure. Your transfers should proceed fine with the command above. Do you see any transfer failure?

**Comment by zezha-msft** [comment]
Hi @HandyManny66, the transferring of data is already happening on the service side, i.e. the data never flows through your local machine.

"service may be limiting speed" means that you are being throttled. Please consider setting a lower concurrency or set  AZCOPY_CONCURRENCY_VALUE  to AUTO. Doc is [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize?toc=/azure/storage/blobs/toc.json#increase-the-number-of-concurrent-requests).
