### ISSUE TITLE
cannot scan the path 

### ISSUE THREAD

**Issue by jn-githubber** [Azure/azure-storage-azcopy#1453]
### Which version of the AzCopy was used? 
10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2019

### What command did you run?
 .\azcopy.exe copy $targetfile $Uploadfile  

$TargetFile Variable gets filled from the same input file as $Uploadfile but from a value before an "," 
$Uploadfile is a variable that uses the destinationpath + input from a file + the SAS key
see below

Value before the , is captured in variable $1a.
Value after , is captured in variable $1b 

The Inputfile looks like this
`E:\Test\1084446332_1018229882_80857085_703190389__2019-07-02.pdf,account\80857085\1084446332_1018229882_80857085_703190389__2019-07-02.pdf

E:\Test\1084446332_1018229882_80857085_703190389__2019-07-01.pdf,account\80857085\1084446332_1018229882_80857085_703190389__2019-07-01.pdf`

### What problem was encountered?
failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\?\E:\Test\1084446332_1018229882_80857085_703190389__2019-07-01.pdf, please verify that it is a valid.

### How can we reproduce the problem in the simplest way?
Unknown

### Have you found a mitigation/solution?
Different versions of azcopy, same script used to work with azcopy version 7.  Config of the script was a bit different since when used the Access Key for validation and that's not supported anymore.

I can provide the full PowerShell script if required.

**Comment by jn-githubber** [comment]
I am now getting a different error 

" Source with location type Local doesn't exist "

What does this mean and how can I resolve this??

**Comment by mohsha-msft** [comment]
Hey @jn-githubber ,

What is the exact command you're trying to execute?

**Comment by jn-githubber** [comment]
Hi Mohsha!

It looks like this

.\azcopy.exe" /Source:e:\test\something.pdf /Dest:https://something.blob.core.windows.net/somecontainer/something\containername\samefilenameassource.pdf /DestKey:****** /Y

Which results in
Error parsing source location "e:\test\something.pdf": Source with location type Local doesn't exist. For more details, please type "AzCopy /?:Source" or use verbose option /V.

**Comment by mohsha-msft** [comment]
Please try this and let me know.

`.\azcopy.exe E:\test\something.pdf "https://something.blob.core.windows.net/somecontainer/something\containername\samefilenameassource.pdf?SAS"`

Most likely your source isn't properly formatted.

**Comment by jn-githubber** [comment]
I tried that and then I get the error

failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\?\E:\Test\Input\something.pdf, please verify that it is a valid.

using 10.10 azcopy

**Comment by mohsha-msft** [comment]
Hey @jn-githubber ,

I noticed you raised issue for AzCopy `10.10.0` which is v10. We don't support v7 anymore. Can you please ask your customer to move to AzCopyV10?

After that's done, 
`.\azcopy.exe E:\path\to\upload "https://something.blob.core.windows.net/somecontainer/something\containername\samefilenameassource.pdf?<SAS>" `

If you're still getting "Unable to scan", try navigating to this path on command-prompt or file explorer because most likely that path provided is incorrect.

**Comment by jn-githubber** [comment]
Mosha, many thanks fixed the issue, seemed like the directory wasn't accesible for my account
