### ISSUE TITLE
Problems copying from Files to Blob. 

### ISSUE THREAD

**Issue by Diego-MX** [Azure/azure-storage-azcopy#1454]
### Which version of the AzCopy was used? 
`2021/05/27 02:13:02 AzcopyVersion  10.10.0`

### Which platform are you using? (ex: Windows, Mac, Linux)
`2021/05/27 02:13:02 OS-Environment  windows`

### What command did you run?
 `azcopy copy "https://<storage-account>.file.core.windows.net/<file-share>/my-filename.txt?<sas-token-with-all-permissions>" "https://<same-storage-account>.blob.core.windows.net/<blob-share>/folder/my-filename.txt"`

### What problem was encountered?
```
INFO: Scanning...
INFO: Authenticating to destination using Azure AD

INFO: Failed to create one or more destination container(s). Your transfers may still succeed if the container already exists.
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 5651b09b-a007-ce43-4235-2eb4287ac2ba has started
Log file is located at: C:\Users\my-name\.azcopy\5651b09b-a007-ce43-4235-2eb4287ac2ba.log

0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,


Job 5651b09b-a007-ce43-4235-2eb4287ac2ba summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed
```

In log file: 
```
[lines 17-27]
===== RESPONSE ERROR (ServiceCode=ResourceNotFound) =====
Description=The specified resource does not exist.
RequestId:d8b94b38-801a-00f7-539d-520b02000000
Time:2021-05-27T02:13:03.5506526Z, Details: 
   Code: ResourceNotFound
   GET https://<storage-account>.file.core.windows.net/<file-container>/my-filename.txt?restype=**directory**&<FILE-TOKEN>
   User-Agent: [AzCopy/10.10.0 Azure-Storage/0.8.0 (go1.15; Windows_NT)]
   X-Ms-Client-Request-Id: [8c459393-13ce-482d-6bb8-a558c6b79ae3]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified resource does not exist.
```

### How can we reproduce the problem in the simplest way?

It's a simple example, just copy a file from one File account to another Blob account.  
I have been able to do it, using my computer in the middle. 

### Have you found a mitigation/solution?
Using my computer in the middle, which I dislike, and I'm getting sidelooks from the security people.

**Comment by zezha-msft** [comment]
Hi @Diego-MX, please search for the keyword `COPYFAILED` instead, it should show you the actual failure reason.

The quoted error is benign and didn't cause the failure.
