### ISSUE TITLE
AzCopy Node package missing options

### ISSUE THREAD

**Issue by bragma** [Azure/azure-storage-azcopy#1458]
### Which version of the AzCopy was used? 
@azure-tools/azcopy-node 2.2.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What problem was encountered?
Package does not support --include-path and --cache-control options

### Have you found a mitigation/solution?
Not with this package. Will missing options be added?

**Comment by MRayermannMSFT** [comment]
@bragma thanks for the request. We'll try to add those options for the next release of the node package. That will go out at about the same time the next release of AzCopy.

**Comment by MRayermannMSFT** [comment]
@bragma sorry it took so long to get it out, but 2.3.0 of the package is now available. It makes the include path and cache control options available (among other things):
![image](https://user-images.githubusercontent.com/21112697/125856101-23d43012-2c03-4e55-ada0-8c52d0c1d222.png)

**Comment by zezha-msft** [comment]
Fixed.
