### ISSUE TITLE
azcopy --recursive moves directory with files rather than just files

### ISSUE THREAD

**Issue by PARADISSEEKR** [Azure/azure-storage-azcopy#1463]
##### Note: The version is visible when running AzCopy without any argument
10.10.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy copy https://[account].blob.core.windows.net/[container]/path/to/old_file_dir https://[account].blob.core.windows.net/[other_container]/path/to/new_file_dir --recursive --include-pattern "*.my_file_pattern"`
### What problem was encountered?
I would expect the above to result in my files copied to new_file_dir.

`https://[account].blob.core.windows.net/[other_container]/path/to/new_file_dir/file1.my_file_pattern
https://[account].blob.core.windows.net/[other_container]/path/to/new_file_dir/file2.my_file_pattern`
Instead, I get my files copied to new_file_dir/old_file_dir.

`https://[account].blob.core.windows.net/[other_container]/path/to/new_file_dir/old_file_dir/file1.my_file_pattern
https://[account].blob.core.windows.net/[other_container]/path/to/new_file_dir/old_file_dir/file2.my_file_pattern`

**Comment by adreed-msft** [comment]
On your source, you should add /*.

e.g. `azcopy copy https://[account].blob.core.windows.net/[container]/path/to/old_file_dir/* https://[account].blob.core.windows.net/[other_container]/path/to/new_file_dir --recursive --include-pattern "*.my_file_pattern"`
