### ISSUE TITLE
Can not find files when copy from AzureStorage-path written with backslash as separator .

### ISSUE THREAD

**Issue by nao830713** [Azure/azure-storage-azcopy#1465]
### Which version of the AzCopy was used? 
10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2019

### What command did you run?
https://smddevtest.blob.core.windows.net/interfacedata/pattern02%5CSub_Folder/%2A D:\10_DataTransfer\AzureStorage\Download\pattern01 --recursive=false --include-pattern sx_test02.txt* 

### What problem was encountered?
We could copy the files from AzureFolder using path with backslash "%5C" as folder separator in AzCopy V8 version.
But the 10.10.0's copy from AzureStorage function can not find files with same path.

### How can we reproduce the problem in the simplest way?
Could you support backslash separator in copy function from AzureStorage.
 * Currently, Copy to AzureStorage function supports backslash separator in 10.10.0.

### Have you found a mitigation/solution?
Now, we get back to use V8 version AzCopy.

**Comment by t-cguruceaga-msft** [comment]
Hi @nao830713, the current version of AzCopy does not supports "%5C" as backslash separator instead try using a regular backslash "/" for sub folders.
