### ISSUE TITLE
AZCopy from Windows App Service Instance not working (ok if I use copy from Microsoft download page)

### ISSUE THREAD

**Issue by esukmonica** [Azure/azure-storage-azcopy#1468]
### Which version of the AzCopy was used? 
AzCopy 10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy.exe  sync "E:\logfiles\GE" "https://xxx.file.core.windows.net/logs/?sv=xxx" --recursive

### What problem was encountered?

I am developing a webjob, currently testing it locally on my development machine. I got the AzCopy.exe for Windows 64-bit from :
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

and this works locally (running debug from within VS 2019).
[AZCOPY_WORKING.txt](https://github.com/Azure/azure-storage-azcopy/files/6624695/AZCOPY_WORKING.txt)

However after publishing the webjob, it was not working, no errors given. I could see my logs for started job, completed job but I could not see any information regarding az copy being executed (i.e. Files Scanned at Source , at Destination, etc

So I downloaded the "AzCopy.exe" from within the Windows App Service instance at D:\devtools\AzCopy\AzCopy.exe (which also appears to be AzCopy 10.10.0), and again tested the webjob locally running on debug and it is not working, again no errors and I can see my logs as everything being completed but no file transfer is occurring.
[AZCOPY_NOT_WORKING.txt](https://github.com/Azure/azure-storage-azcopy/files/6624694/AZCOPY_NOT_WORKING.txt)

If I put back the AzCopy.exe that I got from  https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10, then everything starts to work and I can see the files being scanned, transferred, etc

Any help will be greatly appreciate

**Comment by adreed-msft** [comment]
So for reference, manually placing azcopy into the app service works? Are you perhaps not packaging it with your app service on accident?

Hit properties on the executable in VS and make sure you have copy to output directory set to either "Always copy" or "Copy if newer".
![image](https://user-images.githubusercontent.com/49764384/123891885-6e67d480-d90e-11eb-86fb-fa9c42263551.png)

**Comment by esukmonica** [comment]
I did not test that. My intention was to use the AzCopy that is already within the app service dev tools, rather than deploying another one (which in theory is the same?) with the webjob, Maybe I should conduct this test as a work around solution.

I would really like to understand why they are behaving differently even though they appear to be the same version, or another way of asking, is the AzCopy.exe within the app service devtools the same as the one we can download from microsoft download page?

**Comment by LordJZ** [comment]
I also use azcopy in an Azure App Service. I found out that the vm has two versions of azcopy, both old:

```
D:\home>D:\devtools\AzCopy\AzCopy.exe /?
------------------------------------------------------------------------------
AzCopy 6.3.0 Copyright (c) 2017 Microsoft Corp. All Rights Reserved.
------------------------------------------------------------------------------
```

```
D:\devtools\AzCopy>D:\devtools\AzCopy8\AzCopy.exe /?
------------------------------------------------------------------------------
AzCopy 8.1.0-netcore Copyright (c) 2018 Microsoft Corp. All Rights Reserved.
------------------------------------------------------------------------------
```

So I had to ship my own version of azcopy.
