### ISSUE TITLE
panic error when using azcopy benchmark (used to work fine till today) 

### ISSUE THREAD

**Issue by Hamza-Benm** [Azure/azure-storage-azcopy#1474]
##### Note: The version is visible when running AzCopy without any argument
tried with 10.10 and 10.9
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 (all the updates)
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy bench https://hbstotest.file.core.windows.net/hamzasto?xxxxxmySASKeyxxxxx" --file-count 100 --size-per-file 1G
### What problem was encountered?
got this panic error : 

panic: couldn't create job part plan file "b73ea971-b6cd-3f48-5e4f-39823d48a92b--00000.steV16": open C:\Users\adm-id184826\.azcopy/plans/b73ea971-b6cd-3f48-5e4f-39823d48a92b--00000.steV16: L’opération demandée n’a pu s’accomplir sur un fichier ayant une section mappée utilisateur ouverte.

goroutine 991 [running]:
github.com/Azure/azure-storage-azcopy/ste.JobPartPlanFileName.Create(0xc015fbfc40, 0x32, 0xb73ea97100000000, 0x82394f5e3f48b6cd, 0x2ba9483d, 0x400000000000001, 0x3, 0x0, 0x0, 0x0, ...)
        /home/vsts/work/1/s/ste/JobPartPlanFileName.go:134 +0x276c
github.com/Azure/azure-storage-azcopy/ste.ExecuteNewCopyJobPartOrder(0xb73ea97100000000, 0x82394f5e3f48b6cd, 0x2ba9483d, 0x400000000000001, 0x3, 0x0, 0x0, 0x0, 0xc000260420, 0x60, ...)
        /home/vsts/work/1/s/ste/init.go:143 +0xb9
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0xeebe45, 0x10, 0xd45080, 0xc097b65340, 0xd450c0, 0xc097e527e0, 0xe40701, 0xc097e527e0)
        /home/vsts/work/1/s/cmd/rpc.go:44 +0x91f
github.com/Azure/azure-storage-azcopy/cmd.glob..func4(0xeebe45, 0x10, 0xd45080, 0xc097b65340, 0xd450c0, 0xc097e527e0)
        /home/vsts/work/1/s/cmd/rpc.go:36 +0x65
github.com/Azure/azure-storage-azcopy/cmd.(*copyTransferProcessor).sendPartToSte(0xc097e80120, 0x500000000, 0x1031740, 0xc0205e0a00)
        /home/vsts/work/1/s/cmd/zc_processor.go:132 +0x8d
github.com/Azure/azure-storage-azcopy/cmd.(*copyTransferProcessor).dispatchFinalPart(0xc097e80120, 0xc097e80120, 0xf155fd, 0x160ef40)
        /home/vsts/work/1/s/cmd/zc_processor.go:108 +0x45
github.com/Azure/azure-storage-azcopy/cmd.newRemoveEnumerator.func2(0xc0205e0a00, 0x0)
        /home/vsts/work/1/s/cmd/removeEnumerator.go:77 +0x3e
github.com/Azure/azure-storage-azcopy/cmd.(*copyEnumerator).enumerate(0xc0205e0a40, 0xc0205e0a40, 0x0)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:673 +0x9f
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc000081800, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copy.go:1266 +0x865
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc000081800, 0xc0163fbfc0, 0xc2961f)
        /home/vsts/work/1/s/cmd/copy.go:1045 +0xbc
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).launchFollowup.func1(0xc097b5c900, 0xc000080c00)
        /home/vsts/work/1/s/cmd/copy.go:1352 +0x79
created by github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).launchFollowup
        /home/vsts/work/1/s/cmd/copy.go:1349 +0x66

### How can we reproduce the problem in the simplest way?
ran the same commande from 3 differents computers (which used to work fine) , the panic error appears randomly , sometimes at the end of the copy sometime in the middle (stopping the bench) . 
### Have you found a mitigation/solution?

no

**Comment by Hamza-Benm** [comment]
Tried running the benchmark on a different server , this time using the 10.10 and got the following panic message  : 

azcopy : panic: couldn't create job part plan file "531e1138-94dd-424c-462f-9f132e6ab5c3--00000.steV16": open 
C:\Users\account\.azcopy/plans/531e1138-94dd-424c-462f-9f132e6ab5c3--00000.steV16: The requested operation cannot be performed on a file with a user-mapped section open.
Au caractère Ligne:1 : 1
+ azcopy benchmark $path_bench --file-count 100 --size-per-file 1G
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: couldn't...d section open.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
goroutine 1373 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.JobPartPlanFileName.Create(0xc038dae2c0, 0x32, 0x531e113800000000, 0x139f2f46424c94dd, 0xc3b56a2e, 0x400000000000001, 0x3, 0x0, 0x0, 
0x0, ...)
	/home/vsts/work/1/s/ste/JobPartPlanFileName.go:134 +0x27f5
github.com/Azure/azure-storage-azcopy/v10/ste.ExecuteNewCopyJobPartOrder(0x531e113800000000, 0x139f2f46424c94dd, 0xc3b56a2e, 0x400000000000001, 0x3, 0x0, 0x0, 0x0, 0xc0000826c0, 
0x5e, ...)
	/home/vsts/work/1/s/ste/init.go:143 +0xb9
github.com/Azure/azure-storage-azcopy/v10/cmd.inprocSend(0xe239c5, 0x10, 0xc7a720, 0xc038db2000, 0xc7a760, 0xc03c5dd1e0, 0xed85d9b01, 0xc03c5dd1e0)
	/home/vsts/work/1/s/cmd/rpc.go:44 +0x91f
github.com/Azure/azure-storage-azcopy/v10/cmd.glob..func4(0xe239c5, 0x10, 0xc7a720, 0xc038db2000, 0xc7a760, 0xc03c5dd1e0)
	/home/vsts/work/1/s/cmd/rpc.go:36 +0x65
github.com/Azure/azure-storage-azcopy/v10/cmd.(*copyTransferProcessor).sendPartToSte(0xc038d837a0, 0x0, 0xc000328054, 0x8)
	/home/vsts/work/1/s/cmd/zc_processor.go:133 +0x8d
github.com/Azure/azure-storage-azcopy/v10/cmd.(*copyTransferProcessor).dispatchFinalPart(0xc038d837a0, 0xe275fc, 0x14, 0x0)
	/home/vsts/work/1/s/cmd/zc_processor.go:109 +0x45
github.com/Azure/azure-storage-azcopy/v10/cmd.newRemoveEnumerator.func2(0xc038bb4680, 0x0)
	/home/vsts/work/1/s/cmd/removeEnumerator.go:79 +0x3e
github.com/Azure/azure-storage-azcopy/v10/cmd.(*copyEnumerator).enumerate(0xc038bb46c0, 0xc038bb46c0, 0x0)
	/home/vsts/work/1/s/cmd/zc_enumerator.go:682 +0x9f
github.com/Azure/azure-storage-azcopy/v10/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc00012ac00, 0x0, 0x0)
	/home/vsts/work/1/s/cmd/copy.go:1313 +0x8a5
github.com/Azure/azure-storage-azcopy/v10/cmd.(*cookedCopyCmdArgs).process(0xc00012ac00, 0x4282ca, 0xc03bc2d278)
	/home/vsts/work/1/s/cmd/copy.go:1088 +0xbc
github.com/Azure/azure-storage-azcopy/v10/cmd.(*cookedCopyCmdArgs).launchFollowup.func1(0xc038d664c8, 0xc00004fc00)
	/home/vsts/work/1/s/cmd/copy.go:1399 +0x79
created by github.com/Azure/azure-storage-azcopy/v10/cmd.(*cookedCopyCmdArgs).launchFollowup
	/home/vsts/work/1/s/cmd/copy.go:1396 +0x66

**Comment by adreed-msft** [comment]
Could you try with 10.11? Can you manage a normal copy/sync operation, or is it specific to benchmark?

**Comment by kibnelbachyr** [comment]
@adreed-msft, I have the same exact issue with azcopy version 10.12.2. The first run of the command went well but the second throws this error : 
`INFO: Any empty folders will be processed, because deletion is from a folder-aware location
0.0 %, 0 Done, 0 Failed, 100 Pending, 0 Skipped, 100 Total, panic: couldn't create job part plan file "b38f396a-e48a-0247-459e-d530ecf7d0e7--00000.steV16": open C:\Users\-------\.azcopy/plans/b38f396a-e48a-0247-459e-d530ecf7d0e7--00000.steV16: The requested operation cannot be performed on a file with a user-mapped section open.` 

Could you please advice on this ?

**Comment by nakulkar-msft** [comment]
Fixed with #1598

**Comment by mohsha-msft** [comment]
Fix released in AzCopy `10.14.0`

**Comment by jcopps** [comment]
Encountering this in 10.25.1
