### ISSUE TITLE
When a single / is in list of files, AzCopy deletes all blobs under the src directory 

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#1475]
### Which version of the AzCopy was used? 
10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
All

### What command did you run?
Delete blob

### What problem was encountered?
If a line ends with consecutive /s in the list of files file, e.g. /, AzCopy will delete all blobs under the src directory. The expected result is that only blobs with a prefix / under the src directory are deleted.

### How can we reproduce the problem in the simplest way?
Have a blob container with these two blobs
blob.txt
/blob.txt

azcopy delete https://acct.blob.core.windows.net/container/

list of files content:
/

Check the result, blob.txt is deleted. Only blob.txt is deleted.

### Have you found a mitigation/solution?
Manually filter the lines before passing AzCopy the list of files. I think a quick mitigation would be simply to ignore lines that are / so people won't accidentally delete their blobs.

**Comment by nakulkar-msft** [comment]
The expectation is incorrect. The blob storage is a different product and does not behave traditional filesystems behave, and clients (like azcopy) adhere to convention that the path separators in blob name are used as virtual directories. Please follow the [convention ](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names) recommended here. Azcopy will consider any path ending with '/' as a directory.
