### ISSUE TITLE
How can we pause an AzCopy download in progress?

### ISSUE THREAD

**Issue by jesskube** [Azure/azure-storage-azcopy#1476]
My team is using the latest **AzCopy** (currently 10.10.0) to typically download a single large file from Blob Storage using a single **AzCopy.exe copy** command. The size of one of our single file downloads is roughly 10 GiB to 50 GiB.

Is there a way that we can effectively pause a download in-progress? Perhaps a way that we can have AzCopy.exe temporarily reduce the transfer rate while in-progress?

Could you suggest a way to best temporarily suspend, pause, or delay **AzCopy.exe** during a large download, without breaking the connection?

Thanks
-Jess

**Comment by siminsavani-msft** [comment]
Hi @jesskube one option is to cancel the job (CTRL + C) and then use `azcopy jobs resume <jobID>` to resume transfers. 

Hope this helps!
