### ISSUE TITLE
Access Denied on folders while using --backup 

### ISSUE THREAD

**Issue by Hamza-Benm** [Azure/azure-storage-azcopy#1479]
### Which version of the AzCopy was used? 
10.11.0 and 10.10.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 and WIndows Server 2019
### What command did you run?
in my case is a network folder , my account is in the Backup operator group in the domain , ran the command in elevated Powershell sessions (and Cmd too) 

Azcopy copy "G:\testfolder" "https:\\sto.file.core.windows.net\Sharetest***SASkey***" --backup --recursive --preserve-smb-info=true
### What problem was encountered?
can't copy folders with message Accessing "G:\testfolder"

INFO : Accessing '\\?\G:\testfolder' failed with error : open \\?\G:\testfolder: access denied 

verified my privileges with WHOAMI /priv and SeBackupPrivilege  is listed (disabled but listed which is normal) 

### How can we reproduce the problem in the simplest way?

re-run the command on a folder where you don't have access rights 

### Have you found a mitigation/solution?
no

**Comment by zezha-msft** [comment]
--backup Activates Windows' SeBackupPrivilege for uploads, or SeRestorePrivilege for downloads, to allow AzCopy to see and read all files, regardless of their file system permissions, and to restore all permissions. **Requires that the account running AzCopy already has these permissions (for example, has Administrator rights or is a member of the Backup Operators group)**. This flag activates privileges that the account already has.

Hi @Hamza-Benm, unfortunately we cannot help debug environment issues. Please double check that you have the right permissions.
