### ISSUE TITLE
Cannot find files when AzCopy from AzureStorage using --include-pattern option

### ISSUE THREAD

**Issue by nao-830713** [Azure/azure-storage-azcopy#1483]
### Which version of the AzCopy was used? 
10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2016

### What command did you run?

"azcopy.exe"   copy "https://XXX.blob.core.windows.net/interfacedata/SMD_INPUT/*"   "D:\10_DataTransfer\PJ04\AzureStorage\SMD_INPUT"   --recursive=false  --include-pattern   "ABCED.xlsx*"

### What problem was encountered?
Azcopy can not fine file, when using --include-pattern option and if the file has same name with folder at same level.
[202106_AzCopy_Download_Issue.xlsx](https://github.com/Azure/azure-storage-azcopy/files/6705425/202106_AzCopy_Download_Issue.xlsx)
[AzCopy_log_NG.log](https://github.com/Azure/azure-storage-azcopy/files/6705426/AzCopy_log_NG.log)
[AzCopy_log_OK.log](https://github.com/Azure/azure-storage-azcopy/files/6705428/AzCopy_log_OK.log)

### How can we reproduce the problem in the simplest way?
1) Set file and folder at same level in AzureStorage Container.  Please check attached .xlsx file.
2) Set required file in folder set at 1) step.
3) Do azcopy command from path 1)-folder and  assign "--include-pattern" with 2)-filename.

### Have you found a mitigation/solution?
Yes, we delete the file has same name with folder, we can download required files.

**Comment by nakulkar-msft** [comment]
@nao-830713 Having Virtual directories and flles with identical names at same level is not recommended. This scenario will not be supported.
