### ISSUE TITLE
Environment Variable azcopy_request_try_timeout not working

### ISSUE THREAD

**Issue by tymcpherson** [Azure/azure-storage-azcopy#1484]
### Which version of the AzCopy was used? 
10.10.0 / 10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy copy "file" "SASURI"

### What problem was encountered?
variable azcopy_request_try_timeout was established using
set azcopy_request_try_timeout=3

Once it eventually times out this is the summary info

Elapsed Time (Minutes): 16.1385
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed

### How can we reproduce the problem in the simplest way?
Perform the following commands

1. set azcopy_request_try_timeout=3
2. azcopy copy "file" "SASURI"

### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment]
Hey @tymcpherson ,

The environment variables are case-sensitive. Can you please try `AZCOPY_REQUEST_TRY_TIMEOUT` instead of lower-case.
To validate the value of environment variable, check [this out](https://golangcode.com/get-and-set-environment-variables/) to see if you're able to get/set the value.

Please reach out if this issue persists.

**Comment by tymcpherson** [comment]
@mohsha-msft - I used **set AZCOPY_REQUEST_TRY_TIMEOUT=3**.  It's also reflected when executing **azcopy env**.  However, the behavior remained the same.
![image](https://user-images.githubusercontent.com/39322129/124213476-a31a8e00-dabe-11eb-9f48-05c967f82ccb.png)
![image](https://user-images.githubusercontent.com/39322129/124213578-d826e080-dabe-11eb-88e1-7a5962d8e535.png)

**Comment by tbutler-qontigo** [comment]
Can this issue be reopened?  We see exactly the same thing - the variable is not being respected if the transfer is taking too long.
Perhaps it is only considered in initiating the request and not once it is in progress?
