### ISSUE TITLE
Azcopy from Blob to Azurite

### ISSUE THREAD

**Issue by ikivanc** [Azure/azure-storage-azcopy#1486]
### Which version of the AzCopy was used? 
10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?

azcopy copy 'https://storage.blob.core.windows.net/test/input.parquet?<SAS_TOKEN>' 'http://azurite:10000/devstoreaccount1/output.parquet' 

and

azcopy copy 'https://storage.blob.core.windows.net/test/input.parquet?<SAS_TOKEN>' 'http://127.0.0.1:10000/devstoreaccount1/output.parquet' 

### What problem was encountered?
I would like to copy a file in available in blob storage to my azurite. What is the best way to copy this?

**Comment by mohsha-msft** [comment]
Hey @ikivanc ,

Please use `--from-to=BlobBlob` flag to specify the direction of upload.

**Comment by mohsha-msft** [comment]
If the issue still persists, please don't hesitate to reach out
