### ISSUE TITLE
Server-side copying between storage accounts is not working

### ISSUE THREAD

**Issue by saihv** [Azure/azure-storage-azcopy#1489]
### Which version of the AzCopy was used? 
AzCopy 10.11.0

### Which platform are you using? 
Linux, Windows

### What command did you run?

`./azcopy copy 'https://<sourceaccount>.blob.core.windows.net/<srccontainer>?<SAS>' 'https://<destaccount>.blob.core.windows.net/<destcontainer>/directory' --recursive`

I already have access to the destination storage account through Azure AD authentication.

### What problem was encountered?

This command is consuming network bandwidth to download data locally, and is slower than expected. Whereas the documentation for similar commands says this should be a server-to-server process.

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs-copy

Am I doing something wrong?

**Comment by mohsha-msft** [comment]
Hey @saihv ,

Thanks for reaching out!

Understand that for a service to service copy, AzCopy traverses the source to figure out what needs to be transferred and performs a `GetProperty()` call on each blob to transfer. This could account for the consumed bandwidth you mentioned.

I'm quite sure that's the case but If you still think something's not right, share with me the AzCopy log file to investigate further.
