### ISSUE TITLE
azcopy between azure file shares

### ISSUE THREAD

**Issue by geremy42** [Azure/azure-storage-azcopy#1491]
### Which version of the AzCopy was used? 
10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`.\azcopy.exe copy "https://mystaaccountsource.file.core.windows.net/sharebackup/myfile?<SAS-TOKEN>" "https://mystaaccountdest.file.core.windows.net/sharerestore?<SAS-TOKEN>" `

### What problem was encountered?
```
INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5
/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=CannotVerifyCopySource) =====
Description=This request is not authorized to perform this operation.
RequestId:229c4679-e01a-0068-3c0e-74834d000000
Time:2021-07-08T15:36:14.8265566Z, Details:
   Code: CannotVerifyCopySource
   PUT https://mystaaccountdest.file.core.windows.net/sharerestore/myfile?comp=range&se=2051-07-08t22%3A54%3A08z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-07-08t14%3A54%3A08z&sv=2020-08-04&timeout=901
   Content-Length: [0]
   User-Agent: [AzCopy/10.11.0 Azure-Storage/0.8.0 (go1.15; Windows_NT)]
   X-Ms-Client-Request-Id: [6f963518-e5a8-43b5-6d1d-8c9d112bfb9c]
   X-Ms-Copy-Source: [https://mystaaccountsource.file.core.windows.net/sharebackup/myfile?se=2051-07-08t22%3A52%3A12z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-07-08t14%3A52%3A12z&sv=2020-08-04]
   X-Ms-Range: [bytes=0-21]
   X-Ms-Source-Range: [bytes=0-21]
   X-Ms-Version: [2020-02-10]
   X-Ms-Write: [update]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [248]
   Content-Type: [application/xml]
   Date: [Thu, 08 Jul 2021 15:36:14 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [6f963518-e5a8-43b5-6d1d-8c9d112bfb9c]
   X-Ms-Error-Code: [CannotVerifyCopySource]
   X-Ms-Request-Id: [229c4679-e01a-0068-3c0e-74834d000000]
   X-Ms-Version: [2020-02-10]
```

IP of server from which azcopy command is run is allowed in firewall rules of both storage accounts.
Those storage accounts (Premium FileStorage) are not on same subscription and so not on the same network

### How can we reproduce the problem in the simplest way?
Copying data from an Azure Premium Fileshare to another one

### Have you found a mitigation/solution?
Allow all networks in firewall rules of both storage accounts (not a solution obviously)

**Comment by zezha-msft** [comment]
Hi @geremy42, thanks for reaching out!

That is a service setting issue and we unfortunately do not have the expertise to help you here. 

Please refer to this [documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?toc=%2Fazure%2Fstorage%2Ffiles%2Ftoc.json&tabs=azure-portal), and if you still have trouble, please reach out to Azure Support.
