### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by antmar904** [Azure/azure-storage-azcopy#1497]
### Which version of the AzCopy was used? 
10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
copy

### What problem was encountered?
high memory utilization
 
### How can we reproduce the problem in the simplest way?
copy a 18gb file from local disk to azure blob

### Have you found a mitigation/solution?
no

Hi.
I use azcopy to copy large files from remote workstations and/or servers to azure and it takes up a lot of ram.  Is there any syntax available to specify how much percentage of ram to use when uploading?

**Comment by zezha-msft** [comment]
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize?toc=/azure/storage/blobs/toc.json#optimize-memory-use
