### ISSUE TITLE
New version available Info message doesn't state current version.

### ISSUE THREAD

**Issue by peterdrier** [Azure/azure-storage-azcopy#1502]
I don't know enough GO to change this myself, but this seems to be the line in question:

https://github.com/Azure/azure-storage-azcopy/blob/87cba068b4cb797fb822163905cf6e92a4ec4db4/cmd/root.go#L253

Background:  Trying to debug a problem with AzureFileCopy@4 Task on Devops.  log is littered with messages stating a newer version is available, but there's no mention of the current version, so I'm left to guess if the problem we're having has been fixed in a newer version of azcopy.exe which the AzureFileCopy task needs to incorporate, or if it's a new problem.  

### Which version of the AzCopy was used?  
Unknown - this is the problem.

### Which platform are you using? (ex: Windows, Mac, Linux)
Azure DevOps - AzureFileCopy@4 task

### What problem was encountered?
azcopy provides a message stating a new version is available, but that message doesn't indicate the current version.  e.g. :

INFO: AzCopy.exe: A newer version 10.11.0 is available to download

### How can we reproduce the problem in the simplest way?
Run any old version of azcopy.exe I'd presume, and check the relevant log.

### Have you found a mitigation/solution?
no.

Ideally from my perspective, this INFO message would be improved to state the current version, and possibly a link to the release notes.  Something like: 

INFO: AzCopy.exe: A newer version 10.11.0 is available to download, currently 10.9.2, release notes: https://github.com/Azure/azure-storage-azcopy/releases

**Comment by gapra-msft** [comment]
Hi @peterdrier this has been fixed in a release from AzCopy. I will go ahead and close this issue. Thanks for the request!
