### ISSUE TITLE
azcopy sync : Last modified timestamp doesn't get synced

### ISSUE THREAD

**Issue by sukumarpatel** [Azure/azure-storage-azcopy#1512]
### Which version of the AzCopy was used? 
10.11.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy sync 'https://testaccount1.blob.core.windows.net/data?sv=********' 'https://testaccount2.blob.core.windows.net/data?sv=********'  --recursive

### What problem was encountered?
The last modified timestamp on the target storage account is different from the source storage account. The last modified is set to the time when azcopy was run.

### How can we reproduce the problem in the simplest way?
1. Create two storage accounts
2. Add some files to account 1
3. Run azcopy sync
4. Observe the last modified time in the target account.

### Have you found a mitigation/solution?
No.

**Comment by siminsavani-msft** [comment]
Hi @sukumarpatel ! AzCopy performs a one-way sync so the last modified time on the target account would be the current time. Here's the wiki for AzCopy sync: https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync. Please let me know if you have any questions!
