### ISSUE TITLE
AzCopy does not return VersionId

### ISSUE THREAD

**Issue by sayandaw** [Azure/azure-storage-azcopy#1513]
##### Note: The version is visible when running AzCopy without any argument
10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
**AzCopy does not return VersionId**
I checked with "LastModifiedTime" that works ok

PS P:\> .\azcopy list https://xyz.blob.core.windows.net/scripts2?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2021-09-07T17:37:30Z&st=2021-08-05T09:37:30Z&spr=https&sig=QWERTYUIO!@#$%^& **--properties LastModifiedTime**
INFO: File1.ps1; _LastModifiedTime: 2021-08-10 04:58:32 +0000 GMT_;  Content Length: 827.00 B

PS P:\> .\azcopy list https://xyz.blob.core.windows.net/scripts2?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2021-09-07T17:37:30Z&st=2021-08-05T09:37:30Z&spr=https&sig=QWERTYUIO!@#$%^& **--properties VersionId**
INFO: File1.ps1; _VersionId:_ ;  Content Length: 827.00 B

### What problem was encountered?
**AzCopy does not return VersionId**

### How can we reproduce the problem in the simplest way?
run azcopy list **--properties VersionId**

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
The issue has been addressed in the latest versions.
