### ISSUE TITLE
Job finishes with "CompletedWithErrors". How to retry the failed transfers?

### ISSUE THREAD

**Issue by aravindyeduvaka** [Azure/azure-storage-azcopy#1515]
### Which version of the AzCopy was used? 
10.11

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy cp $SRC_SAS $LOCAL_DIR  --check-md5 FailIfDifferentOrMissing --recursive

### What problem was encountered?
The job which involves copying around 50k-60k small size files, occasionally corrupts some of the files. So the job ends with "CompletedWithErrors" status. This leaves a few files (around 10-20) corrupted. However, it seems that there is no easy way to retry these 10 failed transfers. 

### Have you found a mitigation/solution?
No. Manually deleting these files and recopying does work but it is very tedious. We want to automate this process. So what's easiest way to retry these failed transfers, especially since you can't retry a "CompletedWithErrors" job.

**Comment by mohsha-msft** [comment]
Hey @aravindyeduvaka , 

Thanks for reaching out!
By default, we retry a failed transfer 20 times. 
- You can use `azcopy sync` to transfer incremental changes which you may have.  AzCopy sync enumerates the source and destination. It then deduce what needs to be transferred based on last-modified-time of the files.
- You can also use `azcopy resume job` command to retry a job too.

**Comment by aravindyeduvaka** [comment]
Its not that the job failed. As I pointed out above, the job fails with "CompletedWithErrors" so its not possible to resume this job.

The copy does succeed, however the MD5 validation fails (so the content is corrupted), so we need to re-write these files with uncorrupted version

**Comment by mohsha-msft** [comment]
Hey @OliverRC, 

Would you mind telling me what error you're getting?
Also, will you share AzCopy logs so I can assist you better. The error must be non-retriable, that's why the transfers failed.

**Comment by mohsha-msft** [comment]
> Hey @aravindyeduvaka Aravind Yeduvaka FTE ,
> 
> Thanks for reaching out! By default, we retry a failed transfer 20 times.
> 
> * You can use `azcopy sync` to transfer incremental changes which you may have.  AzCopy sync enumerates the source and destination. It then deduce what needs to be transferred based on last-modified-time of the files.
> * You can also use `azcopy resume job` command to retry a job too.

As for retrying the failed ones, I pointed out what you can do to transfer the failed files.
