### ISSUE TITLE
Support for copying from Azure Blob to S3 storage

### ISSUE THREAD

**Issue by WaiLoonTan** [Azure/azure-storage-azcopy#1522]
##### Note: The version is visible when running AzCopy without any argument
10.11.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What problem was encountered?
I read this utility can be used to copy from S3 to Azure blob, can it be the other way around ? Meaning from Azure Blob to S3 storage ? If yes, how can we do it ?
### How can we reproduce the problem in the simplest way?
From the guide in https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-s3 :
azcopy copy 'https://s3.amazonaws.com/mybucket' 'https://mystorageaccount.blob.core.windows.net/mycontainer' --recursive=true,

So we just reverse it : 

azcopy copy 'https://mystorageaccount.blob.core.windows.net/mycontainer' 'https://s3.amazonaws.com/mybucket'  --recursive=true,

From azure blob to S3 storage.

**Comment by nakulkar-msft** [comment]
Hi @WaiLoonTan, we have already logged this for development. This has not yet been prioritized. We'll keep you posted. For now, I'll be closing this issue.
