### ISSUE TITLE
Exclude doesn't work for subfolders

### ISSUE THREAD

**Issue by pablospe** [Azure/azure-storage-azcopy#1523]
### Which version of the AzCopy was used? 
azcopy version 10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?

azcopy cp <REMOTE_PATH> <LOCAL_PATH> --overwrite=ifSourceNewer --check-md5 FailIfDifferent --from-to=BlobLocal --recursive --log-level=INFO --exclude-pattern="*/*bla*"

### What problem was encountered?

<REMOTE_PATH>/a/bla
<REMOTE_PATH>/b/bla
<REMOTE_PATH>/bla

Exclude pattern or path doesn't work for subfolders, for example, `a/bla` and `b/bla` are still downloaded.

### Have you found a mitigation/solution?

No.

**Comment by zezha-msft** [comment]
Hi @pablospe, thanks for reaching out!

We are going to release 10.12 soon which will have include/exclude regex support, the flags will apply to the whole path.

The work is being tracked [here](https://github.com/Azure/azure-storage-azcopy/issues/1281).
