### ISSUE TITLE
Feature Request: Microsoft Linux Repo Package (apt, etc)

### ISSUE THREAD

**Issue by AdamCoulterOz** [Azure/azure-storage-azcopy#1524]
Can we get native Linux repo packages for this?

Microsoft already has a native Linux package repository, but I can't find azcopy anywhere listed there:

https://packages.microsoft.com/

**Comment by zezha-msft** [comment]
Thanks for the suggestion @AdamCoulterOz!

We are tracking this work [here](https://github.com/Azure/azure-storage-azcopy/issues/900).
