### ISSUE TITLE
"Disk may be limiting speed" showed while uploading files from NAS to Azure blob storage using AzCopy

### ISSUE THREAD

**Issue by abby984003004** [Azure/azure-storage-azcopy#1526]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

./azcopy sync <Nas path>   "https://XXXX.blob.core.windows.net/testingupload?<SAS>"  --recursive  --delete-destination=true

### What problem was encountered?

Message "Disk may be limiting speed" showed while uploading files from NAS to Azure blob storage using AzCopy

I ran Azcopy on my on-prem VM with NAS attached, the throughput was around 600-800 Mb/s. The speed is quite fast, but the message showed up constantly. 

1. Does this message specify there is a bottleneck of the reading speed from NAS to local VM? Does the disk mean local disk or NAS disk?
2. I would like to optimize the memory use, what value of AZCOPY_BUFFER_GB I can start with?

**Comment by zezha-msft** [comment]
Hi @abby984003004, "Disk may be limiting speed" means that the tool is idling waiting for data to be read from the source. In other words, network/outbound speed > source speed in your case.

Your NAS is mounted on your client machine, the data needs to be read from your NAS and uploaded from the client machine via AzCopy. So "Disk may be limiting speed" applies to the combination of NAS disk + your internal network.

As for memory use, I would suggest to only tune it if you think the usage is too much. We infer a default usage (0.5GB per logical core, max of 16GB) based on how powerful your machine is.

**Comment by abby984003004** [comment]
Thank you @zezha-msft for the explanation. Will you suggest me to test the speed from NAS to VM and also monitor the CPU/memory/network usage on NAS when the message shows up again?

**Comment by apolloxm** [comment]
> Hi @abby984003004, "Disk may be limiting speed" means that the tool is idling waiting for data to be read from the source. In other words, network/outbound speed > source speed in your case.
> 
> Your NAS is mounted on your client machine, the data needs to be read from your NAS and uploaded from the client machine via AzCopy. So "Disk may be limiting speed" applies to the combination of NAS disk + your internal network.
> 
> As for memory use, I would suggest to only tune it if you think the usage is too much. We infer a default usage (0.5GB per logical core, max of 16GB) based on how powerful your machine is.

If we are using the two AZcopy command at the same time,Is that means we need double CPU/Memory/Network resource?
per my testing, If I run one AZcopy then the speed would be 200 MB/s, If I run two AZcopy then speed would be 260 MB/s. 
Is Microsoft suggest user to run  two AZCopy or just One AZCopy?Thanks

**Comment by abby984003004** [comment]
@zezha-msft Could you reopen the case since we still have some performance tuning questions? Thank you so much
