### ISSUE TITLE
azcopy crashes with: runtime/cgo: pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by bendavis78** [Azure/azure-storage-azcopy#1527]
### Which version of the AzCopy was used? 
10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
```
azcopy copy 'https://REDACTED.file.core.windows.net/REDACTED/*?se=2021-08-26T00%3A00Z&sp=rwl&spr=https&sv=2018-11-09&sr=s&sig=REDACTED' /tmp/download --recursive
```

### What problem was encountered?
Crashes with `runtime/cgo: pthread_create failed: Resource temporarily unavailable`

- [see here for full output from command](https://gist.github.com/bendavis78/9253f2367818e16d76e7be0a1c0e23f1)
- [see here for logfile created by azcopy](https://gist.github.com/bendavis78/643db601d4d295cf8e9c6f761ddefaec)

### How can we reproduce the problem in the simplest way?
This problem occurs when spawned from inside a Python script using `subprocess.Popen` (basically a forked process):
```python
cmd = ('azcopy', 'copy', url, temp_dir, '--recursive')
proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False)
(stdout, stderr) = proc.communicate()
```
The Python process is running under `uwsgi` in emperor mode. Not sure if that has anything to with it, but it's the only way I can reproduce.

**Comment by bendavis78** [comment]
For anyone else that comes across this issue, I was able to work around this by rebuilding azcopy with `CGO_ENABLED=0`:
```sh
$ env CGO_ENABLED=0 go build -buildmode=pie
```

**Comment by mohsha-msft** [comment]
Hey @bendavis78 ,

Thanks for reaching out!

Can you try to reproduce this issue by running it without Python script? 
If yes, it may not be the fault of AzCopy. 

C libraries for GO aka CGO is enabled by default for native builds on systems where it is expected to work. 
CGO can bring more compilation complications, less portability and cross compilation issues so I'll discuss this with my team on whether we should enable/disable this by default.  It is convenient so it is enabled by default. Thanks for bringing that up.

**Comment by mohsha-msft** [comment]
Hey @bendavis78 ,

Can you also share RAM/process snapshots at the time you're reproducing the crash through Python process.  

The error about `pthread_create failed: Resource temporarily unavailable` normally means that you are trying to create too many threads and not closing the older ones. This is associated with too much memory consumption. 

I tried looking for the solution on internet and found that disabling CGO should work.

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/263
