### ISSUE TITLE
panic: runtime error: slice bounds out of range [Need better error message for unsupported List scenario]

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-storage-azcopy#153]
### Which version of the AzCopy was used? 
```
$  azcopy --version
azcopy version 10.0.4-Preview
```
### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu 16.04.5 LTS

### What command did you run?
```
$  azcopy list https://mystorageaccount.blob.core.windows.net
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/cmd.copyHandlerUtil.urlIsContainerOrShare(0xc4206a0100, 0xd42be0)
        /go/src/github.com/Azure/azure-storage-azcopy/cmd/copyUtil.go:69 +0x1d7
github.com/Azure/azure-storage-azcopy/cmd.getBlobCredentialType(0xa2cb60, 0xc42001e2d0, 0x7ffc215ae778, 0x2f, 0x8f0001, 0xa25210, 0xa2cb60, 0xc42001e2d0)
        /go/src/github.com/Azure/azure-storage-azcopy/cmd/credentialUtil.go:103 +0x21b
github.com/Azure/azure-storage-azcopy/cmd.HandleListContainerCommand(0x7ffc215ae778, 0x2f, 0x1, 0x0, 0x0)
        /go/src/github.com/Azure/azure-storage-azcopy/cmd/list.go:89 +0xe9
github.com/Azure/azure-storage-azcopy/cmd.init.7.func2(0xc4200ed400, 0xc4200727a0, 0x1, 0x1)
        /go/src/github.com/Azure/azure-storage-azcopy/cmd/list.go:69 +0xb3
github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200ed400, 0xc420072760, 0x1, 0x1, 0xc4200ed400, 0xc420072760)
        /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xd1ff40, 0xd, 0x56, 0x18)
        /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra.(*Command).Execute(0xd1ff40, 0x11, 0xd)
        /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc4200be2c0, 0x11, 0xc4200be2c0, 0x11)
        /go/src/github.com/Azure/azure-storage-azcopy/cmd/root.go:71 +0x7d
main.main()
        /go/src/github.com/Azure/azure-storage-azcopy/main.go:55 +0x1c8
```

### Have you found a mitigation/solution?
The following does not return any errors but  does not list any object either:
```
$  azcopy list https://mystorageaccount.blob.core.windows.net/
List is using OAuth token for authentication.
```

**Comment by zezha-msft** [comment]
Hi @johanburati, thanks for reaching out!

As the help doc(`./azcopy list --help`) mentions, only blob containers are supported at the moment. We will improve this command in the future, thanks for your feedback!

**Comment by zezha-msft** [comment]
The error message should definitely be improved.

**Comment by ppakawatk** [comment]
> Hi @johanburati, thanks for reaching out!
> 
> As the help doc(`./azcopy list --help`) mentions, only blob containers are supported at the moment. We will improve this command in the future, thanks for your feedback!
> 
> --Edit--
> To clarify, only listing blobs inside a container is supported at the moment.

Hi. Is it able to list the containers by now?

**Comment by JohnRusk** [comment]
Do you mean give it an account, and it gives you a list of containers? No.  You'll need to use powershell or `az cli` for that. (Or call the [REST API directly,](https://docs.microsoft.com/en-us/rest/api/storageservices/list-containers2) which is "easy" enough with SAS auth, but not so easy with other authorization forms).

**Comment by ppakawatk** [comment]
> Do you mean give it an account, and it gives you a list of containers? No. You'll need to use powershell or `az cli` for that. (Or call the [REST API directly,](https://docs.microsoft.com/en-us/rest/api/storageservices/list-containers2) which is "easy" enough with SAS auth, but not so easy with other authorization forms).

I meant giving a list of containers. Thank you for your answer, sir.

**Comment by JohnRusk** [comment]
Giving `azcopy list` a list of containers is not supported. Sorry.

**Comment by zezha-msft** [comment]
This is fixed. We now support listing all blobs under all containers if an account URL is given.
