### ISSUE TITLE
10.12 is deleting all destination files during a sync then downloading them again

### ISSUE THREAD

**Issue by alecdombrowski** [Azure/azure-storage-azcopy#1539]
##### Note: The version is visible when running AzCopy without any argument
10.12

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 2004 and up

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
AZcopy.exe sync <blob sas key> <destination> --delete-destination=true

### What problem was encountered?
Running "AZcopy.exe sync <blob sas key> <destination> --delete-destination=true" will sync all files from the blob, but then on following sync will delete all files. Each subsequent sync will download all files, then delete all files, over and over again.

### How can we reproduce the problem in the simplest way?
Use AZcopy 10.12 and sync files from a blob using the above command, repeat command and the files should show up and delete.

### Have you found a mitigation/solution?
Replace 10.12 version with 10.11, works after that without issues.

**Comment by Disordely** [comment]
We are also seeing this exact issue with 10.12.1

**Comment by mpartes** [comment]
Same issues here with latest version. Can this be assigned as seems to be a bug that will affect all using that command?

**Comment by alecdombrowski** [comment]
I posted this 8 days ago and there is still no response from developers. This is a pretty big issue, it's deleting all files from a sync. I would expect some more visibility on this.

**Comment by mohsha-msft** [comment]
Hey @alecdombrowski ,

Thanks for reaching out.
Let me reproduce this issue. In the meantime, can you use AzCopy version `10.11.0`.

**Comment by mohsha-msft** [comment]
Here's the [link](https://azcopyvnextrelease.blob.core.windows.net/release20210616/drop.zip) to ``10.11`

**Comment by alecdombrowski** [comment]
Thanks for the response, will this link for 10.11 stay live for the foreseeable future? If I deploy this link out for my Windows clients to download 10.11 will they continue to be able to access this version for months or years from now?

**Comment by mohsha-msft** [comment]
This is a permanent link which you can use :)

**Comment by adreed-msft** [comment]
Obtaining a repro. Will mark as a regression if I can obtain it.

**Comment by adreed-msft** [comment]
I am unable to reproduce on 10.12.1. I'll try going back to 10.12 and see if I can get a repro there.

**Comment by adreed-msft** [comment]
No repro on 10.12... Could you provide more details about your scenario? --delete-destination will delete files that *aren't* present at the source, FYI.

**Comment by alecdombrowski** [comment]
For my scenario, I will run AZCopy (AZcopy.exe sync "blob SAS" "Destination folder" --delete-destination=true) to sync all files from a blob to windows clients. AZcopy runs from a scheduled task every few hours or so. (I get the same result if I run AZCopy manually as well). On the first time AZCopy runs with 10.12, it will download and sync all files from the blob, as is desired and works well. On the next AZcopy, using the same exact command, all of the files that had previously synced down will delete. The AZCopy log file will state that it doesn't see any of the files at the destination existing in the blob.

I apologize, I don't have any of the log files anymore. I can likely reproduce the issue again later today if needed so I can maybe grab one.

**Comment by Disordely** [comment]
We have the exact same issue with this release. On one sync it deletes all files, on the next it populates the files, and bing-bong it repeats that cycle every time you sync. Reproduced with 10.11 and below and it only happens on 10.12 and above.

**Comment by Disordely** [comment]
we can share log files if it helps, but in the case of 10.12+ it basically says X files scanned at source / X files scanned at dest (matching number) and then proceeds to delete all on one sync but not on the next. It's like it's confusing src and dst

**Comment by adreed-msft** [comment]
Ah, blob to local. I was trying blob to blob. I'll try to repro that. Logs would be helpful, yes.

**Comment by siminsavani-msft** [comment]
Hi @alecdombrowski , @Disordely , @mpartes ! We have made a new release [10.12.2 ](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.12.2) that fixes this issue. Please let us know if you may have any questions!
