### ISSUE TITLE
AzCopy remove fails on empty/non-existing directory

### ISSUE THREAD

**Issue by EvertEt** [Azure/azure-storage-azcopy#1540]
##### Note: The version is visible when running AzCopy without any argument
10.3.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Mac
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy rm unexisting_path --recursive=true

### What problem was encountered?
AzCopy errored. We wish to be able to control if it errors for an empty/non-existing directory on removal. 

### How can we reproduce the problem in the simplest way?
Remove an unexisting folder

### Have you found a mitigation/solution?
Currently we are parsing the stdout from azcopy

**Comment by adreed-msft** [comment]
Sounds like the remove if not exist features we have in our SDKs.

**Comment by mohsha-msft** [comment]
`CreateIfNotExists` and `RemoveIfExists` APIs are not part of track1.5. Though we've included them in track2. Do you think we should add them in track1.5 as well @adreed-msft ?

**Comment by EvertEt** [comment]
This seems fixed in the latest version, correct?

**Comment by gapra-msft** [comment]
Hi @EverEt, Thanks for the feature request. Could you please clarify if the latest version of AzCopy satisfies your request so we can go ahead and close this issue?

**Comment by EvertEt** [comment]
I do not have access to our AzCopy setup anymore so I cannot verify sadly. Will close anyway
