### ISSUE TITLE
Untar .tar files after decompressing

### ISSUE THREAD

**Issue by gvilar** [Azure/azure-storage-azcopy#1544]
Hello,

When I use decompress option on a tar.gz file and content-encoding setted to gzip azcopy download file and delete gz extension only  (not uncompress and delete gz - not tar.gz) . 
The copy delete the gz extension only and don't uncompress the file.  

Any way to download and uncompress a tar.gz file with azcopy ? 

Azcopy Version: 
azcopy version 10.12.1 on Linux

Command used:

azcopy copy https://blob_url/archive.tar.gz --decompress destination/

Result : 

destination/archive.tar

**Comment by adreed-msft** [comment]
You're right; it decompressed the file, but it did not untar it. I'll mark this a feature request.

**Comment by digital2real** [comment]
Tar extract to destination would be greet!

Support of tar extract from stdin (pipe) would be a killer feature for me.

My use case for backup restore with borg could be :

borg export-tar /path/to/repo::Monday - | azcopy copy --tar-extract "https://[account].blob.core.windows.net/[container]/[path/to/blob]" --from-to PipeBlob

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
