### ISSUE TITLE
100% percentage always reported for sync command

### ISSUE THREAD

**Issue by zmechanic** [Azure/azure-storage-azcopy#1545]
##### Note: The version is visible when running AzCopy without any argument
10.12.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy sync \\path\path$\cmo_cdu https://storage.file.core.windows.net/share/path/cmo_cdu?[SAS] --recursive --exclude-path=SAFE_TO_DELETE 
### What problem was encountered?
always reports 100% percentage:

INFO: Reducing progress output frequency to 2m0s, because there are over 1000000 files
100.0 %, 1504 Done, 0 Failed, 4399091 Pending, 4400595 Total, 2-sec Throughput (Mb/s): 59.6609 (Disk may be limiting spe
100.0 %, 2929 Done, 0 Failed, 4397666 Pending, 4400595 Total, 2-sec Throughput (Mb/s): 65.0982 (Disk may be limiting spe
100.0 %, 4422 Done, 0 Failed, 4396173 Pending, 4400595 Total, 2-sec Throughput (Mb/s): 55.1317 (Disk may be limiting spe
100.0 %, 5792 Done, 0 Failed, 4394803 Pending, 4400595 Total, 2-sec Throughput (Mb/s): 60.8757 (Disk may be limiting spe

### Have you found a mitigation/solution?
none

**Comment by siminsavani-msft** [comment]
Hi there, I've tried to repro this and the sync percentage seems to work fine in the latest AzCopy version. Please give it a try and let us know if the issue still persists!
