### ISSUE TITLE
Azcopy list on subfolder

### ISSUE THREAD

**Issue by brentmjohnson** [Azure/azure-storage-azcopy#1546]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.12.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
./azcopy list https://{STORAGE ACCOUNT}.blob.core.windows.net/{BLOB CONTAINER}/{SUBFOLDER}/
Note: executed using AAD OAUTH authentication

### What problem was encountered?
Command returns blobs from all subfolders

### How can we reproduce the problem in the simplest way?
Execute the above command on a blob container with subfolders

### Have you found a mitigation/solution?
List everything in the container then filter client-side but this is very time consuming for containers with a lot of subfolders

This appears to have been addressed previously in #583? Maybe there was a reversion.

**Comment by adreed-msft** [comment]
To be clear; you want a --recursive=false option for list?

**Comment by brentmjohnson** [comment]
> To be clear; you want a --recursive=false option for list?

This was actually a bug report because it didn't seem like #583 was working anymore, but it looks like I was wrong.  

My issue in this case had to do with the container name: **$web**  AzCopy doesn't seem to be URL encoding the remote source / destination args.  As soon as I replaced $web with %24web the list command did exactly what I expected - list all blobs under the specified subfolder path recursively.

The URL encoding handling of "$" in remote source / destination args may be a separate issue.  For reference, the generated SAS token URL for the $web container does not URL encode the "$"

**Comment by marc-hb** [comment]
> To be clear; you want a --recursive=false option for list?

I don't know about @brentmjohnson but I certainly do, otherwise the `list` command becomes totally unusable for top level folders. Is there already a request filed about this? I didn't find it yet.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
