### ISSUE TITLE
Publish binaries in GitHub releases

### ISSUE THREAD

**Issue by aelij** [Azure/azure-storage-azcopy#1549]
Currently azcopy binaries are pushed to a CDN (azcopyvnext), which makes it harder to automate updates.
So please additionally publish the binaries in GitHub releases. GitHub has an API that allows querying the latest release and fetch the files.
Another option is to remove the `/release<date>/` part in the CDN URI so the download URI could be inferred from GitHub release name.

**Comment by mohsha-msft** [comment]
Hey @aelij,

Thanks for your recommendation. Let me get back to you once I discuss this idea with my team-mates.

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/1190

**Comment by aelij** [comment]
Thanks @mohsha-msft
Duplicate of #1190
