### ISSUE TITLE
'azcopy remove --recursive' does not remove the container

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-storage-azcopy#155]
'azcopy remove --recursive' does not remove the container

### Which version of the AzCopy was used? 
```
$  azcopy --version
azcopy version 10.0.4-Preview
```
### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu 16.04.5 LTS

### What command did you run?
```
$  azcopy list https://mystorageaccount.blob.core.windows.net/bootdiagnostics-aad-f3af6b83-9ff2-476a-8fd5-269f38f44884
List is using OAuth token for authentication.
aad.f3af6b83-9ff2-476a-8fd5-269f38f44884.screenshot.bmp
aad.f3af6b83-9ff2-476a-8fd5-269f38f44884.serialconsole.log
$  azcopy remove https://mystorageaccount.blob.core.windows.net/bootdiagnostics-aad-f3af6b83-9ff2-476a-8fd5-269f38f44884 --recursive
Using OAuth token for authentication.

Job e7c4f345-e2fb-004f-66c1-9332e62b37fe has started

Log file is located at: /home/job/.azcopy/e7c4f345-e2fb-004f-66c1-9332e62b37fe.log
0 Done, 0 Failed, 2 Pending, 0 Skipped, 2 Total


Job e7c4f345-e2fb-004f-66c1-9332e62b37fe summary
Elapsed Time (Minutes): 0.0667
Total Number Of Transfers: 2
Number of Transfers Completed: 2
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 617472
Final Job Status: Completed

$  azcopy list https://mystorageaccount.blob.core.windows.net/bootdiagnostics-aad-f3af6b83-9ff2-476a-8fd5-269f38f44884
List is using OAuth token for authentication.
```

### What problem was encountered?

I expect the container to be removed as well, the blobs are removed but the container itself remains.

### Have you found a mitigation/solution?

Delete the container from the portal.

**Comment by zezha-msft** [comment]
Hi @johanburati, thanks for the feedback!

@seguler should we delete the container in this case?

**Comment by nusairi** [comment]
Hi Any update on this

**Comment by nakulkar-msft** [comment]
Please use azcopy rm <container-name> to remove container

**Comment by syedhamjath** [comment]
@nakulkar-msft I have a different case, I don't want to remove the container. I want to remove only the content recursively so I use below command. This removes the container, how can we prevent it from removing container?

`azcopy remove "https://$($target_storageAccount).dfs.core.windows.net/$($_.Name)/*" --recursive=true`
