### ISSUE TITLE
AzCopy Sync does not update a file with an immutable policy

### ISSUE THREAD

**Issue by DiouxX** [Azure/azure-storage-azcopy#1550]
##### Note: The version is visible when running AzCopy without any argument

10.12.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

```powershell
azcopy sync "https://{storageaccount1}.blob.core.windows.net/source?sastoken" "https://{storageaccount2}.blob.core.windows.net/destination?sastoken" --recursive=true --delete-destination=true
```

### What problem was encountered?

The file updated on source container is not updated on destination container when the immutable policy on destination container is expired for this file
The source and destination container are in different storage accounts

Here is the error that is logged in the logfile

```
2021/09/13 08:46:38 ERR: [P#0-T#0] COPYFAILED: https://{storageaccount}.blob.core.windows.net/source/a.txt?sastoken : 409 : 409 This operation is not permitted as the blob is immutable due to a policy.. When Put Blob from URL. X-Ms-Request-Id: XXXXX
```

### How can we reproduce the problem in the simplest way?

1. Add a file on source container
2. Launch azcopy sync command to sync the file on destination container -> the file is copied because it's not existing
3. Update the file on source container
4. Launch azcopy sync command to sync the file on destination container -> the updated file is synced
5. Add a Time-based retention with 1 day retention and lock the policy
6. Update the file on source container
7. Wait that retention policy is expired (1 Day) to launch azcopy sync command -> the updated file is not synced

### Have you found a mitigation/solution?

No

**Comment by nakulkar-msft** [comment]
Hi @DiouxX, blobs with immutable policy cannot be overwritten till policy does not expire.
