### ISSUE TITLE
custom path for accessToken.json

### ISSUE THREAD

**Issue by tdanur** [Azure/azure-storage-azcopy#1565]
##### Note: The version is visible when running AzCopy without any argument
10.12.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy login

### What problem was encountered?
We are using azcopy in a multi-tenant IIS based virtual machine. We can have multiple tenants/customers in one virtual machine and they have their own storage repository that we want to sync to their own azure blob storage via a background job running in each tenant's application.

The background job is running on a .net framework web app via the IIS. This background job will run a process to execute azcopy.exe with azcopy commands in it, i.e. login, sync, and jobs clean. We authenticate the login to Azure storage by using a service principal and currently we notice that the accessToken.json file is always generated in a common folder: C:\Windows\System32\config\systemprofile\.azcopy. 

This is not ideal for our implementation since we have multiple tenant/customers. We want to be able to store the accessToken.json in their respective unique/private directory so that multiple sync operations can run among the different customers in the VM. 

I noticed from the documentation and the source code that there is no way to customise where the accessToken.json is stored after login operation, unlike the log and plan files.

Is there a possible workaround for this scenario? or is it possible to add the ability to customise the accessToken.json location in the future release, please?

### How can we reproduce the problem in the simplest way?
execute azcopy login command, and the accessToken.json is stored in user profile folder and cant be customised.

### Have you found a mitigation/solution?
No. Currently i couldnt find a way to make it work for multi-tenant scenario, token file is stored in a global location which will then be conflicting when i run multiple background jobs for multiple tenants.

**Comment by nakulkar-msft** [comment]
Hi @tdanur Have you tried using auto-login? This eliminates need for accessToken, and can be customized using user profile.
https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)

**Comment by tdanur** [comment]
Hi @nakulkar-msft .. thank you for your reply. i was not aware of the auto login functionality before you mentioned it, and thank you for that! i have tried to implement this, and the auto login worked like a charm! it seems like it will be a suitable approach for our multi-tenant setup. thank you, and i am closing this issue :)
