### ISSUE TITLE
Avoiding block size limit

### ISSUE THREAD

**Issue by onny** [Azure/azure-storage-azcopy#157]
### Which version of the AzCopy was used? 
10.0.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
``
 pv -cN source /dev/vg0/storage_snap | gpg --batch --passphrase **** --symmetric --compress-algo zlib | azcopy cp --block-size 8194304 "https://EXAMPLE.blob.core.windows.net/EXAMPLE/storage_$(date +"%Y-%m-%d").img.gpg?sv=****"
``
### What problem was encountered?
After 1,3 hours, I get following error:
```
RESPONSE Status: 400 The block list may not contain more than 50,000 blocks.
```
### How can we reproduce the problem in the simplest way?
Maybe copy a file to Azure with STDIN for about 550-600 gb size.

### Have you found a mitigation/solution?
Not yet

Best regards and thank you for your support,
Jonas

**Comment by zezha-msft** [comment]
Hi @onny, thanks for reaching out!

I see that you've specified `--block-size 8194304`. (500 gigabytes) / (8 194 304 bytes) =
61 017.9949 blocks, which is higher than the 50,000 block limit for block blobs. Is there any reason why you need such a block size?

My suggestion would be to specify a larger block size. Thanks!

**Comment by poseidon0206** [comment]
Hi,

I'm having a similar issue using the 10.0.5-Preview version:

### Which version of the AzCopy was used?
10.0.5-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
`tar cfv - workspace | azcopy copy "https://mystorageaccount.blob.core.windows.net/container/project_name/project_workspace_backup.tar" --log-level=DEBUG --block-size=9000000`

### What problem was encountered?
`RESPONSE Status: 400 The block list may not contain more than 50,000 blocks.`

### How can we reproduce the problem in the simplest way?
The _workspace_ is a directory containing the workspace I'm backing up, it's about 400G+ in size. It seems like azcopy ignores the **--block-size** option when 

### Have you found a mitigation/solution?
Not yet. I am however, able to copy workspaces around 200GB+.

After reading this issue I have tried adjusting the block size from 8000000 to 9000000, and both attempts were fruitless. Please if anyone could help with this issue as I'm pretty much stumped.

**Comment by zezha-msft** [comment]
Hi @poseidon0206, thanks for reaching out! I just verified and there is indeed a bug, where the block size is passed in but not used. I'll fix it right away and try to include it in the release today.

**Comment by zezha-msft** [comment]
This should now be fixed. Please try the [latest version](https://github.com/Azure/azure-storage-azcopy/pull/181/commits/97810179c7f1ed0f4fdf838278cc7751fe404960).

**Comment by poseidon0206** [comment]
Hi @zezha-msft ,

Thanks very much for the prompt response. I have tested uploading a 400GB+ tarball as well as a 600GB+ tarball: both uploaded finished without errors.

Thanks again for the prompt action.

**Comment by zezha-msft** [comment]
@poseidon0206 Awesome! Please don't hesitate if you have any other feedback!

**Comment by onny** [comment]
Now I'm getting a different error message. Running azcopy with ``azcopy --block-size=11000000 cp [...]``:
```
failed to perform copy command due to error: -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewResponseError, /build/azcopy-10/src/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_response_error.go:29                                                                                                     
===== RESPONSE ERROR (ServiceCode=BlockCountExceedsLimit) =====
Description=The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.
RequestId:****
Time:2019-01-27T01:34:56.3953814Z, Details:
   Code: BlockCountExceedsLimit
   PUT https://****.blob.core.windows.net/****/storage_test.img.gpg?blockid=***&comp=block&se=2019-01-29t17%3A26%3A09z&sig=REDACTED&sp=rwdlac&spr=https&srt=sco&ss=b&st=2019-01-26t09%3A26%3A09z&sv=2018-03-28&timeout=601                                                                                        
   Content-Length: [11000000]
   User-Agent: [AzCopy/10.0.6-Preview Azure-Storage/0.4 (go1.11.5; linux)]
   X-Ms-Client-Request-Id: [****]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 409 The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.                                                                                                     
   Content-Length: [269]
   Content-Type: [application/xml]
   Date: [Sun, 27 Jan 2019 01:34:55 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [BlockCountExceedsLimit]
   X-Ms-Request-Id: [****]
   X-Ms-Version: [2018-03-28]
```

**Comment by zezha-msft** [comment]
Hi @onny, how big is your blob? The maximum size for the block size of 11MB is: 11MB*50000(max committed block count) = 550GB.

You may have hit the uncommitted block limit of 100,000 because another tool is targeting the same blob and staged a bunch of blocks but did not commit them. AzCopy always uses the same block IDs so we shouldn't hit this problem on our own, assuming the blob size is under 1.1TB(11MB*100000).
