### ISSUE TITLE
Cannot directory upload a full drive since v10.12.0

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#1571]
### Which version of the AzCopy was used? 
10.12.2, this regresses from 10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
copy (upload)

e.g. copy "E:\" "blob folder url"

### What problem was encountered?
AzCopy scanning log says "Failed to get last change of target at \\?\E:: Access is denied.

### How can we reproduce the problem in the simplest way?
Execute a command to copy a drive to a blob folder.

### Have you found a mitigation/solution?
No.

### Additional context
This is a customer issue reported to Storage Explorer.

**Comment by mohsha-msft** [comment]
Hey @JasonYeMSFT ,

I tried to reproduce the issue and it worked perfectly with me. Can you please share with me the logs so that I can investigate further?
