### ISSUE TITLE
400 error when copying to azurite 

### ISSUE THREAD

**Issue by sordonia** [Azure/azure-storage-azcopy#1572]
### Which version of the AzCopy was used? 

10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

### What command did you run?

azcopy copy amlt.py "http://127.0.0.1:10000/foocontainer/foo" --output-type=json --recursive=false --from-to=LocalBlob --put-md5

(sas hidden)

### What problem was encountered?

{"TimeStamp":"2021-09-28T11:10:43.636145-04:00","MessageType":"EndOfJob","MessageContent":"{\"ErrorMsg\":\"\",\"JobID\":\"4e622a48-33b9-9a4a-65d0-cc39185453de\",\"ActiveConnections\":\"0\",\"CompleteJobOrdered\":true,\"JobStatus\":\"Failed\",\"TotalTransfers\":\"1\",\"FileTransfers\":\"1\",\"FolderPropertyTransfers\":\"0\",\"TransfersCompleted\":\"0\",\"TransfersFailed\":\"1\",\"TransfersSkipped\":\"0\",\"BytesOverWire\":\"9050\",\"TotalBytesTransferred\":\"0\",\"TotalBytesEnumerated\":\"9050\",\"TotalBytesExpected\":\"0\",\"PercentComplete\":\"100\",\"AverageIOPS\":\"0\",\"AverageE2EMilliseconds\":\"3\",\"ServerBusyPercentage\":\"0\",\"NetworkErrorPercentage\":\"0\",\"FailedTransfers\":[{\"Src\":\"/Users/alsordon/Workspace/philly-tools/amlt/amlt.py\",\"Dst\":\"http://127.0.0.1:10000/foocontainer/foo/amlt.py\",\"IsFolderProperties\":false,\"TransferStatus\":\"Failed\",\"ErrorCode\":\"400\"}],\"SkippedTransfers\":null,\"PerfConstraint\":0,\"PerformanceAdvice\":[],\"IsCleanupJob\":false}","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}

**Comment by siminsavani-msft** [comment]
Hi @sordonia ! The 400 error should indicate incorrect syntax. Could you try running --log-level=DEBUG?
