### ISSUE TITLE
AzCopy Sync with --force-if-read-only=true; no workie! :(

### ISSUE THREAD

**Issue by pjfontes** [Azure/azure-storage-azcopy#1578]
##### Note: The version is visible when running AzCopy without any argument
10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 2021

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy sync $source $dest --recursive=true --log-level=Error --preserve-smb-info=True --delete-destination=true **--force-if-read-only=true**

### What problem was encountered?
--force-if-read-only=true argument not supported when using 'sync'.  azcopy fails to overwrite readonly files at the target.

### How can we reproduce the problem in the simplest way?
azcopy sync ..... --force-if-read-only=true

### Have you found a mitigation/solution?
manual file copying.

**Comment by adreed-msft** [comment]
Seems like a flag parity issue between copy and sync.

**Comment by wingfeng** [comment]
is there plan to support "--force-if-read-only" in sync? or any other way to handle the read-only files instead of raise error only.

**Comment by rpalves** [comment]
Hi team!

Is it possible to implement --force-if-read-only=true for file sync?

**Comment by adreed-msft** [comment]
I will look into squeezing this into 10.18.1; it should just be passing a flag to the STE.

**Comment by siminsavani-msft** [comment]
Fixed in 10.19.0!
