### ISSUE TITLE
AzCopy does not support S3 providers besides AWS

### ISSUE THREAD

**Issue by dcdanko-biotia** [Azure/azure-storage-azcopy#1587]
### Which version of the AzCopy was used? 

`azcopy version 10.11.0`

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

### What command did you run?

```
azcopy cp \
    --from-to S3Blob \
    'https://s3.wasabisys.com/sewage-covid-microbiome/pangea/v1/Sewage%20COVID-19%20Microbiome/samples/negative-control-dv2_S74/negative-control-dv2_S74_L001_R1_001.fastq.gz?<signature>' \
    'https://btprtlstagingstorage.blob.core.windows.net:443/personal-container-67?<sas>'
```

### What problem was encountered?

AzCopy does not recognize the Wasabi URL as a valid S3 URL. It gives this error message 

```
panic: Invalid S3 URL. AzCopy supports standard virtual-hosted-style or path-style URLs defined by AWS, E.g: https://bucket.s3.amazonaws.com or https://s3.amazonaws.com/bucket
```

If the `--from-to S3Blob` is omitted AzCopy treats the wasabi URL like a local filepath which does not work either.

### How can we reproduce the problem in the simplest way?

Try to copy a file from Wasabi (or, likely, any non-AWS S3 provider) to azure storage using azcopy

### Have you found a mitigation/solution?

Download the files from wasabi then re-upload

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/1634
