### ISSUE TITLE
Unable to migrate data from AWS S3 bucket to Azure Blob storage

### ISSUE THREAD

**Issue by shaikjahangir04** [Azure/azure-storage-azcopy#1596]
##### Note: The version is visible when running AzCopy without any argument

10.12.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
.\azcopy copy "https://aispl-testing.s3.ap-south-1.amazonaws.com/testing/" "https://datamigrationstracct.blob.core.windows.net/data-migration-container?<SAS>" --recursive=true --s2s-handle-invalid-metadata=RenameIfInvalid

### What problem was encountered?
Skipping S3 object testing/._.TESTT$1112122_____8u.tyYYY20.txt, as it is not a valid Blob name. Rename the object and retry the transfer

**Comment by mohsha-msft** [comment]
Fix released in AzCopy `10.14.0`
