### ISSUE TITLE
AzCopy sync to Container behind Application Gateway - issues

### ISSUE THREAD

**Issue by FairW** [Azure/azure-storage-azcopy#1597]
### Which version of the AzCopy was used? 
10.11.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
./azcopy sync "../to_be_uploaded/" "https://[AppGwPublicIP]/<storage_account_container>?<SAS_token>" --recursive=false --put-md5

### What problem was encountered?
Replacing [AppGwPublicIP] with URL for Storage Account - sync works fine. But when using the Public IP address for the Application Gateway in the URL, things go south. I get the following error message:

*INFO: Cannot infer destination location of https://[AppGwPublicIP]/dataingestion?<SAS_token>. Please specify the --from-to switch. Valid values are two-word phases of the form BlobLocal, LocalBlob etc.  Use the word 'Blob' for Blob Storage, 'Local' for the local file system, 'File' for Azure Files, and 'BlobFS' for ADLS Gen2. If you need a combination that is not supported yet, please log an issue on the AzCopy GitHub issues list.*

*error parsing the input given by the user. Failed with error Unable to infer the source '../to_be_uploaded/' / destination https://[AppGwPublicIP]/dataingestion?<SAS_token>*

**Questions**
1) Regarding the error message above; I'm using the `azcopy sync`. The `--from-to` switch mentioned only applies to the `azcopy copy` according to the doc... The error message seems to be off... If I try to specify `--from-to` in an `azcopy sync` command I get:
`unknown flag: --from-to`

2) Is what I'm trying to do, at all doable/advisable? I.e. to have an Application Gateway in front of the Storage Account when using azcopy to upload files from on prem to a container on the Storage Account? If doable - any code samples to be found?

3) Is there a better way / best pratice? Eventually we will close down public IP access, this was only used as a first test scenario.

**Comment by gapra-msft** [comment]
Hi @FairW and @steinrr are you still hitting this issue in the latest release of AzCopy?

**Comment by steinrr** [comment]
We have not tested latest versions of azcopy, because we got the old setup
to work as required.

**Comment by gapra-msft** [comment]
Perfect, so sounds like your issue has been resolved. Please feel free to re-open a new issue if you encounter anything else!

**Comment by steinrr** [comment]
The ip bug might still be present. We are using domains now, so we don’t
know.

**Comment by gapra-msft** [comment]
@steinrr I see. I was able to manually verify the latest AzCopy version using Azurite as a destination with its IP endpoint style URL and hit no issues, so I think this issue is safe to close for now.

**Comment by steinrr** [comment]
Ok - thanks!
