### ISSUE TITLE
Known issue: potential data corruption for Azure File uploads for version 10.0.4 and prior

### ISSUE THREAD

**Issue by zezha-msft** [Azure/azure-storage-azcopy#160]
Sparse file [optimizations](https://github.com/Azure/azure-storage-azcopy/blob/59b3a184fef708669ef9779e27f5cb3ed43b7ccd/ste/xfer-localToFile.go#L228-L253) resulted in potential data corruption in the following cases:

1. File’s size is < 8 bytes.
2. File’s size is > chunkSize(4MB by default), file is uploaded chunk by chunk, and last chunk < 8 bytes.
3. Customer customized chunkSize(through –block-size) or use default value. For each chunk, chunkSizeInBytes % 8 != 0, and all bytes in range [0 : chunkSizeInBytes / 8 * 8] are 0(byte 0), while the bytes in range[len(chunkSizeInBytes) / 8 * 8 : chunkSizeInBytes] are not all 0(byte 0).

This problem has been [fixed](https://github.com/Azure/azure-storage-azcopy/pull/159), and will be released soon. We really apologize for the inconvenience. Please be mindful that this tool is still in preview, so please keep backups of your data.

**Comment by jiacfan** [comment]
Hi, All:

Following is a guide for finding out files that potentially influenced by this issue and recovering the files:
1.	Please use code ([here](https://gist.github.com/jiacfan/33150df696459d04cd55d3b908e83e7a)) to find files might be influenced by the issue.
  - How to build:
    a. Download go [SDK](https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgolang.org%2Fdl%2F&data=02%7C01%7Cjiacfan%40microsoft.com%7C5f4c6057ebd740709c1d08d678227e3a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636828486906322408&sdata=0RIbfplKKx2j8qPqALkzj%2Ffc5B2a8%2BsyIFjvmlGUZnk%3D&reserved=0).
    b. Create a folder and copy the code to a file naming “main.go” inside the folder.
    c. Run: `go get "github.com/Azure/azure-storage-file-go/azfile"`
    d. Run: `go build`
    e. Run the binary which is built out.
 
2.	Please check the listed files. Check if they exist in local and local version is expected to be uploaded.
3.	Upload listed files use azcopy with version >= 10.0.5-preview to recover the files.

Best Regards,
Jiachen

**Comment by zezha-msft** [comment]
Closing after a month+ on display. Please update to the latest version (v10.0.8).
