### ISSUE TITLE
I saw 2 different azcopy processes running copy files, and eventually failed

### ISSUE THREAD

**Issue by hanksu-deloitte** [Azure/azure-storage-azcopy#1600]
### Which version of the AzCopy was used? 
azcopy 7.1.0-netcorepreview

### Which platform are you using? (ex: Windows, Mac, Linux)
RHEL 7.5

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
sending data over to Storage BLOB containers.

### What problem was encountered?
I saw two processes running to send the one file:
1) /lib/azcopy/bin/azcopy
2) /bin/azcopy

### How can we reproduce the problem in the simplest way?
it happened but not always.

### Have you found a mitigation/solution?
not yet, but I want to use /bin/azcopy instead of azcopy which may trigger 2 different executables simultaneously and failed eventually with contention.

**Comment by mohsha-msft** [comment]
Please reopen if the issue persists.
