### ISSUE TITLE
Issues Running AzCopy with Azure container instance when deploying it from ARM templates

### ISSUE THREAD

**Issue by sarthakvijayvergiya** [Azure/azure-storage-azcopy#1607]
Which version of the AzCopy was used?
10.13.0

Which platform are you using? (ex: Windows, Mac, Linux)
Linux

What command did you run?
azcopy

What problem was encountered?
segmentation fault
![image](https://user-images.githubusercontent.com/18403281/139162276-0684e1d0-79ca-47c6-b1c2-22597174800f.png)

How can we reproduce the problem in the simplest way?
wget https://aka.ms/downloadazcopy-v10-linux
tar -xvf downloadazcopy-v10-linux
cd azcopy_linux*/
cp azcopy /usr/bin/
azcopy

Have you found a mitigation/solution?
no

**Comment by nakulkar-msft** [comment]
This was because of intermittent issues with getting environmental vars in ACI. Please file a new issue if you see this again.
