### ISSUE TITLE
Does AzureCopy v10x or v8.1 support table copy?

### ISSUE THREAD

**Issue by deepumi** [Azure/azure-storage-azcopy#161]
Hi, 

I would like to know how do I copy azure table storage data to on premise using azcopy latest versions (v8 or v10x). Currently I am using v73 https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy#azcopy-with-table-support-v73 which support table copy to local. However, I am seeing one issue that UTC column for TimeStamp is storing as different value. 

What is the alternative solution?

For ex : 
Azure storage explorer = 2019-01-10T15:38:48.035Z

![image](https://user-images.githubusercontent.com/554039/50996622-6292b880-14f0-11e9-8b1f-7bb1c202553e.png)

Downloaded json file using azurecopy.exe v73

![image](https://user-images.githubusercontent.com/554039/50996595-51e24280-14f0-11e9-829e-5be2947dedd7.png)

Thank you!
Deepu

**Comment by zezha-msft** [comment]
Hi @deepumi, thanks for reaching out!

AzCopy V10 does not, and probably will not, support copying table storage data. I'll let @EmmaZhu help you on the format issue with V7.3.

**Comment by deepumi** [comment]
@zezha-msft Thank you.

**Comment by EmmaZhu** [comment]
@deepumi AzCopy v8 doesn't support table transferring either. You can download AzCopy 7.1 from (
![image](https://user-images.githubusercontent.com/6396650/51093497-0c1ec600-17df-11e9-8060-5e68f4ec3ce9.png)) for table transferring.

**Comment by deepumi** [comment]
@EmmaZhu 
I'm already using AzCopy 7.1 version to download the data which I mentioned above, However, If I use this approach I will be not able to use any latest features for the newer version tool. Is there any alternative solution?. 

I can think of one more solution is to use storage explorer and export to locally. But in that case I cannot automate the download processand data loading to locally. 

What is the recommended approach?

Also any solution for DateTime serialization issue?

Thank you
Deepu

**Comment by AMoghrabi** [comment]
@zezha-msft Out of curiosity, why won't the v10 tool support table storage copy?

We're trying to automate the backups of blobs and table storage, the two resources we use in Azure Storage Accounts. It would be nice if we can have one tool that can do both jobs.

**Comment by zezha-msft** [comment]
Hi @AMoghrabi, great question! +@seguler to help answer it.

To my understanding, the Table Storage is going to be part of the Cosmos DB, so I think the tools supporting CosmosDB will be adding support for Table.

**Comment by deepumi** [comment]
@zezha-msft Does CosmosDB tool currently support storage table download?

**Comment by seguler** [comment]
@wmengmsft for Table support asks

**Comment by zezha-msft** [comment]
Closing as AzCopy is most likely not the right tool for adding Table support.
