### ISSUE TITLE
Azcopy cannot copy all data in aws s3 bucket

### ISSUE THREAD

**Issue by dumb-stuff** [Azure/azure-storage-azcopy#1618]
##### Note: The version is visible when running AzCopy without any argument
10.13.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
```bash
azcopy copy https://s3.ap-east-1.amazonaws.com/content.aws.biomooping.tk https://contentazurebiomoopingtk.blob.core.windows.net/contentazurebiomoopingtk --recursive=true
```
### What problem was encountered?
```bash
INFO: Scanning...
INFO: Authenticating to destination using Azure AD
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

failed to perform copy command due to error: cannot start job due to error: cannot list objects, The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to..
```
### How can we reproduce the problem in the simplest way?
Follow tutorial at [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-s3)
### Have you found a mitigation/solution?
no

**Comment by siminsavani-msft** [comment]
Hi @dumb-stuff ! Thank you for reaching out! I was able to successfully upload from S3 bucket to Blob. I noticed that you are running getting an error `The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to..` which seems to be an issue related to AWS's way of checking regional location.

Could you please try the command again with the correct location?

**Comment by dumb-stuff** [comment]
how to that?  
you mean https://s3.ap-east-1.awsamazon.com ?

**Comment by siminsavani-msft** [comment]
@dumb-stuff You can check the AWS region by clicking properties in your S3 bucket in the AWS console.

**Comment by dumb-stuff** [comment]
Uh yeah it's not success it also fail

**Comment by siminsavani-msft** [comment]
@dumb-stuff Could you please send the new command you are running now?

**Comment by dumb-stuff** [comment]
> @dumb-stuff Could you please send the new command you are running now?

My bucket is at ap-east-1 by default so I tested to download files through aws cli and it's working.

I haven't modified anything in commands yet.

**Comment by dumb-stuff** [comment]
Also when tries to copy data again with azcopy with this command
```
azcopy copy "https://s3.awsamazon.com/content-aws.biomooping.tk" "https://contentazurebiomoopingtk.blob.core.windows.net/contentazurebiomoopingtk" --recursive
```
Now I get weirds error
```
INFO: Scanning...
INFO: Authenticating to destination using Azure AD
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\?\C:\Users\Rukchad Wongprayoon\https:\s3.awsamazon.com\content-aws.biomooping.tk, please verify that it is a valid.
```

**Comment by siminsavani-msft** [comment]
@dumb-stuff Let's try changing the source URL to something like this 
`"https://[insert-bucket-name].s3.[region-name].amazonaws.com/[object-name]"` 

So in your case this would be:
`"https://[insert-bucket-name].s3.ap-east-1.amazonaws.com/content-aws.biomooping.tk"` 

The command should look like this:
`copy "https://[insert-bucket-name].s3.ap-east-1.amazonaws.com/content-aws.biomooping.tk" "https://contentazurebiomoopingtk.blob.core.windows.net/contentazurebiomoopingtk" --recursive`

Note that you should add the bucket name to the URL. Please let me know if this works!

**Comment by dumb-stuff** [comment]
So I used this command
```
azcopy copy "https://content-aws.biomooping.tk.s3.ap-east-1.amazonaws.com/content-aws.biomooping.tk" "https://contentazurebiomoopingtk.blob.core.windows.net/contentazurebiomoopingtk" --recursive
```
And it have certificate error
```
C:\Users\Rukchad Wongprayoon>azcopy copy "https://content-aws.biomooping.tk.s3.ap-east-1.amazonaws.com" "https://contentazurebiomoopingtk.blob.core.windows.net/contentazurebiomoopingtk" --recursive
INFO: Scanning...
INFO: Authenticating to destination using Azure AD
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

failed to perform copy command due to error: cannot start job due to error: cannot list objects, Get "https://biomooping.tk.s3.ap-east-1.amazonaws.com/content-aws.biomooping.tk/?delimiter=&fetch-owner=true&list-type=2&max-keys=1000&prefix=": x509: certificate is valid for *.s3.ap-east-1.amazonaws.com, s3.ap-east-1.amazonaws.com, *.s3-ap-east-1.amazonaws.com, s3-ap-east-1.amazonaws.com, *.s3.dualstack.ap-east-1.amazonaws.com, s3.dualstack.ap-east-1.amazonaws.com, *.s3-control.ap-east-1.amazonaws.com, s3-control.ap-east-1.amazonaws.com, *.s3-control.dualstack.ap-east-1.amazonaws.com, s3-control.dualstack.ap-east-1.amazonaws.com, *.s3-accesspoint.ap-east-1.amazonaws.com, *.s3-accesspoint.dualstack.ap-east-1.amazonaws.com, not biomooping.tk.s3.ap-east-1.amazonaws.com
```

**Comment by dumb-stuff** [comment]
oh wait i have idea  
what if I make another bucket copy all data in it and use content-aws.biomooping.tk bucket as a redirector?  
So I will not have error?  
I will try it out

**Comment by dumb-stuff** [comment]
well it didnt work

**Comment by dumb-stuff** [comment]
because of the redirector in bucket  
it didnt accept any domain

**Comment by siminsavani-msft** [comment]
> rform copy co

Hmm... Could you try renaming your bucket name without "." in the name? Not sure if this will help but it is worth a shot!

**Comment by dumb-stuff** [comment]
nevermind it  
i don't use azure s3 now.  
thanks for your time  
<3
