### ISSUE TITLE
sync big files to azure storage container:  uncommitted block count exceeded 

### ISSUE THREAD

**Issue by dimidir** [Azure/azure-storage-azcopy#1621]
### Which version of the AzCopy was used? 
azcopy version 10.12.2 on Ubuntu 18.04

### What command did you run?
.../azcopy sync "/datadisk/pgbackrest/log" "https://url+SAS" --put-md5

### What problem was encountered?
ERR: [P#0-T#0] UPLOADFAILED: /path/to/file : 409 : 409 The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.. When Staging block. X-Ms-Request-Id: 57d4adc9-601e-001a-4d9d-db9e48000000

### How can we reproduce the problem in the simplest way?
azcopy sync big files to azure storage container

What I am trying is to copy the backup repos + logs of my postgres backup solution to a storage container as another backup layer.

**Comment by mohsha-msft** [comment]
Hey @dimidir ,
Thanks for reaching out and I apologize for not replying earlier.

What is the maximum size of file you are trying to transfer? Can you send me the log file or complete snippet of error from log file. I want to understand the content-length we're transferring in Put Block call.

As a mitigation step, can you manually try setting `block-size-mb` to large value (Upto 4000MiB) 
https://docs.microsoft.com/en-us/rest/api/storageservices/put-block#remarks

**Comment by mohsha-msft** [comment]
Please reopen the issue with more information.
