### ISSUE TITLE
sync panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by asgerls** [Azure/azure-storage-azcopy#1625]
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run? 
.\azcopy sync "https://xxxxx.blob.core.windows.net/drive-r/*?sp=SAS" "F:\" --recursive
### What problem was encountered?
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job f4f8808d-4317-984e-7026-6744b0efaaa6 has started
Log file is located at: C:\Users\asgers_aadds_admin\.azcopy\f4f8808d-4317-984e-7026-6744b0efaaa6.log

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x1352800]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/cmd.(*localTraverser).Traverse.func1(0xc0000302d0, 0x6, 0x0, 0x0, 0x0, 0x0, 0xc0000302f0, 0xc000030350)
        /home/vsts/work/1/s/cmd/zc_traverser_local.go:355 +0x680
github.com/Azure/azure-storage-azcopy/v10/cmd.WalkWithSymlinks.func1(0xc0000302f0, 0x7, 0x1707358, 0xc0001342a0, 0x0, 0x0, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/zc_traverser_local.go:278 +0x1104
github.com/Azure/azure-storage-azcopy/v10/common/parallel.Walk(0xc0000302f0, 0x7, 0x10, 0x0, 0xc000a9ec00)
        /home/vsts/work/1/s/common/parallel/FileSystemCrawler.go:89 +0x136
github.com/Azure/azure-storage-azcopy/v10/cmd.WalkWithSymlinks(0xc0000302d0, 0x7, 0xc000a9eeb8, 0x0, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/zc_traverser_local.go:186 +0x217
github.com/Azure/azure-storage-azcopy/v10/cmd.(*localTraverser).Traverse(0xc0000a1120, 0x0, 0xc00003e2a0, 0x1d2dfa0, 0x0, 0x0, 0x16eece0, 0xc00037a230)
        /home/vsts/work/1/s/cmd/zc_traverser_local.go:382 +0x925
github.com/Azure/azure-storage-azcopy/v10/cmd.(*syncEnumerator).enumerate(0xc0000e6190, 0x1701b00, 0xc00003a390)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:622 +0x9e
github.com/Azure/azure-storage-azcopy/v10/cmd.(*cookedSyncCmdArgs).process(0xc000264a80, 0xb4, 0x0)
        /home/vsts/work/1/s/cmd/sync.go:683 +0x425
github.com/Azure/azure-storage-azcopy/v10/cmd.init.19.func2(0xc0003d3900, 0xc0003c8cf0, 0x2, 0x3)
        /home/vsts/work/1/s/cmd/sync.go:718 +0x17a
github.com/spf13/cobra.(*Command).execute(0xc0003d3900, 0xc0003c8c90, 0x3, 0x3, 0xc0003d3900, 0xc0003c8c90)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1cd9e20, 0xa6aaefb044672670, 0x30, 0x14a75e0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute(0xc0000d06c0, 0x23, 0xc0000d06c0, 0x23, 0xc0000d07b0, 0x29, 0x7fffffff)
        /home/vsts/work/1/s/cmd/root.go:165 +0xfa
main.main()
        /home/vsts/work/1/s/main.go:82 +0x397

### How can we reproduce the problem in the simplest way?
sync content of container to a local drive.
### Have you found a mitigation/solution?
no

**Comment by mohsha-msft** [comment]
Hey @asgerls ,

Thanks for reaching out. I've reproduced this. I'll try to fix it in the next release.

**Comment by mohsha-msft** [comment]
`fileInfo` is coming as NULL. fileInfo.Mode()  in L355 -> is causing panic.
https://github.com/Azure/azure-storage-azcopy/blob/058bd5bc5b970074520e4ee088b15328d888c483/cmd/zc_traverser_local.go#L336-L355

**Comment by subercui** [comment]
Hi @mohsha-msft, I encountered the same issue. Is there any walk-around so far? Need to copy the files to local disk.

**Comment by mohsha-msft** [comment]
Duplicate https://github.com/Azure/azure-storage-azcopy/issues/1601

**Comment by mohsha-msft** [comment]
Fixed in 10.14.1 release.

**Comment by Amila13** [comment]
> 
this not fixed in this version in 10.14.1 release,  still azcopy.exe not working
