### ISSUE TITLE
AzCopy sync re-copies files even if file already exists and is unchanged (date modified matches).

### ISSUE THREAD

**Issue by g7cnp** [Azure/azure-storage-azcopy#1631]
##### Note: The version is visible when running AzCopy without any argument
10.13.0
### Which platform are you using? (ex: Windows, Mac, Linux)
windows 11
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy.exe sync "https://scottrichards.file.core.windows.net/sr2/apps/test1?[KEY]" "C:\local copies\apps\test1" 
### What problem was encountered?
On first run all works fine and files copy from remote folder 'test1' to local folder 'test1' 
If the command is then re-run the files get copied again despite neither file being changed. If either source or destination file is modified behaviour is as expected. 
It would appear that the destination file gets over written if it's modified date is less than or equale to the source file rather than just less than? It may be I'm just missing a flag to adjust this behaviour?
### How can we reproduce the problem in the simplest way?
Just run a sync twice and check if files get copied during the second run.
### Have you found a mitigation/solution?
Double check the date/time comparison logic.

**Comment by g7cnp** [comment]
Is there a reason this hasn't been picked up?
All i want to do is copy a folder structure from Azure to the local drive, then keep that local copy UpToDate with any changes i make to the Azure version, but every time i run the command it copies everything not just the changes. I've tried using the sync command and copy with --overwrite=ifSourceNewer

**Comment by adreed-msft** [comment]
I've got a repro on this.

**Comment by adreed-msft** [comment]
> Is there a reason this hasn't been picked up?
I apologize. Unfortunately, sometimes things fall through the cracks. We're a somewhat small team working on AzCopy and we can't keep up with everything, between issues, feature requests, etc. both internal and external.

**Comment by g7cnp** [comment]
I let #1631 drop as it seamed a duplicate of #1666, but either will do!

Regards

Huw Weatherhead
Weatherheads Web
07917890093

**Comment by adreed-msft** [comment]
It seems like this is a bit of funkiness at play with --preserve-smb-info=true (which is the default setting). There are two separate LMTs stored service side-- The actual `Last-Modified` header (which is the last time we've written to the file according to the service) and `x-ms-last-write-time` (which is the last time we've written to the file according to our SMB properties). These don't end up aligning, and this causes issues.

@zezha-msft @mohsha-msft @nakulkar-msft @siminsavani-msft this does raise an interesting question I believe I asked back when I was writing this feature initially. Should we consider the SMB last write time to be "truer" than the service Last-Modified header?

**Comment by zezha-msft** [comment]
@adreed-msft  could you please outline how the timestamps cause this issue?

**Comment by adreed-msft** [comment]
We use two flags for LMT on Azure Files-- Before SMB property persistence came along, we used Last-Modified (this is still the case in the frontend even if --preserve-smb-info=true). When we preserve info, we choose to write the file times according to the SMB properties (x-ms-file-change-time etc.)

The latter may not always be present, nor necessarily accurate, as the service doesn't handle updating it unless the user informs it to by setting the property manually.

The former is eternally accurate, but isn't compatible with our typical SMB property persistence methodology, as the file timestamp will for certain be in the past every time (assuming a user doesn't write a file time in the future)

**Comment by adreed-msft** [comment]
So, the question becomes, despite the potential inaccuracy of x-ms-file-change-time, should we opt to use it instead when present, when --preserve-smb-info is present?

Secondarily, this behavior of using x-ms-file-change-time is not available on Linux and MacOS.

**Comment by g7cnp** [comment]
I'm syncing from Azure File Share to a local drive.
So the first time sync is run the file doesn't exist locally so, it is copied from Azure, using a  Get File call?, which will return headers for x-ms-file-last-write-time, x-ms-file-change-time and Last-Modified, presumable one of these three will be used to set the last modified time for the new local file.

On a second run I would assume a Get File Properties call is used, which basically gets the same set of headers, with the same three candidates for Last Modified Time. Assuming the header values are exactly the same as those returned by the original Get File call, it doesn't matter which one is used to compare with the local file LMT as long as it's the same one that was originally used to set the LMT on the local file?

This is very reminiscent of errors in Robocopy when synching between NTFS and FAT where the the times were recorded at different resolutions so the time was rounded to fit the lower resolution, but I'm sure you are both far too young to remember such fun!

**Comment by Miltxn** [comment]
Is this bug still being worked on? Is there a work-around?
I need to sync several TBs, and it's copying every single file every time I sync, instead of only replacing the modified ones.

**Comment by ramakrishnaraov** [comment]
workaround is to use azcopy **copy** --overwrite=ifSourceNewer

**Comment by g7cnp** [comment]
> > Is this bug still being worked on? Is there a work-around? I need to sync several TBs, and it's copying every single file every time I sync, instead of only replacing the modified ones.
> 
> workaround is to use azcopy **copy** --overwrite=ifSourceNewer

I tried using Copy with the --overwrite=ifSourceNewer option but the behavior was the same, at least it was with 10.14

**Comment by bricelabelle** [comment]
I'm on 10.16.1 and this issue is still present.

**Comment by gapra-msft** [comment]
Hi, it looks like this issue has been resolved with the above PR which was shipped as part of 10.16.2, so I will go ahead and close this issue. In case you are still experiencing this issue after upgrade, please feel free to reopen the issue to let us know.

**Comment by bhusvariso** [comment]
Hi all - I'm using 10.16.2 and I still seem to be having the issue where azcopy sync with --mirror-mode=true is still re-copying all files even though their modification dates match on both source and destination.

**Comment by DanRamage** [comment]
I know this issue is closed, however the latest version: 10.18.1 still exhibits this behavior.

**Comment by badnumbers** [comment]
I have this same issue using 10.18.1 on Ubuntu. I'm syncing from a local directory to blob and it always copies all files, even ones that are already in blob. Please reopen this ticket.

**Comment by MonkeyNinja** [comment]
I've been having this issue with the latest version of azcopy( 10.19.0)...

I dug in and read through some of the sync code...noticed it writes its  copy/not copy decisions to a log file - which you can find next to the job log, in my case:

```
/home/vscode/.azcopy/<<<job guid>>>-scanning.log
```
I had a poke around in there and noticed I was getting access denied when azcopy tried to enumerate the destination directories...( i've now noticed you  get a message in summary like this: INFO: Failed to scan directory/file . Logging errors in scanning logs. )


I changed my SAS key to include containers and objects - and now it will just transfer the updated files...


```bash
Files Scanned at Source: 38
Files Scanned at Destination: 19
Elapsed Time (Minutes): 0.0671
Number of Copy Transfers for Files: 19
Number of Copy Transfers for Folder Properties: 1 
Total Number Of Copy Transfers: 20
Number of Copy Transfers Completed: 20
Number of Copy Transfers Failed: 0
Number of Deletions at Destination: 0
Total Number of Bytes Transferred: 11120402
Total Number of Bytes Enumerated: 11120402
Final Job Status: Completed
```
