### ISSUE TITLE
azcopy copy stuck in when it is run in the background Linux

### ISSUE THREAD

**Issue by Irmius** [Azure/azure-storage-azcopy#1633]
### Which version of the AzCopy was used? 
10.11.0 and 10.13.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux Ubuntu docker
docker file
```
FROM eostudio/eos:v2.0.7

RUN cd / && \
    apt-get update -y && \
    apt install wget -y && \
    apt install jq -y && \
    apt install pigz -y && \
    #apt-get install ntpdate -y && \
    #ntpdate -s time.nist.gov && \
    wget -c https://aka.ms/downloadazcopy-v10-linux && \
    tar -xf downloadazcopy-v10-linux && rm downloadazcopy-v10-linux && \
    cp azcopy_linux_amd64*/azcopy /usr/local/bin && rm -r azcopy_linux_amd64*
```
### What command did you run?

(azcopy copy "filename" "https://storageacc.file.core.windows.net/filesharename/filename?svtoken) &

### What problem was encountered?

Process just hangs and do nothing even in the azcopy jobs list it doesn't appear. It was working before and stopped to work.
It works if I run command not in the background 
like this `azcopy copy "filename" "https://storageacc.file.core.windows.net/filesharename/filename?svtoken`, but if I run it like this 
`(azcopy copy "filename" "https://storageacc.file.core.windows.net/filesharename/filename?svtoken) &` in the background it doesn't work
Linux process stat is Tl
### How can we reproduce the problem in the simplest way?

Use docker file which provided, issue sas token. try to copy any file, but run azcopy in the background. As in my example:
`(azcopy copy "filename" "https://storageacc.file.core.windows.net/filesharename/filename?svtoken) &`

### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment]
Hey @Irmius ,

Thanks for reaching out!
Can you try running AzCopy in background without using a Docker. We have tried to reproduce this issue but it worked as expected. Please share your findings and reopen the issue again.
