### ISSUE TITLE
Support Azure File NFS as target

### ISSUE THREAD

**Issue by TiloGit** [Azure/azure-storage-azcopy#1648]
https://docs.microsoft.com/en-us/azure/storage/files/files-nfs-protocol#support-for-azure-storage-features

Is that planned feature of azcopy? any ETA to share?

**Comment by adreed-msft** [comment]
I'll file this in our backlog for now. We don't currently have any plans so far as I know.

**Comment by nakulkar-msft** [comment]
Currently Azure NFS shares do not support data plane rest apis. This feature request will be revisited when we've support for the same.

**Comment by TiloGit** [comment]
@adreed-msft any update on that? can you link the backlog item. please.
