### ISSUE TITLE
azcopy vs PowerShell *AzStorage* executables

### ISSUE THREAD

**Issue by Liturgist** [Azure/azure-storage-azcopy#1649]
What is the difference between and in what situations is it better to use azcopy.exe or the PowerShell Core *-AzStorage* commands?

Searching the net has not yet resulted in anything clear.

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10?toc=/azure/storage/blobs/toc.json
https://docs.microsoft.com/en-us/powershell/module/az.storage/start-azstoragefilecopy?view=azps-7.1.0

**Comment by adreed-msft** [comment]
I'm unaware of the particular downsides of the AzStorage commands compared to AzCopy, but I can at least describe AzCopy. AzCopy is a dedicated tool that can be executed from outside of the PowerShell environment. Additionally, it makes use of service-to-service copy APIs for transfers within Azure Storage services and multi-threading to enable high throughput transfers.

**Comment by Liturgist** [comment]
Thank you for your reply, @adreed-msft. There are 142 `*-AxStorage*` commands and only one (1) `azcopy.exe` with mand command parameters. Do they both have equivalent functionality?

Are these both based on a .Net API that uses host services?

**Comment by gapra-msft** [comment]
Hi @Liturgist while we can't speak to the specifics of AzStorage commands, azcopy and AzStorage do not have equivalent functionality. As @adreed-msft mentioned, AzCopy is a dedicated tool for efficient Azure storage transfers. It is written in GoLang, and depends on various azure-sdk-for-go SDKs.

**Comment by Liturgist** [comment]
There appears to be no comparison of the capabilities of azcopy and PowerShell Core -AzStorage. Closing as dead end.
