### ISSUE TITLE
Is azcopy with a destination blob filename no longer supported?

### ISSUE THREAD

**Issue by sicklittlemonkey** [Azure/azure-storage-azcopy#1652]
### Which version of the AzCopy was used? 
Success: 10.5.0
Failure: 10.13.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows (amd64)

### What command did you run?

This PowerShell script which was working a year ago:
```
$source = $file.FullName
$blob_name = $file.Name -replace ' ',''
$dest = "https://$account.blob.core.windows.net/$container/$blob_path/$blob_name?$SAS"
azcopy copy $source $dest
```

Here are the commands from the azcopy logs (with paths and filenames changed).

Success command with version 10.5.0.
Note that the logged command contains the specified destination blob name:
> 2020/07/28 05:40:17 Job-Command copy C:\dev\Filename With Spaces.exe https://somewhere.blob.core.windows.net/path/1.0.0.0/FilenameWithoutSpaces.exe?se=2020-08-22t00%3A45%3A59z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28

Failure command with version 10.13.0.
Note that the logged command OMITS the specified destination blob name:
> 2022/01/10 08:53:01 Job-Command copy C:\dev\Filename With Spaces.exe https://somewhere.blob.core.windows.net/path/1.0.0.0/?se=2025-07-02t12%3A23%3A00z&sig=-REDACTED-&sp=racwdxlt&sr=c&st=2021-07-01t12%3A23%3A14z&sv=2020-04-08 

### What problem was encountered?

In both cases the file is successfully copied.

But in the failure case (recent versions) the specified destination blob filename is ignored.
The blob created in Azure has the same name as the source file, not the specified destination blob name.

### How can we reproduce the problem in the simplest way?

Copy a local file to Azure blob storage and specify a blob name different from the source file name.

### Have you found a mitigation/solution?

Only to rename the source file locally.

**Comment by nakulkar-msft** [comment]
Hi @sicklittlemonkey, this is still supported and working. Can you let us know if you're seeing something different. If you've the log file that will be helpful.

**Comment by sicklittlemonkey** [comment]
I quoted log excerpts from working and non-working versions above. The blob name is omitted from the URL in the log.

> 2022/01/10 08:53:01 Job-Command copy C:\dev\Filename With Spaces.exe https://somewhere.blob.core.windows.net/path/1.0.0.0/?se=2025-07-02t12%3A23%3A00z&sig=-REDACTED-&sp=racwdxlt&sr=c&st=2021-07-01t12%3A23%3A14z&sv=2020-04-08

**Comment by nakulkar-msft** [comment]
@sicklittlemonkey  the statement you've mentioned is logged by a simple code which logs the command line args after redacting secrets. Have to checked command you've provided to azcopy again?

**Comment by nakulkar-msft** [comment]
Hi @sicklittlemonkey Please reopen after you've verified the logs.

**Comment by roscoegray** [comment]
Having the same issue, how do you now define the destination name?
