### ISSUE TITLE
azcopy hangs for 2 seconds following every job

### ISSUE THREAD

**Issue by mkcello96** [Azure/azure-storage-azcopy#1653]
(This is a repost of https://github.com/Azure/azure-storage-azcopy/issues/1624 since it got missed)

### Which version of the AzCopy was used? 

Note: The version is visible when running AzCopy without any argument
10.13.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

azcopy copy 'https://qag1ge1cassandrabackup.blob.core.usgovcloudapi.net/cassandra-backup-cct?' '/tmp/medusa-restore-94bfe653-12db-48be-838f-364ecbc9228b/system_auth/resource_role_permissons_index-5f2fbdad91f13946bd25d5da3a5c35ec' --include-path 'qag1ge1lcct001.ag1.taservs.net/data/system_auth/resource_role_permissons_index-5f2fbdad91f13946bd25d5da3a5c35ec/md-22-big-Digest.crc32'

### What problem was encountered?

There is a 2 second pause after every job, even for a simple single-file download from blob storage. We are trying to speed up database restores with azcopy, which means that many azcopy commands will run in sequence. We try and batch as many files as possible but we end up with a lot of small batches of small files - the 2 second pauses really add up.

Can a flag be added to disable whatever is happening during these 2 seconds? I assume it's the job summary at the end but logs do not tell me what is going on during that time (I've tried enabling DEBUG as well). I have added the logs to the end of this description.

NOTE: I've followed suggestions here for optimizing performance: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize. None seem to help this situation.

NOTE 2: The servers that these commands are running on are Azure VMs that are heavily locked down in terms of access to the internet. There is a proxy that only allows specific traffic.

### How can we reproduce the problem in the simplest way?

Do any small-file copy job

### Have you found a mitigation/solution?

No

Logs:

```
2021/11/17 21:58:15 OS-Environment  linux
2021/11/17 21:58:15 OS-Architecture  amd64
2021/11/17 21:58:15 Log times are in UTC. Local time is 17 Nov 2021 21:58:15
2021/11/17 21:58:15 Job-Command copy https://qag1ge1cassandrabackup.blob.core.usgovcloudapi.net/cassandra-backup-cct?REDACTED /tmp/medusa-restore-94bfe653-12db-48be-838f-364ecbc9228b/system_auth/resource_role_permissons_index-5f2fbdad91f13946bd25d5da3a5c35ec --include-path qag1ge1lcct001.ag1.taservs.net/data/system_auth/resource_role_permissons_index-5f2fbdad91f13946bd25d5da3a5c35ec/md-22-big-Digest.crc32 --log-level INFO 
2021/11/17 21:58:15 Number of CPUs: 2
2021/11/17 21:58:15 Max file buffer RAM 1.000 GB
2021/11/17 21:58:15 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2021/11/17 21:58:15 Check CPU usage when dynamically tuning concurrency: false (Based on AZCOPY_TUNE_TO_CPU environment variable)
2021/11/17 21:58:15 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2021/11/17 21:58:15 Max enumeration routines: 1 (Based on AZCOPY_CONCURRENT_SCAN environment variable)
2021/11/17 21:58:15 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2021/11/17 21:58:15 Max open files when downloading: 3689 (auto-computed)
2021/11/17 21:58:15 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2021-11-17T21:58:10Z or --include-after=2021-11-17T21:58:10Z
2021/11/17 21:58:15 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2021/11/17 21:58:15 Final job part has been created
2021/11/17 21:58:15 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs:  0
2021/11/17 21:58:15 100.0 %, 0 Done, 0 Failed, 0 Pending, 0 Skipped, 0 Total (scanning...), [States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs:  0], 
2021/11/17 21:58:15 JobID=d6b2e267-de97-d64e-5faf-cca99847a91d, credential type: Anonymous
2021/11/17 21:58:15 scheduling JobID=d6b2e267-de97-d64e-5faf-cca99847a91d, Part#=0, Transfer#=0, priority=0
2021/11/17 21:58:15 Final job part has been scheduled
2021/11/17 21:58:15 INFO: [P#0-T#0] has worker 9 which is processing TRANSFER 0
2021/11/17 21:58:15 ==> REQUEST/RESPONSE (Try=1/18.928562ms, OpTime=36.812627ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://qag1ge1cassandrabackup.blob.core.usgovcloudapi.net/cassandra-backup-cct/qag1ge1lcct001.ag1.taservs.net/data/system_auth/resource_role_permissons_index-5f2fbdad91f13946bd25d5da3a5c35ec/md-22-big-Digest.crc32?se=2021-11-18t19%3A17%3A57z&sig=-REDACTED-&sp=r&sr=c&sv=2018-11-09&timeout=901
   X-Ms-Request-Id: [6e0affe5-501e-0046-08fe-db78ac000000]

2021/11/17 21:58:15 INFO: [P#0-T#0] DOWNLOADSUCCESSFUL: /tmp/medusa-restore-94bfe653-12db-48be-838f-364ecbc9228b/system_auth/resource_role_permissons_index-5f2fbdad91f13946bd25d5da3a5c35ec/cassandra-backup-cct/qag1ge1lcct001.ag1.taservs.net/data/system_auth/resource_role_permissons_index-5f2fbdad91f13946bd25d5da3a5c35ec/md-22-big-Digest.crc32
2021/11/17 21:58:15 JobID=d6b2e267-de97-d64e-5faf-cca99847a91d, Part#=0, TransfersDone=1 of 1
2021/11/17 21:58:15 all parts of entire Job d6b2e267-de97-d64e-5faf-cca99847a91d successfully completed, cancelled or paused
2021/11/17 21:58:15 is part of Job which 1 total number of parts done 
2021/11/17 21:58:17 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs: 32
2021/11/17 21:58:17 

Diagnostic stats:
IOPS: 0
End-to-end ms per request: 36
Network Errors: 0.00%
Server Busy: 0.00%


Job d6b2e267-de97-d64e-5faf-cca99847a91d summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 1
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 10
Final Job Status: Completed
```

**Comment by zezha-msft** [comment]
Hi @mkcello96, could you please clarify how you observed the 2 second hang? Is it after the job summary or before?

**Comment by mkcello96** [comment]
@zezha-msft it is before the job summary. See the attached logs. It occurs after this log:

```2021/11/17 21:58:15 is part of Job which 1 total number of parts done ```

**Comment by zezha-msft** [comment]
Thanks @mkcello96 for the confirmation. I think the 2 second delay is caused by the transfer being extremely small and AzCopy fetching the job status every 2 seconds. 

If you don't mind me asking, how many jobs are you running consecutively? Have you considered using the pipe mode? It doesn't have status updates. 
```
azcopy cp "https://[account].blob.core.windows.net/[container]/[path/to/blob]?[SAS]" > "/path/to/file.txt"
```

**Comment by mkcello96** [comment]
@zezha-msft sorry for the delay and thanks for your input. We are hoping to run ~100 of these jobs consecutively. Single thread so no parallel work. 
The `--include-path` functionality is important to us. The example I gave was simple but in most jobs we have many different files included in the azcopy command (separated by semi-colons). 

I imagine running a single azcopy job per file will be slower? Is there any option to use pipe mode with a list of files?

**Comment by zezha-msft** [comment]
Hi @mkcello96, pipe mode is by definition for a single file. 

To confirm, you are running ~100 of these jobs consecutively, where each job consists of up to 100 distinct files going to the same destination, correct?

Are these 100 files all small like the example you've shown? Your example was only 10 bytes.

If the amount of data to transfer is negligible, then the overhead is the 2 second wait between status updates. If your 100 files add up to considerable amount of data, then the 2 second wait has almost no impact.

**Comment by mkcello96** [comment]
Hi @zezha-msft , yes most of the files are quite small. The 2 seconds really add up. Is there no way to disable the job summary?

**Comment by zezha-msft** [comment]
@mkcello96 not right now, the 2 second is hard coded to not pull status too frequently, which could cause problems for large jobs. I see your point that for extremely small jobs that requires low latency, this long wait time is not great.

This is an open source project after all, so if you want to simply override the value [here](https://github.com/Azure/azure-storage-azcopy/blob/main/common/lifecyleMgr.go#L508) and build your own version, that's totally a reasonable way to mitigate the issue for now.

We will look into solving this issue for the long-term.

**Comment by mkcello96** [comment]
@zezha-msft ok thank you for confirming!

**Comment by supermistag** [comment]
Feedback: I had a similar issue with almost 8 million files of 50KB each. After 12 hours it wasn't even 5% complete.

I built a copy using the branch of nakulkar, and reduced the time down to 75 minutes.

Thanks.
