### ISSUE TITLE
AzCopy throwing "panic error" when using "--include-before" option

### ISSUE THREAD

**Issue by abu3lia** [Azure/azure-storage-azcopy#1655]
### Which version of the AzCopy was used? 
>azcopy --version
azcopy version 10.13.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
C:\Users\muabuali\Downloads>azcopy.exe copy "https://a3standard.file.core.windows.net/testingsnapshots?SAS_Goes_Here" "https://a3standard.file.core.windows.net/include-before?SAS_Goes_Here" --recursive --preserve-smb-info=true --include-before 2021-11-10	

### What problem was encountered?
`INFO: Please note: the preserve-permissions flag is set to false, thus AzCopy will not copy SMB ACLs between the source and destination. To learn more: https://aka.ms/AzCopyandAzureFiles.
INFO: Scanning...
INFO: Any empty folders will be processed, because source and destination both support folders. For the same reason, properties defined on folders will be processed
**panic: cannot use IncludeBeforeDateFilter on an object for which no Last Modified Time has been retrieved**

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/cmd.(*IncludeBeforeDateFilter).DoesPass(0xc0004760c0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x229dfa0, 0x0, ...)
        /home/vsts/work/1/s/cmd/zc_filter.go:345 +0x108
github.com/Azure/azure-storage-azcopy/v10/cmd.passedFilters(0xc0001c4ae0, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:704 +0x162
github.com/Azure/azure-storage-azcopy/v10/cmd.processIfPassedFilters(0xc0001c4ae0, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:727 +0x98
github.com/Azure/azure-storage-azcopy/v10/cmd.(*fileTraverser).Traverse.func2(0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x229dfa0, 0x0, 0x0, ...)
        /home/vsts/work/1/s/cmd/zc_traverser_file.go:156 +0xa5
github.com/Azure/azure-storage-azcopy/v10/cmd.(*fileTraverser).Traverse(0xc00014e080, 0x0, 0xc000380cc0, 0xc0001c4ae0, 0x1, 0x1, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/zc_traverser_file.go:172 +0xbe3
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CopyEnumerator).enumerate(0xc00003e080, 0xe361ff2500000000, 0xe42e8049aa4cedf7)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:676 +0x6e
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CookedCopyCmdArgs).processCopyJobPartOrders(0xc000081000, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copy.go:1403 +0x6af
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CookedCopyCmdArgs).process(0xc000081000, 0x1b2, 0xb)
        /home/vsts/work/1/s/cmd/copy.go:1157 +0xc5
github.com/Azure/azure-storage-azcopy/v10/cmd.init.2.func2(0xc00041d680, 0xc000360d20, 0x2, 0x6)
        /home/vsts/work/1/s/cmd/copy.go:1793 +0x1e5
github.com/spf13/cobra.(*Command).execute(0xc00041d680, 0xc000360c60, 0x6, 0x6, 0xc00041d680, 0xc000360c60)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2249e20, 0xf1fdb4c5e42e8049, 0x30, 0x1a175e0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute(0xc0000ab160, 0x19, 0xc0000ab160, 0x19, 0xc0000ab1a0, 0x1f, 0x7fffffff)
        /home/vsts/work/1/s/cmd/root.go:165 +0xfa
main.main()
        /home/vsts/work/1/s/main.go:82 +0x397`

### How can we reproduce the problem in the simplest way?
Perform an AzCopy copy operation with the parameter "--include-before".

### Have you found a mitigation/solution?
No,

**Comment by mohsha-msft** [comment]
Fix released in AzCopy `10.14.0`
