### ISSUE TITLE
Azcopy not working on Azure virtual machine but is working locally

### ISSUE THREAD

**Issue by TomGraham1** [Azure/azure-storage-azcopy#1656]
### Which version of the AzCopy was used? 
AzCopy 10.13.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows  
### What command did you run?
azcopy copy "<fileshare path><sastoken>" . --recursive

### What problem was encountered?
I got an authorization error response when running it on the virtual machine. Note we setup a static public ip address for the vm. I ran the same code as above on my local machine and it worked fine. Both machines have had their IP's whitelisted in the fileshare. 
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Tue, 18 Jan 2022 11:10:03 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [23a021fa-cb58-4f14-61dd-6e906dea73c4]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [c355059c-901a-006e-125b-0cb2c6000000]

### How can we reproduce the problem in the simplest way?
run the same code on both a local machine and an azure virtual machine with a static IP
### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment]
Hey @TomGraham1 ,

Thanks for reaching out!

Please help me with more information.
1. What is the mode of authentication you're using? Are you using SAS or Shared Key or AAD? Do you have enough permissions? 
2. What is the AzCopy command you're using.
3. Can you please provide us with the AzCopy log file.

Please reopen this issue again once you have the answers to above questions.

**Comment by james64738** [comment]
Apologies for posting on a closed thread, but was there a solution to this one?

I'm having this exact same problem, can upload fine locally (from my dev PC), but can't when trying to backup/upload from an Azure VM. I get the same error that Tom was. I'm using AzCopy v10.

Details:
- Version: 10.25.1
- Authentication: SAS. Date Range, tried both IP and without IP, with full permissions
- Command: AZcopy "local src directory\*" "cloud-url?sp...." --recursive=true

The log records the failure with: 
- INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission PUT ....

I have:
- Added the Web Servers IP address to the exception list for the container.
- Confirmed that I have correctly assigned permissions to SAS token: All permissions, valid date ranges, and the IP address
- Also tried using Shared Access token without any IP. And used that same token from both the VM and from my local PC, it works from my local PC, but does not from the VM. 

Is there some obscure Azure setting somewhere that I missed?
Any ideas/suggestions would be greatly appreciated.

thanks for your time.

**Comment by james64738** [comment]
Just posting a follow up.

Turns out Azure doesn't honour the Container's IP address exception rule if the virtual PC is within the same region as the Container.
Creating a container in a different region to the VM allowed the azcopy to upload the files successfully.
