### ISSUE TITLE
Uploading isn't reliable and doesn't indicate failures or (lack of?) progress

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-storage-azcopy#1657]
### Which version of the AzCopy was used?

10.13.0
 
### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

    azcopy.exe copy "myfile.7z" "https://sas" --put-md5 --overwrite=prompt

I'm trying again without the extra switches...

### What problem was encountered?

It sits there, using ~0.5-1 Mbps bandwidth (with bursts) on average. I know it's doing _something_ because my Internet speed slows down noticeably, but the percentage never gets above 0.0 and it never seems to make progress and never finishes.

This is a ~330 MB file. I was able to split it into 33 little 10 MB files, which worked. It took about a minute to upload each of those. However, after an hour or more, the single file upload was still at 0% when it should have been finished:

    0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 0.4451

Typically, the log has lines like this in it every couple seconds, only the bandwidth number changes:

    2022/01/21 15:30:46 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B: 41, E:  0, T: 41, GRs: 128
    2022/01/21 15:30:46 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 1.0471
    2022/01/21 15:30:48 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B: 41, E:  0, T: 41, GRs: 128
    2022/01/21 15:30:48 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 1.1786

I'm not sure if one of those letters is bytes transferred or something which should also change...

I did find some errors in the log for one attempt after about 6 minutes of logs like above:

	2022/01/21 15:56:52 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B: 41, E:  0, T: 41, GRs: 128
	2022/01/21 15:56:52 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 1.3097
	2022/01/21 15:56:52 ==> REQUEST/RESPONSE (Try=1/0s, OpTime=5m46.6728462s) -- REQUEST ERROR
	PUT https://...
	Content-Length: [8388608]
	User-Agent: [AzCopy/10.13.0 Azure-Storage/0.14 (go1.16; Windows_NT)]
	X-Ms-Client-Request-Id: [7dd833fd-f9de-43c2-5300-f7dc2d19f52e]
	X-Ms-Version: [2019-12-12]
	--------------------------------------------------------------------------------
	ERROR:
	-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
	HTTP request failed

	Put "https://...": write tcp 192.168.254.70:56855->20.60.128.132:443: wsasend: An existing connection was forcibly closed by the remote host.

	goroutine 149 [running]:
	github.com/Azure/azure-storage-azcopy/v10/ste.stack(0xc01b304270, 0xc00138ec00, 0x0)
		/home/vsts/work/1/s/ste/xferLogPolicy.go:237 +0xa5
	github.com/Azure/azure-storage-azcopy/v10/ste.NewRequestLogPolicyFactory.func1.1(0x1c11b80, 0xc00047f080, 0xc0003a7200, 0x10, 0x1, 0x0, 0xc0003b5760)
		/home/vsts/work/1/s/ste/xferLogPolicy.go:151 +0x7c5
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000070f50, 0x1c11b80, 0xc00047f080, 0xc0003a7200, 0xc0003b5800, 0x19382c0, 0x4, 0x30000)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-azcopy/v10/ste.NewVersionPolicyFactory.func1.1(0x1c11b80, 0xc00047f080, 0xc0003a7200, 0x2030000, 0x20, 0x1be7270, 0x6)
		/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:83 +0x1c9
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000004f30, 0x1c11b80, 0xc00047f080, 0xc0003a7200, 0xc0003b0f38, 0xf39c06, 0xc0000a2800, 0x74)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0x1c01e00, 0xc000004f30, 0xc00065e840, 0x1c11b80, 0xc00047f080, 0xc0003a7200, 0x279a5613280, 0x10, 0x10, 0x279ffc31348)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zz_generated_responder_policy.go:33 +0x5a
	github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(...)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_credential_anonymous.go:54
	github.com/Azure/azure-storage-azcopy/v10/ste.(*retryNotificationPolicy).Do(0xc001427d40, 0x1c11b80, 0xc00047f080, 0xc0003a7200, 0x0, 0xc00047f090, 0x1af8878, 0xc0003b10b8)
		/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x62
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc001427d50, 0x1c11b80, 0xc00047f080, 0xc0003a7200, 0xc00047f080, 0xc001427e90, 0xc000000001, 0x0)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-azcopy/v10/ste.NewBlobXferRetryPolicyFactory.func1.1(0x1c11b10, 0xc00003e0c0, 0xc0003a7100, 0x10, 0x18ff920, 0x64492d747301, 0xc0003b54a0)
		/home/vsts/work/1/s/ste/xferRetrypolicy.go:384 +0x762
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000070fa0, 0x1c11b10, 0xc00003e0c0, 0xc0003a7100, 0xc0003b5570, 0x20, 0x1be725a, 0xc0003b1448)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0x1c11b10, 0xc00003e0c0, 0xc0003a7100, 0x10, 0x18ff920, 0xeeee01, 0xc0003b54a0)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_policy_unique_request_id.go:22 +0xd4
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000004f60, 0x1c11b10, 0xc00003e0c0, 0xc0003a7100, 0xc0003b5558, 0x36, 0xc00002e480, 0xc0003b1500)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0x1c11b10, 0xc00003e0c0, 0xc0003a7100, 0x1, 0x0, 0x1, 0xc000006080)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_policy_telemetry.go:34 +0x169
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000674270, 0x1c11b10, 0xc00003e0c0, 0xc0003a7100, 0xc000674270, 0x0, 0xc0003b15d0, 0xeeeebf)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc00003e080, 0x1c11b10, 0xc00003e0c0, 0x1c01f00, 0xc00065e840, 0xc0003a7100, 0x23, 0xc00047c0eb, 0x13, 0x0)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:129 +0x88
	github.com/Azure/azure-storage-blob-go/azblob.blockBlobClient.StageBlock(0xc00047c0c0, 0x5, 0x0, 0x0, 0x0, 0xc00047c0c8, 0x23, 0xc00047c0eb, 0x13, 0x0, ...)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zz_generated_block_blob.go:505 +0x525
	github.com/Azure/azure-storage-blob-go/azblob.BlockBlobURL.StageBlock(0xc00047c0c0, 0x5, 0x0, 0x0, 0x0, 0xc00047c0c8, 0x23, 0xc00047c0eb, 0x13, 0x0, ...)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/url_block_blob.go:96 +0x213
	github.com/Azure/azure-storage-azcopy/v10/ste.(*blockBlobUploader).generatePutBlock.func1()
		/home/vsts/work/1/s/ste/sender-blockBlobFromLocal.go:78 +0x3f6
	github.com/Azure/azure-storage-azcopy/v10/ste.createChunkFunc.func1(0x20)
		/home/vsts/work/1/s/ste/sender.go:180 +0x21a
	github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0xc0004461a0, 0x20)
		/home/vsts/work/1/s/ste/JobsAdmin.go:435 +0xdf
	created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
		/home/vsts/work/1/s/ste/JobsAdmin.go:364 +0x67d
	2022/01/21 15:56:54 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B: 41, E:  0, T: 41, GRs: 128
	2022/01/21 15:56:54 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 1.0478

	2022/01/21 15:58:16 ==> REQUEST/RESPONSE (Try=1/0s, OpTime=7m9.9380643s) -- REQUEST ERROR
	PUT https://...
	Content-Length: [8388608]
	User-Agent: [AzCopy/10.13.0 Azure-Storage/0.14 (go1.16; Windows_NT)]
	X-Ms-Client-Request-Id: [08c9ea8f-fd18-41c2-501d-f69acb0de984]
	X-Ms-Version: [2019-12-12]
	--------------------------------------------------------------------------------
	ERROR:
	-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
	HTTP request failed

	Put "https://...": write tcp 192.168.254.70:56826->20.60.128.132:443: wsasend: An existing connection was forcibly closed by the remote host.

	goroutine 156 [running]:
	github.com/Azure/azure-storage-azcopy/v10/ste.stack(0xc01b2e61e0, 0xc001402300, 0x0)
		/home/vsts/work/1/s/ste/xferLogPolicy.go:237 +0xa5
	github.com/Azure/azure-storage-azcopy/v10/ste.NewRequestLogPolicyFactory.func1.1(0x1c11b80, 0xc000706300, 0xc0003a6000, 0x10, 0x0, 0x4b, 0x1af6270)
		/home/vsts/work/1/s/ste/xferLogPolicy.go:151 +0x7c5
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0000705f0, 0x1c11b80, 0xc000706300, 0xc0003a6000, 0xc000109aa8, 0xa215c506422ea6b1, 0xf9410c, 0x30000)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-azcopy/v10/ste.NewVersionPolicyFactory.func1.1(0x1c11b80, 0xc000706300, 0xc0003a6000, 0x2030000, 0x20, 0x1be7270, 0xef5e1b)
		/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:83 +0x1c9
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00046c420, 0x1c11b80, 0xc000706300, 0xc0003a6000, 0xc0006fef38, 0xf39c06, 0xc000470400, 0x2)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0x1c01e00, 0xc00046c420, 0xc00065e210, 0x1c11b80, 0xc000706300, 0xc0003a6000, 0x279ffee2e40, 0x10, 0x10, 0x279ffc317d8)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zz_generated_responder_policy.go:33 +0x5a
	github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(...)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_credential_anonymous.go:54
	github.com/Azure/azure-storage-azcopy/v10/ste.(*retryNotificationPolicy).Do(0xc000142340, 0x1c11b80, 0xc000706300, 0xc0003a6000, 0x0, 0xc000706310, 0x1af8878, 0xc0006ff0b8)
		/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x62
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000142350, 0x1c11b80, 0xc000706300, 0xc0003a6000, 0xc000706300, 0xc000142490, 0xc000000001, 0x0)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-azcopy/v10/ste.NewBlobXferRetryPolicyFactory.func1.1(0x1c11b10, 0xc00003e0c0, 0xc000375f00, 0x10, 0x38, 0x38, 0x1af6270)
		/home/vsts/work/1/s/ste/xferRetrypolicy.go:384 +0x762
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000070640, 0x1c11b10, 0xc00003e0c0, 0xc000375f00, 0xc0001092b0, 0x20, 0x1be725a, 0xc0006ff448)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0x1c11b10, 0xc00003e0c0, 0xc000375f00, 0x10, 0x18ff920, 0x37, 0x1af6270)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_policy_unique_request_id.go:22 +0xd4
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00046c498, 0x1c11b10, 0xc00003e0c0, 0xc000375f00, 0xc000109298, 0x36, 0xc00002e480, 0xc0006ff500)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0x1c11b10, 0xc00003e0c0, 0xc000375f00, 0x1, 0x0, 0x1, 0xc000474090)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_policy_telemetry.go:34 +0x169
	github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000712300, 0x1c11b10, 0xc00003e0c0, 0xc000375f00, 0xc000712300, 0xc0006ff5d0, 0xef5e1b, 0xc00065e218)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
	github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc00003e080, 0x1c11b10, 0xc00003e0c0, 0x1c01f00, 0xc00065e210, 0xc000375f00, 0x23, 0xc00047c0eb, 0x13, 0x0)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:129 +0x88
	github.com/Azure/azure-storage-blob-go/azblob.blockBlobClient.StageBlock(0xc00047c0c0, 0x5, 0x0, 0x0, 0x0, 0xc00047c0c8, 0x23, 0xc00047c0eb, 0x13, 0x0, ...)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zz_generated_block_blob.go:505 +0x525
	github.com/Azure/azure-storage-blob-go/azblob.BlockBlobURL.StageBlock(0xc00047c0c0, 0x5, 0x0, 0x0, 0x0, 0xc00047c0c8, 0x23, 0xc00047c0eb, 0x13, 0x0, ...)
		/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/url_block_blob.go:96 +0x213
	github.com/Azure/azure-storage-azcopy/v10/ste.(*blockBlobUploader).generatePutBlock.func1()
		/home/vsts/work/1/s/ste/sender-blockBlobFromLocal.go:78 +0x3f6
	github.com/Azure/azure-storage-azcopy/v10/ste.createChunkFunc.func1(0x27)
		/home/vsts/work/1/s/ste/sender.go:180 +0x21a
	github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0xc0004461a0, 0x27)
		/home/vsts/work/1/s/ste/JobsAdmin.go:435 +0xdf
	created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
		/home/vsts/work/1/s/ste/JobsAdmin.go:364 +0x67d

	2022/01/21 15:58:16 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B: 41, E:  0, T: 41, GRs: 128
	2022/01/21 15:58:16 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 1.5728

I've also seen `net/http: TLS handshake timeout` errors, along with long stretches of no errors in between. My guess is that it's trying to start over completely, or fill in failed chunks, but there is no indication that this is happening and the percentage just sits at 0.0% the whole time. I find it hard to believe it didn't even get to 0.1% after several minutes, especially when the 10 MB file upload finished after a minute... I also would have expected some sort of indication of a retry if it had to restart or something, even if it went from x% back to 0% instead of a message. I didn't find any CLI switch related to verbosity or showing warnings/errors.

I am able to keep TCP connections open generally in other contexts. Something about this app, blob storage, or the configured timings seems particularly fragile.

### How can we reproduce the problem in the simplest way?

I'm not sure, upload a large file I guess. Maybe throttle your upload speed? I don't know what the root problem is, I suspect it's dropped packets or slow throughput as my DSL is pretty horrible sometimes.

**Comment by josh-endries** [comment]
I just tried uploading while on a VPN, and within the first 30 seconds it had 5 tls timeouts...

**Comment by nakulkar-msft** [comment]
Hi @josh-endries, it appears that the network is flaky and is of low bandwidth. Please use a better n/w.
If you're continuing to use the same n/w, you should use azcopy with a lower concurrency by setting environment variable "AZCOPY_CONCURRENCY_VALUE" to "AUTO".
