### ISSUE TITLE
cannot opt out from version control

### ISSUE THREAD

**Issue by gmassari-88** [Azure/azure-storage-azcopy#166]
##### Note: The version is visible when running AzCopy without any argument
Version is 10.0.4-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2016

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
param(
  [Parameter(Mandatory=$true)][string] $dbname
)

$ErrorActionPreference = "Stop"

$targetPath = "D:"

$containerBasePath =  'NOPE'
$sasToken = 'DOUBLE-NOPE'

$containerPath = $containerBasePath+$sasToken

$blobs = D:\AzCopy\AzCopy.exe list $containerPath
if (!$blobs) { throw "No backups found at all." }

$last = $blobs | select-string "$dbname`_" | sort -Descending | select -First 1
if (!$last) { throw "No latest backup found." }
$last

$srcPath = $containerBasePath+$last+$sasToken

set AZCOPY_CONCURRENCY_VALUE=10
D:\AzCopy\AzCopy.exe cp "$srcPath" "$targetPath" --overwrite --output=json > $null

### What problem was encountered?
Always returns error on version 10.0.4-Preview after version 10.0.5-Preview was released. Version update should be done manually by sysadmins and there should be an opt-out settings (maybe configured by azcopy env)

### How can we reproduce the problem in the simplest way?
just copy something from an azure blob storage with a version previous to the latest preview.

### Have you found a mitigation/solution?
Apart from updating azcopy version, no mitigation/solution is available. There is no documented opt out mechanism.

**Comment by zezha-msft** [comment]
Hi @gmassari-88, thanks for reaching out!

I'm a bit confused by what you meant by "returns error". Did you mean the output on stderr? Like this

> azcopy: A newer version 10.0.5-preview is available to download

**Comment by iclanton** [comment]
Yes, it appears to output on sdterr. It causes CI pipelines to fail as soon as a new version is released.

There perhaps could be a "--no-update-check" option that suppresses this behavior.

**Comment by zezha-msft** [comment]
Hi @iclanton, thanks for the explanation!

Is there no way to prevent your CI pipelines from failing when it sees output on stderr? Could you redirect it?

**Comment by gmassari-88** [comment]
Actually, no. The copy job itself fails silently (status: failed) after reporting that line to stderr. So, yeah, as stated before, it would be nice to have a --no-update-check switch that suppresses this behavior

**Comment by zezha-msft** [comment]
Hi @gmassari-88, the failed job is probably not caused by reporting that line to stderr, please provide us the log file if possible.

**Comment by zezha-msft** [comment]
Hi @gmassari-88, I've fixed this issue in 10.0.8, please give it try! Thanks for your patience!
