### ISSUE TITLE
Support migrating S3 legacy buckets with non DNS-compliant names to Azure

### ISSUE THREAD

**Issue by walterstypula** [Azure/azure-storage-azcopy#1660]
### Which version of the AzCopy was used?  
10.13.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy.exe cp "https://s3.us-east-1.amazonaws.com/BUCKETname/" "https://storageaccount.blob.core.windows.net/<containername>?<SAS>" --recursive=true 

### What problem was encountered?
S3 bucket names are case-sensitive. BUCKETname, bucketname, and BUCKETNAME are all different in the eyes of s3. Behind the scenes AzCopy appears to be making the S3 bucket lower case when attempting to copy from S3 to Azure Blob Storage.

### How can we reproduce the problem in the simplest way?
1) Create two s3 buckets with the same name, one using all upper case characters and the other one all lower case characters.
2) Upload two different files to the root of each bucket. Such as textfile1.txt and textfile2.txt
3) Run AzCopy to migrate files from a s3 bucket to azure blob storage. Use the UPPERCASE bucket as the source. When the command executes, it will copy the file from the lower case bucketname.

### Have you found a mitigation/solution?
No, it requires a code change in azcopy not to lowercase the source bucket name.

**Comment by walterstypula** [comment]
Yes, I understand that the standard for bucketname is now -> "The bucket name can be between 3 and 63 characters long, and can contain only lower-case characters, numbers, periods, and dashes."

However, we have a number of buckets that are mixed case.

**Comment by walterstypula** [comment]
I did a bit of debugging here to see what the actual awssdk is doing when generating a presigned url. Turns out the issue is that AzCopy treats all s3 bucket names to be subdomain compatible, which is case insensitive. This is what lead me to believe that the bucketname was being lowercased using my steps to reproduce. Az copy simply takes the bucketname from the path and converts it into a subdomain of s3.amazon.com

When legacy s3buckets are used, the bucketname needs to remain in the path of the url. I ended up writing a C# tool that basically does s3 to azure blob storage migrations. I'll post it up to my github in a few days.

**Comment by nakulkar-msft** [comment]
Hi @walterstypula, 
Azure blob containers can be named only with lower case letters. Please check the naming convention [here](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names)

**Comment by walterstypula** [comment]
@nakulkar-msft this issue was incorrectly closed.
 
The root cause is not the target azure blob storage container name needing to be lower case. This is expected.

The problem is how Azcopy generates a s3 presigned url. There is missing logic to handle upper case characters in s3 bucket names. Legacy s3 buckets do support both upper and lower case characters.

Currently, Azcopy cannot copy files from a legacy s3 bucketname (with mixed case characters) to ANY valid container in azure blob storage.  Even if that target container name is all lower case characters.

**Comment by nakulkar-msft** [comment]
reopening for investigation

**Comment by nakulkar-msft** [comment]
Please upgrade to newer DNS compliant buckets before migrating

**Comment by walterstypula** [comment]
@nakulkar-msft just so I understand the recommended solution incase others run into the same issue:
1) Create a new AWS s3 bucket (dns compliant)
2) Migrate terabytes of data
3) Verify all files successfully migrated
4) Repeat this with all 50 affected AWS s3 buckets
5) Use AZCopy to migrate the data from new s3 buckets to azure blob storage
6) Verify all files successfully migrated

I ended up modifying azcopy code for my needs and added support for legacy buckets names. It wasn't pretty hack job but it worked.

**Comment by pola** [comment]
> I ended up modifying azcopy code for my needs and added support for legacy buckets names. It wasn't a pretty hack job but it worked.
@walterstypula, can you share the modifications you made to Azcopy to support legacy S3 bucket names?
