### ISSUE TITLE
copy blob from archive tier fails

### ISSUE THREAD

**Issue by Rsimk** [Azure/azure-storage-azcopy#1663]
### Which version of the AzCopy was used? 
10.13.0

### Which platform are you using? 
Tested on Linux and Windows

### What command did you run?
azcopy copy "https://stbackuptest1.blob.core.windows.net/backup/[SAS token removed]" "https://stbackuptest1.blob.core.windows.net/restore/[SAS token removed]" --block-blob-tier=Hot --recursive

### What problem was encountered?
COPYFAILED:  "409 Copy source blob has been modified.. When Put Blob from URL"
Storage account access log shows:
![image](https://user-images.githubusercontent.com/56922442/152110088-61b00976-2248-4005-9020-cbb025bfac8f.png)

I tested it on Windows with Fidlder running. Request header had x-ms-access-tier set to Hot.

### How can we reproduce the problem in the simplest way?
1. create three blobs in one container, set tier archive on all.
2. copy that container to another container in the same storage account with target tier hot and recursive parameter

### Have you found a mitigation/solution?
No.

**Comment by Rsimk** [comment]
BTW, copying same single blob with "az storage blob copy start" with storage account key works.

**Comment by nakulkar-msft** [comment]
Hi @Rsimk, archived blobs have to be rehydrated (i.e. moved to hot or cool tier) before accessing them. Do retry the operation after moving the blobs to hot tier.

**Comment by AnimMouse** [comment]
@nakulkar-msft According to this document [Rehydrate an archived blob to an online tier](https://docs.microsoft.com/en-us/azure/storage/blobs/archive-rehydrate-to-online-tier), it should be possible to copy archived blobs without rehydrating it first, in fact we use copy operation instead of changing its tier to avoid early deletion fee.

This bug also affects me, I can't copy archived blobs using azcopy.

**Comment by Miclaud** [comment]
@AnimMouse I have the same problem here, even if using MS Azure StorageExplorer tool

Did you find any solution? According to the document you linked it should be possible

**Comment by AnimMouse** [comment]
@Miclaud Yes, you can use Azure CLI or REST API to copy archived blobs without rehydrating it first, it is sad that AzCopy does not implement this option.

**Comment by AnimMouse** [comment]
@Miclaud Yes, you can use Azure CLI or REST API to copy archived blobs without rehydrating it first.
