### ISSUE TITLE
Problems with Directory and file component names with more than 255 characters in length

### ISSUE THREAD

**Issue by Sameeraj85** [Azure/azure-storage-azcopy#1665]
##### Note: The version is visible when running AzCopy without any argument

It is not problem of AzCopy version, we have AzCopy 10.13.0 version, we are doing a lot of test from two weeks ago, please, elaborate a little more the answer…

 

From the next URL:

 

https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata

 

We need you to answer the following questions:

 

	
Regarding to 255 characters in the files name length, would you mind to verify this information and say me if Microsoft has ETA ( (Estimated Time of Arrival) to remove this limitation in a future?

 

	
New architectures of Windows Servers have removed this old limitation of the 32 bits architectures... Why do storage accounts enforce that now?

It was mentioned on notes that it may not be a Storage issue : 

 

 

 
Please help on how to proceed. 

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What problem was encountered?

More than 255 characters issue

### Have you found a mitigation/solution?

No

**Comment by siminsavani-msft** [comment]
Hi @Sameeraj85 ! Please take a look at this documentation regarding character length and limitations: https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names

I hope this help! :)
