### ISSUE TITLE
Tags lost when copying blobs

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-storage-azcopy#1670]
### Which version of the AzCopy was used? 
v10

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?

Command used documented [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs-copy#copy-a-container)

### What problem was encountered?
Tags were stripped from the blobs in the destination.

### How can we reproduce the problem in the simplest way?
Run the command on a blob with blob index tags.

### Have you found a mitigation/solution?
No.

**Comment by mohsha-msft** [comment]
Hey @SeanFeldman ,

We don't preserve tags by default. You can use `s2s-preserve-blob-tags` to copy tags.
[How to use blob index tag feature in AzCopy](https://github.com/Azure/azure-storage-azcopy/wiki/How-to-use-blob-index-tag-feature-in-AzCopy#preserve-blob-tags-from-the-source-through-azcopy)

**Comment by mohsha-msft** [comment]
Please reopen this issue if even after using `s2s-preserve-blob-tags` is not transferring tags properly..
