### ISSUE TITLE
azcopy some folders cannot copy ACL with it

### ISSUE THREAD

**Issue by gina2537** [Azure/azure-storage-azcopy#1672]
### Which version of the AzCopy was used? 
v10
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
.\azcopy.exe copy "local path" "azure storage acc file share" --recursive --preserve-smb-permissions=true --preserve-smb-info=true
### What problem was encountered?
mount my azure file share and found some folders did not copy ACL with it.
(files can be successfully copied with no error)

### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
Hi @gina2537, can you post the log file for this transfer? It would help us if you could post a couple of paths where the ACL has not been transferred.

**Comment by gina2537** [comment]
Hi @nakulkar-msft ,

I've found that azcopy doesn't support full fidelity.
https://docs.microsoft.com/en-us/azure/storage/files/storage-files-migration-overview#migration-toolbox
![image](https://user-images.githubusercontent.com/99727492/154904651-898edd88-e6c8-45ae-8e2a-e4c7bdd3112d.png)

I think that might be the reason why sometimes ACL cannot copy along.
I'm now wondering when will azcopy be able to support full fidelity.

Thanks!

**Comment by adreed-msft** [comment]
Hi, @gina2537.

Azure Files does not enforce ACLs-- My understanding is that the ACL support is designed to be used as a backup of your ACLs.

Secondarily, AzCopy (until next version) may end up merging ACEs that overlap in some way to their effective ACE-- For instance, if you had an ACE that was full privileges and an ACE that removed write privileges, they'd be merged potentially.

**Comment by gina2537** [comment]
Hi,

Are there any target date on when will the next version of AzCopy that will support entirely copying ACL along to Azure File Share?
Also, I still didn't get why azcopy sync isn't able to copy along but azcopy copy seems to be success in this scenario.

Thanks!

**Comment by gina2537** [comment]
@mohsha-msft could you help to remove the label since I cannot get any reply?

**Comment by gina2537** [comment]
> Hi @gina2537, can you post the log file for this transfer? It would help us if you could post a couple of paths where the ACL has not been transferred.

I've found that azcopy doesn't support full fidelity.
I think that might be the reason why sometimes ACL cannot copy along.
Also, I've found that azcopy sync will have this issue, yet azcopy copy can copy ACL along.

I'm now wondering when will azcopy be able to support full fidelity.

**Comment by adreed-msft** [comment]
Apologies for the slow response.

> Are there any target date on when will the next version of AzCopy that will support entirely copying ACL along to Azure File Share?
v10.14.0 was released 17 days ago.
> Also, I still didn't get why azcopy sync isn't able to copy along but azcopy copy seems to be success in this scenario.
In what way does sync fail?

>nakulkar-msft added feature request and removed waiting for customer
I'm not sure this is a feature request.

**Comment by gapra-msft** [comment]
Hi @gina2537 was v10.14.0 able to resolve your issue?

**Comment by gina2537** [comment]
Yes, thank you!

Gauri Prasad ***@***.***>於 2022年12月10日 週六，上午2:33寫道：
