### ISSUE TITLE
Copy fails (CannotVerifyCopySource) when storage account firewall is enabled

### ISSUE THREAD

**Issue by vijred** [Azure/azure-storage-azcopy#1673]
Using azcopy 10.13.0 (Windows), with a storage account firewall enabled on the source and destination, copy between containers fails with CannotVerifyCopySource.

Sample command 
```
azcopy cp "https://mysourceaccount.blob.core.windows.net/project/path/file.csv?sp=r&st=2022-02-15T15:59:11Z&se=2022-02-15T23:59:11Z&spr=https&sv=2020-08-04&sr=b&sig=asdfsafasdf%34ddfdsfas%sadf%af%3D" "https://mydestinationaccount.blob.core.windows.net/container/path/filename.csv?sp=rw&st=2022-02-15T17:32:00Z&se=2022-02-16T01:32:00Z&sv=2020-08-04&sr=c&sig=asdfsadfdsafdsf%afsdsaf%3D"
```

Sample Error -
```
RequestId:ceac92c2-f01e-0065-1a5b-23c0e2000002
Time:2022-02-16T17:34:46.1621358Z, Details:
   Code: CannotVerifyCopySource
   PUT https://destinationstorageaccoun.blob.core.windows.net/project/path/file.csv?se=2022-02-17t01%3A32%3A00z&sig=-REDACTED-&sp=rw&sr=c&st=2022-02-16t17%3A32%3A00z&sv=2020-08-04&timeout=901
   Content-Length: [0]
   User-Agent: [AzCopy/10.13.0 Azure-Storage/0.14 (go1.16; Windows_NT)]
   X-Ms-Access-Tier: [Hot]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Type: [application/vnd.ms-excel]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [c2f412be-17f1-4415-659f-eeeaa88f1127]
   X-Ms-Copy-Source: [https://sourcestorageaccount.blob.core.windows.net/project/path/file.csv?se=2022-02-16t23%3A59%3A11z&sig=-REDACTED-&sp=r&spr=https&sr=b&st=2022-02-16t15%3A59%3A11z&sv=2020-08-04]
   X-Ms-Version: [2020-08-04]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [248]
   Content-Type: [application/xml]
   Date: [Wed, 16 Feb 2022 17:34:45 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [c2f412be-17f1-4415-659f-eeeaa88f1127]
   X-Ms-Error-Code: [CannotVerifyCopySource]
   X-Ms-Request-Id: [ceac92c2-f01e-0065-1a5b-23c0e2000000]
   X-Ms-Version: [2020-08-04]
```

Problem can be replicated by attempting a copy between shares on different storage accounts which both have a storage account firewall configured.

Disabling the storage account firewall on both the source and destination works.
The same problem is reported and closed @ https://github.com/Azure/azure-storage-azcopy/issues/755

**Comment by nakulkar-msft** [comment]
@vijred you need to add vm or machine where AzCopy runs to allowlist on both source and destination storage accounts. Further the source storage account must be reachable from destination account.

**Comment by snird** [comment]
That means absolutely nothing. @nakulkar-msft 

![image](https://user-images.githubusercontent.com/2139589/167394792-a376b38c-409a-425c-9df7-1688761f5c61.png)

The networking config for a storage account has no connection for VMs or allowed IPs.
How come this thing is not well documented? This is Azure! paid for with hundred thousand dollars a month by the average customer. not some unsupported open source project.

**Comment by Ismail-Ham** [comment]
Same question, it should not be closed, does the azcopy copies data from destination instead of using the local machine ?

**Comment by siminsavani-msft** [comment]
Hi all! This issue is not something AzCopy can fix or handle. The destination cannot read the source in this scenario. The best solution is to whitelist IPs. Please view this documentation for additional information: https://github.com/Azure/azure-storage-azcopy/wiki/Troubleshooting---FAQ#firewallprivate-endpoint-issues

**Comment by hari-metacube** [comment]
i am still getting same issue 

RESPONSE 403: 403 This request is not authorized to perform this operation.
ERROR CODE: CannotVerifyCopySource
--------------------------------------------------------------------------------
���<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>This request is not authorized to perform this operation.
RequestId:6e52845f-a01a-005a-413b-381a35000000
Time:2025-10-08T10:07:21.5169355Z</Message></Error>
