### ISSUE TITLE
Bug: AzCopy sync scans destination despite not enabling --delete-destination 

### ISSUE THREAD

**Issue by lmeyerov** [Azure/azure-storage-azcopy#1675]
### Which version of the AzCopy was used? 

`10.13.0`

### Which platform are you using? (ex: Windows, Mac, Linux)

Ubuntu

### What command did you run?

```
sudo ./azcopy_linux_amd64_10.13.0/azcopy sync /***/migration/data 'https://***.blob.core.windows.net/***/data?st=***&se=***&sp=racwdl&sv=***&sr=c&sig=***' --exclude-path=sessions --recursive=true --put-md5
```

### What problem was encountered?

10X more files were scanned the destination than at the source. This is slow and unexpected as we did not set `--delete-destination`:

```
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 45ff7704-b6e7-1a48-5ff1-*** has started
Log file is located at: /home/***/.azcopy/45ff7704-b6e7-1a48-5ff1-***.log

22830 Files Scanned at Source, 241072 Files Scanned at Destination

Job 45ff7704-b6e7-1a48-5ff1-*** Summary
Files Scanned at Source: 22830
Files Scanned at Destination: 243617
Elapsed Time (Minutes): 3.654
```

Our dest folder structure looks something like

```
grandparent/parent/{childA,childB}/{file1,,file2,file3}
```

Maybe the issue is nesting?

### How can we reproduce the problem in the simplest way?

Presumably, make a folder structure like the above and run

### Have you found a mitigation/solution?

No

**Comment by nakulkar-msft** [comment]
@lmeyerov , this is the expected behaviour. Sync uses a map of files at source and destination to generate a list of files which should be transferred. However, we're making improvements to reduce the memory footprint and scanning. 
Let us know if you've more questions.

**Comment by lmeyerov** [comment]
Thanks, though I'm not sure if this was understood. A local->server upload sync (no deletes) can build a map of only paths in the source, so the use of a mapping isn't the issue. The problem is the destination is scanned, which doesn't scale for something like syncing uploads to a generic file server if you have to scan the entire file server :)
