### ISSUE TITLE
Possibility to error on zero-item copy

### ISSUE THREAD

**Issue by EvertEt** [Azure/azure-storage-azcopy#1676]
##### Note: The version is visible when running AzCopy without any argument
10.13.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

any `azcopy copy` command

### What problem was encountered?

Before 10.5.0, changelog:
> Stop treating zero-item job as failure, to improve the user experience.
a copy would error when nothing was transferred which is behaviour we were expecting.

Is there a way to replicate this behaviour with the latest azcopy version?
We are running azcopy from subprocess in python but would like to keep live logs to stdout so capturing all logs to check some text would not be optimal.
Could a flag be introduced for this?

Many thanks

**Comment by nakulkar-msft** [comment]
Hi @EverEt, we're sorry you're facing difficulty with results. This change was made after a careful discussion. Not having any files to transfer is not an error. Also, introducing too many flags impacts usability of the product.

In case it helps, you can run 'azcopy jobs show -jobID <>' which will print only the status of that job, which could be parsed easily. Let us know if you need more help.

**Comment by nakulkar-msft** [comment]
The job id is thrown on the stdout just after job started, and also right before the job summary is displayed in a statements similar to this. We'll be soon adding a way to provide ID upfront.
`Job c3de3c3c-66dc-6a4b-604c-74aec72c4a8a has started`
`Job c3de3c3c-66dc-6a4b-604c-74aec72c4a8a summary`

**Comment by EvertEt** [comment]
Extracting the id from the logs would require parsing the logs again, in which case we could just parse the summary right?
Sadly, parsing the stdout while keeping the normal output behaviour is not easy in our case. Any suggestions would be welcome.
