### ISSUE TITLE
Issue Trying to Copy AZ File Share content between Storage Accounts

### ISSUE THREAD

**Issue by scottydztcg** [Azure/azure-storage-azcopy#1687]
### Which version of the AzCopy was used? 
AzCopy 10.13.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy login --tenant-id=xxx-xxx-xxx-xxx

azcopy copy  "\\xxxxxxxP01.file.core.windows.net\ocon" "\\xxxxxxxSTD01.file.core.windows.net\ocon" -File --recursive

### What problem was encountered?
PS C:\Windows\system32> azcopy copy  "\\tcgazfilesp01.file.core.windows.net\ocon" "\\tcgazfilestd01.file.core.windows.net\ocon" -File --recursive
azcopy : Error: unknown shorthand flag: 'F' in -File

### How can we reproduce the problem in the simplest way?
???
### Have you found a mitigation/solution?
no

**Comment by nakulkar-msft** [comment]
Hi @scottydztcg, AzCopy does not have any parameter/flag named -File. What is your expectation here?

**Comment by scottydztcg** [comment]
Hello there,

Thanks for the reply.

I was using a script for AZ copy that I had found here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs-copy to try and copy files between two different storage accounts

Cheers,

Scotty de Zoete | Infrastructure Solution Architect
Mob:                                                     +64 21 760 992
Business Hours:          M-F    06:30 - 14:30 UTC +13

***@***.***
Please consider the environment before printing this email

New Zealand Comfort  Group

**Comment by nakulkar-msft** [comment]
@scottydztcg, the doc is up-to-date and there is no flag with name "File". To copy files between two fileshares, use the below command.
`azcopy copy "https://acc1.file.core.windows.net/<share>[SAS]" "https://acc2.file.core.windows.net/<share>[SAS]" --recursive"`

Filestore does not support OAuth, and you'll have to use SAS on both source and destination. Let us know if you need more help.
