### ISSUE TITLE
Azcopy ignores Flag  --log-level=NONE

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-storage-azcopy#1689]
### Which version of the AzCopy was used? 
```
PS C:\Users\admin\Desktop> azcopy
AzCopy 10.3.0
```
### Which platform are you using? (ex: Windows, Mac, Linux)
```
PS C:\Users\admin\Desktop> Get-ComputerInfo
OsName                                                  : Microsoft Windows Server 2022 Datacenter
OsType                                                  : WINNT
OsOperatingSystemSKU                                    : DatacenterServerEdition
OsVersion                                               : 10.0.20348
```
### What command did you run?
When I disable the Logging of `azcopy`, I still get the Info that a Log file is created. Bug or Feature?

`PS > azcopy.exe sync "d:\source" $sasDest --recursive --log-level=NONE`

```
Job 369181ca-67c8-a644-7460-bd500648a5a0 has started
Log file is located at: C:\Users\admin\.azcopy\369181ca-67c8-a644-7460-bd500648a5a0.log
```

`4034607 Files Scanned at Source, 0 Files Scanned at Destination`

**Comment by nakulkar-msft** [comment]
Hi @Gill-Bates, a few statements like the job command and summary still be logged at level NONE. This is a conscious decision made. To clean the log files you can use `azcopy jobs clean -with-status=Completed`. Let us know if you've more questions.
