### ISSUE TITLE
Signed Directory Depth Invalid

### ISSUE THREAD

**Issue by iorparask** [Azure/azure-storage-azcopy#1692]
### Which version of the AzCopy was used? 
10.14.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
./azcopy copy "https://xxx.blob.core.windows.net/centralhubprodfs/dir1/dir2/dir3/dir4?sp=rle&st=2022-03-03T07:00:35Z&se=2022-03-03T15:00:35Z&spr=https&sv=2020-08-04&sr=d&sig=***&sdd=4" "https://yyy.blob.core.windows.net/centralhubprodfs/dir1/dir2/dir3?sp=rwe&st=2022-03-03T07:01:30Z&se=2022-03-03T15:01:30Z&skoid=***&sktid=***&skt=2022-03-03T07:01:30Z&ske=2022-03-03T15:01:30Z&sks=b&skv=2020-08-04&spr=https&sv=2020-08-04&sr=d&sig=***&sdd=3" --recursive --s2s-detect-source-changed

### What problem was encountered?
Transfer begins and proceeds up to a certain percentage (different each time). After that point it auto-cancels.
In the log I see the following message right at the start, although it is not shown at the command prompt:

===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:26fa859e-801e-003c-75ce-2e938d000000
Time:2022-03-03T07:16:41.3683250Z, Details: 
   AuthenticationErrorDetail: Signed Directory Depth Invalid
   Code: AuthenticationFailed
   PUT https://xxx.blob.core.windows.net/centralhubprodfs?restype=container&sdd=3&se=2022-03-03t15%3A01%3A30z&sig=-REDACTED-&ske=2022-03-03t15%3A01%3A30z&skoid=***&sks=b&skt=2022-03-03t07%3A01%3A30z&sktid=***&skv=2020-08-04&sp=rwe&spr=https&sr=d&st=2022-03-03t07%3A01%3A30z&sv=2020-08-04&timeout=180
   User-Agent: [AzCopy/10.14.0 Azure-Storage/0.14 (go1.16.14; Windows_NT)]
   X-Ms-Client-Request-Id: [ae493bd7-9e97-46d4-7853-a9500066ee7e]
   X-Ms-Version: [2020-04-08]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [405]
   Content-Type: [application/xml]
   Date: [Thu, 03 Mar 2022 07:16:41 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [26fa859e-801e-003c-75ce-2e938d000000]

Command prompt shows:
Final Job Status: Cancelled

### How can we reproduce the problem in the simplest way?
Copy folder and subfolders from one container with Premium Data Lake account to another with Simple Gen2 account using SAS keys (as generated from Azure portal).

### Have you found a mitigation/solution?
Using Data Factory seems to work properly but is much slower - didn't test it to the end because of that.

**Comment by siminsavani-msft** [comment]
Hi @iorparask ! Could you please try running your command with --log-level=DEBUG and share the logs with us?

**Comment by siminsavani-msft** [comment]
Hi @iorparask ! This is a known issue with Azure Service and we have notified them of this issue. Thank you for bring this issue to our attention. As a workaround, I would recommend using account SAS for now.
