### ISSUE TITLE
Azcopy sync File Creation Error cannot simultaneously send two files

### ISSUE THREAD

**Issue by prohand** [Azure/azure-storage-azcopy#1693]
Which version of the AzCopy was used?
V10.13.0

Which platform are you using? (ex: Windows, Mac, Linux)
Windows

What command did you run?
$BackupShareNas =  "Y:\BKPAZURE\BLOBS\"
$copysource = "https://xxxxx.blob.core.windows.net"
$clessassource = "xxxxx"

$containerToBackup = @('test','test2')
foreach($container in $containerToBackup)
{
    $source = -join($copysource,'/',$container,$clessassource)
    $destination = -join($BackupShareNas,'\',$container)
    .\AzCopy.exe sync  $source $destination --delete-destination=true --log-level ERROR
}
What problem was encountered?
Error : File Creation Error cannot simultaneously send two files to same destination name
The source file can't be copied in the destination.
The problem is random
The error is : 

```
2022/03/03 17:40:46 AzcopyVersion  10.13.0
2022/03/03 17:40:46 OS-Environment  windows
2022/03/03 17:40:46 OS-Architecture  amd64
2022/03/03 17:40:46 Log times are in UTC. Local time is 3 Mar 2022 18:40:46
2022/03/03 17:40:46 Job-Command sync https://xxxxx.blob.core.windows.net/xxxx?se=xxxxx&sig=signature Y:\BKPAZURE\BLOBS\xxxxx\xxx --delete-destination=true --log-level ERROR 
2022/03/03 17:41:11 ERR: [P#1-T#6599] DOWNLOADFAILED: https://xxxxx.blob.core.windows.net/xxxxx/Templates/Devis_XX_fragment/v3.3.1/Devis_XX_fragment_v3.3.1.mrt?se=xxxx&sig=xxxxx : 412 : 412 The condition specified using HTTP conditional header(s) is not met.. When Downloading response body. X-Ms-Request-Id: b500a548-501e-0036-7425-2fa62d000000
```

   Dst: \\?\Y:\BKPAZURE\BLOBS\xxxxx\xxxx\Templates\Devis_XX_fragment\v3.3.1\Devis_XX_fragment_v3.3.1.mrt

How can we reproduce the problem in the simplest way?
Have you found a mitigation/solution?
No

Thank you for you're help

This issue is next of ticket : https://github.com/Azure/azure-storage-azcopy/issues/1647

**Comment by zezha-msft** [comment]
Hi @prohand, thanks for reaching out.

The title and the problem description seems to be incoherent. If you are still concerned about #1647, I've provided an explanation there.

For the following failure:
2022/03/03 17:41:11 ERR: [P#1-T#6599] DOWNLOADFAILED: https://xxxxx.blob.core.windows.net/xxxxx/Templates/Devis_XX_fragment/v3.3.1/Devis_XX_fragment_v3.3.1.mrt?se=xxxx&sig=xxxxx : 412 : 412 The condition specified using HTTP conditional header(s) is not met.. When Downloading response body. X-Ms-Request-Id: b500a548-501e-0036-7425-2fa62d000000

It means that your blob was being edited as download was going on. In other words, while downloading is happening and some part of the data was already downloaded, the blob changed, and there is no way to know whether the part that was already downloaded is still good or not. Thus, the transfer is failed.

**Comment by zezha-msft** [comment]
The 412 condition failed error is because AzCopy locks onto the Last-Modified Time of the blob. So if the blob changes after the download starts, the service would give back a 412 error, and AzCopy knows that it should fail the transfer to avoid data corruption. 

Please retry the failed transfers once the blob is not being actively modified.

**Comment by prohand** [comment]
Ok thank you ;)
