### ISSUE TITLE
--include does not only include these files when copying

### ISSUE THREAD

**Issue by JSPieterse** [Azure/azure-storage-azcopy#170]
### Which version of the AzCopy was used?  
10.0.5

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy sync  "SourceDir" "https://blobstoragesite/etc"--recursive=true --force=true --include *.png;*.bmp 

### What problem was encountered?
--include does not only copy the specified extension but all other files too.

### How can we reproduce the problem in the simplest way?
Sync a directory to a blob storage with --recursive=true --force=true --include *.png;*.bmp  
Add other files to the source directory that have different extension and run a sync. the other files will sync through to the storage despite what is stated in the help:
azcopy sync -h
--include string      Filter: only include these files when copying. Support use of *. More than one file are separated by ';'

### Have you found a mitigation/solution?
Find every other extension of files in the folders and add a --exclusion list

**Comment by JSPieterse** [comment]
-include *.png;*.bmp
The * before the extension did not show when submitting the issue but was used.

**Comment by zezha-msft** [comment]
Hi @JSPieterse, thanks for reaching out!

I'll try to reproduce this problem and get back to you.

**Comment by Lazymindz** [comment]
@zezha-msft Issue occurs on azcopy version 10.0.7-Preview (Windows) as well

**Comment by zezha-msft** [comment]
Hi @Lazymindz, thanks for reaching out! I'm working on the fix.

**Comment by zezha-msft** [comment]
@JSPieterse sorry for the inconvenience, and I really appreciate your patience!

I've rewritten the sync command and released it in 10.0.8. This issue should be fixed. Please let us know if you still encounter any problem.

Here is a [wiki](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide) explaining how the new sync command works. Please feel free to reach out if you have any question or concern.
