### ISSUE TITLE
Copy file from Sharepoint Online to Azure Blob

### ISSUE THREAD

**Issue by thiagocoliver** [Azure/azure-storage-azcopy#1702]
### Which version of the AzCopy was used? 

10.14.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

I used "azcopy login" and then ran:
AzCopy copy "\\\TENANT-NAME.sharepoint.com@SSL\sites\SITE-NAME\LIBRARY-NAME\FILE-NAME.PST" "SAS KEY"
AzCopy copy "\\\TENANT-NAME.sharepoint.com@SSL\DavWWWRoot\sites\SITE-NAME\LIBRARY-NAME\FILE-NAME.PST" "SAS KEY"
AzCopy copy "https:// TENANT-NAME.sharepoint.com/sites/SITE-NAME/\LIBRARY-NAME/FILE-NAME.PST" "SAS KEY"

I also tried map the sharepoint site with: New-PsDrive -Name S -PSProvider Sharepoint -Root "\\TENANT-NAME.sharepoint.com@SSL\sites\SITE-NAME\LIBRARY-NAME"

And then tried:
AzCopy copy "S:/sites/SITE-NAME/LIBRARY-NAME/FILE-NAME.PST" "SAS KEY"
AzCopy copy "S:\sites\SITE-NAME\LIBRARY-NAME\FILE-NAME.PST" "SAS KEY"

### What problem was encountered?

In all commands above I got the error:
**failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\?\UNC\URL**
OR
**failed to perform copy command due to error: cannot start job due to error: cannot scan the path \\?\S:\URL**

### How can we reproduce the problem in the simplest way?

Try copy any sharepoint file to azure blob storage

### Have you found a mitigation/solution?

Not yet

**Comment by mohsha-msft** [comment]
Hey @thiagocoliver , 

Thanks for reaching out!
AzCopy doesn't support your use-case at the moment. We have had similar asks in the past and we're tracking it internally.
Please see [this](https://github.com/Azure/azure-storage-azcopy#supported-operations) for more information on what resources we support.

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/596

**Comment by thiagocoliver** [comment]
@mohsha-msft thanks for the support!

I hope this fixed. Would be very useful! :)
