### ISSUE TITLE
AzCopy Sync and --check-length flag

### ISSUE THREAD

**Issue by supermistag** [Azure/azure-storage-azcopy#1704]
##### Note: The version is visible when running AzCopy without any argument
10.14.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
2022/03/11 11:41:38 Job-Command sync D:\xxxx\ https://xxxx.blob.core.windows.net/nodesync/yyyyy/xxxx/?se=2022-04-07t12%3A00%3A00z&sig=-REDACTED-&sp=racwdl&spr=https&sr=c&st=2022-03-07t12%3A00%3A00z&sv=2020-08-04 --recursive=true --delete-destination=true --check-length=false --cap-mbps 500 

### What problem was encountered?
I was reviewing the documentation at https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize and it recommended I added --check-length flag, as I have a large number of small files. The command failed with

unknown flag: --check-length

After reviewing other docs, it appears that --check-length is not available for the sync command.

Is there a reason why it is not available for sync command?
If not, can it be added?

### How can we reproduce the problem in the simplest way?
Attempt to use --check-length on azcopy sync

### Have you found a mitigation/solution?
I reviewed the code briefly and added the --check-length equivalent code from copy.go to sync.go. 

Appeared to work fine, just not 100% sure why it isn't available for sync.

Perhaps to check remote file size during sync compare?

**Comment by mohsha-msft** [comment]
Hey @supermistag ,

We have destination length validation check enabled by default in `azcopy sync` command. So, you don't need `--check-length` check. You can check [this code](https://github.com/Azure/azure-storage-azcopy/blob/fc4b103e4ed8ecf2ac3bcf5febdf330354e1ae46/cmd/syncProcessor.go#L62) for your reference.

**Comment by supermistag** [comment]
It recommends turning it off.

So, how do I turn it off?

**Comment by mohsha-msft** [comment]
I have added PR to expose it to customers.

**Comment by maxnasonov** [comment]
@mohsha-msft The PR was closed silently. What was the reason?
