### ISSUE TITLE
Chunk Upload Failed - Big File

### ISSUE THREAD

**Issue by matheus-santoro** [Azure/azure-storage-azcopy#171]
### Which version of the AzCopy was used? 
AzCopy/10.0.4-Preview Azure-Storage

### Which platform are you using? (ex: Windows, Mac, Linux)
SUSE 11 SP4

### What command did you run?

./azcopy cp /my/origin/folder/* https://myaccount.blob.core.windows.net/mycontainer?SASL-HERE --recursive=true 

### What problem was encountered?
When Uploading a big file > 898G, the log displays an error message like:

_Chunk Upload Failed -> github.com/Azure/azure-storage-azcopy/ste.newAzcopyHTTPClientFactory.func1.1, /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:97_

### How can we reproduce the problem in the simplest way?
Try to upload a 898GB file.

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @matheus-santoro, thanks for reaching out!

Could you please share the log file with us? There should be some other error message that could provide more information on why the chunk failed to upload. We scrub the SAS signatures from the logs so you don't have to worry about credentials leaking out.

Btw there's a [newer version](https://aka.ms/downloadazcopy-v10-linux) available if you'd like to try it out.

**Comment by zezha-msft** [comment]
Hi @matheus-santoro, thanks for much for providing the log file!

I see a bunch of unexpected EOF errors. How often does this happen for you? Could you also reproduce this problem with the latest version? On what kind of environment are you running AzCOpy from?

**Comment by zezha-msft** [comment]
Hi @matheus-santoro, it'd be great if you could repro this problem and provide the log file again, so that I can get the service folks to help investigate this issue. The logs roll over on the service side, so a more recent log is required. Thank you!

**Comment by zezha-msft** [comment]
@matheus-santoro we have made many significant improvement in the recent months. Could you please give the latest version (v10.0.8) a try? And don't hesitate if you still encounter any issue.
