### ISSUE TITLE
How can I set concurrent connections?

### ISSUE THREAD

**Issue by cooperchen1990** [Azure/azure-storage-azcopy#1717]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Job-Command cp /home/appletv/portal/event https://twmmyvideo1120.file.core.windows.net/myvideosmb/PORTAL --recursive=true 

### What problem was encountered?
I want to set concurrent connections.
I use command "export AZCOPY_CONCURRENCY_VALUE=32".
And than,I use "./azcopy env" to check.

"Current Value: 32"

But, when I use azcopy. Log still show

"Max concurrent network operations:  will be dynamically tuned up to 3000"
and
"Trying 128 concurrent connections"

### How can we reproduce the problem in the simplest way?
Use "azcopy cp" to upload many small files. 

### Have you found a mitigation/solution?
NO

**Comment by siminsavani-msft** [comment]
Hi @cooperchen1990 ! Thank you for bringing this issue to our attention! We have added a fix for this for our next release.

**Comment by nakulkar-msft** [comment]
Fixed in 10.15.0
