### ISSUE TITLE
Too many open files - RHEL 8.2

### ISSUE THREAD

**Issue by kowalski-pawel** [Azure/azure-storage-azcopy#1720]
### Which version of the AzCopy was used? 
10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
RedHat Enterprise 8.2

### What command did you run?
I have a podman container with airflow. Airflow dag has a task with azcopy command:

/azcopy copy '/data/datafile' 'https://adls_location'   --from-to LocalBlob --log-level=ERROR --overwrite=true: INFO: Scanning...

INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
panic: open /root/.azcopy/plans/4df1d54f-e26c-da46-70bd-66bb66f0a04b--00000.steV16: too many open files

### What problem was encountered?
panic: open /root/.azcopy/plans/4df1d54f-e26c-da46-70bd-66bb66f0a04b--00000.steV16: too many open files

Sometimes it happens while creating azcopy log, sometimes azcopy plans

### How can we reproduce the problem in the simplest way?
To be honest I don't know. It looks a bit random.

Additional info.
There is a airflow run in the podman container.
Podman is executed from a dedicated user. Limits for this user:
```
ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 189738
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65335
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 189738
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

while in the container we have: 
```
ulimit -a:

core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 189738
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65335
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 189738
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

There are 10 azcopy commands executed in parallel.

**Comment by zezha-msft** [comment]
Hi @kowalski-pawel, could you please confirm if you are running the 10 processes in a single container?

Roughly speaking, the total number of open file descriptors is equal to: 10*(number of plans + number of concurrent connections + number of concurrent files)

The last 2 values are configurable. Could you please check the settings that you have for them?

And have you tried increasing the open file descriptor limit?

**Comment by zezha-msft** [comment]
Please try the latest version as well

**Comment by nakulkar-msft** [comment]
@kowalski-pawel, what is the result of 'ls /proc/<PID>/fd' while a transfer is in progress' ? It would help us if we're leaking file  descriptors. PID would be process id for AzCopy.

**Comment by kowalski-pawel** [comment]
So first of all I have modified azcopy paramaters and set below parameters for container:
 -e AZCOPY_CONCURRENCY_VALUE=10 \
    -e AZCOPY_CONCURRENT_FILES=10 \
    -e AZCOPY_CONCURRENT_SCAN=10 \

So everything was really limited.

For ls /ptoc/PID/fd I didn't catch the values for moment of error but while normal upload it was 18-20 for each azcopy processes.

The error looks like this:
```
panic: couldn't create job part plan file "d2ce1b0f-f0b0-1c4b-69df-93a9539c0c02--00000.steV16": open /root/.azcopy/plans/d2ce1b0f-f0b0-1c4b-69df-93a9539c0c02--00000.steV16:                                                                 too many open files

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/ste.JobPartPlanFileName.Create(0xc0007a23c0, 0x32, 0xd2ce1b0f00000000, 0xa993df691c4bf0b0, 0x20c9c53, 0x103000000000001, 0x1, 0x0, 0x0,                                                                 0x0, ...)
        /home/vsts/work/1/s/ste/JobPartPlanFileName.go:143 +0x2631
github.com/Azure/azure-storage-azcopy/ste.ExecuteNewCopyJobPartOrder(0xd2ce1b0f00000000, 0xa993df691c4bf0b0, 0x20c9c53, 0x103000000000001, 0x1, 0x0, 0x0, 0x0, 0x7ffc24a085ea                                                                , 0x68, ...)
        /home/vsts/work/1/s/ste/init.go:143 +0xb7
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0xc28eb6, 0x10, 0xaf1ee0, 0xc0000eab00, 0xaf1f20, 0xc00000fba0, 0x1, 0xc00000fba0)
        /home/vsts/work/1/s/cmd/rpc.go:44 +0x9ad
github.com/Azure/azure-storage-azcopy/cmd.glob..func6(0xc28eb6, 0x10, 0xaf1ee0, 0xc0000eab00, 0xaf1f20, 0xc00000fba0)
        /home/vsts/work/1/s/cmd/rpc.go:36 +0x5d
github.com/Azure/azure-storage-azcopy/cmd.dispatchFinalPart(0xc0000eab00, 0xc00077a000, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copyEnumeratorHelper.go:62 +0xcf
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).initEnumerator.func6(0xc00000fa20, 0x0)
        /home/vsts/work/1/s/cmd/copyEnumeratorInit.go:251 +0x33
github.com/Azure/azure-storage-azcopy/cmd.(*copyEnumerator).enumerate(0xc0007ca0c0, 0xd2ce1b0f00000000, 0xa993df691c4bf0b0)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:635 +0x98
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc00077a000, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copy.go:1238 +0x62a
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc00077a000, 0x266, 0xb)
        /home/vsts/work/1/s/cmd/copy.go:1026 +0x84
github.com/Azure/azure-storage-azcopy/cmd.init.2.func2(0xc00020b400, 0xc0002201e0, 0x2, 0x6)
        /home/vsts/work/1/s/cmd/copy.go:1625 +0x1da
github.com/spf13/cobra.(*Command).execute(0xc00020b400, 0xc000220120, 0x6, 0x6, 0xc00020b400, 0xc000220120)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x129e060, 0xc00016bdd8, 0x0, 0x0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc0000252b0, 0xd, 0xc0000252b0, 0xd, 0xc000028ba0, 0x13, 0x3ffff)
        /home/vsts/work/1/s/cmd/root.go:141 +0xcf
main.main()
        /home/vsts/work/1/s/main.go:82 +0x3dd

```

The file that caused the error was 2,8GB big.

BTW - is it possible prevent removing log and plan files of azcopy execution? In my case it's /root/.azcopy in the container.

**Comment by kowalski-pawel** [comment]
It failed once again. This time I got this error from the container: /bin/sh: error while loading shared libraries: libc.so.6: cannot open shared object file: Error 24

**Comment by nakulkar-msft** [comment]
@kowalski-pawel it appears to be same problem. Can you monitor the value for /proc/<PID>/fd, may be on a bash loop, for say every 2 seconds while azcopy is running? 

Yes, you can remove log and plan files by either a simple rm command or 'azcopy jobs clean --with-status=Completed'

**Comment by kowalski-pawel** [comment]
I did monitor it.
I run something like this:
while true; do d=$(date); echo $d >> fd_file.txt; for i in `ps -e | grep azcopy | awk '{ print $1 }'`; do echo fd\($i\): $(ls -l /proc/$i/fd|wc -l); done >> fd_file.txt; sleep 1; done &

and there were 10 processes with 20-23 fd value

I was also monitoring number of files in .azcopy and .azcopy/plans.
I noticed when it exceeded around 66k I got the error 'too many open files' Does azcopy keep the files from these directories open somehow? 

And can you suggest - how many files (sockets? whatever can cause too many files  error)  does azcopy create for a single file upload? 
My full upload consists of around 200-300 k files in up to 90TB in total.

**Comment by nakulkar-msft** [comment]
AzCopy has a configurable value, AZCOPY_CONCURRENT_FILES, which says how many files we transfer in parallel. Assuming that value to be 64, you should see something like 64 + No of open plan files + logfile, which would not exceed 100 in total. For 10 processes, we'll multiply. This is what Ze mentioned above. 

Can you post the fd_file.txt file to us. Either you can post here or mail to my address on my profile.

**Comment by kowalski-pawel** [comment]
Please find attached df_file.txt you requested 

[fd_file.txt](https://github.com/Azure/azure-storage-azcopy/files/8396276/fd_file.txt)

and additional one showing a number of open files on OS level:
[number_of_opened_files.log](https://github.com/Azure/azure-storage-azcopy/files/8396415/number_of_opened_files.log)

It was generated by script::
while true; do n=$(lsof -u ingest | awk '{print $9}' | sort | uniq | wc -l);d=$(date);echo "$d $n" 2>&1 >> number_of_opened_files.log; sleep 5; done &

Both were produced on the machine with all azcopy default parameters except this one:
AZCOPY_CONCURRENCY_VALUE=100

It uploaded 20k files and we got 'too many open files' error.
Be also aware that if I restart the process it works fine for some time and it fails again...

As a quick summary:
1. there are 10 parallel azcopy executions in the podman container on RHEL 8.2
2. each azcopy uploads a single file (we do not provide directories as a source)
3. both users - system (ingest) and the one in the container (root) have limit of open files set to : open files (-n) 65335

Thanks

**Comment by kowalski-pawel** [comment]
It looks like we solved it.
The problem was at the junction of OS and podman container. 
Azcopy is triggered in the container and generates a massive number of logs (and plans). We are required to upload each of numerous files (up to 1 million) in a separate azcopy call.
And there was a problem with synchronization between OS and container.
The bug was in fuse-overlayfs

You can find detailed description here:

[https://bugzilla.redhat.com/show_bug.cgi?id=1849557](https://bugzilla.redhat.com/show_bug.cgi?id=1849557)

[https://github.com/containers/fuse-overlayfs/issues/210](https://github.com/containers/fuse-overlayfs/issues/210)
