### ISSUE TITLE
V10.14.1 - Panic - too many open files (Mac OSX)

### ISSUE THREAD

**Issue by lukesammy** [Azure/azure-storage-azcopy#1725]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac (11.5)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy https://example.blob.core.windows.net/example/ . --recursive

### What problem was encountered?
Panic - too many open files

### How can we reproduce the problem in the simplest way?
It is consistent - happens every time running above command

### Have you found a mitigation/solution?
No, I have tried settings/reducing the following values with either no effect or increased error rates (in the case of AZCOPY_CONCURRENT_SCAN).

```
INFO: Name: AZCOPY_CONCURRENCY_VALUE
Current Value: 10
Description: Overrides how many HTTP connections work on transfers. By default, this number is determined based on the number of logical cores on the machine.

INFO: Name: AZCOPY_CONCURRENT_FILES
Current Value: 10
Description: Overrides the (approximate) number of files that are in progress at any one time, by controlling how many files we concurrently initiate transfers for.

INFO: Name: AZCOPY_CONCURRENT_SCAN
Current Value: 10
Description: Controls the (max) degree of parallelism used during scanning. Only affects parallelized enumerators, which include Azure Files/Blobs, and local file systems.
```

**Comment by nakulkar-msft** [comment]
Hi Luke, what is the limit on number of open files per user? Can you post the o/p for ulimit -a on your shell.

**Comment by lukesammy** [comment]
HI @nakulkar-msft here is the output
```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                4864
```

**Comment by mohsha-msft** [comment]
It seems like the number of file-descriptors is less. Please try setting the hard limit of file-descriptors to 65535 and give it a try again.

**Comment by lukesammy** [comment]
@mohsha-msft - I set it to 65535 and it ran for a little longer but still ended up throwing the same error.

```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                65535
```

**Comment by nakulkar-msft** [comment]
Hi @lukesammy , we need additional help with the panic. Can you please reach me on my email. It is on my profile. Thanks!

**Comment by nakulkar-msft** [comment]
This was found to be an issue with the way we create http clients. Please create a new issue if you see again.
