### ISSUE TITLE
invalid header value

### ISSUE THREAD

**Issue by angryjohnnie** [Azure/azure-storage-azcopy#1726]
##### Note: The version is visible when running AzCopy without any argument
10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy copy "https://STORAGEACCOUNTSOURCE.blob.azuremsk.ec.mts.ru/media/?sv=2019-02-02&ss=bqt&srt=sco&sp=rwdlacup&se=2022-03-25T00:29:20Z&st=2022-03-24T16:29:20Z&spr=https&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" "https://STORAGEACCOUNTDEST.blob.azuremsk.ec.mts.ru/media/?sv=2019-02-02&ss=b&srt=c&sp=rwdlac&se=2022-03-25T00:20:07Z&st=2022-03-24T16:20:07Z&spr=https&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" --recursive

### What problem was encountered?
Code: InvalidHeaderValue
HeaderName: x-ms-version
HeaderValue: 2020-04-08

### Have you found a mitigation/solution?
no mitigation

I don't understand where the header value is coming from if the sv=2019-02-02 is set in the url string. ive tried manually setting the api-version in the url string also and that doesn't work either. but it does return with a different header value. still not the correct one that was specified though.d

**Comment by nakulkar-msft** [comment]
Hi @angryjohnnie, can you let us knwo which request failed with this error? You can find it in the log file. (Logs are in ~/.azcopy btw). Else if you can forward the log, we can take a look. Email on my profile.

**Comment by angryjohnnie** [comment]
> Hi @angryjohnnie, can you let us knwo which request failed with this error? You can find it in the log file. (Logs are in ~/.azcopy btw). Else if you can forward the log, we can take a look. Email on my profile.

thanks for looking. ive sent the requested info.

**Comment by nakulkar-msft** [comment]
Reopen if you see this again.
