### ISSUE TITLE
Failed to sync file from local to Azure file

### ISSUE THREAD

**Issue by robga** [Azure/azure-storage-azcopy#1727]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
.\azcopy sync \\{localIp}\{localSmbShrea} 'https://{saAccount}.file.core.windows.net/{shareName}/{folderName}?{sasToken}'  --recursive --preserve-smb-permissions=true --preserve-smb-info=true --delete-destination=prompt

### What problem was encountered?
It throws exception: 
panic: runtime error: index out of range [0] with length 0

goroutine 104 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.localFileSourceInfoProvider.GetSDDL(0x14b0ed0, 0xc00025a0e0, 0xe64ae187366c7999, 0xfb2a1bb69fe01670, 0x800000, 0xc0024da000, 0x4e, 0x0, 0xc002b44000, 0x108, ...)
        /home/vsts/work/1/s/ste/sourceInfoProvider-Local_windows.go:78 +0x5dc
github.com/Azure/azure-storage-azcopy/v10/ste.(*azureFileSenderBase).addPermissionsToHeaders(0xc000942ea0, 0xe64ae187366c7999, 0xfb2a1bb69fe01670, 0x800000, 0xc0024da000, 0x4e, 0x0, 0xc002b44000, 0x108, 0x10201, ...)
        /home/vsts/work/1/s/ste/sender-azureFile.go:274 +0x11d
github.com/Azure/azure-storage-azcopy/v10/ste.(*azureFileSenderBase).SetFolderProperties(0xc000942ea0, 0x0, 0x0)
        /home/vsts/work/1/s/ste/sender-azureFile.go:381 +0x1d8
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote_folder(0x14b0ed0, 0xc00025a0e0, 0xe64ae187366c7999, 0xfb2a1bb69fe01670, 0x800000, 0xc0024da000, 0x4e, 0x0, 0xc002b44000, 0x108, ...)
        /home/vsts/work/1/s/ste/xfer-anyToRemote-folder.go:85 +0x55d
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote(0x14b0ed0, 0xc00025a0e0, 0x148b0c0, 0xc0003a2080, 0x1707c6dc200, 0xc0004a0010, 0x1377530, 0x1377580)
        /home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:180 +0x1a5
github.com/Azure/azure-storage-azcopy/v10/ste.parameterizeSend.func1(0x14b0ed0, 0xc00025a0e0, 0x148b0c0, 0xc0003a2080, 0x1707c6dc200, 0xc0004a0010)
        /home/vsts/work/1/s/ste/xfer.go:76 +0x7a
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartMgr).StartJobXfer(0xc000315a40, 0x14b0ed0, 0xc00025a0e0)
        /home/vsts/work/1/s/ste/mgr-JobPartMgr.go:679 +0x78
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).StartJobXfer(0xc00025a0e0)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:216 +0x4f
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).transferProcessor.func1(0x14b0ed0, 0xc00025a0e0)
        /home/vsts/work/1/s/ste/JobsAdmin.go:467 +0x1b9
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).transferProcessor(0xc000346340, 0x31)
        /home/vsts/work/1/s/ste/JobsAdmin.go:475 +0x95
created by github.com/Azure/azure-storage-azcopy/v10/ste.initJobsAdmin
        /home/vsts/work/1/s/ste/JobsAdmin.go:221 +0x7bd

### How can we reproduce the problem in the simplest way?
No (Sorry, I can only tell the same cmd (the same local smb share) worked for me before on an older version azcopy that was downloaded around Dec. 2021)

### Have you found a mitigation/solution?
No

**Comment by mohsha-msft** [comment]
Hey @robga ,

Thanks for reaching out!

AzCopy sync from local source to Azure file is working fine in the released versions. I tried to repro the issue but it worked as expected for me as well.

```pwsh
 .\azure-storage-azcopy.exe sync F:\RandomData\2020\ "https://azurestrgmohitfrance.file.core.windows.net/testdirectory/2020?<SAS>" --recursive --preserve-smb-permissions=true --preserve-smb-info=true --delete-destination=prompt
INFO: Any empty folders will be processed, because source and destination both support folders. For the same reason, properties and permissions defined on folders will be processed

Job 48ebf78e-a951-cf45-5e71-8b6a4d310a69 has started
Log file is located at: C:\Users\mohsha\.azcopy\48ebf78e-a951-cf45-5e71-8b6a4d310a69.log

The File 'Az %Copy.txt' does not exist at the source. Do you wish to delete it from the destination(https://azurestrgmohitfrance.file.core.windows.net/testdirectory/2020/mycont)? Please confirm with: [Y] Yes  [N] No  [A] Yes for all  [L] No for all A
INFO: Confirmed. All the extra Files will be deleted.     
INFO: Deleting extra object: Az %Copy.txt
INFO: Deleting extra object: Import_User_Sample_en%.csv   
INFO: Deleting extra object: max%resdefault.jpg           
24 Files Scanned at Source, 7 Files Scanned at Destination

Job 48ebf78e-a951-cf45-5e71-8b6a4d310a69 Summary
Files Scanned at Source: 24
Files Scanned at Destination: 27
Elapsed Time (Minutes): 0.1337
Number of Copy Transfers for Files: 0
Number of Copy Transfers for Folder Properties: 0
Total Number Of Copy Transfers: 0
Number of Copy Transfers Completed: 0
```

I would like you to double check the command you're passing. I suspect that the source is not correctly formed. In the AzCopy log file, we publish `Job-Command` that you can see to validate the correct source/destination.

If it doesn't help, please share the AzCopy log and AzCopy Scanning log with me? I'll investigate it for you.

**Comment by robga** [comment]
Whatever the parameters I gave, it shouldn't crush. I cannot share you the log. But I can tell you there is no error in the log. You should be able to investigate it based on the exception.
