### ISSUE TITLE
Logging to Azure Application Insights

### ISSUE THREAD

**Issue by DVN196** [Azure/azure-storage-azcopy#1728]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.14.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
`azcopy copy ./data '<SAS>'`
### What problem was encountered?
I need to use AZcopy to transfer a large amount of data, and I would like to monitor its progress in realtime using Azure Application Insights.

Currently, I must wait for the completion of the transaction in order to view the log file.
### How can we reproduce the problem in the simplest way?
Any data transfer process.
### Have you found a mitigation/solution?
An option for logging to Application Insights, or printing the log to stdout and pipe the output

**Comment by mohsha-msft** [comment]
Hey @DVN196 ,

Thanks for reaching out!

We do not support Azure Application Insight though I can see where you're coming from and how it can be nice feature for a subset of users. 

BTW, you can see the logs even when AzCopy jobs is executing? I noticed you're using Linux environment. DId you try running [tail command](https://man7.org/linux/man-pages/man1/tail.1.html)?

You can set the `--log-level` flag  to specify the log verbosity for the log file, 
Available levels: INFO(all requests/responses), WARNING(slow responses), ERROR(only failed requests), and NONE(no output logs). (default 'INFO'), DEBUG.

**Comment by DVN196** [comment]
Ok, thank you for your suggestion. Currently, I just watch the AZCOPY_LOG_LOCATION for filesystem changes to detect file modification.
