### ISSUE TITLE
New feature request of preserving timestamp and copying empty folder from AWS S3 to Azure Blob

### ISSUE THREAD

**Issue by GlenGengMicrosoft** [Azure/azure-storage-azcopy#1730]
### Which version of the AzCopy was used? 
10.14.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
azcopy copy "awsS3uri" "azurebloburi" --preserve-last-modified-time
### What problem was encountered?
The azcopy tool cannot preserve the timestamp in the AWS S3 bucket and cannot copy empty folders as well.
### How can we reproduce the problem in the simplest way?
Run the command to transfer data
### Have you found a mitigation/solution?
Not yet.

**Comment by amishra-dev** [comment]
Hi @GlenGengMicrosoft,
this is a good feature ask. the change needs to be made in azure storage service first before azcopy could make it. We have raised the feature request with my friends on the service side. 
When the service adds it (no timeline yet), we will add it to azcopy. 
We are tracking this ask in our backlog so closing this issue.

Thanks and please feel free to let us know of any other feedback you have.
Ashish
