### ISSUE TITLE
Question: Will copy avoid full-target scans, unlike sync?

### ISSUE THREAD

**Issue by lmeyerov** [Azure/azure-storage-azcopy#1731]
Does `azcopy cp` avoid full-target scans?

We currently use `azcopy sync` for backup & restore, e.g., `"small production vm -> giant backup blobstore"` and `"giant backup blobstore -> small caching tier vm"`. `sync` has some nice as well because it can propagate deletions, though not too critical for us. However, `sync` is too slow for us nowadays because, even when doing `local -> blobstore`, it'll do a full scan of the blobstore ( https://github.com/Azure/azure-storage-azcopy/issues/1675 ), which can be too big.

So... 

- does `azcopy cp <local> <blobstore>` avoid the full-blobstore scan problem? Or will it also scan?

- does `--include-before` / `--include-after` factor into this somehow? e.g.,is that acting just on local scan, or helping speed up the blobstore scan too?

For reference, our slow `sync` version:

```bash
azcopy sync \
    /some/local/path  \
    "https://${ARM_STORE_NAME}.blob.core.windows.net/${ARM_CONTAINER_NAME}/data?${SAS_TOKEN}" \
    --exclude-path=some_folder \
    --recursive=true \
    --put-md5
```

**Comment by nakulkar-msft** [comment]
Hi @lmeyerov, 

- Copy does not scan destination. If you're copying from your local source to blobstore, you can speed this up with flag --overwrite=IfSourceNewer. This would generally be faster than sync. But you would lose the capability to propagate deletions.
- Include* flags are acting on local scan. 

Let me know more about your usecase, I'll check how to speed up.

**Comment by lmeyerov** [comment]
Great to hear, will give a whirl :)
