### ISSUE TITLE
[WSL] Service principal auth fails for v10.14.1 in Linux

### ISSUE THREAD

**Issue by aranga81** [Azure/azure-storage-azcopy#1734]
### Which version of the AzCopy was used? 
10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
./azcopy login --service-principal --certificate-path <path> --application-id <>

### What problem was encountered?
SPN auth via cert succeeded 
But login status is still not active and it fails to obtain credentials.
I used the same 10.14.1 on windows and it works fine for the same certificate and the app_id of Service principal 

### How can we reproduce the problem in the simplest way?
Using WSL2 20.04 - get latest v10.14.1 Azcopy and try to login with service principal / with certificate (local copy)

**Comment by nakulkar-msft** [comment]
Hi @aranga81, Please use [Autologin](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)) while we look into this issue. Thanks.

**Comment by adreed-msft** [comment]
Out of curiosity, is the certificate specified as a literal path (/path/to/your/cert) or a relative path? (path/to/your/cert) I'd be curious to know if that makes a difference.

**Comment by amir-abdi** [comment]
Same problem. 
Couldn't manage to use Autologin with `AZCOPY_AUTO_LOGIN_TYPE=MSI`. I'm quite new to azure.

**Comment by nakulkar-msft** [comment]
Waiting for fix on WSL.

**Comment by gabe-microsoft** [comment]
Azcopy login has been broken in WSL for over a year. Any status update?

**Comment by mcobzarenco** [comment]
On Ubuntu 22.04. Autologin doesn't work either.

Commands:
```
> azcopy login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <redacted> to authenticate.
INFO: Logging in under the "Common" tenant. This will log the account in under its home tenant.
INFO: If you plan to use AzCopy with a B2B account (where the account's home tenant is separate from the tenant of the target storage account), please sign in under the target tenant with --tenant-id
INFO: Login succeeded.
> azcopy login status
INFO: You are currently not logged in. Please login using 'azcopy login'
```

**Comment by joshuafernandes** [comment]
You can get past the login with :
