### ISSUE TITLE
Export AZCOPY_LOG_LOCATION / Command not recognized on Linux azcopy v10.14.0

### ISSUE THREAD

**Issue by vstanescu** [Azure/azure-storage-azcopy#1736]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.14.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (rhel)
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy --recursive "${pathFull}/rawdata/journal.gz" "${storageAccountBase}/${storageAccountContainer}/${indexName}/${bucket}/?${storageAccount_TokenSAS}"
### What problem was encountered?
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript panic: open /root/.azcopy/ca98dd3b-bd81-fc42-440a-3d7a3e04bebd-scanning.log: permission denied
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript goroutine 1 [running]:
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript github.com/Azure/azure-storage-azcopy/v10/common.PanicIfErr(...)
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript    /home/vsts/work/1/s/common/lifecyleMgr.go:596
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript github.com/Azure/azure-storage-azcopy/v10/common.(*jobLogger).OpenLog(0xc00049c000)
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript    /home/vsts/work/1/s/common/logger.go:135 +0x4f7
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript github.com/Azure/azure-storage-azcopy/v10/cmd.rawCopyCmdArgs.cook(0x7ffca91d850c, 0x6f, 0x7ffca91d857c, 0x12c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript    /home/vsts/work/1/s/cmd/copy.go:259 +0x28f
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript github.com/Azure/azure-storage-azcopy/v10/cmd.init.2.func2(0xc00049e780, 0xc000469320, 0x2, 0x3)
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript    /home/vsts/work/1/s/cmd/copy.go:1785 +0xe5
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript github.com/spf13/cobra.(*Command).execute(0xc00049e780, 0xc0004692c0, 0x3, 0x3, 0xc00049e780, 0xc0004692c0)
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript    /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript github.com/spf13/cobra.(*Command).ExecuteC(0x1681640, 0xbdbe043e7a3d0a44, 0xc0002dfdf8, 0x0)
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript    /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript github.com/spf13/cobra.(*Command).Execute(...)
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript    /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript github.com/Azure/azure-storage-azcopy/v10/cmd.Execute(0xc00049a700, 0xd, 0xc00049a700, 0xd, 0xc00003e6f0, 0x13, 0xffff)
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript    /home/vsts/work/1/s/cmd/root.go:165 +0xf8
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript main.main()
04-04-2022 04:13:48.649 +0000 ERROR BucketMover - coldToFrozenScript    /home/vsts/work/1/s/main.go:82 +0x3a5

### How can we reproduce the problem in the simplest way?
When triggering script manually it works properly but when Splunks launches the script it can't use azcopy. (works on another server with azcopy v10.2xxx) We tried to set the AZCOPY_LOG_LOCATION using azcopy export AZCOPY_LOG_LOCATION=/tmp/ but command isn't recognized...
What is this error that we are getting?

Your help is much appreciated
### Have you found a mitigation/solution?
N\A

**Comment by nakulkar-msft** [comment]
@vstanescu, this is a configuration issue and not a bug with AzCopy. The environment variables has not been passed to AzCopy. To confirm if AzCopy has picked the environment, you an run 'azcopy env'.

If running as root, use sudo -E to inherit environment variables, or pass them on command line as below.

AZCOPY_LOG_LOCATION=<> azcopy copy <source> <destination> <Flags>
