### ISSUE TITLE
azcopy aborts if file is updated after copy started

### ISSUE THREAD

**Issue by dskdas** [Azure/azure-storage-azcopy#1744]
### Which version of the AzCopy was used? 
10.14.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy copy [local file pat] [storage container] --recursive

### What problem was encountered?
We are using azcopy to copy snapshot of log files that are being written into. We have been using gsutil on google for the same and it works perfectly fine. AzCopy however aborts when it detects that last modified time has changed after copy started.

### How can we reproduce the problem in the simplest way?

unit tests already capture this seems like:
https://github.com/Azure/azure-storage-azcopy/blob/aedcd0b00711650f0acaf43f69bcb08a0c26e578/e2etest/zt_change_detection_test.go#L34

seems below code is triggering this:
https://github.com/Azure/azure-storage-azcopy/blob/aedcd0b00711650f0acaf43f69bcb08a0c26e578/ste/xfer-anyToRemote-file.go#L304

create a large file using dd or some other cmd. 
start azcopy to copy it to some storage container
append something to the file or do some operation to update the last modified time.

### Have you found a mitigation/solution?

Ideal solution it seems could be that there is an option to bypass this check.

We have to currently first use linux cp command to copy to a local staging directory and then use azcopy to copy from the staging directory to a storage container. This is problematic in long run for us as a) it adds to overall elapsed time b) the local storage space is in demand for other things

**Comment by nakulkar-msft** [comment]
Hi @dskdas, this is expected behaviour, files updated on while being transferred cause data inconsistency on the destination. This feature will be retained.
