### ISSUE TITLE
Sync between blob container folder and local folder failing

### ISSUE THREAD

**Issue by L-P-G** [Azure/azure-storage-azcopy#1746]
Does AZCopy no longer support copying the contents of a folder in a blob container to a folder in a local file system? Looking at the examples for azcopy sync. I don't see any examples showing syncing from an Azure blob storage folder to a filesystem folder.

I know this used to work as I had a scheduled job working but after updating azcopy it now states:

Cannot perform sync due to error: sync must happen between source and destination of the same type, e.g. either file <-> file, or directory/container <-> directory/container

See exact command used below:

**Comment by nakulkar-msft** [comment]
Hi @L-P-G, AzCopy still supports copying between a container and directory. Please check if you have enough permissions on the SAS. Or try with other ways of auth - SPN or MSI and let us know.

**Comment by L-P-G** [comment]
Found the issue. v10.13.0 has a bug there the sync wouldn't work. after upgrading to v10.14.0 and leaving the command+SAS the same. The issue went away.
