### ISSUE TITLE
File Modification time not preserved when copying files from Unix platform to Azure File Share

### ISSUE THREAD

**Issue by PVergwen** [Azure/azure-storage-azcopy#1750]
I am using AZcopy v10.13.0 and am trying to retain the file modified date attribute when copying files from a linux host to an Azure file share.
Tried using copy parameters --preserve-last-modified-time and --preserve-smb-info (one at a time) but the file in Azure file share always shows the file copy time stamp as modified date.
Wasn't this supposed to be solved from AZcopy v10.4 onward? any suggestion on what I'm doing wrong?
Note that preserving the file modified date in the opposite direction from Azure file share to Unix DOES work using the --preserve-last-modified-time copy parameter.

**Comment by mohsha-msft** [comment]
Hey @PVergwen ,

Thanks for reaching out!

AzCopy supports preserving properties and ACLs when source and destination are SMB aware (Windows/FileShare/Datalake Gen2).
We currently do not support preserving ACLs from UNIX. We are in progress of making that change and current most likely target is AzCopy 10.16.0.

Please reach out for more information!
