### ISSUE TITLE
Automatic login failure is non-descript when no other auth is present

### ISSUE THREAD

**Issue by adreed-msft** [Azure/azure-storage-azcopy#1753]
##### Note: The version is visible when running AzCopy without any argument
10.14.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Any operation that may require OAuth (e.g. azcopy copy)
### What problem was encountered?
When automatic login fails, no error is handed off to the user, nor mention of auto-login, giving the appearance the feature is not working correctly.
### How can we reproduce the problem in the simplest way?
Attempt to perform auto-login with a secret-based service principal, giving an incorrect secret.

**Comment by nakulkar-msft** [comment]
tracked via #1805
