### ISSUE TITLE
azcopy slow to copy and reports "Disk may be limiting speed" when network and disk look OK

### ISSUE THREAD

**Issue by MaxTaggart** [Azure/azure-storage-azcopy#1756]
AzCopy version: 10.14.1
Platform: MacOS 12.1 (Apple M1 Max chip)
Command: 
```
azcopy copy 'https://<account>.blob.core.windows.net/<container>/<blob>/<sas>' <output_file>
```

The blob I am copying is 1.32 GB and the log file shows that the command ran for 1.0673 minutes. Included is a screenshot of a disk-throughput test and a network speed test. (In case the image gets lost the disk throughput was tested using the "Black Magic" disk testing tool and the write speed is reported as 3673.4 MB/s, read speed 5216.4 MB/s. The network speed test was run using M-Lab and shows a download speed of 186.4 Mbps and an upload speed of 194.3 Mbps).

<img width="1135" alt="Screen Shot 2022-04-25 at 11 32 28 AM" src="https://user-images.githubusercontent.com/16192899/165144225-d3b3777c-67e5-4e21-a501-cc9239bd2ea5.png">

And here is the output in my terminal:
```
$ azcopy copy redacted
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 8edaa007-d666-7343-7914-fe27b3bebda9 has started
Log file is located at: redacted

100.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,  (Disk may be limiting speed)


Job 8edaa007-d666-7343-7914-fe27b3bebda9 summary
Elapsed Time (Minutes): 1.0673
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 1
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 1412682122
Final Job Status: Completed
```

Happy to supply the log file via email.

Here is some info about the hard disk on my machine:

```
Device Name:	APPLE SSD AP0512R
Media Name:	AppleAPFSMedia
Medium Type:	SSD
Protocol:	Apple Fabric
Internal:	Yes
Partition Map Type:	Unknown
S.M.A.R.T. Status:	Verified
```

I'm not sure how best to re-create the issue but happy to provide more info or try any suggestions. I am also seeing very slow download speeds using the Python `azure-storage-blob` library (only writing to memory) and the Azure speed test tool (https://www.azurespeed.com/Azure/Download) that was suggested in this Azure Q&A thread: https://docs.microsoft.com/en-us/answers/questions/89440/getting-very-slow-speed-while-downloading-storage.html

**Comment by siminsavani-msft** [comment]
Hi @MaxTaggart ! I would recommend turning off MD5 checks by setting --check-md5 to 'NoCheck' if you do not need MD5 hashes for integrity checks. This will help increase the speed. Please check out this documentation on how performance is impacted by large files (https://github.com/Azure/azure-storage-azcopy/wiki/Performance:-Large-files-in-general). 

Please let me know if you have any questions!
