### ISSUE TITLE
AzCopy copy hangs while running in background

### ISSUE THREAD

**Issue by caleb-terry** [Azure/azure-storage-azcopy#1761]
##### Note: The version is visible when running AzCopy without any argument
10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux - Rocky 8 

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
#!/bin/bash

BASEDIR="/backups";
FTS=`date '+%Y%m%d-%H%M%S'`;
SERVER="<OUR CONTAINER>"
BLOBURL="<OUR URL>
LOG="/backups/logs/backup-$FTS.log"
export AZCOPY_SPA_CLIENT_SECRET="<OUR SECRET>"
export PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

echo "Backing up" >> $LOG 2>&1

mariabackup --backup --parallel=6 --incremental-basedir=$BASEDIR/MySQL_Full  --socket=/data/mysql/mysql.sock --target-dir=$BASEDIR/inc_$FTS 2> /root/xtrabackup/xtrabackup_log

echo "Compressing the backup" >> $LOG 2>&1
tar --remove-files -jcf - $BASEDIR/inc_$FTS | (pv > $BASEDIR/inc_$FTS.tar.bz2) >> $LOG 2>&1

echo "Signing into Azure Storage Account" >> $LOG 2>&1
azcopy login --service-principal --application-id <APP ID> --tenant-id <TENANT ID> >> $LOG 2>&1

echo "Copying the backup to Azure" >> $LOG 2>&1
azcopy copy $BASEDIR/inc_$FTS.tar.bz2 "$BLOBURL" >> $LOG 2>&1

echo "Signing out of Azure Storage Account" >> $LOG 2>&1
azcopy logout

echo "Backup complete" >> $LOG 2>&1

### What problem was encountered?
When running as a cron job or running in the background with &, the script makes it to the azcopy portion and then ends and you can see the process still running in the background but not doing anything. Doesn't show in azcopy jobs list

[root@server ~]# azcopy copy /backups/inc_20220504-090225.tar.bz2 "<OUR URL>" &
[1] 144158

[root@1235355-DBKSBP01 ~]# 
[1]+  Stopped                 azcopy copy /backups/inc_20220504-090225.tar.bz2 "<OUR URL>"

[root@server ~]# ps aux | grep azcopy
root      144158  0.0  0.3 1098984 24396 pts/0   Tl   09:38   0:00 azcopy copy /backups/inc_20220504-090225.tar.bz2 <OUR URL>
root      144176  0.0  0.0  12132  1164 pts/0    S+   09:38   0:00 grep --color=auto azcopy

### How can we reproduce the problem in the simplest way?
azcopy copy filename bloburl &

### Have you found a mitigation/solution?
nohup azcopy copy filename bloburl &

**Comment by desius** [comment]
Can reproduce

`script.py &/tmp/out &`

Running a python script with azcopy in it such as above will cause azcopy to hang when uploading a file to blob storage.
Running the process through nohup will complete.

**Comment by games** [comment]
same here, any update?

**Comment by nakulkar-msft** [comment]
Hi, this is configuration on the client side. Sorry we cannot help you here.
