### ISSUE TITLE
Panic error when using --preserve-smb-permissions=true

### ISSUE THREAD

**Issue by krosbonz** [Azure/azure-storage-azcopy#1763]
### Which version of the AzCopy was used? 
10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 VM attempting to copy files from a remote 
[bc5eb7de-42b9-4345-7b7d-06bf8a0d24e6.log](https://github.com/Azure/azure-storage-azcopy/files/8632509/bc5eb7de-42b9-4345-7b7d-06bf8a0d24e6.log)
[bc5eb7de-42b9-4345-7b7d-06bf8a0d24e6-scanning.log](https://github.com/Azure/azure-storage-azcopy/files/8632510/bc5eb7de-42b9-4345-7b7d-06bf8a0d24e6-scanning.log)
2012R2 file server share to Azure Files share

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy 'S:\some_folder' 'https://azfiles.file.core.windows.net/shared?SAS' --recursive --preserve-smb-permissions=true --preserve-smb-info=true --overwrite=ifSourceNewer

### What problem was encountered?
INFO: Trying 4 concurrent connections (initial starting point)
0.0 %, 0 Done, 0 Failed, 9 Pending, 0 Skipped, 9 Total, panic: runtime error: index out of range [0] with length 0

goroutine 21 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.localFileSourceInfoProvider.GetSDDL(0x1450ed0, 0xc00017a380, 0xfe429048fc023299, 0x8ef74c0165dd997e, 0x800000, 0xc00009c8a0, 0x5c, 0x17e8553, 0xc000af88c0, 0x12d, ...)
        /home/vsts/work/1/s/ste/sourceInfoProvider-Local_windows.go:78 +0x5dc
github.com/Azure/azure-storage-azcopy/v10/ste.(*azureFileSenderBase).addPermissionsToHeaders(0xc0000bb9e0, 0xfe429048fc023299, 0x8ef74c0165dd997e, 0x800000, 0xc00009c8a0, 0x5c, 0x17e8553, 0xc000af88c0, 0x12d, 0x10200, ...)
        /home/vsts/work/1/s/ste/sender-azureFile.go:274 +0x11d
github.com/Azure/azure-storage-azcopy/v10/ste.(*azureFileSenderBase).Prologue(0xc0000bb9e0, 0xc0003ae400, 0x200, 0x200, 0x0)
        /home/vsts/work/1/s/ste/sender-azureFile.go:154 +0x205
github.com/Azure/azure-storage-azcopy/v10/ste.scheduleSendChunks(0x1450ed0, 0xc00017a380, 0xc00009c8a0, 0x5c, 0x1436910, 0xc0000074b0, 0x17e8553, 0x14478f8, 0xc0000bb9e0, 0xc0000b9680, ...)
        /home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:428 +0x71b
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote_file(0x1450ed0, 0xc00017a380, 0xfe429048fc023299, 0x8ef74c0165dd997e, 0x800000, 0xc00009c8a0, 0x5c, 0x17e8553, 0xc000af88c0, 0x12d, ...)
        /home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:345 +0x9b2
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote(0x1450ed0, 0xc00017a380, 0x142b0c0, 0xc00039e380, 0x24959c04a70, 0xc0000b2008, 0x1317530, 0x1317580)
        /home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:182 +0x258
github.com/Azure/azure-storage-azcopy/v10/ste.parameterizeSend.func1(0x1450ed0, 0xc00017a380, 0x142b0c0, 0xc00039e380, 0x24959c04a70, 0xc0000b2008)
        /home/vsts/work/1/s/ste/xfer.go:76 +0x7a
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartMgr).StartJobXfer(0xc000098000, 0x1450ed0, 0xc00017a380)
        /home/vsts/work/1/s/ste/mgr-JobPartMgr.go:679 +0x78
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).StartJobXfer(0xc00017a380)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:216 +0x4f
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).transferProcessor.func1(0x1450ed0, 0xc00017a380)
        /home/vsts/work/1/s/ste/JobsAdmin.go:467 +0x1b9
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).transferProcessor(0xc000a00000, 0x1)
        /home/vsts/work/1/s/ste/JobsAdmin.go:475 +0x95
created by github.com/Azure/azure-storage-azcopy/v10/ste.initJobsAdmin
        /home/vsts/work/1/s/ste/JobsAdmin.go:221 +0x7bd

### How can we reproduce the problem in the simplest way?
This occurs anytime "--preserve-smb-permissions=true" is used

### Have you found a mitigation/solution?
Removing "--preserve-smb-permissions=true" allows the folder to copy without issue, but ACLs are not copied which is required.

**Comment by GitPhunkie** [comment]
I'm not sure if I'm supposed to add something in issue threads, I'm fairly new to github. But I'm experiencing the same problem.

Source folder is a network resource either mapped to a drive or using UNC.
ROBOCOPY works fine while preserving security. 
AZCOPY works without the switch to preserve security (no security copied), but doesn't work with the switch.

Logging on the server and running azcopy from the local drive (example: D:\whatever\something) works.

**Comment by krosbonz** [comment]
Exactly what I am seeing including successfully using Robocopy to preserve security.

**Comment by abardall** [comment]
also seeing this issue however only appears to be when copying from a network location. copied direct from drive and it worked
azcopy copy '**C:**\some_folder' 'https://azfiles.file.core.windows.net/shared?SAS' --recursive --preserve-smb-permissions=true --preserve-smb-info=true --overwrite=ifSourceNewer

**Comment by im-denis** [comment]
I struggle with the same problem when using the flag --preserve-smb-permissions=true

`panic: runtime error: index out of range [0] with length 0`

**Comment by im-denis** [comment]
> Is yours also trying to copy from a network location?

yes exactly

**Comment by im-denis** [comment]
Any update on this bug?

**Comment by Randomsense** [comment]
I'm very much in need to be able to --preserve-smb-permissions and it looks like 10.15.1 might be released later than I can afford for my project. im-denis mentioned the functionality works in 10.12.2 though the link posted doesn't seem to be available any longer. Is there any known safe way to get the older version binary?

**Comment by cricketthomas** [comment]
Can we reopen this? I am now getting this same error when running AzCopy in Azure devops.
This is happening on ubuntu-latest
```
    - task: AzureCLI@2
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
              $env:AZCOPY_SPA_CLIENT_SECRET = $env:servicePrincipalKey
              azcopy login --service-principal --application-id $env:servicePrincipalId --tenant-id $env:tenantId              
              azcopy sync "${{ parameters.directory }}" "${{ parameters.azFileShareUrl }}"  --recursive --preserve-smb-info=true           
        addSpnToEnvironment: true
        failOnStandardError: true
```

**Comment by adreed-msft** [comment]
It sounds like your issue is separate @cricketthomas (this one was remote share->azure from windows; yours appears to be utilizing the UNIX SMB props work our partner team did). Please open a new issue, and I'll inform the relevant parties.

**Comment by cricketthomas** [comment]
@adreed-msft I opened a new one. Thank you!
https://github.com/Azure/azure-storage-azcopy/issues/2055
