### ISSUE TITLE
Azcopy not working on on-premise linux VM

### ISSUE THREAD

**Issue by shubhamgarg150391** [Azure/azure-storage-azcopy#1765]
### Which platform are you using? (ex: Windows, Mac, Linux)
On-premise linux VM
### What command did you run?
destination_path="destination"
blob_name="test"
FILE_Upload="./data.csv"
blob_metadata="rcf=test;sh=223"
blob_target="https://shubhstrg150391.blob.core.windows.net/${blob_name}/${destination_path}/data.csv?"
sas_limit=$(date --utc --date "4 hour" +%FT%TZ)
sas_generate=$(az storage container generate-sas --account-key -REDACTED- == --account-name shubhstrg150391 --expiry $sas_limit --name test --permissions dlrw)
echo $sas_generate
temp="${sas_generate%\"}"
sas_token="${temp#\"}"
echo "$sas_token"
./azcopy cp "${FILE_Upload}" "${blob_target}${sas_token}" --metadata "${blob_metadata}"

### What problem was encountered?
azcopy file is not present or not working
### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
Please run this command from the directory where you've downloaded/extracted azcopy
