### ISSUE TITLE
Proxy servers that require authentication are not supported on Linux

### ISSUE THREAD

**Issue by smitha-cgi** [Azure/azure-storage-azcopy#1766]
### Which version of the AzCopy was used? 
10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy -h

### What problem was encountered?
Proxy server not detected correctly when https_proxy is set to http://domain\\username:password@ip:port. The environment variable is not being processed correctly.

### How can we reproduce the problem in the simplest way?
Set https_proxy to http://1.2.3.4:80, and run azcopy -h. It prints 'INFO: Proxy detected: https://azcopyvnextrelease.blob.core.windows.net -> http://1.2.3.4:80'

Then set https_proxy to http://home\\me:mypass@1.2.3.4:80 and run azcopy -h again. It prints 'INFO: Proxy detected: https://azcopyvnextrelease.blob.core.windows.net -> http://http://home%5Cme:mypass@1.2.3.4:80'

It is putting an additional http:// prefix at the start which makes the proxy invalid

### Have you found a mitigation/solution?
No

**Comment by marc-hb** [comment]
`http://home\\me:mypass@1.2.3.4:80` looks strange/invalid. According to https://urlparse.com/ the user name is `home\\me:mypass`!?

Did you mean `http://me:mypass@1.2.3.4:80`?

**Comment by smitha-cgi** [comment]
In my environment I can't just use a username and password - I have to prefix the username with the domain that the user belongs to. So home is the domain, me is the user, and mypass is the password in this example.

**Comment by marc-hb** [comment]
Then you need to escape/encode the URL to make it standard compliant. azcopy is likely using some Go library similar to `urlparse` and that library can only support standard compliant URLs.

Maybe try this: http://home%5C%5Cme:mypass@1.2.3.4:80

**Comment by gapra-msft** [comment]
Hi @smitha-cgi I believe @marc-hb 's suggestion above is the correct way to set the https proxy URL. When I set it to that the proxy looks correct. Closing this issue for now as AzCopy is behaving as expected. Feel free to reopen if you still feel that is not the case.
