### ISSUE TITLE
AzCopy Sync not processing files. 

### ISSUE THREAD

**Issue by hp-alanj** [Azure/azure-storage-azcopy#1774]
### Which version of the AzCopy was used? 
AzCopy 10.14.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2019 also Windows 11 (Both on the same network)
### What command did you run?
azcopy sync "https://xxx.blob.core.windows.net/sftpgw-callcentre/?sv=2020-08-04..." "H:\SFTP_Repository" --recursive
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
[46bd05c6-c26d-5142-65b3-616aa5c0cb26-scanning.log](https://github.com/Azure/azure-storage-azcopy/files/8669846/46bd05c6-c26d-5142-65b3-616aa5c0cb26-scanning.log)

### What problem was encountered?
Job 46bd05c6-c26d-5142-65b3-616aa5c0cb26 has started
Log file is located at: C:\Users\AlanJ\.azcopy\46bd05c6-c26d-5142-65b3-616aa5c0cb26.log

0 Files Scanned at Source, 0 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination
0 Files Scanned at Source, 39933 Files Scanned at Destination

I constantly loops this and never copies any files. I have also attached the log file. 

### How can we reproduce the problem in the simplest way?
Not sure. I am copying from a blob storage account that I am able to access with storage explorer to a local system drive. This process was working until 2022/05/07-10. No updates were done on the server in question but have used a separate machine on the network anyway.  

### Have you found a mitigation/solution?
Non as yet.

**Comment by nakulkar-msft** [comment]
Hi @hp-alanj, what do you mean by 'access the blob storage with Azure Storage Explorer'? All the errors in the log statement provided show that the connection was forcibly closed, and this points to a configuration error.

**Comment by hp-alanj** [comment]
It was our firewall that was updated. The issue was resolved.


Thank you
Alan Jordaan
Phone: (011) 874-1800 (ext:2004)  |  Email: ***@***.******@***.***>  |  www.hpattorneys.co.za<http://www.hpattorneys.co.za>



[Hammond Pole]

[https://www.hammondpole.co.za/wp-content/uploads/2021/06/HP_Warning.png]


You can now make a payment and view your accounts through our App by clicking the links below!  Find us on Facebook or WhatsApp.

***@***.***<https://appgallery.cloud.huawei.com/ag/n/app/C105051755>       ***@***.*** <https://apps.apple.com/za/app/hp-portal/id1598506502>       ***@***.*** <https://play.google.com/store/apps/details?id=za.co.hpd.portal.app>      ***@***.*** <https://www.facebook.com/HPAttorneys/>     ***@***.*** <https://bit.ly/30xScMn>


This e-mail (including attachments) is subject to the email disclaimer published on our website<https://www.hpattorneys.co.za/disclaimer/>.
Note: HP Attorneys will never change banking details via email. Any notification of amended banking details that appear to come from our office are to be ignored & disregarded. *If there are any queries, please contact our Customer Care Team directly. In the event of making a payment pursuant to an email purporting to have come from our offices changing account details, you will be liable for any losses you may incur as a result thereof. Before depositing funds into our Trust account, contact our customer care team to confirm the banking details.
