### ISSUE TITLE
AzCopy copy does not return the uploaded file's ETag in response headers

### ISSUE THREAD

**Issue by asafisser** [Azure/azure-storage-azcopy#1775]
### Which version of the AzCopy was used?
AzCopy 10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 11

### What command did you run?
azcopy copy "file.json" "https://..."

### What problem was encountered?
I uploaded a single file in this command, and I expected to receive the uploaded file's **ETag** in the response headers (either in CLI or in the job's log file).

### How can we reproduce the problem in the simplest way?
Just upload some blob into a Storage Account using the "azcopy copy" CLI command.

### Have you found a mitigation/solution?
No.
I can get the file's **ETag** when I upload it to Data Lake via API call, but not when using the AzCopy tool.

**Comment by htalluri9** [comment]
any update on this issue ?

**Comment by siminsavani-msft** [comment]
Hi there! Please try our latest AzCopy version (found [here](https://github.com/Azure/azure-storage-azcopy/releases)). ETag is displayed in the response header found in the log file. You will need to add `--log-level=DEBUG` to see all the response headers. 

I'm closing this issue as it is resolved. Please feel free to reply or open a new GitHub issue if there are any questions or concerns!
