### ISSUE TITLE
azcopy failing with "SIGBUS: bus error code=0x2..."

### ISSUE THREAD

**Issue by jonwbstr** [Azure/azure-storage-azcopy#178]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.0.5-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy jobs resume 77f9107e-0dd3-f640-7fd-1ae01d720d11 --destination-sas <snip> 2>&1|tee azcopy.log

### What problem was encountered?
Log file is located at: /root/.azcopy/77f9107e-0dd3-4640-7f d-1ae01d7207d1.log

20 Done, 0 Failed, 4 Pending, 0 Skipped, 24 Totalunexpected fault address 0x7efb96000d1b
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7efb96000d1b pc=0x459bd5]

goroutine 1212 [running]:
runtime.throw(0x9c5700, 0x5)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc426287940 sp=0xc426287920 pc=0x42be31
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:385 +0x273 fp=0xc426287990 sp=0xc426287940 pc=0x441373
runtime.memmove(0xc427a19265, 0x7efb96000000, 0xd9b)
	/usr/local/go/src/runtime/memmove_amd64.s:329 +0x3c5 fp=0xc426287998 sp=0xc426287990 pc=0x459bd5
bytes.(*Reader).Read(0xc42544b2c0, 0xc427a19265, 0xd9b, 0xd9b, 0xc426c9d7e8, 0x987380, 0xffffffffffffffff)
	/usr/local/go/src/bytes/reader.go:44 +0x92 fp=0xc4262879c8 sp=0xc426287998 pc=0x4cec82
github.com/Azure/azure-storage-azcopy/ste.(*bodyPacer).Read(0xc424ff8460, 0xc427a19265, 0xd9b, 0xd9b, 0xc426287b88, 0x644d9b, 0xa353a0)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/pacer.go:141 +0x74 fp=0xc426287a28 sp=0xc4262879c8 pc=0x858604
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.(*retryableRequestBody).Read(0xc424f3d3a0, 0xc427a19265, 0xd9b, 0xd9b, 0x644d9b, 0x1, 0x1)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/request.go:129 +0x51 fp=0xc426287a70 sp=0xc426287a28 pc=0x671141
net/http.transferBodyReader.Read(0xc427a2c000, 0xc427a19265, 0xd9b, 0xd9b, 0x40ee8d, 0xc420010000, 0x930c40)
	/usr/local/go/src/net/http/transfer.go:60 +0x56 fp=0xc426287ad0 sp=0xc426287a70 pc=0x64de86
io.(*LimitedReader).Read(0xc42799e1e0, 0xc427a19265, 0xd9b, 0xd9b, 0xc427932900, 0xc427910330, 0x4d1dad)
	/usr/local/go/src/io/io.go:446 +0x63 fp=0xc426287b18 sp=0xc426287ad0 pc=0x470373
bufio.(*Writer).ReadFrom(0xc4268ad680, 0xa30e80, 0xc42799e1e0, 0x7efc5c00b310, 0xc4268ad680, 0x1)
	/usr/local/go/src/bufio/bufio.go:703 +0xcd fp=0xc426287ba0 sp=0xc426287b18 pc=0x4d1eed
io.copyBuffer(0xa2fe20, 0xc4268ad680, 0xa30e80, 0xc42799e1e0, 0x0, 0x0, 0x0, 0x94e1e0, 0x13, 0x18)
	/usr/local/go/src/io/io.go:386 +0x31a fp=0xc426287c10 sp=0xc426287ba0 pc=0x47027a
io.Copy(0xa2fe20, 0xc4268ad680, 0xa30e80, 0xc42799e1e0, 0xc427a19263, 0x9c4b38, 0x2)
	/usr/local/go/src/io/io.go:362 +0x5a fp=0xc426287c70 sp=0xc426287c10 pc=0x46ff1a
net/http.(*transferWriter).WriteBody(0xc427a2c000, 0xa2fe20, 0xc4268ad680, 0x2, 0x2)
	/usr/local/go/src/net/http/transfer.go:337 +0x5fa fp=0xc426287d20 sp=0xc426287c70 pc=0x64fdaa
net/http.(*Request).write(0xc424f9c800, 0xa2fe20, 0xc4268ad680, 0x0, 0xc427910330, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:622 +0x6b2 fp=0xc426287e68 sp=0xc426287d20 pc=0x646e82
net/http.(*persistConn).writeLoop(0xc425664120)
	/usr/local/go/src/net/http/transport.go:1825 +0x1ea fp=0xc426287fd8 sp=0xc426287e68 pc=0x65c4ca
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc426287fe0 sp=0xc426287fd8 pc=0x458fa1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1238 +0x97f
<snip>

### How can we reproduce the problem in the simplest way?
Files over 1TB appear to have this issue more frequently, fault can happen instantly or after several minutes after a transfer has begun

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @jonwbstr, thank you for reaching out!

Could you please share the log file with us for additional insights? We scrub off the SAS signatures so you don't have to worry about leaking the credentials.

What kind of disk are you uploading from? Are you running from an Azure VM or on premise?

**Comment by jonwbstr** [comment]
I emailed you from my work account, don't want to post this type of log online. Onprem machine from a physical disk formatted as vmfs?

**Comment by zezha-msft** [comment]
Hi @jonwbstr, thanks for your patience, this problem should be fixed now in the [latest version](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.0.6), which stopped leveraging memory mapped files, so these weird memory errors should go away now.

Please have a try, and let us know if you still encounter issues. Thank you!
