### ISSUE TITLE
Copying blobs between stroage accounts - ADLS Gen2

### ISSUE THREAD

**Issue by JosefPrakljacic** [Azure/azure-storage-azcopy#1781]
[Copying blobs between storage accounts - Private Endpoints](https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints#copying-blobs-between-storage-accounts)

Is there an ETA when AzCopy copy will work work for ADLS Gen2 that are using Private Link? Since the above mentioned article states that: "Private endpoints that target the Data Lake Storage Gen2 or the File resource are not yet supported."

**Comment by Luisrod12** [comment]
Any updates on this request? Thanks in advance.

**Comment by JosefPrakljacic** [comment]
Unfortunately I didn’t receive a response

**Comment by nakulkar-msft** [comment]
Hi, this feature needs to be supported by Azure Service. AzCopy repo is not the right place to track or report this. Please use https://feedback.azure.com/d365community/forum/a8bb4a47-3525-ec11-b6e6-000d3a4f0f84
