### ISSUE TITLE
Using SAS token to copy from local UNC path to File Storage on Azure is throwing errors: ResourceNotFound and ShareSizeLimitReached

### ISSUE THREAD

**Issue by mdonnaruma** [Azure/azure-storage-azcopy#1791]
### Which version of the AzCopy was used? 
`10.15.0`

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2012R2

### What command did you run?
`./azcopy.exe copy \\local-nas\backitup\ https://redacted.file.core.usgovcloudapi.net/backup/?SAS Token --overwrite=false --from-to=LocalFile --follow-symlinks --put-md5 --follow-symlinks --disable-auto-decoding=false --cap-mbps=25 --recursive --log-level=ERROR --check-length=false --s2s-preserve-access-tier=false 
`
### What problem was encountered?
Some files are found and are properly ignored due to already existing in the target location:
`2022/05/18 15:02:57 WARN: [P#0-T#11] \\?\UNC\local-nas\backitup\someservername\somefile.tar.gz File already exists, so will be skipped Dst: https://redacted.file.core.usgovcloudapi.net/backup/backitup/someservername/somefile.tar.gz?se=SAS Token`

`2022/05/18 15:02:57 ==> OUTGOING REQUEST (Try=1)`
`   HEAD https://redacted.file.core.usgovcloudapi.net/backup/backitup/someservername/somefile.tar.gz?SAS Token`
`   User-Agent: [AzCopy/10.15.0 Azure-Storage/0.8.0 (go1.17.9; Windows_NT)]
`   X-Ms-Client-Request-Id: [974d7a2c-68c5-46ec-508b-370e1f2b5f90]
`   X-Ms-Version: [2020-10-02]`

4000 rows later in the log file, these start showing up

`2022/05/18 15:03:00 ==> REQUEST/RESPONSE (Try=1/26.0644ms, OpTime=26.0644ms) -- RESPONSE STATUS CODE ERROR
PUT https://redacted.file.core.usgovcloudapi.net/backup/backitup/someotherfolder2/someotherfile2.trn?SAS Token&timeout=901`
`User-Agent: [AzCopy/10.15.0 Azure-Storage/0.8.0 (go1.17.9; Windows_NT)]`
`X-Ms-Cache-Control: []`
`X-Ms-Client-Request-Id: [bbeaac29-01cf-4764-44dd-55d7e12a8c09]`
`X-Ms-Content-Disposition: []`
`X-Ms-Content-Encoding: []`
`X-Ms-Content-Language: []`
`X-Ms-Content-Length: [10240]`
`X-Ms-Content-Type: [application/octet-stream]`
`X-Ms-File-Attributes: [Archive]`
`X-Ms-File-Creation-Time: [2022-05-03T05:46:01.2969820Z]`
`X-Ms-File-Last-Write-Time: [2022-05-03T05:46:01.3281823Z]`
`X-Ms-File-Permission: [inherit]`
`X-Ms-Type: [file]`
`X-Ms-Version: [2020-10-02]`
`RESPONSE Status: 403 The specified share is full.`
`Content-Length: [218]`
`Content-Type: [application/xml]`
`Date: [Wed, 18 May 2022 15:02:59 GMT]`
`Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]`
`X-Ms-Client-Request-Id: [bbeaac29-01cf-4764-44dd-55d7e12a8c09]`
`X-Ms-Error-Code: [**ShareSizeLimitReached**]`
`X-Ms-Request-Id: [eec053b0-601a-0005-2dc8-6acbed000000]`
`X-Ms-Version: [2020-10-02]`
`Response Details: ﻿**ShareSizeLimitReached** The specified share is full. `

Meanwhile our azure drive has 5TB of data and sized for up to 100TB. So there's no way we've run out of space.

### How can we reproduce the problem in the simplest way?
Not sure 

### Have you found a mitigation/solution?
Robocopy to a drive mapped to azure doesn't give any grief.

**Comment by Edgaras91** [comment]
@mdonnaruma How did you fix this if you have? I am facing same issue
