### ISSUE TITLE
`--log-level` argument gets ignored

### ISSUE THREAD

**Issue by Storm-BE** [Azure/azure-storage-azcopy#1794]
### Which version of the AzCopy was used? 
AzCopy 10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`azcopy copy --recursive 'SourceBlobContainerUrl' 'TargetAzureFilesShareUrl' --check-length=false --log-level=ERROR`

### What problem was encountered?
The `--log-level=ERROR` flag gets ignored.
Huge log files (many gigabytes) still get created in my user profile directory.
I also tried different values (`NONE`, `FATAL`), different syntax (`--log-level ERROR`) and different orders of arguments (flags before positional arguments) to no avail.

I tested this on multiple machines.

### How can we reproduce the problem in the simplest way?
Run an `azcopy copy` as described above on version 10.15.0 :)

### Have you found a mitigation/solution?
I don't have this issue with other versions I've tested:
- v10.14.1
- v10.10.0

So downgrading to v10.14.1 is my workaround for now

**Comment by tiverma-msft** [comment]
closing this issue now.

**Comment by tiverma-msft** [comment]
will be closed when we release the fix.

**Comment by nakulkar-msft** [comment]
Fixed in 10.16.0.
