### ISSUE TITLE
azcopy login fails silently

### ISSUE THREAD

**Issue by ant0nsc** [Azure/azure-storage-azcopy#1805]
### Which version of the AzCopy was used? 

 10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)

WSL on Windows 11 

### What command did you run?

```
> azcopy login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <redacted> to authenticate.
INFO: Logging in under the "Common" tenant. This will log the account in under its home tenant.
INFO: If you plan to use AzCopy with a B2B account (where the account's home tenant is separate from the tenant of the target storage account), please sign in under the target tenant with --tenant-id
INFO: Login succeeded.
> azcopy login status
INFO: You are currently not logged in. Please login using 'azcopy login'
```

### What problem was encountered?
Login appears to work successfully, but any subsequent `azcopy` operation fails, saying that I'm not authenticated.

### Have you found a mitigation/solution?

#452 lists a workaround: 
```
sudo apt install keyutils
keyctl new_session
azcopy login
keyctl show
```
@zezha-msft , happy to provide more details if needed

**Comment by smrfeld** [comment]
Encountered the same issue. Only comes up on WSL.
@ant0nsc thanks for your workaround, this worked for me too.

**Comment by nakulkar-msft** [comment]
same as #1734

**Comment by NicholasDawson** [comment]
Encountering same issue but workaround worked.

System information:
Windows 10 Enterprise
Version	10.0.19045 Build 19045

WSL2 - 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

AZCOPY Version 10.19.0
