### ISSUE TITLE
Missing "list" permission for SAS on Azure portal, and thus azcopy failed to copy blob directories.

### ISSUE THREAD

**Issue by dunalduck0** [Azure/azure-storage-azcopy#1810]
### Which version of the AzCopy was used? 
I am using azcopy version 10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)
I am using Linux

### What command did you run?
I am downloading a single file or all files from a blob directory with the following commands:
```
azcopy copy --recursive "https://<path1>.blob.core.windows.net/<path2>/output_dir/file1.txt?sp=<SAS>" ./
azcopy copy --recursive "https://<path1>.blob.core.windows.net/<path2>/output_dir/*?sp=<SAS>" ./
```

### What problem was encountered?
Downloading a single file worked fine but downloading all files failed (see errors below). I guess it's because SAS lacks "list" permission to the directory.
```
failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Details: (none)
```
I used to see "list" permission in Azure portal, but unfortunately, I cannot find it anymore now and thus cannot add it to generate SAS. Can someone advise how to guarant "list" permission to SAS?

![image](https://user-images.githubusercontent.com/51274745/170890110-e40742e3-f5cd-4795-ae41-eb3070fa413c.png)

### How can we reproduce the problem in the simplest way?
Can you check if you have "list" permission when generating SAS from Azure portal?

### Have you found a mitigation/solution?
No.

**Comment by nakulkar-msft** [comment]
Hi @dunalduck0. please check if you've enough permissions to generate SAS. You should have Storage Blob Data Contributor role to have these permissions.

**Comment by dunalduck0** [comment]
Thank you @nakulkar-msft for pointing out permissions. I am actually a "contributor" of the Azure Machine Learning resources. The "workspaceblobstorage" comes automatically with AML resource and I've no idea what role I am. What surprised me is that I seem to have two different sets of permissions to the same blob directory.

1. if I start from the "workspaceblobstorage", click through and navigate into the directory manually, then I have the "list" permission! AzCopy was successful downloading the entire directory as well.

![image](https://user-images.githubusercontent.com/51274745/171270108-0980196f-f3b8-413e-acd3-31112aa3eb63.png)

2. if I click into the directory directly from an AML run's output port, I don't have the "list" permission, and AzCopy failed as described in the thread. This is really confusing as they seem to be the same datastore and same path in the datastore.

![image](https://user-images.githubusercontent.com/51274745/171270318-0ae8ebcb-15ec-4a2a-906c-0f0a864e48f8.png)

At least I am unblocked, though I don't know why. I hope this is by design.
