### ISSUE TITLE
Failed to copy empty folders when trying to copy from a storage account

### ISSUE THREAD

**Issue by chuckz1321** [Azure/azure-storage-azcopy#1812]
### What problem was encountered?
It's not able to copy empty folder to destination in ADLS Gen2 when run the command above. But it's able to create empty folder in destination with the command when I add '--preserve-permissions=true' to it.

Without --preserve-permissions : Just one file copied. 
![image](https://user-images.githubusercontent.com/33536264/171125883-f5004286-048d-43b5-a5f1-1d8ccb296293.png)

### Have you found a mitigation/solution?
Added '--preserve-permissions=true' to create empty folders.

**Comment by nakulkar-msft** [comment]
Hi @chuckz1321, this is behavior of Gen2 storage accounts. Please use preserve-permissions to create empty folders.
