### ISSUE TITLE
Cannot use S3 source that is non-AWS

### ISSUE THREAD

**Issue by ElMudo** [Azure/azure-storage-azcopy#1817]
### Which version of the AzCopy was used?

10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

### What command did you run?

```
./azcopy cp "https://s3.objectstore.eu/mybucket/ams_schema/readme.txt" 'https://objectstoretestaccount.file.core.windows.net/test-azcopy-001?<SAS>'
```

### What problem was encountered?

Source is not recognised as an S3 bucket. Error messages indicates that the source is treated as a local file:

> failed to scan path /Users/conorwyse/dev/copy/https:/s3.objectstore.eu/mybucket/ams_schema/readme.txt

The source location has S3 emulation and an S3 token has been saved to the environment variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`).

Try the command again changed the domain from `objectstore.eu` to `amazonaws.com`. The source is now treated as a remote location and as an S3 bucket. (Of course, the path and file are incorrect.)

```
./azcopy cp "https://s3.amazonaws.com/mybucket/ams_schema/readme.txt" 'https://objectstoretestaccount.file.core.windows.net/test-azcopy-001?<SAS>'
```

### How can we reproduce the problem in the simplest way?

take any valid/working `azcopy copy` command that has an Amazon AWS S3 bucket as source. Change `amazonaws.com` to `objectstore.eu`. Instead of getting an error message about failed authentication or that the path or file is not found at objectstore.eu, the error will be about not finding a local file.

### Have you found a mitigation/solution?

Seemingly only AWS is supported.The azcopy code matches explicitly on AWS domains:

```
const s3HostPattern = "^(?P<bucketName>.+\\.)?s3[.-](?P<dualStackOrRegionOrAWSDomain>[a-z0-9-]+)\\.(?P<regionOrAWSDomainOrCom>[a-z0-9-]+)"
```

It would be better to match on "https://s3/." Then we could use `azcopy` to copy from other S3 sources.

I don't really expect `azcopy` to fully support all S3 sources, but it would be nice if we could try using this tool "as is" for sources other than AWS with the knowledge that the tool is offering just "best effort".

**Comment by nakulkar-msft** [comment]
#1815
