### ISSUE TITLE
azcopy list hangs

### ISSUE THREAD

**Issue by funcker2** [Azure/azure-storage-azcopy#1827]
### Which version of the AzCopy was used? 
10.14.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Win 10

### What command did you run?
azcopy list https://(anything_can_be_here)azuresa.blob.core.windows.net?${SAS_token}
### What problem was encountered?
If any name of StorageAccount is ended with 'azuresa' process hangs for ever
### How can we reproduce the problem in the simplest way?
azcopy list https://xxxazuresa.blob.core.windows.net?${SAS_token}
### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
Fixed in 10.16
