### ISSUE TITLE
Wrong error message returned during blob to blob copy when file not found

### ISSUE THREAD

**Issue by kevlarmpowered** [Azure/azure-storage-azcopy#1830]
### Which version of the AzCopy was used? 

azcopy version 10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

$sourcesastoken = New-AzStorageAccountSASToken -Context $sourcestoragecontext -Service Blob -ResourceType Service,Container,Object -Permission "rl" -StartTime $ContainerStartDate -ExpiryTime $ContainerEndDate
$targetsastoken= New-AzStorageAccountSASToken -Context $targetstoragecontext -Service Blob -ResourceType Service,Container,Object -Permission "rwdl" -StartTime $ContainerStartDate -ExpiryTime $ContainerEndDate

$source = "https://mysource.blob.core.windows.net/sourcecontainer/non-existant-file.txt' +$sourcesastoken
$target = "https://mytarget.blob.core.windows.net/targetcontainer/' +$targetsastoken

.\azcopy.exe cp $source $target

### What problem was encountered?

azcopy returns the error "failed to perform copy command due to error: cannot use directory as source without --recursive or a trailing wildcard (/*)" when the file in the source does not exist instead of "file not found"

### How can we reproduce the problem in the simplest way?

Try to do a blob to blob copy with SAStoken at the source and target where the source file is missing or does not exist in the source blob.

### Have you found a mitigation/solution?

Use the right URL to point to the file I want to copy... This was totally user error, but the user error exposed a wrongly returned error message.

**Comment by nakulkar-msft** [comment]
#1418
