### ISSUE TITLE
Azcopy job resume restarts from progress 0%

### ISSUE THREAD

**Issue by eileen0290** [Azure/azure-storage-azcopy#1831]
##### Note: The version is visible when running AzCopy without any argument
10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
I copy the vhd from Azure to local PC, thus, I use the following command to do resume.
Azcopy jobs resume "job-id" --source-sas=”sas token from disk export URL”

### What problem was encountered?
The progress restarted from 0%. Does this mean it resume from the beginning?

### How can we reproduce the problem in the simplest way?
1) Go to VM disk, click disk export. Then we can get a URL for downloading vhd.
2) Execute azcopy copy command from local side. Like: azcopy copy "disk vhd URL" "C:\disk"
3) Let copy operation failed.
4) Use job resume command to resume the copy operation.

### Have you found a mitigation/solution?
N/A

**Comment by nakulkar-msft** [comment]
Hi @eileen0290, AzCopy, at this point, does not allow to resume transfers at file level. Every file will be transferred from beginning if azcopy job is resumed. We're working on improving this.
