### ISSUE TITLE
Why does azcopy check that each file exist?

### ISSUE THREAD

**Issue by itaihay** [Azure/azure-storage-azcopy#1832]
##### Note: The version is visible when running AzCopy without any argument
10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy copy https://blob.windows.net/PATH/TO/MAIN/FOLDER/ /DESTINATION/FOLDER --overwrite=false --check-length=false --list-of-files file_list.txt`

### What problem was encountered?
Azcopy creates a request for each file, and by that slowing the process.
There should be a method of just trying to copy the files and skip if failed. 

Scanning log:

```
2022/06/20 11:53:53 ==> REQUEST/RESPONSE (Try=1/6.406603ms, OpTime=6.514003ms) -- RESPONSE SUCCESSFULLY RECEIVED
   HEAD <FILE_PATH>?timeout=901
   X-Ms-Request-Id: [...]

2022/06/20 11:53:53 ==> REQUEST/RESPONSE (Try=1/10.477304ms, OpTime=48.707522ms) -- RESPONSE SUCCESSFULLY RECEIVED
   HEAD <FILE_PATH>?timeout=901
   X-Ms-Request-Id: [...]
.
.
.

```

**Comment by nakulkar-msft** [comment]
Hi @itihay, this is by design. Knowing the file details like size, metadata, tier helps us schedule blocks in much efficient way.

**Comment by itaihay** [comment]
Hello @nakulkar-msft thank you for the reply. I believe the ability to avoid this could vastly improve the performance when copying many files at once

**Comment by fabriziofortino** [comment]
@nakulkar-msft we are having the same problem copying many files across different regions:

```
2022/09/16 13:24:49 ==> REQUEST/RESPONSE (Try=1/88.950271ms, OpTime=369.264181ms) -- RESPONSE SUCCESSFULLY RECEIVED
   HEAD <FILE>
   X-Ms-Request-Id: [...]
```

We use `--include-path` with the list of files to download. I understand the reasons this is needed. I was wondering if there could be potential improvements here. Example: make a bulk request with multiple file ids to reduce the number of calls.
