### ISSUE TITLE
Azcopy login command does not work. Please help

### ISSUE THREAD

**Issue by onenessboy** [Azure/azure-storage-azcopy#1840]
### Which version of the AzCopy was used? 
Used azcopy_linux_amd64_10.15.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (ubuntu VM) via Docker Image

### What command did you run?
 ```
            echo "export AZCOPY_SPA_CLIENT_SECRET=${clientsecret}" >> $BASH_ENV
            echo "export AZCOPY_AUTO_LOGIN_TYPE=SPN" >> $BASH_ENV
            echo "export AZCOPY_SPA_APPLICATION_ID=$ARM_CLIENT_ID" >> $BASH_ENV
            echo "export AZCOPY_TENANT_ID=$ARM_TENANT_ID" >> $BASH_ENV
            source $BASH_ENV
            printenv #this is printing all values correctly
            echo "Hello" > /tmp/magic.txt
            wget https://aka.ms/downloadazcopy-v10-linux
            tar -xvf downloadazcopy-v10-linux
            sudo mkdir /usr/bin/mydir
            sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/mydir
            cd /usr/bin/mydir
            ls -lrt
            sudo chmod 777 azcopy
            sudo apt install keyutils
            keyctl session workaroundSession
            ./azcopy login --service-principal --application-id $AZCOPY_SPA_APPLICATION_ID --tenant-id $AZCOPY_TENANT_ID
            ./azcopy --source /tmp/magic.txt--destination https://xxxxxxxxxxxxxx.blob.core.windows.net/client-a/magic.txt
```
### What problem was encountered?

I have used keyctl session workaround as per different issues on this repo, but 

I am getting error at 
`keyctl_join_session_keyring: Operation not permitted`

### How can we reproduce the problem in the simplest way?

Issue same commands above

### Have you found a mitigation/solution?

somebody suggested to use keyctl, but its not working

**Comment by jakebreen** [comment]
Hi, I've had the same issue. I found that removing the seccomp docker file resolves the issue for testing purposes but this is not recommended.

Has anyone had any luck modifying the docker seccomp file enough to allow `azcopy login` to work?

**Comment by jakebreen** [comment]
Update:

I've fixed `azcopy login` not working on Dockeriszed Linux containers.

The following Linux system commands are blocked by docker through the default seccomp profile; "add_key", "keyctl" and "request_key".

They must be added to the profile using an `SCMP_ACT_ALLOW` action.

**Comment by nakulkar-msft** [comment]
Hi, this is a problem with your environment.  Use [auto-login](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)).
