### ISSUE TITLE
GetBlobProperties operation from unknow private IP address

### ISSUE THREAD

**Issue by yuriwoof** [Azure/azure-storage-azcopy#1842]
##### Note: The version is visible when running AzCopy without any argument

10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows Server 2019 Datacenter

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

```
PS C:\Users\azureuser> azcopy sync --log-level NONE --delete-destination true "https://(Source Storage Accout).core.windows.net/src?(BLOB SAS)" "https://(Destination Storage Account).blob.core.windows.net/dst?(BLOB SAS)"
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 1e08da1d-dd81-8048-7bd9-e76a85e17e92 has started
Log file is located at: C:\Users\azureuser\.azcopy\1e08da1d-dd81-8048-7bd9-e76a85e17e92.log

100.0 %, 1 Done, 0 Failed, 0 Pending, 1 Total, 2-sec Throughput (Mb/s): 4.1587

Job 1e08da1d-dd81-8048-7bd9-e76a85e17e92 Summary
Files Scanned at Source: 2
Files Scanned at Destination: 1
Elapsed Time (Minutes): 0.0336
Number of Copy Transfers for Files: 1
Number of Copy Transfers for Folder Properties: 0
Total Number Of Copy Transfers: 1
Number of Copy Transfers Completed: 1
Number of Copy Transfers Failed: 0
Number of Deletions at Destination: 0
Total Number of Bytes Transferred: 1048576
Total Number of Bytes Enumerated: 1048576
Final Job Status: Completed
```

### What problem was encountered?

The operation itself was successful, however, we can see GetBlobProperties operation against source storage account from unknown private address was recorded as 403 error.
What is this IP used for? and can this error be ignorable? If not, it would be helpful if you could advise how they allow this using storage firewall rule.

```
	TenantId　<Tenant ID>
	TimeGenerated [UTC]　2022-07-04T13:52:15.453Z
	AccountName　<Source Storage Account>
	Location　Japan East
	Protocol　HTTPS
	OperationName　GetBlobProperties
	AuthenticationType　SAS
	StatusCode　403
	StatusText　AuthorizationFailure
	DurationMs　4
	ServerLatencyMs　4
	Uri　https://<Source Storage Account>a.blob.core.windows.net:443/src/dummy2?se=2022-07-04T19%3A36%3A29Z&sig=XXXXX&sp=racwdli&spr=https&sr=c&st=2022-07-04T11%3A36%3A29Z&sv=2021-06-08
	CallerIpAddress　10.138.214.105:49551
	CorrelationId　c56ecdf0-f01e-0081-12ad-8f69c5000000
	SchemaVersion　1.0
	OperationVersion　2020-10-02
	AuthenticationHash　key1(1D152CD0013450F0ACEE00BF32B57516D449A482747BD608C21031968976DEF1),SasSignature(C115561F95E399B10E0AEACE8587023BED24268273686B92FAD71E865E9194EA)
	UserAgentHeader　AzCopy/10.15.0 Azure-Storage/0.15 (go1.17.9; Windows_NT)
	ClientRequestId　13bfbb47-201e-003e-59ad-8f6f73000000
	ServiceType　blob
	RequestHeaderSize　428
	ResponseHeaderSize　168
	Category　StorageRead
	TlsVersion　TLS 1.2
	SourceSystem　Azure
	Type　StorageBlobLogs
_ResourceId　/subscriptions/93b7ca88-d2cc-4381-97ec-f99f3a702495/resourcegroups/labstorage/providers/microsoft.storage/storageaccounts/labsrcsa/blobservices/default
```

![image](https://user-images.githubusercontent.com/1770342/177271369-0e490e0b-060d-48db-a3d2-1ecfc9e68a98.png)

### How can we reproduce the problem in the simplest way?

	1. Deploy Windows Server 2019 as client VM
           -Network Address: 10.20.0.0/16
           -Subnet Address: 10.20.0.0/24
	2. Create 2 vnet integrated storage account and enable diagnostics (stored data in  LA)
	3. Download azcopy and run "azcopy sync" command

**Comment by nakulkar-msft** [comment]
Hi @yuriwoof, we cannot determine why the call failed with 403. However, the call was to get properties of the source blob to optimize transfer parameters and if we do not get a successful response, azcopy will ignore that and proceed with transfer. Log file would help me comment more, but this is benign.
