### ISSUE TITLE
log-level ERROR ignored / not support in 10.15.0

### ISSUE THREAD

**Issue by foxmeyson** [Azure/azure-storage-azcopy#1845]
### Which version of the AzCopy was used? 

10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux (Ubuntu 20.04)

### What command did you run?

`azcopy cp SRC_Storage?SAStoken DST_Storage?SAStoken --recursive=true --log-level=ERROR --overwrite=false`

### What problem was encountered?

in version 10.15.0, when azcopy running multiple times, the --log-level option is **ignored** and INFO is always written.
**In 10.14.1 - this is not reproduced.** on the same server and in the same environment with the same tokens and storage accounts

### How can we reproduce the problem in the simplest way?

0) Install on Linux (Ubuntu 20.04) azcopy 10.15.0
1) multiple run azcopy `azcopy cp SRC_Storage?SAStoken DST_Storage?SAStoken --recursive=true --log-level=ERROR --overwrite=false` :
        sequentially one after another, waiting for the execution of the previous command, run 8-10 times the azcopy
2) check `cat ~/.azcopy/*`
3) see that in `~/.azcopy/*` log files INFO is always written

### Have you found a mitigation/solution?

In 10.14.1 - this is not reproduced.
Used azcopy 10.14.1

**Comment by nakulkar-msft** [comment]
Fixed in 10.16.0.
