### ISSUE TITLE
Azcopy command should accept a file with a list of blobs as an argument

### ISSUE THREAD

**Issue by chibulcuteanu** [Azure/azure-storage-azcopy#1848]
##### Note: The version is visible when running AzCopy without any argument
10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (docker)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
```
azcopy copy --include-path ${LIST_OF_BLOBS} ${CONNECTION_STRING} ${DOWNLOAD_PATH}
```

LIST_OF_BLOBS is a comma separated list of blobs.

### What problem was encountered?
This is an improvement proposal. The problem is that the LIST_OF_BLOBS cannot exceed 64k chars, which means that a limited number of blobs can be downloaded at a time. 

E.g if a blob ID is 30 chars long, an azcopy command is limited to downloading ~2.1K blobs at one time. 
If azcopy would accept a file as an argument, which would contain the list of blobs then more blobs could be downloaded in one azcopy process. 

### How can we reproduce the problem in the simplest way?
Run azcopy the following azcopy command:
```
azcopy copy --include-path ${LIST_OF_BLOBS} ${CONNECTION_STRING} ${DOWNLOAD_PATH}
```
with a LIST_OF_BLOBS that exceeds 64k chars.

### Have you found a mitigation/solution?
Current workaround is to split the LIST_OF_BLOBS into chunks that azcopy can manage (less thank 64k chars) and run multiple azcopy commands for each chunk.

**Comment by nakulkar-msft** [comment]
Hi @chibulcuteanu use the below command
azcopy copy <source><destination> --list-of-files <path to list-of-files.txt>, where list-of-files.txt contains a list of files to be transferred with each file specified on a separate line.
