### ISSUE TITLE
Azcopy using too much memory

### ISSUE THREAD

**Issue by BenHesketh21** [Azure/azure-storage-azcopy#1850]
### Which version of the AzCopy was used? 
[azcopy_linux_amd64_10.15.0.tar.gz](https://azcopyvnext.azureedge.net/release20220511/azcopy_linux_amd64_10.15.0.tar.gz)
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux Container

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy copy SOURCE_ACCOUNT_URL/dir DEST_ACCOUNT_URL/dir --recursive=true --preserve-smb-info=true --preserve-permissions=true --overwrite=ifSourceNewer --log-level=ERROR --include-after 2022-07-18T13:23:50Z

### What problem was encountered?

AZCOPY_BUFFER_GB is set but to no avail (I guessed not, with it especially mentioning uploads and downloads)
include_after has been set to a week, day and hour before the current date it makes 0 difference to the amount of memory being used.

Azcopy uses too much memory, I'm running it in a container and it has 2 CPUS and 2GiB of memory and it runs out of memory very quickly.

How much memory should I give it and should the include-after be helping?

I am copying over a large number of small files which I know will cause it problems but nowhere as many as the documentation says it will struggle at, 3 million at the most.

### How can we reproduce the problem in the simplest way?

Copy a large number of small files and run with and without include after

### Have you found a mitigation/solution?

N/A

**Comment by nakulkar-msft** [comment]
Hi, azcopy is designed to use up significant memory, and compute to transfers. 2cores are very less. Please upgrade atleast to a 4 core machine

**Comment by chrishonselaar** [comment]
@nakulkar-msft unsure why you closed this as "completed"? 
"azcopy is designed to use up significant memory" is very vague and non-actionable. How much memory should we allocate? And how is using up significant memory a design choice of itself? What is it traded off against, and why? Why is it not able to manage its own memory use?
