### ISSUE TITLE
AzCopy Node failing in Azure Function with 'UnexpectedQuit'

### ISSUE THREAD

**Issue by grainerm** [Azure/azure-storage-azcopy#1854]
##### Note: The version is visible when running AzCopy without any argument
* "@azure-tools/azcopy-node": "^2.6.0"
* AzCopy 10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
* Windows => works
* Mac => works
* Azure Function on Windows => does not work

### What command did you run?
Azure Function with HTTP trigger

import { AzCopyClient } from "@azure-tools/azcopy-node";

export default async function (context, req) {
  let copyClient = new AzCopyClient();
  let src = {
    type: "RemoteSas",
    sasToken:
      "\<sas-token>",
    resourceUri: "https://\<account>.blob.core.windows.net/\<container>",
    path: "",
    useWildCard: false,
  };
  let dst = {
    type: "RemoteSas",
    sasToken:
      "\<sas-token>",
    resourceUri: "https://\<account>.blob.core.windows.net/<container>",
    path: "/\<path>",
    useWildCard: false,
  };
  let opt = {
    recursive: true,
    fromTo: "BlobBlob",
    overwriteExisting: true,
    logLevel: "DEBUG",
  };
  let jobId = await copyClient.copy(src, dst, opt);
  let status;
  while (!status || status.StatusType !== "EndOfJob") {
    let jobInfo = await copyClient.getJobInfo(jobId);
    status = jobInfo.latestStatus;
    await new Promise((resolve, reject) => setTimeout(resolve, 1000));
    context.log(jobInfo);
  }
}

### What problem was encountered?
The AzCopyClient does not work when running as Azure Function. Output throws 'UnexpectedQuit' error message.
Same code works locally on Windows and Mac.

[Information] {
  "latestStatus":{
     "StatusType":"EndOfJob",
     "ErrorMsg":"",
     "ActiveConnections":0,
     "CompleteJobOrdered":false,
     "JobStatus":"Failed",
     "TotalTransfers":0,
     "TransfersCompleted":0,
     "TransfersFailed":0,
     "TransfersSkipped":0,
     "PercentComplete":0,
     "BytesOverWire":0,
     "TotalBytesTransferred":0,
     "TotalBytesEnumerated":0,
     "FailedTransfers":null,
     "SkippedTransfers":null,
     "IsDiskConstrained":false,
     "TimeStamp":"Mon Jul 25 2022"
  },'

  **"errorMessage":"UnexpectedQuit",**
  "logFileLocation":"undefined",
  "scanningStarted":false,
  "canceled":false,
  "killed":false,
  "command":"./azcopy.exe copy \"https://\<account>.blob.core.windows.net/\<container>?\<sas-Token>\" \"https://\<account>.blob.core.windows.net/\<container>?\<sas-token>\" --overwrite=true --from-to=BlobBlob --recursive --log-level=DEBUG;\n",
  "promptMessage":"undefined",
  "lastMessageTime":"undefined"
}

### How can we reproduce the problem in the simplest way?
Create index.mjs file with above code and deploy to Windows Azure Function.

---
When re-writing the code to the following, it runs in Kudu at least with `node index.mjs`, without any error:

export default async function main(req) {
  ...
}

main ();

### Have you found a mitigation/solution?
No.

**Comment by JasonYeMSFT** [comment]
Usually unexpected quit means AzCopy crashes before emitting a proper "EndOfJob" status message. To diagnose the real cause, you can try executing a sample command directly (e.g. via NodeJS childProcess APIs) that triggers this failure and log the standard output. If AzCopy crashed, it will print a stack trace at the location where it crashed.

**Comment by grainerm** [comment]
Thanks for the hint. I found out that the default log and job plan location can't be accessed by the Azure function. Passing the following settings to the client solved the problem: 

copyClient.setEnvVars({
    AZCOPY_LOG_LOCATION: "C:\\local\\Temp\\.azcopy",
    AZCOPY_JOB_PLAN_LOCATION: "C:\\local\\Temp\\.azcopy",
  });

**Comment by gapra-msft** [comment]
Hi @graierm, it looks like you were able to find a workaround to solve this issue so I will go ahead and close it. Please feel free to reopen or create a new issue if you need further assistance.
