### ISSUE TITLE
Which firewall ports to which FQDNs/URLs need to opened for azcopy and how the proxy settings have to be configured

### ISSUE THREAD

**Issue by sezginr** [Azure/azure-storage-azcopy#1855]
### Which version of the AzCopy was used? 
10.13.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy login

### What problem was encountered?

INFO: Proxy detected: https://azcopyvnextrelease.blob.core.windows.net -> //******.***.**.**:8000
INFO: Proxy detected: https://login.microsoftonline.com -> //-> //******.***.**.**:8000

adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS700027
: The certificate with identifier used to sign the client assertion is not registered on application. [Reason - The key was not found.

I am using azcopy with a service principal and a certificate and Azure AD Authentication. I get the error above on an on prem Windows server. On an Azure Windows Server VM azcopy works fine with the same service principal and certificate. I believe this is not an azcopy issue, but a matter of opening the necessary firewall ports to the relevant Azure/Microsoft FQDN/URLs and having the correct proxy configuration.  Could you please advise which target FQDN/URL/port pairs have to accessible and how the proxy configuration has to be done for azcopy on prem to function without any connectivity related issues. 

I intend to do some tests with Storage Explorer as well, so if any additional FQDN/URL/Port and proxy configuration is needed for Storage Explorer could you please add the relevant details too.

### How can we reproduce the problem in the simplest way?
Not sure. 

### Have you found a mitigation/solution?
No

**Comment by adreed-msft** [comment]
Hi there, @sezginr!

It sounds like the client certificate is possibly getting overwritten by your proxy. I'm not sure about the configuration of your particular proxy unfortunately.

Regards,
Adele

**Comment by sezginr** [comment]
Hi Adele,

Thanks for your reply.
We have made some progress, now azcopy version 10.13.0 authenticates (explicit login and autologin), but the latest version 10.16.0 does not and gives the error below. The only difference is the azcopy version, everything else is the same - same server,same proxy settings, same azcopy service principal and certificate.

Failed to perform login command: 
adal: Failed to execute the refresh request. Error = 'Post "https://login.microsoftonline.com/18ed93f5-e470-4996-b0ef-9554af9
85d50/oauth2/token?api-version=1.0": dial tcp 20.190.160.22:443: connectex: No connection could be made because the target ma
chine actively refused it.'

Regards,

Sezgin

**Comment by adreed-msft** [comment]
Interesting to hear. I'm not certain we made any specific changes to the login process between 10.13.0 and 10.16.0. Do any other versions in between work? It'd be useful to know where the break begins, so we might be able to track it down.

**Comment by sezginr** [comment]
Unfortunately I don't have any versions between 10.13.0 and 10.16.0. I am not sure if anything is wrong/broken with version 10.16.0, it could be that it has different requirements for allowed URLs/FQDNs and we have not met them.

**Comment by adreed-msft** [comment]
Let me get you some download URLs for those.

https://azcopyvnextrelease.blob.core.windows.net/release20220228/azcopy_windows_amd64_10.14.0.zip
https://azcopyvnextrelease.blob.core.windows.net/release20220315/azcopy_windows_amd64_10.14.1.zip
https://azcopyvnextrelease.blob.core.windows.net/release20220511/azcopy_windows_amd64_10.15.0.zip

Could you test each of these and tell me when the issue starts to present?

**Comment by sezginr** [comment]
Thanks.

I tried all 3 versions in Powershell on a new server where v.10.13.0 works and got the same error below with all:

"INFO: If you set an environment variable by using the command line, that variable will be readable in your command line history. Consider clearing variables that contain credentials from your 
command line history.  To keep variables from appearing in your history, you can use a script to prompt the user for their credentials, and to set the environment variable.

Failed to perform login command: 
adal: Failed to execute the refresh request. Error = 'Post "https://login.microsoftonline.com/18ed93f5-e470-4996-b0ef-9554af985d50/oauth2/token?api-version=1.0": dial tcp 20.190.159.73:443: i/o timeout' "

No mention of proxy. v.10.13.0 which works detects the system proxy(without any $env:HTTPS_PROXY entry in the user Powershell profile) :

INFO: Proxy detected: https://login.microsoftonline.com -> http://**************:8888
INFO: SPN Auth via cert succeeded.

With our network configuration azcopy needs to authenticate to Azure AD using the proxy, but for authorization to the storage account and file transfer it needs to bypass the proxy and go over ExpressRoute, the storage account network access settings prohibit access from public networks (public network access is set to Disabled, there is a private endpoint configured).

azcopy v.10.13.0 detects the system proxy without the Powershell HTTPS_PROXY environment variable being defined($env:HTTPS_PROXY). In the system proxy config we have instructions to bypass the proxy for blob storage account targets, so the authorization and azcopy file transfer works.

azcopy versions v.10.14.0-10.16.0 seem to not detect the system proxy. If I declare the proxy explicitly in the user Powershell profile using  $env:HTTPS_PROXY then all azcopy versions detect the system proxy and authenticate, but they fail to get authorized because I guess they don't honour the system proxy bypass settings and the storage account network access is only allowed over ExpressRoute (via the private endpoint) and not via the proxy. I get the error below:

 User-Agent: [AzCopy/10.16.0 Azure-Storage/0.15 (go1.17.9; Windows_NT)]
   X-Ms-Client-Request-Id: [7758c2d1-9e48-4913-699a-3ad461e23019]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Tue, 13 Sep 2022 15:56:59 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [7758c2d1-9e48-4913-699a-3ad461e23019]
   X-Ms-Error-Code: [AuthorizationFailure]

**Comment by sezginr** [comment]
Finally all azcopy versions from v.10.13.0 up to v.10.16.0 authenticate and get authorised so file transfer works (in Powershell).
The trick was to define the 2 Powershell environment variables with the values below:

$env:HTTPS_PROXY="http://ourproxyurlhere:proxyporthere"
$env:NO_PROXY="*.blob.core.windows.net"

Thank you very much for your help.

**Comment by adreed-msft** [comment]
Awesome. I'm glad that all worked out for you. Have a nice day!
