### ISSUE TITLE
Azcopy sync not working for directory to directory

### ISSUE THREAD

**Issue by walter-heymans** [Azure/azure-storage-azcopy#1858]
### Which version of the AzCopy was used? 
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (Ubuntu 20.04, CentOS 8 Stream) - both are broken

### What command did you run?
I ran the following command:
```
azcopy sync "https://xxxx.blob.core.windows.net/path/to/directory?SAS" \
    "https://xxx.blobl.core.chinacloudapi.cn/path/to/directory?SAS" --recursive=true
```

### What problem was encountered?
```
Cannot perform sync due to error: trying to sync between different resource types (either file <-> directory or directory <-> file) which is not allowed.sync must happen between source and destination of the same type, e.g. either file <-> file or directory <-> directory
```
### How can we reproduce the problem in the simplest way?
A directory on Azure Global region exists. The path on the Azure China region does not exist (path up to the last directory already exists). The sync command (used to work always) shows the error above.

The exact same command work when I use azcopy version 10.13.0 and 10.15.0, but NOT when using 10.16.0.

Example:
```
# Azure Global structure
container
└── mydir_1
    ├── mydir_2
    └── mydir_3  
        ├── non_empty_dir
        └── non_empty_dir2           

# Azure China structure
container
└── mydir_1
    └── mydir_2

# Azcopy command
azcopy sync "https://xxxx.blob.core.windows.net/container/mydir_1/mydir_3?SAS" \
    "https://xxx.blobl.core.chinacloudapi.cn/container/mydir_1/mydir_3?SAS" --recursive=true
```
I expect `mydir_3` to be synced to Azure China, but it shows an error on `azcopy v10.16.0`, the command works correctly on previous versions.

### Have you found a mitigation/solution?
Downgrading to Azcopy 10.15.0 works.

**Comment by nakulkar-msft** [comment]
Hi, Please use below command. Note '/' suffix after directory
azcopy sync "https://xxxx.blob.core.windows.net/path/to/directory/?SAS" \
    "https://xxx.blobl.core.chinacloudapi.cn/path/to/directory/?SAS" --recursive=true

**Comment by walter-heymans** [comment]
Thanks, that worked. It is weird that the trailing `/` is required, it feels like this should not be required. But in any case, thanks for the quick response.
