### ISSUE TITLE
Missing Binary on AZCOPY for linux ARM distributive

### ISSUE THREAD

**Issue by marcserrat** [Azure/azure-storage-azcopy#1861]
Hi Team,

I'm reporting you that the archive that is publicly available at Microsoft site, relative to AZCopy for Linux and ARM architecture contains no binary and just the readme file. The intel version is OK but the ARM one not.

Can you please check and fix it?

thanks!

**Comment by elulcao** [comment]
For the record.

```bash
➜  test curl -L -o azcopy.tar.gz https://azcopyvnext.azureedge.net/release20220721/azcopy_linux_arm64_10.16.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21158  100 21158    0     0  36250      0 --:--:-- --:--:-- --:--:-- 36860

➜  test tar -zxvf azcopy.tar.gz
x azcopy_linux_arm64_10.16.0/
x azcopy_linux_arm64_10.16.0/NOTICE.txt

➜  test
```

**Comment by siminsavani-msft** [comment]
Hi @marcserrat and @elulcao ! Thank you for bringing this to our attention! We are working on updating the links and will update this thread accordingly.

**Comment by siminsavani-msft** [comment]
Hi @marcserrat and @elulcao ! The link for Linux ARM has been updated to include the executable. Thank you for your patience!

**Comment by marcserrat** [comment]
Thanks @siminsavani-msft!
