### ISSUE TITLE
Copy doesn't error if the target file does not exist

### ISSUE THREAD

**Issue by TomBolton** [Azure/azure-storage-azcopy#1862]
### Which version of the AzCopy was used? 

`10.16.0`

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

### What command did you run?

```
azcopy cp "https://atmcodeqldata.blob.core.windows.net/atm/evaluation/codeql-clis/codeql-linux64_03bad5e887edbe453377bfb8e0ffe69aa86a828b.zip" codeql-cli.zip
```

### What problem was encountered?

The file trying to be downloaded locally, `codeql-linux64_03bad5e887edbe453377bfb8e0ffe69aa86a828b.zip`, does not exist. In previous versions of `azcopy` (<=10.15.0), this would fail.

![Screenshot 2022-07-29 at 09 48 37](https://user-images.githubusercontent.com/14887813/181723785-eff6ef6e-0ee2-449f-bb0e-9eb0bf110b32.png)

However, with `10.16.0`, if the target file does not exist, no error or exception is raised.

![Screenshot 2022-07-29 at 09 50 12](https://user-images.githubusercontent.com/14887813/181724056-3fa15ced-2af1-4300-b60f-69607e8cc6cc.png)

### How can we reproduce the problem in the simplest way?

Use `azcopy copy` on any target file that does not exist.

### Have you found a mitigation/solution?

No, not yet. It would be great if the original behaviour could be reintroduced, or a flag added to force the command to fail if the target doesn't exist.

**Comment by siminsavani-msft** [comment]
Hi @TomBolton ! Thank you for your feedback! We felt that the original behavior lacked clarity, so we chose to go with the latest behavior to indicate that that no transfers were completed. 

I will share your feedback with the team to discuss how we can improve the UX. Thanks again!
