### ISSUE TITLE
azcopy sync - File CreateTime not preserved in destination 

### ISSUE THREAD

**Issue by mahasadanandan** [Azure/azure-storage-azcopy#1864]
##### Note: The version is visible when running AzCopy without any argument
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy sync

![image](https://user-images.githubusercontent.com/110687889/183125336-bedfdb1b-8292-4728-a904-ef7d0fb312ec.png)

### What problem was encountered?
We installed the latest version of AZCOPY 10.16 and ran the sync command to replicate the files to another region.  The file was copied with a CreationTime that was different from the source file, although we expected the CreationTime to be preserved..  

### Have you found a mitigation/solution?
No

**Comment by adreed-msft** [comment]
Hi there! It is not possible to alter the service side last modified time or create time on Blob.

For all UNIX time properties, we persist into metadata. The particular metadata names are:

- posix_ctime
- linux_btime
- modtime
- posix_atime

**Comment by venkat7be1** [comment]
Hello Adreed, are there any known limitations with azcopy sync with preserve-posix-properties? the following is the sync command used to sync containers and there are no metadata properties added on target side. 
`azcopy sync "SourceBlobContainerUrlWithSASToken"  "TargetBlobContainerUrlWithSASToken" --recursive --preserve-posix-properties= true`

**Comment by adreed-msft** [comment]
If there is no metadata on the source, there will be no metadata on the destination. AzCopy cannot discern information that does not exist.
