### ISSUE TITLE
sync issue with azcopy v10.16.0

### ISSUE THREAD

**Issue by nikunjbadjatya** [Azure/azure-storage-azcopy#1865]
### Which version of the AzCopy was used? 
bash-4.4$ azcopy -v
azcopy version 10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux 

### What command did you run?
azcopy sync https://source1.blob.core.windows.net/cont1/dir1/**folder1**?sasredacted https://destination1.blob.core.windows.net/cont2/somefolder1/somefolder2/somefolder3/**folder1**?sasredacted --recursive

note: only final folder name 'folder1' is common between the two paths.
folder1 has many subfolders and each of them has many files.

### What problem was encountered?
output: 
Cannot perform sync due to error: trying to sync between different resource types (either file <-> directory or directory <-> file) which is not allowed.sync must happen between source and destination of the same type, e.g. either file <-> file or directory <-> directory

### How can we reproduce the problem in the simplest way?
Use azcopy v10.16.0 and do a sync like above.  Issue is reproducible.

### Have you found a mitigation/solution?
Works fine in azcopy v10.15.0

**Comment by nakulkar-msft** [comment]
Hi @nikunjbadjatya, include a '/' after folder1 on both source and destination.
