### ISSUE TITLE
Copy archive to hot with azcopy copy not working

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-storage-azcopy#1866]
##### Note: The version is visible when running AzCopy without any argument
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

./azcopy copy 'https://yangshendls004.blob.core.windows.net/container1/dir1/msft.png' 'https://yangshendls004.blob.core.windows.net/container2/dir1/msft.png' --block-blob-tier=hot

### What problem was encountered?

According to document 
https://docs.microsoft.com/en-us/azure/storage/blobs/archive-rehydrate-to-online-tier?tabs=azcopy

I should be able to copy archive blob to hot tier with command

./azcopy copy 'https://yangshendls004.blob.core.windows.net/container1/dir1/msft.png' 'https://yangshendls004.blob.core.windows.net/container2/dir1/msft1.png?sasToken' --block-blob-tier=hot

but it failed

2022/08/08 05:20:05 ERR: [P#0-T#0] COPYFAILED: https://yangshendls004.blob.core.windows.net/container1/dir1/msft.png : 409 : 409 Copy source blob has been modified.. When Put Blob from URL. X-Ms-Request-Id: 9bf1bb68-301e-0073-29e6-aa1394000000

   Dst: https://yangshendls004.blob.core.windows.net/container2/dir1/msft1.png?se=2022-08-08T11%3A51%3A50Z&sig=-REDACTED-&sp=rwdlacupyx&spr=https&srt=sco&ss=bfqt&st=2022-08-08T03%3A51%3A50Z&sv=2021-06-08
2022/08/08 05:20:05 JobID=019446b4-addc-034d-7838-11dc1167303c, Part#=0, TransfersDone=1 of 1
2022/08/08 05:20:05 all parts of entire Job 019446b4-addc-034d-7838-11dc1167303c successfully completed, cancelled or paused
2022/08/08 05:20:05 is part of Job which 1 total number of parts done 
2022/08/08 05:20:05 PERF: primary performance constraint is Unknown. States: W:  0, F:  0, S:  0, E:  0, T:  0, GRs:  1
2022/08/08 05:20:05 0.0 %, 0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 0.0233

I tried to set AZCOPY_DEFAULT_SERVICE_API_VERSION to 2021-06-08 but it is not working as well.

https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-configuration-settings
Reference to all versions: https://docs.microsoft.com/en-us/rest/api/storageservices/previous-azure-storage-service-versions

Request id: 9bf1bb68-301e-0073-29e6-aa1394000000

azcopy set-properties is working
./azcopy set-properties "https://yangshendls004.blob.core.windows.net/container1/dir1/msft.png" --block-blob-tier=hot --rehydrate-priority=high

### How can we reproduce the problem in the simplest way?
Use the the same command.

### Have you found a mitigation/solution?
I tried to use Postman and it works

![image](https://user-images.githubusercontent.com/71274085/183357294-cb74f562-161e-474e-b951-bba09e9091dc.png)

**Comment by zezha-msft** [comment]
Hi @yangchengs, we are really sorry about that, that documentation is incorrect, as you cannot synchronously rehydrate blobs. We'll get the doc fixed.

We will add async copy support, which will allow you to copy archived blobs.

**Comment by yangchengs** [comment]
@zezha-msft  I believe you can implement sync call as well, azcopy can call CopyBlob API and pass correct headers (x-ms-version, x-ms-copy-source and x-ms-access-tier)

**Comment by zezha-msft** [comment]
@yangchengs that's async: https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob

Archived blobs are sitting in archive storage, they can't be brought back in real time.

**Comment by nakulkar-msft** [comment]
@zezha-msft's comment: This is unsupported, and this will have to be done asyncronously.
