### ISSUE TITLE
azcopy 8.1 always upload image with wrong content type application/octet-stream

### ISSUE THREAD

**Issue by tkumark** [Azure/azure-storage-azcopy#187]
I am using azcopy 8.1 to upload .jpg files to azure blob storage but on upload the content type is set to application/octet-stream instead of image/jpeg.

Should it not recognized it from AzCopyConfig.json. Is this a bug?

& $azcopyLocation /Source:$sourcePath /Dest:$deploymentPath /destkey:$destinationKey /Pattern:"*.jpg" /S /Y

**Comment by zezha-msft** [comment]
Hi @tkumark, V10 has this fixed already, would you like to give it a try?

Otherwise, @EmmaZhu could help you with this issue.

**Comment by EmmaZhu** [comment]
@tkumark 
AzCopy will set blob's content type automatically when option /SetContentType is indicated. Could you try with adding it?

**Comment by zezha-msft** [comment]
Closing since V8 is no longer being actively maintained. Please give V10 a try [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy), it's been GA for a bit of time now. Please don't hesitate if you encounter any issue.
