### ISSUE TITLE
Upaloding large files with Short Life SAS Token

### ISSUE THREAD

**Issue by schenardie** [Azure/azure-storage-azcopy#1871]
##### Note: The version is visible when running AzCopy without any argument
10.16
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azCopy.exe cp "filePath" "sastoken" --output-type "json" --block-size-mb 4
### What problem was encountered?
By default intune generates 15 minutes SAS tokens and provides an API call to renew the token, but only before the token expires it can be renewed. How can i use AzCopy to copy a large file (which will exceed the 15 minutes) by pausing or stoping the job to call the api renew function and keep copying from where it left off?

**Comment by nakulkar-msft** [comment]
Hi @schenardie, check if you can use alternate methods of [login](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)). AzCopy cannot support resuming at file level, so generating newer SAS does not help. Sorry, we cannot help you here.
