### ISSUE TITLE
azcopy login fails with error "failed to get keyring during saving token, function not implemented" on WSL

### ISSUE THREAD

**Issue by bbusschots-mu** [Azure/azure-storage-azcopy#1873]
### Which version of the AzCopy was used? 
azcopy version 10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu on Windows via WSL

### What command did you run?
azcopy login

### What problem was encountered?
Login failed with error:

```
Failed to perform login command:
failed to get keyring during saving token, function not implemented
```

### How can we reproduce the problem in the simplest way?
Install the latest azcopy into Ubuntu on Windows and try to log in with `azcopy login`

### Have you found a mitigation/solution?
No, tried `apt-get install keyutils` but it did not help 🙁

**Comment by nakulkar-msft** [comment]
same as #1734
