### ISSUE TITLE
Unable to  copy or delete files  from the blob, when there is a "#"  symbol in the file name 

### ISSUE THREAD

**Issue by kaksenov** [Azure/azure-storage-azcopy#1874]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.13.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy 'https://storage-account-name.file.core.windows.net/file-share-name/file-path/file-name?&SAS-token' 'local-file-path'
azcopy delete 'https://storage-account-name.file.core.windows.net/file-share-name/file-path?&SAS-token' 

### What problem was encountered?
Unable to  copy or delete file  from the blob  , when there is a "#"  symbol in the file name 

azcopy fails  with :

failed to perform remove command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public

### How can we reproduce the problem in the simplest way?
create a file AAA#BBB.txt  in the blob 
run 
azcopy  copy ...
azcopy delete ... 

### Have you found a mitigation/solution?
Have to manually copy/delete  files using storage explorer on windows

**Comment by nakulkar-msft** [comment]
Hi @kaksenov, you can copy and remove blobs with # in the name. Perhaps you're seeing a different issue? Can you post the error from azcopy log here?

**Comment by nakulkar-msft** [comment]
You'd have to URL encode the '#" the name though. Replace with %23

**Comment by kaksenov** [comment]
Hi nakulkar-msft 
%23 seems to be working . thank you
