### ISSUE TITLE
Azcopy issue: failed to perform copy command due to error: failed to move temporary token to desired output location

### ISSUE THREAD

**Issue by jacksong1315** [Azure/azure-storage-azcopy#1877]
### Which version of the AzCopy was used? 
azcopy_windows_amd64_10.13.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows (Windows Server 2019 Datacenter)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

...
set file_name=%1%
set XX_id=%2%
set azcpy_dir=C:\azcopy_windows_amd64_10.13.0
set token_url=https://XXXXX.blob.core.windows.net/XXXXXX/
set AZCOPY_AUTO_LOGIN_TYPE=MSI
set AZCOPY_JOB_PLAN_LOCATION=%home_dir%\plan
set AZCOPY_LOG_LOCATION=%home_dir%\log

set temp_log=%home_dir%\log\upload_%XX_id%.log
	
%azcpy_dir%\azcopy.exe copy %file_name% %token_url% > %temp_log%
...

### What problem was encountered?

INFO: Scanning...
INFO: Authenticating to destination using Azure AD
INFO: azcopy.exe: A newer version 10.16.0 is available to download

failed to perform copy command due to error: failed to move temporary token to desired output location. src="C:\\Windows\\system32\\config\\systemprofile\\.azcopy\\token030202203" dst="C:\\Windows\\system32\\config\\systemprofile\\.azcopy/accessToken.json", rename C:\Windows\system32\config\systemprofile\.azcopy\token030202203 C:\Windows\system32\config\systemprofile\.azcopy/accessToken.json: Access is denied.

### How can we reproduce the problem in the simplest way?
Occasionally occurred, have no idea

### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
@jacksong1315 use [auto-login](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)) for this scenario. With auto-login, you can skip the explicit login command in your script.
