### ISSUE TITLE
Need golang version to be updated to 1.18.5 to resolve high level security issues

### ISSUE THREAD

**Issue by muhanator** [Azure/azure-storage-azcopy#1878]
### Which version of the AzCopy was used? 
latest version: @azure-tools/azcopy-linux:10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
We have a node.js based microservice which uses @azure-tools/azcopy-node as dependency (in our package.json)
![image](https://user-images.githubusercontent.com/26660603/186442878-c591dabf-882f-42ba-b789-52f3f0ff137f.png)

@azure-tools/azcopy-node uses "@azure-tools/azcopy-linux" as a dependency (in our package-lock.json)
![image](https://user-images.githubusercontent.com/26660603/186442784-89125853-9eac-419a-be91-6a89a337721e.png)

### What problem was encountered?
attached is security scan: 
[Docker_ccss-4.1.0-gl1200247_Security_Export.pdf](https://github.com/Azure/azure-storage-azcopy/files/9416955/Docker_ccss-4.1.0-gl1200247_Security_Export.pdf)

We see 16 high level security issues detected in our security scans because we use @azure-tools/azcopy-linux:10.16.0, which uses golang:1.17.9.
![image](https://user-images.githubusercontent.com/26660603/186443551-9696073a-eed7-40a8-b0f1-9f2fdee96fac.png)

### How can we reproduce the problem in the simplest way?
Use the npm package @azure-tools/azcopy-linux:10.16.0 from https://www.npmjs.com/package/resolve in your node.js project, build it as a docker image, run a xray security scan (scanning tool used in our case) and you will see multiple high level security issue due to the use of golang:1.17.9 (which is used in @azure-tools/azcopy-linux:10.16.0)

### Have you found a mitigation/solution?
Upgrading the golang version to 1.18.5 should resolve the issue, should be a similar fix to https://github.com/Azure/azure-storage-azcopy/commit/1883a4b6b4006dd86aa12c31002836663b9d2215

**Comment by adreed-msft** [comment]
@zezha-msft I'll submit a PR to upgrade our target Go version.

@JasonYeMSFT FYI
