### ISSUE TITLE
Azcopy fails when copying blobs between two subscriptions with private endpoints

### ISSUE THREAD

**Issue by htwashere** [Azure/azure-storage-azcopy#1879]
### Which version of the AzCopy was used? 
10.14.1
### Which platform are you using? (ex: Windows, Mac, Linux) 
Windows

### What command did you run? 
azcopy copy "https://SOURCEst01.blob.core.windows.net/system/Microsoft.Compute/Images/images/testdata.txt?<sas redacted>"  "https://DESTst01.blob.core.windows.net/imagevhd/testdata.txt?<sas redacted>" --overwrite=prompt --s2s-preserve-access-tier=false --include-directory-stub=false --recursive --log-level=INFO
### What problem was encountered?
Various errors would show. Here are some snippets:
Description=This request is not authorized to perform this operation.
RequestId:b0746cb8-101e-002f-3283-b97279000000
Time:2022-08-26T19:35:53.0559192Z, Details:
   Code: CannotVerifyCopySource  <== I do not believe this is the correct reason for the error
...
RESPONSE Status: 403 This request is not authorized to perform this operation.

### How can we reproduce the problem in the simplest way? 
Create two subscriptions, set up private endpoint for both storage accounts. Confirm that you can resolve both xxx.blob.core.windows.net endpoints with resolvable private IPs and they can be reached (I tried with port 443)
### Have you found a mitigation/solution? 
Yes sort of, on the destination storage account, I have to remove private endpoint and secured it via specific IP only ("Enabled from selected virtual networks and IP addresses"). With that, I am able to copy the blobs. However, this is not the desired outcome that I want to achieve

Please advise if this is by design?

**Comment by adreed-msft** [comment]
I believe this is more in Azure limitation territory.

In a S2S transfer, AzCopy talks to the source, gathers information about the object landscape, and then talks to the destination and says "hey, please copy these objects". The destination reaches out to the source, and the source says "whut" because it would probably be a bad thing if these private endpoints weren't all that private.

**Comment by barron-j** [comment]
To allow for this scenario though, couldn't AzCopy take a second SAS token as a parameter that it then provides to the destination storage for it to use to communicate back to the source? Without this, using IP restrictions on SAS tokens just won't work with a S2S transfer.
