### ISSUE TITLE
FreeBSD binary?

### ISSUE THREAD

**Issue by ItalyPaleAle** [Azure/azure-storage-azcopy#188]
Would it be possible to publish pre-compiled binaries for FreeBSD?

(Or, at least, publishing instructions on how to manually compile from source on *NIX systems?)

**Comment by zezha-msft** [comment]
Hi @ItalyPaleAle, thanks for reaching out!

Perhaps @seguler can help with your feature request.

If you have Go 1.11 installed, it should be pretty easy to compile from source. Just call `go build -o azcopy`, and the module support will get all the dependencies for you.

**Comment by zezha-msft** [comment]
In the mean while, if you'd like to learn more about Golang: https://golang.org/doc/.

**Comment by ItalyPaleAle** [comment]
Thanks @zezha-msft  for confirming the command was the basic one :)

I've tried it on a FreeBSD (12) VM, with Go 1.11.4, but it fails:

```sh
root@freebsd:~/azure-storage-azcopy # go version
go version go1.11.4 freebsd/amd64
root@freebsd:~/azure-storage-azcopy # go build -o azcopy
# github.com/Azure/azure-storage-azcopy/common
common/oauthTokenManager.go:56:15: undefined: CredCache
```

I've also tried cross-compiling from Linux (Ubuntu, via Docker), and I'm getting the same error:

```sh
root@ffb468aff251:~/azure-storage-azcopy# go version
go version go1.11.5 linux/amd64
root@ffb468aff251:~/azure-storage-azcopy# go build -o "azcopy_linux"
root@ffb468aff251:~/azure-storage-azcopy# file azcopy_linux
azcopy_linux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped
root@ffb468aff251:~/azure-storage-azcopy# GOARCH=amd64 GOOS=freebsd go build -o "azcopy_freebsd_amd64"
# github.com/Azure/azure-storage-azcopy/common
common/oauthTokenManager.go:56:15: undefined: CredCache
```

**Comment by zezha-msft** [comment]
Hi @ItalyPaleAle, sorry for the inconvenience!

I added the corresponding file for FreeBSD, but unfortunately it looks like [one of our dependencies](https://github.com/jiacfan/keyctl) does not support this OS at the moment. We'll have to look this further.

**Comment by ItalyPaleAle** [comment]
Thanks for looking into this! I see the module is used for storing keys; how are those stored on macOS?

I’d love to see this on FreeBSD also because that would enable it on FreeNAS too.

**Comment by ItalyPaleAle** [comment]
Never mind, I see that on macOS this is using the Keychain so the solution wouldn’t be portable to FreeBSD.

**Comment by ItalyPaleAle** [comment]
@zezha-msft Would leveraging [pass](https://www.passwordstore.org/) be a good solution? It works on Linux and FreeBSD (and others), and it's also what Docker uses.

**Comment by zezha-msft** [comment]
Hi @ItalyPaleAle, when my colleague @jiacfan comes back, he'll be able to look into your requirement more closely. Thanks for your suggestion!

**Comment by jiacfan** [comment]
Hi, @ItalyPaleAle 

Thanks for reaching us! 

Currently, [Linux embedded keyring](http://man7.org/linux/man-pages/man7/keyrings.7.html) is used for saving token in Linux OS, and freeBSD is not supported. 

At same time, we'll discuss internally and plan to extend the support for FreeBSD. (e.g. using gnome-keyring or other approaches)

Best Regards,
Jiachen

**Comment by cemeyer** [comment]
Suppose #768 is accepted in some form; what remaining infrastructure, test automation / coverage, CI integration/infrastructure, formal documentation, etc, is still missing in order for Microsoft to officially provide FreeBSD binaries?  (Or even unofficially — call it an "alpha.")  Is it something external contributors can help facilitate, or is there a hard barrier to additional official platforms as a business decision?

I.e., please let us know if we can help. 🙂

**Comment by JohnRusk** [comment]
Conrad, @zezha-msft is going to follow up with you.

**Comment by ksrx** [comment]
Hi there, any news about it? No new azcopy for freebsd?

**Comment by greendx** [comment]
Hi. Looking for this as well.

**Comment by vibhansa-msft** [comment]
As of now we do not have any plan to support BSD. AzCopy being open-source, user is free to compile and make it work on BSD and contribute back the changes to main line.
