### ISSUE TITLE
MSI doesn't work with Azure Image Builder customizers

### ISSUE THREAD

**Issue by yaegashi** [Azure/azure-storage-azcopy#1886]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Azure Windows VM managed by [Azure Image Builder](https://docs.microsoft.com/en-us/azure/virtual-machines/image-builder-overview)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

Running the following commands on the build VM with [the PowerShell customizer](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-json#powershell-customizer):

```
& .\azcopy.exe login --identity
& .\azcopy.exe copy https://...blob.core.windows.net/foo/bar.zip .
```

The build VM was surely given a user assigned identity: [User Assigned Identity for the Image Builder Build VM](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-json#user-assigned-identity-for-the-image-builder-build-vm)

The build VM was actually created and driven by [Packer's azure-arm builder](https://www.packer.io/plugins/builders/azure/arm) via WinRM remoting.

### What problem was encountered?

It seems it succeeded to acquire an MSI token but failed to encrypt it.  Maybe related to #1309.

```
[fb28108c-d37c-4817-8785-2110a3646f5c] PACKER OUT     azure-arm: Failed to perform login command:
[fb28108c-d37c-4817-8785-2110a3646f5c] PACKER OUT     azure-arm: failed to encrypt token, Access is denied.
[fb28108c-d37c-4817-8785-2110a3646f5c] PACKER OUT     azure-arm:
[fb28108c-d37c-4817-8785-2110a3646f5c] PACKER OUT     azure-arm: NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again.
[fb28108c-d37c-4817-8785-2110a3646f5c] PACKER OUT     azure-arm: INFO: Scanning...
[fb28108c-d37c-4817-8785-2110a3646f5c] PACKER OUT     azure-arm: INFO: Authenticating to source using Azure AD
[fb28108c-d37c-4817-8785-2110a3646f5c] PACKER OUT     azure-arm:
[fb28108c-d37c-4817-8785-2110a3646f5c] PACKER OUT     azure-arm: failed to perform copy command due to error: no cached token found, please log in with azcopy's login command
```

### How can we reproduce the problem in the simplest way?

Set up an Azure Image Builder template and run `azcopy login --identity` with the PowerShell customizer.

### Have you found a mitigation/solution?

No.  I cannot understand why `Access is denied` happens in this situation.

It would be nice to have options to cache tokens with no encryption in a specified file (that is, no dependency on the OS and user environment) for automation use cases like Azure Image Builder where you don't have to worry about security so much.

**Comment by nakulkar-msft** [comment]
Hi, please use [Auto-login](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store))
