### ISSUE TITLE
Azure AD Workload Identity support

### ISSUE THREAD

**Issue by adam-orosz** [Azure/azure-storage-azcopy#1887]
I'm trying to use [Azure AD Workload Identity](https://azure.github.io/azure-workload-identity/docs/) with `azcopy` and I'm getting `panic: runtime error: index out of range [1] with length 1`. I'm wondering if this method of authentication is supposed to work.

### Which version of the AzCopy was used? 
AzCopy 10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
`azcopy login --identity --identity-client-id < redacted Client ID of a Managed Identity >`

### What problem was encountered?
`panic: runtime error: index out of range [1] with length 1`

### Have you found a mitigation/solution?
no

### Additional notes
The pod was patched by the mutating webhook of the `Azure AD Workload Identity` project.

**Comment by adreed-msft** [comment]
I've reviewed your PR. Thank you for your contribution.
