### ISSUE TITLE
Blobs that contain a <no name> folder are not removed by sync --delete-destination true

### ISSUE THREAD

**Issue by skyaddict** [Azure/azure-storage-azcopy#1888]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy.exe sync $fromstorageaccount $tostorageaccount --recersive --delete-destination $true

### What problem was encountered?
When blobs created with a <no name> folder exist in the destination that needs to be deleted the delete command removes the \\

![image](https://user-images.githubusercontent.com/18058674/188758265-98fffa72-6137-4d15-ad4d-14c8537fbacd.png)

this blob name:
container\foo\\bar.txt
becomes:
container\foo\bar.txt

and the delete fails with  Code: BlobNotFound

### How can we reproduce the problem in the simplest way?

create a blob with a <no name> folder in a destination account and sync from an empty account to this destination account using the --delete-destination true

### Have you found a mitigation/solution? 

no

**Comment by adreed-msft** [comment]
If your folder is a stub file (like that which ADLSG2 uses where it's an empty file in place of the folder with the metadata hdi_isfolder=true), our enumerators will actually skip over it with the default settings. We unfortunately don't have the same flag exposed for sync, but you could potentially remove it with `azcopy rm` as that removes stubs by default.

**Comment by skyaddict** [comment]
we have some files that were being written with an empty folder name. It is interesting the file discovery sees them but when sync tries to remove it then throws the error. It seems to me it should be consistent.

**Comment by gapra-msft** [comment]
Hi @skyaddict 

I attempted to reproduce this issue but was unsuccessful. Could you please clarify exactly how the storage account (source and destination) should be configured?

In my repro, I created a source and destination container. I left the source empty and created a file in a virtual directory in the destination

So the destination looked like this

myfolder/myfile 

Note: there is no virtual directory stub in place of myfolder in my repro, so there is no real blob there.

**Comment by adreed-msft** [comment]
--delete-destination for folders in Sync has been implemented & is targeting 10.19.0. https://github.com/Azure/azure-storage-azcopy/pull/2147
