### ISSUE TITLE
azcopy cp command always returns with code 1 even when job passes which should return 0

### ISSUE THREAD

**Issue by shaunakv1** [Azure/azure-storage-azcopy#189]
### Which version of the AzCopy was used? 

azcopy version 10.0.7-Preview

### Which platform are you using?

Linux REHL

### What command did you run?
azcopy cp "./somedatadir/*" "https://dummysample.blob.core.windows.net/\$web/slr/?sp=rwdl&st=2019-01-31T03:07:19Z&se=2030-02-01T03:07:00Z&sv=2018-03-28&sig=X5cg4LIBEGvDWLdhlTi1K6I3ODR5kch4qeerf4npv1MiI%3D&sr=c" --recursive=true

### What problem was encountered?

Copy commands succeeds and data is copied, however scripts always returns error code 1 instead of 0. This is making out Bamboo CI deploy task fail, even if actual deploy goes through. 

### How can we reproduce the problem in the simplest way?

Just run any cp command and check return code. It's always 1 even if copy goes through successfully

### Have you found a mitigation/solution?

no

**Comment by shaunakv1** [comment]
Never mind.. return codes are correct

**Comment by zezha-msft** [comment]
Hi @shaunakv1, thanks for reaching out!

Btw if there's any failed transfer, then the exit code is non-zero.
