### ISSUE TITLE
Folder structure lost during copy, copy routine only copy last folder to destination

### ISSUE THREAD

**Issue by pedrolsazevedo** [Azure/azure-storage-azcopy#1894]
### Which version of the AzCopy was used? 
azcopy version 10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux Ubuntu 22.04

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
```
azcopy copy "https://mysourcestorageaccount.blob.core.windows.net/mysourcecontainer/root_folder/sub-folderA/end_folder?SAS_TOKEN" \
  "https://mydeststorageaccount.blob.core.windows.net/mydestcontainer?SAS_TOKEN" \
  --recursive \
  --overwrite ifSourceNewer
```

### What problem was encountered?
During the copy the folder structure is not created in destination container.

source: 
  mysourcecontainer
    - root_folder
      - sub-folderA
        - end_folder

destination
  mydestcontainer
    - end_folder

### How can we reproduce the problem in the simplest way?
Running a copy between two storage account, with a multilevel folder structure.

### Have you found a mitigation/solution?
No.

**Comment by adreed-msft** [comment]
By design.

If you want this, you should have your destination be `"https://mydeststorageaccount.blob.core.windows.net/mydestcontainer/root_folder/sub-folderA/end_folder?SAS_TOKEN"` and you should use the flag `--as-subdir=false`
