### ISSUE TITLE
10.16.0 broke sync into empty target container

### ISSUE THREAD

**Issue by ChrisCSAP** [Azure/azure-storage-azcopy#1900]
### Which version of the AzCopy was used? 
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux AMD64

### What command did you run?
`./azcopy sync "/data/source/he1" "https://xxxxxxx.blob.core.windows.net/target-container/he1?sv=xxxx&st=xxxx%3A13%3A07Z&se=xxxx%3A13%3A07Z&sr=c&sp=xxxxx&sig=xxxxxxxxx%3D" --delete-destination=true --put-md5 --recursive --log-level NONE `

### What problem was encountered?
`Cannot perform sync due to error: trying to sync between different resource types (either file <-> directory or directory <-> file) which is not allowed.sync must happen between source and destination of the same type, e.g. either file <-> file or directory <-> directory`

### How can we reproduce the problem in the simplest way?
Have a `/data/source/he1` directory that contains other directories and files. Empty the `target-container` totally so that `he1` is not yet existing there.
Expectation is that the `he1` directory is created and all content is been synced. (so first run is more a copy than a sync, but that is intentional as second run should sync without rethink about the parameters and so on)

### Have you found a mitigation/solution?
Switching back to version 10.15.0 made it running again like before. So i guess an patch in 10.16.0 made this "way" of copy/sync not working anymore.

**Comment by adreed-msft** [comment]
I have gotten a reproduction. I will identify the change that caused this and submit a fix.

**Comment by nakulkar-msft** [comment]
We've consciously made the decision to help improve other aspects of error. Please use a / at the end of your URL.

**Comment by ChrisCSAP** [comment]
Okay, created followup issue as this is not a obvious behavior and therefore a documentation/ error message change is needed https://github.com/Azure/azure-storage-azcopy/issues/1905 -> please keep always a perspective on user, that like to have direct hints instead of trying around.
