### ISSUE TITLE
Azcopy failed to unmarshal response body, Details: (none) ,RESPONSE Status: 403 MediaTypeCommon-Custom

### ISSUE THREAD

**Issue by RaymonZh** [Azure/azure-storage-azcopy#1903]
### Which platform are you using? (ex: Windows, Mac, Linux)
both windows and linux shows azcopy failed

### What command did you run?
azcopy copy "VM's path" "SA's path"

### What problem was encountered?
After customer changed proxy IP address(from http://172.20.30.245:8080 to http://10.53.66.1:8080), 
Azcopy failed at most of time.

### How can we reproduce the problem in the simplest way?
No

### Have you found a mitigation/solution?
no, I can not understand the error message's meaning

### failed log
------------------------------------------------------------------------------------------------------------------------
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 8b348c6d-f314-254e-53ac-1ad5477104ab has started
Log file is located at: C:\Users\prdmngr\.azcopy\8b348c6d-f314-254e-53ac-1ad5477104ab.log

0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, INFO: Proxy detected: https://strbakm001.blob.core.windows.net -> http://10.53.66.1:8080
0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 91.75040.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 93.0611INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20210407023846-16cf969ec1c3/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (**ServiceCode=**) =====
Description=**failed to unmarshal response body, Details: (none)**
   PUT https://strbakm001.blob.core.windows.net/zaiapm001%5Clog/Archive-System-2022-07-15-13-00-43-105.evtx?blockid=ztm3ymzimdetmji5nc1inzriltrlnmqtmja4yjrjytuzmzcz&comp=block&se=2031-06-30t15%3A00%3A00z&sig=-REDACTED-&sp=rwdlactfx&spr=https&srt=co&ss=b&st=2021-07-01t02%3A39%3A00z&sv=2020-02-10&timeout=901
   Content-Length: [4198400]
   User-Agent: [AzCopy/10.11.0 Azure-Storage/0.13 (go1.15; Windows_NT)]
   X-Ms-Client-Request-Id: [86551a80-40b3-4b5a-5628-a86b1943a777]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   **RESPONSE Status: 403 MediaTypeCommon-Custom**
   Cache-Control: [no-cache]
   Connection: [Keep-Alive]
   Content-Length: [3136]
   Content-Type: [text/html]
   Via: [1.1 10.53.32.4 (McAfee Web Gateway 10.2.9.40478)]
   X-Frame-Options: [deny]

xml: (*azblob.storageError).UnmarshalXML did not consume entire <html> element

0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 93.0611
------------------------------------------------------------------------------------------------------------------------

[04_errorlog_Windows.txt](https://github.com/Azure/azure-storage-azcopy/files/9613791/04_errorlog_Windows.txt)

**Comment by adreed-msft** [comment]
Sounds like McAfee Web Gateway is interfering with AzCopy. I'm not too sure why that would be, mayhaps it's some policy the customer has configured or something else along those lines.

Non-azcopy issue.
