### ISSUE TITLE
10.16.0 broke sync into empty target container and documentation/error message needs to be adjusted accordingly

### ISSUE THREAD

**Issue by ChrisCSAP** [Azure/azure-storage-azcopy#1905]
### Which version of the AzCopy was used? 
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux AMD64

### What problem was encountered?
Due to bug https://github.com/Azure/azure-storage-azcopy/issues/1900 that was decided to not fix but instead a workaround should be used, this workaround needs to reflected in user documentation and error message. Otherwise users (especially existing users) get confused and frustrated as it is not a very obvious workaround. So if it is not solved in code correctly you need to help the users, cause a tailing / is normally not shown in browser (just see https://github.com/Azure/azure-storage-azcopy/issues but a sub entry https://github.com/Azure/azure-storage-azcopy/issues/new (so issues is a resource))

### How can we reproduce the problem in the simplest way?
Please see https://github.com/Azure/azure-storage-azcopy/issues/1900

### Have you found a mitigation/solution?

- Add to guidelines the usecase of syncing a folder into an empty container with the important hint to add a "/" in end of URL.
- The error message `Cannot perform sync due to error: trying to sync between different resource types (either file <-> directory or directory <-> file) which is not allowed.sync must happen between source and destination of the same type, e.g. either file <-> file or directory <-> directory` must be changed to: `Cannot perform sync due to error: trying to sync between different resource types (either file <-> directory or directory <-> file) which is not allowed.sync must happen between source and destination of the same type, e.g. either file <-> file or directory <-> directory. To make sure that target is handled as directory you need to add a tailing "/" to target URL!`

**Comment by vibhansa-msft** [comment]
Fix will be released as part of 10.17.0. Feel free to reopen if the issue persists.
