### ISSUE TITLE
Use AzureIdentity SDK or MSAL instead of ADAL

### ISSUE THREAD

**Issue by adam-orosz** [Azure/azure-storage-azcopy#1907]
### Which version of the AzCopy was used? 
V10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?

I'm trying to use `azcopy` with [Azure AD Workload Identity](https://github.com/Azure/azure-workload-identity) *without* using Workload Identity's proxy sidecar. The proxy sidecar is used to intercept token requests to IMDS and acquire an AAD token on behalf of the user with federated identity credential. Unfortunately, our use case requires running `azcopy` in a k8s init-container therefore we can't rely on the proxy sidecar.

Based on [this comment](https://github.com/Azure/azure-workload-identity/issues/556#issuecomment-1251797942) if a project uses the AzureIdentity SDK or MSAL then there is no need for the proxy sidecar. However, it seems `azcopy` is using ADAL, which is both [deprecated](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-migration) and prevents `azcopy` to be used in an init-container.

The command below only works in conjunction with a proxy sidecar:
azcopy login --identity --identity-client-id < client ID of a managed identity >

### What problem was encountered?

Not using Azure AD Workload Identity's proxy sidecar will make `azcopy` fail to acquire a token.

### How can we reproduce the problem in the simplest way?

- follow the [installation guide](https://azure.github.io/azure-workload-identity/docs/installation.html) for Workload Identity
- create a pod without the proxy sidecar (this is the default behaviour)
- attempt to run azcopy login --identity --identity-client-id < client ID of a managed identity >

### Have you found a mitigation/solution?
No

**Comment by jbpaux** [comment]
With ADAL being deprecated on June 2023, @zezha-msft how do you plan to migrate to MSAL or AzureIdentity library ?

**Comment by gapra-msft** [comment]
Hi @jbpaux 

The plan is to migrate azcopy to the new Azure Identity library  https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity This is work we have scheduled and will get to it soon.

**Comment by jbpaux** [comment]
Perfect @gapra-msft please target 1.3.0+ as it support Workload Identity 😉

**Comment by watahani** [comment]
Hi @gapra-msft  Do you have any updates on this issue?  It would be helpful if you could comment on the ETA  if you have one.

**Comment by gapra-msft** [comment]
Hi, we are currently blocked on the MSAL and Azure Identity SDKs until they add support for token cache persistence. https://github.com/Azure/azure-sdk-for-go/issues/16643

We have almost completed the bulk of the work on our end to upgrade, we are just waiting on this support.

**Comment by maikschulze** [comment]
@gapra-msft , will it be possible after migrating to MSAL and Azure Identity SDk to share a token cache with other applications? In my use case, a long-running service application already uses MSAL to obtain a valid token. Occasionally, azcopy is called to perform actions. At the moment, this requires re-authenticating in the azcopy child process due to the opaque token cache persistance, or abusing $env:AZCOPY_OAUTH_TOKEN_INFO.

**Comment by gapra-msft** [comment]
Hi @maikschulze I would recommend you create a new Github issue describing the details of the scenario you are interested in. Then, the team will internally discuss this and get back to you on our thoughts.

**Comment by randywallace** [comment]
I got tired of waiting on this, as its a massive blocker for our usecases, and only gets worse as time marches forward.  So, for those of you in the same position we're in, I patched in azidentity 1.3.0 to replace the MSI implementation for ADAL, which works in our initial testing.  https://github.com/Azure/azure-storage-azcopy/compare/main...randywallace:azure-storage-azcopy:add-default-azure-credential-msal?expand=1 .  I'm not opening a PR, b/c I'm all but certain the implementation is not sustainably mergeable, but for those that need this, here it is, until this issue is resolved.

**Comment by jbpaux** [comment]
It seems to be available in next version `10.21.0` in preview

**Comment by gapra-msft** [comment]
Hi, yes we have upgraded most of the OAuth logic to the new azure identity SDK, with the exception of device code credential, as of 10.21.0

Closing this issue as this has been addressed in a recent release.

**Comment by LukaszRacon** [comment]
Hi @gapra-msft,
Original task was about using "azcopy with Azure AD Workload Identity", not about SDK upgrade.  
When I tried 10.21.0 a couple weeks ago it wasn't working as expected.
Is there a config, environmental variable setup that I am missing?

Related issue: https://github.com/Azure/azure-storage-azcopy/issues/2112

**Comment by junchen6072** [comment]
Hi @gapra-msft
 Would also like to have some instructions on how to use workload identity/federated credentials, if it's already supported by azcopy. Thanks!

**Comment by gapra-msft** [comment]
@rpahli we are tracking adding native support to AzCopy for workload identity [here](https://github.com/Azure/azure-storage-azcopy/issues/2545). Please subscribe to that issue for updates.
