### ISSUE TITLE
azcopy copy from local linux disk to azure file storage give error because file tried to copy to a non existing folder

### ISSUE THREAD

**Issue by mstenz** [Azure/azure-storage-azcopy#1908]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.16.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
```
copy /storage/foldername/ https://xxxxxx.file.core.windows.net/xxxxxxxxx/2022-09-28?xxxxxx --recursive=true
### What problem was encountered?
it tried to copy a file to a (sub)folder that was not yet created before by azcopy, 
===== RESPONSE ERROR (ServiceCode=ParentNotFound) =====
Description=The specified parent path does not exist.
RequestId:45a77d46-901a-004d-04ee-d2b415000000
Time:2022-09-28T04:00:03.2748121Z, Details:
   Code: ParentNotFound
   PUT https://xxxxxxxx.file.core.windows.net/xxxxxxxxxx/2022-09-28/xxxxxx/xxxxxx/xxxxxx/xxxxx/64/7a64ce427ce0ca963ce9c3ab0da2db27c1f3ac9620444e1b4312422af8e093b9.git/packed-refs?>   User-Agent: [AzCopy/10.16.0 Azure-Storage/0.8.0 (go1.17.9; linux)]
   X-Ms-Cache-Control: []
   X-Ms-Client-Request-Id: [39ff3ee3-6719-409c-5e34-2a1354a14ee1]
   X-Ms-Content-Disposition: []
   X-Ms-Content-Encoding: []
   X-Ms-Content-Language: []
   X-Ms-Content-Length: [16743]
   X-Ms-Content-Type: [text/plain]
   X-Ms-File-Attributes: [None]
   X-Ms-File-Creation-Time: [now]
   X-Ms-File-Last-Write-Time: [now]
   X-Ms-File-Permission: [inherit]
   X-Ms-Type: [file]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified parent path does not exist.
   Content-Length: [224]
   Content-Type: [application/xml]
   Date: [Wed, 28 Sep 2022 04:00:02 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [39ff3ee3-6719-409c-5e34-2a1354a14ee1]
   X-Ms-Error-Code: [ParentNotFound]
   X-Ms-Request-Id: [45a77d46-901a-004d-04ee-d2b415000000]
   X-Ms-Version: [2020-10-02]
```

After this error azcopy creates the folder and retry copy the file:

 AzCopy going to create parent directories of the Azure files
2022/09/28 04:00:03 ==> REQUEST/RESPONSE (Try=1/330.32612ms, OpTime=804.319892ms) -- RESPONSE SUCCESSFULLY RECEIVED

This is the job summary:

Job fad8f113-febd-8c4f-61f3-8f6dbfd8675b summary
Elapsed Time (Minutes): 12.936
Number of File Transfers: 55970
Number of Folder Property Transfers: 44314
Total Number of Transfers: 100284
Number of Transfers Completed: 100279
Number of Transfers Failed: 5
Number of Transfers Skipped: 0
TotalBytesTransferred: 39960244162
Final Job Status: CompletedWithErrors

As you can see there were 5 failed, but the number is different everytime. I have seen even 500 failed

### How can we reproduce the problem in the simplest way?
Not sure, this happens all the time in my environment for random folders (a job is executed once a day for a backup)
### Have you found a mitigation/solution?
no

**Comment by mstenz** [comment]
also, why are there failed transfers marked in summary when in the end it gets retried and successfully transferred? shouldn't there only really failed transfers marked?

Also, I found that there are both file and folder property transfers, but in the failed, completed, and skipped statistics it is not divided between them so you would not know if a folder or file transfer failed.

**Comment by adreed-msft** [comment]
> also, why are there failed transfers marked in summary when in the end it gets retried and successfully transferred? shouldn't there only really failed transfers marked?

I don't believe those get marked as failed (at least, it wouldn't make sense for them to, as a failure status indicates no more work will be done on the transfer). The logic doesn't mark it as a failure before at least trying to do the parent dir creation etc.

```
err = u.DoWithOverrideReadOnly(u.ctx,
	func() (interface{}, error) {
		return u.fileURL().Create(u.ctx, info.SourceSize, creationHeaders, u.metadataToApply)
	},
	u.fileOrDirURL,
	u.jptm.GetForceIfReadOnly())

if strErr, ok := err.(azfile.StorageError); ok && strErr.ServiceCode() == azfile.ServiceCodeParentNotFound {
	// Create the parent directories of the file. Note share must be existed, as the files are listed from share or directory.
	jptm.Log(pipeline.LogError, fmt.Sprintf("%s: %s \n AzCopy going to create parent directories of the Azure files", strErr.ServiceCode(), strErr.Error()))
	err = AzureFileParentDirCreator{}.CreateParentDirToRoot(u.ctx, u.fileURL(), u.pipeline, u.jptm.GetFolderCreationTracker())
	if err != nil {
		u.jptm.FailActiveUpload("Creating parent directory", err)
	}

	// retrying file creation
	err = u.DoWithOverrideReadOnly(u.ctx,
		func() (interface{}, error) {
			return u.fileURL().Create(u.ctx, info.SourceSize, creationHeaders, u.metadataToApply)
		},
		u.fileOrDirURL,
		u.jptm.GetForceIfReadOnly())
}
```

It seems interesting that the number of failed transfers varies almost randomly. Would you be willing to post your logs?

**Comment by mstenz** [comment]
`It seems interesting that the number of failed transfers varies almost randomly. Would you be willing to post your logs?`
Not here in public, I would be able to send link to a file via email.

**Comment by adreed-msft** [comment]
Looked over log, failures were related to a changing file structure and not due to azcopy failing to create destination folders in order.
