### ISSUE TITLE
--include-pattern file limits?

### ISSUE THREAD

**Issue by MrRogers1201** [Azure/azure-storage-azcopy#1910]
##### Note: The version is visible when running AzCopy without any argument
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy.exe copy C:\Sourcedir\* <file share url> --include-pattern <string of 600+ files separated by ;> --put-md5
(I can be more specific but my question is more about the capabilities of --include-pattern)

### What problem was encountered?
azcopy.exe failed to run: The filename or extension is too long

### How can we reproduce the problem in the simplest way?
Run similar command with over 600-1000 files listed in --include-pattern

### Have you found a mitigation/solution?
Potentially running a file counter and splitting the azcopy command up in chunks of 500ish files at a time

My question is if there is a limit of how many files can be passed to the --include-pattern switch? And is there a better way to go about it so I don't have to split copy step into chunks?   I've seen the --list-of-files switch but am unsure if I'd hit the same limits there as well.   Any help is greatly appreciated!

**Comment by opeongo** [comment]
> --list-of-files is handled as a file, not as a full parameter. So, it takes in a file that is a list of new line (`\n`) separated file names to transfer. This may help work around the issue.

Could you please give me a pointer to the documentation for this option?

**Comment by vibhansa-msft** [comment]
There is no documentation on this as such. It's just a CLI command in preview mode. You can provide a text file as input using this parameter and that text file shall have "\n" separated list of files.
```--include-pattern=``` is limited by the CLI input length based on your host machine.
Closing this as there is no bug here. Feel free to post here if you have any further queries in this regard.
