### ISSUE TITLE
HTTP request failed error.go:157

### ISSUE THREAD

**Issue by adrian-vieceli** [Azure/azure-storage-azcopy#1911]
### Which version of the AzCopy was used? 
AzcopyVersion  10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
copy https://***********.blob.core.windows.net/?se=****-**-**t07%3A27%3A49z&sig=-REDACTED-&sip=***.**.***.***&sp=rl&srt=sco&ss=bfqt&st=****-**-**t07%3A27%3A49z&sv=****-**-**G:\******\******--recursive --overwrite ifSourceNewer --log-level=ERROR 

### What problem was encountered?
I wrote a skript to read out ERROR Logs. 
We use AzCopy to backup our files on HDD to store them offline. The skript should notify me if something was wrong.
There are many logs of this kind in the logfile, but the files were still downloaded. What does this ERROR mean?
`2022/10/02 13:24:43 AzcopyVersion  10.8.0
2022/10/02 13:24:43 OS-Environment  windows
2022/10/02 13:24:43 OS-Architecture  amd64
2022/10/02 13:24:43 Log times are in UTC. Local time is 2 Oct 2022 15:24:43
2022/10/02 13:24:43 Job-Command copy https://******.blob.core.windows.net/?se=****-**-**t07%3A27%3A49z&sig=-REDACTED-&sip=***.**.***.***&sp=rl&srt=sco&ss=bfqt&st=****-**-**t07%3A27%3A49z&sv=****-**-**G:\******\*****--recursive --overwrite ifSourceNewer --log-level=ERROR 
2022/10/02 13:25:34 ==> REQUEST/RESPONSE (Try=1/108.0009ms, OpTime=108.0009ms) -- REQUEST ERROR
   GET https://*****.blob.core.windows.net/**********/*******/******************?se=****-**-**t07%3A27%3A49z&sig=-REDACTED-&sip=***.**.***.***&sp=rl&srt=sco&ss=bfqt&st=****-**-**t07%3A27%3A49z&sv=****-**-**&timeout=901
   If-Unmodified-Since: [Thu, 08 Sep 2022 10:12:56 GMT]
   User-Agent: [AzCopy/10.8.0 Azure-Storage/0.10 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [29e2bf64-39ea-413f-5bd1-01aa4bcce178]
   X-Ms-Range: [bytes=0-133119]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Get https://***.blob.core.windows.net/********/*****/********************?se=****-**-**T07%3A27%3A49Z&sig=-REDACTED-&sip=***.**.***.***&sp=rl&srt=sco&ss=bfqt&st=****-**-**T07%3A27%3A49Z&sv=****-**-**&timeout=901: dial tcp **.***.***.**:***: connectex: Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden.

goroutine 24687 [running]:
github.com/Azure/azure-storage-azcopy/ste.stack(0xc00282f740, 0xc002772d00, 0x0)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:232 +0xa4
github.com/Azure/azure-storage-azcopy/ste.NewRequestLogPolicyFactory.func1.1(0xdb74a0, 0xc0069e0d20, 0xc002772700, 0x10, 0x4, 0x0, 0xc000c0cf20)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:146 +0x7ac
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0053c91d0, 0xdb74a0, 0xc0069e0d20, 0xc002772700, 0xc000c0d008, 0xc000bfa6e0, 0xa, 0x2030014)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0xdb74a0, 0xc0069e0d20, 0xc002772700, 0xc000bfa6f8, 0xc000bfa768, 0x40c7c0, 0xc0053c95e0)
	/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:78 +0x1b8
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00a192e60, 0xdb74a0, 0xc0069e0d20, 0xc002772700, 0x10, 0x10, 0xb939e0, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0xda72e0, 0xc00a192e60, 0xc0001c8320, 0xdb74a0, 0xc0069e0d20, 0xc002772700, 0x0, 0x12e2760, 0xc000bfa7c8, 0x4310d8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zz_generated_responder_policy.go:33 +0x5a
github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_credential_anonymous.go:54
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do(0xc002353620, 0xdb74a0, 0xc0069e0d20, 0xc002772700, 0x0, 0x0, 0x0, 0xc000bfa8e8)
	/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x62
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0023536c0, 0xdb74a0, 0xc0069e0d20, 0xc002772700, 0xc0069e0d20, 0xc002353c80, 0xc000000001, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0xdb74e0, 0xc0054cb6e0, 0xc002772600, 0x10, 0xb411a0, 0x64492d747301, 0xc000c0cdc0)
	/home/vsts/work/1/s/ste/xferRetrypolicy.go:384 +0x70f
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0053c94f0, 0xdb74e0, 0xc0054cb6e0, 0xc002772600, 0xc000c0cea8, 0x30, 0x28, 0x8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0xdb74e0, 0xc0054cb6e0, 0xc002772600, 0x10, 0xb411a0, 0x40d001, 0xc000c0cdc0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_policy_unique_request_id.go:19 +0xb5
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00a192ea0, 0xdb74e0, 0xc0054cb6e0, 0xc002772600, 0xc000c0ce90, 0x35, 0xc0022ca800, 0xc000bfacb0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0xdb74e0, 0xc0054cb6e0, 0xc002772600, 0x1, 0x0, 0x1, 0xc000f18220)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_policy_telemetry.go:34 +0x164
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0054cb8f0, 0xdb74e0, 0xc0054cb6e0, 0xc002772600, 0xc0054cb8f0, 0xc002772600, 0xc000bfad80, 0x40d06f)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc003441e40, 0xdb74e0, 0xc0054cb6e0, 0xda73e0, 0xc0001c8320, 0xc002772600, 0x1c, 0xc00493e870, 0x42, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:129 +0x88
github.com/Azure/azure-storage-blob-go/azblob.blobClient.Download(0xc002404b40, 0x5, 0x0, 0x0, 0x0, 0xc002404b48, 0x1c, 0xc00493e870, 0x42, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zz_generated_blob.go:715 +0x43c
github.com/Azure/azure-storage-blob-go/azblob.BlobURL.Download(0xc002404b40, 0x5, 0x0, 0x0, 0x0, 0xc002404b48, 0x1c, 0xc00493e870, 0x42, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/url_blob.go:113 +0x1e6
github.com/Azure/azure-storage-azcopy/ste.(*blobDownloader).GenerateDownloadFunc.func1()
	/home/vsts/work/1/s/ste/downloader-blob.go:117 +0x945
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0x24)
	/home/vsts/work/1/s/ste/sender.go:179 +0x1ae
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc000068000, 0x24)
	/home/vsts/work/1/s/ste/JobsAdmin.go:433 +0xe6
created by github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).poolSizer
	/home/vsts/work/1/s/ste/JobsAdmin.go:362 +0x682`

### How can we reproduce the problem in the simplest way?
No idea, sorry

### Have you found a mitigation/solution?
I think it is related to this parameter, but I didn't have yet time to test it out. **AZCOPY_CONCURRENCY_VALUE**

**Comment by nakulkar-msft** [comment]
Hi @adrian-vieceli, please post the azcopy log file. If the transfer completed fine, this would be temporary network error and should be ignored.

**Comment by adrian-vieceli** [comment]
I just log the log level ERROR, I think there is no added value in this?

**Comment by nakulkar-msft** [comment]
Error log should be fine in this scenario. In any case, do you see the transfer failing?

**Comment by nakulkar-msft** [comment]
Hi @adrian-vieceli, this would be because of network issues. You should not worry unless the transfers actually fail. Reduce the number of parallel requests to service by setting environment variable AZCOPY_CONCURRENCY_VALUE. Check [here](https://github.com/Azure/azure-storage-azcopy/wiki/Performance:-small-blobs). Set the value to AUTO for best case.
