### ISSUE TITLE
azcopy keeps nagging a newer version is available, but there's no way to get it

### ISSUE THREAD

**Issue by gh-andre** [Azure/azure-storage-azcopy#1916]
### Which version of the AzCopy was used? 

10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)

CentOS 8 Stream, Windows 10

### What command did you run?
Happens on every command, including `--version`, like this:
```
azcopy --version
```
### What problem was encountered?
It keeps reporting this information:
```
INFO: azcopy: A newer version 10.16.1 is available to download
```
However, the download link here downloads v16.10.0:

https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

The Releases page on GitHub doesn't even have binaries:

https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.16.1

What's the point of reporting a new version availability if there's no way to upgrade?

### How can we reproduce the problem in the simplest way?

Run any `azcopy` command.

### Have you found a mitigation/solution?

No

**Comment by jbroome** [comment]
Same behavior with 10.16.0 on macOS Monterey with azcopy installed with homebrew.

**Comment by nakulkar-msft** [comment]
These are now rectified.
