### ISSUE TITLE
Release hygiene - 10.16.1 tag is wrong, PR is concerning, etc

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-storage-azcopy#1918]
Sooo.... 10.16.1 was tagged and released and then #1915 was merged with more **seemingly non-trivial** changes and ...  **the tag wasn't updated**.

Releases should be automated in a way that this can't happen. Releases and tags should be immutable.

Please consider automating, and tagging and releasing 10.16.2.

**Comment by nakulkar-msft** [comment]
These are now rectified.
