### ISSUE TITLE
Feature Request: Allow for a reduction of the timeout when copying

### ISSUE THREAD

**Issue by tymcpherson** [Azure/azure-storage-azcopy#1919]
##### Note: The version is visible when running AzCopy without any argument
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy <filename> <SAS URI>

### What problem was encountered?
If there is no connection between the source endpoint and the destination endpoint, I don't want to wait 15+ minutes to fail.

### How can we reproduce the problem in the simplest way?
Attempt to copy a file from an endpoint to a storage blob with a blocking mechanism (Firewall / Proxy)

### Have you found a mitigation/solution?
No

### Suggestion
Env variable or command-line parameter to reduce the timeout
AZCOPY_MAX_TIMEOUT = 5
azcopy copy <filename> <SAS URI> --timeout-5

In the above examples I would be able to reduce the timeout to 5 minutes

**Comment by adreed-msft** [comment]
Make use of the environment variable `AZCOPY_REQUEST_TRY_TIMEOUT`.
