### ISSUE TITLE
Feature Request: Skip version check

### ISSUE THREAD

**Issue by tymcpherson** [Azure/azure-storage-azcopy#1920]
##### Note: The version is visible when running AzCopy without any argument
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows / Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy

### What problem was encountered?
azcopy checks for newer versions

### How can we reproduce the problem in the simplest way?
azcopy --version

### Have you found a mitigation/solution?
no

### Suggestion
Allow for a toggle using either env variable or command-line parameter to turn off the new version check.  Default would function as-is and check for a new version

AZCOPY_DISABLE_VERCHECK = True
azcopy copy <filename> <SAS URI> --disablevercheck-true

In the above examples I do not want azcopy to check for the availability of a new version

**Comment by adreed-msft** [comment]
The version check is an async process and does not block AzCopy functionality. Additionally, the messaging is minimal and non-intrusive.

@zezha-msft What do you think?

**Comment by zezha-msft** [comment]
@tymcpherson thanks for reaching out. Could you please provide a bit of context behind this ask? Is the version check creating a problem for your security rules or something like that?

**Comment by adreed-msft** [comment]
Ty responded offline in an email thread.

**Comment by supermistag** [comment]
Requirements as explained in #1705 

Thanks for fixing.
