### ISSUE TITLE
azcopy login no longer working is WSL

### ISSUE THREAD

**Issue by gabe-microsoft** [Azure/azure-storage-azcopy#1922]
### Which version of the AzCopy was used? 
10.16.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Subsystem of Linux (WSL) running Ubuntu 20.04 (kernel: 5.10.102.1-microsoft-standard-WSL2), running on Windows 11 Enterprise 21H2 (Build 22000.978, Windows Feature Experience Pack 1000.22000.978.0)

Note: I have also experienced this on other Windows 10 computers running WSL2.

### What command did you run?
```bash
$ azcopy login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.

INFO: Logging in under the "Common" tenant. This will log the account in under its home tenant.
INFO: If you plan to use AzCopy with a B2B account (where the account's home tenant is separate from the tenant of the target storage account), please sign in under the target tenant with --tenant-id
INFO: Login succeeded.

$ azcopy login status
INFO: You are currently not logged in. Please login using 'azcopy login'
```

### What problem was encountered?
Although the login is succeeding, the credentials don't appear to be getting stored. Any subsequent command that requires credentials (e.g., a copy) will fail with `failed to perform copy command due to error: no cached token found, please log in with azcopy's login command, required key not available`

### How can we reproduce the problem in the simplest way?
Use the commands listed above in WSL.

### Have you found a mitigation/solution?
No, I've tried deleting my `~/.azcopy` directory, and rebooting with no luck. My co-workers are also experiencing this problem on azcopy 10.15 and greater.

`azcopy login` has always worked in the past...I just can't figure out what has changed

**Comment by nakulkar-msft** [comment]
#1734
