### ISSUE TITLE
failed to move temporary token to desired output location. when syncing multiple containers in parallels

### ISSUE THREAD

**Issue by skyaddict** [Azure/azure-storage-azcopy#1924]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.16.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What problem was encountered?

I have a powershell script running in a pipeline that downloads the latest azcopy from Microsoft and runs azcopy login using a spn key. Then in a foreach-object loop, I queue 5 jobs to sync 5 containers at the same time  awaiting the completion

most of the time this works great but occasionally I get the following error. 4 of the containers will sync just fine but then 1 will fail to process.

Cannot perform sync due to error: failed to move temporary token to desired output location. src="C:\\Users\\user\\.azcopy\\plans\\token1928218855" dst="C:\\Users\\user\\.azcopy/plans/accessToken.json", rename C:\Users\user\.azcopy\plans\token1928218855 C:\Users\user\.azcopy/plans/accessToken.json: Access is denied.

### How can we reproduce the problem in the simplest way?

```
  .\azcopy.exe login;
    $storageSyncJob = $containers | ForEach-Object -AsJob -ThrottleLimit 5 -Parallel {
      Write-Output "*** sync container $_ from $using:sourceStorageAccount to $using:targetStorageAccount ***";
      ./azcopy.exe sync "https://$using:sourceStorageAccount.blob.core.windows.net/$_" "https://$using:targetStorageAccount.blob.core.windows.net/$_" --recursive --delete-destination $using:deleteDestination;
      if (!$?)
      {
        Throw "Azcopy failed to sync container $_";
      }
    }
    $storageSyncJob.ChildJobs | ForEach-Object { $_ | Receive-Job -Wait; }
    Remove-Job $storageSyncJob;
```

### Have you found a mitigation/solution?

No, Is there a way to specify a different plan folder for each run? I tried to set AZ_JOB_PLAN_LOCATION to disambiguate but that seems to be a global environment variable.

**Comment by nakulkar-msft** [comment]
Hi @skyaddict, use [auto-login](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)) for this scenario.  With auto-login, you can skip the explicit login command in your script.

Plan location is global at this time, and we will continue to do so.

**Comment by skyaddict** [comment]
I will give that a shot thanks!

**Comment by skyaddict** [comment]
@nakulkar-msft It appears that autologin does not honor AZCOPY_JOB_PLAN_LOCATION. If I set this along with $env:AZCOPY_LOG_LOCATION, I get the following error: 

INFO: Authenticating to destination using Azure AD

Cannot perform sync due to error: no cached token found, please log in with azcopy's login command

If I use just AZCOPY_LOG_LOCATION autologin works fine. do you think that is a bug?
