### ISSUE TITLE
Blob deletion impacted network connections to both Outlook and Azure portal

### ISSUE THREAD

**Issue by writeconrad** [Azure/azure-storage-azcopy#1926]
### Which version of the AzCopy was used? 
10.16.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
2022/10/08 20:40:36 AzcopyVersion  10.16.1
2022/10/08 20:40:36 OS-Environment  windows
2022/10/08 20:40:36 OS-Architecture  amd64
2022/10/08 20:40:36 Log times are in UTC. Local time is 8 Oct 2022 21:40:36
2022/10/08 20:40:36 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2022-10-08T20:40:31Z or --include-after=2022-10-08T20:40:31Z
2022/10/08 20:40:36 Any empty folders will be processed, because source and destination both support folders
2022/10/08 20:40:42 Job-Command remove https://[storageaccount].blob.core.windows.net/docfolder/[GUID]?se=2022-10-08t21%3A40%3A15z&sig=-REDACTED-&sp=rdl&sr=c&sv=2020-08-04 --recursive=true 

### What problem was encountered?
I was deleting 20 to 30 thousand blobs from a blob container using a powershell script which was taking a long time. 
I tried to access the container from the Azure portal and couldn't access the resource. I then tried windows storage explorer and found it couldn't access the storage account either, it was also using Azcopy 10.16.1.

I stopped the script, which had been deleting blobs, and tried to do the same thing using Storage Explorer and saw the same thing happen.
Eventually I used another PC which had an older version of AzCopy 10.

I had Outlook running and saw it had trouble connecting as well. Memory use was high but not critical; I didn't think to check network capacity though.

I used the same script to delete groupings of hundreds of blobs earlier without error.

Saw the errors below in the log files.

2022/10/08 20:32:11 ==> REQUEST/RESPONSE (Try=2/8.0333ms, OpTime=1.1493175s) -- REQUEST ERROR
   DELETE https://storageaccount.blob.core.windows.net/docs/cd410462-1ca2-4c48-bbac-197d4565fea5/cd/cd410462-1ca2-4c48-bbac-197d4565fea5.docx?se=2022-10-08T21%3A04%3A42Z&sig=-REDACTED-&sp=rdl&sr=c&sv=2020-08-04&timeout=901
   User-Agent: [AzCopy/10.16.1 Azure-Storage/0.15 (go1.17.9; Windows_NT)]
   X-Ms-Client-Request-Id: [2af18784-c3a0-468a-6520-c5ada906a8a1]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
HTTP request failed

Delete "https://storageaccount.blob.core.windows.net/docs/cd410462-1ca2-4c48-bbac-197d4565fea5/cd/cd410462-1ca2-4c48-bbac-197d4565fea5.docx?se=2022-10-08T21%3A04%3A42Z&sig=-REDACTED-&sp=rdl&sr=c&sv=2020-08-04&timeout=901": dial tcp ##.##.##.###:443: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.

goroutine 413 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.stack()
	/home/vsts/work/1/s/ste/xferLogPolicy.go:237 +0x65
github.com/Azure/azure-storage-azcopy/v10/ste.NewRequestLogPolicyFactory.func1.1({0x16a8660, 0xc008bad920}, {0xc009c36c60})
	/home/vsts/work/1/s/ste/xferLogPolicy.go:151 +0xa29
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x14533e0, {0x16a8660, 0xc008bad920}, {0xc})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f
github.com/Azure/azure-storage-azcopy/v10/ste.NewVersionPolicyFactory.func1.1({0x16a8660, 0xc008bad920}, {0xc0009b7400})
	/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:88 +0x157
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0017acdf8, {0x16a8660, 0xc008bad920}, {0xc0017acdf8})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f
github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do({{0x1693a60, 0xc008569290}, 0xc007dea0b0}, {0x16a8660, 0xc008bad920}, {0xc005589200})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zz_generated_responder_policy.go:33 +0x44
github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_credential_anonymous.go:54
github.com/Azure/azure-storage-azcopy/v10/ste.(*retryNotificationPolicy).Do(0xc0017ace88, {0x16a8660, 0xc008bad920}, {0x16a85f0})
	/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x2f
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x16a85f0, {0x16a8660, 0xc008bad920}, {0x7})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f
github.com/Azure/azure-storage-azcopy/v10/ste.NewBlobXferRetryPolicyFactory.func1.1({0x16a85f0, 0xc00192ac40}, {0xc000aeb1e0})
	/home/vsts/work/1/s/ste/xferRetrypolicy.go:384 +0xa6c
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x14533e0, {0x16a85f0, 0xc00192ac40}, {0x16})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1({0x16a85f0, 0xc00192ac40}, {0xc000aeb1e0})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_unique_request_id.go:22 +0x191
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x14533e0, {0x16a85f0, 0xc00192ac40}, {0xa})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1({0x16a85f0, 0xc00192ac40}, {0xc0005488c0})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_telemetry.go:34 +0x11c
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc008dc8bc0, {0x16a85f0, 0xc00192ac40}, {0x4})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc005420900, {0x16a85f0, 0xc00192ac40}, {0x1693be0, 0xc007dea0b0}, {0xc005420908})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:129 +0x54
github.com/Azure/azure-storage-blob-go/azblob.blobClient.Delete({{{{0xc005420900, 0x5}, {0x0, 0x0}, 0x0, {0xc005420908, 0x2d}, {0xc005420935, 0x5b}, {0x0, ...}, ...}, ...}}, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zz_generated_blob.go:627 +0x394
github.com/Azure/azure-storage-blob-go/azblob.BlobURL.Delete({{{{{...}, {...}, 0x0, {...}, {...}, {...}, 0x0, {...}, {...}, {...}}, ...}}}, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/url_blob.go:141 +0x12f
github.com/Azure/azure-storage-azcopy/v10/ste.doDeleteBlob({0x16c9e10, 0xc005e0e9a0}, {0x168f920, 0xc008dc8bc0})
	/home/vsts/work/1/s/ste/xfer-deleteBlob.go:67 +0x42e
github.com/Azure/azure-storage-azcopy/v10/ste.DeleteBlob.func1()
	/home/vsts/work/1/s/ste/xfer-deleteBlob.go:28 +0x29
github.com/Azure/azure-storage-azcopy/v10/ste.createChunkFunc.func1(0x5f5e100)
	/home/vsts/work/1/s/ste/sender.go:194 +0x2b4
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).chunkProcessor(0xc000029880, 0x0)
	/home/vsts/work/1/s/ste/mgr-JobMgr.go:983 +0xbd
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).poolSizer
	/home/vsts/work/1/s/ste/mgr-JobMgr.go:885 +0x245

### How can we reproduce the problem in the simplest way?
load a blob container with saw 20,000 blobs and attempt to delete them.
our containers have 2 folders, a root GUID then subfolders for GUID named files starting with the first 2 characters (11,1A,9A ...)

### Have you found a mitigation/solution?
Use an older version of AzCopy! I'm trying to get a copy of 10.14.1

**Comment by nakulkar-msft** [comment]
@writeconrad AzCopy tries to reserve all the resources. You can limit the n/w usage in this case by setting environment variable AZCOPY_CONCURRENCY_VALUE to a lower number. Say 16.
