### ISSUE TITLE
Installer to replace AzCopy 8.1.0 in Program Files to v10

### ISSUE THREAD

**Issue by sengiv** [Azure/azure-storage-azcopy#1929]
The installer at _https://aka.ms/downloadazcopy_ is still at v8.1.0.
Is this done on purpose, because v10 is not yet final?

For beginners this can be very confusing, as v8 commands don't work in v10.
Example : https://stackoverflow.com/questions/66784580/microsoft-azure-storage-azcopy-error-parsing-the-argument-copy

_Possible solution:_ v10 installer to automatically replace previous installations

**Comment by adreed-msft** [comment]
AzCopy V10 does not require installation, nor do I believe we're inclined to create an installer any time soon. Links to v10 downloads are available on the first Google result. https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy
