### ISSUE TITLE
Unable to download azcopy 10.13 binary in an Azure Devops Pipelines with custom linux agents

### ISSUE THREAD

**Issue by ValKiriann** [Azure/azure-storage-azcopy#1933]
##### Note: The version is visible when running AzCopy without any argument
Trying to use 10.13
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
az storage remove -c '' --exclude-path '' --recursive --account-name '' --name '' --only-show-errors
### What problem was encountered?
##[error]ERROR: Connection error while attempting to download azcopy 10.13.0. You could also install the specified azcopy version to /home/AzDevOps/bin manually. (HTTP Error 409: Conflict)

### How can we reproduce the problem in the simplest way?
Trying to use any az storage command with my cli version from scratch I suppose, my agents start from a fresh az cli version with no az copy binary downloaded, my az cli version is 2.40.0, but updating to 2.41.0 has not solved the problem.
### Have you found a mitigation/solution?
No, and its risky because we cant deploy in our company at the moment.

**Comment by ValKiriann** [comment]
I tried to get the url to downloadit and placed them in my agents but its the direct link of the version the one that its giving the 409

wget https://azcopyvnext.azureedge.net/release20211027/azcopy_linux_amd64_10.13.0.tar.gz

--2022-10-19 09:15:09--  https://azcopyvnext.azureedge.net/release20211027/azcopy_linux_amd64_10.13.0.tar.gz
Resolving azcopyvnext.azureedge.net (azcopyvnext.azureedge.net)... 23.216.77.13, 23.216.77.32, 2a02:26f0:480:10::213:7e9e, ...
Connecting to azcopyvnext.azureedge.net (azcopyvnext.azureedge.net)|23.216.77.13|:443... connected.
HTTP request sent, awaiting response... 409 Conflict
2022-10-19 09:15:12 ERROR 409: Conflict.

**Comment by ramondeklein** [comment]
We can confirm this issue. This link is highly unstable. On some systems it does work, but on a lot of systems (i.e. our build server) it also fails. Trying to fetch the file manually also results in the same issue.

**Comment by KevinSmall** [comment]
We are facing same issue yesterday and today, it affects our dev and QA VMs and customer deployments of our service are also failing for the same reason.

```
$ wget https://azcopyvnext.azureedge.net/release20210415/azcopy_linux_amd64_10.10.0.tar.gz
--2022-10-20 12:10:14--  https://azcopyvnext.azureedge.net/release20210415/azcopy_linux_amd64_10.10.0.tar.gz
Resolving azcopyvnext.azureedge.net (azcopyvnext.azureedge.net)... 62.252.115.16, 62.252.115.25, 2a02:8801:102:1::3efd:4811, ...
Connecting to azcopyvnext.azureedge.net (azcopyvnext.azureedge.net)|62.252.115.16|:443... connected.
HTTP request sent, awaiting response... 409 Conflict
2022-10-20 12:10:16 ERROR 409: Conflict.
```

Is it known when this will be resolved?

**Comment by segunak** [comment]
+1 on this. Seeing this issue both yesterday and today trying to access https://azcopyvnext.azureedge.net/release20220315/azcopy_windows_amd64_10.14.1.zip.

Would appreciate resolution!

**Comment by chriskucinski** [comment]
We experienced a similar issue in our Azure Pipelines (Windows agents). As a workaround, we switched the download link from `https://azcopyvnext.azureedge.net/release20220511/azcopy_windows_amd64_10.15.0.zip` to `https://aka.ms/downloadazcopy-v10-windows`.

As long as you are OK using the latest version then this work.

**Comment by zezha-msft** [comment]
I'm really sorry for the inconvenience. We had a configuration problem yesterday and got it fixed quickly. But it seems that the CDN nodes close your locations have cached some bad results. Unfortunately, I cannot easily purge all cached contents. I did purge the content for everyone on this thread that posted links. Please let me know if this fixes the problem for you.

**Comment by zezha-msft** [comment]
If you are still blocked, please try using our storage account directly: https://azcopyvnextrelease.blob.core.windows.net

For example:
https://azcopyvnextrelease.blob.core.windows.net/release20220511/azcopy_windows_amd64_10.15.0.zip

Instead of:
https://azcopyvnext.azureedge.net/release20220511/azcopy_windows_amd64_10.15.0.zip

**Comment by KevinSmall** [comment]
@zezha-msft thanks for update, are you able to purge the cache for this link:

https://azcopyvnext.azureedge.net/release20210415/azcopy_linux_amd64_10.10.0.tar.gz

It is still not working for us.

**Comment by KevinSmall** [comment]
This link: https://azcopyvnext.azureedge.net/release20210415/azcopy_linux_amd64_10.10.0.tar.gz 

is working for us now, thanks, so it seems cache is cleared.

**Comment by segunak** [comment]
> If you are still blocked, please try using our storage account directly: https://azcopyvnextrelease.blob.core.windows.net
> 
> For example: https://azcopyvnextrelease.blob.core.windows.net/release20220511/azcopy_windows_amd64_10.15.0.zip
> 
> Instead of: https://azcopyvnext.azureedge.net/release20220511/azcopy_windows_amd64_10.15.0.zip

Is it generally recommended to use the `azcopyvnextrelease.blob.core.windows.net` domain instead of the `azcopyvnext.azureedge.net`? In terms of reliability and avoiding caching issues.

**Comment by nicoleajoy** [comment]
Seems this is working now, did not make any changes on my end though. How about for you guys?

**Comment by segunak** [comment]
> Seems this is working now, did not make any changes on my end though. How about for you guys?

Same. We did nothing but twiddle our thumbs during a prod deployment yesterday while discussing the latest UK prime minister drama. We then crossed our fingers, re-ran our pipeline and it worked.

**Comment by zezha-msft** [comment]
@segunak It's best practice to use the CDN ([https://azcopyvnext.azureedge.net](https://azcopyvnext.azureedge.net/release20220511/azcopy_windows_amd64_10.15.0.zip)), as it is globally distributed and redundant. But in this case, it accidentally cached some bad results. We've certainly learnt from this issue, and will make sure to not repeat the same mistake again.

I apologize again for the inconvenience that this issue has caused. Please don't hesitate if you are still having any issue.

**Comment by zffocussss** [comment]
@zezha-msft 
When upload files with **az storage blob sync**. the errors were thrown
```
WARNING: Azcopy not found, installing at /root/.azure/bin/azcopy
ERROR: Connection error while attempting to download azcopy 10.13.0. You could also install the specified azcopy version to /root/.azure/bin manually. (<urlopen error [Errno -2] Name does not resolve>)

```
for your investigation

az version: 2.66
os release: alpine-3.18
[az cli code reference](https://github.com/Azure/azure-cli/blob/a0acfb32a5966fac72f54d25639ebc5fbd53a509/src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py#L61)

My conclusion is that the cdn link is not stable at all.Please have a check.

**Comment by crohrer** [comment]
I have the same problem. @zezha-msft can this issue be reopened?

**Comment by katedou** [comment]
I have got the same problem : 

`ERROR: Connection error while attempting to download azcopy 10.13.0. You could also install the specified azcopy version to /home/runner/.azure/bin manually. (<urlopen error [Errno -2] Name or service not known>)`

**Comment by segunak** [comment]
> [@zezha-msft](https://github.com/zezha-msft) When upload files with **az storage blob sync**. the errors were thrown
> 
> ```
> WARNING: Azcopy not found, installing at /root/.azure/bin/azcopy
> ERROR: Connection error while attempting to download azcopy 10.13.0. You could also install the specified azcopy version to /root/.azure/bin manually. (<urlopen error [Errno -2] Name does not resolve>)
> ```
> 
> I also tried to download it manually.
> 
> ```
> wget https://azcopyvnext.azureedge.net/release20211027/azcopy_linux_amd64_10.13.0.tar.gz
> --2025-01-10 11:51:39--  https://azcopyvnext.azureedge.net/release20211027/azcopy_linux_amd64_10.13.0.tar.gz
> Resolving azcopyvnext.azureedge.net (azcopyvnext.azureedge.net)... failed: nodename nor servname provided, or not known.
> wget: unable to resolve host address ‘azcopyvnext.azureedge.net’
> ```
> 
> for your investigation
> 
> az version: 2.66 os release: alpine-3.18 [az cli code reference](https://github.com/Azure/azure-cli/blob/a0acfb32a5966fac72f54d25639ebc5fbd53a509/src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py#L61)
> 
> My conclusion is that the cdn link is not stable at all.Please have a check and cooperate with the [az cli team](https://github.com/Azure/azure-cli),as the **az storage** use the azcopy under the hood

Not sure if this is related to [Azure CDN from Edgio retirement](https://learn.microsoft.com/en-us/azure/cdn/edgio-retirement-faq) Basically the `azureedge.net` is on it's way out. Turns out Microsoft was relying on a third party for its Azure CDN.

![Image](https://github.com/user-attachments/assets/20337b65-c56d-487c-8350-1b9844a2ddcf)

**Comment by crohrer** [comment]
see also https://github.com/Azure/azure-cli/issues/30635

**Comment by zffocussss** [comment]
@segunak 
Ms team is working on this issue.Hopefully the next release can solve it in the end.
see also https://github.com/Azure/azure-cli/issues/30635
