### ISSUE TITLE
AZCOPY for ARM can't be downloaded

### ISSUE THREAD

**Issue by marcserrat** [Azure/azure-storage-azcopy#1934]
Hi Team,

once again seems that azcopy for ARM has disappeared. this time, when trying to download it from the official link at Microsoft page (https://aka.ms/downloadazcopy-v10-linux-arm64) an error is returned

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:f1debaef-d01e-004b-4fc2-e309f3000000 Time:2022-10-19T13:56:36.0118773Z</Message>
</Error>

Can it be fixed again? Thanks

**Comment by segunak** [comment]
> Hi Team,
> 
> once again seems that azcopy for ARM has disappeared. this time, when trying to download it from the official link at Microsoft page (https://aka.ms/downloadazcopy-v10-linux-arm64) an error is returned
> 
> `PublicAccessNotPermitted` Public access is not permitted on this storage account. RequestId:f1debaef-d01e-004b-4fc2-e309f3000000 Time:2022-10-19T13:56:36.0118773Z
> Can it be fixed again? Thanks

+1 on this. Seeing the same issue trying to access https://azcopyvnext.azureedge.net/release20220315/azcopy_windows_amd64_10.14.1.zip. Would appreciate resolution!

**Comment by zezha-msft** [comment]
Really sorry about the problem, I've purged both links, they should work now.
