### ISSUE TITLE
Support creating containers in Azurite

### ISSUE THREAD

**Issue by kimsey0** [Azure/azure-storage-azcopy#1935]
### Which version of the AzCopy was used? 
AzCopy 10.16.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
```pwsh
& azcopy.exe make "http://127.0.0.1:10000/devstoreaccount1/newcontainer?{SAS}"
```

### What problem was encountered?
```
please provide a valid top-level(ex: File System or Container) resource URL
```

### How can we reproduce the problem in the simplest way?
Create a Shared Access Signature link for a non-existing container in a local Azurite installation, then run the command above, substituting the link.

### Have you found a mitigation/solution?
No, not using AzCopy.

**Comment by mirnoca** [comment]
I also have this problem. Glad when it gets fixed

**Comment by vibhansa-msft** [comment]
As of now AzCopy does not support Azurite. We have added this to our backlog, based on customer feedbacks we will prioritize. Closing this from here.

**Comment by kimsey0** [comment]
Thanks for the response, @vibhansa-msft. Where is this backlog you refer to? Is there any reason it's not the issues for this GitHub repository, like for most other Microsoft open-source projects? If it's an internal issue tracker, that makes it pretty hard for us in the community to follow along in the prioritization and development.

**Comment by PiterZet-RB** [comment]
still not implemented? Guys it is 2025 now.
