### ISSUE TITLE
Allow copying folder of folders to Azure storage account

### ISSUE THREAD

**Issue by kimsey0** [Azure/azure-storage-azcopy#1936]
### Which version of the AzCopy was used? 
AzCopy 10.16.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
```pwsh
# Setup to create local folder
& azcopy.exe copy "http://127.0.0.1:10000/devstoreaccount1?{SAS}" C:\localfolder\ --recursive --from-to BlobLocal

# Failing command
& azcopy.exe copy C:\localfolder\ "http://127.0.0.1:10000/devstoreaccount1?{SAS}" --recursive --from-to LocalBlob
```

### What problem was encountered?
`failed to perform copy command due to error: failed to initialize enumerator: cannot transfer individual files/folders to the root of a service. Add a container or directory to the destination URL`

### How can we reproduce the problem in the simplest way?
Create a Shared Access Signature link with full permissions for a local Azurite instance or an Azure Storage account. Create an empty folder. Run commands above, substituting the SAS link and the path to the local folder.

### Have you found a mitigation/solution?
Copying directly from one storage account to another is sometimes an option, but not always.
Otherwise, you have to iterate over the subfolders, create containers (which [cannot be done with AzCopy for Azurite](https://github.com/Azure/azure-storage-azcopy/issues/1935)), then copy the content of the folder into the new container.

### Implementation notes
If AzCopy adds support for copying a folder of folders to an Azure storage account, it could either ignore files in the root folder or abort if it finds any.

**Comment by vibhansa-msft** [comment]
As of now AzCopy does not support Azurite. We have added this to our backlog, based on customer feedbacks we will prioritize. Closing this from here.
