### ISSUE TITLE
Put pre-built binaries of azcopy in GitHub releases

### ISSUE THREAD

**Issue by cutecycle** [Azure/azure-storage-azcopy#1937]
In light of recent issues:
#1934 
#1933 

I think it may be best to have azcopy's binaries published on GitHub as part of the CI process. This gives the process of downloading azcopy as part of CI pipelines more consistency.

**Comment by segunak** [comment]
> In light of recent issues: #1934 #1933
> 
> I think it may be best to have azcopy's binaries published on GitHub as part of the CI process. This gives the process of downloading azcopy as part of CI pipelines more consistency.

Agreed. Have seen several issues as of late attempting to download azcopy for use, as have other users. More transparency would be great!

**Comment by zezha-msft** [comment]
Thanks for the feedbacks!

We are really sorry for this problem that occurred. I agree with you, we will look into more ways of publishing AzCopy so that there's redundancy in case of a problem.

**Comment by nakulkar-msft** [comment]
Hi, we'll be moving to more stable ways of publishing. At this point, we are continuing our decision to not publish binaries on Github.
