### ISSUE TITLE
Log "Using blob endpoint on destination HNS account" at a higher severity

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-storage-azcopy#1938]
https://github.com/Azure/azure-storage-azcopy/blob/418594894e14b6f800428509b5c876eda7e59221/cmd/copy.go#L282

Since the user is making no explicit choice in azcopy to use the Blob API, they may be surprised if/when they then try and edit one of the files that they synced using the same `dns` root URI but bump into the [limitation that](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-known-issues#blob-storage-apis), "You cannot use blob APIs, NFS 3.0, and Data Lake Storage APIs to write to the same instance of a file."

The severity for the logged message should be higher, or at least more details should be provided about that limitation.

**Comment by tasherif-msft** [comment]
Hi @Arithmomaniac I have put up a PR to provide extra info https://github.com/Azure/azure-storage-azcopy/pull/2002

**Comment by Arithmomaniac** [comment]
LGTM. Would close the issue but I don't know at which step of the release pipeline you usually do that.

**Comment by tasherif-msft** [comment]
We can close it now. It will be in our next release!
