### ISSUE TITLE
Failure to recursively delete a directory with many nested subdirectories

### ISSUE THREAD

**Issue by tikkanu** [Azure/azure-storage-azcopy#1939]
##### Note: The version is visible when running AzCopy without any argument

AzCopy 10.16.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows 10

### What command did you run?

azcopy rm "https://storageaccountname.file.core.windows.net/fileshare/directory1/directory1a?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2022-10-25T15:21:10Z&st=2022-10-24T07:21:10Z&spr=https&sig=REDACTED" --recursive

### What problem was encountered?

INFO: Trying 4 concurrent connections (initial starting point)
panic: runtime error: slice bounds out of range [:104] with length 84

goroutine 3087 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.(*standardFolderDeletionManager).getParent(0x0, 0xc001108090)
        /home/vsts/work/1/s/common/folderDeletionManager.go:133 +0x1d2
github.com/Azure/azure-storage-azcopy/v10/common.(*standardFolderDeletionManager).RecordChildExists(0xc000640450, 0x70290443e2382b64)
        /home/vsts/work/1/s/common/folderDeletionManager.go:156 +0x33
github.com/Azure/azure-storage-azcopy/v10/ste.DeleteFile({0xd19e10, 0xc00012c460}, {0xcdf920, 0xc000c32240}, {0x3, 0xabaa60})
        /home/vsts/work/1/s/ste/xfer-deleteFile.go:34 +0x13f
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartMgr).StartJobXfer(0x137b6a0, {0xd19e10, 0xc00012c460})
        /home/vsts/work/1/s/ste/mgr-JobPartMgr.go:715 +0x50
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).StartJobXfer(0xc00012c460)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:236 +0x32
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor.func1({0xd19e10, 0xc00012c460})
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:1015 +0x1b9
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor(0xc00090e000, 0xc00021db00)
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:1027 +0xc2
created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:200 +0xbf4
panic: runtime error: slice bounds out of range [:104] with length 84

goroutine 3057 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.(*standardFolderDeletionManager).getParent(0x0, 0xc000634090)
        /home/vsts/work/1/s/common/folderDeletionManager.go:133 +0x1d2
github.com/Azure/azure-storage-azcopy/v10/common.(*standardFolderDeletionManager).RecordChildExists(0xc000640450, 0x70290443e2382b64)
        /home/vsts/work/1/s/common/folderDeletionManager.go:156 +0x33
github.com/Azure/azure-storage-azcopy/v10/ste.DeleteFile({0xd19e10, 0xc00012c4d0}, {0xcdf920, 0xc000c32240}, {0x3, 0xabaa60})
        /home/vsts/work/1/s/ste/xfer-deleteFile.go:34 +0x13f
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartMgr).StartJobXfer(0x137b6a0, {0xd19e10, 0xc00012c4d0})
        /home/vsts/work/1/s/ste/mgr-JobPartMgr.go:715 +0x50
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).StartJobXfer(0xc00012c4d0)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:236 +0x32
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor.func1({0xd19e10, 0xc00012c4d0})
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:1015 +0x1b9
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor(0xc00090e000, 0x0)
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:1027 +0xc2
created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:200 +0xbf4
panic: runtime error: slice bounds out of range [:73] with length 61

goroutine 3088 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.(*standardFolderDeletionManager).getParent(0x0, 0xc0006bc1b0)
        /home/vsts/work/1/s/common/folderDeletionManager.go:133 +0x1d2
github.com/Azure/azure-storage-azcopy/v10/common.(*standardFolderDeletionManager).RecordChildExists(0xc000640450, 0x70290443e2382b64)
        /home/vsts/work/1/s/common/folderDeletionManager.go:156 +0x33
github.com/Azure/azure-storage-azcopy/v10/ste.DeleteFile({0xd19e10, 0xc00012c3f0}, {0xcdf920, 0xc000c32240}, {0x3, 0xabaa60})
        /home/vsts/work/1/s/ste/xfer-deleteFile.go:34 +0x13f
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartMgr).StartJobXfer(0x137b6a0, {0xd19e10, 0xc00012c3f0})
        /home/vsts/work/1/s/ste/mgr-JobPartMgr.go:715 +0x50
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).StartJobXfer(0xc00012c3f0)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:236 +0x32
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor.func1({0xd19e10, 0xc00012c3f0})
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:1015 +0x1b9
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor(0xc00090e000, 0xc000328480)
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:1027 +0xc2
created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr
        /home/vsts/work/1/s/ste/mgr-JobMgr.go:200 +0xbf4

### How can we reproduce the problem in the simplest way?

Run "AzCopy rm" on a directory (in a file share) with many nested subdirectories.

### Have you found a mitigation/solution?

No

**Comment by tikkanu** [comment]
Correction for the mitigation/solution:

I was able to delete the folders by mapping the file share onto the workstation. However, this is merely a temporary workaround. I would really like to know if there is some path limit I have hit, or this is a bug.

Thank you.

**Comment by tikkanu** [comment]
Thank you Adreed!

**Comment by gapra-msft** [comment]
Hi @tikkanu. The fix for this issue was released in AzCopy 10.16.2 through this PR https://github.com/Azure/azure-storage-azcopy/pull/1927/files so I am going to go ahead and close this issue. If you still hit the issue, please feel free to reopen it.

**Comment by tikkanu** [comment]
Thank you!
