### ISSUE TITLE
Can't detect new Azcopy version after update

### ISSUE THREAD

**Issue by je-delacruz** [Azure/azure-storage-azcopy#1940]
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What problem was encountered?
I replaced the azcopy file to the latest download link but it still detects my previous version.  Please help and let me know if im missing something.

**Comment by nakulkar-msft** [comment]
Hi @je-delacruz, can you describe a few more details?
What is the current version of AzCopy you're using? (Run azcopy without any arguments)
If you're using the latest version, you wont see any prompts for update. The most recent version is 10.16.1.

**Comment by je-delacruz** [comment]
Hi @nakulkar-msft , im running on 10.3.3 and I need to update to 10.16.1 for the --properties flag for azcopy list.
I download the tar.gz file and extracted the azcopy file then replaced the file which is on my linux. I ran the command and it still running on 10.3.3
<img width="960" alt="image" src="https://user-images.githubusercontent.com/55268123/197759405-32da9e4f-e29c-4db9-856d-a9b60ae97795.png">

**Comment by je-delacruz** [comment]
Looks like the azcopy is executing from /usr/bin not on the folder which I put the updated the azcopy. I would need to direclty use the azcopy from the folder I put the 10.16.1 version. Thanks @nakulkar-msft for your help!
