### ISSUE TITLE
AzCopy with file share failed when --overwrite=ifSourceNewer, should be skip

### ISSUE THREAD

**Issue by aleblanc70** [Azure/azure-storage-azcopy#1943]
### Which version of the AzCopy was used? 
10.16.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
### What command did you run?
azcopy cp [file] "https://xxxxxx.file.core.windows.net/hsc-installer/[SAS]" --overwrite=ifSourceNewer --recursive=true --check-length=false

Remarque: My SAS token is write only.

### What problem was encountered?
**_We should have a more meaning full message or at least have a 1 Skipped when the file is present._**

INFO: Scanning...
INFO: Any empty folders will be processed, because source and destination both support folders

Job ad93e445-bf55-b040-4f7f-355150d1bb10 has started
Log file is located at: /root/.azcopy/ad93e445-bf55-b040-4f7f-355150d1bb10.log

INFO: Trying 4 concurrent connections (initial starting point)
0.0 %, 0 Done, **_1 Failed_**, 0 Pending, 0 Skipped, 1 Total, 

Job ad93e445-bf55-b040-4f7f-355150d1bb10 summary
Elapsed Time (Minutes): 0.0333
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
_**Number of Transfers Failed: 1**_
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
_**Final Job Status: Failed**_

### How can we reproduce the problem in the simplest way?
run the command with a SAS token that have write only permission

### Have you found a mitigation/solution?
Remove --overwrite=ifSourceNewer

**Comment by nakulkar-msft** [comment]
Hi @aleblanc70, this behaviour is intentional and will not be changed. If azcopy cannot determine the last-modified-time on destination, it cannot decide if the file has to be transferred. With the write-only SAS, we cannot fetch last-modified-time. Because this failure is per file basis, more info will be logged to log file.
