### ISSUE TITLE
login failure using certificate without a password

### ISSUE THREAD

**Issue by El-Gor-do** [Azure/azure-storage-azcopy#1944]
### Which version of the AzCopy was used? 
10.16.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
From a Windows command prompt, run the following commands
```
set AZCOPY_AUTO_LOGIN_TYPE=SPN
set AZCOPY_SPA_APPLICATION_ID=<clientId>
set AZCOPY_SPA_CERT_PATH=<path to my .pfx certificate>
set AZCOPY_TENANT_ID=<tenantId>
azcopy list https://<accountName>.blob.core.windows.net/<containerName>
```

### What problem was encountered?
AzCopy fails with `failed to obtain credential info: Login Credentials missing. No SAS token or OAuth token`

The certificate has a private key but no password. According to https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/storage/common/storage-use-azcopy-authorize-azure-active-directory.md#authorize-a-service-principal-by-using-a-certificate-1 the certificate should have a password, not must have a password.

The same tenant ID, client ID and certificate work fine when using C# and the Azure.Storage.Blobs package v12.8.0 to list blobs in a container.

### How can we reproduce the problem in the simplest way?
Run the commands mentioned above

### Have you found a mitigation/solution?
No. I originally raised this bug in https://github.com/Azure/azure-storage-azcopy/issues/1755 and it was incorrectly closed. This bug is not the same as https://github.com/Azure/azure-storage-azcopy/issues/1753 or https://github.com/Azure/azure-storage-azcopy/issues/1805. This bug is not being able to use a certificate that doesn't have a password.

**Comment by adreed-msft** [comment]
Apologies about the accidental closing.

Could you attempt to log in with AzCopy login rather than the auto-login? This will output useful information about why authorization is failing.

In the meantime, I'm going to go fix the issue with auto-login not providing details of failure.

**Comment by El-Gor-do** [comment]
I am using azcopy in a corporate environment, attempting to access company's Storage Account. Using ```azcopy login```, after browsing to https://microsoft.com/devicelogin and entering the code shown by azcopy, I provided my username/password and the login page returns this warning:
```
Your sign-in was successful, but your admin requires the device that's requesting access to be managed by {admin} to access this resource.
```

When I then run ```azcopy list https://<accountName>.blob.core.windows.net/<containerName>``` I get this error:
```
INFO: Authenticating to source using Azure AD

failed to obtain credential info: no cached token found, please log in with azcopy's login command
```

**Comment by vibhansa-msft** [comment]
We have added additional logging for such failures. This will be part of next release (10.17.0). Feel free to reopen if issue persists.
