### ISSUE TITLE
Cross-compiling from Windows 10 64-bit to Linux ARM 32-bit fails

### ISSUE THREAD

**Issue by smuehlst** [Azure/azure-storage-azcopy#1945]
### Which version of the AzCopy was used? 

Trying to build azcopy for Raspberry Pi Linux ARM 32-bit by cross-compiling on Windows 10 64-bit, as of commit 418594894e14b6f800428509b5c876eda7e59221.

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows 10 64-bit

### What command did you run?

Installed Go from [go1.19.2.windows-amd64.msi](https://go.dev/dl/go1.19.2.windows-amd64.msi).
Cloned `git@github.com:Azure/azure-storage-azcopy.git`.

From PowerShell command line:

```
E:\Users\stm\Documents\GitHub\azure-storage-azcopy [main ≡]> $env:GOOS = "linux"
E:\Users\stm\Documents\GitHub\azure-storage-azcopy [main ≡]> $env:GOARCH = "arm"
E:\Users\stm\Documents\GitHub\azure-storage-azcopy [main ≡]> go build
...
# github.com/Azure/azure-storage-azcopy/v10/ste
ste\sourceInfoProvider-Local_linux.go:126:9: cannot use s.Nlink (variable of type uint32) as type uint64 in return statement
```
### What problem was encountered?

Cross-compilation for Linux ARM 32-bit failed with above error message.

### How can we reproduce the problem in the simplest way?

See above.

### Have you found a mitigation/solution?

No.

**Comment by nakulkar-msft** [comment]
fixed in branch dev
