### ISSUE TITLE
Copy with a base64 metadata value fails with "invalid metadata string passed"

### ISSUE THREAD

**Issue by ivanp-ms** [Azure/azure-storage-azcopy#1946]
### Which version of the AzCopy was used? 
AzCopy 10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
.\azcopy copy .\test.txt "https://xxx.blob.core.windows.net/share?sp=rw&st=2022-11-01T17:44:45Z&se=2022-11-02T01:44:45Z&spr=https&sv=2021-06-08&sr=c&sig=xxx" --metadata "foo=dGVzdCBtZXRhZGF0YQ=="

### What problem was encountered?
**failed to parse user input due to error: invalid metadata string passed**

### How can we reproduce the problem in the simplest way?
It seems the equal signs in the base64 padding is causing the problem, so copying any file with metadata value containing equal signs should repro the problem.

### Have you found a mitigation/solution?
No. One could try to escape those equal signs and restore them on read but in our case it is not possible since another part of the system is not using azcopy to upload blobs with metadata.

**Comment by adreed-msft** [comment]
Simple bug. I'll push it through for 10.17.0
