### ISSUE TITLE
Feature Request: Enhance Job summary

### ISSUE THREAD

**Issue by mstenz** [Azure/azure-storage-azcopy#1947]
This is an example of a job summary

```
Job 58c00558-22ad-4d47-4292-8e3b7d20e99f summary
Elapsed Time (Minutes): 27.4721
Number of File Transfers: 69252
Number of Folder Property Transfers: 51863
Total Number of Transfers: 121115
Number of Transfers Completed: 120986
Number of Transfers Failed: 129
Number of Transfers Skipped: 0
TotalBytesTransferred: 48585824404
Final Job Status: CompletedWithErrors
```

The Number of Files and Folder Property Transfers is split and gives a total Number of Transfers first, but then in further statistics, it is not anymore. 
Especially in  "Number of Transfers Failed" it is unknown if this references to folders and/or files. 

It would be good if the statistics contain more granular information. Also adding more details like average transfer speed and so on would be valuable.

**Comment by gapra-msft** [comment]
File/Folder granularity in PR.

TODO: Average transfer speed

**Comment by mstenz** [comment]
there also can be a "TotalBytesTransferred" in human readable format B/KB/MB/GB/TB and so on.
