### ISSUE TITLE
https://aka.ms/downloadazcopy No longer available

### ISSUE THREAD

**Issue by saji-code** [Azure/azure-storage-azcopy#1951]
We are facing an issue while downloading MicrosoftAzureStorageAzCopy_netcore_x64.msi .The link https://aka.ms/downloadazcopy no longer available

**Comment by adreed-msft** [comment]
We are aware of the discrepancy. Unfortunately we do not maintain AzCopy v8.1. We are trying to reach out to relevant individuals to get this fixed.
