### ISSUE TITLE
Difference between clean and remove command

### ISSUE THREAD

**Issue by richardMSFT** [Azure/azure-storage-azcopy#1954]
### Which version of the AzCopy was used? 
10.16.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Mac
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy jobs clean 

azcopy jobs remove

### What problem was encountered?

What is the difference between the `clean` and `remove` command? Is it just that `clean` removes the plans and logs for all jobs? Is there any difference under the hood?

Does the `remove` command clean anything beyond logs and plans? The feature I'm working on requires me to remove only the logs.

Thanks!

### How can we reproduce the problem in the simplest way?

N/A

### Have you found a mitigation/solution?

N/A

**Comment by adreed-msft** [comment]
Hi there Richard! There is in fact a difference. Remove is intended for use against one particular job, Clean is intended to remove data for jobs with successful states.

Please re-open if you have more questions about the difference between these commands.
