### ISSUE TITLE
azcopy remove with --list-of-files option throws errors

### ISSUE THREAD

**Issue by ngorur** [Azure/azure-storage-azcopy#1957]
### What command did you run?
azcopy.exe login --aad-endpoint https://login.microsoftonline.us
azcopy remove "container" --recursive=false --list-of-files="FileNameListforDeletion.txt" --delete-snapshots "include"
### What problem was encountered?
Part#=0 failed to refresh token, please check error details and try to log in with azcopy login command again. (Error details: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_grant","error_description":"AADSTS50196: The server terminated an operation because it encountered a client request loop. Please contact your app vendor.\r\nTrace ID: redacted\r\nCorrelation ID: redacted\r\nTimestamp: 2022-11-09 20:52:49Z","error_codes":[50196],"timestamp":"2022-11-09 20:52:49Z","trace_id":"redacted","correlation_id":"redacted","error_uri":"https://login.microsoftonline.us/error?code=50196"} Endpoint https://login.microsoftonline.us/common/oauth2/token?api-version=1.0)

### How can we reproduce the problem in the simplest way?
run the above command, ensure the FileNameListforDeletion.txt has at least 20 filenames

**Comment by adreed-msft** [comment]
I cannot reproduce this.

Do other commands work over OAuth for you? Or is it *only* delete that fails?

**Comment by tasherif-msft** [comment]
Hi @ngorur we're working on a fix at the moment! will update you once a PR is out

**Comment by ngorur** [comment]
Thanks

Nanda Gorur
Senior Consultant | Azure Cloud and AI | Microsoft Federal
Work: 301 771 8294 | Mobile: 201 213 8364 | ***@***.******@***.***>



________________________________
