### ISSUE TITLE
v7 Link is no longer available

### ISSUE THREAD

**Issue by Charles808** [Azure/azure-storage-azcopy#1959]
https://azcopy.azureedge.net/azcopy-7-3-1/MicrosoftAzureStorageAzCopy.msi

This link is no longer available.
I need it for Table Storage Copy. 

Is there any alternative link ?

**Comment by bs-fl** [comment]
We also need this version available for compatibility with other applications.
https://azcopy.azureedge.net/azcopy-7-3-0/azcopy_7.3.0-netcore_linux_x64.tar.gz

**Comment by adreed-msft** [comment]
I believe this should be resolved now. Please re-open if it is not.

**Comment by Hyleon-Ou** [comment]
Hi @adreed-msft, 

https://aka.ms/downloadazcopynet
The link is no longer available again.
Could you pls help us?
