### ISSUE TITLE
[2022/11/11 18:10:38][ERROR] Unexpected end of file.

### ISSUE THREAD

**Issue by walamami** [Azure/azure-storage-azcopy#1960]

**Comment by adreed-msft** [comment]
Hi there. We do not maintain AzCopy V8 and cannot provide support for it.

If you are not in need of Tables support, we advise you to upgrade to AzCopy V10. You can download binaries for your operating system [here](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10).

A guide is available to [help migrating to V10](https://github.com/Azure/azure-storage-azcopy/blob/main/MigrationGuideV8toV10.md).

I will close this issue now. If you have any questions or concerns about V10, we welcome you to open a new thread.

**Comment by walamami** [comment]
I unable to upgrade AZCopy version on windows server 16,

Error saying "This App can't run on your pc"

**Comment by adreed-msft** [comment]
Well, that's bizarre. Have you tried running AzCopy under compatibility modes? Does your server use any kind of antivirus that could cause this? Are there any special group policies etc.?
