### ISSUE TITLE
Error Launching AZCopy

### ISSUE THREAD

**Issue by IndigoChrist** [Azure/azure-storage-azcopy#1965]
### Which version of the AzCopy was used? 
AzCopy 10.16.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac 10.14.6 

### What command did you run?
None

### What problem was encountered?
I think I missed something when "installing", but when opening AZCopy I do not have the possibility to enter anything. The process is terminated directly.

iMac-?:~ ?$ /Applications/azcopy ; exit;
AzCopy 10.16.2
Project URL: github.com/Azure/azure-storage-azcopy

AzCopy is a command line tool that moves data into and out of Azure Storage.
To report issues or to learn more about the tool, go to github.com/Azure/azure-storage-azcopy

The general format of the commands is: 'azcopy [command] [arguments] --[flag-name]=[flag-value]'.

Usage:
  azcopy [command]

    [...]  

Use "azcopy [command] --help" for more information about a command.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Prozess beendet]

### How can we reproduce the problem in the simplest way?
I don't know

### Have you found a mitigation/solution?
Not yet

**Comment by nakulkar-msft** [comment]
Hi,
AzCopy is not interactive. All the parameters for command need to be given on the command itself. [Documentation](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10) for AzCopy.
