### ISSUE TITLE
Possible to tell if azcopy is logged in?

### ISSUE THREAD

**Issue by hongooi73** [Azure/azure-storage-azcopy#197]
Is there a way to tell, programmatically, if `azcopy login` or `azcopy logout` has been previously run on this machine? I'd like to know if it's going to use OAuth authentication or something else when I go to transfer a file.

I looked in the `c:\users\<username>\.azcopy` directory but there wasn't anything that looked like a token.

**Comment by zezha-msft** [comment]
Hi @Hong-Revo, thanks for reaching out!

I'll discuss your suggestion with the team.

**Comment by ollieatkinson** [comment]
This would be a useful feature. I need to know if the consumer is logged into `azcopy` before attempting any operations, so that I can ask them to login.

**Comment by zezha-msft** [comment]
Hi @ollieatkinson, could you please elaborate a bit on your use case? Do you need to know any other information? I.e. is a simple "yes" enough or do you need to know more about how the user is logged in?

**Comment by ollieatkinson** [comment]
> Hi @ollieatkinson, could you please elaborate a bit on your use case? Do you need to know any other information? I.e. is a simple "yes" enough or do you need to know more about how the user is logged in?

A simple yes or no answer would suffice, I am including it as a step in a `Makefile` and it would be useful to give a descriptive error (or just ask them to login) if they are not currently signed into the tool.

As long as they are authenticated it's fine to move on.

**Comment by ollieatkinson** [comment]
I am using this workaround until support is added into the tool:

```makefile
login:
	@azcopy list "https://myskyappdependencies.blob.core.windows.net/binaries${AZURE_SAS_TOKEN}" \
		| grep "ServiceCode=ResourceNotFound" > /dev/null \
		&& open https://microsoft.com/devicelogin \
		&& echo "Please login with the code:" \
		&& azcopy $@ \
		| sed -n "s/.*code \(.*\) to.*$$/\1/p" \
		&& echo "Logged in!" \
		|| echo "Logged in!"
```

**Comment by JohnRusk** [comment]
On Linux we store the logged-in token in the SessionKey ring.  If you do `keyctl show` after logging in you'll see which keyname we use.  You can probably just grep the result of keyctl show, for that key-name string.

Note that this doesn't confirm that the token is still valid, but given their relatively long lifetimes, it's reasonably reliable.

**Comment by ollieatkinson** [comment]
Thanks @JohnRusk. We are currently using this for macOS - is the mechanism the same but using the Keychain?

**Comment by JohnRusk** [comment]
Yes.

**Comment by ollieatkinson** [comment]
Thanks @JohnRusk 

```make
login:
	@security find-generic-password -a AzCopyOAuthTokenCache \
		&& open https://microsoft.com/devicelogin \
		&& azcopy $@ \
		|| echo "Logged in!"
```

**Comment by felickz** [comment]
Windows version

`$isAzCopyLoggedIn = Test-Path "$env:USERPROFILE\.azcopy\accessToken.json" -PathType Leaf`

**Comment by nakulkar-msft** [comment]
This is available in the new version.
`PS C:\Users\nakulkar\Desktop> .\azcopy --version
azcopy version 10.12.2`
`PS C:\Users\nakulkar\Desktop> .\azcopy login status
INFO: You have successfully refreshed your token. Your login session is still active`
