### ISSUE TITLE
AZCOPY 10.16.2 Error 403 Authentication

### ISSUE THREAD

**Issue by AndyH010493** [Azure/azure-storage-azcopy#1970]
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run? 
Starting transfer: Source "/mnt/HGSL_SAN01/Auto_Archive/.Hidden/hwr0hgsl0000000000visage/1.mov" Destination "https://hwr0hgsl0000000000visage.blob.core.windows.net/fromhgslsan01/hwr0hgsl0000000000visage/1.mov

### What problem was encountered?
2022/11/18 13:45:11 == REQUEST/RESPONSE (Try=1/6.481485ms, OpTime=48.129368ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://hwr0hgsl0000000000visage.blob.core.windows.net/fromhgslsan01/hwr0hgsl0000000000visage/1.mov
   User-Agent: [AzCopy/10.16.2 Azure-Storage/0.15 (go1.17.9; linux)]
   X-Ms-Client-Request-Id: [80a26e92-40e6-4018-6b75-8519e84eb2d5]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Date: [Fri, 18 Nov 2022 13:45:10 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [c615d550-401e-0056-2c53-fb615e000000]
Response Details: 

### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
Tracing above request showed that the SAS used with the command was invalid. Please generate a different SAS and try again.

**Comment by AndyH010493** [comment]
Hello, thanks for the reply.

I am making the SAS via the below method via az cli, the sas is generated properly but not working?

az storage container generate-sas --account-name $accountname --account-key $acckey --name $container --permissions racwdl --expiry $date

**Comment by nakulkar-msft** [comment]
Did you try generating SAS from portal or Storage Explorer? Also, do you have firewall enabled on the storage account?
