### ISSUE TITLE
Broken symlinks barely reported (when using --follow-symlink=true)

### ISSUE THREAD

**Issue by marc-hb** [Azure/azure-storage-azcopy#1974]
### Which version of the AzCopy was used? 

10.16.2

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

`azcopy copy --recursive --follow-symlink=true`

### What problem was encountered?

Broken symbolic links are barely reported:

- Broken symbolic links are not mentioned at all in the otherwise super verbose `$HOME/.azcopy/*.log`
- The exit code is `0` / success
- They get reported on `stdout` but only at the lowest INFO level, should be an ERROR
```
INFO: Failed to resolve symlink brokenlink.html: lstat doesnotexist: no such file or directory
```

`--follow-symlink=true` is not the default option. This means the user passing `--follow-symlink=true`  really cares about symbolic links being resolved. So a failure to follow a symlink them should be much, much more visible.

### How can we reproduce the problem in the simplest way?

Create a broken symbolic link and try to use `azcopy copy --recursive --follow-symlink=true`. 

### Have you found a mitigation/solution?

No.

**Comment by marc-hb** [comment]
Ignoring ERRORs is not a just "user experience" problem, far from it. Ignored ERRORs give the wrong information that everything went fine, this is very serious.

At the very least the log level should be raised and the error code changed.

**Comment by argretzi** [comment]
I see this was added to the 10.17.0 milestone, what is the thought that the change might be?

**Comment by nakulkar-msft** [comment]
@argretzi This will be logged at a higher severity. However, the job will not report failure. Any failure during traversing source will be reported at a higher severity, but will not result in faiure of job.

**Comment by marc-hb** [comment]
@nakulkar-msft what do you mean by "failure"? To clarify I never meant aborting the current job. For sure it should keep processing other files. However the exit status should not be zero.

**Comment by marc-hb** [comment]
@nakulkar-msft you missed my last question: what do mean exactly by "failure"? Exit status or aborting the job or both? Please clarify.

**Comment by nakulkar-msft** [comment]
The exit status will be zero. Any failure during traversing source will be reported at a higher severity, but will not result in non-zero exit status.
