### ISSUE TITLE
`azcopy remove https://server/area/file_that_does_not_exist` does not fail

### ISSUE THREAD

**Issue by marc-hb** [Azure/azure-storage-azcopy#1975]
### Which version of the AzCopy was used? 

10.16.2

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

azcopy remove https://server/area/file_that_does_not_exist 

### What problem was encountered?

The command does not fail; it pretends everything was fine.

No ERROR or WARNING in `$HOME/.azcopy`, nothing on stdout either and a successful, zero exit code. Happy as a clam!

### How can we reproduce the problem in the simplest way?

Try to `azcopy remove` a file that does not exist.

### Have you found a mitigation/solution?

No

**Comment by tasherif-msft** [comment]
Hi @marc-hb this is a duplicate issue to https://github.com/Azure/azure-storage-azcopy/issues/1931, we are currently working on it. I will close this issue in the meantime.

**Comment by marc-hb** [comment]
Thanks @tasherif-msft, it's not obvious that it is a duplicate because #1931 is about downloading and this one is about deleting. Are you saying these two features share the same, relevant code?
- #1931

**Comment by tasherif-msft** [comment]
Hi @marc-hb it falls within the same category (don't throw if a targeted file does not exist)
