### ISSUE TITLE
AZ copy duraiton

### ISSUE THREAD

**Issue by aslam2790** [Azure/azure-storage-azcopy#1978]
I need to copy data from one tenant to another using AZcopy(using storage account). my file size is around 250TB. What is the approx duration to complete the data transfer. Also do we have any calculator availble to measure this?

**Comment by nakulkar-msft** [comment]
The time depends on the number of files, size per file, location of the data, sku of the client vm. There are too many variables, and it would be advisable to start the transfer/benchmark command in azcopy to perform the estimate.
