### ISSUE TITLE
Azcopy failing | Authorized via AAD, but asking for SAS token or access key

### ISSUE THREAD

**Issue by snsaran-msft** [Azure/azure-storage-azcopy#1985]
### Which version of the AzCopy was used? 
10.8.0
### Which platform are you using? (ex: Windows, Mac, Linux) 
Windows

### What command did you run?
azcopy copy "https://source-storage.blob.core.windows.net/container-name" "https://dest-storage.blob.core.windows.net/" --recursive

### What problem was encountered?
failed to perform copy command due to error: a SAS token (or S3 access key) is required as a part of the source in S2S transfers, unless the source is a public resource

I was able to run it locally for MSFT tenant but not able to run it in torus tenant
Have granted storage blob data contributor role 
I am able to do a make "container" in src and dest storage accounts using azcopy so it tells me that I have the right permissions set

### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
10.8 is older version, and will require SAS on source. Use current version of azcopy and the destination credentials will be forwarded to source.
