### ISSUE TITLE
Azcopy stopped working for blob copy from one storage account to another

### ISSUE THREAD

**Issue by KillerFrost2000** [Azure/azure-storage-azcopy#1989]
### What command did you run? 
azcopy cp "https://source.blob.core.windows.net/?[SAS]" "https://destination.blob.core.windows.net/?[SAS]" --recursive=true --preserve-smb-permissions=true --preserve-smb-info=true

### Have you found a mitigation/solution?
No

**Comment by gapra-msft** [comment]
Hi @KillerFrost2000 Could you please share more information here? A snippet of the logs where the command fails would help, or a brief snippet on how to reproduce the issue. Sharing information on the permissions on the SAS tokens would help as well.
