### ISSUE TITLE
ADLS Gen2 - B2B User : provide relevant error message when tenantid not provided

### ISSUE THREAD

**Issue by kvaes** [Azure/azure-storage-azcopy#199]
### What command did you run?
(login with B2B user, where the tenant is different from the one of the owner of the storage account)
azcopy login
azcopy cp https://testaccount.dfs.core.windows.net/testcontainer/testfile. /test
=> "failed to perform copy command due to error: cannot start job due to error: the destination must be an existing directory in this download scenario."

(login with B2B user, whilst specifying the tenant of the one of the owner of the storage account)
azcopy login --tenant-id *insert tenant id of storage account/subscription owner*
azcopy cp https://testaccount.dfs.core.windows.net/testcontainer/testfile. /test
=> Scanning...
Using OAuth token for authentication.

Job eb7e7868-f41e-ad44-78ee-ea6a922a8015 has started

Log file is located at: /home/kvaes/.azcopy/eb7e7868-f41e-ad44-78ee-ea6a922a8015.log
0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total , 2-sec Throughput (Mb/s): 81.0663

Job eb7e7868-f41e-ad44-78ee-ea6a922a8015 summary
Elapsed Time (Minutes): 0.0669
Total Number Of Transfers: 1
Number of Transfers Completed: 1
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 21326192
Final Job Status: Completed

### Expected behaviour? Provide an error message that states that there was an issue with the authentication part.

**Comment by kvaes** [comment]
Update : It seems that the above error message is also shown if the permissions (POSIX ACLs) are not correct. So it's not limited to the the tenant-id.

**Comment by jiacfan** [comment]
@kvaes Thanks for reaching us!  We'll discuss this internal, and update the thread later.

Best Regards,
Jiachen

**Comment by adreed-msft** [comment]
Hi, kvaes, could you provide the complete log for your test with no specified Tenant ID? I suspect there's something important logged that you have omitted. Before AzCopy will reach the error that you had, it will output a graceful error along the lines of `INFO: source is not validated as a single file: <Error>`.

I believe that will help us target what kind of error is the culprit and thus provide a meaningful error message.

**Comment by kvaes** [comment]
Sent the log offline.

**Comment by adreed-msft** [comment]
Hi, this was patched in #358 and has been released as a part of AzCopy 10.2.x. Enjoy!
