### ISSUE TITLE
AzCopy adding empty Content Disposition property when copying files from Storage Explorer

### ISSUE THREAD

**Issue by kranthilam** [Azure/azure-storage-azcopy#1991]
##### Note: The version is visible when running AzCopy without any argument
10.16.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "https://dls2lamuswsippd.file.core.windows.net/docman/File2/00-00003-01_R_1.PDF?sv=2021-10-04xxxx" "https://dls2lamuswsippd.file.core.windows.net/docman-u/File2/00-00003-01_R_1.PDF?sv=2021-10-04xxxx" --overwrite=prompt --from-to=FileFile --preserve-smb-info=true --recursive --log-level=INFO
### What problem was encountered?
After the copy of a file in the Storage explorer from one fileshare to another, on the destination file there is a new Content Disposition property getting added with NULL. This is causing downstream application using these files to fail.
### How can we reproduce the problem in the simplest way?
Copy the file in storage explorer at source and paste in destination.

**Comment by htalluri9** [comment]
any update on fix for the issue ?

**Comment by siminsavani-msft** [comment]
Hi there! I tried to repro your issue using the latest Storage Explorer and was able to see Content Disposition property being transferred properly when transferring from one fileshare to another. Please try the latest version of Storage Explorer and AzCopy let us know if this issue still persists!
