### ISSUE TITLE
azcopy copy using any filtering parameters (include-pattern | include-before | include-after) on large number of items extremely slow scanning

### ISSUE THREAD

**Issue by ZaoDigital** [Azure/azure-storage-azcopy#1995]
##### Note: The version is visible when running AzCopy without any argument
10.16.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
./azcopy copy "https://s3.us-west-2.amazonaws.com/bucketname" "https://storage.blob.core.windows.net/?SAS" --recursive --log-level=DEBUG --check-length=false --overwrite=false --include-before='2022-01-01'

This behavior is also seen when I used --overwrite=ifSourceNewer
### What problem was encountered?
Scanning is occurring extremely slow when there are a lot of items in the overall bucket and using a filtering type of parameter to try and do this in parts. The debug log will fill extremely slowly ~1kb of entries on DEBUG per second roughly such as:

2022/12/16 21:59:58 AzcopyVersion  10.16.2
2022/12/16 21:59:58 OS-Environment  linux
2022/12/16 21:59:58 OS-Architecture  amd64
2022/12/16 21:59:58 Log times are in UTC. Local time is 16 Dec 2022 15:59:58
2022/12/16 21:59:58 ---------START-HTTP---------

2022/12/16 21:59:58 GET /?delimiter=&fetch-owner=true&list-type=2&max-keys=1000&prefix= HTTP/1.1
Host: bucket.s3.dualstack.us-west-2.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.14
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20221216/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=-REDACTED-
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20221216T215958Z
Accept-Encoding: gzip

2022/12/16 21:59:58 HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 16 Dec 2022 21:59:59 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-west-2
X-Amz-Id-2: someid
X-Amz-Request-Id: someid

2022/12/16 21:59:58 ---------END-HTTP---------

and it will not create a log file like usual while it does this very slowly

### How can we reproduce the problem in the simplest way?
Have an S3 bucket with 40 million+ files and try to segment a copy using filtering parameters

### Have you found a mitigation/solution?
No I will have to run azcopy for a week to do it without filtering on all items at once,. I've tried all the optimization options I can find on the internet and nothing will speed this particular situation up

**Comment by vibhansa-msft** [comment]
@ZaoDigital : Providing any sort of filtering criteria does not help AzCopy in terms of listing the files. It will always list all files (40million+) in your case and then apply all the filters on received items as and when they arrive. As total number of files to be listed is huge, backend will take its own time and multiple iterations to go through entire list. Backend does not provide any filtering option which can help us reduce the number of calls and time spent on listing.

**Comment by ZaoDigital** [comment]
when I look at the debug scanning logs, though, it is scanning extremely slow as if it wasn't doing pages sizes of 1000 but rather one at a time

**Comment by vibhansa-msft** [comment]
Kindly share logs that report this scanning of one item at a time.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update, feel free to reopen once required info is available.
