### ISSUE TITLE
Why does `azcopy jobs list` show `Completed` status but `azcopy jobs show <jobid>` show `InProgress`?

### ISSUE THREAD

**Issue by gitgithan** [Azure/azure-storage-azcopy#2003]
### Which version of the AzCopy was used? 
10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux 

### What command did you run?
`azcopy jobs show <jobid>`

### What problem was encountered?
Output shows `Final Job Status: InProgress` but Completed status is expected

### How can we reproduce the problem in the simplest way?
Not sure how to do that, i was following https://learn.microsoft.com/en-us/training/modules/copy-blobs-from-command-line-and-code/6-exercise-move-blobs-using-azcopy

### Have you found a mitigation/solution?
No

![image](https://user-images.githubusercontent.com/29853829/209062913-6ce1b8d2-58d5-4213-8b85-9d517299face.png)

I have verified from the portal and cli that the copy was completed

**Comment by siminsavani-msft** [comment]
Hi there! I have tried to repro and when I do `azcopy jobs show <>` for a `Completed` job, it appears as `Completed` in the info as well. Please try the latest AzCopy version and let us know if this issue still persists!
