### ISSUE TITLE
Feature request: azcopy -4, -6 flags to force IPv4 or IPv6

### ISSUE THREAD

**Issue by juju4** [Azure/azure-storage-azcopy#2005]
### Which version of the AzCopy was used? 
10.16.2/latest

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows, Linux

### What command did you run?
`azcopy copy <file> <sas_url>`

### What problem was encountered?
It seems for some azure storage account `azcopy copy <file> <sas_url>` inside azure, acopy does the transfer on IPv6 with destination inside FC00::/7 (reserved for unique local unicast use [RFC4193]). It seems related to vnet usage.

Problem IPv6 is not supported for storage account networking rules (https://learn.microsoft.com/en-ca/azure/storage/common/storage-network-security?tabs=azure-portal#grant-access-from-an-internet-ip-range "Only IPV4 addresses are supported for configuration of storage firewall rules.") which means that it is forcing allow all networks. Reviewing vnet filtering option.

IPv4 and IPv6 flags are also standard options with network tools.

### How can we reproduce the problem in the simplest way?
Azure service tunneling file transfer with vnet for example.

### Have you found a mitigation/solution?
Vnet filtering likely.

**Comment by nakulkar-msft** [comment]
Hi @juju4, azcopy does not pick or choose any ip address to perform transfer. Please check your network configuration again.
