### ISSUE TITLE
azcopy list --properties "versionid" does not return versions and versionids

### ISSUE THREAD

**Issue by Peejay62** [Azure/azure-storage-azcopy#2007]
##### Note: The version is visible when running AzCopy without any argument
V10.16.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows server 2016
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy,exe list https://<stgaccount/container><sasconnect> --properties "LastModifiedTime;VersionID"

### What problem was encountered?
the above list does only list current versions and also doesn't return a versionid.  I would expect that when I had an object A and older versions of object A (A_v1, A_v2, A_v3 and so on)  azcopy list would return all versions in the listing. 
### How can we reproduce the problem in the simplest way?
Make an object with versioning on, write this object multiple times to create versions and the run azcopy list.
### Have you found a mitigation/solution?
no

**Comment by grillba** [comment]
Why is this labeled a feature request when the functionality is documented as above at https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-list? 

it doesnt return any version IDs at all - And the  LastModifiedTime is set to "0001-01-01 00:00:00 +0000 UTC"

**Comment by siminsavani-msft** [comment]
Hi @Peejay62 and @grillba ! Apologies for the confusion here. As an alternative, try using the --list-of-versions flag on azcopy copy command.

**Comment by Peejay62** [comment]
I do not want to copy (versions). I merely want to report on the content of the container (say dir of container). Only the active occurrences of blobs are listed, no "older" versions.  copy --list-of-versions is not suitable in this case

**Comment by siminsavani-msft** [comment]
Hi @Peejay62 and @grillba ! Apologies in taking so long to back to this issue! I am currently working on this issue as seen in the linked PR above and wanted to make sure that the expectations are met. 

With this PR, Blob VersionIds are printed out correctly:
`INFO: hello/stuff/foo.txt; VersionId: 2023-06-05T18:39:41.0295735Z;  Content Length: 3.00 B`

If the blob has more versions, then that will also be printed out:
`INFO: hello/stuff/foo.txt; VersionId: 2023-06-05T18:39:41.0295735Z;  Content Length: 3.00 B`
`INFO: hello/stuff/foo.txt; VersionId: 2023-06-06T10:50:20.0295735Z;  Content Length: 3.00 B`

Please let me know if there are any other questions or concerns!

**Comment by Peejay62** [comment]
Hi, this is what I expect to see with Azcopy list. So this will be available in the new release of Azcopy?

**Comment by siminsavani-msft** [comment]
Thanks for your reponse @Peejay62 ! We intend to make this available in 10.24. The upcoming release is 10.23 and will not contain the linked PR for this issue.

**Comment by gapra-msft** [comment]
This is released in AzCopy v10.24.0
