### ISSUE TITLE
azcopy sync not delete destination file if only include pattern specified

### ISSUE THREAD

**Issue by githubths** [Azure/azure-storage-azcopy#2011]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.16.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy sync S:\Folder %SASURI% --recursive --include-pattern "test-file1.txt;test-file2.txt;test-file3.txt" --delete-destination true

### What problem was encountered?
azcopy sync not delete destination file if only include pattern specified

### How can we reproduce the problem in the simplest way?
The goal is to sync only certain files of a file structure to Azure. All files are specified in the include pattern. When files are no longer in the include pattern, they should also be deleted from Azure. However, deleting files does not happen on Azure.

## Sync 1 (3 Files to sync)
azcopy sync S:\Folder %SASURI% --recursive --include-pattern "test-file1.txt;test-file2.txt;test-file3.txt" --delete-destination true
-> azcopy sync all 3 Files = ok

## Sync 2 (only 2 Files to sync and one to delete on azure)
azcopy sync S:\Folder %SASURI% --recursive --include-pattern "test-file1.txt;test-file2.txt" --delete-destination true
-> azcopy sync no files but also delete no files, why? 
For my understanding azcopy should delete test-file3.txt on azure because it is not in syncscope anymore, but exist on Azure.

### Have you found a mitigation/solution?
NO

**Comment by gapra-msft** [comment]
Closing as this was deemed to not be an issue.

**Comment by himanshukgit** [comment]
I have same issue and we are stuck, we sort data as per size in TBs successfully still the sync is not delete destination files....don't close the issue it's real time bug

**Comment by himanshukgit** [comment]
> Closing as this was deemed to not be an issue.

I have same issue and we are stuck, we sort data as per size in TBs successfully still the sync is not delete destination files....don't close the issue it's real time bug
