### ISSUE TITLE
azcopy 7.3.0-netcore on linux doesn't support table storage, any other version is available for table storage migration on Linux client?

### ISSUE THREAD

**Issue by chpagit** [Azure/azure-storage-azcopy#2021]
##### Note: The version is visible when running AzCopy without any argument
azcopy 7.3.0-netcore

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What problem was encountered?
According to the command usage, this version of azcopy only provides blob and file as source/destination type. Looks like the azcopy 7.3.0 doesn't support table storage copy, is there any way to copy tables on Linux client?
--source-type <blob | file>
                              Specifies that the source resource is a blob
                              or file available in the local development
                              environment or running in the storage emulator.

--dest-type <blob | file>
                              Specifies that the destination resource is a
                              blob or file available in the local
                              development environment or running in the
                              storage emulator.

### How can we reproduce the problem in the simplest way?
Always, and looks like by design.

### Have you found a mitigation/solution?
Nope

**Comment by adreed-msft** [comment]
AzCopy v7 is no longer supported.

[v7 with table support](https://learn.microsoft.com/en-us/previous-versions/azure/storage/storage-use-azcopy#azcopy-with-table-support-v73) appears to be Windows-only. I would advise you attempt to utilize the [WINE](https://www.winehq.org/) compatibility layer to run it, however, I will warn you that we will be unable to provide much support for such an old version of AzCopy. We do not currently have plans to support Tables or Queues in v10.

**Comment by stefandeml** [comment]
any reason table support has been dropped?

**Comment by adreed-msft** [comment]
Tables/Queues have largely been superseded by other Azure services (CosmosDB, Service Bus, etc.), which is not under Azure Storage. Also, tables/queues support in AzCopy adds a layer of complexity to the product we've deemed largely unnecessary.
