### ISSUE TITLE
Cannot clean jobs

### ISSUE THREAD

**Issue by sc211166** [Azure/azure-storage-azcopy#2024]
### Which version of the AzCopy was used? 
10.16.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 11

### What command did you run?
azcopy jobs clean

### What problem was encountered?
INFO: Removed 0 files.

Failed to remove log/plan files due to error: remove C:\scripts\LOGS\/429d85ba-b775-ca47-78a7-6be13c4aba07.log: The process cannot access the file becaus
e it is being used by another process..
 
### How can we reproduce the problem in the simplest way?
just run a previous azcopy command to generate logs and plan

### Have you found a mitigation/solution?
deleting the files manually

**Comment by adreed-msft** [comment]
Is another copy of AzCopy presently running? That could cause this.

**Comment by sc211166** [comment]
No, just one that ended.

**Comment by EurikasHP** [comment]
I can second this issue. Just moved from 10.14.1 to 10.17.0 
To reproduce: 
Run "azcopy sync [...] --from-to LocalBlob", than "azcopy jobs clean". 
With 10.14.1 you will get "jobs successfully removed" 
With 10.17.0, you will get the error "Failed to remove log/plan files due to error: [...]  The process cannot access the file because it is being used by another process..

**Comment by nakulkar-msft** [comment]
Hi, this would happen if one or more azcopy jobs were forcefully killed. Please allow azcopy to gracefully exit and try again

**Comment by EurikasHP** [comment]
It looks like in the new versions of azcopy the job cleanup is blocked by its own log file. So when you run "azcopy jobs clean" in 10.17 it will be blocked by the log file it creates. In 10.14 this does not happen.

**Comment by sc211166** [comment]
In our case the azcopy was never forcefully closed and it happens each and every time

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EurikasHP** [comment]
> Hi, this would happen if one or more azcopy jobs were forcefully killed. Please allow azcopy to gracefully exit and try again

Hi, can you reopen the issue based on the replies, which came after it was closed?
