### ISSUE TITLE
AzCopy Copy with versioning for "directory" at a specific datetime

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-storage-azcopy#2026]
I am using the versioning feature in Azure blob storage.  Is it possible to download an entire "directory", but at a specific date time.  

So it would need to download the correct version of each blob, ignore blobs that didn't exist and download deleted blobs that existed at the date time.

Is this something that people have previously solved?  It seems like it might be a popular request given the "sync" functionality of AzCopy.

Update - Just to add a little more context.  Each "directory" may contain 100,000 blobs, so doing this manually isn't really an option.  I'm really looking for an automated method.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
