### ISSUE TITLE
failed to refresh token The server terminated an operation because it encountered a client request loop

### ISSUE THREAD

**Issue by piercsi** [Azure/azure-storage-azcopy#2030]
?Related to #1984 #1957 supposed to be fixed in 10.17.0 (#1986)

### Which version of the AzCopy was used? 

```
PS C:\Windows\system32> azcopy --version
azcopy version 10.17.0
```

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows, but also the same on WSL.

### What command did you run?

`azcopy copy 'https://<storage account>.blob.core.windows.net' 'https://<backup storage account>.blob.core.windows.net' --recursive`

### What problem was encountered?

The commands seems to start ok but after a few seconds repeats the final error

INFO: Scanning...
INFO: Autologin not specified.
INFO: Authenticating to destination using Azure AD
INFO: Authenticating to source using Azure AD
INFO: failed to refresh token, please check error details and try to log in with azcopy login command again. (Error details: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_grant","error_description":"AADSTS50196: The server terminated an operation because it encountered a client request loop. Please contact your app vendor.\r\nTrace ID: aea08e96-bedc-45d6-9a2e-53979c883300\r\nCorrelation ID: 07f3efed-6c29-4eb0-b21c-d6a3ae3657b0\r\nTimestamp: 2023-01-24 10:22:31Z","error_codes":[50196],"timestamp":"2023-01-24 10:22:31Z","trace_id":"aea08e96-bedc-45d6-9a2e-53979c883300","correlation_id":"07f3efed-6c29-4eb0-b21c-d6a3ae3657b0","error_uri":"https://login.microsoftonline.com/error?code=50196"} Endpoint https://login.microsoftonline.com/common/oauth2/token?api-version=1.0)

### How can we reproduce the problem in the simplest way?

Attempt to copy a large storage account to another account.

### Have you found a mitigation/solution?

It works for smaller copies

**Comment by tasherif-msft** [comment]
Can you please share your job log file @piercsi on debug?
Also, out of curiosity how large approx. is this transfer?

**Comment by piercsi** [comment]
So I was a bit impatient. I left the process to continue through the error messages and in the end it completes claiming there are no failures:

Job b53f5024-1b83-0c4a-4b5c-42a9a0f4f6b2 summary
Elapsed Time (Minutes): 1.9023
Number of File Transfers: 90317
Number of Folder Property Transfers: 0
Total Number of Transfers: 90317
Number of File Transfers Completed: 90317
Number of Folder Transfers Completed: 0
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
TotalBytesTransferred: 57887654289
Final Job Status: Completed

However there were some errors in the log:

2023/01/25 14:06:51 ==> REQUEST/RESPONSE (Try=1/17.7035ms, OpTime=197.7513ms) -- RESPONSE STATUS CODE ERROR
   GET https://<REDACTED>.blob.core.windows.net/bootdiagnostics-aksnodepo-0143045d-e626-489d-8880-0d22961d6566/aks-nodepool1-34440816-0.0143045d-e626-489d-8880-0d22961d6566.screenshot.bmp?comp=pagelist&timeout=901
   User-Agent: [AzCopy/10.17.0 Azure-Storage/0.15 (go1.19.2; Windows_NT)]
   X-Ms-Client-Request-Id: [fdc98343-5177-453d-7d6c-4d08c614cf4c]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
   Content-Length: [303]
   Content-Type: [application/xml]
   Date: [Wed, 25 Jan 2023 14:06:51 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   Www-Authenticate: [Bearer authorization_uri=https://login.microsoftonline.com/75bca4c0-0262-480f-9a32-c1223ca2e6ea/oauth2/authorize resource_id=https://storage.azure.com]
   X-Ms-Client-Request-Id: [fdc98343-5177-453d-7d6c-4d08c614cf4c]
   X-Ms-Error-Code: [NoAuthenticationInformation]
   X-Ms-Request-Id: [e5cbc757-a01e-0015-41c6-300773000000]
   X-Ms-Version: [2020-10-02]
Response Details: ﻿<?xml version="1.0" encoding="utf-8"?> <Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header. </Message>

**Comment by tasherif-msft** [comment]
Hi @piercsi if it reports that the job succeeded then it did, were you able to confirm the files were transferred?
How did you provide your oauth credentials?
I have attempted to repro with 1.5+ mil files as a long running job with no issues. Also, I noticed your job is only 1.9 minutes long - this actually doesn't have to do with the issue you're referencing. The issue you're referencing that we resolved in 10.17 is related to oauth tokens refreshing 10's of times too quickly, which doesn't seem to be the case for you.

**Comment by piercsi** [comment]
I remove the weird bootdiagnostics folder and the log errors go away. The files seem to transfer successfully.

I don't know why it is reporting the client request loop message but it is just an INFO message.

I am logging in using azcopy login and using the code in my desktop browser to authenticate.

**Comment by tasherif-msft** [comment]
We have retry policies in place, so as long as the authentication and the transfer worked you should be good to go. I will close this issue in the meantime.
