### ISSUE TITLE
unknown flag: --missing-hash-policy

### ISSUE THREAD

**Issue by krapgras** [Azure/azure-storage-azcopy#2031]
### Which version of the AzCopy was used?  
10.17.0
### Which platform are you using? (ex: Windows, Mac, Linux)- 
Windows

### What command did you run? 
azcopy sync

### What problem was encountered? 

unknown flag: --missing-hash-policy

### How can we reproduce the problem in the simplest way? 

Add the flag: --missing-hash-policy

### Have you found a mitigation/solution? 

It seems this is not working but it is mentioned in the changelogs of version 10.17.0
Is something missing?

**Comment by adreed-msft** [comment]
Oh, sorry, this accidentally made it into the change log. Missing hash policy was removed shortly before the work was merged in, as it didn't feel especially intuitive to have to opt-in to hashing for local files when working with the hash based sync feature.

**Comment by krapgras** [comment]
Ok that makes sense but then i have a follow-up question.
Knowing most files are not hashed if they are bigger the 250MB then what will azcopy do?

One of the most usefull cases i found personally is that you can copy two remote blob storages as you don't need to duplicate the data locally. But i have been struggling to make sure all files are hashed and verified.

The hash generate part seemed promising as it would create a way to always have the files MD5 hashed no? 

If you have any other advice to make sure I can verify all files i'm happy to have advice there as well :)
