### ISSUE TITLE
AzCopy Node failing in Azure Function with Unexpected token '.'

### ISSUE THREAD

**Issue by jansha** [Azure/azure-storage-azcopy#2034]
### Which version of the AzCopy was used? 
"@azure-tools/azcopy-node": "^2.9.0",

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows => does not work
Mac => works

### What command did you run?
const { AzCopyClient } = require("@azure-tools/azcopy-node");

### What problem was encountered?
C:\WorkArea\OSA-WEB\node_modules\@azure-tools\azcopy-node\dist\src\AzCopyClient.js:38
        this._envVars = options?.envVars || {};
                                ^
SyntaxError: Unexpected token '.'

### How can we reproduce the problem in the simplest way?

If if adding this line (const { AzCopyClient } = require("@azure-tools/azcopy-node");) it starts throwing the error.
Is there any way to add the options and envVars

### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
Hi,
@azure-tools/azcopy-node is not owned or developed by AzCopy. Please reach out to the appropriate person.
