### ISSUE TITLE
random errors

### ISSUE THREAD

**Issue by ctaynet1** [Azure/azure-storage-azcopy#2037]
### Which version of the AzCopy was used? 
10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
copy
### What problem was encountered?
see attached log

### How can we reproduce the problem in the simplest way?
IDK

### Have you found a mitigation/solution?
No
[7107b787-a9f5-ef4c-507e-1d3269d9e26f.log](https://github.com/Azure/azure-storage-azcopy/files/10521046/7107b787-a9f5-ef4c-507e-1d3269d9e26f.log)

**Comment by nakulkar-msft** [comment]
Hi, these messages are because of flaky n/w. Please switch to a more stable n/w.
