### ISSUE TITLE
Security linux export client secret

### ISSUE THREAD

**Issue by elcaminator** [Azure/azure-storage-azcopy#2042]
##### Note: The version is visible when running AzCopy without any argument
V10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy login

### What problem was encountered?
I have to export client secret in environment variable

### How can we reproduce the problem in the simplest way?
Follow instruction on microsoft tutorial to connect with service principal
https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory

Tutorial export environment variable. Secret can be then seen by other.

### Have you found a mitigation/solution?
No

How to use azcopy in linux without environment variable ? Can it read through a config file stored in home of a linux service account which is used to launch azcopy ?
Is azcopy suitable for that kind of scenario (giving access to other clients with specific rights tied to service principal) ?

Thank you.

**Comment by tasherif-msft** [comment]
Hi @elcaminator there is no config file options the page you referenced contains all OAuth methods to authenticate. Alternatively, you can use SAS tokens as well. https://github.com/Azure/azure-storage-azcopy/blob/main/README.md describes which operations support OAuth and/or SAS auth. Will proceed to close this issue.

**Comment by elcaminator** [comment]
Hi @tasherif-msft, so we can say than azcopy is not suitable for automation on a server where a service account is mandatory (no user profil in windows / no login in linux) ?
Exporting client secret leads other programs / services on the server to be able to read it.
SAS token is logged in the server log (that's why the best practice for it is to issue it with a short time window which is not possible for us because we give access to people external to our organizations to specific folder).

So azcopy is not for a server like use case : can we say that due to security readon ?

**Comment by nakulkar-msft** [comment]
Hi @elcaminator, Would Service Principal login with Certificate work for you?
https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-a-service-principal-by-using-a-certificate-1
https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

**Comment by elcaminator** [comment]
@nakulkar-msft it won't work because what i read is that instead of the client secret, now we'll have to export the certifcate passphrase in order to make azcopy work.

The problem is the need to export secrets as environment variable.

If azcopy could read a conf file, it could be possible to restrict access to the specific folder to the owner.

**Comment by elcaminator** [comment]
@nakulkar-msft @tasherif-msft can you point to me another direction based on what we discussed ?
