### ISSUE TITLE
Using azcopy to move files to subdirectory in container

### ISSUE THREAD

**Issue by rigdent** [Azure/azure-storage-azcopy#205]
Hello,
I'm trying to move a bunch of files in a blob container to a subdirectory in the same container.
I'm able to grab the files using the `--include` command if I use the `--recursive` flag with it, but since I'm trying to move the files to the same container, I can't use the `--recursive` flag.

``` 
azcopy --version
azcopy 7.3.0-netcore
```

```
azcopy --dry-run  --source <container> --destination ./ --include "stdout.txt" --source-key=<key>
Listed: 1 file(s)                                                                                                                                                                                            
[2019/02/08 22:36:56] Transfer summary:                                                                                                                                                                      
-----------------
Total files listed: 1
Elapsed time:       00.00:00:01

azcopy --dry-run  --source <container> --destination ./ --include "stdout" --source-key=<key>
Listed: 0 file(s)                                                                                                                                                                                            
[2019/02/08 22:37:13] Transfer summary: 
-----------------
Total files listed: 0
Elapsed time:       00.00:00:00

azcopy --dry-run  --source <container> --recursive  --destination ./ --include "stdout" --source-key=<key>
Listed: 1 file(s)                                                                                                                                                                                            
[2019/02/08 22:37:21] Transfer summary:                                                                                                                                                                      
-----------------
Total files listed: 1
Elapsed time:       00.00:00:00
```

And I essentially want to be able to run it like 

```
azcopy --dry-run  --source <container>  --destination <container>/subdir/ --include "stdout" --source-key=<key> --dest-key
```

Underlying issue is that it seems the `--include` flag only works as a file prefix for a blob source when used with the `--recursive` flag. Which seems like what the `azcopy --help` says as well. Just wanted to confirm and see if there is a way to run it to do what I need it to do. 

Or is Azcopy not the right tool for this? 
Thanks!

**Comment by EmmaZhu** [comment]
@rigdent 
AzCopy lists blobs in segments, and starts each blob copying while listing is still on going, to support to copy large number of blob. To copy a directory to its subdirectory may cause unfinished loop. 
For example, to copy a folder "A" with blob named "a0", "a1", "a2" to its subfolder "A/B". While lists to blob "A/a1", blob "A/a0" may have already been copied to "A/B/a0". After copying "A/a0", "A/a1", "A/a2" to "A/B/a0", "A/B/a1", "A/B/a2", AzCopy will list to "A/B/a0", and start to copying "A/B/a0" to "A/B/B/a0", etc... 

To avoid this kind of endless loop, AzCopy explicitly disabled copying to source's subdirectory. 

Thanks
Emma
