### ISSUE TITLE
cannot specify a simple date range pattern for file.core.windows.net?

### ISSUE THREAD

**Issue by coffeebeantraining** [Azure/azure-storage-azcopy#2053]
### Which platform are you using? (ex: Windows, Mac, Linux)
Both
### What command did you run? azcopy copy with a SAS key
azcopy copy 'https://mystorageaccount.file.core.windows.net/myfileshare/myDirectory?sv=3D' 'D:\workspace\2023-reports'  --include-pattern 'DATE RANGE from 2023-01-01 to 2023-01-14 of all *.log files' --recursive --overwrite=true --dry-run --list-of-files "C:\backend\stg-exp-azcopy.txt"
### What problem was encountered?
I don't see an option to download files for a date range and include a file filter?  WHY?  that to me is an expected basic feature.
### How can we reproduce the problem in the simplest way?
not reproducable because it's the date range is not supported yet.
### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
Hi, use "include-after" and "include-before" flags in conjunction.
