### ISSUE TITLE
AzCopy Cp --exclude-path not working

### ISSUE THREAD

**Issue by paulh-utilita** [Azure/azure-storage-azcopy#2054]
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux in a container built for Azure DevOps Hosted Agent

### What command did you run?
azcopy cp "/azp/_work/1/s/*" "https://sanamehere.blob.core.windows.net/\$web/foldercontent" --recursive --overwrite ifSourceNewer --cache-control no-cache --exclude-path "/builds";"/.git" --put-md5

### What problem was encountered?
In essence, whatever was put in the exclude-path section, it was basically ignored and therefore still copied the content out to the storage account regardless. The idea was to use AzCopy as a pipeline step in Azure DevOps to copy static website content over to the $web container.

### How can we reproduce the problem in the simplest way?
in essence try to copy using AzCopy from a Ubuntu 20.04 container excluding the .git folder and a builds folder that contains content and see if they still show up on the Azure Storage Container

### Have you found a mitigation/solution?
Added steps to remove those folders ahead of the AzCopy command executing which means the unrequired content can never copied over by AzCopy. This does throw a warning up in the pipeline when cleaning up .git but the job still succeeds.

**Comment by nakulkar-msft** [comment]
Hi @paulh-utilita, please change your command to
azcopy cp "/azp/_work/1/s/*" "[https://sanamehere.blob.core.windows.net/\$web/foldercontent](https://sanamehere.blob.core.windows.net/%5C$web/foldercontent)" --recursive --overwrite ifSourceNewer --cache-control no-cache --exclude-path "builds;.git" --put-md5

**Comment by robsmi-msfte** [comment]
Could we update the Learn documents for the exact syntax of '--exclude-path'?  I wasted a lot of time until I found this (multiple items need to be surrounded by double-quotes and separated by semi-colon).
