### ISSUE TITLE
AzCopy not working while copying from one container to another using Azure storage emulator on local machine

### ISSUE THREAD

**Issue by GoradeAarti** [Azure/azure-storage-azcopy#2056]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.16.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

.\azcopy.exe cp http://127.0.0.1:10000/devstoreaccount1/default-leases?SAS http://127.0.0.1:10000/devstoreaccount1/default-leases-copy?SAS --recursive --from-to BlobBlob

### What problem was encountered?
operation failed with below error in log file

023/01/31 18:00:28 ERR: [P#0-T#6] COPYFAILED: http://127.0.0.1:10000/devstoreaccount1/default-leases/taskhub.json?se=2023-02-01T17%3A38%3A44Z&sig=-REDACTED-&sp=rl&sr=c&st=2023-01-31T17%3A38%3A44Z&sv=2018-03-28 : 000 : **destination length does not match source length. When S2S Length check.** X-Ms-Request-Id:

### How can we reproduce the problem in the simplest way?
1. Start Azure Storage Emulator on local machine
2. Generate SAS token from Storage explorer running on the local machine 
3. Create test source and destination containers. Add some blobs in the source container
4. Run the above 'AzCopy cp' command and should be able to see the failure

### Have you found a mitigation/solution?
No

Please find attached AzCopy log files generated on my machine
[c9c03ea1-8034-7d48-73c2-8ae53b03f685.log](https://github.com/Azure/azure-storage-azcopy/files/10670279/c9c03ea1-8034-7d48-73c2-8ae53b03f685.log)
[c9c03ea1-8034-7d48-73c2-8ae53b03f685-scanning.log](https://github.com/Azure/azure-storage-azcopy/files/10670281/c9c03ea1-8034-7d48-73c2-8ae53b03f685-scanning.log)

**Comment by nakulkar-msft** [comment]
Hi @GoradeAarti, thanks for reaching us. This is unfortunately a bug with the emulator and you would need to reach the appropriate owners. This is not a bug with AzCopy.
