### ISSUE TITLE
Node AzCopy: Parallelisation of the copy command – Missing `--list-of-files`-support

### ISSUE THREAD

**Issue by rene-leanix** [Azure/azure-storage-azcopy#2057]
##### Note: The version is visible when running AzCopy without any argument

@azure-tools/azcopy-node@2.9.0, which uses azcopy version 10.16.2 under the hood.

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

### What command did you run? & What problem was encountered?

I was trying to parallelise the copying of a few hundred to a few thousand blobs between two storage containers by running several `azCopyClient.copy()` commands in parallel. (The fact that this call returns a job ID rather than a promise resolving to the result seems to suggest that parallelisation is supported and expected.) Unfortunately, even with a concurrency rate as low as 10 I was hitting resource limits in our Kubernetes container, which resulted in out-of-memory errors and very surprising "too many open file" errors.

### How can we reproduce the problem in the simplest way?

I haven't double-checked the memory consumption of a single copy command call, but in our case the Kubernetes container had about 1 GB of free memory and 10 concurrent copy commands for single blobs lead to out-of-memory errors.

### Have you found a mitigation/solution?

I ended up calling the azcopy-binary directly providing the list of files to be copied via the (somewhat hidden) [`--list-of-files` argument](https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer). I am aware that this has performance issues for large number of files, but I consider those negligible compared to the poor performance of having to copy all files sequentially! 

It would be great to extend the support of `--list-of-files` in @azure-tools/azcopy-node from the delete to the copy operation.

**Comment by adreed-msft** [comment]
Re: parallelization: AzCopy itself is not really intended to be parallelized. It _can_ be, but it is not designed to be.

Re: listoffiles: @JasonYeMSFT @MRayermannMSFT

**Comment by MRayermannMSFT** [comment]
@rene-leanix 

> The fact that this call returns a job ID rather than a promise resolving to the result seems to suggest that parallelisation is supported and expected.

More like since operations can take a really long time, azcopy-node does not want you to have to wait around for the results. If you want to the library page on npmjs.com gives on example of how to do that: https://www.npmjs.com/package/@azure-tools/azcopy-node

> It would be great to extend the support of --list-of-files in @azure-tools/azcopy-node from the delete to the copy operation.

It is supported. 🙂 The `copy` method on `AzCopyClient` has an `options` parameter of type `ICopyOptions`. That type inherits from `ICommonOptions`, which contains `listOfFiles`.

![image](https://user-images.githubusercontent.com/21112697/217655261-b5d7268e-3e0c-4400-995c-7609861863f6.png)

Let me know if you aren't seeing that, and if so, version of azcopy-node you are using.

**Comment by MRayermannMSFT** [comment]
> Oops, sorry, I missed that when I was browsing your source code! I think what convinced me that this option is only available for deletions was its JSDoc:

Oh. Ya we should fix that. 😁 And ok, we'll think about how we can update the README to expose some of the more useful things.
