### ISSUE TITLE
Disk may be limiting speed - --check-md5 removed

### ISSUE THREAD

**Issue by dcCMPY** [Azure/azure-storage-azcopy#2059]
**Which version of the AzCopy was used?**
10.17.0

**Which platform are you using?**
Windows

**What command did you run?**
azcopy copy "https://sa.blob.core.windows.net/container/Data/*?si=xxxxx" "H:\Drive1\" --overwrite=prompt --check-md5 NoCheck --from-to=BlobLocal --list-of-files "C:\Users\a\Documents\azcopycmd\files2.txt" --recursive --log-level=INFO

**_and_**

azcopy copy "https://sa.blob.core.windows.net/container/Data/*?si=xxxxx" "H:\Drive1" --overwrite=prompt --check-md5 FailIfDifferet --from-to=BlobLocal --list-of-files "C:\Users\a\Documents\azcopycmd\files2.txt" --recursive --log-level=INFO

**What problem was encountered?**
Hi

We have a VM in Azure that is spec'd as Standard E20ds v5 with the disk my azcopy is downloading to set as Standard SSD LRS

For the life of me I cannot figure out why or how to remove the message _(Disk may be limiting speed)_

As an example I'm trying to download 10x 15 GB files in one go

I also see the below message appear:

_2-sec Throughput (MB/s):_ 

The number that follows the (MB/s): fluctuates, from 250, 430, 950 etc. 

As per the above I have ran both commands with and without the md5 chec

I just would like to know if the speeds I'm getting is expected and if the (Disk may be limiting speed) is anything to be concerned about ?

**How can we reproduce the problem in the simplest way?**
This essentially happens every time I attempt to copy the files 
**Have you found a mitigation/solution?**
No

**Comment by adreed-msft** [comment]
This indicates that AzCopy has detected that your disk speed is a bottleneck. You cannot disable this message. It is intended to let you know why you are receiving poor throughput.

**Comment by dcCMPY** [comment]
Sorry I don’t know why this was closed 

I have close to 12Gbps throughput with this machine it should take 5 minutes to download. 

Is there any way to identify if it’s the disk on the VM ?

**Comment by adreed-msft** [comment]
> Sorry I don’t know why this was closed
I closed this as it's not really an issue with AzCopy per se.

> I have close to 12Gbps throughput with this machine it should take 5 minutes to download.
> Is there any way to identify if it’s the disk on the VM ?
The `azcopy benchmark` command can assist with identifying bottlenecks as well.

**Comment by dcCMPY** [comment]
Sorry I'm running a AZCopy command and its returning this error, it would be good to have this reopened, or should I just raise a Microsoft support ticket ?

**Comment by adreed-msft** [comment]
> Sorry I'm running a AZCopy command and its returning this error

This is not actually an error-- it is a warning, indicating that AzCopy is finding that the disk you're copying from may be bottlenecking the throughput. It will not prevent your transfer from running. This is intended functionality.

**Comment by MonkeyNinja** [comment]
azcopy has scanned at source and dest, it just not start the copy, then it tell use that something is limiting speed...it will suddenly start and transfer the files.....

14 files in 10 minutes cannot be right -- and is it really the disk speed? system seems fine, is usable etc....


1373 Files Scanned at Source, 100 Files Scanned at Destination
INFO: Deleting extra object: bmds-data/2023-02-01/NMC6224413.jpg
1373 Files Scanned at Source, 100 Files Scanned at Destination
INFO: Deleting extra object: bmds-data/2023-02-01/NMC6224443.jpg
1373 Files Scanned at Source, 100 Files Scanned at Destination
1373 Files Scanned at Source, 523 Files Scanned at Destination
1373 Files Scanned at Source, 1047 Files Scanned at Destination
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0 (Disk may be limiting speed)
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0 (Disk may be limiting speed)
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0 (Disk may be limiting speed)
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0 (Disk may be limiting speed)..

... many more rows....

0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0 (Disk may be limiting speed)
0.0 %, 0 Done, 0 Failed, 14 Pending, 14 Total, 2-sec Throughput (Mb/s): 0 (Disk may be limiting speed)
15.0 %, 3 Done, 0 Failed, 11 Pending, 14 Total, 2-sec Throughput (Mb/s): 0.581 (Disk may be limiting speed)
54.4 %, 5 Done, 0 Failed, 9 Pending, 14 Total, 2-sec Throughput (Mb/s): 1.5229 (Disk may be limiting speed)
79.3 %, 8 Done, 0 Failed, 6 Pending, 14 Total, 2-sec Throughput (Mb/s): 0.9629 (Disk may be limiting speed)
79.3 %, 8 Done, 0 Failed, 6 Pending, 14 Total, 2-sec Throughput (Mb/s): 0 (Disk may be limiting speed)
94.6 %, 11 Done, 0 Failed, 3 Pending, 14 Total, 2-sec Throughput (Mb/s): 0.5934 (Disk may be limiting speed)
96.6 %, 13 Done, 0 Failed, 1 Pending, 14 Total, 2-sec Throughput (Mb/s): 0.0766 (Disk may be limiting speed)
96.6 %, 13 Done, 0 Failed, 1 Pending, 14 Total, 2-sec Throughput (Mb/s): 0 (Disk may be limiting speed)
100.0 %, 14 Done, 0 Failed, 0 Pending, 14 Total, 2-sec Throughput (Mb/s): 0.132


Job f19e901e-382c-2442-7fde-3937742cd754 Summary
Files Scanned at Source: 1373
Files Scanned at Destination: 1377
Elapsed Time (Minutes): 9.7702
Number of Copy Transfers for Files: 12
Number of Copy Transfers for Folder Properties: 2
Total Number Of Copy Transfers: 14
Number of Copy Transfers Completed: 14
Number of Copy Transfers Failed: 0
Number of Deletions at Destination: 116
Total Number of Bytes Transferred: 967484
Total Number of Bytes Enumerated: 967484
Final Job Status: Completed
