### ISSUE TITLE
AzCopy writes files to container, but if I drop and recreate the container it fails (using devops)

### ISSUE THREAD

**Issue by clintgrove** [Azure/azure-storage-azcopy#2060]
I am using AzureFileCopy@5 in a yaml file in devops to copy files from a repo folder to a storage account .
I am running the agent on windows-latest

The devops agent has run this 
"AzCopy\AzCopy.exe" copy "D:\a\1\sourcejson" "[https://bhft111xxxmy.blob.core.windows.net/schemajson"](https://bhft111stdgrsuksdummy.blob.core.windows.net/schemajson%22)  --log-level=INFO --recursive

The error comes up as
##[error]Upload to container: 'schemajson' in storage account: 'bhft111stdgrsuksdummy' with blob prefix: '' failed with error: 'AzCopy.exe exited with non-zero exit code while uploading files to blob storage.'
INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission ->
" Code: AuthorizationPermissionMismatch"

The service connection in DevOps has ACL permissions on the container. Its an Owner of the subscription. 

When I first ran this, it worked. Then when the container got deleted and I recreated it, and gave the relevant permissions again, it fails.

**Comment by adreed-msft** [comment]
Permissions can take a bit to propagate and actually apply in Azure. Unfortunately, this is not something we have control over. It would be recommended in this case to not delete the container if there is no need to.
