### ISSUE TITLE
panic: mkdir C:\Users\Default\.azcopy: Access is denied.

### ISSUE THREAD

**Issue by aistvan** [Azure/azure-storage-azcopy#2061]
##### Note: The version is visible when running AzCopy without any argument
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "file.ext" "https://corpstorage.blob.core.windows.net/corpcontainer/file.ext?sastoken"
Running from SQL Server job under a dedicated user name let's call it "domain\jobrunner"

### What problem was encountered?
Got an interesting error. The app tried to create a folder at wrong place. (in this case under the "Default" user home folder instead of the "jobrunner":

`panic: mkdir C:\Users\**Default**\.azcopy: Access is denied.
`
### How can we reproduce the problem in the simplest way?

1. Create a CMD file which contains the command.
2. Create a user in Sql Server act as a domain user.
3. Create an Sql Agent job, which will run this command under the user, created in the previous step.
4. Create the right permission in the file system for the user to access this cmd.
5. Start the job

### Have you found a mitigation/solution?
Currently no. I created a .net app to achive the copy task.

**Comment by adreed-msft** [comment]
Specifying the environment variable(s) `AZCOPY_LOG_LOCATION` and `AZCOPY_JOB_PLAN_LOCATION` will allow you to specify this manually. This occurs when AzCopy fails to pick up a user directory (for instance, in the case the user directory does not exist.)
