### ISSUE TITLE
10.17.0 AzCopy intermittently fails with "Could not check destination file existence"

### ISSUE THREAD

**Issue by trampanzee** [Azure/azure-storage-azcopy#2068]
### Which version of the AzCopy was used? 
10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy copy "\\SourceUNCPath\directory\*" "https://storagetpud.blob.core.windows.net/shared?SASTOKEN" --recursive=true --overwrite=ifSourceNewer

### What problem was encountered?
Trying to run as scheduled task.  Successful run is intermittent.  Sometimes it is successful, other times not. Log file includes error: "UPLOADFAILED: \\?\UNC\sourcedirectory\file.txt : 000 : Could not check destination file existence. -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
HTTP request failed"

### How can we reproduce the problem in the simplest way?
Run it

### Have you found a mitigation/solution?
No.

**Comment by nakulkar-msft** [comment]
Hi @trampanzee, the log file would contain why the request failed. Can you post the log file or the http request which failed. You'll find the log file in $HOME/.azcopy/<jobID>.log

**Comment by trampanzee** [comment]
Is this enough information?

  ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError,
/home/vsts/go/pkg/mod/
***@***.***/pipeline/error.go:157
HTTP request failed

Head "https://REMOVED&timeout=901": Bad Request

goroutine 116 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.stack()
/home/vsts/work/1/s/ste/xferLogPolicy.go:237 +0x65
github.com/Azure/azure-storage-azcopy/v10/ste.NewRequestLogPolicyFactory.func1.1({0x1c99e60,
0xc000547a40}, {0xc0003691e0?})
/home/vsts/work/1/s/ste/xferLogPolicy.go:151 +0xa1c
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x1a1e8c0?,
{0x1c99e60?, 0xc000547a40?}, {0xc?})
/home/vsts/go/pkg/mod/
***@***.***/pipeline/core.go:43
+0x2f
github.com/Azure/azure-storage-azcopy/v10/ste.NewVersionPolicyFactory.func1.1({0x1c99e60,
0xc000547a40}, {0xc000080400?})
/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:88 +0x157
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00046ac90?,
{0x1c99e60?, 0xc000547a40?}, {0xc00046ac90?})
/home/vsts/go/pkg/mod/
***@***.***/pipeline/core.go:43
+0x2f
github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do({{0x1c949a0?,
0xc000009b78?}, 0xc000328a50?}, {0x1c99e60?, 0xc000547a40?},
{0xc001272900?})
/home/vsts/go/pkg/mod/
***@***.***/azblob/zz_generated_responder_policy.go:33
+0x44
github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(..
.)
/home/vsts/go/pkg/mod/
***@***.***/azblob/zc_credential_anonymous.go:54
github.com/Azure/azure-storage-azcopy/v10/ste.(*retryNotificationPolicy).Do(0xc00046ad20?,
{0x1c99e60, 0xc000547a40}, {0x1c99df0?})
/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x2f
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x1c99df0?,
{0x1c99e60?, 0xc000547a40?}, {0x7?})
/home/vsts/go/pkg/mod/
***@***.***/pipeline/core.go:43
+0x2f
github.com/Azure/azure-storage-azcopy/v10/ste.NewBlobXferRetryPolicyFactory.func1.1({0x1c99df0,
0xc00043c180}, {0xc000368580?})
/home/vsts/work/1/s/ste/xferRetrypolicy.go:384 +0xa95
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x1a1e8c0?,
{0x1c99df0?, 0xc00043c180?}, {0x16?})
/home/vsts/go/pkg/mod/
***@***.***/pipeline/core.go:43
+0x2f
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1({0x1c99df0,
0xc00043c180}, {0xc000368580?})
/home/vsts/go/pkg/mod/
***@***.***/azblob/zc_policy_unique_request_id.go:22
+0x191
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0x1a1e8c0?,
{0x1c99df0?, 0xc00043c180?}, {0xa?})
/home/vsts/go/pkg/mod/
***@***.***/pipeline/core.go:43
+0x2f
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1({0x1c99df0,
0xc00043c180}, {0xc0004164d0?})
/home/vsts/go/pkg/mod/
***@***.***/azblob/zc_policy_telemetry.go:34
+0x11c
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00043c140?,
{0x1c99df0?, 0xc00043c180?}, {0x4?})
/home/vsts/go/pkg/mod/
***@***.***/pipeline/core.go:43
+0x2f
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc000194000?,
{0x1c99df0, 0xc00043c180}, {0x1c94b00?, 0xc000328a50?}, {0xc000194008?})
/home/vsts/go/pkg/mod/
***@***.***/pipeline/core.go:129
+0x54
github.com/Azure/azure-storage-blob-go/azblob.blobClient.GetProperties({{{{0xc000194000,
0x5}, {0x0, 0x0}, 0x0, {0xc000194008, 0x21}, {0xc000194029, 0x1e}, {0x0,
...}, ...}, ...}}, ...)
/home/vsts/go/pkg/mod/
***@***.***/azblob/zz_generated_blob.go:933
+0x378
github.com/Azure/azure-storage-blob-go/azblob.BlobURL.GetProperties({{{{{...},
{...}, 0x0, {...}, {...}, {...}, 0x0, 0x0, {...}, {...}, ...}, ...}}}, ...)
/home/vsts/go/pkg/mod/
***@***.***/azblob/url_blob.go:200
+0x14a
github.com/Azure/azure-storage-azcopy/v10/ste.(*blockBlobSenderBase).RemoteFileExists(0xc000005680)
/home/vsts/work/1/s/ste/sender-blockBlob.go:170 +0x10a
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote_file({_, _},
{{0xd6811311, 0xd8c3, 0xca49, {0x73, 0x1d, 0xe3, 0x80, 0x5e, ...}}, ...},
...)
/home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:242 +0x642
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote({0x1ca5860,
0xc00016e070}, {0x1c90800, 0xc00043c140}, {0x1bf68da0a40, 0xc00039cd40},
0xc0000340c0?, 0x2c?)
/home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:187 +0x41d
github.com/Azure/azure-storage-azcopy/v10/ste.parameterizeSend.func1({0x1ca5860?,
0xc00016e070?}, {0x1c90800?, 0xc00043c140?}, {0x1bf68da0a40?,
0xc00039cd40?})
/home/vsts/work/1/s/ste/xfer.go:77 +0x44
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartMgr).StartJobXfer(0x22baae0?,
{0x1ca5860?, 0xc00016e070?})
/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:720 +0x50
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).StartJobXfer(0xc00016e070
?)
/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:237 +0x32
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor.func1({0x1ca5860,
0xc00016e070})
/home/vsts/work/1/s/ste/mgr-JobMgr.go:1020 +0x1b9
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor(0xc00041a400,
0x12d3851?)
/home/vsts/work/1/s/ste/mgr-JobMgr.go:1032 +0xbd
created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr
/home/vsts/work/1/s/ste/mgr-JobMgr.go:202 +0xc37

2023/02/13 21:51:04 ==> REQUEST/RESPONSE (Try=2/0s, OpTime=1.1920856s) --
REQUEST ERROR
   HEAD https://REMOVED&timeout=901
   User-Agent: [AzCopy/10.17.0 Azure-Storage/0.15 (go1.19.2; Windows_NT)]
   X-Ms-Client-Request-Id: [42565acf-97aa-49f6-681e-3c4a13c6fb18]
   X-Ms-Version: [2020-10-02]

**Comment by nakulkar-msft** [comment]
hi @trampanzee, sorry I missed your response. Can you please post the log file? We would need request  ids to be helpful.

**Comment by vibhansa-msft** [comment]
Feel free to reopen once you have the requested information.
