### ISSUE TITLE
AzCopy occasionally hangs after canceling a non-HNS blob delete job

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#2074]
### Which version of the AzCopy was used? 
10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac

### What command did you run?
delete non-HNS blobs

### What problem was encountered?
In rare cases, after canceling the job, AzCopy get stuck in a state where it keeps tuning the concurrency values without making any progress.

### How can we reproduce the problem in the simplest way?
I cannot consistently reproduce the problem. It is more likely to occur when using list-of-files to delete a large number of blobs.

### Have you found a mitigation/solution?
Kill AzCopy job.

**Comment by nakulkar-msft** [comment]
Same as #2073

**Comment by siminsavani-msft** [comment]
Fixed in 10.19.0!
