### ISSUE TITLE
Azure is creating log in /root/.azcopy, even environment path is mentioned in /etc/bashrc 

### ISSUE THREAD

**Issue by sourav2cool86** [Azure/azure-storage-azcopy#2075]
##### Note: The version is visible when running AzCopy without any argument
10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What problem was encountered?

A cronjob has been scheduled for an azcopy script, Also, environment path has been set in /ets/bashrc for azcopylogs. But it is still generating logs under /root/.azcopy 

### How can we reproduce the problem in the simplest way?
to trigger script under root.

### Have you found a mitigation/solution?
not yet

**Comment by nakulkar-msft** [comment]
Hi @sourav2cool86, it appears environment variable is not appropriately set. Verify that azcopy has correctly picked up the environment with 'azcopy env' command.
