### ISSUE TITLE
azcopy has to login every time with OTP (one time passcode)

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-storage-azcopy#2076]
##### Note: The version is visible when running AzCopy without any argument
10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 11

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy

### What problem was encountered?
The problem is that when we use an account to OTP login with azcopy using “azcopy login” and then execute an “azcopy copy” task, it works for the first time but later on when we try to execute another “azcopy copy” task, it failed with error and we need to re-login using “azcopy login” again. The same won’t happen when using “azcopy login” with Azure B2B Guest or any other Azure AD account.

Both OTP and B2B supports refresh token, it seems that azcopy does not handle OTP refresh token properly.

https://learn.microsoft.com/en-us/azure/active-directory/external-identities/one-time-passcode

Error messge:
failed to perform copy command due to error: get cached token failed to ensure token fresh, please log in with azcopy’s login command again, Manually created ServicePrincipalToken does not contain secret material to retrieve a new access token.

### Have you found a mitigation/solution?
No

**Comment by yangchengs** [comment]
cx issue

**Comment by nakulkar-msft** [comment]
Hi @yangchengs, you can use a service-principal / MSI with [auto-login](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)) 

We do refresh token, however if you copy after the token has expired, you will need to login again.
Use [azcopy login status](https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-login-status) to verify and refresh if the token has not expired.
