### ISSUE TITLE
Azcopy cp and list command work, but error  X-Ms-Error-Code: [NoAuthenticationInformation] is logged in the Windows event log.

### ISSUE THREAD

**Issue by sezginr** [Azure/azure-storage-azcopy#2077]
### Which version of the AzCopy was used? 
10.17.10, 10.16.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
running azcopy cp , also azcopy list

### What problem was encountered?
azcopy cp and list commands work, but error is logged in the Windows event log:

RESPONSE Status: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
X-Ms-Error-Code: [NoAuthenticationInformation]

We have few different server environments. A powershell script executing azcopy cp commands is triggered by batch scheduling agent.
I am wondering how I can troubleshoot the error. Would it be worth installing network packet capture software (e.g. Microsoft Network Monitor) , start capture, run azcopy, then filter the captured frames by azcopy and HTTP response status > 400
It may give a clue which endpoint azcopy is accessing when 401 error is returned.

### How can we reproduce the problem in the simplest way?
Not sure that is possible

### Have you found a mitigation/solution?
No

Please note I have previously raised issue 1855. It has some details about our proxy settings.

**Comment by sezginr** [comment]
Some more details:

azcopy is triggered in Powershell, autologin configured with Powershell environment variables, azcopy authentication method is “SPN Authentication via certificate”.
The connection to the storage account is via ExpressRoute and private endpoint, public network access to the storage account is disabled.

$env:NO_PROXY is configured, I tried various settings, the minimum required is  ourstorageaccountname.blob.core.windows.net ,  *.blob.core.windows.net and *.core.windows.net also work

the Internet access web proxy allows for azcopy authentication to work (access to login.microsoftonline.com )

On the same server, everything else equal, the azcopy cp  command does not log the error, but the azcopy list command does log the error in the event log.
I think on some of the other azcopy servers the azcopy cp command logs
the same error as well, but that is to confirmed later. The key question is why are we getting a “NoAuthenticationInformation” error logged in the Windows event logs while azcopy actually works (transfers files and lists the contents of the blob container).

The error logged in the Windows event log is below, with some sensitive details anonymised/masked. 

==> REQUEST/RESPONSE (Try=1/142.747ms, OpTime=142.747ms) -- REQUEST ERROR GET https://ourstoracc.blob.core.windows.net/treasury?restype=container&timeout=901 User-Agent: [Azure-Storage/0.15 (go1.19.2; Windows_NT)] X-Ms-Client-Request-Id: ***************************] X-Ms-Version: [2020-10-02] -------------------------------------------------------------------------------- RESPONSE Status: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header. Content-Length: [302] Content-Type: [application/xml] Date: [Mon, 20 Feb 2023 21:24:40 GMT] Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0] Www-Authenticate: [Bearer authorization_uri=https://login.microsoftonline.com/***************************/oauth2/authorize resource_id=https://storage.azure.com] X-Ms-Client-Request-Id: [***************************] X-Ms-Error-Code: [NoAuthenticationInformation] X-Ms-Request-Id: [3ad0dfe9-401e-009a-5571-453cf9000000] X-Ms-Version: [2020-10-02] -------------------------------------------------------------------------------- ERROR: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42 ===== RESPONSE ERROR (ServiceCode=NoAuthenticationInformation) ===== Description=Server failed to authenticate the request. Please refer to the information in the www-authenticate header. RequestId:3ad0dfe9-401e-009a-5571-453cf9000000 Time:2023-02-20T21:24:41.2410499Z, Details: Code: NoAuthenticationInformation GET https://ourstoracc.blob.core.windows.net/treasury?restype=container&timeout=901 User-Agent: [Azure-Storage/0.15 (go1.19.2; Windows_NT)] X-Ms-Client-Request-Id: [***************************] X-Ms-Version: [2020-10-02] -------------------------------------------------------------------------------- RESPONSE Status: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header. Content-Length: [302] Content-Type: [application/xml] Date: [Mon, 20 Feb 2023 21:24:40 GMT] Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0] Www-Authenticate: [Bearer authorization_uri=https://login.microsoftonline.com/***************************/oauth2/authorize resource_id=https://storage.azure.com] X-Ms-Client-Request-Id: [***************************] X-Ms-Error-Code: [NoAuthenticationInformation] X-Ms-Request-Id: [3ad0dfe9-401e-009a-5571-453cf9000000] X-Ms-Version: [2020-10-02] goroutine 1 [running]: github.com/Azure/azure-storage-blob-go/azblob.stack() /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_request_log.go:158 +0x65 github.com/Azure/azure-storage-blob-go/azblob.NewRequestLogPolicyFactory.func1.1({0xd69e60, 0xc000018ea0}, {0xd18c2e2800?}) /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_request_log.go:108 +0x73e github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xd69e98?, {0xd69e60?, 0xc000018ea0?}, {0x7?}) /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f github.com/Azure/azure-storage-blob-go/azblob.NewRetryPolicyFactory.func1.1({0xd69e98, 0xc00003e600}, {0xc00047e9a0?}) /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_retry.go:204 +0xa56 github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xaee8c0?, {0xd69e98?, 0xc00003e600?}, {0x16?}) /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1({0xd69e98, 0xc00003e600}, {0xc00047e9a0?}) /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_unique_request_id.go:22 +0x191 github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xaee8c0?, {0xd69e98?, 0xc00003e600?}, {0xa?}) /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1({0xd69e98, 0xc00003e600}, {0xc0000c6090?}) /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_policy_telemetry.go:34 +0x11c github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000374480?, {0xd69e98?, 0xc00003e600?}, {0xc0004695f0?}) /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc00007e100?, {0xd69e98, 0xc00003e600}, {0xd64b00?, 0xc0003129a0?}, {0xc00007e108?}) /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:129 +0x54 github.com/Azure/azure-storage-blob-go/azblob.containerClient.GetProperties({{{{0xc00007e100, 0x5}, {0x0, 0x0}, 0x0, {0xc00007e108, 0x2e}, {0xc000466a00, 0x9}, {0x0, ...}, ...}, ...}}, ...) /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zz_generated_container.go:526 +0x2d8 github.com/Azure/azure-storage-blob-go/azblob.ContainerURL.GetProperties({{{{{...}, {...}, 0x0, {...}, {...}, {...}, 0x0, 0x0, {...}, {...}, ...}, ...}}}, ...) /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/url_container.go:109 +0x90 github.com/Azure/azure-storage-azcopy/v10/cmd.getBlobCredentialType.func1() /home/vsts/work/1/s/cmd/credentialUtil.go:245 +0x48c github.com/Azure/azure-storage-azcopy/v10/cmd.getBlobCredentialType({0xd69e98, 0xc00003e600}, {0xc00007e100?, 0x0?}, 0x1, {0x0, 0x0}, {0x0, {0x0, 0x0}, ...}) /home/vsts/work/1/s/cmd/credentialUtil.go:280 +0x839 github.com/Azure/azure-storage-azcopy/v10/cmd.doGetCredentialTypeForLocation({0xd69e98, 0xc00003e600}, 0x3, {0xc00007e100, 0x7e}, {0x0, 0x0}, 0x0?, 0xc30288?, {0x0, ...}) /home/vsts/work/1/s/cmd/credentialUtil.go:560 +0x254 github.com/Azure/azure-storage-azcopy/v10/cmd.getCredentialTypeForLocation(...) /home/vsts/work/1/s/cmd/credentialUtil.go:541 github.com/Azure/azure-storage-azcopy/v10/cmd.GetCredentialInfoForLocation({_, _}, _, {_, _}, {_, _}, _, {0x0, {0x0, ...}, ...}) /home/vsts/work/1/s/cmd/credentialUtil.go:606 +0xb7 github.com/Azure/azure-storage-azcopy/v10/cmd.cookedListCmdArgs.HandleListContainerCommand({{0xc0000d0080, 0x7e}, 0x3, {0x0, 0x0, 0x0}, 0x0, 0x0, 0x0}) /home/vsts/work/1/s/cmd/list.go:212 +0x249 github.com/Azure/azure-storage-azcopy/v10/cmd.init.11.func2(0xc00046ea00?, {0xc000044170?, 0x1?, 0x1?}) /home/vsts/work/1/s/cmd/list.go:146 +0x114 github.com/spf13/cobra.(*Command).execute(0xc00046ea00, {0xc000044150, 0x1, 0x1}) /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663 github.com/spf13/cobra.(*Command).ExecuteC(0x13e2260) /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd github.com/spf13/cobra.(*Command).Execute(...) /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902 github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc0000a6d80?, 0xc0000840e0?}, {0xc0000a1ac0?, 0xbee5f8?}, 0x74?, {0x45817d35, 0x16d2, 0x454e, {0x7a, 0x28, ...}}) /home/vsts/work/1/s/cmd/root.go:192 +0x106 main.main() /home/vsts/work/1/s/main.go:89 +0x4f5

**Comment by nakulkar-msft** [comment]
Hi @sezginr, azcopy performs a GET call on the target without auth to check if the target/source is public. This is benign and should be ignored.

**Comment by sezginr** [comment]
Thank you for your response. If this error is benign would it be possible to prevent it from being logged in the Windows event log.

**Comment by elvischau** [comment]
Hi @nakulkar-msft, is there any way to disable this feature where azcopy performs a GET call on the target without auth to check if the target/source is public, it generated a lot of noise in the security log

**Comment by jbeyer05** [comment]
I would second that this 'error' should not be logged, or should be able to be disabled.
