### ISSUE TITLE
 RESPONSE Status: 401 Server failed to authenticate the request logged in Win events, But the file transfer is successful after some time.

### ISSUE THREAD

**Issue by veedi** [Azure/azure-storage-azcopy#2081]
##### Note: The version is visible when running AzCopy without any argument
10.16.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy $source $target --overwrite=$true --recursive=$true
Note: we are running azure automation powershell runbook in hybridworker, for auth it takes machine identity to transfer files.

### What problem was encountered?
Hybrid worker is used to run azure automation runbooks, Windows Event log in filled with 401 server failed and net/http: TLS handshake timeout

### How can we reproduce the problem in the simplest way?
azcopy is wrapped inside a powershell script and configured as runbook in azure automation account.
Runbook is initiated using webhook from an api.

### Have you found a mitigation/solution?
No
[winevt_errlog.log](https://github.com/Azure/azure-storage-azcopy/files/10804228/winevt_errlog.log)

If windows events logged are not actual errors or false positives. Is there a way to suppress these logs?

**Comment by nakulkar-msft** [comment]
Hi @veedi, azcopy performs a GET request without auth to check if the source is Public. This is benign and should be ignored.
