### ISSUE TITLE
Upload performance issue

### ISSUE THREAD

**Issue by yusuf-jkhan1** [Azure/azure-storage-azcopy#2083]
##### Note: The version is visible when running AzCopy without any argument
10.13 although same issue on all versions
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
copy, and sync
### What problem was encountered?
I get far less, about ~30% of my upload bandwidth speed when using Azcopy. My upload speed on the network is 100Mbps. I can't seem to get more than ~30Mbps from azcopy when uploading. Is Azcopy default multi-threaded? I did not set any concurrency env value or any cap options. The default behavior out of the box I believe is tuned to maximum performance. I've read the performance optimization documents on the wiki and online. Any suggestions or is this expected behavior?

**Comment by nakulkar-msft** [comment]
Hi @yusuf-jkhan1,  please check these pages, and accordingly configure what suits your use case.
https://github.com/Azure/azure-storage-azcopy/wiki/Performance:-Large-files-in-general
https://github.com/Azure/azure-storage-azcopy/wiki/Performance:-small-blobs 
You can use [benchmark command](https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-bench) to identify optimal config for your environment.

**Comment by yusuf-jkhan1** [comment]
Hey thanks, I did read the two articles you mentioned but even at optimal I don't seem to get near the full upload bandwidth. 

Is Azcopy default multi threaded?

**Comment by nakulkar-msft** [comment]
Yes.
