### ISSUE TITLE
Prevent AzCopy from logging into Windows event log

### ISSUE THREAD

**Issue by alexmiloev** [Azure/azure-storage-azcopy#2092]
##### Note: The version is visible when running AzCopy without any argument
10.16.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2019
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
all
### What problem was encountered?
multiple benign errors logged in Windows application log. AzCopy works fine
"The description for Event ID 0 from source C:\azcopy\azcopy.exe cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer."
### Have you found a mitigation/solution?
No

**Comment by siminsavani-msft** [comment]
Hi @alexmiloev ! Thank you for reporting this! Do you have screenshots or logging files we can refer to for this?

**Comment by alexmiloev** [comment]
![image](https://user-images.githubusercontent.com/18438535/222392860-300dce68-bced-4556-97bb-657e38a16922.png)
After that failed unauthenticated GET, azcopy connects and works as told, but this fills event log with errors. I don't want to go to --log-level NONE if there is an alternative, like disable logging to Windows event log while still logging to file?

**Comment by siminsavani-msft** [comment]
AzCopy performs a GET call on the target without auth to check if the target/source is public. This is benign and should be ignored. 

At the moment, there isn't a way to disable logging to Windows event log from AzCopy. I would recommend checking if there is way to do that outside of AzCopy.
