### ISSUE TITLE
Missing Error message when azcopy rm failed

### ISSUE THREAD

**Issue by veedi** [Azure/azure-storage-azcopy#2093]
##### Note: The version is visible when running AzCopy without any argument
10.16.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy rm <leased blob path>

### What problem was encountered?
azcopy failed when trying to remove a blob i.e. leased, **TransfersFailed: 1**. But error message was not populated.
![image](https://user-images.githubusercontent.com/7250226/222090237-8712cb65-8c23-4071-a424-718223e16642.png)

### How can we reproduce the problem in the simplest way?
Try deleting a leased blob[Azure storage container] using azcopy rm.

### Have you found a mitigation/solution?
No

**Comment by siminsavani-msft** [comment]
Hi @veedi ! I am able to successfully delete a leased blob with AzCopy. Could you please rerun with --log-level=DEBUG and share the results with us?

**Comment by veedi** [comment]
Hi again @siminsavani-msft , 
We do not know the leaseid for the blob and there could be 'n' number of files to remove that may be leased, it's ok if the azcopy fail.
We expect error message to be populated why the azcopy rm command failed. we could see the error message in log file but not in the error message property in the command output logs.

Please see attached log file generated in azcopy logs folder.
**RESPONSE Status: 412 There is currently a lease on the blob and no lease ID was specified in the request.**
[leasejob.log](https://github.com/Azure/azure-storage-azcopy/files/10870096/leasejob.log)


**Command log output when executing azcopy rm command,**
========================================
ErrorMsg                : 
JobID                   : 85fa3c45-9004-cc4c-4124-16f8c3aa7ab2
ActiveConnections       : 0
CompleteJobOrdered      : True
JobStatus               : Failed
TotalTransfers          : 1
FileTransfers           : 1
FolderPropertyTransfers : 0
TransfersCompleted      : 0
TransfersFailed         : 1
TransfersSkipped        : 0
BytesOverWire           : 0
TotalBytesTransferred   : 0
TotalBytesEnumerated    : 20
TotalBytesExpected      : 0
PercentComplete         : 100
AverageIOPS             : 0
AverageE2EMilliseconds  : 0
ServerBusyPercentage    : 0
NetworkErrorPercentage  : 0
FailedTransfers         : {@{Src=https://stousedmdmzdv.blob.core.windows.net/rbac-product-p00000046-pc00000282/sample2.t
                          xt; Dst=; IsFolderProperties=False; TransferStatus=Failed; TransferSize=0; ErrorCode=0}}
SkippedTransfers        : 
PerfConstraint          : 0
PerformanceAdvice       : {}
IsCleanupJob            : False
===================================

**Comment by siminsavani-msft** [comment]
@veedi Thank you for sharing the logs! The command output is intended to be minimized for perf/UX reasons and errors won't populate in the command output. 

When you run AzCopy on many files, the `TransfersFailed` and `TransfersCompleted` will be updated to match the number of files that have failed or completed, respectively. The best way to get **why** AzCopy failed is running `--log-level=DEBUG` (which I noticed from the log files that you already did).
