### ISSUE TITLE
File name with specials characters [#,%] fail using azcopy

### ISSUE THREAD

**Issue by veedi** [Azure/azure-storage-azcopy#2094]
##### Note: The version is visible when running AzCopy without any argument
10.16.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy rm "<storageaccount>/<container>/test_special_#_6_^_&_yt_88" --> **Number of File Transfers: 0**
azcopy rm "<storageaccount>/<container>/test_special_$_6_^_&_yt_88" --> **Number of File Transfers: 0**
azcopy rm "<storageaccount>/<container>/test_special_%_6_^_&_yt_88" --> **Failed**
**Note: Using powershell script to run azcopy commands.**

### What problem was encountered?
azcopy failed when using special character '%' in file name that was stored in azure storage account.
Special characters # and $ in filename cause **Number of File Transfers: 0**.

### How can we reproduce the problem in the simplest way?
when using special character '%' in file name, all acopy commands fail.

### Have you found a mitigation/solution?
No

If Azure storage account is able to save blobs with special characters in file name,  azcopy should allow the same for transfers and remove files with special characters. Please assist if specials characters needs to treated separately when passing to azcopy commands.

**Comment by siminsavani-msft** [comment]
Hi @veedi ! I am able to successfully remove files/folders with special characters using AzCopy. Could you please share your full command?

For reference, this is what my command looks like: 
`azcopy rm "https://[account-name].blob.core.windows.net/[container-name]?[SAS]" --recursive`

**Comment by veedi** [comment]
Hi @siminsavani-msft, 
**Command:**
azcopy login
azcopy rm "https://XXXXX.blob.core.windows.net/XXXXX-XXXX/test_special_#_4_$_%_6_^_&_yt_88.txt" --log-level=DEBUG

**Error message:**
Error: invalid source type Local to delete. azcopy support removing blobs/files/adls gen2

screenshot fyr
![image](https://user-images.githubusercontent.com/7250226/222390294-9b865d23-9e0e-4aa5-9f62-5fd0c43ce366.png)

**Comment by nakulkar-msft** [comment]
Hi @veedi, these characters will have to be url encoded. Please retry the operation with appropriate url.

**Comment by veedi** [comment]
Thanks @nakulkar-msft , encoding file name worked.
