### ISSUE TITLE
azcopy copy --recursive --follow-symlinks=true does not support symlinks to individual files

### ISSUE THREAD

**Issue by michaelmoore10** [Azure/azure-storage-azcopy#2095]
### Which version of the AzCopy was used? 
10.13.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy copy --recursive --follow-symlinks=true . 'https://<BLOB ACCOUNT NAME>/container001/fy23/q2/AgnosticData/MSPEC/24.7.1/ProductionReadyNeutral?[SAS TOKEN]'
### What problem was encountered?

azcopy reported that multiple messages about symlinks to individual files were not supported:  Example

INFO: Symlinks to individual files are not currently supported, so will ignore file at <FILENAME REDACTED>

### How can we reproduce the problem in the simplest way?

In a testing  directory
1. echo "test" > foo
2. mkdir testdir/testdir1
3. cd testdir/testdir1
4. ln -s ../../foo
5. cd ../
6. azcopy copy --recursive --follow-symlinks=true . '<SAS URL to Blob or ASDL2 container>'

### Have you found a mitigation/solution?
No

**Comment by siminsavani-msft** [comment]
Hi @michaelmoore10 ! Symlinks are supported in the latest version of AzCopy v10.17.0 (https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.17.0). Please consider upgrading and trying again! 

I will close this issue for now, but feel free to reopen if you find any other issues.

**Comment by michaelmoore10** [comment]
Thank you.  I upgraded to 10.17.0 after opening the ticket, and follow-symlinks work.  You can close the ticket.

From: siminsavani-msft ***@***.***>
Sent: March 1, 2023 4:45 PM
To: Azure/azure-storage-azcopy ***@***.***>
Cc: Moore, Michael ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Azure/azure-storage-azcopy] azcopy copy --recursive --follow-symlinks=true does not support symlinks to individual files (Issue #2095)

CAUTION: This Email is from an EXTERNAL source. Ensure you trust this sender before clicking on any links or attachments.
________________________________

Hi @michaelmoore10<https://urldefense.com/v3/__https:/github.com/michaelmoore10__;!!L7QdHkQ!m5T_Mzf2yqcdhEUzHx9FFZLugUiy3KTwVW_mbPtX3QxDDsk_O5eRQvudevKaXE8LAtZTNz6fMW5FjrZP2agpp-ms19Y$> ! Symlinks are supported in the latest version of AzCopy v10.17.0 (https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.17.0<https://urldefense.com/v3/__https:/github.com/Azure/azure-storage-azcopy/releases/tag/v10.17.0__;!!L7QdHkQ!m5T_Mzf2yqcdhEUzHx9FFZLugUiy3KTwVW_mbPtX3QxDDsk_O5eRQvudevKaXE8LAtZTNz6fMW5FjrZP2agpKM4fwGY$>). Please consider upgrading and trying again!

I will close this issue for now, but feel free to reopen if you find any other issues.
