### ISSUE TITLE
Copying to an empty fileshare terminates with CompletedWithSkipped

### ISSUE THREAD

**Issue by mtessier84** [Azure/azure-storage-azcopy#2101]
### Which version of the AzCopy was used? 
10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy.exe copy https://mystorageaccount.file.core.windows.net/MyFileshare/Data$SAS https://mystorageaccount2.file.core.windows.net/MyFileshare2/Data$SAS) --check-length=false --recursive=true --overwrite "ifSourceNewer" --log-level "INFO"

### What problem was encountered?
The target fileshare is empty and the copy completes with 'CompletedWithSkipped' because 'Folder already exists'

Job 37d043b9-27e7-744a-5add-d907688af760 summary
Elapsed Time (Minutes): 7.5939
Number of File Transfers: 20289
Number of Folder Property Transfers: 2172
Total Number of Transfers: 22461
Number of File Transfers Completed: 20289
Number of Folder Transfers Completed: 2041
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
**Number of Folder Transfers Skipped: 131**
TotalBytesTransferred: 810884531
**Final Job Status: CompletedWithSkipped**

I can get the skipped entities by running
azcopy jobs show 37d043b9-27e7-744a-5add-d907688af760 --with-status=Failed

There is 131 folder skipped with the mention 'SkippedEntityAlreadyExists'. 
The detailed logs says: Folder already exists, so due to the --overwrite option, its properties won't be set

In orther words, they were not really skipped. The same copy can complete without any skip on the next run.

### Have you found a mitigation/solution?
I perform further analysis in the logs to ensure nothing was really skipped

**Comment by mtessier84** [comment]
Just an update. I have cases with as much as 80595 skipped folders

Job 601b9fdc-9a67-e041-56c0-50836a944078 summary
Elapsed Time (Minutes): 188.3566
Number of File Transfers: 57277
Number of Folder Property Transfers: 83090
Total Number of Transfers: 140367
Number of File Transfers Completed: 57277
Number of Folder Transfers Completed: **2495**
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: **80595**
TotalBytesTransferred: 30569986253
Final Job Status: **CompletedWithSkipped**

This is still a copy to an empty fileshare.

I reverted back to 10.16.2 and things are much better

**Comment by siminsavani-msft** [comment]
Hi @mtessier84 ! Thank you for updating us. I had a few questions so I can understand your case better. 

1. Just so I'm understanding correctly, your destination/target fileshare is empty but when you run azcopy it returns 'CompletedWithSkipped'. When you check for the files/folders that are skipped, they are not actually skipped?

2. Could you provide the azcopy log file?

3. You mentioned reverting to 10.16.2 led to better results, are you not seeing the 'CompletedWithSkipped' anymore?

**Comment by mtessier84** [comment]
Hi,

Thank you for checking

Your understanding is correct. When I say "they are not actually skipped", I mean that the folder and files are in the target file share. However, according to logs, it seems like the process want to "set" the folder properties after the folder was created thus it leads to ' Folder already exists, so due to the --overwrite option, its properties won't be set'

if I run azcopy jobs show 'the-job-id' --with-status=Failed, then I can see the skipped item and the mention 'SkippedEntityAlreadyExists'

The same behavior can be observed in 10.16.2, but looks more stable and it returns less 'CompletedWithSkipped'

I can share the logs by email.

Thank you

**Comment by siminsavani-msft** [comment]
That's interesting, thank you for clarifying. Please feel free to send the logs at siminsavani@microsoft.com.

**Comment by mtessier84** [comment]
Thanks

Unfortunately, I can't help you to reproduce the issue and the logs (and many more) demonstrate the issue. The copy is from Azure Files to Azure Files, so I think you explanation would not apply.

One additional observation I made is that things look more stable since 2 weeks. I wonder if the issue could be on the Azure backend API rather than the azcopy tool itself.

Please note that the reported issued occurred 10+ times within the same week, so it was not just a one time issue

**Comment by siminsavani-msft** [comment]
@mtessier84 Apologies for the delay! There are a couple of "503 The server is busy."  errors when doing some upload operations in the logs you shared, which indicates that your job is being throttled by the Storage service. Please consider breaking down your job into smaller jobs or following these documentations: 
- https://github.com/Azure/azure-storage-azcopy/wiki/Troubleshooting---FAQ#server-busy-network-errors-timeouts
- https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json#increase-the-number-of-concurrent-requests
- https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-use-azcopy-troubleshoot#server-busy-network-errors-or-timeouts

Please feel free to reopen this issue or create a new issue if you are still having trouble with this or have any other questions!
