### ISSUE TITLE
--list-of-files cannot open txt file

### ISSUE THREAD

**Issue by mwarqee** [Azure/azure-storage-azcopy#2111]
### Which version of the AzCopy was used?
10.17.0 
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy copy --dry-run --recursive https://source.blob.core.windows.net/ https://target.blob.core.windows.net/ --list-of-files https://source.blob.core.windows.net/dir1/copy.txt

ALSO

azcopy set-properties --list-of-files https://source.blob.core.windows.net/ https://source.blob.core.windows.net/dir1/copy.txt

### What problem was encountered?
failed to parse user input due to error: cannot open source.blob.core.windows.net/dir1/copy.txt file passed with the list-of-file flag

### How can we reproduce the problem in the simplest way?
run the commands above logged in with an SP via aad (azcopy -login --service-principal --application-id --tenant-id)
### Have you found a mitigation/solution?
NOPE and also not properly described in the documentation

The text file (copy.txt) on the storage account container contains 1 line 
https://source.blob.core.windows.net/test/bigddlakes/RAW/DB

**Comment by gapra-msft** [comment]
Hi @mwarqee,

I believe you are using the list of files parameter incorrectly. Please take a look at [this page](https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer) in our Wiki to learn more about the parameter.

**Comment by mwarqee** [comment]
> Hi @mwarqee,
> 
> I believe you are using the list of files parameter incorrectly. Please take a look at [this page](https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer) in our Wiki to learn more about the parameter.

@gapra-msft - apologies but could you please give an example of how this flag can be used properly? The link you have pointed at contains no examples, and is rather ambiguous. As stated in the page (from 2020)` this flag remains undocumented (except for this wiki page)`.

Questions:
1. Is the flag applicable only for local to cloud uploads or does it also work from cloud to cloud storage?
2. Do you have to point to a specific file, or is it enough to point to paths which azcopy copy will then pick up recursively?
3. If it is only valid for individual files is there another option to use it in the following way:

A txt file stored in a container on Azure Storage (storageaccount.container.blob.core.windows.net/container1/) which contains a list of paths:

storageaccount.container.blob.core.windows.net/container2/dir2/ - copies everything in path dir2

storageaccount.container.blob.core.windows.net/container2/dir3/dir4 - copies everything in path dir4

If the --list-of-files flag is not suitable for this functionality, can you please specify what should be used? If this feature does not exist yet will it be made available in the future?

Thanks!

**Comment by gapra-msft** [comment]
Closing as I believe the questions have been addressed. Please feel free to reopen in case something else comes up.
