### ISSUE TITLE
azcopy not working for wasabi buckets

### ISSUE THREAD

**Issue by svrviny1324** [Azure/azure-storage-azcopy#2114]
### Which version of the AzCopy was used? 
version 10.17.0 ? 
### Which platform are you using? (ex: Windows, Mac, Linux)
linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "https://<blob-name>.blob.core.windows.net/batch-output/tts/e?<SAS>" "https://s3.eu-central-2.wasabisys.com/france/" --recursive

### What problem was encountered?
when iam trying to copy data from azure storage container to wasabi bucket by using above command it get copying into local instead of wasabi bucket.
### How can we reproduce the problem in the simplest way?
is azcopy cp support to copy data from azure to wasabi bucket?

**Comment by nakulkar-msft** [comment]
Hi @svrviny1324, azcopy currently does not transfer data to S3 endpoints. We've already logged this in our backlog.
