### ISSUE TITLE
How to copy from local Unix to ADLS Gen2 using AZCOPY(10) Preview?

### ISSUE THREAD

**Issue by Dreambubble** [Azure/azure-storage-azcopy#212]

**Comment by Dreambubble** [comment]
Version: 10.0.7
Linux
./azcopy "/home/file1.gz" "https://<myaccount>.dfs.core.windows.net/folder1/test1"
OAuth token or shared key should be provided for Blob FS

Can you please provide me a complete sample/test command to do this?

**Comment by zezha-msft** [comment]
Hi @Dreambubble, please refer to the help message `./azcopy cp --help` for command syntax. 

Please log in using `./azcopy login`. Then launch your command `./azcopy cp "/home/file1.gz" "https://account.dfs.core.windows.net/folder1/test1"`.
