### ISSUE TITLE
AzCopy V10.0.7 Cannot Bind parameter 'NewerThan' error

### ISSUE THREAD

**Issue by Kapanther** [Azure/azure-storage-azcopy#213]
Azcopy V10.0.7 - Win 7 64 bit and win 10 64 bit

When using AZCOPY SYNC from BLOB to LOCAL i keep getting this strange date time error

> ERROR: Cannot bind parameter 'NewerThan'. Cannot convert value "True" to type "System.DateTime". Error: Invalid cast from "Boolean' to "datetime'."

![image](https://user-images.githubusercontent.com/12637127/52823524-61653480-3109-11e9-9dc7-998274bb4ed0.png)

Any Ideas?

**Comment by JeffreyRichter** [comment]
This really seems like an AzCopy v8 issue; not a v10 issue.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Ftraining%2Fdistributed-cloud-apps%2F&data=02%7C01%7Cjeffreyr%40microsoft.com%7C948cf3366acf45f6ef8d08d62e3b3b00%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636747229263047172&sdata=sg%2FtzHWpscWQDr7foOSsaNrKDP5vNSHE3b72HJG8swU%3D&reserved=0>)

**Comment by zezha-msft** [comment]
Hi @Kapanther, thanks for reaching out! Could you please share the full command (please scrub away your account info)? That error indeed looks a bit strange.

On a side note, I've rewritten the sync command, to address the various issues reported on Github. It will be released soon.

**Comment by Kapanther** [comment]
How embarrassing.. was a faulty subroutine in power shell script that was called just before azcopy ran.. Please delete this thread or abuse me accordingly for wasting your time! Promise ill check more thoroughly before posting.

**Comment by zezha-msft** [comment]
Hi @Kapanther, no worries! Thanks for letting us know!
