### ISSUE TITLE
CannotVerifyCopySource Error while performing AzCopy Sync between two File Shares

### ISSUE THREAD

**Issue by alemairebe** [Azure/azure-storage-azcopy#2164]
### Which version of the AzCopy was used? 
10.18.0

### Which platform are you using? (ex: Windows, Mac, Linux)
All 3
### What command did you run?
azcopy sync "https://[account1].file.core.windows.net/[src_share]?sv=2021-12-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-04-17T16:46:49Z&st=2023-04-17T08:46:49Z&spr=https&sig=[removed]%3D" "https://[account2].file.core.windows.net/[dest_share]?sv=2021-12-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-04-17T16:29:11Z&st=2023-04-17T08:29:11Z&spr=https&sig=[removed]%3D" --recursive --delete-destination true

### What problem was encountered?
===== RESPONSE ERROR (ServiceCode=CannotVerifyCopySource) =====
Description=This request is not authorized to perform this operation.
RequestId:9d721c21-301a-0047-3c37-717cff000000
Time:2023-04-17T14:20:53.2147373Z, Details:
   Code: CannotVerifyCopySource
   PUT https://[account2].file.core.windows.net/[dest_share]/[some_file]?comp=range&se=2023-04-17t16%3A29%3A11z&sig=-REDACTED-&sp=rwdlacupiytfx&spr=https&srt=sco&ss=bfqt&st=2023-04-17t08%3A29%3A11z&sv=2021-12-02&timeout=901
   Content-Length: [0]
   User-Agent: [AzCopy/10.18.0 Azure-Storage/0.8.0 (go1.19.6; linux)]
   X-Ms-Client-Request-Id: [adb33255-558e-49f6-4019-a8a714c64939]
   X-Ms-Copy-Source: [https://[account1].file.core.windows.net/[src_share]/[some_file]?se=2023-04-17t16%3A46%3A49z&sig=-REDACTED-&sp=rwdlacupiytfx&spr=https&srt=sco&ss=bfqt&st=2023-04-17t08%3A46%3A49z&sv=2021-12-02]
   X-Ms-Range: [bytes=58720256-62914559]
   X-Ms-Source-Range: [bytes=58720256-62914559]
   X-Ms-Version: [2020-10-02]
   X-Ms-Write: [update]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [248]
   Content-Type: [application/xml]
   Date: [Mon, 17 Apr 2023 14:20:53 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [adb33255-558e-49f6-4019-a8a714c64939]
   X-Ms-Error-Code: [CannotVerifyCopySource]
   X-Ms-Request-Id: [9d721c21-301a-0047-3c37-717cff000000]
   X-Ms-Version: [2020-10-02]

### How can we reproduce the problem in the simplest way?
each storage account is in a different subscription.
each have private endpoints. They can both be accessed from on-prem over vpn / hub subscription.
https endpoints are reachable in any subscriptions; unlike the SMB endpoints.

### Have you found a mitigation/solution?
Mount the share of the subscription on a VM and perform a copy/sync from HTTPS interface of the other share.

**Comment by nakulkar-msft** [comment]
Hi @alemairebe you should set up a vnet peering between the vnets on source and destination. Let us know if you still see this issue post that.

**Comment by nakulkar-msft** [comment]
Please reopen if you still see the issue.
https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview
