### ISSUE TITLE
panic: service sided attribute flags should never fail

### ISSUE THREAD

**Issue by Caramba77** [Azure/azure-storage-azcopy#2174]
##### Note: The version is visible when running AzCopy without any argument
10.18.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy.exe copy "$srcURL/plugins/$srcToken" "$dstURL/data2/$dstToken" --recursive=true --log-level=ERROR

### What problem was encountered?
panic: service sided attribute flags should never fail

### How can we reproduce the problem in the simplest way?
From a VM, copy from one Storage Account to another

### Have you found a mitigation/solution?
No.  If I use my personal Windows PC, it works passing through the proxy.
Not working from the virtual machine on the company network.
Was working 3 weeks ago and stopped working.
I guess there's been a change in the network here, but I'd like to know what could cause this based on the error I get.
I tried both these :
$env:HTTP_PROXY=""
$env:HTTPS_PROXY=""
and
$env:HTTPS_PROXY="dummy.invalid"
$env:NO_PROXY="*"
without success.

**Comment by nakulkar-msft** [comment]
Hi @Caramba77, can you post the backtrace?

**Comment by Caramba77** [comment]
Hello !
Here it is :
./azcopy.exe : panic: service sided attribute flags should never fail
Au caractère C:\Users\bw6735-5\azcopy\jira_test.ps1:110 : 1
+ ./azcopy.exe copy "$srcURL/plugins/$srcToken" "$dstURL/data2/$dstToke ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: service ...ould never fail:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
goroutine 67 [running]:
github.com/Azure/azure-storage-file-go/azfile.ParseFileAttributeFlagsString({0x0, 0x0})
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/smb_property_bitflags.go:101 +0x2a5
github.com/Azure/azure-storage-file-go/azfile.(*SMBPropertyAdapter).FileAttributes(0xc001338af8?)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/zz_response_helpers.go:63 +0x27
github.com/Azure/azure-storage-azcopy/v10/ste.(*azureFileSenderBase).addSMBPropertiesToHeaders(_, {{0xbd7c5b28, 0x977b, 0xc642, {0x55, 0xfd, 0xdb, 0x2f, 0xb7, 0xb1, ...}}, ...}, 
...)
	/home/vsts/work/1/s/ste/sender-azureFile.go:317 +0x9a
github.com/Azure/azure-storage-azcopy/v10/ste.(*azureFileSenderBase).Prologue(0xc0028fe1a0, {{0x0?, 0x9d0?, 0xc00007c0d0?}})
	/home/vsts/work/1/s/ste/sender-azureFile.go:160 +0x4db
github.com/Azure/azure-storage-azcopy/v10/ste.scheduleSendChunks({0x149e2a0, 0xc0001280e0}, {0xc0000d4180, 0xbe}, {0x0?, 0x0}, 0x9d0, {0x14945c0, 0xc0028fe1a0}, 0x0, ...)
	/home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:440 +0x6c4
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote_file({_, _}, {{0xbd7c5b28, 0x977b, 0xc642, {0x55, 0xfd, 0xdb, 0x2f, 0xb7, ...}}, ...}, ...)
	/home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:357 +0xe1b
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote({0x149e2a0, 0xc0001280e0}, {0x14877e0, 0xc000490100}, {0x190fc7aba18, 0xc00006c3c0}, 0xc000466680?, 0x2b?)
	/home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:191 +0x458
github.com/Azure/azure-storage-azcopy/v10/ste.parameterizeSend.func1({0x149e2a0?, 0xc0001280e0?}, {0x14877e0?, 0xc000490100?}, {0x190fc7aba18?, 0xc00006c3c0?})
	/home/vsts/work/1/s/ste/xfer.go:77 +0x44
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartMgr).StartJobXfer(0x1b1b400?, {0x149e2a0?, 0xc0001280e0?})
	/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:730 +0x50
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).StartJobXfer(0xc0001280e0?)
	/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:243 +0x32
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor.func1({0x149e2a0, 0xc0001280e0})
	/home/vsts/work/1/s/ste/mgr-JobMgr.go:1015 +0x199
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor(0xc000003400, 0x0?)
	/home/vsts/work/1/s/ste/mgr-JobMgr.go:1027 +0xbd
created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr
	/home/vsts/work/1/s/ste/mgr-JobMgr.go:202 +0xc37

**Comment by adreed-msft** [comment]
Smells like azure files supports a new attribute flag our code doesn't handle. Simple enough fix, in theory.

**Comment by adreed-msft** [comment]
BTW, temporary workaround can be to disable smb properties persistence; `--preserve-smb-info=false`

**Comment by adreed-msft** [comment]
Doesn't look like there were any new properties introduced. Here's what we'll do here: I'll add a recover in the usual places this could get called. What I'd like you to do, after 10.19 releases (or whatever release this PR makes it into) @Caramba77 is to retry this, and report what we're getting handed back to do some experimentation.

**Comment by adreed-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/pull/2207
