### ISSUE TITLE
The specified parent path does not exist

### ISSUE THREAD

**Issue by monishadua01** [Azure/azure-storage-azcopy#2179]
### Which version of the AzCopy was used? 
10.18.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
cat "x.log" | less

### What problem was encountered?
Backup is completing with errors

### How can we reproduce the problem in the simplest way?
Through backup report and log file

### Have you found a mitigation/solution?
We tried to free some space from the server

**Comment by monishadua01** [comment]
![image](https://user-images.githubusercontent.com/130741983/233590659-f6359d51-6464-4608-b1fb-183aeb34492e.png)

**Comment by monishadua01** [comment]
This is what we have found from the logs. We have azcopy script running on daily basis for the backup of our live environment, but we are getting Completed job with errors. For reference below:

Existing Jobs JobId: 29e1bb20-2686-5541-4756-a35877d2e0d0 Start Time: Thursday, 20-Apr-23 04:00:02 UTC Status: CompletedWithErrors Command: copy /storage/gitaly1-backup-snapshot/ https://domainname.file.core.windows.net/gitaly1-backup/daily/2023-04-20?se=2030-09-20t02%3A05%3A11z&sig=REDACTED&sp=rwdlc&spr=https&srt=sco&ss=f&st=2022-09-19t18%3A05%3A11z&sv=2021-06-08 --recursive=true --log-level=ERROR

**Comment by monishadua01** [comment]
![image](https://user-images.githubusercontent.com/130741983/233637810-56786c74-4792-410b-a28f-1d75fdbdd5a5.png)

**Comment by nakulkar-msft** [comment]
Hi @monishadua01, can you post the log file? My email address on my profile.

**Comment by nakulkar-msft** [comment]
HI @monishadua01, these are not errors  but expected request failures in the workflow. AzCopy does not create parent directories for a file, unless they dont exist. We rely on the request failure error to determine if AzCopy needs to create parent directories.

**Comment by mstenz** [comment]
Hi @nakulkar-msft As you see the whole job was failing. I think if you internally only create folders when they were found as "not available" is ok, but you should then not fail the whole job if this is expected behavior, instead do not log the error, and do not fail the job?

**Comment by nakulkar-msft** [comment]
Empty folders are copied. The job failed for a different reason. Your source is case sensitive, while destination - Azure Files - is [case insensitive](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata#directory-and-file-names). 

You have more than one file, with names differing in casing of the letters. Delete/rename them and retry the operation
storage/gitaly1-backup-snapshot/repositories/@hashed/dc/d0/dcd0ea5b0fea71aa19678a266ac3620df54c68aef9e329a31f969a3862ba9168.git/refs/heads/develop_HTML_Mockup

**Comment by mstenz** [comment]
> Delete/rename them and retry the operation

not sure understand what you mean by this. Where I should delete something? The target is empty when the copy is started. This is why I do not expect any issues. The whole structure should be copied 1:1 to the target (like a backup)

**Comment by mstenz** [comment]
> while destination - Azure Files - is [case insensitive](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata#directory-and-file-names).

That's very interesting, I was not aware of this. we need a 1:1 full backup to a case-sensitive target. I think we need to move from Azure File Storage to Object Storage.
