### ISSUE TITLE
Missing `v` prefix in the latest git tag (`10.18.1`)

### ISSUE THREAD

**Issue by PeterDaveHello** [Azure/azure-storage-azcopy#2180]
### Which version of the AzCopy was used? 

10.18.1

### Problem:

I use wget and jq to send the request and parse the result from GitHub API, the result is inconsistent:

```
$ wget https://api.github.com/repos/Azure/azure-storage-azcopy/releases -qO- | jq -r '.[]|.tag_name' | head
10.18.1
v10.18.0
v10.17.0
v10.16.2
v10.16.1
v10.16.0
v10.15.0
v10.14.1
v10.14.0
v10.13.0
```

### Reference

#1067

**Comment by adreed-msft** [comment]
Whoops!

Thanks for pointing this out. As it's already public, it's possible someone has come to rely upon the (accidental) new scheme. Thus, we will not delete the old tag, but will instead add a new `v10.18.1` tag on.
