### ISSUE TITLE
azcopy list a single file and output the filename

### ISSUE THREAD

**Issue by sebaszero** [Azure/azure-storage-azcopy#2181]
### Which version of the AzCopy was used? 
10.18.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy list "<container_url>/<container_directory>/<blob_filename>?<sas_token>"

### What problem was encountered?
I can list all the files in the directory but when i list a single specific file it doesn't output the filename only:
INFO: ;  Content Length: 482.81 KiB

I tried using available attributes in --properties it does find the attribute of the single file i use in my command but still no filename in the output

### How can we reproduce the problem in the simplest way?
By running the command to list a single file (blob). You won't get the filename as output.
azcopy list "<container_url>/<container_directory>/<blob_filename>?<sas_token>"

### Have you found a mitigation/solution?
When listing a single file also show the filename in the output

**Comment by adreed-msft** [comment]
This is expected behavior given the way the listing operation works, but we can correct this in 10.19.0.

I'll assign this to myself now and get a PR out soon.

**Comment by nakulkar-msft** [comment]
Fixed in 10.19
