### ISSUE TITLE
--output-type=json not honoured in copy download with destination path ending \.

### ISSUE THREAD

**Issue by SimonTiz** [Azure/azure-storage-azcopy#2182]
AzCopy 10.16.2

Windows (10), 
Powershell 5.1.19041.2673

. ". . .\azcopy.exe" copy "https://[account].blob.core.windows.net/[container]/[path/to/blob]?[SAS" "path\to\" --log-level=INFO --output-level=default --output-type=json

If the destination path is  "path\to"  or "path\to\filename" then no problem, however if as above destination path for download is "path\to\"  (with final '\'), then has an issue.
Having an issue with such is not he issue, but the PROBLEM IS:  when this occurs the  --output-type=json  flag/option is not honoured and the output is produced as text.

Repro - see above

Mitigation - TBD  ( will avoid the circumstance and have to decide whether to put effort into the output being in the incorrect format - an issue as am writing my own Powershell wrapper function for this, and want to be able to identify issue and pull errors/exception messaging in a consistent way ).

**Comment by adreed-msft** [comment]
Hi, @SimonTiz, just to verify, you're not accidentally escaping the last quotation mark, right? I could see the flags not getting caught if that were the case.

**Comment by nakulkar-msft** [comment]
Hi @SimonTiz, can you let me know the exact command you've used? Also, Can you post the first 20 lines of the azcopy log file?

**Comment by SimonTiz** [comment]
Hi @nakulkar-msft, @adreed-msft.  Thanks for the responses,

my cmd line is
 **$op = (. "$AzCopyExe" cp "$source$SAS2" "$target$SAS" $CopyOptions )** 
where $variables are [string] except for $CopyOptions which is Object[] (System.Array)

resulting in (paths shortened):-
**$op = (. "C:\myApps\Azcopy\Exe\azcopy.exe" cp "https://mysa.blob.core.windows.net/simon-ftfr-01/DummyA.txt?sv=2021-12-02&ss=b&srt=sco&sp=rwdliytfx&se=2033-04-19T23:00:00Z&st=2023-04-15T23:00:00Z&spr=https&sig=REDACTED" "C:\myFolder\Data\" --log-level=INFO --output-level=default --output-type=json )**
    which exhibits the same behaviour when issued in above expanded variables line, and with "'s replaced with 's.

whlist I don't see that escaping what comes after,
From the log (below) it does appear to be escaping that "

**1st lines of log of such**
2023/04/25 07:06:15 AzcopyVersion  10.16.2
2023/04/25 07:06:15 OS-Environment  windows
2023/04/25 07:06:15 OS-Architecture  amd64
2023/04/25 07:06:15 Log times are in UTC. Local time is 25 Apr 2023 08:06:15
2023/04/25 07:06:15 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2023-04-25T07:06:10Z or --include-after=2023-04-25T07:06:10Z
2023/04/25 07:06:15 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
**2023/04/25 07:06:16 Job-Command cp https://mysa.blob.core.windows.net/simon-ftfr-01/DummyA.txt?se=2033-04-19t23%3A00%3A00z&sig=-REDACTED-&sp=rwdliytfx&spr=https&srt=sco&ss=b&st=2023-04-15t23%3A00%3A00z&sv=2021-12-02 C:\myFolder\Data" --log-level=INFO --output-level=default --output-type=json** 


I have just tried with re-ordered cmd line  
 **$op = (. "$AzCopyExe" cp $CopyOptions "$source$SAS2" "$target$SAS" )** 
and that works ok. ( So a workaround ).

But I still don't understand why it would expand/parse the way it appears to be so doing.
If I suffix a extra \ , it then escapes the \ and evaluates correctly, but it doesn't need any of the other \s to be so escaped;  nor is it a problem if a destination filename is provided .

**Comment by adreed-msft** [comment]
Putting the flags behind the arguments being a workaround isn't surprising; if anything it gives credence to the idea that the second string isn't getting escaped properly. Same to the last quotation mark being included in the log:

> 2023/04/25 07:06:16 Job-Command cp https://mysa.blob.core.windows.net/simon-ftfr-01/DummyA.txt?se=2033-04-19t23%3A00%3A00z&sig=-REDACTED-&sp=rwdliytfx&spr=https&srt=sco&ss=b&st=2023-04-15t23%3A00%3A00z&sv=2021-12-02 ***C:\myFolder\Data"*** --log-level=INFO --output-level=default --output-type=json

This doesn't sound like explicitly an AzCopy error.

**Comment by SimonTiz** [comment]
I suspect you are right, I don't know much about cobra.
I had thought it quite possibly that it was down to AzCopy'ss parsing of its passed-in arguments, and then I found the GitHub Writer for this site does the same thing.

One would expect any parser to require all escapable characters to be escaped, including the escape character \ itself, but that's clearly not the case here as the other instances of \ themselves don't need it (but will accept it), (and the other "s are interpreted).  The likelihood seems to be that what ever is parsing the line is checking the character following an escape \ and if it is an escapable character then it 'escapes' it, if not then it takes the \ as itself 'escaped';  and we end up with this mish-mash.

Not a big issue in most coding circumstances as currently the final \ needs to be dropped, which testing ought to show up , but I can see instances where it might become an issue.  Perhaps a warning in the AzCopy documentation would be an idea.

**Comment by adreed-msft** [comment]
> Not a big issue in most coding circumstances as currently the final \ needs to be dropped, which testing ought to show up , but I can see instances where it might become an issue. Perhaps a warning in the AzCopy documentation would be an idea.

`\` tends to be a universal escape character, which is a bit of "assumed knowledge" when working with command line tools. I can pop a line into the AzCopy helptext, though.

**Comment by gapra-msft** [comment]
Most shells treat \ as a escape character. As this is generally assumed knowledge when working with command line tools, we do not intend to add this to our documentation.
