### ISSUE TITLE
Add Support for Azure Files to Azure Files Sync Using Identity

### ISSUE THREAD

**Issue by mbrat2005** [Azure/azure-storage-azcopy#2183]
### Which version of the AzCopy was used? 
10.18.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows and Linux

### What command did you run?

`azcopy  sync  https://filesyncfunction01.file.core.windows.net/sourceshare/  https://filesyncfunction03.file.core.windows.net/destshare/  --preserve-smb-info  --preserve-smb-permissions  --recursive`

### What problem was encountered?

Difficult error message:
`error parsing the input given by the user. Failed with error service level URLs () are not supported in sync:`

--> https://github.com/Azure/azure-storage-azcopy/blob/main/cmd/pathUtils.go#L260

### How can we reproduce the problem in the simplest way?

1. azcopy login
2. Run command as above with two shares

### Have you found a mitigation/solution?

Continue using SAS tokens.

**Comment by mbrat2005** [comment]
It would be great if the error were more clear, but even better if AzCopy supported identity based file sync--especially with more customers moving to further secure their Storage Account by disabling key-based auth.

**Comment by gapra-msft** [comment]
This should be fixed in 10.20.0. Thanks for your patience while we got the release out!
