### ISSUE TITLE
Feature: Allow Console output configurable

### ISSUE THREAD

**Issue by mstenz** [Azure/azure-storage-azcopy#2185]
Hi, with --log-level parameter you can specifiy how the logfile is written, but the console output is still very detailed. Is there a way to introduce a flag that independant from the logfile control the console output? For example for us it would be beneficial if only some initial information and then the summary is printed, this also should come together with a parameter how often the "status bar" gets refreshed. if you cal azcopy by cron-job and sent console output via email you currently get a very long text.

**Comment by nakulkar-msft** [comment]
Please reopen if this does not work for you. Thanks!

**Comment by mstenz** [comment]
@gapra-msft Thank you for the note. It seems this is a undocumented feature or where can i find the documentation and different values for this paramter? thx.

**Comment by mstenz** [comment]
@gapra-msft I just tried the flag, but it doesn't work: 

`unknown flag: --outputVerbosityRaw`

**Comment by mstenz** [comment]
> Please reopen if this does not work for you. Thanks!

@nakulkar-msft  unfortunately i cannot reopen as this function is not available to me

**Comment by gapra-msft** [comment]
@mstenz sorry about that, I must have read the wrong param. You should be able to set the output verbosity by setting --output-level to quiet. I've pasted the line where we read that param below so you can see the options. 


	rootCmd.PersistentFlags().StringVar(&outputVerbosityRaw, "output-level", "default", "Define the output verbosity. Available levels: essential, quiet.")

**Comment by gapra-msft** [comment]
Let me know if this helps resolve your issue.

**Comment by mstenz** [comment]
Thank you. the "essential" level is exactly what I needed.

**Comment by gapra-msft** [comment]
Awesome, going to go ahead and close this issue again. Feel free to comment and tag us if you have any further problems here.
