### ISSUE TITLE
AzCopy sync re-copies files even if file already exists and is unchanged

### ISSUE THREAD

**Issue by DanRamage** [Azure/azure-storage-azcopy#2187]
### Which version of the AzCopy was used? 
10.8.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Debian Linux

### What command did you run?
azcopy sync --recursive=true --delete-destination=true --mirror-mode=true --preserve-smb-info=true --log-level=INFO 

### What problem was encountered?
Every file is re-copied every time I run the command.

### Have you found a mitigation/solution?
No

SOme things that might be unique to my setup, the source Debian is mounting a NFS drive which is hosted on a Linux based NAS device(Buffalo Terrastation).
What I notice is the Last Modifed Time on in the Azure container seems to get updated to the date/time when the azcopy runs, it's not keeping the source date/time. 

I also tested using --dry-run on a windows server where I mapped the NAS drive and all the files would have been copied over as well.

**Comment by wingfeng** [comment]
remove  --mirror-mode=true or mark it as false,  --mirror-mode=false

**Comment by DanRamage** [comment]
> remove --mirror-mode=true or mark it as false, --mirror-mode=false

That works, thanks for the help.
