### ISSUE TITLE
Delete ingestiondata pst

### ISSUE THREAD

**Issue by bezik46** [Azure/azure-storage-azcopy#2193]
### Which version of the AzCopy was used? 
10.18.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy.exe remove "https://036c89b4a73043 .....

### What problem was encountered?
failed to perform remove command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=403 This request is not authorized to perform this operation using this permission., Details: (none)
   HEAD https://036c89b4a730433185f7f6b.blob.core.windows.net/ingestiondata/AB.pst?se=2023-06-01t13%3A40%3A19z&si=ingestionsasforazcopy202302271129303161&sig=-REDACTED-&sr=c&sv=2015-04-05&timeout=901
   User-Agent: [AzCopy/10.18.1 Azure-Storage/0.15 (go1.19.2; Windows_NT)]
   X-Ms-Client-Request-Id: [8873116e-8754-4f32-73df-f28bbbef51ae]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: [Tue, 02 May 2023 14:26:15 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   Vary: [Origin]
   X-Ms-Client-Request-Id: [8873116e-8754-4f32-73df-f28bbbef51ae]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [e639fc73-201e-0019-7e02-7d4430000000]
   X-Ms-Version: [2020-10-02]

No idea if that has anything to do with azopy or something else in the MS 3ecosystem. The imported pst is supposed to be auto deleted after 30 days
But in my case I finished the import on the **27 March** 2023 but the pst is still there on **02 May** 2023

Seb

**Comment by scerazy** [comment]
NONE whatsoever (at least not by me consciously).
Just importing pst to Exchange online mailbox as per:

https://www.alitajran.com/import-pst-office-365/

**Comment by gapra-msft** [comment]
Unfortunately, there isn't much we can do on the AzCopy side here. I would suggest reaching out to the O365 support team (or whoever is generating the SAS) to determine the permissions on the SAS so we can further help diagnose. AzCopy needs at minimum read and delete permissions to perform a successful remove.

**Comment by gapra-msft** [comment]
Closing this for now, please feel free to reopen once you get further details.
