### ISSUE TITLE
Feature Request - Copy all blob snapshots when doing a blob copy

### ISSUE THREAD

**Issue by justingross-msft** [Azure/azure-storage-azcopy#2195]
It seems that copying blob snapshots is supported as per the Copy Blob API, https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=azure-ad.

We know that the snapshots should be located in https://myaccount.blob.core.windows.net/mycontainer/myblob?snapshot=<DateTime>. Would it be possible to check for snapshots when doing a blob copy and have the program ask whether we would like tc copy all of the available snapshots as well?

**Comment by gapra-msft** [comment]
Hi @jgross-njnc thank you for your feature request. We will discuss as a team if/when we can pick up this request.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
