### ISSUE TITLE
azcopy copy problem with  empty path resources

### ISSUE THREAD

**Issue by xuejinx911** [Azure/azure-storage-azcopy#2204]
### Which version of the AzCopy was used? 
10.18.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy copy 'https://blobjoylearning.blob.core.chinacloudapi.cn/report//mnt/resource/ap/report/%E8%80%83%E8%AF%95%E6%88%90%E7%BB%A9%E6%9F%A5%E8%AF%A2120181121113950.xlsx' 'https://uattest.file.core.chinacloudapi.cn/globalx-file-shares/report//mnt/resource/ap/report/%E8%80%83%E8%AF%95%E6%88%90%E7%BB%A9%E6%9F%A5%E8%AF%A2120181121113950.xlsx' 

### What problem was encountered?
dears
when i execute azcopy copy command to  transfer my resources from blob container to file shares, i got http code 400 failure status.when i changed target path "//" in to "/",then it runs with ok state.
the problem is i run with command to transfer all  my blob resources, the "//" path is auto generated, would you please help to  provide a solution? thanks for your great support.
I have posted the log file below for your reference

### Have you found a mitigation/solution?

[ab4453fe-1223-594f-57a0-9c03345deb65.log](https://github.com/Azure/azure-storage-azcopy/files/11413853/ab4453fe-1223-594f-57a0-9c03345deb65.log)

**Comment by xuejinx911** [comment]
thanks a lot

**Comment by xuejinx911** [comment]
@gapra-msft thanks for your contribution.

**Comment by gapra-msft** [comment]
@xuejinx911 apologies for the lack of comment. I must have missed this. Our suggestion would be to fix the user application that is generating the paths to strip the slashes appropriately before passing it to AzCopy.
