### ISSUE TITLE
Issue with AzCopy sync wrt file sizes

### ISSUE THREAD

**Issue by shubhamsharma156** [Azure/azure-storage-azcopy#2216]
### What problem was encountered? - Even though AZCopy claims that it does not copy files which are currently being written by other tools to target storages, we have seen multiple instances where the tool creates 4 kb ( default size ) files on target side (blob) with a different timestamp than the actual file commit time on source side. This results in the tool skipping those files to sync and results in failed export consistency as there is a difference in file size on source and target side.

We are unable to find a flag which compared the last modified time or the size of the files from source to target so that the sync happens accurately.

**Comment by nakulkar-msft** [comment]
Hi Shubham,
AzCopy cannot modify or set the timestamps on blob storage.  Blob storate does not allow this. The timestamps is the time at which blob was committed.
Also, AzCopy does not claim that we do not copy blobs which are currently being writen by other tools. Again, blob storage does not allow to identify this.

If you are performing sync, and if a file is marked for transfer, we will fire PutBlob or PutBlock calls appropriately. If the source changed, after the copy was done, it would be copied again. AzCopy does not create placeholder blobs.

Can you let us know your usecase a bit more? Is the source being actively changed?

**Comment by shubhamsharma156** [comment]
Hi nakulkar

I agree that azcopy should not set timestamps. I am saying that azcopy in SAP export scenarios, does not compare the last modified time stamp or the size of file on source wrt target to upload the files. This results in us getting partial files on target size which corrupts our import process

**Comment by adreed-msft** [comment]
Hi, @shubhamsharma156!

In our last release, we added a flag to AzCopy Sync, namely `--compare-hash`. This flag instead of comparing LMTs opts to compare the hashes, and if they are mismatched, replaces. This probably could resolve your scenario.

Regards,
Adele

**Comment by markmiddleton908** [comment]
Hi @shubhamsharma156.  Did the --compare-hash flag resolve your issues?  We are experiencing exactly the same issues as you.  However, when I tested the --compare-hash flag, I found it didn't sync ANY source files to the destination, if say just one source file was locked.  In such a case it doesn't copy any source files at all, even those which are unlocked.  I've logged a new issue for this.

**Comment by adreed-msft** [comment]
Oh! Admittedly, I think both me and my colleague misunderstood the scenario. Disregard the --compare-hash response.

We advise users to not be touching the source or destination while AzCopy is running, but I imagine some filtering could be done on files which have an open lock. @markmiddleton908 I'm going to close your other issue and include this in the discussion for next release.

**Comment by shubhamsharma156** [comment]
Hi @adreed-msft 

Could you please let us know as well if there is any ETA on this as we are running critical loads as of right now and a very crucial go live is upcoming in a few days.

Thanks a lot in advance

Regards
Shubham

**Comment by markmiddleton908** [comment]
> Oh! Admittedly, I think both me and my colleague misunderstood the scenario. Disregard the --compare-hash response.
> 
> We advise users to not be touching the source or destination while AzCopy is running, but I imagine some filtering could be done on files which have an open lock. @markmiddleton908 I'm going to close your other issue (since they're the same issue under the hood) and include this in the discussion for next release.

Hi @adreed-msft 

Are they the same issue?  This one concerns uploaded file sizes when running a sync and the recommendation was to run with --compare-hash to resolve that.  So in testing Adele's recommendation and using --compare-hash, I found the other issue below which is:

When running with --compare-hash, it doesn't sync ANY files if one of the source files is locked.  It aborts the whole sync.  This differs to current sync functionality without --compare-hash which will sync all files without a lock and merely ignore the locked ones.  So --compare-hash is breaking current functionality and that was my other issue.

**Comment by adreed-msft** [comment]
Hi, all. I've spoken with the team, and we've decided to not fix this. Our advisory has always been that customers should not mutate any files within the source for the duration of the transfer.
