### ISSUE TITLE
Compare hash option results in no sync of files, if any of the source files are locked

### ISSUE THREAD

**Issue by markmiddleton908** [Azure/azure-storage-azcopy#2220]
### Which version of the AzCopy was used? 

10.18.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

azcopy sync {source} {destination} --recursive=true --compare-hash MD5

### What problem was encountered?

With the --compare-hash option, when syncing from a local source to Azure storage, the entire job fails if a source file is open (and therefore locked) and no files at all are synced to the destination.  This differs to behaviour when NOT using the --compare-hash option, which would still sync all other non-locked files.

### How can we reproduce the problem in the simplest way?

Create a local source folder and copy a number of files to that folder.  Open one file in an application ensuring that file is locked.

Run the command azcopy sync {source} {destination} --recursive=true --compare-hash MD5

See that no files are synced to the destination, not even those files which are unlocked.

### Have you found a mitigation/solution?

No.  The only solution is not to use the --compare-hash switch at all and revert back to the default behaviour of last modified time checking

**Comment by adreed-msft** [comment]
This probably will not be fixed in 10.19 since we're so close to release, but I'll make sure it does in 10.20.
