### ISSUE TITLE
AzCopy 10.18.1 TLS Handshake Timeout on Windows Server 2012 Standard

### ISSUE THREAD

**Issue by shendan19880401** [Azure/azure-storage-azcopy#2227]
##### Note: The version is visible when running AzCopy without any argument
AzcopyVersion  10.18.1

### Which platform are you using? (ex: Windows, Mac, Linux)
server experiencing errors：Microsoft Windows Server 2012 Standard(not azure VM)
server successfully completed ：Microsoft Windows Server 2019 Standard(not azure VM)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
$env:AZCOPY_SPA_CLIENT_SECRET="XXXXXX"
$appId = "YYYYY"
$tenantId = "ZZZZZ"
$env:https_proxy="xx.xx.xx.xx:xxxx"
.\azcopy login --service-principal --application-id $appId --tenant-id $tenantId

$inputForCSV  = "G:\audit\" + $args[0]
$storageAccount = https://XXXX.blob.core.windows.net/YYY/ZZZ/
$outputForCSV = $storageAccount + $date_4HoursAgo + "/"
.\azcopy copy $inputForCSV $outputForCSV --log-level=DEBUG

### What problem was encountered?
When I run the command above on Windows Server 2012 Standard,  there is TLS handshake timeout error.
Here's some relevant output from the logs:

ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, [/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157](mailto:/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157)
HTTP request failed
 
Put [https://tdssynapsedatalake01.blob.core.windows.net/production/temporary/20230426/20230426002715.csv?blockid=MDAwMDBjZ4dKxg1MaXtb%2F1z0H%2BC3MDAwMDAwMDAwMDAwMDA0&comp=block&timeout=901](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftdssynapsedatalake01.blob.core.windows.net%2Fproduction%2Ftemporary%2F20230426%2F20230426002715.csv%3Fblockid%3DMDAwMDBjZ4dKxg1MaXtb%252F1z0H%252BC3MDAwMDAwMDAwMDAwMDA0%26comp%3Dblock%26timeout%3D901&data=05%7C01%7Cv-danshen%40microsoft.com%7Cc9670a9dcab547ade83c08db5b6f4ecf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638204305966904911%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=acudn%2Fq260ciFQzvgD8OHhKTe3YuR%2BNe7llooor%2F4dk%3D&reserved=0): net/http: TLS handshake timeout

### How can we reproduce the problem in the simplest way?
N/A

### Have you found a mitigation/solution?
If I run this same command on other Windows Server 2019 Standard server, AzCopy executes successfully.
I also confirmed if there is low memory, high connection count, firewall block(443), but the issue is still unresolved.

**Comment by siminsavani-msft** [comment]
Since there is a high connection count, could you try setting the environment variable AZCOPY_CONCURRENCY_VALUE to "AUTO" and let us know how that goes.

**Comment by shendan19880401** [comment]
After setting the environment variable AZCOPY_CONCURRENCY_VALUE to "AUTO", the same error displayed.

Base azcopy log, it displays [x509: certificate signed by unknown authority] error after 3rd try to send request, so I think the certificate on the Microsoft Windows Server 2012 Standard device is not OK.

**1st request try：**
2023/05/22 04:32:27 ==> REQUEST/RESPONSE (Try=1/10.0667423s[SLOW >3s], OpTime=10.0667423s) -- REQUEST ERROR
…
Put [https://xxxxxx.blob.core.windows.net/xxx/xx/20230522/20230519132315.csv?timeout=901](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxxxxxx.blob.core.windows.net%2Fxxx%2Fxx%2F20230522%2F20230519132315.csv%3Ftimeout%3D901&data=05%7C01%7Cv-danshen%40microsoft.com%7Cf79679f6af7f4043af8708db60f6e68f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638210385884952050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Eraq%2Fvy7UDbMe6gRpkw22gt%2FMXhBAodj82HKsoJSY78%3D&reserved=0): net/http: **TLS handshake timeout**

**2nd request try：**
2023/05/22 04:32:38 ==> REQUEST/RESPONSE (Try=2/10.0176402s[SLOW >3s], OpTime=21.2780856s) -- REQUEST ERROR
…
Put [https://xxxxxx.blob.core.windows.net/xxx/xx/20230522/20230519132315.csv?timeout=901](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxxxxxx.blob.core.windows.net%2Fxxx%2Fxx%2F20230522%2F20230519132315.csv%3Ftimeout%3D901&data=05%7C01%7Cv-danshen%40microsoft.com%7Cf79679f6af7f4043af8708db60f6e68f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638210385884952050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Eraq%2Fvy7UDbMe6gRpkw22gt%2FMXhBAodj82HKsoJSY78%3D&reserved=0): net/http: **TLS handshake timeout**

**3rd request try：**
2023/05/22 04:32:42 ==> REQUEST/RESPONSE (Try=3/28.9946ms, OpTime=24.8725907s) -- REQUEST ERROR
…
Put [https://xxxxx.blob.core.windows.net/xxx/xxx/20230522/20230519132315.csv?timeout=901](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxxxxx.blob.core.windows.net%2Fxxx%2Fxxx%2F20230522%2F20230519132315.csv%3Ftimeout%3D901&data=05%7C01%7Cv-danshen%40microsoft.com%7Cf79679f6af7f4043af8708db60f6e68f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638210385884952050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P%2F%2FWlOcUXuZejHCFEzpiTEgROZCvxNMbGe8jwKe1CpM%3D&reserved=0): **x509: certificate signed by unknown authority**

**Comment by nakulkar-msft** [comment]
Hi @shendan19880401, this would be an issue with your network config. Please reverify and retry operation.
