### ISSUE TITLE
sync command does not seem to log much info

### ISSUE THREAD

**Issue by williexu** [Azure/azure-storage-azcopy#223]
### Which version of the AzCopy was used? 
10.0.7

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
sync <source> <destination>

### What problem was encountered?
The sync command only logs:
```
2019/02/20 23:52:17 AzcopVersion  10.0.7-Preview
2019/02/20 23:52:17 OS-Environment  windows
2019/02/20 23:52:17 OS-Architecture  amd64
```
Compared to the log from a copy command, there is almost no info. 
Is this a bug or because logging for the sync command just hasn't been worked on? or is this by design? 

### How can we reproduce the problem in the simplest way?
Run a sync command

**Comment by zezha-msft** [comment]
Hi @williexu, the default logging level for sync is WARNING(can be seen with `./azcopy sync --help`). Please set it to INFO if you'd like to see more detailed information.

**Comment by williexu** [comment]
@zezha-msft why the different logging levels for each command? Logging level seems like something that would be a global flag/configuration.

**Comment by zezha-msft** [comment]
@williexu I will make the default level consistent.
