### ISSUE TITLE
Unable to transfer from file share to blob container with only create permissions at the source

### ISSUE THREAD

**Issue by MRayermannMSFT** [Azure/azure-storage-azcopy#2234]
##### Note: The version is visible when running AzCopy without any argument

10.18.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

`copy https://xxxxxxxxxxxxxx.file.core.windows.net/xxxxx/xxxxx/xxxxx.mp4?se=2023-06-02t17%3A06%3A57z&sig=-REDACTED-&sp=rl&sr=s&st=2023-05-26t17%3A06%3A57z&sv=2022-11-02 https://xxxxxxxxxxxxxx.blob.core.windows.net/xxxxx/xxxxx/xxxxx.mp4?se=2024-05-19t15%3A52%3A00z&sig=-REDACTED-&sp=rcl&sr=c&st=2022-05-18t15%3A52%3A00z&sv=2021-10-04 --output-type=json --cancel-from-stdin --overwrite=prompt --from-to=FileBlob --s2s-preserve-access-tier=false --check-length=true --block-size-mb=999999 --include-directory-stub=false --s2s-preserve-blob-tags=false --recursive --log-level=DEBUG`

### What problem was encountered?

AzCopy tried to do a put block request, which failed because my destination SAS only has `create` permission. It should have done a put blob request, with the source contents as the body of the blob. That way the transfer would be done in a single request/create call.

### How can we reproduce the problem in the simplest way?

1. Have a file share with a file
2. Have a blob container without that file
3. Copy the file to the blob container, where the blob container authorization comes from a SAS with `create` but not `write` permissions, use the `--block-size-mb` flag to force a single block for the blob.

### Have you found a mitigation/solution?

Download the file and then reupload.

**Comment by nakulkar-msft** [comment]
Also document what API/Permissions are required for azcopy to operate.

**Comment by gapra-msft** [comment]
This should be fixed in 10.20.0.

**Comment by MRayermannMSFT** [comment]
Confirmed as fixed. Thanks!
