### ISSUE TITLE
Confirmation of log save destination

### ISSUE THREAD

**Issue by furuta17** [Azure/azure-storage-azcopy#2236]
##### Note: The version is visible when running AzCopy without any argument
10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Could you please inform me where the logs are stored when azcopy is executed?
I am aware that they are typically outputted under the './azcopy' directory.

**Comment by siminsavani-msft** [comment]
Hi @furuta17 ! It should be under `$HOME$\.azcopy` in Linux. Please view this document for additional information: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#log-and-plan-files
