### ISSUE TITLE
Edge warns about azcopy's ZIP file: azcopy_windows_amd64_10.19.0.zip isn't commonly downloaded

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-storage-azcopy#2241]
### Which version of the AzCopy was used? 

Any version.

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What problem was encountered?
When downloading azcopy with Edge, Edge warns 

> azcopy_windows_amd64_10.19.0.zip isn't commonly downloaded. Make sure you trust azcopy_windows_amd64_10.19.0.zip before you open it.

### How can we reproduce the problem in the simplest way?
Download https://aka.ms/downloadazcopy-v10-windows with Edge.

### Have you found a mitigation/solution?
I have to click my mouse 5 times for Edge to keep it, which is truly tedious.

![image](https://github.com/Azure/azure-storage-azcopy/assets/4003950/0aa699ea-6587-4f84-83a9-c7a016796946)

Google Chrome on the other hand doesn't warn anything and downloads it successfully:

![image](https://github.com/Azure/azure-storage-azcopy/assets/4003950/02e5fb11-5efa-4d72-93be-c7bd064ec8ca)

I understand this may not be azcopy's duty to fix it, but I just want to create this issue for tracking purpose.

**Comment by schoag-msft** [comment]
@jiasli We've flagged this with the Defender Smartscreen team and it appears to be resolved. Can you confirm that you're no longer seeing the warning?

**Comment by siminsavani-msft** [comment]
Hi! This should be resolved now, but if the issue persists please let us know!
