### ISSUE TITLE
AzCopy copy command is waiting most of the time

### ISSUE THREAD

**Issue by bharat149** [Azure/azure-storage-azcopy#2243]
azcopy 10.18.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy copy command from s3 to azure
### What problem was encountered?
We are migrating 3TB blobs data from S3 to azure. For that we are passing the azure bucket to the source . Now as per the optimisation per AZ copy we have enable overwrite=ifSourceNewer Since the data migration is happening for the first time.
Also we have update the AZCOPY_CONCURRENCY_VALUE=1000 Since this is cloud to cloud migration

But still we are getting printed in the LOG :  100.0 %, 30000 Done, 0 Failed, 0 Pending, 0 Skipped, 30000 Total (scanning...),  

### How can we reproduce the problem in the simplest way?
azcopy copy SourceS3 destinationAazure

### Have you found a mitigation/solution?
We need to decrease the azcopy time .For that we try to run bechmarking also but failing in that . What are the suitable optimisations we can pass to azcopy to migration 3TB blobs

**Comment by siminsavani-msft** [comment]
Hi @bharat149 ! Please take a look at the suggestions in our wiki: https://github.com/Azure/azure-storage-azcopy/wiki/Performance:-large-files-on-Linux and https://github.com/Azure/azure-storage-azcopy/wiki/Performance:-Large-files-in-general. 

Feel free to reopen this issue if the issue still persists!

**Comment by bharat149** [comment]
We are not passing any file . We are passing the S3 bucket directly.If the overwrite=ifSourceNewer is set then it is showing pending in the Logs.
But if we set overwrite=False then this logs are not coming.
But in the wiki [0] part It is mention to set overwrite=ifSourceNewer

[0] https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize

**Comment by siminsavani-msft** [comment]
I see! Using `-overwrite=IfSourceNewer` should help. I saw that you created another issue with running `azcopy bench`, hopefully this will provide some more information.

**Comment by bharat149** [comment]
Any update on the issue

**Comment by bharat149** [comment]
Hi Team Any update why -overwrite=IfSourceNewer is slow

**Comment by nakulkar-msft** [comment]
Hi @bharat149, when overwrite is set to values other than true, azcopy has to query the destination to confirm existence of the destination file. When you have a large number of blobs, this almost makes two times the nework calls, and thus the overhead.

**Comment by bharat149** [comment]
Thanks @nakulkar-msft for the update. Just one point to confirm since we are doing first time migration and we have set overwrite=false in that okay or should be set this to false

**Comment by gapra-msft** [comment]
Hi @bharat149 do you have any further questions about your migration? are we able to close this issue?
