### ISSUE TITLE
Azcopy list command doesn't return any properties on Azure Files 

### ISSUE THREAD

**Issue by sameeraman** [Azure/azure-storage-azcopy#2257]
### Which version of the AzCopy was used? 
azcopy version 10.19.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Tested in Windows X64 and MacOS ARM64 - Both had the same behaviour

### What command did you run?
azcopy list https://<azure files storage account name>.file.core.windows.net/?<sas token> --properties LastModifiedTime

### What problem was encountered?
The outputs didn't have any properties included. In the above example command LastModifiedTime was returned as "0001-01-01 00:00:00 +0000 UTC" for all files. See the screenshots below. 

Windows x64
![image](https://github.com/Azure/azure-storage-azcopy/assets/18417281/ad84b5b2-6e0b-450b-a565-b83063b21c75)

ARM64
![image](https://github.com/Azure/azure-storage-azcopy/assets/18417281/2ec5211a-962c-46d0-b6ad-3228bc4737c1)

### How can we reproduce the problem in the simplest way?
Create a storage account with Azure Files. Upload some files in to a Azure Files container. Run the above command with a SAS Token

### Have you found a mitigation/solution?
No.

**Comment by nakulkar-msft** [comment]
Fixed in 10.20.1
