### ISSUE TITLE
az copy incorrectly double encodes forward slash

### ISSUE THREAD

**Issue by janhurst** [Azure/azure-storage-azcopy#2269]
### Which version of the AzCopy was used? 
10.19.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
`azcopy cp <uri> <uri> --recursive --overwrite true`
### What problem was encountered?
I am copying a partitioned Parquet dataset from one storage account to another. My partition names have a encoded "/" in them e.g. `<storageaccount>/<container>/my_dir/key=foo%2Fbar/...`

When I try to use azcopy between storage accounts the source file is double encoding the %2F  and enumerating `<storageaccount>/<container>/my_dir/key=foo%252Fbar/...` as a source item, which subsequently fails with a 404 Not Found.

### How can we reproduce the problem in the simplest way?
Create a blob in a folder with `%2F` in the name, then `azcopy cp` from that storage account to another storage account

### Have you found a mitigation/solution?
Not really. I am using `az sync ...` to copy from my local machine to a storage account in my closest Azure data center. I am then trying to sync from that storage account to another storage account in a distant Azure datacenter. I can just copy from my local machine to both locations but this is becoming prohibitively slow

**Comment by vibhansa-msft** [comment]
When you create a file with '%2F' in name, '%' appears as a character and for any REST call this '%' itself will be encoded hence '%2F' becomes '%252F'. If you wish a '/' to appear in the name it shall not be encoded this way.

**Comment by janhurst** [comment]
I have a requirement for the directory/folder name to have '%2F' in it. I can `az sync` a local folder with such a name into a container and access it from clients as expected.

Running `az copy` from one storage container to another when the '%2F' is in the folder name fails, which I don't believe should happen.

**Comment by gapra-msft** [comment]
Hi @janhurst, 

I just replicated your scenario and was unable to reproduce the issue you are seeing. I created a source container with a file under mydir/key=foo%2Fbar. When i ran azcopy copy from one container to another, I see the same directory structure. Could you please further describe the incorrect behavior you are experiencing?
