### ISSUE TITLE
Not able to build azcopy on AIX.

### ISSUE THREAD

**Issue by RajanGahlout** [Azure/azure-storage-azcopy#2281]
### Which platform are you using? (ex: Windows, Mac, Linux)
We are trying to build on AIX OS: 
# go version
go version go1.20.4 aix/ppc64

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
# go build main_unix.go

### What problem was encountered?
We are getting below issue while running go build command:
bash# go build main_unix.go
# github.com/Azure/azure-storage-file-go/azfile
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:112:7: undefined: mmf
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:114:12: undefined: newMMF
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:251:7: undefined: mmf
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:253:12: undefined: newMMF

### How can we reproduce the problem in the simplest way?
While runing below command:
bash-5.1# go build main_unix.go

### Have you found a mitigation/solution?
No.
[az copy on AIX.txt](https://github.com
[az copy on AIX.txt](https://github.com/Azure/azure-storage-azcopy/files/11933515/az.copy.on.AIX.txt)
/Azure/azure-storage-azcopy/files/11933494/az.copy.on.AIX.txt)

**Comment by siminsavani-msft** [comment]
Hi @RajanGahlout ! We do not support AIX. Please try using AzCopy on a supported OS.
