### ISSUE TITLE
Support for listing blob metadata?

### ISSUE THREAD

**Issue by badbob001** [Azure/azure-storage-azcopy#2282]
Is there a way for "azcopy list" to include showing the metadata for each blob? It is possible to set the metadata but there doesn't seem to be a way to "get" it.

The plan is for each storage account blob to have metadata to store the last modified time. Then after I download all blobs with "azcopy copy", I want to use "azcopy list" to view the metadata of each file and use a separate app/script to modified the last modified time of the files to match the associated metadata. I'm on windows so --preserve-posix-properties would not help.

Perhaps "azcopy list" is not even a high priority feature given how machine-unfriendly the output is.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
