### ISSUE TITLE
Supportability of Dell's ECS (S3 Object supportability) as Source

### ISSUE THREAD

**Issue by nellaivijay** [Azure/azure-storage-azcopy#2283]
##### Note: The version is visible when running AzCopy without any argument
10.19.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (RedHat/Oracle Enterprise Linux)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Configured S3 access key id and secret access key as environment variables
(AWS_ACCESS_KEY_ID) (AWS_SECRET_ACCESS_KEY)
./azcopy copy 'https://cloudstorage.onefs.dell.com/adls_poc/ecs_to_adls/sample.parquet' 'https://scusirisstoragepoc.blob.core.windows.net/dsccontainereddpoc/aztestlanding/<sas_token>'

### What problem was encountered?
The source is not recognized as an S3 bucket. Error messages indicate that the source is treated as a local file:

> failed to perform copy command due to error: cannot start job due to error: failed to scan path:/home/roopa_kommisetti/https:/cloudstorage.onefs.dell.com/adls_poc/ecs_to_adls/sample.parquet

Tried azcopy command with –from-to flag
./azcopy copy 'https://xyz.onefs.abc.com/adls_poc/ecs_to_adls/sample.parquet' 'https://xyz.blob.core.windows.net/ghj/aztestlanding/<sas_token> '  --from-to S3Blob

The Source is now treated as S3, but an error message indicates that invalid s3 URL.
Invalid S3 URL. AzCopy supports standard virtual-hosted-style or path-style URLs defined by AWS, e.g., https://bucket.s3.amazonaws.com or https://s3.amazonaws.com/bucket

### How can we reproduce the problem in the simplest way?
Replace azcopy copy command with an Amazon AWS S3 bucket as source to DELL ECS S3 bucket ('https://xyz.onefs.abc.com). Instead of getting an error message about failed authentication or bucket is not found at, the error will be about not finding a local file.

### Have you found a mitigation/solution?
No

**Comment by siminsavani-msft** [comment]
This is an unsupported scenario. AzCopy contains an explicit check and we only support S3 - *not* S3 compatible sources.
