### ISSUE TITLE
Is AzCopy.exe distributed through a nuget package? 

### ISSUE THREAD

**Issue by SivarudrappaMahesh** [Azure/azure-storage-azcopy#2288]
### Which version of the AzCopy was used? 
any/latest Version
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows, Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
NA

### What problem was encountered?
Need a way to get AzCopy as a Nuget Package so that the tool can be integrated into our build/release process. 

### How can we reproduce the problem in the simplest way?
NA

### Have you found a mitigation/solution?
Use AzCopy.exe directly, which is not a desirable solution.

**Comment by siminsavani-msft** [comment]
AzCopy is not distributed through a nuget package. 

Please checkout the following resources to fit your build/release process: 
1. https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#use-in-a-script 
3. https://github.com/marketplace/actions/install-azcopy
