### ISSUE TITLE
Windows Task Scheduler Issue and Resolution

### ISSUE THREAD

**Issue by DanRamage** [Azure/azure-storage-azcopy#2291]
### Which version of the AzCopy was used? 
10.18.12023

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`
         azcopy sync --recursive=true --delete-destination=true --mirror-mode=false --preserve-smb-info=true --log-level=DEBUG <source directory> <destination storage blob>
 
`

### What problem was encountered?
I kept seeing an error in the log:
`
2023/06/15 07:00:00 AzcopyVersion  10.18.1
2023/06/15 07:00:00 OS-Environment  windows
2023/06/15 07:00:00 OS-Architecture  amd64
2023/06/15 07:00:00 Log times are in UTC. Local time is 15 Jun 2023 07:00:00
2023/06/15 07:00:00 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2023-06-15T06:59:55Z or --include-after=2023-06-15T06:59:55Z

`
### Have you found a mitigation/solution?
Yes, that's what this issue is really about in case someone else runs into this. The log message above just led me nowhere. It's misleading since I thought it could see the files and was complaining about timestamps when in reality it was not able to connect at all.
I'm running AzCopy on a Windows server to sync files from a NAS to an Azure cold storage blob. The command above ran fine from the powershell command line, but I it scheduled in Task Scheduler to run once an hour. I kept getting the error above. I was using a UNC path: \\ip-to-my-nas\directory-to-sync for AzCopy. That path exists in my environment because I'd connected to it, however in the task scheduler shell, it doesn't exist. I solved this by using New-PSDrive to connect to the NAS using a credential file, basically mapping the drive, AzCopy sync, then I unmap.

I'm happy to share this script if anyone else is trying to do something similar.

**Comment by nakulkar-msft** [comment]
Hi @DanRamage, This is not an error log. It is a help statement, and implies what it says. 
"to copy files that changed before or after this job started, use the parameter --include-before=2023-06-15T06:59:55Z or --include-after=2023-06-15T06:59:55Z"

When you run next run of azcopy, to copy files ... use the param.. 
Can you let us know how would you reword this?

**Comment by nakulkar-msft** [comment]
Reopen with details.

**Comment by DanRamage** [comment]
I understand that it is an informational message now. However, I think the conditions that caused it are maybe a unique situation.  I think the issue was I was using a UNC path in a scheduled task. I think the shell spawned in that task did not have access to the UNC path, my solution was to create a mapped drive in the script before the AzCopy command.
