### ISSUE TITLE
Request: Support for oauth tokens to authenticate source and destination 

### ISSUE THREAD

**Issue by SivarudrappaMahesh** [Azure/azure-storage-azcopy#2296]
### Which version of the AzCopy was used? 
Latest
### Which platform are you using? (ex: Windows, Mac, Linux)
WIndows, Linux

### What problem was encountered?

AzCopy supports user auth through az login, which requires user credentials. Would it be possible to add support for source/destination auth using user oauth tokens? this would be super helpful in integrating azcopy in other service workflows. 

### How can we reproduce the problem in the simplest way?
NA
### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
This is supported starting 10.15. If the source and destination happen to be on same tenant, the token will be forwarded to source.
