### ISSUE TITLE
--skip-version-check option doesn't work with azcopy login

### ISSUE THREAD

**Issue by atakadams** [Azure/azure-storage-azcopy#2299]
##### Note: The version is visible when running AzCopy without any argument

10.19.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy login --skip-version-check --service-principal --application-id <application-id> --tenant-id <tenant-id>

### What problem was encountered?
Version check (access to azcopyvnextrelease.blob.core.windows.net) observed during successful azcopy-login execution, while the option "--skip-version-check" is expected to suppress the version check.

### How can we reproduce the problem in the simplest way?
1. Create service principal and keep your appId, password and tenant in the result.
    az ad sp create-for-rbac -n <SP-name>

2. store the password into AZCOPY_SPA_CLIENT_SECRET

3. Try azcopy login while running packet capture or any other methods to monitor network connections.
  azcopy login --skip-version-check --service-principal --application-id <application-id> --tenant-id <tenant-id>

### Have you found a mitigation/solution?

The PR #1950 introduced "--skip-version-check" option, which sets azcopySkipVersionCheck to skip beginDetectNewVersion() in rootCmd().

https://github.com/Azure/azure-storage-azcopy/blob/c78f86cce616bb0eb90686b605bd3ab4c875ab05/cmd/root.go#L155

However, there are another calls to beginDetectNewVersion() in Execute(), which is said to be effective in login/logout/help cases.

https://github.com/Azure/azure-storage-azcopy/blob/c78f86cce616bb0eb90686b605bd3ab4c875ab05/cmd/root.go#L198

I believe we also need to check azcopySkipVersionCheck flag in Execute() and skip beginDetectNewVersion() if the flag is set.

**Comment by siminsavani-msft** [comment]
Hi @atakadams ! I was able to repro this issue. We will work on getting a fix out for this soon. Thank you!

**Comment by gapra-msft** [comment]
This should be fixed in 10.20.0. Thanks for your patience while we got the release out!
