### ISSUE TITLE
Install error on AIX

### ISSUE THREAD

**Issue by ravi-kumar81** [Azure/azure-storage-azcopy#2300]
### Which version of the AzCopy was used? 
azure-storage-azcopy-10.19.0

### Which platform are you using? (ex: Windows, Mac, Linux)
AIX

### What command did you run?
# go build
# github.com/Azure/azure-storage-file-go/azfile
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:112:7: undefined: mmf
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:114:12: undefined: newMMF
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:251:7: undefined: mmf
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:253:12: undefined: newMMF

# go env
GO111MODULE=""
GOARCH="ppc64"
GOBIN=""
GOCACHE="/.cache/go-build"
GOENV="/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="ppc64"
GOHOSTOS="aix"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="aix"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/freeware/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/freeware/lib/golang/pkg/tool/aix_ppc64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="/opt/freeware/bin/gccgo"
GOPPC64="power8"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/azure-storage-azcopy-10.19.0/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -maix64 -pthread -mcmodel=large -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1703029050=/tmp/go-build -gno-record-gcc-switches"

### What problem was encountered?
Getting below error while building on AIX:
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:112:7: undefined: mmf
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:114:12: undefined: newMMF
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:251:7: undefined: mmf
/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/highlevel.go:253:12: undefined: newMMF

### How can we reproduce the problem in the simplest way?
Try building on AIX
### Have you found a mitigation/solution?
No

**Comment by ravi-kumar81** [comment]
I know that AzCopy is not supported for AIX. 
But can we have a work around for the above error or why this above error occurs?
Can someone help me fixing this above error so I can try to build on AIX.

**Comment by vibhansa-msft** [comment]
This error points that Go lang's memory mapping APIs are not supported on AIX. Are you on latest Go lang version? If so, it might be just not supported by Go lang itself.

**Comment by nakulkar-msft** [comment]
Hi @ravi-kumar81, we've added this to our backlog. However, please be aware that this would be a low priority item, and it would be a while before team gets here.
