### ISSUE TITLE
Azcopy Azure Files managed identity authentication support.

### ISSUE THREAD

**Issue by sameeraman** [Azure/azure-storage-azcopy#2302]
### Which version of the AzCopy was used? 
azcopy version 10.19.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
After authenticating to the azcopy using managed identity, ran the following command. 

```
.\azcopy.exe login --identity
.\azcopy.exe login status
.\azcopy.exe list "https://xxxx.file.core.windows.net/container1"
```

![image](https://github.com/Azure/azure-storage-azcopy/assets/18417281/ef3c61c3-f115-4a31-a103-72a9cdd189ca)

### What problem was encountered?
Receiving error message: "Azure file requires a SAS token for authentication" . Requesting support for Managed Identity authentication in Azcopy. 

### How can we reproduce the problem in the simplest way?
Run the above commands

### Have you found a mitigation/solution?
Alternate option is to use the SAS Token. But ideally it should support managed Identity authentication.

**Comment by gapra-msft** [comment]
Hi @sameeraman This item is already on our radar and we hope to add support for this as soon as we can.

**Comment by gapra-msft** [comment]
Closing this for now as our next release will support Files managed identity due to the merge of the above PR.
