### ISSUE TITLE
Support for login with federated identity token 

### ISSUE THREAD

**Issue by TheKangaroo** [Azure/azure-storage-azcopy#2303]
### Which version of the AzCopy was used? 
azcopy version 10.19.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac/Linux

### What command did you run?
I am trying to use a managed identity with a federated identity token from our gitlab pipeline. This works fine with az cli, but does not seem to be implemented in azcopy.
azcopy login --service-principal --identity-client-id<client_id>  --tenant-id <tenant_id> --federated-token $TOKEN

### What problem was encountered?
azcopy responds with `unknown flag: --federated-token`.

### How can we reproduce the problem in the simplest way?
This is always reproducible by running the command above.

### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
AzIdentity package which is integrated in AzCopy as of now does not support fedrated tokens. There is an effort going on to integrate latest track-2 SDK in AzCopy which also brings latest AzIdentity package and once that is done, we can take this feature-request.

**Comment by sugibuchi** [comment]
> AzIdentity package which is integrated in AzCopy as of now does not support fedrated tokens.

Is this still the case? Other issues with"track 2 migration" tag have closed. This issue is the only remaining issue with this tag.

**Comment by gapra-msft** [comment]
@nakulkar-msft is this issue now resolved with the addition of the AZCLI and PWSH oauth options? Could you please take a look.

**Comment by jluongh** [comment]
@nakulkar-msft do you have any updates on the support for federated identity?

**Comment by nakulkar-msft** [comment]
> @nakulkar-msft do you have any updates on the support for federated identity?

Check this documentation to use AzCLI/Powershell credentials with azcopy 
https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-with-azure-cli

You can login to azcli federated credential using command 
az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID

**Comment by LukaszRacon** [comment]
Using AzCli in containers adds unnecessary dependencies and increases image size by at least 700MB (mcr.microsoft.com/azure-cli).

**Comment by sugibuchi** [comment]
As we reported in https://github.com/Azure/azure-storage-azcopy/issues/2112#issuecomment-1724059919, the federated identity token (AAD workload identity) is the official and the only way to use managed identities in AKS Kubernetes cluster. 

If we have to use Azure CLI to use azcopy with workload identities, we need to embed AzureCLI in every Docker image of pods which use azcopy. It will significantly increase the sizes of our Docker images. The proposed workaround using AzureCLI is clearly not a preferable solution.

**Comment by adam-richardson-openai** [comment]
Hi there. Is it certain that `AZCLI` authentication actually works with federated identity? Are there additional setup steps or limitations that may not be documented?

I am implementing a GitHub Actions workflow that (successfully) authenticates using the `az` CLI via federated identity via https://github.com/marketplace/actions/azure-login. In a subsequent step of the workflow that invokes `azcopy`, I observe:
```
Failed to perform Auto-login: AzureCLICredential: WARNING: Could not retrieve credential from local cache for service principal *** under tenant common. Trying credential under tenant <redacted>, assuming that is an app credential.
ERROR: AADSTS700016: Application with identifier '***' was not found in the directory 'Microsoft'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. Trace ID: <redacted> Correlation ID: <redacted> Timestamp: 2024-01-31 21:54:42Z
```
The same script runs just fine on my local machine after authenticating with `az login`. Moreover, a previous version of the script that used `az blob upload file` instead of `azcopy` also worked just fine in Github Actions after authenticating with `az login`.

**Comment by adam-richardson-openai** [comment]
As it turned out, I simply needed to explicitly specify the `AZCOPY_TENANT_ID` environment variable when invoking `azcopy`. (Maybe this still merits an update to the docs? It's not 100% clear why/when this would be necessary)

**Comment by gapra-msft** [comment]
Hi everyone, it looks like there are a few issues tracking the same work item. We are tracking adding support to AzCopy for workload identity [here](https://github.com/Azure/azure-storage-azcopy/issues/2545). Please subscribe to that issue for updates.

**Comment by Kaloszer** [comment]
@adam-richardson-openai

Could you share a snippet of what you're doing - I seem to be stuck and unable to replicate what you mean exactly :D.
Are you using bash or the pwsh shell?

**Comment by snoa93** [comment]
I got it working in Github Actions using a federated identity token:
```
permissions:
  id-token: write
  contents: read
```

```
- name: Az Login
  uses: azure/login@v2
  with:
    client-id: ${{ secrets.AZ_CLIENT_ID }}
    tenant-id: ${{ secrets.AZ_TENANT_ID }}
    subscription-id: ${{ env.AZ_SUBSCRIPTION_ID }}
```

```
 - name: Copy
   run: 
      export AZCOPY_AUTO_LOGIN_TYPE=AZCLI &&
      export AZCOPY_CLIENT_ID=${{ secrets.AZ_CLIENT_ID }} &&
      export AZCOPY_TENANT_ID=${{ secrets.AZ_TENANT_ID }} &&
      azcopy copy '${{ github.workspace }}/dir/*' 'https://example.blob.core.windows.net/artifacts/dir' --recursive=true            
```
