### ISSUE TITLE
How to run Azcopy v10 copy command using .Net Process and exit when download complete

### ISSUE THREAD

**Issue by softnado** [Azure/azure-storage-azcopy#2311]
##### Note: The version is visible when running AzCopy without any argument
10.19.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Using .Net Process Start commandline execution
azcopy copy <SASURL> <Local>
### What problem was encountered?
Expect the azcopy download the file then exit the command but it seems directly exit. Is there any flags to force exit after the current job finish?

**Comment by siminsavani-msft** [comment]
AzCopy exits after the transfer is completed so there is no need for a force exit flag.
