### ISSUE TITLE
v.minor error response issues

### ISSUE THREAD

**Issue by SimonTiz** [Azure/azure-storage-azcopy#2318]
v10.19.0
Windows

a blobstorage SAS authenticated   list request

Got
 ===== RESPONSE ERROR (ServiceCode=InvalidResourceName) =====
Description=The specifed resource name contains invalid characters

2 minor points:
  A.  caused by case sensitivity in url 'path' ;  however as characters are valid characters for a path but not present in this instance,  a more accurate error message please
 B.  'specifed'  typo in error message (lacking second 'i').

_#poss RFC - I've not noticed any flag/option or config setting to 'go case insensitive' , can understand that given variant nature of environments possibly not worth it, but a means to request to 'ignore' case  might be nice._

**Comment by gapra-msft** [comment]
Hi @SimonTiz, this actually looks like a suggestion for the Azure Storage Service, please feel free to create an Azure Support Ticket or participate in the [Azure Support Forum](https://azure.microsoft.com/en-us/support/community/). 

Closing this as it is not an AzCopy issue.
