### ISSUE TITLE
V10.0.7 azcopy sync takes a long time to copy last few files

### ISSUE THREAD

**Issue by Kapanther** [Azure/azure-storage-azcopy#232]
Running AZCOPY V10.0.7 (possibly you have correct in 10.0.8 but here goes)

It seems the AZCOPY sync command is really quick except for the last 10-20 files. It seems to jsut freak out and only copying them very very slowly.

![image](https://user-images.githubusercontent.com/12637127/53253781-bf97a600-370d-11e9-8be5-a74879b1d180.png)

**Comment by JohnRusk** [comment]
@Kapanther Was this an upload or a download?

**Comment by Kapanther** [comment]
Was a download.  From blob to local

**Comment by Kapanther** [comment]
Ill see if the behavious is in 10.0 8

**Comment by JohnRusk** [comment]
Thanks.  In theory, the issue should be fixed, since in 1.0.0.8 we fixed the only _known_ cause of that problem.  Will be interesting to hear what you observe.

**Comment by Kapanther** [comment]
@johnrusk just to confirm this issue is resolved by 10.0.8.  Thanks guys.  No delay at all now.

**Comment by Kapanther** [comment]
@JohnRusk @zezha-msft 

Guys not sure what happened in 10.0.9 but this is now back again. 10.0.8 definitely had this fixed.

I have tested in both 'copy' and 'sync' and both seem to just timeout and not copy anything for last 10-200 files.

Any ideas?

![image](https://user-images.githubusercontent.com/12637127/56203676-0a3bfb80-6089-11e9-8615-854f5164e6f7.png)

**Comment by JohnRusk** [comment]
Hi @Kapanther .  Sometimes behavior like that can vary from one run to the next.  But 10.0.8 and 10.0.9 are both supposed to take actions to spot the variations in behaviour and remedy them.  It looks like that didn't happen fo you.  Would you be able to send us the log file from the 10.0.9 run?  They log files can be found in the %USERPROFILE%\.azcopy directory on Windows.

BTW, log files contain file names, but any SAS tokens used for authentication are redacted and so are not present in the log.

**Comment by JohnRusk** [comment]
PS. You can email the (zipped) log to us if desired.  Most of us on the team have our real email addresses in our profiles.

**Comment by JohnRusk** [comment]
@Kapanther Also, if sending a log is not convenient, you can extract just the performance info from the log, and that will probably give us enough to go on. To do so, use PowerShell like this (but replace the log file name with the name of your log file, in %USERPROFILE%\\.AzCopy directory).

`select-string .\858ebb30-4796-914f-632e-dc355cda0e1c.log -Pattern "PERF" | Out-File perfLines.txt`

The above extracts all the performance info into a file named perfLines.txt.

**Comment by zezha-msft** [comment]
Hi @Kapanther please give the GA version (10.1.0) a try. Thanks!

**Comment by JohnRusk** [comment]
@Kapanther, I'm about to close this, since we've had no reports of this in the GA version. If you'd like to re-open it, please let us know.
