### ISSUE TITLE
azcopy 10.20.0 new dependency introduced

### ISSUE THREAD

**Issue by AlexeyMinasyan** [Azure/azure-storage-azcopy#2320]
### Which version of the AzCopy was used? 
10.20.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Alpine based images e.g **mcr.microsoft.com/azure-cli:2.47.0**
### What command did you run?
azcopy

### What problem was encountered?
Error loading shared library libresolv.so.2: No such file or directory (needed by ./azcopy)
Error relocating ./azcopy: __res_search: symbol not found
Error relocating ./azcopy: __vfprintf_chk: symbol not found
Error relocating ./azcopy: __fprintf_chk: symbol not found

### How can we reproduce the problem in the simplest way?
Download and execute azcopy in mentioned platform

### Have you found a mitigation/solution?
Seems like new dependency introduced. Installing **gcompat** resolves the issue.

Wondering if I've skipped an announcement somewhere. Would be good to have this documented in a changelog or in portal

**Comment by renrutsirhc** [comment]
I had this issue this morning running a bicep deployment script that uses azcopy. Deployment scripts run on alpine linux which is missing libresolv.so.2. In my case, the solution was to install gcompat and also make a symlink as suggested in this thread https://github.com/gohugoio/hugo/issues/10839

    apk update
    apk add gcompat
    ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2

**Comment by somanwal** [comment]
> I had this issue this morning running a bicep deployment script that uses azcopy. Deployment scripts run on alpine linux which is missing libresolv.so.2. In my case, the solution was to install gcompat and also make a symlink as suggested in this thread [gohugoio/hugo#10839](https://github.com/gohugoio/hugo/issues/10839)
> 
> ```
> apk update
> apk add gcompat
> ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
> ```

After this also it's not working. I am getting following error:

`/usr/bin/azcopy: Not a valid dynamic program`

**Comment by qrzychu** [comment]
we also noticed that our job in Gitlab CI that uses azcopy fails, we install following packages to make it work:

```
apk add gcompat libc6-compat ca-certificates libstdc++
```

I'm not sure you really need all of them, but I don't want to spend moret ime on trial&error to make this list shorter

btw, it seems like the reason is that latest Go compiler changed default behaviour. It would be nice to maybe use the flag for static linking to make it easier to run

**Comment by nakulkar-msft** [comment]
Please upgrade 10.20.1
