### ISSUE TITLE
Simple copy and paste between different storage accounts fails

### ISSUE THREAD

**Issue by bakoontz2** [Azure/azure-storage-azcopy#2327]
##### Note: The version is visible when running AzCopy without any argument
10.19.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
```
$ ./azcopy.exe copy "https://corp.file.core.windows.net/cor-p/nfs/npportal_ncprd/apps/sched/bin/test.sh?sv=2022-11-02&st=2023-07-20T18%3A15%3A53Z&se=2023-07-27T18%3A15%3
A53Z&sr=s&sp=rl&sig=-REDACTED-" "https://cors.file.core.windows.net/cor-s/nfs/npportal_ncstg/apps/sched/bin/test.sh?sv=2022-11-0
2&se=2023-08-19T18%3A31%3A17Z&sr=s&sp=rwl&sig=-REDACTED-" --overwrite=prompt --from-to=FileFile --preserve-smb-info=true --recursive --log-level=INFO --trailing-dot=Enabl
e;
```
### What problem was encountered?
Transfer was canceled
### How can we reproduce the problem in the simplest way?
Create two fileshares in two separate storage accounts.  Attempt to copy a file between the two storage accounts.
### Have you found a mitigation/solution?
Copy to local machine first, then copy to remote storage account (I presume this is what azcopy does?)

Please see https://github.com/microsoft/AzureStorageExplorer/issues/7078 for complete command-line logs.

**Comment by nakulkar-msft** [comment]
Hi @bakoontz2, if you have firewall on source, this copy would not work. In that case, enable private endpoint for souce and destination in the same vnet.

**Comment by bakoontz2** [comment]
I'm a bit confused by your response.

> Copy to local machine first, then copy to remote storage account (I presume this is what azcopy does?)

If this works, then how can a firewall issue be at fault here?  Clearly there is no firewall issue if I'm able to do an azcopy download followed by an azcopy upload?

**Comment by MRayermannMSFT** [comment]
> If this works, then how can a firewall issue be at fault here? Clearly there is no firewall issue if I'm able to do an azcopy download followed by an azcopy upload?

The copy from storage account to storage account is all happening on the server side. Thus depending on how your firewall/s are configured for each account, they may not be able to talk to each other.

Whether or not you can download and uplooad depends on if your firewall/s are configured such that your local machine can talk to each storage account.

Does that make sense?

**Comment by bakoontz2** [comment]
Ah, so azcopy isn't splitting the operation into two separate actions.  Yes, that makes sense.  Will check to see if that is the case.  Thanks for the clarification.

**Comment by bakoontz2** [comment]
@MRayermannMSFT OK, had a chance to test this by using Storage Explorer and azcopy natively.

From SE, a transfer between two SAs failed with this error:

```
Transfer from 'cor-p/nfs/npportal_ncprd/common/rm/prod/' to 'cor-s/nfs/npportal_ncstg/common/rm/stageStable/' canceled: 0 items transferred, error: UnexpectedCancel (used SAS, discovery completed)
Started at: 9/20/2023 9:26 AM, Duration: 16 seconds
```

Strangely, SE correctly warned with a dialog box that some files at the destination would be overwritten, so that would indicate to me that azcopy in this instance was able to read, at the very least, the filenames in the source and destination dirs.

I then exec'd into a pod that has cor-p (source) mounted as an SMB share and tried a raw azcopy command:

```
azcopy cp ./ https://cors.file.core.windows.net/cor-s/nfs/npportal_ncstg/common/rm/stageStable/?se=2032-09-02t2
3%3A55%3A15z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2022-09-02t15%3A55%3A15z&sv=
2021-06-08 --recursive
```

This SA-to-SA transfer was successful:

```
Job 6f377e03-6825-e84a-6f72-21fdc6836080 summary
Elapsed Time (Minutes): 1.2671
Number of File Transfers: 9
Number of Folder Property Transfers: 1
Number of Symlink Transfers: 0
Total Number of Transfers: 10
Number of File Transfers Completed: 9
Number of Folder Transfers Completed: 1
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
TotalBytesTransferred: 10161682550
Final Job Status: Completed
```

So I'm still a bit confused why this SA-to-SA transfer works when using azcopy natively, but fails when doing _the same identical transfer_ in SE.

**Comment by MRayermannMSFT** [comment]
> So I'm still a bit confused why this SA-to-SA transfer works when using azcopy natively, but fails when doing the same identical transfer in SE.

If you want to know, sharing the logs would for each of these would be helpful. Although I think exec'ing into your pod with the SMB mounted share is going to be at the root of "why" in this instance".

> Strangely, SE correctly warned with a dialog box that some files at the destination would be overwritten, so that would indicate to me that azcopy in this instance was able to read, at the very least, the filenames in the source and destination dirs.

Assuming the transfer ultimately failed because the destination storage account could not get past the source storage account's firewall, SE/AzCopy showing a conflict dialog is not something I would consider unexpected. If the machine you are on can access the destination storage account, then there's nothing odd about AzCopy being able to check for conflicts before submitting the copy API call to the destination storage account.

**Comment by MRayermannMSFT** [comment]
But what about logs for executing after exec'ing into the pod?

**Comment by bakoontz2** [comment]
@MRayermannMSFT It's a Linux image, so that's not possible.  

However, based on your comments, I ran another test from my local machine on our VPN.  I can (1) azcopy a file from SA corp to local, then (2) azcopy that file from local to SA cors.  However, (3) azcopy from SA corp to SA cors fails with an authentication error:  

```
===== RESPONSE ERROR (ServiceCode=CannotVerifyCopySource) =====
Description=This request is not authorized to perform this operation.
```

So azcopy isn't proxying anything during an SA-to-SA transfer, but setting up a direct transfer between SA and SA.  Not sure how that's done, but I think your comments have convinced me that both SAs need to be on the same private vnet per @nakulkar-msft.

I think we can close this issue, thank you for the assist and hopefully it helps others as well.
