### ISSUE TITLE
Issue with Handling $ Symbol in Container Name within URL in AzCopy 10.20.0

### ISSUE THREAD

**Issue by AZsoftAlanZheng** [Azure/azure-storage-azcopy#2328]
##### Note: The version is visible when running AzCopy without any argument

AzCopy 10.20.0

### Which platform are you using? (ex: Windows, Mac, Linux)

macOS (version 10.15.7)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

EX:
$azcopy copy  "https://something.blob.core.windows.net/web?sp=XXX" "https://something.blob.core.windows.net/$web?sp=XXX" --recursive

### How can we reproduce the problem in the simplest way?

$azcopy copy '<URL without $ symbol'>' '<URL with $ symbol>'
I encountered an issue with the $ symbol in the URL. When running the command with the URL containing the $ symbol, a destination error occurs. Escaping the $ with a backslash (e.g., /\$web) resolves the issue, but this should not be necessary.

### Have you found a mitigation/solution?

I need to manually escape the $ with a backslash.

**Comment by nakulkar-msft** [comment]
Hi @AZsoftAlanZheng please post the error you received without escaping the $?

**Comment by schoag-msft** [comment]
Hi @AZsoftAlanZheng - what is your shell? The following with zsh on macOS works without escaping the `$` in the source and the destination:

```
❯ ps -p $$
  PID TTY           TIME CMD
  15009 ttys000    0:03.44 -zsh

❯ ./azcopy --version
  azcopy version 10.20.1

❯ ./azcopy copy 'https://azcopy2328web.blob.core.windows.net/$web/index.html?sv=REDACATED' 'https://azcopy2328web.blob.core.windows.net/$web/index1.html?sv=REDACATED'
```

**Comment by gapra-msft** [comment]
Hi @AZsoftAlanZheng are you still experiencing this issue? Please feel free to reopen in case you are. Closing this now due to inactivity.
