### ISSUE TITLE
azcopy - "403 request not authorized" - but I can see files in portal just fine

### ISSUE THREAD

**Issue by tdevopsottawa** [Azure/azure-storage-azcopy#2333]
##### Note: The version is visible when running AzCopy without any argument
10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy sync 'https://<redacted>.blob.core.windows.net/<redacted>/' ./blah/ --recursive

### What problem was encountered?
```
Cannot perform sync due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=403 This request is not authorized to perform this operation using this permission., Details: (none)
   HEAD https://<redacted>.blob.core.windows.net/<redacted>?timeout=901
   Authorization: REDACTED
   User-Agent: [AzCopy/10.17.0 Azure-Storage/0.15 (go1.19.2; Windows_NT)]
   X-Ms-Client-Request-Id: [95225d47-1e5c-42a5-4c6f-f0d200c82cb2]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: [Tue, 08 Aug 2023 21:19:19 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [95225d47-1e5c-42a5-4c6f-f0d200c82cb2]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [404cae43-901e-004d-123d-cac440000000]
   X-Ms-Version: [2020-10-02]
```

I am running this with a user account that has Owner on this storage account, and with no firewall issues. Using the exact same account on the exact same PC, I can browse files in the portal and download them from the portal with no issues whatsoever.

### How can we reproduce the problem in the simplest way?
Unique to me? Not sure

### Have you found a mitigation/solution?
No

**Comment by siminsavani-msft** [comment]
I'm under the assumption that your transfer completed, and these errors were found in the log. 

Typically, these are generally benign errors and can safely be ignored. Please see our documentation on 403 errors here: https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-use-azcopy-troubleshoot#403-errors
