### ISSUE TITLE
Bump github.com/golang-jwt/jwt/v4 version to v4.4.3

### ISSUE THREAD

**Issue by Bjyothi2023** [Azure/azure-storage-azcopy#2334]
### Which version of the AzCopy was used? 
Latest v10.20.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What problem was encountered?
Vulnerability "PRISMA-2022-0270" is reported in azcopy due to "github.com/golang-jwt/jwt/v4", and fix is available in v4.4.3
### How can we reproduce the problem in the simplest way?
By running any vulnerability scanner
### Have you found a mitigation/solution?
update all occurrences of  "github.com/golang-jwt/jwt/v4 " to v4.4.3

**Comment by gapra-msft** [comment]
Hi, this should be resolved in our next release. Thank you for reporting this issue

**Comment by gapra-msft** [comment]
Closing this issue as it should be fixed by our next release which should be released within the next month. If this is not resolved by 10.21, feel free to reopen the issue.
