### ISSUE TITLE
Is there any way to prevent azcopy from failing when source blobs are modified or deleted?

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-storage-azcopy#2335]
### Which version of the AzCopy was used? 
10.20.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 11 x64
### What command did you run?
azcopy.exe copy 'https://...' 'https://...' --recursive --overwrite=ifSourceNewer
### What problem was encountered?
```
2023/08/09 20:47:47 ERR: [P#51-T#1135] COPYFAILED: https://.... : 409 : 409 Copy source blob has been modified.. When Put Blob from URL.
```
```
2023/08/09 20:57:08 ERR: [P#68-T#9820] COPYFAILED: https://... : 404 : 404 The specified blob does not exist.. When Put Blob from URL.
```
### Have you found a mitigation/solution?
No

Is there any way to make azcopy retry the transfer of modified source blobs and skip missing blobs, rather than mark them as failed?

**Comment by nakulkar-msft** [comment]
Hi @andrei-faber , we do not have a way to ignore deleted source blobs. This will be treated as a failure. Also, we fail the transfer if the source has been modified to preserve the consistency of data. This behaviour will not be changed. Please make sure that the source remains constant while transfer is in progress.
