### ISSUE TITLE
AzCopy skips the --block-blob-tier arg when uploading to a Premium block blob storage account

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#2337]
##### Note: The version is visible when running AzCopy without any argument
10.20.1

### Which platform are you using? (ex: Windows, Mac, Linux)
All

### What command did you run?
`
./azcopy copy "/Users/chunanye/Documents/bad_webpack.js" "https://jasonpremiumblock.blob.core.windows.net/first/bad_webpack.js?sv=2021-10-04&st=st_datetime&se=se_datetime&sr=c&sp=cw&sig=sig_redacted" --overwrite=true --from-to=LocalBlob --blob-type BlockBlob --follow-symlinks --cap-mbps 1000 --check-length=false --put-md5 --follow-symlinks --block-blob-tier=Hot --disable-auto-decoding=false --recursive --log-level=DEBUG;
`

### What problem was encountered?
The --block-blob-tier=Hot is dropped when performing the upload. As a result, the blob always ends up at the default tier. This is not the desirable behavior for a premium block blob storage account. The platform team wants to allow customers to directly upload blobs to a specific tier.

### How can we reproduce the problem in the simplest way?
Create a premium block blob storage account. Use such a command to upload a block blob to a Hot/Cool/Cold/Archive tier.

### Have you found a mitigation/solution?
Not yet.

Related issue:
https://github.com/microsoft/AzureStorageExplorer/issues/7123

**Comment by seanmcc-msft** [comment]
It appears this limitation is by-design:

PUT [https://seanpremiumblockblob.blob.core.windows.net/test-container-c06bca3f-7056-4371-a4d9-09f6a38b5bd1/test-blob-59f67bb1-596b-482b-a6cc-a474f7f92d00 HTTP/1.1](https://seanpremiumblockblob.blob.core.windows.net/test-container-c06bca3f-7056-4371-a4d9-09f6a38b5bd1/test-blob-59f67bb1-596b-482b-a6cc-a474f7f92d00)
Host: seanpremiumblockblob.blob.core.windows.net
x-ms-blob-type: BlockBlob
**x-ms-access-tier: Hot**
x-ms-version: 2023-11-03
Accept: application/xml
x-ms-client-request-id: b1a0ca8c-a226-45c1-af50-4b67be270b97
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.19.0-alpha.20231003.1 (.NET 6.0.22; Microsoft Windows 10.0.22621)
x-ms-date: Tue, 03 Oct 2023 16:34:57 GMT
Authorization: SharedKey seanpremiumblockblob:tNeXDSPktxytOJ9qW/Z6xFIppx0x7H7EVfScOcB84CY=
traceparent: 00-106bb4b0114a89ce27ec03b90cda3324-b83a3402045b39aa-00
Content-Length: 1024
Content-Type: application/octet-stream

HTTP/1.1 400 Blob access tier is not supported on this storage account type.
Content-Length: 272
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 27f7e442-701e-006a-5117-f62269000000
x-ms-client-request-id: b1a0ca8c-a226-45c1-af50-4b67be270b97
x-ms-version: 2023-11-03
x-ms-error-code: BlobAccessTierNotSupportedForAccountType
Date: Tue, 03 Oct 2023 16:34:57 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAccessTierNotSupportedForAccountType</Code><Message>Blob access tier is not supported on this storage account type.
RequestId:27f7e442-701e-006a-5117-f62269000000
Time:2023-10-03T16:34:58.3537466Z</Message></Error>


The [public documentation](https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview#rule-actions) also indicates that Tiering is not yet supported on premium block blob accounts.

**Comment by siminsavani-msft** [comment]
Hi @JasonYeMSFT ! I'm closing this issue as this PR is merged in dev and will be released in our November release.
