### ISSUE TITLE
Zip and copy using azcopy

### ISSUE THREAD

**Issue by fraheu** [Azure/azure-storage-azcopy#2339]
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

I just started working with Azure storage and I am trying to copy a big folder/repository (~600 GB). My question is, can I zip and copy the folder at the same time using azcopy? (the folder would land as a zip on the blob ) if so, how would the command look like in Linux?

**Comment by adreed-msft** [comment]
For a temporary workaround, check the zip manpage

https://linux.die.net/man/1/zip

You can pipe the output of `zip` into `azcopy` and specify `--from-to=PipeBlob`.

The catch of this is, pipe is entirely serial, not parallel. You're going to experience worse performance than say `zip xyz.zip <files>; azcopy copy xyz.zip <destination>` (maybe, I'm guessing?), but you'll avoid the disk usage by piping it.

**Comment by fraheu** [comment]
Thanks a lot for your answer. I just tried it. The syntax seems to be ok. 

zip foo.txt test.zip | azcopy cp "destination" --from-to=PipeBlob

But the file weren't uploaded to the blob. also no message at all whether error message or "done". 
This is what I see in the logfile: 
2023/08/17 08:15:41 AzcopyVersion  10.20.0
2023/08/17 08:15:41 OS-Environment  linux
2023/08/17 08:15:41 OS-Architecture  amd64
2023/08/17 08:15:41 Log times are in UTC. Local time is 17 Aug 2023 10:15:41
2023/08/17 08:15:41 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2023-08-17T08:15:36Z or --include-after=2023-08-17T08:15:36Z

what does include before or include after has to do with it?

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality. We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
