### ISSUE TITLE
Authenticate with blob storage from a managed identity

### ISSUE THREAD

**Issue by mazong1123** [Azure/azure-storage-azcopy#234]
Hi,

I saw AzCopy has an interactive `azcopy login` authentication mode that is using Azure Active Directory. If an Azure VM is MSI enabled and "Storage Blob Data Contributor" role has been assigned to the managed identity, is it a way to get rid of the interactive `azcopy login` and directly access to the Azure blob storage?

**Comment by jiacfan** [comment]
Hi, @mazong1123 

Thanks for reaching us.

For your question, yes. AzCopy supports MSI. Please use `azcopy login --help` to check detailed usages.

For example, to login with system assigned identity:
```
Log in using a VM's system-assigned identity:
- azcopy login --identity
```

Best Regards,
Jiachen

**Comment by mazong1123** [comment]
@jiacfan Thanks. That's a great news. 

I just got one question: 

Once the MSI is turned on and `azcopy login --identity` called, seems the identity is cached forever. Later even if I turned MSI off, `azcopy login --identity` can still success (`azcopy logout` is called before testing). Is there a way to prevent `azcopy login --identity` when MSI is turned off?

**Comment by mazong1123** [comment]
@jiacfan OK I saw the code [here](https://github.com/Azure/azure-storage-azcopy/blob/9c1d19029bb41ce4cb3a60b06b81cff3e94c0c10/common/credCacheInternal_windows.go#L109)

```Go
// removeCachedTokenInternal deletes all the cached token.
func (c *CredCacheInternalIntegration) removeCachedTokenInternal() error {
	// By design, not useful currently.
	return errors.New("Not implemented")
}
```

Will the cache removal be implemented before GA?

**Comment by jiacfan** [comment]
Hi, @mazong1123 

For MSI, currently azcopy login --identity doesn't  get or cache the token, it records the requirement that user wish to use OAuth with MSI. And token is fetched during run-time, through the [official procedure](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview), as token need be regularly refreshed during copy. And if no valid token can be get before last valid token get expired, copy will fail.

For azcopy logout, it works, for MSI it clears the requirement that user wish to use OAuth with MSI. The code pasted is a specific token cache where remove is not necessary in this phase. Please check public versions' token cache for their detailed implementation, e.g. [WinTokenCacheWithDPAPI](https://github.com/Azure/azure-storage-azcopy/blob/master/common/credCache_windows.go)

For the questions:

- use azcopy login --identity to check whether MSI is switched on or off. This could be an optimization! I'll discuss this with the team.
- For RBAC assignment, it should be service-side delay. There will be at most 5 minutes delay in service-side between your action and when it take effect. 

Welcome discussions!

Best Regards,
Jiachen

**Comment by jiacfan** [comment]
Hi, @mazong1123 

For MSI, currently azcopy login --identity do get or cache the token, it records the requirement that user wish to use OAuth with MSI. And token is fetched during run-time, through the [official procedure](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview), as token need be regularly refreshed during copy. And if no valid token can be get before last valid token get expired, copy will fail.

For azcopy logout, it works, for MSI it clears the requirement that user wish to use OAuth with MSI. The code pasted is a specific token cache where remove is not necessary in this phase. Please check public versions' token cache for their detailed implementation, e.g. [WinTokenCacheWithDPAPI](https://github.com/Azure/azure-storage-azcopy/blob/master/common/credCache_windows.go) which azcopy logout depends for removing cache.

For the questions:

- use azcopy login --identity to check whether MSI is switched on or off. This could be related how fast MSI enabling/disabling take effect in the VM. If `azcopy login --identity` is used on a VM where MSI is disabled, proper error message would be returned.
- For RBAC assignment, it should be service-side delay. There will be at most 5 minutes delay in service-side between your action and when it take effect. 

Welcome discussions!

Best Regards,
Jiachen

**Comment by mazong1123** [comment]
> * There will be at most 5 minutes delay in service-side between your action and when it take effect.

Actually I wait for over 1 hour - the RBAC changes did not take effect. I created 2 VMs and 2 blob storage for testing and got the same result. Following are the reproduce steps:

- In Azure Portal, create an Azure blob storage container `blobstorage1`.
- In Azure Portal, create an Azure VM with `Windows 2016 Datacenter` installed.
- Enable MSI for the Azure VM.
- Login to the VM, create a folder `d:\msitest` and download `azcopy-preview-1.0.0.7` to C drive. 
- In the VM, run `azcopy login --identity`. Then run `azcopy sync https://blobstorage1url d:\msitest`. The permission denied message should occur as expected.
- In Azure Portal, go to `blobstorage1`, assign `Storage Blob Data Reader (Preview)` role for the VM.
- Back to the VM, run `azcopy logout`.
- Wait 5 min, in the VM run `azcopy login`. Then run `azcopy sync https://blobstorage1url d:\msitest`

**Expected:**
The command can be executed successfully.

**Actual:**
Permission denied message show up.

**Comment by jiacfan** [comment]
Hi, @mazong1123 

Thanks for following up, let's discuss more and try to figure out if there is an issue. 

I tried to repro the issue with same step, while it behaves correctly in my side:
1. With a new VM, enabled MSI, no Storage Blob Data Reader/Contributor role are ever assigned, downloading blob will fail. 
2. And later assign Storage Blob Data Reader, download can fulfill successfully.
3. Disable again, download fails again.

Could you help to provide following info for further investigation:
1. I see you create a storage container blobstorage1, while roles are assigned in storage account level, could you check if there are Storage Blob Data Reader/Contributor role already assigned to the account, before container is created?
2. Wish to double confirm that blobstorage you mean is Blob and not ADLS gen 2 filesystem.
3. Are you using pure system-assigned identity, or user-assigned identity are set as well?

Best Regards,
Jiachen

**Comment by mazong1123** [comment]
@jiacfan I tried this morning seems the RBAC changes applied. How long did you wait for the RBAC changes you made take effect?

Answers to you questions:

1. The roles were assigned to container level not for storage account level.
2. Yes It's a Blob. At least I clicked "Blobs" under the Services and then created the container.
3. Pure system-assigned identity.

**Comment by jiacfan** [comment]
Hi, @mazong1123 

As my testing, within 1 minute. Could the issue still be reproduce in your side?

Best Regards,
Jiachen

**Comment by mazong1123** [comment]
@jiacfan The issue persists. I need to wait for 1 day to take the RBAC changes take effect. I tested the changes as following:

- No any role assigned -> Storage Blob Data Reader assigned. Wait for 1 day to take effect.
   - Steps for testing:
      - Before the RBAC change, run `azcopy sync https://msitestjingm.blob.core.windows.net/test1 D:\ddw`. I got `===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.`
      - After the RBAC change, run the same command. Still got the same error. Continue to try this every 5 min. Same results.
      - Next day when I try the same command again, the files can be synced down to the folder.
- Storage Blob Data Reader assigned -> No any role assigned. Wait for 1 day to take effect.
   - Steps for testing:      
      - Before the RBAC change, run  `azcopy sync https://msitestjingm.blob.core.windows.net/test1 D:\ddw`. It success to sync the files to local folder.
      - After the RBAC change, run the same command. Still can sync the files to local folder. Continue to try this every 5 min. Same results.
      - Next day when I try the same command again, the error occurs: `===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.`

**Comment by jiacfan** [comment]
Thanks for the info! Having forward the problem to service team, and will update later if there is any update.

**Comment by JohnRusk** [comment]
@jiacfan Any update on this?

**Comment by jiacfan** [comment]
@JohnRusk, thanks for reminding.

As my testing, the reported scenario works well now! Please let me if the issue still happens in your side @mazong1123 .

Thanks,
Jiachen
