### ISSUE TITLE
request that remove -recursive, should remove an entire path without need for repeated such calls

### ISSUE THREAD

**Issue by SimonTiz** [Azure/azure-storage-azcopy#2344]
azcopy version 10.20.0
Windows (10)  , Powershell 5.1

. "....\AzCopy.10.20.0.exe" remove "https://[account].blob.core.windows.net/[container]/[path]?[SAS] --log-level=INFO --output-level=default --output-type=json --skip-version-check --recursive=true

### What problem was encountered?
The path has sub-paths from under it (with blobs therein).  Despite the  --recursive=true  clearly indicating the desire is to remove entire path, it fails to remove path elements due to being Non-Empty.  I suspect the issue is that asynchronous deletion is requested of all 'elements' for the entire path-tree, and that some elements will be Non-Empty due to the order (lack) of processing / (without any cycling thereof).  Whilst I understand the refusal for Non-Empty is intentional, I think the intention of the initial request is clear and it is the lack of ordering or cycling that results in it failing to fulfill that initial request.  
Repeated calls of exactly the same nature will clear the full path, (which oughtn't to be necessary with the --recursive=true).
There are a number of ways this could be addressed and can be mitigated by those repeated calls as mentioned.  I feel such mitigation with its fail handling on each cycle, should not be necessary, and that the 'remove' processing (when recursive=true) itself should handle it.  Please can it be enhanced to this effect.

### How can we reproduce the problem in the simplest way?
Create path structure containing e.g.
.../path/item(s)
.../path/subpath1/subpath2/item(s)
.../path/subpath1B
and issue remove (recursive) against .../path

### Have you found a mitigation/solution?
Repeated calls.   But this issue being raised for RFC, so that such isn't necessary.

**Comment by gapra-msft** [comment]
Hi @SimonTiz is your account a hierarchical namespace enabled account?

**Comment by SimonTiz** [comment]
Yes it is a hierarchical namespace enabled storage account.


log contains errors wrt. non-empty e.g.
409: DELETE ERROR -409 This operation is not permitted on a non-empty directory.. X-Ms-Request-Id:0eee3944-d01e-006c-0b47-e549b7000000

Info from a repro run below.

==================================================================================
===  Listing before  =============================================================
..................................................................................

FullName                                               LastModifiedTime
--------                                               ----------------
tst230912/Dummy.downloaded                             2023-09-12 07:59:15 +0100 BST
tst230912/Dummy.txt                                    2023-09-12 07:59:06 +0100 BST
tst230912/DummyA.txt                                   2023-09-12 07:59:07 +0100 BST
tst230912/DummyA1.txt                                  2023-09-12 07:59:06 +0100 BST
tst230912/DummyA2.txt                                  2023-09-12 07:59:06 +0100 BST
tst230912/DummyA2.txt.Moved.20230815_100302            2023-09-12 07:59:06 +0100 BST
tst230912/DummyA2.txt.Moved.20230815_122524            2023-09-12 07:59:07 +0100 BST
tst230912/DummyA2.txt.Moved.20230817_032729            2023-09-12 07:59:06 +0100 BST
tst230912/DummyA2.txt.Moved.20230817_035148            2023-09-12 07:59:06 +0100 BST
tst230912/DummyA2.txt.Moved.20230817_035850            2023-09-12 07:59:06 +0100 BST
tst230912/DummyA2.txt.Moved.20230817_040353            2023-09-12 07:59:06 +0100 BST
tst230912/DummyA2.txt.Moved.20230817_040836            2023-09-12 07:59:06 +0100 BST
tst230912/DummyA2.txt.Moved.20230817_085912            2023-09-12 07:59:06 +0100 BST
tst230912/DummyA2.txt.Moved.20230817_092139            2023-09-12 07:59:07 +0100 BST
tst230912/DummyDown.txt                                2023-09-12 07:59:06 +0100 BST
tst230912/SimonSays.oof.oof                            2023-09-12 07:59:06 +0100 BST
tst230912/listing.txt                                  2023-09-12 07:59:06 +0100 BST
tst230912/SubDir/New Text Document.txt                 2023-09-12 07:59:15 +0100 BST
tst230912/SubDir/owssvr (3).ics                        2023-09-12 07:59:15 +0100 BST
tst230912/NubSub1/NubSub2/New Text Document.txt        2023-09-12 07:59:15 +0100 BST
tst230912/NubSub1/NubSub2/internet-Domains-Trusted.txt 2023-09-12 07:59:15 +0100 BST
tst230912/NubSub1/NubSub2/owssvr (4).ics               2023-09-12 07:59:15 +0100 BST
tst230912                                              2023-09-12 07:59:15 +0100 BST
tst230912/SubDir                                       2023-09-12 07:59:15 +0100 BST
tst230912/NubSub1/NubSub2                              2023-09-12 07:59:15 +0100 BST
tst230912/NubSub1                                      2023-09-12 07:59:15 +0100 BST

==================================================================================
===  Ran  ========================================================================
..................................................................................

$Obj = New-Object PSObject -Property @{Url=$null;Can=$null;SAS=$null;SAX=$null}
$Obj.Url = "https://cccuksdevfinintdls1.blob.core.windows.net"
$Obj.Can = "test-any/tst230912"
$Obj.SAS = "?sv=2022-11-02&ss=b&srt=sco&sp=rwdlacyx&se=2024-07-17T10:00:00Z&st=2023-07-21T06:42:38Z&sip=2.56.196.16-2.56.196.28&spr=https&sig=REDACTED"

. $AzCopyExe remove "$($Obj.Url)/$($Obj.Can)$($Obj.SAS)" --log-level=INFO --output-level=default --output-type=text --skip-version-check --recursive=true


==================================================================================
===  Output  =====================================================================
..................................................................................


INFO: Any empty folders will be processed, because source and destination both support folders
INFO: Proxy detected: https://cccuksdevfinintdls1.blob.core.windows.net -> //webproxy:8080

Job 67678492-a63b-5c43-7c58-f1214e777af3 has started
Log file is located at: C:\Users\cvsti230\.azcopy\67678492-a63b-5c43-7c58-f1214e777af3.log

100.0 %, 23 Done, 3 Failed, 0 Pending, 0 Skipped, 26 Total, 


Job 67678492-a63b-5c43-7c58-f1214e777af3 summary
Elapsed Time (Minutes): 0.0336
Number of File Transfers: 22
Number of Folder Property Transfers: 4
Number of Symlink Transfers: 0
Total Number of Transfers: 26
Number of File Transfers Completed: 22
Number of Folder Transfers Completed: 1
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 3
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
TotalBytesTransferred: 54032
Final Job Status: CompletedWithErrors

==================================================================================
===  Job log  ====================================================================
..................................................................................

2023/09/12 07:02:41 AzcopyVersion  10.20.0
2023/09/12 07:02:41 OS-Environment  windows
2023/09/12 07:02:41 OS-Architecture  amd64
2023/09/12 07:02:41 Log times are in UTC. Local time is 12 Sep 2023 08:02:41
2023/09/12 07:02:41 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2023-09-12T07:02:36Z or --include-after=2023-09-12T07:02:36Z
2023/09/12 07:02:41 Any empty folders will be processed, because source and destination both support folders
2023/09/12 07:02:42 Job-Command remove https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912?se=2024-07-17t10%3A00%3A00z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21t06%3A42%3A38z&sv=2022-11-02 --log-level=INFO --output-level=default --output-type=text --skip-version-check --recursive=true 
2023/09/12 07:02:42 Number of CPUs: 8
2023/09/12 07:02:42 Max file buffer RAM 4.000 GB
2023/09/12 07:02:42 Max concurrent network operations: 128 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2023/09/12 07:02:42 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2023/09/12 07:02:42 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2023/09/12 07:02:42 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2023/09/12 07:02:42 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2023/09/12 07:02:42 Max open files when downloading: 2147483119 (auto-computed)
2023/09/12 07:02:42 Final job part has been created
2023/09/12 07:02:42 JobID=67678492-a63b-5c43-7c58-f1214e777af3, credential type: Anonymous
2023/09/12 07:02:42 Final job part has been scheduled
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/85.4424ms, OpTime=702.2711ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt.Moved.20230817_040836?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [826b2704-f01e-00a0-6a47-e52681000000]

2023/09/12 07:02:43 INFO: [P#0-T#14] DELETE SUCCESSFUL: DummyA2.txt.Moved.20230817_040836
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/85.4424ms, OpTime=701.7558ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA1.txt?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [803b52d8-201e-001a-7f47-e5c3ff000000]

2023/09/12 07:02:43 INFO: [P#0-T#6] DELETE SUCCESSFUL: DummyA1.txt
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/85.4424ms, OpTime=701.7558ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/NubSub1/NubSub2/internet-Domains-Trusted.txt?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [7441f2b5-d01e-0088-3f47-e54729000000]

2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/85.4424ms, OpTime=702.2711ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt.Moved.20230817_035850?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [6772ead3-e01e-0067-6b47-e5b2dc000000]

2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/85.4424ms, OpTime=701.7558ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/listing.txt?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [0ca0a8e5-b01e-009e-6c47-e5b1fe000000]

2023/09/12 07:02:43 INFO: [P#0-T#19] DELETE SUCCESSFUL: listing.txt
2023/09/12 07:02:43 INFO: [P#0-T#24] DELETE SUCCESSFUL: NubSub1/NubSub2/internet-Domains-Trusted.txt
2023/09/12 07:02:43 INFO: [P#0-T#12] DELETE SUCCESSFUL: DummyA2.txt.Moved.20230817_035850
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/85.4424ms, OpTime=702.2711ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt.Moved.20230817_085912?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [4f4f2b1d-f01e-0054-8047-e5ed77000000]

2023/09/12 07:02:43 INFO: [P#0-T#15] DELETE SUCCESSFUL: DummyA2.txt.Moved.20230817_085912
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/86.6452ms, OpTime=702.9586ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/NubSub1/NubSub2/New%20Text%20Document.txt?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [9bb8957d-601e-0069-0f47-e59b6c000000]

2023/09/12 07:02:43 INFO: [P#0-T#23] DELETE SUCCESSFUL: NubSub1/NubSub2/New Text Document.txt
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/86.6452ms, OpTime=702.9586ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/SimonSays.oof.oof?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [67998b49-501e-003f-1447-e56a83000000]

2023/09/12 07:02:43 INFO: [P#0-T#18] DELETE SUCCESSFUL: SimonSays.oof.oof
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/90.6242ms, OpTime=706.9376ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/SubDir/owssvr%20%283%29.ics?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [9fa81690-a01e-003b-2a47-e5e784000000]

2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/90.6242ms, OpTime=707.4529ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/Dummy.txt?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [66d27c66-b01e-0008-4047-e5b82f000000]

2023/09/12 07:02:43 INFO: [P#0-T#21] DELETE SUCCESSFUL: SubDir/owssvr (3).ics
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/90.6242ms, OpTime=706.9376ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/SubDir/New%20Text%20Document.txt?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [70a25654-301e-0029-6647-e59c54000000]

2023/09/12 07:02:43 INFO: [P#0-T#4] DELETE SUCCESSFUL: Dummy.txt
2023/09/12 07:02:43 INFO: [P#0-T#20] DELETE SUCCESSFUL: SubDir/New Text Document.txt
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/90.6242ms, OpTime=706.6937ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA.txt?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [7672342a-501e-0072-1947-e5a56f000000]

2023/09/12 07:02:43 INFO: [P#0-T#5] DELETE SUCCESSFUL: DummyA.txt
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/94.8702ms, OpTime=711.1836ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyDown.txt?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [cc78b58e-101e-0073-5947-e5fab3000000]

2023/09/12 07:02:43 INFO: [P#0-T#17] DELETE SUCCESSFUL: DummyDown.txt
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/133.9205ms, OpTime=750.5043ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [b1a5f959-401e-009a-3f47-e53cf9000000]

2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/101.868ms, OpTime=751.2635ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt.Moved.20230817_040353?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [8371dcba-b01e-007a-2647-e5bf60000000]

2023/09/12 07:02:43 INFO: [P#0-T#13] DELETE SUCCESSFUL: DummyA2.txt.Moved.20230817_040353
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/101.9604ms, OpTime=751.2635ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt.Moved.20230815_100302?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [ac5922ee-601e-00a2-4447-e59839000000]

2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/134.4278ms, OpTime=751.7708ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt.Moved.20230817_035148?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [14fd4320-401e-000c-1947-e53528000000]

2023/09/12 07:02:43 INFO: [P#0-T#8] DELETE SUCCESSFUL: DummyA2.txt.Moved.20230815_100302
2023/09/12 07:02:43 INFO: [P#0-T#7] DELETE SUCCESSFUL: DummyA2.txt
2023/09/12 07:02:43 INFO: [P#0-T#11] DELETE SUCCESSFUL: DummyA2.txt.Moved.20230817_035148
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/134.6081ms, OpTime=751.9511ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt.Moved.20230815_122524?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [955517c6-d01e-0021-6147-e5865b000000]

2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/102.648ms, OpTime=751.9511ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/Dummy.downloaded?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [1a35214d-001e-001d-6a47-e5af9c000000]

2023/09/12 07:02:43 INFO: [P#0-T#9] DELETE SUCCESSFUL: DummyA2.txt.Moved.20230815_122524
2023/09/12 07:02:43 INFO: [P#0-T#3] DELETE SUCCESSFUL: Dummy.downloaded
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/134.6081ms, OpTime=751.4358ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt.Moved.20230817_092139?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [d8d216ed-101e-0011-2d47-e53894000000]

2023/09/12 07:02:43 INFO: [P#0-T#16] DELETE SUCCESSFUL: DummyA2.txt.Moved.20230817_092139
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/103.1555ms, OpTime=751.9433ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/NubSub1/NubSub2?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [0eee3944-d01e-006c-0b47-e549b7000000]

2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/103.1555ms, OpTime=752.4586ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/NubSub1?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [4d17204a-401e-0023-0a47-e538e3000000]

2023/09/12 07:02:43 ERR: [P#0-T#22] https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/NubSub1/NubSub2?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02: 409: DELETE ERROR -409 This operation is not permitted on a non-empty directory.. X-Ms-Request-Id:0eee3944-d01e-006c-0b47-e549b7000000

2023/09/12 07:02:43 ERR: [P#0-T#1] https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/NubSub1?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02: 409: DELETE ERROR -409 This operation is not permitted on a non-empty directory.. X-Ms-Request-Id:4d17204a-401e-0023-0a47-e538e3000000

2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/98.8091ms, OpTime=801.0802ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/DummyA2.txt.Moved.20230817_032729?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [826b273b-f01e-00a0-1847-e52681000000]

2023/09/12 07:02:43 INFO: [P#0-T#10] DELETE SUCCESSFUL: DummyA2.txt.Moved.20230817_032729
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/98.8091ms, OpTime=800.5649ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/NubSub1/NubSub2/owssvr%20%284%29.ics?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [803b5325-201e-001a-4347-e5c3ff000000]

2023/09/12 07:02:43 INFO: [P#0-T#25] DELETE SUCCESSFUL: NubSub1/NubSub2/owssvr (4).ics
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/112.528ms, OpTime=814.0399ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912/SubDir?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [0ca0a914-b01e-009e-1247-e5b1fe000000]

2023/09/12 07:02:43 INFO: [P#0-T#2] DELETE SUCCESSFUL: SubDir
2023/09/12 07:02:43 ==> REQUEST/RESPONSE (Try=1/214.126ms, OpTime=862.6699ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02&timeout=901
   X-Ms-Request-Id: [abea51ef-c01e-002d-4047-e51153000000]

2023/09/12 07:02:43 ERR: [P#0-T#0] https://cccuksdevfinintdls1.blob.core.windows.net/test-any/tst230912?se=2024-07-17T10%3A00%3A00Z&sig=-REDACTED-&sip=2.56.196.16-2.56.196.28&sp=rwdlacyx&spr=https&srt=sco&ss=b&st=2023-07-21T06%3A42%3A38Z&sv=2022-11-02: 409: DELETE ERROR -409 This operation is not permitted on a non-empty directory.. X-Ms-Request-Id:abea51ef-c01e-002d-4047-e51153000000

2023/09/12 07:02:43 JobID=67678492-a63b-5c43-7c58-f1214e777af3, Part#=0, TransfersDone=26 of 26
2023/09/12 07:02:43 all parts of entire Job 67678492-a63b-5c43-7c58-f1214e777af3 successfully completed, cancelled or paused
2023/09/12 07:02:43 is part of Job which 1 total number of parts done 
2023/09/12 07:02:44 PERF: primary performance constraint is Unknown. States: T:  0, GRs: 128
2023/09/12 07:02:44 100.0 %, 23 Done, 3 Failed, 0 Pending, 0 Skipped, 26 Total, 
2023/09/12 07:02:44 

Diagnostic stats:
IOPS: 10
End-to-end ms per request: 737
Network Errors: 0.00%
Server Busy: 0.00%


Job 67678492-a63b-5c43-7c58-f1214e777af3 summary
Elapsed Time (Minutes): 0.0336
Number of File Transfers: 22
Number of Folder Property Transfers: 4
Number of Symlink Transfers: 0
Total Number of Transfers: 26
Number of File Transfers Completed: 22
Number of Folder Transfers Completed: 1
Number of File Transfers Failed: 0
Number of Folder Transfers Failed: 3
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
TotalBytesTransferred: 54032
Final Job Status: CompletedWithErrors


==================================================================================
===  Listing after  ==============================================================
..................................................................................

No files

BUT Folders still present :
	test-any/tst230912/NubSub1/NubSub2

If exactly the same job then re-run then
.. result :  100.0 %, 2 Done, 1 Failed, 0 Pending, 0 Skipped, 3 Total, 
and folder structure reduced to :
	test-any / tst230912
	
If exactly the same job then re-run then
.. result :  100.0 %, 1 Done, 0 Failed, 0 Pending, 0 Skipped, 1 Total,
and none of the folders remain

==================================================================================

**Comment by piero2c** [comment]
Same issue here

**Comment by gapra-msft** [comment]
Hi @SimonTiz and @piero2c 

If you specify the URL as a .dfs URL instead of .blob, you should experience the behavior you expect.

**Comment by gapra-msft** [comment]
Closing this item as a resolution was provided.
