### ISSUE TITLE
AZCopy Scanning and Copying Entire Root Share Instead of Passed Source Directory

### ISSUE THREAD

**Issue by Improving-Lee** [Azure/azure-storage-azcopy#2346]
### Which version of the AzCopy was used?
10.20.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy sync "https://fileshare.file.core.windows.net/share/Directory/SubDirectory?snapshot={snapshot_timestamp_id}&{SAS}" "https://filesharewus.file.core.windows.net/share&{SAS}" --recursive --preserve-smb-info --preserve-smb-permissions --delete-destination=TRUE

### What problem was encountered?
AZCopy is scanning and copying the entire root of the share, not the /Directory/SubDirectory only.

### How can we reproduce the problem in the simplest way?
Create two storage accounts each with an Azure File Share with at least one directory under the root of the share.  Crate a snapshot of the source share and use that as the source location in AZCopy.

### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
@Improving-Lee, sync will scan both source and destination. Your destination is https://filesharewus.file.core.windows.net/share, and azcopy will scan all sub-directories under https://filesharewus.file.core.windows.net/share. To restrict scanning to Directory/sub-directories append the path to destination as well.
