### ISSUE TITLE
Issue when copying huge amount of data to a blob container

### ISSUE THREAD

**Issue by dumpeal** [Azure/azure-storage-azcopy#2351]
##### Note: The version is visible when running AzCopy without any argument
10.20.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
export AZCOPY_AUTO_LOGIN_TYPE=MSI
export AZCOPY_REQUEST_TRY_TIMEOUT=720
tar --use-compress-program="pigz -6 -p 12" -c -f - * | azcopy cp "https://xxx.blob.core.windows.net/container/file.tar.gz" --from-to PipeBlob --cap-mbps 3200
I don't have any azcopy job log since we're using --from-to option.

### What problem was encountered?
Command runs for a 2-3 hours (due to the compression we can easily check when it's running) and gets stuck at some point, no more activity on the source machine. Nevertheless, command still runs (apparently) and I have to ctrl-c to get access back.

### How can we reproduce the problem in the simplest way?
Try to compress and send 17TB of data to a blob container with the above command.

### Have you found a mitigation/solution?
No mitigation/solution so far.

**Comment by vibhansa-msft** [comment]
As the file size is huge, can you set higher block size in "azcopy copy" command and retry. "block-size-mb=500" is the cli option you can try with this. You can also enable log-info to get insight on what is happening in azcopy and share those logs.

**Comment by dumpeal** [comment]
Thanks @vibhansa-msft, adding parameter --block-size-mb seems to have solved our issue, copy operation is now in success.
