### ISSUE TITLE
AzCopy always creates directory and zero length file with same name as directory

### ISSUE THREAD

**Issue by georgewfisher** [Azure/azure-storage-azcopy#2358]
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux 

`Linux version 5.15.0-1042-azure (buildd@lcy02-amd64-005) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #49~20.04.1-Ubuntu SMP Wed Jul 12 12:44:
56 UTC 2023`

### What command did you run?

`azcopy cp "/mnt/repos/test_logs/*" https://myaccount.dfs.core.windows.net/packagetests/test_logs/ --log-level DEBUG`

and

`azcopy cp --recursive=true /mnt/repos/test_logs/ https://myaccount.dfs.core.windows.net/packagetests/`

### What problem was encountered?

When the files are uploaded a zero-length file is created with the same name as the directory. This means, when you download to Windows, this does not work because it's an invalid state.

![image](https://github.com/Azure/azure-storage-azcopy/assets/4565745/2944b6ce-b2de-4e44-be89-48ee57a011ca)

### How can we reproduce the problem in the simplest way?

1. Try to copy a directory from Linux to a storage account using this command:
`azcopy cp --recursive=true /mnt/repos/test_logs/ https://myaccount.dfs.core.windows.net/packagetests/`
2. Inspect the storage account and there will be both a directory created and a file with the same name as the directory.

### Have you found a mitigation/solution?

You can avoid this by not copying directories.

**Comment by nakulkar-msft** [comment]
Hi, include "--include-directory-stub=false" in your command.
