### ISSUE TITLE
Azcopy ServerBusy when copy files from VM to Fille Share

### ISSUE THREAD

**Issue by ShengquanYu** [Azure/azure-storage-azcopy#2359]
##### Note: The version is visible when running AzCopy without any argument
10.20.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2012R2 on Azure VM.

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
folder_path: A directory in the VM that you want to upload to the File Share.
destination_path: Share URL
sas_token: Storage Account's sas token
azcopy copy folder_path destination_path+sas_token --recursice=true

### What problem was encountered?
When using the azcopy command to upload files from a VM to Azure File Share, I encounter numerous error logs in StorageFileLogs with StatusText=ServerBusy.

### How can we reproduce the problem in the simplest way?
The problem can be reproduced by having a folder with a large number of text or log files inside that needs to be uploaded. Every time the 'azcopy copy' command is executed, it generates 'ServerBusy' logs in StorageFileLogs.

### Have you found a mitigation/solution?
No. It appears that the upload was successful, but these error logs are affecting the monitoring functionality. It's necessary to resolve these errors.

**Comment by nakulkar-msft** [comment]
Hi @ShengquanYu, these errors are expected. AzCopy tries to utilize all the available resources and at times we may be throttled by the service. As such, we recover from these request failures and transfer the file. We recommend you to refer [this](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#review-the-logs-for-errors) instead to identity failed transfers.

You can also lower the throughput either by setting AZCOPY_CONCURRENCY_VALUE to a lower number (say 8) or by restricting throughput using --cap-mbps parameter.
