### ISSUE TITLE
Auto-login not persisting token when AZCOPY_AUTO_LOGIN_TYPE=DEVICE

### ISSUE THREAD

**Issue by sean-jost** [Azure/azure-storage-azcopy#2361]
### Which version of the AzCopy was used? 
10.20.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
export AZCOPY_AUTO_LOGIN_TYPE=DEVICE
export AZCOPY_TENANT_ID=_tenant id_
... multiple azcopy commands

### What problem was encountered?
Have to enter code into web browser for _every_ azcopy command encountered a script.  Not a usable solution when there many commands.

### How can we reproduce the problem in the simplest way?
Should be easy to reproduce.  It appears from the code that auto-login disables token persistence altogether.

### Have you found a mitigation/solution?
Don't use auto-login, use `azcopy login` instead, but it's getting removed in 10.22.

Azure CLI persists tokens in ~/.azure folder; could azcopy do the same?

**Comment by htpawel** [comment]
+1337

**Comment by david-chaves** [comment]
This error it's algo present Using azcopy version 10.21.1 under windows 10 19044.3086

**Comment by gapra-msft** [comment]
Related to this PR https://github.com/Azure/azure-storage-azcopy/pull/2574

**Comment by gapra-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/pull/2747
