### ISSUE TITLE
Wrong title in latest release preview

### ISSUE THREAD

**Issue by jbpaux** [Azure/azure-storage-azcopy#2369]
### Which version of the AzCopy was used? 

- v10.21.0-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
NA

### What command did you run?
NA

### What problem was encountered?

The release title for the latest preview is 10.20.1-Preview while the actual preview version is 10.21.0-Preview (note the subtle difference)

### How can we reproduce the problem in the simplest way?

Go to https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.21.0-Preview and have a look on the release title

### Have you found a mitigation/solution?

Change the title

**Comment by gapra-msft** [comment]
@jbpaux thanks for letting us know! I just fixed the title.
