### ISSUE TITLE
Throttling errors on azcopyvnextrelease storage account

### ISSUE THREAD

**Issue by hanshagers** [Azure/azure-storage-azcopy#2370]
### Which version of the AzCopy was used? 
10.14.1
### Which platform are you using? (ex: Windows, Mac, Linux) 
Windows

### What problem was encountered?

It seems that the version check that is being executed gives 503 throttling errors when checking for the next version.
This problem only seems to be occuring on whole hours. E.g. 11.00 PM / 09.00 AM.
It looks like the storage account(azcopyvnextrelease) limits are being reached at certain moments. 

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="F:\Tools\azcopy.exe" /> 
  <TimeCreated SystemTime="2023-09-05T11:00:05.987136300Z" /> 
 <EventData>
  <Data>==> REQUEST/RESPONSE (Try=1/149.9987ms, OpTime=620.9558ms) -- RESPONSE STATUS CODE ERROR GET https://azcopyvnextrelease.blob.core.windows.net/releasemetadata/latest_version.txt?timeout=901 
  User-Agent: [AzCopy/10.14.1 Azure-Storage/0.14 (go1.16.14; Windows_NT)] 
  X-Ms-Version: [2020-08-04] -------------------------------------------------------------------------------- RESPONSE Status: 503 Operations per second is over the account limit. 
  Content-Length: [227] Content-Type: [application/xml] Date: [Tue, 05 Sep 2023 11:00:05 GMT] 
  Server: [Microsoft-HTTPAPI/2.0] 
  X-Ms-Error-Code: [ServerBusy] 
  Response Details: ﻿<Code>ServerBusy</Code><Message>Operations per second is over the account limit. </Message></Data> 
  </EventData>
  </Event>

### How can we reproduce the problem in the simplest way?

Run the azcopy commands on whole hours. We dont have this every hour, its very intermediate.

### Have you found a mitigation/solution?

Suggestion was made in 1175 to supress logging entirely, but we do want logging and definitly Error type
https://github.com/Azure/azure-storage-azcopy/issues/1175

**Comment by gapra-msft** [comment]
Hi @hanshagers we recently put out a feature to cache version checking and limit checking the remote URL to once every 24 hours, which should help mitigate this issue in the future. [This ](https://github.com/Azure/azure-storage-azcopy/pull/2426)was released as of 10.22.0. Closing this issue as a result.
