### ISSUE TITLE
Azcopy unable to perform 2 way sync in both directions- Source to Destination and Destination to Source. 

### ISSUE THREAD

**Issue by Dinesh6777** [Azure/azure-storage-azcopy#2378]
##### Note: The version is visible when running AzCopy without any argument
Latest
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
.\AzCopy.exe sync $sourceLocation  $targetLocation --recursive=$recursive --delete-destination=$deleteDestination 

### What problem was encountered?
Unable to perform 2 way sync- Source to Destination and Destination to Source. 
## Detailed Description: 
The synchronize action needs to make two folders mirror each other, keeping the latest changes made to the files in either folder. New and updated files are copied both ways. Renames and deletes on either side are repeated on the other. Folder Creates, folder deletes and folder updates are also propagated both ways.

• Every file in the Source folder that is new or changed is copied to the destination folder. 
• Every file in the Source folder that has been renamed is renamed in the destination folder. 
• Every file that was deleted from the Source folder is deleted in the destination folder. 
• The process is repeated for files in the destination folder.

**Comment by gapra-msft** [comment]
Hi @dinu99 in your use case do the source and destination change at the same time?

**Comment by dinu99** [comment]
Hi @gapra-msft - Yes, files can be updated either at the source or destination but during Sync only the latest change will be retained.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
