### ISSUE TITLE
AuthorizationError occurs when copying data between storage account (but copy is successful)

### ISSUE THREAD

**Issue by mageshwarm** [Azure/azure-storage-azcopy#2386]
### Which version of the AzCopy was used? 
10.20.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
`azcopy copy https://sa1.blob.core.windows.net/container1/source/input1?$SAS_TOKEN https://sa1.blob.core.windows.net/container1/target/output1?$SAS_TOKEN --recursive` 

### What problem was encountered?
For each azcopy copy command, it creates 3 AuthorizationError (GetAccountInformation, GetContainerProperties, CreateContainer). Even thought error recorded, copy operation is successful. But we have pipeline which uses this code to copy thousands of file, this leads us to creating lot of compliance issue.

Below screenshot taken after running 4 azcopy commands (total 12 error metric)
<img width="1432" alt="image" src="https://github.com/Azure/azure-storage-azcopy/assets/49895127/0e2571f9-8006-41c0-840b-403233d72372">

### How can we reproduce the problem in the simplest way?
Step 1: Create User delegation SAS Token with below javascript snippet code or configuration
```javascript
  const startsOn = new Date(new Date().valueOf() - 10 * 60 * 1000 ) // current - 10mins
  const expiresOn = new Date()
  expiresOn.setDate(expiresOn.getDate() + 5)
const delegationKey = await blobServiceClient.getUserDelegationKey(startsOn, expiresOn)
const sasToken = generateBlobSASQueryParameters({
         containerName,
        permissions: ContainerSASPermissions.parse('racwdltm'),
         startsOn, 
         expiresOn,
         protocol: SASProtocol.Https,
         version: '2021-10-04'
         
       },
       delegationKey,
       accountName
     )
console.log(containerSAS.toString())
```
Step 2: Copy data between storage account.
```bash
azcopy copy https://sa1.blob.core.windows.net/container1/source/input1?$SAS_TOKEN https://sa1.blob.core.windows.net/container1/target/output1?$SAS_TOKEN --recursive
```

### Have you found a mitigation/solution?
- No, we need to optimise the copy command code.

**Comment by nakulkar-msft** [comment]
Hi @mageshwarm, azcopy performs some of these calls to optimize the way we transfer. These errors are should be ignored.  This is by design and cannot be changed.

**Comment by mageshwarm** [comment]
Thank you @nakulkar-msft , I understand that, I am confirming that this errors are ignored. This error is not happening when we copy data from local to blob or blob to local. and occurring only when copy is happening when source and destination are blob containers. why is that?

**Comment by nakulkar-msft** [comment]
AzCopy allows transfers between accounts/container even when destination container does not exist. We attempt to create a destination container. Also, we try to check if the source is public, which is why you see other auth failure.

**Comment by mageshwarm** [comment]
@nakulkar-msft can we introduce flag to skip this validation?
