### ISSUE TITLE
Flag '--decompress' doesn't work in Linuх, but does in Windows

### ISSUE THREAD

**Issue by ramiros-ua** [Azure/azure-storage-azcopy#2392]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.20.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Red Hat Enterprise Linux release 8.2 (Ootpa)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy cp with flag '--decompress' both on Windows and Linux

### What problem was encountered?
no actual downloading, no errors in Linux

### How can we reproduce the problem in the simplest way?
1. Upload gz file with encoding-content
 azcopy cp ./test.file.gz https://mystorageaccount.blob.core.windows.net/backup/test/test.file.gz --content-encoding 'gzip'
2. Download in Windows - it works
 C:\temp\azcopy_windows_amd64_10.20.1\azcopy_windows_amd64_10.20.1\azcopy cp https://mystorageaccount.blob.core.windows.net/backup/test/test.file.gz ./ --decompress
...
Number of File Transfers Completed: 1
TotalBytesTransferred: 293739
Final Job Status: Completed

C:\temp\download> ls
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           9/29/2023  2:13 PM      104865792 test.file

3. Download in Linux - doesn't work
 azcopy cp https://mystorageaccount.blob.core.windows.net/backup/test/test.file.gz ./ --decompress
Number of File Transfers Completed: 1
TotalBytesTransferred: 293739
Final Job Status: Completed

echo $?
0

ls -l
total 0
ls -la
0 Sep 29 13:17 .azDownload-3a4d7cb4-b09b-c847-7377-eefbf4da1f9a-test.file

We can see, that in Linux azcopy has returned 0, but nothing downloaded, only temp hidden file of zero-size

### Have you found a mitigation/solution?
Workaround
do not use --decompress, and after downloading run gunzip

**Comment by heiner** [comment]
+1, `azcopy` with `--decompress` is broken in newer versions. 10.16.2 is the last version where this worked.

**Comment by gapra-msft** [comment]
Closing this issue as a PR was merged that will be released as part of 10.23.0 which will resolve this issue.
