### ISSUE TITLE
Azcopy 10 not working on our Windows azure servers while azcopy 8 does

### ISSUE THREAD

**Issue by c-petit** [Azure/azure-storage-azcopy#241]
### Which version of the AzCopy was used? 
10.0.7-Preview
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows server 2012 R2
### What command did you run?
azcopy.exe copy ThirdPartyNotice.txt "https://poccftlnx.blob.core.windows.net/iazrgbl0/recep/test?st=2018-11-19T08%3A45%3A51Z&se=2020-11-20T08%3A45%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=..."
### What problem was encountered?
file upload stay at pending, one cpu go to 100% until timeout or cancel.

### How can we reproduce the problem in the simplest way?
Don't know. Our server is hosted on azure on a private VLAN, The storage account access is for now unrestricted at the network level.
### Have you found a mitigation/solution?
The same upload is working fine on the same server with the azcopy 8.1.0 version :
this command is working :
C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy>azcopy /Source:"c:\temp\ThirdPartyNotice.txt" /Dest:"https://poccftlnx.blob.core.windows.net/iazrgbl0/recep/test?st=2018-11-19T08%3A45%3A51Z&se=2020-11-20T08%3A45%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=..."

**Comment by c-petit** [comment]
log file:
2019/02/28 09:25:02 AzcopVersion  10.0.7-Preview
2019/02/28 09:25:02 OS-Environment  windows
2019/02/28 09:25:02 OS-Architecture  amd64
2019/02/28 09:25:02 Job-Command copy ThirdPartyNotice.txt https://poccftlnx.blob.core.windows.net/iazrgbl0/recep/test?se=2020-11-20t08%3A45%3A00z&sig=REDACTED&sp=rwdl&sr=c&st=2018-11-19t08%3A45%3A51z&sv=2018-03-28 
2019/02/28 09:25:02 JobID=934f71c1-59e2-864b-4a2c-4025a9698aee, credential type: Anonymous
2019/02/28 09:25:02 scheduling JobID=934f71c1-59e2-864b-4a2c-4025a9698aee, Part#=0, Transfer#=0, priority=0
2019/02/28 09:25:02 INFO: [P#0-T#0] has worker 0 which is processing TRANSFER
2019/02/28 09:25:02 INFO: [P#0-T#0] Starting transfer: Source "ThirdPartyNotice.txt" Destination "https://poccftlnx.blob.core.windows.net/iazrgbl0/recep/test?se=2020-11-20t08%3A45%3A00z&sig=REDACTED&sp=rwdl&sr=c&st=2018-11-19t08%3A45%3A51z&sv=2018-03-28". Specified chunk size 8388608
2019/02/28 09:25:02 ==> OUTGOING REQUEST (Try=1)
   PUT https://poccftlnx.blob.core.windows.net/iazrgbl0/recep/test?se=2020-11-20t08%3A45%3A00z&sig=REDACTED&sp=rwdl&sr=c&st=2018-11-19t08%3A45%3A51z&sv=2018-03-28&timeout=901
   Content-Length: [14944]
   User-Agent: [AzCopy/10.0.7-Preview Azure-Storage/0.4 (go1.10.3; Windows_NT)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Type: [text/plain; charset=utf-8]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [08682b1c-02cd-42b5-5408-c005a1e31d0c]
   X-Ms-Version: [2018-03-28]

2019/02/28 09:27:44 JobID=934f71c1-59e2-864b-4a2c-4025a9698aee canceled
2019/02/28 09:27:44 ==> REQUEST/RESPONSE (Try=1/2m41.7190015s[SLOW >3s], OpTime=2m41.7199918s) -- REQUEST ERROR
   PUT https://poccftlnx.blob.core.windows.net/iazrgbl0/recep/test?se=2020-11-20t08%3A45%3A00z&sig=REDACTED&sp=rwdl&sr=c&st=2018-11-19t08%3A45%3A51z&sv=2018-03-28&timeout=901
   Content-Length: [14944]
   User-Agent: [AzCopy/10.0.7-Preview Azure-Storage/0.4 (go1.10.3; Windows_NT)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Type: [text/plain; charset=utf-8]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [08682b1c-02cd-42b5-5408-c005a1e31d0c]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-storage-azcopy/ste.newAzcopyHTTPClientFactory.func1.1, /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:100
HTTP request failed

Put https://poccftlnx.blob.core.windows.net/iazrgbl0/recep/test?se=2020-11-20T08%3A45%3A00Z&sig=ut104jrewSqAAx6Gg9fo06JpYbns8sqA0pgK89%2F7fbw%3D&sp=rwdl&sr=c&st=2018-11-19T08%3A45%3A51Z&sv=2018-03-28&timeout=901: context canceled

goroutine 37 [running]:
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.stack(0xc042136380, 0xc04225aa00, 0x0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_request_log.go:146 +0xae
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewRequestLogPolicyFactory.func1.1(0xbcd7e0, 0xc04224f860, 0xc04225b600, 0xb46827, 0xc, 0xb44d8b, 0xa)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_request_log.go:96 +0x66c
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc042084870, 0xbcd7e0, 0xc04224f860, 0xc04225b600, 0xa, 0xa8af20, 0xc04203c800, 0xc042519170)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0xbcd7e0, 0xc04224f860, 0xc04225b600, 0x79, 0xc0425191a0, 0x42bb5b, 0xb72f48)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:64 +0xef
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc042807520, 0xbcd7e0, 0xc04224f860, 0xc04225b600, 0xc0425191b0, 0xc042519270, 0x4e096a, 0xc04224f870)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0xbc7720, 0xc042807520, 0xc042052960, 0xbcd7e0, 0xc04224f860, 0xc04225b600, 0xc04224f870, 0xbcd760, 0xc042048440, 0x0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_responder_policy.go:34 +0x5a
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(0xbc7760, 0xc042807540, 0xbcd7e0, 0xc04224f860, 0xc04225b600, 0xfaba00, 0xbcd7e0, 0xc04224f860, 0xc0465ac780)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_credential_anonymous.go:54 +0x56
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0xbcd760, 0xc042048440, 0xc04225b500, 0xb4d61b, 0x16, 0xc046596f90, 0x24)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/xferRetrypolicy.go:362 +0x6c8
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0420848c0, 0xbcd760, 0xc042048440, 0xc04225b500, 0x24, 0x60b512, 0xab5dc0, 0xc0465a0cc0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0xbcd760, 0xc042048440, 0xc04225b500, 0xb450e7, 0xa, 0xc04201a900, 0x3e)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_unique_request_id.go:19 +0xa3
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc042807560, 0xbcd760, 0xc042048440, 0xc04225b500, 0x3e, 0xc042004c68, 0xc0465a0d20, 0xc042519690)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0xbcd760, 0xc042048440, 0xc04225b500, 0x1, 0x0, 0x1, 0xc042004c68)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_telemetry.go:34 +0xa5
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0465a0d20, 0xbcd760, 0xc042048440, 0xc04225b500, 0xc0465a0d20, 0xc042519700, 0x4119cc, 0xc042052968)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc042048400, 0xbcd760, 0xc042048440, 0xbc7780, 0xc042052960, 0xc04225b500, 0x1f, 0xc0420785d7, 0x14, 0x0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:128 +0x88
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.blockBlobClient.Upload(0xc0420785b0, 0x5, 0x0, 0x0, 0x0, 0xc0420785b8, 0x1f, 0xc0420785d7, 0x14, 0x0, ...)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_block_blob.go:421 +0x560
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.BlockBlobURL.Upload(0xc0420785b0, 0x5, 0x0, 0x0, 0x0, 0xc0420785b8, 0x1f, 0xc0420785d7, 0x14, 0x0, ...)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/url_block_blob.go:64 +0x252
github.com/Azure/azure-storage-azcopy/ste.(*blockBlobUploader).generatePutWholeBlob.func1()
	/go/src/github.com/Azure/azure-storage-azcopy/ste/uploader-blockBlob.go:157 +0x4d8
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0x19)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/uploader.go:104 +0xf4
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc0420740e0, 0x19)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:220 +0x97
created by github.com/Azure/azure-storage-azcopy/ste.initJobsAdmin
	/go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:173 +0x625

2019/02/28 09:27:44 INFO: [P#0-T#0] UPLOAD SUCCESSFUL
2019/02/28 09:27:44 JobID=934f71c1-59e2-864b-4a2c-4025a9698aee, Part#=0, TransfersDone=1 of 1
2019/02/28 09:27:44 all parts of Job 934f71c1-59e2-864b-4a2c-4025a9698aee successfully completed, cancelled or paused

**Comment by zezha-msft** [comment]
Hi @c-petit, thanks for reaching out!

Were there any proxy configuration that you made for V8?

**Comment by c-petit** [comment]
Hello,

Nothing from my part.
I'm not really familiar with Windows servers  .net and go (I'm more of a unix/java background)
when i run 'set', i don't see any environment variable looking like a proxy address
internet explorer have access to the blob and is configured to automatically detect settings , but when disabled, it still have internet access
my vm is using a private ip 
(Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . : reddog.microsoft.com
   Link-local IPv6 Address . . . . . : fe80::ed87:3901:b3f9:672e%12
   IPv4 Address. . . . . . . . . . . : 10.221.194.144
   Subnet Mask . . . . . . . . . . . : 255.255.255.192
   Default Gateway . . . . . . . . . : 10.221.194.129
) so i probably have NATed outbound internet connectivity.
the network card is eth2 which looks a bit weird, could it have an impact ?
what network configuration would a .net app use ?

**Comment by zezha-msft** [comment]
Hi @c-petit, it seems to be a configuration issue related to your environment. I'd suggest to reach out to Azure Support to see if they can help you sort it out.

**Comment by zezha-msft** [comment]
@c-petit please let us know if we can assist you with anything else.

**Comment by JohnRusk** [comment]
@c-petit I'd like to follow up with you on something related to this issue.  Could you please email me?  My email address can be found on my profile page.
