### ISSUE TITLE
custom headers

### ISSUE THREAD

**Issue by oriziv** [Azure/azure-storage-azcopy#242]
have a few questions:

How can i set custom metadata headers (such as "cache-control") when im copying to blob storage?
How can i set the blob to be gzipped when served to the client?

thanks

**Comment by zezha-msft** [comment]
Hi @oriziv, thanks for reaching out!

The custom blob properties like cache-control will be supported soon, it's definitely on our roadmap.

As for your second question, could you please clarify what do you mean? Would you like to gzip a file before right sending it to Storage (without creating an intermediate zipped file)? We do have piping support for blob uploads/downloads, please refer to the help message `./azcopy cp --help` to see an example.

**Comment by iclanton** [comment]
Any word on when custom headers will be added?

**Comment by adreed-msft** [comment]
Hi, this was added in release v10.1.2. Enjoy!
