### ISSUE TITLE
Error copying files with certain unicode characters

### ISSUE THREAD

**Issue by simonmerrell** [Azure/azure-storage-azcopy#2421]
### Which version of the AzCopy was used? 
10.18.1, 10.21.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2019, Windows 10

### What command did you run?
azcopy copy X:\folder https://storage.blob.core.windows.net/container/folder/?se=REDACTED --recursive --log-level=ERROR --overwrite=ifSourceNewer

### What problem was encountered?
 RESPONSE Status: 400 Bad Request

 UPLOADFAILED: \\?\X:\folder\file_.txt : 000 : Could not check destination file existence. -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42

It seems that certain special characters (unicode) do not work with Azcopy, even when not listed as a character to be avoided in the naming standards [here](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#unicode-characters-not-recommended-for-use-in-container-or-blob-names).

The following unicode characters are causing my Azcopy jobs to fail:
U+007F
U+0081
U+008D
U+008F
U+009D

These are not listed as prohibited unicode characters (or characters to be avoided)

I have many similar errors, I'm slowly trying to work through them and identify which are the problem unicode characters.

### How can we reproduce the problem in the simplest way?
Create a file with the above unicode characters in the filename and try to azcopy them

### Have you found a mitigation/solution?
No, this is quite a tricky problem when trying to azcopy millions of files, first need to develop a process to identify all the problem unicode values and then rename them. Would be great if Azcopy could copy more of these files.

**Comment by simonmerrell** [comment]
I tried to upload these same problem files using PowerShell, and I get a similar failure

e.g. 
`Get-ChildItem "C:\unicode" -File -Recurse | Set-AzStorageBlobContent -Container $container -Context $storageContext`

And the files are failing to upload, with a message such as :
```
Set-AzStorageBlobContent : Bad Request HTTP Status Code: 400 - HTTP Error Message: Bad Request
ErrorCode: 
ErrorMessage: Bad Request
RequestId: 
```

So I don't know if this is really a problem with Azcopy or is it simply that these chars are not supported with Blob storage and the documentation needs to be updated?

**Comment by gapra-msft** [comment]
[Here ](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#unicode-characters-not-recommended-for-use-in-container-or-blob-names)is a list of unsupported unicode characters for blob storage.

**Comment by gapra-msft** [comment]
Closing as this is not an AzCopy issue
