### ISSUE TITLE
Getting Inconsistent 403s (CannotVerifyCopySource) 

### ISSUE THREAD

**Issue by BHC3-KevinFaneca** [Azure/azure-storage-azcopy#2422]
### Which version of the AzCopy was used? 
azcopy version 10.21.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

#### Run batch copy (apologies here - needed to block out a lot of the commands)
`azcopy <some s3 URI> <some storage location path> --recursive`

![image](https://github.com/Azure/azure-storage-azcopy/assets/81317611/489af4d8-b679-43fa-bc84-8e48fd84f923)

#### Then on the file that failed to copy
`azcopy <s3 file URI> <some storage location path>`

![image](https://github.com/Azure/azure-storage-azcopy/assets/81317611/aee74677-0c9f-4210-ba83-31f7dbe271dd)

### What problem was encountered?
I run a copy job and it fails with a 403 (CannotVerifyCopySource) on a random file.  I can then successfully copy that file individually.  I can repeat this process and resume the copy job and it will fail on another random file.  I can then successfully copy that file individually.  I have also experienced failing to copy a single file with the above error, then immediately being able to successfully copy it.  The frequency of failures is also inconsistent.  What is consistent is that I am logged into Azcopy, have valid credentials for AWS, have the appropriate environment variables set, and have the appropriate role applied to write to Azure storage, but I get these intermittent 403s.  Any insights would be greatly appreciated ☺️ .  I have seen the other posts too - my files end in `.csv` and there are no metadata issues on the files I have encountered. 

### How can we reproduce the problem in the simplest way?
Have files stored in S3
Have an Azure storage account
Login to Azcopy
Get credentials for AWS 
Store credentials in environment variables
Try to copy a group of files (or a single file - this is inconsistent)

### Have you found a mitigation/solution?
Not really 😕 .  You can write a script to resume the copy job and loop until it completes.  However I want to move a large amount of files and this approach just isn't feasible.

**Comment by nakulkar-msft** [comment]
Hi @BHC3-KevinFaneca, do you have a firewall on the source?

**Comment by BHC3-KevinFaneca** [comment]
> Hi @BHC3-KevinFaneca, do you have a firewall on the source?

Actually meant to reach out yesterday.  The issue was my bucket policy in S3.  There was a deny on Pre-signed URLs with signatures older than a certain age.  Working now!
