### ISSUE TITLE
Unable to delete/remove container

### ISSUE THREAD

**Issue by manuvaldi** [Azure/azure-storage-azcopy#2427]
### Which version of the AzCopy was used? 
azcopy version 10.21.0

##### Note: The version is visible when running AzCopy without any argument
Yes

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy rm https://xxxxxxx.blob.core.windows.net/bucket 

### What problem was encountered?
Unable to remove container

### How can we reproduce the problem in the simplest way?

azcopy makehttps://xxxxxxx.blob.core.windows.net/bucket 
azcopy rm https://xxxxxxx.blob.core.windows.net/bucket 

### Have you found a mitigation/solution?

Use az cli to delete container

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
