### ISSUE TITLE
File Creation Error: too many open files

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-storage-azcopy#243]
### Which version of the AzCopy was used? 

AzCopy 10.0.7-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

```
./azcopy_linux_amd64_10.0.7/azcopy copy \
   --preserve-last-modified-time \
   --recursive \
   "${URL}" \
   ./cdr
```

### What problem was encountered?

Half the job failed. Looking at the log, there are errors like so:

```
2019/02/28 12:51:44 ERR: [P#0-T#3930] DOWNLOADFAILED: [REDACTED] : 
000 : File Creation Error open ./cdr/cdr/[REDACTED]: too many open files
```

### How can we reproduce the problem in the simplest way?

The storage account many small files, `9,068 blobs; 127,597,455 bytes` to be exact.

I can only guess `azcopy` does not close locally opened files in timely manner and we are hitting the limits.

Currently `ulimit` reports my user is allowed 1024 open files.

### Have you found a mitigation/solution?

Potentially can use `ulimit` to increase the number of allowed opened files, but this generally requires `root` for large values.

I did increase opened files to `4096` (the max value allowed to non-root users on that box) and still hit the same issue, although the number of failures was smaller this time.

-----

This is potentially related to #209 , as in a resource leak

**Comment by JohnRusk** [comment]
Thanks for logging this @ppanyukov.  What are the approx. specs of the machine you're running it on: number of CPUs in particular, and is it an Azure VM or something on-premises?

**Comment by JohnRusk** [comment]
BTW, this is unlikely to be related to #209, since 209 was an upload and this here is a download.  The open file count characteristics are different between upload and download.

**Comment by JohnRusk** [comment]
BTW In my testing, /proc/<pid>/limits for a running instance of AzCopy shows that the limit has been increased to the hard limit. 
E.g. 
`ulimit -n` returns `1024`; `ulimit -Hn` returns `1048576` and it is the latter which is reported by /proc/<pid>/limits.  So it looks like something - presumably in AzCopy - is moving the soft limit up to the hard limit. But that doesn't help if AzCopy is doing something that exceeds the hard limit. So I'll look now at controlling more closely the number of active file handles used by AzCopy when moving small files.

**Comment by JohnRusk** [comment]
It turns out the limit affects AzCopy in two ways: one in the count of the number of files, and one in the count of the number of active TCP connections. (Both count as files on Linux). I've found a solution to the former, and will work on the latter next week. Thanks again for logging this Philip.

**Comment by ppanyukov** [comment]
Just to confirm, yes `4096` is the hard limit on the box.

FYI, we are on Centos/RHEL, I suspect you must be on Ubuntu or something so there will be differences.

So on Centos7 default hard limit seems to be `4096`.  On some older boxes we have it even lower: `1024`. 

Perhaps this needs to be taken into consideration.

**Comment by JohnRusk** [comment]
We have a solution for the second half of the problem (number of TCP connections) too. Should be included in next release (after 10.0.8).

**Comment by zezha-msft** [comment]
Hi @ppanyukov, the fix has been released in 10.0.9. Please feel free to give it try. Thank you!

**Comment by Will-Bill** [comment]
I am having this same issue using 10.2.1. I am using macOS. ulimit is unlimited. Working fine on Windows.

My CMD:
.\azcopy cp "source" "dest" --recursive=true 

Error:

Job 0bce51fd-48da-4342-6d14-7c4ef2221479 has started
Log file is located at: /Users/bill/.azcopy/0bce51fd-48da-4342-6d14-7c4ef2221479.log

1496 Done, 0 Failed, 8504 Pending, 0 Skipped, 10000 Total (scanning...), 2-sec Throughput (Mb/s): 1395.1759panic: couldn't create job part plan file "0bce51fd-48da-4342-6d14-7c4ef2221479--00001.steV7": open /Users/bill/.azcopy/plans/0bce51fd-48da-4342-6d14-7c4ef2221479--00001.steV7: too many open files

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/ste.JobPartPlanFileName.Create(0xc003a00080, 0x31, 0xbce51fd00000000, 0x4e7c146d434248da, 0x1791422f2, 0x30300000100, 0xc0000d4c90, 0xc0000d4cc0, 0x0, 0x0, ...)
	/Users/vsts/agent/2.153.2/work/1/s/ste/JobPartPlanFileName.go:124 +0x1e15
github.com/Azure/azure-storage-azcopy/ste.ExecuteNewCopyJobPartOrder(0xbce51fd00000000, 0x4e7c146d434248da, 0x1791422f2, 0x30300000100, 0xc0000d4c90, 0xc0000d4cc0, 0x0, 0x0, 0x0, 0xc0000c83c0, ...)
	/Users/vsts/agent/2.153.2/work/1/s/ste/init.go:142 +0xaa
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0x473b966, 0x10, 0x462dfa0, 0xc000152500, 0x462dfe0, 0xc000b42680, 0x2701, 0xc000b42680)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/rpc.go:44 +0xa14
github.com/Azure/azure-storage-azcopy/cmd.glob..func3(0x473b966, 0x10, 0x462dfa0, 0xc000152500, 0x462dfe0, 0xc000b42680)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/rpc.go:36 +0x5d
github.com/Azure/azure-storage-azcopy/cmd.addTransfer(0xc000152500, 0xc0064131cf, 0x10, 0xc005f96515, 0x10, 0x0, 0xecd7902fc, 0x4d6c760, 0x32a25, 0xc000d95626, ...)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copyEnumeratorHelper.go:31 +0x27d
github.com/Azure/azure-storage-azcopy/cmd.(*copyS2SMigrationBlobEnumerator).addTransfer(...)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copyS2SMigrationBlobEnumerator.go:287
github.com/Azure/azure-storage-azcopy/cmd.(*copyS2SMigrationBlobEnumerator).addBlobToNTransfer(0xc000152500, 0xc0000c8390, 0x5, 0x0, 0x0, 0x0, 0xc0000c8398, 0x1f, 0xc007890f80, 0x18, ...)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copyS2SMigrationBlobEnumerator.go:242 +0x2c3
github.com/Azure/azure-storage-azcopy/cmd.(*copyS2SMigrationBlobEnumerator).addTransfersFromContainer.func2(0x0, 0x0, 0xc000d9550c, 0x4, 0xc000d95540, 0xf, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copyS2SMigrationBlobEnumerator.go:231 +0x36f
github.com/Azure/azure-storage-azcopy/cmd.enumerateBlobsInContainer(0x487e800, 0xc000026090, 0xc0000c8390, 0x5, 0x0, 0x0, 0x0, 0xc0000c8398, 0x1f, 0xc000c5e078, ...)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copyEnumeratorHelper.go:189 +0x2ba
github.com/Azure/azure-storage-azcopy/cmd.(*copyS2SMigrationBlobEnumerator).addTransfersFromContainer(0xc000152500, 0x487e800, 0xc000026090, 0xc0000c8390, 0x5, 0x0, 0x0, 0x0, 0xc0000c8398, 0x1f, ...)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copyS2SMigrationBlobEnumerator.go:217 +0x1fc
github.com/Azure/azure-storage-azcopy/cmd.(*copyS2SMigrationBlobEnumerator).enumerate(0xc000152500, 0xc000822000, 0x35, 0x25)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copyS2SMigrationBlobEnumerator.go:128 +0x113f
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc000822000, 0x1, 0x0)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copy.go:906 +0xdc1
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc000822000, 0x147, 0xb)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copy.go:579 +0x8a
github.com/Azure/azure-storage-azcopy/cmd.init.1.func2(0xc0001bf180, 0xc0000b1950, 0x2, 0x3)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/copy.go:1140 +0x196
github.com/spf13/cobra.(*Command).execute(0xc0001bf180, 0xc0000b1890, 0x3, 0x3, 0xc0001bf180, 0xc0000b1890)
	/Users/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x4d66e00, 0x7fffffffffffffff, 0x100, 0x7fffffffffffffff)
	/Users/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc000128620, 0x13, 0xc000128620, 0x13, 0x100)
	/Users/vsts/agent/2.153.2/work/1/s/cmd/root.go:85 +0x88
main.main()
	/Users/vsts/agent/2.153.2/work/1/s/main.go:60 +0x211

**Comment by JohnRusk** [comment]
@Will-Bill Since this issue thread is already closed (and yours relates specifically to MacOS) I have created a new issue #556 to track yours, and will respond to you there.
