### ISSUE TITLE
azcopy has vulnerability GHSA-m425-mq94-257g due to a library it uses #6703

### ISSUE THREAD

**Issue by fouomene** [Azure/azure-storage-azcopy#2431]
##### Note: The version is visible when running AzCopy without any argument

AzCopy 10.21.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

Scan high image vuln with trivy, in an image that contains the latest version of azcopy downloaded (curl -L https://aka.ms/downloadazcopy-v10-linux ) and installed

### What problem was encountered?

AzCopy is built with go and the google.golang.org/grpc  library has a vulnerability:  https://github.com/advisories/GHSA-m425-mq94-257g

### How can we reproduce the problem in the simplest way?

Scan high image vuln with trivy.

./trivy image --severity HIGH --exit-code=1  name_image

Report : 
usr/local/bin/azcopy (gobinary)
Library  :   google.golang.org/grpc
Vulnerability  :   GHSA-m425-mq94-257g
Severity :  HIGH
Installed Version :  v1.53.0   
**Fixed Version : 1.56.3, 1.57.1, 1.58.3** 
Title  : gRPC-Go HTTP/2 Rapid Reset vulnerability ,  https://github.com/advisories/GHSA-m425-mq94-257g

### Have you found a mitigation/solution?

build AzCopy with library  google.golang.org/grpc  fixed version : 1.56.3, 1.57.1, 1.58.3

**Comment by gapra-msft** [comment]
Hi @fouomene I have a PR out upgrading this dependency, https://github.com/Azure/azure-storage-azcopy/pull/2432

This will be fixed in our next release.

**Comment by gapra-msft** [comment]
Closing this issue for now since it will be fixed in our next release.

**Comment by rene-leanix** [comment]
@gapra-msft, would you be able to propagate this fix to your `@azure-tools/azcopy-*` packages? It's currently not available for us on `@azure-tools/azcopy-node`.
