### ISSUE TITLE
AZCopy 10 does not work but AZCopy 8 does

### ISSUE THREAD

**Issue by scsummers** [Azure/azure-storage-azcopy#244]
I am interested in testing AZCopy 10 for things like skipping existing files, copying empty directories.

This command works with AZCopy 8 where Source is a local file path (e.g. D:\Test), destination is a file share.

AZCopy /Source:"%Source%" /Dest:"%Http%/%Dest%" /DestKey:%Key% /V:"%Log%" /Z:"%Journal%" /S /Y

Tried this command line with AZCopy 10 and it starts the upload but every file fails where

AZCopy cp D:\Test  https://ptsdatatransfer.file.core.windows.net/ptsfileshare01/CWSRV1/Apps?<sastoken> --recursive=true

They all fail with this sort of error.

2019/02/28 21:03:36 INFO: [P#0-T#276] Starting transfer: Source "d:///Test/temp/1288409109365/components.xml.2011-12-16-22-00-00-000.ADD" Destination "https://ptsdatatransfer.file.core.windows.net/ptsfileshare01/CWSRV1/Apps/Test/temp/1288409109365/components.xml.2011-12-16-22-00-00-000.ADD?2cTsulLNNKpUFGdv%2FXeMZcXIiaN1d6emJ2l3xZpQ6qjLKR8xnSfwnUp1P%2FhqQ+QlOIPVqYDzmOEgErKVesWyDA=%3D". Specified chunk size 4194304
2019/02/28 21:03:36 ERR: [P#0-T#244] UPLOADFAILED: d:///Test/temp/1288409109365/writers.xml.2011-11-21-22-00-00-000.ADD : 404 : 404 The specified resource does not exist. when Creating parent directory
   Dst: https://ptsdatatransfer.file.core.windows.net/ptsfileshare01/CWSRV1/Apps/Test/temp/1288409109365/writers.xml.2011-11-21-22-00-00-000.ADD?2cTsulLNNKpUFGdv%2FXeMZcXIiaN1d6emJ2l3xZpQ6qjLKR8xnSfwnUp1P%2FhqQ+QlOIPVqYDzmOEgErKVesWyDA=%3D
2019/02/28 21:03:36 ERR: [P#0-T#235] UPLOADFAILED: d:///Test/temp/1288409109365/components.xml.2011-12-01-22-00-00-000.ADD : 404 : 404 The specified resource does not exist. when Creating parent directory
   Dst: https://ptsdatatransfer.file.core.windows.net/ptsfileshare01/CWSRV1/Apps/Test/temp/1288409109365/components.xml.2011-12-01-22-00-00-000.ADD?2cTsulLNNKpUFGdv%2FXeMZcXIiaN1d6emJ2l3xZpQ6qjLKR8xnSfwnUp1P%2FhqQ+QlOIPVqYDzmOEgErKVesWyDA=%3D
2019/02/28 21:03:36 INFO: [P#0-T#277] has worker 20 which is processing TRANSFER
2019/02/28 21:03:36 INFO: [P#0-T#278] has worker 53 which is processing TRANSFER
2019/02/28 21:03:36 WARN: [P#0-T#278] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
2019/02/28 21:03:36 ==> REQUEST/RESPONSE (Try=1/30.0017ms, OpTime=30.0017ms) -- RESPONSE SUCCESSFULLY RECEIVED
   DELETE https://ptsdatatransfer.file.core.windows.net/ptsfileshare01/CWSRV1/Apps/Test/temp/1288409109365/Microsoft%20Exchange%20Server/Microsoft%20Information%20Store/CWSRV1/Mailbox%20Database%200090690103/E000003E72E.log.2011-11-16-22-00-00-000.ADD?2cTsulLNNKpUFGdv%2FXeMZcXIiaN1d6emJ2l3xZpQ6qjLKR8xnSfwnUp1P%2FhqQ+QlOIPVqYDzmOEgErKVesWyDA=%3D&timeout=121
   User-Agent: [AzCopy/10.0.7-Preview Azure-Storage/0.4.1 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [85d6b10e-2f71-4797-7168-ddfd38eb3fdf]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified resource does not exist.
   Content-Length: [223]
   Content-Type: [application/xml]
   Date: [Thu, 28 Feb 2019 21:03:35 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [ResourceNotFound]
   X-Ms-Request-Id: [de489086-e01a-00c3-3aa9-cf79de000000]
   X-Ms-Version: [2018-03-28]

2019/02/28 21:03:36 WARN: [P#0-T#274] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
2019/02/28 21:03:36 ==> OUTGOING REQUEST (Try=1)
   GET https://ptsdatatransfer.file.core.windows.net/ptsfileshare01/CWSRV1/Apps/Test/temp/1288409109365?2cTsulLNNKpUFGdv%2FXeMZcXIiaN1d6emJ2l3xZpQ6qjLKR8xnSfwnUp1P%2FhqQ+QlOIPVqYDzmOEgErKVesWyDA=%3D&restype=directory&timeout=901
   User-Agent: [AzCopy/10.0.7-Preview Azure-Storage/0.4.1 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [fd70ad7c-438d-41d4-74a4-99dc98d330ca]
   X-Ms-Version: [2018-03-28]

**Comment by scsummers** [comment]
Anyone out there???

**Comment by zezha-msft** [comment]
Hi @scsummers, thanks for reaching out! And sorry for the delayed response.

To clarify, AzCopy V10 does not support Shared Keys for authentication because they have admin privileges and shouldn't be passed around on the command line.

Could you please verify that you've included a valid SAS? What is this string `2cTsulLNNKpUFGdv%2FXeMZcXIiaN1d6emJ2l3xZpQ6qjLKR8xnSfwnUp1P%2FhqQ+QlOIPVqYDzmOEgErKVesWyDA=%3D`? The easiest way to generate a SAS is through the [Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/). Please refer to `./azcopy cp --help` for examples on how to use the copy command. 

You could also use OAuth to authenticate against the Storage service (you can login via `./azcopy login`)
