### ISSUE TITLE
Failed to download the azure container to linux empty directory

### ISSUE THREAD

**Issue by MadalasaP** [Azure/azure-storage-azcopy#2450]
### Which version of the AzCopy was used? 
azcopy version 10.21.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Oracle Linux 7.9

### What command did you run?
azcopy copy --put-md5 'https://bryck.blob.core.windows.net/test2/?' '/bryck/cloud_test_data2' --recursive=true
src contains: 'https://bryck.blob.core.windows.net/test2/test3/files

### What problem was encountered?
DOWNLOADFAILED: https://bryck.blob.core.windows.net/mobility-transfer-test/cloud_test_data/test_file.9 : 000 : failed to write xattr: operation not supported; consider utilizing an OS-agnostic hash storage mode. When saving MD5 data (writing alternate data stream). X-Ms-Request-Id:

### How can we reproduce the problem in the simplest way?
Download data from azcopy to Linux with the above azcopy version

### Have you found a mitigation/solution?
No

**Comment by gapra-msft** [comment]
Hi @MadalasaP from the error message, it sounds like your system does not support setting xattr. Also is your goal to save the md5 locally? From the [documentation](https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy), AzCopy only supports --put-md5 for uploads. 
**--put-md5 Create an MD5 hash of each file, and save the hash as the Content-MD5 property of the destination blob or file. (By default the hash is NOT created.) Only available when uploading.**

If your intention is to validate the md5, AzCopy has another flag --check-md5 which you can set to the following NoCheck, LogOnly, FailIfDifferent, FailIfDifferentOrMissing. FailIfDifferent is the default value.

**Comment by gapra-msft** [comment]
Tagging this as a usability/error messages item to improve the error resurfaced to the customer

**Comment by gapra-msft** [comment]
Hi @MadalasaP, in this scenario, does the remote source contain md5 metadata?

**Comment by gapra-msft** [comment]
Closing due to lack of customer activity. Please feel free to reopen once you've shared an answer to the above if you are still experiencing problems.
