### ISSUE TITLE
Cannot set cache-control property using azcopy setprops

### ISSUE THREAD

**Issue by philippn** [Azure/azure-storage-azcopy#2451]
### Which version of the AzCopy was used? 
10.21.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy set-properties --metadata "Cache-Control=max-age=604800" --recursive "https://xxx.blob.core.windows.net/$web/container?sas"

### What problem was encountered?
I'm trying to set the Cache-Control header for all the files in a container, but it doesn't work. Possibly because of the = in the property value?

Noteworthy: The metadata key value pair is parsed correctly by AzCopy; But the requests posted to the Azure Blob service return this HTTP error:

Response Details: ﻿<Code>InvalidMetadata</Code><Message>The metadata specified is invalid. It has characters that are not permitted. </Message>

This error appears in the log file for every file in the container.

### How can we reproduce the problem in the simplest way?
Try to update the cache-Control property in the same way

### Have you found a mitigation/solution?
No

Thanks in advance for looking into this!

**Comment by gapra-msft** [comment]
Hi @philippn I think the issue here is actually the dash in the key (Cache-Control) 

[This ](https://learn.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata?tabs=microsoft-entra-id#request-headers)page indicates that the metadata names must adhere to the naming rules for [C# identifiers](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference).

**Comment by philippn** [comment]
Hi @gapra-msft ,

so umm how am I supposed to set this metadata property then?

**Comment by gapra-msft** [comment]
@philippn you will need to modify the metadata key to match the Azure Storage service guidelines that I linked above.

**Comment by philippn** [comment]
Hi @gapra-msft ,

I have tried that, but it doesn't work as expected.

When I try the command `azcopy set-properties --metadata "CacheControl=max-age=604800" --recursive "https://xxx.blob.core.windows.net/$web/container?sas"`, it doesn't fail. But the metadata is not applied to the built-in CacheControl property.

![cachecontrol](https://github.com/Azure/azure-storage-azcopy/assets/445105/e9388a31-ec57-4d4c-9aaa-f065c7ff7704)

**Comment by vibhansa-msft** [comment]
Setting http header properties will not be in our priority list soon. We will add this item to our backlog though. Closing this item here.
