### ISSUE TITLE
az storage copy does not work with directory symlinks using relative path

### ISSUE THREAD

**Issue by yhzs8** [Azure/azure-storage-azcopy#2459]
### Which version of the AzCopy was used? 
10.13.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (Centos 7)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it 
```
cd /tmp
az storage copy -s 'test2/*' -d  <url> --recursive --follow-symlinks --debug
```

### What problem was encountered?
With the below folder structure (relative path in the directory symlinks)
```
tmp
  test1
    parent1
      child1
        child1.txt
  test2
    parent2
      symlink to ../../test1/parent1/child1 (created by "ln -s ../../test1/parent1/child1")
```
After `az storage copy`, on the target file system `parent2` folder will be empty

With the debug log enabled it also printed out the following
```
INFO: Ignored already linked directory pointed at /tmp/test2/parent2 (link at /tmp/test2/parent2/child1)
```

but with the following absolute path directory symlinks:
```
tmp
  test1
    parent1
      child1
        child1.txt
  test2
    parent2
      symlink to /tmp/test1/parent1/child1 (created by "ln -s /tmp/test1/parent1/child1")
```
it will work (`parent2/child1/child1.txt` exists)

The INFO logging printed out for the failed case was not seen here.

### How can we reproduce the problem in the simplest way?
use the above simple folder structure

### Have you found a mitigation/solution?
use absolute path in the directory symlink

**Comment by gapra-msft** [comment]
Hi @yhzs8 Could you upgrade to the latest version of AzCopy and let us know if this works?

**Comment by yhzs8** [comment]
Hi @gapra-msft  yes upgraded to `10.21.2` and it seems working now, closing this ticket
