### ISSUE TITLE
Discussion: should we aim for `rsync`-like interface and features?

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-storage-azcopy#246]
**Version**: `/azcopy_linux_amd64_10.0.7/azcopy`
**Platform**: Linux

--------

I wanted to raise this with regards to:

- interface: the command line switches
- features: what is actually possible with this tool
- behaviour: how this tool actually works

It's somewhat biased towards Linux as this is what my current
experience is with.

All this in the hope to make this tool even more betterer and more awesomer :) 

---------

The `azcopy` essentially aims to do exactly same job as `rsync`, the only difference
being "Azure Blob Storage" instead of "rsync/ssh". People on Linux platform will be
familiar with `rsync` -- it is a very well known and established tool (since 1996). 
It's available even on Windows, via git bash I'm sure.

Since `rsync` is such a battle-hardened and tested tool for countless real-life
production scenarios, it's probably worth having a look at its interface, features,
and behaviour; and see what is applicable to `azcopy`.

The benefits of matching `azcopy` to `rsync` are numerous, some are:

- They probably found a satisfactory solution to most of the required
  features etc.  Why not borrow their solution?

- There are **so many** really useful features in `rsync`, they can be
  an inspiration for roadmap, e.g. `--dry-run`, `--list-only`, 
  `--backup`, `--inplace`, `--checksum-choice`, and `--bwlimit` options.

- The features of `rsync` had a good test in real life. Chances are they
  probably were actually needed and they probably got it more or less right.

- People already familiar with `rsync` will find `azcopy` much easier to
  use if the two work pretty much the same.

- There really isn't a need for separate `cp` and `sync` commands if
  we follow `rsync`.

- There are a few open issues which either ask for features
  present in `rsync` or get puzzzled when behaviour does not match
  what `rsync` would do. Just a couple here as an example:

  - Support batch jobs (https://github.com/Azure/azure-storage-azcopy/issues/196),
    solved with `--exclude=PATTERN`, `--exclude-from=FILE`, `--include=PATTERN`,
    `--include-from=FILE `, `--files-from=FILE` in `rsync`.

  - Various proposals to use flags like `--purge` and `--check-lmt` as in
    https://github.com/Azure/azure-storage-azcopy/issues/220.
    These are addressed in `rsync` by `--delete` and `--ignore-times` options.

  - Logging. Complex issue but may be worth looking at how `rsync` does it.

Reference links:

- Main man page: https://ss64.com/bash/rsync.html
- Brief summary of interface (command line options): https://ss64.com/bash/rsync.html
- Full list of options: https://ss64.com/bash/rsync_options.html

For completeness, here is the "Brief summary of interface" copypasta:

--------

```
OPTIONS SUMMARY

MAKE SURE TO LOOK AT FULL LIST AS THERE ARE **TONS** MORE.
FULL LIST: https://ss64.com/bash/rsync_options.html


    Here is a short summary of the options available in rsync.
    Please refer to the FULL List of OPTIONS for a complete description.

    What to copy:
     -r, --recursive             recurse into directories
     -R, --relative              use relative path names
         --exclude=PATTERN       Exclude files matching PATTERN
         --exclude-from=FILE     Read exclude patterns from FILE
     -I, --ignore-times          Don't exclude files that match length and time
         --size-only             only use file size when determining if a file should be transferred
     -@  --modify-window=NUM     Timestamp window (seconds) for file match (default=0)
         --include=PATTERN       Don't exclude files matching PATTERN
         --include-from=FILE     Read include patterns from FILE

    How to copy it:
     -n, --dry-run               Perform a trial run with no changes made
     -l, --links                 Copy symlinks as symlinks
     -L, --copy-links            Transform symlink into referent file/dir
         --copy-unsafe-links     Only "unsafe" symlinks are transformed
         --safe-links            Ignore links outside the destination tree
         --munge-links           Munge symlinks to make them safer
     -H, --hard-links            Preserve hard links
         --devices               preserve device files (super-user only)
         --specials              preserve special files
     -D, --devices --specials    Preserve devices (super-user only) +files
     -g, --group                 Preserve group
     -o, --owner                 Preserve owner (super-user only)
     -p, --perms                 Preserve permissions
         --remove-source-files   Sender removes synchronized files (non-dir)
     -t, --times                 Preserve times
     -S, --sparse                Handle sparse files efficiently
     -x, --one-file-system       Don't cross filesystem boundaries
     -B, --block-size=SIZE       Force a fixed checksum block-size (default 700)
     -e, --rsh=COMMAND           Specify rsh replacement
         --rsync-path=PATH       Specify path to rsync on the remote machine
         --numeric-ids           Don't map uid/gid values by user/group name
         --timeout=SECONDS       Set IO timeout in seconds
     -W, --whole-file            Copy whole files, no incremental checks

    Destination options:
     -a, --archive               Archive mode equals -rlptgoD (no -H,-A,-X)
     -b, --backup                Make backups (see --suffix & --backup-dir)
         --backup-dir=DIR        Make backups into this directory
     -z, --compress              Compress file data during the transfer
     -c, --checksum              Skip based on checksum, not mod-time & size
     -C, --cvs-exclude           Auto ignore files in the same way CVS does
         --existing              Only update files that already exist
         --delete                Delete files that don't exist on the sending side
         --delete-excluded       also delete excluded files on the receiving side
         --delete-after          Receiver deletes after transfer, not during
         --force                 Force deletion of directories even if not empty
         --ignore-errors         Delete even if there are IO errors
         --max-delete=NUM        Don't delete more than NUM files
         --log-file-format=FMT   Log file transfers using specified format
         --partial               Keep partially transferred files
         --progress              Show progress during transfer
     -P                          equivalent to --partial --progress
         --stats                 Give some file transfer stats
     -T  --temp-dir=DIR          Create temporary files in directory DIR
         --compare-dest=DIR      also compare destination files relative to DIR
     -u, --update                update only (don't overwrite newer files)

    Misc Others:
         --address=ADDRESS       bind to the specified address
         --blocking-io           Use blocking IO for the remote shell
         --bwlimit=KBPS          Limit I/O bandwidth, KBytes per second
         --config=FILE           Specify alternate rsyncd.conf file (daemon)
         --daemon                Run as a rsync daemon
         --no-detach             Do not detach from the parent (daemon)
         --password-file=FILE    Get daemon-access password from FILE
         --port=PORT             Specify alternate rsyncd port number
     -f, --read-batch=FILE       Read batch file
     -F, --write-batch=FILE      Write batch file
         --version               Print version number
     -v, --verbose               Increase verbosity
     -q, --quiet                 Decrease verbosity
     -4, --ipv4                  Prefer IPv4
     -6, --ipv6                  Prefer IPv6
     -h, --help                  show this help screen
```

-------

**Comment by zezha-msft** [comment]
Hi @ppanyukov, thank you so much for this feedback!

I've tagged our PMs to have a look.

**Comment by artemuwka** [comment]
Thanks for the suggestion @ppanyukov! Makes perfect sense to me and we'll need to take a closer look at this once we reach general availability. Added this to our triage items.

**Comment by mohsha-msft** [comment]
Since the discussion started, we have evolved as a product and are supporting a bunch of features now. Please take a look and share your feedback on how we can improve further.
