### ISSUE TITLE
Failed files on first run of copy corrupt the stats of the job on resume

### ISSUE THREAD

**Issue by lukasz-krzykowski** [Azure/azure-storage-azcopy#2461]
### Which version of the AzCopy was used? 

10.21.2 (latest stable at the moment) 

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

For starting the job:
```
azcopy.exe copy C:\SourceCode\DTX\__data_sets\custom\small\csv-and-word "https://skynetadls.blob.core.windows.net/dev/resume-test?sv=2021-06-08&spr=https&st=2022-10-01T07%3A58%3A10Z&se=2023-12-31T16%3A58%3A10Z&si=testReadWritePolicy&sr=c&sig=REDACTED" --recursive --output-type json
```

For resuming the job:

```
azcopy.exe jobs resume c782cc04-57fd-734c-4978-6b05f9b56532 --output-type json --destination-sas "sv=2021-06-08&spr=https&st=2022-10-01T07%3A58%3A10Z&se=2023-12-31T16%3A58%3A10Z&si=testReadWritePolicy&sr=c&sig=REDACTED"
```

### What problem was encountered?

When job completed:
- failed files from previous run of this job were reported as failed, despite the fact that they were successfully transferred on this second attempt on the job (resume)
- percentage complete was miscalculated (it shows more than 100%)

Produced output after running resume on the job:

```
{"TimeStamp":"2023-11-21T12:46:36.196641+01:00","MessageType":"EndOfJob","MessageContent":"{\"ErrorMsg\":\"\",\"JobID\":\"98442a2e-e7f1-9945-5568-d251ef2e5ad6\",\"ActiveConnections\":\"0\",\"CompleteJobOrdered\":true,\"JobStatus\":\"Completed\",\"TotalTransfers\":\"2\",\"FileTransfers\":\"2\",\"FolderPropertyTransfers\":\"0\",\"SymlinkTransfers\":\"0\",\"FoldersCompleted\":\"0\",\"TransfersCompleted\":\"2\",\"FoldersFailed\":\"0\",\"TransfersFailed\":\"1\",\"FoldersSkipped\":\"0\",\"TransfersSkipped\":\"0\",\"BytesOverWire\":\"5\",\"TotalBytesTransferred\":\"14465\",\"TotalBytesEnumerated\":\"14465\",\"TotalBytesExpected\":\"14460\",\"PercentComplete\":\"100.03458\",\"AverageIOPS\":\"1\",\"AverageE2EMilliseconds\":\"266\",\"ServerBusyPercentage\":\"0\",\"NetworkErrorPercentage\":\"0\",\"FailedTransfers\":[{\"Src\":\"\\\\\\\\?\\\\C:\\\\SourceCode\\\\DTX\\\\__data_sets\\\\custom\\\\small\\\\csv-and-word\\\\dummy.csv\",\"Dst\":\"https://skynetadls.blob.core.windows.net/dev/resume-test/csv-and-word/dummy.csv\",\"IsFolderProperties\":false,\"TransferStatus\":\"Failed\",\"TransferSize\":0,\"ErrorCode\":\"0\"}],\"SkippedTransfers\":null,\"PerfConstraint\":0,\"PerformanceAdvice\":[],\"IsCleanupJob\":false}","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
```

### How can we reproduce the problem in the simplest way?

Try to upload some data set to Azure Blob, but force fail on some file - I used an .csv file in the data set and just open the file in Excel during the transfer - that prevents the files to be read and uploaded on the first try.
Then try close the Excel (releasing the blocked file) and try to resume the failed job in azcopy.

### Have you found a mitigation/solution?

No workaround, but I'm working on PR to fix that

**Comment by vibhansa-msft** [comment]
Can you share the full azcopy logs from both the runs.

**Comment by lukasz-krzykowski** [comment]
I've attached all logs from 1st and 2nd run and also the console output

[9d77672c-a86a-9b45-7ec2-b9e4de31bbfb.log](https://github.com/Azure/azure-storage-azcopy/files/13435155/9d77672c-a86a-9
[output-1st-run.log](https://github.com/Azure/azure-storage-azcopy/files/13435158/output-1st-run.log)
[output-2nd-run.log](https://github.com/Azure/azure-storage-azcopy/files/13435161/output-2nd-run.log)
b45-7ec2-b9e4de31bbfb.log)
[9d77672c-a86a-9b45-7ec2-b9e4de31bbfb-scanning.log](https://github.com/Azure/azure-storage-azcopy/files/13435156/9d77672c-a86a-9b45-7ec2-b9e4de31bbfb-scanning.log)
[2982caad-c2fc-f04c-512d-8a5ab5981498.log](https://github.com/Azure/azure-storage-azcopy/files/13435157/2982caad-c2fc-f04c-512d-8a5ab5981498.log)

**Comment by vibhansa-msft** [comment]
When you are resuming the job its actually creating a new job. We already have an open work item to fix the resume behavior and with that this shall also get fixed implicitly.

**Comment by lukasz-krzykowski** [comment]
Can we link it here?
