### ISSUE TITLE
Custom interval for progress reporting

### ISSUE THREAD

**Issue by lukasz-krzykowski** [Azure/azure-storage-azcopy#2463]
### Which version of the AzCopy was used? 

10.21.2 (latest stable at the moment) 

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

Simple `copy` (upload from local to blob) on data set that had over 1M files inside.

```
azcopy.exe copy C:\temp\dg\dg-files-1m-size-1gb-seed-1 "https://skynetadls.blob.core.windows.net/dev/onem?sv=2021-06-08&spr=https&st=2022-10-01T07%3A58%3A10Z&se=2023-12-31T16%3A58%3A10Z&si=testReadWritePolicy&sr=c&sig=REDACTED" --recursive --output-type json
```

### What problem was encountered?

I received notification:
```
{"TimeStamp":"2023-11-21T13:16:29.0510169+01:00","MessageType":"Info","MessageContent":"INFO: Reducing progress output frequency to 2m0s, because there are over 1000000 files","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
```

It would be great if we could override this default behavior with some CLI parameter (e.g. setting custom intervals between progress reporting, let's say with no lower value than every 1 second)

It's not suitable for my case to wait for 2 minutes to see if the job is progressing properly or not.

### How can we reproduce the problem in the simplest way?

Try to upload some data set to Azure Blob with more than 1000000 files

### Have you found a mitigation/solution?

No, but I think I can prepare a PR for such change if you find such feature welcome

**Comment by vibhansa-msft** [comment]
These intervals for reporting are based on best effort. In large jobs computing and emitting out summaries periodically uses some compute process. AzCopy as a tool wants to focus on the core migration work and not put load on CPU for reporting. If you feel you need faster reporting, then you can create your own version by forking the main repo.

**Comment by lukasz-krzykowski** [comment]
What is your policy when it comes to introduce such feature to the tool? I am more than happy to contribute with a PR for such change. When it comes to forking - it is a possibility for our team, but we would want not to go that way as it's more difficult to maintain and stay in sync with the original code

**Comment by vibhansa-msft** [comment]
Adding such high frequency reporting will hamper the transfer job performance, hence we do not intend to make any such changes in the main line. Best way for you is to fork or maintain a separate copy for the tool.
