### ISSUE TITLE
All commands (including azcopy --version) takes ~8 seconds

### ISSUE THREAD

**Issue by carlsmedstad** [Azure/azure-storage-azcopy#2482]
##### Note: The version is visible when running AzCopy without any argument

```sh
$ azcopy --version
azcopy version 10.22.0
```

### Which platform are you using? (ex: Windows, Mac, Linux)

Arch Linux.

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

```sh
$ time azcopy --version
azcopy version 10.22.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc6a2a3]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.(*lifecycleMgr).Exit(0xc0001dca20, 0x0?, 0x0)
	github.com/Azure/azure-storage-azcopy/v10/common/lifecyleMgr.go:375 +0xc3
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc0000e8a08?, 0x18b91b0?}, {0xc0000eb4c0?, 0x10c1337?}, 0x74?, {0x638f2c95, 0x1d76, 0xea43, {0x6e, 0x56, ...}})
	github.com/Azure/azure-storage-azcopy/v10/cmd/root.go:214 +0x17f
main.main()
	github.com/Azure/azure-storage-azcopy/v10/main.go:84 +0x4fa

real	0m8.032s
user	0m0.233s
sys	0m0.247s
```

### What problem was encountered?

There seems to be some kind of deadlock. Every command takes ~8 seconds. Also the stack trace.

See the attached [strace.log](https://github.com/Azure/azure-storage-azcopy/files/13596323/strace.log).

### How can we reproduce the problem in the simplest way?

Unsure.

### Have you found a mitigation/solution?

Unfortunately, no.

**Comment by carlsmedstad** [comment]
The issue seems to be in the version check. Running the following is near-instant:

```sh
$ time azcopy --skip-version-check --version
azcopy version 10.22.0

real	0m0.017s
user	0m0.010s
sys	0m0.007s
```

**Comment by gapra-msft** [comment]
Hi! This has been fixed in our latest release. Please feel free to open a new issue in case you hit any other issues with AzCopy!
