### ISSUE TITLE
Invalid URL while running azcopy sync (HTTP 404) in v10.22.0

### ISSUE THREAD

**Issue by ljelonek** [Azure/azure-storage-azcopy#2485]
### Which version of the AzCopy was used? 
10.22.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
```powershell
$path = "http://127.0.0.1:10000/devstoreaccount1/emulated/folder/$sasToken"
Invoke-Expression "$InstallPath\azcopy sync .\localfolder '$path' --from-to LocalBlob --delete-destination=true"
```
### What problem was encountered?
```
Cannot perform sync due to error: cannot list files due to reason GET http://127.0.0.1:10000/emulated
--------------------------------------------------------------------------------
RESPONSE 404: 404 The specified resource does not exist.
ERROR CODE: ResourceNotFound
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>ResourceNotFound</Code>
  <Message>The specified resource does not exist.
RequestId:c9b4d898-347e-42a2-9ec9-4aaf8025308c
Time:2023-12-07T11:04:21.095Z</Message>
</Error>
--------------------------------------------------------------------------------
```
### How can we reproduce the problem in the simplest way?

Download 10.22.0 to $InstallPath and run the command above.
### Have you found a mitigation/solution?

No, looks like internal problem with building URL.

**Comment by vibhansa-msft** [comment]
Was this working in older versions? What kind of emulator you are running here?

**Comment by ljelonek** [comment]
I can confirm that 10.17.0 version was working perfectly fine.
Emulator that I am using is `https://hub.docker.com/_/microsoft-azure-storage-azurite` version 3.28.0.

I highly doubt that emulator is the problem here, as changing the url to `http://127.0.0.1:10000/devstoreaccount1/devstoreaccount1/emulated/` returns error `Cannot perform sync due to error: cannot list files due to reason GET http://127.0.0.1:10000/devstoreaccount1`.

This is the second time I need to freeze azcopy version. Previously, I needed to do the same thing to mitigate #2140 . Is it possible to bring more attention to `sync` to avoid similar situations in the future?

**Comment by gapra-msft** [comment]
This should be resolved by this PR https://github.com/Azure/azure-storage-azcopy/pull/2495

**Comment by gapra-msft** [comment]
Hi! This has been fixed in our latest release. Please feel free to open a new issue in case you hit any other issues with AzCopy!
