### ISSUE TITLE
Ppermssion 

### ISSUE THREAD

**Issue by Daiannec** [Azure/azure-storage-azcopy#2487]
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy.exe copy "local" "SAS key" --
### What problem was encountered?
Error 403
### How can we reproduce the problem in the simplest way?
> Go to > https://compliance.microsoft.com/informationgovernance?viewid=import
> following this process https://learn.microsoft.com/en-us/purview/use-network-upload-to-import-pst-files
> in the end of process show error 403 
### Have you found a mitigation/solution?
no
![AZStorage_azcopy](https://github.com/Azure/azure-storage-azcopy/assets/104602080/6232e119-ea78-4ca2-a52b-a0e407e13461)
![AZStorage](https://github.com/Azure/azure-storage-azcopy/assets/104602080/a2a4f25a-286d-4d88-86d4-f978588d504b)
[c214f6c3-dcc7-4049-5e7e-36af557d17d3.log](https://github.com/Azure/azure-storage-azcopy/files/13604299/c214f6c3-dcc7-4049-5e7e-36af557d17d3.log)

**Comment by gapra-msft** [comment]
Hi @Daiannec it looks like the transfer completed successfully, we just weren't able to verify the length of the resource due to lack of permissions. This is not a required check, which is why it was simply shown in an INFO message.
