### ISSUE TITLE
azcopy fails with the message of abort

### ISSUE THREAD

**Issue by amsword** [Azure/azure-storage-azcopy#249]
### Which version of the AzCopy was used? 
azcopy 7.2.0-netcore
### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu 16.04
### What command did you run?
azcopy --source folderA --destination https://xxxx/folderB --exclude-older --dest-key xxxxxxxx== --quiet --parallel-level 32 --resume /tmp/azure.1639be1.jnl --recursive

### What problem was encountered?
/usr/bin/azcopy: line 8: 29564 Aborted                 $DIR/../lib/azcopy/azcopy "$@"

### Have you found a mitigation/solution?
re-install it and it works for the first time. But if i upload another data, it fails again. Then, i have to re-install it again.

**Comment by EmmaZhu** [comment]
@amsword 
Would you have a try with AzCopy 7.3.0? You can download and install it with following commands: 
```
wget -O azcopy.tar.gz https://aka.ms/downloadazcopylinux64
tar -xf azcopy.tar.gz
sudo ./install.sh
```

**Comment by zezha-msft** [comment]
Closing since V7 is no longer being actively maintained. Please give V10 a try [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy), it's been GA for a bit of time now. Please don't hesitate if you encounter any issue.
