### ISSUE TITLE
PowerShell auto-login untrusted module error

### ISSUE THREAD

**Issue by aelij** [Azure/azure-storage-azcopy#2490]
### Which version of the AzCopy was used?
10.22.0
### Which platform are you using?
Windows
### What command did you run?
```pwsh
$env:AZCOPY_AUTO_LOGIN_TYPE='PSCRED'
azcopy cp ...
```
### What problem was encountered?
```
INFO: Scanning...

Do you want to run software from this untrusted publisher?
File C:\Users\user\Documents\PowerShell\Modules\Az.Accounts\2.12.5\Accounts.format.ps1xml is published by CN=Microsoft Corporation,
O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\Users\user\Documents\PowerShell\Modules\Az.Accounts\2.12.5\Accounts.generated.format.ps1xml is published by CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Failed to perform Auto-login: PSContextCredentialInvalid output while retrving token.
```
### Have you found a mitigation/solution?
Running the shell using `pwsh -ExecutionPolicy Bypass`, but that's not a great option.
Note that the module works fine when using it directly (e.g. calling `Get-AzAccessToken`).

**Comment by gapra-msft** [comment]
@nakulkar-msft please take a look

**Comment by nakulkar-msft** [comment]
Hi @aelij, this is error with powershell. Please file your issue here.
https://github.com/PowerShell/PowerShell

**Comment by aelij** [comment]
@nakulkar-msft I'm pretty sure this error is because of #2491. Please prefer using `pwsh` over `powershell` even on Windows, or try to detect the current shell.
