### ISSUE TITLE
Is it passible to use blank in --blob-tags option

### ISSUE THREAD

**Issue by koneko26** [Azure/azure-storage-azcopy#2492]
### Which version of the AzCopy was used? 
10.21.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
./azcopy copy <source> <distination>?<SAS> --blob-tags "tag1=''"

### What problem was encountered?
I would like to upload data with index-tag including value is blank.
But, I got a error.
failed to parse user input due to error: incorrect set used in value : ''

I succeeded in uploading data with index-tag including value is null.
./azcopy copy <source> <destination>?<SAS> --blob-tags "tag1="

### How can we reproduce the problem in the simplest way?
Please excecute like this.
./azcopy copy <source> <distination>?<SAS> --blob-tags "tag1=''"

### Have you found a mitigation/solution?
Not yet.

**Comment by gapra-msft** [comment]
Hi @koneko26 how are you determining that the tag value set when you specify --blob-tags "tag1=" is null instead of empty string?

**Comment by koneko26** [comment]
Hi @gapra-msft 
I got metadata of tag1=null with Java SDK.

And, I have an app with working java for blob.
It can execute tag index of empty string, not null.
It couldn't work for uploaded data from Linux.

So, I determined there are null in tag index.

I would like to upload from Linux with azcopy of Linux.
Could you please let me know if there is any solution?

**Comment by gapra-msft** [comment]
Hi @koneko26 I just took a look at the Java SDK code and it looks like by default, any empty string is deserialized to null values, so you can consider null and empty string for the tag value to be one and the same.

**Comment by gapra-msft** [comment]
Closing this issue since its not an AzCopy issue
