### ISSUE TITLE
OOM on azcopy, need help (Kubernetes with 1 GB RAM)

### ISSUE THREAD

**Issue by rogoz** [Azure/azure-storage-azcopy#251]
Hello,

I'm running azcopy command within a kubernetes container to sync some data from the local disk with the azure blobs.The problem that i have is that my data is increasing over time, and at some point the azcopy command fails due to memory limits (basically the k8s kills the azcopy process as it reaches the memory limits ~1GB).Is there a way to configure azcopy or golang to not reach this limit over time?
The AZCOPY_CONCURRENCY_VALUE doesn't have any effect on the memory consumption. So, is there any configuration (environment variable to set), so that i can work with a lot of data on azcopy and not reach the 1GB of RAM that is allocated ? 

I'm running azcopy 10.0.6-preview on a ubuntu linux environment and using azcopy sync command.

Thank you,
Tudor

**Comment by zezha-msft** [comment]
Hi @rogoz, thanks for reaching out!

Memory usage and [sync command](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide) were both improved significantly in 10.0.8, could you please give the latest version a try?

**Comment by JohnRusk** [comment]
@rogoz, in spite of the latest improvements, 1 GB is lower than what I've previously tested with.  Version 10.0.8 is uses 0.5 GB per CPU, plus some overhead. For cases like yours we may have to add configurability of the RAM usage. Although, in the interests of simplicity, I've been trying to avoid adding such a flag unless absolutely necessary.

**Comment by JohnRusk** [comment]
Update: we're looking at plans to detect available RAM and respond accordingly.  But it's unlikely those plans will make it into the initial GA release.

**Comment by JohnRusk** [comment]
Version 10.3.0 will include support for an environment variable to give greater control over RAM usage.  It will be called something like AZCOPY_BUFFER_GB.  Running a test just now, with it set to 0.25 gave really low RAM usage - so it should fit fine in 1 GB as discussed above. 

Not sure yet whether auto-detection of RAM size will also be in 10.3.0

**Comment by JohnRusk** [comment]
Version 10.3 is out. It has the environment variable listed above.  It does not have any auto detection of RAM size, but the environment variable alone should be enough to get it working fine on low-RAM environments.
