### ISSUE TITLE
azcopy is waiting on input when run in the background

### ISSUE THREAD

**Issue by slagelwa** [Azure/azure-storage-azcopy#2510]
### Which version of the AzCopy was used? 
```
$ azcopy --version
azcopy version 10.21.2
INFO: azcopy 10.21.2: A newer version 10.22.1 is available to download
```

### Which platform are you using? (ex: Windows, Mac, Linux)
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.9 (Ootpa)
Release:        8.9
Codename:       Ootpa
```

### What command did you run?

`azcopy copy $URL my_local_file &`

### What problem was encountered?
Process is started in the background and is then stopped waiting for input.
```
[1]+   Stopped    azcopy copy $URL my_local_file
```

### How can we reproduce the problem in the simplest way?

Attempt to copy a blob from cloud storage that requires login credentials when you don't have any:
```
azcopy logout
export URL='https://XXXXXXX.blob.core.windows.net/...'
azcopy copy $URL mylocalfile &
```

### Have you found a mitigation/solution?
Providing some input, e.g.:
```
export URL='https://XXXXXXX.blob.core.windows.net/...'
azcopy copy $URL mylocalfile </dev/null &
```

**Comment by slagelwa** [comment]
Could be related to #974

**Comment by slagelwa** [comment]
Problem also occurs with `azcopy rm`

**Comment by vibhansa-msft** [comment]
When any file is to be overwritten or delete AzCopy asks for confirmation on the console for the same. If you run it in background then it will wait forever in such situation. You need to provide force related options in CLI to avoid this.

**Comment by slagelwa** [comment]
Ok.  I just tried it again using the following commands:
```
URL=https://azureopendatastorage.blob.core.windows.net
URL=$URL/holidaydatacontainer/Processed
URL=$URL/part-00000-tid-8468414522853579044-35925ba8-a227-4b80-9c89-17065e7bf1db-649-c000.snappy.parquet
azcopy cp $URL /tmp/holidays.parquet
ls -al /tmp/holidays.parquet
sleep 60
azcopy cp $URL /tmp/holidays.parquet
ls -al /tmp/holidays.parquet
```
The file was copied from cloud storage and then 60 seconds later I was not prompted for confirmation to overwrite the file and the timestamp of the file changed.

**Comment by vibhansa-msft** [comment]
```
 --overwrite string                     Overwrite the conflicting files and blobs at the destination if this flag is set to true. (default 'true') Possible values include 'true', 'false', 'prompt', and 'ifSourceNewer'. For destinations that support folders, conflicting folder-level properties will be overwritten this flag is 'true' or if a positive response is provided to the prompt. (default "true")
```
I see it shall overwrite by default and prompt only if you configure it to.
Can you validate if you run in foreground does it prompt anything or wait for any user input. If no then background should have also worked. However, azcopy dumps quite a few details on console so running it in background is not a good practice.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update on this. Feel free to reopen once you have required data available.

**Comment by slagelwa** [comment]
I can confirm that:

- indeed the default option is to overwrite as using `--overwrite true` works the same as not providing the option at all
- running azcopy in the background, `azcopy cp $URL /tmp/holidays.parquet > log &`, results in the background process waiting for input regardless if you provide the `--overwrite true` option or not and also does not display any output messages
- running azcopy with `--overwrite false` executes without error and reports the file as skipped.  Running it in the background however **still** results in the background process waiting for input.
- running azcopy with `--overwrite prompt` works as expected. I didn't run it in the background because...well it is going to prompt to overwrite...

When placing long-running Linux commands in the background I'm quite comfortable using `>` and `|` to handle the output. And azcopy already dumps plenty of information in its logs under ~/.azcopy.  I'm just not used to them waiting on input when they're not supposed to be receiving any.

**Comment by stewartadam** [comment]
> When any file is to be overwritten or delete AzCopy asks for confirmation on the console for the same. If you run it in background then it will wait forever in such situation. You need to provide force related options in CLI to avoid this.

If nothing else this itself is a bug. CLI tools can tell if they're running with a tty or if stdin is open; azcopy should fail when user input is required and that input channel is not available.
