### ISSUE TITLE
copy --background-op stuck in "Scanning..."

### ISSUE THREAD

**Issue by gmassari-88** [Azure/azure-storage-azcopy#252]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.0.8-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 2016 Server
Windows 10

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
AzCopy.exe cp "$srcPath" "$targetPath" --overwrite --background-op

### What problem was encountered?
The downloaded test file is about 1.5MB in size. Stdout would be stuck with the message "Scanning..." and never recover control until the script is manually stopped. Note that download is actually performed in the background.

### How can we reproduce the problem in the simplest way?
1. Create a blob storage container
2. Create a test file in the container
3. On a computer, create a script to download the test file including --background-op=true in the copy syntax
4. run the script from powershell/powershell ISE

### Have you found a mitigation/solution?
Removing the --background-op=true bit from the script restores full functionality. Interrupting the script recovers immediate response from the console.

**Comment by zezha-msft** [comment]
Hi @gmassari-88, thank you for reaching out!

I apologize for the inconvenience. It looks like I mistakenly revealed the background-op flag which is **not supported** anymore. I'll fix it right away, thank you for bringing this to our attention!

**Comment by zezha-msft** [comment]
Fixed in 10.0.9.
