### ISSUE TITLE
Is it expected behavior for azcopy to make requests to the blob endpoint for a storage account when although you specify it to use dfs?

### ISSUE THREAD

**Issue by harristemuri** [Azure/azure-storage-azcopy#2522]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.22.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy list https://mystorageacct.dfs.core.windows.net/my-container/folder/`
### What problem was encountered?
azcopy makes requests to the storage account **blob** endpoint when I specified the **dfs** endpoint.
### How can we reproduce the problem in the simplest way?
Create an ADLSgen2 storage account and a container within that storage account. Then run an `azcopy list` command against the Data Lake Storage primary endpoint. When inspecting the network packets on your machine, you should see that azcopy is using the Blob service endpoint to send requests to. See below for an example:

![image](https://github.com/Azure/azure-storage-azcopy/assets/109305607/9f3ff18e-18d2-43ad-acda-131593ffc27c)

My question is whether this is expected behavior or not. The documentation shows the option to use either dfs or blob as if you only need to be able to make requests to the endpoint you choose.

**Comment by vibhansa-msft** [comment]
This is expected. Not all requests go over dfs endpoint.
