### ISSUE TITLE
Log files are missing .log extension

### ISSUE THREAD

**Issue by pid1** [Azure/azure-storage-azcopy#2529]
Apologies if this is a duplicate, but I couldn't find another report for this.

### Which version of the AzCopy was used? 
10.22.1

### Which platform are you using? (ex: Windows, Mac, Linux)
macOS

### What command did you run?
`azcopy cp "<vhd_uri>" .`

### What problem was encountered?
As indicated by the command, a log file is created. However, the log file is actually missing the `.log` file extension indicated by the output.

`Log file is located at: /Users/<user>/.azcopy/<uuid>.log`

However, the file is actually at `/Users/<user>/.azcopy/<uuid>`

### How can we reproduce the problem in the simplest way?
Run `azcopy cp <uri> .`

Observe that the log file is not created with the correct extension

### Have you found a mitigation/solution?
The file _is_ created at the expected directory, and can be used as expected.

**Comment by gapra-msft** [comment]
Closing this issue as a PR was merged that will be released as part of 10.23.0 which will resolve this issue.
