### ISSUE TITLE
File Copy Fails to complete 

### ISSUE THREAD

**Issue by caiwan-msft** [Azure/azure-storage-azcopy#2543]
### Which version of the AzCopy was used? 
2024/01/18 03:21:01 AzcopyVersion  **10.22.2**
### Which platform are you using? (ex: Windows, Mac, Linux)
2024/01/18 03:21:01 OS-Environment  **linux**
2024/01/18 03:21:01 OS-Architecture  amd64

### What command did you run?
azcopy copy “server_dir” “sas url of the container” --recursive=true
### What problem was encountered?
Using azcopy to copy files from a Huawei server to a storage container in a StorageV2 (general purpose v2) account. All small files were copied successfully while large ones, ~8 GBs and above, failed, with a timeout error. 

**Errors in logs with ‘--log-level=DEBUG’:**
2024/01/18 03:21:07 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  1, W: 35, F:  0, B: 300, E:  0, T: 336, GRs: 300
2024/01/18 03:21:07 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 310.6022
2024/01/18 03:21:09 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  1, W: 180, F:  0, B: 300, E:  0, T: 481, GRs: 300
2024/01/18 03:21:09 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 134.5545
2024/01/18 03:21:11 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W: 271, F:  0, B: 300, E:  0, T: 571, GRs: 300
2024/01/18 03:21:11 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 165.6097
2024/01/18 03:21:12 ==> REQUEST/RESPONSE (Try=1/10.014928601s[SLOW >3s], OpTime=10.01501538s) -- REQUEST ERROR
   PUT https://storageaccount.blob.core.chinacloudapi.cn/dslab/copied_models%2Fmeta?blockid=MDAwMDBk9n%2BLrMFFa08Erh8dFqDoMDAwMDAwMDAwMDAwMDMx&comp=block&se=2026-01-15T16%3A00%3A00Z&sig=-REDACTED-&sp=racwdlme&spr=https&sr=c&st=2024-01-15T16%3A00%3A00Z&sv=2022-11-02
   Accept: application/xml
   Content-Length: 8388608
   Content-Type: application/octet-stream
   User-Agent: AzCopy/10.22.2 azsdk-go-service.Client/v1.2.0 (go1.19.12; linux)
   X-Ms-Client-Request-Id: 9180941e-a889-48bd-489d-14317f08652c
   x-ms-version: 2023-08-03
   --------------------------------------------------------------------------------
   ERROR:
Put "https://storageaccount.blob.core.chinacloudapi.cn/dslab/copied_models%2Fmeta?blockid=MDAwMDBk9n%2BLrMFFa08Erh8dFqDoMDAwMDAwMDAwMDAwMDMx&comp=block&se=2026-01-15T16%3A00%3A00Z&sig=-REDACTED-&sp=racwdlme&spr=https&sr=c&st=2024-01-15T16%3A00%3A00Z&sv=2022-11-02": net/http: TLS handshake timeout
goroutine 388 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.stack()
	/home/vsts/work/1/s/ste/xferLogPolicy.go:100 +0x65
github.com/Azure/azure-storage-azcopy/v10/ste.logPolicy.Do({{{0xb2d05e00, 0x0}, 0xc0003aac90, 0xc0003aaca8}, 0xc0003815c0, 0xc0003815f0, 0xc000381620}, 0xc000226280)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:232 +0xb5d
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000226240)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/request.go:107 +0xf8
github.com/Azure/azure-storage-azcopy/v10/ste.(*retryNotificationPolicy).Do(0x0?, 0xc000226240)
	/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:64 +0x36
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc003965430)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/request.go:107 +0xf8
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*retryPolicy).Do(0xc003965568?, 0xc000226200)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/runtime/policy_retry.go:126 +0x5b4
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0002261c0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/request.go:107 +0xf8
github.com/Azure/azure-storage-azcopy/v10/ste.(*fileUploadRangeFromURLFixPolicy).Do(0xc0039655e8?, 0xc0002261c0)
	/home/vsts/work/1/s/ste/sender-azureFileFromURL.go:118 +0x15f
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000226180)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/request.go:107 +0xf8
github.com/Azure/azure-storage-azcopy/v10/ste.(*versionPolicy).Do(0xe8e260?, 0xc000226180)
	/home/vsts/work/1/s/ste/xferVersionPolicy.go:49 +0x134
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000226140)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/request.go:107 +0xf8
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*requestIDPolicy).Do(0xc003965738?, 0xc000226140)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/runtime/policy_request_id.go:33 +0x146
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000226100)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/request.go:107 +0xf8
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.telemetryPolicy.Do({{0xc0003cec80?, 0xfd16c0?}}, 0xc000226100)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/runtime/policy_telemetry.go:70 +0x1c5
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0002260c0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/request.go:107 +0xf8
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.includeResponsePolicy(0xc0002260c0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/runtime/policy_include_response.go:19 +0x25
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.PolicyFunc.Do(0x566d62764e565970?, 0x30424d6645545979?)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/request.go:212 +0x1f
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000226080)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/request.go:107 +0xf8
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.Pipeline.Do({{0xc0003c2500?, 0x0?, 0x0?}}, 0x5?)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.9.0/internal/exported/pipeline.go:76 +0x56
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/generated.(*BlockBlobClient).StageBlock(0xc0003aa180, {0x128c030?, 0xc0003880c0?}, {0xc002438420?, 0x0?}, 0x8?, {0x128a2c0?, 0xc000110a20?}, 0x418c8b?, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.2.0/internal/generated/zz_blockblob_client.go:545 +0xeb
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob.(*Client).StageBlock(0x0?, {0x128c030, 0xc0003880c0}, {0xc002438420, 0x30}, {0x128a2c0?, 0xc000110a20}, 0xc00249fd70)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.2.0/blockblob/client.go:219 +0x2a5
github.com/Azure/azure-storage-azcopy/v10/ste.(*blockBlobUploader).generatePutBlock.func1()
	/home/vsts/work/1/s/ste/sender-blockBlobFromLocal.go:104 +0x368
github.com/Azure/azure-storage-azcopy/v10/ste.createChunkFunc.func1(0x5f5e100?)
	/home/vsts/work/1/s/ste/sender.go:207 +0x29e
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).chunkProcessor(0xc000101000, 0x0?)
	/home/vsts/work/1/s/ste/mgr-JobMgr.go:1064 +0xbd
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).poolSizer
	/home/vsts/work/1/s/ste/mgr-JobMgr.go:966 +0x23d

Job 8b7ff664-c1ac-6b45-4f04-ae1f1d16a0e8 summary
Elapsed Time (Minutes): 43.2809
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Number of Symlink Transfers: 0
Total Number of Transfers: 1
Number of File Transfers Completed: 0
Number of Folder Transfers Completed: 0
Number of File Transfers Failed: 1
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed

2024/01/18 04:04:18 Closing Log

### How can we reproduce the problem in the simplest way?
Can be reproduced in-demand in customer' s side. 

### Have you found a mitigation/solution?
No.  
Seems to be similar to the two issues:
https://github.com/Azure/azure-storage-azcopy/issues/1004   
https://github.com/Azure/azure-storage-azcopy/issues/1199   

!!!If full debug azcopy log is needed, please feel free to reach out to me!!!

**Comment by caiwan-msft** [comment]
[8b7ff664-c1ac-6b45-4f04-ae1f1d16a0e8_Modified.log](https://github.com/Azure/azure-storage-azcopy/files/13972711/8b7ff664-c1ac-6b45-4f04-ae1f1d16a0e8_Modified.log)
Attached azcopy debug log.  Removed sensitive information.

**Comment by vibhansa-msft** [comment]
This is not related to the linked issues. As per logs you are getting lot of "connection reset by peer" and "tls handshake failure" error. You need to check with the backend team on why the connections are not going through. Might be some sort of throttling done by the backend which is restricting your connections. If your account is being throttled, then you can reduce the concurrency and apply a bandwidth limit while submitting the azcopy command.
