### ISSUE TITLE
Azcopy sync between two storage accounts in different tenants fails with CannotVerifyCopySource

### ISSUE THREAD

**Issue by benomalley25** [Azure/azure-storage-azcopy#2544]
### Which version of the AzCopy was used? 
10.22.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (WSL)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy sync "https://*sourceaccount*.file.core.windows.net/*sourcefileshare*/*sourcefolder*/" 'https://*destinationaccount*.blob.core.windows.net/*destinationcontainer*/*destinationpath*/?*sas-token*' --recursive --cap-mbps 100 --from-to FileBlob

### What problem was encountered?
**output**: 
Job 080829fd-19ac-5548-7897-54f0650a0667 Summary
Files Scanned at Source: 97
Files Scanned at Destination: 0
Elapsed Time (Minutes): 0.8003
Number of Copy Transfers for Files: 97
Number of Copy Transfers for Folder Properties: 0
Total Number Of Copy Transfers: 97
Number of Copy Transfers Completed: 0
Number of Copy Transfers Failed: 97
Number of Deletions at Destination: 0
Total Number of Bytes Transferred: 0
Total Number of Bytes Enumerated: 11398388
Final Job Status: Failed

Checking the StorageBlobLogs on the destination storage account every copy failed with status code 400 and statusTest "CannotVerifyCopySource"

Both source and destination storage accounts are on DIFFERENT azure tenants, however they both have public access enabled.
I have not tried using SAS authentication for the source account yet as I don't have permission to generate SAS tokens for that account.

### How can we reproduce the problem in the simplest way?
Two storage accounts in different tenants. Setup azure files folder in source and a blob storage container in destination with hierarchical namespaces. Use az cli to log into source tenant and then run azcopy sync from source to destination using a sas token for destination

### Have you found a mitigation/solution?
Not yet - I'm looking into getting permission to create sas tokens on source account as I believe that might help, but I'd prefer not to require this.

**Comment by vibhansa-msft** [comment]
If they are in two different tenants, can you verify vnet peering is done properly if they both fall in two different vnets.
Copy source verification generally fails when destination account is not able to authenticate properly to source account.

**Comment by benomalley25** [comment]
> If they are in two different tenants, can you verify vnet peering is done properly if they both fall in two different vnets. Copy source verification generally fails when destination account is not able to authenticate properly to source account.

I don't think either storage account is in a vnet

**Comment by vibhansa-msft** [comment]
Can not verify copy source generally points that your source account is not accessible from your destination account. This is more of a storage account setup issue and not really an azcopy issue. Kindly check with respective teams on what you might be missing. Mostly we have seen its either a vnet or a firewall related issue where accounts are not accessible in such cases.

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to reopen once the required information is available.
