### ISSUE TITLE
[StgExp] ADLS Gen 2 encoded path name removal fails

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-storage-azcopy#2549]
##### Note: The version is visible when running AzCopy without any argument
10.22.2

### Which platform are you using? (ex: Windows, Mac, Linux)
any

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
./azcopy.exe rm https://XXXX.dfs.core.windows.net/XXXX/%23%2C%25%2C%3F?SAS --from-to=BlobFSTrash --recursive --log-level=DEBUG

### What problem was encountered?
removal of path fails with invalid URL escape "%,?"

### How can we reproduce the problem in the simplest way?
Create a directory in an HNS account called #,%,? and run the above command 

### Have you found a mitigation/solution?
you could use the blob endpoint

related issue https://github.com/microsoft/AzureStorageExplorer/issues/7692

The root cause of the issue is the datalake Go SDK. FileSystemClient.NewDirectoryClient and NewFileClient do not call url.PathEscape on the directoryName or fileName passed. See ContainerClient.NewBlobClient for how it should be handled. Special care should be taken so that both the APIs that hit blob endpoints and dfs endpoints continue to work after the fix is made.

**Comment by gapra-msft** [comment]
Note: When we pick up the new SDK dependency, add tests testing the above.

**Comment by Steven23661** [comment]
93162b88ad1b421dd67659d3cd59224bd3af3c1393162b88ad1b421dd67659d3cd59224bd3af3c13
