### ISSUE TITLE
Sync command not interpreting source files properly

### ISSUE THREAD

**Issue by williexu** [Azure/azure-storage-azcopy#255]
##### Note: The version is visible when running AzCopy without any argument
10.0.8

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`sync .\garbage https://wilxstorage.blob.core.windows.net/wilxcontainer --delete-destination true `

### What problem was encountered?
source files not interpreted correctly. My source directory(garbage) has two files in it: `file.txt` and `file2.txt`

Yet in my log file I see:
`Starting transfer: Source "./garbage/garbage/file.txt" Destination "https://wilxstorage.blob.core.windows.net/wilxcontainer/garbage%2Ffile.txt". Specified chunk size 8388608`

It looks like the directory name is being appended twice to form source paths, and then because sync cannot find those malformed source paths, it fails.

This also causes **ALL** destination blobs to be deleted if the `delete-destination` flag is specified, as there are no matches.

### How can we reproduce the problem in the simplest way?
Run the command with a source directory and destination container

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @williexu, thanks for letting us know!

I was able to repro and confirmed that it's an issue **specific** to relative paths on Windows. I tried the same thing on MacOS and it worked fine. Please use full paths for now as a workaround.

I also realize that we have a lack of testing for relative paths, I'll look into how we can improve this. Thanks for the feedback!

**Comment by zezha-msft** [comment]
Hi @williexu, I've fixed this issue for the sync command. It was a string processing bug. Really sorry for the inconvenience. I'll try to figure out how to add relative paths to our testing so that they are covered as well.

**Comment by zezha-msft** [comment]
Fixed in 10.0.9.
