### ISSUE TITLE
Difference between azcopy sync and az storage blob sync

### ISSUE THREAD

**Issue by landscapepainter** [Azure/azure-storage-azcopy#2551]
Hi team, we just started to use Azure. Thanks for the great tool! I had a question regards to difference between `azcopy sync` and `az storage blob sync`. Are there any specific difference in a way that the use of each tool are for difference purpose? Thanks!

**Comment by gapra-msft** [comment]
Hi @landscapepainter 

AzCopy is a dedicated tool that  makes use of service-to-service copy APIs for transfers within Azure Storage services and multi-threading to enable high throughput transfers.

az storage blob sync is an Azure CLI command. It [looks](https://learn.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-sync) like it is currently in preview mode. For more information on Azure CLI, I'd direct you to their public documentation [here](https://learn.microsoft.com/en-us/cli/azure/what-is-azure-cli).

**Comment by gapra-msft** [comment]
Closing this issue as I believe the question has been answered. In case you have any further questions about AzCopy, we are happy to answer.
