### ISSUE TITLE
Auto-Login Process, Messaging, and Documentation is Confusing

### ISSUE THREAD

**Issue by Mike-E-angelo** [Azure/azure-storage-azcopy#2556]
### Which version of the AzCopy was used? 

10.22.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

`azcopy copy` and then `azcopy login` after this because the copy command doesn't work

### What problem was encountered?

I am attempting to use auto login, or really, any login, but the process is confusing.  To start, consider what happens when I `azcopy login`:

```
INFO: 'azcopy login' command will be deprecated starting release 10.22. Use auto-login instead. Visit https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-without-a-secret-store  to know more.
```

I am on version 10.22.2, so doesn't that mean azopy login **is** deprecated for me?  The messaging makes it sound like it's going to be deprecated in a future version, but as I understand it, that future version is _now_.  

Additionally, when I visit `https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-without-a-secret-store` the link does not mention Auto-Login or anything about it.  There is no information on this feature or how to enable it.  The only place I see "auto" is in variable names, but this doesn't tell me exactly how this works.

_What exactly is auto-login and how do I enable it?_

I want to do the same thing I am doing now with `azcopy login` and use the current (administrative) user to perform key automation tasks to stand up an environment.

### How can we reproduce the problem in the simplest way?

enter `azcopy login` and enjoy the show.

### Have you found a mitigation/solution?

Opening the issue here is the best I got. :)  Thank you for any assistance you can provide. 🙏

**Comment by gapra-msft** [comment]
@nakulkar-msft Please take a look.

**Comment by pranavmalik-msft** [comment]
Thank you for expressing your concern. 
In a nut-shell Auto-Login enables AzCopy commands to authenticate to Azure storage by picking up Azure Active Directory (AAD) credentials from environment variables without the need to explicitly invoke the azcopy login command.

We have a dedicated page [AZCOPY-AUTOLOGIN] (https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)) that comprehensively explains the AUTO-LOGIN feature and addresses various scenarios associated with its usage.

Furthermore, I'd like to clarify that, at present, we have decided not to deprecate AzCopy Login. We have initiated a pull request (PR) to modify the message you encounter during the login process.
As of now you can use both the old azcopy login and  Auto-Login.

**Comment by Mike-E-angelo** [comment]
Thank you for all your efforts out there @pranavmalik-msft and team.  This is a great product and works really well. 👍
