### ISSUE TITLE
Question about behavior of wildcard when deleting blobs

### ISSUE THREAD

**Issue by williexu** [Azure/azure-storage-azcopy#256]
##### Note: The version is visible when running AzCopy without any argument
10.0.8
### Which platform are you using? (ex: Windows, Mac, Linux)
windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
remove
### What problem was encountered?
For some reason or other, I accidently created blobs with '*' in their names like: `https://wilxstorage.blob.core.windows.net/wilxcontainer/*/file.txt`.

When I run the command: `remove https://wilxstorage.blob.core.windows.net/wilxcontainer/* --recursive`, all my other blobs aside from the ones with the '*' are deleted.

Just wanted to know what was going on and wondered whether this was expected?

### How can we reproduce the problem in the simplest way?
Run command with blobs and wildcard character

### Have you found a mitigation/solution?
Yes: `remove https://wilxstorage.blob.core.windows.net/wilxcontainer/*/* --recursive`

In this version of the command is the first `*` being interpreted as the actual character or another asterisk?

**Comment by zezha-msft** [comment]
Remove command has been re-written in 10.0.9. Please refer to the help message for more details. Thank you!
