### ISSUE TITLE
`RESPONSE 401: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.`

### ISSUE THREAD

**Issue by Mike-E-angelo** [Azure/azure-storage-azcopy#2560]
### Which version of the AzCopy was used? 
10.23.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
My principal/user has been given `Storage Blob Data Reader` on the source storage account and `Storage Blob Data Owner` on the destination storage account.
```
$Env:AZCOPY_AUTO_LOGIN_TYPE="DEVICE"
$Env:AZCOPY_TENANT_ID="<tenant>"    
azcopy copy "https://<source>.blob.core.windows.net/assetscontainer" "https://<destination>.blob.core.windows.net/assetscontainer" --recursive
```
### What problem was encountered?

```
INFO: Scanning...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code *** to authenticate.

^VINFO: Login succeeded.
INFO: Authenticating to destination using Azure AD
INFO: Authenticating to source using Azure AD
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason GET https://<source>.blob.core.windows.net/assetscontainer
--------------------------------------------------------------------------------
RESPONSE 401: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
ERROR CODE: NoAuthenticationInformation
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?><Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.       
RequestId:536c2925-f01e-0001-5f5d-540ff9000000
Time:2024-01-31T15:52:40.7538466Z</Message></Error>
--------------------------------------------------------------------------------
.

```

### How can we reproduce the problem in the simplest way?

Hopefully by running the above. 😊

### Have you found a mitigation/solution?
Interestingly enough, I did not encounter this with 10.22, but I did encounter the same error on the destination side.

**Comment by Mike-E-angelo** [comment]
I was able to get my copying done via the approach in #2564

**Comment by Dinky7NZ** [comment]
I have exactly this issue.
How did the approach in https://github.com/Azure/azure-storage-azcopy/issues/2564 help you address this authentication issue?

#2564 was about the bandwidth being used which I believe the resolution was to use the --check-length=false flag to reduce the amount of requests for each blob copied.
