### ISSUE TITLE
AzCopy Documentation States Copying is Done Server-to-Server but Local Network Bandwidth is Used

### ISSUE THREAD

**Issue by Mike-E-angelo** [Azure/azure-storage-azcopy#2564]
### Which version of the AzCopy was used? 

10.23.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

In my case I am wanting to copy the files from the past five days from one storage account to another.  Some variables are omitted but hopefully you can get the gist of it:

```
$starting = (Get-Date).AddDays(-5).ToString("yyyy-MM-dd")
$from = "https://$source.blob.core.windows.net/$($container)?$sourceSAS"
$to = "https://$destination.blob.core.windows.net/$($container)?$destinationSAS"
azcopy copy $from $to --recursive --include-after $starting
```
### What problem was encountered?

[According to this document](url), AzCopy uses server-to-server APIs:

> AzCopy uses [server-to-server](https://learn.microsoft.com/en-us/rest/api/storageservices/put-block-from-url) [APIs](https://learn.microsoft.com/en-us/rest/api/storageservices/put-page-from-url), so data is copied directly between storage servers.

However, upon running the above command, I see significant network utilization on my local machine:

![image](https://github.com/Azure/azure-storage-azcopy/assets/2931376/fe35dfeb-edc1-41bd-9e56-386c5e1eb85b)

It would seem that data is not copied server-to-server, but from server, to local node, to server.  I would greatly appreciate knowing if I misunderstood something, however.  Given the amount of data being passed for such a sustained amount of time, it would seem the data is passing through my local machine which is not expected reading the documentation.

### How can we reproduce the problem in the simplest way?

Hopefully by running the above command locally and observing similar results.

### Have you found a mitigation/solution?

No

**Comment by gapra-msft** [comment]
Hi @Mike-E-angelo could you share AzCopy logs for your command? Do you have a large number of files in the source? AzCopy lists the source and based on the number of files, will issue s2s requests for each file, so if there are a large number of files, that can take up bandwidth.

**Comment by Mike-E-angelo** [comment]
Hi @gapra-msft thank you for your quick reply!  And for your efforts out there.  I do have the logs here, but wonder the best way to get them to you?  It's about 38MB of logging, are you saying that is what makes up the bandwidth?  It seemed to last quite a while on my end which was surprising.

Also to answer your question I do have many files in my containers, about 80GB worth at the moment.

**Comment by gapra-msft** [comment]
Could you send the logs to azcopydev AT microsoft.com?

**Comment by gapra-msft** [comment]
Just to be clear, what is taking up bandwidth includes performing listing operations to get the paths of n files (we only get a maximum of 5000 files per list request, so approx n/5000 requests) and then n requests are made to the service to perform service to service copy operations. 
Listing might end early but for the duration of the azcopy operation, we are issuing some subset of those n service to service requests.

**Comment by Mike-E-angelo** [comment]
Great.  I have done so. 👍🙏

**Comment by gapra-msft** [comment]
Thanks, I'm taking a look now. Will get back to you shortly.

**Comment by gapra-msft** [comment]
It looks like there is an additional Get Properties request per file, which AzCopy performs to validate that the destination file has the same size as the source. This check can be opted out and possibly save additional time/network bandwidth on your operation if you don't need that functionality, but I'd recommend keeping it as it's helpful to verify the transfer after it's complete.

The CLI option to have AzCopy skip that additional check is called --check-length=false.

Other than that AzCopy looks to be behaving as expected, so I will go ahead and close this issue. 

Feel free to open new issues as new questions arise!
