### ISSUE TITLE
Login issues behind corporate proxy 

### ISSUE THREAD

**Issue by GabrielGosden** [Azure/azure-storage-azcopy#2570]
### Which version of the AzCopy was used? 
AzCopy 10.23.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

### What command did you run?

`sudo azcopy login`

### What problem was encountered?

I am unable to login into azcopy and unable to use SAS token to copy files due to incorrect proxy settings. I'm sitting behind a corporate proxy. 

According to [documentation](https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-configuration-settings) azcopy should use the environment variable `HTTPS_PROXY` to define the proxy for azcopy. 

My `HTTPS_PROXY` is defined as:
`HTTPS_PROXY=http://"username":"password"@"ip":"port"/`

When running `sudo azcopy login`  it returns the following:
```
INFO: 'azcopy login' command will be deprecated starting release 10.22. Use auto-login instead. Visit https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-without-a-secret-store  to know more.
INFO: Proxy detected: https://login.microsoftonline.com -> https://"username":"password"@"ip":"port"/
INFO: Proxy detected: https://azcopyvnextrelease.blob.core.windows.net -> https://"username":"password"@"ip":"port"/

Failed to perform login command: 
failed to login with tenantID "common", Azure directory endpoint "https://login.microsoftonline.com", autorest/adal/devicetoken: -REDACTED- occurred while sending request for Device Authorization Code: Post "https://login.microsoftonline.com/common/oauth2/devicecode?api-version=1.0": proxyconnect tcp: tls: first record does not look like a TLS handshake

NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again.
```

It therefore add's an "s" character to my HTTPS proxy which results in me being unable to login

### How can we reproduce the problem in the simplest way?

1. Define environment variable 
`export HTTPS_PROXY=http://username:password@1.1.1.1:8080`
2. Run 
`sudo azcopy -h`

### Have you found a mitigation/solution?

no

**Comment by gapra-msft** [comment]
Hi @GabrielGosden 

I am unable to reproduce the issue as described. When I set the HTTPS_PROXY variable and run the version of AzCopy you are running I see the expected proxy. Please double check what you are setting as the HTTPS_PROXY variable. 
![image](https://github.com/Azure/azure-storage-azcopy/assets/51212198/08cd6aa8-11df-4f23-83cb-3286ef89f69c)

**Comment by GabrielGosden** [comment]
@gapra-msft Thank you for your feedback. I was able to find issues
