### ISSUE TITLE
Copying contents of container into another storage account with a folder specified, results in nested folders

### ISSUE THREAD

**Issue by mattou07** [Azure/azure-storage-azcopy#2571]
### Which version of the AzCopy was used? 
10.21.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy copy "https://source.blob.core.windows.net/media?sv=sas-for-read-list-only" "https://dest.blob.core.windows.net/container-name/media/?sv=sas-to-create-write-list-read-add" --recursive
### What problem was encountered?
I need to copy a large amount of Umbraco media from a container called media in the source account. However in the destination account I need to alter the structure so the media goes into a container and within a folder called media of that container.
So: https://dest.blob.core.windows.net/container-name/media/

What happens is for some reason it puts the media into another media folder called media resulting in all the files going into https://dest.blob.core.windows.net/container-name/media/media/*
### How can we reproduce the problem in the simplest way?
Upload a few images within folders into a container so
1/hello.jpg
2/azure.jpg
3/azcopy.jpg
etc ...

Then try and copy them into another storage account in a container inside a folder called media with the file structure preserved.

### Have you found a mitigation/solution?
I run the command and let the files go into https://dest.blob.core.windows.net/container-name/media/media/*. I then copy the media folder so its in the correct level of https://dest.blob.core.windows.net/container-name/media/ and then delete the nested media folder (however this takes 30 mins to complete as it has to go through all the files.)

**Comment by gapra-msft** [comment]
Hi @mattou07 

The correct way to format the command so you get your desired result would be to omit the last level of the destination directory.

> azcopy copy "https://source.blob.core.windows.net/media?sv=sas-for-read-list-only" "https://dest.blob.core.windows.net/container-name/?sv=sas-to-create-write-list-read-add" --recursive

Alternatively, you can also use a trailing asterisk in your source and that will work as well 

azcopy copy "https://source.blob.core.windows.net/media/*?sv=sas-for-read-list-only" "https://dest.blob.core.windows.net/container-name/media/?sv=sas-to-create-write-list-read-add" --recursive

**Comment by gapra-msft** [comment]
Closing this for now as I believe the above issue has been addressed. In case I have closed it in error, feel free to reopen.

**Comment by mattou07** [comment]
Thanks @gapra-msft. Just confirming that using a trailing asterisk provides the desired result of putting the contents of a source container into a folder of another container on the destination account.

**Comment by gapra-msft** [comment]
Yes that is what I experienced in my testing
