### ISSUE TITLE
AzCopy list command fails with storage account with Azure Frontdoor or Azure application gateway

### ISSUE THREAD

**Issue by daggubatirao** [Azure/azure-storage-azcopy#2579]
### Which version of the AzCopy was used? 
10.23
### Which platform are you using? (ex: Windows, Mac, Linux) 
Windows

### What command did you run?
azcopy list --trusted-microsoft-suffixes xxxx.z01.azurefd.net https://xxxx.z01.azurefd.net/
azcopy list --trusted-microsoft-suffixes xxxx.yyy.com https://xxxx.yyy.com/
### What problem was encountered?
Azcopy shows the following error:
failed to parse user input due to error: invalid path passed for listing. given source is of type Local while expect is container / container path

### How can we reproduce the problem in the simplest way?
1. Create a storage account and blob container
2. create azure frondoor with backend as storage blob or create application gateway with backend as storage blob

### Have you found a mitigation/solution?
It appears Azcopy validates the url and expects .blob in the URL in InferArgumentLocation function. Need support for URLs with frontdoor or custom domains.

> func InferArgumentLocation(arg string) common.Location {
> 	if arg == pipeLocation {
> 		return common.ELocation.Pipe()
> 	}
> 	if startsWith(arg, "http") {
> 		// Let's try to parse the argument as a URL
> 		u, err := url.Parse(arg)
> 		// NOTE: sometimes, a local path can also be parsed as a url. To avoid thinking it's a URL, check Scheme, Host, and Path
> 		if err == nil && u.Scheme != "" && u.Host != "" {
> 			// Is the argument a URL to blob storage?
> 			switch host := strings.ToLower(u.Host); true {
> 			// Azure Stack does not have the core.windows.net
> 			case strings.Contains(host, ".blob"):
> 				return common.ELocation.Blob()
> 			case strings.Contains(host, ".file"):
> 				return common.ELocation.File()
> 			case strings.Contains(host, ".dfs"):
> 				return common.ELocation.BlobFS()
> 			case strings.Contains(host, benchmarkSourceHost):
> 				return common.ELocation.Benchmark()
> 				// enable targeting an emulator/stack
> 			case IPv4Regex.MatchString(host):
> 				return common.ELocation.Unknown()
> 			}
> 
> 			if common.IsS3URL(*u) {
> 				return common.ELocation.S3()
> 			}
> 
> 			if common.IsGCPURL(*u) {
> 				return common.ELocation.GCP()
> 			}
> 		}
> 	}
> 
> 	return common.ELocation.Local()
> }

**Comment by gapra-msft** [comment]
Hi @daggubatirao this is being tracked by [this ](https://github.com/Azure/azure-storage-azcopy/issues/1090)issue already and we are currently working on making this enhancement. Please subscribe to the existing issue to get updates.
