### ISSUE TITLE
Confusing results from recursion flag and wildcard

### ISSUE THREAD

**Issue by williexu** [Azure/azure-storage-azcopy#258]
##### Note: The version is visible when running AzCopy without any argument
10.0.8
### Which platform are you using? (ex: Windows, Mac, Linux)
windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
remove
### What problem was encountered?
I have a container with virtually nested blobs that looks something like:
```
<container>
    <dir>
        <subdir>
            file1
            file2
        file3
    file4
```
1. `azcopy remove https://wilxstorage.blob.core.windows.net/wilxcontainer/*` or `azcopy remove https://wilxstorage.blob.core.windows.net/wilxcontainer` (no recursive flag):
    - nothing is deleted, error suggests using recursion flag
    - I would have expected file4 to be deleted(at least for the wildcard one), to allow for deleting at a certain directory level

2. `azcopy remove https://wilxstorage.blob.core.windows.net/wilxcontainer/dir` (no recursive flag):
    - nothing is deleted, error suggests using recursion flag

3. `azcopy remove https://wilxstorage.blob.core.windows.net/wilxcontainer/dir/*` (no recursive flag):
    - Everything under dir (even the subdirectory, subdir, is deleted
    - I would have expected only file3 to be deleted, seems like '*' is acting recursively when used on a virtual directory level

-I think 1. and 3. scenarios with the wildcards should behave the same, i.e. treat the container and virtual directories as similar entities when using wildcards.
-using /* acts as a substitute for the recursive flag, which I do not think is by design.
-it would be great if there was a way to delete blobs only at a certain dir level. Removing the recursive nature of the current `*` wildcard globbing would solve this, if we allow the wildcard to achieve this.

**Comment by hdost** [comment]
There is a similar issue with the --exclude flag, not sure if it's related, but exclude will not exclude entire directories.

**Comment by zezha-msft** [comment]
@williexu @hdost thanks for your patience. The remove command was re-written in 10.0.9 with a much cleaner and less error-prone design. 

In short, pattern matches are no longer allowed for remove. And instead, the include/exclude flags are now patterns on the file names. If recursive flag is false, the immediate files under a directory will be deleted, if true, all the sub-directories will be removed too. Please refer to the help message for more info, and feel free to give it a try.
