### ISSUE TITLE
Azcopy is much slower compare to earlier version 

### ISSUE THREAD

**Issue by challaswamy097** [Azure/azure-storage-azcopy#2586]
### The performance is prolonged and even the percentage information displays wrong. if you see the below provided info it copied 635158 files out of 905800  but still shows 51.3 %
INFO:
51.3 %, 635158 Done, 0 Failed, 270642 Pending, 905800 Total, 2-sec Throughput (Mb/s): 0

**Comment by challaswamy097** [comment]
Which AzCopy version are you comparing v10.23.0 with? v10.22.0
Is only sync operation compromised or all? I think only Sync

**Comment by siminsavani-msft** [comment]
Thank you for your response @challaswamy097 ! As mentioned in https://github.com/Azure/azure-storage-azcopy/issues/2596, we are taking deeper look into performance and will update both threads.

**Comment by challaswamy097** [comment]
@siminsavani-msft Can you help me to download the Azcopy of older version for Linux azcopy_linux_amd64_10.22.2

**Comment by siminsavani-msft** [comment]
Absolutely @challaswamy097 ! Here you go: https://azcopyvnextrelease.blob.core.windows.net/releases/release-10.22.2-20240110/drop.zip

**Comment by wyw656141** [comment]
@siminsavani-msft 
Your blob link has expired. The same problem exists in our Azure DevOps pipeline.
The command is as follows:
```
azcopy copy <sourceUrl> <targetUrl> --recursive=true --overwrite=ifSourceNewer --preserve-smb-permissions=true --preserve-smb-info=true
```
**(Disk may be limiting speed)** will not appear in 10.22.2, but this message exists in 10.30 and the latest version. Under the same files and environment, the Elapsed Time will increase significantly. 

<img width="1027" alt="Image" src="https://github.com/user-attachments/assets/faf9a0e4-a707-411c-af40-a78a51ae978e" />

<img width="1302" alt="Image" src="https://github.com/user-attachments/assets/6eebec72-91fc-4192-a6eb-737614c3bba0" />
