### ISSUE TITLE
AzCopy auto-login fails when using Azure CLI authorization with user assigned managed identity

### ISSUE THREAD

**Issue by Minreaux** [Azure/azure-storage-azcopy#2587]
### Which version of the AzCopy was used? 
AzCopy 10.23.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 Pro (SKU: win10-22h2-pro-g2)

### What command did you run?
Ran these commands in pwsh 7.4.1:
```
$Env:AZCOPY_AUTO_LOGIN_TYPE="AZCLI"
az login --identity
azcopy --log-level NONE --output-level "essential" copy "<blob>" "<destination>" --check-length=false
```
### What problem was encountered?
I currently use `azcopy login --identity` to run azcopy commands on an Azure VM that has a user assigned managed identity. Each time I run this command, I get the following messages:
```
azcopy login --identity
INFO: 'azcopy login' command will be deprecated starting release 10.22. Use auto-login instead. Visit https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-without-a-secret-store  to know more.
INFO: Login with identity succeeded.
```
Because it says `azcopy login` is deprecated, I attempted to use the recommended auto-login functionality from [this link](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-without-a-secret-store).

I ran the commands listed in the "What command did you run" section and received the following error:
```
Failed to perform Auto-login: AzureCLICredential: ERROR: Tenant shouldn't be specified for managed identity account
```

### How can we reproduce the problem in the simplest way?
1.  Provision an Azure Windows VM with a user assigned managed identity attached to it
2.  Open pwsh
3.  Run `$Env:AZCOPY_AUTO_LOGIN_TYPE="AZCLI"`
4.  Run `az login --identity`
5.  Run any azcopy command that requires authentication
6.  Observe the error

### Have you found a mitigation/solution?
Setting `$Env:AZCOPY_AUTO_LOGIN_TYPE="MSI"` fixes the issue and allows AzCopy to use the user assigned managed identity without requiring `azcopy login --identity` or `az login --identity`, however, I think it is confusing that the Azure CLI managed authentication for AzCopy did not work with the user assigned managed identity.

**Comment by pranavmalik-msft** [comment]
Hey @Minreaux ,
We have a dedicated page outlining the usage of the Azcopy Autologin feature. I would recommend referring to the following link for detailed information: [AzCopy Autologin Feature](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store)).
Moreover we have decided not to deprecate Azcopy login , we have a fix in place for the message that you see over the console citing the deprecation.

**Comment by specialforest** [comment]
@pranavmalik-msft the referenced page does not mention AZCLI at all.

**Comment by pablospe** [comment]
This is what it worked for me:
```bash
az login --use-device-code 
export AZCOPY_AUTO_LOGIN_TYPE=AZCLI
azcopy copy URL ...
```
