### ISSUE TITLE
ORA-03137: malformed TTC packet from client rejected about copying data from a Synapse SQL pool to an Oracle db using Data Factory

### ISSUE THREAD

**Issue by pscorca** [Azure/azure-storage-azcopy#2597]
Hi, inside an Azure Data Factory instance I've implemented a pipeline to copy data from a Synapse SQL pool to an Oracle db on premise. I need to copy a Synapse table having 260 columns and more of three millions of rows. For the copy activity I've enabled the staging. When I run the pipeline I've this error message:

ErrorCode=UserErrorOdbcOperationFailed,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=ERROR [HY000] [Microsoft][ODBC Oracle Wire Protocol driver][Oracle]ORA-39776: fatal Direct Path API error loading table "DWH"."xxxxxx"
ORA-03137: malformed TTC packet from client rejected: [klaprs_11] [60] [512] [3] [4] [573] [] []
,Source=Microsoft.DataTransfer.ClientLibrary.Odbc.OdbcConnector,''Type=Microsoft.DataTransfer.ClientLibrary.Odbc.Exceptions.OdbcException,Message=ERROR [HY000] [Microsoft][ODBC Oracle Wire Protocol driver][Oracle]ORA-39776: fatal Direct Path API error loading table "DWH"."xxxxxx"
ORA-03137: malformed TTC packet from client rejected: [klaprs_11] [60] [512] [3] [4] [573] [] []
,Source=msora28.dll,'

Any helps to me, please?

**Comment by siminsavani-msft** [comment]
Hi @pscorca AzCopy is not involved in this scenario. You are likely to get better expertise by opening a Support Request against Azure Data Factory. I believe this link will guide you in getting that support: https://learn.microsoft.com/en-us/azure/data-factory/quota-increase.

Closing as not AzCopy related.
