### ISSUE TITLE
Does azcopy work like replication?

### ISSUE THREAD

**Issue by ye-idealump** [Azure/azure-storage-azcopy#2605]
Does azcopy work like replication in Azure for wordpress uploads?

**Comment by vibhansa-msft** [comment]
Can you share more details on what kind of workflow you are trying to solve with AzCopy?
If you wish to copy your contents from one storage account to another then yes AzCopy can help you achieve that without any data movement on host (purely backend to backend copy)

**Comment by vibhansa-msft** [comment]
Closing this as there is no update. Feel free to reopen or post your queries in this thread.
