### ISSUE TITLE
Include chocolatey package

### ISSUE THREAD

**Issue by StephenCleary** [Azure/azure-storage-azcopy#262]
Please upload a Chocolatey Nupkg as part of your release process (Chocolatey also supports prerelease versions).

**Comment by zezha-msft** [comment]
Hi @StephenCleary, thanks for the reaching out! 

I'll bring up your suggestion with the team.

**Comment by zezha-msft** [comment]
It looks like a community member has been releasing AzCopy on Chocolatey: https://community.chocolatey.org/packages/azcopy10#versionhistory

I'll close this for now since we are tracking the ask with the overall package manager work (which includes several other similar asks).
