### ISSUE TITLE
Provide a statically linked version of azcopy for linux

### ISSUE THREAD

**Issue by rhudea** [Azure/azure-storage-azcopy#263]
The linux binary of azcopy is a dynamically linked ELF executable. Building a statically one (CGO_ENABLED=0) will allow running this binary on a larger variety of docker images.

**Comment by zezha-msft** [comment]
Hi @rhudea, thanks for reaching out! I'll bring up your suggestion with the team. Thanks!

**Comment by vibhansa-msft** [comment]
We do have some dependency on the CGO (some indirect modules use it) and hence CGO can not be disabled while building the binaries. Closing this for now. We do have plans to migrate to latest version of Golang and as part of that we are also planning to reduce the CGO dependencies.
