### ISSUE TITLE
No Transfer - files on azure storage

### ISSUE THREAD

**Issue by LefeuvreG** [Azure/azure-storage-azcopy#264]
I tried 8.1 version and 10.0.8 and it was the same thing

I'm on Windows serveur 2012R2 with Powershell 5.1

I Try to send PST file on the Azure Storage to integrate it on Exchnage O365.  I generated on Administation portal the URI of the storage.
I can connect on it with "Microsoft Azure Storage Explorer"

I used these commands
  on 8.1 :     ./azcopy.exe source destination /V:"d:\temp\logazcopy.log" /Pattern:"test*.pst" /Y
  on 10.0.8  ./azcopy.exe cp source destination

where destination is the uri "https://xxxxxx.blob/core.windows.net/etc......"

In the 8.1 log I see a lot of  "[2019/03/07 12:39:25.103+01:00][VERBOSE] Finished: 0 file(s), 0 B; Average Speed:0 B/s." and nothing on the Azure storage.

In the 10.0.8 one linet with several same thing
"2019/03/07 10:54:41 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  1, T:  1"

I verified the internet connection and it's OK. 

I don't know what can I do to progress with this issue.

Thanks by advanced for your help.

**Comment by zezha-msft** [comment]
Hi @LefeuvreG, thanks for reaching out!

To clarify, your SAS is included in the destination URL, right?

What's the output for V10?

**Comment by LefeuvreG** [comment]
Hello Zezha,
Yes, the destination is include in the URL 
on the console I have 
"Job 9833a432-d949-ff4b-5f5d-598f7dae22ea has started
Log file is located at: D:\USERS\a0h48001/.azcopy/9833a432-d949-ff4b-5f5d-598f7dae22ea.log

0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,"
Job a6cc66c6-33af-db47-5fc4-fcd77b34a12b summary
Elapsed Time (Minutes): 20.0372
Total Number Of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed

I Tried again this morning and in the log I have a lot of things. Yesterday I didn't have all these lines!
I replace some characters by ...
2019/03/08 07:29:43 AzcopyVersion  10.0.8-Preview
2019/03/08 07:29:43 OS-Environment  windows
2019/03/08 07:29:43 OS-Architecture  amd64
2019/03/08 07:29:43 Job-Command cp \\acgonsmm05\archives_pst\a0h48001\boites\testgl2.pst https://059d3...c56445.blob.core.windows.net/ingestiondata?se=2019-04-07t07%3A27%3A02z&si=ingestionsasforazcopy201903060956345666&sig=REDACTED&sr=c&sv=2015-04-05 
2019/03/08 07:29:43 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  0, T:  0
2019/03/08 07:29:43 JobID=1689169d-f81e-be4c-73f8-6bf846fd49a6, credential type: Anonymous
2019/03/08 07:29:43 scheduling JobID=1689169d-f81e-be4c-73f8-6bf846fd49a6, Part#=0, Transfer#=0, priority=0
2019/03/08 07:29:43 INFO: [P#0-T#0] has worker 15 which is processing TRANSFER
2019/03/08 07:29:43 INFO: [P#0-T#0] Starting transfer: Source "//acgonsmm05/archives_pst/a0h48001/boites/testgl2.pst" Destination "https://059d3...c56445.blob.core.windows.net/ingestiondata/testgl2.pst?se=2019-04-07t07%3A27%3A02z&si=ingestionsasforazcopy201903060956345666&sig=REDACTED&sr=c&sv=2015-04-05". Specified chunk size 8388608
2019/03/08 07:29:43 ==> OUTGOING REQUEST (Try=1)
   PUT https://059d3...c56445.blob.core.windows.net/ingestiondata/testgl2.pst?blockid=mjiwymnmm...zwzmymnkn2q1owqx&comp=block&se=2019-04-07t07%3A27%3A02z&si=ingestionsasforazcopy201903060956345666&sig=REDACTED&sr=c&sv=2015-04-05&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.0.8-Preview Azure-Storage/0.5 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [35d8b12a-fe10-4673-5f65-1a81094f6378]
   X-Ms-Version: [2018-03-28]

2019/03/08 07:29:43 ==> OUTGOING REQUEST (Try=1)
   PUT https://059d3bae316246808c56445.blob.core.windows.net/ingestiondata/testgl2.pst?blockid=mdjiy2yzogytz...ztewnmeznjbk&comp=block&se=2019-04-07t07%3A27%3A02z&si=ingestionsasforazcopy201903060956345666&sig=REDACTED&sr=c&sv=2015-04-05&timeout=901
   Content-Length: [9216]
   User-Agent: [AzCopy/10.0.8-Preview Azure-Storage/0.5 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [0b0805ba-169f-49df-6c1e-3712b4b317df]
   X-Ms-Version: [2018-03-28]

2019/03/08 07:29:45 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:29:47 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:29:49 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:29:51 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:29:53 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:29:55 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:29:57 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:29:59 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:30:01 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:30:03 PERF: disk disk IS NOT limiting throughput. States: R:  0, D:  0, W:  0, B:  2, T:  2
2019/03/08 07:30:04 ==> REQUEST/RESPONSE (Try=1/21.0792041s[SLOW >3s], OpTime=21.0792041s) -- REQUEST ERROR
   PUT https://059d3...c56445.blob.core.windows.net/ingestiondata/testgl2.pst?blockid=mjiwymnmmz...zltrkogqtzwzmymnkn2q1owqx&comp=block&se=2019-04-07t07%3A27%3A02z&si=ingestionsasforazcopy201903060956345666&sig=REDACTED&sr=c&sv=2015-04-05&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.0.8-Preview Azure-Storage/0.5 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [35d8b12a-fe10-4673-5f65-1a81094f6378]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-storage-azcopy/ste.newAzcopyHTTPClientFactory.func1.1, /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:100
HTTP request failed

Put https://059d3...c56445.blob.core.windows.net/ingestiondata/testgl2.pst?blockid=MjIwYmNmMzMtM...kOGQtZWZmYmNkN2Q1OWQx&comp=block&se=2019-04-07T07%3A27%3A02Z&si=IngestionSasForAzCopy201903060956345666&sig=tPuJhMKZCLuyaxcvEeBgfjdvoNxTG4pyR4hLsZZyJp8%3D&sr=c&sv=2015-04-05&timeout=901: dial tcp 52.239.134.164:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Thanks for your help

**Comment by zezha-msft** [comment]
Hi @LefeuvreG, thanks for providing the info!

Is your server using a proxy? If yes, please set the proxy info following [these instructions](https://github.com/Azure/azure-storage-azcopy#configure-proxy-settings).

**Comment by LefeuvreG** [comment]
Hello Zezha, thank you dor answer,
Yes, I need a proxy with user and password to connect to Internet.
I tried to declare enviconment variable : set https_proxy=<proxy IP>:<proxy port> or set https_proxy=user:password@<proxy IP>:<proxy port>

But the result is always the same 
ERROR:
-> github.com/Azure/azure-storage-azcopy/ste.newAzcopyHTTPClientFactory.func1.1, /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:100
HTTP request failed.
Put https://059d3bae316246808c56445.blob.core.windows.net/ingestiondata/testgl2.pst?blockid=YTNmYTFiYmMtM...NDY2MjQ2YjY3NzYw&comp=block&se=2019-04-11T10%3A43...&si=IngestionSasForAzCopy201903060956345666&sig=Ythvme9XX...sCoFyRt4vnUVwXovOXNM%3D&sr=c&sv=2015-04-05&timeout=901: dial tcp 52.239.134.164:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by zezha-msft** [comment]
Hi @LefeuvreG, could you please double-check the syntax: `https_proxy=<user>:<pass>@<proxy IP>:<proxy port>

You could also try setting the environment variable through the UI:

> You can also view or modify the environment variables by selecting System from the Control Panel, selecting Advanced system settings, and clicking Environment Variables.

@artemuwka @seguler any tips on using a proxy?

**Comment by LefeuvreG** [comment]
Hi Zezha,
I tried to realise a transfer on a computer without proxy address (line direct on internet) with Azcopy10. The result is the same "Serveur failed to identicate the request" ! 
I tried the same thing with Azcopy 8.1 and it worked. 
Unfortunately I can't use this line for my PST because the flow is not high enough

On my normal line where the flow is good unable to pass the proxy with ver8.1 or 10.
with version 10 the environment variable has no result.
On version 8.1, I tried put in the azcopy folder different "azcopy.exe.config" but no result only 
[2019/03/13 17:05:12.209+01:00][VERBOSE] Finished: 0 file(s), 0 B; Average Speed:0 B/s
I despair...

**Comment by zezha-msft** [comment]
Hi @LefeuvreG, I'm sorry to hear that.

Did you use the same SAS for both V8.1 and V10?

Could you please verify the proxy information? It sounds to me like they may be the source of the issue. Please refer to this [page](https://helpdeskgeek.com/networking/internet-connection-problem-proxy-settings/).

**Comment by artemuwka** [comment]
Hi @LefeuvreG! Did you use CMD to set the proxy variables for AzCopyV10? It won't work in PowerShell.

**Comment by seguler** [comment]
Proxy documentation is up to date, and correct: https://github.com/Azure/azure-storage-azcopy/#configure-proxy-settings

> export https_proxy=MYDOMAIN%5Cmyuser:mypassword@192.168.1.5:443

**Comment by LefeuvreG** [comment]
Hi thank you for your interest to my issue,
Of course I used the same SAS in the two cases. But in the case that I used V10 on a line without proxy, it's not worked.
Yes I used CMD to set proxy variable for AzcopyV10 and I verified it in the UI of windows system.
I'm on windows system and "export https...." is not supported so I can't use this syntax to add the variable but only set https_proxy....

It works now. I found two things 
    1. the proxy address, I used the name of the proxy server and not the Ip address in the variable environment only Ip address is good.
    2. The command not works in a batch file ! Very strange. I copied the command from the file to the cmd console and it worked. In powershell it doesn't work in a script file or directly with the command line.

Thank you for your help.

**Comment by zezha-msft** [comment]
@LefeuvreG glad to hear that it's working now!

You observations are interesting. It sounds like the proxy setting somehow is not shared with Powershell. We'll do some experimentation when we get a chance.
