### ISSUE TITLE
Fails after several Minutes

### ISSUE THREAD

**Issue by VanGone1337** [Azure/azure-storage-azcopy#2648]
### Which version of the AzCopy was used? 
10.24.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy.exe copy "C:\Outlook\Alle\*" "SAS-Key"

### What problem was encountered?
Stopped with Failed Tasks

### How can we reproduce the problem in the simplest way?
Tried to Import Every Mailbox itself. Some of them are over 20 GB
Same issue after 15-20 Minutes

**Comment by siminsavani-msft** [comment]
Hi @VanGone1337 ! Could you please share the error that is showing in the logs for the failed tasks? It would also be good to run with the `--log-level=DEBUG` flag.

**Comment by VanGone1337** [comment]
Hi @siminsavani-msft, thanks for your reply. We managed to let it run through the Azreu Storage Explorer.

**Comment by siminsavani-msft** [comment]
Glad to hear it, I will close this issue. Let us know if you are still facing any issues!
