### ISSUE TITLE
Support Azure Arc Identity Endpoint for AZCOPY_AUTO_LOGIN_TYPE=MSI

### ISSUE THREAD

**Issue by kriszentner** [Azure/azure-storage-azcopy#2654]
### Which version of the AzCopy was used? 

10.24.0

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

export AZCOPY_AUTO_LOGIN_TYPE=MSI
azcopy copy [URL] [DESTINATION FILE]

### What problem was encountered?
```
INFO: Scanning...

Failed to perform Auto-login: ManagedIdentityCredential: ManagedIdentityCredential: Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fstorage.azure.com": dial tcp 169.254.169.254:80: connect: network is unreachable.
```

The issue is that azcopy is unaware of the Azure Arc IMDS endpoint at localhost:40342.
I would also accept being able to log in via access token, but there doesn't seem to be a supported method to do this.

### How can we reproduce the problem in the simplest way?
The above is about as simple as can be.

### Have you found a mitigation/solution?
For single files, I can use the instructions to get an access token:
https://learn.microsoft.com/en-us/azure/azure-arc/servers/managed-identity-authentication

And then I can use curl with the `--oauth-bearer` argument to download files. However, downloading many files or doing the equivalent of `azcopy sync` becomes complicated.

**Comment by gapra-msft** [comment]
@chlowell Does the azidentity SDK support the Azure Arc IMDS endpoint?

**Comment by kriszentner** [comment]
azcopy gets a little further when entering the `IDENTITY_ENDPOINT` variable.

I ensured that the Arc identity has [Storage Blob Data Reader](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-reader) access on the storage account. I also confirmed the copy command works with Azure hosts that have the same access.

I set the following:
```bash
export AZCOPY_AUTO_LOGIN_TYPE=MSI
export IMDS_ENDPOINT="http://localhost:40342"
export IDENTITY_ENDPOINT="http://localhost:40342/metadata/identity/oauth2/token"
```

```
INFO: Scanning...
INFO: Autologin not specified.
INFO: Authenticating to source using Unknown
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason GET https://<storageaccount>.blob.core.windows.net/<containername>
--------------------------------------------------------------------------------
RESPONSE 401: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
ERROR CODE: NoAuthenticationInformation
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:eaa38772-801e-0076-4bf5-946597000000
Time:2024-04-22T20:39:37.0348360Z</Message></Error>
--------------------------------------------------------------------------------
.
```
I also tried the above by setting:
```bash
IDENTITY_ENDPOINT=http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com
```
with the same result.

I suspect that perhaps it's not doing the challenge token handoff that need to take place to get a proper storage token. This is because when the call is made to the IMDS endpoint, you'll get a breadcrumb to the challenge token file location, but you'll also get a misleading `401` error:

```bash
curl -s -D - -H Metadata:true "http://127.0.0.1:40342/metadata/identity/oauth2/token?api
-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com"

HTTP/1.1 401 Unauthorized
Content-Type: application/json
Www-Authenticate: Basic realm=/var/opt/azcmagent/tokens/95df74bd-8a2b-41e3-a506-c5565d9600cc.key
Date: Mon, 22 Apr 2024 21:26:47 GMT
Content-Length: 253

{"error":"unauthorized_client","error_description":"Missing Basic Authorization header","error_codes":[401],"timestamp":"2024-04-22 21:26:47.294978719 +0000 UTC m=+610443.507420729","trace_id":"","correlation_id":"443f0a55-fade-4efd-a06b-473db605256d"}
```

Validating permissions - I'm able copy a file the very manual way doing the following:
```bash
CHALLENGE_TOKEN_PATH=$(curl -s -D - -H Metadata:true "http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com" | grep Www-Authenticate | cut -d "=" -f 2 | tr -d "[:cntrl:]")
CHALLENGE_TOKEN=$(cat $CHALLENGE_TOKEN_PATH)
STORAGE_TOKEN=$(curl -s -H Metadata:true -H "Authorization: Basic $CHALLENGE_TOKEN" "http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com")
curl --oauth2-bearer "$STORAGE_TOKEN" -i -H 'x-ms-version: 2019-12-12' "https://<mystorageaccount>.blob.core.windows.net/myfile" -o myfile
```

**Comment by kriszentner** [comment]
An additional datapoint, this does work with Go.

I tried the storage-quickstart.go from [this tutorial](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-go?tabs=roles-azure-portal)

This simple Go code was able to download and print the file with the following environment vars set:

```bash
IMDS_ENDPOINT=http://localhost:40342
IDENTITY_ENDPOINT=http://localhost:40342/metadata/identity/oauth2/token
```

```golang
import (
        "bufio"
        "bytes"
        "context"
        "fmt"
        "log"
        "os"

        "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
        "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
)

// Azure Storage Quickstart Sample - Demonstrate how to upload, list, download, and delete blobs.
//
// Documentation References:
// - What is a Storage Account - https://docs.microsoft.com/azure/storage/common/storage-create-storage-account
// - Blob Service Concepts - https://docs.microsoft.com/rest/api/storageservices/Blob-Service-Concepts
// - Blob Service Go SDK API - https://godoc.org/github.com/Azure/azure-storage-blob-go
// - Blob Service REST API - https://docs.microsoft.com/rest/api/storageservices/Blob-Service-REST-API
// - Scalability and performance targets - https://docs.microsoft.com/azure/storage/common/storage-scalability-targets
// - Azure Storage Performance and Scalability checklist https://docs.microsoft.com/azure/storage/common/storage-performance-checklist
// - Storage Emulator - https://docs.microsoft.com/azure/storage/common/storage-use-emulator

func handleError(err error) {
        if err != nil {
                log.Fatal(err.Error())
        }
}

func main() {
        fmt.Printf("Azure Blob storage quick start sample\n")

        // TODO: replace <storage-account-name> with your actual storage account name
        url := "https://<mystorageaccount>.blob.core.windows.net/"
        ctx := context.Background()

        credential, err := azidentity.NewDefaultAzureCredential(nil)
        handleError(err)

        client, err := azblob.NewClient(url, credential, nil)
        handleError(err)


        // Download the blob
        containerName := "<mycontainer>"
        blobName := "<myfile>"
        get, err := client.DownloadStream(ctx, containerName, blobName, nil)
        handleError(err)

        downloadedData := bytes.Buffer{}
        retryReader := get.NewRetryReader(ctx, &azblob.RetryReaderOptions{})
        _, err = downloadedData.ReadFrom(retryReader)
        handleError(err)

        err = retryReader.Close()
        handleError(err)

        // Print the content of the blob we created
        fmt.Println("Blob contents:")
        fmt.Println(downloadedData.String())

        fmt.Printf("Press enter key to delete resources and exit the application.\n")
        bufio.NewReader(os.Stdin).ReadBytes('\n')
        fmt.Printf("Cleaning up.\n")

}
```

**Comment by gapra-msft** [comment]
@kriszentner Does the same code work if you manually specify the credential as a 
azidentity.ManagedIdentityCredential?

**Comment by gapra-msft** [comment]
> azcopy gets a little further when entering the `IDENTITY_ENDPOINT` variable.
> 
> I ensured that the Arc identity has [Storage Blob Data Reader](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-reader) access on the storage account. I also confirmed the copy command works with Azure hosts that have the same access.
> 
> I set the following:
> 
> ```shell
> export AZCOPY_AUTO_LOGIN_TYPE=MSI
> export IMDS_ENDPOINT="http://localhost:40342"
> export IDENTITY_ENDPOINT="http://localhost:40342/metadata/identity/oauth2/token"
> ```
> 
> ```
> INFO: Scanning...
> INFO: Autologin not specified.
> INFO: Authenticating to source using Unknown
> INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
> 
> failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason GET https://<storageaccount>.blob.core.windows.net/<containername>
> --------------------------------------------------------------------------------
> RESPONSE 401: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
> ERROR CODE: NoAuthenticationInformation
> --------------------------------------------------------------------------------
> ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
> RequestId:eaa38772-801e-0076-4bf5-946597000000
> Time:2024-04-22T20:39:37.0348360Z</Message></Error>
> --------------------------------------------------------------------------------
> .
> ```
> 
> I also tried the above by setting:
> 
> ```shell
> IDENTITY_ENDPOINT=http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com
> ```
> 
> with the same result.
> 
> I suspect that perhaps it's not doing the challenge token handoff that need to take place to get a proper storage token. This is because when the call is made to the IMDS endpoint, you'll get a breadcrumb to the challenge token file location, but you'll also get a misleading `401` error:
> 
> ```shell
> curl -s -D - -H Metadata:true "http://127.0.0.1:40342/metadata/identity/oauth2/token?api
> -version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com"
> 
> HTTP/1.1 401 Unauthorized
> Content-Type: application/json
> Www-Authenticate: Basic realm=/var/opt/azcmagent/tokens/95df74bd-8a2b-41e3-a506-c5565d9600cc.key
> Date: Mon, 22 Apr 2024 21:26:47 GMT
> Content-Length: 253
> 
> {"error":"unauthorized_client","error_description":"Missing Basic Authorization header","error_codes":[401],"timestamp":"2024-04-22 21:26:47.294978719 +0000 UTC m=+610443.507420729","trace_id":"","correlation_id":"443f0a55-fade-4efd-a06b-473db605256d"}
> ```
> 
> Validating permissions - I'm able copy a file the very manual way doing the following:
> 
> ```shell
> CHALLENGE_TOKEN_PATH=$(curl -s -D - -H Metadata:true "http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com" | grep Www-Authenticate | cut -d "=" -f 2 | tr -d "[:cntrl:]")
> CHALLENGE_TOKEN=$(cat $CHALLENGE_TOKEN_PATH)
> STORAGE_TOKEN=$(curl -s -H Metadata:true -H "Authorization: Basic $CHALLENGE_TOKEN" "http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com")
> curl --oauth2-bearer "$STORAGE_TOKEN" -i -H 'x-ms-version: 2019-12-12' "https://<mystorageaccount>.blob.core.windows.net/myfile" -o myfile
> ```

From the initial AzCopy error message here, it looks like AzCopy did not recognize the Auto Login Type env var, which is why its not picking up MSI. Are you sure the environment variable is set before performing the AzCopy command?

**Comment by kriszentner** [comment]
> @kriszentner Does the same code work if you manually specify the credential as a azidentity.ManagedIdentityCredential?

I swapped line in the code:

```go
 credential, err := azidentity.NewDefaultAzureCredential(nil)
```

with

```go
credential, err := azidentity.NewManagedIdentityCredential(nil)
```

It works only if I set the following environment variables:
```bash
export IMDS_ENDPOINT=http://localhost:40342
export IDENTITY_ENDPOINT=http://localhost:40342/metadata/identity/oauth2/token
```

Otherwise it hangs and eventually fails with: 
```
2024/05/30 00:25:41 ManagedIdentityCredential: Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fstorage.azure.com": dial tcp 169.254.169.254:80: connect: network is unreachable
exit status 1
```

**Comment by gapra-msft** [comment]
@kriszentner Could you retry the azcopy command with those two variables set and set AZCOPY_AUTO_LOGIN_TYPE=MSI

AzCopy under the hood in the latest version uses the same ManagedIdentityCredential, so as long as AzCopy can recognize the auto login type, it should authenticate successfully.

**Comment by kriszentner** [comment]
> > azcopy gets a little further when entering the `IDENTITY_ENDPOINT` variable.
> > I ensured that the Arc identity has [Storage Blob Data Reader](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-reader) access on the storage account. I also confirmed the copy command works with Azure hosts that have the same access.
> > I set the following:
> > ```shell
> > export AZCOPY_AUTO_LOGIN_TYPE=MSI
> > export IMDS_ENDPOINT="http://localhost:40342"
> > export IDENTITY_ENDPOINT="http://localhost:40342/metadata/identity/oauth2/token"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > INFO: Scanning...
> > INFO: Autologin not specified.
> > INFO: Authenticating to source using Unknown
> > INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
> > 
> > failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason GET https://<storageaccount>.blob.core.windows.net/<containername>
> > --------------------------------------------------------------------------------
> > RESPONSE 401: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
> > ERROR CODE: NoAuthenticationInformation
> > --------------------------------------------------------------------------------
> > ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
> > RequestId:eaa38772-801e-0076-4bf5-946597000000
> > Time:2024-04-22T20:39:37.0348360Z</Message></Error>
> > --------------------------------------------------------------------------------
> > .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also tried the above by setting:
> > ```shell
> > IDENTITY_ENDPOINT=http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with the same result.
> > I suspect that perhaps it's not doing the challenge token handoff that need to take place to get a proper storage token. This is because when the call is made to the IMDS endpoint, you'll get a breadcrumb to the challenge token file location, but you'll also get a misleading `401` error:
> > ```shell
> > curl -s -D - -H Metadata:true "http://127.0.0.1:40342/metadata/identity/oauth2/token?api
> > -version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com"
> > 
> > HTTP/1.1 401 Unauthorized
> > Content-Type: application/json
> > Www-Authenticate: Basic realm=/var/opt/azcmagent/tokens/95df74bd-8a2b-41e3-a506-c5565d9600cc.key
> > Date: Mon, 22 Apr 2024 21:26:47 GMT
> > Content-Length: 253
> > 
> > {"error":"unauthorized_client","error_description":"Missing Basic Authorization header","error_codes":[401],"timestamp":"2024-04-22 21:26:47.294978719 +0000 UTC m=+610443.507420729","trace_id":"","correlation_id":"443f0a55-fade-4efd-a06b-473db605256d"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Validating permissions - I'm able copy a file the very manual way doing the following:
> > ```shell
> > CHALLENGE_TOKEN_PATH=$(curl -s -D - -H Metadata:true "http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com" | grep Www-Authenticate | cut -d "=" -f 2 | tr -d "[:cntrl:]")
> > CHALLENGE_TOKEN=$(cat $CHALLENGE_TOKEN_PATH)
> > STORAGE_TOKEN=$(curl -s -H Metadata:true -H "Authorization: Basic $CHALLENGE_TOKEN" "http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fstorage.azure.com")
> > curl --oauth2-bearer "$STORAGE_TOKEN" -i -H 'x-ms-version: 2019-12-12' "https://<mystorageaccount>.blob.core.windows.net/myfile" -o myfile
> > ```
> 
> From the initial AzCopy error message here, it looks like AzCopy did not recognize the Auto Login Type env var, which is why its not picking up MSI. Are you sure the environment variable is set before performing the AzCopy command?

I tried this again today and I'm having trouble replicating the error. So I'm going to close this. Thanks so much for the time you spent on this, and my apologies for having wasted your time.
