### ISSUE TITLE
AzCopy cannot copy blob from a storage account with Object Replication policy

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#2655]
### Which version of the AzCopy was used? 
10.23.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac

### What command did you run?
s2s Azure blob copy

### What problem was encountered?
While reading the source, AzCopy incorrectly treat the object replication header as metadata, whose name doesn't comply to the rules of metadata names and cause the copy to fail.

![image](https://github.com/Azure/azure-storage-azcopy/assets/39359541/5a64f638-a9e8-4185-95f7-24916df82d28)

![image](https://github.com/Azure/azure-storage-azcopy/assets/39359541/3aa841ac-190c-424e-a43e-dc8670569ab2)

### How can we reproduce the problem in the simplest way?
Assign an object replication policy to a storage account. Go to the replicated source container. View properties of a blob on Portal and make sure there is an Object replication field. Use AzCopy to copy this blob to another storage account.

### Have you found a mitigation/solution?
No

**Comment by tanyasethi-msft** [comment]
Hi @JasonYeMSFT, 
Thanks for reporting this. The team is actively working on this issue and a fix will be available in the next release.

**Comment by tanyasethi-msft** [comment]
Code Generator release: https://github.com/Azure/autorest.go/releases/tag/v4.0.0-preview.65

**Comment by kaptinkoda** [comment]
Running into the same issue in AzCopy v10.24.0.
Error Message: Status: 400 The metadata specified is invalid. It has characters that are not permitted.
I was able to copy using older version AzCopy v10.0.22631

**Comment by tanyasethi-msft** [comment]
Hi @kaptinkoda, this is not fixed yet. It will be available from AzCopy next release.

**Comment by tanyasethi-msft** [comment]
This was fixed in go sdk - [Storage - code generator update by tanyasethi-msft · Pull Request #22792 · Azure/azure-sdk-for-go (github.com)](https://github.com/Azure/azure-sdk-for-go/pull/22792)
AzCopy next release in July 2024 will have this fix.

**Comment by tanyasethi-msft** [comment]
Next Azcopy release should fix this issue.

**Comment by JasonYeMSFT** [comment]
AzCopy 10.26.0 is released. Should we close this issue?

**Comment by tanyasethi-msft** [comment]
Yes, this was fixed. Closing the issue.
