### ISSUE TITLE
setting --log-level to ERROR or WARNING removes Job Summary block

### ISSUE THREAD

**Issue by FairW** [Azure/azure-storage-azcopy#2659]
azcopy version: 10.22.0 on Linux

./azcopy/azcopy copy '../filearchive/*' 'https://<target-url>?<sas-toekn>' --overwrite ifSourceNewer --recursive --log-level "ERROR" --from-to=LocalBlob

The summary section in enclosed screendump (present in logfile when --log-level is set to INFO) is _not_ displayed when setting --log-level to ERROR or WARNING.
It would be nice to have the summary section whatever --log-level is set. 
-Maybe this is a feature because summary section is generated based on available content in the log file (i.e. only when INFO or DEBUG is set..)?

![image](https://github.com/Azure/azure-storage-azcopy/assets/16018281/da8b8e8c-d01c-4317-9de0-321caf80288e)

**Comment by gapra-msft** [comment]
@FairW are you still experiencing this with the latest AzCopy? (10.24.0) We recently added a feature to print some of these summaries no matter the log level above Error https://github.com/Azure/azure-storage-azcopy/pull/2553

**Comment by FairW** [comment]
I tried version 10.24.0 - and you are right; using --log-level [ "ERROR" | "WARNING" ] now output s the summary block I was looking for. 
-Thanks! Case closed.
