### ISSUE TITLE
Python Bindings? (Feature request)

### ISSUE THREAD

**Issue by marcrleonard** [Azure/azure-storage-azcopy#266]
I am curious if there are any plans to provide python bindings for this library. It would be very helpful for integrating into larger, automated systems.

**Comment by zezha-msft** [comment]
Hi @marcrleonard, thanks for reaching out!

Bindings in python (and other languages) are definitely on our roadmap. We'll get to them after GA. Thanks for the feedback!

**Comment by seguler** [comment]
YES! This is a great idea.

@marcrleonard -- tell us about your larger automated systems. What are you going to do with AzCopy in those systems ?

**Comment by marcrleonard** [comment]
@seguler We automate uploading/downloading of files via our our internal API. We try and treat it like a 'blackbox', so we send jobs to remote machines that do the work, and query their status. Currently, we use the Azure python sdk, but it's significantly slower than azcopy 10. Given this, it would be nice to interact with a python library, rather than parsing output of a command line utility :-)

**Comment by gabe-microsoft** [comment]
+1 My team has a very similar use case. We use AzCopy because it is much, much faster than using the Python Azure API.

**Comment by matthai** [comment]
+1

**Comment by JohnRusk** [comment]
We don't have bindings yet, and the work to create them hasn't reached the top of our list yet.  But, one thing you might like to know about is the `--output-type json` command-line flag. It changes AzCopy's output to be JSON, so that's easier to parse.  So, if you're invoking AzCopy from Python (or any other tooling), it can help to set that flag because then your calling code can more easily deal with the output.

**Comment by zezha-msft** [comment]
The decision has been made to not provide bindings in other languages, but rather provide native data movement libraries. Please stay tuned for Azure updates on the upcoming SDKs.

**Comment by matthai** [comment]
> The decision has been made to not provide bindings in other languages, but rather provide native data movement libraries. Please stay tuned for Azure updates on the upcoming SDKs.

What does "native libraries" mean? C/C++?

**Comment by zezha-msft** [comment]
@matthai, sorry I meant native to the language platform, so basically DMLibs written in .NET, Java, Python.

**Comment by mockodin** [comment]
+1 definitely something that would be huge "--output-type json" out only gets your so far :-)

**Comment by sordonia** [comment]
hi, are there any news on this matter? thanks!

**Comment by AndrewJackson2020** [comment]
Is there any update on this? Would love to get either python bindings to azcopy or native bindings.
