### ISSUE TITLE
PageBlob copy operation stuck at 0% - Managed disk had private endpoint which was disabled

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-storage-azcopy#2667]
### Which version of the AzCopy was used? 
10.23.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
copy SASURL1 SASURL2 --blob-type PageBlob 
[azcopyLogFile.txt](https://github.com/Azure/azure-storage-azcopy/files/15189672/azcopyLogFile.txt)

### What problem was encountered?
Copy process stuck at 0% for 1+ hour.

### How can we reproduce the problem in the simplest way?
Copy Managed disk 1 to Managed Disk 2.
Azure managed disk had private endpoint access enabled. Same was removed. Still getting 403 error in log file for SAS URL generated.

### Have you found a mitigation/solution?
No. Need help.

**Comment by ashruti-msft** [comment]
Auth has failed with "The specified signed resource is not allowed for this resource level"; I can see your SAS has (`sr=b`) which is for Blobs. Try checking if your SAS has the correct permissions and has not expired. Also try generating a new SAS and let me know if this fixes your issue.

**Comment by AjKundnani** [comment]
> Auth has failed with "The specified signed resource is not allowed for this resource level"; I can see your SAS has (`sr=b`) which is for Blobs. Try checking if your SAS has the correct permissions and has not expired. Also try generating a new SAS and let me know if this fixes your issue.

@ashruti-msft - We're using PS script to orchestrate the copy operation using below commands. Not expecting timeout or permissions to be issue as same script is working in other environment.

**For source disk**
Grant-AzDiskAccess -ResourceGroupName $vmResourceGroupName -DiskName $($CurrentVMConfig.osdisk.Name) -Access 'Read' -DurationInSecond 45000

**For target disk**
Grant-AzDiskAccess -ResourceGroupName $vmResourceGroupName -DiskName $targetOsDiskName -DurationInSecond 86400 -Access 'Write' -ErrorAction 'Stop'

**Comment by ashruti-msft** [comment]
Hey, can you please share your SASurl with the signature redacted. Also, can you please run this test again so I can check the backend logs to investigate the issue. From your logs it looks like you ran this test last on 2024/03/28 and the backend logs have expired. Thanks!

**Comment by AjKundnani** [comment]
> Hey, can you please share your SASurl with the signature redacted. Also, can you please run this test again so I can check the backend logs to investigate the issue. From your logs it looks like you ran this test last on 2024/03/28 and the backend logs have expired. Thanks!

@ashruti-msft - Shared updated log file offline. Please review.

**Comment by pranavmalik-msft** [comment]
> > Hey, can you please share your SASurl with the signature redacted. Also, can you please run this test again so I can check the backend logs to investigate the issue. From your logs it looks like you ran this test last on 2024/03/28 and the backend logs have expired. Thanks!
> 
> @ashruti-msft - Shared updated log file offline. Please review.

As discussed offline, the logs that were shared recently have expired due to 2-day roll-over policy. The customer will retry the test with the latest version and share the newer logs.

**Comment by AjKundnani** [comment]
This issue is resolved in **10.24.0** version of azCopy client. Thanks for pointing in right direction.
