### ISSUE TITLE
Feature request: azcopy sync: local <-> local

### ISSUE THREAD

**Issue by adamjstewart** [Azure/azure-storage-azcopy#2669]
I would like to request support for local <-> local file transfers using `azcopy sync`. Similar utilities like `rsync` also support this. 

My situation is as follows. Some of the datasets we work with are hosted in Azure, and we need to be able to download them. However, we don't want our unit tests to rely on internet access, nor do we want them to download very large datasets. For our non-Azure datasets, we simply store a mock version of the dataset on disk and "download" that instead. However, this doesn't seem to work with `azcopy sync`.

### Which version of the AzCopy was used? 

10.19.0

### Which platform are you using? (ex: Windows, Mac, Linux)

macOS

### What command did you run?

```console
azcopy sync a b
```

### What problem was encountered?

```
INFO: The parameters you supplied were Source: 'a' of type Local, and Destination: 'b' of type Local
INFO: Based on the parameters supplied, a valid source-destination combination could not automatically be found. Please check the parameters you supplied.  If they are correct, please specify an exact source and destination type using the --from-to switch. Specified to nudge AzCopy when resource detection may not work (e.g. piping/emulator/azure stack); Valid FromTo are pairs of Source-Destination words (e.g. BlobLocal, BlobBlob) that specify the source and destination resource types. All valid FromTos are: BlobBlob, BlobBlobFS, BlobFSBlob, BlobFSBlobFS, BlobFSFile, BlobFSLocal, BlobFile, BlobLocal, BlobPipe, FileBlob, FileBlobFS, FileFile, FileLocal, FilePipe, GCPBlob, LocalBlob, LocalBlobFS, LocalFile, PipeBlob, PipeFile, S3Blob

error parsing the input given by the user. Failed with error the inferred source/destination combination could not be identified, or is currently not supported
```

### How can we reproduce the problem in the simplest way?

```console
azcopy sync a b
```

### Have you found a mitigation/solution?

Not yet. I also tried `file://`-style paths as well.

**Comment by gapra-msft** [comment]
Hi @adamjstewart unfortunately this feature request is beyond the scope that AzCopy is meant for, so we will not be able to take this up as a feature this at the moment.
