### ISSUE TITLE
Weird error message when source does not exist

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-azcopy#268]
```
./azcopy cp "https://myaccount.blob.core.windows.net/bigdata/20x1GB/?st=2019-003-06T23%3A04%3A00Z&se=2019-03-09T23%3A04%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=redacted" /data --recursive --md5-validation=NoCheck
Scanning...

failed to perform copy command due to error: cannot start job due to error: no transfer queued to download. Please verify the source / destination.
```

In this case 20x1GB directory does not exist. Could AzCopy not say the source path does not exist instead ?

**Comment by zezha-msft** [comment]
@seguler right now there's no such thing as a blob directory, so we scan the container with the prefix "20x1GB/". 

There might be a blob (ADLS dir stub) that's named exactly "20x1GB", so we don't want to say "it does not exist" since we didn't check for it.

**Comment by sterkhedkar** [comment]
Need more verbose error. I spent 8 crazy hours finding out what is wrong with my code.

**Comment by JohnRusk** [comment]
Maybe we could leave the existing message intact, but add something to it that says "This MAY be because the source does not exist, or no source files were found".

Or just change "no transfer queued to download" to "no source files found"
