### ISSUE TITLE
Unable to download from Storage Account using WIF and @AzureFileCopy6

### ISSUE THREAD

**Issue by dpgray94** [Azure/azure-storage-azcopy#2682]
> The new [AzureFileCopy@6](https://learn.microsoft.com/azure/devops/release-notes/2024/pipelines/sprint-236-update#new-azurefilecopy6-task-supports-secret-less-configurations) task supports workload identity federation. The task also uses Azure RBAC to access blob storage instead. This requires the identity of the service connection used to have the appropriate RBAC role e.g. [Storage Blob Data Contributor](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-contributor). See [Assign an Azure role for access to blob data](https://learn.microsoft.com/azure/storage/blobs/assign-azure-role-data-access?tabs=portal).

Following the updates to AzureFileCopy@6  - I have made changes that strip out the SAS Token when concatenating a valid URI together. However I get the following error messages in the pipeline:

InvalidContentLink: Unable to download deployment content from 'https://**redacted**.blob.core.windows.net/**filename**/**file**.json'.

I have checked the access at container level for my Service Connection which has Contributor role amongst other roles - and confirmed that my storage account is open to the public. Has anyone else had similar issues? I am probably just missing something super simple...

_Originally posted by @dpgray94 in https://github.com/Azure/azure-storage-azcopy/issues/2545#issuecomment-2112675985_

**Comment by souravgupta-msft** [comment]
Hi @dpgray94. How is this related to AzCopy?
If you are looking for Workload Identity support, the next AzCopy release will have this.

**Comment by dpgray94** [comment]
Hi @souravgupta-msft - https://github.com/Azure/azure-storage-azcopy/issues/2545# is the closest/only related forum where I could find any information regarding workload identity and AzureFileCopy that was still receiving updates. I believe that https://github.com/microsoft/azure-pipelines-tasks/issues/19207 was closed but has little information.

If this is not the correct place to raise a question regarding WIF and AzureFileCopy please can you point me in the right direction?

**Comment by souravgupta-msft** [comment]
This is not the correct repo for queries/issues related to AzureFileCopy. You can create a new issue in [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks) repo.
