### ISSUE TITLE
Unable to delete the files not completed automaticly when fileshare is full.

### ISSUE THREAD

**Issue by v-youxie** [Azure/azure-storage-azcopy#2685]
### Which version of the AzCopy was used? 
10.24.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
.\azcopy.exe copy "C:\Users\v-youxie\Downloads\123" "https://xie********.file.core.chinacloudapi.cn/testing?sv**********************************************" --preserve-smb-permissions=true --preserve-smb-info=true --recursive

### What problem was encountered?
I have an Azure fileshare with 1GB quota. While the whole size of the source directory is 1.2GB（11 files）
When uploading source directory to Azure fileshare. The process ended witwithin 10s（obviously no file transferred completly）. The file transfers completed is 0. But in Azure fileshare ,some files generated. They consume capacity，but ccould not be used cause not completed.

![image](https://github.com/Azure/azure-storage-azcopy/assets/170086424/558718c3-548f-4e90-a50d-38b1a8f9f39f)
![image](https://github.com/Azure/azure-storage-azcopy/assets/170086424/9b2de5b8-a42a-4dc1-84d1-08e3bef4fef2)

In more tests, the file  transfers completed changes randomly. Still a lot of uncompleted files generated in Azure fileshare.
![image](https://github.com/Azure/azure-storage-azcopy/assets/170086424/2e5ff82a-e4b8-40dc-8fd5-c42115359ba1)
![image](https://github.com/Azure/azure-storage-azcopy/assets/170086424/4593b437-0749-4986-9a64-7c69827f6498)

First of all ,  uncompleted files need to be deleted automaticly to keep the consistency.
Secondly, when the source size is larger than fileshare quota， need to have a certain policy，no matter fullfilling the fileshare or uploading nothing，rather than uploading some of the files randomly.

### How can we reproduce the problem in the simplest way?
Create a Azuzre fileshare，change the quota to a small number.
Upload a directory larger than fileshare with azcopy.

### Have you found a mitigation/solution?
no

**Comment by adreed-msft** [comment]
Normally, we would delete failed objects. In this case though, it seems AzCopy got back a 403... Typically, we interpret that as the literal meaning of the status code (forbidden, access denied), and exit the transfer early. In this case, this isn't the correct behavior. This is a bug. Thanks for reporting this!

**Comment by adreed-msft** [comment]
I've put this into our backlog for next release, but, no guarantees that will be in the next release.

**Comment by wonwuakpa-msft** [comment]
Hi! @v-youxie Thanks for reporting this.  Could you clarify what you mean by "uncomplete" files. Do you mean the upload not transferring all the files? Also, you can increase your standard file share quota and [cost will be based ](https://learn.microsoft.com/en-us/azure/storage/files/understanding-billing)on your actual usage.

**Comment by v-youxie** [comment]
Hi

It's long time ago.
In my memory，When the copy starts，the files will generate in the destination directory in a very short time（obviously not enough to transfer all the data，should be only an empty file）.
Then the copy process stops due to quota limit ，while the "uncompleted" or "empty" files are still there（destination directory），but not usable.
Should delete the  "uncompleted" or "empty" files cause they are not ready for use.



Best Regards,

Neal Xie


________________________________
发件人: wonwuakpa-msft ***@***.***>
发送时间: 2024年11月15日 2:59
收件人: Azure/azure-storage-azcopy ***@***.***>
抄送: Neal Xie (Shanghai Centific Technology) ***@***.***>; Mention ***@***.***>
主题: Re: [Azure/azure-storage-azcopy] Unable to delete the files not completed automaticly when fileshare is full. (Issue #2685)


Hi! @v-youxie<https://github.com/v-youxie> Thanks for reporting this. Could you clarify what you mean by "uncomplete" files. Do you mean the upload not transferring all the files? Also, you can increase your standard file share quota and cost will be based <https://learn.microsoft.com/en-us/azure/storage/files/understanding-billing> on your actual usage.

―

**Comment by wonwuakpa-msft** [comment]
A fix for this bug is in our backlog for next release. If you still have access to it, please send over your log files and name(s) of the incomplete files. @v-youxie

**Comment by wonwuakpa-msft** [comment]
Hi! checking in on this @v-youxie we would like to fully repro and diagnose the bug you encountered.

**Comment by gapra-msft** [comment]
Closing based on lack of response. 

Please increase file share quota and resume your job.
