### ISSUE TITLE
Copy looking only at certain depth

### ISSUE THREAD

**Issue by Marinell0** [Azure/azure-storage-azcopy#2687]
##### Note: The version is visible when running AzCopy without any argument
10.22.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy copy "https://saalphabotsimulationbrs.blob.core.windows.net/simulation-data/production/morning/" "/dev/shm" --recursive=true --include-pattern "results.csv" --overwrite=ifSourceNewer`

### What problem was encountered?
`results.csv` is found at the root of the first folder for each folder inside the storage. Inside that folder, we have lots of folders with thousands of files. When I call this command, it takes a minimum of 10 minutes to start running as there are a lot of useless files that it is looking at.

`results.csv` is kinda like an aggregator for every folder inside it, putting all the necessary data into one singular file for faster processing.

### How can we reproduce the problem in the simplest way?
Run a command to copy a single file in the following structure:

```
.
└── storage/
    ├── folder1/
    │   ├── thousands/
    │   ├── of/
    │   ├── folders/
    │   ├── .../
    │   └── results.csv
    ├── folder2/
    │   ├── lots/
    │   ├── more/
    │   ├── here/
    │   ├── .../
    │   └── results.csv
    └── folder3/
        ├── .../
        └── results.csv
```

See that, even though the file `results.csv` would be found at the root of the folders, azcopy has no way to know that, and keeps checking thousands of files in other folders.

### Have you found a mitigation/solution?

A depth limitator for `copy` would suffice, ignoring all the folder's files and keep the command fast (in this case, `--depth=2` or similar).

Other option would be to list all folders in a storage, ignoring files. With that, I could generate a command on the fly removing the folders from the check using `--exclude-path` and excluding every single folder (Not optimal but would work).

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
