### ISSUE TITLE
Release a new azcopy with "golang.org/x/net" of "0.23.0" to fix the vulnerability issue.

### ISSUE THREAD

**Issue by Bowen-Guo** [Azure/azure-storage-azcopy#2692]
### Which version of the AzCopy was used? 
10.24.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What problem was encountered?
We are azure machine learning prompt flow team. azcopy is installed in our docker image. Recently a vulnerability  issue was reported and needed to be fixed before June 6th. 

The vulnerability was because azcopy used package "golang.org/x/net" with version "0.20.0". To fix this vulnerability, "golang.org/x/net" has to be upgraded to "0.23.0": https://github.com/advisories/GHSA-4v7x-pqxf-cx7m

I noticed that in main branch, the package version has already been "0.23.0", could you please release a new azcopy version? So that we can use the latest version in our docker image to fix the vulnerability issue.

**Comment by adreed-msft** [comment]
AzCopy v10.25.0 has been released, based on Go 1.22.3
