### ISSUE TITLE
10.25.0 Breaks List Command

### ISSUE THREAD

**Issue by gabe-microsoft** [Azure/azure-storage-azcopy#2694]
### Which version of the AzCopy was used? 
10.25.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
`azcopy list https://mysa.blob.core.windows.net/mycontainer`
### What problem was encountered?
No output was produced, the files found were never printed to the screen.

### How can we reproduce the problem in the simplest way?
Try listing any blob container.

### Have you found a mitigation/solution?
Using `--output-type=json` files are listed, but never when `output-type=text` (default)

**Comment by gabe-microsoft** [comment]
Based on the code being changed, PR #2583 is likely the source of the bug

**Comment by sschols** [comment]
I just ran into this. Do we have a static link for 10.24.0 binaries as a workaround? I couldn't find any, and the releases here only contain the source archives.

**Comment by gapra-msft** [comment]
Hi @gabe-microsoft and @sschols 

We are aware of this issue and are working towards fixing it. Here is the PR that is still a work in progress resolving this issue. https://github.com/Azure/azure-storage-azcopy/pull/2671

**Comment by brettpostin** [comment]
We are also seeing breaking changes in 10.25.0 running the following command:

```azcopyExe jobs list --output-type json```

This results in the following error in our azure devops build pipeline:

```
unexpected fault address 0x1c3ed7929b8
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x1c3ed7929b8 pc=0x5751cb]
```

**Comment by MahmoudFathi-TomTom** [comment]
Same issue here.

**Comment by DonRhodes** [comment]
Can https://aka.ms/downloadazcopy-v10-linux  be updated to not pull this broken version?

**Comment by gapra-msft** [comment]
Please upgrade to the latest version of AzCopy 10.25.1, which fixes this regression.

**Comment by gabe-microsoft** [comment]
@gapra-msft, it seems that the formatting of the list output between 10.24.0 and 10.25.1 has changed (I'm not sure if this was intentional or not). In 10.25.1 the list output is no longer prefixed by `INFO: ` and there is now only a single space after the semicolon, while there used to be 2, see examples below.

Output from 10.24.0:
```text
INFO: mydir/myfile.txt;  Content Length: 150.58 KiB
```

Output from 10.25.1:
```text
mydir/myfile.txt; Content Length: 150.58 KiB
```

**Comment by bpodfwgit** [comment]
This is still not working it seems. 10.25.1 does not generate output for me. I had to fall back to older version to get output.
