### ISSUE TITLE
Azcopy on Mac: too many open files

### ISSUE THREAD

**Issue by pkcecw** [Azure/azure-storage-azcopy#2696]
### Have you found a mitigation/solution? No

Here is the session output:

 azcopy_darwin_amd64_10.24.0 % ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                256
 azcopy_darwin_amd64_10.24.0 % ulimit -n 65536
 azcopy_darwin_amd64_10.24.0 % ulimit -a      
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                65536

azcopy_darwin_amd64_10.24.0 % export AZCOPY_CONCURRENCY_VALUE=10
azcopy_darwin_amd64_10.24.0 % export AZCOPY_CONCURRENT_FILES=10
azcopy_darwin_amd64_10.24.0 % export AZCOPY_CONCURRENT_SCAN=20
azcopy_darwin_amd64_10.24.0 % export AZCOPY_BUFFER_GB=1

 azcopy_darwin_amd64_10.24.0 % ./azcopy cp "https://xx.blob.core.windows.net/xx/?sip=xx&spr=https&sv=2018-11-09&si=rl-download&sr=c&sig=xx" "/Users/xx/Desktop/xx/" --overwrite=ifSourceNewer --recursive=true
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job f7df6df7-f6e8-f94e-5a40-1a884ea36e3e has started
Log file is located at: /Users/ayeshahusain/.azcopy/f7df6df7-f6e8-f94e-5a40-1a884ea36e3e.log

0.1 %, 1897 Done, 0 Failed, 26330 Pending, 431773 Skipped, 460000 Total (scanning...), 2-sec Throughput (Mb/s): 29.682 panic: couldn't create job part plan file "f7df6df7-f6e8-f94e-5a40-1a884ea36e3e--00047.steV18": open /Users/ayeshahusain/.azcopy/plans/f7df6df7-f6e8-f94e-5a40-1a884ea36e3e--00047.steV18: too many open files

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.JobPartPlanFileName.Create({_, _}, {0x0, {0xf7df6df7, 0xf6e8, 0xf94e, {0x5a, 0x40, 0x1a, 0x88, ...}}, ...})
	/Users/runner/work/1/s/ste/JobPartPlanFileName.go:144 +0x1b74
github.com/Azure/azure-storage-azcopy/v10/jobsAdmin.ExecuteNewCopyJobPartOrder({0x0, {0xf7df6df7, 0xf6e8, 0xf94e, {0x5a, 0x40, 0x1a, 0x88, 0x4e, 0xa3, ...}}, ...})
	/Users/runner/work/1/s/jobsAdmin/init.go:165 +0x98
github.com/Azure/azure-storage-azcopy/v10/cmd.inprocSend({0x100cbb7cc, 0x10}, {0x100a75640?, 0xc0001b2a80?}, {0x100a75680?, 0xc0090add88?})
	/Users/runner/work/1/s/cmd/rpc.go:39 +0x138
github.com/Azure/azure-storage-azcopy/v10/cmd.glob..func6({0x100cbb7cc?, 0x0?}, {0x100a75640?, 0xc0001b2a80?}, {0x100a75680?, 0xc0090add88?})
	/Users/runner/work/1/s/cmd/rpc.go:31 +0x32
github.com/Azure/azure-storage-azcopy/v10/cmd.addTransfer(_, {{0xc010708ee0, 0x65}, {0xc010709110, 0x70}, 0x0, {0x0, 0xedd29aab0, 0xc0064e3570}, 0x1702, ...}, ...)
	/Users/runner/work/1/s/cmd/copyEnumeratorHelper.go:24 +0xb2
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CookedCopyCmdArgs).initEnumerator.func5({{0xc013e36b2d, 0x32}, 0x0, {0x0, 0xedd29aab0, 0xc0064e3570}, {0x0, 0x0, 0x0}, 0x1702, ...})
	/Users/runner/work/1/s/cmd/copyEnumeratorInit.go:321 +0x5a7
github.com/Azure/azure-storage-azcopy/v10/cmd.processIfPassedFilters({_, _, _}, {{0xc013e36b2d, 0x32}, 0x0, {0x0, 0xedd29aab0, 0xc0064e3570}, {0x0, ...}, ...}, ...)
	/Users/runner/work/1/s/cmd/zc_enumerator.go:839 +0x9f
github.com/Azure/azure-storage-azcopy/v10/cmd.(*blobTraverser).parallelList(0xc000133dc0, 0xc00007ff20, {0xc00009d02f, 0x36}, {0xc00009d066, 0xb}, {0x0, 0x0}, 0x0, 0xc00012cc60, ...)
	/Users/runner/work/1/s/cmd/zc_traverser_blob.go:437 +0x379
github.com/Azure/azure-storage-azcopy/v10/cmd.(*blobTraverser).Traverse(0xc000133dc0, 0x0?, 0x0?, {0x10158d4d8, 0x0, 0x0})
	/Users/runner/work/1/s/cmd/zc_traverser_blob.go:308 +0xaa8
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CopyEnumerator).enumerate(0xc0003d3d00)
	/Users/runner/work/1/s/cmd/zc_enumerator.go:787 +0x42
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CookedCopyCmdArgs).processCopyJobPartOrders(0xc000091680)
	/Users/runner/work/1/s/cmd/copy.go:1618 +0xe8c
github.com/Azure/azure-storage-azcopy/v10/cmd.(*CookedCopyCmdArgs).process(0xc0001162d0?)
	/Users/runner/work/1/s/cmd/copy.go:1273 +0x65
github.com/Azure/azure-storage-azcopy/v10/cmd.init.2.func2(0xc00037f900?, {0xc0003d3680?, 0x2?, 0x4?})
	/Users/runner/work/1/s/cmd/copy.go:2023 +0x1f4
github.com/spf13/cobra.(*Command).execute(0xc00037f900, {0xc0003d3640, 0x4, 0x4})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x10154db60)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc0001bcbe0?, 0xc0001920e0?}, {0xc0001be8a0?, 0x100cf8501?}, 0x74?, {0xf7df6df7, 0xf6e8, 0xf94e, {0x5a, 0x40, ...}})
	/Users/runner/work/1/s/cmd/root.go:220 +0x106
main.main()
	/Users/runner/work/1/s/main.go:84 +0x507
 azcopy_darwin_amd64_10.24.0 %

**Comment by gapra-msft** [comment]
Could you try increasing the number of file descriptors and trying the command again? Please try setting the hard limit of file-descriptors to 65535 and give it a try again.

**Comment by pkcecw** [comment]
@Thanks gapra-msft! Yes, I have tried that and ran the azcopy copy session and it didn't help.

azcopy_darwin_amd64_10.24.0 % ulimit -n 65536
azcopy_darwin_amd64_10.24.0 % ulimit -a
-t: cpu time (seconds) unlimited
-f: file size (blocks) unlimited
-d: data seg size (kbytes) unlimited
-s: stack size (kbytes) 8192
-c: core file size (blocks) 0
-v: address space (kbytes) unlimited
-l: locked-in-memory size (kbytes) unlimited
-u: processes 2784
-n: file descriptors 65536

**Comment by gapra-msft** [comment]
@pkcecw Could you share the AzCopy log file?

**Comment by gapra-msft** [comment]
Closing as there hasnt been any activity on this thread. Please reopen if you are still experiencing issues.
