### ISSUE TITLE
azcopy login status shows "INFO: You are currently not logged in. Please login using 'azcopy login'" after login with AzCLI login-type

### ISSUE THREAD

**Issue by anglicare** [Azure/azure-storage-azcopy#2697]
### Which version of the AzCopy was used? 
10.25.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
1. AzCli login with service principal + certificate 
``az login --service-principal -u {my_sp_appid} -p {sp_certificate} --use-cert-sn-issuer --tenant {my_tenant_id}``

2. Run azcopy login and returns succeeded
``azcopy login --tenant-id {my_tenant_id} --login-type AzCLI``
INFO: Login with AzCliCreds succeeded

3. Check login status, but shows not logged in
``azcopy login status``
INFO: You are currently not logged in. Please login using 'azcopy login'

4. Run copy between two storage accounts, where the service principal has access to.
``azcopy copy https://{source}.blob.core.windows.net/{container} https://{dest}.blob.core.windows.net/{path} --recursive=true --overwrite=ifSourceNewer``
INFO: Scanning...
INFO: Autologin not specified.
INFO: Authenticating to destination using Azure AD

failed to perform copy command due to error: get cached token failed, failed to unmarshal token during loading token, json: cannot unmarshal string into Go struct field OAuthTokenInfo._token_refresh_source of type common.AutoLoginType

5. Manual fix Autologin not specified issue.
``set AZCOPY_CRED_TYPE=OAuthToken``
``azcopy copy https://{source}.blob.core.windows.net/{container} https://{dest}.blob.core.windows.net/{path} --recursive=true --overwrite=ifSourceNewer``
INFO: Scanning...
INFO: Authenticating to destination using Azure AD

failed to perform copy command due to error: get cached token failed, failed to unmarshal token during loading token, json: cannot unmarshal string into Go struct field OAuthTokenInfo._token_refresh_source of type common.AutoLoginType

### What problem was encountered?
Failed to copy even after azcopy login shows succeed

### How can we reproduce the problem in the simplest way?
Run above commands. 

### Have you found a mitigation/solution?
No. Note, my service principal is using subject name + issuer based certificate authentication due to organization policy, thus I'm not able to use "azcopy login" with SPN + certificate because it only supports thumbprint based certificate auth.

**Comment by gapra-msft** [comment]
Hi, please follow the instructions here to authorize with Azure CLI via autologin 
https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#authorize-with-azure-cli
