### ISSUE TITLE
Number of pending file transfers is greater than total number of files

### ISSUE THREAD

**Issue by gil-cunha-diconium** [Azure/azure-storage-azcopy#2701]
### Which version of the AzCopy was used? 
azcopy version 10.24.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1061-azure x86_64)

### What command did you run?
azcopy copy "https://source-storage-account.blob.core.windows.net/operational-container" "https://target-storage-account.dfs.core.windows.net/landing-container" --recursive

### What problem was encountered?
AzCopy progress logs show percentage over 100% and **pending** nb of files greater than **total**.

![image](https://github.com/Azure/azure-storage-azcopy/assets/159032069/57722ecd-8990-427c-99ef-83723bddc793)

### How can we reproduce the problem in the simplest way?
Source storage account has about 35569 files and 42.35 TB in total size.

While azcopy executes we monitor its output/logs and we should be able to get accurate information. Why does this happen?

**Comment by vibhansa-msft** [comment]
Can you upgrade to latest version i.e. 10.25 and revalidate.

**Comment by gil-cunha-diconium** [comment]
We will do some testing with the newest version and will let you know if the issue reoccurs by the end of this week.
Thank you!
