### ISSUE TITLE
`azcopy list` version `10.25.0` with the default output `text` does not output resources 

### ISSUE THREAD

**Issue by akorp** [Azure/azure-storage-azcopy#2709]
### Which version of the AzCopy was used? 
10.25.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac, Linux
### What command did you run?
`azcopy list`
### What problem was encountered?
```
> azcopy -v
azcopy version 10.25.0
> azcopy list "https://myblob.blob.core.windows.net/mycontainer?sas_token"
>
```

```
❯ azcopy list "https://myblob.blob.core.windows.net/mycontainer?sas_token" --output-type json
{"TimeStamp":"2024-06-08T15:49:55.310901+02:00","MessageType":"ListObject","MessageContent":"{\"Path\":\"myblobfile\",\"ContentLength\":\"4.20 KiB\"}","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
{"TimeStamp":"2024-06-08T15:49:55.31102+02:00","MessageType":"EndOfJob","MessageContent":"","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}
```
### How can we reproduce the problem in the simplest way?
Install version `10.25.0` and run `azcopy list https://container_url`
### Have you found a mitigation/solution?
Version `azcopy list` version `10.24.0 does output correctly.

**Comment by akorp** [comment]
Hi @siminsavani-msft,
See you are working now on `newe2e supportability for testing for azcopy list output-type=text`. Maybe you could have a quick look into this issue since it might be related. If not related, apologies for tagging you 🙏

**Comment by jb4415** [comment]
Can the version available from https://aka.ms/downloadazcopy-v10-linux be reverted to a functional version immediately until this is resolved?

**Comment by aujasm1** [comment]
Hi, I'm seeing similar issue during idempotent automated processes which download latest azcopy and use it.  Shouldn't a basic problem like this fail some sort of automated release testing?  Is there any way for us to download another version that is not broken?

**Comment by vibhansa-msft** [comment]
We are working towards fixing this problem, Meanwhile you can revert back to 10.24 image using below link:
https://azcopyvnextrelease.blob.core.windows.net/releases/release-10.24.0-20240326/azcopy_linux_amd64_10.24.0.tar.gz
