### ISSUE TITLE
azcopy list --output-type="text" not showing anything

### ISSUE THREAD

**Issue by rtrevino89** [Azure/azure-storage-azcopy#2717]
##### Note: The version is visible when running AzCopy without any argument
10.25.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy list --outout-type="text"

### What problem was encountered?
When using type="text" no output is shown to console. However, if I use --output-type="json" I see information. Is there any other flag I need to set?
I also tried with cloud shell and see the same issue as in Desktop using 10.25.0

![image](https://github.com/Azure/azure-storage-azcopy/assets/99822668/0b05662c-88ac-4907-8ba0-bbe3340111c0)

### How can we reproduce the problem in the simplest way?

1. Create a blob container.
2. Upload any file
3. run azcopy list --output-type="text" <path_to_container> or  azcopy list <path_to_container>

### Have you found a mitigation/solution?
Using --output-type="json"

**Comment by gapra-msft** [comment]
Please upgrade to the latest version of AzCopy 10.25.1, which fixes this regression.
