### ISSUE TITLE
piping issue is still there in 10.0.8 version, while copying from AzStorage to local machine it gets struck for 7-8 min for 1 gb of data showing Scanning..... message

### ISSUE THREAD

**Issue by yegneshch** [Azure/azure-storage-azcopy#272]

**Comment by zezha-msft** [comment]
Hi @yegneshch, please double check that you are indeed using 10.0.8, and not an earlier version. That issue was already fixed, and I just verified on MacOS and Windows. 

In the latest version, AzCopy never outputs anything when it's piping.

**Comment by yegneshch** [comment]
hi Zezha can you let me know why the scanning message is showing and it will be showing for atleast for 6 to 7 min for 1GB of data.

**Comment by zezha-msft** [comment]
Hi @yegneshch, that message should never be shown for the piping scenario. 

Could you please provide the exact command that you ran and the output? (please scrub away the SAS signature to protect your credential)
