### ISSUE TITLE
Azcopy never completes 100% sync - Always Pending.  Says Total number of Files Transfered until the end then I get Final Job Status Failed.

### ISSUE THREAD

**Issue by LastChance1963** [Azure/azure-storage-azcopy#2723]

**Comment by LastChance1963** [comment]
Sorry we tested this off of another network that wasn't behind proxies and it worked fine. It is the network that has proxies that it is failing.  It seems like communication is setup with Azure using SAS .

**Comment by vibhansa-msft** [comment]
Closing this as it's more of a setup issue. Feel free to reopen if the issue persists, even after network setup correction.

**Comment by LastChance1963** [comment]
This isn't a network issue.  If you read my post SAS and the information's getting to the Azure Blob.  After 30-60 minutes it fails

**Comment by LastChance1963** [comment]
How do I reopen?
