### ISSUE TITLE
Security issues in @azure-tools/azcopy-node 3.2.0

### ISSUE THREAD

**Issue by dlange-hp** [Azure/azure-storage-azcopy#2725]
### Which version of the AzCopy was used? 
10.23.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
npm start

### What problem was encountered?
There are security vulnerabilities in AzCopy 10.23.0.  See https://msrc.microsoft.com/report/vulnerability/VULN-125618
The latest version of @azure-tools/azcopy-node (version 3.2.0) uses AzCopy 10.23.0.  See https://www.npmjs.com/package/@azure-tools/azcopy-node

### How can we reproduce the problem in the simplest way?
Use @azure-tools/azcopy-node 3.2.0 in a node program.  See that it depends on AzCopy 10.23.0.

### Have you found a mitigation/solution?
Please publish a version of @azure-tools/azcopy-node that uses AzCopy 10.25.1.

**Comment by vibhansa-msft** [comment]
AzCopy 10.25.1 release is already out. Kindly upgrade and see if the issue persists or not.

**Comment by dlange-hp** [comment]
The problem is with @azure-tools/azcopy-node.  The latest version of @azure-tools/azcopy-node does NOT use AzCopy 10.25.1.
See: https://www.npmjs.com/package/@azure-tools/azcopy-node
Is this not the correct place to report issues with @azure-tools/azcopy-node?  The repository and homepage links both point here.

**Comment by gapra-msft** [comment]
@MRayermannMSFT Could someone on your team update the package if all is good with v10.25.1?

**Comment by MRayermannMSFT** [comment]
@gapra-msft we'll handle this after lunch.

**Comment by MRayermannMSFT** [comment]
We have now published azcopy-node 3.4.1 which depends on AzCopy v10.25.1.

**Comment by gapra-msft** [comment]
Closing this issue as this should be resolved now.
