### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by stephc-msft** [Azure/azure-storage-azcopy#273]
Strongly suggest the first line of the readme and first item in the wiki is a simple description of the tool.
PRESUMABLY it copies to/from a local system to an Azure storage account  (using current or specified  subscription credentials ), but in order to find out I have to dig a lot deeper   (I was given a link with "try using this tool")

**Comment by zezha-msft** [comment]
Thanks for the suggestion @stephc-msft!

@seguler

**Comment by seguler** [comment]
Does it not say that already ?

AzCopy (v10 Preview) is the next-generation command-line utility designed for copying data to/from Microsoft Azure Blob and File, using simple commands designed for optimal performance. You can copy data between a file system and a storage account, or between storage accounts.

**Comment by zezha-msft** [comment]
@seguler the [wiki front page](https://github.com/Azure/azure-storage-azcopy/wiki) is empty.

**Comment by zezha-msft** [comment]
Fixed here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10
