### ISSUE TITLE
0.0% while uploading larger files

### ISSUE THREAD

**Issue by VanGone1337** [Azure/azure-storage-azcopy#2733]
### Which version of the AzCopy was used?
10.25.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
./azcopy.exe copy "P:\Outlook-Export\buchhaltung\buchhaltung.pst" "SASKey" --overwrite=true --from-to=LocalBlob --blob-type Detect --follow-symlinks --check-length=false --put-md5 --follow-symlinks --block-size-mb=256 --disable-auto-decoding=false --recursive --log-level=DEBUG;

### What problem was encountered?
Upload stays at 0.0%. We dont have the best internet connection (10Mbit/s). When I upload smaller files, like 300mb it works with Azure Storage Exploerer. But with bigger files >1GB it is just running to infinity. Then I tried it with the command above. There I saw, that it is not going over 0.0%.

### How can we reproduce the problem in the simplest way?

Run the command with a file lager thant arround 1GB

**Comment by VanGone1337** [comment]
I did find this, in the logs:

2024/06/22 09:29:05 ==> REQUEST/RESPONSE (Try=1/0s, OpTime=12m49.6672224s) -- REQUEST ERROR
   PUT https://****.blob.core.windows.net/ingestiondata/buchhaltung.pst?blockid=MDAwMDA7s8zwaPZB%2F2bM7jpzvTv%2BMDAwMDAwMDAwMDAwMDAz&comp=block&se=2024-07-19T13%3A17%3A59Z&si=IngestionSasForAzCopy202406191317593225&sig=-REDACTED-&sr=c&sv=2015-04-05
   Accept: application/xml
   Content-Length: 268435456
   Content-Type: application/octet-stream
   User-Agent: AzCopy/10.25.1 azsdk-go-azblob/v1.3.1 (go1.22.4; Windows_NT)
   X-Ms-Client-Request-Id: ff8b3f82-5e8d-404d-5db3-412964bd70dd
   x-ms-version: 2023-08-03
   --------------------------------------------------------------------------------
   ERROR:
Put "https://****.blob.core.windows.net/ingestiondata/buchhaltung.pst?blockid=MDAwMDA7s8zwaPZB%2F2bM7jpzvTv%2BMDAwMDAwMDAwMDAwMDAz&comp=block&se=2024-07-19T13%3A17%3A59Z&si=IngestionSasForAzCopy202406191317593225&sig=-REDACTED-&sr=c&sv=2015-04-05": write tcp 192.168.2.64:31585->20.60.23.161:443: wsasend: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
goroutine 100 [running]:

**Comment by ashruti-msft** [comment]
It looks your current bandwidth is not able to handle requests sent by azcopy at a time for larger files. You can try setting low concurrency values manually by changing the env variables AZCOPY_CONCURRENCY_VALUE(default:300), AZCOPY_CONCURRENT_FILES(default:64), AZCOPY_CONCURRENT_SCAN(default:16). You can verify these values in the log file generated.

**Comment by VanGone1337** [comment]
--block-size-mb=100 and AZCOPY_CONCURRENCY_VALUE="8" -> Made it
