### ISSUE TITLE
Requesting latest version of azcopy to be uploaded to MSFT packages portal.

### ISSUE THREAD

**Issue by tariq1890** [Azure/azure-storage-azcopy#274]
Can we have the latest version uploaded here ?

https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod/pool/main/a/azcopy/

**Comment by zezha-msft** [comment]
Hi @tariq1890, thanks for the suggestion!

We'll deploy to package managers once the tool GAs.

**Comment by tariq1890** [comment]
Where can we download azcopy then? We use it in our docker images.

**Comment by zezha-msft** [comment]
It's right [here](https://github.com/Azure/azure-storage-azcopy#installation).
