### ISSUE TITLE
AzCopy not working on Azure Cloud Shell

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-storage-azcopy#2748]
##### Note: The version is visible when running AzCopy without any argument
Trying to use **10.25.1** but unable to run only `AzCopy` without any argument.

### Which platform are you using? (ex: Windows, Mac, Linux)
Azure Cloud shell.

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`AzCopy` or `./azcopy.exe` in Cloud Shell.

### What problem was encountered?
```
ResourceUnavailable: Program 'azcopy.exe' failed to run: An error occurred trying to start process '/home/ajay/azcopy_windows_amd64_10.25.1/azcopy.exe' with working directory '/home/ajay/azcopy_windows_amd64_10.25.1'. No such file or directoryAt line:1 char:1
+ ./azcopy.exe
+ ~~~~~~~~~~~~.
```

### How can we reproduce the problem in the simplest way?
1. Try to run `azcopy` on Cloud shell, it'll return following error. This was working 8-10 days ago.
```
azcopy: The term 'azcopy' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
2. Download azcopy zip file -> extract it -> set directory path to same and run `./azcopy.exe`, it'll return above error in cloud shell.

### Have you found a mitigation/solution?
No.

**Comment by souravgupta-msft** [comment]
Hi @AjKundnani. There was an issue recently in AzCopy in Cloud Shell, which has been fixed. Can you please retry.

**Comment by AjKundnani** [comment]
> Hi @AjKundnani. There was an issue recently in AzCopy in Cloud Shell, which has been fixed. Can you please retry.

I've asked customer to validate. Will keep this thread posted. Thanks.

**Comment by AjKundnani** [comment]
@souravgupta-msft - This is resolved now, confirmed by customer.
