### ISSUE TITLE
azcopy download shuffles lines on windows but works on linux

### ISSUE THREAD

**Issue by dwr-psandhu** [Azure/azure-storage-azcopy#2759]
### Which version of the AzCopy was used? 
azcopy 10.25.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows vs Linux
### What command did you run?
```
azcopy copy "https://{storage_account}.blob.core.windows.net/{container}/simulations/archive_ts/elev_2021c1_omg_v1400_e2300.csv?$SAS" elev_2021c1_omg_v1400_e2300_try1.csv --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive --log-level=INFO
```
The command was originally run by storage explorer but finally the test was done with windows command line and a linux shell where the latest versions of azcopy were used

### What problem was encountered?
The windows version shuffled the lines in the .csv file even though the size is the same. Infact redownloading it twice did this in different ways. 
The linux version of azcopy produced identical files on the download.

Also notable is the the check md5 was on so why it did not fail is beyond my understanding. Perhaps it points to some other issue?

### How can we reproduce the problem in the simplest way?
I can provide the file, however it is a large csv file (> 40 MB) so perhaps it is an issue with any csv file with that size. Also the csv file was produced on linux by a post process so there might be the end of line differences 
### Have you found a mitigation/solution?
Just use the linux version, though this is a usability issue when porting over to windows

**Comment by ashruti-msft** [comment]
Hello, could you please share your csv file to try out the scenario. Also, can you check md5sum on local after downloading the file and md5sum of the original file and compare? I tried this scenario with a csv file created on linux of size 80MB and downloaded it on windows and I did not see any changes in the data. So, it would help if I could test using your csv file as well. Thanks!

**Comment by dwr-psandhu** [comment]
Sure the mdf5sums for the two tries are below
```
C:\Users\psandhu\Downloads\test_download_csv>md5sum elev_2021c1_omg_v1400_e2300_try1.csv
e4aacf36ca44e8dcff72102388928bad *elev_2021c1_omg_v1400_e2300_try1.csv

C:\Users\psandhu\Downloads\test_download_csv>md5sum elev_2021c1_omg_v1400_e2300_try2.csv
c3b97072d729ca41bb04087bbd377b37 *elev_2021c1_omg_v1400_e2300_try2.csv
```

The file is rather large so let me know if I can DM you the URL of the blob with the SAS access.

**Comment by dwr-psandhu** [comment]
Here is a screenshot with winmerge. As you can see on the left side bar, the thin yellow lines indicate that there are sparse differences. I have highlighed one of those; essentially a few rows that have been reshuffled as shown in the screen shot.

![Screenshot 2024-07-25 080854](https://github.com/user-attachments/assets/dbef65e2-fb61-4537-8405-5e368a04b9a7)

**Comment by ashruti-msft** [comment]
> The file is rather large so let me know if I can DM you the URL of the blob with the SAS access.

 Please share your csv file over mail at [ashruti@microsoft.com](mailto:ashruti@microsoft.com)

**Comment by dwr-psandhu** [comment]
@ashruti-msft I sent you the url via email, however this morning I retried and I can't reproduce the issue. I believe it is related to network traffic scanner that is being used by our organization called [Palo Alto Networks firewall product](https://live.paloaltonetworks.com/t5/pancast-episodes/pancast-episode-9-should-you-have-ssl-decryption-enabled/ta-p/526755#:~:text=It%20works%20by%20doing%20what,going%20through%20the%20encrypted%20session). It decrypts and reencrypts SSL traffic and I belive it might be interfering with azcopy on windows.

Lets close the issue for now as I can't reproduce it anymore this morning, however this might still be useful information for others
