### ISSUE TITLE
Support for Azure Files (v10 Sync, Files<->Files and Local<->Files)

### ISSUE THREAD

**Issue by stuarthomerbp** [Azure/azure-storage-azcopy#277]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.0.8-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux Agent on VSTS/Azure DevOps

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`./azcopy sync 
       "$(DevUrl)/Media$(DevSAS)" 
       "$(StagingUrl)/Media$(StagingSAS)" 
       --log-level=INFO --delete-destination=true --recursive=true`

### What problem was encountered?
We have a need to sync Azure Files repositories, which are not accessible via NFS/SMB between environments.  The older copy (v8) allows us to copy from source to destination, but only additive.  We'd like to leverage the new sync capability so they're properly in sync.

For reference, our v8 command is:
`azcopy 
--source "$(DevUrl)/Media" 
--source-sas "$(DevSAS)" 
--destination "$(StagingUrl)/Media" 
--dest-sas "$(StagingSAS)" 
--recursive --quiet --verbose --exclude-older`

Our v10 command is:
`./azcopy sync 
       "$(DevUrl)/Media$(DevSAS)" 
       "$(StagingUrl)/Media$(StagingSAS)" 
       --log-level=INFO --delete-destination=true --recursive=true`

We get the error:
`error parsing the input given by the user. Failed with error Unable to infer the source / destination`

Trying out a local source/destination suggests `filelocal` or `localfile` are not supported.  I'm also inferring `filefile` nor `blobblob` are supported either.  Can these be added to v10?

### How can we reproduce the problem in the simplest way?
1. Create two storage accounts
2. Create a File end point in each, put some files in one of them.
3. Generate SAS tokens for each
4. Try to use AZCopy to sync from one to the other

### Have you found a mitigation/solution?
Using v8 with copy.

**Comment by zezha-msft** [comment]
Hi @stuarthomerbp, thanks for reaching out!

Sync only supports local <-> blob right now, but local <-> file, blob <-> blob, and file <-> file are definitely on our roadmap. Thanks for your feedback!

**Comment by GFoley83** [comment]
Any dates or ETA on that roadmap?

**Comment by zezha-msft** [comment]
Hi @GFoley83, thanks for reaching out!

We don't have a specific date yet, but this item is very high on our list.

**Comment by dwrightpulse** [comment]
+1 on this for me...

Time frame would be good too!

**Comment by v-mitor** [comment]
+1 more.    Any ETA  ??

**Comment by JohnRusk** [comment]
No ETA to publicly announce just yet, but keep an eye on the next release or two.  Next one is due out in a few weeks.

**Comment by jmon12** [comment]
Hi,
I'm not able to list the files of an Azure file storage. (very new azcopy user sorry)
Is it also not yet supported? Should I create a separate feature request?
+1 btw.

**Comment by zezha-msft** [comment]
Hi @jmon12, sorry for the inconvenience, we don't support File for listing operations just yet. We'll be adding more support for the File service soon.

**Comment by jmon12** [comment]
Hi @zezha-msft. Thank you for your quick answer. Should I create a feature request?

**Comment by Tetradeus** [comment]
+1

**Comment by zezha-msft** [comment]
@jmon12 yes please! That'd be really helpful for our tracking purposes.

**Comment by jonathonwpowell** [comment]
This feature would be great! +1

**Comment by JohnRusk** [comment]
Sync from Azure Files to Azure Files is now supported, in version 10.3 which has just been released.

**Comment by dwrightpulse** [comment]
Not sure why this has been closed on the basis that "Sync from Azure Files to Azure Files is now supported, in version 10.3", when local <-> file was also promised, and that's what I +1'd for...

**Comment by JohnRusk** [comment]
@dwrightpulse Thanks for pointing that out. I've reopened this, and changed the title to make it clear that this issue covers both File <-> File (which is in 10.3) and Local <-> File (which is not).

**Comment by JohnRusk** [comment]
cc @rishabpoh for visibility

**Comment by DanWatters** [comment]
@JohnRusk - Not to meaning to pile on, but I'm anxious to use the Local<->File functionality too.

**Comment by JohnRusk** [comment]
@rishabpoh Can you please check to see if this is on the backlog, and review its priority?

**Comment by rishabpoh** [comment]
Thanks for the feedback everyone! I have added this feature request (Local <-> File sync capability) to our backlog.
