### ISSUE TITLE
Azcopy blob download of case sensitive files to local case sensitive fs fails on mac os.

### ISSUE THREAD

**Issue by ziggy90127** [Azure/azure-storage-azcopy#2771]
export USER_NAME=$(whoami)
export AZCOPY_ACCOUNT1="REDACTED"
export AZCOPY_CONTAINER1="tc2"
export AZCOPY_SAS1="REDACTED"
export AZCOPY_URI_DEST="https://${AZCOPY_ACCOUNT1}.blob.core.windows.net/${AZCOPY_CONTAINER1}?${AZCOPY_SAS1}"
export AZCOPY_URI_SRC="https://${AZCOPY_ACCOUNT1}.blob.core.windows.net/${AZCOPY_CONTAINER1}/*?${AZCOPY_SAS1}"

hdiutil create -size 100m -fs HFSX -volname "CaseSensitiveVolume" ~/Desktop/CaseSensitiveImage.dmg
hdiutil attach ~/Desktop/CaseSensitiveImage.dmg

mkdir /Volumes/CaseSensitiveVolume/src
touch /Volumes/CaseSensitiveVolume/src/a
touch /Volumes/CaseSensitiveVolume/src/A
mkdir /Volumes/CaseSensitiveVolume/dst

azcopy copy "/Volumes/CaseSensitiveVolume/src/*" ${AZCOPY_URI_DEST} --recursive

\# upload succeeds

azcopy copy ${AZCOPY_URI_SRC} "/Volumes/CaseSensitiveVolume/dst"--recursive

\# download fails with this message:

INFO: azcopy 10.25.1: A newer version 10.26.0 is available to download

INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 271def17-5474-eb44-59a9-c8fb70c5974a has started
Log file is located at: /Users/${USER_NAME}/.azcopy/271def17-5474-eb44-59a9-c8fb70c5974a.log

100.0 %, 1 Done, 1 Failed, 0 Pending, 0 Skipped, 2 Total, 

Job 271def17-5474-eb44-59a9-c8fb70c5974a summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 2
Number of Folder Property Transfers: 0
Number of Symlink Transfers: 0
Total Number of Transfers: 2
Number of File Transfers Completed: 1
Number of Folder Transfers Completed: 0
Number of File Transfers Failed: 1
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
Total Number of Bytes Transferred: 0
Final Job Status: CompletedWithErrors

cat /Users/${USER_NAME}/.azcopy/271def17-5474-eb44-59a9-c8fb70c5974a.log

2024/08/06 15:35:55 AzcopyVersion  10.25.1
2024/08/06 15:35:55 OS-Environment  darwin
2024/08/06 15:35:55 OS-Architecture  amd64
2024/08/06 15:35:55 Log times are in UTC. Local time is 6 Aug 2024 09:35:55
2024/08/06 15:35:55 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2024-08-06T15:35:50Z or --include-after=2024-08-06T15:35:50Z
2024/08/06 15:35:55 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2024/08/06 15:35:56 Job-Command copy https://${AZCOPY_ACCOUNT1}.blob.core.windows.net/tc2/*?se=2024-09-05t14%3A52%3A43z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28 /Volumes/CaseSensitiveVolume/dst--recursive 
2024/08/06 15:35:56 Number of CPUs: 16
2024/08/06 15:35:56 Max file buffer RAM 8.000 GB
2024/08/06 15:35:56 Max concurrent network operations: 256 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2024/08/06 15:35:56 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2024/08/06 15:35:56 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2024/08/06 15:35:56 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2024/08/06 15:35:56 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2024/08/06 15:35:56 Max open files when downloading: 48483 (auto-computed)
2024/08/06 15:35:56 Final job part has been created
2024/08/06 15:35:56 Final job part has been scheduled
2024/08/06 15:35:56 ERR: [P#0-T#1] DOWNLOADFAILED: https://${AZCOPY_ACCOUNT1}.blob.core.windows.net/tc2/a : 000 : Empty File Creation error cannot simultaneously send two files to same destination name
   Dst: /Volumes/CaseSensitiveVolume/dst--recursive/a
2024/08/06 15:35:56 INFO: [P#0-T#0] DOWNLOADSUCCESSFUL: /Volumes/CaseSensitiveVolume/dst--recursive/A
2024/08/06 15:35:56 JobID=271def17-5474-eb44-59a9-c8fb70c5974a, Part#=0, TransfersDone=2 of 2
2024/08/06 15:35:56 all parts of entire Job 271def17-5474-eb44-59a9-c8fb70c5974a successfully completed, cancelled or paused
2024/08/06 15:35:56 is part of Job which 1 total number of parts done 
2024/08/06 15:35:58 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs: 256
2024/08/06 15:35:58 100.0 %, 1 Done, 1 Failed, 0 Pending, 0 Skipped, 2 Total, 
2024/08/06 15:35:58 

Diagnostic stats:
IOPS: 0
End-to-end ms per request: 0
Network Errors: 0.00%
Server Busy: 0.00%

Job 271def17-5474-eb44-59a9-c8fb70c5974a summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 2
Number of Folder Property Transfers: 0
Number of Symlink Transfers: 0
Total Number of Transfers: 2
Number of File Transfers Completed: 1
Number of Folder Transfers Completed: 0
Number of File Transfers Failed: 1
Number of Folder Transfers Failed: 0
Number of File Transfers Skipped: 0
Number of Folder Transfers Skipped: 0
Total Number of Bytes Transferred: 0
Final Job Status: CompletedWithErrors

2024/08/06 15:35:58 Closing Log

\# The internal Azcopy machinery for issuing multiple copies is not doing it in a case sensitive fashion on mac.
\# Downloading the case sensitive files 1 at a time to the same directory succeeds.

**Comment by tanyasethi-msft** [comment]
Hi @ziggy90127 ,
The download failed because the two files have names that are duplicates in all but capitalization (src/a andsrc/A).
Mac is case insensitive, and such files will be downloaded to same destination file. 
To work around this problem, please rename your blobs so that their names differ in more than the casing.

**Comment by ziggy90127** [comment]
This line:

   hdiutil create -size 100m -fs HFSX -volname "CaseSensitiveVolume" ~/Desktop/CaseSensitiveImage.dmg

creates a case sensitive file system. This is a mac native case sensitive file system, there's no tricks here.

src/a andsrc/A exist on that file system, and are correctly uploaded to the tc3 container.  Each file a and A can be individually downloaded with Azcopy to dst with no problem with the correct case.  Azcopy, when downloading them at the same time, incorrectly assumes that the Mac can't have a case sensitive file system.  Clearly the mac does have a case sensitive file system that works.  It's only Azcopy's bad assumption that prevents this from working.  If you need to add a flag to Azcopy like "--allow_mac_case_sensitive", or some such, please do so.  As of right now, I can't use Azcopy copy on the Mac to do my work, and it's just because of a bad assumption.  You're forcing me to use a linux VM to do my work, when clearly I don't need to if Azcopy worked properly on a mac case sensitive file system.

**Comment by ziggy90127** [comment]
Here is a cobbled together program to test if a directory path is on a case sensitive file system or not:

`#include <iostream>
#include <sys/attr.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <unistd.h>
#include <cstring>
#include <sys/syslimits.h>
#include <limits.h>

void get_root_volume(const char *path, char *volume, size_t volume_size) {
    struct statfs buf;
    if (statfs(path, &buf) == 0) {
        strncpy(volume, buf.f_mntonname, volume_size - 1);
        volume[volume_size - 1] = '\0';  // Ensure null-termination
    } else {
        perror("statfs");
        exit(EXIT_FAILURE);
    }
}

bool isCaseSensitive(const char* path) {
	bool file_names_case_sensitive = false;
	char volume[PATH_MAX];

	get_root_volume(path, volume, sizeof(volume));

	/* Formulate a query for the volume capabilities.  */
	struct attrlist attrList
	= {ATTR_BIT_MAP_COUNT,
		0,				      /* reserved.  */
		0,				      /* commonattr.  */
		ATTR_VOL_INFO | ATTR_VOL_CAPABILITIES, /* volattr.  */
		0,				      /* dirattr.  */
		0,				      /* fileattr.  */
		0				      /* forkattr.  */
		};
		
	struct returnBuf {
		u_int32_t length;
		vol_capabilities_attr_t caps;
	} __attribute__ ((aligned (4), packed)) retBuf;

	if (getattrlist(volume,
						&attrList,
						&retBuf,
						sizeof (retBuf),
						0) == 0) {
		/* The call succeeded.  */
		if ((retBuf.caps.valid[VOL_CAPABILITIES_FORMAT]
				& VOL_CAP_FMT_CASE_SENSITIVE))
			/* The volume could be case-sensitive.  */
			if (retBuf.caps.capabilities[VOL_CAPABILITIES_FORMAT]
					& VOL_CAP_FMT_CASE_SENSITIVE)
				/* The volume is case-sensitive.  */
				file_names_case_sensitive = true;
	} else {
        perror("getattrlist");
        exit(EXIT_FAILURE);
	}

    return file_names_case_sensitive;
}

int main(int argc, char* argv[]) {
    if (argc != 2) {
        std::cerr << "Usage: " << argv[0] << " <path>" << std::endl;
        return 1;
    }

    const char* path = argv[1];

    if (isCaseSensitive(path)) {
        std::cout << "The file system at " << path << " is case sensitive." << std::endl;
    } else {
        std::cout << "The file system at " << path << " is not case sensitive." << std::endl;
    }

    return 0;
}
`
Compile line `g++ -o case_sensitive_check case_sensitive_check.cpp`

Example test runs:

`./case_sensitive_check /Volumes/CaseSensitiveVolume/src
The file system at /Volumes/CaseSensitiveVolume/src is case sensitive.
./case_sensitive_check /
The file system at / is not case sensitive.`

**Comment by tanyasethi-msft** [comment]
Hi @ziggy90127 , 
This is the expected behavior by design. It would be a new feature request to support the scenario you are mentioning. 
To work around this problem, please rename your blobs so that their names differ in more than the casing.

**Comment by ziggy90127** [comment]
Fact:  Azcopy mac already supports case sensitive file download, but only if files are transferred 1 at a time.  No code changes required.

I am not asking for a change in the default design.  I am asking to add a switch, to skip the case insensitive name collision check that is performed for multi file copy on mac.  Should probably take 20 lines of easy code.  

If I were asking for a design change, it would be this: A smart design change would be to check the destination case sensitivity, for which I've provided code, and do the name collision check if appropriate.  

Regarding your work around suggestion, you want me to rename over 45,000 blob files to be case insensitive, and scan and recode 2,000 C# source code files to be case insensitive?  All because you don't want to enable functionality that is already in Azcopy mac?  That's ridiculous.  The case sensitive file system on mac has existed for over 2 decades, it should be supported.

If you choose to do nothing, then you have a bug in that you allow a case sensitive file transfer to take place in a single file download.
