### ISSUE TITLE
Which permissions are required by `--overwrite=false`?

### ISSUE THREAD

**Issue by tevoinea** [Azure/azure-storage-azcopy#2776]
##### Note: The version is visible when running AzCopy without any argument
`AzcopyVersion  10.26.0`
### Which platform are you using? (ex: Windows, Mac, Linux)
`OS-Environment  windows`
`OS-Architecture  amd64`
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

`azcopy copy "<my file>" "<my sas>" --recursive=false --blob-tags=<redacted> --overwrite=false`

Here are the relevant SAS fields:
```
se=2024-08-14T16%3A56%3A03Z
&sig=-REDACTED-
&ske=2024-08-14T16%3A56%3A03Z
&skoid=-REDACTED-
&sks=b
&skt=2024-08-08T10%3A50%3A03Z
&sktid=-REDACTED-
&skv=2024-05-04
&sp=wt
&sr=c
&st=2024-08-08T10%3A50%3A03Z
&sv=2024-05-04 
```

This is using a user-delegated SAS.

### What problem was encountered?

That exact command returns:
```
RESPONSE 403: 403 This request is not authorized to perform this operation using this permission.
ERROR CODE: AuthorizationPermissionMismatch
```

However, if I remove the `--overwrite=false` option, it works.

According to the docs[^1], the default value for `overwrite` is `true`. This means there is some permission(s) which my SAS URL doesn't have, which are required by overwrite=false, and not required by overwrite=true.

I haven't been able to find any indication of what those missing permissions may be.

[^1]: https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy

**Comment by tevoinea** [comment]
The behavior I'm trying to achieve with azcopy (and work with that same SAS) is a Blob PUT with the `If-None-Match` header set to `*` as described in the docs here: https://learn.microsoft.com/en-us/rest/api/storageservices/specifying-conditional-headers-for-blob-service-operations

**Comment by tanyasethi-msft** [comment]
When you use `--overwrite=false`, AzCopy checks whether the blob exists before writing. If the blob does not exist, the operation would require the `c (Create)` permission to create a new blob. Without the `c` permission, the operation cannot create a new blob, which can result in a `403 AuthorizationPermissionMismatch error.`

**Comment by tanyasethi-msft** [comment]
With just `Write (w) and Read (t)` permissions, you cannot achieve the `If-None-Match` behavior because the creation of a new blob under the `If-None-Match: * condition` requires the Create (c) permission. Therefore, you would need to obtain a SAS token that also includes the Create (c) permission to use `If-None-Match` successfully in your azcopy operation.

**Comment by tanyasethi-msft** [comment]
Offline conversation - 
[tevoinea]: after talking with my team I think we're going to stick with the API call instead of trying to move this functionality to azcopy
