### ISSUE TITLE
Error while copying data from ADLS to ADLS in azure

### ISSUE THREAD

**Issue by leelax22** [Azure/azure-storage-azcopy#2783]
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows and Ubuntu

### What command did you run?

Using SAS Token

azcopy sync "https://lcmsto001.blob.core.windows.net/blob001?SASToken" "https://lcmsto002.blob.core.windows.net/blob002?SASToken" --delete-destination=true --preserve-permissions=true

Using Service Principal

azcopy sync "https://lcmsto001.blob.core.windows.net/blob001" "https://lcmsto002.blob.core.windows.net/blob002" --delete-destination=true --preserve-permissions=true

### What problem was encountered?

Error seems like there is no proper permission

```
INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission PATCH https://lcmsto002.dfs.core.windows.net/blob002/240222-1607.workbook
--------------------------------------------------------------------------------
RESPONSE 403: 403 This request is not authorized to perform this operation using this permission.
ERROR CODE: AuthorizationPermissionMismatch
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationPermissionMismatch",
    "message": "This request is not authorized to perform this operation using this permission.\nRequestId:71ebb4b1-f01f-0004-6168-f30660000000\nTime:2024-08-21T01:23:53.4968198Z"
  }
}
```

![image](https://github.com/user-attachments/assets/980f0697-4e1e-4c6e-9932-d7e629108d79)

I gave SAS token all permissions to the blob side, but the error message indicated that the patch permissions were insufficient.
So I created a service principal, assigned a Storage Blob Data Contributor, and ran the command through that sp, but I got the same error.

https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json

If you look at the --preserve--permission part of the following document, it says that the sync function between adslgen2 <-> adslgen2 is possible, but I wonder why not.

I was wondering if it would be solved if I updated the latest version, so it was the same even if I proceeded after the update, and this error message appeared before the update.
```
2024/08/21 00:46:18 ERR: [P#0-T#0] COPYFAILED: https://lcmsto001.blob.core.windows.net/blob001/240222-1523.workbook : 000 : Invalid Service Client. Expecting Datalake Service client. When Grabbing source ACLs. X-Ms-Request-Id: 
```

### How can we reproduce the problem in the simplest way?
If you grant acl permission to the original adslgen2 and run it through the command, you can see that it is not maintained at the destination. There is no problem with the file being copied, but acl is not maintained.

**Comment by leelax22** [comment]
As stated in the text, I performed both methods, and the corresponding error message appears. For the authority of Sas token, I checked it like the screenshot above, and for rbac, I set it to Storage Blob Data Contributor, but neither method worked.

**Comment by souravgupta-msft** [comment]
The screenshot you shared above is for creating account level SAS. For your scenario, you will have to create container level SAS. For that, go to your container and create SAS from there. Make sure that the `Permissions` flag is set.
![image](https://github.com/user-attachments/assets/9f25fca3-fe0a-402c-9c26-47cc36a3e07f)

For the SPN mode, assign `Storage Blob Data Owner` role to it as `Storage Blob Data Contributor` role is not sufficient for preserving the ACLs.

**Comment by souravgupta-msft** [comment]
Closing, please try out the above suggested option. For more queries you can post in this thread.
