### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by sticksevans** [Azure/azure-storage-azcopy#2787]
### What command did you run?

azcopy login --login-type=MSI --identity-client-id "XXX"
where XXX is the Client ID of a user assigned managed identity within the resource group that contains my Storage Account and file share. The managed identity has been assigned the Reader and Storage File Data Privileged Contributor in the Storage Account.  

I also tried adding the terms to the environment variables and using auto-login

I'm trying to automate the uploading of files from test stations running Windows and/or Linux to an Azure File Share so that I can bring into Databricks. 

### What problem was encountered?

Failed to perform login command: ManagedIdentityCredential: ManagedIdentityCredential: Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=XXX&resource=https%3A%2F%2Fstorage.azure.com": dial tcp 169.254.169.254:80: i/o timeout.

### Have you found a mitigation/solution?
Using an SAS token works, login on interactively with my own user account works.  Just not using the managed identity.

**Comment by souravgupta-msft** [comment]
Hi @sticksevans. Can you check if the Managed Identity is assigned to your VM where you are running the azcopy login command?
You can also verify login with Managed Identity using Azure CLI, https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-managed-identity

**Comment by sticksevans** [comment]
Hi, thanks for the quick response. I might be misunderstanding the Managed Identities... I'm running azcopy on a local windows machine rather than on a VM.

Per your suggestion, I've tried to login to Azure using Managed Identity in CLI - i.e. typing az login --identity --username XXX on my laptop but get the same timeout:

Failed to connect to MSI. Please make sure MSI is configured correctly and check the network connection.
Error detail: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01&client_id=XXX (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2F9A6F7D0>, 'Connection to 169.254.169.254 timed out. (connect timeout=None)'))

I'm clearly doing something wrong with how the managed identity is set up. I could just revert to using the SAS but the documentation is clearly trying to lead me to using Managed Identities as best practice so it's a little confusing!

**Comment by souravgupta-msft** [comment]
Managed Identity can't be used for authentication of locally running apps. You will have to use Azure VM and assign the identity to it.
