### ISSUE TITLE
Is it possible to skip scanning of the excluded folders?

### ISSUE THREAD

**Issue by tsvietOK** [Azure/azure-storage-azcopy#2796]
### Which version of the AzCopy was used? 
10.26.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?

```
azcopy sync ".\src\" "https://<storage_acc>.blob.core.windows.net/<container>/src/?<sas>" --delete-destination true --exclude-path "backup;import;system/caches" --compare-hash "MD5" --put-md5 --cap-mbps 200
```
### What problem was encountered?
We have ~12 million files that need to be uploaded to the storage account. But in the "src" folder there are ~20 millions files in total (this includes folders which are excluded in the azcopy command above). So, each time I want to sync folder with the storage account it takes more than 20 hours only to scan all 20 million files in the folder. Is it possible to skip the scan of the excluded folders? It would save a lot of time. 
Also, does/should parameter --cap-mbps affect scanning?
### How can we reproduce the problem in the simplest way?
1. Create a folder "test" to sync
2. Create a test file in the "test" folder
3. Create a subfolder "subtest" and a file in "subtest" folder
4. Run az copy sync on folder "test" with the excluded "subtest" folder.
5. Make sure it scanned two files instead of one. 
### Have you found a mitigation/solution?
No.

**Comment by tanyasethi-msft** [comment]
Unfortunately, as of AzCopy version 10.26.0, it is not possible to skip the scanning of excluded folders entirely. The current implementation of the azcopy sync command requires scanning all files within the source directory to determine which files need to be copied, deleted, or excluded. This means that even though you use the --exclude-path flag to exclude certain folders from the synchronization process, AzCopy still needs to scan the entire directory structure, including the excluded folders, to know which files to act upon.

This can indeed be time-consuming, especially with a large number of files like the 20 million files in your case. The exclusion happens after the scan when AzCopy determines which files should not be processed further.

Potential Workarounds:
Pre-process Exclusions: Before running the AzCopy command, you could manually or programmatically move excluded folders to another location, reducing the number of files AzCopy needs to scan.

Split the Sync: If feasible, split the synchronization process into smaller batches, perhaps by directory or file type, to make the scans more manageable.

Improve I/O Performance: If possible, improve the disk I/O performance of the source directory, which might reduce the time taken for scanning.

These are some of the options you can consider to minimize the impact of scanning on your sync operation.

Feel free to reach out if you have any more questions!
