### ISSUE TITLE
AZCopy finishes successfully, although an AuthorizationFailure and a Cancelled job status were reported.

### ISSUE THREAD

**Issue by LacazeThomas** [Azure/azure-storage-azcopy#2798]
### Which version of the AzCopy was used? 

AZCopy version 10.19.0 - 10.26.0

### Which platform are you using? (ex: Windows, Mac, Linux)

phusion/baseimage-docker:focal-1.2.0

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

We are running the following command through cronjob from kube to upload a file to an Azure storage.
I obscured the url and tokens for security reasons. (I put parameters "<?>" instead of actual details)
```bash
azcopy copy $file "<AZURE_URL>/<FOLDER_NAME>?<SAS_TOKEN>"
```
### What problem was encountered?

We are getting an authorization failure in the logs and the AZCopy Job Status of Cancelled. But the AZCopy command finishes successfully. This causes the pipeline to finish successfully, although the files were not uploaded properly to the destination folder. The expectation is that the AZCopy should finish with an error and cause the whole pipeline to report a failure, instead of silently not copy the 

files.

![Capture d’écran 2024-08-29 à 17 36 22](https://github.com/user-attachments/assets/c8c3dc83-e113-4844-8a05-90f2faf25c2e)

### How can we reproduce the problem in the simplest way?

I don't think there is a simple way to reproduce, but you need to have an Azure storage account created with a folder and a proper SAS token. Wait for the token expiration or remove write permission on it. 

### Have you found a mitigation/solution?

No

**Comment by LacazeThomas** [comment]
Hi, yes i'm talking about exit code.

Thanks for this migration, this bug has been reported few months ago. This is any plan to fix it ? 

It seems to be a really bad bug.

**Comment by tanyasethi-msft** [comment]
Appropriate PR which solves the issue is linked.
