### ISSUE TITLE
Piped input fails with content-length of 0

### ISSUE THREAD

**Issue by jvallery** [Azure/azure-storage-azcopy#28]
Attempted to pipe input and get 400 error because content-length is zero.   Is this a supported scenario?

head -c 1K < /dev/urandom | ./azcopy-v2-linux cp "https://$account/test/file1.dat$token"

![untitled](https://user-images.githubusercontent.com/3673164/44474010-dc341380-a5ee-11e8-8250-b536e3d1e404.png)

**Comment by zezha-msft** [comment]
Hi @jvallery, thanks for reaching out!

It is a bug. We changed the default block size to 0, but did not handle it properly for the piping code path. I'll fix it soon.

**Comment by zezha-msft** [comment]
Fixed [here](https://github.com/Azure/azure-storage-azcopy/commit/035db8c9e3e41cb09d3e86465dbeacb9c1ecb235).
