### ISSUE TITLE
Missing from Debian 12 apt packages

### ISSUE THREAD

**Issue by ZachMassia** [Azure/azure-storage-azcopy#2800]
Hi,

I was following to [instructions](https://learn.microsoft.com/en-ca/azure/storage/common/storage-use-azcopy-v10?tabs=apt#install-azcopy-on-linux-by-using-a-package-manager) to install azcopy via apt, and it seems that azcopy is missing from the Debain 12 packages.

Here is the output of `sudo apt install azcopy`:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package azcopy
```

---

Doing some digging, I found that azcopy exists for Debian 11 here:
- https://packages.microsoft.com/debian/11/prod/pool/main/a/azcopy/

However the same URL with a 12 results in a 404, and I can see it is indeed missing from the [list](https://packages.microsoft.com/debian/12/prod/pool/main/a/) :

![image](https://github.com/user-attachments/assets/a46a6268-14b3-4207-affd-6d97834795c6)

---

As an aside, if one follows the msodbc driver [install instruction](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=debian18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline) before those for azcopy, apt will throw errors as the same repo is now added twice, but through two non-conflicting methods.

Removing the `.list` placed by the `.deb`, and reimporting the keys fixed all errors, but wanted to mention that as it could trip up some newer users.

Thanks!

**Comment by dphulkar-msft** [comment]
Hi @ZachMassia,

Currently, we do not provide Debian 12 packages for azcopy. However, we are planning to add Debian 12 compatibility in the upcoming releases.

We appreciate your patience as we work on expanding our support. Please keep an eye on our release notes or announcements for updates on when Debian 12 packages will become available.

**Comment by ZachMassia** [comment]
Hi @dphulkar-msft,

Sounds good - I was able to make my existing Python code using the blog storage library work, so I no longer have an immediate need for `azcopy`.

I will nontheless keep an eye out for the Debian 12 release.

Thanks.

**Comment by sdebruyn** [comment]
Now this is missing an arm64 version of azcopy @ZachMassia
