### ISSUE TITLE
does azcopy V10 support windows 2008R2?

### ISSUE THREAD

**Issue by wbypai** [Azure/azure-storage-azcopy#2803]
##### Note: The version is visible when running AzCopy without any argument
amd64_10.26.0

### Which platform are you using? (ex: Windows, Mac, Linux)
windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy.exe -h

### What problem was encountered?
error
![image](https://github.com/user-attachments/assets/df8d86af-fec7-4b77-ba97-f6d047005127)

![image](https://github.com/user-attachments/assets/2e21c33a-6790-47ea-b1f9-214612f36473)

### How can we reproduce the problem in the simplest way?
run azcopy V10 on windows2008R2
### Have you found a mitigation/solution?
no

**Comment by dphulkar-msft** [comment]
Server 2008R2 was EOL 2015 and even out of extended support since 2020.  The user should not use such an old version of windows server. That's a huge security risk! 

https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2008-r2
