### ISSUE TITLE
exclude-pattern not working

### ISSUE THREAD

**Issue by devhl-labs** [Azure/azure-storage-azcopy#2806]
### Which version of the AzCopy was used? 
azcopy version 10.26.0

### Which platform are you using? (ex: Windows, Mac, Linux)
WSL

### What command did you run?
```bash
azcopy copy "https://foo.blob.core.windows.net/foo/staticfiles/bar/*" "https://bar.blob.core.windows.net/bar" `
    --exclude-pattern="*.zip;*.zip.agc;*.dir*" `
    --recursive=true `
    --overwrite=ifSourceNewer `
    --s2s-preserve-access-tier=false `
    --trusted-microsoft-suffixes '*.private.com;*.also.private.com'
```

### What problem was encountered?
A blob containing .dir was copied

### How can we reproduce the problem in the simplest way?
Create a blob like this and run the above command.

```bash
az storage blob upload -f "your file" --account-name foo -c foo-n "staticfiles/bar/some.dir/any"
```
### Have you found a mitigation/solution?
No

**Comment by devhl-labs** [comment]
Moved to exclude-regex to get this to work.

**Comment by vibhansa-msft** [comment]
Closing this as exclude-regex is working for you. Feel free to reopen or post any further queries here.
