### ISSUE TITLE
azcopy sync --dry-run errors on files with % in name (issue #2349 again?)

### ISSUE THREAD

**Issue by simplerit** [Azure/azure-storage-azcopy#2808]
This looks to be a repeat of issue #2349 which is closed.

This is a problem with the latest azcopy version 10.26.0.

Seen on these clients: Windows Server 2019, Ubuntu Linux 24.04, Azure cloud shell.

Command run (where localDirectory has a file with filename containing %):

`azcopy sync  localDirectory https://storageaccount.blob.core.windows.net/container/ --dry-run`

When this command is run, azcopy terminates with error **panic: invalid URL escape "%te"**. Note that without "--dry-run" it works properly.

To reproduce the problem:
```
mkdir tmp
echo "hello" > tmp/%test.txt
azcopy sync tmp https://storageaccount.blob.core.windows.net/container/ --dry-run
```

Without "--dry-run" it works, but we want to determine the number of files that changed before we upload to our blob storage backup. We haven't found a way to work around this using azcopy. If this can't be fixed we could possibly use rclone instead of azcopy.

**Comment by dphulkar-msft** [comment]
The fix will be available in 10.27.0 version
