### ISSUE TITLE
azcopy has no log pruning

### ISSUE THREAD

**Issue by RomanBednar** [Azure/azure-storage-azcopy#2813]
### Which version of the AzCopy was used? 
latest

### Which platform are you using? (ex: Windows, Mac, Linux)
Any

### What command did you run?
azcopy clone or snapshot

### What problem was encountered?
Azcopy stores log files and job plan files in default locations that can be overridden by user: https://github.com/Azure/azure-storage-azcopy/blob/2a8f693c6371a922287a03001333c38c5aff2009/common/environment.go#L294-L307

However I could not find any configuration related to log pruning for these locations. If azcopy does not have a limit for log size and not pruning the logs it might eventually fill up entire device.

Is there such feature or is it planned to be added in near future? There's log splitting feature already but it does not help with pruning it seems: https://github.com/Azure/azure-storage-azcopy/issues/2213

### How can we reproduce the problem in the simplest way?
Have a small or almost entirely filled device and have azcopy store logs and/or job files there, keep using azcopy until device runs out of space.

### Have you found a mitigation/solution?
Files can be removed manually.

**Comment by dphulkar-msft** [comment]
Hi @RomanBednar,
                
We don't have log pruning support in Azcopy. The user can manually delete the logs from the system if required.

**Comment by RomanBednar** [comment]
@dphulkar-msft Acknowledged, thank you for the response. Feel free to close this issue if there is no plan to add this feature currently.
