### ISSUE TITLE
azcopy download fails md5 check, tool broken for 100GB+ data

### ISSUE THREAD

**Issue by harsha-simhadri** [Azure/azure-storage-azcopy#2836]
I am trying to download large files from public blob to a local drive with azcopy version 10.26.0 on PowerShell7.
```
 azcopy copy "https://comp21storage.z5.web.core.windows.net/wiki-cohere-35M/wikipedia_base.bin" cohere/ --from-to BlobLocal
```

The download proceeds to 100% and then fails MD5 checksum test. 

```
024/10/17 07:43:28 ERR: [P#0-T#0] DOWNLOADFAILED: https://comp21storage.z5.web.core.windows.net/wiki-cohere-35M/wikipedia_base.bin : 000 : the MD5 hash of the data, as we received it, did not match the expected value, as found in the Blob/File Service. This means that either there is a data integrity error OR another tool has failed to keep the stored hash up to date. (NOTE In the specific case of downloading a Page Blob that has been used as a VM disk, the VM has probably changed the content since the hash was set. That's normal, and in that specific case you can simply disable the MD5 check. See the documentation for the check-md5 parameter.). When Checking MD5 hash. X-Ms-Request-Id: 
```

This problem is repeatable on windows cmd prompt, WSL on multiple machines and with multiple origin files on different storage accounts. For example, with this URL as well `'https://msmarco.z22.web.core.windows.net/msmarcowebsearch/vectors/SimANS/passage_vectors/vectors.bin' 

Other tools like `wget` and python downloader packages work just fine for the same blob (we have other ways of validating data integrity).

**Comment by tanyasethi-msft** [comment]
Hi @harsha-simhadri , 
Could you please get the md5 sum after you download the file from another tool and validate if it matches. This is to see if the file in storage is corrupted. 
Alternatively, you could disable the md5 check entirely if you just want to download the file. 

`azcopy copy <source> <destination> --check-md5 None`

**Comment by harsha-simhadri** [comment]
After several experiments by my team across machines, we are convinced that the tool is downloading corrupt data (its not md5 error). We manually inspected and we have other sanity checks for our data.

Specifically, it works fine upto 100GB and after that it injects some spurious data in the stream at 100GB mark. So large file download is broken.

**Comment by sphen13** [comment]
same issue here -

**Comment by dphulkar-msft** [comment]
Hello,
The issue you're encountering is likely due to the fact that you're trying to download a file from a static website endpoint, rather than directly from the Blob Storage endpoint. When you use the azcopy command with --from-to as BlobLocal, it expects a standard Blob Storage response (which includes proper block ranges), the mismatch leads to the download being treated as incomplete or corrupt, with the checksum validation failing after download.

To resolve this issue, we suggest you to use the Blob Storage endpoint instead of the static website URL.

**Comment by gapra-msft** [comment]
Closing this issue as this is not a supported use case. 

As suggested above, please use the blob endpoint (https://<account-name>.blob.core.windows.net/%24web/<your path>) instead of the static website endpoint

**Comment by harsha-simhadri** [comment]
Thanks for the suggestion. These blobs are configured for access via static website since that was Microsoft Research's policy for creating public-facing assets without requiring authentication.
Is there a way to access blobs without requiring Azure Authentication?

**Comment by gapra-msft** [comment]
Enabling public access to the associated resources would be the way to go here if you want to use Azcopy 

https://learn.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal

**Comment by harsha-simhadri** [comment]
Anonymous access has been disabled as a matter of org policy.

**Comment by gapra-msft** [comment]
Another option would be to use SAS tokens, but those have an expiration, so may not be ideal based on your scenario.
