### ISSUE TITLE
Can't upload single file to a container using SAS

### ISSUE THREAD

**Issue by alvipeo** [Azure/azure-storage-azcopy#284]
On Windows 10, both version tried - 7.3 and 8.1.

I have a SAS for container (WRITE only, but I tries READ-WRITE-LIST too). And I need to upload a single file to that container. So I use AzCopy for that:

> AzCopy /Source:./ /Dest:https://account.blob.core.windows.net/container/?sv=2018-03-28&si=write&sr=c&sig=****** /Pattern:somefile.ext /V:./AzCopy.log

And I tried another version:

> AzCopy /Source:somefile.ext /Dest:https://account.blob.core.windows.net/container/somefile.ext /DestSAS:******

but that doesn't work either.
And I tried both AzCopy versions - 7.1.3 and 8.1! What else should I try?

BTW, with Powershell it works like a charm, with the same SAS token! Windows 10 latest.

Asked on SO too - [https://stackoverflow.com/q/55291430/2896495](https://stackoverflow.com/q/55291430/2896495)

**Comment by EmmaZhu** [comment]
Hi @alvipeo,

The command line like following should work well for uploading one file with WRITE only SAS:

`AzCopy.exe /source:<filePath> /dest:https://accountname.blob.core.windows.net/containername/blobname /destsas:"?SASToken" /y`

Please be noted: 
1. There are double quote marks around the sas token
2. The sas token string should be the one starting with a question mark like: "?sv=2018-03-28&sr=b&sig=***&se=2019-03-25T16%3A00%3A00Z&sp=w"
3. /Y option to suppress the checking for destination blob's existence which would require READ permission.

Thanks
Emma

**Comment by alvipeo** [comment]
Thank you! Sorry, it was my bad as I used AzCopy in a .CMD file and I didn't know I had to escape '%'! Learned the hard way :)
