### ISSUE TITLE
azcopy copy - Huge diff between recursive folder copy with wildcard vs --list-of-files option

### ISSUE THREAD

**Issue by jrevault** [Azure/azure-storage-azcopy#2857]
Hi azcopy team,

I'm trying to copy a local folder containing 200 files (size from 500 bytes to 2M) in various subdirectories (max depth 3) to a blob storage.

When, I use **wildcard** it takes around **20 seconds to proceed** from init to end (15 seconds of execution) :
`azcopy copy "tests_files/*" "https://region1store.blob.core.windows.net/extracted/test_WC/?sv=xxxxxxx" --recursive=true`

> ...
> Elapsed Time (Minutes): 0.2501
> ...

When I use **--list-of-files** it takes around **3 minutes to proceed** from init to end (14 seconds of execution):
`azcopy copy "tests_files" "https://region1store.blob.core.windows.net/extracted/test_FP/?sv=xxxxxxx" --list-of-files=filepath.txt`

With the list-of-files, the longest waiting moment seems to be before the processing, explanation in the logs

> INFO: Discarding incorrectly formatted input message
> INFO: Scanning...
> INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

<<**WAITS HERE FOR a bit more than 2 minutes and a half**>>

> Job c877dd8f-79e5-3a46-4178-69e16c14f403 has started
> Log file is located at: /root/.azcopy/c877dd8f-79e5-3a46-4178-69e16c14f403.log
> 
> 100.0 %, 200 Done, 0 Failed, 0 Pending, 0 Skipped, 200 Total,                                
> 
> Job c877dd8f-79e5-3a46-4178-69e16c14f403 summary
> Elapsed Time (Minutes): 0.2334
> ...

The Elapsed time shows that the total execution time is roughly the same (tiny advantage for list-of-files option)

Unfortunately my business scenario would rather use the list-of-files option as I don't need to copy all files in the folder.
The filepath.txt is generated right before the azcopy command, hence it has a valid list of files that does not need to be verified.

Is there anything I could do to minimize this waiting period ?

**Comment by syeleti-msft** [comment]
Hi @jrevault, 
This the expected behavior, by design list-of-files option takes more time. This flag is hidden, and we encourage customers to not use it.

**Comment by jrevault** [comment]
Hi @syeleti-msft ,

Thank you for the info, too bad for me :)

Cheers
