### ISSUE TITLE
OAuth Token refresh procedure

### ISSUE THREAD

**Issue by rturnbull1977** [Azure/azure-storage-azcopy#287]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.0.8-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Generated OAuth token from storage.azure.com - Saved output to variable - AZCOPY_OAUTH_TOKEN_INFO

azcopy_v10 cp https://<storage_account>.blob.core.windows.net/named_container/* /tmp/named_directory --recursive

### What problem was encountered?
Cannot refresh token - have been looking for a procedure to use.  Looks like based on the code, you cannot use gnome-keyring as its "Not Implemented".  I have been looking through the code and see that maybe keyctl is available to use.

### How can we reproduce the problem in the simplest way?
Use a Centos 7 system, azcopy v10.0.8, generate OAuth token - I have been using a OAuth token on the minimum expiry of 10 minutes, run long running download or upload to Azure storage ( or at least a upload/download that last longer than OAuth token expiry time ).

Any documentation ( proper documentation ) on this process would be appreciated. I have been in contact with MS rep but documentation has not been that strong...

### Have you found a mitigation/solution?
No, we have a client that requires us to use OAuth to connect to their storage rather than using SAS token which is a violation of their security policies.

**Comment by jiacfan** [comment]
Hi, @rturnbull1977 

Setting AZCOPY_OAUTH_TOKEN_INFO is a special approach for non-interactive login used e.g. in testing, while it's not the public supported approach.

Would you try login subcommand, i.e. check `azcopy login` for how it could be used, and establish the session for copies with `azcopy login` according to your scenario(user token or MSI) using OAuth, and then run copies without SAS.

Thanks,
Jiachen

**Comment by zezha-msft** [comment]
@rturnbull1977 Please let us know if we can assist you in any other way.

**Comment by bonybabu-tomtom** [comment]
Hi, 

I am facing the same issue mentioned above. So I set the variable AZCOPY_OAUTH_TOKEN_INFO and 
the commands like 'azcopy list <storage-account>' was listing the files without azcopy login. 
But suddenly it stopped working. Now I am getting the message:


![image](https://user-images.githubusercontent.com/67628858/93602034-5861d680-f9c2-11ea-93a2-bf5e7a4c9b90.png)

I am wondering whether there is already some solution for this.
