### ISSUE TITLE
AzCopy doesn't encode characters when downloading file on Windows

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#2871]
This is reproducible in AzCopy 10.27.0. To reproduce the issue, 

- Upload a blob to a blob container named as "syslog-test/syslog/PAN/pan:traffic/2024/11/20/cvl-plsxpan01.ns.agilent.net/pan:traffic-2skS19.21.json.gz"
- On a Windows machine, use AzCopy to download this blob to a local folder.
- The download would fail with errors about incorrect parameter while renaming the file.

In the logs, it seems like AzCopy is not properly encoding the ':' character in the file name, which is an invalid character for Windows file names. One more observation is that if I upload a blob with a simpler blob name, such as "pan:traffic-2skS19.21.json.gz", AzCopy is able to download the blob and can encode the ':' character properly.

**Comment by dphulkar-msft** [comment]
Hi @JasonYeMSFT,

Thank you for sharing your results. I tried to repro the scenario and the azcopy command successfully downloaded the blob. The downloaded file was correctly renamed as pan%3Atraffic-2skS19.21.json.gz, indicating that the : character in the blob name was properly encoded.

**Command used:**
.\azcopy.exe copy "https://<storage-account-name>.blob.core.windows.net/testdata/syslog-test/syslog/PAN/pan:traffic/2024/11/20/cvl-plsxpan01.ns.agilent.net/pan:traffic-2skS19.21.json.gz?<sas-url>" "<local-folder>"

1. Could you please confirm what version of azcopy are you using?
2. Can you share the exact command you used, including any additional flags or arguments (with sensitive information like SAS tokens redacted)?

**Comment by JasonYeMSFT** [comment]
@dphulkar-msft After additional investigation, I found that our code is not encoding the destination file name, which causes the failure. While looking for a solution, I encountered another AzCopy issue which I described here https://github.com/Azure/azure-storage-azcopy/issues/2886. A comment in our code indicates that us encoding the file name would cause problems in AzCopy decompressing in the past so we were intentionally skipping it. We also have another feature which is broken at the moment because it requires us to know the final name of the downloaded blob so we can open it for the user. Could you help us find out what's the expected behavior of AzCopy's --decompress flag to help us determine where we should encode the destination file name and how we can predict final file name after the download?
