### ISSUE TITLE
Copy does not multi thread blob container creation

### ISSUE THREAD

**Issue by TylerBurnett** [Azure/azure-storage-azcopy#2872]
I am working on a use case where I need to replicate 75'000 containers that contain data from one blob storage account to another.
When trying to do this copy, the scanning itself (Which I have noticed to include pre-creating the containers on the dest) takes upwards of 70 hours. Watching the logs, I have noticed there is no threading that occurs in the scanning phase for containers which accounts for this massive slowdown.

Copying the data itself after the scan only takes 20 minutes. Are there any alternatives or settings I could try to speed this up?

**Comment by dphulkar-msft** [comment]
Hello @TylerBurnett ,

You can try using the below alternative approaches.

1. **Pre-create the Containers: ** Utilize a custom script or tool (e.g., Azure CLI) to create all 75,000 destination containers in parallel before initiating the data copy. This can help eliminate delays caused by container creation during the transfer process.

2. **Copy Containers Individually: ** Develop a script to copy data from one container at a time using AzCopy.

**Comment by TylerBurnett** [comment]
Thanks for ideas, I ended up going with a concept similar to what you've noted where I parallelized the individual container copies. That said this comes with a variety of drawbacks which are not as ideal.

Is there any chance, this could be added to the backlog for prioritisation? I know this isn't the first or last time someone will encounter this issue.

Thanks,
Tyler

**Comment by dphulkar-msft** [comment]
Could you share any challenges or drawbacks you encountered while copying individual containers? 
Your insights could be valuable for us.

**Comment by TylerBurnett** [comment]
Certainly, when copying multiple containers it was challenging for the fact of:

- I had to create a solution using PowerShell to pull down every container listed in the source account and copy it into the dest account.
- The script became exponentially harder to write and debug when you start multithreading the individual copy jobs with the tool
- After achieving this, iterating over each account is not terrible, but it becomes a bit painful to manage because it's not 1 AZ copy job, it's 75'000 individual jobs. This means that finding failures requires you to look through the 75'000 individual log files (Keep in mind that the console can only hold so much data, new jobs will eventually push older jobs out of the console)

In hindsight, it would have been much easier to create a C# script that does this copying job rather than using AZ Copy considering the drawbacks. Had I known it would be difficult to use it in this circumstance I wouldn't have used it.

**Comment by dphulkar-msft** [comment]
Hello,

Its not recommended to run multiple instances of azcopy command on same machine. If you need to perform multiple transfers, consider queuing them or scripting them to run sequentially.

**Comment by TylerBurnett** [comment]
I appreciate that, but what else could I do to copy all the containers in a reasonable amount of time? I don't have a server farm readily available for something like this.
