### ISSUE TITLE
AzCopy v10.27.1 "panic: close of nil channel" on 403 Response

### ISSUE THREAD

**Issue by pierre-mounir** [Azure/azure-storage-azcopy#2884]
panic: close of nil channel on response 403
when copying local files to azure file share where public access is disabled.

### Command and output:

& '.\azcopy.exe' copy 'C:\NewData\*' 'https://<account>.file.core.windows.net/<fileshare>/<virt_dir>?<SAS>'
\INFO: Please note: the preserve-permissions flag is set to false, thus AzCopy will not copy SMB ACLs between the source and destination. To learn more: https://aka.ms/AzCopyandAzureFiles.
INFO: Scanning...
INFO: Any empty folders will not be processed, because --recursive was not specified. For the same reason, properties defined on folders will not be processed

Job 589efb46-8928-464d-446a-24d710edf8f6 has started
Log file is located at: <user_profile>\.azcopy\589efb46-8928-464d-446a-24d710edf8f6.log

INFO: Trying 4 concurrent connections (initial starting point)
INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission PUT https://<account>.file.core.windows.net/<fileshare>/<virt_dir>/ApsTenderMapConfig.xml
--------------------------------------------------------------------------------
RESPONSE 403: 403 This request is not authorized to perform this operation.
ERROR CODE: AuthorizationFailure
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:5a6d971e-601a-0002-375b-43d50f000000
Time:2024-11-30T19:07:28.5490691Z</Message></Error>
--------------------------------------------------------------------------------

panic: close of nil channel

goroutine 142 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).reportJobPartDoneHandler(0xc0005a6008)
        D:/a/1/s/ste/mgr-JobMgr.go:718 +0x327
created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr in goroutine 1
        D:/a/1/s/ste/mgr-JobMgr.go:203 +0xc88
PS > panic: close of nil channelpanic: close of nil channelpanic: close of nil channel

**Comment by dphulkar-msft** [comment]
Hello,

This is fixed and will be available in 10.28.0 release.

**Comment by vibhansa-msft** [comment]
Changed is merged in main line, fix will be available in next release of AzCopy.

**Comment by Gyeltshen-Nima** [comment]
May I inquire for the release date of the ver 10.28.0.

**Comment by andyzhangx** [comment]
we are already using 10.28.0, but we hit similar issue, is this a different nil channel panic issue?  @vibhansa-msft 
```
INFO: Login with identity succeeded.

INFO: Authenticating to destination using Azure AD

INFO: Authenticating to source using Azure AD

INFO: Failed to create one or more destination container(s). Your transfers may still succeed if the container already exists.

INFO: Any empty folders will be processed, because source and destination both support folders



Job 31226fde-1408-4e43-6993-4dd497982afd has started

Log file is located at: /root/.azcopy/31226fde-1408-4e43-6993-4dd497982afd.log



INFO: Trying 4 concurrent connections (initial starting point)

INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission PUT https://f0044b1ae4bd84caca03d7b.file.core.windows.net/pvc-faf72443-bd4a-4aad-adb9-803da0d0327c/AFS AKS Premium Attach.xlsx

--------------------------------------------------------------------------------

RESPONSE 403: 403 This request is not authorized to perform this operation.

ERROR CODE: AuthorizationFailure

--------------------------------------------------------------------------------

﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.

RequestId:0e329fb1-901a-004b-2baf-8dd933000000

Time:2025-03-05T09:17:56.8281443Z</Message></Error>

--------------------------------------------------------------------------------



panic: close of nil channel



goroutine 212 [running]:

github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).reportJobPartDoneHandler(0xc00017c708)

	/mnt/vss/_work/1/s/ste/mgr-JobMgr.go:718 +0x327

created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr in goroutine 1

	/mnt/vss/_work/1/s/ste/mgr-JobMgr.go:203 +0xc88

```

**Comment by andyzhangx** [comment]
nvm, this issue happens on v10.27.1, just ignore this error, thanks.
