### ISSUE TITLE
AzCopy --decompress has inconsistent and unexpected behavior

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#2886]
When AzCopy uses --decompress flag to download a blob whose content encoding is gzip, it's supposed to decompress the content and remove the .gz/.zz/.gzip file extension at the destination.

Here is the description for --decompress flag from the --help output:

> Automatically decompress files when downloading, if their content-encoding indicates that they are compressed. The supported content-encoding values are 'gzip' and 'deflate'. File extensions of '.gz'/'.gzip' or '.zz' aren't necessary, but will be removed if present.

However, I've seen inconsistent behavior of AzCopy 10.27.0.

On windows, I am seeing AzCopy decompressing the file and renaming the file but the final name is unexpected. If I download a blob named "compressed.tar.gz" with the --decompress flag, the downloaded file is renamed to "compressed.gz". I expected to be renamed to "compressed.tar" instead.

On mac, I am seeing AzCopy decompressing the file but it doesn't rename the file. If I download a blob named "compressed.tar.gz" with the --decompress flag, the downloaded file is still named "compressed.tar.gz".

To reproduce the issue, you can use the following steps:

- Create a gzip compressed file and upload as a block blob to a blob container with name "compressed.tar.gz". In the blob properties, set the content-encoding to "gzip".
- Use AzCopy to download the blob with the --decompress flag
- Check what the downloaded file's name is. Also check the size of the file to see if it's properly decompressed.

**Comment by wonwuakpa-msft** [comment]
Naming the destination path (in the AzCopy command) to include the `tar.gz` extension takes precedence for the local destination file name as well. To obtain the desired end result for the `--decompress` flag, the destination should include only top-level directory.
