### ISSUE TITLE
Using AzCopy return values on Windows CMD files

### ISSUE THREAD

**Issue by alvipeo** [Azure/azure-storage-azcopy#289]
This is not a bug report, this is a suggestion which would help a lot of people I'm sure.

I use AzCopy in Windows batch files (.CMD) and when operation fails I evaluate the result with an IF statement. So when it fails I start over (IF => GOTO :startcopy). I know this latest version is going to be resilient, so maybe I don't need it anymore. But please return some reliable result values.

An example .CMD script ("AzCopy with SAS.cmd"):

```
@echo off 
SETLOCAL ENABLEEXTENSIONS
REM usage AzCopy with SAS <filename>
SET _fname=%1
SET /A retries = 0

:startover

"%ProgramFiles(x86)%\Microsoft SDKs\Azure\AzCopy\AzCopy" /Source:"./" /Dest:"https://account.blob.core.windows.net/container" /DestSAS:"?sv=2018-03-28&si=..." /Pattern:%_fname% /V:"./AzCopy with SAS.log" /Y
IF %ERRORLEVEL% NEQ 0 (
  SET /A retries = retries + 1
  IF %retries% LEQ 100 (
    ECHO Trying again %retries% ...
    ECHO
    GOTO :startover
  )
)

```
And the I can just use `"AzCopy with SAS" "file-to-upload"`. And I could sent it to customer so he could easily run it and make sure the file (a HUGE file) will be uploaded successfully.

**Comment by zezha-msft** [comment]
Thanks for sharing! @alvipeo

**Comment by pauby** [comment]
I'm not in the habit of adding to close issues, but this was closed with no indication of it being resolved, and if it was resolved what is the result?

**Comment by ianc911** [comment]
So, the question was asked (nearly a year ago!!!!!!!!) why this issue was closed with no additional info by zezha-msft, but no response was forthcoming. How about getting on the stick and posting a reply?

**Comment by zezha-msft** [comment]
Oh sorry @pauby @ianc911, I should have posted a response (not sure what happened).

In short, the old V8 was not very fault tolerant, so it sometimes it needed users to do this sort of user-side "retry". On the other hand, V10 tries to be as fault tolerant as possible, each request is retried at most 20 times. We also added throttling control and various other knobs to make sure most cases succeed. So if something really fails, chances are it's fatal, so the user should not stick the tool in a loop. 

I'm not sure whether this is a satisfactory response, please let me know your thoughts.

**Comment by ianc911** [comment]
"I'm not sure whether this is a satisfactory response" - well, in fact you really don't mention the generation of an exit code, which is in fact the subject of this post. I did find mention of it briefly and in a kind of offhand way here:[https://stackoverflow.com/questions/37746054/does-azcopy-have-an-exit-code-which-can-be-used-to-throw-error-in-a-powershell-s](url)
Wouldn't it be nice if MS could properly document it?

**Comment by zezha-msft** [comment]
@ianc911 The original issue was fixed, AzCopy follows the standard of returning 0 for success, and non-zero for failure. But I just wanted to clarify that the pattern of retrying in the script is not advised, for the reason mentioned. V10 also provides a `jobs resume` command to retry only the failed transfers.

I apologize again for not replying before closing, I should have said it's fixed.

**Comment by ianc911** [comment]
Thanks for the confirm on this . Surprising that it's not officially documented, say here:

[https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10](url)

I'll post there asking that it be added. Thanks again!
