### ISSUE TITLE
Files have been deleted locally but cannot be synchronized to destination address

### ISSUE THREAD

**Issue by sysnick** [Azure/azure-storage-azcopy#290]
### Which version of the AzCopy was used? 
10.0.8 - Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

### What command did you run?
azcopy.exe sync f:\blobtest "https://demoblobstorage01.blob.core.chinacloudapi.cn/blobtest --recursive=true
### What problem was encountered?
When delete a file from source, the delete operation is not sync to destination. the stdout is:
"2 Files Scanned at Source, 3 Files Scanned at Destination
The source and destination are already in sync."

### Have you found a mitigation/solution?
 I just test the new sync feature.

**Comment by zezha-msft** [comment]
Hi @sysnick, thanks for reaching out!

Please set `--delete-destination` to `true` or `prompt` if you'd like to remove files from the destination that are not present at the source.

The default value to the flag is false, as our assumption was that most users prefer to keep the extra data.

**Comment by sysnick** [comment]
Thanks Got it. IT's fine now.
