### ISSUE TITLE
How to setup azcopy on a build server (scripted authentication)?

### ISSUE THREAD

**Issue by zhughes3** [Azure/azure-storage-azcopy#291]
##### Note: The version is visible when running AzCopy without any argument
`azcopy version 10.0.8-Preview`

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy cp someDir/public/* https://some-static-site.blob.core.windows.net/$web --recursive=true`

### What problem was encountered?
When running from a CI server, all copy commands fail.

If I do the copy manually, and do the manual `azcopy login` , get code, open web browser, input code, etc. before running the above command ... the copy works fine.

Can you recommend any best practices for authenticating with Azure so I can successfully write to a storage blob container from a build server via a script?

**Comment by zhughes3** [comment]
Is the only way to do this similar to the (dotnet example)[https://docs.microsoft.com/en-us/azure/storage/blobs/storage-dotnet-shared-access-signature-part-2#part-1-create-a-console-application-to-generate-shared-access-signatures] which requires you to generate a SAS token from the client and appending this token to the container URI?

**Comment by zezha-msft** [comment]
Hi @zhughes3, yes, you should use SAS to authenticate. Please remember to save the token as a secured environment variable in your CI system, so that your credential is not exposed.

Btw you could also use Storage Explorer to generate the SAS. It is by far the easiest tool to use.

Please let me know if you have any other question.
