### ISSUE TITLE
Issue when copying files between containers in a storage

### ISSUE THREAD

**Issue by Jackychans** [Azure/azure-storage-azcopy#294]
### Which version of the AzCopy was used? 
AzCopy/10.0.8-Preview Azure-Storage

### Which platform are you using? (ex: Windows, Mac, Linux)

MacOSX

### What command did you run?

./azcopy cp "https://fraserprod.blob.core.windows.net/document?st=2019-03-26T10%3A27%3A03Z&se=2019-03-27T10%3A27%3A03Z&sp=rl&sv=2018-03-28&sr=c&sig=[REDACTED]" "https://fraserprod.blob.core.windows.net/test?st=2019-03-26T10%3A27%3A34Z&se=2019-03-27T10%3A27%3A34Z&sp=wl&sv=2018-03-28&sr=c&sig=[REDACTED]" --recursive=true

### What problem was encountered?

Keep receiving message transfer failed. To be detailed it's related to header invalid format. Please take a look at the log file below.

### How can we reproduce the problem in the simplest way?

Just run the command above to see if any other error since SAS url still valid in 24hours. SAS generated from Azure Explorer.
[a9c1ffb8-2601-c541-42ba-7269b2f829b4.log](https://github.com/Azure/azure-storage-azcopy/files/3007811/a9c1ffb8-2601-c541-42ba-7269b2f829b4.log)

### Have you found a mitigation/solution?
No, but I found something quite weird:
 - Transfering files between local & Azure Storage working perfectly fine.
 - Transfering files between container working perfectly fine only if Azure Storage is classic (the issue originated from Storage Type V2)

I tried hundreds of times but still not working. Please help me, thanks a lots.

**Comment by zezha-msft** [comment]
Hi @Jackychans, thanks for reaching out!

We'll investigate and update you shortly.

Please avoid exposing your SAS tokens, I've edited them away.

**Comment by jiacfan** [comment]
@Jackychans

Would you try again, this could be a service-side issue, we have reported this to service team, and this should has been mitigated.

**Comment by Jackychans** [comment]
Thanks. Just tried again and working like a charm !

**Comment by jiacfan** [comment]
Great to know this!
