### ISSUE TITLE
No error when you try to copy a blob that it is not in the container (also with a non existen container)

### ISSUE THREAD

**Issue by ToledoEM** [Azure/azure-storage-azcopy#300]
### Which version of the AzCopy was used? 
10.0.8-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac

### What command did you run?
`azcopy cp "https://account.blob.core.windows.net/container/nonexistnetfile.foo?XXXXX
`
### What problem was encountered?
When a non-existent file is tried to be copy, azcopy gives a non-specific error or no error. The same happens with a non-existent container. 

`
Scanning...
failed to perform copy command due to error: cannot start job due to error: cannot download the enitre container / virtual directory. Please use --recursive flag.
`

Also, this spelling mistake it is killing me, "enitre" in _cmd/removeBlobEnumerator.go_ and in _cmd/copyDownloadBlobEnumerator.go_

### How can we reproduce the problem in the simplest way?
Just try to copy a file that is not in the container or in a non-existent container.

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @ToledoEM, thanks for reaching out and providing feedbacks!

We'll fix the error message in the next release.

**Comment by zezha-msft** [comment]
Hi @ToledoEM, the output in `10.0.9` now looks like:
```
INFO: Scanning...
INFO: source is not validated as a single file: BlobNotFound
INFO: trying to copy the source as container/directory/list of files

failed to perform copy command due to error: cannot start job due to error: cannot download the enitre container / virtual directory. Please use --recursive flag.
```
Please let us know if you have any other concern.

**Comment by ToledoEM** [comment]
This is fantastic !
