### ISSUE TITLE
AzCopy 10.0.8 preview with DSC Resource, VirtualAlloc - out of memory error

### ISSUE THREAD

**Issue by SantoshKumar1193** [Azure/azure-storage-azcopy#309]
**Which version of the AzCopy was used?**
azcopy version 10.0.8-Preview

**Which platform are you using? (ex: Windows, Mac, Linux)**
System type: Azure VMlite
Windows Server 2016 Datacenter
RAM: 28GB
Hard Disk: 1TB (C-drive: 600GB)
Standard DS4 v2 (8 vcpus, 28 GB memory)

**What command did you run?**
With in a Custom DSC Resource, downloading a single large file (70 GB) from Blob container. 
.\azcopy.exe cp $sourcepath $destinationpath --recursive = true

 **What problem was encountered?**
On running the azcopy command, with in a custom DSC resource, after running for about 9mins, a runtime error related to VirtualAlloc (out of memory) is occurring. Error stack is as follows:

_runtime: VirtualAlloc of 8388608 bytes failed with errno=1455,
fatal error: out of memory\n,
runtime stack:
  runtime.throw(0xb58878, 0xd)
	/usr/local/go/src/runtime/panic.go:616 +0x88\nruntime.sysMap(0xc134110000, 0x800000, 0x1, 0xfe9558)
	/usr/local/go/src/runtime/mem_windows.go:122 +0x13b\n",
  runtime.(*mheap).sysAlloc(0xfcfde0, 0x800000, 0x0)
	/usr/local/go/src/runtime/malloc.go:470+0xdb
runtime.(*mheap).grow(0xfcfde0, 0x400, 0x0)
	/usr/local/go/src/runtime/mheap.go:907 +0x67
runtime.(*mheap).allocSpanLocked(0xfcfde0, 0x400, 0xfe9568, 0x5eafe48)
	/usr/local/go/src/runtime/mheap.go:820 +0x308
runtime.(*mheap).alloc_m(0xfcfde0, 0x400, 0x5ea0101, 0x43294f)
	/usr/local/go/src/runtime/mheap.go:686 +0x126
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:753+0x54
runtime.(*mheap).alloc, 0x400, 0xc042010101, 0xc042031900)
	/usr/local/go/src/runtime/mheap.go:752 +0x91
runtime.largeAlloc(0x800000, 0xc0491e0101,0x800000, 0xc0491e0101,0x80)
	/usr/local/go/src/runtime/malloc.go:826 +0x9b_
 
**How can we reproduce the problem in the simplest way?**
We are creating a simple custom DSC Resource, which downloads a file from Azure Blob container. When the file getting downloaded is less than 15GB size, azcopy is running fine (with in a DSC resource).
 Essentially, it was observed that, if the runtime of AzCopy process is exceeding 9mins duration, AzCopy is crashing with the above mentioned error.
We have also tried increasing the Pagefile size, but even then there was no luck.

**Have you found a mitigation/solution?**
So far, as a workaround, we are dividing the file of 50GB size, into 4 sub files. After which  the Azcopy is getting called and this is working fine. Could anyone please assist us in understanding a permanent fix for this issue.

_Originally posted by @SantoshKumar1193 in https://github.com/Azure/azure-storage-azcopy/issues/209#issuecomment-478965957_

**Comment by JohnRusk** [comment]
Hi Santosh, Sorry to hear this issue has affected you. It's a known issue, the fix is coded (#271) and is due for release.  The timing of the release is dependent on one or two factors beyond our control but we want it to be very soon.  Please email me directly if you have any further questions about the release date.

**Comment by SantoshKumar1193** [comment]
Thank you @JohnRusk, for the update.
Will be waiting for the new release.

**Comment by zezha-msft** [comment]
Fixed in 10.0.9.

**Comment by kssrinivasreddy** [comment]
I am getting same error in azcopy version 10.20.1

below is the error 
.\azcopy.exe : runtime: VirtualAlloc of 8388608 bytes failed with errno=1455
At C:\Temp\vtt\Copy_Azure.ps1:27 char:9
+         .\azcopy.exe copy "\\server\ Dig  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (runtime: Virtua...with errno=1455:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
fatal error: out of memory
runtime: VirtualAlloc of 
8388608 bytes failed with errno=1455
fatal error: out of memory
runtime stack:
runtime.throw
