### ISSUE TITLE
Download performance

### ISSUE THREAD

**Issue by gabe-microsoft** [Azure/azure-storage-azcopy#313]
I've done some profiling of the upload and download speeds using AzCopy 10.0.8-Preview compared to the released version of AzCopy v8, and found some surprising results (details of setup below). The upload speed using v10 was approximately 10x faster than v8. However, the download speed was about 10x SLOWER than v8. This result was reproducible 5 times in a row on a single day.

All transfers were done using the exact same files/blobs, and were done on the same computer one after another. Each test was repeated 5 times to eliminate random variations. 

### Computer running AzCopy:
Windows 10 Pro
Azure VM running in the same data center as the blob storage account I'm transferring to/from
Xenon Platinum 8168
72 vcpus
144GB RAM
Local disk: Azure Premium SSD

### Files transferred
400 files
8GB total size

### Command
All tests were run using azcopy copy <SRC_DIR> <DST_DIR> --recursive=true
For uploads <SRC_DIR> was a local directory, and <DST_DIR> was a blob prefix
For downloads <DST_DIR> was a local directory, and <SRC_DIR> was a blob prefix

**Comment by JohnRusk** [comment]
Hi Gabe,

Thanks for the test results.

There are a number of performance fixes coming in v10.0.9. Some apply specifically to downloads, and others apply specifically to relatively small total job sizes (as 8GB is, in the context of a big Azure VM reading from its local region).  

I expect that those fixes will fix the download perf issue that you see.  Would you like to re-run and post here again once v10.0.9 is available? (Should be out in a few days).

**Comment by gabe-microsoft** [comment]
Sure, I'm happy to test again with 10.0.9. Let me know when it's available.

**Comment by JohnRusk** [comment]
Its just been released. The download links now point to the new version

John

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gabe-microsoft** [comment]
I've retested using 10.0.9 and can confirm that I no longer see the performance problems that I saw using 10.0.8. Both upload and download speeds (for my test workload) are as fast for faster using 10.0.9 compared to any previous version of AzCopy that I've tested.

**Comment by zezha-msft** [comment]
Thanks for the update! @gabe-microsoft 

I'm closing this issue now. Please don't hesitate if you have any other question/concern.
