### ISSUE TITLE
cp from local to gen 2 blob store issue when space in destination path

### ISSUE THREAD

**Issue by BigDrums00** [Azure/azure-storage-azcopy#323]
##### Note: The version is visible when running AzCopy without any argument
10.0.8-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

.\azcopy.exe copy "C:\Users\BigDrums00\azcopy\*" "https://client.dfs.core.windows.net/data/RawData/3rd Party/BigDrums00/Inbound/" --overwrite=true --recursive --follow-symlinks --log-level debug --list-of-files "C:\Users\BigDrums00\azcopy\list.json"

list.json contains:
{"files":["test_upload.txt"]}

### What problem was encountered?
Destination is corrupted and becomes:
"https://client.dfs.core.windows.net/data/RawData/3rd%20Party/BigDrums00/Inbound/https://client.dfs.core.windows.net/data/RawData/3rd%20Party/BigDrums00/Inbound/test_upload.txt" and connection fails

### How can we reproduce the problem in the simplest way?
Include a space in the AD blob store path

### Have you found a mitigation/solution?
Replace space with %20 in destination uri section "3rd Party"

**Comment by zezha-msft** [comment]
Hi @BigDrums00, thanks for reaching out!

Spaces in URLs need to be escaped with %20. We can add a validation to throw a meaningful error. Thanks!

**Comment by BigDrums00** [comment]
If it means anything, In the logs it looks like it attempted to update the url with %20. The same url with a space works fine for downloads too without %20.

**Comment by zezha-msft** [comment]
Fixed in 10.1.0.
