### ISSUE TITLE
404 the specified resource does not exist

### ISSUE THREAD

**Issue by cshea15** [Azure/azure-storage-azcopy#329]
### Which version of the AzCopy was used? 
Az v10.0.9
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
.\azcopy sync "https://storageeus.blob.core.windows.net/mycontainer" "C:\test"  --recursive=true 

### What problem was encountered?
Log file is located at: C:\Users\chashea/.azcopy/56f98556-bc0c-c14f-5e39-65ef745c0348.log

0 Files Scanned at Source, 0 Files Scanned at Destination
Cannot perform sync due to error: cannot list blobs. Failed with error -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewResponseError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_response_error.go:29
===== RESPONSE ERROR (ServiceCode=ResourceNotFound) =====
Description=The specified resource does not exist.
RequestId:316787e4-f01e-00d9-77e1-ef409f000000
Time:2019-04-10T21:11:31.0804878Z, Details:
   Code: ResourceNotFound
   GET https://storageeus.blob.core.windows.net/azure-webjobs-hosts?comp=list&include=metadata&restype=container&timeout=901
   User-Agent: [AzCopy/10.0.9-Preview Azure-Storage/0.6 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [cd9b15d7-bfc7-4ab9-57a7-f743f46ffccc]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified resource does not exist.
   Content-Length: [223]
   Content-Type: [application/xml]
   Date: [Wed, 10 Apr 2019 21:11:30 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [ResourceNotFound]
   X-Ms-Request-Id: [316787e4-f01e-00d9-77e1-ef409f000000]
   X-Ms-Version: [2018-03-28]

I have not found a solution. I added the Storage Contributor to my account.

**Comment by zezha-msft** [comment]
Hi @cshea15, thanks for reaching out.

I don't see any authentication header in the error message, did you login first? You need to run `./azcopy login`.  

Please refer to `./azcopy login -h` for more info.

**Comment by cshea15** [comment]
Ah thank you for the help. I didn’t realize I needed to do that. It works now.

﻿ --
[Microsoft]

Charles J Shea
Azure Premier Field Engineer
SecInf-Pubsec PFE-ATZ-US

   Office: +1 (518) 292-2987
   Mobile: +1 (518) 257-6623
   Charles.Shea@microsoft.com<mailto:Charles.Shea@microsoft.com>
   8 AM - 5 PM EST

﻿ If you have any feedback about my work, please let either me or my manager Diana Godfrey know at Diana.Godfrey@Microsoft.com<mailto:Diana.Godfrey@Microsoft.com>

[cid:image006.png@01D4EFC8.8DC62DE0][cid:image007.png@01D4EFC8.8DC62DE0][cid:image008.png@01D4EFC8.8DC62DE0]
