### ISSUE TITLE
The azcopy elapsed time does not match the actual time (windows v8)

### ISSUE THREAD

**Issue by zhengyiqun** [Azure/azure-storage-azcopy#344]
I am using azcopy to sync data, but I found that elapsed time does not match the actual time. Why is that?

**Comment by zezha-msft** [comment]
Hi @zhengyiqun, thanks for reaching out!

There should only be a tiny difference between the two numbers, right? AzCopy starts the timer after having validated the arguments/flags.

**Comment by zhengyiqun** [comment]
Hi @zezha-msft 
I downloaded a 127G VHD file, and the completion time is about 5 minutes away from the actual time. And the bigger the file, the bigger the difference

**Comment by zezha-msft** [comment]
Closing since V8 is no longer being actively maintained. Please give V10 a try [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy), it's been GA for a bit of time now. Please don't hesitate if you encounter any issue.
