### ISSUE TITLE
Support for Azure to AWS copy

### ISSUE THREAD

**Issue by gazataeon** [Azure/azure-storage-azcopy#348]
### Version: 
amd64_10.0.9

### Which platform are you using?
 Windows 10 Pro

### What command did you run?
`.\azcopy.exe cp "https://myexample.blob.core.windows.net/test$($SAStoken)" "https://s3-eu-west-1.amazonaws.com/example/testaws/" --recursive`

### What problem was encountered?
> failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

### How can we reproduce the problem in the simplest way?
The above format should do it!

### Have you found a mitigation/solution?
Just use s3 to s3 copy and skip azure. But that's not ideal for either of us.

### Notes:
I think it's pretty obvious what I want to do here but I can also see politically speaking it's unlikely for MS to create a tool that moves data _**away**_ from their service rather than _**to**_ it, so I can see this feature not happening. 
Still, I hold out hope for this, plus if you don't ask, you don't get.

**Comment by zezha-msft** [comment]
Hi @gazataeon, thanks for reaching out!

It's a totally reasonable ask (no hard feelings 😢). I'll let our PM determine the priority of this feature.

**Comment by kspearrin** [comment]
Also interested in this feature. It would be nice for creating off-site backups to AWS

**Comment by howie** [comment]
Do you have any schedule update?

**Comment by JohnRusk** [comment]
No update at this stage.  It's not anywhere near to the top of our priority list, I'm afraid. We get asked for a lot of things, by a lot of people both inside and outside Microsoft, and so there's a lot of other things sitting above this one at the moment. 

BTW I don't know what opinion, if any, we have on the potential political issue that gazataeon mentioned above when originally logging the issue.

**Comment by howie** [comment]
Or can you point out some hint, which API we can use  to implement this feature.
Currently we work on Multiple-cloud support, we need both aws to azure and azure to aws.

**Comment by JohnRusk** [comment]
One option is to get a VM running in AWS, mount your S3 bucket as a drive on that VM, then run AzCopy there to _download_ from Azure to that mounted "drive" (that is actually your S3 bucket, but AzCopy doesn't know that).  Web search for "mount s3 bucket" for info.

There are doubtless other tools as well, from outside Microsoft, that could do this.  But you'll have to search for those yourself, I'm sorry, because I'm not familiar with them.

**Comment by gazataeon** [comment]
I do use a similar version of what John has asked for above. 
https://github.com/gazataeon/Azure2AwsSync
untested as I've had to strip out a lot of the customisation I'm using. But does the job for now.

I have it on a daily run where it picks up backups and ships them off to S3.

**Comment by RPrudden** [comment]
I see this issue is now closed. Does this mean it has been implemented?

**Comment by zezha-msft** [comment]
Hi @RPrudden, unfortunately no, we are not prioritizing this feature request for the moment.
