### ISSUE TITLE
AzCopy Proxy Issues

### ISSUE THREAD

**Issue by godlikesme** [Azure/azure-storage-azcopy#353]
I've been having issues setting the proxy info for both **AzCopy** version **8** and **10**. I've tried setting the info based on the instructions documented [here](https://github.com/Azure/azure-storage-azcopy/#configure-proxy-settings) and also tried setting them via a **AzCopy.exe.config** file as documented [here](https://www.the1bit.hu/azcopy-behind-proxy/). Neither method seems to work.

I'm not getting any errors either. Once I run **AzCopy** from the command line or invoking it from **PowerShell**, it just keeps executing forever without providing any kind of meaningful feedback other than "0 bytes transferred'.

Thoughts?

**Comment by zezha-msft** [comment]
Hi @godlikesme, thanks for reaching out!

Does your proxy require authentication by any chance? Please refer to [here](https://github.com/Azure/azure-storage-azcopy/#configure-proxy-settings) for more info.

**Comment by JohnRusk** [comment]
Is this on Windows?  The next public release is planned to have better proxy detection on Windows.

**Comment by ggsggs** [comment]
I also have the very same problem in Windows 10. I tried to make an upload using Azcopy V10 for Powershell, behind a proxy. I found similar links to those that @godlikesme found to set the proxy configuration with no success. Of course, while not connected to the corporate network the upload is working fine.

It surprises me that Azure Storage Explorer with the "AzCopy for Improved Blob Upload and Download" option enabled works fine behind the proxy, after configuring the same proxy settings(Edit -> Configure Proxy).  (Copying AzCopy command from Azure Storage Explorer does not work).

**Comment by JohnRusk** [comment]
Interesting @ggsggs. Did you, by any chance, follow instructions that tell you to do this:

`set https_proxy=<proxy IP>:<proxy port>`

Unfortunately, while that's correct in a CMD prompt, "set" in PowerShell doesn't actually set environment variables. It sets a different group of _PowerShell_ variables. (Yes, it confused me too ;-)

For PowerShell, you need to do 
`$env:https_proxy=<proxy IP>:<proxy port>`

@normesta , this sounds like something we should fix in the docs.  Do you agree? (Maybe with two sample commands for Windows. One for CMD.exe and one for PowerShell?)

Finalyl, @ggsggs, as noted earlier in this thread, proxy detection will become much more automated on Windows in the next release.

**Comment by normesta** [comment]
Awesome. Adding this to the content now. Thx!

**Comment by ggsggs** [comment]
Oh, wow. Thank you @JohnRusk! 
Your solution worked, (with the quotation marks, perhaps it's self-explanatory for powershell users but it took me three fast tries): `$env:https_proxy="<proxy IP>:<proxy port>"`

I actually didn't even find the `set https_proxy=<proxy IP>:<proxy port>` suggestion. It kind of makes me ashamed of my research. I can now see it can be found in [Configure, optimize, and troubleshoot AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure). :)

Before, I found suggestions regarding creating a **AzCopy.exe.config** file and adding some specific network configuration lines (this does work for me in App.Config if I use the Azure SDK for C#), same ones as @godlikesme linked in his post.

Thanks guys!

**Comment by normesta** [comment]
@ggsggs - You didn't miss a thing. That entry didn't appear in the "Configure, optimize, and troubleshoot AzCopy" topic until this morning. I added that entry in response to @JohnRusk 's suggestion - so I'll give a bit thx to @JohnRusk as well!

**Comment by ggsggs** [comment]
@normesta - I see!! I feel better now. 

Thank you too for your fast replies and updating so promptly the docs :)

**Comment by JohnRusk** [comment]
Version 10.2.1 is now released with automatic proxy detection on Windows.
