### ISSUE TITLE
Sync: support symbolic links

### ISSUE THREAD

**Issue by jamiems** [Azure/azure-storage-azcopy#357]
### Which version of the AzCopy was used? 
10.1.0, 10.0.8, 10.0.7 (crashes with index out of range)

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy sync c:\app\store https://stgacct.blob.core.windows.net/store

### What problem was encountered?
Do not recursively enumerate items under junction point

### How can we reproduce the problem in the simplest way?
Create a NTFS junction to a local folder hierarchy, ex mklink /J c:\app\store c:\mounts\nvme.1\store

Attempt to sync local folder hierarchy using junction point

### Have you found a mitigation/solution?
Yes

**Comment by zezha-msft** [comment]
Hi @jamiems, thanks for reaching out!

We do not yet support symbolic links in the sync command. It's on our backlog, and we'll try to get to it shortly.

**Comment by nakulkar-msft** [comment]
#718
