### ISSUE TITLE
azcopy log file oddities

### ISSUE THREAD

**Issue by gatornation11** [Azure/azure-storage-azcopy#360]
version 10.1.0
azcopy sync issue. If the files are in sync no log file is created. Even though the output indicates that one is generated and a job ID is assigned. It would be nice to see a log file for a sync job had nothing to sync and have an elapsed time value. Another small thing, when I do "azcopy jobs list" it changes the date modified time for all the log files to the time I ran the command. This is very confusing when you are trying to get an idea of when a job finished. Why is it modifying the log file, seems like it should be just reading it...not to sound ungrateful, I like the tool very much.

**Comment by adreed-msft** [comment]
Hi, @gatornation11, could you please resubmit the issue in the proper format?

As I understand it, `azcopy jobs list` changing the last modified dates on all log files is currently on our backlog to investigate. Atop this, no log file from an empty transfer is intended functionality as far as I know.

**Comment by JohnRusk** [comment]
Re no-log-if-nothing-to-sync, perhaps we should change our minds about whether its intended functionality or not.  I've added a reminder on that topic to the backlog.
