### ISSUE TITLE
azcopy fails on UNC source

### ISSUE THREAD

**Issue by gatornation11** [Azure/azure-storage-azcopy#361]
### Which version of the AzCopy was used?
10.1.0

### Which platform are you using? (ex: Windows, Mac, Linux)
windows

### What problem was encountered?
When I use a UNC source path I get this error. 
140204 Files Scanned at Source, 0 Files Scanned at Destinationpanic: runtime error: invalid memory add
ress or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xa4f9fa]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/cmd.(*localTraverser).traverse.func1(0xc0463fa120, 0x10c, 0x0, 0
x0, 0xc94b00, 0xc04229b800, 0x0, 0x0)
/go/src/github.com/Azure/azure-storage-azcopy/cmd/zc_traverser_local.go:66 +0x19a
path/filepath.walk(0xc049805180, 0xdb, 0xca3e00, 0xc0497cb680, 0xc0422910c0, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:377 +0x214
path/filepath.walk(0xc049817440, 0xb4, 0xca3e00, 0xc0497ca900, 0xc0422910c0, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:381 +0x2c9
path/filepath.walk(0xc048f56e60, 0x9f, 0xca3e00, 0xc044b8a3c0, 0xc0422910c0, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:381 +0x2c9
path/filepath.walk(0xc044fb2f00, 0x98, 0xca3e00, 0xc044fb1c80, 0xc0422910c0, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:381 +0x2c9
path/filepath.walk(0xc0431d4240, 0x8b, 0xca3e00, 0xc044fb1bc0, 0xc0422910c0, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:381 +0x2c9
path/filepath.walk(0xc0431d1dd0, 0x88, 0xca3e00, 0xc044fb1b00, 0xc0422910c0, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:381 +0x2c9
path/filepath.walk(0xc042f6f6c0, 0x70, 0xca3e00, 0xc044fb19e0, 0xc0422910c0, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:381 +0x2c9
path/filepath.walk(0xc044fbc500, 0x4d, 0xca3e00, 0xc044fb1620, 0xc0422910c0, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:381 +0x2c9
path/filepath.walk(0xc042074750, 0x2c, 0xca3e00, 0xc0424ea3c0, 0xc0422910c0, 0x0, 0x40)
/usr/local/go/src/path/filepath/path.go:381 +0x2c9
path/filepath.Walk(0xc042074750, 0x2c, 0xc0422910c0, 0x42bc00, 0x0)
/usr/local/go/src/path/filepath/path.go:403 +0x10d
github.com/Azure/azure-storage-azcopy/cmd.(*localTraverser).traverse(0xc042003180, 0xc0421a6b40, 0xc04
21a6a70, 0x1, 0x1, 0xb92920, 0xc0424a03f0)
/go/src/github.com/Azure/azure-storage-azcopy/cmd/zc_traverser_local.go:59 +0x17e
github.com/Azure/azure-storage-azcopy/cmd.(*syncEnumerator).enumerate(0xc04209a5f0, 0xc04209a500, 0x0)

    /go/src/github.com/Azure/azure-storage-azcopy/cmd/zc_enumerator.go:122 +0x97
github.com/Azure/azure-storage-azcopy/cmd.(*cookedSyncCmdArgs).process(0xc0420a2480, 0xfe, 0x2c)
/go/src/github.com/Azure/azure-storage-azcopy/cmd/sync.go:459 +0x229
github.com/Azure/azure-storage-azcopy/cmd.init.14.func2(0xc0422e2f00, 0xc0421cc5d0, 0x2, 0x3)
/go/src/github.com/Azure/azure-storage-azcopy/cmd/sync.go:489 +0x141
github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra.(*Command).execute(0xc0422e2f00, 0
xc0421cc4b0, 0x3, 0x3, 0xc0422e2f00, 0xc0421cc4b0)
/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra/command.go:766 +0x
2c8
github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x10d0bc0, 0x1
00, 0x56, 0x3)
/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra/command.go:852 +0x
311
github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra.(*Command).Execute(0x10d0bc0, 0xd,
0xc0424a0090)
/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra/command.go:800 +0x
32
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc04205ecc0, 0x19, 0xc04205ecc0, 0x19)
/go/src/github.com/Azure/azure-storage-azcopy/cmd/root.go:72 +0x84
main.main()
/go/src/github.com/Azure/azure-storage-azcopy/main.go:64 +0x19e

### How can we reproduce the problem in the simplest way?
try it with more than 200k files in a unc path?
I tried multiple times, it fails around the 140k file mark every time. Not the same exact file but in the same ballpark.

### Have you found a mitigation/solution?
no, but it does work when I map the UNC path to a drive letter. However I need it to work for the UNC path so I can use task scheduler.

**Comment by zezha-msft** [comment]
Hi @gatornation11, thanks for reaching out!

I've fixed the bug [here](https://github.com/Azure/azure-storage-azcopy/commit/dd4851672bf876acdb605cc2578831261ed146c7), it's pending release. Sorry for the inconvenience.

**Comment by gatornation11** [comment]
Cool, when will it get released?

**Comment by adreed-msft** [comment]
Have patience, young padawan

**Comment by gatornation11** [comment]
Was this fixed in 10.1.1?

**Comment by JohnRusk** [comment]
Yes, it was fixed in that release. (We did that release specifically to fix that bug). Thanks for following up about the status. I'll close this issue now.

**Comment by gatornation11** [comment]
Just tired it. When the source is a mapped drive it works no issue. But when the source is a UNC path it choked on about 35 files, here is an example error message

INFO: Accessing \\abcnas1\Public\Customers_SVN_From_abcsrv03\bradelb_global_Logistics_Inc-C10122001\pr
ojects\FiscalYear\Initial Source Code From SGL\Sol80_CodeSplitToSeperateDirectories\MISC-SQL\SQLSrcipt
sRun\Run to Refresh Test DBs\Rebuild view vr 01620recon for report 0162000.sql failed with error: GetF
ileAttributesEx \\abcnas1\Public\Customers_SVN_From_abcsrv03\bradelb_global_Logistics_Inc-C10122001\pr
ojects\FiscalYear\Initial Source Code From SGL\Sol80_CodeSplitToSeperateDirectories\MISC-SQL\SQLSrcipt
sRun\Run to Refresh Test DBs\Rebuild view vr 01620recon for report 0162000.sql: The system cannot find
 the path specified.

It's probably a character path limit issue as the path has 266 characters. I tried to prepend the UNC source with \\?\UNC\ but I got this error.

Cannot perform sync due to error: illegal local path, no pattern matching allowed for sync command

Here is the end of the jobs output
205929 Files Scanned at Source, 205975 Files Scanned at Destination
The source and destination are already in sync.

**Comment by JohnRusk** [comment]
Thanks. Sounds like the UNC issue is fixed, but long paths remain as an issue. Is that correct?

We're working on long paths in our current sprint.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Eric-ITaaS** [comment]
Yes, that is correct.
________________________________

**Comment by JohnRusk** [comment]
OK. I'll close this and leave #376 open.
