### ISSUE TITLE
azcopy sync doesn't create log file when nothing to sync.

### ISSUE THREAD

**Issue by Eric-ITaaS** [Azure/azure-storage-azcopy#362]
### Which version of the AzCopy was used? 
10.1.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy sync "z:" "https://blahblah"

### What problem was encountered?
When there is nothing to sync no log file is created even though the output of the command indicates that it was created. See the attached image.
Any job should create a log file for auditing purposes.

### How can we reproduce the problem in the simplest way?
do the same command twice. first one will sync, 2nd will have nothing to sync you will see the issue.

### Have you found a mitigation/solution?
no
![image](https://user-images.githubusercontent.com/30324134/57093919-22448980-6cdd-11e9-9669-69ad10340942.png)

**Comment by JohnRusk** [comment]
Thanks @gatornation11. This issue is on our backlog, to be fixed.

**Comment by adreed-msft** [comment]
![test result](https://user-images.githubusercontent.com/49764384/65642009-11a1f200-dfa3-11e9-8f0d-0e9795f05b6e.png)
Hi there, this should be fixed this upcoming release. Thanks for opening an issue.

**Comment by JohnRusk** [comment]
Fixed in version 10.3, which has just been released.
