### ISSUE TITLE
Transfer Status /progress

### ISSUE THREAD

**Issue by anilkumar15** [Azure/azure-storage-azcopy#367]
### Which version of the AzCopy was used? 
Azcopy v10
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
Azcopy copy source destination (sas key)
### What problem was encountered?
No. running azcopy and need to show progress back to user (% upload complete)  

### How can we reproduce the problem in the simplest way?
Run Azcopy copy
### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @anilkumar15, thanks for reaching out!

Please leverage the flag `--output-type=json` to get outputs in a more parseable format.
