### ISSUE TITLE
 I want to get the current progress of any job-id by ". \ azcopy jobs show <job-id>" command

### ISSUE THREAD

**Issue by IzuruSenokuchi** [Azure/azure-storage-azcopy#371]
Which version of the AzCopy was used?
10.0.9-Preview

Note: The version is visible when running AzCopy without any argument
Which platform are you using? (ex: Windows, Mac, Linux)
Linux

What command did you run?
.\azcopy jobs show <job-id>

What problem was encountered?
I can not get the current progress status.

How can we reproduce the problem in the simplest way?
any job-id get the current progress status.

Have you found a mitigation/solution?
Simply example, include InProgress in the condition of IsJobDone() function.
However, I think there is a reason why it can not be so simple, but I would like you to solve it.

**Comment by JohnRusk** [comment]
Thanks @IzuruSenokuchi. I've logged this, to be discussed with the team.

**Comment by adreed-msft** [comment]
![image](https://user-images.githubusercontent.com/49764384/61077489-5f12b800-a3d3-11e9-8d79-fdd77e4476b8.png)

I believe this is already present, though this is just under WSL

**Comment by IzuruSenokuchi** [comment]
Wonderful!! I would like to try this one, but when was this feature implemented?

**Comment by adreed-msft** [comment]
I'm actually quite uncertain. Note I did try this under WSL and that isn't a perfect recreation of a Linux environment. 

I'd suggest jumping to 10.2.x, the latest version of AzCopy and testing this out in your environment.

**Comment by JohnRusk** [comment]
@IzuruSenokuchi  Is this working for you? Can we close the issue?

**Comment by IzuruSenokuchi** [comment]
I'm sorry. contacted me, but I haven't tried yet.
I will try it when I finish the work I'm doing now, but it will be a little later.

**Comment by IzuruSenokuchi** [comment]
After all I tried because I became interested. 
progress has been confirmed. Thanks!!
