### ISSUE TITLE
RESPONSE Status: 400 Blob API is not yet supported for hierarchical namespace accounts.

### ISSUE THREAD

**Issue by francisco-ltech** [Azure/azure-storage-azcopy#375]
##### Note: The version is visible when running AzCopy without any argument
10.0.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy cp

### What problem was encountered?
RESPONSE Status: 400 Blob API is not yet supported for hierarchical namespace accounts.

### How can we reproduce the problem in the simplest way?

1. Create ADL Gen2 HNS
2. azcopy login (login in browser window with authentication code)
3. \azcopy.exe cp "C:\bin\abc.pdf" "https://{account}.blob.core.windows.net/fs1/landing"

### Have you found a mitigation/solution?
No

**Comment by francisco-ltech** [comment]
Trying with https://{account}.dfs.core.windows.net/fs1/landing/" gets: RESPONSE Status: 400 The request URI is invalid.

**Comment by francisco-ltech** [comment]
Ignore this item, it was due to permissions in the file system.

**Comment by ExadatumGeek** [comment]
Hey @JohnRusk
I am using following azcopy command to copy zip file from Azure vm to ADLS gen 2

**step 1**: azcopy login
**step 2**: command :  
azcopy copy "<local path to zip file>" "https://<account_name>.blob.core.windows.net/<container_name>/<path to directory>"

**Output**: Job failed 
**Error** : RESPONSE Status: 400 Blob API is not yet supported for hierarchical namespace accounts.

**Comment by ExadatumGeek** [comment]
Hey @JohnRusk
I am using following azcopy command to copy zip file from Azure vm to ADLS gen 2

step 1: azcopy login
step 2: command :
azcopy copy "<local path to zip file>" "https://<account_name>.blob.core.windows.net/<container_name>/"

Output: Job failed
Error : RESPONSE Status: 400 Blob API is not yet supported for hierarchical namespace accounts.

**Comment by adreed-msft** [comment]
@ExdatumGeek, you're trying to copy to ADLSG2. The Blob API interop has not been enabled yet.

You'll need to use the DNS suffix dfs.core.windows.net.

**Comment by ExadatumGeek** [comment]
@adreed-msft 
I tried suffix dfs.core.windows.net still getting error.
**Error**: RESPONSE STATUS: 400 the request URI is invalid

**Comment by adreed-msft** [comment]
Do you have adequate RBAC roles for this storage account?

**Comment by ExadatumGeek** [comment]
@adreed-msft 
Thank you, now its working needed RBAC roles.

**Comment by anbhulerupesh** [comment]
> @adreed-msft Thank you, now its working needed RBAC roles.

Hi, What was the RBAC roles you added for the account. I am facing the same issue
