### ISSUE TITLE
UNC path longer than 260 characters

### ISSUE THREAD

**Issue by Eric-ITaaS** [Azure/azure-storage-azcopy#376]
### Which version of the AzCopy was used?
10.1.1 
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 2008 R2 server

### What command did you run?
azcopy "\\\\server\share" "https://blobinfo" --recursive=true
### What problem was encountered?
chokes on UNC paths greater than 260 characters.

### How can we reproduce the problem in the simplest way?
Try with a UNC path longer than 260 characters

### Have you found a mitigation/solution?
No. I tried to prepend "\\\\?\UNC\" to the path but got this error
Cannot perform sync due to error: illegal local path, no pattern matching allowed for sync command

**Comment by JohnRusk** [comment]
The issue is not unique to UNC paths.  We are actively working on long path support.

**Comment by Eric-ITaaS** [comment]
Okay, thanks. Any idea when this will get fixed?

**Comment by JohnRusk** [comment]
A wild guess would be that it's a few weeks away.  But don't count on that guess being accurate.  If we find that it's easier than anticipated, and that it makes sense to release it "early" rather than wait and release it with a bunch of other changes, we may release it earlier.  If we have significant difficulties in getting it working, it may take longer. Sorry about the uncertainty!

**Comment by Eric-ITaaS** [comment]
No problem, I saw that 10.1.2 was out but I couldn't find any notes as to what was fixed/changed from 10.1.1.

**Comment by JohnRusk** [comment]
Actually, it looks like the issue probably is unique to UNC paths. From my reading of the Go SDK source code, it should work fine if you just map a drive. (ie same path length, but not unc)

**Comment by Eric-ITaaS** [comment]
Yes, works fine from a mapped drive. However I need to script this to run via a scheduled task. There isn't a way to expose a mapped drive in a script when not logged in, hence the use of a UNC path.

**Comment by JohnRusk** [comment]
Oh, I see.  

BTW, I do wonder if there may be some way to expose a mapped drive to a script that is not logged in.  I've seen it done with a call to `New-PSDrive` in the script. (Probably need the `-Persist` parameter to make it work with AzCopy, and probably need to clean up/remove any old mapping to the same letter right at the very start of the script using, `Remove-PSDrive -name "..." -Force`)

I suspect it can also be done with "net use" (maybe) and I've also heard people saying they'd done it by just creating a symbolic link: https://superuser.com/a/651015/   The symbolic link option is probably easiest, if it works for you.

**Comment by JohnRusk** [comment]
Log UNC path support is coming in version 10.3

**Comment by JohnRusk** [comment]
Version 10.3 is now released, and fixes this issue.
