### ISSUE TITLE
Can't copy from s3->azure

### ISSUE THREAD

**Issue by matthewjoneill** [Azure/azure-storage-azcopy#377]
### Which version of the AzCopy was used? 
10.1.1

### Which platform are you using? (ex: Windows, Mac, Linux)
OSX

### What command did you run?
./azcopy cp --from-to "S3Blob"  [s3path] [azurepath]

### What problem was encountered?
This happens if i'm trying to copy a single file, folder, or bucket from s3 -> ADLS Gen2 

INFO: Scanning...
INFO: Using OAuth token for authentication.
INFO: AWS S3 to Azure Blob copy is currently in preview. Validate the copy operation carefully before removing your data at source.
INFO: source is not validated as a single file: The specified key does not exist.
INFO: trying to copy the source as bucket/folder/list of files
INFO: source is bucket and destination is an Azure service endpoint, bucket with name "marts" will be created in destination to store data
failed to perform copy command due to error: cannot start job due to error: fail to create container, -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=) =====
Description=failed to unmarshal response body, Details: (none)
   PUT https://thproddataanalytics.dfs.core.windows.net/th-prod-databricks?restype=container&timeout=901
   Authorization: REDACTED
   User-Agent: [AzCopy/10.1.1 Azure-Storage/0.6 (go1.10.3; darwin)]
   X-Ms-Client-Request-Id: [77ab0246-969f-43ba-42de-a992450fb424]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Value for one of the query parameters specified in the request URI is invalid.
   Content-Length: [221]
   Content-Type: [application/json;charset=utf-8]
   Date: [Sat, 11 May 2019 13:07:32 GMT]
   Server: [Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Request-Id: [6b085359-801f-0045-20fa-075c2e000000]

### How can we reproduce the problem in the simplest way?
Copy a file from s3 to a data lake gen2 storage account

**Comment by JohnRusk** [comment]
Currently, ADLS Gen 2 is not accessible via blob APIs.

>Blob storage APIs are disabled to prevent inadvertent data access issues that could arise because Blob Storage APIs aren't yet interoperable with Azure Data Lake Gen2 APIs.

from https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-known-issues

When they become interoperable, the command you are running will work. But for now, I'm sorry, it will not.

**Comment by matthewjoneill** [comment]
Bummer!  Ok, thanks for the update.
