### ISSUE TITLE
copy help message -- ADLS Gen2 support only Azure Active Directory Authentication

### ISSUE THREAD

**Issue by gutzeit1106** [Azure/azure-storage-azcopy#379]
Help Messages shows the following.

./azcopy copy --help
Copies source data to a destination location. The supported directions are:
  - local <-> Azure Blob (SAS or OAuth authentication)
  - local <-> Azure File (Share/directory SAS authentication)
  - **local <-> ADLS Gen 2 (OAuth or SharedKey authentication)**
  - Azure Blob (SAS or public) <-> Azure Blob (SAS or OAuth authentication)
  - Azure File (SAS) -> Azure Block Blob (SAS or OAuth authentication)
  - AWS S3 (Access Key) -> Azure Block Blob (SAS or OAuth authentication)

But ADLS Gens does not support SharedKey authentication only AAD Auth.  Should this message be revised?

Source  : https://github.com/Azure/azure-storage-azcopy/blob/master/cmd/helpMessages.go
Version :AzCopy V10.1.0 GA Release

**Comment by adreed-msft** [comment]
Hi, Shared Key authentication is different than SAS authentication. Furthermore, SAS authentication is in an open PR (#347).

Apologies for any confusion.

**Comment by adreed-msft** [comment]
Just to provide clarity @gutzeit1106, Shared keys can be used using the environment variables `ACCOUNT_NAME` and `ACCOUNT_KEY`. These keys are intended to be full access to a single storage account. If you need them in a user-friendly way, you can obtain them using Azure Storage Explorer.

**Comment by gutzeit1106** [comment]
@adreed-msft  I understand that SharedKey for this help means ACCOUNT_NAME and ACCOUNT_KEY. Thank you for your response. 

On the other hands,  README.md describe the following. 

https://github.com/Azure/azure-storage-azcopy#authenticating-with-azure-storage
![image](https://user-images.githubusercontent.com/17121624/57757430-65b4e400-7730-11e9-8b94-98ce6bce2cd5.png)

I think that this explanation should be revised.
