### ISSUE TITLE
How to override "There is currently a pending copy operation."

### ISSUE THREAD

**Issue by japicket** [Azure/azure-storage-azcopy#385]
Using the command line tool, I will occasionally receive an error: "The remote server returned an error: (409) Conflict. There is currently a pending copy operation." Is there a way to override the current copy operation or force the current copy operation to succeed instead of it failing? There shouldn't be any other pending copy operations taking place, but I am receiving this error anyways.

This occurs when copying an azure storage blob container to another azure storage blob container.

I have /NC:"number-of-concurrent-operations" set to 1 and there shouldn't be any miscellaneous copy operations interfering.

Using AzCopy v7.3.1.7 since I need Table support.

**Comment by EmmaZhu** [comment]
Hi @japicket , 
AzCopy doesn't support to force to copy to destination with a pending operation.

For the issue you met, did you use the resuming feature in AzCopy? Or when you meet this issue, could you share the storage account name you are using and the time shit when it happens?  I may be able to find some clue on our server side log.

Thanks
Emma

**Comment by zezha-msft** [comment]
Closing since V8 is no longer being actively maintained. Please give V10 a try [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy), it's been GA for a bit of time now. Please don't hesitate if you encounter any issue.
