### ISSUE TITLE
Parallel level in sync 

### ISSUE THREAD

**Issue by 6ixtec** [Azure/azure-storage-azcopy#390]
### Which version of the AzCopy was used? 
azcopy version 10.1.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy sync "$folder" "$container/$saskey" --recursive=true **--parallel-level 20** --delete-destination=true

### What problem was encountered?
unknown flag: --parallel-level

**Comment by JohnRusk** [comment]
See the AZCOPY_CONCURRENCY_VALUE environment variable documented here https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#advanced-configuration.

There is no command line parameter for parallelism.

Btw the default behaviour is already highly parallel. There is seldom any need to change it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by roberdaniel** [comment]
Hi @JohnRusk 
I came here trying to find out how to instruct azcopy to sync only a few files at a time.
I will try to explain a scenario where I think that limit simultaneous syncing files is very useful. 
I have a folder with 70~ big files that I want to put in Azure Blobs, 
The first time I run AZcopy It will start to upload 70 files at a time (which is crazy). Lets suppose that after 8 ours or running, none of then still finished its upload. At this point, for a given reason, you have to stop azcopy. 
As none of the sync files job has ended, if you cannot resume later, all your effort is lost.
I'm uploading to Azure Blob and I think resume is not possible, I'm right?
Not all the people has a big bandwidth, sometimes the upload slow a lot all the net, etc, you will find a lot of reasons to stop azcopy. 
So if you can narrow the sync effort to a few files at a time, you will have a better chance of sync success or at least not to lost all the work doing.
At this moment, I'm facing this problem. :(
It should be good to have the possibility to instruct Azcopy to sync a few files at a time (not to attack all the sync files at once). 
I hope my point has been understood.
Regards.

**Comment by zezha-msft** [comment]
Hi @roberdaniel, thanks for the feedbacks!

The tool was indeed optimized for high bandwidth scenarios, and that's why we try to do as many files simultaneously as possible, since the service side scales better this way.

I see that for your scenario, the current behavior is not ideal. I'll discuss with @JohnRusk and the team to figure out how to better support it.

**Comment by JohnRusk** [comment]
Robert and Ze, I've been thinking for some time of adding an optional environment variable to configure the number of files that are read from disk at the same time. If that is added, you'll be able to set it to a low value, to achieve what you want.

However, we are trying to minimize the number of "tuning knobs" that users have to think about when using the tool. So we'll need to think about it a bit more to decide whether that really is the right way to do this.

@roberdaniel What would you think of setting an environment variable, called for example AZCOPY_CONCURRENT_DISK_FILES?.  If you set it to, e.g., 10, then it won't start reading the 11th file until the one of the first 10 has been fully read.

**Comment by roberdaniel** [comment]
> Robert and Ze, I've been thinking for some time of adding an optional environment variable to configure the number of files that are read from disk at the same time. If that is added, you'll be able to set it to a low value, to achieve what you want.
> 
> However, we are trying to minimize the number of "tuning knobs" that users have to think about when using the tool. So we'll need to think about it a bit more to decide whether that really is the right way to do this.
> 
> @roberdaniel What would you think of setting an environment variable, called for example AZCOPY_CONCURRENT_DISK_FILES?. If you set it to, e.g., 10, then it won't start reading the 11th file until the one of the first 10 has been fully read.

Hi John
I think that AZCOPY_CONCURRENT_DISK_FILES will achieve exactly what I need.
I'm very pleased to this issue has been reopened.
Thank you very much.
Regards.

**Comment by JohnRusk** [comment]
I will add this environment variable to PR #511

**Comment by roberdaniel** [comment]
Glad to hear that

**Comment by JohnRusk** [comment]
BTW, I might change the name slightly, e.g. to AZCOPY_CONCURRENT_FILES.

**Comment by roberdaniel** [comment]
Sure!, regards.

**Comment by JohnRusk** [comment]
The release is out now, version 10.3 and I can confirm the name is AZCOPY_CONCURRENT_FILES.

**Comment by roberdaniel** [comment]
Many thanks, I will try it.
Regards!!!
