### ISSUE TITLE
Copy local to Azure Blob storage with SAS *and* specifying a destination folder

### ISSUE THREAD

**Issue by alvipeo** [Azure/azure-storage-azcopy#395]
Windows 10 x46, AzCopy 10.1.2

So how can I copy files from local to blob storage when I have SAS token for a container, but I want those files to be in a folder?

So I need to copy *.mp4 => [container-SAS]/some-folder. Is this possible?

**Comment by JohnRusk** [comment]
I can't check the code for you right now, but I _think_ you can just edit the SAS, and put more path elements in.  E.g. start with http://account.blob.core.windows.net/container?SAS
and edit it to 
http://account.blob.core.windows.net/container/some-folder?SAS

**Comment by alvipeo** [comment]
tried that. doesn't work.

**Comment by JohnRusk** [comment]
Thanks. We'll investigate the issue next week.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JohnRusk** [comment]
Wow, this one has slipped through the cracks. So sorry, @alvipeo! I said "next week" months ago.  

I'm puzzled that it didn't work, since in the time since you've logged this, I've often edited the target URL in my tests to add a subfolder in, and it works for me.  What happens when you try it?

**Comment by adreed-msft** [comment]
Hi there, this should be fixed in the upcoming release. Thanks for opening an issue!

**Comment by JohnRusk** [comment]
Version 10.3 is now out.
