### ISSUE TITLE
File with <no name> name is created when copying local folder with only one file inside

### ISSUE THREAD

**Issue by mkozioro** [Azure/azure-storage-azcopy#397]
### What command did you run?
azcopy copy \
    "/some_dir/*.gz" \
    "https://${ACCOUNT_NAME}.blob.core.windows.net/${CONTAINER_NAME}/some_dir/?${STORAGE_ACCOUNT_SAS}"

When /some_dir/ has only one file with .gz extension, uploaded file has <no name> name. I expect file name to be name of .gz file. When multiple .gz files exists in folder, names are correct.

![image](https://user-images.githubusercontent.com/8501148/58033640-1e11cc00-7b25-11e9-9744-79c8c9bf9d82.png)

**Comment by adreed-msft** [comment]
Hi there, this was patched in #451 and has made it into AzCopy v10.2.x. Enjoy!

**Comment by elsing** [comment]
When using the older service API for use with Azure Stack Hub - this bug once again appears. Is this something that can be fixed easily? 

<img width="264" alt="Screenshot 2021-12-24 at 08 27 23" src="https://user-images.githubusercontent.com/5830702/147334553-ba9341c2-eae9-45b9-8af4-91debd45d806.png">

https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-storage-transfer?view=azs-2108&tabs=az1#azcopy
