### ISSUE TITLE
Memory issues in Mac

### ISSUE THREAD

**Issue by focux** [Azure/azure-storage-azcopy#405]
##### Note: The version is visible when running AzCopy without any argument
I coudn't find the version but I'm using the latest version of Microsoft Azure Storage Explorer with AzCopy enabled.

### Which platform are you using? (ex: Windows, Mac, Linux)
MacBook Pro 16gb RAM

### What problem was encountered?
When I start copying a folder which size is around 80gb, It start taking all the available memory and then my mac shut down.

### How can we reproduce the problem in the simplest way?
Try to copy a big size folder in a Mac?

### Have you found a mitigation/solution?
No

### Attachments

![image](https://user-images.githubusercontent.com/3316818/58191535-c2625280-7c8c-11e9-86af-471f64f41d57.png)

![image](https://user-images.githubusercontent.com/3316818/58191544-c8583380-7c8c-11e9-9e45-0c9ea7c9ec74.png)

**Comment by JohnRusk** [comment]
Currently, AzCopy sets its memory usage target at 0.5 GB per CPU, plus some overhead.  How many CPUs does your Mac have?

BTW, we are looking at moving to directly detecting the amount of RAM instead of basing our cap on CPU count.

**Comment by focux** [comment]
I'm not sure if it's the answer you want but I have a Inter i7 2.9  Quadcore. Thank you for your help.

**Comment by JohnRusk** [comment]
Hmm, if it's quad core, that definitely suggests something is wrong with the way AzCopy is acting, because it should not use 10 GB on a 4 core machine.

One last question, just to make sure we try to reproduce this in the right way: roughly what was the typical size of the files in the folder you were transferring.  E.g. a few hundred KB each, a few MB each, several GB each?

**Comment by focux** [comment]
I'm transferring around 8M of JPG pictures, each one has a size of around ~9Kb.

Also, there's any work around to set the memory usage manually?

**Comment by JohnRusk** [comment]
Thanks. That will be useful information as we try to reproduce it.  Currently there is no workaround to set memory usage manually. We are considering that feature for a future release.

In the meantime, for a workaround, can you use Storage Explorer with AzCopy _disabled_ as a workaround. (that should work for everything except Data Lake Gen2, for which it can't be disabled).

**Comment by zezha-msft** [comment]
Hi @focux, thanks a lot for reaching out! I'm working on reproducing your scenario. For my information, were you uploading or downloading the 8 million images? And how were the images organized? Was there a particular folder structure? Were some images in deeper paths from the root? For example: root/.../.../.../.../.../.../..../example.jpg.

@JohnRusk I'm suspecting that the [list-of-files](https://github.com/Azure/azure-storage-azcopy/blob/master/cmd/copy.go#L204) flag might be the culprit. I'll try to repro with an accurate setup.

**Comment by JohnRusk** [comment]
@zezha-msft Oh yeah, that's a very plausible theory. (And we have no alternative theories that explain it!)

**Comment by JohnRusk** [comment]
@focux We are pretty certain that list-of-files is the culprit.  Ze has re-written that feature to avoid the problem, and its scheduled for release in 10.3

**Comment by focux** [comment]
Awesome! Thank you. I'm going to close the issue.
