### ISSUE TITLE
Copy from AWS S3 to Azure Data lake store Gen 2 not supported

### ISSUE THREAD

**Issue by vinulohar007** [Azure/azure-storage-azcopy#407]
### Which version of the AzCopy was used? 

azcopy_windows_amd64_10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?

.\azcopy.exe cp "https://S3.amazonaws.com/bucket_name/folder_name" "https://accont_name.dfs.core.windows.net/adls/folder<SAS token>" --recursive

### What problem was encountered?

failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

### How can we reproduce the problem in the simplest way?
Try copying files from AWS S3 to ADLS Gen 2

### Have you found a mitigation/solution?

NO

**Comment by JohnRusk** [comment]
Duplicate of #377

**Comment by JohnRusk** [comment]
Closing this because its a duplicate.
