### ISSUE TITLE
Copy more than one file at once

### ISSUE THREAD

**Issue by borisklug** [Azure/azure-storage-azcopy#409]
### Which version of the AzCopy was used? 
10.1.2

### Which platform are you using?
Linux and Windows Subsystem for Linux (WSL)

### What command did you run?
`azcopy sync` or `azcopy copy` 

Like `scp` it would be great if azcopy can copy more than one file with one command. 
For example:

`azcopy copy file1 file2 file3 <destinationfolder>`

**Comment by JohnRusk** [comment]
And you don't want to use a wildcard, right, you want to name the individual files?

**Comment by borisklug** [comment]
Thank you for the (very!) quick reply.

It may work for others but we have a list of files that do not have a common patter like afile* or so.

**Comment by JohnRusk** [comment]
Hi @borisklug. Sorry about the delay. We have a solution. It was previously undocumented, but in response to your request we've had some discussions and decided to document it here: https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer 

Will it do what you need?

**Comment by borisklug** [comment]
He tested it and it works for us. Thank you for the response!

**Comment by jaymins93** [comment]
> He tested it and it works for us. Thank you for the response!

is it works on one storage account to another storage account

**Comment by borisklug** [comment]
> > He tested it and it works for us. Thank you for the response!
> 
> is it works on one storage account to another storage account

We only tested it from a local Linux pc to file storage.

**Comment by jaymins93** [comment]
i did several failed attempt , please let me know in case you guys can transfer between to azure storage account , it might be possible because azure storage explorer can copy paste between two azure storage account directly just we are not aware how it is doing john can you please help

**Comment by jaymins93** [comment]
i did several failed attempt , please let me know in case you guys can transfer between to azure storage account , it might be possible because azure storage explorer can copy paste between two azure storage account directly just we are not aware how it is doing john can you please help

**Comment by JohnRusk** [comment]
If you do a test on a small container, with just one or two files in it, does that work with AzCopy if you transfer the whole container I.e. if you do _not_ use `--list-of-files`?

**Comment by jaymins93** [comment]
single file to multiple azure storage account works but it is very slow to process single file , No i can not transfer entire container because i am processing azure queue message  , should i drop email to you regarding this for better communication  ?

**Comment by JohnRusk** [comment]
Sure. Send me an email.  It's evening in my part of the world, so it might be tomorrow when I reply.

**Comment by jaymins93** [comment]
ok no issue , i will drop you an email for this thanks
