### ISSUE TITLE
unable to download from azure blob - v10

### ISSUE THREAD

**Issue by cbugslag** [Azure/azure-storage-azcopy#411]
### Which version of the AzCopy was used? 
azcopy version 10.1.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
/usr/local/bin/azcopy copy "https://********.blob.core.windows.net/container/file.extension$SAS Token" "/path/to/file/newfilname.extension"

### What problem was encountered?
INFO: Scanning...
INFO: source is not validated as a single file: ResourceNotFound
INFO: trying to copy the source as container/directory/list of files

failed to perform copy command due to error: cannot start job due to error: the destination must be an existing directory in this download scenario.

### How can we reproduce the problem in the simplest way?
Not sure - I ran the same commands earlier this week successfully and now they fail, so it might be a change in azure functionality...

### Have you found a mitigation/solution?
No

**Comment by cbugslag** [comment]
What command can I run to see if my connectivity to the blob storage is failing?

**Comment by cbugslag** [comment]
so, it used to require a $ separating the file from the SAS token, that seems to have been removed.

**Comment by adreed-msft** [comment]
I was about to comment that ResourceNotFound is often used as a substitute for failed authentication when looking around in blob storage-- it's safer to just blanket it with ResourceNotFound than to directly tell the person that authentication failed.
