### ISSUE TITLE
"azcopy sync" tier option not available?

### ISSUE THREAD

**Issue by jantielens** [Azure/azure-storage-azcopy#416]
### Which version of the AzCopy was used? 
10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
``azcopy sync "(local file system)" "(SAS token)" --block-blob-tier=archive``

### What problem was encountered?
Using the ``copy`` option of azcopy, I can set the desired tier for the files in my Azure storage container (e.g. archive tier). When using the ``sync`` command, this is not possible. Is this by design?

My scenario: I have a bunch of files on my local file system, which I want to copy to Azure using the archive tier. Files are added to my local file system over time (but files are not changed/deleted). I just want to copy the new files, so the ``sync`` option seemed to be a good candidate.

### How can we reproduce the problem in the simplest way?
Just just the ``sync`` option in combination with ``block-blob-tier``.

### Have you found a mitigation/solution?
/

**Comment by zezha-msft** [comment]
Hi @jantielens, thanks for reaching out!

You can use the `copy` command with the flag `--overwrite=false`, it will only copy the new files like you wanted.

The `sync` command was kept simple intentionally, but we'll definitely consider expanding its flag set in the future.

**Comment by mvodep** [comment]
So sync only works on Hot / Cool and than move blobs to archive? And if I want to sync again - other way round?

**Comment by mrgum** [comment]
please consider adding this flag.

without it I have to reimplement the sync function to list changed files and use copy to send the files that have changed
