### ISSUE TITLE
When resuming, throughput is no longer shown

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-azcopy#42]
C:\Users\seguler\Desktop\azcopy_windows_amd64_10.0.0\azcopy_windows_amd64_10.0.0>.\azcopy_windows_amd64.exe jobs resume 8f925120-9bb6-b540-707e-4be86899b4ff --destination-sas="REDACTED"

Job 8f925120-9bb6-b540-707e-4be86899b4ff has started

8f925120-9bb6-b540-707e-4be86899b4ff.log file created in C:\Users\seguler/.azcopy
1350 Done, 0 Failed, 0 Skipped, 58065 Pending, 59415 Total

**Comment by seguler** [comment]
Issue still not fixed:

seguler@seguler-sdk-test:~/azcopy_linux_amd64_10.0.3$ ./azcopy jobs resume 1c7740e6-0e4a-1d4f-743f-5ceb97f3e38a --destination-sas "redacted"

Job 1c7740e6-0e4a-1d4f-743f-5ceb97f3e38a has started

1c7740e6-0e4a-1d4f-743f-5ceb97f3e38a.log file created in /home/seguler/.azcopy
125285 Done, 0 Failed, 0 Skipped, 2616425 Pending, 2741710 Total

**Comment by zezha-msft** [comment]
This is fixed.
