### ISSUE TITLE
High CPU usage with azcopy login

### ISSUE THREAD

**Issue by dalee-bis** [Azure/azure-storage-azcopy#420]
##### Note: The version is visible when running AzCopy without any argument

AzCopy 10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows 10 64-bit

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

`azcopy login`

### What problem was encountered?

The application prompts to go to a web address to login. While waiting for the user to login, the CLI uses 25% of a quad-core processor (doesn't seem to be maxing out a single core though).

### How can we reproduce the problem in the simplest way?

Remove login credentails, then run `azcopy login`. Once prompted to login, open task manager and find azcopy in the details tab.

### Have you found a mitigation/solution?

No

**Comment by JohnRusk** [comment]
Related to https://github.com/Azure/azure-storage-azcopy/issues/419

**Comment by JohnRusk** [comment]
I've checked the code in the AD auth library that we call, and can't see anything that looks like a "busy wait". I.e. whatever is chewing up the CPU... I can't find it. However, the next release will fix #419 so at least the system will be usable on even single-CPU machines.  So I propose to close this issue.

cc @zezha-msft FYI.
