### ISSUE TITLE
AZCOPY_LOG_LOCATION

### ISSUE THREAD

**Issue by bbieb** [Azure/azure-storage-azcopy#421]
##### Note: The version is visible when running AzCopy without any argument
10.1.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 64 bit
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
set AZCOPY_LOG_LOCATION=c:\azcopy

![azcopy-log-location](https://user-images.githubusercontent.com/13998759/58575565-efbc7c80-8207-11e9-898e-e8b428cfb25a.png)

### What problem was encountered?
Log file location does not change.
### How can we reproduce the problem in the simplest way?
Is this the correct way to change the log location?  Try in Windows Powershell.  
### Have you found a mitigation/solution?
I tried the same process for logs as described [here](https://kvaes.wordpress.com/2019/05/13/what-the-proxy-how-to-use-a-proxy-with-the-typical-azure-tools/) but that didn't seem to work.

**Comment by adreed-msft** [comment]
Are you sure you're setting your environment variables correctly?

I'm unable to reproduce this. I set my environment variables as following in powershell:
```powershell
$env:AZCOPY_LOG_LOCATION="<wherever>"
```

**Comment by bbieb** [comment]
I was pretty sure I wasn't setting it correctly but couldn't figure out the correct keystrokes.
Thanks.
brian

**Comment by bbieb** [comment]
It worked great except the plans are still in the C:\Users\bbieber\.azcopy\plans.

**Comment by pmpopovichjr** [comment]
I just ran into this issue today actually. The documents here https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure?toc=/azure/storage/blobs/toc.json dont really lay out the proper usage as adreed-msft has in the comment above. Not sure how to request an update on the docs, but it might not be a terrible idea to help others.

**Comment by JohnRusk** [comment]
@normesta ?

**Comment by normesta** [comment]
Hello. This section of content describes how to set log file location - [Change the location of plan and log files](https://docs.microsoft.com/azure/storage/common/storage-use-azcopy-configure?toc=/azure/storage/blobs/toc.json#change-the-location-of-the-plan-and-log-files).

**Comment by pmpopovichjr** [comment]
![image](https://user-images.githubusercontent.com/49451139/83521394-2c6f2380-a4ad-11ea-9e84-c9c9ec3fce10.png)
Yes, however, there is no "$" in the docs, which adreed-msft noted in the comment above and was needed to fix it. That's what is missing in the docs that made it work for me.

**Comment by pmpopovichjr** [comment]
Oh, wow. Nice catches. I also am surprised the settings doesn't persist (tho, there's no config file to hold it that I saw so that makes sense). If you can call that out it would be appreciated for future folks to hopefully not end up back here. :)

**Comment by JohnRusk** [comment]
>I noticed that this setting doesn't persist after the session is closed but we don't document that behavior. Should we call this out?

I'm not sure @normesta. On one hand, it's standard behavior of environment variables. On the other hand, we are likely to have some users who aren't familiar with that standard behavior. So probably its worth mentioning it.

**Comment by mwarqee** [comment]
is it possible to set the AZCOPY_LOG_LOCATION to a folder on an azure storage account? For example setting it to a "logs" folder in the destination storage account.
