### ISSUE TITLE
azcopy using managed identity and piping does not seem to do anything

### ISSUE THREAD

**Issue by RossHannah** [Azure/azure-storage-azcopy#425]
##### Note: The version is visible when running AzCopy without any argument

10.1.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
(pg_dumpall -g | /usr/local/bin/azcopy cp "${BLOB}${BACKUP_MEMBER}/pgdumpallg.sql") 2>&1 

### What problem was encountered?
azcopy using managed identity and piping does not seem to do anything, we are using pg_dumpall to pipe to blob storage and do not want to unnecessarily write to disk first

### How can we reproduce the problem in the simplest way?
azcopy login --identity
cat ~/aaa.txt | azcopy cp "https://<storage>.blob.core.windows.net/backup/aaa.txt"

### Have you found a mitigation/solution?
azcopy login --identity
azcopy cp ~/aaa.txt "https://<storage>.blob.core.windows.net/backups/aaa.txt"

**Comment by JohnRusk** [comment]
Possibly related to #413

**Comment by JohnRusk** [comment]
Logged for investigation

**Comment by cccs-eric** [comment]
Hi @JohnRusk , would it be possible to get an update on that issue?  I'm using 10.4.3 and azcopy fails to copy a file to the lake using OAuth&pipe:

```
export AZCOPY_SPA_CLIENT_SECRET="${CLIENT_SECRET}"
azcopy login --tenant-id ${TENANT_ID} --service-principal --application-id ${CLIENT_ID}

# The following works:
azcopy cp test https://mystorageaccount.blob.core.windows.net/data/test

# The following does NOT work:
cat test | azcopy cp https://mystorageaccount.blob.core.windows.net/data/test

# The following works using SAS, to prove the problem is isolated to OAuth&pipe and not pipe in general
azcopy logout
azcopy cp test https://mystorageaccount.blob.core.windows.net/data/test?${SAS_TOKEN}
cat test | azcopy cp https://mystorageaccount.blob.core.windows.net/data/test?${SAS_TOKEN}
```

We have been using SAS tokens, but we want to move to OAuth, so it would be nice to have azcopy support this use case.

Thanks for looking into this.

**Comment by JohnRusk** [comment]
cccs-eric, I've handed this issue over to @zezha-msft , @adreed-msft , @nakulkar-msft  and @amishra-dev .

**Comment by davelosert** [comment]
Any updates on this? 

I am experiencing the exact same issue.  Piping with SP Login does definitly not work.
The command just returns with an exit-status of 1, but there is no error message (which makes this even harder to debug).
