### ISSUE TITLE
Misleading warning about source enumeration not being complete when cancelling job

### ISSUE THREAD

**Issue by ImrePyhvel** [Azure/azure-storage-azcopy#428]
### Which version of the AzCopy was used? 
AzCopy 10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 

### What command did you run?
`> azcopy.exe sync "https://myaccount.blob.core.windows.net/myContainer?<sasToken>" "myFolder/"`

### What problem was encountered?

I'm copying many files (~200k+), azcopy seems to enumerate source with 5k items at the time, then copying them before enumerating the next batch. When trying to cancel the job with the intent of resuming it later, azCopy warns me with: 

> "The source enumeration is not complete, cancelling the job at this point means it cannot be resumed. Please confirm with y/n"

Listening to this warning would block me from stopping/resuming the job altogether. When I do confirm the cancel, it does not cancel immediately, but stops copying and continues to enumerate source instead. The job actually was able to resume by jobId.

**So, while the provided warning was probably adequately describing the state in that specific moment in time, it was confusing and deeply misleading regarding the actual effect to user.**

### How can we reproduce the problem in the simplest way?
Use slow-enough connection, copy from blob storage with many files (20k+?) to local disk. Press Ctr-C once copy process has started.

### Have you found a mitigation/solution?
The warning can presumably be ignored if you let the follow-up enumeration to finish.

**Comment by zezha-msft** [comment]
Hi @ImrePyhvel, thanks for reaching out!

I've logged this item for further investigation. To clarify though, in a sync command, the tool enumerates the local directory first, and then scans the remote resource to figure out which files need to be transferred. We do this so that data can start to be transferred while enumeration is still happening.

**Comment by siminsavani-msft** [comment]
Hi there! When I try Ctr-C during the transfer/copy process with the latest AzCopy, I do not see the message you have shared with us. Instead, I see this `INFO: Cancellation requested. Beginning clean shutdown...`

Please try the latest AzCopy version and let us know if this issue still persists!
