### ISSUE TITLE
Cannot copy a file from a UNC path when the filename contains both a hash and whitespace characters

### ISSUE THREAD

**Issue by hentie** [Azure/azure-storage-azcopy#432]
### Which version of the AzCopy was used? 
10.1.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
.\azcopy cp "\\testserver\testshare\file with space and #in-the-name.zip" "https://somestorage.blob.core.windows.net/somecontainer/file with space and #in-the-name.zip?st=someSASToken"

### What problem was encountered?
Cannot copy the file to the blob storage and gives a fail to copy in the results

### How can we reproduce the problem in the simplest way?
Try to copy a file with azcopy from a windows file share to a blob storage container WHERE the source file name contains both hash (#) and whitespace ( ) character(s) 

### Have you found a mitigation/solution?
Remove all # charcters OR remove all whitespace characters from the source file

**Comment by JohnRusk** [comment]
Thanks @hentie. We've logged this for investigation

**Comment by adreed-msft** [comment]
This one works in the latest release (10.3.0)! Enjoy!
![image](https://user-images.githubusercontent.com/49764384/66867556-6a382f80-ef50-11e9-88bd-fa2a9bd457d5.png)
