### ISSUE TITLE
Cannot Copy file from AWS S3 Buckets

### ISSUE THREAD

**Issue by thomasmaurer** [Azure/azure-storage-azcopy#435]
### Which version of the AzCopy was used? 
10.1.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy cp "https://s3.amazonaws.com/thomasmaurerimages" "https://tomsazureaccount.blob.core.windows.net/?sv=somesastoken" --recursive=true

### What problem was encountered?
Copy of items from AWS bucket to Azure Blob fails. Strangely the same command worked 3 weeks ago. In the log I get the following error:

INFO: Scanning...
INFO: AWS S3 to Azure Blob copy is currently in preview. Validate the copy operation carefully before removing your data at source.
INFO: trying to copy the source as bucket/folder/list of files
INFO: source is bucket and destination is an Azure service endpoint, bucket with name "thomasmaurerimages" will be created in destination to store data

Job e8663afe-06be-4749-7826-74563e5ff28c has started
Log file is located at: C:\Users\thmaure/.azcopy/e8663afe-06be-4749-7826-74563e5ff28c.log

0 Done, 0 Failed, 33 Pending, 0 Skipped, 33 Total,

Job e8663afe-06be-4749-7826-74563e5ff28c summary
Elapsed Time (Minutes): 0.0334
Total Number Of Transfers: 33
Number of Transfers Completed: 0
Number of Transfers Failed: 33
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed

The log files has marked the following: 

2019/06/11 15:14:21 INFO: [P#0-T#3] Starting transfer: Source "https://s3.amazonaws.com/thomasmaurerimages/images/HJymwQA%20-%20Copy%20%282%29.png" Destination "https://tomsazureaccount.blob.core.windows.net/thomasmaurerimages/images/HJymwQA%20-%20Copy%20%282%29.png?se=2019-06-11t23%3A07%3A16z&sig=REDACTED&sp=rwXXXX". Specified chunk size 8388608
2019/06/11 15:14:21 INFO: [P#0-T#13] Starting transfer: Source "https://s3.amazonaws.com/thomasmaurerimages/images/CjKfteT%20-%20Copy%20%282%29.png" Destination "https://tomsazureaccount.blob.core.windows.net/thomasmaurerimages/images/CjKfteT%20-%20Copy%20%282%29.png?se=2019-06-11t23%3A07%3A16z&sig=REDACTED&sXXXX6-11t15%3A07%3A16z&sv=2018-03-28". Specified chunk size 8388608
2019/06/11 15:14:21 ==> REQUEST/RESPONSE (Try=1/479.1841ms, OpTime=479.1841ms) -- RESPONSE STATUS CODE ERROR
   PUT https://tomsazureaccount.blob.core.windows.net/thomasmaurerimages/images/8h0LEDm%20-%20Copy%20%282%29.png?XXXXXX
   Content-Length: [0]
   User-Agent: [S3Import AzCopy/10.1.2 Azure-Storage/0.6 (go1.10.8; Windows_NT)]
   X-Ms-Client-Request-Id: [80fa0cbb-3b3a-41f5-7dd3-692ebf7034f8]
   X-Ms-Copy-Source: [https://thomasmaurerimages.s3.dualstack.eu-central-1.amazonaws.com/images/8h0LEDm%20-%20Copy%20%282%29.png?x-amz-algorithm=aws4-hmac-sha256&x-amz-credential=akiajcXXXXXquest&x-amz-date=20190611t151420z&x-amz-expires=604800&x-amz-signature=REDACTED&x-amz-signedheaders=host]
   X-Ms-Source-Range: [bytes=0-374443]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The copy source must be an Azure resource.
   Content-Length: [233]
   Content-Type: [application/xml]
   Date: [Tue, 11 Jun 2019 15:14:20 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [CannotVerifyCopySource]
   X-Ms-Request-Id: [2d675b22-301e-006f-5b68-201d65000000]
   X-Ms-Version: [2018-11-09]
goroutine 60 [running]:

### How can we reproduce the problem in the simplest way?
Run the mentioned command

### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Hi @thomasmaurer, thanks for reaching out! And sorry for the inconvenience.

It looks like a configuration issue on the service side. I'll involve the service folks and update this thread accordingly.

**Comment by zezha-msft** [comment]
Hi @thomasmaurer, it was indeed a configuration issue. It should be fixed now. Please let me know if you are still encountering issues.

**Comment by thomasmaurer** [comment]
hi  @zezha-msft, I just tried again. I still have the issue:

2019/06/12 15:29:46 ERR: [P#0-T#2] COPYFAILED: https://s3.amazonaws.com/thomasmaurerimages/8h0LEDm%20-%20Copy.png : 400 : 400 The copy source must be an Azure resource.. When Staging block from URL. X-Ms-Request-Id: e377d22e-201e-003e-2f33-2180e9000000

**Comment by zezha-msft** [comment]
@thomasmaurer really sorry for the inconvenience. There was a minor hiccup in the configuration. It should be fixed now. Really appreciate your patience.

**Comment by TryTryAgain** [comment]
Same issue, seems to still be happening?
