### ISSUE TITLE
Sync Download failed with long source address (SAS)

### ISSUE THREAD

**Issue by ashmosis** [Azure/azure-storage-azcopy#437]
### Which version of the AzCopy was used? 
10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`azcopy sync $"https://gwps01.blob.core.windows.net/quarry-company?sv=2018-03-28&ss=b&srt=sco&sp=rl&se=2028-06-01T11:01:21Z&st=2019-06-10T03:01:21Z&spr=https&sig=REDACTED" "C:\GPlusLiveSync\quarry-company" --recursive=true`

### What problem was encountered?
When the sync occurs, most files download successfully except those with long path names. I noticed that the original SaS (in the above command) gets transformed to:
`se=2028-06-01t11%3A01%3A21z&sig=REDACTED&sp=rl&spr=https&srt=sco&ss=b&st=2019-06-10t03%3A01%3A21z&sv=2018-03-28`. Which also adds to the length of the URL.

Below is an example of the log output:

> 2019/06/12 00:03:04 JobID=85a11013-58f7-a046-7cf3-4d3911283631, Part#=0, TransfersDone=2 of 8
> 2019/06/12 00:03:04 INFO: [P#0-T#2] has worker 13 which is processing TRANSFER
> 2019/06/12 00:03:04 ERR: [P#0-T#2] DOWNLOADFAILED: https://gwps01.blob.core.windows.net/quarry-company/My%20Quarry%2FDust%20%2FDatasetFiles%2FEB1802774_0_SRN_180129170534.pdf?se=2028-06-01t11%3A01%3A21z&sig=REDACTED&sp=rl&spr=https&srt=sco&ss=b&st=2019-06-10t03%3A01%3A21z&sv=2018-03-28 : 000 : File Creation Error mkdir C:/GPlusLiveSync/quarry-company/My Quarry/Dust /DatasetFiles: The system cannot find the path specified.
>    Dst: c:///GPlusLiveSync/quarry-company/My%20Quarry/Dust%20/DatasetFiles/EB1802774_0_SRN_180129170534.pdf
> 2019/06/12 00:03:04 DBG: [P#0-T#2]  Finalizing Transfer Cancellation/Failure
> 2019/06/12 00:03:04 ERR: [P#0-T#2] c:///GPlusLiveSync/quarry-company/My%20Quarry/Dust%20/DatasetFiles/EB1802774_0_SRN_180129170534.pdf: 0: Delete File Error -remove C:/GPlusLiveSync/quarry-company/My Quarry/Dust /DatasetFiles/EB1802774_0_SRN_180129170534.pdf: The system cannot find the path specified.. X-Ms-Request-Id:
> 

### How can we reproduce the problem in the simplest way?
Try to create a container and file with the same path as above. When the sync fails, try to use the url from the log file in your browser (you are presented with an Auth error). Now if you use the originally formatted SaS, it will download.

### Have you found a mitigation/solution?
It appears the formatting of the SaS may affect the authentication on long path names.

**Comment by adreed-msft** [comment]
Hi, I may be misunderstanding your issue. Are you trying to download files with paths longer than 260 characters?

**Comment by ashmosis** [comment]
No, the path is shorter than 260, but once the SaS token is added the URL it uses to get the file is longer than 260 characters.

**Comment by adreed-msft** [comment]
Have you been able to reproduce this on another OS, say, Linux?

**Comment by ashmosis** [comment]
Thanks for your assistance with this.
I have just tested with Linux and the issue does not occur. The same command on Windows (with Windows destination file path convention), fails to download the files.

This should not be a file path length issue with Windows since the full expected path if it downloaded would be "C:\GPlusLiveSync\quarry-company\My Quarry\Dust \DatasetFiles\EB1802774_0_COA.pdf" which is 80 characters.

**Comment by adreed-msft** [comment]
Say, does the folder Dust have a space at the end of it? I have a sneaking suspicion that may be causing this.

**Comment by ashmosis** [comment]
I just had a look and it appears this is the issue for all of the folders that did not sync contain an illegal character. Thanks, I did not spot that. I will let the dev know that maintains these blobs for us.
It might be nice to test for illegal characters so that a more correct error message could be displayed (or potentially be removed so the Sync can proceed).

**Comment by adreed-msft** [comment]
I will keep this issue open and create a backlog for prompts for downloading files/folders with illegal characters. Perhaps it may be best to offer to replace these with a neutral character, like - or _

**Comment by JohnRusk** [comment]
10.3 will replace invalid characters, by URL-encoding them to create the Windows filenames.

**Comment by JohnRusk** [comment]
The invalid character issue is fixed in version 10.3, which has just been released.  It URL-encodes them.
