### ISSUE TITLE
processing multiple files with azcopy.exe takes too much time same operation copy paste works fast in azure storage explorer 

### ISSUE THREAD

**Issue by jaymins93** [Azure/azure-storage-azcopy#442]
### What command did you run?

azcopy.exe cp "https://xxx.blob.core.windows.net/testcontainer/1.txt?mysastoken" "https://yyyy.blob.core.windows.net/container6142019/1.txt?mysastoken"

### What problem was encountered?

it may be not problem but the issue is i want to copy the multiple files from the one container to another container with each as single file ( i do not want entire directory or container as i will be receiving the file list from azure queue message ) so for e.g. i have 5000 file i am able to copy them successfully without any issue , but it process the single file and run azcopy.exe from my code and process the operation , as compare to azure storage explorer even if i copy paste from different storage account it copies very quickly so i want to know the command or way how it is implemented as copying single file using the azcopy.exe taking too much time and it is slowing down the operation too much as compare to azure storage explorer it works very fast , so can you please help me with command to process multiple files or how it is implemented in the azure storage explorer. 

### How can we reproduce the problem in the simplest way?

use azcopy.exe use 5000 text file and use the above command 

### Have you found a mitigation/solution?

no , i  am looking for solution 

just to mention it is not issue i need help or way to achieve the desired output

**Comment by JohnRusk** [comment]
Hi. If I understand correctly, you are currently calling AzCopy 5000 times, once for each file. Is that correct? Do you want to call AzCopy once, and have it process 5000 files in just one call to AzCopy? If so, please see the comments on this issue #409. My last comment there contains a link to a wiki page that tells you how to do what you want.

**Comment by jaymins93** [comment]
yes that's correct , what you understood

**Comment by jaymins93** [comment]
great great great you made my day , why it is not documented but  ?

**Comment by jaymins93** [comment]
is it supports azure one storage account to another storage account i need to transfer between the azure account not between the local and azure
