### ISSUE TITLE
AzCopy v8.1 gets hung during upload data from local to Blob Storage

### ISSUE THREAD

**Issue by JavedEqbal** [Azure/azure-storage-azcopy#443]
### Which version of the AzCopy was used? 
AzCopy 8.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2012 R2 Standard

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Running it via batch script :-
``
set SourceCnt=D:\azcopytest
set DestinationCnt=https:// blobstorage.blob.core.windows.net/documents
set DestinationKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
set AzCopy="%ProgramFiles(x86)%\Microsoft SDKs\Azure\AzCopy\AzCopy.exe"
%AzCopy% /Source:%SourceCnt% /Dest:%DestinationCnt% /DestKey:%DestinationKey% /SetContentType /S /XO /XN /NC:10 /Y
``

### What problem was encountered?
We run this job to copy files (img/jpg) from local <C:\Folder-to-Upload\> to Azure Blob Storage, we upload new data folders to  local <C:\Folder-to-Upload\folder-1 and folder-n> so that it gets detected everytime via /XO & /XN switches and new data folder gets copied to Storage Account but once in around 10-15 days the AzCopy process seems not to work and stops uploading new folders until we restart the AzCopy job and even the AzCopy process gets hung and does not end, ending the task from Task Manager does not work and not even when tried to kill the process from CMD/PowerShell. The same setup is used few places and it works well in production environment with the same AzCopy-v8.1.

NOTE:- Server has ample of resources like 256GB RAM/64CPU & Good Network BW and during the AzCOpy task seems to be hung the system looks working normal with no overutilization of compute/network resources.

Also we are not planning to use v10 into production as it's new release and might cause issues.

### How can we reproduce the problem in the simplest way?
Not sure

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
Answered offline yesterday. Closing.

**Comment by sri-chittela** [comment]
Hi JohnRusk, 
I'm having the same issue as JaveEqbal. Could you please tell me the solution you provided. I can't upgrade our server for now. I'm using Azcopy 8.1 on windows 2012 R2 data center in Azure and the upload job gets hung. 
Thanks in advance.

**Comment by JohnRusk** [comment]
@sri-chittela Best thing is to move to v10 if you can.  If you can't do that, maybe try reducing concurrency in v8.1 with the /NC parameter. I'm not sure that will work every time, but it might help.

**Comment by sri-chittela** [comment]
Thanks for the advice, I'll try with v10.
