### ISSUE TITLE
AWS S3 to Azure failing

### ISSUE THREAD

**Issue by rkmore** [Azure/azure-storage-azcopy#445]
### Which version of the AzCopy was used? 

10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows

### What command did you run?

azcopy cp "https://s3.us-west-2.amazonaws.com/arad-data-prd/lidar/raw/2018/2018_vm_tier3_distribution/greengrid/points/accepted/PTT Data Request/" "https://pgesapequipid.blob.core.windows.net/poleimages<<SAS REMOVED>>" --recursive

### What problem was encountered?

All operations failed

### How can we reproduce the problem in the simplest way?

Unknown.  I have used this before without issue.  Only hint is that folders have special character in name?  Example "100000009%0A"

Pertinent portion of log included below

   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Bad Request
   Content-Length: [324]
   Content-Type: [text/html; charset=us-ascii]
   Date: [Mon, 17 Jun 2019 11:01:28 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
goroutine 275 [running]:
github.com/Azure/azure-storage-azcopy/ste.stack(0xc0434afea0, 0xc04357d800, 0xc04250e750)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/xferLogPolicy.go:135 +0xae
github.com/Azure/azure-storage-azcopy/ste.NewRequestLogPolicyFactory.func1.1(0xc9d620, 0xc042cb9b60, 0xc043379900, 0xbfcb6f, 0xc, 0xbfaebd, 0xa)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/xferLogPolicy.go:102 +0x66c
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc044c5b2c0, 0xc9d620, 0xc042cb9b60, 0xc043379900, 0xa, 0xc042204240, 0x90, 0x90)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0xc9d620, 0xc042cb9b60, 0xc043379900, 0xc042b48c00, 0x60, 0x7e490, 0x0)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:68 +0xef
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc04325e8e0, 0xc9d620, 0xc042cb9b60, 0xc043379900, 0xc042dfb250, 0x10, 0xc043432901, 0xc042dfb200)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0xc96820, 0xc04325e8e0, 0xc044bc05a0, 0xc9d620, 0xc042cb9b60, 0xc043379900, 0x10, 0x10, 0xb2fde0, 0xc042b48c00)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_responder_policy.go:34 +0x5a
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(0xc96860, 0xc04325e900, 0xc9d620, 0xc042cb9b60, 0xc043379900, 0xd402a92901, 0xc042dfb270, 0xc042dfb330, 0x4e1eda)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_credential_anonymous.go:54 +0x56
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do(0xc043c5d180, 0xc9d620, 0xc042cb9b60, 0xc043379900, 0x0, 0x0, 0x0, 0xc042dfb380)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/xferRetryNotificationPolicy.go:59 +0x65
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do-fm(0xc9d620, 0xc042cb9b60, 0xc043379900, 0x10dc4e0, 0xc9d620, 0xc042cb9b60, 0xc043c5d360)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/xferRetryNotificationPolicy.go:77 +0x4f
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc043c5d190, 0xc9d620, 0xc042cb9b60, 0xc043379900, 0xc042cb9b60, 0xc043c5d360, 0x1, 0x0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0xc9d660, 0xc0434328a0, 0xc043379800, 0xc042cf, 0x16, 0xc043dfecf0, 0x24)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/xferRetrypolicy.go:365 +0x71d
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc044c5b310, 0xc9d660, 0xc0434328a0, 0xc043379800, 0x24, 0x60e8c7, 0xb5fbc0, 0xc043432900)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0xc9d660, 0xc0434328a0, 0xc043379800, 0xbfb237, 0xa, 0xc04303e180, 0x3f)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_unique_request_id.go:19 +0xa3
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc04325e920, 0xc9d660, 0xc0434328a0, 0xc043379800, 0x3f, 0xc043718078, 0xc043432960, 0xc042dfb750)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0xc9d660, 0xc0434328a0, 0xc043379800, 0x1, 0x0, 0x1, 0xc043718078)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_telemetry.go:34 +0xa5
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc043432960, 0xc9d660, 0xc0434328a0, 0xc043379800, 0xc043432960, 0xbf6280, 0xc042dfb7c0, 0x410eff)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc042e70040, 0xc9d660, 0xc0434328a0, 0xc96880, 0xc044bc05a0, 0xc043379800, 0x23, 0xc042dffda0, 0x56, 0x0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:128 +0x88
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.blockBlobClient.StageBlockFromURL(0xc0433c4480, 0x5, 0x0, 0x0, 0x0, 0xc0433c4488, 0x23, 0xc042dffda0, 0x56, 0x0, ...)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_block_blob.go:330 +0x401
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.BlockBlobURL.StageBlockFromURL(0xc0433c4480, 0x5, 0x0, 0x0, 0x0, 0xc0433c4488, 0x23, 0xc042dffda0, 0x56, 0x0, ...)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/url_block_blob.go:86 +0x186
github.com/Azure/azure-storage-azcopy/ste.(*urlToBlockBlobCopier).generatePutBlockFromURL.func1()
	/go/src/github.com/Azure/azure-storage-azcopy/ste/sender-blockBlobFromURL.go:138 +0x292
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0xbf)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/sender.go:148 +0x137
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc04288c000, 0xbf)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:230 +0x97
created by github.com/Azure/azure-storage-azcopy/ste.initJobsAdmin
	/go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:181 +0x6d6

2019/06/17 11:01:28 INFO: [P#0-T#8] Starting transfer: Source "https://s3.us-west-2.amazonaws.com/arad-data-prd/lidar/raw/2018/2018_vm_tier3_distribution/greengrid/points/accepted/PTT%20Data%20Request/100015636%0A/20190506-18105488698_InspectResult%20Pic%202_1.jpg" Destination "https://pgesapequipid.blob.core.windows.net/poleimages/PTT%20Data%20Request/100015636%0A/20190506-18105488698_InspectResult%20Pic%202_1.jpg?se=2019-06-16t19%3A07%3A40z&sig=REDACTED&sp=racwl&sr=c&st=2019-06-15t19%3A07%3A40z&sv=2018-03-28". Specified chunk size 8388608
2019/06/17 11:01:28 INFO: [P#0-T#121] has worker 31 which is processing TRANSFER
2019/06/17 11:01:28 ==> REQUEST/RESPONSE (Try=1/81.7822ms, OpTime=81.7822ms) -- RESPONSE STATUS CODE ERROR
   DELETE https://pgesapequipid.blob.core.windows.net/poleimages/PTT%20Data%20Request/100006370%0A/20190407-18102920647_InspectResult%20Pic%203_1.jpg?se=2019-06-16t19%3A07%3A40z&sig=REDACTED&sp=racwl&sr=c&st=2019-06-15t19%3A07%3A40z&sv=2018-03-28&timeout=31
   User-Agent: [S3Import AzCopy/10.1.2 Azure-Storage/0.6 (go1.10.8; Windows_NT)]
   X-Ms-Client-Request-Id: [71595f5b-9a65-4c70-516f-c31cf6d59053]
   X-Ms-Version: [2018-11-09]

### Have you found a mitigation/solution?

No

**Comment by JohnRusk** [comment]
Thanks. Your guess about special characters seems plausible. We'll investigate.

**Comment by zezha-msft** [comment]
Control characters are not allow. Doc: https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata
