### ISSUE TITLE
Azcopy 10 fills up unknown error macos

### ISSUE THREAD

**Issue by masters3d** [Azure/azure-storage-azcopy#448]
### Which version of the AzCopy was u
10
### Which platform are you using? (ex: Windows, Mac, Linux)
Mac
### What command did you run?
Copy
### What problem was encountered?

Unknown error. Fills up hard drive with junk then quits. 

### How can we reproduce the problem in the simplest way?

Always from the same HDD

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
Where does it put the junk?

**Comment by masters3d** [comment]
`.azcopy/plans` source hdd 3tb, boot drive 500gb ands plan takes 200gb until i see 
![image](https://user-images.githubusercontent.com/6539412/59693538-f5203d80-919b-11e9-876b-d7e9b65f7a6e.png)

**Comment by zezha-msft** [comment]
Hi @masters3d, sorry for the inconvenience, could you please tell us a bit about the size of the job you are running?

**Comment by masters3d** [comment]
I am copying a whole HDD which is about 3TB. I just select the root of the drive as a the folder.

**Comment by JohnRusk** [comment]
@zezha-msft What did we think the most probable cause was for this?  Plan file size? Log file size? Something else?

**Comment by zezha-msft** [comment]
@JohnRusk It appears to be plan files. I've made its location configurable for the upcoming release.

**Comment by JohnRusk** [comment]
OK. Will mark it as included in the 10.3 release, since the solution will be to move the plan files to a location with more space.

**Comment by zezha-msft** [comment]
This has been fixed in [10.3.0](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.3.0)!

@masters3d please use the environment variable `AZCOPY_JOB_PLAN_LOCATION` to put the state tracking files elsewhere. We are really sorry for the inconvenience and appreciate your patience.
