### ISSUE TITLE
Advice on optimizing download speeds

### ISSUE THREAD

**Issue by marcioos** [Azure/azure-storage-azcopy#449]
### Which version of the AzCopy was used? 
10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
```
AZCOPY_CONCURRENCY_VALUE=128
AZCOPY_LOG_LOCATION=/tmp

azcopy cp https://path/to/blob?sasStuff /local/file/path --log-level ERROR --check-md5 NoCheck
```

### What problem was encountered?
Operation takes more than 2 minutes to finish.

### How can we reproduce the problem in the simplest way?

Actually I'm filing this issue with the intent of asking for some tips from `azcopy` folks on how to optimize the speed of download operations on my scenario. Here it goes:

We run multiple VMs on Azure, each VM runs up to 16 Docker containers, where the application that relies on `azcopy` for downloads runs. Basically the application downloads a big file (block blob, typically ranging from 1GB to 3GB size) from a Blob Storage account that is in the _same_ Azure region as its hosting VM. Usually the application performs that download only once, at the beginning of its lifecycle. The lifetime of those applications range from a few minutes to hours.

Considering that in the worst case scenario we are going to have 16 Docker containers each downloading a big blob simultaneously, in the same VM (competing for the same CPU cores), I thought it would be reasonable to lower the `AZCOPY_CONCURRENCY_VALUE` value a bit, thus it is currently set to 128 (8 * vcpus). But I have no data on what would be the impact of a higher value on CPU or whether this would affect user experience, or even download speeds. Maybe an even lower value would help by putting less pressure on the storage accounts. *This is the first point where some advice would be appreciated :)*

It happens that, specially during high load hours, we start getting _very_ slow download speeds, like "more than 2 minutes" slow. It feels like either `azcopy` is not dealing with Blob Storage failures well (wild guess) or our Storage account service bandwidth is choking due to the high demand. I'd really like to avoid having to use a secondary Storage account or somehow have to change our file structure organization within the Storage account. 

Could `azcopy` help mitigating this issue somehow? Maybe a different download command than `cp`, or different parameters? Would leaving `AZCOPY_CONCURRENCY_VALUE` with its default value help?

Thanks!

**Comment by JohnRusk** [comment]
Hi @marcioos 

Great questions! :-)

## CPU: 

A high AZCOPY_CONCURRENCY_VALUE will not _necessarily_ result in all your CPU being used.  Often, even with the high values, most running routines are in a wait state, and not using much CPU.

From the perspective of code running inside the Docker container, how many CPUs does that code think it has?  E.g. if code inside the container thinks that's there's only 4 or fewer CPUs (pardon my ignorance of Docker, but I vaguely recall that's possible) then that code will automatically cut AZCOPY_CONCURRENCY_VALUE down to 32.

As a rule of thumb, I would suggest that you should be concerned about CPU usage if overall CPU usage is high on your VM, (e.g. as shown by "top" run on the VM, but watch out to see whether you're seeing figures as % of 1 CPU, or % of _total_ CPUs.)  If VM CPU usage is not high, I don't think CPU is going to be the most _likely_ cause of slow performance.

## Config of the VM:

It _may_ help to optimize the VM's networking settings for optimal download throughput. I don't know for sure. It's just a guess that it might help in your case.  Here is a link to a setup script for one of our other tools. You don't need most of it, but there's a bit inside it that optimizes network settings for download bandwidth.  Maybe that will help. Here is the script: https://aka.ms/fast-data-transfer-setup-linux-server  I'll leave it to you to find the right bit to use, but ask me if you need a hand :-)

## Contention, especially during high load hours:

It does sound like you are seeing some kind of contention in high load hours.

To diagnose, grep search a few of the AzCopy log files for "503" (without the quotes).  If you see a lot of ServerBusy errors, that means the Storage Service is telling AzCopy to slow down. (which AzCopy does by waiting a bit then trying again).  If you're seeing those that probably means that the total load, from all your containers, is  producing throughput higher than what the Storage account can handle. (All Storage accounts have a documented throughput limit).  To resolve that, try reducing the AZCOPY_CONCURENCY_LEVEL even further. E.g. to 16.  Or else, maybe it would help if you [ask to get your throughput levels raised](https://azure.microsoft.com/en-us/blog/announcing-larger-higher-scale-storage-accounts/). BTW, we will have a better resolution coming in a future version, where you can specify a max bandwidth for each instance of AZCopy to use.

If you are not seeing lots of 503s, that suggests that the contention is either at networking/TCP level (which will hopefully be solved by the VM config change above) OR that the contention is CPU or some other resource inside the VM.  The most likely resource under contention is VM disk...

## VM Disk

One possibility, quite a likely one actually, is that the contention is in fact on the VM disk to which you are saving the data.  Grep search the AzCopy logs for PERF and see if any of those lines report that the primary perf constraint is disk. (Note that we don't report on primary perf constraints during the first 30 seconds of a job). Or, to run some tests where you know disk won't be a factor, do some downloads to /dev/nul.  You'll have no data at the end of it (naturally!) but the speed you see is guaranteed not to be limited by local disk.

## Diagnostics: 

For more of performance diagnostics, see https://github.com/Azure/azure-storage-azcopy/wiki/Disk-and-service-constraint-indicators-in-AzCopy .  And if you still have questions after that, please ask here in this  issue.

**Comment by marcioos** [comment]
Thanks for the thoughtful suggestions. 

I'll start by saving `azcopy`'s log files whenever a slow operation happens (we are currently always deleting the log file after an operation finishes or is aborted due to timeout), then look for service contention and disk performance clues on them.

Regarding `AZCOPY_CONCURRENCY_VALUE`, could your confirm that it represents the number of concurrent requests made towards the storage account? If that's the case, I'm thinking we might be getting throttled due a high volume of concurrent requests. Based on the number of concurrent application instances we run at peak times, it is very likely that we are hitting the 20000 limit with with `AZCOPY_CONCURRENCY_VALUE=128`.

At this point that is just a guess though. I'll start analyzing log files to try to get some real data on this.

**Comment by JohnRusk** [comment]
Yes, it means the number of concurrent requests.

Re account limits: unless your blobs are particularly small, you'll generally hit the account throughput limit (20 Gbps) long before you hit the IOPS (request per second) limit.  The IOPS limit is usually only hit when requests are very small (e.g 10s of KB).

**Comment by JohnRusk** [comment]
@marcioos In version 10.2.1 we just released the --cap-mbps parameter when lets you control network usage directly (and indirectly control CPU usage - since less network throughput means less CPU usage).

It provides much more accurate control than messing with AZCOPY_CONCURRENCY_VALUE.

You can use it to reduce contention, if that contention is at the Storage account level. Because it also has the side effect of reducing CPU usage, you can also use it to reduce CPU contention, by telling each instance of AzCopy to go at some limited speed that you select. (It won't help you much with local disk contention, although I guess the host machine may handle that better if you slow each instance of AzCopy down a bit, with this parameter0.

On that basis, I'm going to close this issue. Please let us know if we need to re-open the issue.
