### ISSUE TITLE
Azcoy Sync Command Switches not working using Batch File

### ISSUE THREAD

**Issue by ashishmswipe** [Azure/azure-storage-azcopy#453]
### Which platform are you using? (ex: Windows, Mac, Linux)
     Windows 10

### What command did you run?

azcopy sync "D:\uatazurefiles" "https://blobstorage.blob.core.windows.net/doc/?sv=2018-03-28&ss=b&srt=sco&sp=rwdlac&se=2025-04-23T21:51:53Z&st=2019-06-18T13:51:53Z&spr=https&sig= " --log-level "ERROR"  

### What problem was encountered?

Not able to run batch file.

### How can we reproduce the problem in the simplest way?

Save the above command switches in Bat file and run from windows 10.

**Comment by JohnRusk** [comment]
I think its because some characters in the URL are special to batch file processing. I think you need to escape the & characters by turning them into ^&, and double any % characters (so they become %%). See here https://ss64.com/nt/syntax-esc.html for CMD escaping rules.

**Comment by ashishmswipe** [comment]
@JohnRusk 👍 

I did the same as per your suggesting but still its not working. Can you please suggest what else I am missing.



azcopy sync "D:/uatazurefiles" "https://blobstorage.blob.core.windows.net/doc/?sv=2018-03-28^&ss=b^&srt=sco^&sp=rwdlac^&se=2025-04-23T21:51:53Z^&st=2019-06-18T13:51:53Z^&spr=https^&sig=xxxxxxxxxxxxxxxv9aOx1DgzpZBhYnY%%2Fijw7Q%%3D" --log-level "ERROR"


Also please suggest how can i skip entire blob scanning to destination because i saw by running above command in command prompt it's scanning entire destination blob files.

**Comment by zezha-msft** [comment]
Hi @ashishmswipe, please refer to [here](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide) for context on the sync command.

The original command works on the command-line, correct?

**Comment by ashishmswipe** [comment]
Hi @zezha-msft, yes the original command works on command line but it's very slow processing because I have around more than two tb size of blob container in destination side and it's scanning entire blob again n again I am not looking any skip switch command in link is there any workaround to stop scanning entire blob every time because I am getting images in my local folder freqently n I run batch job in every 3 minute

**Comment by JohnRusk** [comment]
We do not currently have options like /xn or /xo in AzCopy v10, I'm sorry. (Maybe one day we will, but they're not in the product at the moment).  

Workarounds:  If the changes on your source end are just additions of new files (i.e. existing files are _never_ modified) then you can try using 'azCopy copy' with --overwrite=false.  Make sure you test this on a test container first, before using it on your real one.  It checks only for existence, and does not check modified dates.

Another workround might be for you to find the list of files to transfer yourself (with some powershell script or something) and then pass a list of those files to AzCopy as describe here https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer 

Another option you might try is going back to AzCopy v8, and setting the /NC parameter to a low value. E.g. set it to 8. That might, maybe, avoid the hang problem.

**Comment by ashishmswipe** [comment]
Hi @johnrusk thanks for the response. Changes are my source end are just addition of new files existing files never modified. So what your suggestion is to use 'azcopy copy' instead of 'azcopy sync '. My old version command switchs are working fine but I have used /NC is to 10 and it's still working but sometimes all of sudden server or azcopy.exe gets hung so can you help me to understand that using 'azcopy copy' command  such kind of problem like server or azcopy.exe hung will not appear or still have to take any additional steps to save from hanging issue

**Comment by JohnRusk** [comment]
If you use version 10, I do not think it will hang. (We have not had any reports of version 10 hanging, as far as I can recall).

So try 'AzCopy copy' with version 10. There is still some performance risk with that, depending on how many files there are in your source directory tree, but it would be a good option to try.  If that doesn't work fast enough, then you can try the other workaround I suggested (finding the changed files yourself) but that's more work for you.

**Comment by ashishmswipe** [comment]
Thanks @johnrusk finding files by my self it's slow down our process because we are getting n numbers of images and pdf files very frequently and it's tedious task to list all virtual directory and subdirectories first then transfer because daily we are getting around 10gb images in our source files so it would be good to know that how to handle hanging situation with new one

**Comment by JohnRusk** [comment]
I see.  In that case, don't personally know of any answer that will work for you with the current versions of AzCopy v8 and v10.  

Maybe @zezha-msft will have some ideas, and may be able to reply tomorrow morning.  

If @zezha-msft doesn't have any AzCopy solutions either, then you might like to consider Fast Data Transfer (https://www.microsoft.com/en-us/garage/profiles/fast-data-transfer/ ).  It's an experimental tool, and now we are trying to encourage most users to move to AzCopy v10.  But.. it's very fast at finding files that have changed after the last time it ran.  You will need to use the RunDateLogFile command line parameter.  Search the documentation here  https://aka.ms/fast-data-transfer-instructions-pdf for RunDateLog file to see how it works, and read that documentation carefully.

Warning: Fast Data Transfer is harder to set than AzCopy. (Which is one reason why we encourage people to use AzCopy).

Tip: The documentation tells you that you need to run the Fast Data Transfer server in a VM in the cloud. That gives the fastest performance for writing to Storage, but it incurs the cost of running the VM.  If you want to avoid that cost, you can run the server on premises (maybe even on the same machine where you run the client). That's a very unusual configuration, but in your case you don't actually need Fast Data Transfer for maximal storage write performance, you just need it to find the changed files quickly (like AzCopy v8) and avoid hanging.  So running the server on-premises is probably fine for you.

**Comment by ashishmswipe** [comment]
@zezha-msft : Waiting for your response if you can shade some light on my problem.

**Comment by ashishmswipe** [comment]
@zezha-msft : please let me know if you have any idea how to deal with azcopy cp  command

**Comment by zezha-msft** [comment]
Hi @ashishmswipe, using V10's copy command in combination with the flag `--overwrite=false` would be my recommendation. Before scheduling each transfer, the tool would first check whether it exists at the destination container; if yes, it would skip that file; if not, it would copy the file.

I definitely don't think we've ever encountered a hanging issue in the new version (V10), so I recommend sticking to the new version.

**Comment by ashishmswipe** [comment]
Hi @zezha-msft , I am using following command switches but just problem is that getting error for existing blob at source location if you  can help that how to skip the errors for existing files at source location so that we are not getting unnecessary logs error.

azcopy cp D:/uatazurefiles/* https:// blobstorage.blob.core.windows.net/doc/?sv=2018-03-28^&ss=b^&srt=sco^&sp=rwdlac^&se=2025-04-23T21:51:53Z^&st=2019-06-18T13:51:53Z^&spr=https^&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxBhYnY%%2Fijw7Q%%3D --log-level ERROR --overwrite=false  --recursive=true


getting following errors in logs for existing file during upload if file already exist in blob:


Dst: https://blobstorage.blob.core.windows.net/doc/HAPP000495538/1012/HAPP00036551_ECS_1_1012_20180622_191141.jpg?se=2025-04-23t21%3A51%3A53z&sig=REDACTED&sp=rwdlac&spr=https&srt=sco&ss=b&st=2019-06-18t13%3A51%3A53z&sv=2018-03-28
2019/06/21 11:00:57 ERR: [P#0-T#5] UPLOADFAILED: d:///uatazurefiles/HAPP000495538/1044/HAPP00036551_CHQ_1_1044_20180622_190118.jpg : 000 : File already exists


Just let me know if any command switches is available to skip the existing file uploading errors.


I know I can do " --log-level None" but then how could I identify the actual error when received.

**Comment by JohnRusk** [comment]
I've checked the source code. This looks like a bug in our code, in which UPLOADFAILED is being output even when things are skipped. As you say, that shouldn't be tagged in the same way as a failure.  I'll log this as a defect.

**Comment by zezha-msft** [comment]
Hi @ashishmswipe, we will log the collision errors at another level in the future to make it clearer that they are expected, for the moment I'd suggest to skip these errors when you are trying to gather info from the log files (e.g. check if the error message contains `File already exists`; if yes, ignore them).

**Comment by ashishmswipe** [comment]
@zezha-msft :Alright fair enough we can live with this bug as of now but could be good if bug is fixed soon so that we can use latest exe

**Comment by zezha-msft** [comment]
@ashishmswipe Thanks! Sorry for the inconvenience.

**Comment by JohnRusk** [comment]
Version 10.2.1, released recently, fixes the problem with UPLOADFAILED.
