### ISSUE TITLE
403 Error when trying to upload file

### ISSUE THREAD

**Issue by geebd214** [Azure/azure-storage-azcopy#454]
### Which version of the AzCopy was used? 
10.1.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
.\azcopy.exe cp ".\test.txt" "https://slproc2.file.core.windows.net/proc/R%26D/BG/?"
### What problem was encountered?
See log file.  SAS removed.

### How can we reproduce the problem in the simplest way?
Trying to upload a file to a file share.  Downloading works.

### Have you found a mitigation/solution?
No

**Comment by geebd214** [comment]
I'm generating the SAS using the Azure Storage Explorer app

**Comment by geebd214** [comment]
Also seems to work ok with a blob storage SAS

**Comment by zezha-msft** [comment]
Hi @geebd214, thanks for reaching out!

I think @adreed-msft already fixed it [here](https://github.com/Azure/azure-storage-azcopy/pull/451).

**Comment by geebd214** [comment]
So it'll be fixed in the next release?

**Comment by adreed-msft** [comment]
Should be.
________________________________

**Comment by geebd214** [comment]
ok thanks.  as a work around I just stuck the file in a directory and
uploaded that with recursive.   appreciate the quick response.

**Comment by adreed-msft** [comment]
Hi, @geebd214, this should be fixed in AzCopy 10.2.x. Enjoy!
