### ISSUE TITLE
Problem installing azcopy version10

### ISSUE THREAD

**Issue by CWTham** [Azure/azure-storage-azcopy#456]
hi,
I am trying to use azcopy to upload data files to Azure storage. I have downloaded the Version 10 executable but somehow cannot install it.
It is a commmand line tool, but at the command prompt, typing "azcopy" does not seem to start the installation process.
Appreciate any advice please.

**Comment by JohnRusk** [comment]
Hi. There is no installation process ;-)  It's juts a zip file (or a tarball for the Linux version). Inside the zip file are just two things: a text file, and the program itself. You don't need to install it. You just run it.  Typing `azcopy --help` will show you help text.

Note that in PowerShell you probably have to write that as `.\azcopy --help` and in Linux use `./azcopy --help`.  (I.e. dot slash before the name, which is necessary in those environments unless you add it to your path).

Does that get it going for you?

**Comment by adreed-msft** [comment]
Should you want to "install" it, I'd recommend placing it inside `/usr/bin` on Linux, and on Windows, creating a custom bin folder and adding it to your PATH env var. At least that's what I do, personally.

**Comment by CWTham** [comment]
Thanks John and Adreed for your kind advice.
I tried the following command at command prompt:
azcopy cp "C:\....my source folder" "https://....the destination blob store with 
 SAS token" --recursive=true

But encountered long errors saying that - 'azcopy' is not recognized as an internal or external command,
operable program or batch file etc.

Is there anything wrong with the above command line?

**Comment by JohnRusk** [comment]
You need to either add it to your path, like Adele said, or else type this at the command prompt. (Note the .\ that I have added to your example , at the start. That is the only change.

```
.\azcopy cp "C:....my source folder" "https://....the destination blob store with
SAS token" --recursive=true
```

Also, you must run this from the directory that contains AzCopy.exe. E.g. if azcopy.exe is in `C:\mystuff\azcopy10.1.2windows` then your working directory must be `C:\mystuff\azcopy10.1.2windows` at the time you run it.

If you add it to the PATH, like Adele mentioned, then you can run it from any directory.

If this doesn't work for you, you can try using Azure Storage Explorer, since it provides a GUI (and contains AzCopy inside itself).

**Comment by CWTham** [comment]
hi John,
I could not get the command line to work despite using "./azcopy".
I have downloaded and installed Azure Storage Explorer now.
But at the connection screen, I am not sure what option I should choose.
I was given a URL which contains the SAS token, for use in accessing a blob container and uploading my local files into this container.
Which connection type should I use?
I tried "Use a SAS URI" and pasted the "https://xxx" string but encountered error "missing required parameter 'sp' in SAS token)"
I tried "Connect with Name and Key" and pasted the URL but encountered error "The key is not a valid base-64 value".

Appreciate if you could advise what else I could do.

**Comment by CWTham** [comment]
hi everyone,
I finally managed to upload my datafile to the Azure blob container (using the URL string given to me, which contains the SAS token).
I simply copied azcopy.exe to the root folder.
Then I launched Gitbash.
At the $ prompt, I typed:
.\azcopy cp "my data file path and filename" "azure blob container URL string with SAS token..."

Thanks everyone for the advice earlier  8-)

**Comment by JohnRusk** [comment]
Glad to hear its working for you.
