### ISSUE TITLE
Difference with blobxfer

### ISSUE THREAD

**Issue by BossensM** [Azure/azure-storage-azcopy#457]
I was wondering, Microsoft recently released V10 of AzCopy (https://github.com/Azure/azure-storage-azcopy). What exactly is the difference between blobxfer and AzCopy, and which one is the recommended one to use?

I am looking specifically for performance on uploading/downloading a lot of small files. According to this announcement, https://azure.microsoft.com/en-us/blog/azcopy-support-in-azure-storage-explorer-now-available-in-public-preview/, AzCopy seems to be very fast but it is not clear if Azure Storage Explorer was previously based on blobxfer.

**Comment by JohnRusk** [comment]
Storage Explorer was not previously based on blobxfer. It used its own implementation which (I presume) was in Javascript. 

Our goal is that AzCopy v10 should be the right tool to use in virtually all situations.  But small files are almost always the trickiest case for performance.  I don't actually know of comparative stats comparing small-file perf between AzCopy v10 and blobxfer. I expect they are challenging for _both_ tools. I would expect that blobxfer was probably faster than AvCopy v8, but I don't know which would be fastest on small files when comparing v10 and blobxfer. (V10 is a complete re-write).  It depends a lot of what you're talking about when you say "small files" - e.g. there can be a huge performance difference between 1 MB files vs 16 KB files.

By the way, if you're working at the "small" end of "small", I'd definitely suggest doing some tests with [Premium Block Blob Storage](https://azure.microsoft.com/en-us/blog/premium-block-blob-storage-a-new-level-of-performance/). In my experience, once you get down to small file sizes, the factors that most influence performance are:
(a) Standard vs Premium Storage and
(b) (for networks of about 500 Mbps and above) the ability of your local disk system to keep up.  Note that AzCopy v10 [will tell you](https://github.com/Azure/azure-storage-azcopy/wiki/Disk-and-service-constraint-indicators-in-AzCopy), when its running, if disk is your bottleneck.

To create a Premium Block Blob account, choose "Premium" as the performance level, and then choose "BlockBlobStorage" as the Account Kind.

cc @alfpark in case he has anything to add from the blobxfer perspective.

**Comment by JohnRusk** [comment]
I propose to close this issue now.  If we haven't fully answered it @BossensM please re-open it.

**Comment by et2010** [comment]
Azcopy does not support following a symbolic link to file. This is a deal-breaker for me. Before this was solved, I will keep using blobxfer instead of azcopy.
