### ISSUE TITLE
Trying to copy files from AWS S3 to Azure

### ISSUE THREAD

**Issue by michaelrp25** [Azure/azure-storage-azcopy#458]
### Which version of the AzCopy was used? 
10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows and Linux

### What command did you run?
first i login with 
./azcopy.exe login   then
 ./azcopy.exe cp "https://s3.amazonaws.com/proceso-cdn/media/2019/02" "https://efsprc.file.core.windows.net/prcvar/media"

### What problem was encountered?
failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

### How can we reproduce the problem in the simplest way?
Trying to execute the command

### Have you found a mitigation/solution?
no

**Comment by JohnRusk** [comment]
Copying from AWS to Azure Files is not supported yet in AzCopy v10.  As a workaround, you can use AzCopy v10 to copy from AWS to Blob Storage, then AzCopy v8 to copy from Blob Storage to Azure files.  We realize that 's not ideal, but its probably the best option right now.
