### ISSUE TITLE
Write Logs for all the commands - Failed ones as well.. 

### ISSUE THREAD

**Issue by yagohel23** [Azure/azure-storage-azcopy#463]
##### Note: The version is visible when running AzCopy without any argument
10.1.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
C:\Users\yagohel\Downloads\azcopy_windows_amd64_10.1.2>azcopy make "https://monitortest23.file.core.windows.net/test23"
please specify a valid share URL with account SAS
### What problem was encountered?
It seems we currently only log the commands which are valid and make it to the transfer engine. We dont write failed commands to the log files. 

For example, the above command and its failure does not get written in the log files. 

The same is the case for the "AzCopy login" command. We dont write this command to the log file even if the Login was successful. 

Can we log all the commands to the log file? 

### How can we reproduce the problem in the simplest way?
As shown above.
### Have you found a mitigation/solution?
No.

**Comment by zezha-msft** [comment]
Thanks @yagohel23! This item is being tracked in our backlog, and will be scheduled as soon as possible.

**Comment by JohnRusk** [comment]
This will be partially fixed in 10.3 - in that copy and sync jobs that find no files to transfer should now create a log. (But login etc will not)

**Comment by JasonYeMSFT** [comment]
I recently found that remove command for ADLS Gen2 doesn't write any log regardless of the result. This will make it hard to debug related issues.

**Comment by zezha-msft** [comment]
Closing for now. Logs are job-based, so commands like login do not have a job ID, thus their errors cannot go to a log.
