### ISSUE TITLE
AzCopy doesnt fail when we provide non-existent storage account in the command

### ISSUE THREAD

**Issue by yagohel23** [Azure/azure-storage-azcopy#464]
##### Note: The version is visible when running AzCopy without any argument
10.1.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy make "https://2304disks.file.core.windows.net/test23"
### What problem was encountered?
In the above command, I am specifying a storage account which does not exist. AzCopy does not throw an error and seems to be stuck in the retry loop. No errors are thrown in the command prompt. I do see the following getting logged in the event log multiple times - 

==> REQUEST/RESPONSE (Try=4/14.9575ms, OpTime=11.3849529s) -- REQUEST ERROR
   PUT https://2304disks.file.core.windows.net/test23?restype=share&timeout=901
   User-Agent: [AzCopy/10.1.2 Azure-Storage/0.4.1 (go1.10.8; Windows_NT)]
   X-Ms-Client-Request-Id: [15380a58-a38c-4f0c-7775-04b2a584fbf1]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/error.go:154
HTTP request failed

Put https://2304disks.file.core.windows.net/test23?restype=share&timeout=901: dial tcp: lookup 2304disks.file.core.windows.net: no such host

It will be great if we surface this error in the command prompt as well as the AzCopy Logs. 

This seems to be related to the ask here - https://github.com/Azure/azure-storage-azcopy/issues/86

### How can we reproduce the problem in the simplest way?
As shown above
### Have you found a mitigation/solution?
No

**Comment by zezha-msft** [comment]
Thanks @yagohel23 for this feedback! I've logged it to improve the user experience.

**Comment by tusharjn** [comment]
Hi, I encountered the same issue. 
I am using the latest version 10.4.3

**Comment by zezha-msft** [comment]
Non-existent storage account are surfaced as DNS errors, which are also used for temporary network issues, so we cannot distinguish them. 

The retries will ultimately all fail, and give back an error.
