### ISSUE TITLE
Azcopy does not work with V10 but works with V8

### ISSUE THREAD

**Issue by maheshward** [Azure/azure-storage-azcopy#477]
##### Note: The version is visible when running AzCopy without any argument
Does no work with V10 but works with V8

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Any command like login, cp etc..
### What problem was encountered?
Times out - with below error
INFO: Scanning...
INFO: trying to copy the source as container/directory/list of files

failed to perform copy command due to error: cannot start job due to error: cannot list blobs for download. Failed with
error -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/src/gith
ub.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/error.go:154
HTTP request failed
### Have you found a mitigation/solution?
No

**Comment by maheshward** [comment]
command used - azcopy cp  "https://##.blob.core.windows.net/?##SAS###" "C:\mytest"--recursive=true

**Comment by zezha-msft** [comment]
Hi @maheshward, thanks for reaching out!

Could you please show the full error?

This sounds familiar to me, do you have a proxy on your environment?

**Comment by maheshward** [comment]
Here is the full error
INFO: Scanning...
INFO: trying to copy the source as container/directory/list of files

failed to perform copy command due to error: cannot start job due to error: cannot list blobs for download. Failed with error -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/error.go:154
HTTP request failed

Get https://inspoceustostage01.blob.core.windows.net/test?comp=list&include=metadata&restype=container&se=2019-08-01T14%3A39%3A03Z&sig=8IAJHBIZ%2F%2FZMjKx2oo9xb347XUGq6qEc1X2zd%2F786cI%3D&sp=rwdlacup&spr=https%2Chttp&srt=sco&ss=bfqt&st=2019-07-02T06%3A39%3A03Z&sv=2018-03-28&timeout=901: dial tcp 52.239.154.132:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by maheshward** [comment]
Here is the full error

INFO: Scanning...
INFO: trying to copy the source as container/directory/list of files

failed to perform copy command due to error: cannot start job due to error: cannot list blobs for download. Failed with error -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/error.go:154
HTTP request failed

Get https://##blobname###.blob.core.windows.net/test?comp=list&include=metadata&restype=container&se=2019-08-01T14%3A39%3A03Z&sig=8IAJHBIZ%2F%2FZMjKx2oo9xb347XUGq6qEc1X2zd%2F786cI%3D&sp=rwdlacup&spr=https%2Chttp&srt=sco&ss=bfqt&st=2019-07-02T06%3A39%3A03Z&sv=2018-03-28&timeout=901: dial tcp 52.239.154.132:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by zezha-msft** [comment]
@maheshward thanks for sharing the error message!

Could you please give the latest version (v10.2.0) a try? We've added support for auto-detection of proxy from IE/Edge.

**Comment by JohnRusk** [comment]
@maheshward I don't think you've answered Ze's question about proxy servers. But it does look like maybe a proxy issue. Fortunately, version 10.2.1 was released this week, and it automatically finds the proxy in Windows.  Can you try version 10.2.1 please? https://aka.ms/downloadazcopy-v10-windows

**Comment by JohnRusk** [comment]
@maheshward I'm going to assume this is fixed now, because we haven't heard from you recently, and I'm going to close this issue. Please let us know if you are still having problems.
