### ISSUE TITLE
Question on sync command

### ISSUE THREAD

**Issue by mahilleb-msft** [Azure/azure-storage-azcopy#485]
Hi,

  the README states in relation to sync vs. copy:

>  If your goal is to simply move some files, then copy is definitely the right command, since it offers much better performance.

  Could somebody elaborate why sync would be much better performance? Is it because of enumerating files in the source/destination before starting any real work? For comparing, so far sync only depends on timestamps, which would be quick, too?

 Thanks, Mark

**Comment by adreed-msft** [comment]
Copy would be better suited to the task of moving individual files as it only enumerates the source (and checks filepaths against the destination, if you have --overwrite=false).

Sync is better suited to the task of duplicating a local file structure to a storage account, as it checks both destinations and only copies the latest files, optionally deleting files not present on the source at the destination. Futhermore, sync does NOT support wildcard characters.

As a result, I'd recommend using sync more or less to hold a backup of a directory, and I'd recommend using copy for transferring miscellaneous files.

**Comment by adreed-msft** [comment]
Does this adequately answer your question or is there more detail I can provide?

**Comment by mahilleb-msft** [comment]
Thanks @adreed-msft. So the difference in perf is about enumerating/checking the destination before starting to copy?

**Comment by adreed-msft** [comment]
That is correct.

**Comment by mahilleb-msft** [comment]
Thanks!!

**Comment by zezha-msft** [comment]
A wiki with more details is also available here: https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide
