### ISSUE TITLE
Cannot use cp to copy file from local env to blob

### ISSUE THREAD

**Issue by JeremyZhangSYD** [Azure/azure-storage-azcopy#491]
### Which version of the AzCopy was used? 
AzCopy 10.1.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server VM

### What command did you run?
Powershell
$azPath = "C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy"
cd $azPath
$Result = .\azcopy.exe cp “D:\blogArchiva\11” "https://storage accountname.blob.core.windows.net/logarchive(SAStoken)" --recursive=true
$Result 

### What problem was encountered?

 .\azcopy.exe : [2019/07/09 17:08:27][ERROR] The syntax of the command is incorrect. Error parsing the argument "cp": parameter name is required.
At line:38 char:11
+ $Result = .\azcopy.exe cp “D:\blogArchiva\11” "https://cv4auandosmesv ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([2019/07/09 17:...me is required.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

### Have you found a mitigation/solution?

I was tried to the key 
 
$azPath = "C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy"

    $StorageAccountKey = “keyvalue”
    $ContainerName = “logarchive”
    $SourceFolder = “D:\blogArchiva\folder”
    $DestURL = "https://$StorageAccountName.blob.core.windows.net/$ContainerName"
    $Result = .\AzCopy.exe /Source:$SourceFolder /Dest:$DestURL/$NEWFOLDER /BlobType:block /destkey:$StorageAccountKey /S /V:D:\blogArchiva\Logs\Log.txt
    $Result 

By using this, it successfully copied the files to the blob, but this solution is found under one of the articles and seems not up to date. I hope to know why cp is not been recognise as a argument. Thanks

**Comment by JohnRusk** [comment]
The path C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy is where AzCopy version 8 is installed.  Versions 8 and 10 are totally different products, with diferent command lines. In your example that worked, you used version 8, with the version 8 command line syntax.  In your example that failed, I think you are using the version 10 command line syntax, with the version 8 executable.

To use version 10, make sure you download it as shown by the instructions here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10 

The download is just a zip file. Unzip it, and the exe file that it contains _is_ AzCopy v10.  It's not an installer, it IS the program. So just put it in some directory that you choose (_not_ C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy) and run it.  This page has some tips on how to run it https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

**Comment by JeremyZhangSYD** [comment]
Thanks for your quick reply. It is quite clear and very helpful.
Thank you again.

**Comment by JohnRusk** [comment]
One question: do you think it would have helped if our documentation said that the exe in the zip file is not an installer, it just IS the program?
