### ISSUE TITLE
Is it possible to add upload bandwidth control parameter?

### ISSUE THREAD

**Issue by neutral-neutron** [Azure/azure-storage-azcopy#494]
### Which version of the AzCopy was used? 
AzCopy: 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
AzCopy related copy and sync commands had been used.

### What problem was encountered?
While trying to upload content from VM (in Azure DataCenter) to Storage Account (in same Data Center). Because of related connection will try to reuse internal connection, AzCopy default 32 concurrent connection multiple related internal connection bandwidth result the network bandwidth reached to around 300 MB/sec. But unfortunately, because of such a sudden and huge bandwidth consumption, related connection had been automatically and enforced interrupted.

### How can we reproduce the problem in the simplest way?
The simplest way is create VM and storage account within same data center. And then, try to upload several GB content.

### Have you found a mitigation/solution?
Currently, the workaround is set the environment variable "AZCOPY_CONCURRENCY_VALUE" to 4. Even with this settings, sometimes, the upload bandwidth will reach between 190 and 200 MB some time. And the upload speed is quite unstable, can changed between around 40 MB and 190 MB.

So, to control upload speed, it would be better to provide a parameter to control upload speed.

I think similar condition might happened to those company, because AzCopy try to utilize related network bandwidth, it might result IT treat this as wrong usage and break it. Upload speed control will be useful in such condition.

**Comment by JohnRusk** [comment]
We just added that parameter in version 10.2.1, but it's not on the documentation page yet.

Its called `--cap-mbps`. Its in mega bits per second. E.g --cap-mbps 800 will mean that AzCopy will not use more than 800 megabits per second, which equals 100 megabytes per second.
