### ISSUE TITLE
Trying to remove lease locked blobs seem to hang AzCopy 

### ISSUE THREAD

**Issue by Jaurocha** [Azure/azure-storage-azcopy#495]
##### Note: The version is visible when running AzCopy without any argument
10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
WindowsServer 2012R2

### What command did you run?
azcopy rm "https://---.blob.core.windows.net/dbdaily?<sas>" --recursive=true --include="*_backup_2019_06*.bak" --exclude="*_backup_2019_06_01*.bak">Log.txt

### What problem was encountered?
When a blob is locked by a lease AzCopy just hangs doing nothing.
This blocks the rest of the script to finish.

This is in our case caused by SQL server.
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/deleting-backup-blob-files-with-active-leases?view=sql-server-2017

### How can we reproduce the problem in the simplest way?
Try to remove a lease locked blob

### Have you found a mitigation/solution?
Breaking the lease and remove the file in MS Azure Storage Explorer

**Comment by zezha-msft** [comment]
Hi @Jaurocha, thanks for reaching out! And sorry for the inconvenience. 

I've located the bug [here](https://github.com/Azure/azure-storage-azcopy/blob/master/ste/xfer-deleteBlob.go#L58) and will make a fix shortly.

**Comment by zezha-msft** [comment]
This has been fixed in [10.3.0](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.3.0)!
