### ISSUE TITLE
Performance Degradation of v10 when compared to v6

### ISSUE THREAD

**Issue by jiteshkumargouthamchand** [Azure/azure-storage-azcopy#496]
### Have you found a mitigation/solution?No 

Also in addition would like to know what are the possible jobstatus of the AzCopy output ?

**Comment by zezha-msft** [comment]
Hi @jiteshkumargouthamchand, sync is doing additional listing operations on both the source and destination to figure out which files changed and need to be transferred. Comparing V10 sync to V6 copy or V10 copy is not very meaningful, since they are different in nature. V10 copy versus V6 copy would be a better comparison.

To accurately measure performance, V6 and V10 should not be run at the same time. They should run one after the other in repeated iterations. @JohnRusk can provide more tips on how to measure performance accurately if you'd like to.

Possible job status are [here](https://github.com/Azure/azure-storage-azcopy/blob/master/common/fe-ste-models.go#L274).

**Comment by jiteshkumargouthamchand** [comment]
Thanks for sharing possible job status. For our requirement we need to use sync function as in v6 we had to use /xo. . We are running between v6 and v10 at different times and not parallel.   But relatively we saw that times for running 12 hrs load of data between v6 and v10 there was degradation in performance so brought this up.

**Comment by zezha-msft** [comment]
@jiteshkumargouthamchand thanks for the explanation!

/XO and sync are not equivalent though. Sync not only replicates the source's contents to the destination, it also scans the destination to give the user the ability to remove extra files that no longer exist at source.

Here is a wiki about [sync](https://github.com/Azure/azure-storage-azcopy/wiki/Sync-command-guide). And here's the doc on [/XO](https://docs.microsoft.com/en-us/previous-versions/azure/storage/storage-use-azcopy#only-copy-data-that-doesnt-exist-in-the-destination).

Were the tests transferring the exact same files? Could you please let us know if the actual numbers? I can re-open this issue if appropriate.

**Comment by jiteshkumargouthamchand** [comment]
I have jobs running every 12 hrs. So the jobs more or less have same volume of files.   I see ton an average a job which is taking 2 hrs 30 mins in v6 is taking about over 3hrs 30 mins and this increase is almost in all of the jobs I  have. Please see if there can be any improvements doen in v10. FYI, we were been told with newer AzCopy performance would be better that is one reason for us to move to newer version.

**Comment by JohnRusk** [comment]
assigned to you Ze for visibility. (May be nothing more to do, but should consider the perf numbers above)

**Comment by JohnRusk** [comment]
Is this effectively a feature requested for an /XO -like feature in AzCopy v10?

**Comment by jiteshkumargouthamchand** [comment]
I am already using sync for /xo like requirement. But point was performance is better in v6(/xo) vs v10(sync)

**Comment by JohnRusk** [comment]
Thanks. 

Not to self (and rest of AzCopy team): we need to figure out of the perf difference is on the local side, or the cloud-side of sync.  My assumption above was that it was local side, and an xo-like featuer would help.  But I'm seriously doubting that assumption now.

**Comment by jiteshkumargouthamchand** [comment]
It seems that when we deployed AzCopy v10 the performance was really bad. With /xo the code takes only avg. 1hr 30 mins  whereas same is taking much longer in Prod approx.  5 hrs. So it seems it is comparing all of the objects in destination and not within the refined subfolders. Request to please look on this on prioirity.

**Comment by zezha-msft** [comment]
Hi @jiteshkumargouthamchand, thanks for the additional feedback.

Are the time measurements accurate?

As already clarified previously, sync and \XO are not exactly equivalent. Nevertheless, we'll look into adding \XO behavior in the future.

**Comment by jiteshkumargouthamchand** [comment]
yes it is accurate for the run we had so far. Will share wit you more results  as we run for next few runs

**Comment by jiteshkumargouthamchand** [comment]
@zezha-msft Hi Zane, When you get chance could you please let us know on above queries so that we can plan accordingly. Thnaks. The performance has been similar as to what was reported earlier with v10.

**Comment by zezha-msft** [comment]
Hi @jiteshkumargouthamchand, to clarify your scenario further, here is what I understood so far:
```
/src
  /sub-dirs...
  /sub-dirs...
```
On the destination side, are you uploading directly into a container? 
```
/container
  /sub-dirs..
  /sub-dirs..
  /unrelated-sub-dirs
  /other-unrelated-sub-dirs
```
As I've already explained, the sync command scans the whole destination to figure out which files exist at the destination but not the source, so if you target the entire container,  the performance would certainly be impacted.

However, if you were to target a specific virtual directory, like:
```
/container
  /virtual-dir
    /sub-dirs..
    /sub-dirs..
  /unrelated-sub-dirs
  /other-unrelated-sub-dirs
```
Then the tool will only scan container/virtual-dir, which would speed up the scanning process.

**Comment by jiteshkumargouthamchand** [comment]
As I mentioned we have 20*300 servers so if I have to do individual folder wise I will programmatically loop in an deach sub-folder will have one AzCopy so I will have to run AzCopy about 6000 times and in addition we have failure retry logic and summary logging based on AzCopy so that logic will not work for us. Do let us know what best can be done ? Also advice if v6 will be continue in support until this feature is available in newer AzCopy ? So we are thinking similar performance as /xo is required in our case

**Comment by zezha-msft** [comment]
@jiteshkumargouthamchand sorry, I don't really understand the context of your application thus it's hard to recommend a migration strategy. I was merely suggesting that targeting a virtual directory can isolate the scope of the destination scanning.

If V6 is fitting your needs well, I'd suggest to leverage it for the mean time until we add \XO support in V10.

**Comment by jiteshkumargouthamchand** [comment]
Thanks! Can we have an ETA of when /xo feature will be available in v10 ? Also our key is performance as we have been having performance issues from v6 to all higher versions since then so we hope with /xo same performance will be available as in v6 for our requriements of subfolders.

**Comment by zezha-msft** [comment]
@jiteshkumargouthamchand I'm confused. Is V6 performant enough for your scenario? Or not?

**Comment by jiteshkumargouthamchand** [comment]
v6 is enough. We were been told earlier that with future versions of AzCopy we would have improvements when compared with even v6. For now we are ok with Performance as that of v6.

**Comment by zezha-msft** [comment]
@jiteshkumargouthamchand sounds good. We'll provide a timeline once this work has been scheduled.

**Comment by zezha-msft** [comment]
Closing this since we'll be using #559 to track the feature request.

**Comment by jiteshkumargouthamchand** [comment]
@zezha-msft  As you know with recent MS Windows security patches we are having issues with AzCopy v6 and hence it is very important for us to have good performance with v10 and /xo feature. Due to Windows patch constraint we would want this issue to be prioritized.

**Comment by zezha-msft** [comment]
Hi @jiteshkumargouthamchand, thanks for following up, we have this feature planned for 10.5.0.

**Comment by jiteshkumargouthamchand** [comment]
Thanks Much. As mentioned earlier our key issue with Synch in v10.2 was with Performance and hopefully with 10.5.0 having /xo the performance will be relative to atleast what was in v6.1.  What is the ETA for 10.5.0.  I am checking this as we will need to plan accordingly and work with MS for getting a workaround with Windows patch which is causing v6.1 to fail.

**Comment by zezha-msft** [comment]
Hi @jiteshkumargouthamchand, I do not have a reliable ETA yet, since 10.4.0 (which is already full of urgent features as well) needs to come out first. We'll provide a high-confidence estimate as soon as it becomes available.

**Comment by jiteshkumargouthamchand** [comment]
@zezha-msft  @Salomon.Henriquez@microsoft.com - Any updates on performance improvement with the newer AzCopy versions. We need this urgently as AzCopy v6 is not working with latest MS patch.

**Comment by JohnRusk** [comment]
Is that this week's patch that you're talking about?  In what way does V6 fail with it? (Your info may help us to make prioritization decisions).

**Comment by jiteshkumargouthamchand** [comment]
No this has been since October's patch and infact we tried even on Dec's patch

**Comment by jiteshkumargouthamchand** [comment]
I have been in touch with Salomon Henriquez from MS and he has been tracking on this.

**Comment by JohnRusk** [comment]
Thanks for the info.

**Comment by JohnRusk** [comment]
PS. I'm in touch with Salomon.
