### ISSUE TITLE
show percentage of progress

### ISSUE THREAD

**Issue by powdermonkey007** [Azure/azure-storage-azcopy#500]
### Which platform are you using? (ex: Windows, Mac, Linux)
windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
copied file from azure to local storage
### What problem was encountered?
wish it would show percentage of file copied, just like the explorer does. it shows the throughput and updates it, so it would be nice to see a percentage process or x amount of data copied, so it's easier to gage when the copy will be done.

**Comment by JohnRusk** [comment]
It's on our list!

**Comment by JohnRusk** [comment]
Code is now in review: #525

**Comment by JohnRusk** [comment]
Version 10.3 is now released, with this feature included.
