### ISSUE TITLE
AzCopy to Azure Blob Storage as a page blob.

### ISSUE THREAD

**Issue by gerbowers** [Azure/azure-storage-azcopy#503]
Hi 

Version: 10.1.2

Sorry for posting here, but can not find any help with what I am trying to achieve. I need to upload database backups to Azure blob storage, and i have this working, however to restore a database directly from blob store it has to be a page blob. 

Can you let me know what FLAG and value should be set to upload as blob page.  

Gerry

**Comment by zezha-msft** [comment]
Hi @gerbowers, the flag to use is `--blob-type=PageBlob`. You can look at available flags by calling `./azcopy cp --help`.

**Comment by gerbowers** [comment]
Thanks for the help.
Ger
