### ISSUE TITLE
Running windows 386 azcopy on arm64 windows to download zip file from azure produces corrupted zip file

### ISSUE THREAD

**Issue by danielpl-msft** [Azure/azure-storage-azcopy#505]
### What problem was encountered?
File is downloaded fine but it is corrupt.  Windows explorer cannot open it, receives an error "data.zip is invalid"
 
### Have you found a mitigation/solution?
Writing a C# app using the windows azure blog storage API works but I'd rather use azcopy.  There is no option to be arm64 for arm64 windows, nor arm32 on arm64 windows, so I am building the 386 target and attempting to use it.  Another team member has successfully used the 386 (x86) version to upload text files to Azure but it seems it fails on downloading zip files.

**Comment by Virepri** [comment]
Have you tried compiling the latest version yourself? We had a bug in the past regarding downloading compressed data in AzCopy in the past.

**Comment by danielpl-msft** [comment]
I should be able to just do a git pull on master and pick up the latest version?

**Comment by adreed-msft** [comment]
Have you tried using the latest version of AzCopy (10.2.x)? I recall we had an issue in the past regarding downloading compressed data.

**Comment by adreed-msft** [comment]
Yes, you should just be able to do a git pull on master to grab the latest sources.

**Comment by danielpl-msft** [comment]
Thanks. I just did that and propped it to the arm64 machine. I verified that azcopy.exe (I renamed it) --version returns "azcopy version 10.2.1".  I then deleted the local copy of the destination file and re-ran the command. I see the same stderr spew and when I attempt to open the zip file (newly downloaded) it still reports as corrupt.  I can save off the stderr text and attach it. The .azcopy\<guid>.txt log file, I think has the azure access key/token marked as "REDACTED", so it should be safe to attach here?

**Comment by adreed-msft** [comment]
Logs may be helpful. Have you tried doing md5 hash checking? I'm not at a computer right now to check, but I believe `--check-md5` should do it.

**Comment by danielpl-msft** [comment]
[b3b6e928-df51-104e-7bc2-769ef40c4fda.log](https://github.com/Azure/azure-storage-azcopy/files/3397744/b3b6e928-df51-104e-7bc2-769ef40c4fda.log)
[stderr.txt](https://github.com/Azure/azure-storage-azcopy/files/3397745/stderr.txt)

Here is the log file and also the redirected stdout/stderr from the console to a text file.  I ran --check-md5 FailIfDifferent.  I don't know if that actually failed, not obvious from the log file at least to me. Does the zip file need to be uploaded with the --put-md5 in the first place so that it has an md5 hash to use for the download?  Another team member uploaded the zip file and I think just used the Azure portal interface to do that.

**Comment by adreed-msft** [comment]
I'm uncertain of whether that's the case or not. But it may be worth it to try.

I'll take a look at the uploaded logs once I get to work and finish up the first segment of the copy enumerator refactor. Thanks a ton for responding so quickly, by the way.

**Comment by danielpl-msft** [comment]
Thanks.

**Comment by danielpl-msft** [comment]
Well I looked at the stderr/stdout text file more closely and this doesn't look good at all:

0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, runtime: out of memory: cannot allocate 8388608-byte block (1334509568 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x9f61c1, 0xd)
	c:/go/src/runtime/panic.go:617 +0x64
runtime.largeAlloc(0x800000, 0x101, 0x1944bea0)
	c:/go/src/runtime/malloc.go:1057 +0x10f
runtime.mallocgc.func1()
	c:/go/src/runtime/malloc.go:950 +0x39
runtime.systemstack(0x0)
	c:/go/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
	c:/go/src/runtime/proc.go:1153

**Comment by danielpl-msft** [comment]
Potentially related to running 386 version of azcopy running in the x86 emulator on windows arm64?

**Comment by adreed-msft** [comment]
Out of curiosity, does Go not support arm64 windows?

**Comment by adreed-msft** [comment]
If it does,
`GOOS=windows
GOARCH=arm64
go build -o azcopy.exe`

Should build you a arm64 copy. This shouldn't _prevent_ the out of memory error, but it should make running AzCopy more tolerable.

**Comment by adreed-msft** [comment]
The other question is: How much memory does your system have? How many CPU cores?

**Comment by adreed-msft** [comment]
Looking into it, go doesn't support arm64 on Windows.

Is running under Linux an option?

**Comment by danielpl-msft** [comment]
It doesn't appear to support arm64 on windows:
set GOARCH=arm64

go mod vendor
cmd/go: unsupported GOOS/GOARCH pair windows/arm64


go build -o azcopy.exe
cmd/go: unsupported GOOS/GOARCH pair windows/arm64

nor does it support windows/arm32. 

As for the physical machine, it reports as having 95.8 gb of memory(an odd number) and 46 cores, so it is not a low end device. It is basically a server class arm64 machine.

We are trying to stand up our automation and testing Microsoft Edge (arm64 version, chomium based) on arm64 windows) currently, and not looking at linux yet.

**Comment by danielpl-msft** [comment]
I suspect, since golang is Google's, they are more focused on chrome books and thus linux and arm64 from there, not so much for windows on arm64.

**Comment by adreed-msft** [comment]
We try to aim for around 0.5GB per core. Is it possible your emulator isn't allocating enough RAM?

If this is the case, there is a more underlying issue that you may have just identified: High core counts and low memory.

**Comment by danielpl-msft** [comment]
I would suspect x86/386 would have the same 2gb memory limit that all x86 has.  But that should affect hardware x86 as well as emulated x86.  That error looked to indicate it failed attempting to allocate 8 Meg's with 1.3 gb in use.  I would think virtual memory would fault in the needed memory but I don't know how you handle memory nor how golang does under the covers.

**Comment by JohnRusk** [comment]
Sounds like we need to change our Ram cap on 32 bit. (I'm already scheduled to look at ram caps this month) Meantime, if you use CPU affinity to tell it to use only 1 CPU it might work. Let me know if you'd like a sample command line to do that

**Comment by danielpl-msft** [comment]
Also, I've not tested the x86 (386) build in a pure x86 windows machine but I ran it on my dev box which is amd64 windows10 (19h1) and it fails in the same way as it does on arm64.  I want to try it on a pure x86 machine (probably virtual as I don't have an extra physical machine that is pure x86) just to see it if it only an x86 issue and not an x86 emulation on arm64 issue.

**Comment by danielpl-msft** [comment]
Yes, I would very much like to try a sample command to use only 1 cpu.  Using the compat property on the exe within windows itself to set it to 1 cpu doesn't seem to mitigate it.  Is there a command line flag to azcopy to have it restrict itself to one cpu?

**Comment by danielpl-msft** [comment]
Is it AZCOPY_CONCURRENCY_VALUE=1 ?

**Comment by danielpl-msft** [comment]
Yea, that worked!  It clearly feels slower but the fact that it worked is a big improvement

**Comment by JohnRusk** [comment]
Hi, actually, we can probably do better than that. Two points:

No, the CPU affinity thing is different from the environment variable. Best to clear the env var (put it back to "")

After my earlier reply, I realised something: you are building from source.  So why not just change the source, so that it allocates less RAM? I'll look up the line you'll need to change. One moment...

**Comment by danielpl-msft** [comment]
Thanks

**Comment by danielpl-msft** [comment]
ste\JobsAdmin.go -> gbToUse?

**Comment by JohnRusk** [comment]
OK. Here are the details of the code to change. If you change this, you will not need to mess with CPU affinity, and you should leave AZCOPY_CONCURRENCY_VALUE unset (blank).

The file to change is ste/JobsAdmin.go at line 137.

Currently it says
```
gbToUse := float32(runtime.NumCPU()) * gbToUsePerCpu
```

change it to this, and you'll cap the memory used by AzCopy's buffers to 0.5 GB, which will hopefully leave enough for other AzCopy overhead. (If it doesn't, change the 1 in this new line to an 0.5). Here's the new line:

```
gbToUse := float32(1) * gbToUsePerCpu
```

Please let us know how that goes for you.

(As for how you manage the source code, having made a change, I'll leave that up to you.  Probably the easiest way its to clone the git repository and make your changes in your local clone)

**Comment by danielpl-msft** [comment]
Great.  Thanks!

**Comment by danielpl-msft** [comment]
I've cloned the repo, I'll probably make my own local branch and made the change there.  I presume you've got programatic blocks to prevent accidental pushes to master

**Comment by JohnRusk** [comment]
> presume you've got programatic blocks to prevent accidental pushes to master

@zezha-msft Have we got those?  I also presume we do, but am not familiar with the setup.

**Comment by danielpl-msft** [comment]
Yes, that works!  I had to remove the entry in the import the referred to 'runtime' but otherwise the hack is exactly as you indicated. This particular arm64 device is probably somewhat of an oddity.  It has 46 cpus and 96GB of ram, so not like a typical laptop sized arm64 device, and that may be what is causing the memory allocation issue.

Thanks.

**Comment by JohnRusk** [comment]
Great!  Thanks for confirming the outcome. I'm going to close this issue now. (We already have low-memory scenarios in our planning, so no need to keep this open too).

**Comment by danielpl-msft** [comment]
Thanks!

**Comment by zezha-msft** [comment]
@JohnRusk yes only maintainers have write access to the repo.
