### ISSUE TITLE
Azcopy issue -failed to perform copy command due to error: get cached token failed, failed to unmarshal token during loading token, json: cannot unmarshal number into Go struct field OAuthTokenInfo.expires_in of type string

### ISSUE THREAD

**Issue by srini99mkl** [Azure/azure-storage-azcopy#506]
### Which version of the AzCopy was used? 
10.2.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy cp sourcefile destination
### What problem was encountered?
failed to perform copy command due to error: get cached token failed, failed to unmarshal token during loading token, json: cannot unmarshal number into Go struct field OAuthTokenInfo.expires_in of type string

**Comment by adreed-msft** [comment]
`azcopy logout`
`azcopy login`

Our OAuth config changed a bit between versions.

**Comment by adreed-msft** [comment]
Though, it may be beneficial for us to go ahead and ask the user to relog in the event of a failed cached token obtain. I'll leave this issue open and create a PBI for it.

**Comment by srini99mkl** [comment]
I did logout and login, but I still get the same error.


NFO: Scanning...
INFO: Using OAuth token for authentication.

failed to perform copy command due to error: get cached token failed, failed to unmarshal token during loading token, json: cannot unmarshal number into Go struct field OAuthTokenInfo.expires_in of type stri
ng


Thanks,
Srini Arumilli
Markel - IT
Data Services
4501 Highwoods Parkway, Glen Allen, VA 23060
Direct: (804) 525-7041
www.markelcorp.com<http://www.markelcorp.com/>

**Comment by JohnRusk** [comment]
Which version on Windows and, for completeness and because I don't know what could cause the issue, what regional settings are you running with: i.e. under Settings -> Time and Language -> Region (in recent versions of windows) you'll see both a "region" and a "region format". They _shouldn't_ matter, but given the nature of your error, we'll investigate further if you happen to have an unusual setting there.

**Comment by srini99mkl** [comment]
My issue has been resolved, I found out the resolution. Please close this ticket.

Thanks,
Srini Arumilli
Markel - IT
Data Services
4501 Highwoods Parkway, Glen Allen, VA 23060
Direct: (804) 525-7041
www.markelcorp.com<http://www.markelcorp.com/>

**Comment by zezha-msft** [comment]
Hi @srini99mkl could you please share the resolution as well? In case someone else runs into a similar issue. 😄

**Comment by srini99mkl** [comment]
I had run Azcopy login command from Azcopy folder where Azcopy exists.

Thanks,
Srini Arumilli
Markel - IT
Data Services
4501 Highwoods Parkway, Glen Allen, VA 23060
Direct: (804) 525-7041
www.markelcorp.com<http://www.markelcorp.com/>

**Comment by zezha-msft** [comment]
Hi @srini99mkl, to clarify, are you saying that before you were invoking the tool using an absolute path like C://..../..../..../azcopy.exe, and now you are doing ./azcopy.exe?

I don't see how that changes anything, @adreed-msft could you please confirm?
