### ISSUE TITLE
Azcopy login, failed to get keyring during saving token, operation not permitted

### ISSUE THREAD

**Issue by goa5t** [Azure/azure-storage-azcopy#515]
### Which version of the AzCopy was used? 

v 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux (Amazon Linux)

### What command did you run?

$ az login --service-principal --tenant <tenant_id> --username <SPN_name>

### What problem was encountered?

Failed to perform login command: 
failed to get keyring during saving token, operation not permitted

### How can we reproduce the problem in the simplest way?

I'll start off by saying this is probably not even an issue with azcopy, but I was hoping for guidance/confirmation that I was in the right direction.

I'm attempting to run 'az copy login' in an AWS Lambda function. Worth noting that in Lambda, /tmp/ is the only writeable directory; everything else is read-only (hence why I set the below envvars as such).
Things I have done as workarounds:

- Set the following environment variables: AZCOPY_SPA_CLIENT_SECRET=<secret>, HOME=/tmp/, AZCOPY_LOG_LOCATION=/tmp/
- Logging in as a service principal, which works on an EC2 Amazon Linux VM.

I'm not sure how to reproduce this in an easy way. I'm mostly asking for guidance in identifying how azcopy is using keyctl. I've identified the error message from this file:

https://github.com/Azure/azure-storage-azcopy/blob/master/common/credCache_linux.go

Line 162

From my understanding, azcopy is using this project (https://github.com/jsipprell/keyctl) as an interface for the Linux key management system, is that correct?

If so, how do I get a more verbose error from that call?

### Have you found a mitigation/solution?

Not yet

**Comment by goa5t** [comment]
After looking into this more, it's definitely a keyctl issue.

I'll close this issue, but if anyone has any advice regarding keyctl, I would appreciate it! Thanks

**Comment by hdubey** [comment]
I am getting this error as well. How to resolve it?

**Comment by JohnRusk** [comment]
@hdubey I'm not sure whether it would help, but you could try switching to a named session keyring, as described here: https://github.com/Azure/azure-storage-azcopy/issues/452#issuecomment-503812803 .  _Maybe_ that might help.  If it doesn't help, then I'm sorry, we don't currently know of a solution to your issue.

**Comment by sambanks** [comment]
For posterity. I had the same issue in codebuild and had to run it in privileged mode to access the keyring. I would guess that would be why it doesn't work in lambda.
