### ISSUE TITLE
Azcopy v10 is terribly slow in comparison to v7

### ISSUE THREAD

**Issue by schybbkoh** [Azure/azure-storage-azcopy#520]
### Which version of the AzCopy was used? 
`AzCopy 10.1.2` 
`azcopy 7.2.0-netcore`

### Which platform are you using? (ex: Windows, Mac, Linux)
`Ubuntu 16.04.5 LTS`

### What command did you run?
`azcopy --source /var/lib/mysql --destination "blobstorage/container" --dest-key XXX --recursive` for v7
`azcopy cp /var/lib/mysql blobstorage/container?sastoken --recursive 1>/dev/null` for v10

### What problem was encountered?
Azcopy v10 is terribly slow. For the exact same environment the task of copying /var/lib/mysql (about 1TB, 750 files) to blob storage `v7` takes about an hour to finish, while `v10` takes 7 hours (!).

### Have you found a mitigation/solution?
Revert to `azcopy v7`.

**Comment by JohnRusk** [comment]
Hi

Thanks for this. You're the first person to report a difference like this, and we don't see it in our own test environments, so we'd definitely like to learn more about it.

It would be extremely useful if you could extract the "PERF" lines from the v10 log file (see final section of this page) and email them to me. My email address is in my profile.

It would also be very helpful to know the number of CPU s on your test machine, and the amount of Ram.

**Comment by schybbkoh** [comment]
The VM is `Standard DS14 v2 (16 vcpus, 112 GiB memory)`. 
Which page is *this* page? I guess you maybe forgot to include a link? :>

**Comment by JohnRusk** [comment]
Oops, indeed I did: https://github.com/Azure/azure-storage-azcopy/wiki/Disk-and-service-constraint-indicators-in-AzCopy

**Comment by JohnRusk** [comment]
BTW, the issue sounds a bit like this: https://github.com/Azure/azure-storage-azcopy/wiki/Performance:-large-files-on-Linux , but not exactly the same.  If you can send me the PERF lines extracted from the log (as per missing instructions link that I have now posted in my previous reply) I'll look into it more.

**Comment by schybbkoh** [comment]
I've done some extensive testing while reverting to azcopy v7 on my production instances and on almost all of them azcopy v7 was MUCH faster when copying data from disk to remote storage. 
The commands used were identical as previously mentioned (`azcopy --source /var/lib/mysql --destination "blobstorage/container" --dest-key XXX --recursive` and `azcopy cp /var/lib/mysql blobstorage/container?sastoken --recursive`).
I should also mention that all the azcopy commands were used together with `ionice -c 3`, so the whole command would look like this `ionice -c 3 azcopy ...`. 
Sadly, my backup script deletes azcopy temp files, so there are no PERF logs left from these tests. I will, however, fetch a test environment to try and replicate the issue and to something to send you.

**instance 1**

```
Ubuntu 16.04.5 LTS
Standard DS14 v2 (16 vcpus, 112 GiB memory), SSD RAID10 (8TB effective)
1TB of data, 700 files
450 minutes (azcopy v10) --> 70 minutes (azcopy v7)
```

**instance 2**

```
Ubuntu 16.04.5 LTS
Standard D16s v3 (16 vcpus, 64 GiB memory), SSD 2TB
370GB of data, 550 files
170 minutes (azcopy v10) --> 100 minutes (azcopy v7)
```

**instance 3**

```
Ubuntu 16.04.6 LTS
Standard D16s v3 (16 vcpus, 64 GiB memory), SSD 1TB
550GB of data, 789233 files
50 minutes (azcopy v10) --> 70 minutes (azcopy v7)
```

**instance 4**

```
Ubuntu 16.04.5 LTS
Standard DS3 v2 (4 vcpus, 14 GiB memory), SSD 2TB
200GB of data, 2635 files
90 minutes (azcopy v10) --> 20 minutes (azcopy v7)
```

**instance 5**

```
Ubuntu 16.04.5 LTS
Standard D4s v3 (4 vcpus, 16 GiB memory), SSD 2TB
250GB of data, 2733 files
100 minutes (azcopy v10) --> 50 minutes (azcopy v7)
```

I also tested whether there is a disrepancy between azcopy v7 and v10 when downloading data FROM remote storage. And the answer is no, there is none.
The tests were run without `ionice` on one machine - at first it was a rather small VM with small disk (low IOPS), then I upgraded it and re-tested. The files copied are the exact ones that were previously uploaded to remote storage by `instance 5`.

**test instance 1, run 1**

```
Ubuntu 16.04.6 LTS
Standard D2s v3 (2 vcpus, 8 GiB memory), SSD 1TB
250GB of data, 2733 files
90 minutes (azcopy v7) ---> 90 minutes (azcopy v10)
```

**test instance 1, run 2**

```
Ubuntu 16.04.6 LTS
Standard F4s (4 vcpus, 8 GiB memory), SSD 4TB
250GB of data, 2733 files
25 minutes (azcopy v7) ---> 25 minutes (azcopy v10)
```

**Comment by JohnRusk** [comment]
It looks like performance is the same when `ionice` is not used. Is that right?

**Comment by JohnRusk** [comment]
Ie it looks like both tools perform the same as each other, when `ionice` isn't there. Both at 25 mins in the last test. Is that right?

**Comment by schybbkoh** [comment]
Performance seem to be somewhat similar both with and without ionice when testing upload (see above) and download (see below). Sadly, the results from test instance are not very consistent with what I'm experiencing on my production instances. I guess the case is that the test VM is doing literally nothing besides being tested, while production instances are under constant stress (although backups are being run during night when the load is relatively small).
Considering that I can't really replicate the issue on my test instance I think that sending you the PERF file is unnecessary?

**test instance 1, run 3** no ionice, download test

```
Ubuntu 16.04.6 LTS
Standard F4s (4 vcpus, 8 GiB memory), SSD 4TB
1TB of data, 700 files
167 minutes (azcopy v7) ---> 150 minutes (azcopy v10)
```

**test instance 1, run 4** ionice, download test

```
Ubuntu 16.04.6 LTS
Standard F4s (4 vcpus, 8 GiB memory), SSD 4TB
1TB of data, 700 files
166 minutes (azcopy v7) ---> 148 minutes (azcopy v10)
```

The obvious thought here is that the `ionice` is the culprit of the issue reported, however what puzzles me is that `acopy v7` + `ionice` runs much faster than `azcopy v10` + `ionice` which is unexpected.
And `ionice` needs to be used, if not, azcopy "eats up" all IOPS and leaves nothing for other processes (tried `AZCOPY_CONCURRENCY_VALUE=1`, didn't work well enough).

**Comment by JohnRusk** [comment]
Yeah, probably not worth sending me the PERF log lines.

Re `ionice` It wouldn't surprise me if v7 and v10 responded very differently to that. They have very different architectures and very different runtimes (.net for one and Go for the other). I suspect that while you're setting the _same_ `ionice` parameter on both versions, it has a _different _ effect on them. 

Re stopping AzCopy eating up all the IOPS. I'm curious to know, is this about IOPS on the machine where AzCopy is running, or on the Blob Storage account that's its accessing?

Also, I think we can offer you a better solution to that problem. Instead of setting `ionice` or `AZCOPY_CONCURRENCY_VALUE`, version 10.2.1 introduced a command line parameter called `cap-mbps`. It's a much better way than using AZCOPY_CONCURRENCY_VALUE because it provides direct and exact control. Eg `--cap-mbps 500` tells AzCopy to never use more than 500 M bits/sec of network bandwidth. That might provide a good solution to your problem. 

I'd suggest you calculate the Mbps throughput that you are seeing with v7, when using `ionice` then set that as your `cap-mbps` value for v10, and run v10 with that parameter but without `ionice`. I expect both tools will perform the same in that case. 

Thanks for reporting this, and discussing it to help us understand your situation. Please let me know if cap-mbps works as a solution for you.

**Comment by schybbkoh** [comment]
`I'm curious to know, is this about IOPS on the machine where AzCopy is running`
It's about the machine where azcopy is running. The thing is that azcopy (especially v10) seems to be rather IOPS-hungry, but so are database-processes running on the machines mentioned. So the effect would be some miliseconds wasted on these two processes unnecessarily fighting for disk access, that is unless you settle them down manually - for example by using `iops`.

Thanks for the tip on `cap-mbps`. For now, however, I will be unable to give it a go on my production environment, as I had to revert to `azcopy v7` not only because of the "terribly slow" issue reported here, but also (mainly) because of crashes possibly caused by mem-leaks (see https://github.com/Azure/azure-storage-azcopy/issues/498).

**Comment by JohnRusk** [comment]
Thanks for the update. Based on our discussion here, I believe that the cap-mbps option would solve this problem if/when you move to v10 on the future. There are also a couple of new environment variables coming in v10. 3 which will give an even faster - acting iops reduction. (theyll affect iops almost instantly, whereas cap-mbps only affects iops after the internal caches fill). The two new settings let you reduce the number of files read in parallel, and the size of the memory buffer/cache in azcopy. Using them with cap-mbps should work very well. On that basis, I'm going to close this issue now.
