### ISSUE TITLE
azcopy copy fails inside singularity container

### ISSUE THREAD

**Issue by tsnowlan** [Azure/azure-storage-azcopy#521]
We use [singularity](https://github.com/sylabs/singularity) to standardize software versions and ensure the environment is the same where ever it is run.

The `az` utility works fine and some aspects of `azcopy` do (`jobs list`, `jobs show`, `sync`), but `copy` fails. 

### Which version of the AzCopy was used? 
10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
linux. RHEL 7.6 host OS, ubuntu 18.04 container OS

### What command did you run?
```
singularity exec -B /local/path:/local_path az.simg azcopy copy /local_path https://acct-name.blob.core.windows.net:443/container-name --recursive
```

### What problem was encountered?
Upload fails, with logs stating:
```
RESPONSE Status: 404 The specified resource does not exist.
```

### How can we reproduce the problem in the simplest way?
```bash
# Using singularity v2.6.1
# Singularity is from this gist: https://gist.github.com/tsnowlan/f00860e87a309b8b6cb60b49ca0da352
sudo singularity build az.simg Singularity

# az login may or may not be needed?
singularity exec az.simg az login
singularity exec az.simg azcopy login
singularity exec -B /some/local/path:/image/path az.simg azcopy /image/path https://acct-name.blob.core.windows.net:443/container-name --recursive
```

### Have you found a mitigation/solution?
Using `azcopy sync` instead works
```
singularity exec -B /local/path:/local_path az.simg azcopy sync /local_path https://acct-name.blob.core.windows.net:443/container-name --recursive
```

Using `azcopy sync` is probably better anyway from an efficiency point of view, but I spent a while trying to debug what looked like a permission issue before I thought about trying `sync`.

**Comment by JohnRusk** [comment]
There's no known reason why that would happen. Does your `copy` command work if you run it without singularity? (after manually running login)

**Comment by JohnRusk** [comment]
FYI AzCopy login uses the session keyring. Maybe there's an issue with that not being preserved from your login command to your copy command. If you replace your copy command with `keyctl show` and look at the output you should see an AzCopy-related key name that was created by the login process. If you don't, then that will be the problem.

**Comment by tsnowlan** [comment]
I was thinking it might be something to do with the keyring. The image I'm using doesn't have keyctl on it, so will rebuild and check.

It's curious that `azcopy sync` works while `azcopy copy` does not though. Do they use a different authorization method?

**Comment by tsnowlan** [comment]
Looks like the keyring is being preserved okay:

```
$ singularity exec $AZ keyctl show
Session Keyring
  15397392 --alswrv    991   986  keyring: _ses
 952196656 --alswrv    991 65534   \_ keyring: _uid.991
 793819629 --alswrv    991   986   \_ user: AzCopyOAuthTokenCache
```

**Comment by JohnRusk** [comment]
OK, that suggests is probably not a keyctl problem. 

I'm also puzzled as to why you saw different results with sync and copy. They use the same auth mechanism.  

Is there any chance it might be a timing thing?  It can take 5 mins for RBAC role assignments (e.g. granting Storage Blob Data Contributor) to propagate fully within Azure Storage and take effect.  So, if you granted that role to an account, then immediately tested `copy` with that account, it could fail. Then, if you gave up, and a few minutes later tried `sync` you might find that sync worked just because it was more than 5 mins since the granting of the role.

**Comment by tsnowlan** [comment]
After opening a new ssh connection and keyring session, the `copy` action is working as expected. Oddly, it still wasn't working before that. I tested it afterwards on a different server and it worked right off the bat.

Is it possible that creds saved before the role propagated fully could cause something like this? It does seem to be resolved now at least.

**Comment by JohnRusk** [comment]
Good question, re a login result saved before the role propagated. I don't know the answer!

I propose to close this issue now, but please comment if the issue ever happens again and we'll reopoen this (or a new issue)
