### ISSUE TITLE
32-bit public release

### ISSUE THREAD

**Issue by JohnRusk** [Azure/azure-storage-azcopy#526]
Currently, the only public 32-bit AzCopy release is v7. That's way too old. We need to release 32 bit version of 10 (for at least all platforms where v7 runs)

**Comment by adreed-msft** [comment]
IIRC, this is what the 32-bit testing we did was for, yes?

**Comment by JohnRusk** [comment]
I think so.

**Comment by JohnRusk** [comment]
Done. Version 10.3 is out with a 32-bit Windows build.
