### ISSUE TITLE
Passing in bad formed SAS doesn't error out quickly.

### ISSUE THREAD

**Issue by klaaslanghout** [Azure/azure-storage-azcopy#53]
Command:  azcopy cp "source" "destination?SAS" --recursive=true
Where SAS was incorrect.
Command enumerated local files and then starting increasing failure after failure. If the SAS key isn't correct on the first PUT, why continue to process the list ?

**Comment by zezha-msft** [comment]
Hi @klaaslanghout, thanks for reporting this issue!

You have a really good point, we'll look into improving the user experience for this scenario.

**Comment by zezha-msft** [comment]
This has been fixed.
