### ISSUE TITLE
missing silent or quite mode

### ISSUE THREAD

**Issue by slomo** [Azure/azure-storage-azcopy#534]
### Which version of the AzCopy was used? 

azcopy version 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

I am running azcopy as part of a cronjob to upload files nightly onto blob storage.

### What problem was encountered?

As usual for cronjobs I would like the command to not output anything unless there was an error encountered. So what I would like to have is an option to say --silent or --quite which only outputs to stderr if an upload error was encountered-

### Have you found a mitigation/solution?

My solution is so far, just to pipe the output to `/dev/null` and monitor externally that the upload has happend.

**Comment by JohnRusk** [comment]
Your workaround makes sense.  You might like to check the process's exit code, as a way of detecting success or failure.

**Comment by eriksw** [comment]
The workaround of redirecting stdout is not useful for the case of running azcopy in a shell script, where you might want there to be no output in the success case, but you do want there to be output in the event of an error.

(Should it be a bug that error messages are going to stdout instead of stderr?)

**Comment by JohnRusk** [comment]
>(Should it be a bug that error messages are going to stdout instead of stderr?)

I've added an entry to our backlog to investigate.

**Comment by ninallam** [comment]
Hi I'm from Azure Pipelines team, working to upgrade Azure File Copy task to work with Azcopy V10. In azcopy v8 there was an option /Y to suppress confirmation prompts. How can this be done in azcopy V10. Since the copy in happens in the background for Azure File Copy task, we need this feature.

**Comment by JohnRusk** [comment]
If you use `Azcopy copy` there are (almost) no prompts (so no need for a /Y mode).  The only prompt you can get is if you cancel a job before it's finished scanning the source. Then you get a prompt about the job not being resumable if you cancel now. @zezha-msft, is that prompt somehow surpressed in automation scenarios? 

If you use `AzCopy sync` there can be prompts for deletion, and there is a flag to control when those prompts appear.

**Comment by zezha-msft** [comment]
Hi @ninallam, the cancel prompt cannot be silenced right now, but does the Azure File Copy task ever get cancelled?

**Comment by ninallam** [comment]
Hi @zezha-msft , potentially the task can be cancelled. There is an option for the user to cancel the stage at any time. This would send a request to the agent to cancel the task in progress. Is there a workaround for suppressing this prompt?

**Comment by zezha-msft** [comment]
Hi @ninallam, you could preemptively send in a 'y' to the STDIN to avoid the prompt being blocked. We can add a flag to silence this behavior.

**Comment by Rahul-CTS** [comment]
Hi is ther an update on this, I also need it for scripts in a linux VM, wher I am uploading files to blob via azcopy using shell script.

**Comment by mohsha-msft** [comment]
Hey @Rahul-CTS ,

Thanks for reaching out!
We've picked up this task and will try to release it in AzCopy `10.15.0` or `10.16.0`.

**Comment by nakulkar-msft** [comment]
Added in 10.15.0

**Comment by sbonds** [comment]
The option appears to be "--output-level quiet", for those looking to use the new feature.
