### ISSUE TITLE
Downloading and installing binaries is a annoying

### ISSUE THREAD

**Issue by slomo** [Azure/azure-storage-azcopy#535]
### Which version of the AzCopy was used? 

Any 10.x version

### Which platform are you using? (ex: Windows, Mac, Linux)

Any

### What command did you run?

In order to install the binary, I have to download, validate checksum of tar and untar the only the binary untar (avoiding to untar the legal notice).

### What problem was encountered?

For other go binaries I am used to directly download the binary, making it for instance in ansible a one step process. Probably you need the third party notice for some legal reason, but please reconsider this could be so much better if you would offer directly the binary. 

Also while I am at it making whishes. If you could provide a more stable download url where between versions on the version in the url it self changes. In addition right now there is no direct download url for a specific version. Instead I have to get it from a redirect, where it is unclear whether it produces a stable url. If this utility is not only intended for to be of use for user but also is targeted at scripting purposes, it should be easy to install in an automated way and allow to easily pin to a certain version.

### Have you found a mitigation/solution?

Just write some wrapping scripts that unpack the binary and assume that the download url is stable.

**Comment by zezha-msft** [comment]
Hi @slomo, thanks for your feedbacks!

Here is the [doc](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#use-azcopy-in-a-script) on how to pin to a specific version of the tool, and extract it easily. We have to include the notice file unfortunately.
