### ISSUE TITLE
Reading from STDIN doesn't work on Korn shell

### ISSUE THREAD

**Issue by ymondrow** [Azure/azure-storage-azcopy#537]
##### Note: The version is visible when running AzCopy without any argument

We are using the latest version, 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux/GNU, Red Hat

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

cat test1.txt | azcopy cp "https://prhpowerbidev.blob.core.windows.net/test1/test1.txt?[SAS]"

### What problem was encountered?

When piping in data from STDIN as in the command above, it works when using the Bash shell but not when using the Korn shell.  On the Korn shell, it ignores what's being piped in via STDIN and thinks you're trying to download "test1.txt" rather than uploading it.

### How can we reproduce the problem in the simplest way?

On a Linux environment which has the Korn shell installed, switch to Korn by typing "ksh".  Then, run command similar to above where you upload data via piping from STDIN.  It will think you're trying to download rather than upload, and will not upload the new data. 

### Have you found a mitigation/solution?

Use Bash shell.  But as most of our scripts use the Korn shell, it would be great if this can be fixed to work on the Korn as well.

**Comment by adreed-msft** [comment]
I don't know much about Korn shell, does it handle stdin in a different way than usual?

**Comment by ymondrow** [comment]
Not that I know of.  stdin should be handled the same way on all the Korn shell as on the bash shell.

**Comment by nakulkar-msft** [comment]
Fixed with change #1153
