### ISSUE TITLE
Unclear failures in upload from local filesystem to Azure Storage

### ISSUE THREAD

**Issue by klaaslanghout** [Azure/azure-storage-azcopy#54]
Ran a copy command that ended in 1000's of errors.  An example from the log follows.  I assume it was due to slow upload network (from home machine) so, I changed to AZCOPY_CONCURRENCY_VALUE=10 and so far haven't reproed.  Given the concurrency is an optional env var, I'd expect AZCOPY to dynamically reduce the number of threads (or, determine the upload throughput first) or, provide a clear error message so the user can manually set correctly.

Summary:
<redacted>.log file created in C:\Users\klaas/.azcopy
519 Done, 904 Failed, 4322 Pending, 0 Skipped 5745 Total , 2-sec Throughput (Mb/s): 5.7147

Job 42742d06-ee4e-a143-7458-16f358102298 summary
Elapsed Time (Minutes): 1009.0905
Total Number Of Transfers: 5745
Number of Transfers Completed: 519
Number of Transfers Failed: 904
Number of Transfers Skipped: 0
TotalBytesTransferred: 798344735
Final Job Status: Cancelled

Put https://klaasbackup.blob.core.windows.net/summerbackup/2018/2018/JUne/DSCF1731.JPG?blockid=MTM1ODQyMmItYjYyYS00MzQ5LTZiOTUtZWJkYWQ0MjFjNmQ1&comp=block&se=2018-10-15T09%3A50%3A29Z&sig=3W7BpmoZYi8i6OXRlFg3mXhxQMIiEjLtUlR1ZR6jCN8%3D&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2018-09-15T01%3A50%3A29Z&sv=2017-11-09&timeout=601: net/http: HTTP/1.x transport connection broken: write tcp 192.168.1.48:55519->52.183.104.36:443: wsasend: An existing connection was forcibly closed by the remote host.
   PUT https://klaasbackup.blob.core.windows.net/summerbackup/2018/2018/JUne/DSCF1731.JPG?blockid=mtm1odqymmityjyyys00mzq5ltziotutzwjkywq0mjfjnmq1&comp=block&se=2018-10-15t09%3A50%3A29z&sig=REDACTED&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2018-09-15t01%3A50%3A29z&sv=2017-11-09&timeout=601
   PUT https://klaasbackup.blob.core.windows.net/summerbackup/2018/2018/JUne/DSCF1731.JPG?blockid=mtm1odqymmityjyyys00mzq5ltziotutzwjkywq0mjfjnmq1&comp=block&se=2018-10-15t09%3A50%3A29z&sig=REDACTED&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2018-09-15t01%3A50%3A29z&sv=2017-11-09&timeout=601
Put https://klaasbackup.blob.core.windows.net/summerbackup/2018/2018/JUne/DSCF1731.JPG?blockid=MTM1ODQyMmItYjYyYS00MzQ5LTZiOTUtZWJkYWQ0MjFjNmQ1&comp=block&se=2018-10-15T09%3A50%3A29Z&sig=3W7BpmoZYi8i6OXRlFg3mXhxQMIiEjLtUlR1ZR6jCN8%3D&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2018-09-15T01%3A50%3A29Z&sv=2017-11-09&timeout=601: net/http: HTTP/1.x transport connection broken: write tcp 192.168.1.48:55653->52.183.104.36:443: wsasend: An existing connection was forcibly closed by the remote host.
2018/09/15 03:59:27 ERR: [P#0-T#169] UPLOADFAILED: d:///Users/klaas/My%20Pictures/2018/JUne/DSCF1731.JPG : 000 : Chunk Upload Failed -> github.com/Azure/azure-storage-azcopy/ste.newAzcopyHTTPClientFactory.func1.1, /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:95

**Comment by zezha-msft** [comment]
Hi @klaaslanghout, thanks for reporting this issue! We really appreciate your feedbacks.

Could you reliably reproduce this problem? In other words, if you remove the environment variable AZCOPY_CONCURRENCY_VALUE and run the same command on your home network, do you see the same errors? I'm asking this because home networks tend to be less reliable, so I just wanted to make sure that this is a consistent behavior.

We are still working on refining the pacing behavior, AZCOPY_CONCURRENCY_VALUE is for internal testing only, so for the moment we do not plan on documenting it.

**Comment by klaaslanghout** [comment]
I'll try tonight.  I'm slowly moving all my photos up to archive blobs and still have quite a few years to do :)  FWIW the error rate with CONCURRENCY set was much lower (out of 5k files, I have ~5 errors so far).  I'll send an update after I retest without AZCOPY_CONCURRENCY_VALUE set.

**Comment by zezha-msft** [comment]
Hi @klaaslanghout, any update?
