### ISSUE TITLE
azcopy files to upload blob to emulated storage

### ISSUE THREAD

**Issue by igitur** [Azure/azure-storage-azcopy#547]
### Which version of the AzCopy was used? 
AzCopy 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10, 64b

### What command did you run?
```
 .\azcopy.exe copy "C:\Data.zip" "http://127.0.0.1:10000/devstoreaccount1/powertill/WebData.zip?st=2019-08-12T17%3A28%3A50Z&se=2199-08-13T17%3A28%3A00Z&sp=racwdl&sv=2018-03-28&sr=c&sig=s2iPFU7om14HGjgBzA%2FXLaXmsrhYPexx2mjNKBdqMSk%3D"
```

(fake SAS in above command) 

### What problem was encountered?
File upload fails with this message:
`failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired`
### How can we reproduce the problem in the simplest way?
- Run storage emulator
- Create your own shared access signature
- Run above command but replace with your own shared access signature
### Have you found a mitigation/solution?
No, except to use Storage Explorer to upload files. But I prefer to use the command line

**Comment by zezha-msft** [comment]
Hi @igitur, please use the flag `--from-to=LocalBlob`, as the tool cannot know what kind of endpoint you are targeting.

**Comment by igitur** [comment]
Thanks and excuse my ignorance.

**Comment by zezha-msft** [comment]
@igitur no worries, please don't hesitate if you have any other question/concern. 

Btw the [Azurite](https://github.com/Azure/Azurite) project is going to replace the emulator in the future. Perhaps you could give it a try! 😄
