### ISSUE TITLE
Cannot copy blob from/to AzureStack

### ISSUE THREAD

**Issue by werton13** [Azure/azure-storage-azcopy#552]
### Which version of the AzCopy was used? 
AzCopy 8.1.0-netcore
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

### What command did you run?
azcopy /source:https://testuploads.blob.myAzureStackFQDN/distr/ThirdPartyNotice.txt /dest:c:\test\abs.txt /sourcesas:"?mySAS" /V
### What problem was encountered?
My storage accounts is on the Azure Stack version 1907, i'm using SAS generated in Azure Storage explorer to copy files from container
[ERROR] Error parsing source location ":https://testuploads.blob.myAzureStackFQDN/distr/ThirdPartyNotice.txt": Source with location type Blob doesn't exist. For more details, please type "AzCopy /?:Source" or use verbose option /V.

### Have you found a mitigation/solution?
no

**Comment by JohnRusk** [comment]
If you're able to move to version 10, it has pretty good Azure Stack support now, if you set an environment variable as described in the last comment on this page https://github.com/Azure/azure-storage-azcopy/issues/267

I don't know what support exists in older versions, sorry, since I've only worked on v10.

**Comment by werton13** [comment]
I can confirm what it resolve my issue.
I created environment variable with name and value below:
INFO: Name: AZCOPY_DEFAULT_SERVICE_API_VERSION
Current Value: 2017-11-09

but I cannot find 2017-11-0 profile in the list of supported versions for Azure Stack:
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-profiles-azure-resource-manager-versions here:
Microsoft.Storage (Data Plane)	2017-10-01
Microsoft.Storage (Control Plane)	2017-10-01
I had tried this profile and it is not worked.

**Comment by zezha-msft** [comment]
@werton13 glad you figured it out!

We are not familiar with Azure Stack versions unfortunately. We also did our testing using `2017-11-09`. I can reach out to the right person to get you an answer.

**Comment by GeorgeH-MS** [comment]
@werton13 Thanks for figuring it out. The data plane version number in the doc you referred is incorrect, we would fix it. You can find the right version in https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-acs-differences#api-version. The storage service support 2017-11-09 in Azure Stack. 2017-10-01 is a version supported by SRP (control plane)

**Comment by zezha-msft** [comment]
Thanks @GeorgeH-MS!
