### ISSUE TITLE
Issue uploading to Write-Only SAS URI for Office 365 PST Upload - Win10 AzCopy v10.2.1

### ISSUE THREAD

**Issue by dmfrahm** [Azure/azure-storage-azcopy#555]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Win10

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy "E:\PSTs\-REDACTED-\-REDACTED-.pst" "https://c2e88518ee744e04842251e.blob.core.windows.net/ingestiondata?sv=2015-04-05&sr=c&si=IngestionSasForAzCopy-REDACTED-&sig=-REDACTED-&se=-REDACTED-"

### What problem was encountered?

The logs show it attemping to PUT the to the blob. I see a bunch of `"PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  7, F:  0, B:  1, T:  8"` lines, and then I see a request response with a status code of 400 and an error "InvalidBlobOrBlock"

Full error:
```REQUEST/RESPONSE (Try=1/16.4075902s[SLOW >3s], OpTime=16.4085813s) -- RESPONSE STATUS CODE ERROR
   PUT https://-REDACTED-.blob.core.windows.net/ingestiondata/-REDACTED-.pst?blockid=nwjkmje1yjitngq5ys0xzdqxltvmywetowe5zmzmmzm0yta0&comp=block&se=-REDACTED-&si=ingestionsasforazcopy-REDACTED-&sig=-REDACTED-&sr=c&sv=2015-04-05&timeout=901
   Content-Length: [8388608]
   User-Agent: [AzCopy/10.2.1 Azure-Storage/0.7 (go1.12; Windows_NT)]
   X-Ms-Client-Request-Id: [9a5ada29-3532-4e42-6491-d1f5d468a96a]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The specified blob or block content is invalid.
   Content-Length: [234]
   Content-Type: [application/xml]
   Date: [Fri, 16 Aug 2019 15:22:32 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [InvalidBlobOrBlock]
   X-Ms-Request-Id: [8a96053b-701e-00ab-1446-544bf0000000]
   X-Ms-Version: [2018-03-28]
ERR: [P#0-T#0] UPLOADFAILED: e:///PSTs/-REDACTED-/-REDACTED-.pst : 400 : 400 The specified blob or block content is invalid.. When Staging block. X-Ms-Request-Id: 8a96053b-701e-00ab-1446-544bf0000000
```
It then attempts to do a DELETE but that 403s with a permission mismatch, which makes sense as this is a Write-Only SAS URI.

### How can we reproduce the problem in the simplest way?
Attempt to upload to an O365 PST Migration Blob Write-Only SAS URI
I've attempted with a few different SAS URIs, and so far they only seem to work with AzCopy 8 and only then with the /Y switch. However, that runs at 400kb a second for me, and I have 300GB to copy so that's pretty untenable.

### Have you found a mitigation/solution?
Not yet. I checked issue 87 and attempted to do the solution found there, but it doesn't seem to have resolved the issue. Same with Issue 394

**Comment by dmfrahm** [comment]
Note: I've tried this with the concurrent threads set at 1, 4, and 8. None of which have worked.

**Comment by adreed-msft** [comment]
I have a sneaking suspicion: The block ID length in v8 is NOT the same as v10, and the blob is never actually getting deleted. Have you tried uploading to a different blob?

**Comment by dmfrahm** [comment]
When I generate new SAS links for uploads, it still seems to be using the same blob. Any idea how I could go about getting a new one?

**Comment by adreed-msft** [comment]
Do they have different container names? My thought is that we inferred the blob name from the file name. If you're always getting the same container, you're probably still copying to the same blob.

**Comment by dmfrahm** [comment]
They have the same container name and the same blob name. I've got a couple of historic SAS links from other uploads, and they all seem to point to the same place. And when I look there with Azure Storage Explorer, I can see the past few PSTs I used for test uploads and the like, as well as new ones.

**Comment by adreed-msft** [comment]
Hmmmm, yeah, that seems like it's it. You can manually specify a file name in the URL.

So, your URL would become something like
"https://c2e88518ee744e04842251e.blob.core.windows.net/ingestiondata/PSTs-REDACTED--REDACTED-.pst?sv=2015-04-05&sr=c&si=IngestionSasForAzCopy-REDACTED-&sig=-REDACTED-&se=-REDACTED-"

I'm uncertain though if the file name actually matters for O365 ingestion, as I'm unfamiliar with it.

**Comment by dmfrahm** [comment]
Cool! I can work with subfolders on the ingestion side, so that's fine. Did a test upload and that worked! So, I should just have to import them to a sub-container then?

**Comment by adreed-msft** [comment]
In theory, it should work out fine, yeah.

Just a side note, terminology wise we refer to those as virtual directories (since the concept of a directory doesn't actually exist on Blob storage)

**Comment by dmfrahm** [comment]
Thanks for the note. This is my first time really working with them, so it's appreciated. Going to try a full upload now..

**Comment by dmfrahm** [comment]
2 of 40 files uploaded successfully so far. Based on the throughput and amount of data, it's going to take about a day, but that's way better than the week plus I was looking at before! Thanks for the help @adreed-msft !

**Comment by adreed-msft** [comment]
Glad I could help!
