### ISSUE TITLE
Error during Azcopy sync command

### ISSUE THREAD

**Issue by githubvick** [Azure/azure-storage-azcopy#562]
Azopy version 10.1.2

Windows

azcopy sync "https://blobname.blob.core.windows.net/pio-train/?token" "C:\test" --recursive=true

C:\Users\prosbcomrel>azcopy sync "https://blobname.blob.core.windows.net/pio-train/?token" "C:\test" --recursive=true

Job 4cbe4169-4c5f-8e4e-5d75-1a439c951250 has started
Log file is located at: C:\Users\prosbcomrel/.azcopy/4cbe4169-4c5f-8e4e-5d75-1a439c951250.log

0 Files Scanned at Source, 0 Files Scanned at Destination
Cannot perform sync due to error: cannot list blobs. Failed with error -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Get"https://blobname.blob.core.windows.net/pio-train/?token"&timeout=901: dial tcp: lookup blobname.blob.core.windows.net: no such host

### How can we reproduce the problem in the simplest way?
It was working a week back in my Azure VM. Encountering the error from yesterday. The same command works from another Azure VM.

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
Given the nature of the error messages, it looks like either a typo in the account name, or something blocking the outbound traffic from the VM (e.g. an NSG rule).

**Comment by githubvick** [comment]
Just found out that there is some network connectivity issue. Outbound traffic is all fine. But happened all of a sudden and took me off guard.
