### ISSUE TITLE
Azcopy dumping more ... stuff... in $HOME

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-storage-azcopy#563]
10.2.0. Please follow the XDG spec instead of further polluting my home dir with Azure-related cruft. A variety of Go packages are available to aid in this effort.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by adreed-msft** [comment]
Hi, colemickens.

We're currently working on the ability to move the logs and jobs directories. Thank you for your patience.

**Comment by adreed-msft** [comment]
@JohnRusk @zezha-msft

Considering Sercan's focus was on Linux-like functionality with AzCopy, we should consider setting better default locations for logs/plans, as well as the OAuth token.

This would entail checking the $XDG_*_HOME variables and assuming a value if they aren't present.

**Comment by zezha-msft** [comment]
@adreed-msft please log an item in our backlog.

**Comment by JohnRusk** [comment]
I'm tagging this with 10.3 to remind us to add note here when 10.3 comes out. That won't do the XDG thing, but it will at least allow improved configurablity.

**Comment by JohnRusk** [comment]
10.3 is now out. As per the [changelog](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.3.0), it allows moving of both the plan and log files. It does not however, detect any $XDG_*_HOME variables. For that, I will leave this issue open as a feature request.
