### ISSUE TITLE
Can't upload single file to a Data Lake Storage Gen2 container

### ISSUE THREAD

**Issue by kogesaka** [Azure/azure-storage-azcopy#567]
##### Note: The version is visible when running AzCopy without any argument
version 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 Enterprise v1903

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

./azcopy.exe copy "C:\Users\\&lt;User Name&gt;\Desktop\AzCopy\[test].txt" "https://&lt;Storage Account Name&gt;.dfs.core.windows.net/container/[test].txt" --overwrite=true

### What problem was encountered?

The upload failed with the following error message :

failed to perform copy command due to error: cannot start job due to error: cannot find source to upload.

### How can we reproduce the problem in the simplest way?

Include square brackets ([ ]) in the source single file name.

### Have you found a mitigation/solution?

No, I tried using escape character (ex. ^, `,%), but the phenomenon has not been avoided.

**Comment by kogesaka** [comment]
Hi, @adreed-msft san,
Uploading failed even if the file name was enclosed in quotes (Run on Windows PowerShell).

./azcopy.exe copy 'C:\Users\<User Name>\Desktop\"[test].txt"' "https://&lt;Storage Account Name&gt;.dfs.core.windows.net/container/[test].txt" --overwrite=true

-> failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

./azcopy.exe copy "C:\Users\\&lt;User Name&gt;\Desktop\AzCopy\'[test].txt'" "https://&lt;Storage Account Name&gt;.dfs.core.windows.net/container/[test].txt" --overwrite=true

-> failed to perform copy command due to error: cannot start job due to error: cannot find source to upload.

In addition, after renaming "[test] .txt" to "test.txt" and succeeding in the following contents, it seems that parsing of the source file name has failed.

./azcopy.exe copy "C:\Users\\&lt;User Name&gt;\Desktop\AzCopy\test.txt" "https://&lt;Storage Account Name&gt;.dfs.core.windows.net/container/[test].txt" --overwrite=true

**Comment by kogesaka** [comment]
Hi,
Is this issue currently being addressed ?
I'd rather know if this issue is caused by AzCopy parsing than if this issue can be fixed.

**Comment by zezha-msft** [comment]
Hi @kogesaka, what you wrote as destination is not a valid URL. `[` and `]` need to be [escaped](https://www.w3schools.com/tags/ref_urlencode.asp).

**Comment by zezha-msft** [comment]
Ex: "https://<Storage Account Name>.dfs.core.windows.net/container/%5Btest%5D.txt"

**Comment by zezha-msft** [comment]
To escape the brackets for local Windows:
```
Get-Content 'C:\Users\zezha\bla`[test`].txt'
```

**Comment by kogesaka** [comment]
Hi @zezha-msft,

The following command is executed by Windows PowerShell, but it is an error.

Please confirm this issue properly.

./azcopy.exe copy 'C:\Users\<User Name>\Desktop\AzCopy\`[test`].txt' 'https://<Storage Account Name>.dfs.core.windows.net/container/%50test%50.txt' --overwrite=true

failed to perform copy command due to error: cannot start job due to error: cannot find source to upload.

**Comment by adreed-msft** [comment]
Considering the release is out, I'll close this issue again. Enjoy @kogesaka!
