### ISSUE TITLE
Failed to refresh token 

### ISSUE THREAD

**Issue by JulBru** [Azure/azure-storage-azcopy#572]
### Which version of the AzCopy was used? 
AzcopyVersion  10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
OS-Environment  windows
OS-Architecture  amd64

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

Job-Command sync Z:\ExterneFestplattensicherung\I https://brunnersbackup.blob.core.windows.net/backupext --recursive 

### What problem was encountered?
I wanted  to backup my external HDD to Azure S3 cold storage. I tried to sync the folders this night but it stopped working twice. This morning i browsed the log files and found the following entry: 

[](2019/09/02 09:42:15 JobID=b2d43279-d214-8340-5e47-6e51c9ee7669, Part#=1 failed to refresh token, please check error details and try to log in with azcopy login command again. (Error details: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/35e8a96c-5f46-4f70-8976-e603b2f23542/oauth2/token?api-version=1.0: dial tcp 40.126.1.130:443: i/o timeout').)

### How can we reproduce the problem in the simplest way?
I tried to sync around 200 GB of Data from local files to Blob storage (local redundancy) 
I used Azure AD for authentication. 
Then run command like stated above.

### Have you found a mitigation/solution?
Nope. I can only sync about 30 minutes. Then, the token expires.

**Comment by adreed-msft** [comment]
Off the top of my head without any real investigation, this sounds to me like we just outright give up upon a single failed attempt to refresh the token. Could be a relatively simple fix, maybe. I'll have to investigate for real at some point.

**Comment by JulBru** [comment]
Well i observed another phenomenon when having this issue: when the token expires and the script's waiting for a refresh, it won't exit/crash - it hangs up. During this time, my internet is not working: [https://ibb.co/NZrV6Jn](url) 
I can mitigate this by closing the script window....

**Comment by adreed-msft** [comment]
Out of curiosity, are you connected wirelessly or are you wired to your internet source? We've had some reports of AzCopy causing disconnections for some reason in the past, but it's only been on wireless in our cases.

**Comment by zezha-msft** [comment]
@JulBru there might be some kind of policy on your network that is disconnecting you due to high network usage. One possible workaround is to limit the throughput of AzCopy with the flag `--cap-mbps`. Please give it a try and see if that helps.

**Comment by JulBru** [comment]
@adreed-msft it's a wired client

@zezha-msft I'll give it a try when I'm back home. There shouldn't be a problem due to other procresses with fully utilized bandwidth for longer periods where I never experienced a blocking before

**Comment by JulBru** [comment]
@zezha-msft: I tried it with capped bandwidth and it works fine. There's a totally different pattern in the logs after that. I think, azcopy tried to open too many pipes simultanious and that somehow messed up everything. Since then, there are no more token refresh errors. 

However, after running the script for one day (initial upload), the memory is pretty messed up (96% usage). Any explanation for that? Reboot helps but it should only be a workaround right?

**Comment by zezha-msft** [comment]
Hi @JulBru, to clarify, are you saying that after running the script for a whole day (24 hours?), the memory usage of AzCopy specifically, is using 96% of your machine?

Since this is a completely different issue, please open a new issue with more details for us to investigate. Thank you!
