### ISSUE TITLE
Can not upload file from DevOps pipeline Temp storage to Data Lake gen 2

### ISSUE THREAD

**Issue by leosiuk** [Azure/azure-storage-azcopy#573]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Wins
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy $(pathToFile) "abfss://container@datalake.dfs.core.windows.net/" --recursive

### What problem was encountered?
I am trying to upload file (which is created in devops pipeline and save to temp storage) to Data Lake gen 2.  Every time it gives error:

 failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

**Comment by adreed-msft** [comment]
Hi there, this is not the correct syntax for ADLSG2 containers in AzCopy. The correct format is more akin to:

`https://datalake.dfs.core.windows.net/container`

Try using that format in place. Does this solve your problem?
