### ISSUE TITLE
azcopy hangs within azure devops script

### ISSUE THREAD

**Issue by danapoklepovich** [Azure/azure-storage-azcopy#578]
### Which version of the AzCopy was used? 

azcopy 7.3.0-netcore Copyright (c) 2018 Microsoft Corp. All Rights Reserved.
Command Line Usage:
    azcopy --source <source> --destination <destination> [options]
Options:
    [--source-key] [--dest-key] [--source-sas] [--dest-sas] [--verbose] [--resume] 
    [--config-file] [--quiet] [--parallel-level] [--source-type] [--dest-type] 
    [--recursive] [--include] [--check-md5] [--dry-run] [--preserve-last-modified-time]
    [--exclude-newer] [--exclude-older] [--sync-copy] [--set-content-type] [--blob-type] 
    [--delimiter] [--include-snapshot] [--block-size-in-mb]

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy --source $(Build.ArtifactStagingDirectory) --recursive --destination https://mystorage.file.core.windows.net/myfile/$(ARTIFACT)/$(VERSION)  --dest-key mykey

### What problem was encountered?
The script task fails to return and hangs till it fails the pipeline. I can see the artifact is copied into azure file storage and it's there in its entirety when I run an `az storage file download` but the azcopy command doesn't seem to be getting a response from file storage so my pipeline cant carry on. This was working about 3-4 days ago.

I've checked my azure budget and storage quote and I'm still well within my limits. Anyone else experiencing this or have a work around? 

Cheers!

**Comment by zezha-msft** [comment]
Hi @danapoklepovich, thanks for reaching out!

Have you given the new version V10 a try?

**Comment by danapoklepovich** [comment]
Thanks for getting back to me @zezha-msft the problem seems to have been resolved overnight. I suspect it was a bug in pipelines. I'm using that version as that is what was already installed on the build node provided by azure-devops.
