### ISSUE TITLE
Unable to build since 10.0.1: not enough arguments in call to blockBlobUrl.StageBlock

### ISSUE THREAD

**Issue by onny** [Azure/azure-storage-azcopy#58]
### Which version of the AzCopy was used? 
10.0.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
go get github.com/Azure/azure-storage-azcopy
### What problem was encountered?
```
go get github.com/Azure/azure-storage-azcopy                                   :(
# github.com/Azure/azure-storage-azcopy/ste
go/src/github.com/Azure/azure-storage-azcopy/ste/xfer-localToBlockBlob.go:336:36: not enough arguments in call to blockBlobUrl.StageBlock
	have (context.Context, string, io.ReadSeeker, azblob.LeaseAccessConditions)
	want (context.Context, string, io.ReadSeeker, azblob.LeaseAccessConditions, []byte)
go/src/github.com/Azure/azure-storage-azcopy/ste/xfer-localToBlockBlob.go:582:37: not enough arguments in call to pageBlobUrl.UploadPages
	have (context.Context, int64, io.ReadSeeker, azblob.BlobAccessConditions)
	want (context.Context, int64, io.ReadSeeker, azblob.PageBlobAccessConditions, []byte)
```

### How can we reproduce the problem in the simplest way?
```
go get github.com/Azure/azure-storage-azcopy                                   :(
```
### Have you found a mitigation/solution?
10.0.0 worked fine for me

**Comment by zezha-msft** [comment]
Hi @onny, thanks for reaching out! Btw there are download links for the executables on the [readme](https://github.com/Azure/azure-storage-azcopy) page.

To solve your problem, please use [dep](https://github.com/golang/dep) to run `dep ensure`, and then run `go build`.
