### ISSUE TITLE
Azcopy list on specific folder only

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-storage-azcopy#583]
azcopy version 10.2.1

Is there no way using v10 azcopy to list blobs that are only in a specific folder?

Currently if I include a folder in the URL when doing azcopy list the folder is ignored and azcopy begins to list EVERY blob in the entire container. e.g:
azcopy list https://${ACCOUNT}.blob.core.windows.net/${CONTAINER}/${FOLDER}/${SAS}

If it is currently not possible to list only within a certain folder then I would like to make a feature request.

**Comment by JohnRusk** [comment]
Looks like it only supports the whole container, at present.  I've tagged this issue with the feature-request tag.

**Comment by rakelkar** [comment]
+1 to this feature request

**Comment by nofunatall** [comment]
Question:
Seems copy commands work with using specific virtual folder prefixes but list does not.

Is that correct?

**Comment by JohnRusk** [comment]
I believe that is correct.  @adreed-msft , when we update the list logic to use the new enumeration code (same code as the copy), what do you think about making it support the same features as enumeration does: e.g. use virtual folders in the URL (and maybe support include-pattern and include-path)

**Comment by JohnRusk** [comment]
@adreed-msft Do you know if this was fixed in 10.3.x?

**Comment by JohnRusk** [comment]
If NOT fixed, then it will also affect  https://github.com/Azure/azure-storage-azcopy/issues/583 (since the case there is trying to list subdirectory)

**Comment by zezha-msft** [comment]
This has been fixed.
