### ISSUE TITLE
Feature: File or Pipe input for 'Azcopy Remove'

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-storage-azcopy#585]
azcopy version 10.2.1

It would be extremely useful if 'azcopy remove' could recieve input from pipe or iterate over a list of blobs.

The best work around at the moment is to use xargs in parrallel like:
`xargs -P4 -l1 -n1 -I@ -a $HOME/db_blob_no_match.list azcopy remove --recursive=false "https://${ACCOUNT}.blob.core.windows.net/${CONTAINER}/@${SAS}"`

But even in parrallel this is very slow as there is time wasted waiting for the OK response from Azure API.

You can get creative using the --include="" but this has an upper limit on total amount of words it will allow within the --include clause.

**Comment by zezha-msft** [comment]
Hi @nofunatall, thanks for reaching out!

We'll have support for this feature in the next release. You'll be able to use `--list-of-files`.

**Comment by nofunatall** [comment]
Any ETA on the next release?

**Comment by zezha-msft** [comment]
@nofunatall we are targeting the next few weeks.

**Comment by JohnRusk** [comment]
We don't publish the dates, I'm sorry.

**Comment by nofunatall** [comment]
Ok so no dates - last comment was a few weeks which was almost 3 weeks ago.

IS there a more accurate ETA now or still a few weeks?

**Comment by JohnRusk** [comment]
I'll raise your question at today's team meeting.

**Comment by JohnRusk** [comment]
Hi @nofunatall. I raised your question at today's team meeting. Email me if you'd like to discuss.

**Comment by nofunatall** [comment]
Thanks but not needed - I will just keep note maybe expect release sometime next month.

**Comment by JohnRusk** [comment]
The release is out now.  Version number is 10.3.  The file format is just literally a list of relative filenames, as described here: https://github.com/Azure/azure-storage-azcopy/wiki/Listing-specific-files-to-transfer
