### ISSUE TITLE
Listing operations for Azure File Storage

### ISSUE THREAD

**Issue by jmon12** [Azure/azure-storage-azcopy#586]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux - Centos 7.6.1810

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`./azcopy list https://xxx.file.core.windows.net/xxx`

### What problem was encountered?
It seems like any operation other than copying (didn't test it) is not supported by the azcopy tools for File Storage (not blobs), see #277. 
The lack of support for the File Storage isn't well documented. I could be sure of it only when I found the aforementioned feature request.

### How can we reproduce the problem in the simplest way?
Rerun the command for any url corresponding to an Azure file storage.

### Have you found a mitigation/solution?
For now we're using `rsync` with the mounted Azure filesystem. We'll maybe consider `azcopy` once the File storage support is improved.

**Comment by JohnRusk** [comment]
Related to #692

**Comment by JohnRusk** [comment]
This feature was added in 10.3.3., which was release today.
