### ISSUE TITLE
ContentType for JSON objects not correctly identified

### ISSUE THREAD

**Issue by pniederlag** [Azure/azure-storage-azcopy#587]
### Which version of the AzCopy was used? 

AzCopy 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

azcopy sync /app/public 'https://XXXX.blob.core.windows.net/XXXX?sv=XXXX'

### How can we reproduce the problem in the simplest way?

sync some *.json files and check the content-type in storage

### Have you found a mitigation/solution?

According to #66 this issue was fixed in 2018-12 but it is not working for me.

*.js, *.css, *.html are correctly identified and are assigned the corresponding content-type's, it's just not working for *.json

**Comment by pniederlag** [comment]
ok, adding an explicit mapping via /etc/mime.types does solve the issue.

```
cat /etc/mime.types 
application/json				json
```

now the *.json files are properly detected.

**Comment by zezha-msft** [comment]
Hi @pniederlagm, that is correct! The doc is in the tool `./azcopy sync -h` and also [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync#advanced).
