### ISSUE TITLE
azcopy10 within cloud environments - errors out as --RESPONSE Status: 403 This request is not authorized to perform this operation.

### ISSUE THREAD

**Issue by srini99mkl** [Azure/azure-storage-azcopy#588]
We are trying to use Azcopy within the cloud i.e. from a VM to loading data into ADLS gen2, we are getting following error 
 RESPONSE Status: 403 This request is not authorized to perform this operation.

### Which version of the AzCopy was used? 
10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
Azcopy.ps1 -SourceDirFile "F:\Sts\*" -Destination_Azure "https://xxxxxxsdddd.dfs.core.windows.net/sdsdsd-dsdss-fsys-edsdsdl"

### What problem was encountered?
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Date: [Mon, 09 Sep 2019 21:04:49 GMT]
   Server: [Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [24bcba9d-fsdsdf-0sdd-1ddd52-6xxxxxxxx000]
   X-Ms-Version: [2018-11-09]

**Comment by adreed-msft** [comment]
Hi, @srini99mkl -- I'm not entirely sure what goes on within your AzCopy.ps1 file. Could you provide more detail on that?

As this is an auth related error, I need to understand what kind of auth you're trying to use as well as your actual scenario.

**Comment by srini99mkl** [comment]
Hello,
Azcopy.ps1 has  just azcopy command

C:\Program Files (x86)\AzCopy\" -SourceDirFile "D:\files\*" -Destination_Azure "https://dddddssxxxxx.dfs.core.windows.net/sdsdsdv-001"

To get Outh2 autorization I am using

Azcopy azlogin command ….  I was able to login to my azure account from the VM(Azure VM) that calls above azcopy command.

**Comment by JohnRusk** [comment]
@srini99mkl That copy command you showed looks unusual. I don't recognize it as having the format of an AzCopy v10 command, nor does it look like a v8 command.

Also, you mentioned an "azlogin" command. There is no "azlogin" in AzCopy, it's just `AzCopy login`.

It sounds like you might have some mixed up versions of things.

**Comment by JohnRusk** [comment]
I propose to close this, on the assumption that it was indeed some mixed up versions of things - e.g. using "azlogin" (from the cloud CLI) instead of AzCopy's own "AzCopy login". Let us know if you need it reopened.
