### ISSUE TITLE
Cannot SSH to CentOS 7.5 VM after installing azcopy 7.3.0-netcore

### ISSUE THREAD

**Issue by ginga25c3** [Azure/azure-storage-azcopy#59]
### What problem was encountered?
Cannot SSH to CentOS 7.5 VM after installed azcopy 7.3.0-netcore
Found the installation will change the permission of user home directory from 700 to 775

### How can we reproduce the problem in the simplest way?
1. create VM using Azure gallery image CentOS 7.5
      "imageReference": {
        "publisher": "OpenLogic",
        "offer": "CentOS",
        "sku": "7.5",
        "version": "latest"

2. SSH to the VM
before installing azcopy, found the permission of user home directory is 700

[holgo@azcopy home]$ date; ls -al
Wed Sep 26 08:12:12 UTC 2018
total 0
drwxr-xr-x.  3 root  root   19 Sep 26 08:06 .
dr-xr-xr-x. 17 root  root  224 Aug 15 20:04 ..
**drwx------.  5 holgo holgo 124 Sep 26 08:10 holgo**

3. Install azcopy
wget -O azcopy.tar.gz https://aka.ms/downloadazcopylinux64
tar -xf azcopy.tar.gz
sudo ./install.sh
sudo yum install -y libunwind icu

4. Now issue can be reproduced where any further SSH attempt will fail with error saying: 
Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

From /var/log/secure, found error pointing to bad ownership or modes for directory /home/holgo

[holgo@azcopy home]$ sudo tail -f /var/log/secure
...
**Sep 26 08:16:05 localhost sshd[1831]: Authentication refused: bad ownership or modes for directory /home/holgo**
....

5. re-check to find permission of /home/holgo is changed to 775

[holgo@azcopy home]$ date ; ls -al
Wed Sep 26 08:14:52 UTC 2018
total 0
drwxr-xr-x.  3 root  root   19 Sep 26 08:06 .
dr-xr-xr-x. 17 root  root  224 Aug 15 20:04 ..
**drwxrwxr-x.  6 holgo holgo 177 Jul 19 04:56 holgo**
[holgo@azcopy home]$

### Have you found a mitigation/solution?
"sudo chmod -R 700 holgo/" will mitigate the issue

**Comment by ginga25c3** [comment]
To add for the repro, we create VM only with SSH key access. So we can also reset ssh config and password over portal to regain access. But issue would still remain that why permission is changed for user home directory.

**Comment by zezha-msft** [comment]
Hi @ginga25c3, thanks for reaching out!

@EmmaZhu will get back to you shortly.

**Comment by EmmaZhu** [comment]
@ginga25c3 
Thanks for reporting this to us. I've reproduced the issue. Seems command line `tar -xf azcopy.tar.gz` changes permission of home folder. I'm still trying to figure out how this happens. Will update you with any progress.

**Comment by ginga25c3** [comment]
Hi Emma, seeing if any update we can have ?

**Comment by ginga25c3** [comment]
Hi Emma, seeing if we can have any update ?

**Comment by EmmaZhu** [comment]
@ginga25c3, 
Seems the issue is because we used a wrong command line when package the tar ball, We'll publish a new package to correct its behavior soon.

**Comment by arvindrajpurohit** [comment]
any update on this ?

**Comment by karanp24** [comment]
we also faced same issue on CentOS Linux release 7.4.1708 (Core), Kernel version 3.10.0-693.21.1.el7.x86_64.

**Comment by bishal41** [comment]
@EmmaZhu can you provide some update? Thanks.

**Comment by EmmaZhu** [comment]
We've made a new package to resolve this issue, and are working on publishing it. 
For publishing, we use a CDN link for you to download it. There's still a small issue with the CDN, and we are working it. We should be able to make it work in one or two days. By then, the shortcut link will work to download a new package.

**Comment by EmmaZhu** [comment]
Hi,

We've just updated the download shortcut (https://aka.ms/downloadazcopylinux64), the new package to fix the issue can be downloaded from it now. 

Thanks.

**Comment by karanp24** [comment]
not working , after installing the package I am getting this error when I run azcopy.
Failed to load �e�, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/usr/lib/azcopy/libcoreclr.so'

**Comment by EmmaZhu** [comment]
@karanp24 
AzCopy (.Net Core) needs some prerequisites to be installed first. Could you try to install libunwind and icu (with command "yum install -y libunwind icu") and try AzCopy again?

Thanks
Emma

**Comment by karanp24** [comment]
Thanks  Emma !
