### ISSUE TITLE
Azcopy Login support sovereign cloud environment

### ISSUE THREAD

**Issue by casperlw** [Azure/azure-storage-azcopy#590]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

### What command did you run?
azcopy login

### What problem was encountered?
I can't login to the sovereign cloud environment like China

### How can we reproduce the problem in the simplest way?
Can we support parameter like az cloud set -n AzureChinaCloud?

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
I think that all you need to do is add this to your login command line:

--aad-endpoint "https://login.partner.microsoftonline.cn"

That tells AzCopy to use the right Login URI for China.

**Comment by JohnRusk** [comment]
PS I got that link here: https://docs.microsoft.com/en-us/azure/china/resources-developer-guide 

Similar pages will exist, and document the appropriate links for other sovereign clouds.

(If --aad-endpoint is not specified, then AzCopy uses the default global URI, which is https://login.microsoftonline.com)

**Comment by JohnRusk** [comment]
I'm closing this issue, since I believe the parameter described above is what you're looking for.  Please let us know if we need to re-open this.

**Comment by casperlw** [comment]
Thank you very much, that parameter solved my problem.
