### ISSUE TITLE
old azcopy version in azure pipelines hosted pool

### ISSUE THREAD

**Issue by Hazmes** [Azure/azure-storage-azcopy#591]
### Which version of the AzCopy was used? 
`azcopy 7.3.0-netcore Copyright (c) 2018 Microsoft Corp. All Rights Reserved.`
### Which platform are you using? (ex: Windows, Mac, Linux)
`
pool:
  vmImage: 'Ubuntu-16.04'
`
### What command did you run?
`azcopy`
### What problem was encountered?
Old Version of azcopy in hosted ubuntu agent on azure pipelines

```------------------------------------------------------------------------------
azcopy 7.3.0-netcore Copyright (c) 2018 Microsoft Corp. All Rights Reserved.
------------------------------------------------------------------------------
# azcopy is designed for high-performance uploading, downloading, and copying
data to and from Microsoft Azure Blob, and File storage.

# Command Line Usage:
    azcopy --source <source> --destination <destination> [options]

# Options:
    [--source-key] [--dest-key] [--source-sas] [--dest-sas] [--verbose] [--resume] 
    [--config-file] [--quiet] [--parallel-level] [--source-type] [--dest-type] 
    [--recursive] [--include] [--check-md5] [--dry-run] [--preserve-last-modified-time]
    [--exclude-newer] [--exclude-older] [--sync-copy] [--set-content-type] [--blob-type] 
    [--delimiter] [--include-snapshot] [--block-size-in-mb]
```
### How can we reproduce the problem in the simplest way?
Make a pipeline and run azcopy

### Have you found a mitigation/solution?
update azcopy on hosted ubuntu agent image
Or keep multiple version if backwards compatibility is needed, e.g. azcopy-7.3, azcopy10, ...

**Comment by jolauMSFT** [comment]
@rishabpoh 
This is also a problem for Ubuntu 18.04

**Comment by fabianallendorf** [comment]
Is this issue still being tracked?

**Comment by JohnRusk** [comment]
I've make some enquiries internally, but responses may be delayed due to the holiday season.

**Comment by JohnRusk** [comment]
And I see Rishab is actively following up with the relevant team (but again, responses may be delayed due to the holiday season).

**Comment by rishabpoh** [comment]
Hi @fabianallendorf, I am tracking this issue and I have noted that this issue exists for 16.04 and 18.04. I am waiting for a response from the internal team and will post an update here as soon as possible.

**Comment by rishabpoh** [comment]
Update: This is now being worked on with an eta of ~1 month until deployment. I will post a final update upon completion.

**Comment by juergstaub-swissre** [comment]
Hi, I see that azcopy 7.3.0-netcore is still installed on Ubuntu 18.04. Any plan when you update the agents?

**Comment by TomaBusarov** [comment]
Hi, any progress on this in the last 5 months? Having standalone AzCopy (not part of the AzureFileCopy task) could be useful if you want to copy/update files on storage account where subscription is not within your control.

**Comment by JohnRusk** [comment]
@amishra-dev and @rishabpoh

**Comment by nakulkar-msft** [comment]
Now upgraded to v10
