### ISSUE TITLE
Azcopy copy gives error: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by dtotzke** [Azure/azure-storage-azcopy#594]
### Which version of the AzCopy was used? 
10.2.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows Server 2012 Data Center

### What command did you run?
azcopy copy "e:\foo\bar\*" "https://REDACTED.file.core.windows.net/REDACTED?SAS --overwrite=false
### What problem was encountered?
All files produce the same error in the log file:

2019/09/16 13:07:13 ==> REQUEST/RESPONSE (Try=1/173.1697ms, OpTime=173.1697ms) -- REQUEST ERROR
   HEAD https://-REDACTED-.file.core.windows.net/-REDACTED-/U20170628105123469EE573EDE00CF4BD0BAB8A5176CB72A98.dat?<sas>
   User-Agent: [AzCopy/10.2.1 Azure-Storage/0.5.0 (go1.12; Windows_NT)]
   X-Ms-Client-Request-Id: [2fbc429f-6825-496b-6e1f-bc830e492808]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Head https://-REDACTED-.file.core.windows.net/-REDACTED-/U20170628105123469EE573EDE00CF4BD0BAB8A5176CB72A98.dat?<sas>: read tcp 192.168.168.35:52018->13.77.184.76:443: wsarecv: An existing connection was forcibly closed by the remote host.

goroutine 364 [running]:
github.com/Azure/azure-storage-file-go/azfile.stack(0xc000132570, 0xc000bc4300, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.5.0/azfile/zc_policy_request_log.go:146 +0xa4
github.com/Azure/azure-storage-file-go/azfile.NewRequestLogPolicyFactory.func1.1(0xc9bd60, 0xc001574000, 0xc00147a100, 0x10, 0x0, 0xc7b110, 0xa6e6c0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.5.0/azfile/zc_policy_request_log.go:96 +0x658
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00146a0a0, 0xc9bd60, 0xc001574000, 0xc00147a100, 0xc001496348, 0x8, 0x8, 0xa913a0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0xc9bd60, 0xc001574000, 0xc00147a100, 0xc000041900, 0xc000aa72e0, 0x443549, 0xc00154c008)
	/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:69 +0x1b9
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00149a020, 0xc9bd60, 0xc001574000, 0xc00147a100, 0x421555, 0xc000bfe200, 0x2c0774, 0x44bf01)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-file-go/azfile.responderPolicy.Do(0xc8f5a0, 0xc00149a020, 0xc001546000, 0xc9bd60, 0xc001574000, 0xc00147a100, 0x0, 0x10, 0x10, 0xc000bfe200)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.5.0/azfile/zz_generated_responder_policy.go:33 +0x5a
github.com/Azure/azure-storage-file-go/azfile.anonymousCredentialPolicy.Do(...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.5.0/azfile/zc_credential_anonymous.go:54
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do(0xc000bfe0c0, 0xc9bd60, 0xc001574000, 0xc00147a100, 0x0, 0x0, 0x0, 0xc000aa74a0)
	/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x65
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000bfe0d0, 0xc9bd60, 0xc001574000, 0xc00147a100, 0xc001574000, 0xc000bfe200, 0x2c0bc1, 0xc000aa7501)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-file-go/azfile.NewRetryPolicyFactory.func1.1(0xc9bce0, 0xc000a36140, 0xc00147a000, 0x10, 0xa6e6c0, 0xc7b110, 0xa6e6c0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.5.0/azfile/zc_policy_retry.go:194 +0x636
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0014480c0, 0xc9bce0, 0xc000a36140, 0xc00147a000, 0xc001496218, 0x30, 0x28, 0x8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-file-go/azfile.NewUniqueRequestIDPolicyFactory.func1.1(0xc9bce0, 0xc000a36140, 0xc00147a000, 0x10, 0xa6e6c0, 0xc7b110, 0xa6e6c0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.5.0/azfile/zc_policy_unique_request_id.go:19 +0xb6
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00149a060, 0xc9bce0, 0xc000a36140, 0xc00147a000, 0xc001496200, 0x36, 0xc000a200c0, 0xc000aa77d8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-file-go/azfile.NewTelemetryPolicyFactory.func1.1(0xc9bce0, 0xc000a36140, 0xc00147a000, 0x1, 0x0, 0x1, 0xc00154c000)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.5.0/azfile/zc_policy_telemetry.go:34 +0x165
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc001452090, 0xc9bce0, 0xc000a36140, 0xc00147a000, 0xc001452090, 0xc000aa78a8, 0x413bf5, 0xc001546008)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc000a36000, 0xc9bce0, 0xc000a36140, 0xc8f680, 0xc001546000, 0xc00147a000, 0x1f, 0xc0013a2027, 0x3e, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:129 +0x88
github.com/Azure/azure-storage-file-go/azfile.fileClient.GetProperties(0xc0013a2000, 0x5, 0x0, 0x0, 0x0, 0xc0013a2008, 0x1f, 0xc0013a2027, 0x3e, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.5.0/azfile/zz_generated_file.go:283 +0x34d
github.com/Azure/azure-storage-file-go/azfile.FileURL.GetProperties(...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.5.0/azfile/url_file.go:137
github.com/Azure/azure-storage-azcopy/ste.(*azureFilesUploader).RemoteFileExists(0xc000af6000, 0xc000000000, 0x4d, 0xc0013a2000)
	/home/vsts/work/1/s/ste/uploader-azureFiles.go:96 +0xbc
github.com/Azure/azure-storage-azcopy/ste.anyToRemote(0xcb13a0, 0xc000a3e050, 0xc8dc80, 0xc000a36000, 0x40f9880, 0xc00035e048, 0xb8c9a0, 0xb8c9d8)
	/home/vsts/work/1/s/ste/xfer-anyToRemote.go:76 +0xbd4
github.com/Azure/azure-storage-azcopy/ste.parameterizeSend.func1(0xcb13a0, 0xc000a3e050, 0xc8dc80, 0xc000a36000, 0x40f9880, 0xc00035e048)
	/home/vsts/work/1/s/ste/xfer.go:69 +0x7a
github.com/Azure/azure-storage-azcopy/ste.(*jobPartMgr).StartJobXfer(0xc0003fc200, 0xcb13a0, 0xc000a3e050)
	/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:527 +0x78
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).StartJobXfer(0xc000a3e050)
	/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:143 +0x4e
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).transferProcessor.func1(0xcb13a0, 0xc000a3e050)
	/home/vsts/work/1/s/ste/JobsAdmin.go:272 +0x170
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).transferProcessor(0xc0003e6000, 0x5)
	/home/vsts/work/1/s/ste/JobsAdmin.go:280 +0x92
created by github.com/Azure/azure-storage-azcopy/ste.initJobsAdmin
	/home/vsts/work/1/s/ste/JobsAdmin.go:199 +0x6b3

### How can we reproduce the problem in the simplest way?
Run the above command.

### Have you found a mitigation/solution?
I have not found a mitigation for this error specifically.  I do suspect that it has something to do with TLS.  Possibly my server does not have the correct configuration to support the connection.

I can, however, map a drive to the Azure File Share and copy files using Robocopy but this is horribly slow compared to Azcopy.

**Comment by adreed-msft** [comment]
We've seen this happen with one other customer-- From what we could tell from the log, requests started getting turned back with failures for a little while beforehand, and then we just outright got connections closed by the remote.

@JohnRusk I doubt this an intentional way to rate-limit us, but it may still be a good idea to take these kinds of responses as a signal to back off for a little bit and then start trying again. Thoughts?

**Comment by dtotzke** [comment]
@adreed-msft The directory has about 500K files in it and I have set the --overwrite=false.  There are about 50K files already on the server.  Could it be the speed at which you are sending the HEAD requests then?  This is a dual Xeon E5-2450 with 96GB RAM in a data center with, I think, a gigabit connection.  I've not set any limits on Azcopy.

I've let it run for about 10 minutes and it never started copying any files and when I cancel the job it reports zero files copied.  Possibly it didn't get through the initialization before I killed it.

I've run it against a folder with only 11 files in it and got basically the same result although there is an error message in this log saying "Could not check file existence" that was not in the other when I cancelled.  Here is the tail of that log file:

2019/09/16 13:07:55 ERR: [P#0-T#2] UPLOADFAILED: e:///DMS.Data/contoso/U2017091316195187631A0DE2D84474F93B262447ED32611D2.dat : 000 : Could not check file existence. -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Head https://contosodms.file.core.windows.net/myshare/U2017091316195187631A0DE2D84474F93B262447ED32611D2.dat?se=2019-09-30T09%3A58%3A23Z&sig=-REDACTED-&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2019-09-16T01%3A58%3A23Z&sv=2018-03-28&timeout=901: context canceled

   Dst: https://contosodms.file.core.windows.net/myshare/U2017091316195187631A0DE2D84474F93B262447ED32611D2.dat?se=2019-09-30t09%3A58%3A23z&sig=-REDACTED-&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2019-09-16t01%3A58%3A23z&sv=2018-03-28
2019/09/16 13:07:55 JobID=c7ad0f6f-cace-b64f-6fb2-3f4eae1fab9e, Part#=0, TransfersDone=1 of 11
2019/09/16 13:07:55 ERR: [P#0-T#1] UPLOADFAILED: e:///DMS.Data/contoso/U20170628105123469EE573EDE00CF4BD0BAB8A5176CB72A98.dat : 000 : Could not check file existence. -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Head https://contosodms.file.core.windows.net/myshare/U20170628105123469EE573EDE00CF4BD0BAB8A5176CB72A98.dat?se=2019-09-30T09%3A58%3A23Z&sig=-REDACTED-&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2019-09-16T01%3A58%3A23Z&sv=2018-03-28&timeout=901: context canceled

   Dst: https://contosodms.file.core.windows.net/myshare/U20170628105123469EE573EDE00CF4BD0BAB8A5176CB72A98.dat?se=2019-09-30t09%3A58%3A23z&sig=-REDACTED-&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2019-09-16t01%3A58%3A23z&sv=2018-03-28
2019/09/16 13:07:55 JobID=c7ad0f6f-cace-b64f-6fb2-3f4eae1fab9e, Part#=0, TransfersDone=2 of 11
2019/09/16 13:07:57 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, T:  0
2019/09/16 13:07:57 

Job c7ad0f6f-cace-b64f-6fb2-3f4eae1fab9e summary
Elapsed Time (Minutes): 0.7337
Total Number Of Transfers: 11
Number of Transfers Completed: 0
Number of Transfers Failed: 2
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Cancelled


Hope that helps.

**Comment by JohnRusk** [comment]
@dtotzke To help diagnose this, is there any chance you could run a small test to an empty File Share, the first time without any overwrite flag on the command line, and the second time (once the files exist at the destination) with overwrite=false?

If both of those work without error, then the next thing to try would be to scale down the concurrency level of AzCopy, by setting the environment variable AZCOPY_CONCURRENCY_VALUE to something like 16, and the try the big test.

Finally, if you wouldn't mind doing just one more thing... could you search the log file (the one from the very start of this issue/thread) to see how many times this request id appears: 2fbc429f-6825-496b-6e1f-bc830e492808 
That will tell us whether AzCopy is retrying after these failures. We need to figure out whether if its doing its usual "retry up to 20 times". Thanks!

**Comment by JohnRusk** [comment]
@adreed-msft  Depending on @dtotzke's answer to the log search, above, we'll be able to decide next steps re your question about whether the app is (or isn't) backing off correctly in these cases.

**Comment by dtotzke** [comment]
@JohnRusk 
The request id 2fbc429f-6825-496b-6e1f-bc830e492808 appeared 10 times in the log.

I've conducted three tests in the order below and attached the full log files for your examination.  All three tests were executed in the same command prompt instance.

4f0f2e93-2272-c444-40ab-3f852cabca5d.log - 10 local files to an empty share. Upload successful.

15ec2e30-e1f2-e14d-53f1-d674900da334.log - 10 original files plus 10 new files to the same share that still contains the original files.  --overwrite left as default true.  Upload successful but took nearly 15 minutes vs < 1 minute for the original 10.

809d9b72-1bd4-e94b-4a2e-f41eeb973347.log - Deleted the 10 new files from the file share and local directory.  --overwrite=false.  Job completed successfully with 0 files uploaded.  This job also took over 15 minutes to complete.

[azcopy-test-logs.zip](https://github.com/Azure/azure-storage-azcopy/files/3621817/azcopy-test-logs.zip)

Hope that helps.  Happy to perform other tests as needed.

**Comment by dtotzke** [comment]
Tried one more test.  Opened a new command prompt and ran the --overwrite=false test again.  This time the job failed after 15 minutes.  Log is attached. 

[d76a9712-4f92-3e4e-6c89-a56ffb5832fe.zip](https://github.com/Azure/azure-storage-azcopy/files/3621995/d76a9712-4f92-3e4e-6c89-a56ffb5832fe.zip)

**Comment by dtotzke** [comment]
After having waited several hours, I ran the same --overwrite=false test again three times in succession to very different results.

56b2e42b-d257-0045-7f01-3d34965a2c6b.log -- first run - CompletedWithSkipped in ~2 minutes.
d0732f41-537e-7c44-6fb4-41baaf2b3297.log -- second run - CompletedWithSkipped in ~ 2 SECONDS!
b705d0c2-71e6-0945-6962-890e25b746ae.log -- third run - Failed in 15.8 minutes.

Please let me know if you need any further information.
[After Waiting.zip](https://github.com/Azure/azure-storage-azcopy/files/3623188/After.Waiting.zip)

**Comment by JohnRusk** [comment]
Thanks @dtotzke .  Those logs and test cases should be very helpful!

**Comment by dtotzke** [comment]
After having waited several hours, I ran the same --overwrite=false test again three times in succession to very different results.
56b2e42b-d257-0045-7f01-3d34965a2c6b.log -- first run - CompletedWithSkipped in ~2 minutes.
d0732f41-537e-7c44-6fb4-41baaf2b3297.log -- second run - CompletedWithSkipped in ~ 2 SECONDS!
b705d0c2-71e6-0945-6962-890e25b746ae.log -- third run - Failed in 15.8 minutes.

[After Waiting.zip](https://github.com/Azure/azure-storage-azcopy/files/3623207/After.Waiting.zip)

**Comment by dtotzke** [comment]
@JohnRusk You're welcome.  Just added a few more that have weird results that offer additional clues.  Please let me know if you need anything else.

**Comment by JohnRusk** [comment]
Thanks. FYI, it might be a few days until I can investigate this properly. Will update you here once I find anything.

**Comment by JohnRusk** [comment]
Thanks for asking. It's on the top of my list of issues to look at, but I (still) have some things I have to do before I get to that list, I'm sorry.

BTW, do you know roughly what network bandwidth you have?  And can you tell us whether this was to a storage account nearby (e.g. approximately the same part of the world that your client machine is in) or far away?  And finally, was this using a wired or Wifi connection?

**Comment by dtotzke** [comment]
Gigabit connection. Hard line.
Server is in a commercial data center in Vancouver.
Primary storage is in West US 2 with Secondary (GRS) in West Central US.

**Comment by dtotzke** [comment]
FYI I am able to map a drive to the share and copy files without a problem.  I've had robocopy* running around the clock for almost a week now without a problem.  It's terribly slow though. I have about 1.2TB to upload and it's only copied about 400GB to this point.

*The share was not mapped and robocopy was not running during the tests I ran above.

**Comment by JohnRusk** [comment]
Thanks for the additional info.  Yeah, Robocopy is not optimized for long (or even medium)-distance links.

**Comment by dtotzke** [comment]
Hey @JohnRusk Just wanted to add some additional information.  The server that I am trying to run Azcopy on seems to have some issues.  I have a process that talks to Microsoft Graph to update AAD and it's timing out just trying to get an auth token although, like Azcopy, it sometimes works.  I have a feeling that some well-meaning person has blocked/throttled traffic to some outbound destinations of which Microsoft seems to be one.  I can't get to msn.com or microsoft.com using a browser on that server.

I don't think you have a bug in Azcopy per se, but there is certainly an opportunity here for better messaging/error reporting.

**Comment by JohnRusk** [comment]
Thanks @dtotzke .  Yes, I agree re opportunities for better error messages. Thanks for mentioning that.  I'll leave this open until I've checked that we have something about the error messages on our backlog.

**Comment by JohnRusk** [comment]
We have items on our backlog about error message improvements, so closing this now.
