### ISSUE TITLE
copying to sharepoint online

### ISSUE THREAD

**Issue by chppppp** [Azure/azure-storage-azcopy#596]
##### Note: The version is visible when running AzCopy without any argument

10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)

windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

`azcopy.exe copy "https://redacted.blob.core.windows.net/redacted/redacted.zip?st=saskeyredacted" "\\redacted.sharepoint.com@SSL\DavWWWRoot\sites\redacted\Shared%20Documents/" --overwrite=false --log-level ERROR`

### What problem was encountered?

`INFO: Cannot infer destination location of`

### How can we reproduce the problem in the simplest way?

try to copy a file from azure storage to sharepoint online

### Have you found a mitigation/solution?

no

**Comment by JohnRusk** [comment]
SharePoint online is not currently a supported destination.  (Was there something in our documentation that suggested it was?  If so, please let me know, and I'll correct the error in the docs)

**Comment by chppppp** [comment]
Thanks for the quick reply John. I do not have any supporting docs for this. Any chance there is an unsupported method to do this?

I am trying to copy some very large files from a local machine to sharepoint and the browser just isnt cutting it. 

thanks

**Comment by JohnRusk** [comment]
There's nothing that AzCopy can do to help there.  (Sorry).  I feel your pain re-browser-based uploads.  But I don't know the answer, sorry. Hopefully, a little more web searching for something like "upload large files to SharePoint online" might give you something useful.

**Comment by chppppp** [comment]
Thanks John
