### ISSUE TITLE
transferring of data stopped how can i continue and not to overwrite files that already uploaded

### ISSUE THREAD

**Issue by jethrogalolo** [Azure/azure-storage-azcopy#597]
### Which version of the AzCopy was used? 
10.2.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy cp
### What problem was encountered?
Can i continue transferring data that has been stopped that i don't have to  overwrite?
like sort of sync so i can continue what i had left off?

### How can we reproduce the problem in the simplest way?
I am transferring 40gb of data then suddenly it stop for some reason. i would like to continue and not to delete the files that was uploaded and reupload again. Is there any command that can do it?

**Comment by JohnRusk** [comment]
Have a look at the --overwrite parameter.  (Run `AzCopy copy --help` to see details)

I think `--overwrite=false` will do what you want.

**Comment by jethrogalolo** [comment]
Thank you John.

**Comment by JohnRusk** [comment]
Oh, I forgot to mention: there's also the resume feature, which lets you resume a job that has failed.  See `AzCopy resume --help` for details.  That's probably even better than what I first suggested (because it doesn't even need to check for existence of target files - it just reuses the "job plan" file from the original job, complete with file-by-file status as at the time it failed).  Sorry about not thinking of it first.

**Comment by jethrogalolo** [comment]
Hello,
I use the --overwrite parameter but i think it didn't uploaded the files. Please see azcopy result.
and for the azcopy resume where could i get the job ID?

![image](https://user-images.githubusercontent.com/53916531/65150262-5b945080-da56-11e9-9352-b51061bac6de.JPG)

**Comment by JohnRusk** [comment]
Yeah, looks like --overwrite wasn't as much of a good idea as I thought.  

The job id you need for resuming is shown in the output when the job runs.  You can also get a list of jobs, and their statuses and job ids by running `AzCopy jobs list`.  You'll need to look for your failed job in that list. (And if you find that job, and it says Succeeded, then maybe it didn't actually fail afterall...?)

**Comment by JohnRusk** [comment]
@jethrogalolo I'm assuming that the above information about resume has given you what you needed. If that's not the case, please let us know and we'll re-open this issue.
