### ISSUE TITLE
Issue when copying from a file share locally onto another file share

### ISSUE THREAD

**Issue by wilsonge** [Azure/azure-storage-azcopy#60]
##### Note: The version is visible when running AzCopy without any argument
10.0.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
./azcopy_linux_amd64 cp 'https://<fileshare:.file.core.windows.net/<share>/?<redacted_sas>&sharesnapshot=<snapshot>' '<different_azure_file_share>' --recursive=true

### What problem was encountered?
000 : File Creation Error operation not supported

### How can we reproduce the problem in the simplest way?
If I change the path from the CIFS share to the local directory the command works (i.e. saving onto the VM itself). But if I make the path something on a new empty windows cifs fileshare (i.e. restoring my snapshot onto a fresh share) I get errors

### Have you found a mitigation/solution?
No. But I believe it to be related to allocating memory for the file here https://github.com/Azure/azure-storage-azcopy/blob/500f2eec4b658a5294eef523b5802b19ba80f5b7/common/mmf_linux.go#L99

**Comment by jiacfan** [comment]
Hi, @wilsonge 

Thanks for reaching us and report the issue. 
This issue specifically happens in linux systems, where fallocate is not supported by cifs/smb3. We'll provide a fix to this issue, and will update this issue when related fix is released.

Thanks,
Jiachen

**Comment by wilsonge** [comment]
Awesome. Thanks!

**Comment by wilsonge** [comment]
Thanks! Sorry I've been taken off the part that involves this right now. But will try when I'm next able to and let you know!
