### ISSUE TITLE
403 Forbidden on AWS S3 to Blob Storage copy

### ISSUE THREAD

**Issue by goa5t** [Azure/azure-storage-azcopy#604]
### Which version of the AzCopy was used? 
10.2.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy cp https://s3.amazonaws.com/<bucket_name>/ https://<storage_account_name>.blob.core.windows.net/<blob_container_name>/ --recursive=true --log-level=DEBUG
### What problem was encountered?

COPYFAILED: https://s3.amazonaws.com/<bucket_name>/map.pdf : 403 : 403 Forbidden. When Staging block from URL. X-Ms-Request-Id: 0d1bfbe1-001e-0118-7db6-6fb134000000

### How can we reproduce the problem in the simplest way?

I'm getting this when attempting to copy the contents of an S3 bucket running azcopy on an EC2 instance. The instance has an IAM role attached to it which has all S3 privileges

### Have you found a mitigation/solution?

I can run the exact same command, with the same account/login procedure, locally on my laptop.
[azcopy_log.txt](https://github.com/Azure/azure-storage-azcopy/files/3636154/azcopy_log.txt)

Worth mentioning that I set the following environment variables on the EC2:
export AWS_ACCESS_KEY_ID=

export AWS_SECRET_ACCESS_KEY=

export AWS_SESSION_TOKEN=

I'm not sure where the issues lies, but in the effort of troubleshooting:

1. I was able to run 'azcopy make ...' and could successfully make a blob in Azure, so the Azure authentication is working properly.

2. I was able to access the S3 bucket using the AWS CLI from the EC2 (which has the IAM role attached to it)

Any help appreciated. Thanks

**Comment by zezha-msft** [comment]
Hi @goa5t, thanks for reaching out!

Could you please double check whether you could upload local files to the container with the same login info?

**Comment by goa5t** [comment]
I was able to copy files from s3 using the aws cli to a local directory on the EC2

e.g. `aws s3 sync s3://<bucket name> ./<local_dir>`

And then could copy those files to the blob container using azcopy successfully

e.g. `azcopy copy <local_dir> "https://<storage-account-name>.blob.core.windows.net/<container-name>/<blob-name>"

**Comment by goa5t** [comment]
I should also mention that I'm authenticating to Azure via service principal, and that SPN has the Storage Blob Data Contributor role added to it.

**Comment by zezha-msft** [comment]
Thanks for the info @goa5t!

We'll try to get a repro on our end.

**Comment by goa5t** [comment]
Thanks! Let me know if you need additional information.

**Comment by RajasGujarathi** [comment]
Seems related to #1428 and the workaround mentioned in #1428 can help fix the issue

**Comment by adreed-msft** [comment]
Not really related no.

> I should also mention that I'm authenticating to Azure via service principal, and that SPN has the Storage Blob Data Contributor role added to it.

From EC2?

Btw, sorry for the long time with no response-- I doubt it, but are you still blocked on this issue?

**Comment by goa5t** [comment]
No longer blocked, no. Project was deprioritized and not pursued further.

Feel free to close the issue; it's very likely it was a networking issue on our end; I vaguely recall running into problems hitting the Azure API endpoints due to routing issues.
