### ISSUE TITLE
azcopy cp azure_blob azure_blob

### ISSUE THREAD

**Issue by aaaaasam** [Azure/azure-storage-azcopy#612]
![image](https://user-images.githubusercontent.com/29201609/65699697-0937dd00-e0b1-11e9-8737-156961de8553.png)

but i can download this snapshot file(1024G);
![image](https://user-images.githubusercontent.com/29201609/65699819-3d130280-e0b1-11e9-8dd1-beb98ff1258e.png)

**Comment by adreed-msft** [comment]
Hi there, @aaaaasam. I noticed you're trying to set an access tier on your page blob. P30 happens to be a premium page blob tier-- if your destination container is _not_ a premium container (or you're trying to copy to any other type of blob), I believe you cannot set this tier.

To work around this, I'd suggest adding the following flag to your azcopy command:
```
--s2s-preserve-access-tier=false
```

If you still wish to set a custom access tier for the destination blob, we currently don't support this in s2s scenarios (@JohnRusk or @zezha-msft  is this a PBI?); but you could work around it by downloading and then uploading with the relevant access-tier flags.

**Comment by adreed-msft** [comment]
Furthermore, in the upcoming release, if there is a failure to set blob tier, you'll be notified via stdout and your log file that the blob failed to replicate blob tier at the destination.

**Comment by JohnRusk** [comment]
@adreed-msft Did we never support setting command-line specified tiers for S2S?  Can you do a test please, to check, using 10.2.1

**Comment by adreed-msft** [comment]
![image](https://user-images.githubusercontent.com/49764384/65724889-3b701d00-e066-11e9-942c-136a076b1b48.png)
this is on dev, so no we never supported it.

**Comment by JohnRusk** [comment]
@adreed-msft  Pls Master, not dev. (Or check dev as at the 10.2.1 tag; but not latest dev)

**Comment by JohnRusk** [comment]
(Just to make sure)

**Comment by aaaaasam** [comment]
![image](https://user-images.githubusercontent.com/29201609/65731272-a1f14b80-e0f7-11e9-8e0c-16a618c6316e.png)
Thank you @adreed-msft , Is Working when i test it.

I also saw similar people have such problems.

https://social.technet.microsoft.com/Forums/windowsserver/en-US/d0e4bbda-913d-44cf-851b-bed67f5854c2/azure-storage-amp-azcopy-v10-how-to-copy-a-blob-to-another-storage-account-error?forum=windowsazuredata
