### ISSUE TITLE
[question] can we use proxy on v10?

### ISSUE THREAD

**Issue by nmikuni** [Azure/azure-storage-azcopy#62]
##### Note: The version is visible when running AzCopy without any argument
considering to use v10

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What problem was encountered?
it's the question.
I want to use proxy as in Windows
(i.e. https://blogs.msdn.microsoft.com/azure4fun/2016/10/17/azcopy-unable-to-connect-to-the-remote-server/ )

Seen the code, it looks to use the system proxy. can't user change as they want?
https://github.com/Azure/azure-storage-azcopy/blob/master/common/oauthTokenManager.go#L69

If there are any way to set the own proxy, I really want to know how. Thanks,

**Comment by zezha-msft** [comment]
Hi @nmikuni, thanks for reaching out!

We currently do not support proxies, I'll add this feature to our backlog.

**Comment by technowannabe** [comment]
Hi. The proxy capability is a must for our use as well. We are actively using AzCopy 7.x and 8.x. Thank you!

**Comment by zezha-msft** [comment]
Hi @technowannabe, thanks for reaching out!

The proxy setting should be supported by the Go Client already, we just need to test it. If you would like to try it, please set the environment like follows: `export HTTP_PROXY="http://proxyIp:proxyPort"`.

**Comment by seguler** [comment]
This is now fixed. The documents have been updated with the proxy config.

**Comment by technowannabe** [comment]
> Hi @technowannabe, thanks for reaching out!
> 
> The proxy setting should be supported by the Go Client already, we just need to test it. If you would like to try it, please set the environment like follows: `export HTTP_PROXY="http://proxyIp:proxyPort"`.

Hi @zezha-msft, thanks for considering and implementing this quickly!

I've tried it for one of my projects and it seems to work well so far.

--Todd
