### ISSUE TITLE
Missing feature for copy empty folders

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-storage-azcopy#626]
i would really appreachiate an option to enforce copying/syncing of empty folders.

E.g. = —ignoreemptyfolders=false

**Comment by zezha-msft** [comment]
Hi @Gill-Bates, thanks for reaching out! I've logged this item and we'll schedule it as soon as prioritization permits us.

**Comment by davidt99** [comment]
Why is this not the default? We ran into problems, only finding out later this issue.
**This is not a feature, this is a bug**, when I run copy command, on any OS, I expect everything to be copied from the source to the destination. Frustrating.

**Comment by JohnRusk** [comment]
We're working on adding folder support now. (So far, AzCopy's internal work lists contain only files, which is why it can't process empty folders.  We're changing it so that it can also put folders into those work lists).

Question: do you think that there needs to be an ignoreemptyfoders flag (as above) or should it just _always process empty folders, with no need for a flag?

**Comment by davidt99** [comment]
@JohnRusk Thanks for the update. I think it should be the default, I don't see any reason to skip copying empty folders.
And sorry if I was a bit harsh.

**Comment by davidt99** [comment]
@JohnRusk, any update regarding timeline? I just wanted to know whether should I start working on a workaround for this issue or it's will be available on the next version.

**Comment by JohnRusk** [comment]
It's scheduled for 10.4, which is our next planned release. I don't have any update on likely timing, sorry

**Comment by JohnRusk** [comment]
And now that the 10.4 work applies specifically to Azure Files (not blob)

**Comment by adreed-msft** [comment]
Hi there! 10.4 has now released, and this is supported for Azure Files and Azure Data Lakes Gen 2 (via the dfs endpoint).
