### ISSUE TITLE
--cap-mbps is not working as intended

### ISSUE THREAD

**Issue by dineshazure** [Azure/azure-storage-azcopy#628]
### Which version of the AzCopy was used? 
AzCopy 10.2.1
##### Note: The version is visible when running AzCopy without any argument
Yes
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux - Ubuntu 18.04
### What command did you run?
./azcopy --cap-mbps 100
### What problem was encountered?
While running the command it give same output as ./azcopy
### How can we reproduce the problem in the simplest way?
We are trying to reduce the bandwidth utilization of azcopy . When 2 users uses this azcopy server goes not responding and other users lose the access
### Have you found a mitigation/solution?
I believe --cap-mbps should work but not sure if I am doing it correct way

**Comment by JohnRusk** [comment]
The syntax is to add --cap-mbps xxx to whatever the actual command is that you want to run. E.g.

```
./azcopy copy /myfiles 'https:/….' --recursive --cap-mbps 100
```
Does that help?

**Comment by JohnRusk** [comment]
Closing because I assume the suggest above was enough to resolve the issue.

**Comment by dineshazure** [comment]
Hello John,

It is working after adding the parameter. Thanks for the help!
