### ISSUE TITLE
sync incorrectly instructs to use --from-to switch

### ISSUE THREAD

**Issue by SteveBurkettNZ** [Azure/azure-storage-azcopy#631]
### Which version of the AzCopy was used? 
10.2.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy.exe sync c:\dir https://website

### What problem was encountered?
Throws an :
> INFO: Cannot infer destination location of https://website. Please specify the --from-to switch

But the **--from-to** switch mentioned at the end of the info is not supported with the **sync** command? ([Docs Ref](https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync#options))

Running the command again with a **--from-to LocalBlob**  tacked on the end of the command results in :

> Error: unknown flag: --from-to

**--from-to** is supported for the **copy** command though. ([Docs Ref](https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy#options))

### How can we reproduce the problem in the simplest way?
Run **azcopy.exe sync c:\dir https://website**
### Have you found a mitigation/solution?
No.

**Comment by mohsha-msft** [comment]
Hey @SteveBurkettNZ ,

Can you please repro this issue in the newer versions of AzCopy. I believe we've fixed it. If the issue persists, please reopen this issue.
