### ISSUE TITLE
azcopy - copy local directory into an azure blob store

### ISSUE THREAD

**Issue by drauch** [Azure/azure-storage-azcopy#633]
I try to move a whole Azure Blob Storage (all containers and all blobs) to my local dev machine's Storage Emulator for debugging purposes.

I already have a script which downloads all containers and all their blobs into a local directory. I'm using a combination of Get-AzureStorageContainer & azcopy container->directory (--recursive).

Now I want to use azcopy to re-upload them into my storage emulator's blob storage. But I always run into the error below. According to https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs?toc=%2fazure%2fstorage%2fblobs%2ftoc.json#upload-files it should be a supported scenario (see chapter Upload a directory)

### Which version of the AzCopy was used? 
10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
. "$PSScriptRoot\azcopy.exe" copy "$dir\$container" "http://127.0.0.1:10000/devstoreaccount1/$container" --recursive

### What problem was encountered?
failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

### How can we reproduce the problem in the simplest way?
Try to import a whole directory into a blob store container

### Have you found a mitigation/solution?
No.

**Comment by JohnRusk** [comment]
Add this to the command line:  --fromTo LocalBlob

That _should_ fix it.... I think.  (And I think a better fix is coming in release 10.3)

**Comment by drauch** [comment]
Unfortunately this gives me `unknown flag: --fromTo` and a usage message. Any other ideas? A typo maybe?

**Comment by JohnRusk** [comment]
Sorry, silly me. It's `--from-to LocalBlob`

(note the dash between from and to, which I missed out the first time)

**Comment by drauch** [comment]
That worked, thanks!

**Comment by drauch** [comment]
(you should probably put that flag into the docs though :-) )

**Comment by SteveBurkettNZ** [comment]
It is listed on the [docs](https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy#options) page, but easily missed as there's a fair number of options available there. 

Under certain circumstances AzCopy gives additional info along with the error, suggesting you use the from-to flag, but obviously not in this case.

**Comment by drauch** [comment]
Hmm - one more question though, it didn't work as expected. Now I'm always running into "Failed" PUT statements - according to the log:

```
RESPONSE Status: 404 The specified resource does not exist.
   Content-Length: [223]
   Content-Type: [application/xml]
   Date: [Thu, 03 Oct 2019 17:38:30 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [ResourceNotFound]
   X-Ms-Request-Id: [b2880a94-5edc-472b-9d26-94c3b741aa47]
   X-Ms-Version: [2018-03-28]
```

I tried the following commands:
```
copy C:\Temp\ContainerDirectory1 http://127.0.0.1:10000/devstoreaccount1/ --recursive --from-to LocalBlob

// as well as:
copy C:\Temp\ContainerDirectory1 http://127.0.0.1:10000/devstoreaccount1/CotainerDirectory1 --recursive --from-to LocalBlob
```

Is there a catch? Is it not possible to upload a directory and its contents as a container and its blobs?

**Comment by drauch** [comment]
I gave it now a try by using a SAS account token, didn't help either. It now returns with `RESPONSE Status: 404 The specified container does not exist.` - slight difference to before where the resource didn't exist and not the container. BUT of course it does not exist, I'm trying to upload it at this moment...

**Comment by JohnRusk** [comment]
I'm actually not sure!  It's not a super-common usage pattern. THe more common one for uploads is to create the container first, then upload into it.  We support container creation for account-to-account copies, but I'm not sure whether we do for uploads.

@adreed-msft Do you know what 10.3 will support?  Can you upload to a container that does not yet exist?

Finally @drauch, it is possible that there's some issue specifically to do with targeting the emulator, that I don't know about.  So if you try creating the container first and that still doesn't work, please let us know and we'll log a bug against our emulator support.

**Comment by drauch** [comment]
> He more common one for uploads is to create the container first, then upload into it.
OK, this actually works. Thanks so much for the fast replies!

Best regards,
D.R.

**Comment by JohnRusk** [comment]
Great. Will leave this open until @adreed-msft  confirms the 10.3 behaviour, so that we know whether to add something to our backlog to help customers who try it without making the container (even just a clearer error message); or if 10.3 in fact makes it work to upload without an existing container. 

For now, glad to know its working for you.

**Comment by JohnRusk** [comment]
@adreed-msft can you check the comment above pls?
