### ISSUE TITLE
Issues with log level setting version 10.2.1 on centos 8

### ISSUE THREAD

**Issue by damo2929** [Azure/azure-storage-azcopy#634]
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux Centos 8.0 

azcopy --version
azcopy version 10.2.1

### What command did you run?
 azcopy sync source target --recursive --log-level PANIC

### What problem was encountered?
log-level doesn't work as documented regardless of level the same amount of data is written to the log.

### How can we reproduce the problem in the simplest way?

 azcopy sync source target --recursive --log-level PANIC
look at syslog more information than panics is being written.

it's defaulting to INFO regardless of why I set.

**Comment by JohnRusk** [comment]
The log level parameter only controls what is written to the applications own log file.  (the one whose name appears near the start of the on-screen output, and is based on the job id).

There is currently no way to control what is written to Syslog, although writing to sys log is reduced by PR #502 , which will be included in version 10.3.  Do you think that change will be enough to address what you need?

**Comment by damo2929** [comment]
it could do, when is the release due ?

**Comment by JohnRusk** [comment]
Soon.  (We don't currently publish target dates, or revised dates, for AzCopy.)

**Comment by gapra-msft** [comment]
Hi @damo2929 it looks like your issue may have been resolved by the linked PR above so I will go ahead and close this issue. If you do still have the problem, please feel free to reopen the issue or create a new one.
