### ISSUE TITLE
parameter to suppress  2-sec Throughput (Mb/s)

### ISSUE THREAD

**Issue by damo2929** [Azure/azure-storage-azcopy#636]
When using azcopy in a script I only want to see that files are completed, I don't need to see  2-sec Throughput (Mb/s) as it makes the outputs large.

**Comment by JohnRusk** [comment]
Good idea.

**Comment by hho** [comment]
Probably related to #534 

For everyone else coming here via Google: My current workaround is piping through `grep -v "2-sec Throughput"`. That keeps the output volume small, yet leaves the summary intact.

**Comment by nakulkar-msft** [comment]
Same as #534
