### ISSUE TITLE
Optional Arguments in Azure file copy Task

### ISSUE THREAD

**Issue by skamoda** [Azure/azure-storage-azcopy#654]
### Which version of the AzCopy was used? 
v10

### Which platform are you using? 
pool: Hosted VS2017

### What command did you run?
azcopy

### What problem was encountered?
I was redirected from https://github.com/microsoft/azure-pipelines-tasks to this repo. I am working with azure file copy Task in azure pipelines (agent pool: Hosted VS 2017). I added to optional arguments (for uploading files to blob) `cache-control` flag. I tried multiple variation of that flag (including `--cache-control` according to help command). Every time I got:
`[ERROR] The syntax of the command is incorrect. The option "--cache-control=no-cache" is not recognized.` 
My question is how can I set this argument (I mean similar to, for example, `/SetContentType` or `/BlobType:Page`)?

### How can we reproduce the problem in the simplest way?
Add azure task to pipeline and `--cache-control` flag to `Optional Arguments` in azure file copy Task

### Have you found a mitigation/solution?
Not yet

**Comment by JohnRusk** [comment]
AzCopy versions 8.1 and earlier use a slash-based syntax (e.g. /BlobType:Page) but version 10 (which is a complete re-write) has switched to a double dash syntax. E.g. --blob-type PageBlob.

I suspect you are running with version 8.1 or earlier. You'll need to consult the documentation for that version, to see if it has the parameter you want. Seee https://docs.microsoft.com/en-us/previous-versions/azure/storage/storage-use-azcopy

**Comment by JohnRusk** [comment]
I believe the above comment resolves this issue. If not, please comment and I'll re-open it.
