### ISSUE TITLE
Azcopy sync between blobs not working

### ISSUE THREAD

**Issue by amankohli** [Azure/azure-storage-azcopy#671]
### Which version of the AzCopy was used? 
azcopyv10 linux

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
 azcopy sync "https://<storage-account-name>.<blob or dfs>.core.windows.net/<container-name>?sastoken" "https://<storage-account-name>.<blob or dfs>.core.windows.net/<container-name>?sastoken" --recursive

### What problem was encountered?

Sync is not supported for Blob to blob transfer

### How can we reproduce the problem in the simplest way?
By executing the above command

### Have you found a mitigation/solution?
no

**Comment by JohnRusk** [comment]
Blob to blob sync is coming very soon in version 10.3

**Comment by JohnRusk** [comment]
Version 10.3 is now released.
