### ISSUE TITLE
Feature request to get the --list-of-files function added to the copy command

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-storage-azcopy#678]
azcopy version 10.3.0

Feature request to get the --list-of-files function added to the copy command

#585

**Comment by JohnRusk** [comment]
It's already there. We just don't list it in the parameter list, but it works. (we're trying to steer folks towards - - include-path, which is the same functionality but in-line on the command line).

Maybe we should document list of files too. 

In any case, it works for copy and you can use it.

**Comment by nofunatall** [comment]
I just tried it and it works.

It just doesn't show up at all in azcopy copy --help

The include file has it's own use case rather then using in-line on command line being that there is always a max arg/character/word limit for commands within any shell - Works fine until you need to specify thousands of items to copy/delete then you need to use a file list.

This is the only way sane way to quickly do a bulk copy/delete operation on a large number of specific items.

**Comment by JohnRusk** [comment]
Reopening to remind us (the project team) to think about your comments re documenting it.

**Comment by malthe** [comment]
Here's a feature proposal issue I wrote just now which generalizes a little on this idea: #1073.
