### ISSUE TITLE
Download specific version of AZCopy

### ISSUE THREAD

**Issue by EvertEt** [Azure/azure-storage-azcopy#680]
##### Note: The version is visible when running AzCopy without any argument
10.3.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy sync ...`
### What problem was encountered?
`unknown flag: --include`

### How can we reproduce the problem in the simplest way?
Download the latest version and have code written for 10.2.1
### Have you found a mitigation/solution?
Not yet. Is there any way to provide fixed links per version? This is blocking our entire pipeline since we download a fresh copy for every processing job.

**Comment by adreed-msft** [comment]
Hi there, --include has been renamed to --include-pattern

**Comment by EvertEt** [comment]
Can we just change the flag without anything breaking? We would prefer sticking with the old version until we can test the changes.

**Comment by adreed-msft** [comment]
The functionality is the exact same for sync.

**Comment by EvertEt** [comment]
Thank you for the quick answers. I will try to upgrade our code as a quick-fix then. For the future, it would still be nice to have download links per version as breaking versions can disrupt a lot, I think?

**Comment by adreed-msft** [comment]
Understandable. I'll tag this issue as distribution related. If you need access to the old revision, the container is public, so I can link you to the old revision to tide you over until your code is ready

**Comment by EvertEt** [comment]
Thank you. That would be nice!

**Comment by JohnRusk** [comment]
One important thing : if your include pattern only relates to filenames (eg a*.txt) then the new include-pattern parameter should do the same job.  But if your parameter value includes path components (eg. mydir\b.txt) then you can't just change the parameter name, since include-pattern only applies to the file name (not path). That's why there's been a name change.

**Comment by JohnRusk** [comment]
The recommended procedure for downloading specific versions is documented here https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#use-azcopy-in-a-script

**Comment by zezha-msft** [comment]
@EvertEt Here is the [download link](https://azcopyvnext.azureedge.net/release20190703/azcopy_linux_amd64_10.2.1.tar.gz) for 10.2.1.

Sorry for the inconvenience. In the future, please follow the docs link that John shared so that you could pin to a specific version. Thanks!

**Comment by zffocussss** [comment]
> @EvertEt Here is the [download link](https://azcopyvnext.azureedge.net/release20190703/azcopy_linux_amd64_10.2.1.tar.gz) for 10.2.1.
> 
> Sorry for the inconvenience. In the future, please follow the docs link that John shared so that you could pin to a specific version. Thanks!

Hi zezha:
     is there a release list for binary/executable azcopy on a web page?

**Comment by zezha-msft** [comment]
Hi @zffocussss, no, only the latest version is shown on the download page. May I ask why you'd want an older version?

**Comment by theOxifier** [comment]
I know this is an old issue, but I still can't find a link that lets me download a specific version of azcopy.

**Comment by ostronaut** [comment]
> I know this is an old issue, but I still can't find a link that lets me download a specific version of azcopy.

The same problem here. Was trying to find it but didnt succeed.

**Comment by theOxifier** [comment]
I did figure out how to get it finally

https://azcopyvnext.azureedge.net/release<yyyymmdd>/azcopy_linux_amd64_<XX.YY.Z>.tar.gz

You can find the date and release information from the releases section on the repo.

Sometimes the day is just a little off so you have to increase or decrease the date by a day or so.

**Comment by jonaski** [comment]
Whats the download link to 10.18.1?

**Comment by ostronaut** [comment]
> Whats the download link to 10.18.1?

https://azcopyvnext.azureedge.net/release20230123/azcopy_linux_amd64_10.17.0.tar.gz 

this one is for 10.17.0, but you can adjust it for your version.
Note: be sure to change release day

**Comment by jonaski** [comment]
I know that, but I can't find a working URL for 10.18.1.
I get the previous version (10.18.0) to work, URL: https://azcopyvnext.azureedge.net/release20230331/azcopy_linux_amd64_10.18.0.tar.gz

But not 10.18.1, tried https://azcopyvnext.azureedge.net/release20230424/azcopy_linux_amd64_10.18.1.tar.gz and +/- 3 days for the date.

**Comment by nakulkar-msft** [comment]
Here is 10.18.1
https://azcopyvnext.azureedge.net/release20230420/azcopy_linux_amd64_10.18.1.tar.gz

**Comment by jonaski** [comment]
@nakulkar-msft Thanks

**Comment by parisiannoelia** [comment]
can someone please share link of 10.2.1 for mac supported one?
