### ISSUE TITLE
Wiki: "Cost of data transfers" page does not mention bandwidth pricing

### ISSUE THREAD

**Issue by seankwilliams** [Azure/azure-storage-azcopy#681]
##### Note: The version is visible when running AzCopy without any argument
n/a

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
n/a

### What problem was encountered?
When visiting the page at https://github.com/Azure/azure-storage-azcopy/wiki/Cost-of-data-transfers, bandwidth-related pricing is not mentioned even though, I believe, it does apply to data transfers.

### How can we reproduce the problem in the simplest way?
Visit https://github.com/Azure/azure-storage-azcopy/wiki/Cost-of-data-transfers

### Have you found a mitigation/solution?
Modify the Wiki page to mention that the bandwidth pricing at https://azure.microsoft.com/en-us/pricing/details/bandwidth/ may apply to transfers between storage buckets.

**Comment by adreed-msft** [comment]
I've updated the relevant details on the wiki page to contain this information. Does this resolve your issue?

**Comment by seankwilliams** [comment]
It does, thank you @adreed-msft ! I'll close this out.
