### ISSUE TITLE
Allow anything to be uploaded as a page blob/VHDs as block blobs

### ISSUE THREAD

**Issue by MRayermannMSFT** [Azure/azure-storage-azcopy#69]
### Which version of the AzCopy was used? 
10.0.2-preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

Currently, VHDs are always uploaded as page blobs, and everything else is always uploaded as block blobs. It'd be nice if there was a way to override those defaults.

**Comment by zezha-msft** [comment]
Fixed with the flag `--blobType`.

**Comment by MRayermannMSFT** [comment]
Nice!!! Thanks Ze!!! 😍
