### ISSUE TITLE
--exclude-path invalid/unknown flag error

### ISSUE THREAD

**Issue by MSTRcloud** [Azure/azure-storage-azcopy#691]
### Which version of the AzCopy was used? 
Azcopy 10.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
/usr/local/bin/azcopy sync https://<valid-storage-account>.blob.core.windows.net/<container-name>/ /local/dir/ --exclude-path "configs/*"

### What problem was encountered?
--exclude-path : unknown flag

### How can we reproduce the problem in the simplest way?
Run the command using azcopy v10.3

### Have you found a mitigation/solution?
No

**Comment by adreed-msft** [comment]
Sync does not feature --include/exclude-path.

**Comment by JohnRusk** [comment]
@zezha-msft Is this something which makes sense (conceptually) for Sync?  If so, let's mark it as a feature request.

**Comment by zezha-msft** [comment]
@JohnRusk sure, I'm not sure that include-path makes sense in the context of sync, but I can definitely see --exclude-path being useful sometimes.

**Comment by JohnRusk** [comment]
10.3.3. has just been released, and supports `--exclude-path` in sync
