### ISSUE TITLE
azcopy list is listing too many blobs (repeating output)

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-storage-azcopy#692]
azcopy v10.3.0

If running azcopy list on a blob account/container does this function also list deleted blobs and files from snapshots?
Seems like it does as I listed and grepped on a container/virtual folder and had millions and millions of results when I know for a fact that virtual folder is not anywhere near that large.

If list is actually listing deleted files/snapshot files then I would like to request a feature where we can toggle that behavior on and off with the default setting being off.

e.g
azcopy list --show-deleted "https://[srcaccount].blob.core.windows.net/[container]?[SAS]"

**Comment by JohnRusk** [comment]
I've just checked, by running a list command against a container with one blob that has one snapshot.  It did not show the snapshot. 

I also checked the code, and it specifically does _not_ request deleted blobs or snapshots when listing.

On that basis, it seems likely that there might be something else going in in your case - i.e. some other reason for the unexpectedly high count.   I'm not sure what to suggest as a next step... maybe try on a smaller container where you're able to more easily drill into any discrepancies...?

**Comment by nofunatall** [comment]
Should also note that using az-cli:
az storage blob list
Results in a drastically lower number of total blobs.

```
user@ubuntu:~$ azcopy list "https://${SRC_ACC}.blob.core.windows.net/${SRC_CONT}/${PREFIX}${SRC_SAS}" | wc -l
272711
```
```
tm-admin@test-env01-syd-vm:~$ az storage blob list --num-results "*" --account-name "$SRC_ACC" --account-key "$SRC_KEY" --container-name "$SRC_CONT" --prefix "brandimages" --output tsv --query "[][name]" | wc -l
Next Marker:
2!120!MDAwMDQ0IWJyYW5kaW1hZ2VzLzFiMmE4Mjg4NDM2MGI4ZDY2ODdjNDg4ZjVjZGYxZjFhITAwMDAyOCE5OTk5LTEyLTMxVDIzOjU5OjU5Ljk5OTk5OTlaIQ--
47711
```

**Comment by JohnRusk** [comment]
What's that "next marker" it's displaying at the end? I would have expected NextMarker to be empty/null after the final call, to indicate that there are no more results.  In the underlying REST API, a non-empty NextMarker indicates that there are more results which have not yet been retrieved.  I wonder if az storage blob list is actually not fully enumerating the container in this case.... (that would be an unexpected feature/bug, and I'd be surprised if such a behavior existed... but that marker that's shown does make me wonder.)

**Comment by nofunatall** [comment]
I could loop it until it properly finishes but here look at this.
```
user@ubuntu:~$ azcopy list "https://${SRC_ACC}.blob.core.windows.net/${SRC_CONT}${SRC_SAS}" > ${SRC_ACC}.list
user@ubuntu:~$ sudo du -h azure_blob_account.list 
509G	${SRC_ACC}.list
```

The list alone is 509GB
That is not right.

**Comment by JohnRusk** [comment]
OK. I'm asking around here (Microsoft) to see what our best next step is to diagnose what's going on.

**Comment by JohnRusk** [comment]
If you want to try something while we wait, you could try "downloading" the container with AzCopy v8 and the /L flag. It looks like that should just count the blobs and tell you how many there are.  It's a different codebase from V10, so will be a good way to prove the nature of the issue.

**Comment by JohnRusk** [comment]
Best suggestion so far is to check the count shown either by AzCopy v8 or by the Azure Storage metrics described here: https://docs.microsoft.com/en-us/azure/storage/common/storage-metrics-in-azure-monitor?toc=%2fazure%2fstorage%2fblobs%2ftoc.json, to prove that one of those tools is giving a substantially lower count.
The Azure storage metrics approach is only relevant here if there are no other high-blob-count containers in the same account, because it works at container level.

**Comment by JohnRusk** [comment]
I've managed to reproduce this. It is listing far too many files by, somehow, repeating itself. And I have good news: @adreed-msft has already written code that fixes it, in this PR #682.  That's scheduled for inclusion in release 10.4.

**Comment by JohnRusk** [comment]
BTW, I'm going to edit the title, since I believe it does not relate to snapshots, but rather to some incorrect repetition of result sets.

**Comment by JohnRusk** [comment]
https://github.com/Azure/azure-storage-azcopy/pull/682

**Comment by JohnRusk** [comment]
In 10.3.3. we replaced the old list implementation with the scan code that is used by copy and sync. That does not have the duplication issues.
