### ISSUE TITLE
Does it really work for azure file storage?

### ISSUE THREAD

**Issue by dkmbw** [Azure/azure-storage-azcopy#698]
### Which version of the AzCopy was used? 
10 as described in https://docs.microsoft.com/de-de/azure/storage/common/storage-use-azcopy-v10?toc=%2fazure%2fstorage%2ffiles%2ftoc.json
### Which platform are you using? (ex: Windows, Mac, Linux)
linux
### What command did you run?
azcopy cp "$THE_URL" testdata --recursive

### What problem was encountered?
nothing really works.
### How can we reproduce the problem in the simplest way?
i have no idea.
### Have you found a mitigation/solution?
no

I have the problem that i tried azcopy for a kubernetes pvc which is a azure file storage and nothing really works. i am really unsure how to get the SAS-Token and concatenate it with the directory-URL. Is there some concrete example as a script somewhere which you could document? are there ip-based restrictions? can i execute it from my own home-network? do i need to snapshot the kubernetes pvc? i tried different things, nothing works and others i asked had the same problem? :/ perhaps it works only WITHIN azure?

Sorry, but i am at a loss.

**Comment by adreed-msft** [comment]
Yes, AzCopy supports Azure Files.

To obtain a SAS token, I'd recommend using Azure Storage Explorer for a more user friendly experience (though you could use one of our many SDKs, Azure CLI, etc. Etc.)

 As to concatenating the SAS token to the URL, Storage explorer (when generating a share or file (and container or blob) level URL) already does this for you. If you wish to use a service level SAS, simply append it to the end of your URL, ensuring a ? separates the URI and the token.
