### ISSUE TITLE
When output=json is used for copy, some errors aren't outputted in a JSON friendly way

### ISSUE THREAD

**Issue by MRayermannMSFT** [Azure/azure-storage-azcopy#70]
### Which version of the AzCopy was used? 
10.0.2-preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?

I ran  

`copy "C:\Users\marayerm\Desktop\*" "https://redacted.blob.core.windows.net/one/?REDACTED" --overwrite=false --follow-symlinks --recursive --fromTo=LocalBlob --include "New Text Document.txt;" --output=json` 

when there is no file at `C:\Users\marayerm\Desktop\New Text Document.txt`

### What problem was encountered?
Although `output=json` was specified, the output I received was `failed to perform copy command due to error: cannot start job due to error: nothing can be uploaded, please use --recursive to upload directories.`, which is not JSON. I have seen other situations where this happens, but this is the easiest to reproduce. Basically, if `output=json` is used, then all output should be formatted as JSON objects.
### How can we reproduce the problem in the simplest way?
Try to do a copy where the source does not exist.
### Have you found a mitigation/solution?
No.

**Comment by zezha-msft** [comment]
@MRayermannMSFT thanks for reporting this issue!

I've logged it to be fixed.

**Comment by MRayermannMSFT** [comment]
Another scenario where this happens is when uploading an empty folder.

**Comment by MRayermannMSFT** [comment]
This also happens if you do not have permissions to read the contents of the blob container/file system.

**Comment by zezha-msft** [comment]
Fixed in 10.0.8.
