### ISSUE TITLE
undefined: pipeline.LogSanitizer

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-storage-azcopy#703]
I am getting an error when trying to compile:
```
$  git log HEAD -1
commit 5b1d5ad4e97fafb0885726a6868e98e50b4e759a (HEAD -> master, tag: v10.3.1, origin/master, origin/HEAD)
Merge: f825ee4 dd5f21f
Author: Ze Qian Zhang <zezha@microsoft.com>
Date:   Thu Oct 17 18:11:53 2019 -0700

    Merge pull request #702 from Azure/dev

    10.3.1 Release

$  go version
go version go1.11.5 linux/amd64

$  go build
# github.com/Azure/azure-storage-azcopy/common
../../../go/src/github.com/Azure/azure-storage-azcopy/common/lifecyleMgr.go:72:23: undefined: pipeline.LogSanitizer
```

**Comment by JohnRusk** [comment]
We're building with go1.12.x these days, using go mod for depedencies.

The issue you're getting is related to a dependency.  If I recall correctly, go.mod support changed between 11 and 12. (I can't remember whether the change was about it being present, or about it being the default).

I think that if you complie with go 1.12.x, it will automatically use the go.mod file and all will be well.  If that's not the case, let me know and I'll look into it more.

**Comment by johanburati** [comment]
Thanks, for the quick reply, I just installed go 1.13 and was able to compile it.
