### ISSUE TITLE
Queue and table storage

### ISSUE THREAD

**Issue by Hong-Revo** [Azure/azure-storage-azcopy#706]
Hi, do you guys have any plans to support queue and/or table storage?

It looks like the product is pretty much feature-complete, but I thought I should confirm.

**Comment by zezha-msft** [comment]
Hi @Hong-Revo, thanks for reaching out!

Not for table, but we'd be interested in hearing your scenarios for Queue!

**Comment by Hong-Revo** [comment]
Well, it's not technically my scenario for queue....

I have basically a mini-SDK for R, here: https://github.com/Azure/AzureStor

A couple of users have requested queue support: Azure/AzureStor#14

If azcopy doesn't plan to support queues, I will probably end up creating a separate package for it (but importing AzureStor for the basic transport calls).

**Comment by zezha-msft** [comment]
Ah I see, thanks for leveraging AzCopy in your SDK! @Hong-Revo 

We could perhaps provide a new command to interact with Queue. @rishabpoh thoughts?
