### ISSUE TITLE
Vague error when writing to destination

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-azcopy#71]
##### Note: The version is visible when running AzCopy without any argument
10.0.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux 16.04

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
./azcopy cp "https://cjwstorage.blob.core.windows.net/dltest/" /mnt --recursive

### What problem was encountered?
The logs said 'No such file or directory'. I expected it to say 'no permission to write to destination' or something

2018/10/03 20:43:26 ERR: [P#0-T#2096] DOWNLOADFAILED: https://cjwstorage.blob.core.windows.net/dltest/2631.bin?se=2018-10-14t04%3A28%3A12z&sig=REDACTED&sp=rwdlacup&spr=https%2Chttp&srt=sco&ss=bfqt&st=2018-10-02t20%3A28%3A12z&sv=2017-11-09 : 000 : File Creation Error open /mnt/dltest/2631.bin: no such file or directory
   Dst: /mnt/dltest/2631.bin
2018/10/03 20:43:26 ERR: [P#0-T#2100] DOWNLOADFAILED: https://cjwstorage.blob.core.windows.net/dltest/8732.bin?se=2018-10-14t04%3A28%3A12z&sig=REDACTED&sp=rwdlacup&spr=https%2Chttp&srt=sco&ss=bfqt&st=2018-10-02t20%3A28%3A12z&sv=2017-11-09 : 000 : File Creation Error open /mnt/dltest/8732.bin: no such file or directory
   Dst: /mnt/dltest/8732.bin
2018/10/03 20:43:26 ERR: [P#0-T#2100] /mnt/dltest/8732.bin: 0: Delete File Error -remove /mnt/dltest/8732.bin: no such file or directory
2018/10/03 20:43:26 JobID=8ee131d6-d92a-494e-4faa-9230f365db52, Part#=0, TransfersDone=2053 of 10000
2018/10/03 20:43:26 INFO: [P#0-T#2114] has worker 104 which is processing TRANSFER
2018/10/03 20:43:26 ERR: [P#0-T#2114] DOWNLOADFAILED: https://cjwstorage.blob.core.windows.net/dltest/8403.bin?se=2018-10-14t04%3A28%3A12z&sig=REDACTED&sp=rwdlacup&spr=https%2Chttp&srt=sco&ss=bfqt&st=2018-10-02t20%3A28%3A12z&sv=2017-11-09 : 000 : File Creation Error open /mnt/dltest/8403.bin: no such file or directory
   Dst: /mnt/dltest/8403.bin

### Have you found a mitigation/solution?
I didn't have access to the /mnt folder. After chown, the command worked fine

**Comment by zezha-msft** [comment]
The error given back by the file system should be reported as is.
