### ISSUE TITLE
AzCopy 10.3.1 - blob to blob in Azure Stack environemnt

### ISSUE THREAD

**Issue by pmanvoj** [Azure/azure-storage-azcopy#711]
### Which version of the AzCopy was used? 
AzCopy 10.3.1  - is it expected that blob to blob transfer is supported in Azure stack environment?
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows - powershell

### What command did you run?
$env:AZCOPY_DEFAULT_SERVICE_API_VERSION = '2017-11-09'
$destination =  'https://xxx.blob.xxx.az.dsarena.com/galleryimages?sv=...
$source =        'https://yyy.blob.yyy.az.dsarena.com/galleryimages?sv=...
& $azcopy --version  # ---> resulted in 10.3.1
& $azcopy  copy "$source" "$destination"  --overwrite=true --recursive=true
### What problem was encountered?
RESPONSE Status: 400 Bad Request
   Content-Length: [328]
   Content-Type: [application/xml]
   Date: [Tue, 22 Oct 2019 07:20:09 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Request-Id: [e38f99d9-6a44-07a2-5080-7fdbff195890]
Response Details: ﻿<Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format. </Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2018-11-09</HeaderValue>

2019/10/22 07:20:09 ==> REQUEST/RESPONSE (Try=1/16.9996ms, OpTime=16.9996ms) -- RESPONSE STATUS CODE ERROR
   PUT https://xxx..blob.xxx1.az.dsarena.com/galleryimages/Canonical.UbuntuServer1804LTS-ARM.1.0.3/Canonical.UbuntuServer1804LTS-ARM.1.0.3.txt?...&timeout=901
   Content-Length: [0]
   User-Agent: [AzCopy/10.3.1 Azure-Storage/0.7 (go1.12; Windows_NT)]
   X-Ms-Client-Request-Id: [0d02ad3c-5c27-4840-53f4-6fafad13d7c8]
   X-Ms-Copy-Source: [https://xxx.blob.xxx.az.dsarena.com/galleryimages/Canonical.UbuntuServer1804LTS-ARM.1.0.3/Canonical.UbuntuServer1804LTS-ARM.1.0.3.txt?...
   X-Ms-Source-Range: [bytes=0-233]
   X-Ms-Version: [2018-11-09]
### How can we reproduce the problem in the simplest way?
copy blobs between storage accounts hosted by Azure stack
### Have you found a mitigation/solution?
Just tested two steps approach from blob to local drive and from local drive to target blob storage nd it worked, so all setup (paths, sas tokens ...) was correct

**Comment by JohnRusk** [comment]
@zezha-msft , as our Azure Stack expert on the team, can you comment?

**Comment by zezha-msft** [comment]
Hi @pmanvoj, thanks for reaching out!

Unfortunately Azure Stack does not support the synchronous copy APIs yet. [Put block from URL](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-from-url) (for Block Blob) was first introduced in 2018-03-28, which is expected to be supported by Azure Stack in the near future.

A possible workaround is the older version of AzCopy: the [V8](https://docs.microsoft.com/en-us/previous-versions/azure/storage/storage-use-azcopy) downloads the source data and re-uploads it to the destination, which is not ideal. The new APIs allows V10 to orchestrate the transfers and simply ask the destination Storage service to read the data from the source account directly.

**Comment by JohnRusk** [comment]
BTW, if using v8, check the /Sync flag.  If the flag is specified, it downloads from source and streams the data up again to the destination.  If the flag is not there, it does an _asynchronous_ service to service copy. That's different from the synchronous ones that v10 does.  I don't know whether Azure Stack has the async copy apis.  If it doesn't, you'll definitely have to use the /Sync flag.
