### ISSUE TITLE
'azcopy remove' doesn't seem to work with the storage emulator

### ISSUE THREAD

**Issue by thisiscmt** [Azure/azure-storage-azcopy#713]
### Which version of the AzCopy was used?
10.3.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy remove "http://127.0.0.1:10000/devstoreaccount1/extracted/3d0b6a17-6157-40be-96b2-38ba16665984?sv=2019-02-02&st=2019-10-23T22%3A24%3A52Z&se=2019-10-23T22%3A54%3A52Z&sr=c&sp=d&sig=xxxxx" --recursive --log-level ERROR --output-type=json

### What problem was encountered?
Failed to removed anything from the container.

### How can we reproduce the problem in the simplest way?
Simply try to remove a series of blobs that are in a virtual directory, as per the documentation, against the Azure storage emulator.

### Have you found a mitigation/solution?
No

It seems like the remove command doesn't support removing a virtual directory if you are using the Azure storage emulator locally. In azure-storage-azcopy/cmd/remove.go, it tries to infer the target argument and if it's the local machine (i.e. not a host with .blob or .file in the URL), it throws an error.

Are there plans to add support for removing a virtual directory using the emulator?

**Comment by zezha-msft** [comment]
Hi @thisiscmt, thanks for reaching out!

It appears that the tool is not recognizing the endpoint. If you add `--from-to="BlobTrash"`, does that work?

**Comment by thisiscmt** [comment]
Nope, the error it gives is:

Error: unknown flag: --from-to

**Comment by zezha-msft** [comment]
Ah I see, thanks @thisiscmt for bringing this to our attention. We'll try to fix this as soon as possible.

**Comment by thisiscmt** [comment]
Any update on this?

When i filed this issue I was using an older version of Azure Storage Explorer, which did manage to remove an entire virtual directory when you told it to. I recently upgraded to the latest version of Storage Explorer (1.12.0) and it now errors out when I try to delete a virtual directory. I suspect that the older verison of SE didn't use azcopy for that kind of delete operation, but the current version does and is still incompatible with the storage emulator.

**Comment by JasonYeMSFT** [comment]
We know this issue of AzCopy so that we don't use AzCopy when targeting emulators. Please share the errors with us so that we can investigate what goes wrong.

**Comment by adreed-msft** [comment]
The upcoming release of azcopy (10.4) should resolve this issue.

**Comment by thisiscmt** [comment]
Thanks adreed, I'll look out for that release.

Here is the error I see in Azure Storage Explorer, for completeness. This is after trying to delete a virtual directory with other virtual directories and individual blobs inside:

{
  "name": "StorageError",
  "message": "The specified blob does not exist.\nRequestId:1f7e553f-16ac-4dad-bb9a-f59dd427af26\nTime:2020-04-07T16:32:32.718Z",
  "stack": "StorageError: The specified blob does not exist.\nRequestId:1f7e553f-16ac-4dad-bb9a-f59dd427af26\nTime:2020-04-07T16:32:32.718Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at Request.emit (events.js:182:13)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)\n    at Object.onceWrapper (events.js:273:13)\n    at IncomingMessage.emit (events.js:187:15)",
  "code": "BlobNotFound",
  "statusCode": 404,
  "requestId": "1f7e553f-16ac-4dad-bb9a-f59dd427af26"
}

**Comment by JohnRusk** [comment]
@JasonYeMSFT just looking you back in on this, since it could be a  Storage Explorer bug, given your earlier comment.

**Comment by thisiscmt** [comment]
I'm pretty sure in version 1.9.0 of Storage Explorer it did recursively remove a virtual directory of blobs without error. This was the version where using azcopy was a preview option, it wasn't the default mechanism for performing I/O operations.

Let me know if you need additional info or if I should post the SE issue elsewhere.

**Comment by thisiscmt** [comment]
@adreed-msft, et al:

I just grabbed version 10.4.1 and the original issue I filed where azcopy rm doesn't work with an emulator is still present.

It's pretty simple: remove.go on line 50 does a check on the URL you want to remove. If it doesn't contain either '.blob', '.file', or ',dfs', the operation fails with the message 'invalid source type Unknown to delete. azcopy support removing blobs/files/adls gen2'.

It seems like all you need to do is modify inferArgumentLocation() in validators.go so the Blob case also matches when the URL starts with the string 'http://127.0.0.1:10000', which is how blobs in the emulator are always referenced.

Any chance this could get into a future release? Having to add special logic to not run azcopy if my app is running locally is kind of a pain.

**Comment by Zork9999** [comment]
I can confirm this is still a issue. Also with deleting files from a storage account using a custom domain name without blob, file or dfs in the name isn't working. 

Please look into, we are using now version 1.9.0 to avoid this issue but now we can't upload large files.

**Comment by thisiscmt** [comment]
Checking again, any progress on this issue?

**Comment by ShaharHD** [comment]
Same here, still an issue

**Comment by thisiscmt** [comment]
Hello again.

My team is currently working on a new Azure-based app that uses storage quite heavily, and the ability to develop this app locally and batch delete blobs/files in virtual directories is going to become more important. azcopy seems to be the simplest and most viable method of doing a batch delete of a virtual dir. I've looked for others, and the current JavaScript SDK and az CLI don't seem up to it.

So my question is, when will the 'az remove' command support targeting emulators? It's been over a year since I reported this issue with no resolution in sight. And I know at one time there were other open azcopy issues that could be traced back to incomplete emulator support in azcopy. Can this problem be given more attention, since it is integral to developing apps in Azure that use storage?

**Comment by skywalkerisnull** [comment]
This is still an issue, we are in the process of deploying Azure Blob IoT and discovered that we cannot use Azure Storage Explorer to seed the containers with required data, this also includes deleting the data from the blobs. This is an issue that I put up on 

https://github.com/microsoft/AzureStorageExplorer/issues/4099

What specifically would be required to allow for custom domains (including IP addresses) to be used in AzCopy?

**Comment by thisiscmt** [comment]
@skywalkerisnull What would be required, as far as remove operations go, is MS refactoring the validation logic that causes the remove operation to fail if the target URL doesn't match a known list of patterns. I'm not sure if other operations have this same issue.

To MS folks:

As the person who filed this issue well over a year ago and would like to see it fixed, I'm genuinely curious why the remove operation is so weird about the allowed URLs passed is as the target. Is it to prevent security vulnerabilities? Was remove.go originally written to just handle the basic cases and nothing more? The storage emulators (Azurite and the MS distributed one) and a custom domain-fronted storage account basically work the same under the hood, right? If so, why not be less restrictive about which URLs are allowed?

If it's a matter of feature priority, I would think this comes under the heading of 'things that Should Just Work'. Deleting blobs is integral to developing for and managing blob storage, regardless of how you reference them.

**Comment by skywalkerisnull** [comment]
@thisiscmt I was thinking more along the lines of exactly what needs to be done (i.e. Microsoft tell us what they want done in the code) and I could, or get one of our team to do a PR to resolve it.

I am looking at the specific function: 

```go
var IPv4Regex = regexp.MustCompile(`\d+\.\d+\.\d+\.\d+`) // simple regex

func inferArgumentLocation(arg string) common.Location {
	if arg == pipeLocation {
		return common.ELocation.Pipe()
	}
	if startsWith(arg, "http") {
		// Let's try to parse the argument as a URL
		u, err := url.Parse(arg)
		// NOTE: sometimes, a local path can also be parsed as a url. To avoid thinking it's a URL, check Scheme, Host, and Path
		if err == nil && u.Scheme != "" && u.Host != "" {
			// Is the argument a URL to blob storage?
			switch host := strings.ToLower(u.Host); true {
			// Azure Stack does not have the core.windows.net
			case strings.Contains(host, ".blob"):
				return common.ELocation.Blob()
			case strings.Contains(host, ".file"):
				return common.ELocation.File()
			case strings.Contains(host, ".dfs"):
				return common.ELocation.BlobFS()
			case strings.Contains(host, benchmarkSourceHost):
				return common.ELocation.Benchmark()
				// enable targeting an emulator/stack
			case IPv4Regex.MatchString(host):
				return common.ELocation.Unknown()
			}

			if common.IsS3URL(*u) {
				return common.ELocation.S3()
			}
		}
	}

	return common.ELocation.Local()
}
```

And it might be as simple as adding in another case that returns a new type on the Elocation such that it is a URL and then subject to more checks, or it could just fire off optimistically and hope to return something. Also that function should be updated to include IPv6 but I guess that is a different discussion.

As a work around, I found that if I create a new A/AAAA record for *.blob.custom.domain.com and pointed it at the IoT blob, I can successfully delete the blobs. But it would be really nice not to have to do custom domains as a workaround and just stick to our current domain naming schemes and policies.

**Comment by thisiscmt** [comment]
Yes, additional cases of some sort is exactly what should be done. And I and others have specifically [mentioned](https://github.com/Azure/azure-storage-azcopy/issues/713#issuecomment-622163909) that function in validators.go as the place to affect a fix. For some reason MS hasn't done it. I don't know their policy for approving PRs for azcopy, but if you can submit one and get it approved that would be amazing.

**Comment by shoter** [comment]
I would love to see it resolved. Just spend 1 hour figuring out why I am not able to remove blobs from Azuriote/Iot Edge Blob Storage

**Comment by ShaharHD** [comment]
> I would love to see it resolved. Just spend 1 hour figuring out why I am not able to remove blobs from Azuriote/Iot Edge Blob Storage

I resolved this by creating my own customized `azure_deploy.sh` and having the following:

```shell
# Deployment
# ----------

echo "Starting Web Site deployment."

# 1. KuduSync
IGNORE_FILES=".git;.hg;.deployment;.github;.vscode;src"

"$KUDU_SYNC_CMD" -v 50 -x -f "$DEPLOYMENT_SOURCE" -t "$DEPLOYMENT_TARGET" -n "$NEXT_MANIFEST_PATH" -p "$PREVIOUS_MANIFEST_PATH" -i $IGNORE_FILES
exitWithMessageOnError "Kudu Sync failed"
```

**Comment by zezha-msft** [comment]
In 10.12 the rm command can now take a --from-to flag:

--from-to string            Optionally specifies the source destination combination. For Example: BlobTrash, FileTrash, BlobFSTrash
