### ISSUE TITLE
Feature request: filter source by modification date (include-after)

### ISSUE THREAD

**Issue by landro** [Azure/azure-storage-azcopy#716]
It would be great if you could add an option to filter source by creation/modification date. 
One particular use case that I have is to only copy files that have been created/modified after a certain date.

**Comment by JohnRusk** [comment]
Look out for `--include-after` in release 10.5

**Comment by PeterCosa** [comment]
Hi John. Would be great t have the --include-after flag. I need to copy only files older than 3 months from source. Is version 10.5 imminent?

**Comment by JohnRusk** [comment]
Peter, you seem to be asking about an include-before flag.  You asked for files _older_ than three months.  The flag that's planned for 10.5 would let you pick up files that are _newer_ than 3 months.    Did you definitely mean "older"?

(As for dates, we don't pre announce them, sorry).

**Comment by PeterCosa** [comment]
Sorry. Yes I mean older. Therefore --include-before

**Comment by JohnRusk** [comment]
Yours is the first request for include-before.  Until now, we had not expected it to be something that would be needed.  cc @rishabpoh for his consideration as a feature request.

**Comment by PeterCosa** [comment]
Thank you. We are basically shifting backups from live storage to blob as
they age. We then get lifecycle management to progress from hot cold
archive. Hopefully this would be useful to others for automating back up
retention for compliance?

**Comment by JohnRusk** [comment]
I've made a separate issue for include-before, here: https://github.com/Azure/azure-storage-azcopy/issues/1075  and renamed this one to focus only on include-after (which will be in 10.5)

**Comment by landro** [comment]
Fixed in https://github.com/Azure/azure-storage-azcopy/pull/1015 which was merged in 10.5
