### ISSUE TITLE
Failed to perform copy command due to error: OAuth token, SAS token, or shared key should be provided for Blob FS - (SUSE 12.X)

### ISSUE THREAD

**Issue by framic-msft** [Azure/azure-storage-azcopy#724]
___________________________________________________________________
**Which version of the AzCopy was used?** 
___________________________________________________________________
latest - 10.3.1

___________________________________________________________________
**Which platform are you using? (ex: Windows, Mac, Linux)**
___________________________________________________________________
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"
kernel - 4.12.14-6.23-azure

(marketplace image)

___________________________________________________________________
**What command did you run?**
___________________________________________________________________
Authenticate using secret key is successful:
env AZCOPY_SPA_CLIENT_SECRET=<secret-key> ./azcopy login --service-principal --application-id <id> --tenant-id< id>
INFO: If you set an environment variable by using the command line, that variable will be readable in your command line history. Consider clearing variables that contain credentials from your command line history.  To keep variables from appearing in your history, you can use a script to prompt the user for their credentials, and to set the environment variable.
INFO: SPN Auth via secret succeeded.

This is failing:
azcopy copy /azcopy/azcopy.tar.gz "https://mydatalakestorage.dfs.core.windows.net/mydatalakecontainer"
failed to perform copy command due to error: OAuth token, SAS token, or shared key should be provided for Blob FS

https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

___________________________________________________________________
**What problem was encountered?**
___________________________________________________________________

The azcopy copy command will fail with the mentioned error: 
failed to perform copy command due to error: OAuth token, SAS token, or shared key should be provided for Blob FS.

(The same output will be logged if authenticating using certificate instead of secret key)

___________________________________________________________________
**How can we reproduce the problem in the simplest way?**
___________________________________________________________________

This seems to be happening on SUSE version 12.x only - you can just deploy a SUSE 12.4 VM from marketplace and test the above commands

NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"
kernel - 4.12.14-6.23-azure

----------------------------------------------------------------------

If instead, i run the same commands (against the same ADLS2 container) on RHEL or SUSE latest versions, the command will be successful (both versions are coming from Azure marketplace - latest available version for each distro)

NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server" 
kernel - 3.10.0-1062.4.1.el7.x86_64

NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"
kernel - 4.12.14-5.30-azure

___________________________________________________________________
**Have you found a mitigation/solution?**
___________________________________________________________________
No

I have noticed SUSE 12.4 is using keyutils 1.5.9 while SUSE 15 is using keyutils 1.5.10.
I have managed to install keyutils 1.6 on SUSE 12.4 

https://software.opensuse.org/download/package?package=keyutils&project=security
zypper addrepo https://download.opensuse.org/repositories/security/SLE_12_SP4/security.repo
zypper refresh
zypper install keyutils

However, same error message is logged

**Comment by JohnRusk** [comment]
It sounds like it might be a known issue. Can you see this comment please: https://github.com/Azure/azure-storage-azcopy/issues/452#issuecomment-503812803

**Comment by framic-msft** [comment]
It worked - thanks John :) i had looked everywhere but in that article

**Comment by JohnRusk** [comment]
Any suggestions on where else we should document it?  E.g. where did you look? Maybe we should mention it there.
