### ISSUE TITLE
[Question] 10.0.2 prev. Azcopy sync limitations.. Blob storage only?

### ISSUE THREAD

**Issue by Kapanther** [Azure/azure-storage-azcopy#73]
Running Win 7. does new Azcopy sync support (local files) to (file storage)? Or does it only support (blob storage)?

Syncing from local file (C:\GQ) to (Azure File Storage "File Share")

so something like below , should work?
`azcopy sync c:\GQ https:\\<azure file storage path> --recursive`

**Comment by JeffreyRichter** [comment]
Yes, the new AzCopy does support Azure Storage Files (file shares).
