### ISSUE TITLE
azcopy exits without any output if there is no space between source and destination

### ISSUE THREAD

**Issue by amishra-dev** [Azure/azure-storage-azcopy#731]
### Which version of the AzCopy was used? 
10.3.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
..\azcopy.exe copy "https://adlsg2ashish.blob.core.windows.net/testcontainer/storage?AccountSAS""f:\aad2" --overwrite=prompt --follow-symlinks --recursive --put-md5
### What problem was encountered?
there was no space between source and destination and azcopy just quit without any output
### Have you found a mitigation/solution?
add a space

**Comment by JohnRusk** [comment]
This might be a symptom of a more generic problem: report more clearly if our parameters don't make sense. (Not sure if we should attempt to solve the more generic problem tho. It may only be realistic to solve specific cases, such as the one logged here)

**Comment by amishra-dev** [comment]
@JohnRusk i am not sure what you mean by this. The thing I want fixed here is that azcopy should not exit without an error/message or some indication to the user about why we exit. This feels like azcopy crashed.

**Comment by JohnRusk** [comment]
Makes sense. Ignore my earlier comment

**Comment by zezha-msft** [comment]
The command got treated as a piping scenario, and there was an error with the URL. So an error message should be written to Stderr, since the Stdout is used for content output.

**Comment by JohnRusk** [comment]
I'd like is to actually introduce a parameter, that must be specified, to invoke pipe mode. It would avoid these kinds of confusing situations, because we could give an error message on input like that described above, if the pipe-mode parameter wasn't set.

 (But this would be at the expense of being a breaking change).

**Comment by nakulkar-msft** [comment]
This is fixed starting 10.6.1 and piping will explicitly require from-to flag.
