### ISSUE TITLE
Failed to login with tenantID "“tenant-id”"

### ISSUE THREAD

**Issue by Marcusblhw** [Azure/azure-storage-azcopy#732]
### What problem was encountered?

```
Failed to perform login command: 
failed to login with tenantID "“tenant-id”", Azure directory endpoint "https://login.microsoftonline.com", autorest/adal/devicetoken: -REDACTED- occurred while handling response from the Device Endpoint: Error HTTP status != 200

NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again.
```

Hi all, I'm very new to azcopy and azure (had to pick it up just yesterday) and this problem has been driving me up the wall. 

Additional information:
1. yes I have tried waiting before logging in again (more than a few hours each time even)
2. I tried login --tenant-id whenever i opened a new terminal until this problem appeared
3. I have logout since and now when I login, the above problem appears
4. I have successfully copy files from one storage to another before hand. However, problem appears when I close and open a new terminal to replicate the success.

Help in simple english (not so much code jargon) is greatly appreciated. Thanks in advance!

### How can we reproduce the problem in the simplest way?
steps:
1. open terminal
2. login --tenant-id <tenant id>
3. enter code at microsoft.com/devicelogin
4. close terminal
5. repeat multiple times

**Comment by JohnRusk** [comment]
@zezha-msft this looks Mac-specific.  Can you try with the repro steps that are listed?

**Comment by zezha-msft** [comment]
Hi @Marcusblhw, thanks for reaching out! This **part of the error message** looked a bit strange to me.

failed to login with tenantID "**“tenant-id”**", Azure directory endpoint "https://login.microsoftonline.com", autorest/adal/devicetoken: -REDACTED- occurred while handling response from the Device Endpoint: Error HTTP status != 200

Could you please check whether you passed in a valid tenant ID? It looks like the value given for the flag was literally `"tenant-id"`.

**Comment by Marcusblhw** [comment]
> Hi @Marcusblhw, thanks for reaching out! This **part of the error message** looked a bit strange to me.
> 
> failed to login with tenantID "**“tenant-id”**", Azure directory endpoint "https://login.microsoftonline.com", autorest/adal/devicetoken: -REDACTED- occurred while handling response from the Device Endpoint: Error HTTP status != 200
> 
> Could you please check whether you passed in a valid tenant ID? It looks like the value given for the flag was literally `"tenant-id"`.

Hey @zezha-msft thanks for getting back to me!

Yeah you are right. I removed the "" around the tenant-id and it worked. 
I've been following this fomat found on microsoft's azure website:

> azcopy login --identity --identity-client-id "client-id"

when instead it should be 

> azcopy login --tenant-id tenant-id

Thanks for pointing it out for me

**Comment by zezha-msft** [comment]
Hi @Marcusblhw, glad to hear you got it working!

Actually there are many ways to authenticate, please refer to `azcopy login --help` if you'd like to learn more.
