### ISSUE TITLE
Azcopy doesn't transfer any files from blob when runnin in bash task in AzDO

### ISSUE THREAD

**Issue by saroup** [Azure/azure-storage-azcopy#747]
azcopy 7.3.0-netcore
Ubuntu

In my Azure DevOps CI pipeline I have:
- task: Bash@3
  displayName: Download model
  inputs:
    targettype: 'inline'
    script: azcopy --source https://test.blob.core.windows.net/container/model.json --destination $(Agent.TempDirectory)/model/model.json --source-key $(accesskey) --recursive --quiet

When I run this command locally the file is copied fine. However, in the pipeline 
### What problem was encountered?
Transfer summary:
-----------------
Total files transferred: 0
Transfer successfully:   0
Transfer skipped:        0
Transfer failed:         0
Elapsed time:            00.00:00:03

**Comment by saroup** [comment]
it seems that I should put model.json in a folder and have my source be https://test.blob.core.windows.net/container/modelfolder. It took me a bit to figure this out.
Q1: Is this expected behavior
Q2: Can we add this information in the documentation?

**Comment by JohnRusk** [comment]
@saroup You're using version 7, and the latest is v10.  V10 is a total re-write with different commands and different documentation.  So I don't expect will be making any improvements to the old documentation for v7 and v8.

Glad to hear you've got it working though.  

I propose to close this issue now.
