### ISSUE TITLE
please support copying metdata of blobs when using azcopy sync command

### ISSUE THREAD

**Issue by imeya** [Azure/azure-storage-azcopy#748]
### Which version of the AzCopy was used? 

**A: the latest version v10.3.2**

### Which platform are you using? (ex: Windows, Mac, Linux)

**A: windows 10**

### What command did you run?

**A: azcopy sync**

### What problem was encountered?

**A: the metadata of source blob is not copied.**

### How can we reproduce the problem in the simplest way?

**A: just use "azcopy sync" command, and set metadata for some source blobs**

### Have you found a mitigation/solution?

**A: no**

**Comment by imeya** [comment]
@zezha-msft , hello, may I know when this can be done? Thanks.

**Comment by zezha-msft** [comment]
Hi @imeya, we'll be able to provide a reliable estimate once this work has been scheduled.

**Comment by dpolivy** [comment]
Adding my vote for this!

**Comment by JohnRusk** [comment]
Fixed in release 10.3.3.

**Comment by imeya** [comment]
Verified it, it works! Thank you.
