### ISSUE TITLE
Azcopy Sync command not detecting changes to existing files within source directory "File Share"

### ISSUE THREAD

**Issue by djradium** [Azure/azure-storage-azcopy#752]
### Which version of the AzCopy was used? 

10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows (Within Server 2016 Azure DevOps Self Hosted build agent)

### What command did you run?

azcopy.exe sync $source $dest --delete-destination true

### What problem was encountered?

Copying from Az Storage Acc "File Share" to Az Storage Acc "File Share", on first sync it will copy the entire directory successfully.

Added dummy text file for 2nd sync to source folder and ran subsequent sync and detected changes and copied file to destination

Made changes to dummy text file and re uploaded to source file share. Performed another sync and job didn't detect this as a change. Both source and destination showed identical file quantities.

Not sure if this is the intended outcome of this command.

### How can we reproduce the problem in the simplest way?

As above

### Have you found a mitigation/solution?

Revert back to old commands with older azcopy, however over time our source folder will be cleared of files that are no longer required and using standard copy doesn't delete at destination.

**Comment by adreed-msft** [comment]
Right now, we check against your Last Modified Time registered on objects (to see if the src is more recent) before we schedule the transfer-- Could you confirm that the source LMT is ahead of the destination LMT?

**Comment by djradium** [comment]
Hi going to close this issue, the source LMT wasn't ahead of the destination LMT.
