### ISSUE TITLE
Sync from public container to private (Azure China) blob storage with Azure China AD service principal authentication fails

### ISSUE THREAD

**Issue by mhennecke** [Azure/azure-storage-azcopy#754]
### Which version of the AzCopy was used? 
AzCopy 10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
```
read -s AZCOPY_SPA_CLIENT_SECRET
azcopy login --service-principal --application-id {} --tenant-id {} --aad-endpoint "https://login.partner.microsoftonline.cn"
azcopy sync "https://{source sa name}.blob.core.windows.net/{source container name}/" "https://{target sa name}.blob.core.chinacloudapi.cn/{target container name}/"
```

### What problem was encountered?
Source Container has public access level.  A simple `azcopy list https://{source sa name}.blob.core.windows.net/{source container name}/` shows the content of the source container.

However, it seems that the `azcopy sync` tries to obtain an OAuth token for the source container from Azure China AD. The sync command errors out with the following:

```
Cannot perform sync due to error: cannot list blobs. Failed with error -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:22b04de2-a01e-0049-8097-9ff4a3000000
Time:2019-11-20T11:39:16.8628899Z, Details:
   AuthenticationErrorDetail: Signature validation failed. Signature key not found.      
   Code: AuthenticationFailed
   GET https://{source sa name}.blob.core.windows.net/{source container}?comp=list&include=metadata&restype=container&timeout=901
   Authorization: REDACTED
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; linux)]
   X-Ms-Client-Request-Id: [cce63be0-53f5-4d46-6f11-9764458393f1]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------      
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Access-Control-Allow-Origin: [*]
   Access-Control-Expose-Headers: [x-ms-request-id,x-ms-error-code]
   Content-Length: [428]
   Content-Type: [application/xml]
   Date: [Wed, 20 Nov 2019 11:39:16 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [22b04de2-a01e-0049-8097-9ff4a3000000]
```

**Comment by JohnRusk** [comment]
Yes, my first impression is the same as yours, which is that it's failing to treat the source as public.

I'll see if I can find a workaround for you.  Are you able to use a SAS for the _destination_ instead of OAuth?  That might give my more options when looking for a workaround?

**Comment by mhennecke** [comment]
@JohnRusk Currently, I use a long-lived static SAS token for authenticating against the destination and of course no SAS token for the source as it is public. In this workaround scenario I have no authenticated session with a service principal.

My first attempt of getting rid of the long-lived static SAS token, was to use az-cli for generating short-lived tokens via az-cli and a logged in service principal. Please check my comment in https://github.com/Azure/azure-cli/issues/10205 for the issue I ran into with generate-sas.

**Comment by JohnRusk** [comment]
Oh, I see. So you actually already have a workaround (use long-lived SAS) but are looking to get rid of the SAS?

**Comment by mhennecke** [comment]
Yes, workaround exists but I want to get rid of the long-lived SAS. Maybe there is a way to force azcopy to access the source without attempting an authentication as it is public anyway!?

**Comment by JohnRusk** [comment]
Yes, I totally agree. I've added an item to our backlog.  Just wanted to make sure you had a workaround to use before we make the fix.  I'll leave this issue open until the fix is made and released.

**Comment by nakulkar-msft** [comment]
Please reopen if you still see this issue.
