### ISSUE TITLE
azcopy copy works but shows failed error

### ISSUE THREAD

**Issue by cccs-cat001** [Azure/azure-storage-azcopy#756]
##### Note: The version is visible when running AzCopy without any argument
10.3.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy localfile 'https://datalake.blob.core.windows.net/file?SAS'
### What problem was encountered?
It told me the status failed, but when I look at the datalake on the portal or do azcopy list it shows me the file is on the data lake.
### How can we reproduce the problem in the simplest way?
I have a private datalake, using an SAS token which has just enough permissions to write a new file to the data lake  (ss=b&srt=0&sp=w) to write just a test file to the datalake. 
### Have you found a mitigation/solution?
It just works anyways, would be nice if it told me it succeeded when it succeeds.

**Comment by JohnRusk** [comment]
By default it does a check at the end, in which it attempts to read the length of the finished destination file/blob.  That's what will be failing. You can disable that check with --check-length=false

**Comment by JohnRusk** [comment]
BTW, we have a task on our backlog to make the app handle this situation better.
