### ISSUE TITLE
Not enough server storage is available to process this command

### ISSUE THREAD

**Issue by faulus** [Azure/azure-storage-azcopy#758]
##### Note: The version is visible when running AzCopy without any argument
Azcopy  v10
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10
### What command did you run?
Azcopy copy
### What problem was encountered?
Not enough server storage is available to process this command

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
Were you uploading or downloading?  Where did the message appear?  Was there any other text with that message?  Were you using Blob Storage or Azure Files?

**Comment by JohnRusk** [comment]
@faulus We need some more info, to make progress on this issue.  Can you see the questions above please?
