### ISSUE TITLE
azcopy.exe batchfile has Cannot perform sync due to error: cannot list blobs error

### ISSUE THREAD

**Issue by fredsofttech** [Azure/azure-storage-azcopy#762]
azcopy version 10, running from CMD manually is working perfectly, but if run it from batch file has got the following error, 

Cannot perform sync due to error: cannot list blobs. Failed with error -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:d18e490a-601e-0049-764a-a7dd37000000
Time:2019-11-30T06:53:15.3658143Z, Details:
   AuthenticationErrorDetail: Signature size is invalid
   Code: AuthenticationFailed
   GET https://v6buildarchive.blob.core.windows.net/test?comp=list&include=metadata&restype=container&se=2022-11-29t14%3A35%3A31z&sig=-REDACTED-&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2019-11-30t06%3A35%3A31z&sv=2019-02-02&timeout=901
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [3c78577c-68cd-4d4f-58f7-e3c31e899186]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [400]
   Content-Type: [application/xml]
   Date: [Sat, 30 Nov 2019 06:53:14 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [d18e490a-601e-0049-764a-a7dd37000000]
  RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [400]
   Content-Type: [application/xml]
   Date: [Sun, 01 Dec 2019 04:22:48 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [33c8d575-501e-002c-3dfe-a76c6a000000]

anyone has a idea about it? storage blob contributor permission has been given to azure account as well. run it from AD admin account.

**Comment by JohnRusk** [comment]
Question : When running the batch file, are you logged in as the same user as when running it directly from CMD?

One thing to try would be running it from a Powershell script. If that works, it would suggest the problem in the batch file is possibly something about string quoting.

**Comment by fredsofttech** [comment]
@JohnRusk I have used the same Domain admin account when I run the batch file. I tried to run same azcopy command in windows power shell manually,  there is no error at all. 

This is only given above error when run in batch file.

**Comment by JohnRusk** [comment]
@fredsofttech Sounds like it might be this problem, or something like it: https://github.com/Azure/azure-storage-azcopy/issues/177#issuecomment-474349070

**Comment by fredsofttech** [comment]
@JohnRusk thanks so much for your hint here， John, it's all sorted.
