### ISSUE TITLE
Please bump mattn/go-ieproxy module dependency

### ISSUE THREAD

**Issue by cemeyer** [Azure/azure-storage-azcopy#765]
##### Note: The version is visible when running AzCopy without any argument
git master
### Which platform are you using? (ex: Windows, Mac, Linux)
FreeBSD
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`go build`
### What problem was encountered?
```
../../../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.0-20190610004146-91bb50d98149/GetProxyFunc.go:10:9: undefined: proxyMiddleman
```

The bug was already fixed by a Microsoft employee in a revision of ieproxy subsequent to the version pinned in `go.mod`: https://github.com/mattn/go-ieproxy/commit/9ae9a81fc2c37750ed3e28c77d3835d338619a05
### How can we reproduce the problem in the simplest way?
Spin up a FreeBSD 12+ VM on Azure, or whatever you find most convenient, and attempt to `go build`.
### Have you found a mitigation/solution?
Update the pinned `go.mod` version for `mattn/go-ieproxy` to `v0.0.0-20191113090002-7c0f6868bffe`.

**Comment by cemeyer** [comment]
Obviated / duplicated by #768, for what it's worth.

**Comment by JohnRusk** [comment]
Will close this one as a duplicate.
