### ISSUE TITLE
Dose Azcopy version 10.3.2 has file move file functionality as can't see it in help list

### ISSUE THREAD

**Issue by fredsofttech** [Azure/azure-storage-azcopy#767]
##### Note: The version is visible when running AzCopy without any argument
10.3.2
### Which platform are you using? (ex: Windows, Mac, Linux)
windows
### What command did you run?
windows CMD and powershell
### What problem was encountered?
Can't seek any command of "Move" file which should be moving source files to destination instead of just copying files over to azure. 
### How can we reproduce the problem in the simplest way?
NA
### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
Currently, no. See https://github.com/Azure/azure-storage-azcopy/issues/45

**Comment by JohnRusk** [comment]
Closing this issue, because the feature request is tracked in the one I just linked to.
