### ISSUE TITLE
blobs copied from local directory recursively contain local parent directory name in their paths

### ISSUE THREAD

**Issue by jijiechen** [Azure/azure-storage-azcopy#775]
### Which version of the AzCopy was used? 

azcopy version 10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

```sh
cd my-dir-name
azcopy copy --recursive=true . 'https://storage-account.blob.core.windows.net/container-name/?<SAS>'
```

### What problem was encountered?
The files uploaded onto blob container all have a prefix "my-dir-name", which is the parent directory name on the local disk.
I don't want the directory name to be the prefix of the blobs and it seems there is no extra options to achieve that.
### How can we reproduce the problem in the simplest way?

```sh
mkdir dir
echo 'content' > file.txt
azcopy copy --recursive=true . 'https://storage-account.blob.core.windows.net/container-name/?<SAS>'
```

### Have you found a mitigation/solution?
No.

**Comment by JohnRusk** [comment]
It works the same way as Bash and PowerShell: append /* to the source and it will copy just the _contents _of the source, not the name of the source.

In your case, that would be 
AzCopy copy ./* http://... --recursive

**Comment by jijiechen** [comment]
@JohnRusk Thank you very much. It worked like a charm.
