### ISSUE TITLE
Sync does not work with OAuth & error messages are not clear

### ISSUE THREAD

**Issue by artemuwka** [Azure/azure-storage-azcopy#78]
PS C:\Users\artek\Desktop\OneDrive - Microsoft\Current tasks\PowerShell & CLI & AzCopy\azcopy_windows_amd64_10.0.1> .\azcopy sync "C:\azcopy\" https://akzrsdemo.blob.core.windows.net/
Using OAuth token for authentication.

error performing the sync between source and destination. Failed with error error starting the sync between source C:/azcopy/ and destination https://akzrsdemo.blob.core.windows.net. Failed with error cannot list blobs for download. Failed with error -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.NewResponseError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zz_generated_response_error.go:28
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:418ad35a-c01e-0033-54f7-5f6b64000000
Time:2018-10-09T17:39:53.7100125Z, Details:
   AuthenticationErrorDetail: Authentication scheme Bearer is not supported.
   GET https://akzrsdemo.blob.core.windows.net?comp=list&restype=container&timeout=901
   Authorization: REDACTED
   User-Agent: [AzCopy/v10.0.2-Preview Azure-Storage/0.1 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [9352f58d-14b0-44cd-5204-f68040769df0]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [421]
   Content-Type: [application/xml]
   Date: [Tue, 09 Oct 2018 17:39:52 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [418ad35a-c01e-0033-54f7-5f6b64000000]

PS C:\Users\artek\Desktop\OneDrive - Microsoft\Current tasks\PowerShell & CLI & AzCopy\azcopy_windows_amd64_10.0.1> .\azcopy sync "C:\azcopy\" https://akzrsdemo.blob.core.windows.net/newcontainer
Using OAuth token for authentication.

error performing the sync between source and destination. Failed with error error starting the sync between source C:/azcopy/ and destination https://akzrsdemo.blob.core.windows.net/newcontainer. Failed with error cannot list blobs for download. Failed with error -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.NewResponseError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zz_generated_response_error.go:28
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:968a0fa4-101e-009e-7ff7-5f7219000000
Time:2018-10-09T17:40:53.3630243Z, Details:
   AuthenticationErrorDetail: Authentication scheme Bearer is not supported.
   GET https://akzrsdemo.blob.core.windows.net/newcontainer?comp=list&restype=container&timeout=901
   Authorization: REDACTED
   User-Agent: [AzCopy/v10.0.2-Preview Azure-Storage/0.1 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [52d95c9f-9b08-4d6d-4868-f0944d33b6c7]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [421]
   Content-Type: [application/xml]
   Date: [Tue, 09 Oct 2018 17:40:52 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [968a0fa4-101e-009e-7ff7-5f7219000000]

PS C:\Users\artek\Desktop\OneDrive - Microsoft\Current tasks\PowerShell & CLI & AzCopy\azcopy_windows_amd64_10.0.1> .\azcopy sync "C:\azcopy\" https://akzrsdemo.blob.core.windows.net/aktest
Using OAuth token for authentication.

error performing the sync between source and destination. Failed with error error starting the sync between source C:/azcopy/ and destination https://akzrsdemo.blob.core.windows.net/aktest. Failed with error cannot list blobs for download. Failed with error -> github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.NewResponseError, /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zz_generated_response_error.go:28
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:534b0f92-701e-0020-34f7-5fa640000000
Time:2018-10-09T17:41:15.4788450Z, Details:
   AuthenticationErrorDetail: Authentication scheme Bearer is not supported.
   GET https://akzrsdemo.blob.core.windows.net/aktest?comp=list&restype=container&timeout=901
   Authorization: REDACTED
   User-Agent: [AzCopy/v10.0.2-Preview Azure-Storage/0.1 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [0e9363fd-39b9-4cb2-75b7-eca33eb4ab84]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [421]
   Content-Type: [application/xml]
   Date: [Tue, 09 Oct 2018 17:41:15 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [534b0f92-701e-0020-34f7-5fa640000000]

**Comment by zezha-msft** [comment]
I assume this is now solved. @artemuwka Please let me know if this problem persists.
