### ISSUE TITLE
azcopy copy does not follow symbolic links in subdirectories

### ISSUE THREAD

**Issue by Soushi-Atsumi** [Azure/azure-storage-azcopy#791]
### Which version of the AzCopy was used? 
AzCopy 10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10 Pro 64bit

### What command did you run?
`azcopy.exe copy ".\dir2\" "https://host/blob/?$key" --follow-symlinks --recursive --from-to=LocalBlob`

### What problem was encountered?
`failed to perform copy command due to error: no transfers were scheduled because no files matched the specified criteria`

### How can we reproduce the problem in the simplest way?
Try uploading any symbolic links from the parent directory with _--recursive_ option.

### Have you found a mitigation/solution?
Use wildcards instead of applying the option. This code works well.

`azcopy.exe copy ".\dir2\*" "https://host/blob/?$key" --follow-symlinks --from-to=LocalBlob`

However, only symbolic links in the first subdirectory are copied, and symbolic links in subdirectories of subdirectories are not copied.

**Comment by JohnRusk** [comment]
@adreed-msft can you take a look?

**Comment by adreed-msft** [comment]
I'm having some trouble reproducing this one myself.

I'm curious, @Soushi-Atsumi-- Have you tried removing the trailing \ on your local path? We've had some issues with our argument parsing framework WRT that on Windows.

Also, are these symlinks made with `mklink` or are they shortcuts?

**Comment by Soushi-Atsumi** [comment]
Hi,

> I'm curious, @Soushi-Atsumi-- Have you tried removing the trailing \ on your local path?

The same issue occurs even if I remove the trailing \.

> We've had some issues with our argument parsing framework WRT that on Windows.

Surely, this issue does not occur in Linux. I tried it now.

> Also, are these symlinks made with `mklink` or are they shortcuts?

I created symlinks with `New-Item` in PowerShell. And now I tried uploading symlinks made with `mklink` but it failed too.

**Comment by adreed-msft** [comment]
Interesting! Are there any other logs to stdout? (For instance, "Failed to resolve symlink", "Ignored already linked directory", etc.)

**Comment by Soushi-Atsumi** [comment]
This is the all logs to stdout. I replaced the home directory as ~.

```
INFO: Scanning...
INFO: Ignored already seen file located at Z:\test\abc.txt (found at \\?\Z:\test\dir1\dir2\abc.txt)
INFO: Ignored already seen file located at Z:\test\bcd.txt (found at \\?\Z:\test\dir1\dir2\bcd.txt)

Job 9f702095-3d9a-e34a-62cd-97f41f7799a5 has started
Log file is located at: ~\.azcopy\9f702095-3d9a-e34a-62cd-97f41f7799a5.log


failed to perform copy command due to error: no transfers were scheduled because no files matched the specified criteria
```

**Comment by russdot** [comment]
I can confirm the same behaviour on WSL.

**Comment by JohnRusk** [comment]
What's the target of the symlink?  A file or a directory?

**Comment by Soushi-Atsumi** [comment]
Hi @JohnRusk 
> What's the target of the symlink? A file or a directory?
The target is a file. azcopy works correctly when it targets a symbolic link of a directory.

**Comment by JohnRusk** [comment]
That's a known bug, I'm sorry. It doesn't currently work on symlinks to files.  It's on our list to fix.

**Comment by nakulkar-msft** [comment]
#718
