### ISSUE TITLE
Special status for terminations/ close of command line

### ISSUE THREAD

**Issue by qudiransari** [Azure/azure-storage-azcopy#794]
##### Note: The version is visible when running AzCopy without any argument
10
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What problem was encountered?
Status still showing in progress even after closing the command line while running

JobId: f7a70b72-0b7f-c246-7c7e-eca2511a9312
Start Time: Tuesday, 10-Dec-19 15:39:34 GMT
Status: InProgress
Command: copy U:\directorycontents.csv https://usldevstorage.blob.core.windows.net/bpglobe?se=2019-12-20t23%3A00%3A00z&sig=REDACTED&sp=racwdl&sr=c&st=2019-12-05t01%3A00%3A00z&sv=2019-02-02

### How can we reproduce the problem in the simplest way?
Close the comnnad line and check job status
### Have you found a mitigation/solution?
No

**Comment by adreed-msft** [comment]
There's actually not a particularly great way to do this when our process suddenly terminates, aside from some kind of "staleness" indicator on the plan file.

This kind of a feature has been discussed prior though, let me see if I can find a related issue.

**Comment by JohnRusk** [comment]
Good point. E.g. if the process suddenly terminates (or gets terminated, e.g. by Task Manager) it will have no way of setting some kind of special status before termination.  So I'm not sure that we realistically can, or should, implement this feature request.  I know you've discussed this Adele, so I'll leave it to you to comment further, and to close if it's not something that we can or should do.

**Comment by adreed-msft** [comment]
I feel as though this isn't something we should seek after at the moment-- It's a "nice to have", but there's a bit of an inherent technical debt or overengineering to any way we could handle this.

Under a "staleness" implementation (ex. Updating the file on a regular interval with a timeout), it'd either be too slow, or too prone to false positives in the form of a race condition.

Under a PID-based implementation (ex. checking if the PID registered to the job plan is still active), I have my concern that another process may take the same PID and cause a false negative. Furthermore, this'd require per-OS implementation, which given that we have users who compile azcopy for alternate OSes and architectures unofficially, I don't feel like this option is a particularly "great" option.

There is an option that I feel comfortable with in terms of the soundness of the implementation-- A sort of local socket to check what job other copies of AzCopy are running. I however, also feel that this is somewhat over-engineered for the problem.

So, what I'm going to say is that this probably won't be happening. At least not unless AzCopy for some reason goes back to the old ways of a daemon.

**Comment by adreed-msft** [comment]
With that, I'll close the issue. If it feels appropriate, feel free to re-open the issue.
