### ISSUE TITLE
resume jobs is not working

### ISSUE THREAD

**Issue by qudiransari** [Azure/azure-storage-azcopy#795]
##### Note: The version is visible when running AzCopy without any argument
1.
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy jobs resume 3e993a7d-29cb-914f-490e-72ef49cf32c2 --source-sas="U:\*" --destination-sas="xxxxxxxxxxxxxxxxxxxxxxxxxx"
Job 3e993a7d-29cb-914f-490e-72ef49cf32c2 has started
100.0 %, 411636 Done, 295 Failed, 0 Pending, 0 Skipped, 411931 Total,
Job 3e993a7d-29cb-914f-490e-72ef49cf32c2 summary
Elapsed Time (Minutes): 0.1013
Total Number Of Transfers: 411931
Number of Transfers Completed: 411636
Number of Transfers Failed: 295
Number of Transfers Skipped: 0
TotalBytesTransferred: 2699369377486
Final Job Status: CompletedWithErrors

### What problem was encountered?
Resume is not transferring the failed files its showing the same failed ones
### Have you found a mitigation/solution?
No

**Comment by qudiransari** [comment]
Hi,
After closely looking failed file names these file names has chinese name, will it affect the migration if yes then why?

3e993a7d-29cb-914f-490e-72ef49cf32c2Copy.log:6761920:2019/12/16 11:01:32 ERR: [P#19-T#9850] UPLOADFAILED: %5C%5C?\U:\Gxxxxxxxxxxxx\2. GIS\Indus\xxxxxxxxxxx\fras_aux_e90_kutch_mask.␍簴ꊨ簷￿&U:\* : 000 : Couldn't open source-open 
%5C%5C?\U:\xxxxxxxxxxxxxxxxxxxxxxxx\fras_aux_e90_kutch_mask.␍簴ꊨ簷￿&U:\*: The filename, directory name, or volume label syntax is 
incorrect.

**Comment by adreed-msft** [comment]
I noticed this in the command you were running: `--source-sas="U:*"`

Could you try running without this parameter? It looks like AzCopy has accidentally appended a SAS token to a local source, judging by the `&U:*` on the end of your file open failure.

**Comment by adreed-msft** [comment]
This'll hopefully serve as a mitigation to your issue, but it's still technically a usability bug to tackle.

**Comment by qudiransari** [comment]
What is the status on this @adrees-msft @JohnRusk

**Comment by JohnRusk** [comment]
We are waiting to hear your answer to the question Adele asked you, above.
