### ISSUE TITLE
Upload only new and chnge files using azcopy

### ISSUE THREAD

**Issue by jethrogalolo** [Azure/azure-storage-azcopy#797]
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

**Comment by adreed-msft** [comment]
Hi there, have you tried using the command `azcopy sync`? It should achieve exactly what you're looking for.

**Comment by adreed-msft** [comment]
(If it doesn't meet your needs, we can keep the issue open and discuss further)

**Comment by JohnRusk** [comment]
Closing because it sounds like Sync will do what's needed.  Let us know, and we'll re-open if Sync doesn't meet your needs.
