### ISSUE TITLE
AzCopy fails trying to create a file in account psstrg2dnancpdp because a directory exists with the same name

### ISSUE THREAD

**Issue by samueljamkhandi-MSFT** [Azure/azure-storage-azcopy#798]
### Which version of the AzCopy was used? 
**AzcopyVersion 10.3.0**
### Which platform are you using? (ex: Windows, Mac, Linux)
**From Unix servers the file will be copied over to ADLS**
### What command did you run?
**2019/12/11 20:06:32 Job-Command copy /dna/us/data/project/inbound_pharmacy_edw/in/fl_landing/tl_location_store_relocation/tl_location_store_relocation_20191207000512_20191209_080746_000000_0 https://psstrg2dnancpdp.dfs.core.windows.net/inbound-pharmacy-edw/IN/fl-landing/tl_location_store_relocation --recursive** 
### What problem was encountered?
**During the copy operation they see the copy fails with 409 Error intermittently and simply re-running the same job returns successful without having to do anything from their side.

UPLOADFAILED: /dna/us/data/project/inbound_pharmacy_edw/in/fl_landing/tl_location_store_relocation/tl_location_store_relocation_20191207000512_20191209_080746_000000_0 : 409 : 409 The specified path, or an element of the path, exists and its resource type is invalid for this operation.. When Creating file. X-Ms-Request-Id: 1cb36c1e-a01f-00e8-535e-b04bed000000

I’m attaching a logs where Cx attempted to copy the file “tl_location_store_relocation_20191207000512_20191209_080746_000000_0” at 2019/12/11 20:06:32 – Fails
And the same job when Cx re-ran to copy the file “tl_location_store_relocation_20191207000512_20191209_080746_000000_0” at 2019/12/11 20:12:54 – Is Successful

Cx wants to know why is this happening intermittently and possible RCA + fix on how to overcome this. Please let me know if any further information is required from my side.**

### How can we reproduce the problem in the simplest way?
**Can be repro'd by simple copy operation but it is intermittent and cannot be reproduced at will** 
### Have you found a mitigation/solution?
**No
[AzcopyError.zip](https://github.com/Azure/azure-storage-azcopy/files/3983581/AzcopyError.zip)
**

**Comment by samueljamkhandi07** [comment]
Team - really would appreciate your quick help on this issue.

**Comment by Virepri** [comment]
Hi there! Because Azure Data Lakes Generation 2 works much like a filesystem, unlike Azure Blob Storage, files and folders can't share names. If you attempt to create a folder (or a file) that shares a name, you'll find this response. Is it possible that any segment of your path say, already existed as a file or a folder?

**Comment by adreed-msft** [comment]
(whoops, posted this from the wrong account)

**Comment by adreed-msft** [comment]
Hi there! Because Azure Data Lakes Generation 2 works much like a filesystem, unlike Azure Blob Storage, files and folders can't share names. If you attempt to create a folder (or a file) that shares a name, you'll find this response. Is it possible that any segment of your path say, already existed as a file or a folder?

**Comment by zezha-msft** [comment]
Following up offline.

**Comment by adreed-msft** [comment]
Hi there, @samueljamkhandi-MSFT, I'd recommend trying your operation again with the latest version of AzCopy again, and get back to us with the results.

**Comment by samueljamkhandi-MSFT** [comment]
@adreed-msft - this worked, thanks a lot.
