### ISSUE TITLE
Cat command output

### ISSUE THREAD

**Issue by artemuwka** [Azure/azure-storage-azcopy#80]
Is this expected behavior/output of the cat command without having grep in the pipeline?

PS C:\Users\artek\Desktop\OneDrive - Microsoft\Current tasks\PowerShell & CLI & AzCopy\azcopy_windows_amd64_10.0.1> cat "C:\Users\artek\.azcopy\ed3dc4a0-8949-9d4f-57dc-f8fccaa7bd4d.log"
2018/10/09 18:00:01 AzcopVersion  10.0.2-Preview
2018/10/09 18:00:01 OS-Environment  windows
2018/10/09 18:00:01 OS-Architecture  amd64
2018/10/09 18:10:14 AzcopVersion  10.0.2-Preview
2018/10/09 18:10:14 OS-Environment  windows
2018/10/09 18:10:14 OS-Architecture  amd64

**Comment by zezha-msft** [comment]
Hi @arammsft, I'm a bit confused by your question, are you saying that you have an incomplete log file? What command did you run to generate that log?
