### ISSUE TITLE
Features: Batch jobs: Copy and rename

### ISSUE THREAD

**Issue by Socolin** [Azure/azure-storage-azcopy#804]
Hi,

I'm looking for a way to copy a long list of files from a blob to another quickly, like directory copy on server side. But I need to rename the files on the destination blob.

On one blob I have files like `0f/14/487ef487a4874154` and I want to copy them to another blob with a different path like `/some/directory/file.ext`

Recently https://github.com/Azure/azure-storage-azcopy/issues/196 was added but it does not allow renaming the files.

**Comment by mohsha-msft** [comment]
Similar Feature Request: https://github.com/Azure/azure-storage-azcopy/issues/1151

**Comment by nakulkar-msft** [comment]
Hi, we have decided not to go-ahead with this feature. Please file a new issue if you still require this.
