### ISSUE TITLE
AzCopy v10 jobs resume command does the file level resume instead of block level.

### ISSUE THREAD

**Issue by eridai** [Azure/azure-storage-azcopy#806]
### Which version of the AzCopy was used? 
10.3.3
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
AzCopy jobs resume 
### What problem was encountered?
90% of a file was uploaded to Azure and then failed for the rest. With AzCopy jobs resume command, the tool did not start from failed part of the file. Instead, it started from beginning of the file. If the file is large, it waste time and bandwidth for the successful portion.
### Have you found a mitigation/solution?
No.

**Comment by adreed-msft** [comment]
Hi there!

A block-level resume currently isn't supported in V10, but there have been occasional discussions around it.

Sorry!

**Comment by ddelapasse2** [comment]
Wow, this is a huge deficit!  It would be nice if you could add a note into the documentation around this.

**Comment by vibhansa-msft** [comment]
This feature has been released couple of months back. With the latest version of AzCopy you can resume with block-level transfer instead of retrying entire file.
