### ISSUE TITLE
Unable to delete file accessToken.json, generated when login is done using SPN credentials

### ISSUE THREAD

**Issue by 20shivangi** [Azure/azure-storage-azcopy#807]
When we run azcopy command:
$env:AZCOPY_SPA_CLIENT_SECRET="$(Read-Host -prompt "Enter key")"
azcopy login --service-principal --application-id <application-id> --tenant-id=<tenant-id>

a file AccessToken.json is generated. I am unable to figure out how to delete this file once my task is completed.

### Which version of the AzCopy was used? 
10.3.3

### Which platform are you using?
Windows

### What command did you run?
login using credential
azcopy login --service-principal --application-id <application-id> --tenant-id=<tenant-id>

### What problem was encountered?
It generates file accessToken.json at location where log and plan files are generated

### How can we reproduce the problem in the simplest way?
Ty running azcopy login command using credential or certificate

### Have you found a mitigation/solution?
No

**Comment by adreed-msft** [comment]
You aren't necessarily _meant_ to delete this file, as it's a persistent credential, but if you wish to log out in order to clean up, `azcopy logout` is your friend.

**Comment by 20shivangi** [comment]
@adreed-msft It worked for me. Thanks :)
