### ISSUE TITLE
Azcopy hangs at every command after login

### ISSUE THREAD

**Issue by yungtrizzle** [Azure/azure-storage-azcopy#810]
### Which version of the AzCopy was used? 
10.3.3
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

### What command did you run?
azcopy make  "https://storageaseccn5.blob.core.windows.net/testbassetti"
### What problem was encountered?
azcopy prints one line in console "INFO: Make is using OAuth token for authentication."
and hangs, no logs produced and no errors reported.
 I am in China if that matters.

### How can we reproduce the problem in the simplest way?
Run azcopy login
login with azure credentials
Attempt any network related command

### Have you found a mitigation/solution?
no

**Comment by JohnRusk** [comment]
Yes, the issue may relate to you being in China.  Did you use the `--aad-endpoint` parameter in your login?  For the China cloud you need to set it to "https://login.chinacloudapi.cn".

E.g.
```
azcopy login --aad-endpoint "https://login.chinacloudapi.cn"
```

The full list of possible values is here: https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud#azure-ad-authentication-endpoints

@normesta Do you think this is something we should address more in the login documentation?

**Comment by yungtrizzle** [comment]
This info was not in the login documentation for azcopy. The docs only discuss managed identity. Will try this today.

**Comment by JohnRusk** [comment]
Thanks for bringing the documentation gap to our attention.

**Comment by yungtrizzle** [comment]
Forgot to report back on this. Adding the `--aad-enpoint` parameter works.
