### ISSUE TITLE
[Question] Azcopy sync --log-level string flag options?

### ISSUE THREAD

**Issue by Kapanther** [Azure/azure-storage-azcopy#82]
V10.0.2 - Win 7

what are the possible string options for "azcopy sync" --log-level flag?

"WARNING" is default, but it seems that the logs stored in c:\users\<username>\.azcopy store more than just warnings?

Some of these logs get quite large. 1.4GB copy made a 100mb log!!

so decreasing the verbosity would be certainly useful if azcopy was to run on a regular basis?

**Comment by MatthewMcD** [comment]
I stumbled on this by running `azcopy copy --help`
````
Log Levels: DEBUG, INFO, WARNING, ERROR, PANIC, and FATAL
````
Haven't tried `PANIC` yet.

**Comment by MatthewMcD** [comment]
Happy to help. If I can get sync working I'll help update the docs.

**Comment by zezha-msft** [comment]
Fixed.
