### ISSUE TITLE
AzCopy creates an odd folder structure when downloading small files which you do not have permissions to read

### ISSUE THREAD

**Issue by MRayermannMSFT** [Azure/azure-storage-azcopy#822]
### Which version of the AzCopy was used? 
10.3.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
```
./azcopy login;
./azcopy.exe copy "https://myaccount.dfs.core.windows.net/container/New%20Folder/File.txt" "C:\Users\myname\Downloads\File.txt" --overwrite=prompt --recursive --from-to=BlobFSLocal --check-md5 "FailIfDifferent";
```

### What problem was encountered?
When the transfer finished the file was placed here on my disk:
`C:\Users\myname\Downloads\New folder\File.txt\File.txt\New Folder\File.txt`

### How can we reproduce the problem in the simplest way?
Create a ADLS Gen2 container with the following folder and file structure:
```
container/
   New Folder/
      File.txt
```
Note: File.txt needs to be small, I've been testing with something less than 1 MB.

Have a user who is given the following ACL permissions:
```
container/ r-x
   New Folder/ r-x
      File.txt ---
```

Have the user use AzCopy (after logging in) to download the file `container/New Folder/File.txt`.

### Have you found a mitigation/solution?
No.

**Comment by adreed-msft** [comment]
I'm having some trouble reproducing this, but if you have a consistent reproduction on 10.5, I'd love to try to debug.

**Comment by MRayermannMSFT** [comment]
We're using the blob endpoint for downloading gen2 files and folders now, so I think you can just go ahead and close this.
