### ISSUE TITLE
AzCopy successfully downloads empty files even if you do not have read permissions

### ISSUE THREAD

**Issue by MRayermannMSFT** [Azure/azure-storage-azcopy#823]
### Which version of the AzCopy was used? 
10.3.3

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
```
./azcopy login;
./azcopy.exe copy "https://myaccount.dfs.core.windows.net/container/New%20Folder/EmptyFile.txt" "C:\Users\myname\Downloads\EmptyFile.txt" --overwrite=prompt --recursive --from-to=BlobFSLocal --check-md5 "FailIfDifferent";
```

### What problem was encountered?
Although I didn't have read access to the file, AzCopy reported the transfer as successful.
Additional info:
- If the file is not empty, then the transfer is reported as failed
- #822 also repros

### How can we reproduce the problem in the simplest way?
Create a ADLS Gen2 container with the following folder and file structure:
```
container/
   New Folder/
      EmptyFile.txt
```
Note: EmptyFile.txt needs to be empty.

Have a user who is given the following ACL permissions:
```
container/ r-x
   New Folder/ r-x
      EmptyFile.txt ---
```

Have the user use AzCopy (after logging in) to download the file `container/New Folder/File.txt`.

### Have you found a mitigation/solution?
No.

**Comment by JohnRusk** [comment]
Hmm. Interesting.  Can I just play devil's advocate for a moment.... is it really a bug?  If you have enough permissions to list the file, and to know that it exists and it has zero length, then from the perspective on information disclosure, read permission is irrelevant because you already know the contents of the file, before you read it. (I.e. the contents are zero bytes).

So I'm not sure whether its really a bug or not.  What to do you think?

cc @zezha-msft for thoughts.

**Comment by JohnRusk** [comment]
Reminder (to self) this is related to #822

**Comment by MRayermannMSFT** [comment]
While I don't disagree with you (and I actually had the same thought) I can imagine the following happening (and I believe something like this is what generated the original bug report): 

"Hey fellow co-worker, I've taken away your read permissions for all the files in this directory. Can you try downloading one to make sure I did it right?"
`Co-worker picks an empty file and downloads it`
"Oh no, I was still able to do the download! You must have done something wrong."
`Customers are now confused`

**Comment by JohnRusk** [comment]
Good point.  Given that there's no information disclosure risk, I'm not sure we'll prioritize this highly, but you're right that it could create confusion and that's best avoided.

**Comment by adreed-msft** [comment]
In 10.5, this fails immediately after starting due to us failing the job when we get auth failures.

However, it does still produce the 0-byte file in order to fail.

**Comment by adreed-msft** [comment]
My take is that this is a non-issue, though it does make the end user experience a bit confusing in this edge case.

**Comment by vibhansa-msft** [comment]
Closing this, kindly create a new bug report if the issue still persist with the latest version as well.
