### ISSUE TITLE
Azcopy from s3 to adls not supported?

### ISSUE THREAD

**Issue by fjpiqueras** [Azure/azure-storage-azcopy#825]
### Which version of the AzCopy was used? 

10.3.3
### Which platform are you using? (ex: Windows, Mac, Linux)
Mac
### What command did you run?

azcopy copy 'https://XX.s3-eu-west-1.amazonaws.com/YY' 'https://ZZ.dfs.core.windows.net/AA-adls/mis'

### What problem was encountered?

failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

### How can we reproduce the problem in the simplest way?

export AZCOPY_SPA_CLIENT_SECRET="aaaaaaa"
export AWS_ACCESS_KEY_ID="bbbbbb"
export AWS_SECRET_ACCESS_KEY="cccccc"

azcopy login --service-principal --application-id "eeeee" --tenant-id="ffffff"

azcopy copy 'https://XX.s3-eu-west-1.amazonaws.com/YY' 'https://ZZ.dfs.core.windows.net/AA-adls/mis'

Error found: failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

Azcopy works from local to adls, but it seems that s3 to adls is not available. In adition I am not able to run 

azcopy list 'https://AA.s3-eu-west-1.amazonaws.com/BB'

invalid path passed for listing. given source is of type 6 while expect is container / container path

### Have you found a mitigation/solution?

I guess if I install aws cli, get the file to virtual machine and after that use the azcopy from local to adsl it would works.

Could you help me please?

**Comment by JohnRusk** [comment]
[Multi-protocol access](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-multi-protocol-access) is now GA. So just change your command to be:
```
azcopy copy 'https://XX.s3-eu-west-1.amazonaws.com/YY' 'https://ZZ.blob.core.windows.net/AA-adls/mis'

```
(The change is to use the blob.core.windows.net endpoint for the destination)

That should work.

@normesta In addition to the documentation tweak we discussed last week, for ADLS Gen 2 to ADLS Gen2, could you also make a similar tweak for this, the S3 to ADLS Gen 2 scenario?

**Comment by fjpiqueras** [comment]
John, 

I tried with this command as you mention and still not working

azcopy cp https://AA.s3-eu-west-1.amazonaws.com/FILENAME https://BB.dfs.core.windows.net/BB-blob/mis

failed to parse user input due to error: the inferred source/destination combination is currently not supported. Please post an issue on Github if support for this scenario is desired

I think the problem is a incompatibility with S3, because I can not make a azcopy list to s3 and I should, right?

azcopy list https://BB.s3-eu-west-1.amazonaws.com/FILENAME

Error:

invalid path passed for listing. given source is of type 6 while expect is container / container pat

Could you take a look please?

**Comment by JohnRusk** [comment]
That's not the command I mentioned ;-)  The destination URL needs to be a blob one not a dfs one. (All ADLS gen 2 accounts now have BOTH types of endpoint, but only the blob one will work in this case).

**Comment by fjpiqueras** [comment]
Yep, I did not understand yout last comment, now I am able to copy from s3 to blob storage.. so thanks!.

On the other hand, I think it would be useful to copy directly from s3 to adls right? are you planning to include this feature?

**Comment by JohnRusk** [comment]
ADLS Gen 2  _IS_ blob storage (with the Heirarchical Namespace Turned on).  They are just two different APIs to the same underyling platform.  If you had that turned on in your test, then you did copy directly to ADLS Gen 2. Try reading the data you copied through the ADLS Gen 2 endpoint for the same account.
