### ISSUE TITLE
DataMovement library question

### ISSUE THREAD

**Issue by bryjamus** [Azure/azure-storage-azcopy#829]
This is not an issue but I need clarification and I think that maybe this is the fastest place to get answer.

In [this article](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-data-movement-library) is written this:

> The Azure Storage Data Movement library is a cross-platform open source library that is designed for high performance uploading, downloading, and copying of blobs and files. This library is the core data movement framework that powers AzCopy.

I search AzCopy code and couldn't find any reference to DataMovement library. How do you use this library? Is sentence true regarding .net  DataMovement library? Can you point me part of code which use this library?

Regards
Klaudiusz

**Comment by JohnRusk** [comment]
Thanks for pointing that out. The article is old. I was true for versions of AzCopy up to 8.1, but its not true now.

@normesta Can you arrange a fix to that article?

**Comment by normesta** [comment]
@tamram can we remove the mention of AzCopy in this article or perhaps update the mention to include "8.1" so that readers aren't confused. I'd be happy to make the update if you let me know which way you want to go with it. Thx!

**Comment by tamram** [comment]
@normesta - Yes, feel free to remove that sentence (and any others that associate Data Movement with AzCopy).
