### ISSUE TITLE
Feature / Question: Support for non-AWS S3 endpoints

### ISSUE THREAD

**Issue by massive** [Azure/azure-storage-azcopy#832]
### Which version of the AzCopy was used? 
10.3.3.

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac & Linux

### What command did you run?

azcopy cp

### What problem was encountered?

Apparently azcopy detects the source type from the source URL. According to this [file](https://github.com/Azure/azure-storage-azcopy/blob/d4e856e572f7f63521329703d18d9f96bac21613/common/s3URLParts.go) (if I read it correctly) the source is detected to be S3 iff it contains string `amazonaws.com`. This limits the usefulness of `azcopy`. S3 compatible storage is available from many providers, not just AWS.

### How can we reproduce the problem in the simplest way?

By running `cp` command with any of non-aws object storage providers, such as Digital Ocean, as the source.

### Have you found a mitigation/solution?

Not really, no.

**Comment by JohnRusk** [comment]
Thanks. Yes, we're aware of this limitation and agree that it would be great to address it.

cc @rpohane

**Comment by JohnRusk** [comment]
@rpohane When we have an indicative release number for this, can you please update the milestone field?

**Comment by sjdrc** [comment]
Is there any progress on this? I have over 50TB of data I want to move from a non AWS s3 provider to azure and this would be super helpful.

**Comment by johnrhunt** [comment]
Hi there,

If someone can point me in the right direction I could potentially remove this restriction.

**Comment by ehclark** [comment]
I have added support for non-AWS S3 endpoints.  At this point have only tested against Wasabi.  Additional testing against on non-AWS S3 backends would be useful.

Submitted PR #2394 with changes.  The branch to be merged is based on 10.20.1.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
