### ISSUE TITLE
New Feature request: automatic proxy authentication

### ISSUE THREAD

**Issue by ComeChao** [Azure/azure-storage-azcopy#837]
AzCopy v10 does not work when proxy authentication is required.

Please add automatic proxy authentication to AzCopy v10+.

### Which version of the AzCopy was used? 
AzCopy 10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
cp C:\filestoupload\* https://blobaccount.blob.core.windows.net/uploadedfiles/...?<sas> --recursive

### What problem was encountered?
**authenticationrequired**

Stack trace below:

2019/12/18 22:41:21 ==> REQUEST/RESPONSE (Try=1/217.009ms, OpTime=441.0249ms) -- REQUEST ERROR
PUT https://myblobacct.blob.core.windows.net/mycontainer/myfile.csv?<...>&timeout=901
Content-Length: [8388608]
User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
X-Ms-Client-Request-Id: [25fcb796-2bd2-4206-49ca-7a46260e5f10]
X-Ms-Version: [2018-03-28]
ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
HTTP request failed

Put https://myblobacct.blob.core.windows.net/mycontainer/myfile.csv?<...>&timeout=901: **authenticationrequired**

goroutine 299 [running]:
github.com/Azure/azure-storage-azcopy/ste.stack(0xc0002248a0, 0xc0103c1200, 0x0)
/home/vsts/work/1/s/ste/xferLogPolicy.go:232 +0xa4
github.com/Azure/azure-storage-azcopy/ste.NewRequestLogPolicyFactory.func1.1(0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x10, 0x1, 0x0, 0xc0113f6160)
/home/vsts/work/1/s/ste/xferLogPolicy.go:146 +0x7ac
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0007b4e10, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0xc0113f6200, 0xc001a04fc8, 0xa, 0x2030004)
/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x64028f0, 0xc001a05050, 0x40c7c0, 0xc0010c2500)
/home/vsts/work/1/s/ste/mgr-JobPartMgr.go:75 +0x1b8
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00009f760, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x10, 0x10, 0xaffee0, 0x30)
/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0xcdfd40, 0xc00009f760, 0xc00020a960, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x0, 0x11af520, 0xc001a050b0, 0x4310d8)
/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zz_generated_responder_policy.go:33 +0x5a
github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(...)
/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_credential_anonymous.go:54
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do(0xc000207bc0, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0x0, 0x0, 0x0, 0xc001a051d0)
/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x62
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000207bd0, 0xcee0a0, 0xc0010802a0, 0xc0113ea100, 0xc0010802a0, 0xc00cb3a250, 0x1, 0x0)
/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0xcee020, 0xc000024c80, 0xc010bc8000, 0x10, 0xab2660, 0x64492d747301, 0xc010bca420)
/home/vsts/work/1/s/ste/xferRetrypolicy.go:382 +0x70f
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0007b4e60, 0xcee020, 0xc000024c80, 0xc010bc8000, 0xc010bca4f0, 0x30, 0x28, 0x8)
/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0xcee020, 0xc000024c80, 0xc010bc8000, 0x10, 0xab2660, 0x1be, 0xcca256)
/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_policy_unique_request_id.go:19 +0xb5
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00009f7a0, 0xcee020, 0xc000024c80, 0xc010bc8000, 0xc010bca4d8, 0x34, 0xc00001e400, 0xc001a05598)
/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0xcee020, 0xc000024c80, 0xc010bc8000, 0x1, 0x0, 0x1, 0xc000212368)
/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_policy_telemetry.go:34 +0x164
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc001058d50, 0xcee020, 0xc000024c80, 0xc010bc8000, 0xc001058d50, 0xc001a05668, 0x4143e3, 0xc00020a968)
/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x4b
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc000024980, 0xcee020, 0xc000024c80, 0xcdfe00, 0xc00020a960, 0xc010bc8000, 0x25, 0xc0010e662d, 0x4f, 0x0)
/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:129 +0x88
github.com/Azure/azure-storage-blob-go/azblob.blockBlobClient.StageBlock(0xc0010e6600, 0x5, 0x0, 0x0, 0x0, 0xc0010e6608, 0x25, 0xc0010e662d, 0x4f, 0x0, ...)
/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zz_generated_block_blob.go:260 +0x4c0
github.com/Azure/azure-storage-blob-go/azblob.BlockBlobURL.StageBlock(0xc0010e6600, 0x5, 0x0, 0x0, 0x0, 0xc0010e6608, 0x25, 0xc0010e662d, 0x4f, 0x0, ...)
/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/url_block_blob.go:79 +0x17b
github.com/Azure/azure-storage-azcopy/ste.(*blockBlobUploader).generatePutBlock.func1()
/home/vsts/work/1/s/ste/sender-blockBlobFromLocal.go:77 +0x37e
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0x7f)
/home/vsts/work/1/s/ste/sender.go:165 +0x1ae
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc00006c000, 0x7f)
/home/vsts/work/1/s/ste/JobsAdmin.go:427 +0xe6
created by github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).poolSizer
/home/vsts/work/1/s/ste/JobsAdmin.go:356 +0x682

### How can we reproduce the problem in the simplest way?
Run AzCopy in a network that has a proxy server that requires authentication.

### Have you found a mitigation/solution?
No

**Comment by glwr** [comment]
Hi @JohnRusk 
Any news on this topic?
Cheers, Gerrit

**Comment by JohnRusk** [comment]
Hi Gerrit, I've moved on to a different team now. Maybe @zezha-msft can answer
John

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zezha-msft** [comment]
Hi @glwr, I'm sorry to say that we haven't figured out a solution for authenticated proxies. We'll collaborate with a partner team on this and will update the issue when we have updates.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality. We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
