### ISSUE TITLE
Azcopy should show total data size after copy 

### ISSUE THREAD

**Issue by vijayraje23** [Azure/azure-storage-azcopy#841]
##### Note: The version is visible when running AzCopy without any argument
V8.1.0 also tried V10.3.3

### Which platform are you using? (ex: Windows, Mac, Linux) 
Windows/Linux

### What command did you run?
AzCopy /Source:E:\Source folder /Dest:https://destination.blob.core.windows.net/container/Folder /DestKey:xyz /S /V:C:\Azcopy\xyz.log

Azcopy cp "E:\Source folder" "https://destination.blob.core.windows.net/container/Folder?sv=xxxxxxxxxxxxxxxxxxxxxxxxxxx%3D" --recursive=true

### What problem was encountered?
showing total number of files that Transferred,copied,Skiped and Failed

Total files transferred: 201258
Transfer successfully:   201258
Transfer skipped:        0
Transfer failed:         0
Elapsed time:            00.01:31:17

### How can we reproduce the problem in the simplest way?
Run azcopy command it will show similar output

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
v10 does show the total number of bytes transferred.  (Would be better if it was in GB or something, and that's on our to-do list. But for now, its there, and its in bytes).

No new features will be added to v8, not even little ones like this.
