### ISSUE TITLE
azcopy remove command - directories are not deleted

### ISSUE THREAD

**Issue by vmazalov** [Azure/azure-storage-azcopy#857]
##### Note: The version is visible when running AzCopy without any argument
10.1.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy remove --recursive
### What problem was encountered?
Individual files were deleted, but directory structure is still visible with Azure Storage Explorer.
When I try to list files with azcopy, it just hangs without showing anything.

**Comment by JohnRusk** [comment]
This is a known issue, since AzCopy is currently a file-centric tool, with very little focus on directories. We are working on that, for release 10.4, but it's no early for me to confirm whether those changes will address the need you're asking about.

Where are the directories that you want it to delete?  Azure Files?

**Comment by JohnRusk** [comment]
This is not currently planned for inclusion in 10.4.0, since 10.4.0 will be focused on copying properties of folders.  However, the folder copying work will lay some useful groundwork for folder deletion in some future release.

**Comment by ianpittwood** [comment]
Is this still in the works or is there a workaround at all?

**Comment by JohnRusk** [comment]
Oh, thanks for asking!  In the end, we did include it in 10.4.  But we didn't re-update this issue.  I'll mark this issue as 10.4 now, and close it.  

Please give the feature a try and let me know how it goes for you.

**Comment by karthikeyanRV** [comment]
I am running version AzCopy 10.8.0
AzCopy remove only removes the files inside the directory but the directory is still there.

**Comment by svinther** [comment]
> 



> Oh, thanks for asking! In the end, we did include it in 10.4. But we didn't re-update this issue. I'll mark this issue as 10.4 now, and close it.
> 
> Please give the feature a try and let me know how it goes for you.

Hi @JohnRusk How do you turn on this feature ? It seems that empty directories are still left after applying `azcopy remove` no matter if using `--recursive` or not

**Comment by dawiduniec** [comment]
It's still a problem, any planned fix, or workaround?
