### ISSUE TITLE
azcopy list - show only top level directories

### ISSUE THREAD

**Issue by vmazalov** [Azure/azure-storage-azcopy#858]
##### Note: The version is visible when running AzCopy without any argument
10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy list
### What problem was encountered?

It shows list of all files recursively, but we want to show only list of directories at the top level.

**Comment by gtiao** [comment]
I'd also like to have this feature. Our directories have hundreds of thousands of files in subdirectories, so it makes `azcopy ls` uninformative.

**Comment by dinith72** [comment]
yes, I would like to have this feature. I have a set of subdirectories with a large number of files ( thousands maybe millions ) so the plane azcopy list command becomes very time consuming and difficult to deal with.

**Comment by joeshull** [comment]
+1 here

**Comment by delgadom** [comment]
bash workaround...
```bash
# find top level contents
azcopy ls "https://{store}.blob.core.windows.net/{dir}?SAS" | cut -d/ -f 1 | awk '!a[$0]++'

# find directories with depth N
N=3
azcopy ls "https://{store}.blob.core.windows.net/{dir}?SAS" | cut -d/ -f 1-${N} | awk '!a[$0]++'
```

**Comment by vasanth-bk** [comment]
+1 here

**Comment by KingLTS** [comment]
Same here, I sync many thousands of files with azcopy. The workaround to cut the top-level directories works, but is very slow.

I recommend an optional parameter like "--depth" to determine the required level. But a parameter "--top-level-only" would also work for me.

**Comment by KrisJanssen** [comment]
Yes, this is sorely needed...

**Comment by marc-hb** [comment]
sftp:// is the best workaround if you can afford it.

I recommend the `lftp` client, it has been working great for us. `lftp` has a `mirror` command that has been working much, much better than `azcopy sync`.

You can of course use any other `sftp://` client at the same time, they're not mutually exclusive.

Here's a list of other `azcopy` bugs that `lftp` + `sftp://` does NOT have:

- #1973, #1974, #1975, #221, #718, #1294, #1215,...

**Comment by matthai** [comment]
+1

**Comment by gabrielwebster** [comment]
+1

**Comment by marc-hb** [comment]
Please delete "+1" comments and use the "thumbs up" button at the top. Unlike "+1" comments, the latter is usable by both machines and humans.

**Comment by sizhky** [comment]
This is a work around using python's `azure-blob-storage` sdk

```python
from azure.storage.blob import BlobServiceClient
from azure.storage.blob import BlobPrefix

# Replace these with your actual connection string and container name
connection_string = "your_connection_string"
container_name = "your_container_name"

# Create a BlobServiceClient
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

# Get a reference to the container
container_client = blob_service_client.get_container_client(container_name)

# List only the top-level directories (virtual directories)
directories = set()

# Use walk_blobs with delimiter="/" to list virtual directories only
for blob in container_client.walk_blobs(name_starts_with='folder/where/you/want/to/ls/', delimiter='/'):
    if isinstance(blob, BlobPrefix):
        directories.add(blob.name[:-1])  # Remove trailing '/' from the name

# Print the top-level directories
for directory in directories:
    print(directory)
```

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.

**Comment by KrisJanssen** [comment]
Not doing something is hardly ‘completing’ it…

**Comment by marc-hb** [comment]
Closed reasons are a relatively new feature:
https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/

That's probably why they have been barely used:
https://github.com/Azure/azure-storage-azcopy/issues?q=is%3Aclosed+-reason%3Acompleted+

https://github.com/Azure/azure-storage-azcopy/pull/1  was in 2018

**Comment by duhu-sg** [comment]
Since 2020 I wait for this feature .... 👍
