### ISSUE TITLE
azcopy sync with mixed SAS and AD authentication - Authentication information is not given in the correct format

### ISSUE THREAD

**Issue by t-l-k** [Azure/azure-storage-azcopy#860]
##### Note: The version is visible when running AzCopy without any argument
10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

I had a SAS URL specified as the source system, and was intending to rely on AD authentication and RBAC for the target system. `azcopy login` was run first.

```
azcopy sync "<storage-url-with-sas>" "<storage-url-without-sas-but-with-azcopy-login>" --recursive --s2s-preserve-access-tier=false
```

### What problem was encountered?

I discovered today that you can't mix SAS and AD authentication methods between source and target systems in an `azcopy sync`. 

### How can we reproduce the problem in the simplest way?

The error was non-descriptive considering the above command, plus the `RESPONSE ERROR` was related to the source system, so I _thought I had messed up the SAS format_:

```
Description=Authentication information is not given in the correct format. Check the value of Authorization header.
```

All other request parameters looked well formed. I used Azure CLI to generate SAS tokens in Powershell:

``` powershell
az storage container generate-sas -n '<container-name>' --account-name <account-name> --https-only --permissions dlrw --expiry  (Get-Date).AddHours(1/4).ToString("yyyy-MM-ddTHH:mm:ssZ") -o tsv
```

### Have you found a mitigation/solution?

Use only one authentication method for both source and target system. Switching to 2x SAS tokens worked, and using 2x AD Authentication with RBAC worked.

**Comment by JohnRusk** [comment]
>using 2x AD Authentication with RBAC worked.

That's not supposed to work yet ;-)  Are you sure it worked for you?

**Comment by t-l-k** [comment]
@JohnRusk 

> That's not supposed to work yet ;-) Are you sure it worked for you?

Erm... yeah, in 1 subscription, copying from one storage account to another, using just container urls with no SAS, and having done an `azcopy login` authenticating as me using a device code, and after having set Storage Blob Data Owner to my user account, and yeah it just "works".

I can double check today and confirm ...

**Comment by JohnRusk** [comment]
Ah, I think it's because your source and destination were in the same account.  I was assuming they were in different accounts.

**Comment by JohnRusk** [comment]
It is supposed to work with RBAC for the destination and SAS for the source.  And indeed it does, in `azcopy copy`. Thanks for reporting the issue with Sync.

**Comment by adreed-msft** [comment]
_interesting, AND concerning_.

I can fire off an OAuth 2x transfer (but it won't succeed).

I can also fire off a SAS->OAuth tx and it'll fail because we're sending both OAuth and SAS credentials to the service.

This needs to be fixed.
