### ISSUE TITLE
combination 'S3Blob' not supported for sync command

### ISSUE THREAD

**Issue by arik-dokka** [Azure/azure-storage-azcopy#861]
### Which version of the AzCopy was used? 
10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Mac
### What command did you run?
 ./azcopy sync
### What problem was encountered?
Getting an error "combination 'S3Blob' not supported for sync command"
### How can we reproduce the problem in the simplest way?
run azcopy sync with s3 as source
### Have you found a mitigation/solution?
no

**Comment by arik-dokka** [comment]
@JohnRusk Hello. Just noticed you marked this issue as feature request. Does it mean it's not supported by design?

**Comment by JohnRusk** [comment]
For sync, we test and support only the combinations listed here: https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync

Currently S3-Blob is not one of them.  So I marked it as a feature request, for us to enable that option in AzCopy, test it, and support it.

**Comment by adreed-msft** [comment]
You may actually be able to replicate similar conditions to sync using the overwrite=IfSourceNewer flag, but this may not be exactly what you want since sync functions a little differently.

**Comment by JohnRusk** [comment]
Oh, yes, great idea @adreed-msft .  

@arik-dokka , the difference is that `copy` with `overwrite=IfSourceNewer` replicates the functionality of `sync` with `deleteDestination=false`.    So if you just need sync with deleteDestination=false, then you can get exactly the same effect with copy and overwrite=IfSourceNewer.

But if you need some other value of `deleteDestination`, then only sync will work and you can't do it with copy.

**Comment by arik-dokka** [comment]
@JohnRusk  Thanks, it's exactly what I need!
