### ISSUE TITLE
Login token not saved in Ubuntu 16.04

### ISSUE THREAD

**Issue by arik-dokka** [Azure/azure-storage-azcopy#862]
##### Note: The version is visible when running AzCopy without any argument
10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy <s3> <azure>
### What problem was encountered?
I'm getting "no SAS token or OAuth token is present and the resource is not public" error. It seems that authentication token not being stored after login since I can't logout as well, getting "failed to perform logout command, no cached token found for current user" error.
### How can we reproduce the problem in the simplest way?
run azcopy

**Comment by JohnRusk** [comment]
This looks like a duplicate of this one https://github.com/Azure/azure-storage-azcopy/issues/452

Please let us know if the workaround listed there (in the comments) works for you.

**Comment by arik-dokka** [comment]
Thanks guys, the workaround worked!
