### ISSUE TITLE
Azcopy from Blob container to local Windows 10 not keeping original date.

### ISSUE THREAD

**Issue by DavidLafond** [Azure/azure-storage-azcopy#865]
Azcopy 10.3.4
Windows 10
azcopy copy "https://MYSTORAGEACCOUNT.blob.core.windows.net/images/*" "X:\_LOCAL_IMAGES\TEST_STAGING"

I was expecting that azcopy will preserve the original date but all the dates (Created, Modified, Accessed) are the current date of the copy.

**Comment by JohnRusk** [comment]
Limited preservation is currently possible for downloads only, with the `preserve-last-modified-time` command line flag.

In version 10.4 there will be more options, but only for dealing with Azure Files. For Blob Storage, `preserve-last-modified-time` on downloads will still be the only option.

**Comment by DavidLafond** [comment]
OK thanks, I was expecting that it keeps the original date by default. I will downlad again the 500GB of image files with that flag this time.
Regards,
