### ISSUE TITLE
Azcopy sync not working as expected.

### ISSUE THREAD

**Issue by DavidLafond** [Azure/azure-storage-azcopy#866]
azcopy v10.3.4 on Windows 10.

Command used: azcopy sync "https://MYBLOBCONTAINER.blob.core.windows.net/images/*?sv=...MYSAS"  "X:\_LOCAL_FOLDER\images"

I first have done an azcopy to the local folder and it worked. To test the sync I deleted files localy and run again a sync. Azcopy alway mention that everything is sync nothing to do. I deleted all the local files and ran the sync. Azcopy mentionned that everything is sync but the folder is empty.

I'm doing something wrong? I have read everything found on the web but nothing about this issue.

Thanks

**Comment by JohnRusk** [comment]
I'm not sure what's happening. I don't think we normally use /* at the end of sync command lines. (Sync just acts like that's there, even when you dont' add it).

@adreed-msft  Could that be the cause of the unexpected behaviour?  If so, can you please add something to our backlog to show an error or warning message if /* is used in sync?

**Comment by adreed-msft** [comment]
@DavidLafond John is correct in that /* is not used at the end of sync.

Sync targets the contents of the directory, treating it as a duplicate of the root that the destination is.

When you add a /* to the end on sync, it treats it as a virtual directory. So it now goes searching in */ (note, * isn't a wildcard here), not every directory under the root images.

**Comment by DavidLafond** [comment]
Wow thanks for the information now it's working.

**Comment by JohnRusk** [comment]
@adreed-msft Can you add us a backlog item to at least provide an on-screen warning that case, so users are warned that /* with sync won't do what they are probably expecting.

**Comment by adreed-msft** [comment]
Sure thing.
