### ISSUE TITLE
small nit: inconsistent tag for the most recent 10.3.4

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-storage-azcopy#868]
Hi. Small note from a package maintainer: the latest release was tagged as `10.3.4` whereas all previous releases were tagged as `v10.3.4`. Just caught me by surprise for a couple of minutes.

**Comment by JohnRusk** [comment]
Thanks for reporting this. It was our mistake, we should have been consistent.  I think it makes sense for us to leave 10.3.4 as it is, but go back to the v prefix for all future releases.  Do you agree?

**Comment by JohnRusk** [comment]
cc @adreed-msft

**Comment by adreed-msft** [comment]
That makes sense to me.

**Comment by JohnRusk** [comment]
Closing. We used the v prefix for 10.4.0 and should do for all in future.
