### ISSUE TITLE
--include pattern command not working

### ISSUE THREAD

**Issue by qudiransari** [Azure/azure-storage-azcopy#871]
### Which version of the AzCopy was used? 
10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy copy '<network filepath>' "https://xxxxxxxx.blob.core.windows.net/xxxxxxx?sv=xxxxxxxxxx" --recursive --include-pattern '*.pdf'
### What problem was encountered?
I am getting below error msg where as there are files in the source folder. @JohnRusk  Please help.

failed to perform copy command due to error: no transfers were scheduled because no files matched the specified criteria

### How can we reproduce the problem in the simplest way?
running the above command

### Have you found a mitigation/solution?
no

**Comment by qudiransari** [comment]
Hi, There was some syntax issue which is resolved now.

**Comment by Michal-84** [comment]
Is it possible to use the --include - pattern 'Some_file_name * .csv' option on Linux? I am getting an error: 
bash: azcopy: command not found
If '--include--pattern' is not a typo you can run the following command to lookup the package that contains the binary:
    command-not-found --include--pattern
bash: --include--pattern: command not found

**Comment by totalnet32** [comment]
> Hi, There was some syntax issue which is resolved now.

could you share? having the same issue, its ignoring the --include--pattern '*.doc'
