### ISSUE TITLE
azcopy freezes when given URL to non-existent storage account

### ISSUE THREAD

**Issue by andrei-muresanu** [Azure/azure-storage-azcopy#872]
### Which version of the AzCopy was used?
azcopy version 10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Mac Catalina/same on any linux
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
./azcopy copy --recursive=true ../testfile https://doesnotexist.blob.core.windows.net/test?sas
### What problem was encountered?
freezes on scanning:
INFO: Scanning...

(freeze)
### How can we reproduce the problem in the simplest way?
just run the provided command
### Have you found a mitigation/solution?
use correct url

**Comment by JohnRusk** [comment]
Thanks. This is a known issue, in which DNS lookups take a long time to time out when the domain doesn't exist.  It's the correct DNS lookup behaviour, but it is confusing to users.  One day I think we might add something to monitor how long its taking and provide some sort of message.
