### ISSUE TITLE
Lots of OutOfRangeInput errors when trying to copy very large dataset from S3

### ISSUE THREAD

**Issue by manastalukdar** [Azure/azure-storage-azcopy#875]
### Which version of the AzCopy was used? 

10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows, Mac

### What command did you run?

```
azcopy.exe copy https://very-large-dataset.s3-us-west-2.amazonaws.com/some-folder "https://accountname.blob.core.windows.net/very-large-dataset?sastoken" --recursive=true
```

### What problem was encountered?

Getting lots of OutOfRangeInput errors when trying to copy very large dataset from S3. Not a single file was copied over.

```
RESPONSE Status: 400 One of the request inputs is out of range.
   Content-Length: [226]
   Content-Type: [application/xml]
   Date: [Sun, 23 Feb 2020 03:37:03 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [OutOfRangeInput]
   X-Ms-Request-Id: [5552e81f-c01e-0018-6efa-e94f39000000]
   X-Ms-Version: [2018-11-09]
Response Details: ﻿<Code>OutOfRangeInput</Code><Message>One of the request inputs is out of range. </Message>
```

After 10-15 mins, following error is returned in the console:

```
0.0 %, 0 Done, 204 Failed, 9796 Pending, 0 Skipped, 10000 Total (scanning...),

failed to perform copy command due to error: cannot start job due to error: cannot list objects, read tcp [2456:1700:ab98:52b0:d8f:974b:7638:sd34]:23489->[2456:1fa0:416d:fe0:34ed:ee21::]:443: wsarecv: An existing connection was forcibly closed by the remote host..
```

### How can we reproduce the problem in the simplest way?

Create a very large dataset in S3, with files running in the gigabytes. Total size of the dataset I am trying to copy is more than 1 TB.

### Have you found a mitigation/solution?

No.

**Comment by JohnRusk** [comment]
Hi, I can't tell what's going wrong based on the above info. Any chance you can zip up the AzCopy log file and email it to me? My email address is in my profile.  Log files contain filenames but do not contain any security credentials.

**Comment by manastalukdar** [comment]
Emailed logs to dev.

Also, in case anyone else runs into this issue, I was able to copy over many TB's of data from S3 to Azure blobs using Azure Data Factory, Copy Data.

**Comment by gapra-msft** [comment]
@manastalukdar I hope you were able to get your questions answered via email. Closing this issue for now as it is has been quite some time. Feel free to open a new issue if necessary.
