### ISSUE TITLE
azcopy latest version copy's source container folder named folder to destination 

### ISSUE THREAD

**Issue by vscodewinodws** [Azure/azure-storage-azcopy#876]
### How can we reproduce the problem in the simplest way?

execute command on 10.1.2 and 10.3.3 or 10.3.4 and check the results using storage explorer 

### Have you found a mitigation/solution?

no , looking for solution from azcopy team

**Comment by rishabpoh** [comment]
Hey @vscodewinodws, thanks for your feedback! If you take a look at our [ChangeLog](https://github.com/Azure/azure-storage-azcopy/blob/master/ChangeLog.md), the first bullet under 10.3 explains the difference between the following two source URLs: 
1. https://account/container/virtual?SAS 
2. https://account/container/virtualDir/*?SAS
The former copies the virtual directory virtualDir by creating a folder of that name at the destination. The latter copies the contents of virtual dir directly into the target without creating a folder named "virtualDir". Try changing your source URL to - "https://mysourceaccountforexample.blob.core.windows.net/mycontainer/*?mysas"

**Comment by vscodewinodws** [comment]
yes as per your comment I modified url and It works thanks a lot closings issue , since it's not issue and thanks for your kind help

**Comment by humblepie** [comment]
> Hey @vscodewinodws, thanks for your feedback! If you take a look at our [ChangeLog](https://github.com/Azure/azure-storage-azcopy/blob/master/ChangeLog.md), the first bullet under 10.3 explains the difference between the following two source URLs:
> 
> 1. https://account/container/virtual?SAS
> 2. https://account/container/virtualDir/*?SAS
> 

I'm using azcopy v10.3.4 on Mac OSX.

@rishabpoh I tried using the * pattern indicated in source url 2 and it is not working as specified.  Using the * pattern at the end of the virtual directory results in my files being uploaded to this path:

container/virtualDir/*/virtualDir

**Comment by humblepie** [comment]
Forget it.  I found my mistake.  For local directory copy to remote storage, you must specify the * pattern with the source directory.

The following command works:

azcopy cp **upload/*** "https://account/container/my/arbitrary/folder/upload/?SAS --recursive=true

**Comment by JohnRusk** [comment]
Yeah :-)   It works that way to be consistent with command shells (such as PowerShell and Bash).  But admittedly it's not as discoverable as we'd like.  We do call it out in the docs as best we can.
