### ISSUE TITLE
azcopy started failing while using --include-pattern and --exclude-path

### ISSUE THREAD

**Issue by qudiransari** [Azure/azure-storage-azcopy#879]
### Which version of the AzCopy was used? 
azcopy 10

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy copy "U:" "https://<storagename>.blob.core.windows.net/<containername>?<sas-token>" --recursive --exclude-path ~snapshot;ODB$ --include-pattern *.lis;*.dls;*.LIS;*.DLS;*.dlis;*.las;*.LAS;*.DLIS

### What problem was encountered?
No migration is hapenning and after scanning i am geting below lines
goroutine 391 [IO wait]:
internal/poll.runtime_pollWait(0x417f470, 0x77, 0xce3120)
        /opt/hostedtoolcache/go/1.13.0/x64/src/runtime/netpoll.go:184 +0x5c
internal/poll.(*pollDesc).wait(0xc000128e48, 0x77, 0x1145500, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x11ac118, 0xc000128d70, 0xbefd50, 0xc0125d8000, 0x401d, 0x401d)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Write(0xc000128c80, 0xc0125d8000, 0x401d, 0x401d, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/internal/poll/fd_windows.go:723 +0x338
net.(*netFD).Write(0xc000128c80, 0xc0125d8000, 0x401d, 0x401d, 0x401d, 0x4018, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/fd_windows.go:164 +0x56
net.(*conn).Write(0xc000f69100, 0xc0125d8000, 0x401d, 0x401d, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/net.go:196 +0x6f
crypto/tls.(*Conn).write(0xc0115c6000, 0xc0125d8000, 0x401d, 0x401d, 0xc00c7f6000, 0x4000, 0x8000)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:915 +0x167
crypto/tls.(*Conn).writeRecordLocked(0xc0115c6000, 0x17, 0xc00c7f6000, 0x8000, 0x8000, 0x8000, 0x8000, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:964 +0x2a6
crypto/tls.(*Conn).Write(0xc0115c6000, 0xc00c7f6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/crypto/tls/conn.go:1133 +0x1be
io.copyBuffer(0x4159ab0, 0xc0115c6000, 0xce2000, 0xc00d732ec0, 0xc00c7f6000, 0x8000, 0x8000, 0xb21160, 0xafef01, 0x4159a90)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:404 +0x202
io.Copy(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:364
net/http.persistConnWriter.ReadFrom(0xc000c61b00, 0xce2000, 0xc00d732ec0, 0x4159a90, 0xc000c61b00, 0x201)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1591 +0x8c
bufio.(*Writer).ReadFrom(0xc00c855500, 0xce2000, 0xc00d732ec0, 0x4159a70, 0xc00c855500, 0x1)
        /opt/hostedtoolcache/go/1.13.0/x64/src/bufio/bufio.go:713 +0x351
io.copyBuffer(0xce0c40, 0xc00c855500, 0xce2000, 0xc00d732ec0, 0x0, 0x0, 0x0, 0xc01429bc38, 0x40d06f, 0x20)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:388 +0x2f4
io.Copy(...)
        /opt/hostedtoolcache/go/1.13.0/x64/src/io/io.go:364
net/http.(*transferWriter).doBodyCopy(0xc00d720be0, 0xce0c40, 0xc00c855500, 0xce2000, 0xc00d732ec0, 0xc0115c61d8, 0xc01429bcc0, 0x6b7b69)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transfer.go:400 +0x71
net/http.(*transferWriter).writeBody(0xc00d720be0, 0xce0c40, 0xc00c855500, 0x2, 0x2)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transfer.go:359 +0x6e1
net/http.(*Request).write(0xc00f1eda00, 0xce0c40, 0xc00c855500, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/request.go:682 +0x6da
net/http.(*persistConn).writeLoop(0xc000c61b00)
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:2199 +0x1cf
created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.13.0/x64/src/net/http/transport.go:1567 +0xb2a

### How can we reproduce the problem in the simplest way?
run the above command
### Have you found a mitigation/solution?
No

@JohnRusk  Please help

**Comment by JohnRusk** [comment]
Is that the entire output, or is there more?  (You can email it to me if it's too big to post).

**Comment by gapra-msft** [comment]
@qudiransari are you still experiencing issues with this flags? I am going to go ahead and close this issue for now due to inactivity on the thread but if you are still hitting issues please open a new issue.
