### ISSUE TITLE
Provide a docker image on hub.docker.com

### ISSUE THREAD

**Issue by jmaitrehenry** [Azure/azure-storage-azcopy#88]
### Which version of the AzCopy was used? 
Try to use the new Go version of azcopy.

### Which platform are you using? (ex: Windows, Mac, Linux)
Docker, Linux container

### What command did you run?
For now, I'm building my own docker image base on this repository but it's not automated.

**Comment by zezha-msft** [comment]
Hi @jmaitrehenry, could you please elaborate a bit on your use case?

**Comment by zezha-msft** [comment]
Closing for now due to lack of response.

**Comment by PeterDaveHello** [comment]
I think the use case would be use the Docker image in CI/CD ecosystem to deploy some artifacts to the blob storage, I can help write the Dockerfile if you want. @zezha-msft maybe we can reopen this issue?

**Comment by PeterDaveHello** [comment]
Currently, there are about 70+ Docker repository of azcopy, just none of them are official, it'll be great if we can have an official one, just like the az cli ;)

**Comment by PeterDaveHello** [comment]
I was trying to write the Dockerfile with automatic build, however, I don't the rule of the date string in the download url, some of them seem to be the release date, but not all of them, thus I can't build all the existing versions, but only the latest version every build time, it'll be nice if anyone from Microsoft could help provide the info or just directly provide the official Docker image.

**Comment by PeterDaveHello** [comment]
I just build a azcopy image here, feel free to give it a try:
- https://hub.docker.com/r/peterdavehello/azcopy
- https://github.com/PeterDaveHello/docker-azcopy

**Comment by zezha-msft** [comment]
Thank you @PeterDaveHello! We'll have a look shortly!

**Comment by nakulkar-msft** [comment]
Tracking this at #423
