### ISSUE TITLE
Azcopy Sync operation fails on destination scan with timeout 500 error

### ISSUE THREAD

**Issue by kalininsn** [Azure/azure-storage-azcopy#881]
##### Note: The version is visible when running AzCopy without any argument
10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux(Centos 7.5)
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy sync /data/ 'https://account_name.blob.core.windows.net/container_name/SAS_KEY' --output-type json`
### What problem was encountered?
I'm running sync on about 650Gb set of files with ASDL2 container that was already synced before. After successfuly scanned source folder azcopy started scan of destination folder, and hangs on same amount of FilesScannedAtDestination on each run. Error message looks like:
`{"TimeStamp":"2020-03-04T09:08:06.270662679Z","MessageType":"Error","MessageContent":"{\"JobID\":\"ead3bb0b-7378-074f-769c-e486c7451726\",\"Error\":\"cannot list blobs. Failed with error -\\u003e github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=OperationTimedOut) =====\\nDescription=Operation could not be completed within the specified time.\\nRequestId:d3c63b42-701e-0099-1f04-f24a4d000000\\nTime:2020-03-04T09:08:06.2399087Z, Details: \\n   Code: OperationTimedOut\\n   GET https://account_name.blob.core.windows.net/container_name?comp=list\\u0026include=metadata\\u0026marker=2%21344%21mdawmjeyiu1uyzrore0xtxpfek9ettbovel3twpnd05erwdnq0f2ytjgdvlysnbar0ywwvdwnfkyaghibwrsqvrbefjevtvrakuwumtar016tkzramn2yvhsbmfxmxdim0owqvrbefjevtvsakewtkvoqk1vrtnra0l2ulvfdmmzvndjr3g1wtjoagfxnhzjbuyztdbwtljvrxztrvzrtdbwvfzfohzlv1zoy20xdmjuum9qvel3tvrzd05towtzwgwwyvcxbgmzumhiwee5txpfeu16vtrnvfk9itawmdayoceymdiwltazlta0vda4ojqyoju0ljg2otyxntnaiq--\\u0026restype=container\\u0026se=2021-01-28t18%3A38%3A44z\\u0026sig=-REDACTED-   User-Agent: [AzCopy/10.3.4 Azure-Storage/0.7 (go1.13.7; linux)]\\n   X-Ms-Client-Request-Id: [e4faab16-d795-4c09-41b0-346b3684542a]\\n   X-Ms-Version: [2018-03-28]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 500 Operation could not be completed within the specified time.\\n   Content-Length: [245]\\n   Content-Type: [application/xml]\\n   Date: [Wed, 04 Mar 2020 09:08:05 GMT]\\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\\n   X-Ms-Error-Code: [OperationTimedOut]\\n   X-Ms-Request-Id: [d3c63b42-701e-0099-1f04-f24a4d000000]\\n   X-Ms-Version: [2018-03-28]\\n\\n\\n\"}","PromptDetails":{"PromptType":"","ResponseOptions":null,"PromptTarget":""}}`
### Have you found a mitigation/solution?
Clean up destination container helps, but sync it back again from scratch takes too long

**Comment by JohnRusk** [comment]
I'm not sure why that's happening. 

Have a look at the new flag described here: https://github.com/Azure/azure-storage-azcopy/releases/tag/10.3.4  and for more info run `azcopy copy --help`

It let's you achieve the same effect that you're looking for, but with copy instead of sync.  This avoids the scanning of the destination. (Instead it does a separate data check for each file, as it goes).

**Comment by mohsha-msft** [comment]
Hi @kalininsn ,

Is the issue still persisting? I'm closing this issue. If it does persists, please reopen the issue.
