### ISSUE TITLE
always hit timeout when using azcopy to list or copy files from ot to azure container.

### ISSUE THREAD

**Issue by Icybiubiubiu** [Azure/azure-storage-azcopy#887]
### Which version of the AzCopy was used? 
1.Azcopy 10.3.4 on linux.
2.Try azcopy 10.3.2 on windows (using Microsoft Storage Explorer which has embeds azcopy10.3.2)
### Which platform are you using? (ex: Windows, Mac, Linux)
Both linux and Windows failed.
### What command did you run?
#497 azcopy list "container-URL-with-SAS-Token"
or
use storage explorer to copy data to container.
### What problem was encountered?
always indicate timeout when list files.
===error===
![image](https://user-images.githubusercontent.com/61815812/75957358-d82bc600-5ef4-11ea-8876-573d405ba4a3.png)

====end of error====

### How can we reproduce the problem in the simplest way?
I have no idea, maybe you can have make a great numbers of MB files under a folder, and then try to upload them to azure container.

### Have you found a mitigation/solution?
NA

**Comment by Icybiubiubiu** [comment]
we refer to this doc :
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

**Comment by mohsha-msft** [comment]
Closing due to age of issue. The service and the tool have both evolved quite a bit. Please let us know if you still experience this.
