### ISSUE TITLE
cannot use azcopy on linux env which is using proxy (not Kerberos, set https proxy)

### ISSUE THREAD

**Issue by Icybiubiubiu** [Azure/azure-storage-azcopy#888]
### Which version of the AzCopy was used? 
linux azcopy 10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
linux 
### What command did you run?
#azcopy.exe copy "file-on-local-machine" "URL on azure+SAS"

### What problem was encountered?
always hit error like:
![image](https://user-images.githubusercontent.com/61815812/75972392-5052b580-5f0e-11ea-888d-84a4447e630f.png)

### How can we reproduce the problem in the simplest way?
on this server, we can always hit this issue. 
Configure：
1.this server use proxy but not Kerberos authentication way.
2. we have set persist https configure in configure file. besides: we even set :
export https_proxy=<proxy IP>:<proxy port>
no help.
3. on this server we can use wget to outside internet. example: we can download azcopy and run it.

### Have you found a mitigation/solution?
NA, still blocked here.

Could you give some help on this?

**Comment by Icybiubiubiu** [comment]
we use this doc:
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

**Comment by JohnRusk** [comment]
@Icybiubiubiu I emailed you a suggested solution. If it works, can you please add a comment here so that anyone else with the same problem can see the solution.

**Comment by Icybiubiubiu** [comment]
Hi @JohnRusk 
 Thanks for your comments. yes, we used the following methods to solve this isseu:
export http_proxy=http://proxy-ip:port
export https_proxy=http://proxy-ip:port

**Comment by JohnRusk** [comment]
For anyone else reading this, the trick is that many proxies only support HTTP for their CONNECT command, even when proxying HTTPS traffic. What happens is that the client uses one command over HTTP (a CONNECT) command, to cause the proxy to open a TCP connection, then the client sets up a secure-end-to-end HTTPS session running over that connection (and all the proxy does is move the encrypted bytes, without ever understanding any of them).

It appears that only a small number of proxies support receiving the CONNECT over HTTPS (which is what @Icybiubiubiu 's original config was doing, when it had https_proxy=**https**://....
