### ISSUE TITLE
azcopy with scp

### ISSUE THREAD

**Issue by cometta** [Azure/azure-storage-azcopy#895]
May i know is it possible to use remote destination when using azcopy command? i would like to copy files from blob storage to a remote machine with scp

**Comment by JohnRusk** [comment]
Do you mean copy to the local drive of a remote machine?  No, that's not possible.  AzCopy can only access drives that are visible to the machine where AzCopy is running. (I.e. the local drives of the machine where AzCopy is running, plus any network drives that are accessible to that machine)
