### ISSUE TITLE
Run keyctl without root

### ISSUE THREAD

**Issue by cometta** [Azure/azure-storage-azcopy#899]
I am running azcopy and keyctl in a docker, i able to login successfully when i ran the docker with —privileged.  how to run azcopy login and keyctl without root and priviledge.

**Comment by adreed-msft** [comment]
https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile

The default seccomp profile for docker blocks the use of keyctl. You may be able to create a custom seccomp profile that allows access to it.

**Comment by JohnRusk** [comment]
See also https://github.com/Azure/azure-storage-azcopy/issues/423#issuecomment-598475492

**Comment by nakulkar-msft** [comment]
Closing this. Workaround [here](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store))
