### ISSUE TITLE
[Request] Standardised install and update methods for azcli across OSes

### ISSUE THREAD

**Issue by dijitali** [Azure/azure-storage-azcopy#900]
##### Note: The version is visible when running AzCopy without any argument
`AzCopy 10.3.4`

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac & Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
N/A

### What problem was encountered?
No standardised way to install this other than download URLs on this repo.  

Most major Microsoft projects seem to have a regular release process via a package manager that lets me:

- check for updates automatically and lets me report on them
- have a secure, signed download process
- reliable install and auditing of components across different machines/OSes rather than requiring a custom script

### How can we reproduce the problem in the simplest way?
N/A
### Have you found a mitigation/solution?
Other Microsoft mature projects like this offer regular packaged, signed releases, for example the Azure CLI, Powershell:

- https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest
- https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest
- https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7
- https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7

**Comment by adreed-msft** [comment]
Distribution via package managers is something that I believe we're planning on doing at a future date. When, we're not entirely certain about, however.

**Comment by elygre** [comment]
@adreed-msft For our usecase, a pure http download, as today is fine. However, it would be great if the executable itself could be immediately available (not inside a zip file), to avoid this brittle piece of code:

```
curl --silent --location https://aka.ms/downloadazcopy-v10-linux
| sudo tar xvz --wildcards --file - --strip-components 1 --directory /usr/local/bin "*/azcopy"
```

(It's one long line of code, broken into two for readability).

To me, this would be happiness:

```
curl --silent --location https://aka.ms/downloadazcopy-v10-linux-bin --output /usr/local/bin/azcopy
```

**Comment by yeroc** [comment]
@adreed-msft Any chance of this being revisited soon?  Seems strange that the `azcli` is available as a proper package but `azcopy` is not.

**Comment by seanmcc-msft** [comment]
We now support distribution through package manager for Red Hat Enterprise Linux (RHEL), Ubuntu, Mariner, Debian, SUSE, Rocky and CentOS.

https://github.com/Azure/azure-storage-azcopy/pull/2728
