### ISSUE TITLE
Runtime error is thrown by AzCopy while trying to copy a file from Bitbucket Pipelines' build resource/machine to a static website hosted through Azure blob storage container

### ISSUE THREAD

**Issue by darkroastcreative** [Azure/azure-storage-azcopy#901]
##### Note: The version is visible when running AzCopy without any argument
10.3.4 (amd64)

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux (via [Bitbucket Pipelines](https://bitbucket.org/product/features/pipelines))

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy copy "<PROJECT>-Webassets-11.zip" "https://<PROJECT>.blob.core.windows.net/$web<SAS TOKEN>"`

### What problem was encountered?
A runtime error is thrown by AzCopy while trying to copy a (artifact) file from Bitbucket Pipelines' build resource/machine to a static website ([hosted and configured through a Azure blob storage account](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website-host)), preventing the file from being copied to blob storage and preventing the associated pipeline from successfully running. This Pipeline is using AzCopy through the [azure-storage-deploy pipe published and maintained by Microsoft](https://bitbucket.org/microsoft/azure-storage-deploy/src/master/).

```shell
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/cmd.copyHandlerUtil.urlIsContainerOrVirtualDirectory(0xc000112f80, 0x1a4)
	/home/vsts/work/1/s/cmd/copyUtil.go:64 +0x285
github.com/Azure/azure-storage-azcopy/cmd.(*copyUploadEnumerator).enumerate(0xc0001bfb80, 0xc000136300, 0xc000602440, 0x27)
	/home/vsts/work/1/s/cmd/copyUploadEnumerator.go:52 +0x1909
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc000136300, 0xb, 0x40)
	/home/vsts/work/1/s/cmd/copy.go:866 +0x8c5
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc000136300, 0xe6, 0xb)
	/home/vsts/work/1/s/cmd/copy.go:579 +0x8a
github.com/Azure/azure-storage-azcopy/cmd.init.1.func2(0xc00017f900, 0xc0000af300, 0x2, 0x2)
	/home/vsts/work/1/s/cmd/copy.go:1140 +0x196
github.com/spf13/cobra.(*Command).execute(0xc00017f900, 0xc0000af260, 0x2, 0x2, 0xc00017f900, 0xc0000af260)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x1153b80, 0x100000, 0x100000, 0x100000)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc0000b6e62, 0xd, 0xc0000b6e62, 0xd, 0xfffff)
	/home/vsts/work/1/s/cmd/root.go:85 +0x88
main.main()
	/home/vsts/work/1/s/main.go:60 +0x211
```

### How can we reproduce the problem in the simplest way?

1. In a Git repository hosted on [Bitbucket](https://bitbucket.org), configure a Pipeline that creates a zip file in one step (using the `zip` command and making the resulting file an artifact of the step) and uses `azcopy copy` via the [azure-storage-deploy pipe](https://bitbucket.org/microsoft/azure-storage-deploy/src/master/) to upload the file to a Azure static website/blob storage container in a second step (referencing the artifact from the earlier step).
2. Run the pipeline created in step 1.

### Have you found a mitigation/solution?
No. My team and I reviewed the comments on issue #398 and its related issues, but could not find a solution that will allow AzCopy/our Pipeline to execute successfully.

**Comment by JohnRusk** [comment]
Given the call stack, I wonder if we're just getting tripped up by the $ in the path.  That _shouldn't_ happen, but its the first thing I'd check...

**Comment by Gambillan** [comment]
@JohnRusk After following up with your input we found the the $web needed to be escaped with a backslash to run successfully. Thank you for pointing us in the right direction.

**Comment by caffeineandfoxes** [comment]
@JohnRusk Thank you for your prompt follow up on this issue. I can confirm that the "$" in "$web" needed to be escaped with a backslash to allow AzCopy to copy our "source" file to a static website configured Azure blob storage (using the built in static website functionality). At this point, would you consider the issue with $web to be a bug in AzCopy?

**Comment by JohnRusk** [comment]
I'm suprised it needed to be escaped, not sure whether to consider it a bug or not. Will leave this issue open, to be investigated further.

**Comment by gapra-msft** [comment]
Just attempted to reproduce this issue in the latest AzCopy and confirmed this is no longer an issue. Closing this as a result. Please feel free to open a follow up issue in case anything else comes up!
