### ISSUE TITLE
Plan to GA aws related features

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#902]
### Which version of the AzCopy was used? 
10.3.3

Do you have any plan to GA AWS to Azure copy features? Azure Data Factory once asked us about whether there is a way to let users migrate data from AWS to Azure.

**Comment by JohnRusk** [comment]
@rishabpoh was discussing this just a few hours ago.  I'd suggest you email him to discuss.

**Comment by JasonYeMSFT** [comment]
Closing this since v10.5.0 says it is already GA.
