### ISSUE TITLE
AZCopy copy command 'panic: mkdir : no such file or directory' error when executing through Datastage Routine Activity

### ISSUE THREAD

**Issue by mcddvs** [Azure/azure-storage-azcopy#903]
### Which version of the AzCopy was used? 

10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)

Red Hat Enterprise Linux Server 7.6

### What command did you run?

azcopy copy "<PROJECT-PATH>/AltDept.txt" "https://<STORAGE-ACCOUNT>.blob.core.windows.net/dev?<SAS-TOKEN>"

### What problem was encountered?

The above command to transfer file AltDept.txt to storage runs successfully direct through Linux command line.  When the same command is run via IBM Datastage (v11.5.0.2) Routine Activity it is throwing the below error in Datastage logs:

_*** Output from command was: ***
panic: mkdir : no such file or directory

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/common.PanicIfErr(...)
	/home/vsts/work/1/s/common/lifecyleMgr.go:482
main.main()
	/home/vsts/work/1/s/main.go:55 +0x5df_

There is no log file being written to /<HOME>/.azcopy, which leads me to believe Datastage is not even initiating the command with AZCopy, and this is a problem related to Datastage.  However, I can't even make sense as to what this error means and am hoping for some guidance from the community.

### How can we reproduce the problem in the simplest way?

If possible, call the above command or similar from a Datastage Routine Activity.

### Have you found a mitigation/solution?

We have no solution in place.  For testing purposes we can call the command direct from the Linux interface, however we need the ability to embed this into an existing Datastage sequence.

**Comment by JohnRusk** [comment]
Please try setting the AZCOPY_LOG_LOCATION and AZCOPY_PLAN_FILE_LOCATION, and see if that fixes the problem. (See https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#change-the-location-of-the-plan-and-log-files)

**Comment by mcddvs** [comment]
Thank you for the suggestion, however this did not resolve the issue.  AZCOPY_LOG_LOCATION and AZCOPY_PLAN_FILE_LOCATION values have been set as per the linked document, and the change verified using azcopy env.  However, we are still getting the same error, and no azcopy log files are being written to the new specified location.  As I had mentioned, it doesn't appear that the Datastage call is even initiating the command with AZCopy, however I cannot make sense of the error (posted above) that I'm getting in my Datastage logs.

**Comment by JohnRusk** [comment]
The error you posted is from AzCopy, so the command is being initiated.  I suspect that the set of environment variables that are visible to AzCopy when its running in datastage are not the same as when its running in an command line window interactively. Where did you set them?

**Comment by mcddvs** [comment]
The account used to execute the command from both the Linux command line and from within the Datastage sequence is the same account, but that is a good place to start looking for any differences.  I'll dig into that a bit more and post back.  Thank you.

**Comment by JohnRusk** [comment]
One test would be to run AzCopy env in Datastage (and capture the output).  (Before you run azcopy copy)

**Comment by mcddvs** [comment]
Unfortunately I get the same error when I try to run AZCopy env from Datastage:

JobControl (ExecSHReturn): Error when executing command: .../azcopy env
*** Output from command was: ***
panic: mkdir : no such file or directory

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/common.PanicIfErr(...)
	/home/vsts/work/1/s/common/lifecyleMgr.go:482
main.main()
	/home/vsts/work/1/s/main.go:55 +0x5df

**Comment by JohnRusk** [comment]
Oh!  The directory it's trying to make at that point is the log directory, so I do strongly suspect that it's not picking up the environment variable that you've used to point it to a logging directory.

Maybe try a simple command to just echo that evironment variable, and get that executed by DataStage.  E.g. a bash script containing:
echo testing
echo "$AZCOPY_LOG_LOCATION"
echo done

My guess is that the middle lines in those scripts will output nothing, which will confirm the hypothesis that the environment variable setting is not making it through

**Comment by mcddvs** [comment]
You are absolutely correct:

*** Output from command was: ***
testing

done

How do we know where on the server it's trying to make the log directory?  Is it the /home/vsts/work/1/s location in the error msg?  Obviously that location doesn't exist on our server.  Confused as to why environment variables aren't coming across when the command is executed in Datastage under the same account.  I'll check with our Datastage admin.

Thank you for your help so far.

**Comment by mcddvs** [comment]
Success!

Solved by adding the log directory location to the .profile for the account Datastage is using, then explicitly loading the .profile as part of the script it's calling.

Thank you again for your help.  Much appreciated.

**Comment by JohnRusk** [comment]
Excellent!  Thanks for letting us know that it worked.

**Comment by aguegu** [comment]
But why would `/home/vsts/work/`show up in azcopy? It should never look for path like that for the first place.
