### ISSUE TITLE
Block blob upload with piping ignores flag(s)

### ISSUE THREAD

**Issue by jvbmov** [Azure/azure-storage-azcopy#904]
### Which version of the AzCopy was used? 

10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)

Windows 10 Enterprise (10.0.18362 Build 18362)

### What command did you run?

Powershell:

- Works: 

>> D:\> D:/azcopy.exe copy "D:/test_mcect.txt" "https://{account}.blob.core.windows.net/{container}/{folder}/test_mcect.txt?{SAS" --log-level="info" --put-md5="true" --recursive="true" --metadata="author=prjain;viewport=width;description=test file" --content-type="testctype" --content-encoding="testenc" --no-guess-mime-type="true"

- Fails: 
>> D:\> cat .\test_8mb_blob_piping_upload.txt |
>> D:/azcopy.exe copy "https://{account}.blob.core.windows.net/{container}/{folder}/test_8mb_blob_piping_upload.txt?{SAS}" --log-level="info" --put-md5="true" --metadata="author=prjain;viewport=width;description=test file" --content-type="testctype" --content-encoding="testenc" --no-guess-mime-type="true"

And any other combination of flags, even a single flag. Also, Python (3.7.6) subprocess.run() equivalents show the same behaviour.

### What problem was encountered?

The file is uploaded correctly, however, flag based information (md5, metadata etc.) is completely ignored. It seems that somehow the command is processed as an upload and then as a download call.

### How can we reproduce the problem in the simplest way?

1. Create an example file (here: test_16mb_blob_piping_upload.txt)
2. Compare output of the following (PowerShell) commands:

- Fails: 

>> D:\> cat .\test_16mb_blob_piping_upload.txt |
>> D:/azcopy.exe "https://{account}.blob.core.windows.net/{container}/{folder}/test_8mb_blob_piping_upload.txt?{SAS}"  --log-level="info"

- Works:

>>D:/azcopy.exe copy "D:\test_16mb_blob_piping_upload.txt" "https://{account}.blob.core.windows.net/{container}/{folder}/test_8mb_blob_piping_upload.txt?{SAS}" --log-level="info"

### Have you found a mitigation/solution?

Not yet. We've tried many combinations with subprocess (input, stdin, etc.) based on the unit tests.

**Comment by adreed-msft** [comment]
Yes. Currently, uploading via pipe bypasses all enumeration and the backend, and occurs right in the frontend.

**Comment by polys** [comment]
I'm having the same issue with v10.4.3 on Linux.
`--content-type` and `--content-encoding` are completely ignored when piping.

Are there plans to make this work?  If not, maybe you could update the documentation to say so?

**Comment by evenh** [comment]
I would also like the flags to work when piping data between processes

**Comment by gapra-msft** [comment]
Hi, I believe in the latest azcopy version, piped uploads now support setting of content headers, metadata and tags. Closing this issue as a result.
