### ISSUE TITLE
sync produces inconsistencies if killed

### ISSUE THREAD

**Issue by hacst** [Azure/azure-storage-azcopy#906]
### Which version of the AzCopy was used? 
10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy sync --delete-destination true 'https://XXX.blob.core.windows.net/...' /some/folder

### What problem was encountered?
If killed during the initial download (e.g. due to system/process crash) azcopy sync leaves pre-allocated files of the correct size containing 0 bytes in place of the real files. If run again later against this folder structure azcopy will report it as already in sync as the file is newer and has the correct size.

### How can we reproduce the problem in the simplest way?
Run azcopy sync with a big file. Wait for azcopy to pre-allocate the file and then kill it (kill -s 9). Run azcopy sync again and see it report everything is in sync while the file most definitely is not.

### Have you found a mitigation/solution?
Fully mitigating this outside of azcopy does not seem feasible without doing things like manually checksumming all local files.

The real solution could be for azcopy to perform initial download to a temporary location or filename and then atomically move/rename each file once it is done. This prevents it from getting into this inconsistent state and seems easy to implement. Another hack might be to initially artificially make the files older than their originals until they are downloaded but that might have unintended side effects.

More generally it would make sense to at least verify the size of the files though that alone would not help this issue. Having a mode in which the md5 of the local files is used to verify whether files are in sync would also be helpful but of course that would be a different game in terms of load on the filesystem during verification.

**Comment by JohnRusk** [comment]
Sorry 1openWindow, you were assigned to this in error, when I clicked the wrong thing!

**Comment by hacst** [comment]
@zezha-msft @JohnRusk  Any udpates on this? Shouldn't this be considered a bug considering the goal of azcopy sync?

**Comment by JohnRusk** [comment]
@hacst I've moved on to a different project now.  @zezha-msft may be able to comment.

**Comment by zezha-msft** [comment]
Sorry for the delay! 

The only option that's available right now is to create temporary files like you suggested. I'll add this item into our backlog.

**Comment by seanmcc-msft** [comment]
Unfortunately, we are not going to add this functionality.  We are focused on documentation, testing, and quality, and this feature would represent a large increase in scope for the product.
