### ISSUE TITLE
Set Blob Properties - HTTP Cache-Control, etc

### ISSUE THREAD

**Issue by mrgregwaugh** [Azure/azure-storage-azcopy#93]
Is there a way to set properties on uploaded files, such as HTTP x-ms-blob-cache-control?

### Which version of the AzCopy was used? 
AzCopy/v10.0.2-Preview Azure-Storage/0.1 (go1.10.3; Windows_NT)

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows 10

**Comment by zezha-msft** [comment]
Hi @Snfhm, you could use Storage Explorer to set cache control on those files. We'll get to adding this support soon, sorry for the inconvenience!

**Comment by Snfhm** [comment]
Thanks @zezha-msft. Do you have some documentation for that?

If I try to set cache control property using PowerShell script in Azure Web App post deployment, do you think it is possible?

**Comment by eelkram** [comment]
This would be great.  I want to add the cache control property when uploading through Azure DevOps Pipelines.

**Comment by jogonzal** [comment]
+ 1, the lack of this option makes me do manual work instead of automating it in my azure devops pipeline

**Comment by pierfrancesco** [comment]
+1

**Comment by JohnRusk** [comment]
This feature was added in the most recent release: https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.1.2  (Sorry about the delay in updating this issue)

**Comment by dpolivy** [comment]
@JohnRusk Is it possible to have these properties supported for `azcopy sync` as well?

**Comment by JohnRusk** [comment]
For sync, the plan is that they should be sync'd if the sync is blob-to-blob (they're not right now, but that's a bug, and they will be soon).  We haven't yet thought of doing them for upload-style syncs.  @zezha-msft is our sync expert. @zezha-msft  what do you think?
