### ISSUE TITLE
azcopy login

### ISSUE THREAD

**Issue by zffocussss** [Azure/azure-storage-azcopy#933]
### Which version of the AzCopy was used? 
AzCopy 10.2.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux/Mac

### What command did you run?
I want to use azcopy like az storage file

### What problem was encountered?
authenticate are hard to operate

### How can we reproduce the problem in the simplest way?
everytime I want to transfer

### Have you found a mitigation/solution?
no.

I want to know is there a way to make azcopy authenticate like az storage file
there are two environment variables set needed,
one storage account name,the other storage key.

**Comment by JohnRusk** [comment]
Hi.  Authentication to Azure Files with the account key is not supported in AzCopy v10.  And, I'm sorry, we have no plans to support it.  In Azcopy v10, we are trying to move users away from shared key authentication.  For Blob and ADLS Gen to, the tool already offers a number of options, including three forms OAuth (also known as Azure AD Authentication).   Those options are better from a security point of view.  AzCopy also supports SAS token authentication for Azure Files and blob Storage.  THat's actually the easiest option to use, and is the only supported option for Azure Files.

**Comment by JohnRusk** [comment]
Details of all the login options that are supported are here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#choose-how-youll-provide-authorization-credentials
