### ISSUE TITLE
[File share] Windows explorer not listing files in folder after azcopy remove with exclude-pattern

### ISSUE THREAD

**Issue by zonenet** [Azure/azure-storage-azcopy#939]
##### Note: The version is visible when running AzCopy without any argument
amd64 10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy remove "https://[storagename].file.core.windows.net/produksjon/8007_Atlant/Passeringstranser/Innlest?[SAS]" --recursive=true --exclude-pattern="tr202003*;tr202002*"

### What problem was encountered?
after deleting everything except files starting with the exclude-pattern, the folder looks empty in file explorer (Windows)
even powershell get-childitem gives error on listing content
even tried to restart my computer without any luck.

### How can we reproduce the problem in the simplest way?
the folder contained about 270 000 files before I started the azcopy remove, and it seems to only be a problem when the folder contains massive amounts of files.
try running the same command on a folder/directory with high number of files.

### Have you found a mitigation/solution?
azcopy list displays a list of the folders content, but this is not a solution, just a confirmation that the files still are there.. (roughly 68 000 files)
this list also contains files created after the azcopy remove command completed, meaning not even new files gets listed in windows explorer.
also "storage explorer (preview)" lists the files after loading a while.

**Comment by JohnRusk** [comment]
Can I make sure I understand correctly:
1. For files that matched the exclude pattern, you know that AzCopy did NOT delete them. Correct? (Because you can see them in Storage Explorer).
2. But you can't see then in Windows Explorer, when you look at the file share.

Is that right?

**Comment by JohnRusk** [comment]
If that is right, it sounds like a File Share/Windows explorer issue.  I don't know what might cause that, so I have to fall back to "Support 101": have you tried rebooting the Windows machine that you are running Windows Explorer on?

**Comment by zonenet** [comment]
> Can I make sure I understand correctly:
> 
> 1. For files that matched the exclude pattern, you know that AzCopy did NOT delete them. Correct? (Because you can see them in Storage Explorer).
> 2. But you can't see then in Windows Explorer, when you look at the file share.
> 
> Is that right?

1. That's correct, azcopy did not delete them. I can see them in Storage Explorer and with azcopy list
2. The files are not visible to anyone with access through unc path. 
The kicker here is that when someone tries to open the folder in windows explorer, it starts loading for a while (like there is too many files to list at once) but then it just ends up showing an empty folder.

I have tried rebooting my Windows machine which did not change anything. (still empty and still loading for a while before showing contents)

**Comment by JohnRusk** [comment]
Next thing to investigate then, is whether ACLs (security permissions) are preventing it from showing up.  Are you able to figure out what the full path name of one of the files would be, as seen from Windows Explorer (if you could see it)?  If so, try a test on that machine: try using robocopy to copy the file to somewhere else (e.g. onto the machine's temp drive).  Run robocopy from an admin command prompt, and specify its backup mode (which I think is /b).  That can help it to see files that you can't normally see. If that works, then you have a permissions issue.

If that fails, I'm out of ideas, and this will be a question for the Azure Files team.  After you try the above, let me know if you'd like me to forward this on to them.

**Comment by zonenet** [comment]
robocopy \\folder\path C:\temp [filename from storage explorer]
worked just fine, even without the backup mode.

so there seems to be some kind of permission issue, but how do I go about to fix this on a azure file share given that this use access keys instead of user/group specific access management like regular fileservers?

**Comment by JohnRusk** [comment]
I don't know. I'll see if I can get someone from the File Shares team to take a look.

**Comment by JohnRusk** [comment]
I'm going to close this issue (the AzCopy issue) now, since it appears to be, and is being handled as, an Azure Files issue, as per Leslie's request for a email.
