### ISSUE TITLE
azcopy log size issue

### ISSUE THREAD

**Issue by jethrogalolo** [Azure/azure-storage-azcopy#959]
### Which version of the AzCopy was used? 
azcopy 10.4.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
--log-level
### What problem was encountered?
When i azcopy files that have sizes of 100 GB logs was too large also. What command i can use for the --log-level so i can get only the summary or the important logs only.
### Have you found a mitigation/solution?
Not yet

**Comment by JohnRusk** [comment]
--log-level ERROR

Is the option that we recommend in this case.
E.g.
```
azcopy copy "source" "destination" --recursive --log-level ERROR
```
