### ISSUE TITLE
Synchronize contents between two Storage Accounts

### ISSUE THREAD

**Issue by RoseAlgebraI** [Azure/azure-storage-azcopy#96]
Hello,

Is it possible for the Sync command to provide support in synchronizing contents between two storage accounts?

Thank you.

**Comment by seguler** [comment]
Not at this moment. However you can instead use `azcopy cp` command with `--overwrite=false` flag to skip overwriting existing files and sync two accounts.

**Comment by himannetwork** [comment]
https://charbelnemnom.com/2019/11/how-to-sync-between-azure-blob-storage-accounts-and-from-azure-files-to-azure-files/
