### ISSUE TITLE
Response Status: 400 The specified block list is invalid fails AzCopy

### ISSUE THREAD

**Issue by ComeChao** [Azure/azure-storage-azcopy#961]
### Which version of the AzCopy was used? 
v10.3.2

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
cp E:\xxx\Data\* https://xxxblb.blob.core.windows.net/csvfiles/xxxx-713e-4ee5-987c-8f410996f142?xxxxx

### What problem was encountered?
We developed an app that calls AzCopy v10 to copy CSV files from an on premises storage to an Azure storage account.

We are getting one error we do not understand as can be found in this log entry. **We noticed that AzCopy does not retry if it gets a 400 error back from a blob storage account.**

-------------
2020/03/26 16:16:27 == REQUEST/RESPONSE (Try=1/2.5141003s, OpTime=2.5351634s) -- RESPONSE STATUS CODE ERROR
   PUT https://xxxxxblb.blob.core.windows.net/csvfiles/xxxxxxx-713e-4ee5-987c-8f410996f142/xxxxx.csv?comp=blocklist&xxx&timeout=901
   Content-Length: [50723]
   Content-Type: [application/xml]
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Md5: []
   X-Ms-Blob-Content-Type: [text/plain; charset=utf-8]
   X-Ms-Client-Request-Id: [d1be9c97-xxx-46b7-5030-81b15770axxx]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   **RESPONSE Status: 400 The specified block list is invalid.**
   Content-Length: [221]
   Content-Type: [application/xml]
   Date: [Thu, 26 Mar 2020 16:16:25 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [InvalidBlockList]
   X-Ms-Request-Id: [017e6646-001e-00f3-0f89-0337cb000000]
   X-Ms-Version: [2018-03-28]
**Response Details: ﻿InvalidBlockList	The specified block list is invalid.**

-------------

We would like to understand what we are doing wrong so we can fix it.

### Have you found a mitigation/solution?
no

**Comment by JohnRusk** [comment]
We are working on providing better diagnostic messages for this error. In the meantime, you can try a few things:

1. If you can see the problem blob in Azure Storage Explorer, delete it there and try again(*).
2. If you can't see the problem blob in Azure Storage Explorer, make sure that you are running AzCopy with delete rights (i.e. if using SAS authentication make sure the SAS allows delete permissions).  Sometimes this allows AzCopy to sort out the problem for you.  You need to run AzCopy twice in this case: once to let it clean up the bad blob, and again to let it upload the good one.(*)
3. If nothing else works, create an empty text file (or any other very small file), with the same name as a problem blob, and upload it "over the top of" the problem blob. Then upload you real content to the blob.

(*) Note that if you ran an AzCopy job that reported lots of failures, you can use [azcopy jobs resume](https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-jobs-resume) to resume the job (i.e. to re-run the transfers for just the files that failed).  This way you don't have to re-transfer all the blobs that worked successfully.

**Comment by nakulkar-msft** [comment]
Closing this because of age. Also, this issue has not been seen in recent times.

**Comment by mathieulongtin** [comment]
Seeing this issue with 10.16.2. --overwrite=false, files are not visible in blob storage, the storage is set to be hierarchical, but using the blob API, using a SAS token with all permissions.

It seems that if there was a failed upload, there are some invisible remnants of the file, it doesn't appear in the soft delete list either. 

If I create the file by other means and delete it, azcopy will copy the file.

**Comment by nakulkar-msft** [comment]
Hi @mathieulongtin, pleas open a new issue and post logs. Thanks

**Comment by momodedev** [comment]
Dear All,

Can you help me about the below issue?

2025/02/04 15:31:31 ==> REQUEST/RESPONSE (Try=1/7.6382ms, OpTime=7.6382ms) -- RESPONSE STATUS CODE ERROR
   PUT https://urlREDACTED/dt=20250204/event_code=paid_mem_type_qualif/005837_0?comp=blocklist&timeout=901
   Authorization: REDACTED
   Content-Length: [2038]
   Content-Type: [application/xml]
   User-Agent: [AzCopy/10.16.2 Azure-Storage/0.15 (go1.23.1; Windows_NT)]
   X-Ms-Access-Tier: [Hot]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Type: [application/octet-stream]
   X-Ms-Client-Request-Id: [ef55d74b-c40c-4d61-69b7-57dbb90e7e36]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The specified block list is invalid.
   Content-Length: [221]
   Content-Type: [application/xml]
   Date: [Tue, 04 Feb 2025 15:31:30 GMT]
   Server: [Microsoft-HTTPAPI/2.0 Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [ef55d74b-c40c-4d61-69b7-57dbb90e7e36]
   X-Ms-Error-Code: [InvalidBlockList]
   X-Ms-Request-Id: [137a6aba-001e-0026-0819-770742000000]
   X-Ms-Version: [2020-10-02]
Response Details: ﻿<Code>InvalidBlockList</Code><Message>The specified block list is invalid. </Message>

**Comment by momodedev** [comment]
Can you help me? The issue  is still there.
