### ISSUE TITLE
AzCopy fail to copy multiple items from a file share snapshot

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-azcopy#964]
### Which version of the AzCopy was used? 
10.4.0

### Which platform are you using?
macOS

### What command did you run?
./azcopy copy "https://easybugs110.file.core.windows.net/fs10/*?sv=2018-03-28&ss=f&srt=co&sp=rl&se=2020-04-23T23%3A18%3A35Z&sig=<REDACTED>&sharesnapshot=2020-03-05T18%3A06%3A58.0000000Z" "https://easybugs110.file.core.windows.net/fs10/?se=2020-05-16T23%3A19%3A38Z&sp=rwl&sv=2018-03-28&sr=s&sig=LP5STGXpBMabAHQVw1zd8%2BxVVOFyWai8wjaecS92AEY%3D" --overwrite=prompt --recursive --list-of-files "/var/folders/ww/bk24s62x4n3g9vhzt6czwndr0000gn/T/stg-exp-azcopy-cbf7ea31-f07f-417f-a784-4028e1558ec5.txt" --cap-mbps 123 --s2s-preserve-access-tier=false;

List of file contains:
512B copy 100.txt
blobs2.txt

### What problem was encountered?
AzCopy fails with the log file
[c0910ca2-36ce-5845-5893-cef4abf7c4c7.log](https://github.com/Azure/azure-storage-azcopy/files/4494775/c0910ca2-36ce-5845-5893-cef4abf7c4c7.log).

### How can we reproduce the problem in the simplest way?
Try copying two items from a file share snapshot to its root.

### Have you found a mitigation/solution?
Use Azure Storage SDK.

**Comment by nakulkar-msft** [comment]
Fixed with #1442
