### ISSUE TITLE
Error message misspelling

### ISSUE THREAD

**Issue by dporterf** [Azure/azure-storage-azcopy#965]
https://github.com/Azure/azure-storage-azcopy/blob/92eafc2923c2cdc1e8d0528166aaff7ba1ff7f6b/cmd/copy.go#L600

"service" misspelled.
see "copying from sevice to service"

**Comment by adreed-msft** [comment]
Ooh! that's embarassing.

**Comment by adreed-msft** [comment]
Thanks for pointing it out!

**Comment by nakulkar-msft** [comment]
Fixed with #966
