### ISSUE TITLE
azcopy copy to Azure storage container with SAS token, works but reports Failed if read permission not set

### ISSUE THREAD

**Issue by widget31too** [Azure/azure-storage-azcopy#975]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.4.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy copy _localfile_ "https://_storage-container-path_?_sas-token_"

### What problem was encountered?
We have a "dropbox" storage container that we only want our client system to copy files to. I thought that creating the SAS token to only include create permission would do this (upload only once, and don't allow listing or download of any of the files).

This worked, mostly - the file is copied to the storage container, no errors are reported, but the job summary reports the transfer as failed and status code are set to 1 (error) 

### How can we reproduce the problem in the simplest way?
Using Azure PowerShell, create a SAS access token for a storage container:
`$context = (Get-AzStorageAccount -ResourceGroupName <name> -AccountName <storage account name>).context`
`New-AzStorageContainerSASToken -Context $context -Name <container name> -Protocol HttpsOnly -Permissions c -ExpiryTime '2120-04-22 18:00:00' -FullUri`

Use the generated URI for the azcopy command destination.

### Have you found a mitigation/solution?
Add read permission when creating the SAS token

**Comment by JohnRusk** [comment]
The error probably comes from the length check that we do at the end, as a sanity check of the transfer.  You can put `--check-length=false` on the command line if you don't want that check, and then it won't fail.

We may make it smarter about this in the write-only case in a future release.  I'm going to close this issue now, but let us know if the check length setting isn't a suitable solution for you.
