### ISSUE TITLE
AzCopy - Scheduler Batch Job - does not transfer/migrate files when user is signed out the machine

### ISSUE THREAD

**Issue by Kishoremg040** [Azure/azure-storage-azcopy#977]
### What problem was encountered?
Hi Team, We are trying to automate migrating on-premises data to cloud storage with AzCopy. We have created a Windows Task scheduler job by copying the **azcopy sync** commands onto a .bat file. We are using Shared access signature within azcopy sync commands. We have tested, deployed and scheduled this on to a server with a frequency of every 1 hour. 

The scheduler job runs perfectly fine when the user is (remote) logged onto the machine/server. 

But when the user is signed-out of the machine/server, the files does not transfer. Even the azcopy logs are not being generated during this period. Looking at the event log we figure out some kind of Proxy issues, but not sure how to resolve this.

Tried setting the proxy using the following command "set https_proxy=http://.." but for no luck.

The moment we again logon to the machine/server, the files start transferring, the logs are being generated.

We are running the scheduler Job with elevated privileges and the account running it have admin rights and have enough permissions/privileges.  https://danblee.com/log-on-as-batch-job-rights-for-task-scheduler/

Does AzCopy SYNC always require interactive login ? Should we use any external tools like proxycfg.exe  etc 

Anything wrong with my approach. Please advise on how to resolve this issue or any other alternative solution. Thank you.

![azcopy_10 3 3_SchTask_signout_issue](https://user-images.githubusercontent.com/64216346/80129856-ac78a400-8565-11ea-9399-9e4e96d19aef.png)

**Comment by JohnRusk** [comment]
The error you are showing says proxy authentication required.  AzCopy v10 does not yet support NTLM and Kerberos proxy authentication (and I'm assuming your proxy has one of those types, because the others are not very secure).

Is it possible that when logged in interactively the traffic goes by a different proxy, that does not require authentication?  Or maybe it uses no proxy at all?  To make AzCopy 10.4 use no proxy at all, you need to set these two environment variables as follows:

HTTP_PROXY="dummy.invalid"
NO_PROXY="*"

It's the second one that is important (use no proxy for domains matching *, i.e. everything). The first one is just to trick AzCopy into actually using the second one.

Does that help?

**Comment by Kishoremg040** [comment]
Thanks John for the prompt response. I tried your suggestion, but it did not fix the issue. 

Moreover when the HTTP_PROXY is configured incorrectly with some dummy/invalid value (http://proxy.invalid) the scheduler job is running indefinitely - doing nothing, even when logged in interactively or manually initiating the scheduler job.

The individual NO_PROXY entry also has no effect, when signed-out of the machine i.e. it does nothing until next interactive login happens.

I even tried this **http_proxy=http://USERNAME:PASSWORD@PROXYIP:PROXYPORT**, but for no luck.

Please advise. Thank you.

![azcopy_logs_events](https://user-images.githubusercontent.com/64216346/80235798-312bf680-8628-11ea-8b8a-e01e5e752360.png)

**Comment by JohnRusk** [comment]
Sorry about that.  I must have messed up my testing of that solution, somehow.  It certainly did work when I tried it.  But I'll retest and try to figure out what's going on.  Which command prompt are you using, CMD or PowerShell?

**Comment by JohnRusk** [comment]
Hi again. I've found the problem.  It's all about the quotes.

If running from the CMD command prompt, it should look like this (no quotes)

```
set HTTP_PROXY=dummy.invalid
set NO_PROXY=*
```
Does that work for you?

BTW If running from PowerShell, it should look like this:
```
$env:HTTP_PROXY="dummy.invalid"
$env:NO_PROXY="*"
```

**Comment by Kishoremg040** [comment]
Hi John, Thanks much for the support. 

Setting  **HTTPS_PROXY** resolved the issue. The scheduler job is able to transfer the files even with out interactive login now.
e.g. : https_proxy=http://USERNAME:PASSWORD@PROXYIP:PROXYPORT

Thank you.
