### ISSUE TITLE
AzCopy 10.4.0  Coping files from one folder to another folder in Gen2 Storage account - a SAS token (or S3 access key) is required as a part of the source in S2S transfers

### ISSUE THREAD

**Issue by srini99mkl** [Azure/azure-storage-azcopy#980]
### Which version of the AzCopy was used? 
10.4.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
AzCopy cp $blobstoragepath+$filename $BlobStoragePath+$newFileName
$blobstoragepath and $filename are parameters

### What problem was encountered?
I was told AzCopy 10.4.0 onwards we do not need to use SAS key to copy files in Gen2 storage account from one folder to another folder, but this feature is not working.  Here is the error message I am seeing while I am trying to copy files from one folder to another folder with a Gen2 storage account

**failed to perform copy command due to error: a SAS token (or S3 access key) is required as a part of the source in S2S transfers, unless the source is a public resource** 

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
Sorry, due to heavy demand of higher priority issues, that feature had to be dropped from 10.4.

cc @rishabpoh

**Comment by gapra-msft** [comment]
Hi @srini99mkl I believe we require OAuth or SAS for any s2s transfers, so closing this issue for now. Feel free to open a new issue in case you have any further questions/problems with the tool.
