### ISSUE TITLE
azcopy update - better user experience expected

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [Azure/azure-storage-azcopy#985]
### Which version of the AzCopy was used? 
AzCopy 10.4.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac
### What command did you run?
INFO: azcopy: A newer version 10.4.1 is available to download

No `azcopy update` command line, no link to download

### What problem was encountered?
Counting the steps to update AzCopy
1. Google `azcopy download` (no link from the original info message)
2. Open `https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10` (no explanation on the website, just download it)
3. Click on Mac version
4. Downloaded a file `azcopy_darwin_10.4.1.zip` (no installer, no documentation guidance from the microsoft.com website)
5. Go to Download subfolder `azcopy` binary present
6. Hmm, where I need to copy this file? Open a terminal, Check where it is `which azcopy`
7. Copy the file `sudo mv ~/Downloads/azcopy_darwin_amd64_10.4.1/azcopy `which azcopy``
8. Installed but not working as considered as malware

<img width="420" alt="image" src="https://user-images.githubusercontent.com/8209940/80289713-07e19800-8706-11ea-9824-fc0f4f789644.png">

9. Open Finder
10. Go to /usr/local/bin
11. Click Control + context menu and click on Open 

The competition is doing the same in one step `gcloud components update` (including the update of plenty of tools not gsutil only)

Comparative analysis
If you need to rank your tool for user experience what will be the result?

**A suggestion provides a one-click update option `azcopy update` like the competition.**

### Have you found a mitigation/solution?
Example of scripts to do this for Windows, Linux
https://www.thomasmaurer.ch/2019/05/how-to-install-azcopy-for-azure-storage/

**Comment by JohnRusk** [comment]
Thanks for the suggestion.

cc @zezha-msft for visibility the MacOS issues in the steps.

**Comment by PaulG77** [comment]
We were considering deploying azcopy using intune (so that we could use it in scripts to keep part of the local file system up to date). However to do the app needs to be notarized:-
https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-notarizing-your-macos-apps-to-prepare-for-macos/ba-p/808579

As far as I can tell azcopy 10.8 isn't notarized. I see little evidence of this being added to the 10.9 release.  This mean that teying to run azcopy would likely result in warning messages appearing to end users. This means it isn't yet a workable solution for us!

**Comment by zezha-msft** [comment]
Thanks for reaching out @PaulG77. We appreciate the feedback.

We are aware of the problem and will try to tackle it soon, hopefully with the next release.

**Comment by mohsha-msft** [comment]
This has already been taken care of in the new AzCopy release `10.10.0`. Please try to take a look and reopen  if the issue persists

**Comment by AlexDelPab** [comment]
I wanted to upgrade from version 10.10 to 10.12., but now the issue reoccurs with the error message: “azcopy” can’t be opened because Apple cannot check it for malicious software.
