### ISSUE TITLE
SAS token generated from azure-cli is not able to authenticate through azcopy v10.4.1

### ISSUE THREAD

**Issue by toothache** [Azure/azure-storage-azcopy#986]
### Which version of the AzCopy was used? 
10.4.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux [Ubuntu 18.04.4 LTS]

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

```
start=`date -u '+%Y-%m-%dT%H:%MZ'`
end=`date -u -d "2 hours" '+%Y-%m-%dT%H:%MZ'`
sas=`az storage container generate-sas -n [REDACTED] --permissions lr --expiry $end --start $start --account-name [REDACTED] --account-key [REDACTED] -o tsv`
uri="https://[REDACTED].blob.core.windows.net/[REDACTED]/test/copy_test.jpg?$sas"
azcopy list $uri
```

### What problem was encountered?

Fail to authenticate. Here's the output:

```
failed to traverse container: cannot list blobs. Failed with error -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:30993adc-601e-0066-1595-1b857c000000
Time:2020-04-26T06:37:57.1773799Z, Details:
   AuthenticationErrorDetail: se is mandatory. Cannot be empty
   Code: AuthenticationFailed
   GET https://[REDACTED].blob.core.windows.net/[REDACTED]?comp=list&include=metadata&prefix=test%2Fcopy_test.jpg%2F&restype=container&sig=-REDACTED-&sp=rl&sr=c&sv=2018-11-09&timeout=901
   User-Agent: [AzCopy/10.4.1 Azure-Storage/0.7 (go1.13; linux)]
   X-Ms-Client-Request-Id: [ff602450-2f42-4660-5d21-bd1177530ff5]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [407]
   Content-Type: [application/xml]
   Date: [Sun, 26 Apr 2020 06:37:56 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [30993adc-601e-0066-1595-1b857c000000]
```

### How can we reproduce the problem in the simplest way?

```
# Install latest azcopy
wget https://aka.ms/downloadazcopy-v10-linux
tar -xvf downloadazcopy-v10-linux
sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/

# Install azure-cli
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

# Generate sas token
start=`date -u '+%Y-%m-%dT%H:%MZ'`
end=`date -u -d "2 hours" '+%Y-%m-%dT%H:%MZ'`
sas=`az storage container generate-sas -n [REDACTED] --permissions lr --expiry $end --start $start --account-name [REDACTED] --account-key [REDACTED] -o tsv`
uri="https://[REDACTED].blob.core.windows.net/[REDACTED]/test/copy_test.jpg?$sas"

# call azcopy list
azcopy list $uri
```

### Have you found a mitigation/solution?
Switch back to version 10.3.3.

**Comment by adreed-msft** [comment]
Interesting... Could I see what the timestamps on your SAS token look like? We've had issues with various SAS token formats, but this is a regression now.

**Comment by adreed-msft** [comment]
Going to attempt a reproduction myself

**Comment by toothache** [comment]
> Interesting... Could I see what the timestamps on your SAS token look like? We've had issues with various SAS token formats, but this is a regression now.

Here's the timestamps of my SAS token:
```
st=2020-04-28T02%3A02Z&se=2020-04-28T04%3A02Z&
```

**Comment by adreed-msft** [comment]
"2006-01-02T15:04:05Z"

is approximately the expected format within our SDK-- Sounds like you're just missing a millisecond section.

The maximum and minimum precision of ISO8601 be a good thing for us to investigate with @AtOMiCNebula since he's currently got a pull request open to help fixing SAS token times.

**Comment by adreed-msft** [comment]
It is, however, very interesting that it works on 10.3.3... It really shouldn't-- our time format has not changed since 4/7/2018.

**Comment by toothache** [comment]
I tried to convert the sas token to the expected format and it works now.

```
> start=`date -u '+%Y-%m-%dT%H:%M:%SZ'`
> end=`date -u -d "2 hours" '+%Y-%m-%dT%H:%M:%SZ'`
> sas=`az storage container generate-sas -n [REDACTED] --permissions lr --expiry $end --start $start --account-name [REDACTED] --account-key [REDACTED] -o tsv | sed "s/%3A/:/g"`
> echo $sas
  st=2020-04-29T02:33:41Z&se=2020-04-29T04:33:41Z&sp=rl&sv=2018-11-09&sr=c&sig=[REDACTED]
> uri="https://[REDACTED].blob.core.windows.net/[REDACTED]/test/copy_test.jpg?$sas"
> ./azcopy_linux_amd64_10.4.1/azcopy list $uri
INFO: ; Content Length: 120.58 KiB
```

**Comment by adreed-msft** [comment]
Glad I could help. I'll keep the GitHub issue open just for our own purposes.

**Comment by toothache** [comment]
The error message is quite obscure. I have never thought that this is related with the SAS token format.

BTW, the SAS token generated from azure cli is valid, do you know why we don't want to support such format?

**Comment by AtOMiCNebula** [comment]
The Storage Go SDKs (azcopy uses the Blob Go SDK) has weird quirks that require explicit timestamp formats to be listed in the SDK itself, and it can have trouble recognizing timestamps that do not conform to those patterns.

My PR (azure/azure-storage-blob-go#169) adds a few timestamp formats to the Blob SDK and ports over a change from the File SDK to allow multiple formats, which should allow your second-less timestamps to not get mangled by the Blob SDK (and azcopy, once a new library version is released and picked up by azcopy).

**Comment by toothache** [comment]
Thanks for the clarification!
