### ISSUE TITLE
set custom Job ID

### ISSUE THREAD

**Issue by ghost** [Azure/azure-storage-azcopy#987]
### Which version of the AzCopy was used? 
: azcopy version 10.4.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux/Centos

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy cp "D:\Dummy" "https://xxxxxx.blob.core.windows.net/test2020/?sv=<<<SAS TOKEN>>>%3D" --recursive=true --log-level=ERROR

### What problem was encountered?
Getting random JOB ID like eg. JobId: f01b39bf-92ef-c142-6da4-afd730224fc6, We are running azcopy using shell script which create multiple Job Id's and its very difficult to check which azcopy command failed. Is there any way to set custom JobId like source folder name?

JobId : Sourcefolder_container_ST

### How can we reproduce the problem in the simplest way?
You can run any azcopy copy command, it will create random JOB ID.

### Have you found a mitigation/solution?
No.

**Comment by adreed-msft** [comment]
Interesting idea. I don't think it'd be too difficult to do that, just a different mechanism for grabbing job IDs. That being said, this'd be an _odd_ thing to see user experience wise. @JohnRusk and @zezha-msft what are your thoughts on a hidden parameter for this?

**Comment by dmitrychastikov** [comment]
I am in the same boat. So far I mitigated this in a dirty way
```
& c:\tools\azcopy copy "$Source" "$Destination" --recursive=true --overwrite ifSourceNewer  >>$logFile
$match = Select-String -Path $logfile -Pattern "(Job )(.*)( has started)"
$jobname = $match -replace ".*(Job )(.*)( has started)", '$2'
```
The idea of custom job id sounds pretty cool to me.

**Comment by vibhansa-msft** [comment]
Sorry but we do not have any plans to pursue this feature. Job-id allocated to a particular job is random in nature. If we provide this control to user then user may end up assigning similar job-ids to multiple job in which case the whole job will fail or become inconsistent. Also, these job-ids are used for various house keeping inside Azcopy and giving its control to user will make things complicated. Closing this as we do not have any plans to support this feature in near future.
