### ISSUE TITLE
Install AzCopy on Windows sets path wrong

### ISSUE THREAD

**Issue by pbolduc** [Azure/azure-storage-azcopy#99]
### Which version of the AzCopy was used? 
AzCopy 8.1.0-netcore
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
The "Microsoft Azure Storage AzCopy" shortcut installed

### What problem was encountered?
When reviewing the updated path in the new  "Microsoft Azure Storage AzCopy" command prompt window, the path is incorrect.  It has an extra AzCopy at the end.

```
C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy\AzCopy
```

### How can we reproduce the problem in the simplest way?
1. Install AzCopy 8.1 for Windows on Windows 10
2. Launch AzCopy command prompt from the start menu
3. Type PATH to view this session's PATH
4. Change to a different directory and try running AzCopy.exe
5. Observe command not found

```
C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy>cd \

C:\>azcopy
'azcopy' is not recognized as an internal or external command,
operable program or batch file.

C:\>
```

### Have you found a mitigation/solution?
Fix the 'set PATH' statement in C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy\LaunchCmd.cmd

**Comment by seguler** [comment]
We have tried this issue on multiple environments however we could not reproduce it. Regardless, we do not plan to make any more releases in AzCopy v8 at this point. Please upgrade to AzCopy v10.
