### ISSUE TITLE
AzCopy returns 403 Failed to authenticate

### ISSUE THREAD

**Issue by ackrumb** [Azure/azure-storage-azcopy#991]
Hi, I'm brand new to AzCopy, so hopefully this is just a simple usage error. This sounds very much like #77, and it's possible that I'm perhaps using the incorrect tenant ID and that indeed, that tenant may not have access to the given storage blob. Note, I am an internal MS user, please contact [me directly]
### Version and Platform
AzCopy 10.4.1 on Windows.
### What command did you run?
After a correponding `azcopy login --tenant-id <mytenantid>`, I ran `azcopy list "https://myblobstorage.blob.core.windows.net/image"`. Request ID: bb805ecb-901e-008a-70b6-1d178e000000, Time:2020-04-28T23:42:19.5392305Z.

### What problem was encountered?
```
INFO: Authenticating to destination using Azure AD

failed to traverse container: cannot list blobs. Failed with error -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

### Have you found a mitigation/solution?
No.

**Comment by JohnRusk** [comment]
@ackrumb I can't email you right now. Can you email me please?  My full email address is in my profile page.

**Comment by JohnRusk** [comment]
Resolved.  Just needed "Storage Blob Data Contributor" role. Plain "Contributor" is not enough.

**Comment by delahondes** [comment]
I could not make it work using `azcopy login` instruction (I spent hours trying to figure out how it can works), put using this:

https://learn.microsoft.com/fr-fr/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json

Setting up the variables with:
```bash
export AZCOPY_AUTO_LOGIN_TYPE=SPN
export AZCOPY_SPA_APPLICATION_ID=<application-id>
export AZCOPY_SPA_CLIENT_SECRET=<client-secret>
export AZCOPY_TENANT_ID=<tenant-id>
```

Then azcopy works directly (no need to azcopy login)
(do not forget to give the role "Storage Blob Data Contributor" as specified above, create the principal with something like:
```bash
az ad sp create-for-rbac --role "Storage Blob Data Contributor" --scopes /subscriptions/<SubscriptionID>/resourceGroups/<ResourceGroupName> --name <ServicePrincipalName>
```
)
