### ISSUE TITLE
Upload filed for some large files repeatedly input/output error. When chunk data read.

### ISSUE THREAD

**Issue by Gaura** [Azure/azure-storage-azcopy#992]
Hi,

I am trying to sync a local folder with a virtual folder on azure storage container. Of the 567 files at source, 43 are not transferred and they are large size. We have tried rerunning the command but these 43 files are not being transferred. Please help. 

Here is the log:

2020/04/27 13:19:59 AzcopyVersion  10.4.0
2020/04/27 13:19:59 OS-Environment  darwin
2020/04/27 13:19:59 OS-Architecture  amd64
2020/04/27 13:19:59 Log times are in UTC. Local time is 27 Apr 2020 09:19:59
2020/04/27 13:19:59 Job-Command sync local/direcotry/path https://azureaccount.core.windows.net/labstorage/?sastoken --recursive=true
2020/04/27 13:19:59 Number of CPUs: 12
2020/04/27 13:19:59 Max file buffer RAM 6.000 GB
2020/04/27 13:19:59 Max concurrent network operations: 192 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2020/04/27 13:19:59 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2020/04/27 13:19:59 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2020/04/27 13:19:59 Max enumeration routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2020/04/27 13:19:59 Max open files when downloading: 32 (auto-computed)
2020/04/27 13:19:59 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2020/04/27 13:19:59 JobID=69591051-04c3-f340-5b2d-bdd729a00682, credential type: Anonymous
2020/04/27 13:19:59 scheduling JobID=69591051-04c3-f340-5b2d-bdd729a00682, Part#=0, Transfer#=0, priority=0
2020/04/27 13:19:59 scheduling JobID=69591051-04c3-f340-5b2d-bdd729a00682, Part#=0, Transfer#=1, priority=0
2020/04/27 13:19:59 scheduling JobID=69591051-04c3-f340-5b2d-bdd729a00682, Part#=0, Transfer#=2, priority=0
2020/04/27 13:19:59 scheduling JobID=69591051-04c3-f340-5b2d-bdd729a00682, Part#=0, Transfer#=3, priority=0
2020/04/27 13:19:59 scheduling JobID=69591051-04c3-f340-5b2d-bdd729a00682, Part#=0, Transfer#=4, priority=0

### What problem was encountered?
2020/04/27 15:12:48 ERR: [P#0-T#41] UPLOADFAILED: file/path : 000 : read file/path : input/output error. When chunk data read. X-Ms-Request-Id: 

   Dst: https://_______________.blob.core.windows.net/l____________

### How can we reproduce the problem in the simplest way?
Not sure. Here is the summary. 
2020/04/27 15:13:21 JobID=69591051-04c3-f340-5b2d-bdd729a00682, Part#=0, TransfersDone=43 of 43
2020/04/27 15:13:21 all parts of entire Job 69591051-04c3-f340-5b2d-bdd729a00682 successfully completed, cancelled or paused
2020/04/27 15:13:22 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 192
2020/04/27 15:13:22 

Diagnostic stats:
IOPS: 0
End-to-end ms per request: 2707
Network Errors: 4.29%
Server Busy: 0.00%

Job 69591051-04c3-f340-5b2d-bdd729a00682 Summary
Files Scanned at Source: 567
Files Scanned at Destination: 1408
Elapsed Time (Minutes): 114.089
Number of Copy Transfers for Files: 43
Number of Copy Transfers for Folder Properties: 0 
Total Number Of Copy Transfers: 43
Number of Copy Transfers Completed: 0
Number of Copy Transfers Failed: 43
Number of Deletions at Destination: 0
Total Number of Bytes Transferred: 0
Total Number of Bytes Enumerated: 2232658808547
Final Job Status: Failed

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
That's a weird error.

The key info is this:

>file/path : input/output error

That's the actual error message text that the OS is returning to us.  It's not much to go on, I'm afraid.

So  could you try something please? Could you try getting AzCopy to do just _one_ of the files that are failing?  I.e. use the full path of one of the failed files (including the filename) as the source parameter to azCopy.  If that succeeds, or fails, the result may give us additional information to help understand the problem.

**Comment by Gaura** [comment]
Hi,

We no longer need to transfer this data now. I'm sorry I didn't try fixing it much. We figured we don't need to transfer. 

Thanks.
