### ISSUE TITLE
Would like flag for copy/sync to replace (delete/upload) existing blob on Archived tier

### ISSUE THREAD

**Issue by kludd** [Azure/azure-storage-azcopy#993]
##### Note: The version is visible when running AzCopy without any argument

10.4.1

### Which platform are you using? (ex: Windows, Mac, Linux)

Mac

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

$AZCOPY sync "$ARCBASE" "$AZSTORAGECONTAINER?$AZSTORAGESASKEY" --include-pattern="*.enc"

### What problem was encountered?

2020/04/30 12:50:03 ERR: [P#0-T#0] UPLOADFAILED:
** filename ** : 409 : 409 This operation is not permitted on an archived blob.. When Staging block. X-Ms-Request-Id: 7cae4393-d01e-001b-69ed-1e5bd7000000

### How can we reproduce the problem in the simplest way?

azcopy sync or azcopy copy with destination an archived blob

### Have you found a mitigation/solution?

Check log-file, delete blobs and run azcopy sync again.

**Comment by JohnRusk** [comment]
@kludd As far as I know, that's not actually possible. I.e. as far as I know, the Blob Storage Service does not allow overwrite of a blob that is in archived state. So there would be no way we could implement that in AzCopy.

If you have any information to the contrary, please let us know, and I'll re-open this issue.

For now, I'm going to close it.
