### ISSUE TITLE
azcopy plans issue

### ISSUE THREAD

**Issue by jethrogalolo** [Azure/azure-storage-azcopy#998]
### Which version of the AzCopy was used? 
10.4.3
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy plans
### What problem was encountered?
the log for the plan keeps on bigger besides moving it to other location any way i can optimize it size or delete somehow the old ones?
### Have you found a mitigation/solution?
Not yet

**Comment by JohnRusk** [comment]
See https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-jobs-clean

(Don't clean out the plans of any jobs that you intend to resume.)
